{
  "hash": "f2002972f4c94c6a9d723d2355f22ba4",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Explainability Is a Localization Problem\"\nsubtitle: \"Saliency maps on MNIST, confidence intervals on Iris — every explanation answers the same question, *which parts?*. They differ in what counts as a part, what counts as responsible, and whether the answer comes with error bars.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-07-31\"\ncategories: [Machine Learning, Statistics, Explainability, Python]\nimage: \"./cover.png\"\ntags: [xai, saliency, grad-cam, integrated-gradients, anova, pca, permutation-importance]\ndescription: \"Four attribution methods on a misclassified MNIST digit and four classical decompositions of Fisher's irises, implemented from scratch and checked at build time — set against one framing that covers all eight.\"\njupyter: explainability-blog\nexecute:\n  warning: false\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    number-sections: true\n    code-fold: show\n    fig-dpi: 150\n    # Ship light-only. Chrome's \"Auto Dark Mode\" inverts both the page and the\n    # figure PNGs, and this post makes claims the reader is meant to check by\n    # eye against specific colours -- red supports, blue opposes, the digit's\n    # outline drawn in ink over the heatmap. An inverted render contradicts the\n    # prose. Readers with Chrome's *force*-dark flag set will still see a\n    # darkened page; that flag overrides color-scheme on every light site.\n    include-in-header:\n      text: |\n        <style>:root { color-scheme: light; }</style>\n---\n\n\n![Explainability Is a Localization Problem](./cover.png)\n\n\n\n## Localization framing\n\nExplainability methods assign **credit** to **parts** of an input for a model output. The operative question: *which parts were responsible, and how much?*\n\nThree design axes:\n\n1. **Part** — pixel, patch, convolution channel, table column, PCA direction.\n2. **Responsibility** — local gradient, deletion damage, axiom-based attribution, variance share, intervention effect.\n3. **Uncertainty** — almost never in ML attribution; standard in classical statistics.\n\nThis post implements four methods on a misclassified MNIST digit (Part I) and four on Fisher's irises (Part II).\n\n### Running example (MNIST)\n\nTest digit 9729: true class 5, predicted **6** with probability 0\\.996. Correct-class probability 0\\.00055 ranks third, behind 6 and an 8.\n\n::: {.callout-note collapse=\"true\"}\n## Build-time checks\n\nProse values interpolate from the same objects as the figures. 14 cross-checks run at render time — integrated-gradients completeness, Grad-CAM equivalence, logistic SEs vs `statsmodels`, ANOVA vs `scipy`, PCA vs `scikit-learn`. Render fails on any mismatch.\n\nRank correlations in sanity-check and agreement sections are read from figures, not interpolated.\n\n- [wrong] integrated gradients sum to f(x) - f(0) within 3.7e-04 relative\n- [wrong] Grad-CAM via hooks is bit-identical to Grad-CAM via the head split\n- [wrong] Grad-CAM equals CAM / 49 to 8.9e-08 absolute\n- [wrong] all 617 baseline-valued pixels receive exactly zero from IG\n- [right] integrated gradients sum to f(x) - f(0) within 2.1e-04 relative\n- [right] Grad-CAM via hooks is bit-identical to Grad-CAM via the head split\n- [right] Grad-CAM equals CAM / 49 to 1.8e-07 absolute\n- [right] all 562 baseline-valued pixels receive exactly zero from IG\n- [wrong] the largest saliency value in the map (1.35) is on a baseline-valued pixel\n- logistic coefficients match statsmodels to 8.9e-16, standard errors to 2.7e-15\n- ANOVA F statistics match scipy.stats.f_oneway to 2.7e-15 relative\n- PCA explained-variance ratios match scikit-learn to 2.2e-16\n- setosa is linearly separable from the rest; versicolor and virginica are not\n- permutation importances agree with scikit-learn's within Monte-Carlo error (largest gap 0.0066, largest 3-sigma bound 0.0138)\n\n\n:::\n\n## Two traditions\n\n| Tradition | Model size | Typical parts | Uncertainty |\n| :--- | :--- | :--- | :--- |\n| Statistics | Small (legible parameters) | Variables, variance sources | Standard errors, F tests |\n| Machine learning | Large (black box) | Pixels, channels, patches | Point estimates only |\n\n- **Statistics:** regression coefficients, ANOVA decomposition, PCA loadings — attributions with intervals.\n- **Machine learning:** saliency, Grad-CAM, integrated gradients, occlusion — per-part numbers without intervals.\n\nPart I: black box (MNIST). Part II: glass box (Iris).\n\n## Part I — MNIST attribution\n\n### MNIST data\n\n**Source:** [LeCun, Cortes and Burges MNIST database](https://yann.lecun.com/exdb/mnist/), rebuilt from NIST Special Database 3 (Census Bureau employees) and SD-1 (high-school students). Size-normalised 20×20 glyphs centred in 28×28 fields; grey anti-aliased pixels.\n\n- **Objective:** classify digit from image; label = human-intended digit.\n- **Downstream impact:** misread digits on cheques or mail routing (recoverable; suitable for explanation study).\n- **Why attribution:** 784 correlated inputs; no readable coefficients; model is differentiable and cheap to evaluate.\n\n### Model architecture\n\nSmall CNN: two conv blocks → 7×7 grid → 128-channel conv → global average pooling → linear layer (10 logits). Global average pooling collapses spatial structure; final layer sees channel strengths only. Architecture chosen so Grad-CAM remains valid (see below).\n\n```python\ndef features(self, x: torch.Tensor) -> torch.Tensor:\n    return self.act3(self.bn3(self.conv3(self.block2(self.block1(x)))))\n\ndef head(self, a: torch.Tensor) -> torch.Tensor:\n    return self.fc(a.mean(dim=(2, 3)))\n```\n\n\nFour epochs on CPU, fixed seed. Test accuracy 98\\.8% (125 errors in 10,000). Running examples: most confidently wrong digit and most confidently correct digit of the same true class (both fives).\n\n::: {#cell-fig-examples .cell execution_count=4}\n\n::: {.cell-output .cell-output-display}\n![The running examples. Probabilities are on a log scale, so the classes the model ranked below its answer are visible rather than flattened to the axis.](index_files/figure-html/fig-examples-output-1.png){#fig-examples fig-alt='Two MNIST digits, both fives, with the model\\'s probability over ten classes on a log scale. The first is predicted six with probability 0.996; the second is predicted five with probability 1.000.'}\n:::\n:::\n\n\nMisclassified digit: lower stroke forms a closed loop (six-like feature).\n\n### Saliency\n\n**Definition:** $|\\nabla_x f|$ — magnitude of gradient of target logit w.r.t. each pixel. One backward pass. [Simonyan, Vedaldi and Zisserman (2014)](https://arxiv.org/abs/1312.6034).\n\n```python\ndef saliency(model: SmallCNN, x01: torch.Tensor, target: int) -> np.ndarray:\n    x = _as_batch(x01).requires_grad_(True)\n    model.zero_grad(set_to_none=True)\n    model(normalise(x))[0, target].backward()\n    return x.grad[0, 0].detach().numpy()\n```\n\n\n::: {#cell-fig-saliency .cell execution_count=6}\n\n::: {.cell-output .cell-output-display}\n![Gradient magnitude of the predicted logit. The digit's outline is drawn on top so the attribution can be located against the stroke.](index_files/figure-html/fig-saliency-output-1.png){#fig-saliency fig-alt='Two saliency maps over MNIST fives. Both are speckled, with bright pixels scattered inside and outside the stroke.'}\n:::\n:::\n\n\nObservations:\n\n- Speckled map; ReLU piecewise linearity causes neighbouring pixels to differ sharply in derivative.\n- Of 617 black pixels, 617 receive non-zero gradient; max 1\\.35 on empty pixel.\n- Measures **sensitivity** to hypothetical perturbation, not contribution to current output.\n\n### Occlusion\n\n**Definition:** slide 7×7 black patch; record logit drop. Real finite perturbation. [Zeiler and Fergus (2014)](https://arxiv.org/abs/1311.2901).\n\n```python\ndef occlusion(\n    model: SmallCNN,\n    x01: torch.Tensor,\n    target: int,\n    patch: int = 7,\n    fill: float = 0.0,\n) -> np.ndarray:\n    base = target_logit(model, x01, target)\n    half = patch // 2\n    img = _as_batch(x01)\n\n    batch, centres = [], []\n    for r in range(28):\n        for c in range(28):\n            occluded = img.clone()\n            occluded[\n                :, :, max(0, r - half) : r + half + 1, max(0, c - half) : c + half + 1\n            ] = fill\n            batch.append(occluded)\n            centres.append((r, c))\n\n    with torch.no_grad():\n        logits = model(normalise(torch.cat(batch)))[:, target].numpy()\n\n    out = np.zeros((28, 28), dtype=np.float64)\n    for (r, c), value in zip(centres, logits):\n        out[r, c] = base - value\n    return out\n```\n\n\n::: {#cell-fig-occlusion .cell execution_count=8}\n\n::: {.cell-output .cell-output-display}\n![Logit drop under a 7×7 black patch. Red means the patch was supporting the prediction; blue means removing it *helped*.](index_files/figure-html/fig-occlusion-output-1.png){#fig-occlusion fig-alt='Two occlusion maps over MNIST fives. On the misclassified digit the heat concentrates on the closed lower loop.'}\n:::\n:::\n\n\nOn misclassified digit: mass on closed lower loop; max logit drop 8\\.4 for class 6.\n\n**Limitation:** occluding already-black regions does nothing. 319 pixels sit in fully black 7×7 neighbourhoods; max occlusion change 4\\.8e\\-06 vs saliency up to 0\\.82. Different definitions of *absent*.\n\n### Grad-CAM\n\n**Definition:** weight final-convolution channels by mean gradient of target logit across each 7×7 map; sum; keep positive part. Parts = 128 channels, not pixels. [Selvaraju et al. (2017)](https://arxiv.org/abs/1610.02391).\n\n```python\ndef grad_cam(model: SmallCNN, x01: torch.Tensor, target: int) -> np.ndarray:\n    activations = model.features(normalise(_as_batch(x01)))  # (1, 128, 7, 7)\n    activations.retain_grad()\n    model.zero_grad(set_to_none=True)\n    model.head(activations)[0, target].backward()\n\n    weights = activations.grad[0].mean(dim=(1, 2))  # (128,) channel weights\n    cam = torch.relu((weights[:, None, None] * activations[0]).sum(0))  # (7, 7)\n    return _upsample(cam.detach().numpy())\n```\n\n\n::: {#cell-fig-gradcam .cell execution_count=10}\n\n::: {.cell-output .cell-output-display}\n![Grad-CAM over the last convolution, upsampled from its native 7×7 grid to pixel resolution.](index_files/figure-html/fig-gradcam-output-1.png){#fig-gradcam fig-alt='Two Grad-CAM maps over MNIST fives, each a smooth blob. On the misclassified digit the blob covers the closed loop.'}\n:::\n:::\n\n\nProperties:\n\n- Smooth blob on loop; native 7×7 grid → ~4×4 pixel resolution on MNIST.\n- Requires global-average-pooling head (flatten head can zero entire map).\n- With GAP head, collapses to [CAM](https://arxiv.org/abs/1512.04150); build asserts: Grad\\-CAM equals CAM / 49 to 8\\.9e\\-08 absolute.\n\n### Integrated gradients\n\n**Definition:** path integral of gradient from baseline to input; satisfies **completeness** (attributions sum to output difference). [Sundararajan et al. (2017)](https://arxiv.org/abs/1703.01365).\n\n```python\ndef integrated_gradients(\n    model: SmallCNN,\n    x01: torch.Tensor,\n    target: int,\n    baseline: torch.Tensor | None = None,\n    steps: int = 512,\n) -> np.ndarray:\n    x = _as_batch(x01)\n    base = torch.zeros_like(x) if baseline is None else _as_batch(baseline)\n    # Midpoint rule: unbiased for the linear part and far more accurate than\n    # left endpoints at the same cost, which matters because completeness is\n    # checked numerically rather than assumed.\n    alphas = (torch.arange(steps, dtype=torch.float32) + 0.5) / steps\n    path = base + alphas.reshape(-1, 1, 1, 1) * (x - base)\n    path.requires_grad_(True)\n\n    model.zero_grad(set_to_none=True)\n    model(normalise(path))[:, target].sum().backward()\n\n    avg_grad = path.grad.mean(0, keepdim=True)\n    return ((x - base) * avg_grad)[0, 0].detach().numpy()\n```\n\n\n::: {#cell-fig-ig .cell execution_count=12}\n\n::: {.cell-output .cell-output-display}\n![Integrated gradients from a black baseline. Red pixels push the logit up, blue pixels push it down.](index_files/figure-html/fig-ig-output-1.png){#fig-ig fig-alt='Two integrated-gradients maps over MNIST fives. Attribution is confined to the stroke; the background is uniformly blank.'}\n:::\n:::\n\n\n- Sum 10\\.632 vs logit difference 10\\.636.\n- Positive evidence 17\\.1; negative 6\\.5 (top bar = five-like stroke).\n\n#### Baseline dependence\n\nAttribution = $(x - x') \\times$ averaged gradient. Where $x = x'$, attribution is exactly zero — all 617 black pixels are zero by construction, not empirically. Baseline defines \"absent\"; completeness holds relative to that choice.\n\n#### Sanity check (random weights)\n\n[Adebayo et al. (2018)](https://arxiv.org/abs/1810.03292): recompute on untrained weights; map should change if method reads the model.\n\n::: {#cell-fig-sanity .cell execution_count=13}\n\n::: {.cell-output .cell-output-display}\n![The same three methods applied to an untrained network on the same digit. Rank correlations are against the trained network's map, over all 784 pixels.](index_files/figure-html/fig-sanity-output-1.png){#fig-sanity fig-alt='A two-by-three grid. The top row shows saliency, Grad-CAM and integrated gradients from the trained network; the bottom row shows the same three from a randomly initialised network. The integrated-gradients pair look nearly identical in magnitude.'}\n:::\n:::\n\n\n- Saliency: rank correlation $+0.03$ (passes).\n- Grad-CAM: $-0.38$ (passes).\n- Integrated gradients magnitudes: $+0.99$ (fails); signs: $-0.01$. Factor $(x - x')$ dominates magnitude; any network produces stroke-shaped map.\n\n### Method agreement\n\n::: {#cell-fig-agreement .cell execution_count=14}\n\n::: {.cell-output .cell-output-display}\n![All four localizations of the same misclassification, with Spearman rank correlations between their magnitudes over all 784 pixels.](index_files/figure-html/fig-agreement-output-1.png){#fig-agreement fig-alt='Four attribution maps of a misclassified MNIST five, plus a four-by-four matrix of rank correlations. Occlusion and Grad-CAM correlate at 0.77; saliency correlates weakly with everything.'}\n:::\n:::\n\n\n| Pair | Correlation | Interpretation |\n| :--- | ---: | :--- |\n| Occlusion ↔ Grad-CAM | +0.77 | Both coarse, region-based; agree on loop |\n| Integrated gradients ↔ Occlusion | +0.64 | Same stroke, finer distribution; signed negative evidence |\n| Saliency ↔ others | +0.03 to +0.23 | Different quantity (sensitivity vs contribution) |\n\nNone of the four attach uncertainty intervals.\n\n## Part II — Iris attribution\n\n### Iris data\n\n**Source:** Edgar Anderson's 1930s measurements from Gaspé Peninsula, Quebec; used by Fisher (1936). 150 flowers, 4 measurements (cm), 3 species.\n\n- *I. setosa* and *I. versicolor*: same pasture, same day, same apparatus (Anderson, via Fisher).\n- *I. virginica*: different colony (Fisher notes different collection conditions).\n- **Objective:** taxonomic classification from four measurements.\n- **Downstream impact:** misclassified herbarium specimen (research, not clinical).\n- **Why intervals:** $n=50$ per species; petal length ↔ petal width correlation 0\\.963 prevents clean separation of contributions.\n\n### Logistic coefficients\n\nVersicolor vs virginica; unpenalised logistic regression on standardised features; Newton–Raphson. Covariance = inverse of $X^\\top W X$ at maximum; **Wald intervals** = estimate ± 2 SE.\n\n```python\ndef fit_logistic(\n    X: np.ndarray, y: np.ndarray, names: list[str], max_iter: int = 100, tol: float = 1e-10\n) -> LogitFit:\n    Xd = np.column_stack([np.ones(len(X)), X])\n    beta = np.zeros(Xd.shape[1])\n    converged, used = False, max_iter\n\n    for step in range(max_iter):\n        eta = Xd @ beta\n        p = 1.0 / (1.0 + np.exp(-eta))\n        W = p * (1.0 - p)\n        # Ridge-free Newton step. pinv rather than solve: on separable data the\n        # information matrix goes singular, and we want the run to continue and\n        # report a diverging coefficient rather than raise.\n        hessian = Xd.T @ (W[:, None] * Xd)\n        score = Xd.T @ (y - p)\n        delta = np.linalg.pinv(hessian) @ score\n        beta = beta + delta\n        if np.max(np.abs(delta)) < tol:\n            converged, used = True, step + 1\n            break\n\n    eta = Xd @ beta\n    p = np.clip(1.0 / (1.0 + np.exp(-eta)), 1e-15, 1 - 1e-15)\n    W = p * (1.0 - p)\n    cov = np.linalg.pinv(Xd.T @ (W[:, None] * Xd))\n    loglik = float(np.sum(y * np.log(p) + (1 - y) * np.log(1 - p)))\n    return LogitFit(\n        beta=beta,\n        se=np.sqrt(np.diag(cov)),\n        cov=cov,\n        iterations=used,\n        converged=converged,\n        loglik=loglik,\n        names=[\"intercept\"] + list(names),\n    )\n```\n\n\n::: {#cell-fig-coefficients .cell execution_count=16}\n\n::: {.cell-output .cell-output-display}\n![Coefficients with 95% Wald intervals, versicolor versus virginica, on standardised measurements.](index_files/figure-html/fig-coefficients-output-1.png){#fig-coefficients fig-alt='A forest plot of four logistic-regression coefficients. Petal length and petal width are large and positive with very wide intervals; both sepal coefficients straddle zero.'}\n:::\n:::\n\n\n::: {#698a51c6 .cell execution_count=17}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=17}\n| term         |   coef |   std err |      z |     p |   2.5% |   97.5% |\n|:-------------|-------:|----------:|-------:|------:|-------:|--------:|\n| sepal length | -1.634 |     1.587 | -1.030 | 0.303 | -4.745 |   1.476 |\n| sepal width  | -2.223 |     1.491 | -1.491 | 0.136 | -5.145 |   0.698 |\n| petal length |  7.785 |     3.911 |  1.990 | 0.047 |  0.119 |  15.450 |\n| petal width  |  7.767 |     4.138 |  1.877 | 0.061 | -0.344 |  15.878 |\n:::\n:::\n\n\nKey numbers:\n\n- Petal length coef 7\\.78, petal width 7\\.77; SE ~ 4\\.0.\n- Petal length $p =$ 0\\.047; petal width $p =$ 0\\.061 (interval crosses zero).\n- Collinearity: individually unstable coefficients, jointly precise separation.\n\n#### Complete separation\n\nSetosa vs rest: unpenalised model has no finite maximum (hyperplane separates perfectly).\n\n::: {#cell-fig-separation .cell execution_count=18}\n\n::: {.cell-output .cell-output-display}\n![Refitting setosa-versus-rest with increasing Newton budgets. Neither the coefficients nor their standard errors converge.](index_files/figure-html/fig-separation-output-1.png){#fig-separation fig-alt='A log-log plot. Coefficient norm rises from about 1.7 to 92 as Newton steps increase from 1 to 100; the largest standard error rises from about 1.4 to over ten million.'}\n:::\n:::\n\n\n::: {#9d9f9f32 .cell execution_count=19}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=19}\n|   newton steps |   coefficient norm |   largest std err |   log-likelihood |\n|---------------:|-------------------:|------------------:|-----------------:|\n|              1 |               1.67 |          1.37     |       -24.8      |\n|              2 |               2.81 |          2.17     |        -9.6      |\n|              5 |               6.17 |          8.79     |        -0.643    |\n|             10 |              12.6  |        108        |        -0.00623  |\n|             25 |              39.8  |          2.64e+05 |        -2.27e-09 |\n|             50 |              72.7  |          1.45e+07 |        -1.5e-13  |\n|            100 |              91.6  |          1.45e+07 |        -1.5e-13  |\n:::\n:::\n\n\nOver 100 Newton steps: coefficient norm 1\\.67 → 92; largest SE 1\\.37 → 1\\.4e\\+07. `scikit-learn` default L2 regularisation masks this.\n\n### ANOVA\n\nOne-way ANOVA per measurement: total SS splits exactly into between-group and within-group components. $\\eta^2$ = between-group share = marginal attribution to species.\n\n```python\ndef anova_table(df: pd.DataFrame) -> pd.DataFrame:\n    rows = []\n    for feature in FEATURES:\n        groups = [df.loc[df.species == s, feature].to_numpy() for s in SPECIES]\n        values = np.concatenate(groups)\n        grand = values.mean()\n        ss_between = sum(len(g) * (g.mean() - grand) ** 2 for g in groups)\n        ss_within = sum(((g - g.mean()) ** 2).sum() for g in groups)\n        df_between = len(groups) - 1\n        df_within = len(values) - len(groups)\n        f = (ss_between / df_between) / (ss_within / df_within)\n        rows.append(\n            {\n                \"feature\": feature,\n                \"F\": f,\n                \"df\": f\"{df_between}, {df_within}\",\n                \"p\": float(stats.f.sf(f, df_between, df_within)),\n                \"eta^2\": ss_between / (ss_between + ss_within),\n            }\n        )\n    return pd.DataFrame(rows)\n```\n\n\n::: {#cell-fig-anova .cell execution_count=21}\n\n::: {.cell-output .cell-output-display}\n![Each measurement by species, with the between-species share of its variance.](index_files/figure-html/fig-anova-output-1.png){#fig-anova fig-alt='Left, a strip plot of the four measurements coloured by species; petal length and width separate setosa cleanly. Right, bar chart of eta squared: petal length 0.94, petal width 0.93, sepal length 0.62, sepal width 0.40.'}\n:::\n:::\n\n\n::: {#4244427a .cell execution_count=22}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=22}\n| feature      |       F | df     |         p |   eta^2 |\n|:-------------|--------:|:-------|----------:|--------:|\n| sepal length |  119.3  | 2, 147 | 1.67e-31  |  0.6187 |\n| sepal width  |   49.16 | 2, 147 | 4.492e-17 |  0.4008 |\n| petal length | 1180    | 2, 147 | 2.857e-91 |  0.9414 |\n| petal width  |  960    | 2, 147 | 4.169e-85 |  0.9289 |\n:::\n:::\n\n\n- Petal length $\\eta^2$ = 0\\.941 ({94\\.1%} of variance explained by species).\n- Largest p-value among four: 4e\\-17.\n\n#### Marginal vs conditional attribution\n\nSeparate one-way ANOVAs → $\\eta^2$ values sum to 2\\.89 (not shares of one quantity). Sepal length $\\eta^2$ = 0\\.62 partly from correlation 0\\.872 with petal length. Regression coefficients are **conditional** (others fixed); ANOVA $\\eta^2$ is **marginal**.\n\n### PCA\n\nParts = principal components (linear combinations maximising variance). Standardised vs raw scaling changes results.\n\n```python\ndef pca_fit(X: np.ndarray, standardised: bool = True, k: int = 2) -> PCAFit:\n    Z = standardise(X) if standardised else X - X.mean(0)\n    U, S, Vt = np.linalg.svd(Z, full_matrices=False)\n    var = S**2 / (len(Z) - 1)\n    # Sign convention: make each component's largest-magnitude loading positive,\n    # so the biplot does not flip between runs or between standardisations.\n    V = Vt.T\n    flip = np.sign(V[np.abs(V).argmax(0), np.arange(V.shape[1])])\n    V = V * flip\n    scores = Z @ V\n    return PCAFit(\n        ratio=var / var.sum(),\n        loadings=V[:, :k],\n        scores=scores[:, :k],\n        standardised=standardised,\n    )\n```\n\n\n::: {#cell-fig-pca .cell execution_count=24}\n\n::: {.cell-output .cell-output-display}\n![Left: explained variance under two scalings. Right: the standardised biplot, loadings drawn over scores.](index_files/figure-html/fig-pca-output-1.png){#fig-pca fig-alt='Left, a bar chart comparing explained variance ratios for standardised and raw-centimetre PCA. Right, a biplot of the first two standardised components with the three species separated and four loading arrows.'}\n:::\n:::\n\n\n- Standardised: first two PCs carry 95\\.8% of variance.\n- PC1 loadings: petal length 0\\.58, petal width 0\\.56, sepal length 0\\.52, sepal width \\-0\\.27.\n- Raw centimetres: PC1 = 92\\.5% vs 73\\.0% standardised; petal length loading 0\\.86. Scale choice alters \"explanation\" (same issue as occlusion fill value).\n\n### Permutation importance\n\nShuffle one column on held-out set; measure accuracy drop. Occlusion analogue for tabular data.\n\n```python\ndef permutation_importance(\n    predict, X: np.ndarray, y: np.ndarray, repeats: int, rng: np.random.Generator\n) -> pd.DataFrame:\n    baseline = float((predict(X) == y).mean())\n    rows = []\n    for j, name in enumerate(FEATURES):\n        drops = np.empty(repeats)\n        for r in range(repeats):\n            Xp = X.copy()\n            Xp[:, j] = Xp[rng.permutation(len(Xp)), j]\n            drops[r] = baseline - float((predict(Xp) == y).mean())\n        rows.append(\n            {\n                \"feature\": name,\n                \"mean drop\": drops.mean(),\n                \"sd\": drops.std(ddof=1),\n                \"se\": drops.std(ddof=1) / np.sqrt(repeats),\n            }\n        )\n    return pd.DataFrame(rows)\n```\n\n\n::: {#cell-fig-permutation .cell execution_count=26}\n\n::: {.cell-output .cell-output-display}\n![Permutation importance with 95% intervals from 200 shuffles, and the three localizations side by side, each scaled to its own maximum.](index_files/figure-html/fig-permutation-output-1.png){#fig-permutation fig-alt='Left, a bar chart of accuracy lost per shuffled feature with error bars: petal width 0.21, petal length 0.19, both sepals 0.04. Right, grouped bars comparing permutation importance, ANOVA eta squared and absolute coefficient.'}\n:::\n:::\n\n\n::: {#82260423 .cell execution_count=27}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=27}\n| feature      |   mean drop |     sd |     se |\n|:-------------|------------:|-------:|-------:|\n| sepal length |      0.0402 | 0.0224 | 0.0016 |\n| sepal width  |      0.0395 | 0.0279 | 0.0020 |\n| petal length |      0.1922 | 0.0468 | 0.0033 |\n| petal width  |      0.2127 | 0.0470 | 0.0033 |\n:::\n:::\n\n\n- Test accuracy 95\\.0% on 60 flowers.\n- Petal width drop 0\\.213; sepal width 0\\.039.\n- Intervals from 200 shuffle repeats (Monte Carlo on permutation, not sampling SE on 150 rows).\n\n## Method comparison\n\n| Method | Part | Responsible means | Uncertainty |\n|---|---|---|---|\n| Saliency | pixel | large local gradient | none |\n| Occlusion | image patch | logit lost when blanked | none as computed |\n| Grad-CAM | conv channel | active *and* gradient-weighted | none |\n| Integrated gradients | pixel | path integral from baseline | none |\n| Logistic coefficient | feature | log-odds per sd, others fixed | Wald interval |\n| ANOVA $\\eta^2$ | feature | share of between-group variance | F test |\n| PCA loading | direction | variance captured | none as computed |\n| Permutation importance | feature | accuracy lost when shuffled | Monte-Carlo interval |\n\n### Correlational vs intervening methods\n\n- **Read-only:** saliency, coefficients, PCA loadings — structure from fitted object.\n- **Intervening:** occlusion, integrated gradients, permutation importance — construct inputs model never saw.\n\nInterventions use impossible inputs (black patch, shuffled column). Mechanistic interpretability (activation patching) intervenes internally; still point estimates.\n\n### Uncertainty gap\n\nStatistics attaches intervals; ML attribution scales to large models without them. Permutation importance shows one bridge (repeat perturbation, report spread). Occlusion maps could carry the same treatment at cost of many forward passes.\n\n## Reproducing this\n\nSource: `posts/explainability-localization/src/`. Code blocks extracted via `inspect.getsource` at render. See [README](https://github.com/project-delphi/ml-blog/tree/main/posts/explainability-localization) for environment and build checks.\n\n## References\n\n- Adebayo, J. et al. (2018). [Sanity Checks for Saliency Maps](https://arxiv.org/abs/1810.03292). *NeurIPS*.\n- Anderson, E. (1935). The Irises of the Gaspé Peninsula. *Bulletin of the American Iris Society*, 59, 2–5.\n- Fisher, R. A. (1936). [The Use of Multiple Measurements in Taxonomic Problems](https://onlinelibrary.wiley.com/doi/10.1111/j.1469-1809.1936.tb02137.x). *Annals of Eugenics*, 7(2), 179–188.\n- LeCun, Y., Cortes, C. and Burges, C. [The MNIST Database of Handwritten Digits](https://yann.lecun.com/exdb/mnist/).\n- Selvaraju, R. R. et al. (2017). [Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization](https://arxiv.org/abs/1610.02391). *ICCV*.\n- Simonyan, K., Vedaldi, A. and Zisserman, A. (2014). [Deep Inside Convolutional Networks: Visualising Image Classification Models and Saliency Maps](https://arxiv.org/abs/1312.6034). *ICLR Workshop*.\n- Sundararajan, M., Taly, A. and Yan, Q. (2017). [Axiomatic Attribution for Deep Networks](https://arxiv.org/abs/1703.01365). *ICML*.\n- Zeiler, M. D. and Fergus, R. (2014). [Visualizing and Understanding Convolutional Networks](https://arxiv.org/abs/1311.2901). *ECCV*.\n- Zhou, B. et al. (2016). [Learning Deep Features for Discriminative Localization](https://arxiv.org/abs/1512.04150). *CVPR*.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}