<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-10-01">
<meta name="description" content="Ridge shrinks the direction the data cannot see, principal components regression deletes it, the lasso drops a predictor and picks which one by noise, and the elastic net shares the weight. What each rule costs, on two synthetic columns you can turn in 3D and on the diabetes and Longley data, and when dropping a column or doing nothing is the better answer.">

<title>Collinearity, Part 2: Ridge, Principal Components, Lasso and Elastic Net – Synthetic Musings</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a9fbfb7a887b62f4d313264b6afc3d0d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-784891f9eaa39f9ffae573c9e0f86e17.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../../widget-kit/kit.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="post.css">
<meta property="og:title" content="Collinearity, Part 2: Ridge, Principal Components, Lasso and Elastic Net – Synthetic Musings">
<meta property="og:description" content="Ridge shrinks the direction the data cannot see, principal components regression deletes it, the lasso drops a predictor and picks which one by noise, and the elastic net shares the weight. What each rule costs, on two synthetic columns you can turn in 3D and on the diabetes and Longley data, and when dropping a column or doing nothing is the better answer.">
<meta property="og:image" content="https://project-delphi.github.io/ml-blog/posts/collinearity-remedies/cover.png">
<meta property="og:site_name" content="Synthetic Musings">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:title" content="Collinearity, Part 2: Ridge, Principal Components, Lasso and Elastic Net – Synthetic Musings">
<meta name="twitter:description" content="Ridge shrinks the direction the data cannot see, principal components regression deletes it, the lasso drops a predictor and picks which one by noise, and the elastic net shares the weight. What each rule costs, on two synthetic columns you can turn in 3D and on the diabetes and Longley data, and when dropping a column or doing nothing is the better answer.">
<meta name="twitter:image" content="https://project-delphi.github.io/ml-blog/posts/collinearity-remedies/cover.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="630">
<meta name="twitter:image-width" content="1200">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Synthetic Musings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="Home">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Collinearity, Part 2: Ridge, Principal Components, Lasso and Elastic Net</h1>
            <p class="subtitle lead">Every remedy is a rule for the direction the data cannot see</p>
                  <div>
        <div class="description">
          Ridge shrinks the direction the data cannot see, principal components regression deletes it, the lasso drops a predictor and picks which one by noise, and the elastic net shares the weight. What each rule costs, on two synthetic columns you can turn in 3D and on the diabetes and Longley data, and when dropping a column or doing nothing is the better answer.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Linear Algebra</div>
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Numerical Methods</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 1, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-weak-direction" id="toc-the-weak-direction" class="nav-link active" data-scroll-target="#the-weak-direction"><span class="header-section-number">1</span> The weak direction</a>
  <ul class="collapse">
  <li><a href="#the-synthetic-data" id="toc-the-synthetic-data" class="nav-link" data-scroll-target="#the-synthetic-data"><span class="header-section-number">1.1</span> The synthetic data</a></li>
  </ul></li>
  <li><a href="#one-formula-for-the-linear-remedies" id="toc-one-formula-for-the-linear-remedies" class="nav-link" data-scroll-target="#one-formula-for-the-linear-remedies"><span class="header-section-number">2</span> One formula for the linear remedies</a></li>
  <li><a href="#what-each-method-minimises" id="toc-what-each-method-minimises" class="nav-link" data-scroll-target="#what-each-method-minimises"><span class="header-section-number">3</span> What each method minimises</a>
  <ul class="collapse">
  <li><a href="#ridge" id="toc-ridge" class="nav-link" data-scroll-target="#ridge"><span class="header-section-number">3.1</span> Ridge</a></li>
  <li><a href="#principal-components-regression" id="toc-principal-components-regression" class="nav-link" data-scroll-target="#principal-components-regression"><span class="header-section-number">3.2</span> Principal components regression</a></li>
  <li><a href="#lasso" id="toc-lasso" class="nav-link" data-scroll-target="#lasso"><span class="header-section-number">3.3</span> Lasso</a></li>
  <li><a href="#elastic-net" id="toc-elastic-net" class="nav-link" data-scroll-target="#elastic-net"><span class="header-section-number">3.4</span> Elastic net</a></li>
  <li><a href="#summary-of-the-scene" id="toc-summary-of-the-scene" class="nav-link" data-scroll-target="#summary-of-the-scene"><span class="header-section-number">3.5</span> Summary of the scene</a></li>
  </ul></li>
  <li><a href="#the-cost" id="toc-the-cost" class="nav-link" data-scroll-target="#the-cost"><span class="header-section-number">4</span> The cost</a></li>
  <li><a href="#real-data" id="toc-real-data" class="nav-link" data-scroll-target="#real-data"><span class="header-section-number">5</span> Real data</a>
  <ul class="collapse">
  <li><a href="#the-diabetes-data" id="toc-the-diabetes-data" class="nav-link" data-scroll-target="#the-diabetes-data"><span class="header-section-number">5.1</span> The diabetes data</a></li>
  <li><a href="#longley-the-two-columns" id="toc-longley-the-two-columns" class="nav-link" data-scroll-target="#longley-the-two-columns"><span class="header-section-number">5.2</span> Longley: the two columns</a></li>
  </ul></li>
  <li><a href="#other-approaches" id="toc-other-approaches" class="nav-link" data-scroll-target="#other-approaches"><span class="header-section-number">6</span> Other approaches</a></li>
  <li><a href="#choosing" id="toc-choosing" class="nav-link" data-scroll-target="#choosing"><span class="header-section-number">7</span> Choosing</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/collinearity-remedies/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Collinearity, Part 2: Ridge, Principal Components, Lasso and Elastic Net</figcaption>
</figure>
</div>
<p>Every remedy for collinearity supplies, from outside the data, a value for the combination of coefficients the data cannot determine. The remedies differ in which value they supply and how firmly they hold it.</p>
<p>The remedies look like repairs. A regression with unstable coefficients goes into ridge, or the lasso, or a principal components step, and comes out with coefficients that hold still. The data did not change, so the information that was missing is still missing. The method filled the gap with an assumption, and the coefficients are stable because the assumption is.</p>
<p><a href="../collinearity/">Part 1</a> found the gap. With two nearly parallel predictor columns, the data fix the sum of the two coefficients and say almost nothing about their difference. With more columns the undetermined part is whichever combination nearly cancels.</p>
<ul>
<li>What does each method assume about that combination?</li>
<li>What does the assumption cost when it is wrong?</li>
<li>Which problems does each method leave unsolved?</li>
<li>When is dropping a column, or doing nothing, the better choice?</li>
</ul>
<section id="the-weak-direction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="the-weak-direction"><span class="header-section-number">1</span> The weak direction</h2>
<p>The facts carried over from Part 1:</p>
<ul>
<li>Write the singular value decomposition <span class="math inline">\(X = \sum_i \sigma_i u_i v_i^\top\)</span>. Least squares is <span class="math inline">\(\hat\beta = \sum_i (u_i^\top y / \sigma_i)\, v_i\)</span>.</li>
<li>Near collinearity is a small <span class="math inline">\(\sigma_i\)</span>. Its <span class="math inline">\(v_i\)</span> is the <strong>weak direction</strong>: a combination of coefficients that barely changes the fitted values.</li>
<li>Dividing by the small <span class="math inline">\(\sigma_i\)</span> turns noise in <span class="math inline">\(y\)</span> into large swings of <span class="math inline">\(\hat\beta\)</span> along <span class="math inline">\(v_i\)</span>.</li>
<li>For two standardised columns at correlation <span class="math inline">\(r\)</span>, the weak direction is <span class="math inline">\(v_2 \propto (-1, 1)\)</span>: raise one coefficient, lower the other.</li>
</ul>
<section id="the-synthetic-data" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="the-synthetic-data"><span class="header-section-number">1.1</span> The synthetic data</h3>
<p>The two scenes reuse Part 1’s synthetic data with one change.</p>
<ul>
<li><strong>Rows.</strong> <span class="math inline">\(n = 40\)</span>, the same <span class="math inline">\(x\)</span> values and the same 200 noise draws as Part 1.</li>
<li><strong>Predictors.</strong> Two centred columns with standard deviation 1 and correlation <span class="math inline">\(r\)</span>.</li>
<li><strong>Target.</strong> <span class="math inline">\(y = 1.5\,x_1 + 0.5\,x_2 + \varepsilon\)</span>, noise standard deviation 0.6. Part 1 used <span class="math inline">\((1, 1)\)</span>.</li>
<li><strong>Why the change.</strong> With true coefficients <span class="math inline">\((1, 1)\)</span> the true difference <span class="math inline">\(\beta_2 - \beta_1\)</span> is zero, and a method that pushes the difference towards zero would look free. With <span class="math inline">\((1.5, 0.5)\)</span> the difference is <span class="math inline">\(-1\)</span>, and pushing it towards zero is an error the scenes can show.</li>
<li><strong>What it stands in for.</strong> Two measurements that track each other and matter unequally.</li>
</ul>
</section>
</section>
<section id="one-formula-for-the-linear-remedies" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="one-formula-for-the-linear-remedies"><span class="header-section-number">2</span> One formula for the linear remedies</h2>
<p>Standardise the columns and write the loss as the mean squared error, <span class="math inline">\(\mathrm{MSE}(\beta) = \tfrac{1}{n}\lVert y - X\beta\rVert^2\)</span>. Let <span class="math inline">\(d_i = \sigma_i^2 / n\)</span>, the eigenvalues of <span class="math inline">\(X^\top X / n\)</span>. Ridge and principal components regression both return</p>
<p><span class="math display">\[
\tilde\beta = \sum_i f_i \,\frac{u_i^\top y}{\sigma_i}\, v_i ,
\]</span></p>
<p>least squares with each term multiplied by a <strong>filter factor</strong> <span class="math inline">\(f_i\)</span> between 0 and 1.</p>
<div id="tbl-filters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-filters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Filter factors.
</figcaption>
<div aria-describedby="tbl-filters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Filter factor</th>
<th>Effect on a weak direction</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Least squares</td>
<td><span class="math inline">\(f_i = 1\)</span></td>
<td>kept at full size</td>
</tr>
<tr class="even">
<td>Ridge, weight <span class="math inline">\(\lambda\)</span></td>
<td><span class="math inline">\(f_i = d_i / (d_i + \lambda)\)</span></td>
<td>shrunk, more as <span class="math inline">\(d_i\)</span> falls below <span class="math inline">\(\lambda\)</span></td>
</tr>
<tr class="odd">
<td>Principal components, <span class="math inline">\(k\)</span> kept</td>
<td><span class="math inline">\(f_i = 1\)</span> for <span class="math inline">\(i \le k\)</span>, else <span class="math inline">\(0\)</span></td>
<td>deleted</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The lasso and the elastic net are not of this form. They act on the coefficients <span class="math inline">\(\beta_j\)</span> themselves and can set them to zero.</p>
</section>
<section id="what-each-method-minimises" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="what-each-method-minimises"><span class="header-section-number">3</span> What each method minimises</h2>
<p>Every method here minimises <span class="math inline">\(\mathrm{MSE}(\beta) + \lambda \cdot \text{penalty}(\beta)\)</span>, or the MSE under a restriction. The scene draws that objective for two predictors.</p>
<div id="widget-remedy-valley">

</div>
<script src="../../widget-kit/stage.js"></script>
<script src="model.js"></script>
<script src="widgets.js"></script>
<p>With <strong>least squares</strong> at <strong>0.99</strong> it is Part 1’s trough. The answers of the 200 samples lie strewn along its floor, the <span class="math inline">\(x_1\)</span> coefficient has a standard deviation of 0.68, and a typical answer is 0.96 away from the truth.</p>
<section id="ridge" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="ridge"><span class="header-section-number">3.1</span> Ridge</h3>
<p>Ridge (Hoerl and Kennard, 1970) adds the squared length of the coefficient vector:</p>
<p><span class="math display">\[
\tilde\beta_{\text{ridge}} = \arg\min_\beta \; \mathrm{MSE}(\beta) + \lambda \lVert\beta\rVert^2 = \Big(\tfrac{1}{n}X^\top X + \lambda I\Big)^{-1} \tfrac{1}{n}X^\top y .
\]</span></p>
<ul>
<li><strong>In the trough.</strong> The penalty adds curvature <span class="math inline">\(2\lambda\)</span> in every direction. Across the trough that is negligible beside the curvature already there. Along the floor it is most of what there is.</li>
<li><strong>Filter factors.</strong> For two columns, <span class="math inline">\(d_1 = 1 + r\)</span> and <span class="math inline">\(d_2 = 1 - r\)</span>. At <span class="math inline">\(r = 0.99\)</span> and <span class="math inline">\(\lambda = 0.1\)</span>: <span class="math inline">\(f_1 = 1.99/2.09 = 0.95\)</span> and <span class="math inline">\(f_2 = 0.01/0.11 = 0.09\)</span>. The sum of the coefficients keeps 95% of its least-squares value and the difference keeps 9%.</li>
<li><strong>Condition number.</strong> That of <span class="math inline">\(\tfrac{1}{n}X^\top X + \lambda I\)</span> is <span class="math inline">\((d_1 + \lambda)/(d_2 + \lambda)\)</span>: 19 in place of 199.</li>
<li><strong>As extra rows.</strong> Ridge is least squares on the data plus one made-up row per predictor, in which that predictor alone is non-zero and the response is 0. Those are rows in which the predictors move separately, the kind the data lacked.</li>
<li><strong>As a prior.</strong> It is the posterior mode under independent Gaussian priors centred on zero.</li>
</ul>
<ol type="1">
<li>Press <strong>ridge</strong> and set the penalty weight to <strong>0.10</strong>. The floor of the trough has curled up into a bowl. The pink dot, least squares for this sample at <span class="math inline">\((1.68, 0.18)\)</span>, has been pulled along the floor to the amber answer at <span class="math inline">\((0.95, 0.82)\)</span>.</li>
<li>Read the stats. The standard deviation of the <span class="math inline">\(x_1\)</span> coefficient is 0.07. The average answer is <span class="math inline">\((1.00, 0.90)\)</span>, and the truth is <span class="math inline">\((1.5, 0.5)\)</span>.</li>
<li>Slide the weight down to <strong>0.018</strong>. The average answer moves to <span class="math inline">\((1.17, 0.81)\)</span> and the typical distance from the truth is 0.57, the lowest ridge reaches at this correlation.</li>
<li>Slide it up to <strong>1.0</strong>. Both coefficients shrink towards zero together, to an average of <span class="math inline">\((0.67, 0.66)\)</span>, and the distance rises to 0.85.</li>
</ol>
<p>Ridge does not find the difference. It replaces “unknown” with “close to zero”, which here is wrong by 1.</p>
</section>
<section id="principal-components-regression" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="principal-components-regression"><span class="header-section-number">3.2</span> Principal components regression</h3>
<p>Principal components regression (PCR) rotates the predictors onto their principal components, the directions <span class="math inline">\(v_i\)</span>, regresses <span class="math inline">\(y\)</span> on the first <span class="math inline">\(k\)</span> of them, and rotates back.</p>
<ul>
<li><strong>For two columns.</strong> The first component is the average of the two predictors and the second is their difference. Keeping one component forces <span class="math inline">\(\tilde\beta_1 = \tilde\beta_2 = (\hat\beta_1 + \hat\beta_2)/2\)</span>.</li>
<li><strong>Filter factors.</strong> 1 for the kept components, 0 for the others: ridge’s shrinkage taken to its limit for the small <span class="math inline">\(d_i\)</span> and switched off for the large ones.</li>
<li><strong>What <span class="math inline">\(k\)</span> is.</strong> The tuning knob, in whole steps.</li>
</ul>
<ol type="1">
<li>Press <strong>one component</strong>. The amber line on the surface is the restriction <span class="math inline">\(\beta_1 = \beta_2\)</span>, and every answer lies on it.</li>
<li>Read the stats. The standard deviation of the <span class="math inline">\(x_1\)</span> coefficient is 0.05, the average answer is <span class="math inline">\((1.00, 1.00)\)</span>, and the typical distance from the truth is 0.71.</li>
<li>Press <strong>0.9</strong>. Least squares has a typical distance of 0.31 at this correlation. One component still has 0.71.</li>
</ol>
<p>That 0.71 is the length of the part of the truth that lies along the weak direction: <span class="math inline">\((1.5, 0.5) = (1, 1) + (0.5, -0.5)\)</span>, and <span class="math inline">\(\lVert(0.5, -0.5)\rVert = 0.71\)</span>. PCR deletes that part at every correlation. At <span class="math inline">\(r = 0.99\)</span> deleting it costs less than estimating it. At <span class="math inline">\(r = 0.9\)</span> it costs more.</p>
<p>PCR chooses components by the variance of the predictors and never looks at <span class="math inline">\(y\)</span>. A low-variance component can be the one that predicts (Jolliffe, 1982).</p>
</section>
<section id="lasso" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="lasso"><span class="header-section-number">3.3</span> Lasso</h3>
<p>The lasso (Tibshirani, 1996) penalises the sum of absolute values:</p>
<p><span class="math display">\[
\tilde\beta_{\text{lasso}} = \arg\min_\beta \; \mathrm{MSE}(\beta) + \lambda \big(\lvert\beta_1\rvert + \dots + \lvert\beta_p\rvert\big).
\]</span></p>
<ul>
<li><strong>What it is for.</strong> The absolute value has a corner at zero, so the minimum often sits exactly on <span class="math inline">\(\beta_j = 0\)</span>. The lasso selects predictors.</li>
<li><strong>On the floor of the trough.</strong> Along the floor <span class="math inline">\(\beta_1 + \beta_2\)</span> is fixed. While both coefficients are positive, <span class="math inline">\(\lvert\beta_1\rvert + \lvert\beta_2\rvert\)</span> is that same sum, so the penalty is flat along the floor. The lasso adds no curvature where curvature was missing.</li>
<li><strong>What breaks the tie.</strong> The slight tilt of the floor in each sample: noise.</li>
</ul>
<ol type="1">
<li>Press <strong>0.99</strong>, <strong>lasso</strong>, and set the weight to <strong>0.10</strong>. The two dark lines on the surface are <span class="math inline">\(\beta_1 = 0\)</span> and <span class="math inline">\(\beta_2 = 0\)</span>. The grey answers are still spread along the floor, and some have stopped on a line.</li>
<li>Read the stats. The standard deviation of the <span class="math inline">\(x_1\)</span> coefficient is 0.54, against 0.68 for least squares. 4 samples drop <span class="math inline">\(x_1\)</span> and 54 drop <span class="math inline">\(x_2\)</span>.</li>
<li>Press <strong>New noise</strong> three times. The answer goes from <span class="math inline">\((1.65, 0.16)\)</span> to <span class="math inline">\((1.29, 0.56)\)</span>, <span class="math inline">\((1.37, 0.62)\)</span> and <span class="math inline">\((1.92, 0.00)\)</span>.</li>
<li>Press <strong>0.999</strong>. 48 samples drop <span class="math inline">\(x_1\)</span>, the predictor with three times the true coefficient, and 82 drop <span class="math inline">\(x_2\)</span>.</li>
</ol>
<p>With collinear predictors the lasso still selects, and the selection is unstable. It reports one predictor of a pair as irrelevant, and a different sample reverses the report.</p>
</section>
<section id="elastic-net" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="elastic-net"><span class="header-section-number">3.4</span> Elastic net</h3>
<p>The elastic net (Zou and Hastie, 2005) uses both penalties. The scene uses equal weights:</p>
<p><span class="math display">\[
\tilde\beta_{\text{enet}} = \arg\min_\beta \; \mathrm{MSE}(\beta) + \lambda \Big(\tfrac{1}{2}\lVert\beta\rVert_1 + \tfrac{1}{2}\lVert\beta\rVert^2\Big).
\]</span></p>
<ul>
<li><strong>The squared term</strong> curls the floor of the trough, as ridge does, so correlated predictors share the weight. Zou and Hastie call this the grouping effect.</li>
<li><strong>The absolute term</strong> keeps the corner at zero, so predictors unrelated to <span class="math inline">\(y\)</span> can still be dropped.</li>
</ul>
<ol type="1">
<li>Press <strong>0.99</strong>, <strong>elastic net</strong>, weight <strong>0.10</strong>. The answers have gathered: the standard deviation of the <span class="math inline">\(x_1\)</span> coefficient is 0.12, and no sample drops either predictor.</li>
<li>Press <strong>0.999</strong>. Still none dropped, against 130 of 200 for the lasso at the same weight.</li>
<li>Read the average answer, <span class="math inline">\((0.97, 0.95)\)</span>. It shares the weight equally. The truth does not.</li>
</ol>
</section>
<section id="summary-of-the-scene" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="summary-of-the-scene"><span class="header-section-number">3.5</span> Summary of the scene</h3>
<div id="tbl-scene" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-scene-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: The scene’s stats over its 200 noise draws.
</figcaption>
<div aria-describedby="tbl-scene-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Method at <span class="math inline">\(r = 0.99\)</span></th>
<th>sd of the <span class="math inline">\(x_1\)</span> coefficient</th>
<th>Average answer</th>
<th>Typical distance from <span class="math inline">\((1.5, 0.5)\)</span></th>
<th>Samples dropping <span class="math inline">\(x_1\)</span> / <span class="math inline">\(x_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Least squares</td>
<td>0.68</td>
<td>(1.50, 0.49)</td>
<td>0.96</td>
<td>0 / 0</td>
</tr>
<tr class="even">
<td>Ridge, <span class="math inline">\(\lambda = 0.018\)</span></td>
<td>0.25</td>
<td>(1.17, 0.81)</td>
<td>0.57</td>
<td>0 / 0</td>
</tr>
<tr class="odd">
<td>Ridge, <span class="math inline">\(\lambda = 0.10\)</span></td>
<td>0.07</td>
<td>(1.00, 0.90)</td>
<td>0.65</td>
<td>0 / 0</td>
</tr>
<tr class="even">
<td>One component</td>
<td>0.05</td>
<td>(1.00, 1.00)</td>
<td>0.71</td>
<td>0 / 0</td>
</tr>
<tr class="odd">
<td>Lasso, <span class="math inline">\(\lambda = 0.10\)</span></td>
<td>0.54</td>
<td>(1.39, 0.56)</td>
<td>0.78</td>
<td>4 / 54</td>
</tr>
<tr class="even">
<td>Elastic net, <span class="math inline">\(\lambda = 0.10\)</span></td>
<td>0.12</td>
<td>(1.05, 0.88)</td>
<td>0.62</td>
<td>0 / 0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Least squares is right on average and far off in any one sample. Ridge, one component and the elastic net are wrong on average by a fixed amount and stay close to that answer in every sample. The lasso keeps most of the spread.</p>
</section>
</section>
<section id="the-cost" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="the-cost"><span class="header-section-number">4</span> The cost</h2>
<p>The stability is bought with bias, and the bias sits where Part 1 located the damage: at points where the predictors disagree.</p>
<div id="widget-remedy-fence">

</div>
<ol type="1">
<li>Start with <strong>least squares</strong> at <strong>0.99</strong>. At <span class="math inline">\((1.5, -1.5)\)</span> the true value is 1.50. The average prediction is 1.52, its standard deviation is 2.05, and the typical error is 2.04.</li>
<li>Press <strong>ridge</strong>, weight <strong>0.10</strong>. The fan closes. The average prediction is 0.14 with a standard deviation of 0.19, and the typical error is 1.37. Every plane now misses the dark dot, and all miss it by about the same amount.</li>
<li>Press <strong>one component</strong>. The prediction at <span class="math inline">\((1.5, -1.5)\)</span> is 0.00 in every sample. The typical error is 1.50, the true value itself.</li>
<li>Compare at <span class="math inline">\((1.5, 1.5)\)</span>, where the predictors agree. The typical error is 0.14 for least squares, 0.20 for ridge at 0.10, and 0.14 for one component.</li>
<li>Press <strong>0.999</strong> and <strong>least squares</strong>. The typical error at <span class="math inline">\((1.5, -1.5)\)</span> is 6.47. For ridge at 0.10 it is 1.49.</li>
</ol>
<ul>
<li>A point where the predictors disagree is a point along the weak direction. Least squares answers there with a guess that is right on average and wild in any one sample. The remedies answer with the assumption: no effect of the difference.</li>
<li>Whether the trade is good depends on how wild the guess was. At <span class="math inline">\(r = 0.999\)</span> an error of 1.5 replaces one of 6.5. At <span class="math inline">\(r = 0.9\)</span> ridge at 0.10 has a typical error of 0.82 there and least squares 0.64.</li>
<li>No method predicts well where the predictors disagree. The training rows hold no evidence about such points, and a penalty adds none.</li>
</ul>
</section>
<section id="real-data" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="real-data"><span class="header-section-number">5</span> Real data</h2>
<section id="the-diabetes-data" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="the-diabetes-data"><span class="header-section-number">5.1</span> The diabetes data</h3>
<ul>
<li><strong>Source.</strong> Efron, Hastie, Johnstone and Tibshirani (2004), shipped with scikit-learn: 442 diabetes patients, ten baseline measurements, and a measure of disease progression a year later.</li>
<li><strong>What Part 1 found.</strong> Total cholesterol (<code>s1</code>), LDL (<code>s2</code>), HDL (<code>s3</code>) and the triglyceride column (<code>s5</code>) are tied by the Friedewald formula, from which LDL is computed. The variance inflation factor (VIF) of total cholesterol is 59, and its least-squares coefficient is negative with a standard error half its size.</li>
<li><strong>What this post asks of it.</strong> What each remedy does to those coefficients, and whether any remedy predicts better.</li>
<li><strong>Cost of a wrong answer.</strong> Reporting a stabilised coefficient as an effect, or reporting a selected predictor as the relevant one.</li>
<li><strong>Why these methods fit.</strong> Ten standardised predictors, one strong dependence among four of them, and enough rows to resample.</li>
</ul>
<section id="filter-factors" class="level4" data-number="5.1.1">
<h4 data-number="5.1.1" class="anchored" data-anchor-id="filter-factors"><span class="header-section-number">5.1.1</span> Filter factors</h4>
<div id="cell-fig-filters" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">7.4</span>, <span class="fl">2.8</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> np.arange(<span class="dv">1</span>, p <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> <span class="fl">0.38</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].bar(idx <span class="op">-</span> w <span class="op">/</span> <span class="dv">2</span>, d_eig <span class="op">/</span> (d_eig <span class="op">+</span> lam_cv), w, color<span class="op">=</span>PURPLE, label<span class="op">=</span><span class="ss">f"λ = </span><span class="sc">{</span>lam_cv<span class="sc">:.4f}</span><span class="ss"> (cross-validated)"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].bar(idx <span class="op">+</span> w <span class="op">/</span> <span class="dv">2</span>, d_eig <span class="op">/</span> (d_eig <span class="op">+</span> <span class="dv">20</span> <span class="op">*</span> lam_cv), w, color<span class="op">=</span>TEAL, label<span class="op">=</span><span class="ss">f"λ = </span><span class="sc">{</span><span class="dv">20</span> <span class="op">*</span> lam_cv<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Ridge"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">True</span>, framealpha<span class="op">=</span><span class="fl">0.92</span>, edgecolor<span class="op">=</span>RULE, fontsize<span class="op">=</span><span class="fl">7.5</span>, loc<span class="op">=</span><span class="st">"lower left"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar(idx, (idx <span class="op">&lt;=</span> k_best).astype(<span class="bu">float</span>), <span class="fl">0.6</span>, color<span class="op">=</span>AMBER)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="ss">f"Principal components, k = </span><span class="sc">{</span>k_best<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> axes:</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks(idx)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"singular direction"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"filter factor"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-filters" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-filters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-filters-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-filters-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Filter factors on the ten singular directions of the standardised diabetes predictors, ordered from the strongest to the weakest. Left: ridge at the weight cross-validation chooses and at a weight twenty times larger. Right: principal components regression keeping seven components.
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>The eigenvalues <span class="math inline">\(d_i\)</span> run from 4.02 down to 0.078 and 0.0086. The last is the Friedewald identity.</li>
<li>Cross-validation chooses a ridge weight of 0.0039, which leaves the weakest direction with a factor of 0.69. Prediction error does not ask for more.</li>
<li>Of the ten possible settings, PCR with 7 components has the lowest cross-validated error. It deletes the 3 weakest directions.</li>
</ul>
</section>
<section id="coefficient-paths" class="level4" data-number="5.1.2">
<h4 data-number="5.1.2" class="anchored" data-anchor-id="coefficient-paths"><span class="header-section-number">5.1.2</span> Coefficient paths</h4>
<div id="cell-fig-paths" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>lams <span class="op">=</span> np.logspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">80</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>ridge_path <span class="op">=</span> np.array([np.linalg.solve(G <span class="op">+</span> lam <span class="op">*</span> np.eye(p), Z.T <span class="op">@</span> yc <span class="op">/</span> n) <span class="cf">for</span> lam <span class="kw">in</span> lams])</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># scikit-learn's lasso minimises RSS/(2n) + alpha |b|_1, so lambda = 2 alpha here; its elastic</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># net with l1_ratio rho minimises RSS/(2n) + alpha rho |b|_1 + alpha (1 - rho) |b|^2 / 2, so</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># this post's equal mix lambda (|b|_1 / 2 + |b|^2 / 2) is alpha = 0.75 lambda, rho = 1/3.</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>_, lasso_coefs, _ <span class="op">=</span> lasso_path(Z, yc, alphas<span class="op">=</span>lams[::<span class="op">-</span><span class="dv">1</span>] <span class="op">/</span> <span class="dv">2</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>_, enet_coefs, _ <span class="op">=</span> enet_path(Z, yc, alphas<span class="op">=</span><span class="fl">0.75</span> <span class="op">*</span> lams[::<span class="op">-</span><span class="dv">1</span>], l1_ratio<span class="op">=</span><span class="dv">1</span> <span class="op">/</span> <span class="dv">3</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>lasso_cv <span class="op">=</span> LassoCV(cv<span class="op">=</span><span class="dv">5</span>, random_state<span class="op">=</span><span class="dv">0</span>).fit(Z, y)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>enet_cv <span class="op">=</span> ElasticNetCV(l1_ratio<span class="op">=</span><span class="dv">1</span> <span class="op">/</span> <span class="dv">3</span>, cv<span class="op">=</span><span class="dv">5</span>, random_state<span class="op">=</span><span class="dv">0</span>).fit(Z, y)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>chosen <span class="op">=</span> {<span class="st">"Ridge"</span>: lam_cv, <span class="st">"Lasso"</span>: <span class="dv">2</span> <span class="op">*</span> lasso_cv.alpha_, <span class="st">"Elastic net"</span>: enet_cv.alpha_ <span class="op">/</span> <span class="fl">0.75</span>}</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>paths <span class="op">=</span> {<span class="st">"Ridge"</span>: ridge_path, <span class="st">"Lasso"</span>: lasso_coefs.T[::<span class="op">-</span><span class="dv">1</span>], <span class="st">"Elastic net"</span>: enet_coefs.T[::<span class="op">-</span><span class="dv">1</span>]}</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">2.9</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (name, path) <span class="kw">in</span> <span class="bu">zip</span>(axes, paths.items()):</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j, c <span class="kw">in</span> <span class="bu">enumerate</span>(names):</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> c <span class="kw">not</span> <span class="kw">in</span> (<span class="st">"s1"</span>, <span class="st">"s2"</span>):</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>            ax.plot(lams, path[:, j], color<span class="op">=</span>RULE, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    ax.plot(lams, path[:, names.index(<span class="st">"s1"</span>)], color<span class="op">=</span>PURPLE, lw<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span><span class="st">"total cholesterol (s1)"</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    ax.plot(lams, path[:, names.index(<span class="st">"s2"</span>)], color<span class="op">=</span>AMBER, lw<span class="op">=</span><span class="fl">1.8</span>, label<span class="op">=</span><span class="st">"LDL (s2)"</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    ax.axvline(chosen[name], color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">0.7</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    ax.axhline(<span class="dv">0</span>, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    ax.set_xscale(<span class="st">"log"</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    ax.set_title(name)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"penalty weight λ"</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"coefficient"</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="fl">7.5</span>, loc<span class="op">=</span><span class="st">"lower right"</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-paths" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-paths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-paths-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-paths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Coefficients of the ten standardised diabetes predictors as the penalty weight grows. Total cholesterol (s1) and LDL (s2) are coloured; the other eight are grey. The dashed line marks the weight chosen by five-fold cross-validation.
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Ridge.</strong> Between <span class="math inline">\(\lambda = 0.0001\)</span> and <span class="math inline">\(\lambda = 0.05\)</span> the coefficient of total cholesterol goes from -37.3 to -6.3 and LDL’s from +22.3 to -1.9. Body mass index goes from 24.7 to 24.1. A small weight removes the opposed pair and leaves the predictors outside the dependence alone.</li>
<li><strong>Lasso.</strong> The pair holds its opposed values until <span class="math inline">\(\lambda\)</span> is near 0.1. LDL then falls to zero at <span class="math inline">\(\lambda \approx\)</span> 0.54, and total cholesterol keeps a negative coefficient after it.</li>
<li><strong>Elastic net.</strong> The ridge shape, at larger weights because half of the weight goes to the absolute-value term.</li>
<li><strong>The dashed lines.</strong> For ridge and the lasso, cross-validation stops short of the weight at which the pair settles. For the elastic net it does not: at its chosen weight the coefficients are -4.2 and -3.2.</li>
</ul>
</section>
<section id="stability-and-prediction" class="level4" data-number="5.1.3">
<h4 data-number="5.1.3" class="anchored" data-anchor-id="stability-and-prediction"><span class="header-section-number">5.1.3</span> Stability and prediction</h4>
<p>Two measurements for each method, with its tuning chosen by cross-validation:</p>
<ul>
<li><strong>Stability.</strong> Refit on 500 bootstrap resamples of the 442 patients and record the coefficient of total cholesterol.</li>
<li><strong>Prediction.</strong> Ten-fold cross-validated root mean squared error, repeated ten times.</li>
</ul>
<p>“Drop LDL” is least squares on the nine predictors that remain when the computed column is removed.</p>
<div class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>keep_no_ldl <span class="op">=</span> [j <span class="cf">for</span> j, c <span class="kw">in</span> <span class="bu">enumerate</span>(names) <span class="cf">if</span> c <span class="op">!=</span> <span class="st">"s2"</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> DropLDL(LinearRegression):</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> fit(<span class="va">self</span>, X, y):</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="bu">super</span>().fit(X[:, keep_no_ldl], y)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> predict(<span class="va">self</span>, X):</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="bu">super</span>().predict(X[:, keep_no_ldl])</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> s1_coef(model, name):</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> name <span class="op">==</span> <span class="st">"PCR, 7 components"</span>:</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> (model[<span class="dv">1</span>].components_.T <span class="op">@</span> model[<span class="dv">2</span>].coef_)[i1]</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> name <span class="op">==</span> <span class="st">"Drop LDL"</span>:</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> model[<span class="op">-</span><span class="dv">1</span>].coef_[keep_no_ldl.index(i1)]</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model[<span class="op">-</span><span class="dv">1</span>].coef_[i1]</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>models <span class="op">=</span> {</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Least squares"</span>: make_pipeline(StandardScaler(), LinearRegression()),</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Ridge"</span>: make_pipeline(StandardScaler(), RidgeCV(alphas<span class="op">=</span>ALPHAS)),</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    <span class="st">"PCR, 7 components"</span>: make_pipeline(StandardScaler(), PCA(n_components<span class="op">=</span>k_best), LinearRegression()),</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Lasso"</span>: make_pipeline(StandardScaler(), LassoCV(cv<span class="op">=</span><span class="dv">5</span>, random_state<span class="op">=</span><span class="dv">0</span>)),</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Elastic net"</span>: make_pipeline(StandardScaler(), ElasticNetCV(l1_ratio<span class="op">=</span><span class="dv">1</span> <span class="op">/</span> <span class="dv">3</span>, cv<span class="op">=</span><span class="dv">5</span>, random_state<span class="op">=</span><span class="dv">0</span>)),</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Drop LDL"</span>: make_pipeline(StandardScaler(), DropLDL()),</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>B <span class="op">=</span> <span class="dv">500</span></span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>resamples <span class="op">=</span> [rng.integers(<span class="dv">0</span>, n, n) <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(B)]</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>boot <span class="op">=</span> {name: np.array([s1_coef(m.fit(X_raw[ix], y[ix]), name) <span class="cf">for</span> ix <span class="kw">in</span> resamples]) <span class="cf">for</span> name, m <span class="kw">in</span> models.items()}</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>cv_rmse <span class="op">=</span> {}</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, m <span class="kw">in</span> models.items():</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>    mse <span class="op">=</span> <span class="op">-</span>cross_val_score(m, X_raw, y, cv<span class="op">=</span>cv10, scoring<span class="op">=</span><span class="st">"neg_mean_squared_error"</span>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    cv_rmse[name] <span class="op">=</span> np.sqrt(mse.reshape(<span class="dv">10</span>, <span class="dv">10</span>).mean(<span class="dv">1</span>))</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name <span class="kw">in</span> models:</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> boot[name]</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>    rows.append(</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>        {</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Method"</span>: name,</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Mean"</span>: <span class="ss">f"</span><span class="sc">{</span>b<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss">"</span>,</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>            <span class="st">"sd"</span>: <span class="ss">f"</span><span class="sc">{</span>b<span class="sc">.</span>std()<span class="sc">:.1f}</span><span class="ss">"</span>,</span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Positive"</span>: <span class="ss">f"</span><span class="sc">{</span>(b <span class="op">&gt;</span> <span class="dv">0</span>)<span class="sc">.</span>mean()<span class="sc">:.0%}</span><span class="ss">"</span>,</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Exactly zero"</span>: <span class="ss">f"</span><span class="sc">{</span>(b <span class="op">==</span> <span class="dv">0</span>)<span class="sc">.</span>mean()<span class="sc">:.0%}</span><span class="ss">"</span>,</span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>            <span class="st">"CV error"</span>: <span class="ss">f"</span><span class="sc">{</span>cv_rmse[name]<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss"> [</span><span class="sc">{</span>cv_rmse[name]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.1f}</span><span class="ss">, </span><span class="sc">{</span>cv_rmse[name]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.1f}</span><span class="ss">]"</span>,</span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>md(pd.DataFrame(rows), index<span class="op">=</span><span class="va">False</span>, colalign<span class="op">=</span>(<span class="st">"left"</span>,) <span class="op">+</span> (<span class="st">"right"</span>,) <span class="op">*</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-stability" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: The coefficient of total cholesterol (standardised) over 500 bootstrap resamples, and cross-validated prediction error, for each method on the diabetes data. Tuning is by five-fold cross-validation inside each fit. The error column is the mean of ten repeats of ten-fold cross-validation, with the range of the ten repeats in brackets.
</figcaption>
<div aria-describedby="tbl-stability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 23%">
<col style="width: 10%">
<col style="width: 7%">
<col style="width: 15%">
<col style="width: 20%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Method</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">Positive</th>
<th style="text-align: right;">Exactly zero</th>
<th style="text-align: right;">CV error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Least squares</td>
<td style="text-align: right;">-37.6</td>
<td style="text-align: right;">18.4</td>
<td style="text-align: right;">3%</td>
<td style="text-align: right;">0%</td>
<td style="text-align: right;">54.9 [54.6, 55.2]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ridge</td>
<td style="text-align: right;">-26.2</td>
<td style="text-align: right;">21.6</td>
<td style="text-align: right;">1%</td>
<td style="text-align: right;">0%</td>
<td style="text-align: right;">55.0 [54.7, 55.4]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PCR, 7 components</td>
<td style="text-align: right;">-1.9</td>
<td style="text-align: right;">1.6</td>
<td style="text-align: right;">12%</td>
<td style="text-align: right;">0%</td>
<td style="text-align: right;">54.7 [54.5, 54.9]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lasso</td>
<td style="text-align: right;">-22.0</td>
<td style="text-align: right;">20.1</td>
<td style="text-align: right;">0%</td>
<td style="text-align: right;">11%</td>
<td style="text-align: right;">55.0 [54.7, 55.3]</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Elastic net</td>
<td style="text-align: right;">-4.0</td>
<td style="text-align: right;">2.2</td>
<td style="text-align: right;">2%</td>
<td style="text-align: right;">1%</td>
<td style="text-align: right;">54.8 [54.6, 55.0]</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drop LDL</td>
<td style="text-align: right;">-10.5</td>
<td style="text-align: right;">5.4</td>
<td style="text-align: right;">3%</td>
<td style="text-align: right;">0%</td>
<td style="text-align: right;">54.8 [54.6, 55.1]</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ul>
<li><strong>Prediction.</strong> The methods are within 0.3 of each other, 54.7 to 55.0, on a response whose standard deviation is 77. With 442 rows whose predictors follow the training pattern, collinearity was not costing any prediction accuracy, so no remedy could buy any.</li>
<li><strong>Ridge and lasso.</strong> Tuned for prediction, both leave the coefficient as unstable as least squares: a standard deviation of 21.6 and 20.1 against 18.4. Cross-validation picks the weight that predicts best, and prediction did not need the pair settled.</li>
<li><strong>Elastic net and PCR.</strong> These settle it: 2.2 and 1.6.</li>
<li><strong>Drop LDL.</strong> One deleted column gives a standard deviation of 5.4 at the same prediction error.</li>
</ul>
<p>The stable answers disagree with each other about the size of the coefficient. Each reflects its method’s assumption about the weak direction, and the data cannot rank the assumptions.</p>
</section>
<section id="fewer-rows" class="level4" data-number="5.1.4">
<h4 data-number="5.1.4" class="anchored" data-anchor-id="fewer-rows"><span class="header-section-number">5.1.4</span> Fewer rows</h4>
<p>Remedies do improve prediction when rows are scarce, because then the noise in the weak directions reaches the predictions.</p>
<div class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> pcr_cv(Xtr, ytr, Xte):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    best, best_k <span class="op">=</span> np.inf, <span class="dv">1</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">min</span>(p, <span class="bu">len</span>(ytr) <span class="op">-</span> <span class="dv">6</span>) <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>        model <span class="op">=</span> make_pipeline(PCA(n_components<span class="op">=</span>k), LinearRegression())</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>        score <span class="op">=</span> <span class="op">-</span>cross_val_score(model, Xtr, ytr, cv<span class="op">=</span><span class="dv">5</span>, scoring<span class="op">=</span><span class="st">"neg_mean_squared_error"</span>).mean()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> score <span class="op">&lt;</span> best:</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>            best, best_k <span class="op">=</span> score, k</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> make_pipeline(PCA(n_components<span class="op">=</span>best_k), LinearRegression()).fit(Xtr, ytr).predict(Xte)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>sizes <span class="op">=</span> [<span class="dv">20</span>, <span class="dv">30</span>, <span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>]</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>small <span class="op">=</span> {s: {k: [] <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"Least squares"</span>, <span class="st">"Ridge"</span>, <span class="st">"PCR"</span>, <span class="st">"Lasso"</span>, <span class="st">"Elastic net"</span>]} <span class="cf">for</span> s <span class="kw">in</span> sizes}</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> size <span class="kw">in</span> sizes:</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> seed <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">200</span>):</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>        perm <span class="op">=</span> np.random.default_rng(seed).permutation(n)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>        tr, te <span class="op">=</span> perm[:size], perm[size:]</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>        sc <span class="op">=</span> StandardScaler().fit(X_raw[tr])</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>        Xtr, Xte, ytr, yte <span class="op">=</span> sc.transform(X_raw[tr]), sc.transform(X_raw[te]), y[tr], y[te]</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>        preds <span class="op">=</span> {</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Least squares"</span>: LinearRegression().fit(Xtr, ytr).predict(Xte),</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Ridge"</span>: RidgeCV(alphas<span class="op">=</span>ALPHAS).fit(Xtr, ytr).predict(Xte),</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>            <span class="st">"PCR"</span>: pcr_cv(Xtr, ytr, Xte),</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Lasso"</span>: LassoCV(cv<span class="op">=</span><span class="dv">5</span>, random_state<span class="op">=</span><span class="dv">0</span>, max_iter<span class="op">=</span><span class="dv">5000</span>).fit(Xtr, ytr).predict(Xte),</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>            <span class="st">"Elastic net"</span>: ElasticNetCV(l1_ratio<span class="op">=</span><span class="dv">1</span> <span class="op">/</span> <span class="dv">3</span>, cv<span class="op">=</span><span class="dv">5</span>, random_state<span class="op">=</span><span class="dv">0</span>, max_iter<span class="op">=</span><span class="dv">5000</span>).fit(Xtr, ytr).predict(Xte),</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> k, pr <span class="kw">in</span> preds.items():</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>            small[size][k].append(np.sqrt(np.mean((pr <span class="op">-</span> yte) <span class="op">**</span> <span class="dv">2</span>)))</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> size <span class="kw">in</span> sizes:</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    row <span class="op">=</span> {<span class="st">"Training rows"</span>: <span class="bu">str</span>(size)}</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k, v <span class="kw">in</span> small[size].items():</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>        lo, mid, hi <span class="op">=</span> np.percentile(v, [<span class="dv">5</span>, <span class="dv">50</span>, <span class="dv">95</span>])</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>        row[k] <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span>mid<span class="sc">:.1f}</span><span class="ss"> [</span><span class="sc">{</span>lo<span class="sc">:.1f}</span><span class="ss">, </span><span class="sc">{</span>hi<span class="sc">:.1f}</span><span class="ss">]"</span></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>    rows.append(row)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>md(pd.DataFrame(rows), index<span class="op">=</span><span class="va">False</span>, colalign<span class="op">=</span>(<span class="st">"right"</span>,) <span class="op">*</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-small-n" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="8">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-small-n-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Test root mean squared error on the diabetes data when only some of the 442 patients are used for fitting and the others for testing. The median of 200 random splits, with the 5–95% interval in brackets. Tuning is by five-fold cross-validation on the training rows.
</figcaption>
<div aria-describedby="tbl-small-n-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="8">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Training rows</th>
<th style="text-align: right;">Least squares</th>
<th style="text-align: right;">Ridge</th>
<th style="text-align: right;">PCR</th>
<th style="text-align: right;">Lasso</th>
<th style="text-align: right;">Elastic net</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">20</td>
<td style="text-align: right;">85.9 [67.3, 123.5]</td>
<td style="text-align: right;">63.2 [57.5, 79.7]</td>
<td style="text-align: right;">65.9 [58.2, 83.1]</td>
<td style="text-align: right;">64.7 [57.7, 82.4]</td>
<td style="text-align: right;">62.8 [57.4, 73.5]</td>
</tr>
<tr class="even">
<td style="text-align: right;">30</td>
<td style="text-align: right;">69.1 [59.2, 86.3]</td>
<td style="text-align: right;">60.7 [56.8, 72.0]</td>
<td style="text-align: right;">62.9 [57.0, 76.7]</td>
<td style="text-align: right;">62.1 [57.2, 73.4]</td>
<td style="text-align: right;">60.8 [56.7, 67.6]</td>
</tr>
<tr class="odd">
<td style="text-align: right;">50</td>
<td style="text-align: right;">61.3 [56.7, 69.7]</td>
<td style="text-align: right;">58.3 [55.9, 64.1]</td>
<td style="text-align: right;">59.2 [55.9, 66.2]</td>
<td style="text-align: right;">59.0 [55.9, 65.3]</td>
<td style="text-align: right;">58.4 [55.9, 63.0]</td>
</tr>
<tr class="even">
<td style="text-align: right;">100</td>
<td style="text-align: right;">57.2 [54.9, 59.9]</td>
<td style="text-align: right;">56.5 [54.5, 59.2]</td>
<td style="text-align: right;">56.5 [54.5, 59.7]</td>
<td style="text-align: right;">56.9 [54.7, 59.4]</td>
<td style="text-align: right;">56.4 [54.6, 58.6]</td>
</tr>
<tr class="odd">
<td style="text-align: right;">200</td>
<td style="text-align: right;">55.8 [53.3, 58.6]</td>
<td style="text-align: right;">55.6 [53.3, 58.4]</td>
<td style="text-align: right;">55.7 [53.5, 58.6]</td>
<td style="text-align: right;">55.6 [53.4, 58.4]</td>
<td style="text-align: right;">55.5 [53.4, 58.0]</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ul>
<li>With 20 training rows least squares has a median error of 85.9 and ridge 63.2.</li>
<li>With 50 the gap is 61.3 against 58.3.</li>
<li>With 200 all five methods are within 0.2.</li>
</ul>
</section>
</section>
<section id="longley-the-two-columns" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="longley-the-two-columns"><span class="header-section-number">5.2</span> Longley: the two columns</h3>
<ul>
<li><strong>Source.</strong> Longley (1967), shipped with <code>statsmodels</code>: 16 annual observations of the US economy, 1947 to 1962.</li>
<li><strong>What Part 1 found.</strong> Total employment regressed on standardised GNP and population gives coefficients of 6,279 and −2,850, although each predictor alone has a coefficient near 3,400. The two columns correlate at 0.991.</li>
<li><strong>What this post asks of it.</strong> What a ridge penalty does to that pair.</li>
<li><strong>Cost of a wrong answer.</strong> Reading the negative coefficient, or the stabilised one, as the effect of population.</li>
<li><strong>Why it fits.</strong> Two columns, so the sum and the difference can be read off.</li>
</ul>
<div class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Lg <span class="op">=</span> sm.datasets.longley.load_pandas().data</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>Z2 <span class="op">=</span> ((Lg[[<span class="st">"GNP"</span>, <span class="st">"POP"</span>]] <span class="op">-</span> Lg[[<span class="st">"GNP"</span>, <span class="st">"POP"</span>]].mean()) <span class="op">/</span> Lg[[<span class="st">"GNP"</span>, <span class="st">"POP"</span>]].std()).values</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>yL <span class="op">=</span> Lg[<span class="st">"TOTEMP"</span>].values <span class="op">-</span> Lg[<span class="st">"TOTEMP"</span>].mean()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>m <span class="op">=</span> <span class="bu">len</span>(yL) <span class="op">-</span> <span class="dv">1</span>  <span class="co"># the sample standard deviation divides by n - 1, as in Part 1</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>G2 <span class="op">=</span> Z2.T <span class="op">@</span> Z2 <span class="op">/</span> m</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>rows, longley <span class="op">=</span> [], {}</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lam <span class="kw">in</span> [<span class="dv">0</span>, <span class="fl">0.001</span>, <span class="fl">0.01</span>, <span class="fl">0.032</span>, <span class="fl">0.1</span>]:</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> np.linalg.solve(G2 <span class="op">+</span> lam <span class="op">*</span> np.eye(<span class="dv">2</span>), Z2.T <span class="op">@</span> yL <span class="op">/</span> m)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    longley[lam] <span class="op">=</span> b</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    rows.append({<span class="st">"$</span><span class="ch">\\</span><span class="st">lambda$"</span>: <span class="ss">f"</span><span class="sc">{</span>lam<span class="sc">:g}</span><span class="ss">"</span>, <span class="st">"GNP"</span>: <span class="ss">f"</span><span class="sc">{</span>b[<span class="dv">0</span>]<span class="sc">:,.0f}</span><span class="ss">"</span>, <span class="st">"Population"</span>: <span class="ss">f"</span><span class="sc">{</span>b[<span class="dv">1</span>]<span class="sc">:,.0f}</span><span class="ss">"</span>, <span class="st">"Sum"</span>: <span class="ss">f"</span><span class="sc">{</span>b<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:,.0f}</span><span class="ss">"</span>, <span class="st">"Difference"</span>: <span class="ss">f"</span><span class="sc">{</span>b[<span class="dv">0</span>] <span class="op">-</span> b[<span class="dv">1</span>]<span class="sc">:,.0f}</span><span class="ss">"</span>})</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>md(pd.DataFrame(rows), index<span class="op">=</span><span class="va">False</span>, colalign<span class="op">=</span>(<span class="st">"right"</span>,) <span class="op">*</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-longley" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-longley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Ridge coefficients for total employment (thousands) on standardised GNP and population, Longley data, as the penalty weight grows.
</figcaption>
<div aria-describedby="tbl-longley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="10">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(\lambda\)</span></th>
<th style="text-align: right;">GNP</th>
<th style="text-align: right;">Population</th>
<th style="text-align: right;">Sum</th>
<th style="text-align: right;">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">6,279</td>
<td style="text-align: right;">-2,850</td>
<td style="text-align: right;">3,429</td>
<td style="text-align: right;">9,129</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.001</td>
<td style="text-align: right;">5,818</td>
<td style="text-align: right;">-2,390</td>
<td style="text-align: right;">3,427</td>
<td style="text-align: right;">8,208</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">3,857</td>
<td style="text-align: right;">-445</td>
<td style="text-align: right;">3,412</td>
<td style="text-align: right;">4,301</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.032</td>
<td style="text-align: right;">2,681</td>
<td style="text-align: right;">693</td>
<td style="text-align: right;">3,375</td>
<td style="text-align: right;">1,988</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.1</td>
<td style="text-align: right;">2,006</td>
<td style="text-align: right;">1,259</td>
<td style="text-align: right;">3,265</td>
<td style="text-align: right;">747</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ul>
<li>The sum moves from 3,429 to 3,265 from the first row to the last.</li>
<li>The difference falls from 9,129 to 747.</li>
<li>Population’s coefficient turns positive between <span class="math inline">\(\lambda = 0.01\)</span> and <span class="math inline">\(\lambda = 0.032\)</span>.</li>
</ul>
<p>The sign of population’s coefficient is set by the penalty weight. Sixteen yearly figures in which GNP and population rose together cannot say what population does at fixed GNP, with a penalty or without one.</p>
</section>
</section>
<section id="other-approaches" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="other-approaches"><span class="header-section-number">6</span> Other approaches</h2>
<ul>
<li><strong>Drop a column.</strong> When one column is computed from others, as LDL is, remove it. On the diabetes data that took the standard deviation of total cholesterol’s coefficient from 18.4 to 5.4 at no cost in prediction. The coefficient that remains then describes that predictor with the dropped one free to vary alongside it.</li>
<li><strong>Combine columns.</strong> Replace a group by one index: an average, a ratio, a sum. This is PCR with the components chosen by subject knowledge.</li>
<li><strong>Collect rows that break the pattern.</strong> A designed experiment sets the predictors independently, and is the only item on this list that adds information about the weak direction.</li>
<li><strong>Partial least squares.</strong> Like PCR, but each component is chosen for its covariance with <span class="math inline">\(y\)</span>, which answers Jolliffe’s objection.</li>
<li><strong>An informative prior.</strong> Ridge is a prior centred on zero. A prior centred on a value from earlier studies puts outside knowledge into the weak direction explicitly.</li>
<li><strong>Centre before forming powers and products.</strong> <span class="math inline">\(x\)</span> and <span class="math inline">\(x^2\)</span> are nearly collinear when <span class="math inline">\(x\)</span> is far from zero: for 50 evenly spaced values from 10 to 20 their correlation is 0.996, and after centring <span class="math inline">\(x\)</span> it is 0.000. The fitted curve is the same either way. Centring changes which coefficients are asked for.</li>
<li><strong>Errors in the predictors.</strong> Part 1 showed that noise in <span class="math inline">\(X\)</span> is amplified by <span class="math inline">\(\kappa^2\)</span> when the residual is large. Total least squares models that noise; none of the penalties here do.</li>
<li><strong>Nothing.</strong> For predicting new rows that follow the training pattern, with enough rows, least squares on collinear predictors is already as accurate as any remedy.</li>
</ul>
</section>
<section id="choosing" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="choosing"><span class="header-section-number">7</span> Choosing</h2>
<div id="tbl-choosing" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-choosing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: A choice for each goal.
</figcaption>
<div aria-describedby="tbl-choosing-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Goal</th>
<th>Reasonable choice</th>
<th>What it will not give</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Predict rows like the training rows, many rows</td>
<td>least squares</td>
<td>interpretable coefficients inside the dependence</td>
</tr>
<tr class="even">
<td>Predict rows like the training rows, few rows</td>
<td>ridge or elastic net, tuned by cross-validation</td>
<td>interpretable coefficients inside the dependence</td>
</tr>
<tr class="odd">
<td>Predict rows that break the pattern</td>
<td>new data</td>
<td>a penalty cannot supply it</td>
</tr>
<tr class="even">
<td>Stable coefficients to report</td>
<td>drop or combine columns by subject knowledge; ridge or elastic net with a weight chosen for stability</td>
<td>an estimate of each predictor’s separate effect</td>
</tr>
<tr class="odd">
<td>A short list of predictors</td>
<td>elastic net; lasso only if the list need not be stable</td>
<td>evidence that the dropped predictors are irrelevant</td>
</tr>
<tr class="even">
<td>Many near-duplicate predictors, such as spectra</td>
<td>PCR or partial least squares</td>
<td>coefficients on the original columns that mean much</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A weight chosen for prediction and a weight chosen for stable coefficients are different weights. On the diabetes data cross-validation chose the first and left the coefficients unsettled.</p>
<p>Remedies. Assume. Ridge. Shrinks. Components. Delete. Lasso. Flips. Nets. Share. None. Recovers.</p>
</section>
<section id="references" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="references"><span class="header-section-number">8</span> References</h2>
<ul>
<li>Efron, B., Hastie, T., Johnstone, I., and Tibshirani, R. (2004). <a href="https://doi.org/10.1214/009053604000000067">Least angle regression</a>. <em>Annals of Statistics</em>, 32(2), 407–499.</li>
<li>Hoerl, A. E., and Kennard, R. W. (1970). Ridge regression: biased estimation for nonorthogonal problems. <em>Technometrics</em>, 12(1), 55–67.</li>
<li>Jolliffe, I. T. (1982). A note on the use of principal components in regression. <em>Journal of the Royal Statistical Society, Series C</em>, 31(3), 300–303.</li>
<li>Longley, J. W. (1967). An appraisal of least squares programs for the electronic computer from the point of view of the user. <em>Journal of the American Statistical Association</em>, 62(319), 819–841.</li>
<li>Tibshirani, R. (1996). Regression shrinkage and selection via the lasso. <em>Journal of the Royal Statistical Society, Series B</em>, 58(1), 267–288.</li>
<li>Zou, H., and Hastie, T. (2005). Regularization and variable selection via the elastic net. <em>Journal of the Royal Statistical Society, Series B</em>, 67(2), 301–320.</li>
<li><a href="../collinearity/">Collinearity, Part 1: The Direction the Data Cannot See</a>.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/project-delphi\.github\.io\/ml-blog\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Synthetic Musings, by Ravi Kalia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/collinearity-remedies/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>