<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-08-27">
<meta name="description" content="Golub’s 1999 leukemia data, run end to end: recovering the original train/test split from a CSV that lost its labels, fitting a gene signature without letting the test data leak in, and showing why the honest error rate is the hard one to get.">

<title>From Dataset to Biological Signature – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-54476ae42ce8ceac78673d28e233b15d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">From Dataset to Biological Signature</h1>
            <p class="subtitle lead">The same pipeline, told twice — once in the words a machine learning scientist would use, once in a statistician’s. They disagree about vocabulary and about nothing else: both are describing what happens when you let the data choose which genes to keep.</p>
                  <div>
        <div class="description">
          Golub’s 1999 leukemia data, run end to end: recovering the original train/test split from a CSV that lost its labels, fitting a gene signature without letting the test data leak in, and showing why the honest error rate is the hard one to get.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Genomics</div>
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Bioinformatics</div>
                <div class="quarto-category">Python</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 27, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#two-assembly-lines-and-a-glitch-on-one-of-them" id="toc-two-assembly-lines-and-a-glitch-on-one-of-them" class="nav-link active" data-scroll-target="#two-assembly-lines-and-a-glitch-on-one-of-them">Two assembly lines, and a glitch on one of them</a></li>
  <li><a href="#the-data-and-who-went-to-the-trouble-of-collecting-it" id="toc-the-data-and-who-went-to-the-trouble-of-collecting-it" class="nav-link" data-scroll-target="#the-data-and-who-went-to-the-trouble-of-collecting-it">The data, and who went to the trouble of collecting it</a></li>
  <li><a href="#the-file-on-hasties-server-holds-golubs-two-groups-stored-backwards" id="toc-the-file-on-hasties-server-holds-golubs-two-groups-stored-backwards" class="nav-link" data-scroll-target="#the-file-on-hasties-server-holds-golubs-two-groups-stored-backwards">The file on Hastie’s server holds Golub’s two groups, stored backwards</a></li>
  <li><a href="#for-the-ml-scientist-the-biology-is-all-upstream-of-the-matrix" id="toc-for-the-ml-scientist-the-biology-is-all-upstream-of-the-matrix" class="nav-link" data-scroll-target="#for-the-ml-scientist-the-biology-is-all-upstream-of-the-matrix">For the ML scientist: the biology is all upstream of the matrix</a></li>
  <li><a href="#for-the-statistician-the-data-chose-the-genes-and-every-number-remembers-that" id="toc-for-the-statistician-the-data-chose-the-genes-and-every-number-remembers-that" class="nav-link" data-scroll-target="#for-the-statistician-the-data-chose-the-genes-and-every-number-remembers-that">For the statistician: the data chose the genes, and every number remembers that</a>
  <ul class="collapse">
  <li><a href="#cheating-happens-by-default-because-the-gene-filter-looked-at-everything" id="toc-cheating-happens-by-default-because-the-gene-filter-looked-at-everything" class="nav-link" data-scroll-target="#cheating-happens-by-default-because-the-gene-filter-looked-at-everything">Cheating happens by default, because the gene filter looked at everything</a></li>
  <li><a href="#the-gene-list-is-one-draw-not-the-answer" id="toc-the-gene-list-is-one-draw-not-the-answer" class="nav-link" data-scroll-target="#the-gene-list-is-one-draw-not-the-answer">The gene list is one draw, not the answer</a></li>
  </ul></li>
  <li><a href="#closing-34-patients-cannot-tell-you-how-well-this-works" id="toc-closing-34-patients-cannot-tell-you-how-well-this-works" class="nav-link" data-scroll-target="#closing-34-patients-cannot-tell-you-how-well-this-works">Closing: 34 patients cannot tell you how well this works</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/dataset-to-biological-signature/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p><img src="./cover.png" class="img-fluid" alt="Cover card reading From Dataset to a Biological Signature, over a solid purple background."></p>
<p>Two acute leukemias arrive at the clinic looking much the same. Both fill the marrow with immature white cells, both make the patient acutely ill within weeks, and under a microscope the blasts of one can pass for the blasts of the other. They need opposite treatments. Get it wrong and you give a toxic regimen that will not work to someone who has a few weeks to spare.</p>
<p>Before 1999 that call was made by a blood specialist looking down a microscope at the shape of the cells, at how they took up various dyes, and at which proteins sat on their surface. It was good, and two hospitals could reach two answers. Golub and colleagues asked whether the cells’ gene activity could make the call on its own — and whether you could have found the two diseases in the data without being told they existed.</p>
<p>This post runs that question end to end, twice. The argument underneath it is one sentence: <strong>a signature only exists relative to a question you asked, and every number you attach to one is shaped by the fact that the data itself picked the genes.</strong> A machine learning scientist and a statistician say that in different words; both versions are here, and they are the same pipeline. For the concept without the code, <a href="../what-is-a-biological-signature/">What is a Biological Signature?</a> is the primer.</p>
<section id="two-assembly-lines-and-a-glitch-on-one-of-them" class="level3">
<h3 class="anchored" data-anchor-id="two-assembly-lines-and-a-glitch-on-one-of-them">Two assembly lines, and a glitch on one of them</h3>
<p>The biology is worth two minutes, because it turns out to be what the model recovers. Think of bone marrow as a factory with two assembly lines running from a single stem cell. The <strong>lymphoid</strong> line builds the immune system’s sharpshooters, B-cells and T-cells. The <strong>myeloid</strong> line builds everything else: red cells that carry oxygen, platelets that clot, and the white cells that do the frontline brawling.</p>
<p>An acute leukemia is a glitch that jams one line. The marrow fills with cells caught half-built — blasts — that will neither finish growing into anything useful nor stop dividing.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TD
  S["Bone marrow stem cell"] --&gt; L["Lymphoid line&lt;br/&gt;B-cells, T-cells"]
  S --&gt; M["Myeloid line&lt;br/&gt;red cells, platelets, granulocytes"]
  L --&gt;|glitch| ALL["&lt;b&gt;ALL&lt;/b&gt;&lt;br/&gt;lymphoblasts"]
  M --&gt;|glitch| AML["&lt;b&gt;AML&lt;/b&gt;&lt;br/&gt;myeloblasts"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Jam the lymphoid line and you get acute lymphoblastic leukemia, ALL — the commonest cancer of childhood. Jam the myeloid line and you get acute myeloid leukemia, AML, mostly an adult disease, and faster to strip out oxygen transport and clotting because the myeloid line covers more jobs.</p>
<p>So the diagnostic question has a clean biological shape: <em>which line is stuck?</em> Hold on to that. It is what the classifier ends up measuring.</p>
</section>
<section id="the-data-and-who-went-to-the-trouble-of-collecting-it" class="level3">
<h3 class="anchored" data-anchor-id="the-data-and-who-went-to-the-trouble-of-collecting-it">The data, and who went to the trouble of collecting it</h3>
<p>The measurements come from Golub et al.&nbsp;(1999) at the Whitehead Institute and Dana-Farber, who took marrow and blood from 72 acute leukemia patients and ran each sample over an Affymetrix HU6800 array: a glass chip carrying 7,129 tiny patches, each keyed to one gene. Sample material sticks to the patch that matches it and glows, so a bright spot means that gene was busy in that patient. They were not building a product; they pulled samples from hospital archives to argue that a tumour’s type is legible in gene activity at all.</p>
<p>A decision made from this analysis is a treatment assignment: vincristine and steroids for ALL, cytarabine and an anthracycline for AML, for a patient seriously ill either way. So the interesting number is not peak accuracy. It is how much of the accuracy survives being carried to a different hospital.</p>
<p>I use the copy on Efron and Hastie’s <em>Computer Age Statistical Inference</em> data page, cached in this post’s <code>data/</code> directory so the render never touches the network.</p>
<div id="setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Imports, plot style, and loading the cached matrices</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> beta</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>rng_seed <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figure.dpi"</span>: <span class="dv">150</span>, <span class="st">"savefig.bbox"</span>: <span class="st">"tight"</span>, <span class="st">"font.size"</span>: <span class="dv">9</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.top"</span>: <span class="va">False</span>, <span class="st">"axes.spines.right"</span>: <span class="va">False</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.grid"</span>: <span class="va">True</span>, <span class="st">"grid.alpha"</span>: <span class="fl">0.25</span>, <span class="st">"axes.axisbelow"</span>: <span class="va">True</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>ALL_C, AML_C <span class="op">=</span> <span class="st">"#1D5C6E"</span>, <span class="st">"#C98A12"</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="co"># The CASI matrix: 7,128 genes x 72 samples, column names carry the labels.</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>casi <span class="op">=</span> pd.read_csv(<span class="st">"data/leukemia_big.csv.gz"</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> casi.to_numpy().T                                    <span class="co"># samples x genes</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> np.array([<span class="bu">int</span>(c.split(<span class="st">"."</span>)[<span class="dv">0</span>].startswith(<span class="st">"AML"</span>)) <span class="cf">for</span> c <span class="kw">in</span> casi.columns])</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="co"># The original Whitehead files, used only as a key: they carry the Affymetrix</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="co"># probe accessions and the per-patient sample IDs that the CASI copy dropped.</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> read_golub(path):</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> pd.read_csv(path)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    ids <span class="op">=</span> [c <span class="cf">for</span> c <span class="kw">in</span> d.columns[<span class="dv">2</span>:] <span class="cf">if</span> <span class="kw">not</span> c.startswith(<span class="st">"call"</span>)]</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> d[<span class="st">"Gene Accession Number"</span>].to_numpy(), d[<span class="st">"Gene Description"</span>].to_numpy(), <span class="op">\</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>           d[ids].to_numpy(dtype<span class="op">=</span><span class="bu">float</span>), ids</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>acc, desc, G_train, id_train <span class="op">=</span> read_golub(<span class="st">"data/golub_train.csv.gz"</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>_, _, G_test, id_test <span class="op">=</span> read_golub(<span class="st">"data/golub_independent.csv.gz"</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>truth <span class="op">=</span> pd.read_csv(<span class="st">"data/golub_labels.csv"</span>).set_index(<span class="st">"patient"</span>)[<span class="st">"cancer"</span>].to_dict()</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"expression matrix : </span><span class="sc">{</span>X<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> samples x </span><span class="sc">{</span>X<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> genes"</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"class balance     : </span><span class="sc">{</span>(y<span class="op">==</span><span class="dv">0</span>)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> ALL, </span><span class="sc">{</span>y<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> AML"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>expression matrix : 72 samples x 7128 genes
class balance     : 47 ALL, 25 AML</code></pre>
</div>
</div>
<p>Seventy-two samples, 7,128 genes. That is a hundred times more things measured than people to measure them on, and every difficulty below follows from that one ratio.</p>
<div id="cell-slice" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>A corner of the matrix</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    X[:<span class="dv">5</span>, :<span class="dv">6</span>].<span class="bu">round</span>(<span class="dv">3</span>),</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    index<span class="op">=</span>[<span class="ss">f"sample </span><span class="sc">{</span>i<span class="sc">}</span><span class="ss"> (</span><span class="sc">{</span><span class="st">'AML'</span> <span class="cf">if</span> y[i] <span class="cf">else</span> <span class="st">'ALL'</span><span class="sc">}</span><span class="ss">)"</span> <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>)],</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    columns<span class="op">=</span>[<span class="ss">f"gene </span><span class="sc">{</span>j<span class="sc">}</span><span class="ss">"</span> <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">6</span>)],</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="slice" class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">gene 0</th>
<th data-quarto-table-cell-role="th">gene 1</th>
<th data-quarto-table-cell-role="th">gene 2</th>
<th data-quarto-table-cell-role="th">gene 3</th>
<th data-quarto-table-cell-role="th">gene 4</th>
<th data-quarto-table-cell-role="th">gene 5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">sample 0 (ALL)</td>
<td>-1.534</td>
<td>-1.236</td>
<td>-0.334</td>
<td>0.489</td>
<td>-1.301</td>
<td>-1.683</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">sample 1 (ALL)</td>
<td>-0.868</td>
<td>-1.276</td>
<td>0.376</td>
<td>0.444</td>
<td>-1.230</td>
<td>-1.642</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">sample 2 (ALL)</td>
<td>-0.433</td>
<td>-1.184</td>
<td>-0.459</td>
<td>0.436</td>
<td>-1.326</td>
<td>-1.407</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">sample 3 (ALL)</td>
<td>-1.672</td>
<td>-1.596</td>
<td>-1.423</td>
<td>0.193</td>
<td>-1.818</td>
<td>-1.744</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">sample 4 (ALL)</td>
<td>-1.188</td>
<td>-1.335</td>
<td>-0.797</td>
<td>0.236</td>
<td>-1.311</td>
<td>-1.654</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>These are not raw brightness readings. Each <em>column</em> — each patient — has been rescaled so their 7,128 values average zero with a spread of one, which puts every patient on the same footing however bright their chip came out. Something was done to each gene across patients too, but the file’s own documentation says that step is “lost in time”.</p>
</section>
<section id="the-file-on-hasties-server-holds-golubs-two-groups-stored-backwards" class="level2">
<h2 class="anchored" data-anchor-id="the-file-on-hasties-server-holds-golubs-two-groups-stored-backwards">The file on Hastie’s server holds Golub’s two groups, stored backwards</h2>
<p>Golub’s design had a feature that matters more than anything else here. The 72 samples are not one pool. Thirty-eight came from a single hospital, all bone marrow, and those built the predictor. The other 34 were collected later at different reference laboratories, prepared by different hands to different recipes, some of them blood rather than marrow. That second group differs from the training set in exactly the ways a new hospital would — which is the only kind of test set whose score is worth quoting.</p>
<p>The file I am using has no patient identifiers, so that split looks lost. It is recoverable, and worth recovering properly rather than guessing from class counts. Here is the lever: rescaling a patient’s column stretches and shifts their numbers but cannot reorder them, so the gene that was third-brightest before is third-brightest after. That surviving order is as good as a fingerprint. Replace every value by its rank within its column, then see which column of one file moves with which column of the other. Correlating ranks rather than values is what makes this a Spearman correlation.</p>
<div id="recover-split" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> np.hstack([G_train, G_test])[:X.shape[<span class="dv">1</span>]]   <span class="co"># CASI drops Golub's last probe</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>ids <span class="op">=</span> id_train <span class="op">+</span> id_test</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>golub_y <span class="op">=</span> np.array([<span class="bu">int</span>(truth[<span class="bu">int</span>(i)] <span class="op">==</span> <span class="st">"AML"</span>) <span class="cf">for</span> i <span class="kw">in</span> ids])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>rank <span class="op">=</span> <span class="kw">lambda</span> A: np.argsort(np.argsort(A, axis<span class="op">=</span><span class="dv">0</span>), axis<span class="op">=</span><span class="dv">0</span>).astype(<span class="bu">float</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>Rc, Rg <span class="op">=</span> rank(casi.to_numpy()), rank(G)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>Rc <span class="op">=</span> (Rc <span class="op">-</span> Rc.mean(<span class="dv">0</span>)) <span class="op">/</span> Rc.std(<span class="dv">0</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>Rg <span class="op">=</span> (Rg <span class="op">-</span> Rg.mean(<span class="dv">0</span>)) <span class="op">/</span> Rg.std(<span class="dv">0</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>S <span class="op">=</span> (Rc.T <span class="op">@</span> Rg) <span class="op">/</span> G.shape[<span class="dv">0</span>]                    <span class="co"># 72 x 72 Spearman matrix</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>match, best <span class="op">=</span> S.argmax(<span class="dv">1</span>), np.sort(S, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"unique matches      : </span><span class="sc">{</span><span class="bu">len</span>(<span class="bu">set</span>(match.tolist()))<span class="sc">}</span><span class="ss">/72"</span>)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"labels agree        : </span><span class="sc">{</span>(golub_y[match] <span class="op">==</span> y)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss">/72"</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"worst true match    : </span><span class="sc">{</span>best[:, <span class="op">-</span><span class="dv">1</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"best runner-up      : </span><span class="sc">{</span>best[:, <span class="op">-</span><span class="dv">2</span>]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"CASI column 0 -&gt; patient </span><span class="sc">{</span>ids[match[<span class="dv">0</span>]]<span class="sc">}</span><span class="ss">;  column 34 -&gt; patient </span><span class="sc">{</span>ids[match[<span class="dv">34</span>]]<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>unique matches      : 72/72
labels agree        : 72/72
worst true match    : 0.945
best runner-up      : 0.884
CASI column 0 -&gt; patient 39;  column 34 -&gt; patient 1</code></pre>
</div>
</div>
<p>Every column matches exactly one patient, none is claimed twice, and every recovered label agrees. The weakest true match scores 0.945 while the best wrong candidate anywhere reaches 0.884, so nothing here is close. It also settles the ordering: column 0 is patient 39 and column 34 is patient 1, so the file stores the <strong>34 outside samples first</strong>. Slice it at the front expecting training data and you get Golub’s held-out patients instead.</p>
<p>One caveat no amount of later care removes. That undocumented per-gene step may well have been computed across all 72 patients at once. Rescaling a patient’s own column is safe, since it only ever looks at itself; a step that pools every patient is not, because it lets the 34 test samples touch the training data before the split. Everything below is conditional on it.</p>
<div id="cell-fig-data" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Figure 1</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>test_ix, train_ix <span class="op">=</span> np.arange(<span class="dv">34</span>), np.arange(<span class="dv">34</span>, <span class="dv">72</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>probe <span class="op">=</span> {a: i <span class="cf">for</span> i, a <span class="kw">in</span> <span class="bu">enumerate</span>(acc[:X.shape[<span class="dv">1</span>]])}</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>mpo, ccnd3 <span class="op">=</span> probe[<span class="st">"M19507_at"</span>], probe[<span class="st">"M92287_at"</span>]</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>Z <span class="op">=</span> (X <span class="op">-</span> X.mean(<span class="dv">0</span>)) <span class="op">/</span> (X.std(<span class="dv">0</span>) <span class="op">+</span> <span class="fl">1e-9</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>U, sv, _ <span class="op">=</span> np.linalg.svd(Z <span class="op">-</span> Z.mean(<span class="dv">0</span>), full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>pcs <span class="op">=</span> U[:, :<span class="dv">5</span>] <span class="op">*</span> sv[:<span class="dv">5</span>]</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Pick the axes by what they actually carry, rather than assuming PC1/PC2:</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co"># correlate each component with class and with cohort membership.</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>cohort <span class="op">=</span> np.r_[np.zeros(<span class="dv">34</span>), np.ones(<span class="dv">38</span>)]</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>corr <span class="op">=</span> <span class="kw">lambda</span> v: np.array([<span class="bu">abs</span>(np.corrcoef(v, pcs[:, k])[<span class="dv">0</span>, <span class="dv">1</span>]) <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">5</span>)])</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>k_cls, k_coh <span class="op">=</span> corr(y).argmax(), corr(cohort).argmax()</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>fig, (a1, a2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">3.6</span>))</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cls, name, col <span class="kw">in</span> [(<span class="dv">0</span>, <span class="st">"ALL"</span>, ALL_C), (<span class="dv">1</span>, <span class="st">"AML"</span>, AML_C)]:</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> y <span class="op">==</span> cls</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    a1.scatter(X[m, ccnd3], X[m, mpo], c<span class="op">=</span>col, s<span class="op">=</span><span class="dv">28</span>, alpha<span class="op">=</span><span class="fl">0.85</span>, label<span class="op">=</span>name,</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>               edgecolor<span class="op">=</span><span class="st">"white"</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>a1.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"CCND3 (cyclin D3), lymphoid"</span>, ylabel<span class="op">=</span><span class="st">"MPO (myeloperoxidase), myeloid"</span>,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>       title<span class="op">=</span><span class="st">"Two genes"</span>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>a1.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cls, col <span class="kw">in</span> [(<span class="dv">0</span>, ALL_C), (<span class="dv">1</span>, AML_C)]:</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ix, mark, lab <span class="kw">in</span> [(train_ix, <span class="st">"o"</span>, <span class="st">"training"</span>), (test_ix, <span class="st">"^"</span>, <span class="st">"external"</span>)]:</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>        m <span class="op">=</span> np.intersect1d(np.flatnonzero(y <span class="op">==</span> cls), ix)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>        a2.scatter(pcs[m, k_cls], pcs[m, k_coh], c<span class="op">=</span>col, marker<span class="op">=</span>mark, s<span class="op">=</span><span class="dv">28</span>, alpha<span class="op">=</span><span class="fl">0.85</span>,</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>                   edgecolor<span class="op">=</span><span class="st">"white"</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>                   label<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span><span class="st">'AML'</span> <span class="cf">if</span> cls <span class="cf">else</span> <span class="st">'ALL'</span><span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>lab<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>a2.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="ss">f"PC</span><span class="sc">{</span>k_cls <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">  (carries class, |r| = </span><span class="sc">{</span>corr(y)[k_cls]<span class="sc">:.2f}</span><span class="ss">)"</span>,</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>       ylabel<span class="op">=</span><span class="ss">f"PC</span><span class="sc">{</span>k_coh <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">  (carries cohort, |r| = </span><span class="sc">{</span>corr(cohort)[k_coh]<span class="sc">:.2f}</span><span class="ss">)"</span>,</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>       title<span class="op">=</span><span class="st">"Colour = class, shape = cohort"</span>)</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>a2.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">7</span>, loc<span class="op">=</span><span class="st">"best"</span>)</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-data" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-data-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-data-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Left: two genes named later in the post, one myeloid and one lymphoid, separate the classes almost on their own. Right: the component that carries diagnosis plotted against the one that carries cohort. Class separates left-to-right and the laboratory separates bottom-to-top, on different axes — the nuisance variable has structure of its own.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Two hand-picked genes almost draw the line on their own, which tells you the signal here is unusually strong. Hold on to that when the error rates arrive.</p>
<p>The right panel is the warning attached to it. Take the cloud of patients in 7,128 dimensions and ask which single direction through it spreads them out most, then which does so among what is left, and so on; those directions are the principal components. Here the direction tracking the diagnosis and the direction tracking which of the two collection batches a sample belongs to are two <em>different</em> components. The batch is not a fog of random error over the disease signal — it is its own clean pattern at its own angle. Train a ridge classifier to guess only the batch, telling it nothing about the diagnosis, and cross-validation puts it at 78%. A model will learn that, because it is there to be learnt.</p>
</section>
<section id="for-the-ml-scientist-the-biology-is-all-upstream-of-the-matrix" class="level2">
<h2 class="anchored" data-anchor-id="for-the-ml-scientist-the-biology-is-all-upstream-of-the-matrix">For the ML scientist: the biology is all upstream of the matrix</h2>
<p><strong>What does the model actually see?</strong> A table: one row per patient, one column per gene, one number in each cell. Every piece of biology sits upstream of it — which patch stands for which gene, what to do with readings too dim or too bright to trust, how to put different chips on a comparable scale. All of it is specific to this assay and travels nowhere; redo the study on today’s sequencing and every choice changes, while the table coming out looks the same. After the table it is ordinary supervised learning. That lopsidedness is why genomics pipelines break when they are moved rather than when they are built.</p>
<p><strong>So is finding a signature supervised or unsupervised?</strong> Supervised, and worth saying flatly, because the field’s vocabulary blurs it. A signature is only defined against a question — sick or well, this tumour or that one. Take the labels away and the data still has structure, but structure is not a signature. It is a pattern that might be the disease, or the patients’ sex, or the laboratory, or the day the samples were run. Methods that work without labels do the supporting work, including the check that the biggest patterns are biology rather than paperwork — which is what the right panel was for.</p>
<p>There is a real exception, and Golub’s paper is why it is famous. Cluster first, find a grouping nobody had a name for, then treat those groups as if they were labels and go looking for what separates them. That is class <em>discovery</em>, and their paper did both halves. Discovery proposes the question; answering it is still supervised.</p>
<p><strong>What actually ships to a hospital?</strong> Not a model somebody keeps tuning: a fixed list of genes, a fixed weight for each, and a fixed cut-off, all locked before anyone opens the test set. Which is why the penalty below is set by testing inside the training data, never by trying values against the test set and keeping the best:</p>
<p><span class="math display">\[
\hat\beta \;=\; \arg\min_{\beta}\; -\frac{1}{n}\sum_{i=1}^{n}\Big[y_i\,x_i^{\top}\beta - \log\big(1 + e^{x_i^{\top}\beta}\big)\Big] \;+\; \lambda\Big(\alpha\lVert\beta\rVert_1 + \tfrac{1-\alpha}{2}\lVert\beta\rVert_2^2\Big)
\]</span></p>
<p>Read it as two demands pulling against each other. The first part rewards fitting the patients you have. The part after the plus sign charges for weight put on genes, in two currencies. The first, <span class="math inline">\(\lVert\beta\rVert_1\)</span>, charges by the plain size of a weight. That charge has a sharp corner at zero, and the corner is the whole point: it makes an exact zero the best answer for a gene even when some small non-zero weight would fit the patients slightly better. So genes drop out completely and a short list survives. The second, <span class="math inline">\(\lVert\beta\rVert_2^2\)</span>, charges by the <em>square</em> of a weight, which is smooth at zero and so shrinks weights without ever quite reaching it. What it does instead is punish one big weight far more than two medium ones, so genes that rise and fall together end up sharing the credit rather than one being kept at random and its twins discarded. Together they are the elastic net. Fixing <span class="math inline">\(\alpha = 0.5\)</span> keeps both charges in play and leaves a single dial: <span class="math inline">\(\lambda\)</span>, how expensive genes are in total.</p>
<p>Setting that dial needs care, because data used to choose it has helped build the model and can no longer judge it. So choosing and judging get separate patients. Split the 38 into five groups; hold one out; inside the other four run a smaller split that tries each candidate penalty and keeps the winner. (The code and the figure below turn the dial by its reciprocal, <span class="math inline">\(C\)</span>, so larger <span class="math inline">\(C\)</span> means a <em>weaker</em> penalty.) Only then is the held-out group spent, scoring a model whose dial it had no hand in setting. Rotate through all five and average. An inner loop that chooses, an outer loop that scores: nested cross-validation.</p>
<div id="cell-fig-path" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Nested cross-validation, and Figure 2</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> StratifiedKFold, cross_val_score</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, roc_auc_score, brier_score_loss</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>Xtr, ytr, Xte, yte <span class="op">=</span> X[train_ix], y[train_ix], X[test_ix], y[test_ix]</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>Cs <span class="op">=</span> np.logspace(<span class="op">-</span><span class="dv">2</span>, <span class="dv">1</span>, <span class="dv">7</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> enet(C):</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> LogisticRegression(penalty<span class="op">=</span><span class="st">"elasticnet"</span>, solver<span class="op">=</span><span class="st">"saga"</span>, l1_ratio<span class="op">=</span><span class="fl">0.5</span>,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>                              C<span class="op">=</span>C, max_iter<span class="op">=</span><span class="dv">3000</span>, tol<span class="op">=</span><span class="fl">1e-3</span>, random_state<span class="op">=</span>rng_seed)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> screen(A, k<span class="op">=</span><span class="dv">2000</span>):</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Unsupervised variance screen. Never sees y, so it is safe inside a fold."""</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.argsort(<span class="op">-</span>A.var(<span class="dv">0</span>))[:k]</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>outer, scores <span class="op">=</span> StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">0</span>), []</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> a, b <span class="kw">in</span> outer.split(Xtr, ytr):</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    g <span class="op">=</span> screen(Xtr[a])</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    mu, sd <span class="op">=</span> Xtr[a][:, g].mean(<span class="dv">0</span>), Xtr[a][:, g].std(<span class="dv">0</span>) <span class="op">+</span> <span class="fl">1e-9</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    Za, Zb <span class="op">=</span> (Xtr[a][:, g] <span class="op">-</span> mu) <span class="op">/</span> sd, (Xtr[b][:, g] <span class="op">-</span> mu) <span class="op">/</span> sd</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    inner <span class="op">=</span> StratifiedKFold(<span class="dv">4</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    C <span class="op">=</span> <span class="bu">max</span>(Cs, key<span class="op">=</span><span class="kw">lambda</span> c: cross_val_score(enet(c), Za, ytr[a], cv<span class="op">=</span>inner).mean())</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    scores.append(accuracy_score(ytr[b], enet(C).fit(Za, ytr[a]).predict(Zb)))</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Full-training-set path, for the figure and for the final penalty.</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> screen(Xtr)</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>mu, sd <span class="op">=</span> Xtr[:, g].mean(<span class="dv">0</span>), Xtr[:, g].std(<span class="dv">0</span>) <span class="op">+</span> <span class="fl">1e-9</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>Ztr, Zte <span class="op">=</span> (Xtr[:, g] <span class="op">-</span> mu) <span class="op">/</span> sd, (Xte[:, g] <span class="op">-</span> mu) <span class="op">/</span> sd</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>cv5 <span class="op">=</span> StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>path <span class="op">=</span> np.array([cross_val_score(enet(c), Ztr, ytr, cv<span class="op">=</span>cv5) <span class="cf">for</span> c <span class="kw">in</span> Cs])</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>C_star <span class="op">=</span> Cs[path.mean(<span class="dv">1</span>).argmax()]</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"nested CV accuracy : </span><span class="sc">{</span>np<span class="sc">.</span>mean(scores)<span class="sc">:.3f}</span><span class="ss">  (outer folds "</span></span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>[<span class="bu">round</span>(s, <span class="dv">2</span>) <span class="cf">for</span> s <span class="kw">in</span> scores]<span class="sc">}</span><span class="ss">)"</span>)</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="fl">3.2</span>))</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>ax.errorbar(Cs, path.mean(<span class="dv">1</span>), yerr<span class="op">=</span>path.std(<span class="dv">1</span>), marker<span class="op">=</span><span class="st">"o"</span>, color<span class="op">=</span>ALL_C,</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>            capsize<span class="op">=</span><span class="dv">3</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>, markersize<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>ax.axvline(C_star, color<span class="op">=</span>AML_C, linestyle<span class="op">=</span><span class="st">"--"</span>, linewidth<span class="op">=</span><span class="fl">1.3</span>,</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f"chosen C = </span><span class="sc">{</span>C_star<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xscale<span class="op">=</span><span class="st">"log"</span>, xlabel<span class="op">=</span><span class="st">"C  (inverse penalty strength)"</span>,</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>       ylabel<span class="op">=</span><span class="st">"inner-fold accuracy"</span>, title<span class="op">=</span><span class="st">"Regularisation path"</span>)</span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb7-44"><a href="#cb7-44" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>nested CV accuracy : 0.921  (outer folds [0.75, 1.0, 1.0, 0.86, 1.0])</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-path" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-path-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-path-output-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-path-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Inner-fold accuracy along the regularisation path, on the 38 training samples only. Accuracy peaks at a single interior value. To the left the penalty is strong enough to zero out genes the model needs; to the right it is weak enough to admit genes that only help on the training fold. Error bars are one standard deviation across five folds, and they are wide — 38 samples do not locate this optimum precisely.
</figcaption>
</figure>
</div>
</div>
</div>
<p>That two-loop procedure puts the predictor at 0.921 accuracy on the training patients. Now lock the gene list, the weights and the cut-off, and open the 34 outside samples — once.</p>
<div id="external" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>final <span class="op">=</span> enet(C_star).fit(Ztr, ytr)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>selected <span class="op">=</span> g[np.flatnonzero(final.coef_[<span class="dv">0</span>])]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>p_test <span class="op">=</span> final.predict_proba(Zte)[:, <span class="dv">1</span>]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"genes with non-zero coefficient : </span><span class="sc">{</span><span class="bu">len</span>(selected)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"external accuracy : </span><span class="sc">{</span>accuracy_score(yte, p_test <span class="op">&gt;</span> <span class="fl">0.5</span>)<span class="sc">:.3f}</span><span class="ss"> "</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(</span><span class="sc">{</span><span class="bu">int</span>((( p_test <span class="op">&gt;</span> <span class="fl">0.5</span>) <span class="op">==</span> yte).<span class="bu">sum</span>())<span class="sc">}</span><span class="ss">/34)"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"external AUC      : </span><span class="sc">{</span>roc_auc_score(yte, p_test)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"external Brier    : </span><span class="sc">{</span>brier_score_loss(yte, p_test)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>wrong <span class="op">=</span> np.flatnonzero((p_test <span class="op">&gt;</span> <span class="fl">0.5</span>).astype(<span class="bu">int</span>) <span class="op">!=</span> yte)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"the one error     : predicted p(AML) = </span><span class="sc">{</span>p_test[wrong][<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>genes with non-zero coefficient : 88
external accuracy : 0.971 (33/34)
external AUC      : 1.000
external Brier    : 0.041
the one error     : predicted p(AML) = 0.468</code></pre>
</div>
</div>
<p><strong>What did it find?</strong> Thirty-three of the 34 outside samples correct. The AUC of 1.000 says that given any AML patient and any ALL patient, the model always gives the AML patient the higher probability: it ranks all 34 correctly, even though the cut-off at 0.5 converts one of those rankings into a wrong answer. The Brier score averages the <em>squared</em> gap between each quoted probability and what actually happened, and squaring is what makes a confident mistake cost far more than a hesitant one. The single error sits at <span class="math inline">\(p = 0.468\)</span>, three hundredths on the wrong side of the line — the model was almost exactly undecided.</p>
<p>Note which way the gap runs. The training-only estimate said 0.921 and the outside cohort delivered 0.971, so the internal number <em>understated</em> how well the model travelled — the opposite of the failure everyone is trained to expect.</p>
<p>The gene list is what closes the loop back to the marrow.</p>
<div id="lineage" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Naming the selected genes</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>lineage <span class="op">=</span> {</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"M19507_at"</span>: <span class="st">"MPO, myeloperoxidase — the granulocyte enzyme"</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"M23197_at"</span>: <span class="st">"CD33 — myeloid surface antigen"</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"X52056_at"</span>: <span class="st">"SPI1 / PU.1 — myeloid master transcription factor"</span>,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"M84526_at"</span>: <span class="st">"DF, adipsin — Golub's AML-high list"</span>,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"M27891_at"</span>: <span class="st">"CST3, cystatin C — Golub's AML-high list"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"M92287_at"</span>: <span class="st">"CCND3, cyclin D3 — Golub's ALL-high list"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"U05259_rna1_at"</span>: <span class="st">"MB-1 / CD79a — B-cell receptor component"</span>,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">"M31523_at"</span>: <span class="st">"TCF3 / E2A — required for B-cell development"</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>hits <span class="op">=</span> [(acc[i], lineage[acc[i]]) <span class="cf">for</span> i <span class="kw">in</span> selected <span class="cf">if</span> acc[i] <span class="kw">in</span> lineage]</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> a, note <span class="kw">in</span> hits:</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>a<span class="sc">:16s}</span><span class="ss"> </span><span class="sc">{</span>note<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span><span class="bu">len</span>(hits)<span class="sc">}</span><span class="ss"> of these annotated markers survived selection."</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  M27891_at        CST3, cystatin C — Golub's AML-high list
  X52056_at        SPI1 / PU.1 — myeloid master transcription factor
  M84526_at        DF, adipsin — Golub's AML-high list
  M19507_at        MPO, myeloperoxidase — the granulocyte enzyme
  U05259_rna1_at   MB-1 / CD79a — B-cell receptor component
  M23197_at        CD33 — myeloid surface antigen
  M92287_at        CCND3, cyclin D3 — Golub's ALL-high list

7 of these annotated markers survived selection.</code></pre>
</div>
</div>
<p>Myeloid markers on one side, lymphoid on the other. The model is reading out which assembly line is stuck: it has rediscovered the question the biology poses, rather than memorising 72 patients. And among the genes it keeps is myeloperoxidase — the very enzyme the pre-1999 laboratory stain tested for. The gene activity arrives at the specialist’s own marker from the other direction.</p>
<p>That is the optimistic reading. The next section runs the same pipeline and asks what those numbers are estimates <em>of</em>.</p>
</section>
<section id="for-the-statistician-the-data-chose-the-genes-and-every-number-remembers-that" class="level2">
<h2 class="anchored" data-anchor-id="for-the-statistician-the-data-chose-the-genes-and-every-number-remembers-that">For the statistician: the data chose the genes, and every number remembers that</h2>
<p>Describe the same job in a statistician’s words and the difficulty changes shape. Statisticians write that hundred-to-one ratio as <span class="math inline">\(p \gg n\)</span> — far more things measured than subjects to measure them on — and add a bet that only a handful of the 7,128 matter. The procedure then has to do two jobs at once: pick the handful, and report a weight for each one it picked. Those jobs cannot be separated, and the second inherits everything the first did.</p>
<p>That is why the usual confidence interval around a selected gene’s weight means nothing. Such an interval assumes the gene was named in advance. This one is in the list <em>because</em> it looked good in these 38 patients — it won a contest against 7,127 rivals, and some of why it won is luck that will not repeat. Quote the interval anyway and it comes out too narrow, the p-value beside it too small. Three honest repairs exist: choose genes on one half of the patients and do all inference on the half never consulted; work out what winning the contest does to the numbers and correct for it, which is selective inference; or run fake genes that imitate the real correlation structure but are known to be unrelated to the disease through the same contest, and count how often a fake wins — knockoffs.</p>
<p>Then there is the sheer number of tests. Run 7,128 comparisons at the usual 5% threshold and about 356 genes clear it by chance alone. The reflex fix — demand a far stricter threshold on each test — throws away almost every real finding along with the false ones at this scale. The guarantee people use instead is the false discovery rate: not “how likely am I to make even one mistake”, but “of the genes I report, what fraction should I expect to be wrong”,</p>
<p><span class="math display">\[
\mathrm{FDR} \;=\; \mathbb{E}\!\left[\frac{V}{\max(R, 1)}\right],
\]</span></p>
<p>where <span class="math inline">\(R\)</span> counts the genes you reported and <span class="math inline">\(V\)</span> counts how many of those were wrong. Setting that expected fraction to, say, 10% is a workable promise: a tenth of your list is junk, on average, and you proceed knowing it.</p>
<p>The trouble is the phrase <em>on average</em>. Genes do not act independently; they come in gangs that switch on and off together, so one upstream event drags fifty along and the number of genuinely separate questions is far below 7,128. Benjamini–Hochberg still delivers its long-run promise under that kind of correlation. But the fraction you get <em>this time</em> swings widely around it, precisely because genes move in gangs — one gang going wrong takes fifty entries with it. You can control the average perfectly and still hold a badly wrong list today.</p>
<p>Stated as stages, the pipeline the section above ran informally is:</p>
<ol type="1">
<li>Decide what you are estimating, and where the cut-off goes, before looking.</li>
<li>Split the data before any transformation touches it.</li>
<li>Fit rescaling and any gene filter on training data only, inside each fold.</li>
<li>Choose the penalty in an inner loop; measure performance in an outer one.</li>
<li>Check the gene set is stable, not merely best on one draw.</li>
<li>Lock the weights and cut-off, test outside once, and report intervals and how truthful the probabilities were — not one bare accuracy figure.</li>
</ol>
<p>Step 3 is the one usually violated, and the violation is almost never deliberate.</p>
<section id="cheating-happens-by-default-because-the-gene-filter-looked-at-everything" class="level3">
<h3 class="anchored" data-anchor-id="cheating-happens-by-default-because-the-gene-filter-looked-at-everything">Cheating happens by default, because the gene filter looked at everything</h3>
<p>The natural way to handle 7,128 genes is to score each on how cleanly it separates ALL from AML, keep the best 50, and cross-validate on those. It feels safe: inside the loop the model only ever trains on the training fold. But the scoring step ran once, over all the data, before the loop started. So the fold you are holding back already had a vote in choosing the genes it is about to score. Information has leaked across the split, which is why this is called leakage. Ambroise and McLachlan named it in 2002, and it reproduces in a few lines.</p>
<div id="leakage" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> top_genes(A, lab, k<span class="op">=</span><span class="dv">50</span>):</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    m0, m1 <span class="op">=</span> A[lab <span class="op">==</span> <span class="dv">0</span>].mean(<span class="dv">0</span>), A[lab <span class="op">==</span> <span class="dv">1</span>].mean(<span class="dv">0</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    se <span class="op">=</span> np.sqrt(A[lab <span class="op">==</span> <span class="dv">0</span>].var(<span class="dv">0</span>) <span class="op">/</span> (lab <span class="op">==</span> <span class="dv">0</span>).<span class="bu">sum</span>()</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                 <span class="op">+</span> A[lab <span class="op">==</span> <span class="dv">1</span>].var(<span class="dv">0</span>) <span class="op">/</span> lab.<span class="bu">sum</span>()) <span class="op">+</span> <span class="fl">1e-9</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.argsort(<span class="op">-</span>np.<span class="bu">abs</span>((m1 <span class="op">-</span> m0) <span class="op">/</span> se))[:k]</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> two_ways(lab, cv<span class="op">=</span>StratifiedKFold(<span class="dv">10</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">7</span>)):</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    once <span class="op">=</span> cross_val_score(enet(<span class="fl">1.0</span>), Z[:, top_genes(Z, lab)], lab, cv<span class="op">=</span>cv).mean()</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    fold <span class="op">=</span> [accuracy_score(lab[b], enet(<span class="fl">1.0</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>            .fit(Z[a][:, (gi <span class="op">:=</span> top_genes(Z[a], lab[a]))], lab[a])</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>            .predict(Z[b][:, gi])) <span class="cf">for</span> a, b <span class="kw">in</span> cv.split(Z, lab)]</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">1</span> <span class="op">-</span> once, <span class="dv">1</span> <span class="op">-</span> np.mean(fold)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>opt, honest <span class="op">=</span> two_ways(y)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"real labels     : filter once </span><span class="sc">{</span>opt<span class="sc">:.1%}</span><span class="ss"> error | filter in fold </span><span class="sc">{</span>honest<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>shuffled <span class="op">=</span> np.random.default_rng(<span class="dv">3</span>).permutation(y)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>opt_n, honest_n <span class="op">=</span> two_ways(shuffled)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"labels shuffled : filter once </span><span class="sc">{</span>opt_n<span class="sc">:.1%}</span><span class="ss"> error | filter in fold </span><span class="sc">{</span>honest_n<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"chance for this class balance : </span><span class="sc">{</span>(y <span class="op">==</span> <span class="dv">0</span>)<span class="sc">.</span>mean()<span class="sc">:.1%}</span><span class="ss"> correct by always saying ALL"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>real labels     : filter once 2.9% error | filter in fold 4.3%
labels shuffled : filter once 7.0% error | filter in fold 33.2%
chance for this class balance : 65.3% correct by always saying ALL</code></pre>
</div>
</div>
<p>On the real labels the gap is small — 2.9% error the cheating way against 4.3% done properly — and that is the honest result, not a failed demonstration. The ALL/AML difference is so stark that cheating has almost nothing left to add.</p>
<p>The second line is the demonstration. Shuffle the labels so there is genuinely nothing to find, and picking the genes once over the whole dataset reports 7.0% error — 93% accuracy on pure noise. Pick inside each fold instead and the error climbs to 33.2%, about what you get by ignoring the data and calling everyone ALL — the cell prints that as 65.3% correct, which is 34.7% error. So the flattery is not a small bias that shrinks with the signal. With nothing there, the flattery is the whole number: invisible when you do not need the estimate, catastrophic when you do.</p>
</section>
<section id="the-gene-list-is-one-draw-not-the-answer" class="level3">
<h3 class="anchored" data-anchor-id="the-gene-list-is-one-draw-not-the-answer">The gene list is one draw, not the answer</h3>
<p>Being the best list for these 38 patients is not the same as being a list that would come back if you ran the study again. There is a cheap way to tell the difference. Take a random half of the training patients, fit the model, note which genes survived, then draw another random half — a hundred times. A gene picked for a real biological reason keeps reappearing; a gene picked because it flattered one particular set of patients does not. Counting those reappearances is stability selection.</p>
<div id="cell-fig-stability" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Stability selection, and Figure 3</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(rng_seed)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>freq, B <span class="op">=</span> np.zeros(X.shape[<span class="dv">1</span>]), <span class="dv">100</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>pool <span class="op">=</span> screen(Xtr)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(B):</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    take <span class="op">=</span> rng.choice(<span class="bu">len</span>(ytr), <span class="bu">len</span>(ytr) <span class="op">//</span> <span class="dv">2</span>, replace<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">len</span>(np.unique(ytr[take])) <span class="op">&lt;</span> <span class="dv">2</span>:</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">continue</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    A <span class="op">=</span> Xtr[take][:, pool]</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    A <span class="op">=</span> (A <span class="op">-</span> A.mean(<span class="dv">0</span>)) <span class="op">/</span> (A.std(<span class="dv">0</span>) <span class="op">+</span> <span class="fl">1e-9</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    freq[pool[np.flatnonzero(enet(<span class="fl">0.5</span>).fit(A, ytr[take]).coef_[<span class="dv">0</span>])]] <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>freq <span class="op">/=</span> B</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>order <span class="op">=</span> np.argsort(<span class="op">-</span>freq)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t <span class="kw">in</span> (<span class="fl">0.5</span>, <span class="fl">0.6</span>, <span class="fl">0.7</span>, <span class="fl">0.9</span>):</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"selection frequency &gt;= </span><span class="sc">{</span>t<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>(freq <span class="op">&gt;=</span> t)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> genes"</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">3.4</span>))</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>top <span class="op">=</span> order[:<span class="dv">60</span>]</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>ax.bar(<span class="bu">range</span>(<span class="bu">len</span>(top)), freq[top], color<span class="op">=</span>ALL_C, width<span class="op">=</span><span class="fl">0.8</span>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.6</span>, color<span class="op">=</span>AML_C, linestyle<span class="op">=</span><span class="st">"--"</span>, linewidth<span class="op">=</span><span class="fl">1.3</span>, label<span class="op">=</span><span class="st">"cutoff = 0.6"</span>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>above <span class="op">=</span> <span class="bu">int</span>((freq[top] <span class="op">&gt;=</span> <span class="fl">0.6</span>).<span class="bu">sum</span>())</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(<span class="bu">range</span>(above))</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>ax.set_xticklabels([acc[i] <span class="cf">for</span> i <span class="kw">in</span> top[:above]], rotation<span class="op">=</span><span class="dv">90</span>, fontsize<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>ax.<span class="bu">set</span>(xlim<span class="op">=</span>(<span class="op">-</span><span class="dv">1</span>, <span class="bu">len</span>(top)), ylabel<span class="op">=</span><span class="st">"selection frequency"</span>,</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>       xlabel<span class="op">=</span><span class="st">"genes, ranked"</span>, title<span class="op">=</span><span class="ss">f"</span><span class="sc">{</span>B<span class="sc">}</span><span class="ss"> half-samples of the 38 training patients"</span>)</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>selection frequency &gt;= 0.5: 45 genes
selection frequency &gt;= 0.6: 33 genes
selection frequency &gt;= 0.7: 26 genes
selection frequency &gt;= 0.9: 12 genes</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-stability" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-stability-output-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stability-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Selection frequency across 100 half-samples of the training cohort, sorted. The dashed line is a 0.6 cutoff. Genes above it are labelled by Affymetrix probe.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Forty-five genes turn up in at least half the draws, and only 12 in nine draws out of ten. So the 88-gene list is not a single settled object. Most of its members could be swapped for a neighbour that rises and falls with them, and a different 38 patients would have handed back a visibly different list with much the same accuracy.</p>
<p>That wobble is not something the elastic net introduced. Rebuild Golub’s own 50-gene predictor with the score from his paper — the gap between the two group averages divided by how much the groups scatter, <span class="math inline">\(P(g,c) = (\mu_1 - \mu_0)/(\sigma_1 +
\sigma_0)\)</span> — then compute the identical score after the tidying step his methods section mentions in passing: pull readings below 100 up to 100 and above 16,000 down to 16,000, then take logarithms.</p>
<div id="golub50" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Reconstructing the 1999 predictor</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> snr(A, lab):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> A[lab <span class="op">==</span> <span class="dv">1</span>].mean(<span class="dv">0</span>) <span class="op">-</span> A[lab <span class="op">==</span> <span class="dv">0</span>].mean(<span class="dv">0</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> d <span class="op">/</span> (A[lab <span class="op">==</span> <span class="dv">1</span>].std(<span class="dv">0</span>, ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">+</span> A[lab <span class="op">==</span> <span class="dv">0</span>].std(<span class="dv">0</span>, ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">+</span> <span class="fl">1e-12</span>)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>raw <span class="op">=</span> G_train.T</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>P_raw <span class="op">=</span> snr(raw, golub_y[:<span class="dv">38</span>])</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>P_log <span class="op">=</span> snr(np.log10(np.clip(raw, <span class="dv">100</span>, <span class="dv">16000</span>)), golub_y[:<span class="dv">38</span>])</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>fifty <span class="op">=</span> <span class="kw">lambda</span> P: <span class="bu">set</span>(np.argsort(<span class="op">-</span>P)[:<span class="dv">25</span>]) <span class="op">|</span> <span class="bu">set</span>(np.argsort(P)[:<span class="dv">25</span>])</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>g50_raw, g50_log <span class="op">=</span> fifty(P_raw), fifty(P_log)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Golub-50, raw vs his own log10 preprocessing : </span><span class="sc">{</span><span class="bu">len</span>(g50_raw <span class="op">&amp;</span> g50_log)<span class="sc">}</span><span class="ss">/50 shared"</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"elastic net set vs Golub-50 (log10)         : "</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(<span class="bu">set</span>(selected) <span class="op">&amp;</span> g50_log)<span class="sc">}</span><span class="ss"> of 50 genes in common"</span>)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"top AML-high probes:"</span>,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>      <span class="st">", "</span>.join(acc[i] <span class="cf">for</span> i <span class="kw">in</span> np.argsort(<span class="op">-</span>P_log)[:<span class="dv">4</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Golub-50, raw vs his own log10 preprocessing : 32/50 shared
elastic net set vs Golub-50 (log10)         : 26 of 50 genes in common
top AML-high probes: M27891_at, X95735_at, U50136_rna1_at, M23197_at</code></pre>
</div>
</div>
<p>His top 50 changes by 18 genes on that one choice, with the patients, the data and the scoring rule all held fixed. Against that backdrop the elastic net agreeing with him on 26 of 50 is neither a failure to replicate nor a confirmation — it is what two reasonable ways of choosing agree on when the thing chosen is this wobbly. The gene list is an estimate, like an average or a slope, and estimates come with a spread.</p>
</section>
</section>
<section id="closing-34-patients-cannot-tell-you-how-well-this-works" class="level2">
<h2 class="anchored" data-anchor-id="closing-34-patients-cannot-tell-you-how-well-this-works">Closing: 34 patients cannot tell you how well this works</h2>
<p>The outside cohort did what it was supposed to do. Collected somewhere else, prepared differently, and including a tissue the training set never contained — and the locked model still got 33 of 34 right. That is a real result, and Golub designing that split in advance is why it means anything at all.</p>
<p>But 34 is 34.</p>
<div id="closing" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Intervals, and what happens at a different prevalence</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> wilson(k, n, z<span class="op">=</span><span class="fl">1.96</span>):</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>    c <span class="op">=</span> (k <span class="op">/</span> n <span class="op">+</span> z <span class="op">*</span> z <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> n)) <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> z <span class="op">*</span> z <span class="op">/</span> n)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    h <span class="op">=</span> z <span class="op">*</span> np.sqrt(k <span class="op">/</span> n <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> k <span class="op">/</span> n) <span class="op">/</span> n <span class="op">+</span> z <span class="op">*</span> z <span class="op">/</span> (<span class="dv">4</span> <span class="op">*</span> n <span class="op">*</span> n)) <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> z <span class="op">*</span> z <span class="op">/</span> n)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> c <span class="op">-</span> h, c <span class="op">+</span> h</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"external accuracy 33/34   : 95% CI [</span><span class="sc">{</span>wilson(<span class="dv">33</span>, <span class="dv">34</span>)[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>wilson(<span class="dv">33</span>, <span class="dv">34</span>)[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">]"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"nested CV, 35/38          : 95% CI [</span><span class="sc">{</span>wilson(<span class="dv">35</span>, <span class="dv">38</span>)[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>wilson(<span class="dv">35</span>, <span class="dv">38</span>)[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">]"</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>sens, fpr_hi <span class="op">=</span> <span class="dv">13</span> <span class="op">/</span> <span class="dv">14</span>, beta.ppf(<span class="fl">0.975</span>, <span class="dv">1</span>, <span class="dv">20</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">specificity 20/20, but 95% upper bound on the false-positive rate: </span><span class="sc">{</span>fpr_hi<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> prev, where <span class="kw">in</span> [(<span class="fl">0.35</span>, <span class="st">"suspected leukemia at referral"</span>), (<span class="fl">0.02</span>, <span class="st">"a broader haematology clinic"</span>)]:</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>    ppv <span class="op">=</span> sens <span class="op">*</span> prev <span class="op">/</span> (sens <span class="op">*</span> prev <span class="op">+</span> fpr_hi <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> prev))</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  prevalence </span><span class="sc">{</span>prev<span class="sc">:&gt;5.0%}</span><span class="ss"> (</span><span class="sc">{</span>where<span class="sc">}</span><span class="ss">): PPV could be as low as </span><span class="sc">{</span>ppv<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>external accuracy 33/34   : 95% CI [0.851, 0.995]
nested CV, 35/38          : 95% CI [0.792, 0.973]

specificity 20/20, but 95% upper bound on the false-positive rate: 0.168
  prevalence   35% (suspected leukemia at referral): PPV could be as low as 0.75
  prevalence    2% (a broader haematology clinic): PPV could be as low as 0.10</code></pre>
</div>
</div>
<p>Thirty-three out of 34 is 0.971, but the honest range around it — the set of true accuracies that could plausibly have produced this result — runs from 0.851 to 0.995. A model that really gets 30 of 34 right would look no different on evidence this thin.</p>
<p>The same thinness hides on the other side. The model never once called an ALL patient AML — 20 out of 20 — which looks like perfection. But no mistakes in twenty attempts is still consistent with a true error rate near 17%, and that bound is what travels. Push it through the arithmetic of who is being tested. Among patients already referred with suspected leukemia, about a third of whom have AML, a positive call is right roughly three times in four. Take the same model to a broader haematology clinic where only one leukemia patient in fifty has AML, and it is right about one time in ten — most of its positive answers now wrong, because nearly everyone it meets has the other disease. Note what this arithmetic does <em>not</em> cover. Every error rate here was measured on people who already had one of these two leukemias, so none of it says what the model would do when handed someone who has neither.</p>
<p>Which returns to the sentence at the top. A signature is defined against a question, and also against the population you asked it in. Accuracy is not a property of the model. It is a property of the model pointed at a particular group of people. Golub’s predictor answers “which of these two leukemias does this patient have” for a patient who already has one of them. Point it at a population where AML is rare and the arithmetic above, not the classifier, decides what it is worth.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p><strong>Biology and genomics</strong></p>
<ul>
<li>Golub, T. R. et al.&nbsp;(1999). Molecular classification of cancer: class discovery and class prediction by gene expression monitoring. <em>Science</em> 286:531–537.</li>
<li>Alizadeh, A. A. et al.&nbsp;(2000). Distinct types of diffuse large B-cell lymphoma identified by gene expression profiling. <em>Nature</em> 403:503–511.</li>
<li>van ’t Veer, L. J. et al.&nbsp;(2002). Gene expression profiling predicts clinical outcome of breast cancer. <em>Nature</em> 415:530–536.</li>
<li>Subramanian, A. et al.&nbsp;(2005). Gene set enrichment analysis: a knowledge-based approach for interpreting genome-wide expression profiles. <em>PNAS</em> 102:15545–15550.</li>
<li>Leek, J. T. et al.&nbsp;(2010). Tackling the widespread and critical impact of batch effects in high-throughput data. <em>Nature Reviews Genetics</em> 11:733–739.</li>
<li>Whalen, S. et al.&nbsp;(2022). Navigating the pitfalls of applying machine learning in genomics. <em>Nature Reviews Genetics</em> 23:169–181.</li>
</ul>
<p><strong>Statistics and machine learning</strong></p>
<ul>
<li>Tibshirani, R. (1996). Regression shrinkage and selection via the lasso. <em>JRSS-B</em> 58:267–288.</li>
<li>Benjamini, Y. &amp; Hochberg, Y. (1995). Controlling the false discovery rate: a practical and powerful approach to multiple testing. <em>JRSS-B</em> 57:289–300.</li>
<li>Zou, H. &amp; Hastie, T. (2005). Regularization and variable selection via the elastic net. <em>JRSS-B</em> 67:301–320.</li>
<li>Guyon, I., Weston, J., Barnhill, S. &amp; Vapnik, V. (2002). Gene selection for cancer classification using support vector machines. <em>Machine Learning</em> 46:389–422.</li>
<li>Dudoit, S., Fridlyand, J. &amp; Speed, T. P. (2002). Comparison of discrimination methods for the classification of tumors using gene expression data. <em>JASA</em> 97:77–87.</li>
<li>Ambroise, C. &amp; McLachlan, G. J. (2002). Selection bias in gene extraction on the basis of microarray gene-expression data. <em>PNAS</em> 99:6562–6566.</li>
<li>Meinshausen, N. &amp; Bühlmann, P. (2010). Stability selection. <em>JRSS-B</em> 72:417–473.</li>
<li>Barber, R. F. &amp; Candès, E. J. (2015). Controlling the false discovery rate via knockoffs. <em>Annals of Statistics</em> 43:2055–2085.</li>
<li>Candès, E., Fan, Y., Janson, L. &amp; Lv, J. (2018). Panning for gold: ‘model-X’ knockoffs for high-dimensional controlled variable selection. <em>JRSS-B</em> 80:551–577.</li>
<li>Efron, B. &amp; Hastie, T. (2016). <em>Computer Age Statistical Inference: Algorithms, Evidence, and Data Science.</em> Cambridge University Press.</li>
</ul>
<p><strong>Data.</strong> The expression matrix is <code>leukemia_big.csv</code> from the <a href="https://hastie.su.domains/CASI_files/DATA/leukemia.html">CASI data page</a>. Probe accessions and sample identifiers come from the original Whitehead files, <code>data_set_ALL_AML_train.csv</code> and <code>data_set_ALL_AML_independent.csv</code>; the URL cited in the 1999 paper is long dead, so this post uses a <a href="https://github.com/dharsandip/Classification_of_Cancer_by_Gene_Expression_Dataset">mirror</a> of them. Both are cached under <code>data/</code> by <code>src/fetch_data.py</code>.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/dataset-to-biological-signature/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>