<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-07-24">

<title>Lost in Translation: How Math Tribes Speak Different Languages (And Why Epidemiologists Hate MSE) – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ab178281e61a38778536cd86154e5f37.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Lost in Translation: How Math Tribes Speak Different Languages (And Why Epidemiologists Hate MSE)</h1>
            <p class="subtitle lead">Statisticians, epidemiologists, ML researchers, and mathematicians all say ‘calibration’ — and all mean different things. Here is a phrasebook, and one number they will fight over.</p>
                                <div class="quarto-categories">
                <div class="quarto-category">Epidemiology</div>
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Mathematical Modeling</div>
                <div class="quarto-category">SIR Models</div>
                <div class="quarto-category">Python</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 24, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#introduction-four-tribes-one-dictionary-endless-confusion" id="toc-introduction-four-tribes-one-dictionary-endless-confusion" class="nav-link active" data-scroll-target="#introduction-four-tribes-one-dictionary-endless-confusion"><span class="header-section-number">1</span> Introduction: four tribes, one dictionary, endless confusion</a></li>
  <li><a href="#the-rosetta-stone-of-math-tribes" id="toc-the-rosetta-stone-of-math-tribes" class="nav-link" data-scroll-target="#the-rosetta-stone-of-math-tribes"><span class="header-section-number">2</span> The Rosetta Stone of Math Tribes</a></li>
  <li><a href="#the-core-conflict-training-arbitrary-weights-vs.-calibrating-physical-reality" id="toc-the-core-conflict-training-arbitrary-weights-vs.-calibrating-physical-reality" class="nav-link" data-scroll-target="#the-core-conflict-training-arbitrary-weights-vs.-calibrating-physical-reality"><span class="header-section-number">3</span> The core conflict: training arbitrary weights vs.&nbsp;calibrating physical reality</a></li>
  <li><a href="#the-iris-of-epidemics" id="toc-the-iris-of-epidemics" class="nav-link" data-scroll-target="#the-iris-of-epidemics"><span class="header-section-number">4</span> The “Iris” of epidemics</a></li>
  <li><a href="#the-math-why-mse-is-dangerous-for-count-data" id="toc-the-math-why-mse-is-dangerous-for-count-data" class="nav-link" data-scroll-target="#the-math-why-mse-is-dangerous-for-count-data"><span class="header-section-number">5</span> The math: why MSE is dangerous for count data</a></li>
  <li><a href="#the-demonstration" id="toc-the-demonstration" class="nav-link" data-scroll-target="#the-demonstration"><span class="header-section-number">6</span> The demonstration</a></li>
  <li><a href="#conclusion-respect-the-data-generating-process-and-the-person-across-the-table" id="toc-conclusion-respect-the-data-generating-process-and-the-person-across-the-table" class="nav-link" data-scroll-target="#conclusion-respect-the-data-generating-process-and-the-person-across-the-table"><span class="header-section-number">7</span> Conclusion: respect the data-generating process — and the person across the table</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8</span> References</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tribes-and-calibration/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Lost in Translation</figcaption>
</figure>
</div>
<section id="introduction-four-tribes-one-dictionary-endless-confusion" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction-four-tribes-one-dictionary-endless-confusion"><span class="header-section-number">1</span> Introduction: four tribes, one dictionary, endless confusion</h2>
<p>A few posts ago I wrote about <a href="../sir-training-vs-calibration/"><strong>Training vs.&nbsp;Calibrating Epidemiological Models</strong></a> — why fitting a curve is not the same as making a mechanistic model tell the truth about a disease. That post drew a line between <em>training</em> (turning knobs until predictions match) and <em>calibration</em> (pinning down physically meaningful parameters so the model survives contact with a new outbreak).</p>
<p>Writing it, I kept tripping over a deeper problem. The words themselves are booby-trapped.</p>
<p>I have sat in rooms where a statistician, an epidemiologist, a machine-learning researcher, and a mathematician all nodded vigorously at the word <strong>“calibration”</strong> — and every one of them was picturing something different. Same syllables, four incompatible meanings. It is the academic equivalent of four people agreeing to meet “downtown” in four different cities.</p>
<p>This post is a phrasebook for those four tribes. Then, because a phrasebook is boring without a fight to translate, we will stage one: the tribes’ favourite argument, <strong>MSE versus negative log-likelihood</strong>, fought over a 111-year-old flu outbreak in an English boarding school. By the end you will see exactly why an epidemiologist flinches when a machine-learning engineer reaches for mean squared error on count data — and why that flinch is worth about 0.2 units of <span class="math inline">\(R_0\)</span>, which is to say, worth a public-health policy.</p>
</section>
<section id="the-rosetta-stone-of-math-tribes" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="the-rosetta-stone-of-math-tribes"><span class="header-section-number">2</span> The Rosetta Stone of Math Tribes</h2>
<p>Here is the phrasebook. Read across each row and watch the same word fracture into four meanings.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>Statistician</th>
<th>Epidemiologist</th>
<th>ML / CS Researcher</th>
<th>Mathematician</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Mechanistic</strong></td>
<td>A model whose parameters map to a data-generating process, not mere correlation.</td>
<td>Equations that encode how a disease actually spreads (SIR compartments, contacts).</td>
<td>A hand-built simulator, as opposed to a learned black box.</td>
<td>A deterministic dynamical system defined by differential equations.</td>
</tr>
<tr class="even">
<td><strong>Stochastic</strong></td>
<td>Randomness written explicitly into a probability distribution.</td>
<td>Chance in who infects whom, and when.</td>
<td>Noisy or sampled — dropout, mini-batches, Monte Carlo.</td>
<td>A process on a probability space; a random function of time.</td>
</tr>
<tr class="odd">
<td><strong>Interpretable</strong></td>
<td>Coefficients with an effect size and a confidence interval.</td>
<td>Parameters with biological meaning: <span class="math inline">\(R_0\)</span>, incubation period, generation time.</td>
<td>A prediction a human can rationalise after the fact (SHAP, attention).</td>
<td>A closed-form expression or a provable property.</td>
</tr>
<tr class="even">
<td><strong>Calibration</strong></td>
<td>Predicted probabilities match observed long-run frequencies.</td>
<td>Tuning mechanistic parameters so the model reproduces real epidemics.</td>
<td>Post-hoc rescaling of confidence scores (Platt scaling, temperature).</td>
<td>Choosing constants so a model meets its boundary conditions.</td>
</tr>
<tr class="odd">
<td><strong>Training</strong></td>
<td>Estimation — fitting parameters by maximum likelihood or least squares.</td>
<td>Rarely said; the nearest verb is “calibrating” the model to surveillance data.</td>
<td>Gradient descent over weights to drive a loss down.</td>
<td>Solving an optimisation problem for its argmin.</td>
</tr>
<tr class="even">
<td><strong>NLL</strong></td>
<td>The negative log-likelihood — the objective that maximum likelihood minimises.</td>
<td>The principled loss that respects how counts are actually generated.</td>
<td>Cross-entropy; the reflexive classification loss.</td>
<td>A (frequently convex) functional to be minimised.</td>
</tr>
<tr class="odd">
<td><strong>MSE</strong></td>
<td>The log-likelihood of a Gaussian with constant variance, in disguise.</td>
<td>A dangerous default that ignores the variance structure of counts.</td>
<td>The go-to regression loss; plain <span class="math inline">\(L_2\)</span>.</td>
<td>The squared <span class="math inline">\(L_2\)</span> norm of the residual vector.</td>
</tr>
</tbody>
</table>
<p>Notice the last two rows. To the ML researcher, <strong>MSE</strong> and <strong>NLL</strong> are just two entries in <code>torch.nn</code> — pick whichever the leaderboard likes. To the statistician they are <em>the same object</em> under different noise assumptions. To the epidemiologist, one of them is a quiet way to get <span class="math inline">\(R_0\)</span> wrong. Hold that thought.</p>
</section>
<section id="the-core-conflict-training-arbitrary-weights-vs.-calibrating-physical-reality" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="the-core-conflict-training-arbitrary-weights-vs.-calibrating-physical-reality"><span class="header-section-number">3</span> The core conflict: training arbitrary weights vs.&nbsp;calibrating physical reality</h2>
<p>The deepest rift is not vocabulary — it is <strong>what the parameters are allowed to mean</strong>.</p>
<p>When a deep network is <em>trained</em>, its weights are arbitrary. There is no law of physics that says neuron 4,181 in layer 12 “should” be <span class="math inline">\(-0.0037\)</span>. The weights are a coordinate system with no external referent; permuting or rescaling them can leave the function unchanged. Their only job is to make the loss small on data you already have. This is why a model that scores brilliantly can still be, in every meaningful sense, <em>about nothing</em>.</p>
<p>When an epidemiologist <em>calibrates</em> an SIR model, the parameters are load-bearing pieces of biological reality. The transmission rate <span class="math inline">\(\beta\)</span> and recovery rate <span class="math inline">\(\gamma\)</span> are not conveniences — they are claims about how often people meet and how long they stay infectious. Their ratio,</p>
<p><span class="math display">\[
R_0 = \frac{\beta}{\gamma},
\]</span></p>
<p>is the basic reproduction number: the expected number of secondary cases from one infection in a fully susceptible population. It is the single number that decides whether an outbreak fizzles (<span class="math inline">\(R_0 &lt; 1\)</span>) or explodes (<span class="math inline">\(R_0 &gt; 1\)</span>), and it is the number that walks into the health minister’s office.</p>
<p>This is what my earlier post called <strong>structural portability</strong>: because <span class="math inline">\(\beta\)</span> and <span class="math inline">\(\gamma\)</span> mean something, a calibrated model can be <em>carried</em> to a new city, a new pathogen variant, a new intervention, and still make sense. Trained weights do not port; calibrated parameters do. (I develop that argument, with a Mexico-to-Colombia transfer example, in the <a href="../sir-training-vs-calibration/">companion post</a> — I will not re-derive the SIR machinery here.)</p>
<p>None of this is new. In his 2001 essay <a href="https://www2.math.uu.se/~thulin/mm/breiman.pdf"><em>Statistical Modeling: The Two Cultures</em></a>, Leo Breiman split the field into two camps that map almost perfectly onto our tribes. The <strong>data-modeling culture</strong> assumes a <em>stochastic model</em> generated the data and reads the fitted parameters as statements about the world — this is the statistician’s effect size and the epidemiologist’s <span class="math inline">\(R_0\)</span>, quantities meant to be <em>interpreted</em>. The <strong>algorithmic-modeling culture</strong> treats the mechanism as an unknown black box and cares only whether predictions are accurate — this is the ML researcher’s trained network, whose weights are, in Breiman’s terms, a means to an end and nothing to interpret. Our four-tribe confusion is largely Breiman’s two cultures with the seams showing: when the same word crosses the line between “a parameter I believe in” and “a knob I turned,” the argument starts.</p>
<p>The punchline for this post: <strong>when your parameters are real, the loss function you minimise is not a neutral implementation detail. It is an assumption about how reality generated your data — and a wrong assumption will hand you a real-looking, wrong <span class="math inline">\(R_0\)</span>.</strong></p>
</section>
<section id="the-iris-of-epidemics" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="the-iris-of-epidemics"><span class="header-section-number">4</span> The “Iris” of epidemics</h2>
<p>Every field has a toy dataset it has loved to death. Statistics has Fisher’s irises; deep learning has MNIST. Epidemiology has a <strong>boarding school</strong>.</p>
<p>In January 1978, an influenza outbreak swept through a boys’ boarding school in the north of England. All 763 boys were effectively one closed, fully susceptible population, confined together — a near-perfect natural SIR experiment. The school infirmary recorded how many boys were confined to bed each day. The outbreak rose, peaked, and burned out inside two weeks. It is the epidemic modeller’s Iris flower: small, clean, and endlessly re-fitted.</p>
<div id="setup" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>config InlineBackend.figure_format <span class="op">=</span> <span class="st">'retina'</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.integrate <span class="im">import</span> odeint</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.special <span class="im">import</span> gammaln</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figure.dpi"</span>: <span class="dv">140</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"savefig.dpi"</span>: <span class="dv">140</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"font.size"</span>: <span class="dv">11</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.grid"</span>: <span class="va">True</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"grid.alpha"</span>: <span class="fl">0.3</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.top"</span>: <span class="va">False</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.right"</span>: <span class="va">False</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>sns.set_palette(<span class="st">"deep"</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>MSE_COLOR <span class="op">=</span> <span class="st">"#d1495b"</span>   <span class="co"># red</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>NLL_COLOR <span class="op">=</span> <span class="st">"#2e6f95"</span>   <span class="co"># blue</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>DATA_COLOR <span class="op">=</span> <span class="st">"#20232a"</span>  <span class="co"># near-black</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="cell-data" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="dv">763</span>  <span class="co"># total boys in the school (closed population)</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>outbreak <span class="op">=</span> pd.DataFrame({</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"day"</span>:      [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">10</span>, <span class="dv">11</span>, <span class="dv">12</span>, <span class="dv">13</span>, <span class="dv">14</span>],</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">"infected"</span>: [<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">7</span>, <span class="dv">24</span>, <span class="dv">73</span>, <span class="dv">192</span>, <span class="dv">238</span>, <span class="dv">255</span>, <span class="dv">231</span>, <span class="dv">150</span>, <span class="dv">72</span>, <span class="dv">29</span>, <span class="dv">11</span>, <span class="dv">4</span>],</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>outbreak.T</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="data" class="cell-output cell-output-display" data-execution_count="2">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">0</th>
<th data-quarto-table-cell-role="th">1</th>
<th data-quarto-table-cell-role="th">2</th>
<th data-quarto-table-cell-role="th">3</th>
<th data-quarto-table-cell-role="th">4</th>
<th data-quarto-table-cell-role="th">5</th>
<th data-quarto-table-cell-role="th">6</th>
<th data-quarto-table-cell-role="th">7</th>
<th data-quarto-table-cell-role="th">8</th>
<th data-quarto-table-cell-role="th">9</th>
<th data-quarto-table-cell-role="th">10</th>
<th data-quarto-table-cell-role="th">11</th>
<th data-quarto-table-cell-role="th">12</th>
<th data-quarto-table-cell-role="th">13</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">day</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
<td>8</td>
<td>9</td>
<td>10</td>
<td>11</td>
<td>12</td>
<td>13</td>
<td>14</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">infected</td>
<td>1</td>
<td>3</td>
<td>7</td>
<td>24</td>
<td>73</td>
<td>192</td>
<td>238</td>
<td>255</td>
<td>231</td>
<td>150</td>
<td>72</td>
<td>29</td>
<td>11</td>
<td>4</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Fourteen numbers. A rise from a single index case to a peak of 255 boys confined to bed on day 8, then collapse. Everything that follows is an argument about how to draw a curve through these dots.</p>
</section>
<section id="the-math-why-mse-is-dangerous-for-count-data" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="the-math-why-mse-is-dangerous-for-count-data"><span class="header-section-number">5</span> The math: why MSE is dangerous for count data</h2>
<section id="the-mechanistic-curve" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="the-mechanistic-curve"><span class="header-section-number">5.1</span> The mechanistic curve</h3>
<p>The SIR model splits the population into Susceptible, Infected, and Recovered and lets them flow between compartments:</p>
<p><span class="math display">\[
\frac{dS}{dt} = -\beta \frac{S I}{N}, \qquad
\frac{dI}{dt} = \beta \frac{S I}{N} - \gamma I, \qquad
\frac{dR}{dt} = \gamma I .
\]</span></p>
<p>Integrate these with a choice of <span class="math inline">\((\beta, \gamma)\)</span> and you get a predicted infected-count curve <span class="math inline">\(I(t; \beta, \gamma)\)</span>. Early on, while <span class="math inline">\(S \approx N\)</span>, infections grow roughly exponentially at rate <span class="math inline">\(r = \beta - \gamma\)</span>, which is exactly the phase where <span class="math inline">\(R_0\)</span> is decided. <strong>Fitting</strong> means choosing <span class="math inline">\((\beta, \gamma)\)</span> so this curve matches the 14 dots. The only question is: <em>matches according to what ruler?</em></p>
</section>
<section id="ruler-1-mean-squared-error" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="ruler-1-mean-squared-error"><span class="header-section-number">5.2</span> Ruler #1 — Mean Squared Error</h3>
<p>The machine-learning reflex is mean squared error:</p>
<p><span class="math display">\[
\mathrm{MSE}(\beta, \gamma) = \frac{1}{T} \sum_{t=1}^{T} \Big( y_t - I(t; \beta, \gamma) \Big)^2 .
\]</span></p>
<p>MSE is not assumption-free. Minimising it is <em>identical</em> to maximum likelihood under the assumption that each observation is Gaussian with the <strong>same constant variance</strong> at every time point:</p>
<p><span class="math display">\[
y_t \sim \mathcal{N}\big(I(t;\beta,\gamma),\ \sigma^2\big), \quad \sigma^2 \text{ fixed}.
\]</span></p>
<p>That is a fine assumption for many measurements. It is a <em>terrible</em> assumption for epidemic counts. On day 2 the truth is 3 boys; on day 8 it is 255. There is no honest universe in which the noise around 3 and the noise around 255 has the same magnitude. Counts do not work that way.</p>
</section>
<section id="ruler-2-poisson-negative-log-likelihood" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="ruler-2-poisson-negative-log-likelihood"><span class="header-section-number">5.3</span> Ruler #2 — Poisson negative log-likelihood</h3>
<p>Counts are generated by <em>counting</em>, and the natural model for a count is the Poisson distribution:</p>
<p><span class="math display">\[
P(Y_t = y_t \mid \lambda_t) = \frac{\lambda_t^{\,y_t}\, e^{-\lambda_t}}{y_t!}, \qquad \lambda_t = I(t; \beta, \gamma).
\]</span></p>
<p>Take the negative log and sum over days to get the loss that maximum likelihood actually minimises:</p>
<p><span class="math display">\[
\mathrm{NLL}(\beta, \gamma) = \sum_{t=1}^{T} \Big[ \lambda_t - y_t \log \lambda_t + \log(y_t!) \Big] .
\]</span></p>
<p>The Poisson has one defining feature that MSE lacks entirely: <strong>its variance equals its mean</strong>, <span class="math inline">\(\mathrm{Var}(Y_t) = \lambda_t\)</span>. Big days are intrinsically noisier than small days, and the likelihood knows it.</p>
</section>
<section id="the-one-line-that-explains-the-whole-fight" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="the-one-line-that-explains-the-whole-fight"><span class="header-section-number">5.4</span> The one line that explains the whole fight</h3>
<p>Here is the identity that every tribe should tattoo somewhere visible. Expand the Poisson NLL to second order around the fit and it becomes a <em>weighted</em> least squares:</p>
<p><span class="math display">\[
\mathrm{NLL} \;\approx\; \text{const} + \tfrac{1}{2}\sum_{t=1}^{T} \frac{\big(y_t - \lambda_t\big)^2}{\lambda_t}.
\]</span></p>
<p>Read that carefully. <strong>Poisson NLL is just MSE with each residual divided by the expected count.</strong> Plain MSE weights every day equally, so its sum is dominated by the handful of tall days near the peak — a residual of 20 at the peak contributes <span class="math inline">\(400\)</span>, while the entire early growth phase (days 1–4) can contribute less than that combined. Poisson NLL down-weights the loud peak by <span class="math inline">\(1/\lambda_t\)</span> and gives the quiet, low-count days a proportionate say.</p>
<p>MSE listens to the peak. NLL listens to everyone. Now let’s watch it happen.</p>
</section>
</section>
<section id="the-demonstration" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="the-demonstration"><span class="header-section-number">6</span> The demonstration</h2>
<section id="a-mechanistic-sir-simulator-with-odeint" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="a-mechanistic-sir-simulator-with-odeint"><span class="header-section-number">6.1</span> A mechanistic SIR simulator with <code>odeint</code></h3>
<div id="sir-model" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sir_infected(params, days, N<span class="op">=</span>N, I0<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Integrate the SIR ODEs and return predicted infected counts on `days`."""</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    beta, gamma <span class="op">=</span> params</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> deriv(y, t):</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        S, I, R <span class="op">=</span> y</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>        dS <span class="op">=</span> <span class="op">-</span>beta <span class="op">*</span> S <span class="op">*</span> I <span class="op">/</span> N</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>        dI <span class="op">=</span> beta <span class="op">*</span> S <span class="op">*</span> I <span class="op">/</span> N <span class="op">-</span> gamma <span class="op">*</span> I</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>        dR <span class="op">=</span> gamma <span class="op">*</span> I</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> [dS, dI, dR]</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    y0 <span class="op">=</span> [N <span class="op">-</span> I0, I0, <span class="fl">0.0</span>]          <span class="co"># state at the first day: one index case</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    sol <span class="op">=</span> odeint(deriv, y0, days)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.clip(sol[:, <span class="dv">1</span>], <span class="fl">1e-8</span>, <span class="va">None</span>)   <span class="co"># infected column, floored positive</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="two-objective-functions" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="two-objective-functions"><span class="header-section-number">6.2</span> Two objective functions</h3>
<div id="objectives" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>days <span class="op">=</span> outbreak[<span class="st">"day"</span>].to_numpy(dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>observed <span class="op">=</span> outbreak[<span class="st">"infected"</span>].to_numpy(dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> mse_loss(params):</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> params[<span class="dv">0</span>] <span class="op">&lt;=</span> <span class="dv">0</span> <span class="kw">or</span> params[<span class="dv">1</span>] <span class="op">&lt;=</span> <span class="dv">0</span>:      <span class="co"># keep rates physical</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">1e12</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> sir_infected(params, days)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.mean((observed <span class="op">-</span> lam) <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> poisson_nll(params):</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> params[<span class="dv">0</span>] <span class="op">&lt;=</span> <span class="dv">0</span> <span class="kw">or</span> params[<span class="dv">1</span>] <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> <span class="fl">1e12</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> sir_infected(params, days)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.<span class="bu">sum</span>(lam <span class="op">-</span> observed <span class="op">*</span> np.log(lam) <span class="op">+</span> gammaln(observed <span class="op">+</span> <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="calibrate-twice" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="calibrate-twice"><span class="header-section-number">6.3</span> Calibrate twice</h3>
<div id="cell-optimize" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> [<span class="fl">2.0</span>, <span class="fl">0.5</span>]   <span class="co"># a plausible flu-like starting guess</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>fit_mse <span class="op">=</span> minimize(mse_loss,     start, method<span class="op">=</span><span class="st">"Nelder-Mead"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>fit_nll <span class="op">=</span> minimize(poisson_nll,  start, method<span class="op">=</span><span class="st">"Nelder-Mead"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> summarise(name, res):</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    beta, gamma <span class="op">=</span> res.x</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"loss"</span>: name,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>        <span class="st">"beta"</span>: beta,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>        <span class="st">"gamma"</span>: gamma,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"R0"</span>: beta <span class="op">/</span> gamma,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"infectious_period_days"</span>: <span class="fl">1.0</span> <span class="op">/</span> gamma,</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>summary <span class="op">=</span> pd.DataFrame([</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    summarise(<span class="st">"MSE"</span>,         fit_mse),</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    summarise(<span class="st">"Poisson NLL"</span>, fit_nll),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>summary.<span class="bu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="optimize" class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">loss</th>
<th data-quarto-table-cell-role="th">beta</th>
<th data-quarto-table-cell-role="th">gamma</th>
<th data-quarto-table-cell-role="th">R0</th>
<th data-quarto-table-cell-role="th">infectious_period_days</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>MSE</td>
<td>1.703</td>
<td>0.518</td>
<td>3.288</td>
<td>1.931</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Poisson NLL</td>
<td>1.756</td>
<td>0.566</td>
<td>3.103</td>
<td>1.767</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Both fits land in the same neighbourhood — this is a clean, well-specified problem, and I want to be honest about that: nobody’s curve is a disaster. But look at the <code>R0</code> column. <strong>MSE reports <span class="math inline">\(R_0 \approx 3.29\)</span>; Poisson NLL reports <span class="math inline">\(R_0 \approx 3.10\)</span>.</strong> A gap of about 0.19 in the one number that runs the outbreak. It comes almost entirely from the recovery rate <span class="math inline">\(\gamma\)</span>: to hug the tall peak, MSE prefers a slightly slower burn, which nudges <span class="math inline">\(R_0\)</span> up. Let’s see it.</p>
</section>
<section id="the-plot-everyone-in-the-room-is-pointing-at" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="the-plot-everyone-in-the-room-is-pointing-at"><span class="header-section-number">6.4</span> The plot everyone in the room is pointing at</h3>
<div id="cell-fig-fits" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>fine_days <span class="op">=</span> np.linspace(<span class="dv">1</span>, <span class="dv">14</span>, <span class="dv">200</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>curve_mse <span class="op">=</span> sir_infected(fit_mse.x, fine_days)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>curve_nll <span class="op">=</span> sir_infected(fit_nll.x, fine_days)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>R0_mse <span class="op">=</span> fit_mse.x[<span class="dv">0</span>] <span class="op">/</span> fit_mse.x[<span class="dv">1</span>]</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>R0_nll <span class="op">=</span> fit_nll.x[<span class="dv">0</span>] <span class="op">/</span> fit_nll.x[<span class="dv">1</span>]</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="fl">4.9</span>))</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> (ax1, ax2):</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    ax.scatter(days, observed, color<span class="op">=</span>DATA_COLOR, s<span class="op">=</span><span class="dv">48</span>, zorder<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>               label<span class="op">=</span><span class="st">"Observed (boys confined to bed)"</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    ax.plot(fine_days, curve_mse, <span class="st">"--"</span>, color<span class="op">=</span>MSE_COLOR, lw<span class="op">=</span><span class="fl">2.3</span>,</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>            label<span class="op">=</span><span class="ss">f"MSE fit   ($R_0$ = </span><span class="sc">{</span>R0_mse<span class="sc">:.2f}</span><span class="ss">)"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    ax.plot(fine_days, curve_nll, <span class="st">"-"</span>, color<span class="op">=</span>NLL_COLOR, lw<span class="op">=</span><span class="fl">2.3</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>            label<span class="op">=</span><span class="ss">f"Poisson NLL fit   ($R_0$ = </span><span class="sc">{</span>R0_nll<span class="sc">:.2f}</span><span class="ss">)"</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"Day of outbreak"</span>)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">"Infected"</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>ax1.set_title(<span class="st">"Linear scale"</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>ax1.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"upper right"</span>)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">"MSE leans on the tall peak</span><span class="ch">\n</span><span class="st">(largest squared errors live here)"</span>,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>             xy<span class="op">=</span>(<span class="fl">7.4</span>, <span class="dv">249</span>), xytext<span class="op">=</span>(<span class="fl">8.2</span>, <span class="dv">300</span>), fontsize<span class="op">=</span><span class="fl">8.5</span>, color<span class="op">=</span>MSE_COLOR,</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>             arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span>MSE_COLOR, lw<span class="op">=</span><span class="fl">1.3</span>))</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>ax1.annotate(<span class="st">"...and pays for it by</span><span class="ch">\n</span><span class="st">overshooting the decline"</span>,</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>             xy<span class="op">=</span>(<span class="fl">12.8</span>, <span class="dv">40</span>), xytext<span class="op">=</span>(<span class="fl">9.6</span>, <span class="dv">150</span>), fontsize<span class="op">=</span><span class="fl">8.5</span>, color<span class="op">=</span>MSE_COLOR,</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>             arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span>MSE_COLOR, lw<span class="op">=</span><span class="fl">1.3</span>))</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>ax2.set_yscale(<span class="st">"log"</span>)</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">"Infected (log scale)"</span>)</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>ax2.set_title(<span class="st">"Log scale — the count-data view"</span>)</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>ax2.annotate(<span class="st">"relative error is what</span><span class="ch">\n</span><span class="st">you actually feel here"</span>,</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>             xy<span class="op">=</span>(<span class="dv">13</span>, curve_mse[<span class="op">-</span><span class="dv">1</span>]), xytext<span class="op">=</span>(<span class="fl">8.5</span>, <span class="dv">4</span>), fontsize<span class="op">=</span><span class="fl">8.5</span>, color<span class="op">=</span>MSE_COLOR,</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>             arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span>MSE_COLOR, lw<span class="op">=</span><span class="fl">1.3</span>))</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>fig.suptitle(<span class="st">"Same data, same model, two loss functions"</span>, fontsize<span class="op">=</span><span class="dv">13</span>, weight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>fig.savefig(<span class="st">"cover.png"</span>, dpi<span class="op">=</span><span class="dv">200</span>, bbox_inches<span class="op">=</span><span class="st">"tight"</span>)</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-fits" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-fits-output-1.png" width="1663" height="677" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fits-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The same 14 dots, the same SIR model, two loss functions. MSE (dashed red) leans on the tall peak and overshoots the low-count tail; Poisson NLL (solid blue) spreads its attention across every magnitude. The right panel puts the y-axis on a log scale — the natural habitat of count data — where the tail disagreement is impossible to miss.
</figcaption>
</figure>
</div>
</div>
</div>
<p>On the linear scale the two curves look like polite disagreement. That is exactly the trap: MSE’s error is measured in <em>squared boys</em>, so the entire tail — days 11 to 14, where the truth falls from 72 to 4 — barely registers in its loss, and MSE is free to sail over those points to shave a few squared-boys off the peak. Switch to the log scale (the right panel) and the disagreement is obvious. On a log axis, equal <em>relative</em> errors look equal-sized, and that is the ruler an epidemiologist cares about: being “off by a factor of two” matters whether you are at 4 cases or 400. MSE’s tail is visibly adrift; the Poisson fit stays honest down in the low counts.</p>
</section>
<section id="why-this-is-not-a-curiosity-the-r_0-is-biased-not-just-different" class="level3" data-number="6.5">
<h3 data-number="6.5" class="anchored" data-anchor-id="why-this-is-not-a-curiosity-the-r_0-is-biased-not-just-different"><span class="header-section-number">6.5</span> Why this is not a curiosity: the <span class="math inline">\(R_0\)</span> is biased, not just different</h3>
<p>A 0.19 gap in <span class="math inline">\(R_0\)</span> from one dataset could be a fluke. It is not. The reason MSE inflates <span class="math inline">\(R_0\)</span> is structural: <strong>the peak days carry the most Poisson noise</strong> (variance equals mean, so day 8 has a standard deviation of about <span class="math inline">\(\sqrt{255} \approx 16\)</span>), and MSE — trusting absolute residuals — leans hardest on precisely the least reliable observations. To show this is systematic, we re-run the whole calibration on 200 synthetic outbreaks drawn from the same underlying truth with fresh Poisson noise each time, and watch where each loss puts <span class="math inline">\(R_0\)</span>.</p>
<div id="cell-monte-carlo" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>truth <span class="op">=</span> observed</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>reps <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>r0_mse, r0_nll <span class="op">=</span> [], []</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(reps):</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> rng.poisson(truth).astype(<span class="bu">float</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    y[y <span class="op">&lt;</span> <span class="dv">1</span>] <span class="op">=</span> <span class="fl">1.0</span>                      <span class="co"># keep at least one case for the log terms</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> mse_l(p, y<span class="op">=</span>y):</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> p[<span class="dv">0</span>] <span class="op">&lt;=</span> <span class="dv">0</span> <span class="kw">or</span> p[<span class="dv">1</span>] <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="fl">1e12</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.mean((y <span class="op">-</span> sir_infected(p, days)) <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> nll_l(p, y<span class="op">=</span>y):</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> p[<span class="dv">0</span>] <span class="op">&lt;=</span> <span class="dv">0</span> <span class="kw">or</span> p[<span class="dv">1</span>] <span class="op">&lt;=</span> <span class="dv">0</span>:</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>            <span class="cf">return</span> <span class="fl">1e12</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        lam <span class="op">=</span> sir_infected(p, days)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.<span class="bu">sum</span>(lam <span class="op">-</span> y <span class="op">*</span> np.log(lam) <span class="op">+</span> gammaln(y <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    m <span class="op">=</span> minimize(mse_l, start, method<span class="op">=</span><span class="st">"Nelder-Mead"</span>).x</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> minimize(nll_l, start, method<span class="op">=</span><span class="st">"Nelder-Mead"</span>).x</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    r0_mse.append(m[<span class="dv">0</span>] <span class="op">/</span> m[<span class="dv">1</span>])</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    r0_nll.append(n[<span class="dv">0</span>] <span class="op">/</span> n[<span class="dv">1</span>])</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>r0_mse <span class="op">=</span> np.array(r0_mse)</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>r0_nll <span class="op">=</span> np.array(r0_nll)</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>mc <span class="op">=</span> pd.DataFrame({</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    <span class="st">"loss"</span>: [<span class="st">"MSE"</span>, <span class="st">"Poisson NLL"</span>],</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">"mean_R0"</span>: [r0_mse.mean(), r0_nll.mean()],</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>    <span class="st">"sd_R0"</span>:   [r0_mse.std(),  r0_nll.std()],</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    <span class="st">"p5"</span>:      [np.percentile(r0_mse, <span class="dv">5</span>),  np.percentile(r0_nll, <span class="dv">5</span>)],</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    <span class="st">"p95"</span>:     [np.percentile(r0_mse, <span class="dv">95</span>), np.percentile(r0_nll, <span class="dv">95</span>)],</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>mc.<span class="bu">round</span>(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="monte-carlo" class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">loss</th>
<th data-quarto-table-cell-role="th">mean_R0</th>
<th data-quarto-table-cell-role="th">sd_R0</th>
<th data-quarto-table-cell-role="th">p5</th>
<th data-quarto-table-cell-role="th">p95</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>MSE</td>
<td>3.294</td>
<td>0.079</td>
<td>3.160</td>
<td>3.411</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Poisson NLL</td>
<td>3.106</td>
<td>0.062</td>
<td>3.007</td>
<td>3.188</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<div id="cell-fig-r0" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">4.2</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>bins <span class="op">=</span> np.linspace(<span class="fl">2.9</span>, <span class="fl">3.55</span>, <span class="dv">30</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>ax.hist(r0_mse, bins<span class="op">=</span>bins, alpha<span class="op">=</span><span class="fl">0.65</span>, color<span class="op">=</span>MSE_COLOR, label<span class="op">=</span><span class="st">"MSE"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>ax.hist(r0_nll, bins<span class="op">=</span>bins, alpha<span class="op">=</span><span class="fl">0.65</span>, color<span class="op">=</span>NLL_COLOR, label<span class="op">=</span><span class="st">"Poisson NLL"</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>ax.axvline(r0_mse.mean(), color<span class="op">=</span>MSE_COLOR, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="fl">1.6</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>ax.axvline(r0_nll.mean(), color<span class="op">=</span>NLL_COLOR, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="fl">1.6</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Estimated $R_0$"</span>)</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Count across 200 noisy outbreaks"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"MSE systematically over-estimates $R_0$"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-r0" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-r0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-r0-output-1.png" width="1047" height="568" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-r0-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Estimated R0 across 200 synthetic outbreaks with fresh Poisson noise each time. MSE (red) sits systematically higher than Poisson NLL (blue); the two distributions barely overlap. Choosing the loss shifts the headline number by more than either estimator’s own sampling spread.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The two histograms sit almost side by side. MSE centres near <span class="math inline">\(R_0 \approx 3.29\)</span>, Poisson NLL near <span class="math inline">\(R_0 \approx 3.11\)</span>, and each has a spread (standard deviation) of only about <span class="math inline">\(0.06\)</span>–<span class="math inline">\(0.08\)</span>. In other words: <strong>the bias you introduce by picking the wrong loss is larger than the entire statistical uncertainty of the estimate.</strong> You could collect more data, tighten every confidence interval, publish with pride — and still be reliably wrong, because the error was baked into the ruler, not the measurement. Since the data really are counts, the Poisson likelihood is the correct one; MSE’s <span class="math inline">\(R_0\)</span> is the biased one. That is the moment an epidemiologist reaches across the table and takes the MSE away from you.</p>
</section>
</section>
<section id="conclusion-respect-the-data-generating-process-and-the-person-across-the-table" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="conclusion-respect-the-data-generating-process-and-the-person-across-the-table"><span class="header-section-number">7</span> Conclusion: respect the data-generating process — and the person across the table</h2>
<p>Two lessons, one technical and one human.</p>
<p>The technical one: <strong>the loss function is a claim about how your data were generated.</strong> MSE quietly asserts constant-variance Gaussian noise; Poisson NLL asserts that counts are counts, with variance that grows with the mean. On exponential count data those are different claims, and the difference is not cosmetic — it moved <span class="math inline">\(R_0\)</span> by more than its own sampling error and left MSE trusting the noisiest points in the dataset. “Just use MSE, it’s the default” is, for count data, a modelling decision made by accident. Respecting the data-generating process is not pedantry; it is the difference between a portable, biologically meaningful <span class="math inline">\(R_0\)</span> and a plausible-looking artefact of your optimiser.</p>
<p>The human one: <strong>the tribes are not disagreeing, they are mistranslating.</strong> When the ML engineer says “the model is well-calibrated” and the epidemiologist frowns, they are not in conflict about facts — they are using the same word for temperature scaling and for pinning down <span class="math inline">\(\beta\)</span>. The most valuable skill in an interdisciplinary room is not knowing more math; it is noticing the instant a shared word has quietly forked into four meanings, and asking which one everybody is holding. Keep the <a href="#the-rosetta-stone-of-math-tribes">phrasebook</a> handy. And if you want the deeper story on what it means to calibrate rather than merely train a mechanistic model, that is the <a href="../sir-training-vs-calibration/">companion post</a> this one grew out of.</p>
</section>
<section id="references" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="references"><span class="header-section-number">8</span> References</h2>
<ul>
<li><strong>Breiman, L.</strong> (2001). <a href="https://www2.math.uu.se/~thulin/mm/breiman.pdf"><em>Statistical Modeling: The Two Cultures.</em></a> <em>Statistical Science</em> 16(3), 199–231. — The data-modeling vs.&nbsp;algorithmic-modeling split that underlies the whole “tribes” framing.</li>
<li><strong>Kermack, W. O., &amp; McKendrick, A. G.</strong> (1927). <em>A Contribution to the Mathematical Theory of Epidemics.</em> <em>Proceedings of the Royal Society of London A</em> 115(772), 700–721. — The origin of the SIR compartmental model.</li>
<li><strong>“Influenza in a boarding school.”</strong> (1978). <em>British Medical Journal</em> 1(6112), 587. — The news report recording the 14-day case counts used here; a standard SIR teaching example ever since.</li>
<li><strong>McCullagh, P., &amp; Nelder, J. A.</strong> (1989). <em>Generalized Linear Models</em> (2nd ed.). Chapman &amp; Hall/CRC. — Poisson regression and the iteratively reweighted least squares view behind the “Poisson NLL ≈ variance-weighted MSE” identity.</li>
<li><strong>Kalia, R.</strong> <a href="../sir-training-vs-calibration/"><em>Training vs.&nbsp;Calibrating Epidemiological Models: A First-Principles Guide.</em></a> — The companion post this one grew out of.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tribes-and-calibration/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>