project:
  type: website
  output-dir: docs
  render:
  - "*.qmd"
  - "*.ipynb"
  - "!notes/"
website:
  repo-url: https://github.com/project-delphi/ml-blog/
  repo-actions: [edit]
  repo-branch: main
  title: "Blog Directory"
  navbar:
    right:
      - icon: github
        href: https://github.com/project-delphi
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/ravi-kalia-phd
        aria-label: LinkedIn
      - icon: house-fill
        href: https://project-delphi.github.io
        aria-label: LinkedIn
format:
  html:
    theme: zephyr
    css: styles.css
    code-copy: true
    monobackgroundcolor: "#eef0f4"
