project:
  type: website
  output-dir: docs
  render:
  - "*.qmd"
  - "!notes/"
website:
  title: "."
  navbar:
    right:
      - icon: house-fill
        href: https://project-delphi.github.io
      - icon: github
        href: https://github.com/project-delphi
        aria-label: GitHub
format:
  html:
    theme: slate
    css: styles.css
