{
  "hash": "cdfbe8a9af564a492ff0b8c05bdb8272",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Five Photos of One Kite, Five Different Shapes\"\nsubtitle: \"What happens when you point Kendall shape analysis at a photograph instead of a specimen\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-08-18\"\ncategories: [Statistics, Geometry, Computer Vision]\nimage: \"./cover.png\"\ntags: [kendall-shape-analysis, procrustes, morphometrics, homography, thin-plate-splines, shapes-r]\njupyter: kite-blog\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    code-fold: show\n    number-sections: true\n---\n\n\n![Five Photos of One Kite, Five Different Shapes](./cover.png)\n\n## Problem statement\n\nKendall shape analysis quotients out translation, scale, and rotation (the **similarity** group). Field photographs of a rigid object introduce **perspective**, which similarity cannot remove.\n\n**Test case:** five iPhone photographs of one kite, nine seconds apart. Correct shape difference = 0. Standard GPA reports up to 0.33 Riemannian separation.\n\nMethod background: [Kendall shape analysis on synthetic pencils and optic nerve heads](../kendall-shape-analysis/index.qmd).\n\n## Photograph data\n\n**Provenance:** author photographs, Villa de Leyva kite festival, Boyacá, Colombia, 15 August 2026.\n\n**Format:** iPhone HEIC, committed at 1512 × 2016 (half of 3024 × 4032). Timestamps 13:26:12–13:26:21 (9 s span).\n\n**Collection:** handheld, no tripod, scale bar, or fixed distance.\n\n**Objective:** does one rigid object photographed five times yield one shape under similarity quotient?\n\n**Downstream impact:** morphometric studies comparing photographed specimens may confound biology with viewpoint if the nuisance group is wrong.\n\n**Why this dataset:** ground truth is known (one unchanged kite); failure isolates the nuisance group, not landmark error.\n\n## Image representation\n\nA colour photograph is a $H \\times W \\times 3$ array of RGB intensities.\n\n::: {#cell-fig-matrix .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\nfrom PIL import Image\n\nphoto = Image.open(\"photos/kite-01.jpg\").convert(\"RGB\")\nrgb = np.asarray(photo)\ngrey = np.asarray(photo.convert(\"L\"))\n\nfig, axes = plt.subplots(1, 3, figsize=(13, 5))\naxes[0].imshow(rgb)\naxes[0].set_title(f\"colour: {rgb.shape[1]} wide x {rgb.shape[0]} tall x {rgb.shape[2]}\")\naxes[1].imshow(grey, cmap=\"gray\")\naxes[1].set_title(f\"brightness: {grey.shape[1]} wide x {grey.shape[0]} tall\")\n\npatch = grey[600:610, 500:510]\naxes[2].imshow(patch, cmap=\"gray\", interpolation=\"nearest\", vmin=0, vmax=255)\nfor i in range(10):\n    for j in range(10):\n        axes[2].text(j, i, patch[i, j], ha=\"center\", va=\"center\", color=\"tab:red\", fontsize=7)\naxes[2].set_title(\"a 10x10 patch of cloud\")\nfor ax in axes:\n    ax.axis(\"off\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![One frame as a picture, as a brightness matrix, and as raw numbers. The sky patch is flat and bright: cloud is high in brightness and almost zero in colour.](index_files/figure-html/fig-matrix-output-1.png){#fig-matrix}\n:::\n:::\n\n\nCloud patch: high brightness, low colour spread.\n\n## Saturation segmentation\n\n**Saturation** = $(\\max R,G,B - \\min R,G,B) / \\max R,G,B$. Kite fabric: high saturation. Sky: near zero.\n\nThreshold 0.30 + largest connected component isolates the kite in all five frames. Streamers occupy ~half each mask and move independently — excluded from landmarks.\n\n::: {#cell-fig-segment .cell execution_count=2}\n``` {.python .cell-code}\nfrom scipy import ndimage\n\ndef saturation(image):\n    \"\"\"Distance from grey, per pixel: (max channel - min channel) / max channel.\"\"\"\n    a = np.asarray(image).astype(np.float32) / 255.0\n    top, bottom = a.max(axis=2), a.min(axis=2)\n    return (top - bottom) / np.maximum(top, 1e-6)\n\ndef largest_blob(mask):\n    \"\"\"The biggest connected component, plus its bounding box.\"\"\"\n    labels, count = ndimage.label(mask)\n    sizes = ndimage.sum(mask, labels, range(1, count + 1))\n    best = int(np.argmax(sizes)) + 1\n    return labels == best, ndimage.find_objects(labels)[best - 1]\n\nfig, axes = plt.subplots(2, 5, figsize=(16, 7))\nfor frame in range(1, 6):\n    image = Image.open(f\"photos/kite-{frame:02d}.jpg\").convert(\"RGB\")\n    kite, box = largest_blob(saturation(image) > 0.30)\n    pad = 30\n    rows = slice(max(0, box[0].start - pad), box[0].stop + pad)\n    cols = slice(max(0, box[1].start - pad), box[1].stop + pad)\n    axes[0][frame - 1].imshow(np.asarray(image)[rows, cols])\n    axes[0][frame - 1].set_title(f\"frame {frame}\")\n    axes[1][frame - 1].imshow(kite[rows, cols], cmap=\"gray\")\nfor ax in axes.ravel():\n    ax.axis(\"off\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Top: the kite as photographed, cropped from each frame. Bottom: every pixel with saturation above 0.30. The sky vanishes completely.](index_files/figure-html/fig-segment-output-1.png){#fig-segment}\n:::\n:::\n\n\nSame kite appears as wide triangle (frame 1) vs narrow chevron (frame 4). Viewpoint changed; kite did not.\n\n## Landmark correspondence\n\nProcrustes requires **landmarks**: labelled points with the same anatomical meaning in every frame.\n\n- Streamers excluded (non-rigid, no stable correspondence).\n- Six sail landmarks on the rigid colour-chevron block:\n\n| Label | Location |\n|---|---|\n| `nose` | Outer apex of leading edges |\n| `armA_out`, `armB_out` | Far ends of leading edges |\n| `armA_in`, `armB_in` | Inner boundary ends on each arm |\n| `apex_in` | Inner apex where inner boundaries meet |\n\n**Bilateral symmetry:** no single image determines which wing is `armA` vs `armB`. Fixed by consistent traversal order; frame 5 labels swapped relative to the photograph.\n\n**Reflection:** Procrustes allows reflections (forbid → SS 0.855 vs 0.111 with allow). Affine ladder fits per frame separately and is not reflection-invariant.\n\n**Digitisation:** hand-placed from committed photos, ±5 px on ~160 px sail width.\n\n![The six sail landmarks in each frame. Nothing sits on a streamer.](./fig-landmarks.png)\n\n::: {#load-landmarks .cell execution_count=3}\n``` {.python .cell-code}\nimport csv\n\nORDER = [\"nose\", \"armA_out\", \"armA_in\", \"apex_in\", \"armB_in\", \"armB_out\"]\n\nrows = list(csv.DictReader(open(\"landmarks.csv\")))\nby_frame = {}\nfor row in rows:\n    by_frame.setdefault(int(row[\"frame\"]), {})[row[\"landmark\"]] = (\n        float(row[\"x\"]), float(row[\"y\"]))\n\nX = np.stack([np.array([by_frame[f][name] for name in ORDER]) for f in sorted(by_frame)])\nprint(f\"{X.shape[0]} configurations of {X.shape[1]} landmarks in {X.shape[2]}D\")\nprint(f\"mean centroid size: {np.mean([np.linalg.norm(c - c.mean(0)) for c in X]):.0f} px\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n5 configurations of 6 landmarks in 2D\nmean centroid size: 160 px\n```\n:::\n:::\n\n\n## Nose-angle test\n\nSimilarity transformations preserve angles. If frames differ only by similarity, nose angle is invariant.\n\n::: {#nose-angle .cell execution_count=4}\n``` {.python .cell-code}\ndef nose_angle(config):\n    \"\"\"Angle at the nose, between the two leading edges, in degrees.\"\"\"\n    left = config[ORDER.index(\"armA_out\")] - config[ORDER.index(\"nose\")]\n    right = config[ORDER.index(\"armB_out\")] - config[ORDER.index(\"nose\")]\n    cosine = np.dot(left, right) / (np.linalg.norm(left) * np.linalg.norm(right))\n    return np.degrees(np.arccos(cosine))\n\nangles = np.array([nose_angle(c) for c in X])\nfor frame, angle in enumerate(angles, start=1):\n    print(f\"  frame {frame}: {angle:6.2f} degrees\")\nprint(f\"\\nspread: {angles.max() - angles.min():.1f} degrees\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  frame 1: 104.01 degrees\n  frame 2: 112.93 degrees\n  frame 3:  86.97 degrees\n  frame 4:  81.29 degrees\n  frame 5:  88.01 degrees\n\nspread: 31.6 degrees\n```\n:::\n:::\n\n\nNose-angle spread: 31°. ±5 px jitter: 3.6–6.3° SD. Inter-frame map is not similarity.\n\n## Generalised Procrustes analysis\n\nStandard pipeline: centre, scale to unit Frobenius norm, iterate rotation-to-mean (GPA).\n\n::: {#gpa .cell execution_count=5}\n``` {.python .cell-code}\ndef centre_and_scale(config):\n    \"\"\"Remove translation and size.\"\"\"\n    centred = config - config.mean(axis=0)\n    return centred / np.linalg.norm(centred)\n\ndef align_onto(config, target):\n    \"\"\"Least-squares orthogonal map of `config` onto `target`, via an SVD.\n\n    Reflections are allowed, deliberately. The usual version of this function\n    forbids them, on the grounds that a mirror image is a different shape. That\n    is right for a left and a right hand; it is wrong here, because which wing\n    of a symmetric sail got labelled `armA` is a free choice rather than a fact\n    about the kite (see above). Forbidding reflection would charge that free\n    choice to the kite's shape.\n    \"\"\"\n    u, _, vt = np.linalg.svd(target.T @ config)\n    return config @ (vt.T @ u.T)\n\ndef gpa(configs, prepare=centre_and_scale, tol=1e-13, max_iter=500):\n    \"\"\"Generalised Procrustes: prepare each configuration, then iterate to a mean.\"\"\"\n    aligned = np.stack([prepare(c) for c in configs])\n    mean = aligned[0]\n    for _ in range(max_iter):\n        aligned = np.stack([centre_and_scale(align_onto(c, mean)) for c in aligned])\n        new_mean = centre_and_scale(aligned.mean(axis=0))\n        if np.linalg.norm(new_mean - mean) < tol:\n            break\n        mean = new_mean\n    return aligned, mean\n\naligned, mean_shape = gpa(X)\nresidual = np.linalg.norm(aligned - mean_shape, axis=(1, 2))\nsimilarity_ss = float((residual ** 2).sum())\nprint(\"residual to the mean shape:\", residual.round(4))\nprint(f\"Procrustes sum of squares: {similarity_ss:.5f}\")\nprint(f\"RMS residual: {residual.mean():.4f}  ({100 * residual.mean():.1f}% of centroid size)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nresidual to the mean shape: [0.1381 0.1764 0.1416 0.1643 0.1173]\nProcrustes sum of squares: 0.11100\nRMS residual: 0.1475  (14.8% of centroid size)\n```\n:::\n:::\n\n\nRMS residual ≈ 0.15 at unit size. Procrustes SS = 0.111.\n\n::: {#cell-fig-gpa-raw .cell execution_count=6}\n``` {.python .cell-code}\nCOLOURS = plt.cm.viridis(np.linspace(0.05, 0.85, 5))\n\ndef draw(ax, config, colour, lw=1.4, alpha=0.9):\n    loop = np.vstack([config, config[0]])\n    ax.plot(loop[:, 0], loop[:, 1], \"-o\", color=colour, lw=lw, ms=3.5, alpha=alpha)\n\nfig, ax = plt.subplots(figsize=(6, 5))\nfor config, colour in zip(aligned, COLOURS):\n    draw(ax, config, colour)\ndraw(ax, mean_shape, \"black\", lw=2.4, alpha=1.0)\nax.set_aspect(\"equal\")\nax.invert_yaxis()\nax.set_title(\"After GPA: five frames of one rigid kite\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The five sails after generalised Procrustes analysis, with the mean shape in black. This is the best that translation, scale and rotation can do.](index_files/figure-html/fig-gpa-raw-output-1.png){#fig-gpa-raw}\n:::\n:::\n\n\n## Transformation model ladder\n\nCandidate groups (nested):\n\n| Model | DOF | Preserves | Use case |\n|---|---|---|---|\n| Similarity | 4 | Angles | Lab bench, square camera |\n| Affine | 6 | Parallel lines | Weak perspective (distant camera) |\n| Projective | 8 | Straight lines | General plane photograph |\n\nFit each model mapping frames 2–5 onto frame 1; compare RMS pixel error.\n\n::: {#ladder .cell execution_count=7}\n`````` {.python .cell-code}\nfrom scipy.optimize import least_squares\n\ndef fit_similarity(src, dst, allow_reflection=True):\n    \"\"\"Best similarity map from `src` onto `dst` (Umeyama).\n\n    Reflection is allowed by default, matching the Procrustes alignment above\n    and for the same reason: the wing labelling is a free choice. Refusing it\n    takes more than flipping the rotation matrix -- the smallest singular\n    value's contribution to the optimal scale flips sign with it. Leaving\n    `trace` at ``sv.sum()`` in that branch overshoots the scale, and is an easy\n    bug to write by accident.\n    \"\"\"\n    mu_s, mu_d = src.mean(0), dst.mean(0)\n    s0, d0 = src - mu_s, dst - mu_d\n    u, sv, vt = np.linalg.svd(d0.T @ s0)\n    rotation = u @ vt\n    trace = sv.sum()\n    if not allow_reflection and np.linalg.det(rotation) < 0:\n        u = u.copy()\n        u[:, -1] *= -1\n        rotation = u @ vt\n        trace = sv[0] - sv[1]\n    return (s0 @ rotation.T) * (trace / (s0 ** 2).sum()) + mu_d\n\ndef fit_affine(src, dst):\n    design = np.hstack([src, np.ones((len(src), 1))])\n    return design @ np.linalg.lstsq(design, dst, rcond=None)[0]\n\ndef apply_homography(h, src):\n    p = np.hstack([src, np.ones((len(src), 1))]) @ h.T\n    return p[:, :2] / p[:, 2:3]\n\ndef fit_projective(src, dst):\n    \"\"\"Normalised DLT for a starting point, then refine on *geometric* error.\n\n    The plain DLT minimises an algebraic residual, which on six points can be\n    far from the least-squares answer -- badly enough to score worse than the\n    affine fit nested inside it, which is impossible for a correct fit.\n    \"\"\"\n    def normalise(p):\n        mu = p.mean(0)\n        q = p - mu\n        s = np.sqrt(2) / np.sqrt((q ** 2).sum(1)).mean()\n        return np.array([[s, 0, -s * mu[0]], [0, s, -s * mu[1]], [0, 0, 1]]), np.hstack(\n            [q * s, np.ones((len(p), 1))])\n\n    t_src, ns = normalise(src)\n    t_dst, nd = normalise(dst)\n    rows = []\n    for (x, y, _), (u, v, _) in zip(ns, nd):\n        rows.append([x, y, 1, 0, 0, 0, -u * x, -u * y, -u])\n        rows.append([0, 0, 0, x, y, 1, -v * x, -v * y, -v])\n    _, _, vt = np.linalg.svd(np.array(rows))\n    guess = np.linalg.inv(t_dst) @ vt[-1].reshape(3, 3) @ t_src\n    guess = guess / guess[2, 2]\n    fit = least_squares(\n        lambda p: (apply_homography(np.append(p, 1.0).reshape(3, 3), src) - dst).ravel(),\n        guess.ravel()[:8], method=\"lm\", max_nfev=20000)\n    return apply_homography(np.append(fit.x, 1.0).reshape(3, 3), src)\n\ndef rms(predicted, target):\n    return float(np.sqrt(((predicted - target) ** 2).sum(1).mean()))\n\nMODELS = [(\"similarity\", 4, fit_similarity), (\"affine\", 6, fit_affine),\n          (\"projective\", 8, fit_projective)]\n\nprint(f\"{'onto frame 1':>14}\" + \"\".join(f\"{n + f' ({d})':>15}\" for n, d, _ in MODELS))\ntotals = {name: [] for name, _, _ in MODELS}\nfor j in range(1, 5):\n    line = f\"{'frame ' + str(j + 1):>14}\"\n    for name, _, fit in MODELS:\n        value = rms(fit(X[j], X[0]), X[0])\n        totals[name].append(value)\n        line += f\"{value:15.2f}\"\n    print(line)\nprint(f\"\\n{'mean':>14}\" + \"\".join(f\"{np.mean(v):15.2f}\" for v in totals.values()) + \"   px\")\n``````\n\n::: {.cell-output .cell-output-stdout}\n```\n  onto frame 1 similarity (4)     affine (6) projective (8)\n       frame 2           7.14           4.79           2.76\n       frame 3          14.20           9.73           8.03\n       frame 4          15.78          10.56           8.78\n       frame 5          12.96           7.84           7.20\n\n          mean          12.52           8.23           6.69   px\n```\n:::\n:::\n\n\n**Noise floor:** RMS between two independent ±5 px jittered copies of the same frame (true difference = 0).\n\n::: {#ladder-floor .cell execution_count=8}\n``` {.python .cell-code}\nrng = np.random.default_rng(1)\n\nprint(f\"{'':12}{'observed':>10}{'noise floor':>13}{'ratio':>8}\")\nfor name, _, fit in MODELS:\n    scores = []\n    for base in X:\n        for _ in range(120):\n            a = base + rng.normal(0, 5, base.shape)\n            b = base + rng.normal(0, 5, base.shape)\n            scores.append(rms(fit(a, b), b))\n    floor, seen = float(np.mean(scores)), float(np.mean(totals[name]))\n    print(f\"{name:12}{seen:10.2f}{floor:13.2f}{seen / floor:7.1f}x\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              observed  noise floor   ratio\nsimilarity       12.52         7.93    1.6x\naffine            8.23         6.68    1.2x\nprojective        6.69         5.75    1.2x\n```\n:::\n:::\n\n\nLadder results (observed / noise floor):\n\n- Similarity: 12.5 / 7.9 px — above floor (confirms nose-angle test).\n- Affine: 8.2 / 6.7 px — near floor.\n- Projective: 6.7 / 5.8 px — no improvement over affine on six landmarks.\n\n**Reading:** weak perspective holds; affine is the smallest adequate model for these photographs.\n\n## Affine quotient\n\nCompare shapes up to affine maps, not similarity.\n\n**Trap:** swapping GPA rotation for iterative affine fit collapses configurations (aspect ratio → 0.0002; false 74% viewpoint share).\n\n::: {.callout-warning}\n## Iterating affine fits to a mean is not affine Procrustes\n\nUnit centroid size prevents shrink-to-point but not flatten-to-line. Check aspect ratio before trusting the residual.\n:::\n\n**Closed-form fix:** centre, SVD-whiten to isotropic second moment (`remove_affine`). Any affine image shares the same canonical form.\n\n::: {#whiten .cell execution_count=9}\n``` {.python .cell-code}\ndef remove_affine(config):\n    \"\"\"Map a configuration to its affine-invariant canonical form.\"\"\"\n    centred = config - config.mean(axis=0)\n    u, _, _ = np.linalg.svd(centred, full_matrices=False)\n    whitened = u * np.sqrt(len(config))     # singular values replaced by 1\n    return whitened / np.linalg.norm(whitened)\n\naffine_aligned, affine_mean = gpa(X, prepare=remove_affine)\naffine_residual = np.linalg.norm(affine_aligned - affine_mean, axis=(1, 2))\naffine_ss = float((affine_residual ** 2).sum())\n\naspect = [np.divide(*np.linalg.svd(c, compute_uv=False)[::-1]) for c in affine_aligned]\nprint(f\"aspect ratio of the aligned configurations: {np.mean(aspect):.3f}  (1.0 = no collapse)\")\nprint(f\"\\nProcrustes SS, similarity quotient: {similarity_ss:.5f}\")\nprint(f\"Procrustes SS, affine quotient    : {affine_ss:.5f}\")\nprint(f\"share of shape variation the viewpoint explains: {100 * (1 - affine_ss / similarity_ss):.1f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\naspect ratio of the aligned configurations: 1.000  (1.0 = no collapse)\n\nProcrustes SS, similarity quotient: 0.11100\nProcrustes SS, affine quotient    : 0.06839\nshare of shape variation the viewpoint explains: 38.4%\n```\n:::\n:::\n\n\nAffine quotient removes 38% of similarity SS. Aspect ratio stays 1.0 (no collapse).\n\n## Digitisation noise floor\n\nSimulate zero true shape difference: replicate one frame five times, jitter landmarks ($\\sigma$ px), measure Procrustes SS.\n\nGaussian $\\sigma = 5$ is slightly pessimistic vs ±5 px bound (RMS displacement ≈ 7 px).\n\n::: {#noise-floor .cell execution_count=10}\n``` {.python .cell-code}\nrng = np.random.default_rng(0)\n\ndef procrustes_ss(configs, prepare):\n    aligned, mean = gpa(configs, prepare=prepare)\n    return float((np.linalg.norm(aligned - mean, axis=(1, 2)) ** 2).sum())\n\n# Every frame gets a turn as the base. Which one you pick matters: the flattest\n# sails amplify jitter under the affine quotient, so a single base frame can\n# understate the floor by a factor of three.\nprint(f\"{'sigma':>7}{'similarity SS':>26}{'affine SS':>26}\")\nfor sigma in [2, 3, 5, 8]:\n    per_base = np.array([\n        [np.mean([procrustes_ss(base + rng.normal(0, sigma, (5,) + base.shape), prepare)\n                  for _ in range(300)])\n         for prepare in (centre_and_scale, remove_affine)]\n        for base in X\n    ])\n    cells = \"\".join(\n        f\"{per_base[:, k].mean():14.4f}  [{per_base[:, k].min():.4f}-{per_base[:, k].max():.4f}]\"\n        for k in (0, 1))\n    print(f\"{sigma:5.0f}px{cells}\")\n\nprint(f\"\\n{'observed':>7}{similarity_ss:14.4f}{'':15}{affine_ss:14.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  sigma             similarity SS                 affine SS\n    2px        0.0052  [0.0037-0.0063]        0.0068  [0.0031-0.0102]\n    3px        0.0115  [0.0081-0.0145]        0.0151  [0.0073-0.0223]\n    5px        0.0323  [0.0221-0.0409]        0.0418  [0.0197-0.0629]\n    8px        0.0806  [0.0553-0.0989]        0.1075  [0.0505-0.1623]\n\nobserved        0.1110                       0.0684\n```\n:::\n:::\n\n\nResults ($\\sigma = 5$):\n\n- Similarity: observed 0.111 vs floor 0.032 (3.5×) — failure not explained by digitisation.\n- Affine: observed 0.068 vs floor 0.042 (1.6×); worst base frame 1.1×; at $\\sigma = 8$ floor exceeds observed.\n\n**Conclusion:**\n\n- Similarity quotient is wrong for these photographs.\n- Affine quotient removes real viewpoint variation.\n- Residual after affine is within digitisation noise; sail billow cannot be resolved with six hand-placed landmarks.\n\n## R shapes package cross-check\n\nIan Dryden's [`shapes`](https://cran.r-project.org/package=shapes): `procGPA`, `riemdist`, `tpsgrid`, `shapepca`.\n\nR script (pre-run, committed figures): [`src/shapes_analysis.R`](https://github.com/project-delphi/ml-blog/blob/main/posts/kite-shape-analysis/src/shapes_analysis.R).\n\n\n```{r}\n#| eval: false\noptions(rgl.useNULL = TRUE)\nlibrary(shapes)\n\n# landmarks.csv -> the k x m x n array every shapes:: function expects\nX <- array(NA_real_, c(6, 2, 5))   # 6 landmarks, 2 coordinates, 5 frames\n\n# Quotient out similarity. reflect = TRUE because the sail is bilaterally\n# symmetric: no single photograph says which physical wing is which, so the\n# labelling is a free choice and should not count as shape difference.\nsim <- procGPA(X, scale = TRUE, reflect = TRUE)\n\n# Quotient out affine, in closed form -- see the callout above for why the\n# iterative version collapses.\nwhiten <- function(cfg) {\n  cfg <- scale(cfg, center = TRUE, scale = FALSE)\n  w <- svd(cfg)$u * sqrt(nrow(cfg))\n  w / sqrt(sum(w^2))\n}\naff <- procGPA(array(apply(X, 3, whiten), dim(X)), scale = TRUE, reflect = TRUE)\n\n# Pairwise Riemannian distance in Kendall shape space\nriemdist(X[, , 1], X[, , 2])\n\n# Deformation grids, mean shape -> each frame\ntpsgrid(sim$mshape, sim$rotated[, , 3], mag = 1, ngrid = 16, opt = 1)\n```\n\n::: {#r-agreement .cell execution_count=11}\n``` {.python .cell-code}\nimport json\n\nr = json.load(open(\"r_results.json\"))\nprint(f\"R {r['r_version']}, shapes {r['shapes_version']}\\n\")\nprint(f\"{'':22}{'R':>12}{'Python':>12}\")\nprint(f\"{'similarity SS':22}{r['similarity']['procrustes_ss']:12.5f}{similarity_ss:12.5f}\")\nprint(f\"{'affine SS':22}{r['affine']['procrustes_ss']:12.5f}{affine_ss:12.5f}\")\nprint(f\"{'uniform share':22}{100 * r['uniform_share']:11.1f}%{100 * (1 - affine_ss / similarity_ss):11.1f}%\")\n\nriem = np.array(r[\"riemannian\"])\nprint(\"\\npairwise Riemannian distance in shape space (R's riemdist):\")\nprint(np.round(riem, 3))\nprint(f\"\\nlargest: {riem.max():.3f} between frames \"\n      f\"{np.unravel_index(riem.argmax(), riem.shape)[0] + 1} and \"\n      f\"{np.unravel_index(riem.argmax(), riem.shape)[1] + 1}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR 4.0.5, shapes 1.2.6\n\n                                 R      Python\nsimilarity SS              0.11100     0.11100\naffine SS                  0.06839     0.06839\nuniform share                38.4%       38.4%\n\npairwise Riemannian distance in shape space (R's riemdist):\n[[0.    0.124 0.249 0.278 0.227]\n [0.124 0.    0.298 0.326 0.237]\n [0.249 0.298 0.    0.16  0.187]\n [0.278 0.326 0.16  0.    0.192]\n [0.227 0.237 0.187 0.192 0.   ]]\n\nlargest: 0.326 between frames 2 and 4\n```\n:::\n:::\n\n\nPython and R agree to five decimal places. Maximum pairwise Riemannian distance: 0.33.\n\n![`plotshapes` on the raw landmarks and after `procGPA`. Removing position, size and rotation\nbrings the five configurations onto one another — and the scatter still visible on the right is\nthe 0.111 the post has been quoting all along.](./fig-r-plotshapes.png)\n\n![Thin-plate splines carrying the mean shape onto each frame, after quotienting out **similarity** only. The grids have to absorb the entire viewpoint change, so they shear and bow across their whole width.](./fig-r-tps-raw.png)\n\n![The same splines after quotienting out **affine** maps. The global shear is gone and what remains is local and much milder — though, per the caveat above, most of it is digitising noise rather than the kite.](./fig-r-tps-rectified.png)\n\n## Photograph warping\n\nThin-plate spline (TPS) warps images using the same landmark maps as `tpsgrid`. Each frame transported to a shared panel by similarity and by affine map.\n\n\n```{r}\n#| eval: false\n# U(r) = r^2 log r^2, the 2D biharmonic kernel: the shape a thin metal plate\n# takes when pinned at the landmarks. Solving for an affine part plus one\n# radial term per landmark gives the smoothest map carrying every source\n# landmark exactly onto its target.\ntps_kernel <- function(d2) ifelse(d2 > 0, d2 * log(d2), 0)\n\ntps_fit <- function(src, dst) {\n  K <- tps_kernel(as.matrix(dist(src))^2)\n  P <- cbind(1, src)\n  L <- rbind(cbind(K, P), cbind(t(P), matrix(0, 3, 3)))\n  W <- solve(L, rbind(dst, matrix(0, 3, 2)))\n  list(src = src, w = W[seq_len(nrow(src)), ], a = W[nrow(src) + 1:3, ])\n}\n\ntps_apply <- function(fit, pts) {\n  d2 <- outer(pts[, 1], fit$src[, 1], \"-\")^2 + outer(pts[, 2], fit$src[, 2], \"-\")^2\n  cbind(1, pts) %*% fit$a + tps_kernel(d2) %*% fit$w\n}\n\n# Warping an image is the same map run backwards: for every output pixel, ask\n# where in the original photograph it came from, then sample there.\nwarp <- function(photo, from, to) {\n  sample_image(photo, tps_apply(tps_fit(to, from), output_grid))\n}\n```\n\n\nThe static version first, because it carries the finding on its own and an animation should never\nbe the only copy of a result.\n\n![Five photographs of one kite. Top: a plain window on each photograph, the same size in source\npixels every time, centred on the kite so it stays in frame — orientation and relative size\nuntouched. Middle: transported into a shared frame by the best similarity map. Bottom: by the best\naffine map.](./fig-r-warped-stack.png)\n\n- Top row: cropped source windows.\n- Middle: similarity transport.\n- Bottom: affine transport. Middle-to-bottom change is small visually despite 38% SS reduction.\n\n### TPS extrapolation limits\n\nStreamers smear outside the six-landmark hull. TPS interpolates inside; extrapolates (unreliably) outside. Streamers are non-rigid and lack correspondence.\n\n### Morph animation\n\n![Five photographs morphing through a common frame, aligned by similarity (left) and by affine\n(right). The white dashed hexagon is the mean shape, fixed in both panels. Spikes run from each\nmean landmark to where that frame's landmark actually lands, **drawn at three times life size** —\n`tpsgrid` has a `mag` argument for the same reason. Shorter spikes on the right are the affine\nmap's 28% improvement in landmark registration.](./fig-r-morph.gif)\n\nPixel SD across aligned frames: 0.127 (similarity) vs 0.128 (affine) on sail bounding box — visually indistinguishable. Landmark registration improves 7.0 → 5.1 px (25%); too small to see without magnification.\n\n## Summary\n\nKendall shape analysis removes only the nuisance group specified.\n\n- Similarity (translation, scale, rotation) is insufficient for field photographs with perspective.\n- Diagnostic checks: invariant angles, model ladder with noise floors, digitisation simulation, pixel warping.\n- Affine quotient fits these data; residual after affine is within ±5 px landmark noise.\n\n## References\n\n- Dryden, I. L., and Mardia, K. V. (2016). *Statistical Shape Analysis, with Applications in R*, 2nd ed. Wiley.\n- [`shapes` R package](https://cran.r-project.org/package=shapes) (Ian Dryden).\n- Kalia, R. [Kendall shape analysis](../kendall-shape-analysis/index.qmd) — method background on synthetic pencils and optic nerve heads.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}