<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-07-22">

<title>Two Ways to Expand the Space: Persistent Homology and Kernel SVMs on the Same Toy Dataset – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Two Ways to Expand the Space: Persistent Homology and Kernel SVMs on the Same Toy Dataset</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Topology</div>
                <div class="quarto-category">TDA</div>
                <div class="quarto-category">Support Vector Machines</div>
                <div class="quarto-category">Kernel Methods</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 22, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#one-dataset-a-disk-inside-a-ring-built-to-have-exactly-one-hole" id="toc-one-dataset-a-disk-inside-a-ring-built-to-have-exactly-one-hole" class="nav-link active" data-scroll-target="#one-dataset-a-disk-inside-a-ring-built-to-have-exactly-one-hole">One dataset: a disk inside a ring, built to have exactly one hole</a></li>
  <li><a href="#lens-1-persistent-homology-finds-the-hole-without-being-told-there-is-one" id="toc-lens-1-persistent-homology-finds-the-hole-without-being-told-there-is-one" class="nav-link" data-scroll-target="#lens-1-persistent-homology-finds-the-hole-without-being-told-there-is-one">Lens 1: persistent homology finds the hole without being told there is one</a>
  <ul class="collapse">
  <li><a href="#growing-the-space-one-radius-at-a-time" id="toc-growing-the-space-one-radius-at-a-time" class="nav-link" data-scroll-target="#growing-the-space-one-radius-at-a-time">Growing the space one radius at a time</a></li>
  <li><a href="#the-one-real-loop-outlives-the-fakes-by-a-factor-of-four" id="toc-the-one-real-loop-outlives-the-fakes-by-a-factor-of-four" class="nav-link" data-scroll-target="#the-one-real-loop-outlives-the-fakes-by-a-factor-of-four">The one real loop outlives the fakes by a factor of four</a></li>
  </ul></li>
  <li><a href="#lens-2-the-kernel-svm-finds-a-boundary-by-making-the-space-bigger" id="toc-lens-2-the-kernel-svm-finds-a-boundary-by-making-the-space-bigger" class="nav-link" data-scroll-target="#lens-2-the-kernel-svm-finds-a-boundary-by-making-the-space-bigger">Lens 2: the kernel SVM finds a boundary, by making the space bigger</a>
  <ul class="collapse">
  <li><a href="#the-straight-line-fails-and-not-for-want-of-tuning" id="toc-the-straight-line-fails-and-not-for-want-of-tuning" class="nav-link" data-scroll-target="#the-straight-line-fails-and-not-for-want-of-tuning">The straight line fails, and not for want of tuning</a></li>
  <li><a href="#expanding-the-space-by-hand-one-extra-coordinate" id="toc-expanding-the-space-by-hand-one-extra-coordinate" class="nav-link" data-scroll-target="#expanding-the-space-by-hand-one-extra-coordinate">Expanding the space by hand: one extra coordinate</a></li>
  <li><a href="#the-kernel-trick-get-the-lift-without-ever-building-it" id="toc-the-kernel-trick-get-the-lift-without-ever-building-it" class="nav-link" data-scroll-target="#the-kernel-trick-get-the-lift-without-ever-building-it">The kernel trick: get the lift without ever building it</a></li>
  </ul></li>
  <li><a href="#the-agreement-is-a-property-of-this-dataset-not-of-the-two-methods" id="toc-the-agreement-is-a-property-of-this-dataset-not-of-the-two-methods" class="nav-link" data-scroll-target="#the-agreement-is-a-property-of-this-dataset-not-of-the-two-methods">The agreement is a property of this dataset, not of the two methods</a></li>
  <li><a href="#both-are-the-same-move-stop-fixing-the-model-fix-the-coordinates" id="toc-both-are-the-same-move-stop-fixing-the-model-fix-the-coordinates" class="nav-link" data-scroll-target="#both-are-the-same-move-stop-fixing-the-model-fix-the-coordinates">Both are the same move: stop fixing the model, fix the coordinates</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways">Key Takeaways</a>
  <ul class="collapse">
  <li><a href="#questions-for-reflection" id="toc-questions-for-reflection" class="nav-link" data-scroll-target="#questions-for-reflection">Questions for Reflection</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tda-vs-svm-expanding-the-space/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Two Ways to Expand the Space: Persistent Homology and Kernel SVMs on the Same Toy Dataset</figcaption>
</figure>
</div>
<p>Draw a blob of points, then draw a ring of points around it, and try to separate the two groups with a straight line. You cannot. It takes about four seconds to convince yourself: wherever you put the line, the ring wraps around behind it and lands on both sides. The obstruction is not that the line is in the wrong place. It is that the ring encircles the blob, and no straight cut through the plane respects “encircles”.</p>
<p>Two tools that look nothing alike deal with this without complaint. <strong>Persistent homology</strong> — the machinery for finding holes — is handed the points with no labels at all and reports that there is one big hole here. A <strong>kernel support vector machine</strong> is handed the same points <em>with</em> their labels and draws a curve that separates them perfectly.</p>
<p>Neither of them fits a curved line in the plane. Both do the same thing instead: lift the data into a bigger space where the problem stops being curved, solve the easy version there, and read the answer back. The vocabularies could not be less alike, and the move underneath them is the same one.</p>
<section id="one-dataset-a-disk-inside-a-ring-built-to-have-exactly-one-hole" class="level2">
<h2 class="anchored" data-anchor-id="one-dataset-a-disk-inside-a-ring-built-to-have-exactly-one-hole">One dataset: a disk inside a ring, built to have exactly one hole</h2>
<p>The data is synthetic, and the reason is that the answer has to be known in advance for the comparison to mean anything. There is exactly one hole in this point cloud because I put it there, so any second feature persistent homology reports is noise I can name, and the SVM’s boundary can be checked against a circle whose radius I already know.</p>
<p>The generating process is two draws. A hundred points land uniformly inside a disk of radius 0.35 around the origin, labelled class 0. A hundred and forty more land on a circle of radius 1.0, each pushed in or out by Gaussian noise with standard deviation 0.06, labelled class 1. Together they are one point cloud <span class="math inline">\(X \subset \mathbb{R}^2\)</span> of 240 points with two labels, and the empty annulus between radius 0.35 and radius 1.0 is the hole.</p>
<p>What it stands in for is any two-class problem where one class surrounds the other rather than sitting beside it — a normal operating regime ringed by fault conditions in every direction, a healthy range with abnormal values on both sides of it. Those are common, and they are exactly the cases where a linear model fails for a reason that has nothing to do with tuning.</p>
<div id="819c343a" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_disk_and_ring(n_inside<span class="op">=</span><span class="dv">100</span>, n_ring<span class="op">=</span><span class="dv">140</span>, r_inside<span class="op">=</span><span class="fl">0.35</span>, r_ring<span class="op">=</span><span class="fl">1.0</span>, ring_noise<span class="op">=</span><span class="fl">0.06</span>, seed<span class="op">=</span><span class="dv">7</span>):</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    theta_in <span class="op">=</span> rng.uniform(<span class="dv">0</span>, <span class="dv">2</span> <span class="op">*</span> np.pi, n_inside)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    r_in <span class="op">=</span> r_inside <span class="op">*</span> np.sqrt(rng.uniform(<span class="dv">0</span>, <span class="dv">1</span>, n_inside))</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    inside <span class="op">=</span> np.column_stack([r_in <span class="op">*</span> np.cos(theta_in), r_in <span class="op">*</span> np.sin(theta_in)])</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    theta_out <span class="op">=</span> rng.uniform(<span class="dv">0</span>, <span class="dv">2</span> <span class="op">*</span> np.pi, n_ring)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    r_out <span class="op">=</span> r_ring <span class="op">+</span> rng.normal(<span class="dv">0</span>, ring_noise, n_ring)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    ring <span class="op">=</span> np.column_stack([r_out <span class="op">*</span> np.cos(theta_out), r_out <span class="op">*</span> np.sin(theta_out)])</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> np.vstack([inside, ring])</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.concatenate([np.zeros(n_inside), np.ones(n_ring)]).astype(<span class="bu">int</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> X, y</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>X, y <span class="op">=</span> make_disk_and_ring()</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">5</span>))</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>ax.scatter(<span class="op">*</span>X[y <span class="op">==</span> <span class="dv">0</span>].T, s<span class="op">=</span><span class="dv">18</span>, color<span class="op">=</span><span class="st">"tab:blue"</span>, label<span class="op">=</span><span class="st">"inside (class 0)"</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>ax.scatter(<span class="op">*</span>X[y <span class="op">==</span> <span class="dv">1</span>].T, s<span class="op">=</span><span class="dv">18</span>, color<span class="op">=</span><span class="st">"tab:red"</span>, label<span class="op">=</span><span class="st">"ring (class 1)"</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"The toy dataset: 100 points inside, 140 on a noisy ring"</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"upper right"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-2-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This is the same shape of problem as <code>sklearn.datasets.make_circles</code>, deliberately, but framed as one filled blob inside one hollow ring rather than as two thin rings. The filled inner blob is what keeps the hole story clean: with two thin rings there would be two loops to talk about, and the argument would need a paragraph of bookkeeping it does not deserve. Everything from here on uses this exact <code>X</code> and <code>y</code>. No new dataset appears.</p>
</section>
<section id="lens-1-persistent-homology-finds-the-hole-without-being-told-there-is-one" class="level2">
<h2 class="anchored" data-anchor-id="lens-1-persistent-homology-finds-the-hole-without-being-told-there-is-one">Lens 1: persistent homology finds the hole without being told there is one</h2>
<p>Forget the labels for this whole section. Persistent homology never sees them. It gets the 240 points and their pairwise distances, and nothing else.</p>
<section id="growing-the-space-one-radius-at-a-time" class="level3">
<h3 class="anchored" data-anchor-id="growing-the-space-one-radius-at-a-time">Growing the space one radius at a time</h3>
<p>The trick is to refuse to pick a scale. Fix a radius <span class="math inline">\(\varepsilon \geq 0\)</span> and join every pair of points closer together than <span class="math inline">\(\varepsilon\)</span>; now let <span class="math inline">\(\varepsilon\)</span> grow from <span class="math inline">\(0\)</span> upward. Edges only ever get added, never removed, so what you get is not one picture of the data but a nested tower of them — the same 240 points connected up at every scale at once, instead of at one scale somebody had to guess. That tower is the <strong>Vietoris-Rips filtration</strong>, and the objects in it are <em>simplicial complexes</em>: graphs that also fill in their triangles and higher patches, so that a closed loop of edges can be distinguished from a loop that something has plugged.</p>
<p>This is the “expanded space” of the post’s title, in its first of two forms.</p>
<div id="17bd172d" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> itertools <span class="im">import</span> combinations</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_edges(points, eps, ax, colors<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(points)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    dists <span class="op">=</span> np.linalg.norm(points[:, <span class="va">None</span>] <span class="op">-</span> points[<span class="va">None</span>, :], axis<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, j <span class="kw">in</span> combinations(<span class="bu">range</span>(n), <span class="dv">2</span>):</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> dists[i, j] <span class="op">&lt;=</span> eps:</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>            ax.plot(<span class="op">*</span><span class="bu">zip</span>(points[i], points[j]), color<span class="op">=</span><span class="st">"tab:purple"</span>, lw<span class="op">=</span><span class="fl">0.5</span>, alpha<span class="op">=</span><span class="fl">0.5</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    c <span class="op">=</span> colors <span class="cf">if</span> colors <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="cf">else</span> <span class="st">"black"</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    ax.scatter(points[:, <span class="dv">0</span>], points[:, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">6</span>, zorder<span class="op">=</span><span class="dv">2</span>, c<span class="op">=</span>c, cmap<span class="op">=</span><span class="st">"coolwarm"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"$</span><span class="ch">\\</span><span class="ss">varepsilon$ = </span><span class="sc">{</span>eps<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(<span class="op">-</span><span class="fl">1.4</span>, <span class="fl">1.4</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    ax.set_ylim(<span class="op">-</span><span class="fl">1.4</span>, <span class="fl">1.4</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks([])</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    ax.set_yticks([])</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">4</span>))</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, eps <span class="kw">in</span> <span class="bu">zip</span>(axes, [<span class="fl">0.05</span>, <span class="fl">0.15</span>, <span class="fl">0.4</span>, <span class="fl">0.8</span>]):</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    plot_edges(X, eps, ax, colors<span class="op">=</span>y)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-3-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Two counts describe each panel. <span class="math inline">\(\beta_0\)</span> is the number of separate pieces the points have been knitted into, and <span class="math inline">\(\beta_1\)</span> is the number of independent loops — closed rings of edges with nothing filling them in. Both come from the same <code>ripser</code> computation the next section runs, evaluated at these four radii. Reading left to right:</p>
<ul>
<li><span class="math inline">\(\varepsilon = 0.05\)</span>: almost nothing connects yet — 120 separate components, no loops. Too fine a scale to see any structure.</li>
<li><span class="math inline">\(\varepsilon = 0.15\)</span>: local neighborhoods have linked up (12 components), but there are 5 small, short-lived loops — artifacts of exactly which nearby points happened to connect first, not real structure.</li>
<li><span class="math inline">\(\varepsilon = 0.4\)</span>: the ring has consolidated into one single loop that closes all the way around (<span class="math inline">\(\beta_1 = 1\)</span>), while the disk has become one solid, hole-free blob. Ring and disk are still two separate components (<span class="math inline">\(\beta_0 = 2\)</span>) — not yet close enough to touch.</li>
<li><span class="math inline">\(\varepsilon = 0.8\)</span>: ring and disk have merged into one component, the gap between them has filled in with edges and triangles, and the loop is gone (<span class="math inline">\(\beta_1 = 0\)</span>). The whole thing is now one contractible blob.</li>
</ul>
<p>The loop present at <span class="math inline">\(\varepsilon = 0.4\)</span> and gone by <span class="math inline">\(\varepsilon = 0.8\)</span> is the empty annulus between the disk and the ring — the hole this dataset was built to have. The five loops at <span class="math inline">\(\varepsilon = 0.15\)</span> are not that hole. They are sampling noise, gaps that happen to close a moment after they open.</p>
<p>So a snapshot at any single radius is not enough: at <span class="math inline">\(\varepsilon = 0.15\)</span> you would count six loops and believe five lies. What separates them is not where they are but how long they last, and that is the one thing a single snapshot cannot report.</p>
</section>
<section id="the-one-real-loop-outlives-the-fakes-by-a-factor-of-four" class="level3">
<h3 class="anchored" data-anchor-id="the-one-real-loop-outlives-the-fakes-by-a-factor-of-four">The one real loop outlives the fakes by a factor of four</h3>
<p>Tracking every loop from the radius where it opens to the radius where it closes gives each one a birth, a death, and a lifetime. Plot each as a point at (birth, death) and the picture sorts itself out: everything sits above the diagonal, since nothing closes before it opens, and the vertical distance from the diagonal is exactly the lifetime. Noise clings to the line. Real structure floats. That plot is the <strong>persistence diagram</strong>, and it is where the sweep across all scales gets cashed in.</p>
<div id="05274a6c" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ripser <span class="im">import</span> ripser</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> persim <span class="im">import</span> plot_diagrams</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>dgms <span class="op">=</span> ripser(X, maxdim<span class="op">=</span><span class="dv">1</span>)[<span class="st">"dgms"</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>h1 <span class="op">=</span> dgms[<span class="dv">1</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>lifetimes <span class="op">=</span> h1[:, <span class="dv">1</span>] <span class="op">-</span> h1[:, <span class="dv">0</span>]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>top <span class="op">=</span> h1[np.argmax(lifetimes)]</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">5</span>))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>plot_diagrams(dgms, ax<span class="op">=</span>ax, show<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>ax.annotate(</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"the hole</span><span class="ch">\n</span><span class="st">(disk/ring gap)"</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    xy<span class="op">=</span>(top[<span class="dv">0</span>], top[<span class="dv">1</span>]), xytext<span class="op">=</span>(top[<span class="dv">0</span>] <span class="op">-</span> <span class="fl">0.15</span>, top[<span class="dv">1</span>] <span class="op">+</span> <span class="fl">0.55</span>),</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span><span class="st">"black"</span>), fontsize<span class="op">=</span><span class="dv">9</span>,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Persistence diagram (H0 = components, H1 = loops)"</span>)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"longest-lived H1 feature: born </span><span class="sc">{</span>top[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">, dies </span><span class="sc">{</span>top[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">, lifetime </span><span class="sc">{</span>lifetimes<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"next-longest H1 lifetime: </span><span class="sc">{</span>np<span class="sc">.</span>sort(lifetimes)[<span class="op">-</span><span class="dv">2</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>longest-lived H1 feature: born 0.291, dies 0.645, lifetime 0.354
next-longest H1 lifetime: 0.089</code></pre>
</div>
</div>
<p>One <span class="math inline">\(H_1\)</span> point sits far above the diagonal. Every other one — all the transient micro-loops from the <span class="math inline">\(\varepsilon = 0.15\)</span> panel — hugs it. The real loop lives across a span of radii roughly four times the runner-up’s, 0.354 against 0.089, and that ratio is the whole signal. Nobody told persistent homology to look for one hole in the middle. It swept every scale, recorded how long each loop lasted, and the real one outlasted the fakes.</p>
<p>Notice what the computation never touched: the labels. Persistent homology describes the shape of the point cloud on its own terms, with no task attached — which also means it will never tell you which points are which class. For that, we have to start over with a method that does nothing else.</p>
</section>
</section>
<section id="lens-2-the-kernel-svm-finds-a-boundary-by-making-the-space-bigger" class="level2">
<h2 class="anchored" data-anchor-id="lens-2-the-kernel-svm-finds-a-boundary-by-making-the-space-bigger">Lens 2: the kernel SVM finds a boundary, by making the space bigger</h2>
<p>Now bring the labels back. This section drops the persistence machinery entirely and asks a different question of the same 240 points: given the labels, what rule separates the two classes?</p>
<section id="the-straight-line-fails-and-not-for-want-of-tuning" class="level3">
<h3 class="anchored" data-anchor-id="the-straight-line-fails-and-not-for-want-of-tuning">The straight line fails, and not for want of tuning</h3>
<p>Start with the classifier that has no curve available to it at all. A linear support vector machine looks for the single straight line that best splits the two classes, so it is the cleanest way to show that the obstruction is structural rather than a matter of fitting harder.</p>
<div id="8e640207" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.svm <span class="im">import</span> LinearSVC</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>linear <span class="op">=</span> LinearSVC(max_iter<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>linear.fit(X, y)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"linear SVM training accuracy: </span><span class="sc">{</span>linear<span class="sc">.</span>score(X, y)<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>linear SVM training accuracy: 0.58</code></pre>
</div>
</div>
<p>The linear SVM scores 0.58 on the data it was trained on, and that number is worse than it looks. There are 140 ring points out of 240, so calling every single point “ring” and going home scores 0.583. The fitted line has bought precisely nothing over the do-nothing classifier.</p>
<p>That is structural, not a tuning failure. The ring surrounds the disk symmetrically, so <em>any</em> line with some disk points on one side has ring points mixed in on that same side — the ring comes round the back. No slope and no offset fixes it, because the problem is not where the line is.</p>
</section>
<section id="expanding-the-space-by-hand-one-extra-coordinate" class="level3">
<h3 class="anchored" data-anchor-id="expanding-the-space-by-hand-one-extra-coordinate">Expanding the space by hand: one extra coordinate</h3>
<p>So change what the classifier is looking at instead of how hard it looks. This is the classic fix and the seed of the whole kernel trick: leave the classifier linear, and give it a space in which a line is enough. Map every point <span class="math inline">\(x = (x_1, x_2)\)</span> to</p>
<p><span class="math display">\[
\phi(x) = \left(x_1,\ x_2,\ x_1^2 + x_2^2\right) \in \mathbb{R}^3.
\]</span></p>
<p>The third coordinate is squared distance from the origin. It is cheap to compute, and it is exactly the quantity that tells disk points (<span class="math inline">\(x_1^2+x_2^2\)</span> small) from ring points (<span class="math inline">\(x_1^2+x_2^2 \approx 1\)</span>). Picture the disk points staying put while the ring points get hoisted upward out of the plane: two flat sheets at different heights, with room for a plane between them.</p>
<div id="9cca5f80" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> mpl_toolkits.mplot3d <span class="im">import</span> Axes3D  <span class="co"># noqa: F401</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.svm <span class="im">import</span> LinearSVC</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>Z <span class="op">=</span> np.column_stack([X[:, <span class="dv">0</span>], X[:, <span class="dv">1</span>], X[:, <span class="dv">0</span>] <span class="op">**</span> <span class="dv">2</span> <span class="op">+</span> X[:, <span class="dv">1</span>] <span class="op">**</span> <span class="dv">2</span>])</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>lifted <span class="op">=</span> LinearSVC(max_iter<span class="op">=</span><span class="dv">10000</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>lifted.fit(Z, y)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"linear SVM on phi(x), training accuracy: </span><span class="sc">{</span>lifted<span class="sc">.</span>score(Z, y)<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"separating-plane coefficients (x1, x2, x1^2+x2^2): </span><span class="sc">{</span>lifted<span class="sc">.</span>coef_<span class="sc">.</span><span class="bu">round</span>(<span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">5</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> fig.add_subplot(projection<span class="op">=</span><span class="st">"3d"</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>ax.scatter(<span class="op">*</span>Z[y <span class="op">==</span> <span class="dv">0</span>].T, s<span class="op">=</span><span class="dv">12</span>, color<span class="op">=</span><span class="st">"tab:blue"</span>, label<span class="op">=</span><span class="st">"inside"</span>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>ax.scatter(<span class="op">*</span>Z[y <span class="op">==</span> <span class="dv">1</span>].T, s<span class="op">=</span><span class="dv">12</span>, color<span class="op">=</span><span class="st">"tab:red"</span>, label<span class="op">=</span><span class="st">"ring"</span>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"$x_1$"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"$x_2$"</span>)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>ax.set_zlabel(<span class="st">"$x_1^2+x_2^2$"</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="vs">r"$\phi(x) = (x_1, x_2, x_1^2+x_2^2)$: now linearly separable"</span>)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>linear SVM on phi(x), training accuracy: 1.00
separating-plane coefficients (x1, x2, x1^2+x2^2): [[0.016 0.02  2.53 ]]</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The lift works, and the fitted plane says why in its coefficients. The weight on <span class="math inline">\(x_1^2+x_2^2\)</span> is 2.53 against 0.016 and 0.020 on <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, so the plane is barely tilted at all — it is a threshold on squared radius wearing a plane’s clothes, dividing “closer than <span class="math inline">\(r\)</span> from the origin” from “farther than <span class="math inline">\(r\)</span>”. Training accuracy goes to 1.00. A curved boundary in the plane became a flat one in three dimensions, for the price of one well-chosen coordinate.</p>
<p>That price is the catch. It was well-chosen because I already knew the data was radially structured, and there is no such coordinate lying around when you do not.</p>
</section>
<section id="the-kernel-trick-get-the-lift-without-ever-building-it" class="level3">
<h3 class="anchored" data-anchor-id="the-kernel-trick-get-the-lift-without-ever-building-it">The kernel trick: get the lift without ever building it</h3>
<p>Here is the way out, and it is one of the better ideas in machine learning. A support vector machine, it turns out, never needs the coordinates of the lifted points. Every step of fitting one can be written using only the <em>inner products</em> between pairs of lifted points — a number saying how aligned two points are in the new space. So if you can compute that number directly from the original two coordinates, you never have to build the lift at all.</p>
<p>A function that hands you those inner products directly is a <strong>kernel</strong>: <span class="math inline">\(k(x, x') = \langle \phi(x), \phi(x') \rangle\)</span>, a similarity score that behaves as if some feature map <span class="math inline">\(\phi\)</span> had been applied first, without <span class="math inline">\(\phi(x)\)</span> ever being computed for a single point. Since nothing is ever materialized, <span class="math inline">\(\phi\)</span> is free to be enormous. The RBF kernel,</p>
<p><span class="math display">\[
k(x, x') = \exp\!\left(-\gamma \lVert x - x' \rVert^2\right),
\]</span></p>
<p>corresponds to a <span class="math inline">\(\phi\)</span> with infinitely many coordinates — “RBF” for radial basis function, since it depends on the two points only through the distance between them. Fitting the SVM needs <span class="math inline">\(k(x_i, x_j)\)</span> for pairs of training points and nothing more, so the infinite dimension costs nothing. It is never written down.</p>
<div id="34090e21" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.svm <span class="im">import</span> SVC</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>rbf <span class="op">=</span> SVC(kernel<span class="op">=</span><span class="st">"rbf"</span>, C<span class="op">=</span><span class="fl">1.0</span>, gamma<span class="op">=</span><span class="fl">2.0</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>rbf.fit(X, y)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RBF-kernel SVM training accuracy: </span><span class="sc">{</span>rbf<span class="sc">.</span>score(X, y)<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"support vectors used: </span><span class="sc">{</span>rbf<span class="sc">.</span>n_support_<span class="sc">}</span><span class="ss"> (of </span><span class="sc">{</span><span class="bu">len</span>(X)<span class="sc">}</span><span class="ss"> points)"</span>)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>xx, yy <span class="op">=</span> np.meshgrid(np.linspace(<span class="op">-</span><span class="fl">1.5</span>, <span class="fl">1.5</span>, <span class="dv">300</span>), np.linspace(<span class="op">-</span><span class="fl">1.5</span>, <span class="fl">1.5</span>, <span class="dv">300</span>))</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>zz <span class="op">=</span> rbf.decision_function(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">5</span>))</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>ax.contourf(xx, yy, zz, levels<span class="op">=</span><span class="dv">20</span>, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, alpha<span class="op">=</span><span class="fl">0.55</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>ax.contour(xx, yy, zz, levels<span class="op">=</span>[<span class="dv">0</span>], colors<span class="op">=</span><span class="st">"black"</span>, linewidths<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>ax.contour(xx, yy, zz, levels<span class="op">=</span>[<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>], colors<span class="op">=</span><span class="st">"black"</span>, linewidths<span class="op">=</span><span class="fl">0.8</span>, linestyles<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>ax.scatter(<span class="op">*</span>X[y <span class="op">==</span> <span class="dv">0</span>].T, s<span class="op">=</span><span class="dv">16</span>, color<span class="op">=</span><span class="st">"tab:blue"</span>, edgecolor<span class="op">=</span><span class="st">"k"</span>, linewidth<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>ax.scatter(<span class="op">*</span>X[y <span class="op">==</span> <span class="dv">1</span>].T, s<span class="op">=</span><span class="dv">16</span>, color<span class="op">=</span><span class="st">"tab:red"</span>, edgecolor<span class="op">=</span><span class="st">"k"</span>, linewidth<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>ax.scatter(<span class="op">*</span>X[rbf.support_].T, s<span class="op">=</span><span class="dv">60</span>, facecolors<span class="op">=</span><span class="st">"none"</span>, edgecolors<span class="op">=</span><span class="st">"black"</span>, linewidth<span class="op">=</span><span class="fl">0.8</span>, label<span class="op">=</span><span class="st">"support vectors"</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"RBF-kernel SVM decision boundary"</span>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"upper right"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>RBF-kernel SVM training accuracy: 1.00
support vectors used: [8 9] (of 240 points)</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-7-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The RBF SVM was given the raw two coordinates and nothing else — no squared radius, no hint that the origin mattered — and it still lands on a boundary tracing almost exactly the circle the hand-built <span class="math inline">\(\phi\)</span> predicted, at 1.00 training accuracy, using 17 of the 240 points as support vectors. The kernel reproduced the useful part of that feature map from pairwise similarities alone.</p>
<p>So both lenses have now been run, and both found the circle. That agreement is worth being suspicious of.</p>
</section>
</section>
<section id="the-agreement-is-a-property-of-this-dataset-not-of-the-two-methods" class="level2">
<h2 class="anchored" data-anchor-id="the-agreement-is-a-property-of-this-dataset-not-of-the-two-methods">The agreement is a property of this dataset, not of the two methods</h2>
<p>The two methods reached the same place by routes with almost nothing in common, and the differences are easier to see side by side than in prose.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Persistent homology</th>
<th>Kernel SVM</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Uses the labels <code>y</code>?</td>
<td>No — entirely unsupervised</td>
<td>Yes — the boundary is fit to separate the two classes</td>
</tr>
<tr class="even">
<td>Object of study</td>
<td>The whole point cloud’s shape</td>
<td>One decision surface</td>
</tr>
<tr class="odd">
<td>Scale</td>
<td>Every <span class="math inline">\(\varepsilon\)</span> at once, kept in the diagram</td>
<td>One fixed, implicit scale (set by <span class="math inline">\(\gamma\)</span>)</td>
</tr>
<tr class="even">
<td>“Expanded space”</td>
<td>A growing sequence of simplicial complexes <span class="math inline">\(R_\varepsilon(X)\)</span></td>
<td>A single (implicit) feature space <span class="math inline">\(\phi(X)\)</span></td>
</tr>
<tr class="odd">
<td>Output</td>
<td>A multiset of (birth, death) pairs</td>
<td>A function <span class="math inline">\(f(x) = \text{sign}(\sum_i \alpha_i y_i\, k(x, x_i) + b)\)</span></td>
</tr>
<tr class="even">
<td>What “the hole” becomes</td>
<td>An <span class="math inline">\(H_1\)</span> generator, born <span class="math inline">\(\approx 0.29\)</span>, dies <span class="math inline">\(\approx 0.65\)</span></td>
<td>Never named — just the region where <span class="math inline">\(f(x)\)</span> changes sign</td>
</tr>
<tr class="odd">
<td>Guarantee</td>
<td>The diagram is provably stable to small perturbations of the points</td>
<td>The boundary provably maximizes margin on the training labels</td>
</tr>
</tbody>
</table>
<p>The two answers coincide here for one reason: I labelled the points to straddle the topological feature. Class 0 is inside the hole and class 1 is on its rim, so the boundary that separates the labels and the loop that bounds the hole are forced to live in almost the same place — both roughly tracing the circle <span class="math inline">\(x_1^2+x_2^2 = r^2\)</span> for some <span class="math inline">\(r\)</span> between 0.35 and 1.0.</p>
<p>Break that arrangement and the agreement goes. Shuffle the 240 labels at random and the RBF SVM will still find a boundary at high training accuracy, memorizing the noise through its support vectors, with no relationship to the disk-and-ring geometry whatsoever. The persistence diagram computed on those same points would not move by a single coordinate, because it never looked at a label in the first place.</p>
<p>That is the deeper divergence. Persistent homology asks what shapes are in this data, at every scale — a question about the data alone. The SVM asks what one rule separates these two groups — a question about the data <em>and</em> a task. TDA would still describe the hole if there were no classification problem at all. The SVM has nothing whatsoever to say without labels to fit.</p>
</section>
<section id="both-are-the-same-move-stop-fixing-the-model-fix-the-coordinates" class="level2">
<h2 class="anchored" data-anchor-id="both-are-the-same-move-stop-fixing-the-model-fix-the-coordinates">Both are the same move: stop fixing the model, fix the coordinates</h2>
<p>Strip the vocabularies away and one instinct is left in both. The data is tangled in the coordinates it arrived in, so do not fight the tangle — move to a richer space where it comes apart. Connectivity falls out in one case, a straight boundary in the other.</p>
<p><strong>TDA’s expansion</strong> is parameterized by a single scalar, <span class="math inline">\(\varepsilon\)</span>:</p>
<p><span class="math display">\[
X \;\longmapsto\; R_\varepsilon(X), \qquad \varepsilon: 0 \to \infty.
\]</span></p>
<p>Growing <span class="math inline">\(\varepsilon\)</span> literally adds structure to the space itself — first edges, then triangles, then higher simplices — turning a discrete, structureless point cloud into an actual topological object with holes and components that can be counted. Every value of <span class="math inline">\(\varepsilon\)</span> is kept; the persistence diagram is a record of the entire sweep.</p>
<p><strong>The SVM’s expansion</strong> is parameterized by a choice of kernel (and its hyperparameters, like <span class="math inline">\(\gamma\)</span>):</p>
<p><span class="math display">\[
x \;\longmapsto\; \phi(x) \in \mathcal{H}, \qquad k(x, x') = \langle \phi(x), \phi(x') \rangle.
\]</span></p>
<p>Lifting into <span class="math inline">\(\mathcal{H}\)</span> adds coordinates to each individual point — the hand-built <span class="math inline">\(x_1^2+x_2^2\)</span> being the simplest possible example — turning a curved decision problem into a linear one. Only one value of the kernel’s hyperparameters is kept; cross-validation picks the single expansion that generalizes best, and everything else is discarded.</p>
<p>One instinct — <em>the data isn’t the problem, the coordinates are; go find better coordinates</em> — pointed at two different goals. TDA expands the space to describe structure and keeps the whole multi-scale answer, because the shape at every scale is what is being studied. The SVM expands the space to draw one boundary and keeps only the boundary, because separating two classes is all that was asked. Each is right about what it discards: a persistence diagram that changed with the task would be a bug, and an SVM that tried to hold every scale at once would be underfit or overfit depending on which scale won.</p>
<p>Which is the answer to the puzzle we opened with. Two tools that share no vocabulary handled the same unseparable ring because neither of them tried to draw a curve. They went up a dimension instead — one by growing simplices until the hole showed itself, the other by adding a coordinate until a plane sufficed — and in the bigger space there was nothing left to curve around.</p>
</section>
<section id="key-takeaways" class="level2">
<h2 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h2>
<p>The short version, for anyone skimming back:</p>
<ul>
<li>The disk-and-ring dataset is not linearly separable in <span class="math inline">\(\mathbb{R}^2\)</span>, for a topological reason — a ring encircles a disk — that no straight line can respect. The linear SVM’s 0.58 is the majority-class rate, not a near miss.</li>
<li>Persistent homology, run on the unlabeled points, finds the hole through a Vietoris-Rips filtration: one <span class="math inline">\(H_1\)</span> feature lives about four times longer than any other loop in the diagram.</li>
<li>A kernel SVM, run on the labeled points, finds a decision boundary that traces almost the same circle, but does so by implicitly lifting each point into a richer feature space where a <em>linear</em> boundary suffices — never using the word “hole” or “loop” anywhere in the computation.</li>
<li>Both methods “expand the space” — TDA via a filtration parameter <span class="math inline">\(\varepsilon\)</span> swept over its whole range, kernels via an implicit feature map <span class="math inline">\(\phi\)</span> fixed at a single, chosen setting.</li>
<li>They diverge in what they keep: TDA keeps the full multi-scale record because structure is the answer; the SVM keeps a single boundary because classification is the answer.</li>
</ul>
<section id="questions-for-reflection" class="level3">
<h3 class="anchored" data-anchor-id="questions-for-reflection">Questions for Reflection</h3>
<p>Three places where this toy example was doing more work than it looked like:</p>
<ol type="1">
<li>If the labels on this dataset were randomized, the SVM would still find <em>some</em> boundary at high training accuracy. What would that reveal about the difference between “a boundary exists” and “a boundary means something”?</li>
<li>The polynomial-kernel feature map <span class="math inline">\(\phi(x) = (x_1, x_2, x_1^2+x_2^2)\)</span> was chosen by hand because we already knew the data was radially structured. What would happen with a kernel mismatched to the data’s actual shape — say, a linear kernel on data shaped like two interlocking spirals?</li>
<li>Persistence diagrams are stable under perturbation of the input points; SVM decision boundaries can move a lot if a single support vector is added or removed. Is that difference a fundamental one between unsupervised structure-finding and supervised boundary-fitting, or an artifact of these two specific methods?</li>
</ol>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tda-vs-svm-expanding-the-space/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>