{
  "hash": "0d8668329bab694a716e98e04532b80a",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Statistical Jackknife\"\nsubtitle: \"Leave out one observation at a time and a small-sample estimate stops lying to you. The same n passes that cancel its bias also name the single data point holding the answer up — a fraud ring's hub, a fragile drug target, a censored retention curve.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-08-18\"\ncategories: [Statistics, Resampling, Growth-Engineering, Bioinformatics, Python]\ntags: [jackknife, resampling, bias-correction, influence-function, survival-analysis, fraud-detection, genomics]\nimage: \"./cover.png\"\ndescription: \"Quenouille's bias eraser and Tukey's pseudovalues, worked through four examples: ratio bias in small cohorts, promo-abuse syndicates, censored survival regression, and clinical biomarker stability — with interactive widgets that run in the browser.\"\njupyter: jackknife-blog\nresources:\n  - widget-data\n  - cover.png\nexecute:\n  warning: false\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: show\n    theme: [zephyr, theme.scss]\n    fig-width: 8\n    fig-height: 4.5\n    fig-dpi: 150\n    number-sections: true\n---\n\n\n![](./cover.png){fig-alt=\"Cover card reading The Statistical Jackknife, over a solid purple background.\"}\n\n\n\n## Jackknife resampling\n\nThe **jackknife** leaves out one observation at a time ($n$ passes, deterministic).\n\nTwo uses:\n\n- **Bias correction** (Quenouille, 1949): cancels leading $O(1/n)$ bias in smooth estimators.\n- **Influence diagnostics** (Tukey): pseudovalues $J_i$ identify which observations move the estimate.\n\nAlternative: Efron's bootstrap (stochastic, more general for non-smooth statistics).\n\n::: {.callout-note appearance=\"default\"}\n## Name\n\nTukey (1958) named the method after a pocket **jackknife** — a general-purpose tool, not a parametric scalpel.\n:::\n\n## Ratio bias in small samples\n\n**Estimator:** revenue per visit = $\\bar{Y}/\\bar{X}$ (ratio of sample means).\n\n**Problem:** individually unbiased means produce a biased ratio; error is $O(1/n)$, largest at small $n$.\n\n**Synthetic data:**\n\n- Visits ~ Gamma(mean 10); revenue ~ Gamma(mean 25), independent.\n- True revenue-per-visit = 2.50.\n- Gamma: positive, right-skewed stand-in for spend and engagement counts.\n\n**Downstream use:** cohort payback metrics; positive bias flatters unprofitable channels.\n\n50,000 synthetic cohorts at each $n$; compare plug-in ratio vs jackknife-corrected ratio.\n\n::: {#3ce06e19 .cell execution_count=2}\n``` {.python .cell-code}\n# Synthetic cohorts: visits ~ Gamma(mean 10), revenue ~ Gamma(mean 25), drawn independently,\n# so revenue-per-visit is exactly 2.50 and any departure from it is bias, not noise.\nnp.random.seed(42)\n\ntrue_mu_x, true_mu_y = 10.0, 25.0\ntrue_ratio = true_mu_y / true_mu_x  # exactly 2.50\n\nsample_sizes = [5, 10, 20, 40, 80, 160]\nn_sims = 50_000\n\nplugin_biases = []\njackknife_biases = []\n\nfor n in sample_sizes:\n    x = np.random.gamma(shape=5.0, scale=2.0, size=(n_sims, n))   # visits,  mean 10\n    y = np.random.gamma(shape=5.0, scale=5.0, size=(n_sims, n))   # revenue, mean 25\n\n    # Plug-in estimate: ratio of the two sample means\n    plugin_est = np.mean(y, axis=1) / np.mean(x, axis=1)\n    plugin_biases.append(np.mean(plugin_est) - true_ratio)\n\n    # Leave-one-out: recompute the ratio n times, each time dropping one customer\n    sum_x = np.sum(x, axis=1, keepdims=True)\n    sum_y = np.sum(y, axis=1, keepdims=True)\n    r_i = ((sum_y - y) / (n - 1)) / ((sum_x - x) / (n - 1))\n    r_bar = np.mean(r_i, axis=1)\n\n    # Quenouille's recombination\n    jack_est = n * plugin_est - (n - 1) * r_bar\n    jackknife_biases.append(np.mean(jack_est) - true_ratio)\n\nfig, ax = plt.subplots(figsize=(7.5, 3.8))\nax.plot(sample_sizes, plugin_biases, \"o-\", color=PRIMARY, lw=2,\n        label=\"Plug-in ratio $\\\\bar{Y}/\\\\bar{X}$\")\nax.plot(sample_sizes, jackknife_biases, \"s--\", color=SECONDARY, lw=2,\n        label=\"Jackknife-corrected ratio\")\nax.axhline(0, color=RULE, ls=\":\", lw=1.2)\nax.set_xlabel(\"Customers per cohort ($n$)\")\nax.set_ylabel(\"Average error in revenue-per-visit\")\nax.set_title(\"The plug-in ratio runs high on small cohorts; the jackknife does not\")\nax.legend(frameon=True, facecolor=\"white\", edgecolor=RULE)\nplt.tight_layout()\nplt.show()\n\nfor n, pb, jb in zip(sample_sizes, plugin_biases, jackknife_biases):\n    print(f\"n = {n:3d}   plug-in error {pb:+.4f}   jackknife error {jb:+.4f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-3-output-1.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nn =   5   plug-in error +0.1034   jackknife error -0.0062\nn =  10   plug-in error +0.0562   jackknife error +0.0038\nn =  20   plug-in error +0.0241   jackknife error -0.0013\nn =  40   plug-in error +0.0114   jackknife error -0.0012\nn =  80   plug-in error +0.0055   jackknife error -0.0008\nn = 160   plug-in error +0.0033   jackknife error +0.0001\n```\n:::\n:::\n\n\nAt $n = 5$: plug-in error ≈ +0.10 (4% overstatement). Jackknife error within 0.007 at all sizes.\n\n## Quenouille bias correction\n\nLeave-one-out estimates $\\hat{\\theta}_{(i)}$ on samples of size $n-1$ share the same $O(1/n)$ bias at slightly higher strength.\n\nJackknife estimator:\n\n$$\\hat{\\theta}_{\\text{jack}} = n\\hat{\\theta}_n - (n-1)\\bar{\\theta}_{(\\cdot)}$$\n\nExtrapolates from sample sizes $n$ and $n-1$ to remove the $1/n$ term; remainder is $O(1/n^2)$.\n\n::: {.callout-note collapse=\"true\"}\n## The two-line cancellation, for the curious\n\nFor almost any smooth non-linear statistic, the expectation admits an asymptotic expansion in powers of $1/n$:\n\n$$\\mathbb{E}[\\hat{\\theta}_n] = \\theta + \\frac{a}{n} + \\frac{b}{n^2} + O\\!\\left(\\frac{1}{n^3}\\right)$$\n\nEach leave-one-out estimate is computed on a sample of size $n-1$, so it obeys the same expansion evaluated one lower, and so does their average:\n\n$$\\mathbb{E}[\\bar{\\theta}_{(\\cdot)}] = \\theta + \\frac{a}{n-1} + \\frac{b}{(n-1)^2} + O\\!\\left(\\frac{1}{n^3}\\right)$$\n\nMultiply the first by $n$, the second by $n-1$, and subtract. The $\\theta$ terms leave one copy behind, and the $a$ terms — now $a$ and $a$ exactly — annihilate:\n\n$$\\mathbb{E}[\\hat{\\theta}_{\\text{jack}}] = \\theta + \\left(\\frac{b}{n} - \\frac{b}{n-1}\\right) + O\\!\\left(\\frac{1}{n^2}\\right) = \\theta - \\frac{b}{n(n-1)} + O\\!\\left(\\frac{1}{n^2}\\right)$$\n\nThe constant $a$ never had to be known. That is the whole point: the correction is arithmetic on estimates you already computed, not an analysis of the particular statistic in front of you.\n:::\n\n## Tukey pseudovalues\n\nPer-observation **pseudovalue**:\n\n$$J_i = n \\hat{\\theta}_n - (n-1)\\hat{\\theta}_{(i)}$$\n\nJackknife estimate: $\\hat{\\theta}_{\\text{jack}} = \\frac{1}{n}\\sum_i J_i$.\n\n$J_i - \\hat{\\theta}_{\\text{jack}}$ measures observation $i$'s influence.\n\n**Variance:**\n\n$$v_{\\text{jack}} = \\frac{1}{n(n-1)}\\sum_{i=1}^n \\left(J_i - \\hat{\\theta}_{\\text{jack}}\\right)^2$$\n\nStandard error: $\\text{SE}_{\\text{jack}} = \\sqrt{v_{\\text{jack}}}$. Confidence interval: $\\hat{\\theta}_{\\text{jack}} \\pm t_{n-1,\\,\\alpha/2}\\cdot\\text{SE}_{\\text{jack}}$.\n\nRequires smoothness of the statistic (see influence-function expansion in callout below).\n\n::: {.callout-note collapse=\"true\"}\n## Why the fingerprints are independent: the influence function\n\nVon Mises' statistical calculus expands any smooth functional $T$ of the empirical distribution $F_n$ around the population distribution $F$:\n\n$$T(F_n) - T(F) = \\frac{1}{n}\\sum_{i=1}^n L(X_i; F) + R_n$$\n\nwhere $L(x; F)$ is the **influence function** — the derivative of the functional when you nudge an infinitesimal point mass onto $x$. It measures the effect of a single observation on the estimate, in the limit.\n\nDeleting $X_i$ removes exactly that point's term from the sum:\n\n$$\\hat{\\theta}_n - \\hat{\\theta}_{(i)} \\approx \\frac{1}{n-1}\\left(L(X_i; F) - \\bar{L}\\right)$$\n\nSubstituting into $J_i = \\hat{\\theta}_n + (n-1)(\\hat{\\theta}_n - \\hat{\\theta}_{(i)})$ collapses the factors of $n-1$:\n\n$$J_i \\approx \\hat{\\theta}_n + L(X_i; F) \\qquad \\Longrightarrow \\qquad J_i - \\hat{\\theta}_{\\text{jack}} \\approx L(X_i; F)$$\n\nThe pseudovalues are the influence function evaluated at each observation, offset by a constant. The $X_i$ are i.i.d., so the $L(X_i; F)$ are i.i.d., and the sample variance of an i.i.d. mean is the familiar $\\frac{1}{n}\\text{Var}(L(X))$ — which is the variance formula above. The approximation is exactly where the smoothness assumption enters, and it is exactly what fails for the median later on.\n:::\n\nInteractive lab: drag points; end points dominate slope influence; large-residual mid-range points may matter less.\n\n::: {.widget-container}\n::: {.widget-header}\n<span class=\"widget-title\">Interactive Lab 1: Pseudovalues & Empirical Influence</span>\n<span class=\"widget-badge\">Local Compute</span>\n:::\n<div id=\"widget-pseudovalues\"></div>\n:::\n\n## Referral fraud detection\n\n**Metric:** promo-to-spend ratio = total credits / total revenue for a referral cohort.\n\n**Synthetic cluster** (confidential ground truth unavailable):\n\n- 8 legitimate users (1–5 referrals each, normal spend).\n- 1 hub (7 synthetic spokes, $5 spend).\n- 7 spokes ($0 spend).\n- Each account charged: own signup credit + $20 per referee recruited.\n\n**Question:** which account most improves cohort economics if removed?\n\n**Downstream impact:** false bans vs missed syndicates.\n\n::: {#03c3fadd .cell execution_count=3}\n``` {.python .cell-code}\n# Simulated referral cluster: 8 genuine customers, 1 coordinating hub, 7 synthetic spokes.\n# Each account is charged its own signup credit plus one credit per referee it recruited.\nnp.random.seed(101)\nBONUS = 20\n\nlegit_referrals = [3, 2, 4, 1, 2, 5, 1, 3]\naccounts = [\n    {\"name\": f\"Legit User {i+1}\", \"referrals\": r,\n     \"spend\": int(np.random.randint(100, 300)), \"is_hub\": False}\n    for i, r in enumerate(legit_referrals)\n]\naccounts.append({\"name\": \"Syndicate Ringleader\", \"referrals\": 7, \"spend\": 5, \"is_hub\": True})\nfor j in range(7):\n    accounts.append({\"name\": f\"Synthetic Bot {j+1}\", \"referrals\": 0, \"spend\": 0, \"is_hub\": False})\n\ndf_fraud = pd.DataFrame(accounts)\ndf_fraud[\"promo\"] = BONUS * (1 + df_fraud[\"referrals\"])\nn_users = len(df_fraud)\n\ncluster_r = df_fraud[\"promo\"].sum() / df_fraud[\"spend\"].sum()\n\n# Leave-one-out: recompute the cohort ratio with each account removed in turn\ndf_fraud[\"sub_r\"] = [\n    df_fraud.drop(index=i)[\"promo\"].sum() / df_fraud.drop(index=i)[\"spend\"].sum()\n    for i in range(n_users)\n]\ndf_fraud[\"influence\"] = cluster_r - df_fraud[\"sub_r\"]\ndf_fraud[\"pseudovalue\"] = n_users * cluster_r - (n_users - 1) * df_fraud[\"sub_r\"]\n\ntop_culprits = df_fraud.sort_values(by=\"influence\", ascending=False).head(5)\n\nfig, ax = plt.subplots(figsize=(8, 3.8))\ncolors = [DANGER if is_hub else PRIMARY for is_hub in top_culprits[\"is_hub\"]]\nbars = ax.barh(top_culprits[\"name\"], top_culprits[\"influence\"], color=colors, height=0.6)\nax.set_xlabel(\"Improvement in cohort promo-to-spend ratio if this account were removed\")\nax.set_title(\"Top accounts distorting cohort unit economics\")\nax.invert_yaxis()\nfor bar, val in zip(bars, top_culprits[\"influence\"]):\n    ax.text(val + 0.002, bar.get_y() + bar.get_height()/2, f\"+{val:.3f}\",\n            va=\"center\", fontsize=9, color=INK)\nplt.tight_layout()\nplt.show()\n\nprint(f\"Cohort promo-to-spend ratio: {cluster_r:.3f}\")\nprint(f\"Ringleader leverage:  {df_fraud.loc[df_fraud.is_hub, 'influence'].item():.4f}\")\nprint(f\"Each spoke's leverage: {df_fraud.loc[df_fraud.name.str.startswith('Synthetic'), 'influence'].iloc[0]:.4f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-4-output-1.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nCohort promo-to-spend ratio: 0.618\nRingleader leverage:  0.1106\nEach spoke's leverage: 0.0140\n```\n:::\n:::\n\n\nCohort ratio: 0.618. Removing hub improves ratio by 0.111; removing one spoke by 0.014.\n\nInteractive lab: hub lead collapses as spoke count → 0.\n\n::: {.widget-container}\n::: {.widget-header}\n<span class=\"widget-title\">Interactive Lab 2: The Referral Syndicate Unmasker</span>\n<span class=\"widget-badge\">Simulation</span>\n:::\n<div id=\"widget-syndicate\"></div>\n:::\n\n## Censored survival regression\n\n**Target:** restricted mean survival time (RMST) — area under Kaplan–Meier curve to horizon $t^*$.\n\n**Problem:** RMST is cohort-level; censored subjects lack usable per-person durations for regression.\n\n**Andersen and Perme (2010):** jackknife pseudovalues provide per-subject response variables; regress with OLS.\n\n**Synthetic cohort** ($N = 400$):\n\n- Channels: organic vs paid search.\n- Discount 0–40%; true lifetime Exponential with mean depending on channel and discount.\n- Random censoring window 60–365 days.\n- Known generating parameters for validation.\n\n**Downstream use:** acquisition budget allocation.\n\n::: {#3ef1b477 .cell execution_count=4}\n``` {.python .cell-code}\n# Simulated subscription cohort, N=400, heavily right-censored.\n# True lifetime: Exponential(mean = 250 + 80*organic - 150*discount), observed through a\n# uniform 60-365 day window. Because the generating process is known, the regression can be\n# checked against the truth it is trying to recover.\nnp.random.seed(55)\nn_cohort = 400\n\nchannels = np.random.binomial(1, 0.5, size=n_cohort)      # 0 = Organic, 1 = Paid Search\ndiscounts = np.random.uniform(0, 0.4, size=n_cohort)\n\nscale = 250 + 80 * (1 - channels) - 150 * discounts\ntrue_survival = np.random.exponential(scale=scale)\ncensor_time = np.random.uniform(60, 365, size=n_cohort)\n\nobserved_time = np.minimum(true_survival, censor_time)\nevent_observed = (true_survival <= censor_time).astype(int)\n\n\ndef calc_rmst(times, events, t_star=365):\n    \"\"\"Area under the Kaplan-Meier curve out to t_star.\"\"\"\n    order = np.argsort(times)\n    t_sorted, e_sorted = times[order], events[order]\n\n    n_k = len(times)\n    s_t, rmst, prev_t = 1.0, 0.0, 0.0\n\n    k = 0\n    while k < n_k and t_sorted[k] < t_star:\n        cur_t = t_sorted[k]\n\n        # Everyone leaving at this exact time shares one risk set, so count the\n        # events across the whole tied group before shrinking the curve once.\n        j, deaths = k, 0\n        while j < n_k and t_sorted[j] == cur_t:\n            deaths += e_sorted[j]\n            j += 1\n\n        rmst += s_t * (cur_t - prev_t)   # area of the step we are leaving\n        prev_t = cur_t\n        if deaths:\n            s_t *= (1.0 - deaths / (n_k - k))\n        k = j\n\n    return rmst + s_t * (t_star - prev_t)\n\n\ncohort_rmst = calc_rmst(observed_time, event_observed)\n\n# One pseudovalue per customer: the cohort figure, re-levered by deleting that customer\npseudo_rmst = np.array([\n    n_cohort * cohort_rmst\n    - (n_cohort - 1) * calc_rmst(np.delete(observed_time, i), np.delete(event_observed, i))\n    for i in range(n_cohort)\n])\n\n# Ordinary least squares on the pseudovalues, with robust (sandwich) standard errors\nX_mat = np.column_stack([np.ones(n_cohort), channels, discounts])\nbeta_hat = np.linalg.lstsq(X_mat, pseudo_rmst, rcond=None)[0]\nresid = pseudo_rmst - X_mat @ beta_hat\nXtX_inv = np.linalg.inv(X_mat.T @ X_mat)\ncov_hat = XtX_inv @ (X_mat.T @ (X_mat * resid[:, None] ** 2)) @ XtX_inv\nse_hat = np.sqrt(np.diag(cov_hat))\n\n# The truth: each customer's exact restricted mean, best-fit by the same design matrix\ntrue_rmst_i = scale * (1 - np.exp(-365 / scale))\nbeta_true = np.linalg.lstsq(X_mat, true_rmst_i, rcond=None)[0]\n\nprint(f\"Cohort 365-day restricted mean: {cohort_rmst:.1f} active days\\n\")\nlabels = [\"Organic baseline (days)\", \"Paid Search effect (days)\", \"Full-discount effect (days)\"]\nfor name, b, s, t in zip(labels, beta_hat, se_hat, beta_true):\n    lo, hi = b - 1.96 * s, b + 1.96 * s\n    covered = \"yes\" if lo <= t <= hi else \"NO\"\n    print(f\"{name:<28} {b:8.1f} +/- {s:5.1f}   95% CI [{lo:7.1f}, {hi:7.1f}]\"\n          f\"   true {t:7.1f}   covered: {covered}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCohort 365-day restricted mean: 204.2 active days\n\nOrganic baseline (days)         241.2 +/-  15.7   95% CI [  210.4,   272.0]   true   223.3   covered: yes\nPaid Search effect (days)       -45.6 +/-  14.5   95% CI [  -74.1,   -17.1]   true   -32.9   covered: yes\nFull-discount effect (days)     -77.4 +/-  64.0   95% CI [ -202.8,    48.0]   true   -62.5   covered: yes\n```\n:::\n:::\n\n\nAll coefficient 95% CIs cover simulation truth. Discount slope SE ≈ 64 — effect not yet identifiable at $N = 400$.\n\n::: {.callout-note appearance=\"default\"}\n## Constraints\n\nRMST horizon $t^*$ must lie within observed follow-up. Beyond largest censoring time, the flat KM tail extrapolates.\n:::\n\n## Biomarker stability screening\n\n**Setting:** oncology RNA-seq, $N = 30$ patients, ~20k genes, log fold-change (LFC) ranking.\n\n**Problem:** one outlier patient can dominate a gene's mean LFC.\n\n**Stability index:** $|\\hat{\\theta}_{\\text{jack}}| / \\text{SE}_{\\text{jack}}$ (jackknife $t$-like ratio).\n\n**Synthetic screen** (PHI unavailable):\n\n- CDK1: true target, LFC ≈ 3.2 consistently.\n- LINC009: artifact — flat in 29 patients, spike in patient 15 (LFC = 90).\n\n**Downstream impact:** reagent orders and years of lab work on false targets.\n\n::: {#ef140cf0 .cell execution_count=5}\n``` {.python .cell-code}\n# Simulated RNA-seq oncology screen, N=30 patients, tumour vs normal log-fold change.\n# CDK1: a genuine target, consistent across all patients.\n# LINC009: an artifact, flat in 29 patients with one enormous reading in patient 15.\nnp.random.seed(77)\nn_patients = 30\n\ncdk1_diff = np.random.normal(loc=3.2, scale=0.6, size=n_patients)\n\nlinc_diff = np.random.normal(loc=0.2, scale=0.4, size=n_patients)\nlinc_diff[14] = 90.0  # single-patient sample-prep artifact\n\ngenes = {\"CDK1 (true target)\": cdk1_diff, \"LINC009 (artifact)\": linc_diff}\n\nfig, axes = plt.subplots(1, 2, figsize=(8, 3.6))\n\nfor ax, (gname, diffs) in zip(axes, genes.items()):\n    mean_val = np.mean(diffs)\n\n    # Leave-one-patient-out\n    sub_means = np.array([np.mean(np.delete(diffs, i)) for i in range(n_patients)])\n    theta_dot = sub_means.mean()\n    jack_val = n_patients * mean_val - (n_patients - 1) * theta_dot\n    se_j = np.sqrt(((n_patients - 1) / n_patients) * np.sum((sub_means - theta_dot) ** 2))\n    stability = abs(jack_val) / se_j\n\n    is_target = \"CDK1\" in gname\n    ax.scatter(range(1, n_patients + 1), diffs,\n               color=PRIMARY if is_target else DANGER, alpha=0.8, zorder=3)\n    ax.axhline(mean_val, color=SECONDARY, lw=2, label=f\"Naive mean LFC: {mean_val:.2f}\")\n    ax.axhline(0, color=RULE, ls=\":\")\n    ax.set_title(f\"{gname}\\nStability index: {stability:.2f}   (SE$_{{jack}}$ = {se_j:.2f})\")\n    ax.set_xlabel(\"Patient index\")\n    ax.set_ylabel(\"Tumour - normal expression\")\n    ax.legend(loc=\"center left\", fontsize=8)\n\n    if not is_target:\n        ax.annotate(\"patient 15\", xy=(15, linc_diff[14]), xytext=(19, 70),\n                    fontsize=8, color=INK,\n                    arrowprops=dict(arrowstyle=\"->\", color=MUTED, lw=1))\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-6-output-1.png){}\n:::\n:::\n\n\nNaive LFC: LINC009 3.12 > CDK1 3.06. Stability index: CDK1 28.2 vs LINC009 1.04 — ranking inverts.\n\nInteractive lab: planted artifacts rank high on LFC, low on stability.\n\n::: {.widget-container}\n::: {.widget-header}\n<span class=\"widget-title\">Interactive Lab 3: Biomarker Stability Stress-Tester</span>\n<span class=\"widget-badge\">Oncology Target Screen</span>\n:::\n<div id=\"widget-biomarkers\"></div>\n:::\n\n## Median failure\n\nJackknife requires **smooth** statistics: deleting one point causes a small estimate change.\n\nThe **sample median** is non-smooth — deletion shifts the median by adjacent order-statistic spacing, regardless of how extreme the deleted point was.\n\nConsequence: jackknife variance for the median is **inconsistent** (converges to a random multiple of truth, not the true variance).\n\nInteractive lab: compare mean vs median leave-one-out values.\n\n::: {.widget-container}\n::: {.widget-header}\n<span class=\"widget-title\">Interactive Lab 4: Smooth vs. Non-Smooth Stress Test</span>\n<span class=\"widget-badge\">Diagnostic</span>\n:::\n<div id=\"widget-smooth-jagged\"></div>\n:::\n\n### Delete-d jackknife\n\nWu (1986); Shao and Wu (1989): delete $d$ observations at a time ($d \\approx \\sqrt{n}$, $d/n \\to 0$) to restore consistency for medians and quantiles. Cost: subset sampling rather than deterministic $n$ passes.\n\n## Jackknife vs bootstrap\n\n| | Jackknife | Bootstrap |\n| :--- | :--- | :--- |\n| Cost | $n$ deterministic passes | $B \\ge 1000$ stochastic draws |\n| Smooth statistics | Removes $O(1/n)$ bias | Accurate; adds Monte Carlo noise |\n| Non-smooth (median, quantiles) | Fails; use delete-$d$ | Works unmodified |\n| Per-observation diagnostics | Pseudovalues free | Requires weight regression |\n| Setup | No seed or tuning | Choose $B$, fix seed |\n\n## When to use\n\n- Small-$n$ ratio or rate estimators: jackknife bias correction.\n- Influence identification: pseudovalues rank leverage observations.\n- Censored curve functionals: Andersen–Perme pseudovalue regression.\n- Non-smooth statistics: delete-$d$ jackknife or bootstrap instead.\n\n## References\n\n- Quenouille, M. H. (1949). Approximate tests of correlation in time-series. *Journal of the Royal Statistical Society B* 11(1), 68–84.\n- Tukey, J. W. (1958). Bias and confidence in not-quite large samples. *Annals of Mathematical Statistics* 29, 614.\n- Andersen, P. K., and Perme, M. P. (2010). Pseudo-observations in survival analysis. *Statistical Methods in Medical Research* 19(1), 71–99.\n- Wu, C. F. J. (1986). Jackknife, bootstrap and other resampling methods in regression analysis. *Annals of Statistics* 14(4), 1261–1295.\n- Shao, J., and Wu, C. F. J. (1989). A general theory for jackknife variance estimation. *Annals of Statistics* 17(3), 1176–1197.\n- Efron, B. (1979). Bootstrap methods: another look at the jackknife. *Annals of Statistics* 7(1), 1–26.\n\n```{=html}\n<script id=\"jackknife-data\" type=\"application/json\">{\"toy\":{\"points\":[{\"id\":1,\"x\":1.2,\"y\":2.1},{\"id\":2,\"x\":2.0,\"y\":2.9},{\"id\":3,\"x\":2.8,\"y\":3.7},{\"id\":4,\"x\":3.5,\"y\":4.1},{\"id\":5,\"x\":4.1,\"y\":5.2},{\"id\":6,\"x\":4.9,\"y\":5.8},{\"id\":7,\"x\":5.8,\"y\":6.9},{\"id\":8,\"x\":6.7,\"y\":7.4},{\"id\":9,\"x\":7.5,\"y\":8.5},{\"id\":10,\"x\":8.4,\"y\":9.2},{\"id\":11,\"x\":9.2,\"y\":9.8},{\"id\":12,\"x\":5.0,\"y\":9.5}]},\"syndicate\":{\"accounts\":[{\"id\":\"U101\",\"type\":\"legit\",\"name\":\"Organic A\",\"promo_cost\":20,\"net_spend\":185,\"referrals\":3},{\"id\":\"U102\",\"type\":\"legit\",\"name\":\"Organic B\",\"promo_cost\":20,\"net_spend\":140,\"referrals\":2},{\"id\":\"U103\",\"type\":\"legit\",\"name\":\"Organic C\",\"promo_cost\":20,\"net_spend\":220,\"referrals\":4},{\"id\":\"U104\",\"type\":\"legit\",\"name\":\"Organic D\",\"promo_cost\":20,\"net_spend\":95,\"referrals\":1},{\"id\":\"U105\",\"type\":\"legit\",\"name\":\"Organic E\",\"promo_cost\":20,\"net_spend\":160,\"referrals\":2},{\"id\":\"U106\",\"type\":\"legit\",\"name\":\"Organic F\",\"promo_cost\":20,\"net_spend\":310,\"referrals\":5},{\"id\":\"U107\",\"type\":\"legit\",\"name\":\"Organic G\",\"promo_cost\":20,\"net_spend\":115,\"referrals\":1},{\"id\":\"U108\",\"type\":\"legit\",\"name\":\"Organic H\",\"promo_cost\":20,\"net_spend\":190,\"referrals\":3},{\"id\":\"U201\",\"type\":\"syndicate_hub\",\"name\":\"Bot Farm Ringleader\",\"promo_cost\":20,\"net_spend\":5,\"referrals\":8}]},\"biomarkers\":{\"genes\":[{\"name\":\"CDK1\",\"type\":\"robust\",\"tumor_mean\":6.8,\"normal_mean\":2.1,\"std\":0.8,\"description\":\"Consistently overexpressed across all 30 patients\"},{\"name\":\"MYC\",\"type\":\"robust\",\"tumor_mean\":7.4,\"normal_mean\":3.0,\"std\":0.9,\"description\":\"Strong oncogenic transcription factor, widespread upregulation\"},{\"name\":\"EGFR\",\"type\":\"robust\",\"tumor_mean\":5.9,\"normal_mean\":2.2,\"std\":0.7,\"description\":\"Receptor kinase amplification across cohort\"},{\"name\":\"BRCA1\",\"type\":\"robust\",\"tumor_mean\":2.2,\"normal_mean\":5.8,\"std\":0.6,\"description\":\"Tumor suppressor loss across cohort\"},{\"name\":\"TP53\",\"type\":\"robust\",\"tumor_mean\":1.9,\"normal_mean\":5.4,\"std\":0.7,\"description\":\"Consistent downregulation / loss of function\"},{\"name\":\"LINC009\",\"type\":\"brittle\",\"tumor_mean\":3.1,\"normal_mean\":3.0,\"std\":0.4,\"outlier_patient\":14,\"outlier_val\":150.0,\"description\":\"Flat in 29 patients; massive sample-prep artifact in Patient #15\"},{\"name\":\"FAM83A\",\"type\":\"brittle\",\"tumor_mean\":2.8,\"normal_mean\":2.7,\"std\":0.5,\"outlier_patient\":3,\"outlier_val\":140.0,\"description\":\"Looks significant on the naive mean, driven entirely by Patient #4\"},{\"name\":\"OR2T1\",\"type\":\"null\",\"tumor_mean\":3.2,\"normal_mean\":3.1,\"std\":0.6,\"description\":\"Olfactory receptor, unexpressed noise background\"},{\"name\":\"ZNF281\",\"type\":\"null\",\"tumor_mean\":4.0,\"normal_mean\":3.9,\"std\":0.5,\"description\":\"Zinc finger, no differential expression\"},{\"name\":\"ACTB\",\"type\":\"housekeeping\",\"tumor_mean\":11.2,\"normal_mean\":11.1,\"std\":0.3,\"description\":\"Housekeeping reference gene, stable expression\"}]}}</script>\n<script>/* Widgets for \"The Statistical Jackknife\"\n *\n * Dependency-free: no CDN, no module loading, no framework.\n * Built with DOM APIs and inline SVG for seamless local and offline viewing.\n */\n\"use strict\";\n\nconst JK = (function () {\n  const NS = \"http://www.w3.org/2000/svg\";\n  const C = {\n    primary: \"#1D5C6E\",\n    secondary: \"#C98A12\",\n    accent: \"#7A3B6B\",\n    danger: \"#C62828\",\n    success: \"#2E7D32\",\n    ink: \"#171C1B\",\n    muted: \"#67706E\",\n    rule: \"#D2D6D1\",\n    bgLight: \"#F8F9FA\",\n    white: \"#FFFFFF\"\n  };\n\n  // DOM helpers\n  function el(tag, attrs, kids) {\n    const e = document.createElementNS(NS, tag);\n    for (const k in (attrs || {})) e.setAttribute(k, attrs[k]);\n    for (const c of (kids || [])) e.appendChild(c);\n    return e;\n  }\n  function h(tag, attrs, kids) {\n    const e = document.createElement(tag);\n    for (const k in (attrs || {})) {\n      if (k === \"html\") e.innerHTML = attrs[k];\n      else if (k === \"text\") e.textContent = attrs[k];\n      else if (k === \"style\" && typeof attrs[k] === \"object\") {\n        Object.assign(e.style, attrs[k]);\n      } else e.setAttribute(k, attrs[k]);\n    }\n    for (const c of (kids || [])) e.appendChild(c);\n    return e;\n  }\n  function clear(node) {\n    while (node.firstChild) node.removeChild(node.firstChild);\n  }\n\n  // --- WIDGET 1: Pseudovalues & Influence Playground ---\n  function initWidget1(containerId, initialData) {\n    const root = document.getElementById(containerId);\n    if (!root) return;\n    clear(root);\n\n    let points = (initialData && initialData.points) \n      ? JSON.parse(JSON.stringify(initialData.points))\n      : [\n          {id: 1, x: 2, y: 3}, {id: 2, x: 3, y: 4}, {id: 3, x: 4, y: 5},\n          {id: 4, x: 5, y: 6}, {id: 5, x: 6, y: 7}, {id: 6, x: 7, y: 8},\n          {id: 7, x: 8, y: 9}, {id: 8, x: 5, y: 9.5}\n        ];\n\n    const width = 680;\n    const height = 340;\n    const pad = 40;\n\n    // Controls & Summary Header\n    const statPanel = h(\"div\", {\n      style: {\n        display: \"flex\",\n        flexWrap: \"wrap\",\n        gap: \"1.2rem\",\n        marginBottom: \"0.8rem\",\n        fontSize: \"0.9rem\",\n        background: \"#F4F6F6\",\n        padding: \"0.6rem 1rem\",\n        borderRadius: \"6px\",\n        border: `1px solid ${C.rule}`\n      }\n    });\n\n    const svgWrap = h(\"div\", { style: { display: \"flex\", gap: \"1rem\", flexWrap: \"wrap\" } });\n    \n    // Left: 2D scatter svg\n    const scatterSvg = el(\"svg\", {\n      viewBox: `0 0 380 300`,\n      width: \"380\",\n      height: \"300\",\n      style: \"background:#fff;border:1px solid #E2E6E1;border-radius:6px;cursor:grab;\"\n           + \"max-width:100%;height:auto\"\n    });\n\n    // Right: Influence bar chart svg\n    const barSvg = el(\"svg\", {\n      viewBox: `0 0 280 300`,\n      width: \"280\",\n      height: \"300\",\n      style: \"background:#fff;border:1px solid #E2E6E1;border-radius:6px;\"\n           + \"max-width:100%;height:auto\"\n    });\n\n    svgWrap.appendChild(scatterSvg);\n    svgWrap.appendChild(barSvg);\n\n    const note = h(\"div\", {\n      class: \"widget-note\",\n      text: \"Drag any point on the left. Watch its influence bar (right) and the Jackknife standard error recalculate instantly.\"\n    });\n\n    root.appendChild(statPanel);\n    root.appendChild(svgWrap);\n    root.appendChild(note);\n\n    let activeDrag = null;\n\n    function toScreenX(x) { return pad + (x / 10) * (380 - 2 * pad); }\n    function toScreenY(y) { return (300 - pad) - (y / 10) * (300 - 2 * pad); }\n    function toDataX(sx) { return Math.max(0.5, Math.min(9.5, ((sx - pad) / (380 - 2 * pad)) * 10)); }\n    function toDataY(sy) { return Math.max(0.5, Math.min(9.5, (((300 - pad) - sy) / (300 - 2 * pad)) * 10)); }\n\n    function update() {\n      const n = points.length;\n      // Estimator: Correlation r (or mean y)\n      // Let's use correlation r as a classic non-linear statistic\n      const sumX = points.reduce((s, p) => s + p.x, 0);\n      const sumY = points.reduce((s, p) => s + p.y, 0);\n      const meanX = sumX / n;\n      const meanY = sumY / n;\n\n      function calcSlope(pts) {\n        const mX = pts.reduce((s, p) => s + p.x, 0) / pts.length;\n        const mY = pts.reduce((s, p) => s + p.y, 0) / pts.length;\n        let num = 0, den = 0;\n        for (const p of pts) {\n          num += (p.x - mX) * (p.y - mY);\n          den += (p.x - mX) * (p.x - mX);\n        }\n        return den === 0 ? 0 : num / den;\n      }\n\n      const thetaHat = calcSlope(points);\n\n      // Leave-one-out\n      const theta_i = [];\n      const pseudovalues = [];\n      for (let i = 0; i < n; i++) {\n        const sub = points.filter((_, idx) => idx !== i);\n        const t_i = calcSlope(sub);\n        theta_i.push(t_i);\n        const J_i = n * thetaHat - (n - 1) * t_i;\n        pseudovalues.push(J_i);\n      }\n\n      const thetaDot = theta_i.reduce((s, v) => s + v, 0) / n;\n      const thetaJack = n * thetaHat - (n - 1) * thetaDot;\n      const biasEst = (n - 1) * (thetaDot - thetaHat);\n\n      // Jackknife variance\n      let sumSqDiff = 0;\n      for (let i = 0; i < n; i++) {\n        sumSqDiff += Math.pow(theta_i[i] - thetaDot, 2);\n      }\n      const vJack = ((n - 1) / n) * sumSqDiff;\n      const seJack = Math.sqrt(vJack);\n\n      // Influence functions\n      const influences = pseudovalues.map(j => j - thetaJack);\n\n      // Update statPanel\n      clear(statPanel);\n      statPanel.appendChild(h(\"div\", {\n        html: `<strong>Sample slope:</strong> <span class=\"metric-pill\">${thetaHat.toFixed(3)}</span>`\n      }));\n      statPanel.appendChild(h(\"div\", {\n        html: `<strong>Jackknife-corrected slope:</strong> <span class=\"metric-pill positive\">${thetaJack.toFixed(3)}</span>`\n      }));\n      statPanel.appendChild(h(\"div\", {\n        html: `<strong>Est. Bias:</strong> <span class=\"metric-pill ${Math.abs(biasEst) > 0.05 ? 'warning' : ''}\">${biasEst.toFixed(3)}</span>`\n      }));\n      statPanel.appendChild(h(\"div\", {\n        html: `<strong>Jackknife SE:</strong> <span class=\"metric-pill\">${seJack.toFixed(3)}</span>`\n      }));\n\n      // Render Scatter SVG\n      clear(scatterSvg);\n      // Grid lines\n      for (let g = 2; g <= 8; g += 2) {\n        scatterSvg.appendChild(el(\"line\", {\n          x1: toScreenX(g), y1: pad, x2: toScreenX(g), y2: 300 - pad,\n          stroke: \"#EEF0F0\", \"stroke-width\": \"1\"\n        }));\n        scatterSvg.appendChild(el(\"line\", {\n          x1: pad, y1: toScreenY(g), x2: 380 - pad, y2: toScreenY(g),\n          stroke: \"#EEF0F0\", \"stroke-width\": \"1\"\n        }));\n      }\n\n      // Regression line\n      const lineX1 = 0.5, lineX2 = 9.5;\n      const lineY1 = meanY + thetaHat * (lineX1 - meanX);\n      const lineY2 = meanY + thetaHat * (lineX2 - meanX);\n      scatterSvg.appendChild(el(\"line\", {\n        x1: toScreenX(lineX1), y1: toScreenY(lineY1),\n        x2: toScreenX(lineX2), y2: toScreenY(lineY2),\n        stroke: C.primary, \"stroke-width\": \"2\", \"stroke-dasharray\": \"4 2\"\n      }));\n\n      // Points\n      points.forEach((p, idx) => {\n        const cx = toScreenX(p.x);\n        const cy = toScreenY(p.y);\n        const infl = Math.abs(influences[idx]);\n        const isHigh = infl > 0.3;\n\n        const circle = el(\"circle\", {\n          cx, cy, r: isHigh ? \"8\" : \"6\",\n          fill: isHigh ? C.danger : C.primary,\n          stroke: \"#fff\",\n          \"stroke-width\": \"2\",\n          style: \"cursor:grab\"\n        });\n\n        circle.addEventListener(\"mousedown\", (e) => {\n          activeDrag = idx;\n          e.preventDefault();\n        });\n        circle.addEventListener(\"touchstart\", (e) => {\n          activeDrag = idx;\n          e.preventDefault();\n        }, { passive: false });\n\n        scatterSvg.appendChild(circle);\n\n        // Point label\n        scatterSvg.appendChild(el(\"text\", {\n          x: cx + 8, y: cy - 6,\n          fill: C.muted, \"font-size\": \"10\", \"font-family\": \"monospace\"\n        }, [document.createTextNode(`#${p.id}`)]));\n      });\n\n      // Render Bar SVG (Influence)\n      clear(barSvg);\n      barSvg.appendChild(el(\"text\", {\n        x: 140, y: 22, \"text-anchor\": \"middle\",\n        fill: C.ink, \"font-size\": \"12\", \"font-weight\": \"bold\"\n      }, [document.createTextNode(\"Empirical Influence (Jᵢ - β̂_jack)\")]));\n\n      const midX = 140;\n      barSvg.appendChild(el(\"line\", {\n        x1: midX, y1: 35, x2: midX, y2: 280,\n        stroke: C.rule, \"stroke-width\": \"1.5\"\n      }));\n\n      const maxAbsInfl = Math.max(0.6, ...influences.map(Math.abs));\n      const rowHeight = (240) / n;\n\n      influences.forEach((inf, idx) => {\n        const y = 45 + idx * rowHeight;\n        const barW = (inf / maxAbsInfl) * 110;\n        const isPos = inf >= 0;\n\n        const bar = el(\"rect\", {\n          x: isPos ? midX : midX + barW,\n          y: y - 6,\n          width: Math.abs(barW),\n          height: Math.max(4, rowHeight - 4),\n          fill: Math.abs(inf) > 0.3 ? C.danger : C.primary,\n          rx: \"2\"\n        });\n        barSvg.appendChild(bar);\n\n        barSvg.appendChild(el(\"text\", {\n          x: isPos ? midX - 8 : midX + 8,\n          y: y + 4,\n          \"text-anchor\": isPos ? \"end\" : \"start\",\n          fill: C.muted, \"font-size\": \"10\", \"font-family\": \"monospace\"\n        }, [document.createTextNode(`#${points[idx].id}`)]));\n      });\n    }\n\n    function handleMove(clientX, clientY) {\n      if (activeDrag === null) return;\n      // The SVG is CSS-scalable (max-width:100%), so client pixels are not viewBox\n      // units on a narrow screen. Rescale by the rendered size before converting.\n      const rect = scatterSvg.getBoundingClientRect();\n      const kx = rect.width ? 380 / rect.width : 1;\n      const ky = rect.height ? 300 / rect.height : 1;\n      const sx = (clientX - rect.left) * kx;\n      const sy = (clientY - rect.top) * ky;\n      points[activeDrag].x = toDataX(sx);\n      points[activeDrag].y = toDataY(sy);\n      update();\n    }\n\n    window.addEventListener(\"mousemove\", (e) => handleMove(e.clientX, e.clientY));\n    window.addEventListener(\"touchmove\", (e) => {\n      if (activeDrag !== null && e.touches.length > 0) {\n        handleMove(e.touches[0].clientX, e.touches[0].clientY);\n      }\n    }, { passive: false });\n\n    window.addEventListener(\"mouseup\", () => { activeDrag = null; });\n    window.addEventListener(\"touchend\", () => { activeDrag = null; });\n\n    update();\n  }\n\n  // --- WIDGET 2: Referral Syndicate Unmasker ---\n  function initWidget2(containerId, initialData) {\n    const root = document.getElementById(containerId);\n    if (!root) return;\n    clear(root);\n\n    const accounts = (initialData && initialData.accounts) \n      ? JSON.parse(JSON.stringify(initialData.accounts))\n      : [];\n\n    let bonus = 20;\n    let botSpokes = 8;\n\n    // Controls\n    const ctrlWrap = h(\"div\", { class: \"widget-controls\" });\n\n    const bonusSlider = h(\"input\", {\n      type: \"range\", min: \"10\", max: \"50\", step: \"5\", value: String(bonus),\n      style: { width: \"130px\" }\n    });\n    const bonusVal = h(\"span\", { text: `$${bonus}`, style: { fontWeight: \"bold\" } });\n    bonusSlider.addEventListener(\"input\", (e) => {\n      bonus = parseInt(e.target.value);\n      bonusVal.textContent = `$${bonus}`;\n      render();\n    });\n\n    const botSlider = h(\"input\", {\n      type: \"range\", min: \"0\", max: \"15\", step: \"1\", value: String(botSpokes),\n      style: { width: \"130px\" }\n    });\n    const botVal = h(\"span\", { text: `${botSpokes} bots`, style: { fontWeight: \"bold\" } });\n    botSlider.addEventListener(\"input\", (e) => {\n      botSpokes = parseInt(e.target.value);\n      botVal.textContent = `${botSpokes} bots`;\n      render();\n    });\n\n    ctrlWrap.appendChild(h(\"label\", { style: { display: \"flex\", alignItems: \"center\", gap: \"0.5rem\", fontSize: \"0.88rem\" } }, [\n      h(\"span\", { text: \"Promo Credit:\" }), bonusSlider, bonusVal\n    ]));\n    ctrlWrap.appendChild(h(\"label\", { style: { display: \"flex\", alignItems: \"center\", gap: \"0.5rem\", fontSize: \"0.88rem\" } }, [\n      h(\"span\", { text: \"Syndicate Bot Nodes:\" }), botSlider, botVal\n    ]));\n\n    const cardContainer = h(\"div\", {\n      style: {\n        display: \"grid\",\n        gridTemplateColumns: \"repeat(auto-fit, minmax(280px, 1fr))\",\n        gap: \"1rem\",\n        marginTop: \"1rem\"\n      }\n    });\n\n    const statusBanner = h(\"div\", { style: { marginTop: \"1rem\" } });\n\n    root.appendChild(ctrlWrap);\n    root.appendChild(cardContainer);\n    root.appendChild(statusBanner);\n\n    function render() {\n      // Build dynamic user list\n      const activeUsers = accounts.filter(a => a.type === \"legit\" || a.type === \"syndicate_hub\");\n      for (let b = 1; b <= botSpokes; b++) {\n        activeUsers.push({\n          id: `BOT-${b}`,\n          type: \"syndicate_spoke\",\n          name: `Synthetic Node ${b}`,\n          promo_cost: bonus,\n          net_spend: 0,\n          referrals: 0\n        });\n      }\n      // Charge each account the credits it caused: its own signup bonus plus one\n      // bonus per referee it recruited. The hub's referral count tracks the bot slider,\n      // so its cost is the whole syndicate's payout, not a single $20 credit.\n      const priced = activeUsers.map(u => {\n        const referrals = u.type === \"syndicate_hub\" ? botSpokes : (u.referrals || 0);\n        return { ...u, referrals, promo_cost: bonus * (1 + referrals) };\n      });\n\n      const n = priced.length;\n      const totalPromo = priced.reduce((s, u) => s + u.promo_cost, 0);\n      const totalSpend = priced.reduce((s, u) => s + u.net_spend, 0);\n      const clusterRatio = totalSpend > 0 ? (totalPromo / totalSpend) : 999;\n\n      // Leave-one-out\n      const results = priced.map((u, idx) => {\n        const sub = priced.filter((_, i) => i !== idx);\n        const subP = sub.reduce((s, x) => s + x.promo_cost, 0);\n        const subS = sub.reduce((s, x) => s + x.net_spend, 0);\n        const subR = subS > 0 ? (subP / subS) : 999;\n        const pseudovalue = n * clusterRatio - (n - 1) * subR;\n        const leverage = clusterRatio - subR; // How much health drops when this user is PRESENT\n        return { ...u, subR, pseudovalue, leverage };\n      });\n\n      // Sort by absolute leverage / pseudovalue anomaly\n      results.sort((a, b) => b.leverage - a.leverage);\n\n      clear(cardContainer);\n\n      // Summary Card\n      const summaryCard = h(\"div\", {\n        style: {\n          background: \"#FFFFFF\",\n          border: `1px solid ${C.rule}`,\n          borderRadius: \"8px\",\n          padding: \"1rem\"\n        }\n      }, [\n        h(\"h4\", { text: \"Cohort Unit Economics\", style: { margin: \"0 0 0.5rem 0\", color: C.ink } }),\n        h(\"div\", { html: `<strong>Cohort Size:</strong> ${n} users (${botSpokes} syndicate bots)` }),\n        h(\"div\", { html: `<strong>Total Promo Burn:</strong> $${totalPromo}` }),\n        h(\"div\", { html: `<strong>Total Net Revenue:</strong> $${totalSpend}` }),\n        h(\"div\", {\n          style: { marginTop: \"0.5rem\", fontSize: \"1.1rem\" },\n          html: `<strong>Promo-to-Spend Ratio:</strong> <span class=\"metric-pill ${clusterRatio > 0.5 ? 'danger' : 'positive'}\">${clusterRatio.toFixed(3)}</span>`\n        })\n      ]);\n      cardContainer.appendChild(summaryCard);\n\n      // Top Anomaly Table Card\n      const topAnomalies = results.slice(0, 5);\n      const anomalyCard = h(\"div\", {\n        style: {\n          background: \"#FFFFFF\",\n          border: `1px solid ${C.rule}`,\n          borderRadius: \"8px\",\n          padding: \"1rem\"\n        }\n      }, [\n        h(\"h4\", { text: \"Top Jackknife Leverage (Who Breaks the Metric?)\", style: { margin: \"0 0 0.5rem 0\", color: C.ink } }),\n        h(\"table\", { style: { width: \"100%\", fontSize: \"0.85rem\", borderCollapse: \"collapse\" } }, [\n          h(\"thead\", {}, [\n            h(\"tr\", { style: { borderBottom: `1px solid ${C.rule}`, textAlign: \"left\", color: C.muted } }, [\n              h(\"th\", { text: \"User\" }),\n              h(\"th\", { text: \"Spend\" }),\n              h(\"th\", { text: \"Ratio without them\" }),\n              h(\"th\", { text: \"Leverage\" }),\n              h(\"th\", { text: \"Pseudovalue\" })\n            ])\n          ]),\n          h(\"tbody\", {}, topAnomalies.map(u => {\n            const isRingleader = u.type === \"syndicate_hub\";\n            return h(\"tr\", {\n              style: {\n                borderBottom: \"1px solid #F0F2F2\",\n                background: isRingleader ? \"#FFF5F5\" : \"transparent\",\n                fontWeight: isRingleader ? \"bold\" : \"normal\",\n                color: isRingleader ? C.danger : C.ink\n              }\n            }, [\n              h(\"td\", { text: u.name }),\n              h(\"td\", { text: `$${u.net_spend}` }),\n              h(\"td\", { text: u.subR.toFixed(3) }),\n              h(\"td\", { text: `+${u.leverage.toFixed(3)}` }),\n              h(\"td\", { text: u.pseudovalue.toFixed(2) })\n            ]);\n          }))\n        ])\n      ]);\n      cardContainer.appendChild(anomalyCard);\n\n      // Status alert\n      clear(statusBanner);\n      const ringleader = results.find(r => r.type === \"syndicate_hub\");\n      const runnerUp = results.find(r => r.type !== \"syndicate_hub\");\n      if (ringleader) {\n        statusBanner.appendChild(h(\"div\", {\n          class: \"jackknife-hero\",\n          style: { borderColor: C.danger, background: \"rgba(198, 40, 40, 0.05)\" },\n          html: `<strong>🎯 Jackknife Isolation:</strong> Removing <em>${ringleader.name}</em> (${botSpokes} referrals, $${ringleader.net_spend} spend) drops the cohort Promo-to-Spend ratio from <strong>${clusterRatio.toFixed(3)}</strong> to <strong>${ringleader.subR.toFixed(3)}</strong> — leverage <strong>${ringleader.leverage.toFixed(3)}</strong>, <strong>${(ringleader.leverage / runnerUp.leverage).toFixed(1)}×</strong> the next account. ${botSpokes > 0 ? \"The jackknife isolates the coordinator without any network-graph clustering.\" : \"With no spokes to coordinate, the hub is just a low-spending customer and its lead all but vanishes.\"}`\n        }));\n      }\n    }\n\n    render();\n  }\n\n  // --- WIDGET 3: Biomarker Stability Stress-Tester ---\n  function initWidget3(containerId, initialData) {\n    const root = document.getElementById(containerId);\n    if (!root) return;\n    clear(root);\n\n    const genes = (initialData && initialData.genes) \n      ? JSON.parse(JSON.stringify(initialData.genes))\n      : [];\n\n    let injectOutlier = false;\n\n    const ctrlWrap = h(\"div\", { class: \"widget-controls\", style: { alignItems: \"center\" } });\n    const toggleBtn = h(\"button\", {\n      text: \"⚡ Inject artifact patients into LINC009 and FAM83A\",\n      style: {\n        background: C.primary,\n        color: \"#FFF\",\n        border: \"none\",\n        padding: \"0.5rem 1rem\",\n        borderRadius: \"4px\",\n        cursor: \"pointer\",\n        fontWeight: \"600\"\n      }\n    });\n    toggleBtn.addEventListener(\"click\", () => {\n      injectOutlier = !injectOutlier;\n      toggleBtn.textContent = injectOutlier \n        ? \"🔄 Remove artifact patients (restore baseline)\"\n        : \"⚡ Inject artifact patients into LINC009 and FAM83A\";\n      toggleBtn.style.background = injectOutlier ? C.danger : C.primary;\n      render();\n    });\n\n    ctrlWrap.appendChild(toggleBtn);\n    ctrlWrap.appendChild(h(\"span\", {\n      style: { fontSize: \"0.85rem\", color: C.muted },\n      text: \"Watch naive fold change promote both artifacts to the top, while the stability index leaves the genuine targets in place.\"\n    }));\n\n    const displayGrid = h(\"div\", {\n      style: {\n        display: \"grid\",\n        gridTemplateColumns: \"1fr 1fr\",\n        gap: \"1rem\",\n        marginTop: \"1rem\"\n      }\n    });\n\n    root.appendChild(ctrlWrap);\n    root.appendChild(displayGrid);\n\n    function simulateGene(gene, n = 30) {\n      // Create N patient expression differences\n      let diffs = [];\n      for (let i = 0; i < n; i++) {\n        // Deterministic stand-in for patient-to-patient noise: a fixed sinusoid, not a\n        // random draw, so the widget renders identically on every load.\n        const base = (gene.tumor_mean - gene.normal_mean) + (Math.sin(i * 3 + gene.name.length) * gene.std);\n        diffs.push(base);\n      }\n      // A gene declaring an outlier patient in the data file gets that patient's\n      // reading replaced when the artifact is injected. Genes without one are untouched.\n      let injected = false;\n      if (injectOutlier && gene.outlier_patient !== undefined && gene.outlier_patient < n) {\n        diffs[gene.outlier_patient] = gene.outlier_val;\n        injected = true;\n      }\n\n      const meanLFC = diffs.reduce((s, v) => s + v, 0) / n;\n\n      // Jackknife\n      const subMeans = diffs.map((_, idx) => {\n        const sub = diffs.filter((_, i) => i !== idx);\n        return sub.reduce((s, v) => s + v, 0) / (n - 1);\n      });\n      const thetaDot = subMeans.reduce((s, v) => s + v, 0) / n;\n      const jackLFC = n * meanLFC - (n - 1) * thetaDot;\n      const vJack = ((n - 1) / n) * subMeans.reduce((s, m) => s + Math.pow(m - thetaDot, 2), 0);\n      const seJack = Math.sqrt(vJack);\n      const stability = seJack > 0 ? Math.abs(jackLFC) / seJack : 0;\n\n      return {\n        name: gene.name,\n        type: gene.type,\n        injected,\n        meanLFC,\n        jackLFC,\n        seJack,\n        stability\n      };\n    }\n\n    function render() {\n      const results = genes.map(g => simulateGene(g, 30));\n\n      // Sort by naive |LFC| so down-regulated targets (BRCA1, TP53) compete on the\n      // same scale as up-regulated ones, matching how the stability panel ranks.\n      const naiveSorted = [...results].sort((a, b) => Math.abs(b.meanLFC) - Math.abs(a.meanLFC));\n      // Sort by Jackknife Stability\n      const jackSorted = [...results].sort((a, b) => b.stability - a.stability);\n\n      clear(displayGrid);\n\n      // Left Column: Naive Ranking\n      const leftCol = h(\"div\", {\n        style: { background: \"#FFFFFF\", border: `1px solid ${C.rule}`, borderRadius: \"8px\", padding: \"1rem\" }\n      }, [\n        h(\"h4\", { text: \"Naive Ranking (Mean Log-Fold Change)\", style: { margin: \"0 0 0.5rem 0\", color: C.ink } }),\n        h(\"div\", { style: { fontSize: \"0.8rem\", color: C.muted, marginBottom: \"0.5rem\" }, text: \"Ranks genes solely by cohort sample average.\" }),\n        h(\"table\", { style: { width: \"100%\", fontSize: \"0.85rem\", borderCollapse: \"collapse\" } }, [\n          h(\"thead\", {}, [\n            h(\"tr\", { style: { borderBottom: `1px solid ${C.rule}`, textAlign: \"left\", color: C.muted } }, [\n              h(\"th\", { text: \"Rank\" }),\n              h(\"th\", { text: \"Gene\" }),\n              h(\"th\", { text: \"Mean LFC\" })\n            ])\n          ]),\n          h(\"tbody\", {}, naiveSorted.slice(0, 5).map((g, i) => {\n            const isLinc = g.injected;\n            return h(\"tr\", {\n              style: {\n                borderBottom: \"1px solid #F0F2F2\",\n                background: isLinc && injectOutlier ? \"#FFF5F5\" : \"transparent\",\n                fontWeight: isLinc && injectOutlier ? \"bold\" : \"normal\",\n                color: isLinc && injectOutlier ? C.danger : C.ink\n              }\n            }, [\n              h(\"td\", { text: `#${i + 1}` }),\n              h(\"td\", { text: `${g.name} ${isLinc && injectOutlier ? '⚠️' : ''}` }),\n              h(\"td\", { text: g.meanLFC.toFixed(2) })\n            ]);\n          }))\n        ])\n      ]);\n\n      // Right Column: Jackknife Stability Ranking\n      const rightCol = h(\"div\", {\n        style: { background: \"#FFFFFF\", border: `1px solid ${C.rule}`, borderRadius: \"8px\", padding: \"1rem\" }\n      }, [\n        h(\"h4\", { text: \"Jackknife Stability Ranking (|LFC| / SE_jack)\", style: { margin: \"0 0 0.5rem 0\", color: C.primary } }),\n        h(\"div\", { style: { fontSize: \"0.8rem\", color: C.muted, marginBottom: \"0.5rem\" }, text: \"Penalizes genes with high leave-one-out variance.\" }),\n        h(\"table\", { style: { width: \"100%\", fontSize: \"0.85rem\", borderCollapse: \"collapse\" } }, [\n          h(\"thead\", {}, [\n            h(\"tr\", { style: { borderBottom: `1px solid ${C.rule}`, textAlign: \"left\", color: C.muted } }, [\n              h(\"th\", { text: \"Rank\" }),\n              h(\"th\", { text: \"Gene\" }),\n              h(\"th\", { text: \"SE_jack\" }),\n              h(\"th\", { text: \"Stability\" })\n            ])\n          ]),\n          h(\"tbody\", {}, jackSorted.slice(0, 5).map((g, i) => {\n            const isLinc = g.injected;\n            return h(\"tr\", {\n              style: {\n                borderBottom: \"1px solid #F0F2F2\",\n                background: isLinc && injectOutlier ? \"#FFF5F5\" : \"transparent\",\n                color: isLinc && injectOutlier ? C.danger : C.ink\n              }\n            }, [\n              h(\"td\", { text: `#${i + 1}` }),\n              h(\"td\", { text: g.name }),\n              h(\"td\", { text: g.seJack.toFixed(2) }),\n              h(\"td\", { text: g.stability.toFixed(2), style: { fontWeight: \"bold\" } })\n            ]);\n          }))\n        ])\n      ]);\n\n      displayGrid.appendChild(leftCol);\n      displayGrid.appendChild(rightCol);\n    }\n\n    render();\n  }\n\n  // --- WIDGET 4: Smooth vs. Non-Smooth Stress Test ---\n  function initWidget4(containerId) {\n    const root = document.getElementById(containerId);\n    if (!root) return;\n    clear(root);\n\n    let statType = \"mean\";\n    const sample = [1.2, 1.8, 2.3, 2.9, 3.4, 3.8, 4.2, 4.9, 5.5, 6.2, 9.8];\n\n    const ctrlWrap = h(\"div\", { class: \"widget-controls\" });\n    const radioMean = h(\"input\", { type: \"radio\", id: \"w4-opt-mean\", name: \"w4-stat\", value: \"mean\", checked: true });\n    const radioMed = h(\"input\", { type: \"radio\", id: \"w4-opt-med\", name: \"w4-stat\", value: \"median\" });\n\n    radioMean.addEventListener(\"change\", () => { statType = \"mean\"; render(); });\n    radioMed.addEventListener(\"change\", () => { statType = \"median\"; render(); });\n\n    ctrlWrap.appendChild(h(\"label\", { style: { display: \"inline-flex\", alignItems: \"center\", gap: \"0.3rem\", fontSize: \"0.9rem\", cursor: \"pointer\" } }, [\n      radioMean, h(\"span\", { text: \"Smooth: Sample Mean\" })\n    ]));\n    ctrlWrap.appendChild(h(\"label\", { style: { display: \"inline-flex\", alignItems: \"center\", gap: \"0.3rem\", fontSize: \"0.9rem\", cursor: \"pointer\" } }, [\n      radioMed, h(\"span\", { text: \"Non-Smooth: Sample Median\" })\n    ]));\n\n    const canvasWrap = h(\"div\", { style: { background: \"#FFF\", border: `1px solid ${C.rule}`, borderRadius: \"8px\", padding: \"1rem\", marginTop: \"1rem\" } });\n\n    root.appendChild(ctrlWrap);\n    root.appendChild(canvasWrap);\n\n    function calcMedian(arr) {\n      const s = [...arr].sort((a, b) => a - b);\n      const m = Math.floor(s.length / 2);\n      return s.length % 2 === 0 ? (s[m - 1] + s[m]) / 2 : s[m];\n    }\n    function calcMean(arr) {\n      return arr.reduce((s, v) => s + v, 0) / arr.length;\n    }\n\n    function render() {\n      clear(canvasWrap);\n      const n = sample.length;\n      const fullEst = statType === \"mean\" ? calcMean(sample) : calcMedian(sample);\n      const subEsts = sample.map((_, idx) => {\n        const sub = sample.filter((_, i) => i !== idx);\n        return statType === \"mean\" ? calcMean(sub) : calcMedian(sub);\n      });\n\n      const deltas = subEsts.map(sub => fullEst - sub);\n\n      const svgEl = el(\"svg\", {\n        viewBox: \"0 0 600 200\",\n        width: \"100%\",\n        height: \"200\",\n        style: \"display:block\"\n      });\n\n      // Axis\n      svgEl.appendChild(el(\"line\", {\n        x1: \"50\", y1: \"150\", x2: \"550\", y2: \"150\",\n        stroke: C.rule, \"stroke-width\": \"1.5\"\n      }));\n\n      // Plot stem lines for leave-one-out delta\n      const maxDelta = Math.max(0.2, ...deltas.map(Math.abs));\n      deltas.forEach((d, idx) => {\n        const x = 70 + idx * 44;\n        const barH = (d / maxDelta) * 80;\n        const y = 150 - barH;\n\n        svgEl.appendChild(el(\"line\", {\n          x1: x, y1: \"150\", x2: x, y2: y,\n          stroke: statType === \"mean\" ? C.primary : C.danger,\n          \"stroke-width\": \"3\"\n        }));\n        svgEl.appendChild(el(\"circle\", {\n          cx: x, cy: y, r: \"5\",\n          fill: statType === \"mean\" ? C.primary : C.danger\n        }));\n\n        svgEl.appendChild(el(\"text\", {\n          x, y: \"170\", \"text-anchor\": \"middle\",\n          fill: C.muted, \"font-size\": \"10\", \"font-family\": \"monospace\"\n        }, [document.createTextNode(`-${idx + 1}`)]));\n      });\n\n      canvasWrap.appendChild(svgEl);\n\n      const expl = h(\"div\", {\n        style: { marginTop: \"0.8rem\", fontSize: \"0.88rem\", color: C.ink },\n        html: statType === \"mean\"\n          ? `<strong>Smooth Response:</strong> When leaving out observations from the mean, each point creates a gentle, continuous shift proportional to its distance from the sample mean. The influence function is differentiable.`\n          : `<strong>Discontinuous Jumps:</strong> For the median, every point outside the centre moves the estimate by exactly the same <strong>\\u00b10.20</strong> \\u2014 the gap between two neighbouring central values \\u2014 no matter how extreme it is, while dropping the central point itself changes nothing at all (<strong>0.00</strong>). The leave-one-out spread has stopped measuring influence, so the jackknife variance formula fails: the sample median lacks Fr\\u00e9chet differentiability.`\n      });\n      canvasWrap.appendChild(expl);\n    }\n\n    render();\n  }\n\n  return {\n    initWidget1,\n    initWidget2,\n    initWidget3,\n    initWidget4\n  };\n})();\n\n// Auto-initialize when DOM and JSON script data are ready\ndocument.addEventListener(\"DOMContentLoaded\", () => {\n  const dataScript = document.getElementById(\"jackknife-data\");\n  let data = {};\n  if (dataScript) {\n    try {\n      data = JSON.parse(dataScript.textContent);\n    } catch (e) {\n      console.error(\"Error parsing jackknife data payload\", e);\n    }\n  }\n\n  if (document.getElementById(\"widget-pseudovalues\")) {\n    JK.initWidget1(\"widget-pseudovalues\", data.toy);\n  }\n  if (document.getElementById(\"widget-syndicate\")) {\n    JK.initWidget2(\"widget-syndicate\", data.syndicate);\n  }\n  if (document.getElementById(\"widget-biomarkers\")) {\n    JK.initWidget3(\"widget-biomarkers\", data.biomarkers);\n  }\n  if (document.getElementById(\"widget-smooth-jagged\")) {\n    JK.initWidget4(\"widget-smooth-jagged\");\n  }\n});\n</script>\n```\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}