<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-07-23">

<title>What TDA Actually Builds: A Filtered Simplicial Complex, Not a Fancy Graph – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">What TDA Actually Builds: A Filtered Simplicial Complex, Not a Fancy Graph</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Topology</div>
                <div class="quarto-category">TDA</div>
                <div class="quarto-category">Mathematics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 23, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#one-toy-point-cloud" id="toc-one-toy-point-cloud" class="nav-link active" data-scroll-target="#one-toy-point-cloud">1. One toy point cloud</a></li>
  <li><a href="#the-distance-matrix-pairwise-facts-not-shape" id="toc-the-distance-matrix-pairwise-facts-not-shape" class="nav-link" data-scroll-target="#the-distance-matrix-pairwise-facts-not-shape">2. The distance matrix: pairwise facts, not shape</a></li>
  <li><a href="#thresholding-produces-a-nested-sequence-of-graphs" id="toc-thresholding-produces-a-nested-sequence-of-graphs" class="nav-link" data-scroll-target="#thresholding-produces-a-nested-sequence-of-graphs">3. Thresholding produces a nested sequence of graphs</a></li>
  <li><a href="#why-a-graph-alone-is-insufficient" id="toc-why-a-graph-alone-is-insufficient" class="nav-link" data-scroll-target="#why-a-graph-alone-is-insufficient">4. Why a graph alone is insufficient</a></li>
  <li><a href="#simplicial-complexes-hypergraph-like-plus-one-crucial-law" id="toc-simplicial-complexes-hypergraph-like-plus-one-crucial-law" class="nav-link" data-scroll-target="#simplicial-complexes-hypergraph-like-plus-one-crucial-law">5. Simplicial complexes: hypergraph-like, plus one crucial law</a></li>
  <li><a href="#the-vietorisrips-complex-cliques-become-simplices" id="toc-the-vietorisrips-complex-cliques-become-simplices" class="nav-link" data-scroll-target="#the-vietorisrips-complex-cliques-become-simplices">6. The Vietoris–Rips complex: cliques become simplices</a></li>
  <li><a href="#from-filtration-to-persistence-two-different-things" id="toc-from-filtration-to-persistence-two-different-things" class="nav-link" data-scroll-target="#from-filtration-to-persistence-two-different-things">7. From filtration to persistence: two different things</a></li>
  <li><a href="#computing-persistence-on-the-toy-cloud" id="toc-computing-persistence-on-the-toy-cloud" class="nav-link" data-scroll-target="#computing-persistence-on-the-toy-cloud">8. Computing persistence on the toy cloud</a>
  <ul class="collapse">
  <li><a href="#the-persistence-diagram" id="toc-the-persistence-diagram" class="nav-link" data-scroll-target="#the-persistence-diagram">The persistence diagram</a></li>
  <li><a href="#the-same-information-as-a-barcode" id="toc-the-same-information-as-a-barcode" class="nav-link" data-scroll-target="#the-same-information-as-a-barcode">The same information as a barcode</a></li>
  <li><a href="#reading-actual-features-out-of-these-figures" id="toc-reading-actual-features-out-of-these-figures" class="nav-link" data-scroll-target="#reading-actual-features-out-of-these-figures">Reading actual features out of these figures</a></li>
  <li><a href="#betti-numbers-at-chosen-scales" id="toc-betti-numbers-at-chosen-scales" class="nav-link" data-scroll-target="#betti-numbers-at-chosen-scales">Betti numbers at chosen scales</a></li>
  </ul></li>
  <li><a href="#glossary-grounded-in-the-running-example" id="toc-glossary-grounded-in-the-running-example" class="nav-link" data-scroll-target="#glossary-grounded-in-the-running-example">9. Glossary, grounded in the running example</a></li>
  <li><a href="#common-misconceptions" id="toc-common-misconceptions" class="nav-link" data-scroll-target="#common-misconceptions">10. Common misconceptions</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tda-filtered-simplicial-complexes/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>What TDA Actually Builds: A Filtered Simplicial Complex, Not a Fancy Graph</figcaption>
</figure>
</div>
<p>If you come to topological data analysis (TDA) from a graphs background, there is one sentence worth internalizing before anything else:</p>
<blockquote class="blockquote">
<p><strong>TDA builds a filtered simplicial complex — a structured, hypergraph-like object — over a fixed set of original data points.</strong></p>
</blockquote>
<p>Every word in that sentence is doing work, and most of the confusion I’ve seen about TDA comes from quietly replacing one of those words with a more familiar graph-theoretic one. “It’s a graph where edges appear as you raise a threshold” is <em>almost</em> right — and the <em>almost</em> is exactly where loops, voids, and persistence live.</p>
<p>This post builds the correct mental model from first principles, using one tiny 2D point cloud — eight points named A through H — that we will follow from raw coordinates all the way to a persistence diagram. Every number, matrix, and figure below is computed live from that same point cloud.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reproducibility: environment setup
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>This post runs in its own virtualenv, registered as a Jupyter kernel per this blog’s convention:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> <span class="at">-m</span> venv .venv-tda-filtered</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="ex">.venv-tda-filtered/bin/pip</span> install numpy scipy matplotlib networkx ripser persim ipykernel</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">.venv-tda-filtered/bin/python</span> <span class="at">-m</span> ipykernel install <span class="at">--user</span> <span class="at">--name</span> tda-filtered-blog</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Key versions at render time are printed in the setup cell below. The random seed is fixed, so every figure and number reproduces exactly.</p>
</div>
</div>
</div>
<div id="1104b9db" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Setup: imports, style constants, and the drawing helper used throughout</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> itertools</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> networkx <span class="im">as</span> nx</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> ripser</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.colors <span class="im">import</span> LinearSegmentedColormap</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.spatial.distance <span class="im">import</span> pdist, squareform</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"numpy </span><span class="sc">{</span>np<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss"> · scipy </span><span class="sc">{</span>scipy<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss"> · "</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"networkx </span><span class="sc">{</span>nx<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss"> · ripser </span><span class="sc">{</span>ripser<span class="sc">.</span>__version__<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="co"># --- shared color roles (validated palette) ---------------------------------</span></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>INK <span class="op">=</span> <span class="st">"#0b0b0b"</span>      <span class="co"># vertices, primary text</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>MUTED <span class="op">=</span> <span class="st">"#898781"</span>    <span class="co"># axis labels, ticks</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>GRIDC <span class="op">=</span> <span class="st">"#e1e0d9"</span>    <span class="co"># hairline grid</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>BLUE <span class="op">=</span> <span class="st">"#2a78d6"</span>     <span class="co"># edges (1-simplices), H0 series</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>ORANGE <span class="op">=</span> <span class="st">"#eb6834"</span>   <span class="co"># H1 series</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>VIOLET <span class="op">=</span> <span class="st">"#4a3aa7"</span>   <span class="co"># filled triangles (2-simplices), H2 series</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>SEQ_RAMP <span class="op">=</span> LinearSegmentedColormap.from_list(</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">"blue_seq"</span>, [<span class="st">"#cde2fb"</span>, <span class="st">"#86b6ef"</span>, <span class="st">"#3987e5"</span>, <span class="st">"#1c5cab"</span>, <span class="st">"#0d366b"</span>]</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update(</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>        <span class="st">"font.family"</span>: <span class="st">"sans-serif"</span>,</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>        <span class="st">"axes.edgecolor"</span>: MUTED,</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>        <span class="st">"axes.labelcolor"</span>: MUTED,</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>        <span class="st">"xtick.color"</span>: MUTED,</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>        <span class="st">"ytick.color"</span>: MUTED,</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>        <span class="st">"axes.titlecolor"</span>: INK,</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>        <span class="st">"figure.dpi"</span>: <span class="dv">120</span>,</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> style_axes(ax, keep_ticks<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Recessive chrome: no spines, optional ticks."""</span></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> side <span class="kw">in</span> (<span class="st">"top"</span>, <span class="st">"right"</span>, <span class="st">"left"</span>, <span class="st">"bottom"</span>):</span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a>        ax.spines[side].set_visible(<span class="va">False</span>)</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> keep_ticks:</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>        ax.set_xticks([])</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>        ax.set_yticks([])</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_complex(ax, eps, show_triangles<span class="op">=</span><span class="va">True</span>, node_size<span class="op">=</span><span class="dv">210</span>, font_size<span class="op">=</span><span class="fl">8.5</span>):</span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Draw the Vietoris-Rips complex at scale eps over the fixed points.</span></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a><span class="co">    Filled violet patches are 2-simplices (3-cliques of the threshold</span></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a><span class="co">    graph), blue segments are 1-simplices, ink dots are the fixed vertices.</span></span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(points)</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>    n_tri <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> show_triangles <span class="kw">and</span> eps <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i, j, k <span class="kw">in</span> itertools.combinations(<span class="bu">range</span>(n), <span class="dv">3</span>):</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="bu">max</span>(D[i, j], D[i, k], D[j, k]) <span class="op">&lt;=</span> eps:</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>                n_tri <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>                ax.add_patch(</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>                    plt.Polygon(</span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>                        points[[i, j, k]],</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a>                        closed<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a>                        facecolor<span class="op">=</span>VIOLET,</span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a>                        alpha<span class="op">=</span><span class="fl">0.20</span>,</span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a>                        edgecolor<span class="op">=</span><span class="st">"none"</span>,</span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a>                        zorder<span class="op">=</span><span class="dv">1</span>,</span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>                    )</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>                )</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>    n_edges <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, j <span class="kw">in</span> itertools.combinations(<span class="bu">range</span>(n), <span class="dv">2</span>) <span class="cf">if</span> eps <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> []:</span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> D[i, j] <span class="op">&lt;=</span> eps:</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a>            n_edges <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a>            ax.plot(</span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a>                points[[i, j], <span class="dv">0</span>], points[[i, j], <span class="dv">1</span>], color<span class="op">=</span>BLUE, lw<span class="op">=</span><span class="dv">2</span>, zorder<span class="op">=</span><span class="dv">2</span></span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>    ax.scatter(points[:, <span class="dv">0</span>], points[:, <span class="dv">1</span>], s<span class="op">=</span>node_size, color<span class="op">=</span>INK, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> lbl, (x, y) <span class="kw">in</span> <span class="bu">zip</span>(labels, points):</span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a>        ax.text(</span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a>            x, y, lbl, color<span class="op">=</span><span class="st">"white"</span>, fontsize<span class="op">=</span>font_size, fontweight<span class="op">=</span><span class="st">"bold"</span>,</span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a>            ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, zorder<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a>    ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(<span class="op">-</span><span class="fl">1.45</span>, <span class="fl">3.35</span>)</span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a>    ax.set_ylim(<span class="op">-</span><span class="fl">1.45</span>, <span class="fl">1.95</span>)</span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a>    style_axes(ax)</span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> n_edges, n_tri</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>numpy 2.5.1 · scipy 1.18.0 · networkx 3.6.1 · ripser 0.6.15</code></pre>
</div>
</div>
<section id="one-toy-point-cloud" class="level2">
<h2 class="anchored" data-anchor-id="one-toy-point-cloud">1. One toy point cloud</h2>
<p>We need a point cloud small enough to inspect by hand but rich enough to show all the phenomena we care about: <strong>disconnected pieces at small scales, a loop at intermediate scales, and triangles that eventually fill that loop in.</strong></p>
<p>Six points jittered around a circle give us the loop; a tight pair off to the side gives us a component that stays separate for a long time. The seed is fixed, so these are <em>the</em> coordinates for the rest of the post.</p>
<div id="cell-fig-cloud" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">42</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>angles <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">2</span> <span class="op">*</span> np.pi, <span class="dv">6</span>, endpoint<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>circle_points <span class="op">=</span> np.column_stack([np.cos(angles), np.sin(angles)])</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>circle_points <span class="op">+=</span> rng.normal(scale<span class="op">=</span><span class="fl">0.08</span>, size<span class="op">=</span>circle_points.shape)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>pair <span class="op">=</span> np.array([[<span class="fl">2.6</span>, <span class="fl">1.10</span>], [<span class="fl">2.9</span>, <span class="fl">1.45</span>]])</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>points <span class="op">=</span> np.vstack([circle_points, pair])</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> <span class="bu">list</span>(<span class="st">"ABCDEFGH"</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">4</span>))</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>draw_complex(ax, eps<span class="op">=</span><span class="fl">0.0</span>, show_triangles<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"The toy point cloud"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-cloud" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cloud-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-cloud-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cloud-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The running example: eight 2D points. A–F sit roughly on a circle; G and H form a tight pair off to the upper right. Nothing topological has happened yet — this is just a set of coordinates.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Keep the letters in mind: <strong>A–F</strong> are the would-be loop, <strong>G–H</strong> are the satellite pair. Every later figure uses these same positions.</p>
</section>
<section id="the-distance-matrix-pairwise-facts-not-shape" class="level2">
<h2 class="anchored" data-anchor-id="the-distance-matrix-pairwise-facts-not-shape">2. The distance matrix: pairwise facts, not shape</h2>
<p>The only raw ingredient TDA consumes from this point cloud is the <strong>pairwise distance matrix</strong> <span class="math inline">\(D\)</span>, where entry <span class="math inline">\(D_{ij}\)</span> is the Euclidean distance <span class="math inline">\(\lVert x_i - x_j \rVert\)</span> between point <span class="math inline">\(i\)</span> and point <span class="math inline">\(j\)</span>. Reading one entry: <span class="math inline">\(D_{GH} \approx 0.46\)</span> means G and H are 0.46 apart — the closest pair in the data.</p>
<div id="cell-fig-distmat" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> squareform(pdist(points))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.4</span>, <span class="fl">5.4</span>))</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>im <span class="op">=</span> ax.imshow(D, cmap<span class="op">=</span>SEQ_RAMP)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>ax.set_xticks(<span class="bu">range</span>(<span class="dv">8</span>), labels)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(<span class="bu">range</span>(<span class="dv">8</span>), labels)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>ax.tick_params(length<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> side <span class="kw">in</span> (<span class="st">"top"</span>, <span class="st">"right"</span>, <span class="st">"left"</span>, <span class="st">"bottom"</span>):</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    ax.spines[side].set_visible(<span class="va">False</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>mid <span class="op">=</span> D.<span class="bu">max</span>() <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">8</span>):</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">8</span>):</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>        ax.text(</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>            j, i, <span class="ss">f"</span><span class="sc">{</span>D[i, j]<span class="sc">:.2f}</span><span class="ss">"</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>            ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="fl">7.5</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>            color<span class="op">=</span><span class="st">"white"</span> <span class="cf">if</span> D[i, j] <span class="op">&gt;</span> mid <span class="cf">else</span> INK,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>cbar <span class="op">=</span> fig.colorbar(im, ax<span class="op">=</span>ax, shrink<span class="op">=</span><span class="fl">0.85</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>cbar.set_label(<span class="st">"Euclidean distance"</span>, color<span class="op">=</span>MUTED)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>cbar.outline.set_visible(<span class="va">False</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Pairwise distance matrix"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-distmat" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-distmat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-distmat-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-distmat-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The 8×8 Euclidean distance matrix, annotated to two decimals. Darker blue = farther apart. The matrix is symmetric with a zero diagonal. It records pairwise distances only — which pairs are close — and says nothing <em>by itself</em> about components, loops, or voids.
</figcaption>
</figure>
</div>
</div>
</div>
<p>A caution worth stating explicitly: this matrix is <strong>not a topological summary</strong>. It is the <em>input</em> from which topological structure will be built. In particular, no amount of staring at raw matrix entries — or taking matrix powers, as one might with a graph adjacency matrix — directly reveals loops or voids. Powers of an <em>adjacency</em> matrix count walks in a graph; the distance matrix isn’t even an adjacency matrix, and “shape” will only emerge once we make explicit choices about scale, which we do next.</p>
</section>
<section id="thresholding-produces-a-nested-sequence-of-graphs" class="level2">
<h2 class="anchored" data-anchor-id="thresholding-produces-a-nested-sequence-of-graphs">3. Thresholding produces a nested sequence of graphs</h2>
<p>Here is the first genuinely structural move. Pick a scale <span class="math inline">\(\varepsilon \geq 0\)</span> and define a graph <span class="math inline">\(G_\varepsilon\)</span>:</p>
<ul>
<li><strong>the vertex set is fixed</strong>: it is always exactly our eight points A–H, at every scale;</li>
<li><strong>the edge set grows</strong>: connect <span class="math inline">\(x_i\)</span> and <span class="math inline">\(x_j\)</span> whenever <span class="math inline">\(D_{ij} \leq \varepsilon\)</span>.</li>
</ul>
<p>Because the vertex set never changes and edges only accumulate as <span class="math inline">\(\varepsilon\)</span> grows, these graphs are <strong>nested</strong>:</p>
<p><span class="math display">\[
G_{\varepsilon_1} \subseteq G_{\varepsilon_2} \subseteq G_{\varepsilon_3} \subseteq \cdots
\qquad \text{whenever } \varepsilon_1 \leq \varepsilon_2 \leq \varepsilon_3 \leq \cdots
\]</span></p>
<p>Each graph contains all the edges of every earlier one, plus possibly more. Nothing is ever removed. Watch the toy cloud pass through four scales:</p>
<div id="cell-fig-threshold" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>threshold_eps <span class="op">=</span> [<span class="fl">0.6</span>, <span class="fl">0.9</span>, <span class="fl">1.25</span>, <span class="fl">1.9</span>]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="fl">3.4</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, eps <span class="kw">in</span> <span class="bu">zip</span>(axes, threshold_eps):</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    n_edges, _ <span class="op">=</span> draw_complex(ax, eps, show_triangles<span class="op">=</span><span class="va">False</span>, node_size<span class="op">=</span><span class="dv">130</span>, font_size<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    G <span class="op">=</span> nx.Graph()</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    G.add_nodes_from(labels)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    G.add_edges_from(</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        (labels[i], labels[j])</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i, j <span class="kw">in</span> itertools.combinations(<span class="bu">range</span>(<span class="dv">8</span>), <span class="dv">2</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> D[i, j] <span class="op">&lt;=</span> eps</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    n_comp <span class="op">=</span> nx.number_connected_components(G)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    edge_word <span class="op">=</span> <span class="st">"edge"</span> <span class="cf">if</span> n_edges <span class="op">==</span> <span class="dv">1</span> <span class="cf">else</span> <span class="st">"edges"</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    ax.set_title(</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"$</span><span class="ch">\\</span><span class="ss">varepsilon$ = </span><span class="sc">{</span>eps<span class="sc">}</span><span class="ch">\n</span><span class="sc">{</span>n_edges<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>edge_word<span class="sc">}</span><span class="ss"> · </span><span class="sc">{</span>n_comp<span class="sc">}</span><span class="ss"> components"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>        fontsize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>fig.suptitle(</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"One fixed vertex set, a growing edge set"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>, y<span class="op">=</span><span class="fl">1.06</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-threshold" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-threshold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-threshold-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-threshold-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Threshold graphs at four scales, drawn over the identical fixed coordinates. ε = 0.6: only the closest pair (G–H, distance 0.46) is joined — seven components. ε = 0.9: A–F and C–D have joined in — five components. ε = 1.25: the six circle points close into a ring, leaving two components. ε = 1.9: many long edges have appeared; the pair still hangs on as its own component until ε ≈ 1.97. Every panel’s edge set contains the previous panel’s.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Two things to notice. First, <strong>the points never move and are never added or removed</strong> — only our willingness to call a pair “close” changes. Second, connectivity questions (“how many components?”) are already answerable at this stage with ordinary graph theory. If components were all we cared about, we could stop here (this is essentially what single-linkage clustering does). But we want loops and voids too, and for those, graphs are about to run out of vocabulary.</p>
</section>
<section id="why-a-graph-alone-is-insufficient" class="level2">
<h2 class="anchored" data-anchor-id="why-a-graph-alone-is-insufficient">4. Why a graph alone is insufficient</h2>
<p>Here is the tempting shortcut: <em>“Fine, so it’s a graph per scale. If I need more structure, I’ll decorate it — edge weights, edge colors, labels. A sufficiently annotated graph should carry all the information.”</em></p>
<p>This intuition is wrong in a precise and instructive way. Consider points C, D, E, which by <span class="math inline">\(\varepsilon = 1.75\)</span> are all pairwise within range (<span class="math inline">\(D_{CD} \approx 0.86\)</span>, <span class="math inline">\(D_{DE} \approx 1.03\)</span>, <span class="math inline">\(D_{CE} \approx 1.70\)</span>):</p>
<div id="cell-fig-triangle" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>sub <span class="op">=</span> [labels.index(c) <span class="cf">for</span> c <span class="kw">in</span> <span class="st">"CDE"</span>]</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>tri <span class="op">=</span> points[sub]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">3.8</span>))</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, filled <span class="kw">in</span> <span class="bu">zip</span>(axes, [<span class="va">False</span>, <span class="va">True</span>]):</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> filled:</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>        ax.add_patch(</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>            plt.Polygon(tri, closed<span class="op">=</span><span class="va">True</span>, facecolor<span class="op">=</span>VIOLET, alpha<span class="op">=</span><span class="fl">0.25</span>,</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>                        edgecolor<span class="op">=</span><span class="st">"none"</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, j <span class="kw">in</span> itertools.combinations(<span class="bu">range</span>(<span class="dv">3</span>), <span class="dv">2</span>):</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        ax.plot(tri[[i, j], <span class="dv">0</span>], tri[[i, j], <span class="dv">1</span>], color<span class="op">=</span>BLUE, lw<span class="op">=</span><span class="fl">2.2</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    ax.scatter(tri[:, <span class="dv">0</span>], tri[:, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">260</span>, color<span class="op">=</span>INK, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> lbl, (x, y) <span class="kw">in</span> <span class="bu">zip</span>(<span class="st">"CDE"</span>, tri):</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>        ax.text(x, y, lbl, color<span class="op">=</span><span class="st">"white"</span>, fontsize<span class="op">=</span><span class="dv">10</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>                ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, zorder<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(<span class="op">-</span><span class="fl">1.35</span>, <span class="fl">0.05</span>)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    ax.set_ylim(<span class="op">-</span><span class="fl">1.25</span>, <span class="fl">1.15</span>)</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    style_axes(ax)</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Boundary only: three 1-simplices</span><span class="ch">\n</span><span class="st">(a cycle with a hole)"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Filled 2-simplex {C, D, E}</span><span class="ch">\n</span><span class="st">(one 3-way object; hole destroyed)"</span>, fontsize<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-triangle" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-triangle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-triangle-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-triangle-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Left: the triangle <em>boundary</em> — three edges C–D, D–E, C–E, each a relationship between exactly two points. This is a 1-dimensional cycle: you can walk around it, and it encloses a hole. Right: the <em>filled</em> 2-simplex {C, D, E} — a single three-way relationship, drawn as a violet membrane. The filled triangle is a different object, not a styling of the edges: its presence declares that the cycle around it bounds nothing, killing the hole.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The core issue is arity. <strong>An edge, no matter how you weight, color, or label it, is a relationship between exactly two endpoints.</strong> A filled triangle is a <em>single</em> relationship among <em>three</em> points at once. It is not “three edges plus a style”; it is a genuinely different kind of object, the same way a 3-way interaction term in a regression is not a decorated pair of 2-way terms.</p>
<p>The distinction matters because of what each object does topologically:</p>
<ul>
<li>The <strong>triangular cycle</strong> C–D–E–C (three edges) is a candidate 1-dimensional loop: a closed path that may enclose a hole.</li>
<li>The <strong>filled 2-simplex</strong> <span class="math inline">\(\{C, D, E\}\)</span> <em>fills</em> that cycle: it certifies that the loop bounds a membrane and therefore does not count as a hole.</li>
</ul>
<p>Ordinary graph structure can express connectivity and can even enumerate cycles. What it cannot express is <strong>whether a cycle is filled</strong> — and “is this loop filled or is it a real hole?” is exactly the question TDA is designed to answer. To ask it, we need a structure whose vocabulary includes higher-dimensional pieces natively.</p>
</section>
<section id="simplicial-complexes-hypergraph-like-plus-one-crucial-law" class="level2">
<h2 class="anchored" data-anchor-id="simplicial-complexes-hypergraph-like-plus-one-crucial-law">5. Simplicial complexes: hypergraph-like, plus one crucial law</h2>
<p>The intuitive picture first. We want a structure that records relationships of every arity over our fixed points:</p>
<ul>
<li>a relationship involving <strong>one</strong> point — the point itself being present;</li>
<li>a relationship involving <strong>two</strong> points — an edge;</li>
<li>a relationship involving <strong>three</strong> points — a filled triangle;</li>
<li>a relationship involving <strong>four</strong> points — a filled tetrahedron; and so on.</li>
</ul>
<p>If you know hypergraphs, this smells like one: a set system over a vertex set, with “hyperedges” of any size. That intuition is a fine on-ramp. Now the exact vocabulary:</p>
<ul>
<li><p>A <strong>simplex</strong> is a finite set of vertices, interpreted geometrically by its size: a 1-element set is a <strong>0-simplex</strong> (vertex), a 2-element set a <strong>1-simplex</strong> (edge), a 3-element set a <strong>2-simplex</strong> (filled triangle), a 4-element set a <strong>3-simplex</strong> (solid tetrahedron), and in general a <span class="math inline">\((k{+}1)\)</span>-element set is a <span class="math inline">\(k\)</span>-simplex. The subsets of a simplex are its <strong>faces</strong>: the faces of <span class="math inline">\(\{C, D, E\}\)</span> are its three edges, its three vertices (and itself).</p></li>
<li><p>An <strong>abstract simplicial complex</strong> is a collection of simplices that is <strong>closed under taking faces</strong>: if a simplex is in the complex, every face of it must be in the complex too.</p></li>
</ul>
<p>That closure property is the law that separates a simplicial complex from a generic hypergraph, and it is worth spelling out concretely. If the filled triangle <span class="math inline">\(\{C, D, E\}\)</span> is present, then the edges <span class="math inline">\(\{C,D\}, \{D,E\}, \{C,E\}\)</span> <strong>must</strong> be present, and so must the vertices <span class="math inline">\(\{C\}, \{D\}, \{E\}\)</span>. A hypergraph is under no such obligation — it may happily contain a 3-way hyperedge <span class="math inline">\(\{C, D, E\}\)</span> without containing <span class="math inline">\(\{C, D\}\)</span>. So “hypergraph-like” is honest intuition, but a simplicial complex is <em>not</em> merely a hypergraph: the closure property is the extra structure, and it is precisely what makes it meaningful to talk about a triangle <em>filling</em> the cycle formed by its own edges. Boundaries are guaranteed to exist inside the complex; filled things always have their skeletons present.</p>
<p>With this vocabulary, the earlier figure reads cleanly: the left panel is the complex <span class="math inline">\(\{\{C\},\{D\},\{E\},\{C,D\},\{D,E\},\{C,E\}\}\)</span>; the right panel is that same complex <strong>plus the single extra simplex</strong> <span class="math inline">\(\{C,D,E\}\)</span>. One added set — that’s the entire difference between “hole” and “no hole”.</p>
</section>
<section id="the-vietorisrips-complex-cliques-become-simplices" class="level2">
<h2 class="anchored" data-anchor-id="the-vietorisrips-complex-cliques-become-simplices">6. The Vietoris–Rips complex: cliques become simplices</h2>
<p>We now have the target structure (simplicial complex) and a scale-indexed family of graphs. The bridge between them, and the construction this post uses throughout, is the <strong>Vietoris–Rips complex</strong> <span class="math inline">\(\mathrm{VR}_\varepsilon\)</span>:</p>
<blockquote class="blockquote">
<p>Start from the threshold graph <span class="math inline">\(G_\varepsilon\)</span>. Add a simplex for <strong>every clique</strong> in that graph. Equivalently: a set of points forms a simplex whenever <strong>every pair</strong> in the set is within distance <span class="math inline">\(\varepsilon\)</span>.</p>
</blockquote>
<p><span class="math display">\[
\{x_{i_0}, \ldots, x_{i_k}\} \in \mathrm{VR}_\varepsilon
\iff
D_{i_p i_q} \leq \varepsilon \ \text{ for every pair } p, q .
\]</span></p>
<p>Closure under faces is automatic: every subset of a clique is a clique. Here is the toy cloud’s Rips complex at four scales:</p>
<div id="cell-fig-rips" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>rips_eps <span class="op">=</span> [<span class="fl">0.9</span>, <span class="fl">1.25</span>, <span class="fl">1.75</span>, <span class="fl">1.9</span>]</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="dv">7</span>))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, eps <span class="kw">in</span> <span class="bu">zip</span>(axes.flat, rips_eps):</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    n_edges, n_tri <span class="op">=</span> draw_complex(ax, eps, node_size<span class="op">=</span><span class="dv">150</span>, font_size<span class="op">=</span><span class="fl">7.5</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    ax.set_title(</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"$</span><span class="ch">\\</span><span class="ss">varepsilon$ = </span><span class="sc">{</span>eps<span class="sc">}</span><span class="ss"> · </span><span class="sc">{</span>n_edges<span class="sc">}</span><span class="ss"> edges · </span><span class="sc">{</span>n_tri<span class="sc">}</span><span class="ss"> filled triangles"</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>        fontsize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>fig.suptitle(</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Vietoris–Rips complexes: every clique becomes a simplex"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-rips" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-rips-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-rips-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-rips-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Vietoris–Rips complexes at four scales. Ink dots are 0-simplices (always all eight), blue segments 1-simplices, violet patches filled 2-simplices; where patches overlap the violet deepens. ε = 0.9: a few edges, no triangles. ε = 1.25: the ring closes — a genuine 1-dimensional loop, with no triangles yet to dispute it. ε = 1.75: four triangles have filled in and the loop has shrunk to the still-unfilled middle. ε = 1.9: enough triangles overlap that the central cycle is entirely filled — the loop is dead.
</figcaption>
</figure>
</div>
</div>
</div>
<p>One subtlety the drawings can’t show: simplices above dimension 2 exist in this construction but can’t be rendered as flat pictures. A count by dimension makes them visible:</p>
<div id="4d3a4b9c" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Count simplices by dimension at each scale (cliques of the threshold graph)</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> simplex_counts(eps, max_size<span class="op">=</span><span class="dv">5</span>):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    counts <span class="op">=</span> {}</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> size <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, max_size <span class="op">+</span> <span class="dv">1</span>):</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>        counts[size <span class="op">-</span> <span class="dv">1</span>] <span class="op">=</span> <span class="bu">sum</span>(</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>            <span class="dv">1</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> combo <span class="kw">in</span> itertools.combinations(<span class="bu">range</span>(<span class="dv">8</span>), size)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="bu">all</span>(D[i, j] <span class="op">&lt;=</span> eps <span class="cf">for</span> i, j <span class="kw">in</span> itertools.combinations(combo, <span class="dv">2</span>))</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> counts</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [<span class="st">"| $</span><span class="ch">\\</span><span class="st">varepsilon$ | 0-simplices | 1-simplices | 2-simplices | 3-simplices |"</span>,</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"|---|---|---|---|---|"</span>]</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> eps <span class="kw">in</span> [<span class="fl">0.9</span>, <span class="fl">1.25</span>, <span class="fl">1.75</span>, <span class="fl">1.9</span>, <span class="fl">2.0</span>]:</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    c <span class="op">=</span> simplex_counts(eps)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    rows.append(<span class="ss">f"| </span><span class="sc">{</span>eps<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>c[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>c[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>c[<span class="dv">2</span>]<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>c[<span class="dv">3</span>]<span class="sc">}</span><span class="ss"> |"</span>)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>Markdown(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>.join(rows))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="7">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\varepsilon\)</span></th>
<th>0-simplices</th>
<th>1-simplices</th>
<th>2-simplices</th>
<th>3-simplices</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.9</td>
<td>8</td>
<td>3</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>1.25</td>
<td>8</td>
<td>7</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>1.75</td>
<td>8</td>
<td>11</td>
<td>4</td>
<td>0</td>
</tr>
<tr class="even">
<td>1.9</td>
<td>8</td>
<td>13</td>
<td>8</td>
<td>0</td>
</tr>
<tr class="odd">
<td>2.0</td>
<td>8</td>
<td>15</td>
<td>12</td>
<td>4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>At <span class="math inline">\(\varepsilon = 2.0\)</span> a 3-simplex appears: C, D, E, F have become pairwise close (the longest pair, C–F, sits at <span class="math inline">\(\approx 1.99\)</span>), so the <em>solid tetrahedron</em> <span class="math inline">\(\{C,D,E,F\}\)</span> enters the complex — a four-way relationship we can only tabulate, not draw in the plane. Note something conceptually pleasing here: our points live in 2D, but the Rips complex is an <strong>abstract</strong> simplicial complex built from the distance matrix alone. It doesn’t know or care about the plane, and it is free to contain 3-simplices — and, as we’ll see shortly, even a 2-dimensional void.</p>
<p>Worth a brief aside: Vietoris–Rips is not the only way to turn a point cloud into complexes. The <strong>Čech complex</strong> includes a simplex when the points’ <span class="math inline">\(\varepsilon/2\)</span>-balls share a <em>common</em> intersection point, which is a strictly stronger requirement than pairwise proximity and has nicer theoretical guarantees, at higher computational cost. Everything below applies to either; we use Rips because it’s what fast libraries compute.</p>
</section>
<section id="from-filtration-to-persistence-two-different-things" class="level2">
<h2 class="anchored" data-anchor-id="from-filtration-to-persistence-two-different-things">7. From filtration to persistence: two different things</h2>
<p>Because <span class="math inline">\(\mathrm{VR}_\varepsilon\)</span> is built from cliques of a graph whose edges only accumulate, the Rips complexes are nested exactly as the graphs were:</p>
<p><span class="math display">\[
\mathrm{VR}_{\varepsilon_1} \subseteq \mathrm{VR}_{\varepsilon_2} \subseteq \cdots
\]</span></p>
<p>This nested, scale-indexed family is called a <strong>filtration</strong>. Each simplex has a well-defined arrival time: it enters at the scale equal to its longest pairwise distance (its <em>diameter</em>).</p>
<p>Now, a distinction that is easy to blur and important to keep sharp:</p>
<ul>
<li><strong>The filtration is bookkeeping.</strong> Knowing <em>which simplices are present at each scale</em> is a purely combinatorial fact — we just computed it in the table above.</li>
<li><strong>Persistence is a computation on top of it.</strong> Knowing <em>which components, loops, and voids exist</em> at each scale — and when each is born and dies — requires algebraic topology, specifically <strong>homology</strong>, applied across the whole filtration.</li>
</ul>
<p>Why isn’t the bookkeeping enough? Because “is there a loop?” is not a local question about individual simplices. Homology answers it by a quotient: in each dimension <span class="math inline">\(k\)</span> it considers the <strong><span class="math inline">\(k\)</span>-cycles</strong> (closed <span class="math inline">\(k\)</span>-dimensional configurations, like our edge-cycle around the ring) <em>modulo</em> the <strong>boundaries</strong> (cycles that are filled in by <span class="math inline">\((k{+}1)\)</span>-simplices, like the edge-cycle C–D–E once <span class="math inline">\(\{C,D,E\}\)</span> is present). A hole is a cycle that is not a boundary. The count of independent such holes in dimension <span class="math inline">\(k\)</span> is the <strong>Betti number</strong> <span class="math inline">\(\beta_k\)</span>: <span class="math inline">\(\beta_0\)</span> counts connected components, <span class="math inline">\(\beta_1\)</span> independent loops, <span class="math inline">\(\beta_2\)</span> independent enclosed voids.</p>
<p>Mechanically, this is linear algebra: one builds <strong>boundary maps</strong> <span class="math inline">\(\partial_k\)</span> sending each <span class="math inline">\(k\)</span>-simplex to the alternating sum of its faces, and Betti numbers fall out of the ranks of these maps (<span class="math inline">\(\beta_k = \dim\ker\partial_k - \operatorname{rank}\partial_{k+1}\)</span>). <strong>Persistent</strong> homology runs this computation not at one scale but coherently across the entire filtration, tracking each individual hole from the scale where it is <strong>born</strong> to the scale where it <strong>dies</strong> (gets filled in or merges into something older). We won’t derive the matrix reduction algorithm here — the point is that persistence pairs up birth and death <em>scales</em>, which is strictly more information than Betti numbers at any single scale you could have picked in advance.</p>
</section>
<section id="computing-persistence-on-the-toy-cloud" class="level2">
<h2 class="anchored" data-anchor-id="computing-persistence-on-the-toy-cloud">8. Computing persistence on the toy cloud</h2>
<p>Time to hand our eight points to a real library. <code>ripser</code> computes Rips persistence directly from the point cloud (internally, from the same distance matrix we built by hand).</p>
<p>Conventions, stated explicitly so the numbers below are unambiguous: <code>ripser</code> includes a simplex as soon as its diameter is <span class="math inline">\(\leq \varepsilon\)</span> — the same weak inequality we used for the threshold graphs — and its filtration values are in the <em>same units as our distances</em>, so a birth of 1.23 means “born at <span class="math inline">\(\varepsilon = 1.23\)</span>”, directly comparable to every <span class="math inline">\(\varepsilon\)</span> in the figures above. In <span class="math inline">\(H_0\)</span>, one component never dies (the whole dataset is connected for large <span class="math inline">\(\varepsilon\)</span>), so one bar extends to infinity.</p>
<div id="ad74335e" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Compute persistent homology with ripser (dimensions 0, 1, 2)</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>res <span class="op">=</span> ripser.ripser(points, maxdim<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dgms <span class="op">=</span> res[<span class="st">"dgms"</span>]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, dgm <span class="kw">in</span> <span class="bu">enumerate</span>(dgms):</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"H</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss"> intervals (birth, death):"</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b, d <span class="kw">in</span> dgm:</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"  (</span><span class="sc">{</span>b<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span><span class="st">'∞'</span> <span class="cf">if</span> np<span class="sc">.</span>isinf(d) <span class="cf">else</span> <span class="ss">f'</span><span class="sc">{</span>d<span class="sc">:.3f}</span><span class="ss">'</span><span class="sc">}</span><span class="ss">)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>H0 intervals (birth, death):
  (0.000, 0.461)
  (0.000, 0.852)
  (0.000, 0.855)
  (0.000, 1.032)
  (0.000, 1.080)
  (0.000, 1.125)
  (0.000, 1.970)
  (0.000, ∞)
H1 intervals (birth, death):
  (1.229, 1.827)
H2 intervals (birth, death):
  (1.881, 1.989)</code></pre>
</div>
</div>
<section id="the-persistence-diagram" class="level3">
<h3 class="anchored" data-anchor-id="the-persistence-diagram">The persistence diagram</h3>
<p>Each hole becomes a single point <span class="math inline">\((b, d)\)</span>: born at scale <span class="math inline">\(b\)</span>, dead at scale <span class="math inline">\(d\)</span>. Points far above the diagonal persisted across a wide range of scales; points hugging the diagonal barely existed.</p>
<div id="cell-fig-diagram" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>finite_max <span class="op">=</span> <span class="bu">max</span>(d <span class="cf">for</span> dgm <span class="kw">in</span> dgms <span class="cf">for</span> _, d <span class="kw">in</span> dgm <span class="cf">if</span> np.isfinite(d))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>lim <span class="op">=</span> finite_max <span class="op">*</span> <span class="fl">1.12</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>inf_y <span class="op">=</span> lim <span class="op">*</span> <span class="fl">1.06</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="fl">6.2</span>))</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>ax.set_facecolor(<span class="st">"none"</span>)</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">0</span>, lim], [<span class="dv">0</span>, lim], color<span class="op">=</span>GRIDC, lw<span class="op">=</span><span class="fl">1.2</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>ax.axhline(inf_y, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="dv">1</span>, ls<span class="op">=</span>(<span class="dv">0</span>, (<span class="dv">4</span>, <span class="dv">4</span>)), zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">0.12</span>, inf_y, <span class="st">"∞ "</span>, ha<span class="op">=</span><span class="st">"right"</span>, va<span class="op">=</span><span class="st">"center"</span>, color<span class="op">=</span>MUTED, fontsize<span class="op">=</span><span class="dv">11</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>series <span class="op">=</span> [(<span class="st">"$H_0$ components"</span>, BLUE, <span class="st">"o"</span>),</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>          (<span class="st">"$H_1$ loops"</span>, ORANGE, <span class="st">"s"</span>),</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>          (<span class="st">"$H_2$ voids"</span>, VIOLET, <span class="st">"^"</span>)]</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dgm, (name, color, marker) <span class="kw">in</span> <span class="bu">zip</span>(dgms, series):</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    births <span class="op">=</span> dgm[:, <span class="dv">0</span>]</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    deaths <span class="op">=</span> np.where(np.isinf(dgm[:, <span class="dv">1</span>]), inf_y, dgm[:, <span class="dv">1</span>])</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    ax.scatter(births, deaths, s<span class="op">=</span><span class="dv">70</span>, color<span class="op">=</span>color, marker<span class="op">=</span>marker, label<span class="op">=</span>name,</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>               zorder<span class="op">=</span><span class="dv">3</span>, edgecolors<span class="op">=</span><span class="st">"white"</span>, linewidths<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">"the ring A–F</span><span class="ch">\n</span><span class="st">(1.23, 1.83)"</span>, xy<span class="op">=</span>(<span class="fl">1.23</span>, <span class="fl">1.83</span>), xytext<span class="op">=</span>(<span class="fl">0.35</span>, <span class="fl">1.62</span>),</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>            fontsize<span class="op">=</span><span class="dv">9</span>, color<span class="op">=</span>INK,</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-"</span>, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">"G–H pair joins</span><span class="ch">\n</span><span class="st">the rest (1.97)"</span>, xy<span class="op">=</span>(<span class="fl">0.0</span>, <span class="fl">1.97</span>), xytext<span class="op">=</span>(<span class="fl">0.42</span>, <span class="fl">2.06</span>),</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>            fontsize<span class="op">=</span><span class="dv">9</span>, color<span class="op">=</span>INK,</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-"</span>, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="op">-</span><span class="fl">0.08</span>, lim)</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="op">-</span><span class="fl">0.08</span>, inf_y <span class="op">*</span> <span class="fl">1.05</span>)</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"birth scale $</span><span class="ch">\\</span><span class="st">varepsilon$"</span>)</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"death scale $</span><span class="ch">\\</span><span class="st">varepsilon$"</span>)</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> side <span class="kw">in</span> (<span class="st">"top"</span>, <span class="st">"right"</span>):</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>    ax.spines[side].set_visible(<span class="va">False</span>)</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>ax.grid(color<span class="op">=</span>GRIDC, lw<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>ax.set_axisbelow(<span class="va">True</span>)</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, loc<span class="op">=</span><span class="st">"lower right"</span>, labelcolor<span class="op">=</span>INK)</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Persistence diagram"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-diagram" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-diagram-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diagram-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Persistence diagram for the toy cloud. Both axes are the scale parameter ε — there is no time axis. Blue circles (H₀): component mergers, including the long-lived bar for the G–H pair dying at ε ≈ 1.97, and one immortal component plotted on the dashed ∞ line. The orange square (H₁) is the ring A–F: born 1.23, dead 1.83 — far off the diagonal, hence a real feature. The violet triangle (H₂) is a fleeting abstract void, born 1.88 and filled at 1.99 by the tetrahedron {C,D,E,F} — close to the diagonal, hence more curiosity than signal.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="the-same-information-as-a-barcode" class="level3">
<h3 class="anchored" data-anchor-id="the-same-information-as-a-barcode">The same information as a barcode</h3>
<p>A <strong>barcode</strong> redraws each diagram point <span class="math inline">\((b, d)\)</span> as a horizontal bar <span class="math inline">\([b, d]\)</span> over the <span class="math inline">\(\varepsilon\)</span>-axis. Long bars = persistent features.</p>
<div id="cell-fig-barcode" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">8.5</span>, <span class="fl">4.6</span>))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>yticks, ylabels <span class="op">=</span> [], []</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>group_gap <span class="op">=</span> <span class="fl">1.6</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dgm, (name, color, _) <span class="kw">in</span> <span class="bu">zip</span>(dgms, series):</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> np.argsort(dgm[:, <span class="dv">0</span>] <span class="op">+</span> np.where(np.isinf(dgm[:, <span class="dv">1</span>]), <span class="fl">1e9</span>, dgm[:, <span class="dv">1</span>]))</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    group_top <span class="op">=</span> y</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b, d <span class="kw">in</span> dgm[order][::<span class="op">-</span><span class="dv">1</span>]:</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> np.isinf(d):</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>            ax.plot([b, lim <span class="op">*</span> <span class="fl">1.02</span>], [y, y], color<span class="op">=</span>color, lw<span class="op">=</span><span class="fl">3.5</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>                    solid_capstyle<span class="op">=</span><span class="st">"round"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>            ax.annotate(<span class="st">""</span>, xy<span class="op">=</span>(lim <span class="op">*</span> <span class="fl">1.08</span>, y), xytext<span class="op">=</span>(lim <span class="op">*</span> <span class="fl">1.02</span>, y),</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>                        arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span>color, lw<span class="op">=</span><span class="fl">1.6</span>))</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">else</span>:</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>            ax.plot([b, d], [y, y], color<span class="op">=</span>color, lw<span class="op">=</span><span class="fl">3.5</span>, solid_capstyle<span class="op">=</span><span class="st">"round"</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>        y <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    yticks.append((group_top <span class="op">+</span> y <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> <span class="dv">2</span>)</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    ylabels.append(name)</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>    y <span class="op">+=</span> group_gap</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(yticks, ylabels, fontsize<span class="op">=</span><span class="dv">11</span>, color<span class="op">=</span>INK)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>ax.tick_params(axis<span class="op">=</span><span class="st">"y"</span>, length<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="op">-</span><span class="fl">0.05</span>, lim <span class="op">*</span> <span class="fl">1.12</span>)</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"scale $</span><span class="ch">\\</span><span class="st">varepsilon$"</span>)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> side <span class="kw">in</span> (<span class="st">"top"</span>, <span class="st">"right"</span>, <span class="st">"left"</span>):</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>    ax.spines[side].set_visible(<span class="va">False</span>)</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>ax.grid(axis<span class="op">=</span><span class="st">"x"</span>, color<span class="op">=</span>GRIDC, lw<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>ax.set_axisbelow(<span class="va">True</span>)</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Persistence barcode"</span>, fontsize<span class="op">=</span><span class="dv">12</span>, fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-barcode" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-barcode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-barcode-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-barcode-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Persistence barcode — the same intervals as the diagram, drawn as bars over the ε-axis. Reading H₀ top-down: the shortest bar ends at 0.46 (G and H merge), the next at 0.85 twice (A–F and C–D join the circle group), then 1.03, 1.08, 1.12 as the circle assembles, one long bar to 1.97 (the pair holding out), and one bar running off to infinity (the final single component). The lone H₁ bar spans [1.23, 1.83] — the ring. The sliver H₂ bar spans [1.88, 1.99].
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="reading-actual-features-out-of-these-figures" class="level3">
<h3 class="anchored" data-anchor-id="reading-actual-features-out-of-these-figures">Reading actual features out of these figures</h3>
<ul>
<li><strong>The ring is the story.</strong> The single <span class="math inline">\(H_1\)</span> interval <span class="math inline">\([1.23, 1.83]\)</span> says: at <span class="math inline">\(\varepsilon = 1.23\)</span> the edge B–C closes the circle A–B–C–D–E–F into a cycle no triangle yet fills; at <span class="math inline">\(\varepsilon = 1.83\)</span> the edge B–D creates the last triangles needed to fill its interior. Its persistence, <span class="math inline">\(1.83 - 1.23 = 0.60\)</span>, is large relative to the diagram’s scale: a robust loop, not noise.</li>
<li><strong><span class="math inline">\(H_0\)</span> tells the merge history.</strong> Seven finite bars record seven mergers, and their death scales are exactly the edge lengths that performed each merge — compare them with the sorted distance matrix entries: 0.46 (G–H), 0.85, 0.85, 1.03, 1.08, 1.12 (the circle assembling), and finally 1.97 when edge A–G bridges the pair to everything else. The gap between 1.12 and 1.97 is the barcode’s way of saying “for a wide range of scales, this data is <em>two</em> clusters.”</li>
<li><strong>The <span class="math inline">\(H_2\)</span> sliver is a bonus lesson.</strong> Between <span class="math inline">\(\varepsilon = 1.88\)</span> and <span class="math inline">\(1.99\)</span> the complex contains a closed 2-dimensional surface of triangles enclosing an empty interior — an abstract void, despite the points living flat in 2D — which the tetrahedron <span class="math inline">\(\{C,D,E,F\}\)</span> promptly fills. Short bar, near the diagonal: real, computed, and correctly ignored as noise.</li>
</ul>
</section>
<section id="betti-numbers-at-chosen-scales" class="level3">
<h3 class="anchored" data-anchor-id="betti-numbers-at-chosen-scales">Betti numbers at chosen scales</h3>
<p>Fixing a scale and asking “how many holes of each kind <em>right now</em>?” gives the Betti numbers <span class="math inline">\(\beta_k(\varepsilon)\)</span> — computable from the intervals by counting bars alive at <span class="math inline">\(\varepsilon\)</span>, i.e.&nbsp;with <span class="math inline">\(b \leq \varepsilon &lt; d\)</span> (consistent with the <span class="math inline">\(\leq\)</span> inclusion convention). As a cross-check, <span class="math inline">\(\beta_0\)</span> from the intervals matches an independent <code>networkx</code> component count of the threshold graph at every scale:</p>
<div id="e5f5de85" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Betti numbers at selected scales, from the intervals, cross-checked against networkx</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> betti(eps, dgm):</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">int</span>(np.<span class="bu">sum</span>((dgm[:, <span class="dv">0</span>] <span class="op">&lt;=</span> eps) <span class="op">&amp;</span> (eps <span class="op">&lt;</span> dgm[:, <span class="dv">1</span>])))</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [<span class="st">"| $</span><span class="ch">\\</span><span class="st">varepsilon$ | $</span><span class="ch">\\</span><span class="st">beta_0$ (components) | $</span><span class="ch">\\</span><span class="st">beta_1$ (loops) | $</span><span class="ch">\\</span><span class="st">beta_2$ (voids) | graph components (networkx) |"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"|---|---|---|---|---|"</span>]</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> eps <span class="kw">in</span> [<span class="fl">0.6</span>, <span class="fl">0.9</span>, <span class="fl">1.25</span>, <span class="fl">1.75</span>, <span class="fl">1.9</span>, <span class="fl">2.0</span>]:</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    G <span class="op">=</span> nx.Graph()</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    G.add_nodes_from(<span class="bu">range</span>(<span class="dv">8</span>))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    G.add_edges_from(</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>        (i, j) <span class="cf">for</span> i, j <span class="kw">in</span> itertools.combinations(<span class="bu">range</span>(<span class="dv">8</span>), <span class="dv">2</span>) <span class="cf">if</span> D[i, j] <span class="op">&lt;=</span> eps</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    nx_comp <span class="op">=</span> nx.number_connected_components(G)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    b0, b1, b2 <span class="op">=</span> (betti(eps, dgm) <span class="cf">for</span> dgm <span class="kw">in</span> dgms)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> b0 <span class="op">==</span> nx_comp, <span class="st">"β₀ must equal the number of graph components"</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    rows.append(<span class="ss">f"| </span><span class="sc">{</span>eps<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>b0<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>b1<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>b2<span class="sc">}</span><span class="ss"> | </span><span class="sc">{</span>nx_comp<span class="sc">}</span><span class="ss"> |"</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>Markdown(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>.join(rows))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="11">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(\varepsilon\)</span></th>
<th><span class="math inline">\(\beta_0\)</span> (components)</th>
<th><span class="math inline">\(\beta_1\)</span> (loops)</th>
<th><span class="math inline">\(\beta_2\)</span> (voids)</th>
<th>graph components (networkx)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.6</td>
<td>7</td>
<td>0</td>
<td>0</td>
<td>7</td>
</tr>
<tr class="even">
<td>0.9</td>
<td>5</td>
<td>0</td>
<td>0</td>
<td>5</td>
</tr>
<tr class="odd">
<td>1.25</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="even">
<td>1.75</td>
<td>2</td>
<td>1</td>
<td>0</td>
<td>2</td>
</tr>
<tr class="odd">
<td>1.9</td>
<td>2</td>
<td>0</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>2.0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Read one row against the earlier pictures: at <span class="math inline">\(\varepsilon = 1.25\)</span> the complex has <span class="math inline">\(\beta_0 = 2\)</span> (ring group + pair) and <span class="math inline">\(\beta_1 = 1\)</span> (the ring) — exactly what the second Rips panel showed. And notice what no single row can show: that the loop at 1.25 and the loop at 1.75 are <em>the same</em> loop. That identification across scales is precisely what persistence adds over any one-scale snapshot.</p>
</section>
</section>
<section id="glossary-grounded-in-the-running-example" class="level2">
<h2 class="anchored" data-anchor-id="glossary-grounded-in-the-running-example">9. Glossary, grounded in the running example</h2>
<ul>
<li><strong>Point cloud</strong> — a finite set of points with coordinates (or just pairwise distances). Ours: A–H in the plane.</li>
<li><strong>Distance matrix</strong> — the symmetric matrix of pairwise distances; entry <span class="math inline">\(D_{GH} \approx 0.46\)</span>. Input to everything, itself topology-free.</li>
<li><strong>Simplex</strong> — a finite vertex set read as a geometric piece: <span class="math inline">\(\{G\}\)</span> a vertex, <span class="math inline">\(\{G,H\}\)</span> an edge, <span class="math inline">\(\{C,D,E\}\)</span> a filled triangle, <span class="math inline">\(\{C,D,E,F\}\)</span> a solid tetrahedron.</li>
<li><strong>Simplicial complex</strong> — a collection of simplices closed under taking faces.</li>
<li><strong>Closure property</strong> — if <span class="math inline">\(\{C,D,E\}\)</span> is in the complex, so are <span class="math inline">\(\{C,D\}, \{D,E\}, \{C,E\}, \{C\}, \{D\}, \{E\}\)</span>. The law a generic hypergraph doesn’t have to obey.</li>
<li><strong>Vietoris–Rips complex</strong> — the complex at scale <span class="math inline">\(\varepsilon\)</span> whose simplices are exactly the sets of points that are <em>pairwise</em> within <span class="math inline">\(\varepsilon\)</span>; equivalently, the cliques of the threshold graph.</li>
<li><strong>Filtration</strong> — the nested family <span class="math inline">\(\mathrm{VR}_{\varepsilon_1} \subseteq \mathrm{VR}_{\varepsilon_2} \subseteq \cdots\)</span>; each simplex enters at its diameter and never leaves.</li>
<li><strong>Betti numbers</strong> — hole counts of a single complex: <span class="math inline">\(\beta_0\)</span> connected components, <span class="math inline">\(\beta_1\)</span> independent loops, <span class="math inline">\(\beta_2\)</span> independent enclosed voids. At <span class="math inline">\(\varepsilon = 1.25\)</span> our complex has <span class="math inline">\((\beta_0, \beta_1, \beta_2) = (2, 1, 0)\)</span>.</li>
<li><strong>Persistence diagram</strong> — each hole plotted once as (birth scale, death scale); our ring is the point <span class="math inline">\((1.23, 1.83)\)</span>.</li>
<li><strong>Persistence barcode</strong> — the same intervals drawn as bars over the <span class="math inline">\(\varepsilon\)</span>-axis; long bars persist.</li>
<li><strong>Persistence landscape</strong> — a transformation of the diagram into a sequence of real-valued functions (equivalently, vectors after sampling), giving a representation that can be averaged and fed to statistical or machine-learning pipelines — things you cannot straightforwardly do with raw diagrams. A pointer, not a topic, here.</li>
<li><strong>Bottleneck distance</strong> — a metric between two persistence diagrams: over all ways of matching the points of one diagram to the points of the other (allowing any point to instead match to its nearest spot on the diagonal, treating it as a feature that never existed), the smallest achievable <em>largest</em> single matching distance.</li>
<li><strong>Wasserstein distance</strong> — same matching setup, but summing (a power of) <em>all</em> matching distances rather than taking the maximum, so many small discrepancies count, not just the worst one.</li>
</ul>
</section>
<section id="common-misconceptions" class="level2">
<h2 class="anchored" data-anchor-id="common-misconceptions">10. Common misconceptions</h2>
<p>Tempting, and wrong — with one-sentence corrections:</p>
<ul>
<li><strong>“TDA is just a multigraph with colored or weighted edges.”</strong> Edges have exactly two endpoints, so no edge decoration can express the filled triangle <span class="math inline">\(\{C,D,E\}\)</span> — a single three-way simplex — nor whether a cycle is filled, which is the very question homology answers.</li>
<li><strong>“Powers of the raw distance matrix directly reveal topological shape.”</strong> Powers of an adjacency matrix count walks, the distance matrix isn’t one, and shape only emerges from the <em>filtration</em> — the nested family of simplicial complexes indexed by the scale threshold, plus a homology computation over it.</li>
<li><strong>“A persistence diagram has a time axis.”</strong> Both axes are values of the scale parameter <span class="math inline">\(\varepsilon\)</span>: each point is (birth <em>scale</em>, death <em>scale</em>), and nothing in the construction is chronological.</li>
<li><strong>“A long cycle in the threshold graph means TDA will report a loop.”</strong> A cycle only counts if it isn’t filled by higher simplices — β₁ of the <em>complex</em> at <span class="math inline">\(\varepsilon = 1.9\)</span> is 0 even though the threshold <em>graph</em> at 1.9 is full of cycles.</li>
</ul>
<hr>
<p>If you want to go further: <a href="../../posts/topological-data-analysis-clustering/index.html">Topological Data Analysis: Finding Clusters, Loops, and Voids Across Scales</a> works a homology computation by hand and uses persistence as an ML feature extractor, and <a href="../../posts/tda-vs-svm-expanding-the-space/index.html">TDA vs SVM</a> contrasts this machinery with kernel methods. The mental model to carry out the door is the one we started with: a fixed set of points, a growing tower of simplicial complexes over them, and births and deaths of holes read off along the way.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tda-filtered-simplicial-complexes/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>