{
  "hash": "59d6ebbfb50a96ed8e452693d171973c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"The Anatomy of a Volcano Plot\"\nsubtitle: \"Effect size tells you how much a feature moved; p-values tell you how reliably it moved. Neither ranking is safe on its own, and a widget here lets you watch both fail.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-08-19\"\ncategories: [Bioinformatics, Statistics, Data-Visualization, Genomics, Python]\ntags: [volcano-plot, differential-expression, rna-seq, hypothesis-testing, multiple-testing, p-values]\nimage: \"./cover.png\"\ndescription: \"Why statistical significance does not imply biological importance, how the log2 transform makes the two directions comparable, and how a pair of thresholds turns thousands of noisy hypotheses into a shortlist you can defend. With a screening simulation you drive yourself.\"\njupyter: volcano-blog\nresources:\n  - cover.png\n  - data/airway_de_results.csv\nexecute:\n  warning: false\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: show\n    theme: [zephyr, theme.scss]\n    fig-width: 8\n    fig-height: 4.8\n    fig-dpi: 150\n---\n\n\n![](./cover.png){fig-alt=\"Cover card reading The Anatomy of a Volcano Plot, over a solid purple background.\"}\n\n\n\nAn experiment measures twenty thousand things at once — expression of every gene in a\ntumour biopsy, abundance of every protein in a mass-spectrometry run, every engagement\nmetric in a feature rollout. Out of that comes one number per feature for how much it\nmoved, one for how sure you are it moved at all, and a request from your team for a\nshortlist worth chasing.\n\nRank that list by how much each feature moved and the top of it fills with the\nquietest, noisiest measurements in the assay, where an accidental jump of three counts\nreads as an eight-fold surge. Rank it by statistical certainty instead and the top fills\nwith the loudest measurements, where a 7% shift is nailed down so precisely that it\nclears any significance bar you care to set — and is still a 7% shift, too small to\nchange a cell or a product. Magnitude without certainty picks noise. Certainty without\nmagnitude picks trivia.\n\nA **volcano plot** is the two-dimensional answer: effect size along the horizontal axis,\nstatistical significance up the vertical one, so a shortlist becomes a region of the\nplane rather than the head of a list. This post builds that plane from the two\ntransforms it rests on, lets you drag its thresholds around a simulated screen, and then\nruns it over a real airway RNA-seq experiment.\n\n## One-dimensional rankings pick the wrong features\n\nThe failure is easiest to see in a screen where you know the answer. So we simulate one\nwith four kinds of feature in it, which between them cover what a real assay contains:\n1,785 unchanged background features with moderate noise; 765 low-abundance features that\nare also unchanged, but so noisy that chance alone throws them a large apparent fold\nchange; 300 deeply measured features whose shift is real but tiny — 6% to 32% — and whose\nstandard errors are small enough to make it overwhelmingly significant; and 150 genuine\nresponders, moving 3- to 16-fold, which are the only features we want back.\n\nEach feature gets four replicates per group and an ordinary two-sample $t$-test. Then we\nhand each of three selection rules the same budget — the number of candidates the dual\nfilter picks, so nobody wins by simply choosing more — and count how many of the 150\ngenuine responders each rule recovers.\n\n::: {#cell-fig-rankings .cell execution_count=2}\n``` {.python .cell-code}\nrng = np.random.default_rng(42)\nN, N_TRUE, N_MICRO, N_REP = 3000, 150, 300, 4\nn_noisy = round(0.30 * (N - N_TRUE - N_MICRO))\nn_null = N - N_TRUE - N_MICRO - n_noisy\n\ndef block(size, lfc_lo, lfc_hi, se_lo, se_hi):\n    \"\"\"Signed true log2 fold changes and standard errors for one population.\"\"\"\n    lfc = rng.choice([-1.0, 1.0], size) * rng.uniform(lfc_lo, lfc_hi, size)\n    return lfc, rng.uniform(se_lo, se_hi, size)\n\npopulations = [                        # (label, true |log2FC| range, SE range)\n    (n_null,  0.00, 0.00, 0.15, 0.45),  # unchanged background\n    (n_noisy, 0.00, 0.00, 0.80, 1.80),  # low-count, high-variance\n    (N_MICRO, 0.08, 0.40, 0.02, 0.07),  # real but negligible, measured precisely\n    (N_TRUE,  1.50, 4.00, 0.20, 0.50),  # genuine responders\n]\ndrawn = [block(*p) for p in populations]\ntrue_lfc = np.concatenate([d[0] for d in drawn])\nse = np.concatenate([d[1] for d in drawn])\nkind = np.concatenate([np.full(p[0], i) for i, p in enumerate(populations)])\nis_real = kind == 3\n\nobs = true_lfc + rng.normal(0, se)                      # observed log2 fold change\nt_stat = obs / (se / np.sqrt(N_REP))                    # two-sample t statistic\np_vals = np.clip(2 * stats.t.sf(np.abs(t_stat), df=2 * N_REP - 2), 1e-16, 1.0)\nneg_log_p = -np.log10(p_vals)\n\nLFC_CUT, SIG_CUT = 1.0, 2.0                             # |log2FC| >= 1, p <= 0.01\ndual = (np.abs(obs) >= LFC_CUT) & (neg_log_p >= SIG_CUT)\nbudget = int(dual.sum())\nselections = {\n    \"Effect size alone\": np.argsort(-np.abs(obs))[:budget],\n    \"Significance alone\": np.argsort(p_vals)[:budget],\n    \"Both gates\": np.flatnonzero(dual),\n}\n\nfig, axes = plt.subplots(1, 3, figsize=(10, 3.6), sharex=True, sharey=True)\nfor ax, (name, picked) in zip(axes, selections.items()):\n    ax.scatter(obs, neg_log_p, c=NEUTRAL_COLOR, alpha=0.25, s=10, rasterized=True)\n    ax.scatter(obs[picked], neg_log_p[picked], s=18, rasterized=True,\n               c=np.where(is_real[picked], PRIMARY, SECONDARY))\n    hits = int(is_real[picked].sum())\n    ax.set_title(f\"{name}\\n{hits} of 150 genuine ({hits / len(picked):.0%} precision)\", fontsize=10)\n    ax.set_xlabel(\"Observed $\\\\log_2(\\\\mathrm{Fold\\\\,Change})$\")\naxes[0].set_ylabel(\"$-\\\\log_{10}(p)$\")\naxes[2].axvline(LFC_CUT, color=INK, ls=\"--\", lw=1)\naxes[2].axvline(-LFC_CUT, color=INK, ls=\"--\", lw=1)\naxes[2].axhline(SIG_CUT, color=INK, ls=\"--\", lw=1)\nplt.tight_layout()\nplt.show()\n\nprint(f\"Every rule below selects the same {budget} candidates.\\n\")\nprint(f\"{'':<20}{'genuine':>9}{'precision':>11}{'noise':>8}{'negligible':>12}\")\nfor name, picked in selections.items():\n    counts = np.bincount(kind[picked], minlength=4)\n    print(f\"{name:<20}{is_real[picked].sum():>9}{is_real[picked].mean():>10.0%}\"\n          f\"{counts[1]:>8}{counts[2]:>12}\")\n```\n\n::: {.cell-output .cell-output-display}\n![Three selection rules on the same 3,000-feature screen, each given the same budget of candidates.](index_files/figure-html/fig-rankings-output-1.png){#fig-rankings}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nEvery rule below selects the same 213 candidates.\n\n                      genuine  precision   noise  negligible\nEffect size alone         114       54%      99           0\nSignificance alone        104       49%       0         109\nBoth gates                148       69%      56           0\n```\n:::\n:::\n\n\nTeal is a genuine responder, amber an impostor. All three rules spent the same budget of\n213 candidates. Effect size alone returned 114 of the 150 responders, padded with 99\nlow-count artifacts. Significance alone did slightly worse — 104 responders, alongside\n109 features whose shift is real, certain, and far too small to act on. Requiring both\ngates returned 148 of the 150, at 69% precision against 54% and 49%.\n\nThe impostors each rule admits say why. Effect-size ranking took 99 noisy features and\nnot one negligible-but-certain feature; significance ranking took 109 of the negligible\nones and not a single noisy one. Each rule is blind along exactly the axis it does not\nuse. Requiring both gates still leaves 65 impostors — 56 low-count features and nine\nunchanged background ones that cleared a $p \\le 0.01$ bar by luck across 3,000 tests.\nThat residue is what multiple-testing control is for, and it is the last thing this post\nfixes.\n\n## The gates are yours to move\n\nThose thresholds — a 2-fold change, $p \\le 0.01$ — are conventions, not laws, and the\nwhole trade the volcano plot makes lives in how you set them. Tighten them and precision\nclimbs while real hits fall off the list; loosen them and the reverse. The widget below\nre-runs the same four-population screen in your browser and lets you drag both gates,\nchange the replicate count, and switch either axis to the alternative on offer. Every\nmove re-scores all 3,000 features, and the comparison stays the one the figure used: the\nsame budget, handed to each rule in turn.\n\n::: {.widget-container}\n::: {.widget-header}\n<span class=\"widget-title\">Re-run the screen</span>\n<span class=\"widget-badge\">runs in your browser</span>\n:::\n<div id=\"widget-screen\"></div>\n:::\n\nFour things are worth doing to it before reading on. Drag the significance gate to zero:\nthe filter degenerates into effect-size ranking and the amber low-count wings flood in.\nDrag the effect-size gate to zero instead and the plum band of negligible-but-certain\nfeatures climbs into the selection. Raise the replicate count to 12 and watch that band\nrise straight up the plot — more data does not shrink a small effect, it only measures it\nbetter. And switch the vertical axis from raw $p$ to a Benjamini–Hochberg $q$, which is\nwhat turns a threshold picked by convention into one with a false-discovery guarantee\nbehind it.\n\n## Microarray genomics forced dual filtering into existence\n\nThe plot exists because a generation of biologists ran into exactly this in the late\n1990s. For decades molecular biology had studied genes one at a time, on Northern blots\nand by quantitative PCR, where a single hypothesis got its own dedicated assay and its\nown validation. High-density cDNA microarrays and Affymetrix GeneChips ended that: one\nhybridisation now queried the whole transcriptome, and researchers held expression\nestimates for 15,000 genes at once — with three to six replicates per condition, because\nreagents and tissue were expensive.\n\nThe first response was to threshold on fold change alone, declaring any gene that moved\ntwo-fold a hit. That ignored variance completely, and the literature filled with\nlow-intensity, high-noise claims nobody could reproduce. The obvious correction — run a\n$t$-test on every gene and sort by $p$-value — failed in the opposite direction. At $n =\n3$, a sample variance can come out spuriously tiny by luck alone, handing a 10% change a\n$p$-value of $10^{-6}$.\n\nNeither number was safe by itself, and by the early 2000s several groups had converged\non plotting them against each other. Work by [Jin et al.\n(2001)](https://doi.org/10.1038/ng766), [Wolfinger et al.\n(2001)](https://doi.org/10.1089/106652701753307520) and [Cui and Churchill\n(2003)](https://doi.org/10.1186/gb-2003-4-4-210) established the form; Cui and Churchill\nnamed it, after the shape a genome-wide null makes — a wide caldera of unchanged genes\nwith two eruption plumes rising on the flanks. That shape is not decoration. It follows\nfrom what the two axes do.\n\n## The log transform makes the two directions comparable\n\nThe raw ratio between a treated sample $B$ and a control $A$ is a lopsided coordinate. A\ndoubling gives $B/A = 2$; a halving gives $0.5$. Upregulation has the whole interval\n$[1, \\infty)$ to spread out in, while everything that went down is squeezed into the\nsliver $(0, 1]$. Plot raw ratios and a 10-fold increase sits nine units right of\nbaseline while a 10-fold decrease sits nine tenths of a unit to the left — the widget's\nraw-ratio axis shows this directly, and it is unusable.\n\nThe base-2 logarithm fixes it, because it turns multiplication into addition:\n\n$$\\log_2\\left(\\frac{B}{A}\\right) = -\\log_2\\left(\\frac{A}{B}\\right)$$\n\nA doubling is $+1$, a halving is $-1$, a four-fold change is $\\pm 2$, and no change sits\nat zero. Equal biological moves in opposite directions are now equally far from the\norigin, which is what makes the plot's left–right symmetry mean something.\n\nThe vertical axis gets a log too, for a different reason. Under the null that a feature\nis unchanged, the estimated log fold change $\\hat{\\beta}$ scatters around zero with\nstandard error $\\text{SE}(\\hat{\\beta})$, and the test statistic is $t =\n\\hat{\\beta}/\\text{SE}(\\hat{\\beta})$. Tail probabilities fall off exponentially in $t$,\nso raw $p$-values pile up against zero and become impossible to read. Taking\n$-\\log_{10}(p)$ spreads them out, and through the Gaussian tail approximation it also\ntells you the shape of the cloud:\n\n$$-\\log_{10}(p) \\;\\approx\\; \\frac{t^2}{2 \\ln 10} \\;=\\; \\frac{\\hat{\\beta}^2}{2 \\ln(10)\\,\\text{SE}^2}$$\n\nHeight grows with the *square* of the effect size, at a rate set by each feature's own\nstandard error. That is the volcano's silhouette: a parabola-like envelope opening\nupward from the caldera, with the most precisely measured features climbing its steepest\nwalls. It also explains the trap in the middle. A feature with a tiny $\\hat{\\beta}$ still\nflies upward if its $\\text{SE}$ is small enough — which is exactly the plum population in\nthe widget.\n\n## Two thresholds carve the plane into four decisions\n\nCross a vertical pair of gates at $|\\log_2\\text{FC}| = c$ with a horizontal one at\nsignificance $\\alpha$ and the plane splits into four regions, each of which means\nsomething different for what you do next.\n\n1. **The caldera**, $p > \\alpha$ and $|\\log_2\\text{FC}| < c$. Nothing to see: neither\n   evidence nor magnitude.\n2. **The outer wings**, $p > \\alpha$ but $|\\log_2\\text{FC}| \\ge c$. Large apparent moves\n   the data cannot support — mostly low-abundance features whose noise is doing the\n   moving.\n3. **The top centre**, $p \\le \\alpha$ but $|\\log_2\\text{FC}| < c$. Real, certain, and too\n   small to matter. This region grows as your sample size does.\n4. **The top corners**, $p \\le \\alpha$ and $|\\log_2\\text{FC}| \\ge c$. The shortlist:\n   large enough to have consequences, certain enough to defend.\n\nOne correction is not optional. With 3,000 or 20,000 tests, a threshold of $p \\le 0.01$\nadmits hundreds of false positives by construction, so the vertical axis should carry a\nBenjamini–Hochberg $q$-value instead of a raw $p$:\n\n$$q_i = \\min_{k \\ge i} \\left( \\frac{m \\cdot p_{(k)}}{k} \\right)$$\n\nwith $m$ the number of hypotheses and $p_{(k)}$ the $k$-th smallest $p$-value. Thresholding\nat $q \\le 0.05$ means no more than 5% of what you selected is expected to be a false\ndiscovery — a claim about your shortlist, which is what you actually wanted.\n\n## On real airway data, the filter recovers the glucocorticoid programme\n\nSimulations are agreeable because the answer is known in advance. Real screens are not,\nso we run the same geometry over the **Airway RNA-seq dataset** ([Himes et al.,\n2014](https://doi.org/10.1371/journal.pone.0099625), *PLoS ONE* 9(6): e99625; NCBI GEO\naccession [GSE52778](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE52778)).\n\nBlanca Himes and colleagues at Harvard Medical School and Brigham and Women's Hospital\ngathered it to work out how glucocorticoids — the steroids in every asthma inhaler —\nactually act on the airway. They took primary human airway smooth muscle cells from four\ndonors, split each culture in two, treated one half with $1\\,\\mu\\text{M}$ dexamethasone\nfor 18 hours and left the other untreated, then sequenced all eight libraries. The\nquestion asked of the data is which of 18,028 transcripts respond to the steroid, and it\nis asked because the answer directs money: chasing a false positive burns hundreds of\nthousands of dollars of antibodies, assays and knockout animals, while missing a true one\nthrows away an anti-inflammatory target.\n\nCounts are what the sequencer produces, so the fold changes below come from `DESeq2`'s\nnegative-binomial model, which handles count overdispersion at $n = 4$ and shrinks the\nnoisiest estimates. Its output is a table of log fold changes and FDR-adjusted $q$-values\nper gene, which is exactly a volcano plot waiting to be drawn.\n\n::: {#cell-fig-airway .cell execution_count=3}\n``` {.python .cell-code}\ndf = pd.read_csv(\"data/airway_de_results.csv\")\ndf[\"neg_log10_padj\"] = -np.log10(np.clip(df[\"padj\"], 1e-150, 1.0))\n\nLFC_CUT, PADJ_CUT = 1.5, 6.0            # |log2FC| >= 1.5 (2.8-fold), FDR q <= 1e-6\nlfc, sig = df[\"log2_fold_change\"], df[\"neg_log10_padj\"]\ngroups = {\n    \"Not significant\": (sig < PADJ_CUT, NEUTRAL_COLOR, 10, 0.35),\n    \"Significant, small effect\": ((lfc.abs() < LFC_CUT) & (sig >= PADJ_CUT), ACCENT, 14, 0.5),\n    \"Repressed\": ((lfc <= -LFC_CUT) & (sig >= PADJ_CUT), DOWN_COLOR, 22, 0.85),\n    \"Induced\": ((lfc >= LFC_CUT) & (sig >= PADJ_CUT), UP_COLOR, 22, 0.85),\n}\n\nfig, ax = plt.subplots(figsize=(8.5, 5.2))\nfor name, (mask, colour, size, alpha) in groups.items():\n    ax.scatter(lfc[mask], sig[mask], c=colour, s=size, alpha=alpha, rasterized=True,\n               label=f\"{name} ({int(mask.sum()):,})\")\nfor x in (-LFC_CUT, LFC_CUT):\n    ax.axvline(x, color=INK, ls=\":\", lw=1.1, alpha=0.7)\nax.axhline(PADJ_CUT, color=INK, ls=\":\", lw=1.1, alpha=0.7)\n\nkey_genes = [\"DUSP1\", \"FKBP5\", \"CRISPLD2\", \"SPARCL1\", \"ZBTB16\", \"PER1\", \"KLF15\", \"IL6\"]\nlabelled = df[df[\"gene_symbol\"].isin(key_genes)]\nadjust_text([ax.text(r[\"log2_fold_change\"], r[\"neg_log10_padj\"], r[\"gene_symbol\"],\n                     fontsize=8.5, fontweight=\"bold\", color=INK)\n             for _, r in labelled.iterrows()],\n            ax=ax, arrowprops=dict(arrowstyle=\"->\", color=MUTED, lw=0.8))\n\nax.set_xlabel(\"Effect size: $\\\\log_2(\\\\mathrm{Fold\\\\,Change})$ [dexamethasone / untreated]\")\nax.set_ylabel(\"Significance: $-\\\\log_{10}(q)$, Benjamini–Hochberg\")\nax.set_title(\"Airway smooth muscle response to dexamethasone (GSE52778)\", fontsize=11)\nax.set_xlim(-6.5, 9.0)\nax.set_ylim(-2, 145)\nax.legend(loc=\"upper right\", fontsize=8.5, frameon=True, facecolor=\"white\", edgecolor=RULE)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![18,028 transcripts from human airway smooth muscle, treated with dexamethasone versus untreated.](index_files/figure-html/fig-airway-output-1.png){#fig-airway}\n:::\n:::\n\n\nThe corners are the known glucocorticoid programme, which is the reassuring part: a rule\nthis blunt reproduces what the field established gene by gene.\n\n- ***DUSP1***, $\\log_2\\text{FC} = +2.95$ (7.7-fold), $q = 2.2 \\times 10^{-126}$ — the\n  phosphatase that switches off pro-inflammatory MAP kinase signalling.\n- ***FKBP5***, $+4.05$ (16.5-fold), $q = 9.0 \\times 10^{-26}$ — a co-chaperone of the\n  glucocorticoid receptor itself, and part of its negative feedback.\n- ***CRISPLD2***, $+2.63$ (6.2-fold), $q = 4.7 \\times 10^{-46}$ — the novel finding of\n  the Himes paper, a steroid-regulated gene that modulates airway cytokine secretion.\n- ***IL6***, $-0.75$ (a 41% fall), $q = 0.071$ — a classic steroid-repressed cytokine\n  that lands *outside* both gates here, because unstimulated smooth muscle barely\n  expresses it. The plot is telling you this experiment cannot speak to *IL6*, which is\n  more useful than a rank would have been.\n\n## Caveat: the volcano hides how much signal each feature had\n\nTwo axes cost you a third. Neither position on this plot records a feature's baseline\nabundance, and in RNA-seq, single-cell data and proteomics the noise depends on it\nstrongly: read counts are discrete, so relative variance grows as counts shrink. A gene\naveraging 2 reads in control and 6 in treated shows a three-fold change from Poisson\nnoise alone — that is the simulation's amber population, and it is real.\n\nThe companion plot is the **MA plot**, which puts $\\log_2$ fold change against mean\nexpression and so shows exactly what the volcano dropped.\n\n::: {#cell-fig-ma .cell execution_count=4}\n``` {.python .cell-code}\nfig, (ax_v, ax_m) = plt.subplots(1, 2, figsize=(10, 4.2))\nlog10_base = np.log10(np.clip(df[\"base_mean\"], 0.1, None))\n\nfor name, (mask, colour, size, alpha) in groups.items():\n    if name == \"Significant, small effect\":\n        continue\n    ax_v.scatter(lfc[mask], sig[mask], c=colour, s=size * 0.7, alpha=alpha * 0.8, rasterized=True)\n    ax_m.scatter(log10_base[mask], lfc[mask], c=colour, s=size * 0.7, alpha=alpha * 0.8,\n                 rasterized=True, label=name)\n\nfor x in (-LFC_CUT, LFC_CUT):\n    ax_v.axvline(x, color=RULE, ls=\"--\", lw=1)\nax_v.axhline(PADJ_CUT, color=RULE, ls=\"--\", lw=1)\nax_v.set_xlabel(\"$\\\\log_2(\\\\mathrm{Fold\\\\,Change})$\")\nax_v.set_ylabel(\"$-\\\\log_{10}(q)$\")\nax_v.set_title(\"Volcano: abundance is invisible\", fontsize=10)\nax_v.set_ylim(-2, 145)\n\nax_m.axhline(0, color=RULE, ls=\":\", lw=1)\nfor y in (-LFC_CUT, LFC_CUT):\n    ax_m.axhline(y, color=INK, ls=\"--\", lw=1, alpha=0.7)\nax_m.set_xlabel(\"$\\\\log_{10}(\\\\mathrm{mean\\\\,normalised\\\\,expression})$\")\nax_m.set_ylabel(\"$\\\\log_2(\\\\mathrm{Fold\\\\,Change})$\")\nax_m.set_title(\"MA: the low-count funnel\", fontsize=10)\nax_m.set_ylim(-6.5, 9.0)\nax_m.legend(loc=\"upper right\", fontsize=8, frameon=True, facecolor=\"white\", edgecolor=RULE)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The same genes, plotted against baseline abundance: the dispersion funnel the volcano cannot show.](index_files/figure-html/fig-ma-output-1.png){#fig-ma}\n:::\n:::\n\n\nThe funnel on the right is the point: below about ten reads, fold changes fan out between\n$-5$ and $+5$ with nothing behind them. Modern pipelines answer it with empirical Bayes\nshrinkage — `apeglm` or `ashr` in `DESeq2`, the moderated $t$ of `limma` — pulling\npoorly-supported estimates toward zero while leaving well-measured ones alone. Shrunken\nestimates are what belongs on a volcano's horizontal axis.\n\n## The same geometry works outside genomics\n\nNothing in the construction is biological. It needs many simultaneous tests, an effect\nsize worth measuring on a multiplicative scale, and heterogeneous variances — which\ndescribes plenty of work that has never touched a sequencer.\n\nIn clinical proteomics, label-free LC-MS/MS quantification compares peptide intensities\nacross patient cohorts, with heavy missingness and run-to-run ion suppression; plotting\n$\\log_2$ protein ratio against significance separates candidate biomarkers from\ninstrument artifacts. In pooled CRISPR knockout screens, `MAGeCK` scores the depletion of\n100,000 guide RNAs, and the same two gates split high-potency dependencies from\nnon-targeting controls and off-target toxicity. And in product experimentation, a\nfeature release moves hundreds of tracked metrics at once: the top corners are genuine\nwins and regressions, the top centre is the statistically real drift that nobody should\nroll back a release for, and the wings are small segments whose telemetry is too noisy to\nact on. The vocabulary changes; the plane does not.\n\n## When to plot the volcano\n\nThe claim at the top was that neither axis is safe alone: effect size picks up noise,\nsignificance picks up trivia. The simulation put numbers on it — given 213 candidates to\nspend, the two one-dimensional rules found 114 and 104 of the 150 real responders, both\ngates together 148 — and the airway data showed the same rule recovering a drug programme\nthat took the field years to assemble gene by gene.\n\nWhat makes it work is that it is an explicit two-dimensional decision rule, written where\nyou can see it. The $\\log_2$ transform makes opposite-direction changes comparable; the\n$-\\log_{10}$ transform makes tail probabilities legible and gives the cloud its shape;\nand the thresholds you draw across them are an argument you can defend, or change in\nfront of someone who disagrees.\n\n| Rule | Horizontal | Vertical | Strength | Failure mode |\n| :--- | :--- | :--- | :--- | :--- |\n| Fold-change ranking | $\\log_2(\\text{FC})$ | — | Finds large moves | Low-count noise |\n| $p$-value ranking | — | $-\\log_{10}(p)$ | Finds certain moves | Negligible effects |\n| Volcano plot | $\\log_2(\\text{FC})$ | $-\\log_{10}(q)$ | Both at once | Hides abundance |\n| MA plot | $\\log_{10}(\\text{mean})$ | $\\log_2(\\text{FC})$ | Exposes count variance | No significance test |\n\nThree habits make it trustworthy in production. Put an FDR-adjusted $q$-value on the\nvertical axis, never a raw $p$, or the multiple-testing problem you drew the plot to\nmanage is still in the shortlist. Check the corners against an MA plot before committing\nto anything, because a hit that is only a hit at five reads is not one. And with small\n$n$, shrink the fold changes before you plot them. Do those, and the geometry does what a\nranking never could: it makes the trade between \"big enough to matter\" and \"sure enough\nto believe\" something you decide on purpose.\n\n::: {#widget-injection .cell execution_count=5}\n```{=html}\n<script>/* Widget for \"The Anatomy of a Volcano Plot\".\n *\n * One widget: a screen of 3,000 hypothesis tests that the reader re-runs and\n * re-filters in the browser. Dependency-free -- no CDN, no module loader, no\n * framework -- so it works from a plain file:// page as well as over HTTP.\n * Observable JS does not work with the Quarto installed here (1.6.40), which is\n * why this and the other widgets on the blog are hand-rolled.\n *\n * The widget ships no data. It simulates its own: three populations of\n * features, a real two-sample t-test per feature, and Benjamini-Hochberg\n * q-values, all recomputed as the reader moves a control.\n *\n * The simulation core (VolcanoSim) touches no DOM, so `node` can exercise it\n * directly -- which is how its t-tail and its BH adjustment were checked\n * against scipy and statsmodels.\n */\n\"use strict\";\n\n/* ---------------------------------------------------------------------------\n * Simulation core. No DOM, no globals beyond the export at the end.\n * ------------------------------------------------------------------------ */\nconst VolcanoSim = (function () {\n  /* Seeded PRNG, so a draw is reproducible and re-rolling is deliberate. */\n  function mulberry32(seed) {\n    let a = seed >>> 0;\n    return function () {\n      a = (a + 0x6d2b79f5) >>> 0;\n      let t = a;\n      t = Math.imul(t ^ (t >>> 15), t | 1);\n      t ^= t + Math.imul(t ^ (t >>> 7), t | 61);\n      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;\n    };\n  }\n\n  function randn(rng) {\n    // Box-Muller. The second variate is discarded: the loops here are short\n    // and keeping a cached spare made the seeding harder to reason about.\n    let u = 0;\n    while (u === 0) u = rng();\n    return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * rng());\n  }\n\n  const uniform = (rng, lo, hi) => lo + (hi - lo) * rng();\n\n  /* --- the t-distribution tail ------------------------------------------- */\n\n  const LG_C = [\n    76.18009172947146, -86.50532032941677, 24.01409824083091,\n    -1.231739572450155, 0.1208650973866179e-2, -0.5395239384953e-5,\n  ];\n\n  function logGamma(x) {\n    let y = x;\n    let tmp = x + 5.5;\n    tmp -= (x + 0.5) * Math.log(tmp);\n    let ser = 1.000000000190015;\n    for (let j = 0; j < 6; j++) ser += LG_C[j] / ++y;\n    return -tmp + Math.log((2.5066282746310005 * ser) / x);\n  }\n\n  /* Continued fraction for the incomplete beta, evaluated by Lentz's method. */\n  function betacf(a, b, x) {\n    const FPMIN = 1e-300;\n    const qab = a + b;\n    const qap = a + 1;\n    const qam = a - 1;\n    let c = 1;\n    let d = 1 - (qab * x) / qap;\n    if (Math.abs(d) < FPMIN) d = FPMIN;\n    d = 1 / d;\n    let h = d;\n    for (let m = 1; m <= 300; m++) {\n      const m2 = 2 * m;\n      let aa = (m * (b - m) * x) / ((qam + m2) * (a + m2));\n      d = 1 + aa * d;\n      if (Math.abs(d) < FPMIN) d = FPMIN;\n      c = 1 + aa / c;\n      if (Math.abs(c) < FPMIN) c = FPMIN;\n      d = 1 / d;\n      h *= d * c;\n      aa = (-(a + m) * (qab + m) * x) / ((a + m2) * (qap + m2));\n      d = 1 + aa * d;\n      if (Math.abs(d) < FPMIN) d = FPMIN;\n      c = 1 + aa / c;\n      if (Math.abs(c) < FPMIN) c = FPMIN;\n      d = 1 / d;\n      const del = d * c;\n      h *= del;\n      if (Math.abs(del - 1) < 3e-16) break;\n    }\n    return h;\n  }\n\n  /* Regularised incomplete beta I_x(a, b). */\n  function betainc(a, b, x) {\n    if (x <= 0) return 0;\n    if (x >= 1) return 1;\n    const front = Math.exp(\n      logGamma(a + b) - logGamma(a) - logGamma(b) + a * Math.log(x) + b * Math.log(1 - x)\n    );\n    return x < (a + 1) / (a + b + 2)\n      ? (front * betacf(a, b, x)) / a\n      : 1 - (front * betacf(b, a, 1 - x)) / b;\n  }\n\n  /* Two-sided p-value for a Student t statistic on df degrees of freedom. */\n  function tTwoSided(t, df) {\n    const x = df / (df + t * t);\n    return betainc(df / 2, 0.5, x);\n  }\n\n  /* Benjamini-Hochberg: q_i = min over k >= i of m * p_(k) / k, sorted. */\n  function bhAdjust(p) {\n    const m = p.length;\n    const order = Array.from({ length: m }, (_, i) => i).sort((i, j) => p[i] - p[j]);\n    const q = new Float64Array(m);\n    let running = 1;\n    for (let k = m; k >= 1; k--) {\n      const i = order[k - 1];\n      running = Math.min(running, (m * p[i]) / k);\n      q[i] = running;\n    }\n    return q;\n  }\n\n  /* --- the screen --------------------------------------------------------- */\n\n  const N_FEATURES = 3000;\n  const N_TRUE = 150;\n  const N_MICRO = 300;\n\n  /* Draw the effect sizes and standard errors. Four populations, because the\n   * post's argument needs all four: the inert background, low-count features\n   * whose noise fakes a large fold change, high-abundance features whose real\n   * shift is far too small to matter, and the genuine responders. Independent\n   * of the replicate count, so changing n re-tests the same experiment rather\n   * than drawing a new one. */\n  function draw(seed, noiseFrac) {\n    const rng = mulberry32(seed);\n    const pool = N_FEATURES - N_TRUE - N_MICRO;\n    const nNoisy = Math.round(noiseFrac * pool);\n    const nNull = pool - nNoisy;\n\n    const trueLfc = new Float64Array(N_FEATURES);\n    const se = new Float64Array(N_FEATURES);\n    // 0 background null, 1 low-count noise, 2 genuine responder, 3 micro-shift\n    const kind = new Uint8Array(N_FEATURES);\n    const obs = new Float64Array(N_FEATURES);\n\n    let i = 0;\n    for (let k = 0; k < nNull; k++, i++) {\n      kind[i] = 0;\n      trueLfc[i] = 0;\n      se[i] = uniform(rng, 0.15, 0.45);\n    }\n    for (let k = 0; k < nNoisy; k++, i++) {\n      kind[i] = 1;\n      trueLfc[i] = 0;\n      se[i] = uniform(rng, 0.8, 1.8);\n    }\n    for (let k = 0; k < N_MICRO; k++, i++) {\n      // Deeply sequenced, so the standard error collapses and a 7% shift\n      // clears any significance bar you care to set.\n      kind[i] = 3;\n      trueLfc[i] = (rng() < 0.5 ? -1 : 1) * uniform(rng, 0.08, 0.4);\n      se[i] = uniform(rng, 0.02, 0.07);\n    }\n    for (let k = 0; k < N_TRUE; k++, i++) {\n      kind[i] = 2;\n      trueLfc[i] = (rng() < 0.5 ? -1 : 1) * uniform(rng, 1.5, 4.0);\n      se[i] = uniform(rng, 0.2, 0.5);\n    }\n    for (let j = 0; j < N_FEATURES; j++) obs[j] = trueLfc[j] + se[j] * randn(rng);\n\n    return { lfc: obs, se: se, kind: kind, n: N_FEATURES, nTrue: N_TRUE };\n  }\n\n  /* Test the drawn effects at n replicates per group. */\n  function test(sample, nRep) {\n    const df = 2 * nRep - 2;\n    const m = sample.n;\n    const p = new Float64Array(m);\n    for (let j = 0; j < m; j++) {\n      const t = sample.lfc[j] / (sample.se[j] / Math.sqrt(nRep));\n      p[j] = Math.max(tTwoSided(t, df), 1e-16);\n    }\n    const q = bhAdjust(p);\n    const negLogP = new Float64Array(m);\n    const negLogQ = new Float64Array(m);\n    for (let j = 0; j < m; j++) {\n      negLogP[j] = -Math.log10(p[j]);\n      negLogQ[j] = -Math.log10(Math.max(q[j], 1e-16));\n    }\n    return { p: p, q: q, negLogP: negLogP, negLogQ: negLogQ, df: df };\n  }\n\n  /* Cumulative genuine-hit curves for the two one-dimensional rankings.\n   * cum[k] is how many of the top k features by that ranking are real, so any\n   * budget can be answered in constant time while a slider is being dragged.\n   * Benjamini-Hochberg is monotone in p, so ranking by q gives the same order\n   * as ranking by p and one significance curve covers both. */\n  function rankCurves(sample, tested) {\n    const m = sample.n;\n    const idx = Array.from({ length: m }, (_, i) => i);\n    const byEffect = idx.slice().sort((i, j) => Math.abs(sample.lfc[j]) - Math.abs(sample.lfc[i]));\n    const bySig = idx.slice().sort((i, j) => tested.p[i] - tested.p[j]);\n    const cumEffect = new Int32Array(m + 1);\n    const cumSig = new Int32Array(m + 1);\n    for (let k = 0; k < m; k++) {\n      cumEffect[k + 1] = cumEffect[k] + (sample.kind[byEffect[k]] === 2 ? 1 : 0);\n      cumSig[k + 1] = cumSig[k] + (sample.kind[bySig[k]] === 2 ? 1 : 0);\n    }\n    return { effect: cumEffect, significance: cumSig };\n  }\n\n  /* The dual filter, and what it caught. */\n  function score(sample, tested, lfcCut, sigCut, useQ) {\n    const y = useQ ? tested.negLogQ : tested.negLogP;\n    const selected = new Uint8Array(sample.n);\n    let nSel = 0;\n    let nHit = 0;\n    for (let j = 0; j < sample.n; j++) {\n      if (Math.abs(sample.lfc[j]) >= lfcCut && y[j] >= sigCut) {\n        selected[j] = 1;\n        nSel++;\n        if (sample.kind[j] === 2) nHit++;\n      }\n    }\n    return {\n      selected: selected,\n      nSelected: nSel,\n      nGenuine: nHit,\n      precision: nSel > 0 ? nHit / nSel : 0,\n      recall: nHit / sample.nTrue,\n    };\n  }\n\n  return {\n    mulberry32: mulberry32,\n    randn: randn,\n    tTwoSided: tTwoSided,\n    bhAdjust: bhAdjust,\n    draw: draw,\n    test: test,\n    score: score,\n    rankCurves: rankCurves,\n    N_FEATURES: N_FEATURES,\n    N_TRUE: N_TRUE,\n    N_MICRO: N_MICRO,\n  };\n})();\n\nif (typeof module !== \"undefined\" && module.exports) module.exports = VolcanoSim;\n\n/* ---------------------------------------------------------------------------\n * The widget. A canvas scatter of all 3,000 tests, plain DOM controls around\n * it. Points are drawn as small squares through fillRect rather than arcs:\n * 3,000 of them are redrawn on every slider step and squares are several times\n * cheaper.\n * ------------------------------------------------------------------------ */\n(function () {\n  const C = {\n    ink: \"#171C1B\",\n    muted: \"#67706E\",\n    rule: \"#D2D6D1\",\n    paper: \"#FFFFFF\",\n    primary: \"#1D5C6E\",\n    amber: \"#C98A12\",\n    neutral: \"#A0AAB2\",\n    plum: \"#7A3B6B\",\n    up: \"#D9381E\",\n    down: \"#2070B4\",\n  };\n\n  function h(tag, attrs, kids) {\n    const e = document.createElement(tag);\n    for (const k in attrs || {}) {\n      if (k === \"text\") e.textContent = attrs[k];\n      else e.setAttribute(k, attrs[k]);\n    }\n    for (const c of kids || []) e.appendChild(c);\n    return e;\n  }\n\n  function slider(label, min, max, step, value, fmt, onchange) {\n    const out = h(\"span\", { class: \"wv-value\" });\n    const input = h(\"input\", {\n      type: \"range\", min: min, max: max, step: step, value: value, class: \"wv-range\",\n    });\n    const sync = () => {\n      const v = parseFloat(input.value);\n      out.textContent = fmt(v);\n      onchange(v);\n    };\n    input.addEventListener(\"input\", sync);\n    const node = h(\"label\", { class: \"wv-control\" }, [\n      h(\"span\", { class: \"wv-label\", text: label }),\n      input,\n      out,\n    ]);\n    return { node: node, input: input, sync: sync };\n  }\n\n  function toggle(labels, initial, onchange) {\n    let current = initial;\n    const buttons = labels.map((t, i) =>\n      h(\"button\", { type: \"button\", class: \"wv-toggle\", text: t })\n    );\n    const paint = () =>\n      buttons.forEach((b, i) => b.setAttribute(\"class\", \"wv-toggle\" + (i === current ? \" wv-on\" : \"\")));\n    buttons.forEach((b, i) =>\n      b.addEventListener(\"click\", () => {\n        current = i;\n        paint();\n        onchange(i);\n      })\n    );\n    paint();\n    return { node: h(\"span\", { class: \"wv-toggle-group\" }, buttons), get: () => current };\n  }\n\n  function readout(label) {\n    const value = h(\"span\", { class: \"wv-stat-value\", text: \"—\" });\n    const node = h(\"span\", { class: \"wv-stat\" }, [\n      h(\"span\", { class: \"wv-stat-label\", text: label }),\n      value,\n    ]);\n    return { node: node, set: (t) => (value.textContent = t) };\n  }\n\n  function initScreenWidget(mountId) {\n    const root = document.getElementById(mountId);\n    if (!root) return;\n    const S = VolcanoSim;\n\n    const W = 720;\n    const H = 400;\n    const PAD = { l: 58, r: 16, t: 16, b: 44 };\n\n    const state = {\n      seed: 42,\n      noiseFrac: 0.3,\n      nRep: 4,\n      lfcCut: 1.0,\n      sigCut: 2.0,\n      useQ: 0,\n      rawAxis: 0,\n    };\n\n    let sample = null;\n    let tested = null;\n    let curves = null;\n\n    const canvas = h(\"canvas\", { class: \"wv-canvas\" });\n    const ctx = canvas.getContext(\"2d\");\n\n    const rSelected = readout(\"selected\");\n    const rGenuine = readout(\"genuine hits\");\n    const rPrecision = readout(\"precision\");\n    const rRecall = readout(\"recall\");\n    const rTopFc = readout(\"same budget, |log₂FC| alone\");\n    const rTopP = readout(\"same budget, significance alone\");\n    const note = h(\"p\", { class: \"wv-note\" });\n\n    const sLfc = slider(\"effect-size gate |log₂FC| ≥\", 0, 3, 0.1, state.lfcCut,\n      (v) => v.toFixed(1),\n      (v) => { state.lfcCut = v; refilter(); });\n\n    const sSig = slider(\"significance gate −log₁₀ ≥\", 0, 8, 0.25, state.sigCut,\n      (v) => v.toFixed(2),\n      (v) => { state.sigCut = v; refilter(); });\n\n    const sRep = slider(\"replicates per group\", 2, 12, 1, state.nRep,\n      (v) => String(v),\n      (v) => { state.nRep = v; retest(); });\n\n    const sNoise = slider(\"low-count features\", 0, 0.4, 0.02, state.noiseFrac,\n      (v) => (v * 100).toFixed(0) + \"%\",\n      (v) => { state.noiseFrac = v; redraw(); });\n\n    const tAxis = toggle([\"log₂ fold change\", \"raw ratio\"], 0, (i) => {\n      state.rawAxis = i;\n      render();\n    });\n\n    const tSig = toggle([\"raw p\", \"BH q\"], 0, (i) => {\n      state.useQ = i;\n      refilter();\n    });\n\n    const reroll = h(\"button\", { type: \"button\", class: \"wv-button\", text: \"re-roll the experiment\" });\n    reroll.addEventListener(\"click\", () => {\n      state.seed = (state.seed * 1103515245 + 12345) >>> 0;\n      redraw();\n    });\n\n    root.appendChild(\n      h(\"div\", { class: \"wv-controls\" }, [sLfc.node, sSig.node, sRep.node, sNoise.node])\n    );\n    root.appendChild(\n      h(\"div\", { class: \"wv-toggles\" }, [\n        h(\"span\", { class: \"wv-label\", text: \"horizontal axis\" }), tAxis.node,\n        h(\"span\", { class: \"wv-label\", text: \"vertical axis\" }), tSig.node,\n        reroll,\n      ])\n    );\n    root.appendChild(canvas);\n    root.appendChild(\n      h(\"div\", { class: \"wv-stats\" }, [\n        rSelected.node, rGenuine.node, rPrecision.node, rRecall.node,\n      ])\n    );\n    root.appendChild(\n      h(\"div\", { class: \"wv-stats wv-stats-compare\" }, [rTopFc.node, rTopP.node])\n    );\n    root.appendChild(note);\n\n    /* --- the three levels of recomputation ------------------------------- */\n\n    function redraw() {\n      sample = S.draw(state.seed, state.noiseFrac);\n      retest();\n    }\n\n    function retest() {\n      tested = S.test(sample, state.nRep);\n      curves = S.rankCurves(sample, tested);\n      refilter();\n    }\n\n    function refilter() {\n      render();\n    }\n\n    /* --- drawing ---------------------------------------------------------- */\n\n    function xDomain() {\n      return state.rawAxis ? [0, 16] : [-6, 6];\n    }\n\n    function xValue(lfc) {\n      return state.rawAxis ? Math.pow(2, lfc) : lfc;\n    }\n\n    function render() {\n      const y = state.useQ ? tested.negLogQ : tested.negLogP;\n      const res = S.score(sample, tested, state.lfcCut, state.sigCut, state.useQ);\n\n      let yMax = 6;\n      for (let i = 0; i < y.length; i++) if (y[i] > yMax) yMax = y[i];\n      yMax = Math.min(Math.ceil(yMax) + 1, 18);\n\n      const [x0, x1] = xDomain();\n      const px = (v) => PAD.l + ((Math.min(Math.max(v, x0), x1) - x0) / (x1 - x0)) * (W - PAD.l - PAD.r);\n      const py = (v) => H - PAD.b - (Math.min(v, yMax) / yMax) * (H - PAD.t - PAD.b);\n\n      const dpr = window.devicePixelRatio || 1;\n      canvas.width = W * dpr;\n      canvas.height = H * dpr;\n      canvas.style.width = \"100%\";\n      canvas.style.maxWidth = W + \"px\";\n      canvas.style.height = \"auto\";\n      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);\n      ctx.clearRect(0, 0, W, H);\n      ctx.fillStyle = C.paper;\n      ctx.fillRect(0, 0, W, H);\n\n      // Shade the selected regions, so the filter is a place on the plot and\n      // not just a pair of numbers.\n      const yCut = py(state.sigCut);\n      ctx.fillStyle = \"rgba(29, 92, 110, 0.07)\";\n      const rightX = px(xValue(state.lfcCut));\n      const leftX = px(xValue(-state.lfcCut));\n      ctx.fillRect(rightX, PAD.t, W - PAD.r - rightX, yCut - PAD.t);\n      ctx.fillRect(PAD.l, PAD.t, leftX - PAD.l, yCut - PAD.t);\n\n      // Axes.\n      ctx.strokeStyle = C.rule;\n      ctx.lineWidth = 1;\n      ctx.beginPath();\n      ctx.moveTo(PAD.l, PAD.t);\n      ctx.lineTo(PAD.l, H - PAD.b);\n      ctx.lineTo(W - PAD.r, H - PAD.b);\n      ctx.stroke();\n\n      ctx.fillStyle = C.muted;\n      ctx.font = \"11px system-ui, sans-serif\";\n      ctx.textAlign = \"center\";\n      const xTicks = state.rawAxis ? [0, 1, 2, 4, 8, 12, 16] : [-6, -4, -2, 0, 2, 4, 6];\n      for (const t of xTicks) {\n        const X = px(t);\n        ctx.beginPath();\n        ctx.moveTo(X, H - PAD.b);\n        ctx.lineTo(X, H - PAD.b + 4);\n        ctx.stroke();\n        ctx.fillText(String(t), X, H - PAD.b + 16);\n      }\n      ctx.textAlign = \"right\";\n      const yStep = yMax <= 8 ? 2 : 4;\n      for (let t = 0; t <= yMax; t += yStep) {\n        const Y = py(t);\n        ctx.beginPath();\n        ctx.moveTo(PAD.l - 4, Y);\n        ctx.lineTo(PAD.l, Y);\n        ctx.stroke();\n        ctx.fillText(String(t), PAD.l - 7, Y + 4);\n      }\n\n      ctx.fillStyle = C.ink;\n      ctx.font = \"12px system-ui, sans-serif\";\n      ctx.textAlign = \"center\";\n      ctx.fillText(\n        state.rawAxis ? \"fold change (raw ratio, treated / control)\" : \"log₂ fold change\",\n        PAD.l + (W - PAD.l - PAD.r) / 2,\n        H - 8\n      );\n      ctx.save();\n      ctx.translate(14, PAD.t + (H - PAD.t - PAD.b) / 2);\n      ctx.rotate(-Math.PI / 2);\n      ctx.fillText(state.useQ ? \"−log₁₀ q (BH-adjusted)\" : \"−log₁₀ p\", 0, 0);\n      ctx.restore();\n\n      // Points, painted background-first so genuine hits are never buried.\n      const order = [0, 1, 3, 2];\n      const fill = [C.neutral, C.amber, C.primary, C.plum];\n      const alpha = [0.45, 0.6, 0.9, 0.75];\n      for (const k of order) {\n        ctx.fillStyle = fill[k];\n        ctx.globalAlpha = alpha[k];\n        const size = k === 2 ? 4 : 3;\n        for (let i = 0; i < sample.n; i++) {\n          if (sample.kind[i] !== k) continue;\n          ctx.fillRect(px(xValue(sample.lfc[i])) - size / 2, py(y[i]) - size / 2, size, size);\n        }\n      }\n      ctx.globalAlpha = 1;\n\n      // Ring every selected point, so precision is countable by eye.\n      ctx.strokeStyle = C.ink;\n      ctx.lineWidth = 0.9;\n      for (let i = 0; i < sample.n; i++) {\n        if (!res.selected[i]) continue;\n        ctx.beginPath();\n        ctx.arc(px(xValue(sample.lfc[i])), py(y[i]), 4.2, 0, 2 * Math.PI);\n        ctx.stroke();\n      }\n\n      // The gates themselves.\n      ctx.strokeStyle = C.ink;\n      ctx.lineWidth = 1.2;\n      ctx.setLineDash([5, 4]);\n      for (const X of [leftX, rightX]) {\n        ctx.beginPath();\n        ctx.moveTo(X, PAD.t);\n        ctx.lineTo(X, H - PAD.b);\n        ctx.stroke();\n      }\n      ctx.beginPath();\n      ctx.moveTo(PAD.l, yCut);\n      ctx.lineTo(W - PAD.r, yCut);\n      ctx.stroke();\n      ctx.setLineDash([]);\n\n      // Legend.\n      const legend = [\n        [\"genuine responders (150)\", C.primary],\n        [\"low-count noise\", C.amber],\n        [\"tiny but certain shifts\", C.plum],\n        [\"unchanged background\", C.neutral],\n      ];\n      ctx.font = \"11px system-ui, sans-serif\";\n      ctx.textAlign = \"left\";\n      ctx.fillStyle = \"rgba(255, 255, 255, 0.82)\";\n      ctx.fillRect(PAD.l + 4, PAD.t + 2, 148, legend.length * 15 + 6);\n      legend.forEach((entry, i) => {\n        const Y = PAD.t + 12 + i * 15;\n        ctx.fillStyle = entry[1];\n        ctx.fillRect(PAD.l + 10, Y - 5, 8, 8);\n        ctx.fillStyle = C.muted;\n        ctx.fillText(entry[0], PAD.l + 24, Y + 2);\n      });\n\n      const k = res.nSelected;\n      const fcHits = curves.effect[k];\n      const sigHits = curves.significance[k];\n\n      rSelected.set(String(k));\n      rGenuine.set(res.nGenuine + \" / 150\");\n      rPrecision.set(k ? (res.precision * 100).toFixed(0) + \"%\" : \"—\");\n      rRecall.set((res.recall * 100).toFixed(0) + \"%\");\n      rTopFc.set(fcHits + \" genuine\");\n      rTopP.set(sigHits + \" genuine\");\n\n      note.textContent = commentary(res, fcHits, sigHits);\n    }\n\n    function commentary(res, fcHits, sigHits) {\n      const k = res.nSelected;\n      if (state.rawAxis) {\n        return (\n          \"On the raw ratio axis every repressed feature — half the genuine signal — is \" +\n          \"crushed into the sliver between 0 and 1, while induced ones sprawl off the end \" +\n          \"of the axis: anything past 16× is stacked against the right edge. Switch back \" +\n          \"to log₂ and the two halves become mirror images.\"\n        );\n      }\n      if (k === 0) {\n        return \"Both gates are now strict enough that nothing passes at all.\";\n      }\n      if (state.sigCut === 0 && state.lfcCut === 0) {\n        return \"Both gates are open, so all 3,000 features are selected and precision is just the share of the screen that was ever real.\";\n      }\n      if (state.sigCut === 0) {\n        return (\n          \"With the significance gate at zero this is fold-change ranking: \" + k +\n          \" features pass on effect size alone, and \" + (k - res.nGenuine) +\n          \" of them are noise that happened to move.\"\n        );\n      }\n      if (state.lfcCut === 0) {\n        return (\n          \"With the effect-size gate at zero this is significance ranking: \" + k +\n          \" features clear the bar, including deeply sequenced ones whose shift is real, \" +\n          \"certain, and far too small to act on.\"\n        );\n      }\n      return (\n        \"The dual filter selected \" + k + \" features and caught \" + res.nGenuine +\n        \" of the 150 real responders. Hand a one-dimensional ranking the same budget of \" +\n        k + \" and it finds \" + fcHits + \" (effect size alone) or \" + sigHits +\n        \" (significance alone).\"\n      );\n    }\n\n    redraw();\n    sLfc.sync();\n    sSig.sync();\n    sRep.sync();\n    sNoise.sync();\n  }\n\n  if (typeof document !== \"undefined\") {\n    document.addEventListener(\"DOMContentLoaded\", () => initScreenWidget(\"widget-screen\"));\n  }\n})();\n</script>\n```\n:::\n\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}