<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-07-31">
<meta name="description" content="Four attribution methods on a misclassified MNIST digit and four classical decompositions of Fisher’s irises, implemented from scratch and checked at build time — set against one framing that covers all eight.">

<title>Explainability Is a Localization Problem – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>:root { color-scheme: light; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Explainability Is a Localization Problem</h1>
            <p class="subtitle lead">Saliency maps on MNIST, confidence intervals on Iris — every explanation answers the same question, <em>which parts?</em>. They differ in what counts as a part, what counts as responsible, and whether the answer comes with error bars.</p>
                  <div>
        <div class="description">
          Four attribution methods on a misclassified MNIST digit and four classical decompositions of Fisher’s irises, implemented from scratch and checked at build time — set against one framing that covers all eight.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Explainability</div>
                <div class="quarto-category">Python</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 31, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-model-says-six.-which-parts-of-the-image-made-it-say-that" id="toc-a-model-says-six.-which-parts-of-the-image-made-it-say-that" class="nav-link active" data-scroll-target="#a-model-says-six.-which-parts-of-the-image-made-it-say-that">A model says “six”. Which parts of the image made it say that?</a></li>
  <li><a href="#two-traditions-asking-one-question" id="toc-two-traditions-asking-one-question" class="nav-link" data-scroll-target="#two-traditions-asking-one-question">Two traditions asking one question</a></li>
  <li><a href="#part-i-explaining-a-black-box-mnist" id="toc-part-i-explaining-a-black-box-mnist" class="nav-link" data-scroll-target="#part-i-explaining-a-black-box-mnist">Part I — Explaining a black box: MNIST</a>
  <ul class="collapse">
  <li><a href="#where-these-digits-come-from-and-what-a-mistake-costs" id="toc-where-these-digits-come-from-and-what-a-mistake-costs" class="nav-link" data-scroll-target="#where-these-digits-come-from-and-what-a-mistake-costs">Where these digits come from, and what a mistake costs</a></li>
  <li><a href="#the-model-and-the-two-digits-we-keep-coming-back-to" id="toc-the-model-and-the-two-digits-we-keep-coming-back-to" class="nav-link" data-scroll-target="#the-model-and-the-two-digits-we-keep-coming-back-to">The model, and the two digits we keep coming back to</a></li>
  <li><a href="#saliency-the-gradient-as-a-one-term-taylor-expansion" id="toc-saliency-the-gradient-as-a-one-term-taylor-expansion" class="nav-link" data-scroll-target="#saliency-the-gradient-as-a-one-term-taylor-expansion">Saliency: the gradient as a one-term Taylor expansion</a></li>
  <li><a href="#occlusion-responsibility-as-what-breaks-when-you-take-it-away" id="toc-occlusion-responsibility-as-what-breaks-when-you-take-it-away" class="nav-link" data-scroll-target="#occlusion-responsibility-as-what-breaks-when-you-take-it-away">Occlusion: responsibility as what breaks when you take it away</a></li>
  <li><a href="#grad-cam-localizing-to-channels-rather-than-pixels" id="toc-grad-cam-localizing-to-channels-rather-than-pixels" class="nav-link" data-scroll-target="#grad-cam-localizing-to-channels-rather-than-pixels">Grad-CAM: localizing to channels rather than pixels</a></li>
  <li><a href="#integrated-gradients-buying-an-axiom-with-a-baseline" id="toc-integrated-gradients-buying-an-axiom-with-a-baseline" class="nav-link" data-scroll-target="#integrated-gradients-buying-an-axiom-with-a-baseline">Integrated gradients: buying an axiom with a baseline</a></li>
  <li><a href="#caveat-an-explanation-that-survives-randomizing-the-model-explains-nothing" id="toc-caveat-an-explanation-that-survives-randomizing-the-model-explains-nothing" class="nav-link" data-scroll-target="#caveat-an-explanation-that-survives-randomizing-the-model-explains-nothing">Caveat: an explanation that survives randomizing the model explains nothing</a></li>
  <li><a href="#what-the-four-maps-agree-about-and-where-they-part" id="toc-what-the-four-maps-agree-about-and-where-they-part" class="nav-link" data-scroll-target="#what-the-four-maps-agree-about-and-where-they-part">What the four maps agree about, and where they part</a></li>
  </ul></li>
  <li><a href="#part-ii-explaining-a-glass-box-iris" id="toc-part-ii-explaining-a-glass-box-iris" class="nav-link" data-scroll-target="#part-ii-explaining-a-glass-box-iris">Part II — Explaining a glass box: Iris</a>
  <ul class="collapse">
  <li><a href="#where-these-flowers-come-from-and-what-the-labels-mean" id="toc-where-these-flowers-come-from-and-what-the-labels-mean" class="nav-link" data-scroll-target="#where-these-flowers-come-from-and-what-the-labels-mean">Where these flowers come from, and what the labels mean</a></li>
  <li><a href="#coefficients-responsibility-with-an-error-bar-attached" id="toc-coefficients-responsibility-with-an-error-bar-attached" class="nav-link" data-scroll-target="#coefficients-responsibility-with-an-error-bar-attached">Coefficients: responsibility with an error bar attached</a></li>
  <li><a href="#anova-localizing-to-sources-of-variance-rather-than-to-features" id="toc-anova-localizing-to-sources-of-variance-rather-than-to-features" class="nav-link" data-scroll-target="#anova-localizing-to-sources-of-variance-rather-than-to-features">ANOVA: localizing to sources of variance rather than to features</a></li>
  <li><a href="#pca-localizing-to-directions-instead-of-to-features" id="toc-pca-localizing-to-directions-instead-of-to-features" class="nav-link" data-scroll-target="#pca-localizing-to-directions-instead-of-to-features">PCA: localizing to directions instead of to features</a></li>
  <li><a href="#permutation-importance-occlusion-moved-to-a-table" id="toc-permutation-importance-occlusion-moved-to-a-table" class="nav-link" data-scroll-target="#permutation-importance-occlusion-moved-to-a-table">Permutation importance: occlusion, moved to a table</a></li>
  </ul></li>
  <li><a href="#where-the-two-traditions-meet" id="toc-where-the-two-traditions-meet" class="nav-link" data-scroll-target="#where-the-two-traditions-meet">Where the two traditions meet</a></li>
  <li><a href="#the-column-that-is-still-empty" id="toc-the-column-that-is-still-empty" class="nav-link" data-scroll-target="#the-column-that-is-still-empty">The column that is still empty</a></li>
  <li><a href="#reproducing-this" id="toc-reproducing-this" class="nav-link" data-scroll-target="#reproducing-this">Reproducing this</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/explainability-localization/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Explainability Is a Localization Problem</figcaption>
</figure>
</div>
<section id="a-model-says-six.-which-parts-of-the-image-made-it-say-that" class="level2">
<h2 class="anchored" data-anchor-id="a-model-says-six.-which-parts-of-the-image-made-it-say-that">A model says “six”. Which parts of the image made it say that?</h2>
<p>Here is test digit number 9729 of MNIST. A convolutional network that gets 98.8% of the test set right looks at it and returns <strong>6</strong> with probability 0.996. The digit is a 5. The network’s probability for the correct answer is 0.00055 — not second place, but fifth, behind an 8 and a 2.</p>
<p>Something in those 784 pixels made the network confident. The question “why?” is unhelpfully broad, but there is a sharper version of it that we can actually answer: <em>which parts of the input were responsible for the output, and how much?</em> That is a localization problem. It has a shape — you name a set of parts, you define a way of assigning credit to each, and you get back a number per part.</p>
<p>Almost every explainability method in use is an answer to that problem, and the differences between them come down to three choices:</p>
<ol type="1">
<li><strong>What counts as a part?</strong> A pixel. A patch. An internal channel of a convolution. A column of a table. A direction in feature space.</li>
<li><strong>What counts as responsible?</strong> A local gradient. The damage done by deleting it. An attribution satisfying stated axioms. A share of variance. The effect of an intervention.</li>
<li><strong>Does the answer come with error bars?</strong> Almost never in machine learning. Almost always in statistics.</li>
</ol>
<p>This post fills in all three axes with running code — four methods on a misclassified MNIST digit, four on Fisher’s irises — and then argues that the third axis is the one that still separates the two traditions.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Every number below is computed at build time
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Nothing here is typed in from a previous run. The prose interpolates values from the same objects the figures are drawn from, and nine cross-checks run while the page builds — the completeness axiom for integrated gradients, the equivalence of two Grad-CAM implementations, hand-derived logistic standard errors against <code>statsmodels</code>, hand-computed ANOVA against <code>scipy</code>, PCA against <code>scikit-learn</code>. If any of them fails, the page does not render.</p>
<ul>
<li>[wrong] integrated gradients sum to f(x) - f(0) within 3.7e-04 relative</li>
<li>[wrong] Grad-CAM via hooks is bit-identical to Grad-CAM via the head split</li>
<li>[wrong] Grad-CAM equals CAM / 49 to 8.9e-08 absolute</li>
<li>[wrong] all 617 baseline-valued pixels receive exactly zero from IG</li>
<li>[right] integrated gradients sum to f(x) - f(0) within 2.1e-04 relative</li>
<li>[right] Grad-CAM via hooks is bit-identical to Grad-CAM via the head split</li>
<li>[right] Grad-CAM equals CAM / 49 to 1.8e-07 absolute</li>
<li>[right] all 562 baseline-valued pixels receive exactly zero from IG</li>
<li>logistic coefficients match statsmodels to 8.9e-16, standard errors to 2.7e-15</li>
<li>ANOVA F statistics match scipy.stats.f_oneway to 2.7e-15 relative</li>
<li>PCA explained-variance ratios match scikit-learn to 2.2e-16</li>
<li>setosa is linearly separable from the rest; versicolor and virginica are not</li>
<li>permutation importances agree with scikit-learn’s within Monte-Carlo error (largest gap 0.0066, largest 3-sigma bound 0.0138)</li>
</ul>
</div>
</div>
</div>
</section>
<section id="two-traditions-asking-one-question" class="level2">
<h2 class="anchored" data-anchor-id="two-traditions-asking-one-question">Two traditions asking one question</h2>
<p>Statistics has been localizing responsibility for a century, and did it first because its models were small enough to make the answer legible. A regression coefficient is an attribution to a variable. Fisher’s analysis of variance, published in the 1920s, is a literal decomposition: total variability splits into a part explained by the treatment and a part left over, and the arithmetic is an identity rather than an approximation. The tradition’s characteristic move is to attach a standard error to the attribution, so that “this variable matters” can fail to be supported by the data.</p>
<p>Machine learning arrived at the same question from the other end. Its models are too large to read, so the parts are not chosen for interpretability — they are whatever the input happens to be made of, or whatever the architecture happens to expose. SHAP, LIME, saliency maps, Grad-CAM and integrated gradients are all attempts to recover a per-part number from a function you cannot inspect directly. They are typically point estimates with no uncertainty attached at all.</p>
<p>Neither tradition owns the question. They own different regimes of it, and their failures are instructive in opposite directions. Part I takes the black box; Part II takes the glass box.</p>
</section>
<section id="part-i-explaining-a-black-box-mnist" class="level2">
<h2 class="anchored" data-anchor-id="part-i-explaining-a-black-box-mnist">Part I — Explaining a black box: MNIST</h2>
<p>Localizing an answer means choosing parts and a credit rule. In an image the obvious part is the pixel, which is why three of the four methods below are pixel-level; the interesting one is the method that refuses, and localizes to the network’s internal channels instead.</p>
<section id="where-these-digits-come-from-and-what-a-mistake-costs" class="level3">
<h3 class="anchored" data-anchor-id="where-these-digits-come-from-and-what-a-mistake-costs">Where these digits come from, and what a mistake costs</h3>
<p>MNIST is a remix. The original material is two National Institute of Standards and Technology collections of handwritten characters: Special Database 3, written by Census Bureau employees, and Special Database 1, written by American high-school students. NIST gathered them to benchmark optical character recognition — the machinery that reads addresses off envelopes and amounts off cheques. The two populations do not write alike; SD-3 is markedly cleaner. Yann LeCun, Corinna Cortes and Christopher Burges <a href="https://yann.lecun.com/exdb/mnist/">rebuilt the split</a> in the 1990s so that training and test sets each drew from both, size-normalised the glyphs into a 20×20 box and centred them by mass in a 28×28 field. That anti-aliasing is why MNIST pixels are grey rather than binary, and it matters below: a pixel can be <em>slightly</em> on.</p>
<p>The question asked of the data here is the original one — given the image, which digit is it — and the label means what a human reader took the writer to have intended. The cost of being wrong is concrete and asymmetric: a misread digit on a cheque moves money, a misread digit on an envelope moves a letter to the wrong city. Both are recoverable, which makes MNIST a fair place to study explanations. We can afford to be curious about a failure rather than alarmed by it.</p>
<p>Attribution methods are the right tool for exactly one reason: there are 784 inputs, they are strongly correlated with their neighbours, and no coefficient exists to read. The model is a composition of convolutions with hundreds of thousands of parameters, and the only handle on it is that it is differentiable and cheap to evaluate. Every method below exploits one of those two properties.</p>
</section>
<section id="the-model-and-the-two-digits-we-keep-coming-back-to" class="level3">
<h3 class="anchored" data-anchor-id="the-model-and-the-two-digits-we-keep-coming-back-to">The model, and the two digits we keep coming back to</h3>
<p>The classifier is a small convolutional network: two convolution blocks down to a 7×7 grid, a third convolution to 128 channels, then global average pooling and one linear layer. That last part is a deliberate choice rather than a default, and the reason appears when we get to Grad-CAM.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> features(<span class="va">self</span>, x: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">self</span>.act3(<span class="va">self</span>.bn3(<span class="va">self</span>.conv3(<span class="va">self</span>.block2(<span class="va">self</span>.block1(x)))))</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> head(<span class="va">self</span>, a: torch.Tensor) <span class="op">-&gt;</span> torch.Tensor:</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="va">self</span>.fc(a.mean(dim<span class="op">=</span>(<span class="dv">2</span>, <span class="dv">3</span>)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Trained for four epochs on CPU under a fixed seed, it reaches 98.8% on the test set — 125 mistakes in 10,000. We will study one of them, plus a control: the digit the model gets <em>most confidently wrong</em>, and the digit of the same true class it gets <em>most confidently right</em>. Confidence is the interesting regime, because an explanation of a hesitant prediction can always be waved away as noise.</p>
<div id="cell-fig-examples" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="fig-examples" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two MNIST digits, both fives, with the model's probability over ten classes on a log scale. The first is predicted six with probability 0.996; the second is predicted five with probability 1.000.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-examples-output-1.png" class="img-fluid figure-img" alt="Two MNIST digits, both fives, with the model's probability over ten classes on a log scale. The first is predicted six with probability 0.996; the second is predicted five with probability 1.000.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-examples-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The running examples. The mistake is not a near-miss: the correct class ranks fifth.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Both digits are fives. The first is written with the lower stroke curled all the way round into a closed loop, which is what a six has and a five does not. The model is not being stupid; it is being confidently wrong in a way that ought to leave a trace. Four methods now go looking for it.</p>
</section>
<section id="saliency-the-gradient-as-a-one-term-taylor-expansion" class="level3">
<h3 class="anchored" data-anchor-id="saliency-the-gradient-as-a-one-term-taylor-expansion">Saliency: the gradient as a one-term Taylor expansion</h3>
<p>The cheapest possible notion of responsibility is sensitivity. Expand the network’s output around this image and keep one term: the logit for class 6 changes by roughly <span class="math inline">\(\nabla_x f \cdot \delta\)</span> under a small perturbation <span class="math inline">\(\delta\)</span>, so the gradient’s magnitude at each pixel says how fast that pixel could move the answer. <a href="https://arxiv.org/abs/1312.6034">Simonyan, Vedaldi and Zisserman</a> introduced this in 2013 and it remains the floor that every other method is measured against — one backward pass, no hyperparameters.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> saliency(model: SmallCNN, x01: torch.Tensor, target: <span class="bu">int</span>) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> _as_batch(x01).requires_grad_(<span class="va">True</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    model.zero_grad(set_to_none<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    model(normalise(x))[<span class="dv">0</span>, target].backward()</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> x.grad[<span class="dv">0</span>, <span class="dv">0</span>].detach().numpy()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="cell-fig-saliency" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div id="fig-saliency" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two saliency maps over MNIST fives. Both are speckled, with bright pixels scattered inside and outside the stroke.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-saliency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-saliency-output-1.png" class="img-fluid figure-img" alt="Two saliency maps over MNIST fives. Both are speckled, with bright pixels scattered inside and outside the stroke.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-saliency-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Gradient magnitude of the predicted logit. The digit’s outline is drawn on top so the attribution can be located against the stroke.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The map is speckled and only loosely attached to the digit. That is not a rendering artefact, it is what the gradient of a ReLU network looks like: a piecewise-linear function’s slope changes discontinuously across activation boundaries, so neighbouring pixels can have very different derivatives. Worse, look where the largest value lands. Of the 617 pixels in this image that are exactly black, saliency assigns a non-zero gradient to 617 of them — all of them — and the single largest gradient in the entire map, 1.35, sits on one of them.</p>
<p>That is a coherent statement about the model: painting ink onto that empty pixel would change the logit faster than anything else. It is not a statement about <em>this</em> image, which has nothing there. Sensitivity and responsibility are different questions, and saliency answers the first one.</p>
</section>
<section id="occlusion-responsibility-as-what-breaks-when-you-take-it-away" class="level3">
<h3 class="anchored" data-anchor-id="occlusion-responsibility-as-what-breaks-when-you-take-it-away">Occlusion: responsibility as what breaks when you take it away</h3>
<p>If the complaint about gradients is that they describe a hypothetical nudge, the fix is to make the perturbation real and finite. Slide a black square over every position in the image, re-run the network, and record how far the logit falls. A patch that was carrying the prediction leaves a hole when removed. <a href="https://arxiv.org/abs/1311.2901">Zeiler and Fergus</a> used exactly this in 2013 to check that their ImageNet features were tracking objects rather than backgrounds.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> occlusion(</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    model: SmallCNN,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    x01: torch.Tensor,</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    target: <span class="bu">int</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    patch: <span class="bu">int</span> <span class="op">=</span> <span class="dv">7</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    fill: <span class="bu">float</span> <span class="op">=</span> <span class="fl">0.0</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    base <span class="op">=</span> target_logit(model, x01, target)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    half <span class="op">=</span> patch <span class="op">//</span> <span class="dv">2</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    img <span class="op">=</span> _as_batch(x01)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    batch, centres <span class="op">=</span> [], []</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">28</span>):</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> c <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">28</span>):</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>            occluded <span class="op">=</span> img.clone()</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>            occluded[</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                :, :, <span class="bu">max</span>(<span class="dv">0</span>, r <span class="op">-</span> half) : r <span class="op">+</span> half <span class="op">+</span> <span class="dv">1</span>, <span class="bu">max</span>(<span class="dv">0</span>, c <span class="op">-</span> half) : c <span class="op">+</span> half <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>            ] <span class="op">=</span> fill</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>            batch.append(occluded)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>            centres.append((r, c))</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> torch.no_grad():</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>        logits <span class="op">=</span> model(normalise(torch.cat(batch)))[:, target].numpy()</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> np.zeros((<span class="dv">28</span>, <span class="dv">28</span>), dtype<span class="op">=</span>np.float64)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (r, c), value <span class="kw">in</span> <span class="bu">zip</span>(centres, logits):</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>        out[r, c] <span class="op">=</span> base <span class="op">-</span> value</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> out</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="cell-fig-occlusion" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-occlusion" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two occlusion maps over MNIST fives. On the misclassified digit the heat concentrates on the closed lower loop.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-occlusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-occlusion-output-1.png" class="img-fluid figure-img" alt="Two occlusion maps over MNIST fives. On the misclassified digit the heat concentrates on the closed lower loop.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-occlusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Logit drop under a 7×7 black patch. Red means the patch was supporting the prediction; blue means removing it <em>helped</em>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This is legible in a way saliency is not. On the misclassified digit the mass sits squarely on the closed lower loop — the feature that a six has. Cover it and the logit for 6 falls by up to 8.4. The model is not confused about pixels; it is reading a loop that is genuinely there, in a glyph whose writer intended a five.</p>
<p>The cost is a different blind spot. Occluding a region that is already black does nothing at all, because the occluder and the image agree. In this digit 319 pixels sit at the centre of a 7×7 patch that is entirely black, and across all of them the largest logit change occlusion can find is 4.8e-06 — floating-point noise. Saliency, over those same pixels, reports values up to 0.82. Neither method is wrong. They are answering with different definitions of <em>absent</em>, and where the definitions collide the answers cannot be reconciled.</p>
</section>
<section id="grad-cam-localizing-to-channels-rather-than-pixels" class="level3">
<h3 class="anchored" data-anchor-id="grad-cam-localizing-to-channels-rather-than-pixels">Grad-CAM: localizing to channels rather than pixels</h3>
<p>Both methods so far take the pixel as the unit of responsibility, and a pixel is a poor unit — it is far below the scale at which the network represents anything. <a href="https://arxiv.org/abs/1610.02391">Grad-CAM</a> changes the parts. The units become the 128 channels of the final convolution, each of which carries a 7×7 map of where it fired. Weight each channel by the average gradient of the target logit across its map — how much turning that channel up would help — sum the channels with those weights, and keep the positive part.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> grad_cam(model: SmallCNN, x01: torch.Tensor, target: <span class="bu">int</span>) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    activations <span class="op">=</span> model.features(normalise(_as_batch(x01)))  <span class="co"># (1, 128, 7, 7)</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    activations.retain_grad()</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    model.zero_grad(set_to_none<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    model.head(activations)[<span class="dv">0</span>, target].backward()</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    weights <span class="op">=</span> activations.grad[<span class="dv">0</span>].mean(dim<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">2</span>))  <span class="co"># (128,) channel weights</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    cam <span class="op">=</span> torch.relu((weights[:, <span class="va">None</span>, <span class="va">None</span>] <span class="op">*</span> activations[<span class="dv">0</span>]).<span class="bu">sum</span>(<span class="dv">0</span>))  <span class="co"># (7, 7)</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> _upsample(cam.detach().numpy())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="cell-fig-gradcam" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display">
<div id="fig-gradcam" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two Grad-CAM maps over MNIST fives, each a smooth blob. On the misclassified digit the blob covers the closed loop.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gradcam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-gradcam-output-1.png" class="img-fluid figure-img" alt="Two Grad-CAM maps over MNIST fives, each a smooth blob. On the misclassified digit the blob covers the closed loop.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gradcam-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Grad-CAM over the last convolution, upsampled from its native 7×7 grid to pixel resolution.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The map is a smooth blob, and it lands on the loop. It is also, unavoidably, coarse: the underlying grid has 49 cells for 784 pixels, so the finest distinction Grad-CAM can draw on MNIST is a 4×4 pixel block. On a 224×224 ImageNet network the same 7×7 grid buys you a 32-pixel resolution against an object that fills half the frame, which is why the method looks sharper in its original paper than it ever will here. The coarseness is intrinsic to localizing at a layer, not an artefact of the upsampling.</p>
<p>Two things about that channel weighting are worth stating precisely, because both are usually asserted rather than checked. First, the derivation assumes the head treats every spatial position the same way, which is true here because the head is global average pooling followed by one linear layer. On a network whose head flattens the 7×7 map instead — giving each cell its own weight — the mean gradient averages over cells that disagree, and the final ReLU can zero the map completely. That is not hypothetical: with a flatten head on this data, all 49 cells came out negative and Grad-CAM returned an empty image. The architecture was chosen to avoid it.</p>
<p>Second, on a network that <em>does</em> pool, Grad-CAM collapses onto <a href="https://arxiv.org/abs/1512.04150">Zhou et al.’s original CAM</a> — the channel weights become the linear layer’s own weights, divided by the 49 cells being averaged. The build asserts it: Grad-CAM equals CAM / 49 to 8.9e-08 absolute. Grad-CAM’s contribution was never the map; it was removing the architectural precondition for computing one.</p>
</section>
<section id="integrated-gradients-buying-an-axiom-with-a-baseline" class="level3">
<h3 class="anchored" data-anchor-id="integrated-gradients-buying-an-axiom-with-a-baseline">Integrated gradients: buying an axiom with a baseline</h3>
<p>Saliency has no theory of what its numbers sum to. Occlusion has no theory at all. <a href="https://arxiv.org/abs/1703.01365">Integrated gradients</a> starts from the other end: state the properties an attribution ought to have, and derive the method that satisfies them. The key property is <strong>completeness</strong> — the attributions should add up to the difference in output between this input and a chosen reference. Average the gradient along the straight path from the reference to the image, multiply by the displacement, and completeness follows from the fundamental theorem of calculus.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> integrated_gradients(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    model: SmallCNN,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    x01: torch.Tensor,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    target: <span class="bu">int</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    baseline: torch.Tensor <span class="op">|</span> <span class="va">None</span> <span class="op">=</span> <span class="va">None</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    steps: <span class="bu">int</span> <span class="op">=</span> <span class="dv">512</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> np.ndarray:</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> _as_batch(x01)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    base <span class="op">=</span> torch.zeros_like(x) <span class="cf">if</span> baseline <span class="kw">is</span> <span class="va">None</span> <span class="cf">else</span> _as_batch(baseline)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Midpoint rule: unbiased for the linear part and far more accurate than</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># left endpoints at the same cost, which matters because completeness is</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># checked numerically rather than assumed.</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    alphas <span class="op">=</span> (torch.arange(steps, dtype<span class="op">=</span>torch.float32) <span class="op">+</span> <span class="fl">0.5</span>) <span class="op">/</span> steps</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    path <span class="op">=</span> base <span class="op">+</span> alphas.reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>) <span class="op">*</span> (x <span class="op">-</span> base)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    path.requires_grad_(<span class="va">True</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    model.zero_grad(set_to_none<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    model(normalise(path))[:, target].<span class="bu">sum</span>().backward()</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    avg_grad <span class="op">=</span> path.grad.mean(<span class="dv">0</span>, keepdim<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ((x <span class="op">-</span> base) <span class="op">*</span> avg_grad)[<span class="dv">0</span>, <span class="dv">0</span>].detach().numpy()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="cell-fig-ig" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display">
<div id="fig-ig" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two integrated-gradients maps over MNIST fives. Attribution is confined to the stroke; the background is uniformly blank.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-ig-output-1.png" class="img-fluid figure-img" alt="Two integrated-gradients maps over MNIST fives. Attribution is confined to the stroke; the background is uniformly blank.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Integrated gradients from a black baseline. Red pixels push the logit up, blue pixels push it down.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The accounting works: the attributions sum to 10.632 against a true logit difference of 10.636. And because the map is signed we get something the other three cannot express — 17.1 of positive evidence for 6 against 6.5 arguing the other way, with the blue concentrated on the top bar, the one stroke that says five.</p>
<section id="caveat-completeness-is-bought-with-a-choice-and-the-choice-does-the-work" class="level4">
<h4 class="anchored" data-anchor-id="caveat-completeness-is-bought-with-a-choice-and-the-choice-does-the-work">Caveat: completeness is bought with a choice, and the choice does the work</h4>
<p>Look at the background of that figure. It is not faint, it is exactly zero, at every one of the 617 black pixels. This is definitional, not empirical: the attribution is a displacement <span class="math inline">\(x - x'\)</span> times an averaged gradient, and where the image equals the baseline the displacement is zero, so the product is zero whatever the network does there.</p>
<p>That is a real answer to saliency’s stray hotspot — integrated gradients simply cannot put mass on an empty pixel. But it is an answer by construction, and it means the baseline is not a technical parameter. It is the definition of “absent” against which everything is measured, and completeness holds relative to <em>whatever you choose</em>. A black baseline on MNIST encodes the assumption that blank paper is the null state, which is defensible here and much less defensible for natural images, where black is a colour that objects come in. The axiom is satisfied; the interpretation still rests on a judgement call that the axiom does not examine.</p>
</section>
</section>
<section id="caveat-an-explanation-that-survives-randomizing-the-model-explains-nothing" class="level3">
<h3 class="anchored" data-anchor-id="caveat-an-explanation-that-survives-randomizing-the-model-explains-nothing">Caveat: an explanation that survives randomizing the model explains nothing</h3>
<p>Before comparing the four maps, they should have to pass a test. <a href="https://arxiv.org/abs/1810.03292">Adebayo et al.</a> proposed the sharpest one available: replace the trained weights with fresh random ones and recompute the explanation. If the picture barely changes, the method is not reading the model. It is reading the image, and the model was decorative.</p>
<div id="cell-fig-sanity" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div id="fig-sanity" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A two-by-three grid. The top row shows saliency, Grad-CAM and integrated gradients from the trained network; the bottom row shows the same three from a randomly initialised network. The integrated-gradients pair look nearly identical in magnitude.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sanity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-sanity-output-1.png" class="img-fluid figure-img" alt="A two-by-three grid. The top row shows saliency, Grad-CAM and integrated gradients from the trained network; the bottom row shows the same three from a randomly initialised network. The integrated-gradients pair look nearly identical in magnitude.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sanity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: The same three methods applied to an untrained network on the same digit. Rank correlations are against the trained network’s map, over all 784 pixels.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Saliency and Grad-CAM pass comfortably: rank correlations of <span class="math inline">\(+0.03\)</span> and <span class="math inline">\(-0.38\)</span> against their trained counterparts, which is to say the untrained network’s maps carry no usable information about the trained one’s. Integrated gradients fails, and fails spectacularly — the magnitudes correlate at <span class="math inline">\(+0.99\)</span>.</p>
<p>The mechanism is the one from the previous caveat, seen from the other side. Every integrated-gradients attribution carries the factor <span class="math inline">\(x - x'\)</span>, which depends only on the image. That factor dominates the magnitude, so <em>any</em> network produces a map shaped like the digit’s stroke. The signs, which are the part carrying model information, tell a different story: their rank correlation is <span class="math inline">\(-0.01\)</span>, essentially nothing. So the honest reading is that the picture is mostly the input and the information is mostly in the colours — and a reader shown only the magnitudes would learn nothing about the model while feeling that they had.</p>
<p>This is worth generalising. Any attribution of the form <em>gradient times input</em> inherits the input’s structure, which is precisely what makes such maps look convincing. Looking like the object is not evidence that the method found the object.</p>
</section>
<section id="what-the-four-maps-agree-about-and-where-they-part" class="level3">
<h3 class="anchored" data-anchor-id="what-the-four-maps-agree-about-and-where-they-part">What the four maps agree about, and where they part</h3>
<p>Four methods, one wrong answer. They agree more than the pictures suggest, but the disagreements are not noise — each one traces back to a definition.</p>
<div id="cell-fig-agreement" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-agreement" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Four attribution maps of a misclassified MNIST five, plus a four-by-four matrix of rank correlations. Occlusion and Grad-CAM correlate at 0.77; saliency correlates weakly with everything.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-agreement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-agreement-output-1.png" class="img-fluid figure-img" alt="Four attribution maps of a misclassified MNIST five, plus a four-by-four matrix of rank correlations. Occlusion and Grad-CAM correlate at 0.77; saliency correlates weakly with everything.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-agreement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: All four localizations of the same misclassification, with Spearman rank correlations between their magnitudes over all 784 pixels.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Occlusion and Grad-CAM correlate at <span class="math inline">\(+0.77\)</span>, and both land on the closed loop. That is the substantive finding of Part I and all four methods are consistent with it: the network read a loop, and a loop is what distinguishes a six. The two agree because they are asking similar questions at similar scale — both are coarse, both are about regions, and Grad-CAM’s blob is roughly the union of the patches that occlusion found expensive to remove.</p>
<p>Integrated gradients sits at <span class="math inline">\(+0.64\)</span> with occlusion: it finds the same stroke but distributes credit along it much more finely, and spends part of its budget on the negative evidence the other two cannot represent at all.</p>
<p>Saliency is the outlier, correlating between <span class="math inline">\(+0.03\)</span> and <span class="math inline">\(+0.23\)</span> with everything else. Given the previous two sections, that is the expected result rather than a surprise. It measures a different quantity — sensitivity to a hypothetical perturbation, rather than contribution to the actual output — and it is the only one of the four that is free to put its maximum on a pixel containing nothing.</p>
<p>So: which parts made the network say six? Every method that defines responsibility by contribution rather than sensitivity says the same thing, which is the loop. But none of them says <em>how sure we should be</em> of that. Not one of the four numbers on any pixel comes with an interval, or with any way to distinguish a real effect from a fluctuation of this particular image, this particular seed, this particular training run. Part II is about a tradition that would consider that omission disqualifying.</p>
</section>
</section>
<section id="part-ii-explaining-a-glass-box-iris" class="level2">
<h2 class="anchored" data-anchor-id="part-ii-explaining-a-glass-box-iris">Part II — Explaining a glass box: Iris</h2>
<p>Same problem, opposite regime. Four features instead of 784 pixels, 150 rows instead of 60,000, and a model whose parameters are the explanation rather than an obstacle to it. What changes is not the question — still <em>which parts, and how much</em> — but that every answer now arrives with a statement about its own reliability.</p>
<section id="where-these-flowers-come-from-and-what-the-labels-mean" class="level3">
<h3 class="anchored" data-anchor-id="where-these-flowers-come-from-and-what-the-labels-mean">Where these flowers come from, and what the labels mean</h3>
<p>The measurements are Edgar Anderson’s. Working at the Missouri Botanical Garden in the 1930s on the problem of how species boundaries hold up under variation, he measured sepals and petals from irises on the Gaspé Peninsula in Quebec — four measurements per flower, in centimetres, all recorded by hand. The <em>Iris setosa</em> and <em>Iris versicolor</em> plants were, as Fisher quotes him, all from the same pasture, picked on the same day and measured at the same time by the same person with the same apparatus. The 50 <em>Iris virginica</em> flowers were not: they come from a different colony, and Fisher says so explicitly in the paper. The dataset is therefore two clean samples and one that was gathered under other conditions — a detail worth carrying into any claim about how well the three separate.</p>
<p>Ronald Fisher took that table and used it to introduce linear discriminant analysis in <em><a href="https://onlinelibrary.wiley.com/doi/10.1111/j.1469-1809.1936.tb02137.x">The Use of Multiple Measurements in Taxonomic Problems</a></em> (1936). The paper appeared in the <em>Annals of Eugenics</em>, which Fisher edited; he was a prominent eugenicist, and that is a fact about the dataset’s history worth stating plainly rather than eliding.</p>
<p>The question asked of the data, then and here, is taxonomic: given four measurements, which species is this? The label is a botanist’s identification, not an instrument reading, and the downstream consequence of getting it wrong is a misclassified herbarium specimen — a research conclusion, not a diagnosis or a loan. That low stake is exactly why Iris survives as a teaching set, and it is a useful contrast with Part I: nothing below is doing work that anyone should be worried about, which leaves the statistical machinery visible.</p>
<p>The reason to reach for interval estimates on 150 rows is the sample size itself. Fifty flowers per species is enough to estimate a mean and nowhere near enough to treat a fitted coefficient as a fact. Two of the four measurements correlate at 0.963, which means the data cannot cleanly separate their contributions — and a method that reports uncertainty will say so, while a method that reports a point estimate will not.</p>
</section>
<section id="coefficients-responsibility-with-an-error-bar-attached" class="level3">
<h3 class="anchored" data-anchor-id="coefficients-responsibility-with-an-error-bar-attached">Coefficients: responsibility with an error bar attached</h3>
<p>Setosa is trivially separable from the other two, so the interesting comparison is versicolor against virginica. Fit an unpenalised logistic regression to the four standardised measurements by Newton–Raphson; at the maximum, the log-likelihood’s curvature is <span class="math inline">\(X^\top W X\)</span> with <span class="math inline">\(W = \mathrm{diag}(p(1-p))\)</span>, and the inverse of that matrix is the asymptotic covariance of the coefficients. Sharp curvature means the data pin the coefficient down, and the standard error is small. That is the whole content of a confidence interval on a coefficient, and it is the thing Part I had no analogue of.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_logistic(</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>    X: np.ndarray, y: np.ndarray, names: <span class="bu">list</span>[<span class="bu">str</span>], max_iter: <span class="bu">int</span> <span class="op">=</span> <span class="dv">100</span>, tol: <span class="bu">float</span> <span class="op">=</span> <span class="fl">1e-10</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> LogitFit:</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    Xd <span class="op">=</span> np.column_stack([np.ones(<span class="bu">len</span>(X)), X])</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    beta <span class="op">=</span> np.zeros(Xd.shape[<span class="dv">1</span>])</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    converged, used <span class="op">=</span> <span class="va">False</span>, max_iter</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> step <span class="kw">in</span> <span class="bu">range</span>(max_iter):</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>        eta <span class="op">=</span> Xd <span class="op">@</span> beta</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>        p <span class="op">=</span> <span class="fl">1.0</span> <span class="op">/</span> (<span class="fl">1.0</span> <span class="op">+</span> np.exp(<span class="op">-</span>eta))</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        W <span class="op">=</span> p <span class="op">*</span> (<span class="fl">1.0</span> <span class="op">-</span> p)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Ridge-free Newton step. pinv rather than solve: on separable data the</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>        <span class="co"># information matrix goes singular, and we want the run to continue and</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>        <span class="co"># report a diverging coefficient rather than raise.</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>        hessian <span class="op">=</span> Xd.T <span class="op">@</span> (W[:, <span class="va">None</span>] <span class="op">*</span> Xd)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>        score <span class="op">=</span> Xd.T <span class="op">@</span> (y <span class="op">-</span> p)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>        delta <span class="op">=</span> np.linalg.pinv(hessian) <span class="op">@</span> score</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>        beta <span class="op">=</span> beta <span class="op">+</span> delta</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> np.<span class="bu">max</span>(np.<span class="bu">abs</span>(delta)) <span class="op">&lt;</span> tol:</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>            converged, used <span class="op">=</span> <span class="va">True</span>, step <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    eta <span class="op">=</span> Xd <span class="op">@</span> beta</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> np.clip(<span class="fl">1.0</span> <span class="op">/</span> (<span class="fl">1.0</span> <span class="op">+</span> np.exp(<span class="op">-</span>eta)), <span class="fl">1e-15</span>, <span class="dv">1</span> <span class="op">-</span> <span class="fl">1e-15</span>)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    W <span class="op">=</span> p <span class="op">*</span> (<span class="fl">1.0</span> <span class="op">-</span> p)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    cov <span class="op">=</span> np.linalg.pinv(Xd.T <span class="op">@</span> (W[:, <span class="va">None</span>] <span class="op">*</span> Xd))</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    loglik <span class="op">=</span> <span class="bu">float</span>(np.<span class="bu">sum</span>(y <span class="op">*</span> np.log(p) <span class="op">+</span> (<span class="dv">1</span> <span class="op">-</span> y) <span class="op">*</span> np.log(<span class="dv">1</span> <span class="op">-</span> p)))</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> LogitFit(</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>        beta<span class="op">=</span>beta,</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>        se<span class="op">=</span>np.sqrt(np.diag(cov)),</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>        cov<span class="op">=</span>cov,</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>        iterations<span class="op">=</span>used,</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>        converged<span class="op">=</span>converged,</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>        loglik<span class="op">=</span>loglik,</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>        names<span class="op">=</span>[<span class="st">"intercept"</span>] <span class="op">+</span> <span class="bu">list</span>(names),</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="cell-fig-coefficients" class="cell" data-execution_count="16">
<div class="cell-output cell-output-display">
<div id="fig-coefficients" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A forest plot of four logistic-regression coefficients. Petal length and petal width are large and positive with very wide intervals; both sepal coefficients straddle zero.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-coefficients-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-coefficients-output-1.png" class="img-fluid figure-img" alt="A forest plot of four logistic-regression coefficients. Petal length and petal width are large and positive with very wide intervals; both sepal coefficients straddle zero.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-coefficients-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Coefficients with 95% Wald intervals, versicolor versus virginica, on standardised measurements.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="8e79a537" class="cell" data-execution_count="17">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="17">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 12%">
<col style="width: 10%">
<col style="width: 12%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">coef</th>
<th style="text-align: right;">std err</th>
<th style="text-align: right;">z</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">2.5%</th>
<th style="text-align: right;">97.5%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sepal length</td>
<td style="text-align: right;">-1.634</td>
<td style="text-align: right;">1.587</td>
<td style="text-align: right;">-1.030</td>
<td style="text-align: right;">0.303</td>
<td style="text-align: right;">-4.745</td>
<td style="text-align: right;">1.476</td>
</tr>
<tr class="even">
<td style="text-align: left;">sepal width</td>
<td style="text-align: right;">-2.223</td>
<td style="text-align: right;">1.491</td>
<td style="text-align: right;">-1.491</td>
<td style="text-align: right;">0.136</td>
<td style="text-align: right;">-5.145</td>
<td style="text-align: right;">0.698</td>
</tr>
<tr class="odd">
<td style="text-align: left;">petal length</td>
<td style="text-align: right;">7.785</td>
<td style="text-align: right;">3.911</td>
<td style="text-align: right;">1.990</td>
<td style="text-align: right;">0.047</td>
<td style="text-align: right;">0.119</td>
<td style="text-align: right;">15.450</td>
</tr>
<tr class="even">
<td style="text-align: left;">petal width</td>
<td style="text-align: right;">7.767</td>
<td style="text-align: right;">4.138</td>
<td style="text-align: right;">1.877</td>
<td style="text-align: right;">0.061</td>
<td style="text-align: right;">-0.344</td>
<td style="text-align: right;">15.878</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Read it as an explanation and it says: petals discriminate, sepals do not. Read it as a <em>localization with error bars</em> and it says something more interesting. Petal length carries a coefficient of 7.78 and petal width 7.77 — nearly identical, both enormous — and both have standard errors of roughly 4.0. Petal width’s interval crosses zero. Taken one at a time, neither petal measurement is quite significant at the 5% level.</p>
<p>That is not a sign that petals do not matter. It is the interval doing its job on collinear predictors: with the two petal measurements correlated at 0.963, the data can say confidently that petal size separates the species and cannot say which of the two measurements deserves the credit. The coefficients are individually unstable and jointly precise. An attribution method that returned two point estimates here would report the same split and give you no way at all to notice the problem.</p>
<section id="caveat-when-the-classes-separate-there-is-no-estimate-to-put-an-error-bar-on" class="level4">
<h4 class="anchored" data-anchor-id="caveat-when-the-classes-separate-there-is-no-estimate-to-put-an-error-bar-on">Caveat: when the classes separate, there is no estimate to put an error bar on</h4>
<p>The interval only works when a maximum exists. Setosa is the standard demonstration that it need not. Ask the same unpenalised model to separate setosa from the other two species and the likelihood has no maximum: some hyperplane classifies every point correctly, so pushing the coefficients further from zero always improves the fit, and the estimate runs off to infinity. Here separation is confirmed directly, by solving the feasibility problem rather than inferring it from a fit that misbehaves.</p>
<div id="cell-fig-separation" class="cell" data-execution_count="18">
<div class="cell-output cell-output-display">
<div id="fig-separation" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A log-log plot. Coefficient norm rises from about 1.7 to 92 as Newton steps increase from 1 to 100; the largest standard error rises from about 1.4 to over ten million.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-separation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-separation-output-1.png" class="img-fluid figure-img" alt="A log-log plot. Coefficient norm rises from about 1.7 to 92 as Newton steps increase from 1 to 100; the largest standard error rises from about 1.4 to over ten million.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-separation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Refitting setosa-versus-rest with increasing Newton budgets. Neither the coefficients nor their standard errors converge.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="f1b03038" class="cell" data-execution_count="19">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="19">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 27%">
<col style="width: 26%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">newton steps</th>
<th style="text-align: right;">coefficient norm</th>
<th style="text-align: right;">largest std err</th>
<th style="text-align: right;">log-likelihood</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">1.67</td>
<td style="text-align: right;">1.37</td>
<td style="text-align: right;">-24.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2.81</td>
<td style="text-align: right;">2.17</td>
<td style="text-align: right;">-9.6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">6.17</td>
<td style="text-align: right;">8.79</td>
<td style="text-align: right;">-0.643</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">12.6</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">-0.00623</td>
</tr>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: right;">39.8</td>
<td style="text-align: right;">2.64e+05</td>
<td style="text-align: right;">-2.27e-09</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
<td style="text-align: right;">72.7</td>
<td style="text-align: right;">1.45e+07</td>
<td style="text-align: right;">-1.5e-13</td>
</tr>
<tr class="odd">
<td style="text-align: right;">100</td>
<td style="text-align: right;">91.6</td>
<td style="text-align: right;">1.45e+07</td>
<td style="text-align: right;">-1.5e-13</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Nothing settles. Over 100 Newton steps the coefficient norm climbs from 1.67 to 92 and the largest standard error from 1.37 to about 1.4e+07, while the log-likelihood creeps toward zero. The coefficient norm is still climbing at the last step; the standard error stops only because the information matrix has become numerically singular in double precision and the pseudo-inverse has nothing left to invert. Neither number is converging to anything. The most interpretable model in the book, on the most-taught dataset in statistics, returns an explanation whose every component is arbitrarily large with an arbitrarily large error bar.</p>
<p>This is easy to miss in practice, because the defaults hide it: <code>scikit-learn</code>’s <code>LogisticRegression</code> applies L2 regularisation unless told not to, which keeps the coefficients finite and prints a tidy table. The tidiness is the penalty’s, not the data’s. And it is worth being clear about the direction of the lesson — the error bars did not fail here, they worked. They reported honestly that the data does not identify the parameters. A method with no error bars would have reported a number.</p>
</section>
</section>
<section id="anova-localizing-to-sources-of-variance-rather-than-to-features" class="level3">
<h3 class="anchored" data-anchor-id="anova-localizing-to-sources-of-variance-rather-than-to-features">ANOVA: localizing to sources of variance rather than to features</h3>
<p>Coefficients answer “how much does the model lean on this feature”, which is a question about the model. Fisher’s analysis of variance asks something prior to any model: how much of the observed variation in a measurement is variation <em>between</em> species rather than within them? The total sum of squares splits exactly into those two pieces, and <span class="math inline">\(\eta^2\)</span> is the between-group share.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> anova_table(df: pd.DataFrame) <span class="op">-&gt;</span> pd.DataFrame:</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> []</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> feature <span class="kw">in</span> FEATURES:</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        groups <span class="op">=</span> [df.loc[df.species <span class="op">==</span> s, feature].to_numpy() <span class="cf">for</span> s <span class="kw">in</span> SPECIES]</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        values <span class="op">=</span> np.concatenate(groups)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        grand <span class="op">=</span> values.mean()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>        ss_between <span class="op">=</span> <span class="bu">sum</span>(<span class="bu">len</span>(g) <span class="op">*</span> (g.mean() <span class="op">-</span> grand) <span class="op">**</span> <span class="dv">2</span> <span class="cf">for</span> g <span class="kw">in</span> groups)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>        ss_within <span class="op">=</span> <span class="bu">sum</span>(((g <span class="op">-</span> g.mean()) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>() <span class="cf">for</span> g <span class="kw">in</span> groups)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>        df_between <span class="op">=</span> <span class="bu">len</span>(groups) <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        df_within <span class="op">=</span> <span class="bu">len</span>(values) <span class="op">-</span> <span class="bu">len</span>(groups)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>        f <span class="op">=</span> (ss_between <span class="op">/</span> df_between) <span class="op">/</span> (ss_within <span class="op">/</span> df_within)</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        rows.append(</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>            {</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>                <span class="st">"feature"</span>: feature,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>                <span class="st">"F"</span>: f,</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>                <span class="st">"df"</span>: <span class="ss">f"</span><span class="sc">{</span>df_between<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>df_within<span class="sc">}</span><span class="ss">"</span>,</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>                <span class="st">"p"</span>: <span class="bu">float</span>(stats.f.sf(f, df_between, df_within)),</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>                <span class="st">"eta^2"</span>: ss_between <span class="op">/</span> (ss_between <span class="op">+</span> ss_within),</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>            }</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame(rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="cell-fig-anova" class="cell" data-execution_count="21">
<div class="cell-output cell-output-display">
<div id="fig-anova" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Left, a strip plot of the four measurements coloured by species; petal length and width separate setosa cleanly. Right, bar chart of eta squared: petal length 0.94, petal width 0.93, sepal length 0.62, sepal width 0.40.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-anova-output-1.png" class="img-fluid figure-img" alt="Left, a strip plot of the four measurements coloured by species; petal length and width separate setosa cleanly. Right, bar chart of eta squared: petal length 0.94, petal width 0.93, sepal length 0.62, sepal width 0.40.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-anova-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Each measurement by species, with the between-species share of its variance.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="69ddfaa9" class="cell" data-execution_count="22">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="22">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">feature</th>
<th style="text-align: right;">F</th>
<th style="text-align: left;">df</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">eta^2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sepal length</td>
<td style="text-align: right;">119.3</td>
<td style="text-align: left;">2, 147</td>
<td style="text-align: right;">1.67e-31</td>
<td style="text-align: right;">0.6187</td>
</tr>
<tr class="even">
<td style="text-align: left;">sepal width</td>
<td style="text-align: right;">49.16</td>
<td style="text-align: left;">2, 147</td>
<td style="text-align: right;">4.492e-17</td>
<td style="text-align: right;">0.4008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">petal length</td>
<td style="text-align: right;">1180</td>
<td style="text-align: left;">2, 147</td>
<td style="text-align: right;">2.857e-91</td>
<td style="text-align: right;">0.9414</td>
</tr>
<tr class="even">
<td style="text-align: left;">petal width</td>
<td style="text-align: right;">960</td>
<td style="text-align: left;">2, 147</td>
<td style="text-align: right;">4.169e-85</td>
<td style="text-align: right;">0.9289</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Petal length reaches <span class="math inline">\(\eta^2\)</span> = 0.941: knowing the species accounts for 94.1% of its variation. All four F statistics are enormous and the <em>largest</em> of the four p-values is 4e-17, which is the expected result for three species a botanist can tell apart by eye. The interesting content is in the shares, not the significance — with 50 flowers per group, a test this powerful was never going to say anything else.</p>
<section id="caveat-these-shares-sum-to-2.89" class="level4">
<h4 class="anchored" data-anchor-id="caveat-these-shares-sum-to-2.89">Caveat: these shares sum to 2.89</h4>
<p>Which is impossible for shares of one thing. Each row is a <em>separate</em> one-way ANOVA on a single measurement, so each answers “how much of this column’s variance is between-species” in isolation. Sepal length scores 0.62 in large part because it correlates at 0.872 with petal length; it is credited for variation that petal length would also claim.</p>
<p>Univariate variance decomposition is therefore a <em>marginal</em> attribution — what each part explains on its own — while a regression coefficient is a <em>conditional</em> one, holding the others fixed. Both are legitimate and they answer different questions, which is why the two tables above rank the sepals so differently. Any attribution method, in either tradition, has to make this choice, and most do it silently.</p>
</section>
</section>
<section id="pca-localizing-to-directions-instead-of-to-features" class="level3">
<h3 class="anchored" data-anchor-id="pca-localizing-to-directions-instead-of-to-features">PCA: localizing to directions instead of to features</h3>
<p>The three methods so far all take the measured feature as the unit. Principal component analysis gives that up. Its parts are linear combinations of the measurements, chosen so each successive direction captures as much of the remaining variance as it can — buying concentration at the cost of nameability.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> pca_fit(X: np.ndarray, standardised: <span class="bu">bool</span> <span class="op">=</span> <span class="va">True</span>, k: <span class="bu">int</span> <span class="op">=</span> <span class="dv">2</span>) <span class="op">-&gt;</span> PCAFit:</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    Z <span class="op">=</span> standardise(X) <span class="cf">if</span> standardised <span class="cf">else</span> X <span class="op">-</span> X.mean(<span class="dv">0</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>    U, S, Vt <span class="op">=</span> np.linalg.svd(Z, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    var <span class="op">=</span> S<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (<span class="bu">len</span>(Z) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sign convention: make each component's largest-magnitude loading positive,</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># so the biplot does not flip between runs or between standardisations.</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    V <span class="op">=</span> Vt.T</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    flip <span class="op">=</span> np.sign(V[np.<span class="bu">abs</span>(V).argmax(<span class="dv">0</span>), np.arange(V.shape[<span class="dv">1</span>])])</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    V <span class="op">=</span> V <span class="op">*</span> flip</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> Z <span class="op">@</span> V</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> PCAFit(</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>        ratio<span class="op">=</span>var <span class="op">/</span> var.<span class="bu">sum</span>(),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>        loadings<span class="op">=</span>V[:, :k],</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>        scores<span class="op">=</span>scores[:, :k],</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>        standardised<span class="op">=</span>standardised,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="cell-fig-pca" class="cell" data-execution_count="24">
<div class="cell-output cell-output-display">
<div id="fig-pca" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Left, a bar chart comparing explained variance ratios for standardised and raw-centimetre PCA. Right, a biplot of the first two standardised components with the three species separated and four loading arrows.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-pca-output-1.png" class="img-fluid figure-img" alt="Left, a bar chart comparing explained variance ratios for standardised and raw-centimetre PCA. Right, a biplot of the first two standardised components with the three species separated and four loading arrows.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pca-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Left: explained variance under two scalings. Right: the standardised biplot, loadings drawn over scores.
</figcaption>
</figure>
</div>
</div>
</div>
<p>On standardised data the first two components carry 95.8% of the variance, and the biplot shows why Iris is a teaching set: setosa is cleanly detached along PC1, versicolor and virginica overlap slightly. The loadings say what PC1 means — petal length 0.58, petal width 0.56, sepal length 0.52, sepal width -0.27 — a general size axis with sepal width running against it.</p>
<p>The left panel carries the caveat, and it is a sharp one. Run the same decomposition on raw centimetres and PC1 accounts for 92.5% rather than 73.0%, with a loading of 0.86 on petal length alone. Unstandardised PCA maximises variance in the units the data happens to be recorded in, and petal length simply has the widest range in centimetres. The “explanation” changed because someone chose a scale. Note that this is not a defect unique to PCA — occlusion in Part I depended on the fill value in exactly the same way, and for exactly the same reason.</p>
</section>
<section id="permutation-importance-occlusion-moved-to-a-table" class="level3">
<h3 class="anchored" data-anchor-id="permutation-importance-occlusion-moved-to-a-table">Permutation importance: occlusion, moved to a table</h3>
<p>The last method is the ML tradition’s, and it is here to close the loop. Take the fitted model, shuffle one column of the held-out set to break its link with the label while leaving its marginal distribution untouched, and measure the accuracy lost. That is occlusion, with a column in place of a patch and a permutation in place of a black square.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> permutation_importance(</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    predict, X: np.ndarray, y: np.ndarray, repeats: <span class="bu">int</span>, rng: np.random.Generator</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>) <span class="op">-&gt;</span> pd.DataFrame:</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    baseline <span class="op">=</span> <span class="bu">float</span>((predict(X) <span class="op">==</span> y).mean())</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> []</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j, name <span class="kw">in</span> <span class="bu">enumerate</span>(FEATURES):</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>        drops <span class="op">=</span> np.empty(repeats)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> r <span class="kw">in</span> <span class="bu">range</span>(repeats):</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>            Xp <span class="op">=</span> X.copy()</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>            Xp[:, j] <span class="op">=</span> Xp[rng.permutation(<span class="bu">len</span>(Xp)), j]</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>            drops[r] <span class="op">=</span> baseline <span class="op">-</span> <span class="bu">float</span>((predict(Xp) <span class="op">==</span> y).mean())</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>        rows.append(</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>            {</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>                <span class="st">"feature"</span>: name,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>                <span class="st">"mean drop"</span>: drops.mean(),</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>                <span class="st">"sd"</span>: drops.std(ddof<span class="op">=</span><span class="dv">1</span>),</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>                <span class="st">"se"</span>: drops.std(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.sqrt(repeats),</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>            }</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>        )</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> pd.DataFrame(rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="cell-fig-permutation" class="cell" data-execution_count="26">
<div class="cell-output cell-output-display">
<div id="fig-permutation" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Left, a bar chart of accuracy lost per shuffled feature with error bars: petal width 0.21, petal length 0.19, both sepals 0.04. Right, grouped bars comparing permutation importance, ANOVA eta squared and absolute coefficient.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-permutation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-permutation-output-1.png" class="img-fluid figure-img" alt="Left, a bar chart of accuracy lost per shuffled feature with error bars: petal width 0.21, petal length 0.19, both sepals 0.04. Right, grouped bars comparing permutation importance, ANOVA eta squared and absolute coefficient.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-permutation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Permutation importance with 95% intervals from 200 shuffles, and the three localizations side by side, each scaled to its own maximum.
</figcaption>
</figure>
</div>
</div>
</div>
<div id="21cbfc9d" class="cell" data-execution_count="27">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="27">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">feature</th>
<th style="text-align: right;">mean drop</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">se</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sepal length</td>
<td style="text-align: right;">0.0402</td>
<td style="text-align: right;">0.0224</td>
<td style="text-align: right;">0.0016</td>
</tr>
<tr class="even">
<td style="text-align: left;">sepal width</td>
<td style="text-align: right;">0.0395</td>
<td style="text-align: right;">0.0279</td>
<td style="text-align: right;">0.0020</td>
</tr>
<tr class="odd">
<td style="text-align: left;">petal length</td>
<td style="text-align: right;">0.1922</td>
<td style="text-align: right;">0.0468</td>
<td style="text-align: right;">0.0033</td>
</tr>
<tr class="even">
<td style="text-align: left;">petal width</td>
<td style="text-align: right;">0.2127</td>
<td style="text-align: right;">0.0470</td>
<td style="text-align: right;">0.0033</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>On a 60-flower held-out set the multinomial model scores 95.0%, and shuffling petal width costs it 0.213 of that while shuffling sepal width costs 0.039. The same ordering as the coefficients, from a method that never looks inside the model.</p>
<p>The important part is the error bars, and where they come from. The shuffle is random, so 200 repeats give a <em>distribution</em> of importances rather than a number — the interval is a Monte-Carlo statement about the permutation, not a confidence interval for a parameter, and it says nothing about sampling variability in the 150 flowers. It is a genuinely weaker guarantee than the Wald interval above. But it is a guarantee, obtained by a method that treats the model as a black box, and there is no reason the same trick cannot be applied to an occlusion map: re-run it across seeds, across training runs, across bootstrap resamples of the data, and report the spread.</p>
<p>The right panel is the payoff. Three methods, three notions of a part, one dataset, and they agree closely on the petals and disagree on the sepals — with ANOVA rating sepal length far above the other two, exactly as the marginal-versus-conditional distinction predicts. Disagreement between attribution methods is not usually a sign that one is broken. It is usually a sign that they were asked different questions.</p>
</section>
</section>
<section id="where-the-two-traditions-meet" class="level2">
<h2 class="anchored" data-anchor-id="where-the-two-traditions-meet">Where the two traditions meet</h2>
<p>Eight methods, one framing. Laid against the three axes from the opening, the pattern is not that machine learning and statistics do different things — it is that they have covered different parts of the same grid.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Method</th>
<th>Part</th>
<th>Responsible means</th>
<th>Uncertainty</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Saliency</td>
<td>pixel</td>
<td>large local gradient</td>
<td>none</td>
</tr>
<tr class="even">
<td>Occlusion</td>
<td>image patch</td>
<td>logit lost when blanked</td>
<td>none as computed</td>
</tr>
<tr class="odd">
<td>Grad-CAM</td>
<td>conv channel</td>
<td>active <em>and</em> gradient-weighted</td>
<td>none</td>
</tr>
<tr class="even">
<td>Integrated gradients</td>
<td>pixel</td>
<td>path integral from a baseline</td>
<td>none</td>
</tr>
<tr class="odd">
<td>Logistic coefficient</td>
<td>feature</td>
<td>log-odds per sd, others fixed</td>
<td>Wald interval</td>
</tr>
<tr class="even">
<td>ANOVA <span class="math inline">\(\eta^2\)</span></td>
<td>feature</td>
<td>share of between-group variance</td>
<td>F test</td>
</tr>
<tr class="odd">
<td>PCA loading</td>
<td>direction</td>
<td>variance captured</td>
<td>none as computed</td>
</tr>
<tr class="even">
<td>Permutation importance</td>
<td>feature</td>
<td>accuracy lost when shuffled</td>
<td>Monte-Carlo interval</td>
</tr>
</tbody>
</table>
<p>The third column is the interesting one. Every method in the table is <em>correlational</em> in the sense that matters: none of them establishes that the part caused the output, only that the output covaries with the part under some manipulation. But they are not all correlational in the same way. Saliency, coefficients and PCA loadings read structure off the fitted object without changing anything. Occlusion, integrated gradients and permutation importance <em>intervene</em> — they construct inputs the model was never trained on and observe the consequence.</p>
<p>That distinction is where the frontier is. Intervening is closer to a causal claim, but the interventions above all push the input off the data manifold: a digit with a black square through it, a flower with one measurement drawn from another flower. The model’s response to an impossible input is not obviously evidence about its behaviour on possible ones. Mechanistic interpretability takes the natural next step — intervene <em>inside</em> the network instead. Activation patching runs the model on two inputs, copies a specific internal activation from one run into the other, and measures how far the output moves, which localizes responsibility to a component under an intervention the network’s own distribution supports. The parts become circuits and attention heads rather than pixels, and the credit rule becomes an experiment rather than a derivative. What it inherits unchanged from everything above is the third column: those results are point estimates too.</p>
</section>
<section id="the-column-that-is-still-empty" class="level2">
<h2 class="anchored" data-anchor-id="the-column-that-is-still-empty">The column that is still empty</h2>
<p>The two traditions are not really in tension. They have solved adjacent halves of one problem and left the other half open in mirror image. Statistics knows how to attach honest uncertainty to an attribution, and its methods stop scaling somewhere around the point where the parts start interacting in ways no one can write down. Machine learning has attribution methods that run happily on a billion parameters, and almost none of them can tell you whether the number they returned would survive a different seed.</p>
<p>Neither gap is fundamental. Permutation importance already shows the bridge in one direction — repeat the perturbation, report the spread — and nothing prevents an occlusion map from carrying the same treatment. It would cost a hundred forward passes and it is almost never done.</p>
<p>Until then, the honest reading of a saliency map is narrower than it looks. It says: given this model, this input, and this definition of a part, here is where the credit fell. Not that the credit would fall there again.</p>
</section>
<section id="reproducing-this" class="level2">
<h2 class="anchored" data-anchor-id="reproducing-this">Reproducing this</h2>
<p>Everything above runs from <code>posts/explainability-localization/src/</code>, and every code block on this page is the real source of the function it names, extracted with <code>inspect.getsource</code> at render time rather than copied. See the <a href="https://github.com/project-delphi/ml-blog/tree/main/posts/explainability-localization">README</a> for the environment, the runtimes and the list of build-time checks.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Adebayo, J. et al.&nbsp;(2018). <a href="https://arxiv.org/abs/1810.03292">Sanity Checks for Saliency Maps</a>. <em>NeurIPS</em>.</li>
<li>Anderson, E. (1935). The Irises of the Gaspé Peninsula. <em>Bulletin of the American Iris Society</em>, 59, 2–5.</li>
<li>Fisher, R. A. (1936). <a href="https://onlinelibrary.wiley.com/doi/10.1111/j.1469-1809.1936.tb02137.x">The Use of Multiple Measurements in Taxonomic Problems</a>. <em>Annals of Eugenics</em>, 7(2), 179–188.</li>
<li>LeCun, Y., Cortes, C. and Burges, C. <a href="https://yann.lecun.com/exdb/mnist/">The MNIST Database of Handwritten Digits</a>.</li>
<li>Selvaraju, R. R. et al.&nbsp;(2017). <a href="https://arxiv.org/abs/1610.02391">Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization</a>. <em>ICCV</em>.</li>
<li>Simonyan, K., Vedaldi, A. and Zisserman, A. (2014). <a href="https://arxiv.org/abs/1312.6034">Deep Inside Convolutional Networks: Visualising Image Classification Models and Saliency Maps</a>. <em>ICLR Workshop</em>.</li>
<li>Sundararajan, M., Taly, A. and Yan, Q. (2017). <a href="https://arxiv.org/abs/1703.01365">Axiomatic Attribution for Deep Networks</a>. <em>ICML</em>.</li>
<li>Zeiler, M. D. and Fergus, R. (2014). <a href="https://arxiv.org/abs/1311.2901">Visualizing and Understanding Convolutional Networks</a>. <em>ECCV</em>.</li>
<li>Zhou, B. et al.&nbsp;(2016). <a href="https://arxiv.org/abs/1512.04150">Learning Deep Features for Discriminative Localization</a>. <em>CVPR</em>.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/explainability-localization/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>