<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-07-23">

<title>Maximum-Margin Classification from First Principles: SVMs as Convex Optimization – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Maximum-Margin Classification from First Principles: SVMs as Convex Optimization</h1>
            <p class="subtitle lead">Why the widest street wins: geometry, quadratic programming, support vectors, and the soft-margin trade-off — every number below is solved, not asserted.</p>
                                <div class="quarto-categories">
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Optimization</div>
                <div class="quarto-category">Mathematics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 23, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#separating-the-data-does-not-pick-a-classifier" id="toc-separating-the-data-does-not-pick-a-classifier" class="nav-link active" data-scroll-target="#separating-the-data-does-not-pick-a-classifier"><span class="header-section-number">1</span> Separating the data does not pick a classifier</a></li>
  <li><a href="#clearance-is-a-number-so-it-can-be-maximized" id="toc-clearance-is-a-number-so-it-can-be-maximized" class="nav-link" data-scroll-target="#clearance-is-a-number-so-it-can-be-maximized"><span class="header-section-number">2</span> Clearance is a number, so it can be maximized</a>
  <ul class="collapse">
  <li><a href="#the-margin-is-the-distance-to-the-closest-point" id="toc-the-margin-is-the-distance-to-the-closest-point" class="nav-link" data-scroll-target="#the-margin-is-the-distance-to-the-closest-point"><span class="header-section-number">2.1</span> The margin is the distance to the closest point</a></li>
  <li><a href="#fixing-the-scale-turns-a-ratio-into-a-constraint" id="toc-fixing-the-scale-turns-a-ratio-into-a-constraint" class="nav-link" data-scroll-target="#fixing-the-scale-turns-a-ratio-into-a-constraint"><span class="header-section-number">2.2</span> Fixing the scale turns a ratio into a constraint</a></li>
  </ul></li>
  <li><a href="#maximizing-the-margin-is-minimizing-a-length" id="toc-maximizing-the-margin-is-minimizing-a-length" class="nav-link" data-scroll-target="#maximizing-the-margin-is-minimizing-a-length"><span class="header-section-number">3</span> Maximizing the margin is minimizing a length</a>
  <ul class="collapse">
  <li><a href="#the-solver-recovers-the-line-you-can-read-off-the-plot" id="toc-the-solver-recovers-the-line-you-can-read-off-the-plot" class="nav-link" data-scroll-target="#the-solver-recovers-the-line-you-can-read-off-the-plot"><span class="header-section-number">3.1</span> The solver recovers the line you can read off the plot</a></li>
  </ul></li>
  <li><a href="#each-data-point-becomes-a-half-space-and-that-is-what-makes-this-easy" id="toc-each-data-point-becomes-a-half-space-and-that-is-what-makes-this-easy" class="nav-link" data-scroll-target="#each-data-point-becomes-a-half-space-and-that-is-what-makes-this-easy"><span class="header-section-number">4</span> Each data point becomes a half-space, and that is what makes this easy</a>
  <ul class="collapse">
  <li><a href="#convexity-buys-a-global-answer-and-a-certificate" id="toc-convexity-buys-a-global-answer-and-a-certificate" class="nav-link" data-scroll-target="#convexity-buys-a-global-answer-and-a-certificate"><span class="header-section-number">4.1</span> Convexity buys a global answer and a certificate</a></li>
  <li><a href="#convexity-does-not-buy-feasibility-or-a-single-answer" id="toc-convexity-does-not-buy-feasibility-or-a-single-answer" class="nav-link" data-scroll-target="#convexity-does-not-buy-feasibility-or-a-single-answer"><span class="header-section-number">4.2</span> Convexity does not buy feasibility or a single answer</a></li>
  </ul></li>
  <li><a href="#sec-unique" id="toc-sec-unique" class="nav-link" data-scroll-target="#sec-unique"><span class="header-section-number">5</span> Uniqueness holds here, and it is easy to break</a>
  <ul class="collapse">
  <li><a href="#two-unrelated-algorithms-land-on-the-same-line" id="toc-two-unrelated-algorithms-land-on-the-same-line" class="nav-link" data-scroll-target="#two-unrelated-algorithms-land-on-the-same-line"><span class="header-section-number">5.1</span> Two unrelated algorithms land on the same line</a></li>
  <li><a href="#show-it-one-class-and-the-intercept-floats-free" id="toc-show-it-one-class-and-the-intercept-floats-free" class="nav-link" data-scroll-target="#show-it-one-class-and-the-intercept-floats-free"><span class="header-section-number">5.2</span> Show it one class and the intercept floats free</a></li>
  </ul></li>
  <li><a href="#sec-dual" id="toc-sec-dual" class="nav-link" data-scroll-target="#sec-dual"><span class="header-section-number">6</span> Duality explains why eight of the ten points do not matter</a></li>
  <li><a href="#sec-soft" id="toc-sec-soft" class="nav-link" data-scroll-target="#sec-soft"><span class="header-section-number">7</span> When no line can separate, points buy their way across</a>
  <ul class="collapse">
  <li><a href="#charging-for-violations-keeps-the-problem-convex" id="toc-charging-for-violations-keeps-the-problem-convex" class="nav-link" data-scroll-target="#charging-for-violations-keeps-the-problem-convex"><span class="header-section-number">7.1</span> Charging for violations keeps the problem convex</a></li>
  <li><a href="#raising-the-price-narrows-the-corridor-without-saving-the-outlier" id="toc-raising-the-price-narrows-the-corridor-without-saving-the-outlier" class="nav-link" data-scroll-target="#raising-the-price-narrows-the-corridor-without-saving-the-outlier"><span class="header-section-number">7.2</span> Raising the price narrows the corridor without saving the outlier</a></li>
  <li><a href="#sec-flat" id="toc-sec-flat" class="nav-link" data-scroll-target="#sec-flat"><span class="header-section-number">7.3</span> Soft margins bring non-uniqueness back</a></li>
  </ul></li>
  <li><a href="#two-independent-code-paths-land-on-the-same-hyperplane" id="toc-two-independent-code-paths-land-on-the-same-hyperplane" class="nav-link" data-scroll-target="#two-independent-code-paths-land-on-the-same-hyperplane"><span class="header-section-number">8</span> Two independent code paths land on the same hyperplane</a></li>
  <li><a href="#five-traps-the-four-views-disarm" id="toc-five-traps-the-four-views-disarm" class="nav-link" data-scroll-target="#five-traps-the-four-views-disarm"><span class="header-section-number">9</span> Five traps the four views disarm</a></li>
  <li><a href="#the-instinct-written-down" id="toc-the-instinct-written-down" class="nav-link" data-scroll-target="#the-instinct-written-down"><span class="header-section-number">10</span> The instinct, written down</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/svm-max-margin-convex-optimization/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Maximum-Margin Classification from First Principles</figcaption>
</figure>
</div>
<p>Sketch two clouds of points on paper, one class each, and draw a line that keeps them apart. Then draw a second line that also gets every point right. You will manage it easily, and a third, and a fourth. But notice what your hand does unprompted: it steers down the middle of the empty space rather than shaving past the nearest point, even though both lines score exactly the same on the data in front of you.</p>
<p>A support vector machine is that instinct written down as arithmetic. It is usually introduced as a bag of formulas instead — a hyperplane, a margin, a mysterious constant <span class="math inline">\(C\)</span>, and a dual problem that appears out of nowhere — and all four of them fall out of a single sentence:</p>
<blockquote class="blockquote">
<p><strong>An SVM chooses a separating hyperplane by solving a convex optimization problem that maximizes geometric separation from the training data, while soft margins extend that idea to imperfectly separable data.</strong></p>
</blockquote>
<p>Every claim below is made literal on two tiny two-dimensional datasets, small enough that you can check the geometry by eye. The weights, intercepts, margins, support vectors and slack values are not quoted from a textbook: each one is computed by a convex solver on the exact data plotted, driven by <a href="https://www.cvxpy.org/">CVXPY</a> — a Python library that lets you write a convex problem down in something close to its mathematical form and hands it to a solver. The notebook asserts that the solved values match the ones derived by hand before it will render at all. <code>scikit-learn</code>, the standard Python machine-learning toolkit, appears only at the end as an independent cross-check.</p>
<div id="fb67cf93" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Setup: imports, house palette, plotting helpers, and the toy dataset</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> cvxpy <span class="im">as</span> cp</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.lines <span class="im">import</span> Line2D</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> Markdown</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># palette (house style)</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>BLUE, ORANGE, INK <span class="op">=</span> <span class="st">"#2a78d6"</span>, <span class="st">"#eb6834"</span>, <span class="st">"#0b0b0b"</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>MUTED, GRID, SURFACE <span class="op">=</span> <span class="st">"#898781"</span>, <span class="st">"#e1e0d9"</span>, <span class="st">"#fcfcfb"</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>plt.rcParams.update({</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"figure.facecolor"</span>: SURFACE, <span class="st">"axes.facecolor"</span>: SURFACE,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"savefig.facecolor"</span>: SURFACE,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.edgecolor"</span>: MUTED, <span class="st">"axes.labelcolor"</span>: INK,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"xtick.color"</span>: MUTED, <span class="st">"ytick.color"</span>: MUTED, <span class="st">"text.color"</span>: INK,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.grid"</span>: <span class="va">True</span>, <span class="st">"grid.color"</span>: GRID, <span class="st">"grid.linewidth"</span>: <span class="fl">0.8</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"axes.spines.top"</span>: <span class="va">False</span>, <span class="st">"axes.spines.right"</span>: <span class="va">False</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"font.size"</span>: <span class="dv">11</span>, <span class="st">"axes.titlesize"</span>: <span class="dv">12</span>,</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>RNG_SEED <span class="op">=</span> <span class="dv">42</span>          <span class="co"># fixed seed for every random draw in this post</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>TOL <span class="op">=</span> <span class="fl">1e-6</span>             <span class="co"># numerical tolerance used for all constraint checks</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> md_table(headers, rows):</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Render a small Markdown table without extra dependencies."""</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    head <span class="op">=</span> <span class="st">"| "</span> <span class="op">+</span> <span class="st">" | "</span>.join(headers) <span class="op">+</span> <span class="st">" |"</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    sep <span class="op">=</span> <span class="st">"|"</span> <span class="op">+</span> <span class="st">"|"</span>.join([<span class="st">"---"</span>] <span class="op">*</span> <span class="bu">len</span>(headers)) <span class="op">+</span> <span class="st">"|"</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    body <span class="op">=</span> [<span class="st">"| "</span> <span class="op">+</span> <span class="st">" | "</span>.join(<span class="bu">str</span>(c) <span class="cf">for</span> c <span class="kw">in</span> r) <span class="op">+</span> <span class="st">" |"</span> <span class="cf">for</span> r <span class="kw">in</span> rows]</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> Markdown(<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>.join([head, sep, <span class="op">*</span>body]))</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> scatter_classes(ax, X, y, s<span class="op">=</span><span class="dv">70</span>, sv_mask<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Class -1 as blue circles, class +1 as orange squares (shape backs up color)."""</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>    neg, pos <span class="op">=</span> y <span class="op">&lt;</span> <span class="dv">0</span>, y <span class="op">&gt;</span> <span class="dv">0</span></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>    ax.scatter(<span class="op">*</span>X[neg].T, s<span class="op">=</span>s, c<span class="op">=</span>BLUE, marker<span class="op">=</span><span class="st">"o"</span>, zorder<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>               edgecolor<span class="op">=</span>SURFACE, linewidth<span class="op">=</span><span class="fl">1.2</span>, label<span class="op">=</span><span class="st">"class $-1$"</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>    ax.scatter(<span class="op">*</span>X[pos].T, s<span class="op">=</span>s, c<span class="op">=</span>ORANGE, marker<span class="op">=</span><span class="st">"s"</span>, zorder<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>               edgecolor<span class="op">=</span>SURFACE, linewidth<span class="op">=</span><span class="fl">1.2</span>, label<span class="op">=</span><span class="st">"class $+1$"</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> sv_mask <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span> <span class="kw">and</span> sv_mask.<span class="bu">any</span>():</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>        ax.scatter(<span class="op">*</span>X[sv_mask].T, s<span class="op">=</span>s <span class="op">*</span> <span class="fl">3.4</span>, facecolor<span class="op">=</span><span class="st">"none"</span>,</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>                   edgecolor<span class="op">=</span>INK, linewidth<span class="op">=</span><span class="fl">1.6</span>, zorder<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>                   label<span class="op">=</span><span class="st">"support vector"</span>)</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_hyperplane(ax, w, b, level<span class="op">=</span><span class="fl">0.0</span>, x1lim<span class="op">=</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">6</span>), <span class="op">**</span>kw):</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Draw the line w@x + b = level over the given x1 range."""</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>    w <span class="op">=</span> np.asarray(w, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>    x1 <span class="op">=</span> np.array(x1lim, dtype<span class="op">=</span><span class="bu">float</span>)</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">abs</span>(w[<span class="dv">1</span>]) <span class="op">&gt;</span> <span class="fl">1e-12</span>:</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>        ax.plot(x1, (level <span class="op">-</span> b <span class="op">-</span> w[<span class="dv">0</span>] <span class="op">*</span> x1) <span class="op">/</span> w[<span class="dv">1</span>], <span class="op">**</span>kw)</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:  <span class="co"># vertical line x1 = (level - b) / w1</span></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>        ax.axvline((level <span class="op">-</span> b) <span class="op">/</span> w[<span class="dv">0</span>], <span class="op">**</span>kw)</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_svm(ax, w, b, x1lim<span class="op">=</span>(<span class="op">-</span><span class="dv">1</span>, <span class="dv">6</span>)):</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Decision boundary plus the two margin lines w@x + b = ±1."""</span></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>    draw_hyperplane(ax, w, b, <span class="fl">0.0</span>, x1lim, color<span class="op">=</span>INK, lw<span class="op">=</span><span class="fl">2.0</span>,</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>                    label<span class="op">=</span><span class="vs">r"boundary $w^\top x + b = 0$"</span>)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> lv <span class="kw">in</span> (<span class="op">-</span><span class="fl">1.0</span>, <span class="fl">1.0</span>):</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>        draw_hyperplane(ax, w, b, lv, x1lim, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">1.4</span>, ls<span class="op">=</span><span class="st">"--"</span>,</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>                        label<span class="op">=</span><span class="vs">r"margin $w^\top x + b = \pm 1$"</span> <span class="cf">if</span> lv <span class="op">&gt;</span> <span class="dv">0</span> <span class="cf">else</span> <span class="va">None</span>)</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="co"># ---- Dataset A: linearly separable, chosen for clean numbers -----------------</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>X_A <span class="op">=</span> np.array([</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">1.0</span>, <span class="fl">1.0</span>], [<span class="fl">0.0</span>, <span class="fl">1.5</span>], [<span class="fl">1.5</span>, <span class="fl">0.0</span>], [<span class="fl">0.3</span>, <span class="fl">0.4</span>], [<span class="fl">1.2</span>, <span class="fl">0.2</span>],   <span class="co"># class -1</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">3.0</span>, <span class="fl">3.0</span>], [<span class="fl">2.8</span>, <span class="fl">3.4</span>], [<span class="fl">3.5</span>, <span class="fl">4.0</span>], [<span class="fl">4.0</span>, <span class="fl">2.5</span>], [<span class="fl">4.5</span>, <span class="fl">3.2</span>],   <span class="co"># class +1</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>y_A <span class="op">=</span> np.array([<span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>, <span class="op">+</span><span class="dv">1</span>, <span class="op">+</span><span class="dv">1</span>, <span class="op">+</span><span class="dv">1</span>, <span class="op">+</span><span class="dv">1</span>, <span class="op">+</span><span class="dv">1</span>])</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>n_A <span class="op">=</span> <span class="bu">len</span>(y_A)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="separating-the-data-does-not-pick-a-classifier" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="separating-the-data-does-not-pick-a-classifier"><span class="header-section-number">1</span> Separating the data does not pick a classifier</h2>
<p><strong>Dataset A</strong> is the paper sketch, typed in. Ten points in the plane, five per class, labels <span class="math inline">\(y_i \in \{-1, +1\}\)</span>, coordinates I chose by hand rather than measured from anything: the two classes sit in opposite corners with a visible corridor between them. It stands in for any two-class problem with two measurements per case — two blood markers, two sensor readings — where the classes happen not to overlap.</p>
<p>Making the data up is the point. With ten round numbers I know the answer before the solver runs: the two closest points across the corridor are <span class="math inline">\((1,1)\)</span> and <span class="math inline">\((3,3)\)</span>, so the best line has to be their perpendicular bisector. That turns every solver output below into a check rather than a claim, which no real dataset could offer, because on real data nobody knows the right answer to check against.</p>
<p>The simplest way to split a plane is to draw a straight line and call one side positive and the other negative. Written as a function of a point <span class="math inline">\(x\)</span>, that rule is</p>
<p><span class="math display">\[
f(x) = w^\top x + b,
\]</span></p>
<p>where <span class="math inline">\(w \in \mathbb{R}^2\)</span> points perpendicular to the line and <span class="math inline">\(b \in \mathbb{R}\)</span> slides it back and forth. We predict class <span class="math inline">\(+1\)</span> when <span class="math inline">\(f(x) &gt; 0\)</span> and class <span class="math inline">\(-1\)</span> when <span class="math inline">\(f(x) &lt; 0\)</span>, and the line itself — the set <span class="math inline">\(\{x : w^\top x + b = 0\}\)</span> where the rule is undecided — is the <strong>decision boundary</strong>. A rule of this shape is a <strong>linear classifier</strong>; everything in this post is about choosing its two parameters well.</p>
<p>A hyperplane <strong>separates</strong> the training data when every point lands on its own class’s side, which is captured in one inequality per point:</p>
<p><span class="math display">\[
y_i \left( w^\top x_i + b \right) &gt; 0, \qquad i = 1, \ldots, n.
\]</span></p>
<p>Multiplying by the label is a compact trick: for a <span class="math inline">\(+1\)</span> point it requires <span class="math inline">\(f(x_i) &gt; 0\)</span>, and for a <span class="math inline">\(-1\)</span> point it flips the inequality to require <span class="math inline">\(f(x_i) &lt; 0\)</span>. One formula, both cases.</p>
<p>And here is the trouble the paper sketch already hinted at: satisfying every one of those inequalities does not pick a line. Three hand-chosen candidates make it concrete. Each is checked numerically — the smallest <span class="math inline">\(y_i f(x_i)\)</span> over the ten points comes out strictly positive, so every point is on its own side — and then plotted. All three get 100% of the training data right. Which one should we prefer?</p>
<div id="cell-fig-many-separators" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Verify and plot three separating lines</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>candidates <span class="op">=</span> {</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">"(a)  $x_1 + x_2 = 4$"</span>:            (np.array([<span class="fl">1.0</span>, <span class="fl">1.0</span>]),  <span class="op">-</span><span class="fl">4.0</span>),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">"(b)  $2x_1 + x_2 = 6.5$"</span>:         (np.array([<span class="fl">2.0</span>, <span class="fl">1.0</span>]),  <span class="op">-</span><span class="fl">6.5</span>),</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"(c)  $0.3x_1 + x_2 = 2.8$"</span>:       (np.array([<span class="fl">0.3</span>, <span class="fl">1.0</span>]),  <span class="op">-</span><span class="fl">2.8</span>),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, (w_c, b_c) <span class="kw">in</span> candidates.items():</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    worst <span class="op">=</span> np.<span class="bu">min</span>(y_A <span class="op">*</span> (X_A <span class="op">@</span> w_c <span class="op">+</span> b_c))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> worst <span class="op">&gt;</span> <span class="dv">0</span>, <span class="ss">f"candidate </span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> does not separate the data"</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.5</span>, <span class="fl">5.6</span>))</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>scatter_classes(ax, X_A, y_A)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (name, (w_c, b_c)), ls <span class="kw">in</span> <span class="bu">zip</span>(candidates.items(), [<span class="st">"-"</span>, <span class="st">"--"</span>, <span class="st">"-."</span>]):</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    draw_hyperplane(ax, w_c, b_c, <span class="fl">0.0</span>, (<span class="op">-</span><span class="dv">1</span>, <span class="dv">6</span>), color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">1.8</span>, ls<span class="op">=</span>ls,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>                    label<span class="op">=</span>name)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="op">-</span><span class="fl">0.7</span>, <span class="fl">5.4</span>)<span class="op">;</span> ax.set_ylim(<span class="op">-</span><span class="fl">0.7</span>, <span class="fl">5.2</span>)<span class="op">;</span> ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"$x_1$"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"$x_2$"</span>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, loc<span class="op">=</span><span class="st">"upper left"</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.01</span>, <span class="fl">1.0</span>),</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>          fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Many hyperplanes separate the same data"</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-many-separators" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-many-separators-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-many-separators-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-many-separators-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Three different lines, each verified to classify all ten training points correctly. Training accuracy alone cannot choose between them — line (c) skims dangerously close to the orange class, yet separates the data just as ‘perfectly’ as the others.
</figcaption>
</figure>
</div>
</div>
</div>
<p>All three lines are <em>feasible</em>, but they are not equally trustworthy. Line (c) tilts until it almost grazes the orange point at <span class="math inline">\((4, 2.5)\)</span>, close enough that nudging that one observation would flip its predicted label. What your hand was doing on paper was avoiding exactly that: preferring the line with the most <strong>clearance</strong>, the widest empty corridor between it and the nearest data, whichever class the nearest data belongs to. The rest of the post makes that preference exact enough to optimize.</p>
</section>
<section id="clearance-is-a-number-so-it-can-be-maximized" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="clearance-is-a-number-so-it-can-be-maximized"><span class="header-section-number">2</span> Clearance is a number, so it can be maximized</h2>
<p>Preferring the roomiest line is only a preference until clearance has a definition and a formula. Two steps get there: measure how far a line sits from the data, then remove an ambiguity in how lines are written down that would otherwise make the measurement useless to a solver.</p>
<section id="the-margin-is-the-distance-to-the-closest-point" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="the-margin-is-the-distance-to-the-closest-point"><span class="header-section-number">2.1</span> The margin is the distance to the closest point</h3>
<p>Clearance has to become arithmetic before anything can maximize it, and the arithmetic is the perpendicular distance from a point <span class="math inline">\(x_i\)</span> to the line <span class="math inline">\(\{x : w^\top x + b = 0\}\)</span>. Since <span class="math inline">\(w\)</span> is normal to the line, projecting onto the unit normal <span class="math inline">\(w / \lVert w \rVert\)</span> gives</p>
<p><span class="math display">\[
\operatorname{dist}(x_i) \;=\; \frac{\left| w^\top x_i + b \right|}{\lVert w \rVert}.
\]</span></p>
<p>The numerator <span class="math inline">\(|f(x_i)|\)</span> on its own tells you how emphatically the rule votes, not how far away the point is: double <span class="math inline">\(w\)</span> and <span class="math inline">\(b\)</span> and it doubles, while the line has not moved. That raw score is the <strong>functional margin</strong>. Dividing by <span class="math inline">\(\lVert w \rVert\)</span> cancels the scaling and leaves a real distance in the plane, the <strong>geometric margin</strong>.</p>
<p>A line’s clearance is set by whichever point crowds it most, so define the <strong>margin of a separating hyperplane</strong> as its distance to the <em>closest</em> training point:</p>
<p><span class="math display">\[
\gamma(w, b) \;=\; \min_i \frac{y_i \left( w^\top x_i + b \right)}{\lVert w \rVert}.
\]</span></p>
<p>Now we can score the three candidate lines from <a href="#fig-many-separators" class="quarto-xref">Figure&nbsp;1</a> instead of merely checking feasibility:</p>
<div id="1c525afd" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Geometric margin of each candidate line</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, (w_c, b_c) <span class="kw">in</span> candidates.items():</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> y_A <span class="op">*</span> (X_A <span class="op">@</span> w_c <span class="op">+</span> b_c) <span class="op">/</span> np.linalg.norm(w_c)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    rows.append([name, <span class="ss">f"</span><span class="sc">{</span>d<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>                 <span class="ss">f"(</span><span class="sc">{</span>X_A[d.argmin()][<span class="dv">0</span>]<span class="sc">:g}</span><span class="ss">, </span><span class="sc">{</span>X_A[d.argmin()][<span class="dv">1</span>]<span class="sc">:g}</span><span class="ss">)"</span>])</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>md_table([<span class="st">"candidate line"</span>, <span class="st">"geometric margin $</span><span class="ch">\\</span><span class="st">gamma$ (distance)"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>          <span class="st">"closest training point"</span>], rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="3">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>candidate line</th>
<th>geometric margin <span class="math inline">\(\gamma\)</span> (distance)</th>
<th>closest training point</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(a) <span class="math inline">\(x_1 + x_2 = 4\)</span></td>
<td>1.414</td>
<td>(1, 1)</td>
</tr>
<tr class="even">
<td>(b) <span class="math inline">\(2x_1 + x_2 = 6.5\)</span></td>
<td>1.118</td>
<td>(3, 3)</td>
</tr>
<tr class="odd">
<td>(c) <span class="math inline">\(0.3x_1 + x_2 = 2.8\)</span></td>
<td>0.862</td>
<td>(4, 2.5)</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Line (a) keeps every point at least <span class="math inline">\(\sqrt{2} \approx 1.414\)</span> units away; line (c) manages barely <span class="math inline">\(0.86\)</span>, and the point doing the crowding is the orange one at <span class="math inline">\((4, 2.5)\)</span>. “Maximize the margin” now has a precise meaning: among all separating <span class="math inline">\((w, b)\)</span>, find the one with the largest <span class="math inline">\(\gamma\)</span>. Writing that down as something a solver will accept takes one more step.</p>
</section>
<section id="fixing-the-scale-turns-a-ratio-into-a-constraint" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="fixing-the-scale-turns-a-ratio-into-a-constraint"><span class="header-section-number">2.2</span> Fixing the scale turns a ratio into a constraint</h3>
<p>Scoring lines by <span class="math inline">\(\gamma\)</span> is easy; searching over all lines for the largest <span class="math inline">\(\gamma\)</span> is not, and the obstacle is in the notation rather than the geometry. The pairs <span class="math inline">\((w, b)\)</span> and <span class="math inline">\((cw, cb)\)</span> describe <strong>the same line</strong> for any <span class="math inline">\(c &gt; 0\)</span> — every functional margin gets multiplied by <span class="math inline">\(c\)</span>, but the geometric margin <span class="math inline">\(\gamma\)</span> is unchanged because the <span class="math inline">\(\lVert w \rVert\)</span> in the denominator absorbs it. So the parametrization is redundant, and “maximize <span class="math inline">\(\gamma\)</span>” as written is an awkward, non-smooth objective over a redundant space.</p>
<p>The classical fix is to spend the redundancy: <strong>rescale <span class="math inline">\((w, b)\)</span> so that the closest points have functional margin exactly 1.</strong> That is, impose the canonical constraints</p>
<p><span class="math display">\[
y_i \left( w^\top x_i + b \right) \ge 1, \qquad i = 1, \ldots, n,
\]</span></p>
<p>with equality holding for the nearest point(s). Under this convention the nearest points sit at geometric distance</p>
<p><span class="math display">\[
\frac{y_i \left( w^\top x_i + b \right)}{\lVert w \rVert} = \frac{1}{\lVert w \rVert}
\]</span></p>
<p>from the boundary. Two distinct quantities follow, and it pays to keep them straight:</p>
<ul>
<li>the <strong>one-sided geometric margin</strong> — boundary to the nearest point on either side: <span class="math inline">\(1 / \lVert w \rVert\)</span>;</li>
<li>the <strong>full margin width</strong> — the whole empty band from the margin line <span class="math inline">\(w^\top x + b = -1\)</span> across to <span class="math inline">\(w^\top x + b = +1\)</span>: <span class="math inline">\(2 / \lVert w \rVert\)</span>.</li>
</ul>
<p>When people say “the margin” they usually mean the band width <span class="math inline">\(2/\lVert w \rVert\)</span>, but plots of “the margin lines” show the two one-sided boundaries. Both appear in the figures below. With the scale nailed down, the objective simplifies into something a solver recognizes.</p>
</section>
</section>
<section id="maximizing-the-margin-is-minimizing-a-length" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="maximizing-the-margin-is-minimizing-a-length"><span class="header-section-number">3</span> Maximizing the margin is minimizing a length</h2>
<p>Under canonical scaling, maximizing the margin <span class="math inline">\(1 / \lVert w \rVert\)</span> is the same as minimizing <span class="math inline">\(\lVert w \rVert\)</span>, and minimizing <span class="math inline">\(\lVert w \rVert\)</span> is the same as minimizing the smooth, differentiable quantity <span class="math inline">\(\tfrac12 \lVert w \rVert^2\)</span> (the <span class="math inline">\(\tfrac12\)</span> just tidies derivatives). That gives the <strong>hard-margin SVM primal</strong>:</p>
<p><span class="math display">\[
\begin{aligned}
\min_{w, b} \quad &amp; \tfrac{1}{2} \lVert w \rVert^2 \\
\text{subject to} \quad &amp; y_i \left( w^\top x_i + b \right) \ge 1, \qquad i = 1, \ldots, n.
\end{aligned}
\]</span></p>
<p>In words: <em>among all hyperplanes that classify every training point correctly with functional margin at least 1, pick the one whose normal vector is shortest — equivalently, whose geometric margin <span class="math inline">\(1/\lVert w \rVert\)</span> is widest.</em> The constraints do the separating; the objective does the margin-maximizing.</p>
<section id="the-solver-recovers-the-line-you-can-read-off-the-plot" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="the-solver-recovers-the-line-you-can-read-off-the-plot"><span class="header-section-number">3.1</span> The solver recovers the line you can read off the plot</h3>
<p>Dataset A was invented so the answer is knowable in advance, and this is where that pays off. The closest pair of points across the class gap is <span class="math inline">\((1,1)\)</span> and <span class="math inline">\((3,3)\)</span>, so the widest corridor must be centred on their perpendicular bisector <span class="math inline">\(x_1 + x_2 = 4\)</span> — candidate (a) from earlier — giving <span class="math inline">\(w^\star = (0.5,\, 0.5)\)</span>, <span class="math inline">\(b^\star = -2\)</span>, and margin width <span class="math inline">\(2/\lVert w^\star \rVert = 2\sqrt{2}\)</span>.</p>
<p>Handed to CVXPY, the problem above is a quadratic program: a quadratic objective over linear constraints, the easiest interesting shape in convex optimization. The solve below <strong>asserts</strong> that the solver reproduces those hand-derived numbers, so the post cannot render with figures that contradict its own prose.</p>
<div id="6bd33444" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Hard-margin QP in CVXPY, with assertions against the analytic solution</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> cp.Variable(<span class="dv">2</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> cp.Variable()</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>margin_cons <span class="op">=</span> [cp.multiply(y_A, X_A <span class="op">@</span> w <span class="op">+</span> b) <span class="op">&gt;=</span> <span class="dv">1</span>]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>hard <span class="op">=</span> cp.Problem(cp.Minimize(<span class="fl">0.5</span> <span class="op">*</span> cp.sum_squares(w)), margin_cons)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>hard.solve(solver<span class="op">=</span>cp.CLARABEL)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>w_hard, b_hard <span class="op">=</span> w.value, b.value</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>alpha_hard <span class="op">=</span> margin_cons[<span class="dv">0</span>].dual_value        <span class="co"># Lagrange multipliers (used later)</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>func_margins <span class="op">=</span> y_A <span class="op">*</span> (X_A <span class="op">@</span> w_hard <span class="op">+</span> b_hard)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>sv_mask_hard <span class="op">=</span> np.isclose(func_margins, <span class="fl">1.0</span>, atol<span class="op">=</span><span class="fl">1e-4</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>width_hard <span class="op">=</span> <span class="dv">2</span> <span class="op">/</span> np.linalg.norm(w_hard)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> hard.status <span class="op">==</span> <span class="st">"optimal"</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(w_hard, [<span class="fl">0.5</span>, <span class="fl">0.5</span>], atol<span class="op">=</span><span class="fl">1e-5</span>), w_hard</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">abs</span>(b_hard <span class="op">-</span> (<span class="op">-</span><span class="fl">2.0</span>)) <span class="op">&lt;</span> <span class="fl">1e-5</span>, b_hard</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> func_margins.<span class="bu">min</span>() <span class="op">&gt;=</span> <span class="dv">1</span> <span class="op">-</span> TOL           <span class="co"># all constraints satisfied</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> sv_mask_hard.<span class="bu">sum</span>() <span class="op">==</span> <span class="dv">2</span>                 <span class="co"># exactly (1,1) and (3,3)</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"solver status   : </span><span class="sc">{</span>hard<span class="sc">.</span>status<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"w* = (</span><span class="sc">{</span>w_hard[<span class="dv">0</span>]<span class="sc">:.6f}</span><span class="ss">, </span><span class="sc">{</span>w_hard[<span class="dv">1</span>]<span class="sc">:.6f}</span><span class="ss">),  b* = </span><span class="sc">{</span>b_hard<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"decision boundary: </span><span class="sc">{</span>w_hard[<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">·x1 + </span><span class="sc">{</span>w_hard[<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">·x2 "</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"+ </span><span class="sc">{</span>b_hard<span class="sc">:.3f}</span><span class="ss"> = 0   (i.e. x1 + x2 = 4)"</span>)</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"one-sided margin : 1/||w|| = </span><span class="sc">{</span><span class="dv">1</span><span class="op">/</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(w_hard)<span class="sc">:.6f}</span><span class="ss">  (= √2)"</span>)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"full margin width: 2/||w|| = </span><span class="sc">{</span>width_hard<span class="sc">:.6f}</span><span class="ss">  (= 2√2)"</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"support vectors  : </span><span class="sc">{</span>[<span class="bu">tuple</span>(p) <span class="cf">for</span> p <span class="kw">in</span> X_A[sv_mask_hard]]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"min_i y_i(w·x_i+b) = </span><span class="sc">{</span>func_margins<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.8f}</span><span class="ss">  (≥ 1 − </span><span class="sc">{</span>TOL<span class="sc">:g}</span><span class="ss"> ✓)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>solver status   : optimal
w* = (0.500000, 0.500000),  b* = -2.000000
decision boundary: 0.500·x1 + 0.500·x2 + -2.000 = 0   (i.e. x1 + x2 = 4)
one-sided margin : 1/||w|| = 1.414214  (= √2)
full margin width: 2/||w|| = 2.828427  (= 2√2)
support vectors  : [(np.float64(1.0), np.float64(1.0)), (np.float64(3.0), np.float64(3.0))]
min_i y_i(w·x_i+b) = 1.00000000  (≥ 1 − 1e-06 ✓)</code></pre>
</div>
</div>
<p>The solver recovers the hand-derived solution to six decimal places. Going point by point makes the geometry concrete. Under canonical scaling, a point with <span class="math inline">\(y_i f(x_i) = 1\)</span> is touching the edge of the corridor — it is one of the points holding the band open, and points that do this are called <strong>support vectors</strong>. Anything above 1 sits strictly outside the band, contributing nothing:</p>
<div id="7576458b" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Per-point constraint check</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_A):</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    rows.append([</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"(</span><span class="sc">{</span>X_A[i,<span class="dv">0</span>]<span class="sc">:g}</span><span class="ss">, </span><span class="sc">{</span>X_A[i,<span class="dv">1</span>]<span class="sc">:g}</span><span class="ss">)"</span>, <span class="ss">f"</span><span class="sc">{</span>y_A[i]<span class="sc">:+d}</span><span class="ss">"</span>,</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>func_margins[i]<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>func_margins[i]<span class="op">/</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(w_hard)<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"**support vector**"</span> <span class="cf">if</span> sv_mask_hard[i] <span class="cf">else</span> <span class="st">"interior"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>md_table([<span class="st">"$x_i$"</span>, <span class="st">"$y_i$"</span>, <span class="st">"$y_i(w^</span><span class="ch">\\</span><span class="st">top x_i + b)$"</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>          <span class="st">"distance to boundary"</span>, <span class="st">"role"</span>], rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="5">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th><span class="math inline">\(x_i\)</span></th>
<th><span class="math inline">\(y_i\)</span></th>
<th><span class="math inline">\(y_i(w^\top x_i + b)\)</span></th>
<th>distance to boundary</th>
<th>role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(1, 1)</td>
<td>-1</td>
<td>1.0000</td>
<td>1.4142</td>
<td><strong>support vector</strong></td>
</tr>
<tr class="even">
<td>(0, 1.5)</td>
<td>-1</td>
<td>1.2500</td>
<td>1.7678</td>
<td>interior</td>
</tr>
<tr class="odd">
<td>(1.5, 0)</td>
<td>-1</td>
<td>1.2500</td>
<td>1.7678</td>
<td>interior</td>
</tr>
<tr class="even">
<td>(0.3, 0.4)</td>
<td>-1</td>
<td>1.6500</td>
<td>2.3335</td>
<td>interior</td>
</tr>
<tr class="odd">
<td>(1.2, 0.2)</td>
<td>-1</td>
<td>1.3000</td>
<td>1.8385</td>
<td>interior</td>
</tr>
<tr class="even">
<td>(3, 3)</td>
<td>+1</td>
<td>1.0000</td>
<td>1.4142</td>
<td><strong>support vector</strong></td>
</tr>
<tr class="odd">
<td>(2.8, 3.4)</td>
<td>+1</td>
<td>1.1000</td>
<td>1.5556</td>
<td>interior</td>
</tr>
<tr class="even">
<td>(3.5, 4)</td>
<td>+1</td>
<td>1.7500</td>
<td>2.4749</td>
<td>interior</td>
</tr>
<tr class="odd">
<td>(4, 2.5)</td>
<td>+1</td>
<td>1.2500</td>
<td>1.7678</td>
<td>interior</td>
</tr>
<tr class="even">
<td>(4.5, 3.2)</td>
<td>+1</td>
<td>1.8500</td>
<td>2.6163</td>
<td>interior</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Only two points touch <span class="math inline">\(y_i f(x_i) = 1\)</span>; the other eight constraints have room to spare, or are <em>inactive</em>. Delete any of those eight and re-solve and the answer would not move at all. Everything the fit remembers about ten points is stored in two of them.</p>
<div id="cell-fig-hard-solution" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Plot the hard-margin solution</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.5</span>, <span class="fl">5.8</span>))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>scatter_classes(ax, X_A, y_A, sv_mask<span class="op">=</span>sv_mask_hard)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>draw_svm(ax, w_hard, b_hard)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co"># perpendicular distance arrows from each support vector to the boundary</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>u <span class="op">=</span> w_hard <span class="op">/</span> np.linalg.norm(w_hard)          <span class="co"># unit normal</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sv, sign <span class="kw">in</span> <span class="bu">zip</span>(X_A[sv_mask_hard], (<span class="op">-</span><span class="dv">1</span>, <span class="op">+</span><span class="dv">1</span>)):</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    foot <span class="op">=</span> sv <span class="op">-</span> (w_hard <span class="op">@</span> sv <span class="op">+</span> b_hard) <span class="op">/</span> np.linalg.norm(w_hard) <span class="op">*</span> u</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    ax.annotate(<span class="st">""</span>, xy<span class="op">=</span>foot, xytext<span class="op">=</span>sv,</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>                arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"&lt;-&gt;"</span>, color<span class="op">=</span>INK, lw<span class="op">=</span><span class="fl">1.2</span>))</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="vs">r"$\frac</span><span class="sc">{1}</span><span class="vs">{\Vert w\Vert}=\sqrt</span><span class="sc">{2}</span><span class="vs">$ each side"</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>            xy<span class="op">=</span>(<span class="fl">2.0</span>, <span class="fl">2.0</span>), xytext<span class="op">=</span>(<span class="fl">2.7</span>, <span class="fl">0.6</span>), fontsize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>            arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span>MUTED))</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="op">-</span><span class="fl">0.7</span>, <span class="fl">5.4</span>)<span class="op">;</span> ax.set_ylim(<span class="op">-</span><span class="fl">0.7</span>, <span class="fl">5.2</span>)<span class="op">;</span> ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"$x_1$"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"$x_2$"</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, loc<span class="op">=</span><span class="st">"upper left"</span>, bbox_to_anchor<span class="op">=</span>(<span class="fl">1.01</span>, <span class="fl">1.0</span>),</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>          fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="vs">r"Hard-margin SVM: full band width $2/\Vert w\Vert = 2\sqrt</span><span class="sc">{2}</span><span class="vs">$"</span>)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-hard-solution" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hard-solution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hard-solution-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hard-solution-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The maximum-margin solution for Dataset A: boundary <span class="math inline">\(x_1+x_2=4\)</span> (solid), margin lines <span class="math inline">\(w^\top x + b = \pm 1\)</span> (dashed), support vectors ringed in black. Each support vector sits exactly <span class="math inline">\(1/\lVert w\rVert = \sqrt{2}\)</span> from the boundary; the full band is <span class="math inline">\(2\sqrt{2} \approx 2.83\)</span> wide.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="each-data-point-becomes-a-half-space-and-that-is-what-makes-this-easy" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="each-data-point-becomes-a-half-space-and-that-is-what-makes-this-easy"><span class="header-section-number">4</span> Each data point becomes a half-space, and that is what makes this easy</h2>
<p>The solver found the right line in milliseconds and certified it. Neither of those is luck; both come from the shape of the problem, and the word for that shape is convex.</p>
<p>Two plain pictures carry it. A <em>set</em> is convex when the straight segment between any two of its members stays entirely inside it — a disc is, a crescent is not. A <em>function</em> is convex when its graph bows upward, so a chord drawn between two points on it never dips below the graph — a bowl, not a mountain range with valleys between peaks. Minimizing a bowl-shaped function over a disc-shaped set is convex optimization, and the hard-margin problem is exactly that: a <strong>convex quadratic program</strong>. Each ingredient is worth naming.</p>
<ul>
<li><strong>The objective is convex.</strong> <span class="math inline">\(\tfrac12\lVert w \rVert^2 = \tfrac12(w_1^2 + w_2^2)\)</span> is a paraboloid, a bowl with a single lowest point. Its matrix of second derivatives is the identity, which curves upward in every direction, so the bowl has no flat floor — it is <em>strictly</em> convex <strong>in <span class="math inline">\(w\)</span></strong>. (Note <span class="math inline">\(b\)</span> does not appear in the objective at all; as a function of the joint variable <span class="math inline">\((w, b)\)</span> the objective is convex but not strictly convex. This detail matters for uniqueness, below.)</li>
<li><strong>Each constraint is a half-space <em>in parameter space</em>.</strong> Stop thinking of <span class="math inline">\((x_i, y_i)\)</span> as a point to be classified and think of it as a rule about the unknowns. For fixed data, <span class="math inline">\(\{(w, b) : y_i(w^\top x_i + b) \ge 1\}\)</span> is one linear inequality in <span class="math inline">\((w, b)\)</span>, which carves <span class="math inline">\(\mathbb{R}^3\)</span> into a “yes” side and a “no” side — a half-space. This perspective flip is what makes SVMs tractable: each <em>data point</em> becomes a <em>linear constraint</em> on the parameters.</li>
<li><strong>The feasible region is convex.</strong> Overlap any number of half-spaces and what survives is a flat-sided solid, a polyhedron, and a solid like that always contains the segment between any two of its points.</li>
</ul>
<p>To <em>draw</em> that feasible set takes one small maneuver: the full region lives in <span class="math inline">\((w_1, w_2, b)\)</span>-space, and slicing it at the optimal <span class="math inline">\(b^\star\)</span> is useless — at the optimum the two support-vector constraints are tight, so that slice degenerates to a line segment with no area to shade. Instead we <strong>eliminate <span class="math inline">\(b\)</span></strong>: a given <span class="math inline">\(w\)</span> admits <em>some</em> feasible intercept exactly when <span class="math inline">\(\max_{i \in +} (1 - w^\top x_i) \le \min_{j \in -} (-1 - w^\top x_j)\)</span>, i.e.&nbsp;when</p>
<p><span class="math display">\[
w^\top (x_i - x_j) \ge 2 \qquad \text{for every cross-class pair } (i \in +,\ j \in -),
\]</span></p>
<p>which is again an intersection of half-planes — now purely in <span class="math inline">\((w_1, w_2)\)</span>, so we can plot it, along with the circular level sets of <span class="math inline">\(\tfrac12\lVert w\rVert^2\)</span> and the optimum where the smallest circle touches the region.</p>
<div id="cell-fig-parameter-space" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Feasible region in (w1, w2) after eliminating b</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">0.15</span>, <span class="fl">1.25</span>, <span class="dv">500</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>W1, W2 <span class="op">=</span> np.meshgrid(g, g)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>feasible <span class="op">=</span> np.ones_like(W1, dtype<span class="op">=</span><span class="bu">bool</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> xp <span class="kw">in</span> X_A[y_A <span class="op">&gt;</span> <span class="dv">0</span>]:</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> xn <span class="kw">in</span> X_A[y_A <span class="op">&lt;</span> <span class="dv">0</span>]:</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>        d <span class="op">=</span> xp <span class="op">-</span> xn</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>        feasible <span class="op">&amp;=</span> (W1 <span class="op">*</span> d[<span class="dv">0</span>] <span class="op">+</span> W2 <span class="op">*</span> d[<span class="dv">1</span>]) <span class="op">&gt;=</span> <span class="dv">2</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.8</span>, <span class="fl">6.2</span>))</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>ax.contourf(W1, W2, feasible.astype(<span class="bu">float</span>), levels<span class="op">=</span>[<span class="fl">0.5</span>, <span class="fl">1.5</span>],</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>            colors<span class="op">=</span>[<span class="st">"#2a78d633"</span>])</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>ax.contour(W1, W2, feasible.astype(<span class="bu">float</span>), levels<span class="op">=</span>[<span class="fl">0.5</span>],</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>           colors<span class="op">=</span>[BLUE], linewidths<span class="op">=</span><span class="fl">1.4</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>R <span class="op">=</span> np.sqrt(W1<span class="op">**</span><span class="dv">2</span> <span class="op">+</span> W2<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>cs <span class="op">=</span> ax.contour(W1, W2, <span class="fl">0.5</span> <span class="op">*</span> R<span class="op">**</span><span class="dv">2</span>, levels<span class="op">=</span>[<span class="fl">0.0625</span>, <span class="fl">0.125</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.9</span>],</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>                colors<span class="op">=</span>[MUTED], linewidths<span class="op">=</span><span class="fl">0.9</span>, linestyles<span class="op">=</span><span class="st">":"</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>ax.clabel(cs, fmt<span class="op">=</span><span class="kw">lambda</span> v: <span class="vs">rf"$\frac</span><span class="ch">{{</span><span class="vs">1</span><span class="ch">}}{{</span><span class="vs">2</span><span class="ch">}}</span><span class="vs">\|w\|^2$=</span><span class="sc">{</span>v<span class="sc">:g}</span><span class="vs">"</span>, fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>ax.scatter([w_hard[<span class="dv">0</span>]], [w_hard[<span class="dv">1</span>]], s<span class="op">=</span><span class="dv">90</span>, c<span class="op">=</span>INK, zorder<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="vs">r"$w^\star = (0.5,\ 0.5)$"</span>, xy<span class="op">=</span>w_hard, xytext<span class="op">=</span>(<span class="fl">0.60</span>, <span class="fl">0.34</span>),</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>            fontsize<span class="op">=</span><span class="dv">11</span>, arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span>INK))</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">"feasible: some $b$ satisfies</span><span class="ch">\n</span><span class="st">every margin constraint"</span>,</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>            xy<span class="op">=</span>(<span class="fl">0.82</span>, <span class="fl">0.95</span>), fontsize<span class="op">=</span><span class="dv">9</span>, color<span class="op">=</span>INK, ha<span class="op">=</span><span class="st">"center"</span>)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"$w_1$"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"$w_2$"</span>)<span class="op">;</span> ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Smallest norm ball touching the feasible region"</span>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-parameter-space" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-parameter-space-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-parameter-space-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-parameter-space-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The QP in parameter space with the intercept eliminated: each cross-class pair of training points imposes the half-plane <span class="math inline">\(w^\top(x_i - x_j) \ge 2\)</span> on <span class="math inline">\((w_1, w_2)\)</span>; their intersection is the shaded feasible region. The objective’s circular level sets shrink toward the origin, and <span class="math inline">\(w^\star = (0.5, 0.5)\)</span> is the point of the feasible region closest to the origin — its active edge is generated by the support-vector pair <span class="math inline">\((3,3)\)</span> and <span class="math inline">\((1,1)\)</span>.
</figcaption>
</figure>
</div>
</div>
</div>
<section id="convexity-buys-a-global-answer-and-a-certificate" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="convexity-buys-a-global-answer-and-a-certificate"><span class="header-section-number">4.1</span> Convexity buys a global answer and a certificate</h3>
<p>That picture — the shrinking circle settling against the corner of a flat-sided region — is why the fit is dependable. Three guarantees follow from it, and together they explain why nobody trains an SVM with random restarts the way they would a neural network.</p>
<ul>
<li><strong>Every local optimum is a global optimum.</strong> A convex landscape has no false bottoms: if no feasible descent direction exists at a point, no better feasible point exists anywhere.</li>
<li><strong>Solvers can <em>target</em> the global optimum</strong>, not just a stationary point, and can certify optimality via duality — a lower bound that meets the value found, leaving no room for anything better. CLARABEL, the solver used above, works toward the answer from strictly inside the feasible region (an <em>interior-point</em> method) and reports <code>optimal</code>: a certificate, not a hope.</li>
<li><strong>There are no distinct “bad local minima”</strong> to escape, so no restarts, annealing, or initialization tricks are needed.</li>
</ul>
</section>
<section id="convexity-does-not-buy-feasibility-or-a-single-answer" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="convexity-does-not-buy-feasibility-or-a-single-answer"><span class="header-section-number">4.2</span> Convexity does not buy feasibility or a single answer</h3>
<p>Those guarantees are narrower than they sound, and it is worth being blunt about the gaps, because all three bite somewhere in this post.</p>
<ul>
<li><strong>Feasibility.</strong> If no hyperplane separates the data, the constraint set is <em>empty</em> and the hard-margin problem has no solution at all. (We will hit this in <a href="#sec-soft" class="quarto-xref">Section&nbsp;7</a> — the solver honestly reports <code>infeasible</code>.)</li>
<li><strong>Uniqueness of the optimizer.</strong> Convexity guarantees the set of optima is convex, not that it is a single point. Extra conditions are needed.</li>
<li><strong>Numerical immunity.</strong> Finite-precision solvers return answers to a tolerance (note the <code>1e-6</code> and <code>1e-4</code> tolerances used throughout this post); badly conditioned or nearly degenerate problems can stress them.</li>
</ul>
<p>The second gap deserves precision rather than a shrug, because the two parameters are in genuinely different situations: the objective is strictly convex in <span class="math inline">\(w\)</span>, <em>but <span class="math inline">\(b\)</span> never appears in it at all</em>.</p>
<ul>
<li><strong><span class="math inline">\(w^\star\)</span> is always unique</strong> (when the problem is feasible): if two optima had different <span class="math inline">\(w\)</span>’s, their midpoint would be feasible (convexity) with strictly smaller <span class="math inline">\(\tfrac12\lVert w\rVert^2\)</span> (strict convexity) — contradiction.</li>
<li><strong><span class="math inline">\(b^\star\)</span> requires an argument.</strong> Given <span class="math inline">\(w^\star\)</span>, the constraints pin <span class="math inline">\(b\)</span> into an interval <span class="math inline">\([\,b_{\text{lo}},\, b_{\text{hi}}\,]\)</span> where <span class="math inline">\(b_{\text{lo}}\)</span> comes from the <span class="math inline">\(+1\)</span> class and <span class="math inline">\(b_{\text{hi}}\)</span> from the <span class="math inline">\(-1\)</span> class. For a separable two-class problem this interval collapses to a point: if it had positive length, an interior <span class="math inline">\(b\)</span> would leave <em>every</em> constraint slack, and <span class="math inline">\((w, b)\)</span> could be scaled down to a feasible point with smaller norm — contradicting optimality of <span class="math inline">\(w^\star\)</span>. So the standard two-class hard-margin solution <span class="math inline">\((w^\star, b^\star)\)</span> — and hence <strong>the geometric boundary — is unique</strong>.</li>
<li><strong>Degenerate formulations can break this</strong>, as the next section shows with actual solves: <span class="math inline">\(b\)</span> (and even the existence of a boundary) can fail to be pinned down.</li>
</ul>
</section>
</section>
<section id="sec-unique" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="sec-unique"><span class="header-section-number">5</span> Uniqueness holds here, and it is easy to break</h2>
<p>That argument was made on paper, and paper arguments about degeneracy are exactly the ones worth testing against a solver. So take the two-class case first, where uniqueness should hold, then a formulation where it visibly fails.</p>
<section id="two-unrelated-algorithms-land-on-the-same-line" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="two-unrelated-algorithms-land-on-the-same-line"><span class="header-section-number">5.1</span> Two unrelated algorithms land on the same line</h3>
<p>An argument on paper is worth less than a solve, so put the uniqueness claim to work twice over. First compute the interval of intercepts compatible with <span class="math inline">\(w^\star\)</span> and watch it collapse to a point. Then re-solve the same problem with two algorithms that share almost no machinery: CLARABEL, which approaches from inside the feasible region, and OSQP, which takes cheap repeated steps toward it from wherever it starts. Genuine uniqueness means they cannot disagree.</p>
<div id="b34fe823" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>b-interval collapse + independent solvers agree</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>b_lo <span class="op">=</span> np.<span class="bu">max</span>(<span class="dv">1</span> <span class="op">-</span> X_A[y_A <span class="op">&gt;</span> <span class="dv">0</span>] <span class="op">@</span> w_hard)      <span class="co"># +1 class: b ≥ 1 − w·x</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>b_hi <span class="op">=</span> np.<span class="bu">min</span>(<span class="op">-</span><span class="dv">1</span> <span class="op">-</span> X_A[y_A <span class="op">&lt;</span> <span class="dv">0</span>] <span class="op">@</span> w_hard)     <span class="co"># −1 class: b ≤ −1 − w·x</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"b interval given w*: [</span><span class="sc">{</span>b_lo<span class="sc">:.6f}</span><span class="ss">, </span><span class="sc">{</span>b_hi<span class="sc">:.6f}</span><span class="ss">]  →  width "</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>b_hi <span class="op">-</span> b_lo<span class="sc">:.2e}</span><span class="ss"> (collapses to the point b* = −2)"</span>)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>hard.solve(solver<span class="op">=</span>cp.OSQP)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"OSQP     : w = (</span><span class="sc">{</span>w<span class="sc">.</span>value[<span class="dv">0</span>]<span class="sc">:.6f}</span><span class="ss">, </span><span class="sc">{</span>w<span class="sc">.</span>value[<span class="dv">1</span>]<span class="sc">:.6f}</span><span class="ss">), b = </span><span class="sc">{</span>b<span class="sc">.</span>value<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"CLARABEL : w = (</span><span class="sc">{</span>w_hard[<span class="dv">0</span>]<span class="sc">:.6f}</span><span class="ss">, </span><span class="sc">{</span>w_hard[<span class="dv">1</span>]<span class="sc">:.6f}</span><span class="ss">), b = </span><span class="sc">{</span>b_hard<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(w.value, w_hard, atol<span class="op">=</span><span class="fl">1e-3</span>) <span class="kw">and</span> <span class="bu">abs</span>(b.value <span class="op">-</span> b_hard) <span class="op">&lt;</span> <span class="fl">1e-3</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>hard.solve(solver<span class="op">=</span>cp.CLARABEL)   <span class="co"># restore the reference solution</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>b interval given w*: [-2.000000, -2.000000]  →  width 3.11e-10 (collapses to the point b* = −2)
OSQP     : w = (0.500000, 0.500000), b = -2.000000
CLARABEL : w = (0.500000, 0.500000), b = -2.000000</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>np.float64(0.25000000007783907)</code></pre>
</div>
</div>
<p>Two very different algorithms land on the same <span class="math inline">\((w^\star, b^\star)\)</span> — as they must, since the optimum is a single point. Take one class away, though, and that agreement evaporates.</p>
</section>
<section id="show-it-one-class-and-the-intercept-floats-free" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="show-it-one-class-and-the-intercept-floats-free"><span class="header-section-number">5.2</span> Show it one class and the intercept floats free</h3>
<p>Feed the same problem only the five <span class="math inline">\(+1\)</span> points and it stays a perfectly valid convex program, with nothing to warn you. But the constraints <span class="math inline">\(w^\top x_i + b \ge 1\)</span> can be satisfied with <span class="math inline">\(w = 0,\ b \ge 1\)</span>, which achieves the <em>unbeatable</em> objective value <span class="math inline">\(0\)</span>. The optimal set is the entire ray <span class="math inline">\(\{(0, b) : b \ge 1\}\)</span>:</p>
<ul>
<li><span class="math inline">\(w^\star = 0\)</span> <strong>is</strong> unique (strict convexity in <span class="math inline">\(w\)</span> still applies),</li>
<li><span class="math inline">\(b^\star\)</span> is <strong>wildly non-unique</strong> — any <span class="math inline">\(b \ge 1\)</span> is optimal,</li>
<li>and with <span class="math inline">\(w^\star = 0\)</span> there is <strong>no decision boundary at all</strong>: the “hyperplane” <span class="math inline">\(0^\top x + b = 0\)</span> is not a hyperplane.</li>
</ul>
<div id="a730a09d" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>One-class degenerate solve with two solvers</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>w1c, b1c <span class="op">=</span> cp.Variable(<span class="dv">2</span>), cp.Variable()</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>one_class <span class="op">=</span> cp.Problem(cp.Minimize(<span class="fl">0.5</span> <span class="op">*</span> cp.sum_squares(w1c)),</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>                       [X_A[y_A <span class="op">&gt;</span> <span class="dv">0</span>] <span class="op">@</span> w1c <span class="op">+</span> b1c <span class="op">&gt;=</span> <span class="dv">1</span>])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> solver <span class="kw">in</span> (cp.CLARABEL, cp.SCS):</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    one_class.solve(solver<span class="op">=</span>solver)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>solver<span class="sc">:&lt;9}</span><span class="ss">: status=</span><span class="sc">{</span>one_class<span class="sc">.</span>status<span class="sc">}</span><span class="ss">,  ||w|| = "</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(w1c.value)<span class="sc">:.2e}</span><span class="ss">,  b = </span><span class="sc">{</span>b1c<span class="sc">.</span>value<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> np.linalg.norm(w1c.value) <span class="op">&lt;</span> <span class="fl">1e-3</span>   <span class="co"># w* = 0 in both cases</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>CLARABEL : status=optimal,  ||w|| = 5.25e-10,  b = 3.0166
SCS      : status=optimal,  ||w|| = 4.87e-12,  b = 1.0000</code></pre>
</div>
</div>
<p>Both solvers agree that <span class="math inline">\(w^\star = 0\)</span>, but each returns whatever intercept its algorithm happened to stop at — both answers are equally “optimal” because the constraints never pin <span class="math inline">\(b\)</span> down. This is non-uniqueness of a <em>degenerate formulation</em>, honestly labeled: it is <strong>not</strong> evidence that ordinary two-class hard-margin SVMs have multiple solutions (they do not, as shown above). A cleaner and more practically relevant failure of uniqueness — an <em>interval</em> of equally optimal intercepts for a genuine two-class problem — appears once soft margins enter, in <a href="#sec-flat" class="quarto-xref">Section&nbsp;7.3</a>.</p>
<p><em>A caution about symmetry:</em> it is tempting to think a symmetric dataset must admit multiple maximum-margin hyperplanes. Usually the opposite is true — by uniqueness, the one optimal hyperplane must itself be invariant under any symmetry of the data (swap the classes of Dataset A’s support vectors across the corridor and the boundary <span class="math inline">\(x_1 + x_2 = 4\)</span> maps to itself). Symmetry constrains the unique solution; it does not multiply it.</p>
</section>
</section>
<section id="sec-dual" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-dual"><span class="header-section-number">6</span> Duality explains why eight of the ten points do not matter</h2>
<p>Uniqueness says the line is pinned down; it does not say what pins it. The per-point table hinted at the answer — two points touching, eight with room to spare — and duality turns that hint into arithmetic.</p>
<p>The idea is to put a price on each constraint. Instead of forbidding a point from crossing its margin, charge it whenever it does, and let the charge rise until nobody crosses. Every constraint gets its own price <span class="math inline">\(\alpha_i \ge 0\)</span>, and a constraint nobody is pushing against settles at a price of zero, exactly like a resource in surplus. Folding those prices into the objective gives one function of everything at once, the <strong>Lagrangian</strong></p>
<p><span class="math display">\[
\mathcal{L}(w, b, \alpha)
= \tfrac12 \lVert w \rVert^2
- \sum_{i} \alpha_i \left[ y_i \left( w^\top x_i + b \right) - 1 \right].
\]</span></p>
<p>At the optimum, nudging <span class="math inline">\(w\)</span> or <span class="math inline">\(b\)</span> can no longer improve this combined function, so its derivatives in those directions vanish. Setting them to zero gives the <strong>stationarity conditions</strong></p>
<p><span class="math display">\[
\frac{\partial \mathcal{L}}{\partial w} = 0
\;\;\Rightarrow\;\;
w = \sum_i \alpha_i y_i x_i,
\qquad\qquad
\frac{\partial \mathcal{L}}{\partial b} = 0
\;\;\Rightarrow\;\;
\sum_i \alpha_i y_i = 0.
\]</span></p>
<p>Two consequences, both checkable on our solved problem:</p>
<ol type="1">
<li><strong>The optimal <span class="math inline">\(w\)</span> is a weighted combination of data points.</strong> A constraint that is not binding cannot be worth paying for, and a price that is positive must be buying something — for each point, one of the two is zero. (That pairing has a name, <em>complementary slackness</em>: <span class="math inline">\(\alpha_i \cdot [\text{slack of constraint } i] = 0\)</span>.) So every point strictly outside the margin gets <span class="math inline">\(\alpha_i = 0\)</span>, and only points <em>on</em> the margin carry weight. That is why they <em>support</em> the hyperplane.</li>
<li><strong>The weights balance across classes</strong> (<span class="math inline">\(\sum_i \alpha_i y_i = 0\)</span>): the positive-class pull equals the negative-class pull, which is why the boundary settles in equilibrium between the classes.</li>
</ol>
<p>CVXPY hands back the optimal prices as the constraint’s <code>dual_value</code>, so both consequences can be checked rather than believed. Dataset A predicts them by hand too: with the weights balanced across the two classes, <span class="math inline">\(\alpha \cdot \big[(3,3)-(1,1)\big] = w^\star\)</span> gives <span class="math inline">\(\alpha = 0.25\)</span> on each support vector and <span class="math inline">\(0\)</span> everywhere else.</p>
<div id="5540f6ed" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Dual variables: support vectors carry all the weight</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [[<span class="ss">f"(</span><span class="sc">{</span>X_A[i,<span class="dv">0</span>]<span class="sc">:g}</span><span class="ss">, </span><span class="sc">{</span>X_A[i,<span class="dv">1</span>]<span class="sc">:g}</span><span class="ss">)"</span>, <span class="ss">f"</span><span class="sc">{</span>y_A[i]<span class="sc">:+d}</span><span class="ss">"</span>,</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>         <span class="ss">f"</span><span class="sc">{</span>alpha_hard[i]<span class="sc">:.6f}</span><span class="ss">"</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>         <span class="ss">f"</span><span class="sc">{</span>alpha_hard[i] <span class="op">*</span> (func_margins[i] <span class="op">-</span> <span class="dv">1</span>)<span class="sc">:.1e}</span><span class="ss">"</span>]</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_A)]</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>display(md_table([<span class="st">"$x_i$"</span>, <span class="st">"$y_i$"</span>, <span class="st">"$</span><span class="ch">\\</span><span class="st">alpha_i$"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"$</span><span class="ch">\\</span><span class="st">alpha_i</span><span class="ch">\\</span><span class="st">,[y_i f(x_i) - 1]$ (compl. slack)"</span>], rows))</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>w_from_alpha <span class="op">=</span> (alpha_hard <span class="op">*</span> y_A) <span class="op">@</span> X_A</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>dual_val <span class="op">=</span> alpha_hard.<span class="bu">sum</span>() <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> np.linalg.norm(w_from_alpha) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"stationarity  ||w* − Σαᵢyᵢxᵢ||  = "</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(w_hard <span class="op">-</span> w_from_alpha)<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"balance        Σαᵢyᵢ           = </span><span class="sc">{</span>(alpha_hard <span class="op">*</span> y_A)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:+.2e}</span><span class="ss">"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"strong duality: dual objective  = </span><span class="sc">{</span>dual_val<span class="sc">:.6f}</span><span class="ss"> "</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"vs primal ½||w*||² = </span><span class="sc">{</span><span class="fl">0.5</span><span class="op">*</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(w_hard)<span class="op">**</span><span class="dv">2</span><span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(alpha_hard[sv_mask_hard], <span class="fl">0.25</span>, atol<span class="op">=</span><span class="fl">1e-4</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.<span class="bu">all</span>(alpha_hard[<span class="op">~</span>sv_mask_hard] <span class="op">&lt;</span> <span class="fl">1e-6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(x_i\)</span></th>
<th><span class="math inline">\(y_i\)</span></th>
<th><span class="math inline">\(\alpha_i\)</span></th>
<th><span class="math inline">\(\alpha_i\,[y_i f(x_i) - 1]\)</span> (compl. slack)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(1, 1)</td>
<td>-1</td>
<td>0.250000</td>
<td>4.4e-11</td>
</tr>
<tr class="even">
<td>(0, 1.5)</td>
<td>-1</td>
<td>0.000000</td>
<td>2.8e-11</td>
</tr>
<tr class="odd">
<td>(1.5, 0)</td>
<td>-1</td>
<td>0.000000</td>
<td>4.4e-11</td>
</tr>
<tr class="even">
<td>(0.3, 0.4)</td>
<td>-1</td>
<td>0.000000</td>
<td>4.2e-11</td>
</tr>
<tr class="odd">
<td>(1.2, 0.2)</td>
<td>-1</td>
<td>0.000000</td>
<td>4.0e-11</td>
</tr>
<tr class="even">
<td>(3, 3)</td>
<td>+1</td>
<td>0.250000</td>
<td>3.4e-11</td>
</tr>
<tr class="odd">
<td>(2.8, 3.4)</td>
<td>+1</td>
<td>0.000000</td>
<td>5.7e-11</td>
</tr>
<tr class="even">
<td>(3.5, 4)</td>
<td>+1</td>
<td>0.000000</td>
<td>4.0e-11</td>
</tr>
<tr class="odd">
<td>(4, 2.5)</td>
<td>+1</td>
<td>0.000000</td>
<td>3.4e-11</td>
</tr>
<tr class="even">
<td>(4.5, 3.2)</td>
<td>+1</td>
<td>0.000000</td>
<td>3.8e-11</td>
</tr>
</tbody>
</table>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>stationarity  ||w* − Σαᵢyᵢxᵢ||  = 2.33e-10
balance        Σαᵢyᵢ           = -6.50e-11
strong duality: dual objective  = 0.250000 vs primal ½||w*||² = 0.250000</code></pre>
</div>
</div>
<p>Eight of ten points have <span class="math inline">\(\alpha_i = 0\)</span>: as far as the optimization is concerned, they might as well not exist. Substituting the stationarity conditions back into <span class="math inline">\(\mathcal{L}\)</span> yields the <strong>dual problem</strong></p>
<p><span class="math display">\[
\max_{\alpha \ge 0,\ \sum_i \alpha_i y_i = 0}
\;\; \sum_i \alpha_i - \tfrac12 \sum_{i,j} \alpha_i \alpha_j y_i y_j \, x_i^\top x_j,
\]</span></p>
<p>Its value, the <span class="math inline">\(0.25\)</span> printed above, matches the primal optimum exactly. The two problems close on the same number with no gap between them, which is what <em>strong duality</em> means and is not guaranteed in general — convexity is what earns it here. Notice too that the data enters the dual <strong>only through dot products <span class="math inline">\(x_i^\top x_j\)</span></strong>. That single observation is the doorway to kernel methods: swap the dot product for a kernel function and everything above survives unchanged. Linear geometry is enough for this post, so the door stays ajar.</p>
<p>Everything so far has assumed a corridor exists. Real data rarely offers one.</p>
</section>
<section id="sec-soft" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="sec-soft"><span class="header-section-number">7</span> When no line can separate, points buy their way across</h2>
<p><strong>Dataset B</strong> is the awkward case, and like Dataset A it is invented rather than collected. Two clusters of twenty points each are drawn from Gaussian distributions centred at <span class="math inline">\((1.4, 1.6)\)</span> and <span class="math inline">\((3.3, 3.1)\)</span> with a standard deviation of <span class="math inline">\(0.75\)</span>, close enough together that their tails overlap, from a fixed random seed so the figures never move. Then one point labelled <span class="math inline">\(-1\)</span> is planted at <span class="math inline">\((4.3, 3.7)\)</span>, deep inside the <span class="math inline">\(+1\)</span> cluster.</p>
<p>It stands in for the ordinary situation Dataset A skipped: two classes whose measurements genuinely overlap, plus one record that is either mislabelled at the source or a real case that behaves nothing like its peers. Simulating beats borrowing a real dataset here for the same reason as before — I know the outlier is planted and I know no straight line can ever place it correctly, so when the fit fails on it I can be sure that is the data’s fault and not the solver’s. Where this shape of problem is real, that one point is usually the expensive one: the misread patient, the fraudulent transaction that looks ordinary. Everything in the rest of this section is about how much you should bend a boundary to chase it.</p>
<p>Before any of that, an honest check that the machinery built so far genuinely breaks here. The constraint set is empty, and the solver says so rather than returning something plausible:</p>
<div id="9ea75440" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Dataset B + hard margin is infeasible on it</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(RNG_SEED)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>X_neg <span class="op">=</span> rng.normal(loc<span class="op">=</span>[<span class="fl">1.4</span>, <span class="fl">1.6</span>], scale<span class="op">=</span><span class="fl">0.75</span>, size<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">2</span>))</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>X_pos <span class="op">=</span> rng.normal(loc<span class="op">=</span>[<span class="fl">3.3</span>, <span class="fl">3.1</span>], scale<span class="op">=</span><span class="fl">0.75</span>, size<span class="op">=</span>(<span class="dv">20</span>, <span class="dv">2</span>))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>outlier <span class="op">=</span> np.array([[<span class="fl">4.3</span>, <span class="fl">3.7</span>]])                       <span class="co"># labeled −1, sits among +1</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>X_B <span class="op">=</span> np.vstack([X_neg, outlier, X_pos])</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>y_B <span class="op">=</span> np.array([<span class="op">-</span><span class="dv">1</span>] <span class="op">*</span> <span class="dv">21</span> <span class="op">+</span> [<span class="op">+</span><span class="dv">1</span>] <span class="op">*</span> <span class="dv">20</span>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>n_B <span class="op">=</span> <span class="bu">len</span>(y_B)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>wi, bi <span class="op">=</span> cp.Variable(<span class="dv">2</span>), cp.Variable()</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>infeas <span class="op">=</span> cp.Problem(cp.Minimize(<span class="fl">0.5</span> <span class="op">*</span> cp.sum_squares(wi)),</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>                    [cp.multiply(y_B, X_B <span class="op">@</span> wi <span class="op">+</span> bi) <span class="op">&gt;=</span> <span class="dv">1</span>])</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>infeas.solve(solver<span class="op">=</span>cp.CLARABEL)</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"hard margin on Dataset B: status = </span><span class="sc">{</span>infeas<span class="sc">.</span>status<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> infeas.status <span class="op">==</span> <span class="st">"infeasible"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>hard margin on Dataset B: status = infeasible</code></pre>
</div>
</div>
<section id="charging-for-violations-keeps-the-problem-convex" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="charging-for-violations-keeps-the-problem-convex"><span class="header-section-number">7.1</span> Charging for violations keeps the problem convex</h3>
<p>An infeasible problem has no answer to soften, so something in the statement has to give, and the constraints are the only candidate. The fix is to stop treating “stay outside the margin” as an absolute rule and start treating it as one you can break for a fee. Give each point a personal allowance <span class="math inline">\(\xi_i \ge 0\)</span> by which it may fall short of the margin, and charge <span class="math inline">\(C\)</span> per unit of allowance used, added straight to the thing being minimized. A point that behaves buys nothing; a point that misbehaves makes the objective worse in proportion to how badly. These allowances are the <strong>slack variables</strong>, and they turn the hard-margin problem into the soft-margin one:</p>
<p><span class="math display">\[
\begin{aligned}
\min_{w, b, \xi} \quad &amp; \tfrac12 \lVert w \rVert^2 + C \sum_i \xi_i \\
\text{subject to} \quad &amp; y_i \left( w^\top x_i + b \right) \ge 1 - \xi_i, \\
&amp; \xi_i \ge 0, \qquad i = 1, \ldots, n.
\end{aligned}
\]</span></p>
<p>Nothing about the earlier argument breaks: the objective gains a linear term, the constraints stay linear, so this is still a convex quadratic program with the same global-optimum guarantee. Better still, the allowances are self-reporting. No point buys more than it needs, so at the optimum <span class="math inline">\(\xi_i = \max\!\big(0,\, 1 - y_i f(x_i)\big)\)</span>, and reading off one number tells you where that point ended up:</p>
<ul>
<li><span class="math inline">\(\xi_i = 0\)</span>: correctly classified, on or outside the margin — the constraint needed no help;</li>
<li><span class="math inline">\(0 &lt; \xi_i \le 1\)</span>: correctly classified but <strong>inside</strong> the margin band;</li>
<li><span class="math inline">\(\xi_i &gt; 1\)</span>: <strong>misclassified</strong> (<span class="math inline">\(y_i f(x_i) &lt; 0\)</span>; at <span class="math inline">\(\xi_i = 1\)</span> the point sits exactly on the boundary).</li>
</ul>
<p><span class="math inline">\(C\)</span> is therefore an exchange rate between two things the fit wants and cannot both have: a wide corridor, and few points inside it. Nothing in the mathematics chooses it, so solve the same data at a low, a middling and a high price and watch what each one buys.</p>
<div id="ae2eca61" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Solve the soft-margin QP for three values of C</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> solve_soft(X, y, C, solver<span class="op">=</span>cp.CLARABEL):</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="bu">len</span>(y)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    w_, b_, xi_ <span class="op">=</span> cp.Variable(<span class="dv">2</span>), cp.Variable(), cp.Variable(n)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>    cons <span class="op">=</span> [cp.multiply(y, X <span class="op">@</span> w_ <span class="op">+</span> b_) <span class="op">&gt;=</span> <span class="dv">1</span> <span class="op">-</span> xi_, xi_ <span class="op">&gt;=</span> <span class="dv">0</span>]</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    prob <span class="op">=</span> cp.Problem(cp.Minimize(<span class="fl">0.5</span> <span class="op">*</span> cp.sum_squares(w_) <span class="op">+</span> C <span class="op">*</span> cp.<span class="bu">sum</span>(xi_)),</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                      cons)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    prob.solve(solver<span class="op">=</span>solver)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> prob.status <span class="op">==</span> <span class="st">"optimal"</span>, (C, prob.status)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">dict</span>(C<span class="op">=</span>C, w<span class="op">=</span>w_.value, b<span class="op">=</span>b_.value, xi<span class="op">=</span>np.maximum(xi_.value, <span class="dv">0</span>),</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>                alpha<span class="op">=</span>cons[<span class="dv">0</span>].dual_value, obj<span class="op">=</span>prob.value)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>C_values <span class="op">=</span> [<span class="fl">0.05</span>, <span class="fl">1.0</span>, <span class="fl">100.0</span>]</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>fits <span class="op">=</span> [solve_soft(X_B, y_B, C) <span class="cf">for</span> C <span class="kw">in</span> C_values]</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> f <span class="kw">in</span> fits:</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    fm <span class="op">=</span> y_B <span class="op">*</span> (X_B <span class="op">@</span> f[<span class="st">"w"</span>] <span class="op">+</span> f[<span class="st">"b"</span>])</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    n_violate <span class="op">=</span> <span class="bu">int</span>((f[<span class="st">"xi"</span>] <span class="op">&gt;</span> TOL).<span class="bu">sum</span>())          <span class="co"># ξ &gt; tol: inside margin or worse</span></span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    n_miscls <span class="op">=</span> <span class="bu">int</span>((fm <span class="op">&lt;</span> <span class="dv">0</span>).<span class="bu">sum</span>())                  <span class="co"># y·f(x) &lt; 0 (equivalently ξ &gt; 1)</span></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    n_sv <span class="op">=</span> <span class="bu">int</span>((f[<span class="st">"alpha"</span>] <span class="op">&gt;</span> <span class="fl">1e-5</span> <span class="op">*</span> f[<span class="st">"C"</span>]).<span class="bu">sum</span>())  <span class="co"># α &gt; tol: touching or violating</span></span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>    rows.append([<span class="ss">f"</span><span class="sc">{</span>f[<span class="st">'C'</span>]<span class="sc">:g}</span><span class="ss">"</span>,</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>                 <span class="ss">f"(</span><span class="sc">{</span>f[<span class="st">'w'</span>][<span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>f[<span class="st">'w'</span>][<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">)"</span>, <span class="ss">f"</span><span class="sc">{</span>f[<span class="st">'b'</span>]<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>                 <span class="ss">f"</span><span class="sc">{</span><span class="dv">2</span><span class="op">/</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(f[<span class="st">'w'</span>])<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a>                 <span class="ss">f"</span><span class="sc">{</span>f[<span class="st">'xi'</span>]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.3f}</span><span class="ss">"</span>, n_violate, n_miscls, n_sv])</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>md_table([<span class="st">"$C$"</span>, <span class="st">"$w$"</span>, <span class="st">"$b$"</span>, <span class="st">"margin width $2/</span><span class="ch">\\</span><span class="st">lVert w</span><span class="ch">\\</span><span class="st">rVert$"</span>,</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>          <span class="st">"$</span><span class="ch">\\</span><span class="st">sum_i </span><span class="ch">\\</span><span class="st">xi_i$"</span>, <span class="st">"margin violations ($</span><span class="ch">\\</span><span class="st">xi_i &gt; 10^{-6}$)"</span>,</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>          <span class="st">"misclassified ($y_if_i&lt;0$)"</span>, <span class="st">"SV-like points ($</span><span class="ch">\\</span><span class="st">alpha_i&gt;0$)"</span>], rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="12">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(C\)</span></th>
<th><span class="math inline">\(w\)</span></th>
<th><span class="math inline">\(b\)</span></th>
<th>margin width <span class="math inline">\(2/\lVert w\rVert\)</span></th>
<th><span class="math inline">\(\sum_i \xi_i\)</span></th>
<th>margin violations (<span class="math inline">\(\xi_i &gt; 10^{-6}\)</span>)</th>
<th>misclassified (<span class="math inline">\(y_if_i&lt;0\)</span>)</th>
<th>SV-like points (<span class="math inline">\(\alpha_i&gt;0\)</span>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0.05</td>
<td>(0.458, 0.552)</td>
<td>-2.437</td>
<td>2.789</td>
<td>13.089</td>
<td>22</td>
<td>2</td>
<td>24</td>
</tr>
<tr class="even">
<td>1</td>
<td>(0.809, 1.095)</td>
<td>-4.849</td>
<td>1.470</td>
<td>8.964</td>
<td>10</td>
<td>3</td>
<td>12</td>
</tr>
<tr class="odd">
<td>100</td>
<td>(0.868, 2.019)</td>
<td>-7.195</td>
<td>0.910</td>
<td>8.675</td>
<td>7</td>
<td>2</td>
<td>10</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Read the table down the <span class="math inline">\(C\)</span> column and the exchange rate is doing exactly what it charges for: the band narrows from <span class="math inline">\(2.79\)</span> to <span class="math inline">\(0.91\)</span> while total slack falls from <span class="math inline">\(13.09\)</span> to <span class="math inline">\(8.68\)</span>. Violations got expensive, so the fit bought fewer of them by shrinking the corridor. What it never buys is the outlier, which stays misclassified at every price — no straight line can rescue a <span class="math inline">\(-1\)</span> point sitting inside the <span class="math inline">\(+1\)</span> cluster, so past a certain <span class="math inline">\(C\)</span> the extra money goes on reshaping the boundary around a lost cause.</p>
<p>One honest caveat on terminology before the plots. In the soft-margin problem “support vector” is defined by the price a point carries, not by whether it lies exactly on the margin: points with <span class="math inline">\(0 &lt; \alpha_i &lt; C\)</span> sit on the margin with <span class="math inline">\(\xi_i = 0\)</span>, while points at the ceiling price <span class="math inline">\(\alpha_i = C\)</span> are <em>bound</em> support vectors that have paid to cross it (<span class="math inline">\(\xi_i &gt; 0\)</span>). The count above takes any <span class="math inline">\(\alpha_i &gt; 0\)</span>, within solver tolerance.</p>
<p>Splitting the middle fit by category shows how few points are in play at all:</p>
<div id="f132958e" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Per-point slack summary for the medium C = 1 fit</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>f1 <span class="op">=</span> fits[<span class="dv">1</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>fm1 <span class="op">=</span> y_B <span class="op">*</span> (X_B <span class="op">@</span> f1[<span class="st">"w"</span>] <span class="op">+</span> f1[<span class="st">"b"</span>])</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>kinds <span class="op">=</span> np.select(</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    [fm1 <span class="op">&lt;</span> <span class="dv">0</span>, f1[<span class="st">"xi"</span>] <span class="op">&gt;</span> TOL, f1[<span class="st">"alpha"</span>] <span class="op">&gt;</span> <span class="fl">1e-5</span>],</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"misclassified"</span>, <span class="st">"inside margin"</span>, <span class="st">"on margin"</span>], <span class="st">"outside margin"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [[k, <span class="bu">int</span>((kinds <span class="op">==</span> k).<span class="bu">sum</span>()),</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>         <span class="ss">f"</span><span class="sc">{</span>f1[<span class="st">'xi'</span>][kinds <span class="op">==</span> k]<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.3f}</span><span class="ss">"</span>]</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> k <span class="kw">in</span> [<span class="st">"outside margin"</span>, <span class="st">"on margin"</span>, <span class="st">"inside margin"</span>, <span class="st">"misclassified"</span>]]</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>md_table([<span class="st">"point status at $C=1$"</span>, <span class="st">"count"</span>, <span class="st">"total slack $</span><span class="ch">\\</span><span class="st">sum </span><span class="ch">\\</span><span class="st">xi_i$"</span>], rows)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="13">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th>point status at <span class="math inline">\(C=1\)</span></th>
<th>count</th>
<th>total slack <span class="math inline">\(\sum \xi_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>outside margin</td>
<td>29</td>
<td>0.000</td>
</tr>
<tr class="even">
<td>on margin</td>
<td>2</td>
<td>0.000</td>
</tr>
<tr class="odd">
<td>inside margin</td>
<td>7</td>
<td>2.711</td>
</tr>
<tr class="even">
<td>misclassified</td>
<td>3</td>
<td>6.252</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="raising-the-price-narrows-the-corridor-without-saving-the-outlier" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="raising-the-price-narrows-the-corridor-without-saving-the-outlier"><span class="header-section-number">7.2</span> Raising the price narrows the corridor without saving the outlier</h3>
<p>Counts in a table only go so far; the trade-off is a geometric one, and it is easier to believe when you can see the same twenty-one blue and twenty orange points under three different prices side by side. The axes are identical across the three panels, so the boundary and the width of the band can be compared directly by eye.</p>
<div id="cell-fig-c-sweep" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Side-by-side decision boundaries for the three C values</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="fl">12.6</span>, <span class="fl">4.6</span>), sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, f <span class="kw">in</span> <span class="bu">zip</span>(axes, fits):</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>    fm <span class="op">=</span> y_B <span class="op">*</span> (X_B <span class="op">@</span> f[<span class="st">"w"</span>] <span class="op">+</span> f[<span class="st">"b"</span>])</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>    sv_like <span class="op">=</span> f[<span class="st">"alpha"</span>] <span class="op">&gt;</span> <span class="fl">1e-5</span> <span class="op">*</span> f[<span class="st">"C"</span>]</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    miscls <span class="op">=</span> fm <span class="op">&lt;</span> <span class="dv">0</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    scatter_classes(ax, X_B, y_B, s<span class="op">=</span><span class="dv">42</span>, sv_mask<span class="op">=</span>sv_like)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    ax.scatter(<span class="op">*</span>X_B[miscls].T, s<span class="op">=</span><span class="dv">120</span>, marker<span class="op">=</span><span class="st">"x"</span>, c<span class="op">=</span>INK, lw<span class="op">=</span><span class="fl">1.8</span>, zorder<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>               label<span class="op">=</span><span class="st">"misclassified"</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>    draw_svm(ax, f[<span class="st">"w"</span>], f[<span class="st">"b"</span>], x1lim<span class="op">=</span>(<span class="op">-</span><span class="dv">2</span>, <span class="dv">7</span>))</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(<span class="op">-</span><span class="fl">0.6</span>, <span class="fl">5.6</span>)<span class="op">;</span> ax.set_ylim(<span class="op">-</span><span class="fl">0.6</span>, <span class="fl">5.4</span>)<span class="op">;</span> ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"$x_1$"</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="vs">rf"$C = </span><span class="sc">{</span>f[<span class="st">'C'</span>]<span class="sc">:g}</span><span class="vs">$  —  width $= "</span></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                 <span class="vs">rf"</span><span class="sc">{</span><span class="dv">2</span><span class="op">/</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(f[<span class="st">'w'</span>])<span class="sc">:.2f}</span><span class="vs">$"</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"$x_2$"</span>)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>handles, labels <span class="op">=</span> axes[<span class="dv">0</span>].get_legend_handles_labels()</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>fig.legend(handles, labels, frameon<span class="op">=</span><span class="va">False</span>, loc<span class="op">=</span><span class="st">"upper center"</span>,</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>           bbox_to_anchor<span class="op">=</span>(<span class="fl">0.5</span>, <span class="fl">1.0</span>), ncols<span class="op">=</span><span class="dv">6</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>plt.tight_layout(rect<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.92</span>])</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-c-sweep" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-c-sweep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-c-sweep-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-c-sweep-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: The same non-separable data under three violation prices. Small <span class="math inline">\(C\)</span> buys a wide corridor and tolerates several points inside it; large <span class="math inline">\(C\)</span> narrows the band to reduce slack. Ringed points have <span class="math inline">\(\alpha_i &gt; 0\)</span> (support-vector-like); black × marks misclassified points — the planted outlier at (4.3, 3.7) is lost at every <span class="math inline">\(C\)</span>. Axes are identical across panels.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Read the panels left to right:</p>
<ul>
<li><strong>Small <span class="math inline">\(C = 0.05\)</span>:</strong> violations are cheap, so the optimizer keeps <span class="math inline">\(\lVert w \rVert\)</span> small and the corridor wide, letting a handful of borderline points (and the outlier) sit inside or across it. Many points participate in the solution (<span class="math inline">\(\alpha_i &gt; 0\)</span>).</li>
<li><strong>Medium <span class="math inline">\(C = 1\)</span>:</strong> a balance — moderate margin, moderate slack.</li>
<li><strong>Large <span class="math inline">\(C = 100\)</span>:</strong> every unit of slack is expensive, so the boundary tightens against the training points and the margin band narrows sharply. The fit chases individual observations harder — including reshaping itself around an outlier it still cannot classify.</li>
</ul>
<p>Neither extreme is better in general, and the panels are not a ranking. A large <span class="math inline">\(C\)</span> tracks the training data more closely and inherits its noise; a small <span class="math inline">\(C\)</span> protects the corridor and may flatten structure that was real. Which one generalizes is a question about data you have not seen, so it is settled empirically — usually by cross-validation, deliberately out of scope for a geometric tour.</p>
<p>Softening the constraints also gives something back that the hard-margin problem had: it takes away the guarantee that the answer is a single line.</p>
</section>
<section id="sec-flat" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="sec-flat"><span class="header-section-number">7.3</span> Soft margins bring non-uniqueness back</h3>
<p><a href="#sec-unique" class="quarto-xref">Section&nbsp;5</a> promised a genuine two-class example where the <em>intercept</em> is non-unique, and the soft-margin problem supplies one. The reason is that the penalty can stop depending on <span class="math inline">\(b\)</span> altogether. Take the smallest interesting dataset: <span class="math inline">\(x_- = (-1, 0)\)</span> labelled <span class="math inline">\(-1\)</span>, <span class="math inline">\(x_+ = (+1, 0)\)</span> labelled <span class="math inline">\(+1\)</span>, and a low price <span class="math inline">\(C = 0.25\)</span>. Substituting the optimal slack from earlier turns the objective into</p>
<p><span class="math display">\[
\tfrac12 w_1^2 + C\big[\max(0, 1 - w_1 - b) + \max(0, 1 - w_1 + b)\big],
\]</span></p>
<p>where each <span class="math inline">\(\max(0, \cdot)\)</span> charges a point only once it is inside the margin and nothing at all when it is safely outside. A price below <span class="math inline">\(\tfrac12\)</span> is too cheap to push either point clear, so both charges are live. And when both are live, <span class="math inline">\(b\)</span> appears once with each sign and cancels exactly, leaving <span class="math inline">\(\tfrac12 w_1^2 + 2C(1 - w_1)\)</span> — an expression the intercept has vanished from.</p>
<p>What is left is minimized at <span class="math inline">\(w_1 = 2C = 0.5\)</span>. So <span class="math inline">\(w^\star = (0.5, 0)\)</span> is pinned, but <strong>every <span class="math inline">\(b \in [-0.5, +0.5]\)</span> scores the same objective value of <span class="math inline">\(0.375\)</span></strong>. Since the boundary sits at <span class="math inline">\(x_1 = -2b\)</span>, it can be placed anywhere between the two data points, endpoints included, and the optimizer has no preference at all:</p>
<div id="cell-fig-flat-b" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Flat-b demonstration: solver disagreement + objective scan</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>X_flat <span class="op">=</span> np.array([[<span class="op">-</span><span class="fl">1.0</span>, <span class="fl">0.0</span>], [<span class="fl">1.0</span>, <span class="fl">0.0</span>]])</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>y_flat <span class="op">=</span> np.array([<span class="op">-</span><span class="dv">1</span>, <span class="op">+</span><span class="dv">1</span>])</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>C_flat <span class="op">=</span> <span class="fl">0.25</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>sol_a <span class="op">=</span> solve_soft(X_flat, y_flat, C_flat, solver<span class="op">=</span>cp.CLARABEL)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>sol_b <span class="op">=</span> solve_soft(X_flat, y_flat, C_flat, solver<span class="op">=</span>cp.OSQP)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"CLARABEL: w = (</span><span class="sc">{</span>sol_a[<span class="st">'w'</span>][<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>sol_a[<span class="st">'w'</span>][<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">), "</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"b = </span><span class="sc">{</span>sol_a[<span class="st">'b'</span>]<span class="sc">:+.4f}</span><span class="ss">, objective = </span><span class="sc">{</span>sol_a[<span class="st">'obj'</span>]<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"OSQP    : w = (</span><span class="sc">{</span>sol_b[<span class="st">'w'</span>][<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">, </span><span class="sc">{</span>sol_b[<span class="st">'w'</span>][<span class="dv">1</span>]<span class="sc">:.4f}</span><span class="ss">), "</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"b = </span><span class="sc">{</span>sol_b[<span class="st">'b'</span>]<span class="sc">:+.4f}</span><span class="ss">, objective = </span><span class="sc">{</span>sol_b[<span class="st">'obj'</span>]<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">abs</span>(sol_a[<span class="st">"obj"</span>] <span class="op">-</span> sol_b[<span class="st">"obj"</span>]) <span class="op">&lt;</span> <span class="fl">1e-5</span>      <span class="co"># same optimal value...</span></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(sol_a[<span class="st">"w"</span>], sol_b[<span class="st">"w"</span>], atol<span class="op">=</span><span class="fl">1e-3</span>)  <span class="co"># ...same w*</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="co"># scan: freeze b, minimize over (w, ξ) — the floor of this curve is the optimal set</span></span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>b_grid <span class="op">=</span> np.linspace(<span class="op">-</span><span class="fl">1.2</span>, <span class="fl">1.2</span>, <span class="dv">97</span>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>obj_b <span class="op">=</span> []</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b_fix <span class="kw">in</span> b_grid:</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>    w_, xi_ <span class="op">=</span> cp.Variable(<span class="dv">2</span>), cp.Variable(<span class="dv">2</span>)</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> cp.Problem(</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>        cp.Minimize(<span class="fl">0.5</span> <span class="op">*</span> cp.sum_squares(w_) <span class="op">+</span> C_flat <span class="op">*</span> cp.<span class="bu">sum</span>(xi_)),</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>        [cp.multiply(y_flat, X_flat <span class="op">@</span> w_ <span class="op">+</span> b_fix) <span class="op">&gt;=</span> <span class="dv">1</span> <span class="op">-</span> xi_, xi_ <span class="op">&gt;=</span> <span class="dv">0</span>])</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>    p.solve(solver<span class="op">=</span>cp.CLARABEL)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a>    obj_b.append(p.value)</span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a>obj_b <span class="op">=</span> np.array(obj_b)</span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>flat <span class="op">=</span> np.<span class="bu">abs</span>(b_grid) <span class="op">&lt;=</span> <span class="fl">0.5</span></span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> obj_b[flat].<span class="bu">max</span>() <span class="op">-</span> obj_b[flat].<span class="bu">min</span>() <span class="op">&lt;</span> <span class="fl">1e-6</span>   <span class="co"># exactly flat inside</span></span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> obj_b[np.<span class="bu">abs</span>(b_grid) <span class="op">&gt;</span> <span class="fl">0.55</span>].<span class="bu">min</span>() <span class="op">&gt;</span> obj_b[flat].<span class="bu">max</span>() <span class="op">+</span> <span class="fl">1e-4</span></span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a>fig, (axL, axR) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">11.5</span>, <span class="fl">4.3</span>))</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a>axL.plot(b_grid, obj_b, color<span class="op">=</span>BLUE, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a>axL.axvspan(<span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>, color<span class="op">=</span><span class="st">"#2a78d61f"</span>, label<span class="op">=</span><span class="vs">r"optimal set of $b$"</span>)</span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sol, name, c <span class="kw">in</span> [(sol_a, <span class="st">"CLARABEL"</span>, INK), (sol_b, <span class="st">"OSQP"</span>, ORANGE)]:</span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>    axL.scatter([sol[<span class="st">"b"</span>]], [sol[<span class="st">"obj"</span>]], s<span class="op">=</span><span class="dv">70</span>, c<span class="op">=</span>c, zorder<span class="op">=</span><span class="dv">5</span>, label<span class="op">=</span>name)</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a>axL.set_xlabel(<span class="st">"intercept $b$ (frozen per solve)"</span>)</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>axL.set_ylabel(<span class="st">"optimal objective value"</span>)</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a>axL.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a>axL.set_title(<span class="vs">rf"Flat floor: every $b\in[-0.5,0.5]$ is optimal ($C=</span><span class="sc">{</span>C_flat<span class="sc">}</span><span class="vs">$)"</span>)</span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>scatter_classes(axR, X_flat, y_flat, s<span class="op">=</span><span class="dv">120</span>)</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> b_show <span class="kw">in</span> np.linspace(<span class="op">-</span><span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="dv">9</span>):</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>    axR.axvline(<span class="op">-</span><span class="dv">2</span> <span class="op">*</span> b_show, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">1.0</span>, alpha<span class="op">=</span><span class="fl">0.55</span>)</span>
<span id="cb21-42"><a href="#cb21-42" aria-hidden="true" tabindex="-1"></a>axR.axvline(<span class="dv">0</span>, color<span class="op">=</span>INK, lw<span class="op">=</span><span class="fl">1.6</span>, label<span class="op">=</span><span class="st">"equally optimal boundaries"</span>)</span>
<span id="cb21-43"><a href="#cb21-43" aria-hidden="true" tabindex="-1"></a>axR.set_xlim(<span class="op">-</span><span class="fl">2.2</span>, <span class="fl">2.2</span>)<span class="op">;</span> axR.set_ylim(<span class="op">-</span><span class="fl">1.4</span>, <span class="fl">1.4</span>)</span>
<span id="cb21-44"><a href="#cb21-44" aria-hidden="true" tabindex="-1"></a>axR.set_xlabel(<span class="st">"$x_1$"</span>)<span class="op">;</span> axR.set_ylabel(<span class="st">"$x_2$"</span>)</span>
<span id="cb21-45"><a href="#cb21-45" aria-hidden="true" tabindex="-1"></a>axR.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"upper left"</span>)</span>
<span id="cb21-46"><a href="#cb21-46" aria-hidden="true" tabindex="-1"></a>axR.set_title(<span class="st">"All of these lines minimize the soft-margin objective"</span>)</span>
<span id="cb21-47"><a href="#cb21-47" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb21-48"><a href="#cb21-48" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>CLARABEL: w = (0.5000, 0.0000), b = +0.0000, objective = 0.375000
OSQP    : w = (0.5000, 0.0000), b = -0.0000, objective = 0.375000</code></pre>
</div>
<div class="cell-output cell-output-display">
<div id="fig-flat-b" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-flat-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-flat-b-output-2.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-flat-b-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: A valid two-class case with a non-unique intercept. Left: the optimal objective as a function of <span class="math inline">\(b\)</span> (each dot is a full CVXPY solve with <span class="math inline">\(b\)</span> frozen) is exactly flat on <span class="math inline">\([-0.5, 0.5]\)</span>; two solvers pick different points on the flat floor. Right: the corresponding band of equally optimal decision boundaries — the normal vector is pinned, the position is not.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Be precise about <em>which</em> quantity came loose. The normal vector <span class="math inline">\(w^\star\)</span> is still unique, because strict convexity in <span class="math inline">\(w\)</span> never lets go. The optimal objective value is unique too, as it always is for a convex problem. What spreads out is the intercept, and with it the position of the boundary. Convexity promised that the set of optima would be convex — here a line segment in <span class="math inline">\((w, b)\)</span>-space — and never promised it would be one point.</p>
<p>None of that is a solver bug. The flat floor is a known property of soft-margin SVMs at small <span class="math inline">\(C\)</span>, analyzed by Burges and Crisp in <em>Uniqueness of the SVM Solution</em> (NeurIPS 1999), and two solvers stopping at two different places on the same floor is what it looks like from the outside.</p>
</section>
</section>
<section id="two-independent-code-paths-land-on-the-same-hyperplane" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="two-independent-code-paths-land-on-the-same-hyperplane"><span class="header-section-number">8</span> Two independent code paths land on the same hyperplane</h2>
<p>Every number above came from a solver, which means every number above is worth auditing rather than trusting. The audit is mechanical: for the hard-margin fit, every functional margin must be at least <span class="math inline">\(1\)</span>; for the soft-margin fits, the relaxed version <span class="math inline">\(y_i f(x_i) + \xi_i \ge 1\)</span> must hold with non-negative slack doing the work the plots attribute to it.</p>
<div id="c79066d7" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Constraint audits for all solved problems</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"tolerance used in all checks: </span><span class="sc">{</span>TOL<span class="sc">:g}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"hard margin (Dataset A):"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  min_i  y_i(w·x_i + b)          = </span><span class="sc">{</span>func_margins<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.10f}</span><span class="ss">  ≥ 1 − tol ✓"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">soft margin (Dataset B):"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> f <span class="kw">in</span> fits:</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>    resid <span class="op">=</span> y_B <span class="op">*</span> (X_B <span class="op">@</span> f[<span class="st">"w"</span>] <span class="op">+</span> f[<span class="st">"b"</span>]) <span class="op">+</span> f[<span class="st">"xi"</span>]</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  C = </span><span class="sc">{</span>f[<span class="st">'C'</span>]<span class="sc">:&gt;6g}</span><span class="ss">:  min_i [y_i(w·x_i+b) + ξ_i] = "</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>resid<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.10f}</span><span class="ss">  ≥ 1 − tol ✓,   min ξ_i = </span><span class="sc">{</span>f[<span class="st">'xi'</span>]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.1e}</span><span class="ss"> ≥ 0 ✓"</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> resid.<span class="bu">min</span>() <span class="op">&gt;=</span> <span class="dv">1</span> <span class="op">-</span> <span class="fl">1e-5</span> <span class="kw">and</span> f[<span class="st">"xi"</span>].<span class="bu">min</span>() <span class="op">&gt;=</span> <span class="op">-</span>TOL</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>tolerance used in all checks: 1e-06

hard margin (Dataset A):
  min_i  y_i(w·x_i + b)          = 1.0000000001  ≥ 1 − tol ✓

soft margin (Dataset B):
  C =   0.05:  min_i [y_i(w·x_i+b) + ξ_i] = 0.9999999963  ≥ 1 − tol ✓,   min ξ_i = 0.0e+00 ≥ 0 ✓
  C =      1:  min_i [y_i(w·x_i+b) + ξ_i] = 0.9999999945  ≥ 1 − tol ✓,   min ξ_i = 0.0e+00 ≥ 0 ✓
  C =    100:  min_i [y_i(w·x_i+b) + ξ_i] = 0.9999999998  ≥ 1 − tol ✓,   min ξ_i = 0.0e+00 ≥ 0 ✓</code></pre>
</div>
</div>
<p>The slack values connect directly back to <a href="#fig-c-sweep" class="quarto-xref">Figure&nbsp;4</a>: points printed as violations are precisely the ringed-or-crossed points drawn inside or across each panel’s margin band, and each panel’s <span class="math inline">\({\sum_i \xi_i}\)</span> shrinks as <span class="math inline">\(C\)</span> grows while its band narrows.</p>
<p>A stronger check is a second opinion from code that shares nothing with this one. <code>scikit-learn</code>’s <code>SVC</code> solves the <em>dual</em> problem with sequential minimal optimization, an algorithm built specifically for SVMs that updates two prices <span class="math inline">\(\alpha_i\)</span> at a time, rather than the general-purpose primal solve used throughout this post. Different formulation, different algorithm, different library — and it should still land on the same hyperplanes:</p>
<div id="60757ebc" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>Cross-check against scikit-learn (optional, not the primary solve)</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.svm <span class="im">import</span> SVC</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>svc_hard <span class="op">=</span> SVC(kernel<span class="op">=</span><span class="st">"linear"</span>, C<span class="op">=</span><span class="fl">1e8</span>, tol<span class="op">=</span><span class="fl">1e-8</span>).fit(X_A, y_A)  <span class="co"># huge C ≈ hard margin</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"hard   : sklearn w ="</span>, np.<span class="bu">round</span>(svc_hard.coef_[<span class="dv">0</span>], <span class="dv">6</span>),</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>      <span class="st">" b ="</span>, np.<span class="bu">round</span>(svc_hard.intercept_[<span class="dv">0</span>], <span class="dv">6</span>))</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(svc_hard.coef_[<span class="dv">0</span>], w_hard, atol<span class="op">=</span><span class="fl">1e-4</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">abs</span>(svc_hard.intercept_[<span class="dv">0</span>] <span class="op">-</span> b_hard) <span class="op">&lt;</span> <span class="fl">1e-4</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> f <span class="kw">in</span> fits:</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>    svc <span class="op">=</span> SVC(kernel<span class="op">=</span><span class="st">"linear"</span>, C<span class="op">=</span>f[<span class="st">"C"</span>], tol<span class="op">=</span><span class="fl">1e-8</span>).fit(X_B, y_B)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>    dw <span class="op">=</span> np.linalg.norm(svc.coef_[<span class="dv">0</span>] <span class="op">-</span> f[<span class="st">"w"</span>])</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a>    db <span class="op">=</span> <span class="bu">abs</span>(svc.intercept_[<span class="dv">0</span>] <span class="op">-</span> f[<span class="st">"b"</span>])</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"C=</span><span class="sc">{</span>f[<span class="st">'C'</span>]<span class="sc">:&gt;6g}</span><span class="ss">: sklearn w = </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">round</span>(svc.coef_[<span class="dv">0</span>], <span class="dv">4</span>)<span class="sc">}</span><span class="ss">, "</span></span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"b = </span><span class="sc">{</span>svc<span class="sc">.</span>intercept_[<span class="dv">0</span>]<span class="sc">:+.4f}</span><span class="ss">   (‖Δw‖ = </span><span class="sc">{</span>dw<span class="sc">:.1e}</span><span class="ss">, |Δb| = </span><span class="sc">{</span>db<span class="sc">:.1e}</span><span class="ss">)"</span>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> dw <span class="op">&lt;</span> <span class="fl">1e-3</span> <span class="kw">and</span> db <span class="op">&lt;</span> <span class="fl">1e-3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>hard   : sklearn w = [0.5 0.5]  b = -2.0
C=  0.05: sklearn w = [0.4575 0.5523], b = -2.4371   (‖Δw‖ = 5.0e-08, |Δb| = 1.6e-07)
C=     1: sklearn w = [0.8088 1.0946], b = -4.8491   (‖Δw‖ = 5.3e-07, |Δb| = 1.5e-06)
C=   100: sklearn w = [0.8676 2.0191], b = -7.1951   (‖Δw‖ = 1.8e-04, |Δb| = 4.2e-04)</code></pre>
</div>
</div>
<p>Same <span class="math inline">\(w\)</span>, same <span class="math inline">\(b\)</span>, to solver tolerance, on every problem — two unrelated code paths agreeing on the unique optimum that convexity promised.</p>
<p>Agreement on the numbers is not the same as understanding what the fit did, though, and that takes holding four views of one object at once:</p>
<ul>
<li><strong>geometry in input space</strong> — a boundary, a band, and points that touch it;</li>
<li><strong>feasibility and objective in parameter space</strong> — each data point is a half-space constraint on <span class="math inline">\((w, b)\)</span>, and the optimum is where the shrinking norm ball last touches the feasible set (<a href="#fig-parameter-space" class="quarto-xref">Figure&nbsp;3</a>);</li>
<li><strong>support vectors / active constraints</strong> — the sparse subset of data with <span class="math inline">\(\alpha_i &gt; 0\)</span> that actually holds the solution in place;</li>
<li><strong>the regularization trade-off</strong> — <span class="math inline">\(C\)</span> pricing margin width against violations, with neither extreme universally right.</li>
</ul>
</section>
<section id="five-traps-the-four-views-disarm" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="five-traps-the-four-views-disarm"><span class="header-section-number">9</span> Five traps the four views disarm</h2>
<p>Each of those views also kills a plausible-sounding claim that survives when you hold only one of them:</p>
<ol type="1">
<li><strong>“Any separating line is equally good.”</strong> All separators achieve 100% training accuracy, but they differ enormously in clearance (<a href="#fig-many-separators" class="quarto-xref">Figure&nbsp;1</a>: <span class="math inline">\(\gamma = 1.414\)</span> vs <span class="math inline">\(0.86\)</span>). The max-margin criterion is precisely a principled tiebreaker among them.</li>
<li><strong>“Convex means the answer must be unique.”</strong> Convexity eliminates bad <em>local</em> minima; it says nothing about a unique minimizer. We exhibited a genuine two-class problem whose optimal intercepts form an interval (<a href="#fig-flat-b" class="quarto-xref">Figure&nbsp;5</a>). Uniqueness needs extra conditions — strict convexity in <em>all</em> variables, or the two-class separable structure of <a href="#sec-unique" class="quarto-xref">Section&nbsp;5</a>.</li>
<li><strong>“The margin is the distance from the boundary to a support vector.”</strong> That is the <em>one-sided</em> geometric margin <span class="math inline">\(1/\lVert w \rVert\)</span>. The margin band — the full empty street the SVM maximizes — is twice that, <span class="math inline">\(2/\lVert w \rVert\)</span> (both are drawn in <a href="#fig-hard-solution" class="quarto-xref">Figure&nbsp;2</a>).</li>
<li><strong>“Larger <span class="math inline">\(C\)</span> always gives a better classifier.”</strong> Larger <span class="math inline">\(C\)</span> only penalizes <em>training</em> violations more heavily. On Dataset B it progressively contorts the fit around an outlier that no linear boundary can classify, narrowing the margin band substantially (see the widths printed in each panel of <a href="#fig-c-sweep" class="quarto-xref">Figure&nbsp;4</a>) without ever fixing the outlier. Training-set obedience is not generalization.</li>
<li><strong>“The solver found a solution, so one always exists.”</strong> Hard-margin feasibility is an assumption about the data, not a gift of convexity — on our overlapping dataset the solver correctly returned <code>infeasible</code>, and slack variables had to be invented before any answer existed at all.</li>
</ol>
</section>
<section id="the-instinct-written-down" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="the-instinct-written-down"><span class="header-section-number">10</span> The instinct, written down</h2>
<p>The line your hand drew down the middle of the paper was doing one thing: keeping as far as possible from the closest point on either side. Every piece of machinery in this post is that preference made precise enough to compute — clearance measured as <span class="math inline">\(1/\lVert w\rVert\)</span>, the scale pinned so the measurement means something, the widest corridor found by shrinking a norm ball onto a polyhedron, and the answer certified rather than hoped for.</p>
<p>What the arithmetic adds is the part the instinct has no answer for. It tells you which two points out of ten the line is actually resting on. It tells you what to do when the clouds overlap and no line exists at all, and what it costs to bend one around a case that cannot be saved. And it is honest about where it stops: on Dataset B the outlier stayed wrong at every price, and at a low enough price the boundary’s position stopped being determined at all. A wide street is a good default, not a guarantee — the guarantee is only that this is the widest one.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/svm-max-margin-convex-optimization/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>