<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-08-18">

<title>Five Photos of One Kite, Five Different Shapes – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Five Photos of One Kite, Five Different Shapes</h1>
            <p class="subtitle lead">What happens when you point Kendall shape analysis at a photograph instead of a specimen</p>
                                <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Geometry</div>
                <div class="quarto-category">Computer Vision</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 18, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#five-frames-of-one-kite-nine-seconds-apart" id="toc-five-frames-of-one-kite-nine-seconds-apart" class="nav-link active" data-scroll-target="#five-frames-of-one-kite-nine-seconds-apart">Five frames of one kite, nine seconds apart</a></li>
  <li><a href="#a-photograph-is-a-matrix-and-this-one-is-mostly-cloud" id="toc-a-photograph-is-a-matrix-and-this-one-is-mostly-cloud" class="nav-link" data-scroll-target="#a-photograph-is-a-matrix-and-this-one-is-mostly-cloud">A photograph is a matrix, and this one is mostly cloud</a></li>
  <li><a href="#saturation-separates-a-rainbow-kite-from-a-grey-sky" id="toc-saturation-separates-a-rainbow-kite-from-a-grey-sky" class="nav-link" data-scroll-target="#saturation-separates-a-rainbow-kite-from-a-grey-sky">Saturation separates a rainbow kite from a grey sky</a></li>
  <li><a href="#correspondence-is-the-part-you-cannot-skip" id="toc-correspondence-is-the-part-you-cannot-skip" class="nav-link" data-scroll-target="#correspondence-is-the-part-you-cannot-skip">Correspondence is the part you cannot skip</a></li>
  <li><a href="#the-nose-angle-changes-by-thirty-degrees-so-these-are-not-similar-figures" id="toc-the-nose-angle-changes-by-thirty-degrees-so-these-are-not-similar-figures" class="nav-link" data-scroll-target="#the-nose-angle-changes-by-thirty-degrees-so-these-are-not-similar-figures">The nose angle changes by thirty degrees, so these are not similar figures</a></li>
  <li><a href="#procrustes-cannot-remove-what-it-was-not-built-to-remove" id="toc-procrustes-cannot-remove-what-it-was-not-built-to-remove" class="nav-link" data-scroll-target="#procrustes-cannot-remove-what-it-was-not-built-to-remove">Procrustes cannot remove what it was not built to remove</a></li>
  <li><a href="#fit-similarity-affine-and-projective-and-read-off-which-one-the-camera-used" id="toc-fit-similarity-affine-and-projective-and-read-off-which-one-the-camera-used" class="nav-link" data-scroll-target="#fit-similarity-affine-and-projective-and-read-off-which-one-the-camera-used">Fit similarity, affine and projective, and read off which one the camera used</a></li>
  <li><a href="#quotient-out-the-affine-group-and-most-of-the-shape-difference-disappears" id="toc-quotient-out-the-affine-group-and-most-of-the-shape-difference-disappears" class="nav-link" data-scroll-target="#quotient-out-the-affine-group-and-most-of-the-shape-difference-disappears">Quotient out the affine group and most of the shape difference disappears</a></li>
  <li><a href="#caveat-most-of-what-is-left-is-my-own-hand" id="toc-caveat-most-of-what-is-left-is-my-own-hand" class="nav-link" data-scroll-target="#caveat-most-of-what-is-left-is-my-own-hand">Caveat: most of what is left is my own hand</a></li>
  <li><a href="#the-same-pipeline-in-rs-shapes-package" id="toc-the-same-pipeline-in-rs-shapes-package" class="nav-link" data-scroll-target="#the-same-pipeline-in-rs-shapes-package">The same pipeline in R’s shapes package</a></li>
  <li><a href="#warping-the-photographs-themselves-shows-the-size-of-what-was-fixed" id="toc-warping-the-photographs-themselves-shows-the-size-of-what-was-fixed" class="nav-link" data-scroll-target="#warping-the-photographs-themselves-shows-the-size-of-what-was-fixed">Warping the photographs themselves shows the size of what was fixed</a></li>
  <li><a href="#shape-analysis-only-subtracts-what-you-tell-it-to" id="toc-shape-analysis-only-subtracts-what-you-tell-it-to" class="nav-link" data-scroll-target="#shape-analysis-only-subtracts-what-you-tell-it-to">Shape analysis only subtracts what you tell it to</a></li>
  </ul>
<div class="toc-actions"><ul class="collapse"><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/kite-shape-analysis/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Five Photos of One Kite, Five Different Shapes</figcaption>
</figure>
</div>
<p>I photographed the same kite five times in nine seconds. It is a rigid object made of ripstop nylon over two spars, and nothing happened to it between the first frame and the last. Line up the five outlines and they should sit on top of one another exactly.</p>
<p>They do not. The angle at the kite’s nose reads 81 degrees in one frame and 113 degrees in another. Run the standard shape-analysis pipeline over them and it reports the five photographs as five different shapes, with distances of up to 0.33 between them in the space it measures shape in.</p>
<p>That is not noise, and it is not a bug in the pipeline. It is the pipeline being asked to remove something it was never built to remove. Kendall shape analysis subtracts position, size and angle — and a camera does not add position, size and angle. It adds perspective. The repair belongs upstream of Procrustes, not inside it.</p>
<section id="five-frames-of-one-kite-nine-seconds-apart" class="level2">
<h2 class="anchored" data-anchor-id="five-frames-of-one-kite-nine-seconds-apart">Five frames of one kite, nine seconds apart</h2>
<p>The data is five photographs I took at the kite festival at Villa de Leyva, in Boyacá, Colombia, on 15 August 2026. They are iPhone HEIC frames, 3024 wide by 4032 tall, timestamped 13:26:12 through 13:26:21 — so the whole sample spans nine seconds. I have committed them here at half resolution, 1512 × 2016, and every coordinate in this post lives in that pixel grid.</p>
<p>There was no protocol. I stood in a field and pointed a phone at the sky, handheld, with no tripod, no scale bar, no fixed distance and no attempt to keep the camera still between frames. That is the point of using them. This is what field photography actually looks like, and the question I want to ask of these five frames is the one nobody asks out loud: <em>does one rigid object photographed five times give one shape?</em></p>
<p>If the answer is no, then any study that photographs two specimens and reports a shape difference between them has a problem, because some of that difference is the photographer. In morphometrics this is the calibration step that decides whether a published finding is about the organism or about where somebody was standing. Getting it wrong means reporting a camera artefact as biology.</p>
<p>Kendall shape analysis is the right tool to point at this, because it is the tool that claims to delete exactly the nuisances a camera introduces. Testing it where the true answer is known in advance — five photographs of one unchanging object, so the correct shape difference is zero — is the only way to find out which nuisances it really deletes and which it silently leaves behind.</p>
<p>If you want the method itself rather than its failure modes, I wrote it up on synthetic pencils and a real dataset of monkey optic nerve heads in <a href="../../posts/kendall-shape-analysis/index.html">an earlier post</a>. This one is the field test.</p>
</section>
<section id="a-photograph-is-a-matrix-and-this-one-is-mostly-cloud" class="level2">
<h2 class="anchored" data-anchor-id="a-photograph-is-a-matrix-and-this-one-is-mostly-cloud">A photograph is a matrix, and this one is mostly cloud</h2>
<p>Before any geometry, the photograph has to become numbers. An image is a grid of pixels, and each pixel is a triple of intensities — how much red, green and blue it carries — so a colour photograph is a stack of three matrices. Everything downstream is arithmetic on that stack.</p>
<p>It helps to actually look at the numbers once. Here is a frame, the same frame as a single brightness matrix, and a ten-by-ten patch of sky with its raw values printed on it.</p>
<div id="cell-fig-matrix" class="cell" data-execution_count="1">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> PIL <span class="im">import</span> Image</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>photo <span class="op">=</span> Image.<span class="bu">open</span>(<span class="st">"photos/kite-01.jpg"</span>).convert(<span class="st">"RGB"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>rgb <span class="op">=</span> np.asarray(photo)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>grey <span class="op">=</span> np.asarray(photo.convert(<span class="st">"L"</span>))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="dv">5</span>))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].imshow(rgb)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="ss">f"colour: </span><span class="sc">{</span>rgb<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> wide x </span><span class="sc">{</span>rgb<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> tall x </span><span class="sc">{</span>rgb<span class="sc">.</span>shape[<span class="dv">2</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].imshow(grey, cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="ss">f"brightness: </span><span class="sc">{</span>grey<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> wide x </span><span class="sc">{</span>grey<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> tall"</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>patch <span class="op">=</span> grey[<span class="dv">600</span>:<span class="dv">610</span>, <span class="dv">500</span>:<span class="dv">510</span>]</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].imshow(patch, cmap<span class="op">=</span><span class="st">"gray"</span>, interpolation<span class="op">=</span><span class="st">"nearest"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">255</span>)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">10</span>):</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>        axes[<span class="dv">2</span>].text(j, i, patch[i, j], ha<span class="op">=</span><span class="st">"center"</span>, va<span class="op">=</span><span class="st">"center"</span>, color<span class="op">=</span><span class="st">"tab:red"</span>, fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"a 10x10 patch of cloud"</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> axes:</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    ax.axis(<span class="st">"off"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-matrix" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-matrix-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-matrix-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: One frame as a picture, as a brightness matrix, and as raw numbers. The sky patch is flat and bright: cloud is high in brightness and almost zero in colour.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The patch is the useful part. Those numbers are all close together and all fairly large: overcast sky is bright and grey. Grey means the three channels are nearly equal, and that is what separates the sky from what is flying in it. The kite is dyed in saturated dye and the cloud is not, so the quantity that tells them apart is not brightness but <strong>saturation</strong> — how far a pixel’s colour is from grey, computed as the spread between its largest and smallest channel divided by the largest.</p>
</section>
<section id="saturation-separates-a-rainbow-kite-from-a-grey-sky" class="level2">
<h2 class="anchored" data-anchor-id="saturation-separates-a-rainbow-kite-from-a-grey-sky">Saturation separates a rainbow kite from a grey sky</h2>
<p>Saturation turns out to do the whole job on its own. Every pixel of cloud is near zero, every pixel of kite fabric is near one, and there is nothing in between to argue about. One threshold and a connected-components pass isolates the kite in all five frames.</p>
<div id="cell-fig-segment" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> ndimage</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> saturation(image):</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Distance from grey, per pixel: (max channel - min channel) / max channel."""</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    a <span class="op">=</span> np.asarray(image).astype(np.float32) <span class="op">/</span> <span class="fl">255.0</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    top, bottom <span class="op">=</span> a.<span class="bu">max</span>(axis<span class="op">=</span><span class="dv">2</span>), a.<span class="bu">min</span>(axis<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (top <span class="op">-</span> bottom) <span class="op">/</span> np.maximum(top, <span class="fl">1e-6</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> largest_blob(mask):</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""The biggest connected component, plus its bounding box."""</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    labels, count <span class="op">=</span> ndimage.label(mask)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    sizes <span class="op">=</span> ndimage.<span class="bu">sum</span>(mask, labels, <span class="bu">range</span>(<span class="dv">1</span>, count <span class="op">+</span> <span class="dv">1</span>))</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    best <span class="op">=</span> <span class="bu">int</span>(np.argmax(sizes)) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> labels <span class="op">==</span> best, ndimage.find_objects(labels)[best <span class="op">-</span> <span class="dv">1</span>]</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">5</span>, figsize<span class="op">=</span>(<span class="dv">16</span>, <span class="dv">7</span>))</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> frame <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">6</span>):</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    image <span class="op">=</span> Image.<span class="bu">open</span>(<span class="ss">f"photos/kite-</span><span class="sc">{</span>frame<span class="sc">:02d}</span><span class="ss">.jpg"</span>).convert(<span class="st">"RGB"</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    kite, box <span class="op">=</span> largest_blob(saturation(image) <span class="op">&gt;</span> <span class="fl">0.30</span>)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    pad <span class="op">=</span> <span class="dv">30</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> <span class="bu">slice</span>(<span class="bu">max</span>(<span class="dv">0</span>, box[<span class="dv">0</span>].start <span class="op">-</span> pad), box[<span class="dv">0</span>].stop <span class="op">+</span> pad)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    cols <span class="op">=</span> <span class="bu">slice</span>(<span class="bu">max</span>(<span class="dv">0</span>, box[<span class="dv">1</span>].start <span class="op">-</span> pad), box[<span class="dv">1</span>].stop <span class="op">+</span> pad)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>][frame <span class="op">-</span> <span class="dv">1</span>].imshow(np.asarray(image)[rows, cols])</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>][frame <span class="op">-</span> <span class="dv">1</span>].set_title(<span class="ss">f"frame </span><span class="sc">{</span>frame<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>][frame <span class="op">-</span> <span class="dv">1</span>].imshow(kite[rows, cols], cmap<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> axes.ravel():</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    ax.axis(<span class="st">"off"</span>)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-segment" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-segment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-segment-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-segment-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Top: the kite as photographed, cropped from each frame. Bottom: every pixel with saturation above 0.30. The sky vanishes completely.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Look at the top row rather than the bottom one. The same kite, nine seconds apart, appears as a wide shallow triangle in frame 1 and as a sharp narrow chevron in frame 4. Nothing about the kite changed. What changed is where it was pointing relative to the lens.</p>
<p>The masks also show the other problem. Roughly half of every mask is streamers — the long ribbons trailing off the back edge — and they move independently in the wind.</p>
</section>
<section id="correspondence-is-the-part-you-cannot-skip" class="level2">
<h2 class="anchored" data-anchor-id="correspondence-is-the-part-you-cannot-skip">Correspondence is the part you cannot skip</h2>
<p>A mask is not yet something Procrustes can use. Procrustes compares two configurations of <em>labelled</em> points, and the labels have to mean the same thing in both: point 3 must be the same physical spot on the kite in every photograph. That correspondence is what makes two specimens comparable at all, and it is the part that no amount of clever alignment can supply after the fact. Points chosen this way are called <strong>landmarks</strong>.</p>
<p>Sample points off the outline instead and you get configurations of the right size and no correspondence whatsoever — point 3 lands somewhere different on every kite, and Procrustes faithfully rotates one meaningless list onto another. That is the first way this analysis goes wrong, and it is worth ruling out before blaming anything subtler.</p>
<p>So the streamers are out. They flap, so a point on one means a different thing in each frame. The landmarks go on the <strong>sail</strong> — the rigid block of nested colour chevrons — and there is a nice accident there: the sail’s bands are ordered by colour, and colour identity is the anatomical label. Six points, all corners of the band stack:</p>
<ul>
<li><code>nose</code>, the outer apex where the two dark navy leading edges meet;</li>
<li><code>armA_out</code> and <code>armB_out</code>, the far ends of those two leading edges;</li>
<li><code>armA_in</code> and <code>armB_in</code>, the far ends of the band stack’s inner boundary on each arm;</li>
<li><code>apex_in</code>, the inner apex where those two inner boundaries meet.</li>
</ul>
<p>One of these labels is not determined by the photograph, and it is worth being blunt about it. The sail is bilaterally symmetric and so are its colour bands, so nothing in a single image says which physical wing is <code>armA</code> and which is <code>armB</code>. I fixed the choice by making every frame’s traversal run the same way round the sail, which meant swapping the two labels in frame 5 relative to how that photograph reads. That is a free choice about labelling, not a measurement — but it is a free choice that would set the headline number if the analysis were sensitive to it, so the Procrustes alignment below is built not to care, by allowing reflections. Forbid reflection and these same landmarks report a Procrustes sum of squares of 0.855 instead of 0.111; allow it, and the two labellings differ by under 6%. The model ladder further down fits each frame separately rather than to a common mean, so it is not insensitive in the same clean way — relabelling permutes points rather than exactly mirroring them, so even a six-parameter affine fit shifts a little under it.</p>
<p>I placed these by hand off the committed photographs, the way a morphometrician places them in tpsDig, and checked them against the overlay below. Placement is good to about ±5 pixels on a sail 160 pixels across. Hold on to that number — it decides what this analysis can and cannot conclude, and it comes back at the end.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./fig-landmarks.png" class="img-fluid figure-img"></p>
<figcaption>The six sail landmarks in each frame. Nothing sits on a streamer.</figcaption>
</figure>
</div>
<div id="load-landmarks" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> csv</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ORDER <span class="op">=</span> [<span class="st">"nose"</span>, <span class="st">"armA_out"</span>, <span class="st">"armA_in"</span>, <span class="st">"apex_in"</span>, <span class="st">"armB_in"</span>, <span class="st">"armB_out"</span>]</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> <span class="bu">list</span>(csv.DictReader(<span class="bu">open</span>(<span class="st">"landmarks.csv"</span>)))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>by_frame <span class="op">=</span> {}</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> rows:</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    by_frame.setdefault(<span class="bu">int</span>(row[<span class="st">"frame"</span>]), {})[row[<span class="st">"landmark"</span>]] <span class="op">=</span> (</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>        <span class="bu">float</span>(row[<span class="st">"x"</span>]), <span class="bu">float</span>(row[<span class="st">"y"</span>]))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.stack([np.array([by_frame[f][name] <span class="cf">for</span> name <span class="kw">in</span> ORDER]) <span class="cf">for</span> f <span class="kw">in</span> <span class="bu">sorted</span>(by_frame)])</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>X<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> configurations of </span><span class="sc">{</span>X<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> landmarks in </span><span class="sc">{</span>X<span class="sc">.</span>shape[<span class="dv">2</span>]<span class="sc">}</span><span class="ss">D"</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mean centroid size: </span><span class="sc">{</span>np<span class="sc">.</span>mean([np.linalg.norm(c <span class="op">-</span> c.mean(<span class="dv">0</span>)) <span class="cf">for</span> c <span class="kw">in</span> X])<span class="sc">:.0f}</span><span class="ss"> px"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>5 configurations of 6 landmarks in 2D
mean centroid size: 160 px</code></pre>
</div>
</div>
</section>
<section id="the-nose-angle-changes-by-thirty-degrees-so-these-are-not-similar-figures" class="level2">
<h2 class="anchored" data-anchor-id="the-nose-angle-changes-by-thirty-degrees-so-these-are-not-similar-figures">The nose angle changes by thirty degrees, so these are not similar figures</h2>
<p>There is a way to settle the central question before fitting anything at all, and it takes one measurement.</p>
<p>Kendall shape analysis quotients out the <strong>similarity</strong> group: translations, rotations, and uniform rescalings. Every one of those preserves angles. A triangle that has been moved, turned and enlarged has exactly the angles it started with. So if the five frames really were related by similarity — if the camera only ever moved, turned and zoomed — the angle at the kite’s nose would be the same number five times.</p>
<div id="nose-angle" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> nose_angle(config):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Angle at the nose, between the two leading edges, in degrees."""</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    left <span class="op">=</span> config[ORDER.index(<span class="st">"armA_out"</span>)] <span class="op">-</span> config[ORDER.index(<span class="st">"nose"</span>)]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    right <span class="op">=</span> config[ORDER.index(<span class="st">"armB_out"</span>)] <span class="op">-</span> config[ORDER.index(<span class="st">"nose"</span>)]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    cosine <span class="op">=</span> np.dot(left, right) <span class="op">/</span> (np.linalg.norm(left) <span class="op">*</span> np.linalg.norm(right))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.degrees(np.arccos(cosine))</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>angles <span class="op">=</span> np.array([nose_angle(c) <span class="cf">for</span> c <span class="kw">in</span> X])</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> frame, angle <span class="kw">in</span> <span class="bu">enumerate</span>(angles, start<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  frame </span><span class="sc">{</span>frame<span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>angle<span class="sc">:6.2f}</span><span class="ss"> degrees"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">spread: </span><span class="sc">{</span>angles<span class="sc">.</span><span class="bu">max</span>() <span class="op">-</span> angles<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.1f}</span><span class="ss"> degrees"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  frame 1: 104.01 degrees
  frame 2: 112.93 degrees
  frame 3:  86.97 degrees
  frame 4:  81.29 degrees
  frame 5:  88.01 degrees

spread: 31.6 degrees</code></pre>
</div>
</div>
<p>Thirty-one degrees of spread on a quantity that similarity cannot touch. Jittering the landmarks by 5 pixels and remeasuring puts the standard deviation of this angle between 3.6 and 6.3 degrees depending on the frame — so my digitising is worth a few degrees, nowhere near enough to manufacture thirty. Whatever maps one frame onto another, it is not a similarity, and that is settled without running Procrustes once.</p>
<p>The interesting question is no longer <em>whether</em> the pipeline will struggle. It is what the struggle looks like, and what the right group turns out to be.</p>
</section>
<section id="procrustes-cannot-remove-what-it-was-not-built-to-remove" class="level2">
<h2 class="anchored" data-anchor-id="procrustes-cannot-remove-what-it-was-not-built-to-remove">Procrustes cannot remove what it was not built to remove</h2>
<p>The standard pipeline is three deletions, and none of them involve fitting anything. Translation comes off by moving each configuration so its landmarks average to the origin. Size comes off by dividing by the spread of the landmarks around that centre — the Frobenius norm — so every configuration ends up at size one. Rotation comes off by turning each configuration until it sits as close as least squares allows to a target, which falls out of a singular value decomposition.</p>
<p>Rotation needs something to rotate <em>onto</em>, and there is no target to start from. The way out is to guess and refine: take one configuration as a provisional mean, rotate everything onto it, average, and repeat until the mean stops moving. That loop is generalised Procrustes analysis.</p>
<div id="gpa" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> centre_and_scale(config):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Remove translation and size."""</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    centred <span class="op">=</span> config <span class="op">-</span> config.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> centred <span class="op">/</span> np.linalg.norm(centred)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> align_onto(config, target):</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Least-squares orthogonal map of `config` onto `target`, via an SVD.</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Reflections are allowed, deliberately. The usual version of this function</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co">    forbids them, on the grounds that a mirror image is a different shape. That</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co">    is right for a left and a right hand; it is wrong here, because which wing</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co">    of a symmetric sail got labelled `armA` is a free choice rather than a fact</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a><span class="co">    about the kite (see above). Forbidding reflection would charge that free</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co">    choice to the kite's shape.</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    u, _, vt <span class="op">=</span> np.linalg.svd(target.T <span class="op">@</span> config)</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> config <span class="op">@</span> (vt.T <span class="op">@</span> u.T)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gpa(configs, prepare<span class="op">=</span>centre_and_scale, tol<span class="op">=</span><span class="fl">1e-13</span>, max_iter<span class="op">=</span><span class="dv">500</span>):</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Generalised Procrustes: prepare each configuration, then iterate to a mean."""</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    aligned <span class="op">=</span> np.stack([prepare(c) <span class="cf">for</span> c <span class="kw">in</span> configs])</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    mean <span class="op">=</span> aligned[<span class="dv">0</span>]</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(max_iter):</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>        aligned <span class="op">=</span> np.stack([centre_and_scale(align_onto(c, mean)) <span class="cf">for</span> c <span class="kw">in</span> aligned])</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>        new_mean <span class="op">=</span> centre_and_scale(aligned.mean(axis<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> np.linalg.norm(new_mean <span class="op">-</span> mean) <span class="op">&lt;</span> tol:</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>        mean <span class="op">=</span> new_mean</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> aligned, mean</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>aligned, mean_shape <span class="op">=</span> gpa(X)</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>residual <span class="op">=</span> np.linalg.norm(aligned <span class="op">-</span> mean_shape, axis<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>similarity_ss <span class="op">=</span> <span class="bu">float</span>((residual <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>())</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"residual to the mean shape:"</span>, residual.<span class="bu">round</span>(<span class="dv">4</span>))</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Procrustes sum of squares: </span><span class="sc">{</span>similarity_ss<span class="sc">:.5f}</span><span class="ss">"</span>)</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMS residual: </span><span class="sc">{</span>residual<span class="sc">.</span>mean()<span class="sc">:.4f}</span><span class="ss">  (</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> residual<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss">% of centroid size)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>residual to the mean shape: [0.1381 0.1764 0.1416 0.1643 0.1173]
Procrustes sum of squares: 0.11100
RMS residual: 0.1475  (14.8% of centroid size)</code></pre>
</div>
</div>
<p>Every configuration has size one, so a residual of 0.15 means each frame sits about 15% of its own extent away from the average frame. For five photographs of one rigid object taken over nine seconds, that is enormous. Plotted, the five aligned sails do not agree on anything except roughly where the nose is.</p>
<div id="cell-fig-gpa-raw" class="cell" data-execution_count="6">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>COLOURS <span class="op">=</span> plt.cm.viridis(np.linspace(<span class="fl">0.05</span>, <span class="fl">0.85</span>, <span class="dv">5</span>))</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw(ax, config, colour, lw<span class="op">=</span><span class="fl">1.4</span>, alpha<span class="op">=</span><span class="fl">0.9</span>):</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    loop <span class="op">=</span> np.vstack([config, config[<span class="dv">0</span>]])</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    ax.plot(loop[:, <span class="dv">0</span>], loop[:, <span class="dv">1</span>], <span class="st">"-o"</span>, color<span class="op">=</span>colour, lw<span class="op">=</span>lw, ms<span class="op">=</span><span class="fl">3.5</span>, alpha<span class="op">=</span>alpha)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">5</span>))</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> config, colour <span class="kw">in</span> <span class="bu">zip</span>(aligned, COLOURS):</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    draw(ax, config, colour)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>draw(ax, mean_shape, <span class="st">"black"</span>, lw<span class="op">=</span><span class="fl">2.4</span>, alpha<span class="op">=</span><span class="fl">1.0</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>ax.invert_yaxis()</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"After GPA: five frames of one rigid kite"</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-gpa-raw" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gpa-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-gpa-raw-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gpa-raw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The five sails after generalised Procrustes analysis, with the mean shape in black. This is the best that translation, scale and rotation can do.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This is the failure, reproduced honestly, and note <em>when</em> it happens: after the landmarks were placed properly, with real correspondence, on the rigid part of the kite only. Fixing the correspondence was necessary. It was not sufficient.</p>
</section>
<section id="fit-similarity-affine-and-projective-and-read-off-which-one-the-camera-used" class="level2">
<h2 class="anchored" data-anchor-id="fit-similarity-affine-and-projective-and-read-off-which-one-the-camera-used">Fit similarity, affine and projective, and read off which one the camera used</h2>
<p>If similarity is too small a group, the obvious move is to ask how much bigger the right one is. There is a natural ladder of candidates, each containing the last.</p>
<p><strong>Similarity</strong> has four degrees of freedom — translate, rotate, scale — and preserves angles. <strong>Affine</strong> has six: it adds shear and lets the two axes scale differently, so it no longer preserves angles but still maps parallel lines to parallel lines. This is the model you get from a flat object photographed from far enough away that the near edge and the far edge are effectively the same distance from the lens, which is called weak perspective. <strong>Projective</strong> has eight, adds genuine perspective, and is what a plane photographed from any viewpoint actually undergoes: parallel lines converge, and only straight lines are guaranteed to stay straight.</p>
<p>Fit each of the three to each frame and see which one explains the photographs.</p>
<div id="ladder" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> least_squares</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_similarity(src, dst, allow_reflection<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Best similarity map from `src` onto `dst` (Umeyama).</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Reflection is allowed by default, matching the Procrustes alignment above</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">    and for the same reason: the wing labelling is a free choice. Refusing it</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">    takes more than flipping the rotation matrix -- the smallest singular</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">    value's contribution to the optimal scale flips sign with it. Leaving</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co">    `trace` at ``sv.sum()`` in that branch overshoots the scale, and is an easy</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co">    bug to write by accident.</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    mu_s, mu_d <span class="op">=</span> src.mean(<span class="dv">0</span>), dst.mean(<span class="dv">0</span>)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    s0, d0 <span class="op">=</span> src <span class="op">-</span> mu_s, dst <span class="op">-</span> mu_d</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    u, sv, vt <span class="op">=</span> np.linalg.svd(d0.T <span class="op">@</span> s0)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    rotation <span class="op">=</span> u <span class="op">@</span> vt</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    trace <span class="op">=</span> sv.<span class="bu">sum</span>()</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> allow_reflection <span class="kw">and</span> np.linalg.det(rotation) <span class="op">&lt;</span> <span class="dv">0</span>:</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        u <span class="op">=</span> u.copy()</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>        u[:, <span class="op">-</span><span class="dv">1</span>] <span class="op">*=</span> <span class="op">-</span><span class="dv">1</span></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>        rotation <span class="op">=</span> u <span class="op">@</span> vt</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>        trace <span class="op">=</span> sv[<span class="dv">0</span>] <span class="op">-</span> sv[<span class="dv">1</span>]</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (s0 <span class="op">@</span> rotation.T) <span class="op">*</span> (trace <span class="op">/</span> (s0 <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>()) <span class="op">+</span> mu_d</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_affine(src, dst):</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>    design <span class="op">=</span> np.hstack([src, np.ones((<span class="bu">len</span>(src), <span class="dv">1</span>))])</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> design <span class="op">@</span> np.linalg.lstsq(design, dst, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> apply_homography(h, src):</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> np.hstack([src, np.ones((<span class="bu">len</span>(src), <span class="dv">1</span>))]) <span class="op">@</span> h.T</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> p[:, :<span class="dv">2</span>] <span class="op">/</span> p[:, <span class="dv">2</span>:<span class="dv">3</span>]</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit_projective(src, dst):</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Normalised DLT for a starting point, then refine on *geometric* error.</span></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a><span class="co">    The plain DLT minimises an algebraic residual, which on six points can be</span></span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a><span class="co">    far from the least-squares answer -- badly enough to score worse than the</span></span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a><span class="co">    affine fit nested inside it, which is impossible for a correct fit.</span></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb10-40"><a href="#cb10-40" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> normalise(p):</span>
<span id="cb10-41"><a href="#cb10-41" aria-hidden="true" tabindex="-1"></a>        mu <span class="op">=</span> p.mean(<span class="dv">0</span>)</span>
<span id="cb10-42"><a href="#cb10-42" aria-hidden="true" tabindex="-1"></a>        q <span class="op">=</span> p <span class="op">-</span> mu</span>
<span id="cb10-43"><a href="#cb10-43" aria-hidden="true" tabindex="-1"></a>        s <span class="op">=</span> np.sqrt(<span class="dv">2</span>) <span class="op">/</span> np.sqrt((q <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>(<span class="dv">1</span>)).mean()</span>
<span id="cb10-44"><a href="#cb10-44" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> np.array([[s, <span class="dv">0</span>, <span class="op">-</span>s <span class="op">*</span> mu[<span class="dv">0</span>]], [<span class="dv">0</span>, s, <span class="op">-</span>s <span class="op">*</span> mu[<span class="dv">1</span>]], [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>]]), np.hstack(</span>
<span id="cb10-45"><a href="#cb10-45" aria-hidden="true" tabindex="-1"></a>            [q <span class="op">*</span> s, np.ones((<span class="bu">len</span>(p), <span class="dv">1</span>))])</span>
<span id="cb10-46"><a href="#cb10-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-47"><a href="#cb10-47" aria-hidden="true" tabindex="-1"></a>    t_src, ns <span class="op">=</span> normalise(src)</span>
<span id="cb10-48"><a href="#cb10-48" aria-hidden="true" tabindex="-1"></a>    t_dst, nd <span class="op">=</span> normalise(dst)</span>
<span id="cb10-49"><a href="#cb10-49" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> []</span>
<span id="cb10-50"><a href="#cb10-50" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (x, y, _), (u, v, _) <span class="kw">in</span> <span class="bu">zip</span>(ns, nd):</span>
<span id="cb10-51"><a href="#cb10-51" aria-hidden="true" tabindex="-1"></a>        rows.append([x, y, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="op">-</span>u <span class="op">*</span> x, <span class="op">-</span>u <span class="op">*</span> y, <span class="op">-</span>u])</span>
<span id="cb10-52"><a href="#cb10-52" aria-hidden="true" tabindex="-1"></a>        rows.append([<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, x, y, <span class="dv">1</span>, <span class="op">-</span>v <span class="op">*</span> x, <span class="op">-</span>v <span class="op">*</span> y, <span class="op">-</span>v])</span>
<span id="cb10-53"><a href="#cb10-53" aria-hidden="true" tabindex="-1"></a>    _, _, vt <span class="op">=</span> np.linalg.svd(np.array(rows))</span>
<span id="cb10-54"><a href="#cb10-54" aria-hidden="true" tabindex="-1"></a>    guess <span class="op">=</span> np.linalg.inv(t_dst) <span class="op">@</span> vt[<span class="op">-</span><span class="dv">1</span>].reshape(<span class="dv">3</span>, <span class="dv">3</span>) <span class="op">@</span> t_src</span>
<span id="cb10-55"><a href="#cb10-55" aria-hidden="true" tabindex="-1"></a>    guess <span class="op">=</span> guess <span class="op">/</span> guess[<span class="dv">2</span>, <span class="dv">2</span>]</span>
<span id="cb10-56"><a href="#cb10-56" aria-hidden="true" tabindex="-1"></a>    fit <span class="op">=</span> least_squares(</span>
<span id="cb10-57"><a href="#cb10-57" aria-hidden="true" tabindex="-1"></a>        <span class="kw">lambda</span> p: (apply_homography(np.append(p, <span class="fl">1.0</span>).reshape(<span class="dv">3</span>, <span class="dv">3</span>), src) <span class="op">-</span> dst).ravel(),</span>
<span id="cb10-58"><a href="#cb10-58" aria-hidden="true" tabindex="-1"></a>        guess.ravel()[:<span class="dv">8</span>], method<span class="op">=</span><span class="st">"lm"</span>, max_nfev<span class="op">=</span><span class="dv">20000</span>)</span>
<span id="cb10-59"><a href="#cb10-59" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> apply_homography(np.append(fit.x, <span class="fl">1.0</span>).reshape(<span class="dv">3</span>, <span class="dv">3</span>), src)</span>
<span id="cb10-60"><a href="#cb10-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-61"><a href="#cb10-61" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> rms(predicted, target):</span>
<span id="cb10-62"><a href="#cb10-62" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.sqrt(((predicted <span class="op">-</span> target) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>(<span class="dv">1</span>).mean()))</span>
<span id="cb10-63"><a href="#cb10-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-64"><a href="#cb10-64" aria-hidden="true" tabindex="-1"></a>MODELS <span class="op">=</span> [(<span class="st">"similarity"</span>, <span class="dv">4</span>, fit_similarity), (<span class="st">"affine"</span>, <span class="dv">6</span>, fit_affine),</span>
<span id="cb10-65"><a href="#cb10-65" aria-hidden="true" tabindex="-1"></a>          (<span class="st">"projective"</span>, <span class="dv">8</span>, fit_projective)]</span>
<span id="cb10-66"><a href="#cb10-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-67"><a href="#cb10-67" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'onto frame 1'</span><span class="sc">:&gt;14}</span><span class="ss">"</span> <span class="op">+</span> <span class="st">""</span>.join(<span class="ss">f"</span><span class="sc">{</span>n <span class="op">+</span> <span class="ss">f' (</span><span class="sc">{</span>d<span class="sc">}</span><span class="ss">)'</span><span class="sc">:&gt;15}</span><span class="ss">"</span> <span class="cf">for</span> n, d, _ <span class="kw">in</span> MODELS))</span>
<span id="cb10-68"><a href="#cb10-68" aria-hidden="true" tabindex="-1"></a>totals <span class="op">=</span> {name: [] <span class="cf">for</span> name, _, _ <span class="kw">in</span> MODELS}</span>
<span id="cb10-69"><a href="#cb10-69" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">5</span>):</span>
<span id="cb10-70"><a href="#cb10-70" aria-hidden="true" tabindex="-1"></a>    line <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span><span class="st">'frame '</span> <span class="op">+</span> <span class="bu">str</span>(j <span class="op">+</span> <span class="dv">1</span>)<span class="sc">:&gt;14}</span><span class="ss">"</span></span>
<span id="cb10-71"><a href="#cb10-71" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name, _, fit <span class="kw">in</span> MODELS:</span>
<span id="cb10-72"><a href="#cb10-72" aria-hidden="true" tabindex="-1"></a>        value <span class="op">=</span> rms(fit(X[j], X[<span class="dv">0</span>]), X[<span class="dv">0</span>])</span>
<span id="cb10-73"><a href="#cb10-73" aria-hidden="true" tabindex="-1"></a>        totals[name].append(value)</span>
<span id="cb10-74"><a href="#cb10-74" aria-hidden="true" tabindex="-1"></a>        line <span class="op">+=</span> <span class="ss">f"</span><span class="sc">{</span>value<span class="sc">:15.2f}</span><span class="ss">"</span></span>
<span id="cb10-75"><a href="#cb10-75" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(line)</span>
<span id="cb10-76"><a href="#cb10-76" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span><span class="st">'mean'</span><span class="sc">:&gt;14}</span><span class="ss">"</span> <span class="op">+</span> <span class="st">""</span>.join(<span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>mean(v)<span class="sc">:15.2f}</span><span class="ss">"</span> <span class="cf">for</span> v <span class="kw">in</span> totals.values()) <span class="op">+</span> <span class="st">"   px"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  onto frame 1 similarity (4)     affine (6) projective (8)
       frame 2           7.14           4.79           2.76
       frame 3          14.20           9.73           8.03
       frame 4          15.78          10.56           8.78
       frame 5          12.96           7.84           7.20

          mean          12.52           8.23           6.69   px</code></pre>
</div>
</div>
<p>The ladder comes out monotone, which is what should happen: each model contains the one before it, so a fit that truly attains its group’s optimum cannot do worse than the group inside it. Worth saying that this is a property of the answers rather than a guarantee from the code — <code>fit_projective</code> is a local refinement from a DLT seed with no global optimality promise, which is exactly why its unrefined version scored <em>worse</em> than affine.</p>
<p>These numbers mean nothing on their own, because every extra parameter buys some fit even against pure noise. Each model needs its own floor, and the floor is not “±5 pixels” — it is whatever that model scores between two independently jittered copies of one frame, where the true difference is zero by construction.</p>
<div id="ladder-floor" class="cell" data-execution_count="8">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">''</span><span class="sc">:12}{</span><span class="st">'observed'</span><span class="sc">:&gt;10}{</span><span class="st">'noise floor'</span><span class="sc">:&gt;13}{</span><span class="st">'ratio'</span><span class="sc">:&gt;8}</span><span class="ss">"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, _, fit <span class="kw">in</span> MODELS:</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> []</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> base <span class="kw">in</span> X:</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">120</span>):</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>            a <span class="op">=</span> base <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="dv">5</span>, base.shape)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>            b <span class="op">=</span> base <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="dv">5</span>, base.shape)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>            scores.append(rms(fit(a, b), b))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    floor, seen <span class="op">=</span> <span class="bu">float</span>(np.mean(scores)), <span class="bu">float</span>(np.mean(totals[name]))</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:12}{</span>seen<span class="sc">:10.2f}{</span>floor<span class="sc">:13.2f}{</span>seen <span class="op">/</span> floor<span class="sc">:7.1f}</span><span class="ss">x"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              observed  noise floor   ratio
similarity       12.52         7.93    1.6x
affine            8.23         6.68    1.2x
projective        6.69         5.75    1.2x</code></pre>
</div>
</div>
<p>That reframes the ladder. Similarity leaves 12.5 pixels against a floor of 7.9 — clearly above its own noise, and the quantitative version of what the nose angle already said. Affine drops to 8.2 against a floor of 6.7, barely above it, and projective to 6.7 against 5.8, the same ratio again.</p>
<p>So affine does not merely beat similarity: it brings the residual <strong>down to roughly what my own digitising manufactures</strong>, which is as far as this data can take it. There is nothing measurable left for the projective term to explain, and its extra 1.5 pixels are bought with two more parameters on six landmarks. The reading is that the camera was far enough away for weak perspective to hold, and <strong>affine is the smallest model that does the job</strong> — a claim about these photographs, not about cameras. With more landmarks, or a kite closer to the lens, the projective step would separate.</p>
</section>
<section id="quotient-out-the-affine-group-and-most-of-the-shape-difference-disappears" class="level2">
<h2 class="anchored" data-anchor-id="quotient-out-the-affine-group-and-most-of-the-shape-difference-disappears">Quotient out the affine group and most of the shape difference disappears</h2>
<p>If affine is the nuisance group, the fix is to quotient by it rather than by similarity — to compare configurations only up to affine maps, so the parts of the difference an affine map could have produced stop counting.</p>
<p>There is a trap here, and it cost me a wrong answer before I noticed. The obvious approach is to reuse the Procrustes loop with the rotation step swapped for a least-squares affine fit. It runs, it converges, and it reports a beautifully small residual — because the affine group can squash a configuration flat onto a line and leave it at size one while doing so. My first run drove all five sails to an aspect ratio of 0.0002 and announced that 74% of the shape variation was viewpoint. It was measuring the collapse.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Iterating affine fits to a mean is not affine Procrustes
</div>
</div>
<div class="callout-body-container callout-body">
<p>Normalising to unit centroid size stops the configurations shrinking to a point. It does not stop them flattening to a line, which has unit size too. If you swap the rotation step of a GPA loop for an affine fit, check the aspect ratio of what comes out before believing the residual.</p>
</div>
</div>
<p>The way that works is to remove the affine part in closed form instead of searching for it. Centre a configuration and rescale its two principal axes to be equal, so its second moment becomes isotropic. Any affine image of a configuration lands on the same canonical form, so what survives is exactly the non-affine part of its shape — and nothing can collapse, because the answer is isotropic by construction.</p>
<div id="whiten" class="cell" data-execution_count="9">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> remove_affine(config):</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Map a configuration to its affine-invariant canonical form."""</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    centred <span class="op">=</span> config <span class="op">-</span> config.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    u, _, _ <span class="op">=</span> np.linalg.svd(centred, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    whitened <span class="op">=</span> u <span class="op">*</span> np.sqrt(<span class="bu">len</span>(config))     <span class="co"># singular values replaced by 1</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> whitened <span class="op">/</span> np.linalg.norm(whitened)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>affine_aligned, affine_mean <span class="op">=</span> gpa(X, prepare<span class="op">=</span>remove_affine)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>affine_residual <span class="op">=</span> np.linalg.norm(affine_aligned <span class="op">-</span> affine_mean, axis<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">2</span>))</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>affine_ss <span class="op">=</span> <span class="bu">float</span>((affine_residual <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>())</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>aspect <span class="op">=</span> [np.divide(<span class="op">*</span>np.linalg.svd(c, compute_uv<span class="op">=</span><span class="va">False</span>)[::<span class="op">-</span><span class="dv">1</span>]) <span class="cf">for</span> c <span class="kw">in</span> affine_aligned]</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"aspect ratio of the aligned configurations: </span><span class="sc">{</span>np<span class="sc">.</span>mean(aspect)<span class="sc">:.3f}</span><span class="ss">  (1.0 = no collapse)"</span>)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Procrustes SS, similarity quotient: </span><span class="sc">{</span>similarity_ss<span class="sc">:.5f}</span><span class="ss">"</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Procrustes SS, affine quotient    : </span><span class="sc">{</span>affine_ss<span class="sc">:.5f}</span><span class="ss">"</span>)</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"share of shape variation the viewpoint explains: </span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> affine_ss <span class="op">/</span> similarity_ss)<span class="sc">:.1f}</span><span class="ss">%"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>aspect ratio of the aligned configurations: 1.000  (1.0 = no collapse)

Procrustes SS, similarity quotient: 0.11100
Procrustes SS, affine quotient    : 0.06839
share of shape variation the viewpoint explains: 38.4%</code></pre>
</div>
</div>
<p>Quotienting by the affine group removes 38% of the measured shape variation. That is a real number rather than a collapse — the aligned configurations keep an aspect ratio of 1.0, as the construction guarantees.</p>
<p>It is also a lot less than the 74% the broken version reported, and less than the ladder above might have led you to expect. Which raises the obvious question about the 62% still sitting there.</p>
</section>
<section id="caveat-most-of-what-is-left-is-my-own-hand" class="level2">
<h2 class="anchored" data-anchor-id="caveat-most-of-what-is-left-is-my-own-hand">Caveat: most of what is left is my own hand</h2>
<p>The remaining variation has two plausible sources, and they are not equally interesting. One is the kite: a delta sail is not a rigid plane. It billows into a dihedral under wind load, so it is really two curved panels hinged at the spine, and no two-dimensional map of any kind can align a shape that is genuinely bending in three dimensions. The other is me, placing six landmarks by eye to about ±5 pixels.</p>
<p>These are easy to tell apart, because the second one can be simulated. Take a frame, replicate it five times so the true shape difference is exactly zero, jitter every landmark, and measure the Procrustes sum of squares that digitising error alone manufactures.</p>
<p>One wrinkle before the numbers. The jitter below is Gaussian with standard deviation sigma, while my ±5 pixels was meant as a rough bound — and a Gaussian at sigma = 5 puts about a third of its points beyond 5 pixels, with an RMS displacement nearer 7. So the simulated floor at sigma = 5 is if anything a little pessimistic about my hand. That cuts against the conclusion I want, which is the right direction for a check to err in.</p>
<div id="noise-floor" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> procrustes_ss(configs, prepare):</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    aligned, mean <span class="op">=</span> gpa(configs, prepare<span class="op">=</span>prepare)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>((np.linalg.norm(aligned <span class="op">-</span> mean, axis<span class="op">=</span>(<span class="dv">1</span>, <span class="dv">2</span>)) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>())</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Every frame gets a turn as the base. Which one you pick matters: the flattest</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="co"># sails amplify jitter under the affine quotient, so a single base frame can</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># understate the floor by a factor of three.</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'sigma'</span><span class="sc">:&gt;7}{</span><span class="st">'similarity SS'</span><span class="sc">:&gt;26}{</span><span class="st">'affine SS'</span><span class="sc">:&gt;26}</span><span class="ss">"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> sigma <span class="kw">in</span> [<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">5</span>, <span class="dv">8</span>]:</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    per_base <span class="op">=</span> np.array([</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>        [np.mean([procrustes_ss(base <span class="op">+</span> rng.normal(<span class="dv">0</span>, sigma, (<span class="dv">5</span>,) <span class="op">+</span> base.shape), prepare)</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>                  <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">300</span>)])</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>         <span class="cf">for</span> prepare <span class="kw">in</span> (centre_and_scale, remove_affine)]</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> base <span class="kw">in</span> X</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    cells <span class="op">=</span> <span class="st">""</span>.join(</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>        <span class="ss">f"</span><span class="sc">{</span>per_base[:, k]<span class="sc">.</span>mean()<span class="sc">:14.4f}</span><span class="ss">  [</span><span class="sc">{</span>per_base[:, k]<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.4f}</span><span class="ss">-</span><span class="sc">{</span>per_base[:, k]<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.4f}</span><span class="ss">]"</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> k <span class="kw">in</span> (<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>sigma<span class="sc">:5.0f}</span><span class="ss">px</span><span class="sc">{</span>cells<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="sc">{</span><span class="st">'observed'</span><span class="sc">:&gt;7}{</span>similarity_ss<span class="sc">:14.4f}{</span><span class="st">''</span><span class="sc">:15}{</span>affine_ss<span class="sc">:14.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  sigma             similarity SS                 affine SS
    2px        0.0052  [0.0037-0.0063]        0.0068  [0.0031-0.0102]
    3px        0.0115  [0.0081-0.0145]        0.0151  [0.0073-0.0223]
    5px        0.0323  [0.0221-0.0409]        0.0418  [0.0197-0.0629]
    8px        0.0806  [0.0553-0.0989]        0.1075  [0.0505-0.1623]

observed        0.1110                       0.0684</code></pre>
</div>
</div>
<p>This table decides how much of the post survives, and it is worth reading the brackets rather than the means. The spread across base frames is wide, because whitening a nearly flat configuration amplifies whatever jitter you put into it — frames 1 and 2 are the most foreshortened sails, and they generate roughly three times the affine floor that frame 4 does. A simulation run off a single base frame would have hidden that entirely.</p>
<p>The similarity result holds. Observed SS is 0.111 against a sigma = 5 floor of 0.032 on average, so about three and a half times the noise — and still 2.7 times it even against the most pessimistic base frame. The similarity quotient fails for reasons that are not my handwriting.</p>
<p>The affine result does not hold. After quotienting out the affine group the residual is 0.068 against a floor of 0.042, which is 1.6 times the noise on average and only 1.1 times against the worst base frame. At sigma = 8 the floor passes the observed value outright. There is no residual here I can claim, and in particular I cannot claim the sail’s billow, which is the answer I went looking for. Measuring that would need more landmarks, placed more precisely, on a kite filling more of the frame.</p>
<p>So the defensible summary is narrower than the one I set out to write. Similarity is decisively the wrong group to quotient by, and moving to the affine group removes a large and real chunk of the disagreement between these photographs. Whether <em>anything at all</em> is left after that — the kite’s own bending, or any other departure from a flat plane under an affine camera — is below what six hand-placed landmarks can resolve, and this analysis should not be read as evidence either way.</p>
</section>
<section id="the-same-pipeline-in-rs-shapes-package" class="level2">
<h2 class="anchored" data-anchor-id="the-same-pipeline-in-rs-shapes-package">The same pipeline in R’s shapes package</h2>
<p>Everything above is hand-rolled, which makes it worth checking against an implementation nobody wrote for this post. Ian Dryden’s <a href="https://cran.r-project.org/package=shapes"><code>shapes</code></a> package is the reference implementation of this material in R — it ships <code>procGPA</code> for generalised Procrustes, <code>riemdist</code> for Riemannian distance in shape space, <code>tpsgrid</code> for thin-plate spline deformation grids, and <code>shapepca</code> for principal components of shape. What it does not do is touch the photographs: <code>tpsgrid</code> draws a deformation, it does not apply one to pixels. That comes in the next section, and needs a little more machinery.</p>
<p>The R script reads the same <code>landmarks.csv</code> and runs the same two analyses. It is not executed by the render — it runs ahead of time and commits its figures, so this post builds on a machine with no R at all — and it lives at <a href="https://github.com/project-delphi/ml-blog/blob/main/posts/kite-shape-analysis/src/shapes_analysis.R"><code>src/shapes_analysis.R</code></a>.</p>
<pre class="{r}"><code>#| eval: false
options(rgl.useNULL = TRUE)
library(shapes)

# landmarks.csv -&gt; the k x m x n array every shapes:: function expects
X &lt;- array(NA_real_, c(6, 2, 5))   # 6 landmarks, 2 coordinates, 5 frames

# Quotient out similarity. reflect = TRUE because the sail is bilaterally
# symmetric: no single photograph says which physical wing is which, so the
# labelling is a free choice and should not count as shape difference.
sim &lt;- procGPA(X, scale = TRUE, reflect = TRUE)

# Quotient out affine, in closed form -- see the callout above for why the
# iterative version collapses.
whiten &lt;- function(cfg) {
  cfg &lt;- scale(cfg, center = TRUE, scale = FALSE)
  w &lt;- svd(cfg)$u * sqrt(nrow(cfg))
  w / sqrt(sum(w^2))
}
aff &lt;- procGPA(array(apply(X, 3, whiten), dim(X)), scale = TRUE, reflect = TRUE)

# Pairwise Riemannian distance in Kendall shape space
riemdist(X[, , 1], X[, , 2])

# Deformation grids, mean shape -&gt; each frame
tpsgrid(sim$mshape, sim$rotated[, , 3], mag = 1, ngrid = 16, opt = 1)</code></pre>
<div id="r-agreement" class="cell" data-execution_count="11">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> json</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> json.load(<span class="bu">open</span>(<span class="st">"r_results.json"</span>))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"R </span><span class="sc">{</span>r[<span class="st">'r_version'</span>]<span class="sc">}</span><span class="ss">, shapes </span><span class="sc">{</span>r[<span class="st">'shapes_version'</span>]<span class="sc">}</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">''</span><span class="sc">:22}{</span><span class="st">'R'</span><span class="sc">:&gt;12}{</span><span class="st">'Python'</span><span class="sc">:&gt;12}</span><span class="ss">"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'similarity SS'</span><span class="sc">:22}{</span>r[<span class="st">'similarity'</span>][<span class="st">'procrustes_ss'</span>]<span class="sc">:12.5f}{</span>similarity_ss<span class="sc">:12.5f}</span><span class="ss">"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'affine SS'</span><span class="sc">:22}{</span>r[<span class="st">'affine'</span>][<span class="st">'procrustes_ss'</span>]<span class="sc">:12.5f}{</span>affine_ss<span class="sc">:12.5f}</span><span class="ss">"</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'uniform share'</span><span class="sc">:22}{</span><span class="dv">100</span> <span class="op">*</span> r[<span class="st">'uniform_share'</span>]<span class="sc">:11.1f}</span><span class="ss">%</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> affine_ss <span class="op">/</span> similarity_ss)<span class="sc">:11.1f}</span><span class="ss">%"</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>riem <span class="op">=</span> np.array(r[<span class="st">"riemannian"</span>])</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">pairwise Riemannian distance in shape space (R's riemdist):"</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.<span class="bu">round</span>(riem, <span class="dv">3</span>))</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">largest: </span><span class="sc">{</span>riem<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss"> between frames "</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>unravel_index(riem.argmax(), riem.shape)[<span class="dv">0</span>] <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss"> and "</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>unravel_index(riem.argmax(), riem.shape)[<span class="dv">1</span>] <span class="op">+</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>R 4.0.5, shapes 1.2.6

                                 R      Python
similarity SS              0.11100     0.11100
affine SS                  0.06839     0.06839
uniform share                38.4%       38.4%

pairwise Riemannian distance in shape space (R's riemdist):
[[0.    0.124 0.249 0.278 0.227]
 [0.124 0.    0.298 0.326 0.237]
 [0.249 0.298 0.    0.16  0.187]
 [0.278 0.326 0.16  0.    0.192]
 [0.227 0.237 0.187 0.192 0.   ]]

largest: 0.326 between frames 2 and 4</code></pre>
</div>
</div>
<p>The two pipelines agree to five decimal places, which is the point of running both.</p>
<p>The Riemannian distances are worth reading on their own. They measure separation along the curved shape space rather than straight through it, and the largest is 0.33 — between two photographs of one rigid object, nine seconds apart. That single number is the whole problem in one line.</p>
<p>Before the grids, the plainest view <code>shapes</code> offers. <code>plotshapes</code> draws configurations on one set of axes: on the left the five frames as digitised, scattered across the photograph in raw pixel coordinates, and on the right the same five after <code>procGPA</code> has removed position, size and rotation.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./fig-r-plotshapes.png" class="img-fluid figure-img"></p>
<figcaption><code>plotshapes</code> on the raw landmarks and after <code>procGPA</code>. Removing position, size and rotation brings the five configurations onto one another — and the scatter still visible on the right is the 0.111 the post has been quoting all along.</figcaption>
</figure>
</div>
<p>The deformation grids show the same story pictorially. <code>tpsgrid</code> draws the thin-plate spline that carries the mean shape onto one frame: a grid drawn on the average kite, then bent so its landmarks land on that frame’s.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./fig-r-tps-raw.png" class="img-fluid figure-img"></p>
<figcaption>Thin-plate splines carrying the mean shape onto each frame, after quotienting out <strong>similarity</strong> only. The grids have to absorb the entire viewpoint change, so they shear and bow across their whole width.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./fig-r-tps-rectified.png" class="img-fluid figure-img"></p>
<figcaption>The same splines after quotienting out <strong>affine</strong> maps. The global shear is gone and what remains is local and much milder — though, per the caveat above, most of it is digitising noise rather than the kite.</figcaption>
</figure>
</div>
<p>This is what “the thin-plate splines were not good” looks like when you diagnose it rather than tune it. TPS was never the problem. It was faithfully drawing a deformation that was mostly camera.</p>
</section>
<section id="warping-the-photographs-themselves-shows-the-size-of-what-was-fixed" class="level2">
<h2 class="anchored" data-anchor-id="warping-the-photographs-themselves-shows-the-size-of-what-was-fixed">Warping the photographs themselves shows the size of what was fixed</h2>
<p>Everything so far has been six points per frame. The grids above deform an abstract mean, and a reader has to take on trust that this corresponds to anything in the sky. The thin-plate spline that bends a grid will just as happily bend an image, so the honest way to finish is to send the photographs through the same pipeline and look at them.</p>
<p>Each frame gets transported into one shared panel twice — once by the best similarity map, once by the best affine map — and then the animation morphs between consecutive frames, interpolating the landmarks linearly and bending both photographs onto the intermediate shape before cross-dissolving. That last part is the spline doing the work that <code>tpsgrid</code> only illustrates.</p>
<pre class="{r}"><code>#| eval: false
# U(r) = r^2 log r^2, the 2D biharmonic kernel: the shape a thin metal plate
# takes when pinned at the landmarks. Solving for an affine part plus one
# radial term per landmark gives the smoothest map carrying every source
# landmark exactly onto its target.
tps_kernel &lt;- function(d2) ifelse(d2 &gt; 0, d2 * log(d2), 0)

tps_fit &lt;- function(src, dst) {
  K &lt;- tps_kernel(as.matrix(dist(src))^2)
  P &lt;- cbind(1, src)
  L &lt;- rbind(cbind(K, P), cbind(t(P), matrix(0, 3, 3)))
  W &lt;- solve(L, rbind(dst, matrix(0, 3, 2)))
  list(src = src, w = W[seq_len(nrow(src)), ], a = W[nrow(src) + 1:3, ])
}

tps_apply &lt;- function(fit, pts) {
  d2 &lt;- outer(pts[, 1], fit$src[, 1], "-")^2 + outer(pts[, 2], fit$src[, 2], "-")^2
  cbind(1, pts) %*% fit$a + tps_kernel(d2) %*% fit$w
}

# Warping an image is the same map run backwards: for every output pixel, ask
# where in the original photograph it came from, then sample there.
warp &lt;- function(photo, from, to) {
  sample_image(photo, tps_apply(tps_fit(to, from), output_grid))
}</code></pre>
<p>The static version first, because it carries the finding on its own and an animation should never be the only copy of a result.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./fig-r-warped-stack.png" class="img-fluid figure-img"></p>
<figcaption>Five photographs of one kite. Top: a plain window on each photograph, the same size in source pixels every time, centred on the kite so it stays in frame — orientation and relative size untouched. Middle: transported into a shared frame by the best similarity map. Bottom: by the best affine map.</figcaption>
</figure>
</div>
<p>The top-to-middle step is the dramatic one, and it is worth being clear that this is <em>not</em> the post’s argument — it is just Procrustes doing the job it has always been able to do. Size and rotation come off, and five wildly different views become five broadly comparable ones. Position is already gone in the top row, since a window that did not follow the kite would lose it entirely.</p>
<p>The middle-to-bottom step is the post’s argument, and it is small. That is the correct size. A 38% reduction in Procrustes sum of squares does not look like much when you paint it onto pixels, and pretending otherwise would be the wrong lesson to take from this.</p>
<section id="caveat-outside-six-landmarks-the-spline-is-guessing" class="level3">
<h3 class="anchored" data-anchor-id="caveat-outside-six-landmarks-the-spline-is-guessing">Caveat: outside six landmarks the spline is guessing</h3>
<p>The streamers tear, smear and swirl in both warped rows, and that is not a bug to be tuned out. A thin-plate spline is pinned only where you pin it. Inside the hull of the six sail landmarks it interpolates between constraints; outside, it extrapolates from none, and the ribbons trailing off the back edge are entirely outside. They are also genuinely non-rigid, so there is no correspondence out there to get right in the first place.</p>
<p>Read that way the smearing is informative: it marks exactly where this analysis has something to say and where it does not.</p>
</section>
<section id="the-animation-and-what-it-can-and-cannot-show" class="level3">
<h3 class="anchored" data-anchor-id="the-animation-and-what-it-can-and-cannot-show">The animation, and what it can and cannot show</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./fig-r-morph.gif" class="img-fluid figure-img"></p>
<figcaption>Five photographs morphing through a common frame, aligned by similarity (left) and by affine (right). The white dashed hexagon is the mean shape, fixed in both panels. Spikes run from each mean landmark to where that frame’s landmark actually lands, <strong>drawn at three times life size</strong> — <code>tpsgrid</code> has a <code>mag</code> argument for the same reason. Shorter spikes on the right are the affine map’s 28% improvement in landmark registration.</figcaption>
</figure>
</div>
<p>The magnification is not showmanship, and the reason is worth stating because it is a result in itself. Measured on the pixels alone, the two panels are indistinguishable. Averaged over the landmarks’ bounding box — the sail itself, rather than the empty sky around it — the standard deviation across the five aligned frames is 0.127 per pixel under similarity and 0.128 under affine. Taken over the whole panel it is 0.072 and 0.074. Whichever region you pick, the affine version comes out a hair <em>worse</em>. Nothing to see.</p>
<p>That is not because the affine map fails. It is because pixel disagreement between these photographs is dominated by things no two-dimensional alignment can touch — which colour bands a given viewpoint exposes, how the light falls, and the streamers, which are not in correspondence at all. The affine map improves landmark registration from 7.0 to 5.1 panel pixels, roughly a quarter, and on a 220-pixel panel a two-pixel improvement is invisible without help.</p>
<p>So the animation shows two true things at once. The kite really does settle into a common frame, which is what alignment is for. And the improvement this post spent its length establishing is real, reproducible, and far too small to see unless you draw it. Both are worth knowing before trusting an alignment because the overlay looked convincing.</p>
</section>
</section>
<section id="shape-analysis-only-subtracts-what-you-tell-it-to" class="level2">
<h2 class="anchored" data-anchor-id="shape-analysis-only-subtracts-what-you-tell-it-to">Shape analysis only subtracts what you tell it to</h2>
<p>The five photographs are of one rigid kite over nine seconds, and the pipeline reports them as five shapes up to 0.33 apart. Nothing in that is a defect of Kendall shape analysis. It removes translation, size and rotation, exactly as advertised, and it removed them here — the failure is that those three were not the whole nuisance.</p>
<p>That is the part worth carrying away. On a lab bench the similarity group usually <em>is</em> the whole nuisance: the specimen is flat, the camera is square to it, and moving the ruler is the only thing that varies. Point a lens at something in the air and the nuisance group grows, silently. Procrustes will not tell you this has happened. It will converge, return a mean shape, and hand you a number.</p>
<p>Three cheap habits catch it. Measure something the group you are quotienting by cannot change — an angle, for similarity — and check whether it holds still. Simulate your own measurement error before believing any residual, because the number that decided how much of this post I could defend was not the Procrustes sum of squares; it was ±5 pixels. And do not let a picture settle it either way: warping the photographs into register made a real 38% improvement look like nothing at all, and a convincing overlay would have hidden the same gap just as easily in the other direction.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/kite-shape-analysis/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>