<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-10-01">
<meta name="description" content="Two predictors that say nearly the same thing leave least squares with one combination of coefficients it can pin down and one it cannot. The geometry of two columns, the singular values behind it, what the condition number bounds, and the same instability in the Longley and diabetes data, with four three.js scenes to turn.">

<title>Collinearity, Part 1: The Direction the Data Cannot See – Synthetic Musings</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a9fbfb7a887b62f4d313264b6afc3d0d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-784891f9eaa39f9ffae573c9e0f86e17.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../../widget-kit/kit.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="post.css">
<meta property="og:title" content="Collinearity, Part 1: The Direction the Data Cannot See – Synthetic Musings">
<meta property="og:description" content="Two predictors that say nearly the same thing leave least squares with one combination of coefficients it can pin down and one it cannot. The geometry of two columns, the singular values behind it, what the condition number bounds, and the same instability in the Longley and diabetes data, with four three.js scenes to turn.">
<meta property="og:image" content="https://project-delphi.github.io/ml-blog/posts/collinearity/cover.png">
<meta property="og:site_name" content="Synthetic Musings">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:title" content="Collinearity, Part 1: The Direction the Data Cannot See – Synthetic Musings">
<meta name="twitter:description" content="Two predictors that say nearly the same thing leave least squares with one combination of coefficients it can pin down and one it cannot. The geometry of two columns, the singular values behind it, what the condition number bounds, and the same instability in the Longley and diabetes data, with four three.js scenes to turn.">
<meta name="twitter:image" content="https://project-delphi.github.io/ml-blog/posts/collinearity/cover.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="630">
<meta name="twitter:image-width" content="1200">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Synthetic Musings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="Home">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Collinearity, Part 1: The Direction the Data Cannot See</h1>
            <p class="subtitle lead">Why a 2% nudge to the target moves a coefficient by 360% and leaves the fit where it was</p>
                  <div>
        <div class="description">
          Two predictors that say nearly the same thing leave least squares with one combination of coefficients it can pin down and one it cannot. The geometry of two columns, the singular values behind it, what the condition number bounds, and the same instability in the Longley and diabetes data, with four three.js scenes to turn.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Linear Algebra</div>
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Numerical Methods</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">October 1, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-symptom" id="toc-the-symptom" class="nav-link active" data-scroll-target="#the-symptom"><span class="header-section-number">1</span> The symptom</a></li>
  <li><a href="#notation" id="toc-notation" class="nav-link" data-scroll-target="#notation"><span class="header-section-number">2</span> Notation</a></li>
  <li><a href="#which-2" id="toc-which-2" class="nav-link" data-scroll-target="#which-2"><span class="header-section-number">3</span> Which 2%</a></li>
  <li><a href="#the-linear-algebra" id="toc-the-linear-algebra" class="nav-link" data-scroll-target="#the-linear-algebra"><span class="header-section-number">4</span> The linear algebra</a>
  <ul class="collapse">
  <li><a href="#sum-and-difference" id="toc-sum-and-difference" class="nav-link" data-scroll-target="#sum-and-difference"><span class="header-section-number">4.1</span> Sum and difference</a></li>
  <li><a href="#least-squares-in-the-singular-basis" id="toc-least-squares-in-the-singular-basis" class="nav-link" data-scroll-target="#least-squares-in-the-singular-basis"><span class="header-section-number">4.2</span> Least squares in the singular basis</a></li>
  <li><a href="#many-noise-draws" id="toc-many-noise-draws" class="nav-link" data-scroll-target="#many-noise-draws"><span class="header-section-number">4.3</span> Many noise draws</a></li>
  </ul></li>
  <li><a href="#the-condition-number" id="toc-the-condition-number" class="nav-link" data-scroll-target="#the-condition-number"><span class="header-section-number">5</span> The condition number</a>
  <ul class="collapse">
  <li><a href="#definition-and-the-two-column-value" id="toc-definition-and-the-two-column-value" class="nav-link" data-scroll-target="#definition-and-the-two-column-value"><span class="header-section-number">5.1</span> Definition and the two-column value</a></li>
  <li><a href="#what-it-bounds" id="toc-what-it-bounds" class="nav-link" data-scroll-target="#what-it-bounds"><span class="header-section-number">5.2</span> What it bounds</a></li>
  <li><a href="#a-change-to-x-or-a-change-to-y" id="toc-a-change-to-x-or-a-change-to-y" class="nav-link" data-scroll-target="#a-change-to-x-or-a-change-to-y"><span class="header-section-number">5.3</span> A change to X or a change to y</a></li>
  <li><a href="#floating-point" id="toc-floating-point" class="nav-link" data-scroll-target="#floating-point"><span class="header-section-number">5.4</span> Floating point</a></li>
  </ul></li>
  <li><a href="#the-loss-surface" id="toc-the-loss-surface" class="nav-link" data-scroll-target="#the-loss-surface"><span class="header-section-number">6</span> The loss surface</a></li>
  <li><a href="#the-statistics" id="toc-the-statistics" class="nav-link" data-scroll-target="#the-statistics"><span class="header-section-number">7</span> The statistics</a></li>
  <li><a href="#more-than-two-columns" id="toc-more-than-two-columns" class="nav-link" data-scroll-target="#more-than-two-columns"><span class="header-section-number">8</span> More than two columns</a></li>
  <li><a href="#real-data" id="toc-real-data" class="nav-link" data-scroll-target="#real-data"><span class="header-section-number">9</span> Real data</a>
  <ul class="collapse">
  <li><a href="#longley-two-columns-then-six" id="toc-longley-two-columns-then-six" class="nav-link" data-scroll-target="#longley-two-columns-then-six"><span class="header-section-number">9.1</span> Longley: two columns, then six</a></li>
  <li><a href="#diabetes-an-identity-among-four-columns" id="toc-diabetes-an-identity-among-four-columns" class="nav-link" data-scroll-target="#diabetes-an-identity-among-four-columns"><span class="header-section-number">9.2</span> Diabetes: an identity among four columns</a></li>
  </ul></li>
  <li><a href="#what-breaks-and-what-does-not" id="toc-what-breaks-and-what-does-not" class="nav-link" data-scroll-target="#what-breaks-and-what-does-not"><span class="header-section-number">10</span> What breaks and what does not</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">11</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/collinearity/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Collinearity, Part 1: The Direction the Data Cannot See</figcaption>
</figure>
</div>
<p>When two predictors carry nearly the same information, least squares still predicts well, but it can no longer say how much each predictor contributes: the individual coefficients swing with every small change to the data.</p>
<p>The symptom is familiar. A regression is refitted with one more month of data. Its predictions barely move and its <span class="math inline">\(R^2\)</span> is the same to three decimals, yet one coefficient has doubled and another has changed sign. The software is working. The data pin down some combinations of the coefficients tightly and others hardly at all, and a nearly collinear pair of columns is the smallest example of the second kind.</p>
<p>The questions came from one scene in an interactive <a href="https://project-delphi.github.io/tensors-workshop/interactive/linalg-stage.html#collinear">linear-algebra stage</a>. A button there moves a target vector by 2%, and with the two predictor columns half a degree apart the fitted coefficients go from <span class="math inline">\((1.41, 0)\)</span> to <span class="math inline">\((-1.83, 3.24)\)</span>.</p>
<ul>
<li>2% of what?</li>
<li>Why is the response violent only when the columns are nearly parallel?</li>
<li>Do the fitted values and the loss move as well?</li>
<li>Is a change to the predictors worse than a change to the target?</li>
<li>What changes with more than two columns, and with real data?</li>
</ul>
<p><a href="../collinearity-remedies/">Part 2</a> covers what to do about it: ridge, principal components, the lasso, and the elastic net.</p>
<section id="the-symptom" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="the-symptom"><span class="header-section-number">1</span> The symptom</h2>
<p>The first scene uses synthetic data, so the cause can be turned up and down.</p>
<ul>
<li><strong>Rows.</strong> <span class="math inline">\(n = 40\)</span>.</li>
<li><strong>Predictors.</strong> Two columns <span class="math inline">\(x_1, x_2\)</span>, centred, with standard deviation 1 and correlation <span class="math inline">\(r\)</span>.</li>
<li><strong>Target.</strong> <span class="math inline">\(y = x_1 + x_2 + \varepsilon\)</span>, with <span class="math inline">\(\varepsilon\)</span> Gaussian noise of standard deviation 0.6.</li>
<li><strong>What it stands in for.</strong> Any pair of measurements that track each other: two assays of the same quantity, a country’s output and its population, total and LDL cholesterol.</li>
</ul>
<p>Changing <span class="math inline">\(r\)</span> turns <span class="math inline">\(x_2\)</span> towards <span class="math inline">\(x_1\)</span> and leaves the noise, the true coefficients <span class="math inline">\((1, 1)\)</span>, and the 40 values of <span class="math inline">\(x_1\)</span> as they were.</p>
<div id="widget-fence">

</div>
<script src="../../widget-kit/stage.js"></script>
<script src="model.js"></script>
<script src="widgets.js"></script>
<p>Each sheet is one least-squares plane <span class="math inline">\(\hat y = \hat\beta_1 x_1 + \hat\beta_2 x_2\)</span>, fitted to the same <span class="math inline">\(x\)</span> values under a different draw of the noise.</p>
<ol type="1">
<li>Press <strong>r = 0</strong>. The grey shadows of the data fill the floor, the 25 planes lie almost on top of each other, and the <span class="math inline">\(x_1\)</span> coefficient has a standard deviation of 0.09 over 200 noise draws.</li>
<li>Press <strong>0.99</strong>. The shadows collapse onto a narrow band along the diagonal. The planes still agree above that band and fan out away from it, as if hinged on a fence that runs over the data. The standard deviation of the <span class="math inline">\(x_1\)</span> coefficient is 0.68.</li>
<li>Read the sum. The standard deviation of <span class="math inline">\(\hat\beta_1 + \hat\beta_2\)</span> is 0.09, lower than the 0.13 it had at <span class="math inline">\(r = 0\)</span>.</li>
<li>Compare the two vertical lines. At <span class="math inline">\((1.5, 1.5)\)</span>, a point like the data, the predictions have standard deviation 0.14. At <span class="math inline">\((1.5, -1.5)\)</span>, where the predictors disagree, it is 2.05.</li>
<li>Press <strong>0.999</strong>, then <strong>New noise</strong> four times. The amber points barely move, and the solid plane’s coefficients go from <span class="math inline">\((1.87, 0.00)\)</span> to <span class="math inline">\((0.63, 1.27)\)</span>, <span class="math inline">\((0.57, 1.47)\)</span>, <span class="math inline">\((3.73, -1.76)\)</span> and <span class="math inline">\((-2.24, 4.29)\)</span>. Both true values are 1.</li>
</ol>
<p>The planes pivot because the data say where the plane is along the fence and almost nothing about its tilt across it.</p>
</section>
<section id="notation" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="notation"><span class="header-section-number">2</span> Notation</h2>
<ul>
<li><span class="math inline">\(X = [\,x_1 \;\; x_2\,] \in \mathbb{R}^{n \times 2}\)</span>, the predictor columns, centred and of equal length.</li>
<li><span class="math inline">\(y \in \mathbb{R}^n\)</span>, the target.</li>
<li><span class="math inline">\(\hat\beta = \arg\min_\beta \lVert y - X\beta \rVert^2\)</span>, the least-squares coefficients, and <span class="math inline">\(\hat y = X\hat\beta\)</span>, the fitted vector.</li>
<li><span class="math inline">\(\theta\)</span>, the angle between <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> as vectors in <span class="math inline">\(\mathbb{R}^n\)</span>. For centred columns <span class="math inline">\(\cos\theta = r\)</span>, the sample correlation.</li>
</ul>
<p><strong>Collinear</strong> means <span class="math inline">\(\theta = 0\)</span>: one column is a multiple of the other, <span class="math inline">\(X^\top X\)</span> is singular, and no unique <span class="math inline">\(\hat\beta\)</span> exists. <strong>Nearly collinear</strong> means <span class="math inline">\(\theta\)</span> is small.</p>
<p>Correlation compresses the scale near 1.</p>
<div class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> [<span class="fl">0.0</span>, <span class="fl">0.5</span>, <span class="fl">0.9</span>, <span class="fl">0.99</span>, <span class="fl">0.999</span>, <span class="fl">0.9999</span>]:</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>    t <span class="op">=</span> np.arccos(r)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>    rows.append(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>        {</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>            <span class="st">"$r$"</span>: <span class="ss">f"</span><span class="sc">{</span>r<span class="sc">:g}</span><span class="ss">"</span>,</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>            <span class="st">"$</span><span class="ch">\\</span><span class="st">theta$"</span>: <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>degrees(t)<span class="sc">:.2f}</span><span class="ss">°"</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>            <span class="st">"$</span><span class="ch">\\</span><span class="st">sigma_2$"</span>: <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>sqrt(<span class="dv">2</span>) <span class="op">*</span> np<span class="sc">.</span>sin(t <span class="op">/</span> <span class="dv">2</span>)<span class="sc">:.4f}</span><span class="ss">"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>            <span class="st">"$</span><span class="ch">\\</span><span class="st">kappa = </span><span class="ch">\\</span><span class="st">cot(</span><span class="ch">\\</span><span class="st">theta/2)$"</span>: <span class="ss">f"</span><span class="sc">{</span><span class="dv">1</span> <span class="op">/</span> np<span class="sc">.</span>tan(t <span class="op">/</span> <span class="dv">2</span>)<span class="sc">:.1f}</span><span class="ss">"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>            <span class="st">"VIF $= 1/</span><span class="ch">\\</span><span class="st">sin^2</span><span class="ch">\\</span><span class="st">theta$"</span>: <span class="ss">f"</span><span class="sc">{</span><span class="dv">1</span> <span class="op">/</span> np<span class="sc">.</span>sin(t) <span class="op">**</span> <span class="dv">2</span><span class="sc">:,.1f}</span><span class="ss">"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>md(pd.DataFrame(rows), index<span class="op">=</span><span class="va">False</span>, colalign<span class="op">=</span>(<span class="st">"right"</span>,) <span class="op">*</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-angles" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="2">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-angles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Correlation, the angle between the two columns, the smaller singular value of <span class="math inline">\(X\)</span> for unit-length columns, the condition number, and the variance inflation factor. The last three are derived in the sections that follow.
</figcaption>
<div aria-describedby="tbl-angles-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="2">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 32%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(r\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\theta\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\sigma_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\kappa = \cot(\theta/2)\)</span></th>
<th style="text-align: right;">VIF <span class="math inline">\(= 1/\sin^2\theta\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">90.00°</td>
<td style="text-align: right;">1.0000</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">1.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">60.00°</td>
<td style="text-align: right;">0.7071</td>
<td style="text-align: right;">1.7</td>
<td style="text-align: right;">1.3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.9</td>
<td style="text-align: right;">25.84°</td>
<td style="text-align: right;">0.3162</td>
<td style="text-align: right;">4.4</td>
<td style="text-align: right;">5.3</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">8.11°</td>
<td style="text-align: right;">0.1000</td>
<td style="text-align: right;">14.1</td>
<td style="text-align: right;">50.3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">0.999</td>
<td style="text-align: right;">2.56°</td>
<td style="text-align: right;">0.0316</td>
<td style="text-align: right;">44.7</td>
<td style="text-align: right;">500.3</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.9999</td>
<td style="text-align: right;">0.81°</td>
<td style="text-align: right;">0.0100</td>
<td style="text-align: right;">141.4</td>
<td style="text-align: right;">5,000.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>A correlation of 0.9 sounds close to collinear and is 26° apart. The instability starts in earnest at 0.99.</p>
</section>
<section id="which-2" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="which-2"><span class="header-section-number">3</span> Which 2%</h2>
<p>With <span class="math inline">\(n\)</span> observations, <span class="math inline">\(x_1\)</span>, <span class="math inline">\(x_2\)</span> and <span class="math inline">\(y\)</span> are three arrows in <span class="math inline">\(\mathbb{R}^n\)</span>, and least squares is a projection.</p>
<ul>
<li>The columns span a plane. <span class="math inline">\(\hat y\)</span> is the point of that plane closest to <span class="math inline">\(y\)</span>: its shadow.</li>
<li>The coefficients are the coordinates of <span class="math inline">\(\hat y\)</span> in the basis <span class="math inline">\((x_1, x_2)\)</span>: go <span class="math inline">\(\hat\beta_1\)</span> steps along <span class="math inline">\(x_1\)</span>, then <span class="math inline">\(\hat\beta_2\)</span> steps along <span class="math inline">\(x_2\)</span>.</li>
<li>The residual <span class="math inline">\(y - \hat y\)</span> is perpendicular to the plane, and its squared length is the minimum loss.</li>
</ul>
<p>With <span class="math inline">\(n = 3\)</span> the picture fits on a screen. The scene uses <span class="math inline">\(x_1 = (1, 0, 0)\)</span>, <span class="math inline">\(x_2 = (\cos\theta, \sin\theta, 0)\)</span> and <span class="math inline">\(y = (1.4, 0, 0.7)\)</span>, a synthetic target chosen so that <span class="math inline">\(\hat\beta = (1.4, 0)\)</span> at every angle before any nudge.</p>
<div id="widget-nudge">

</div>
<p>The three buttons add a vector <span class="math inline">\(\delta\)</span> with <span class="math inline">\(\lVert\delta\rVert = 0.02\,\lVert y\rVert\)</span> to <span class="math inline">\(y\)</span>. That is the 2%: a change in the target of 2% of its own length. Its direction decides what happens.</p>
<ol type="1">
<li>Press <strong>0.99</strong>, then <strong>out of the floor</strong>. The coefficients do not move. The squared residual grows by 9.1%.</li>
<li>Press <strong>along the columns</strong>. <span class="math inline">\(\hat y\)</span> moves by 2.2% of its length and the coefficients by 1.6%.</li>
<li>Press <strong>across them</strong>. <span class="math inline">\(\hat y\)</span> moves by the same 2.2%. The coefficients move by 22%.</li>
<li>Keep <strong>across them</strong> and press <strong>0.999</strong>, then <strong>θ = 0.5°</strong>. The change in the coefficients is 71%, then 362%: from <span class="math inline">\((1.40, 0)\)</span> to <span class="math inline">\((-2.19, 3.59)\)</span>. The route to <span class="math inline">\(\hat y\)</span> now runs 2.19 units backwards along <span class="math inline">\(x_1\)</span> and 3.59 units forwards along <span class="math inline">\(x_2\)</span> to land 0.03 from where it started.</li>
</ol>
<div id="tbl-nudge" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-nudge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: What a nudge to <span class="math inline">\(y\)</span> does, by direction.
</figcaption>
<div aria-describedby="tbl-nudge-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Nudge <span class="math inline">\(\delta\)</span></th>
<th>Fitted vector <span class="math inline">\(\hat y\)</span></th>
<th>Coefficients <span class="math inline">\(\hat\beta\)</span></th>
<th>Minimum loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>out of the column plane</td>
<td>unchanged</td>
<td>unchanged</td>
<td>changes</td>
</tr>
<tr class="even">
<td>in the plane, along the columns</td>
<td>moves by <span class="math inline">\(\lVert\delta\rVert\)</span></td>
<td>move a little</td>
<td>unchanged</td>
</tr>
<tr class="odd">
<td>in the plane, across the columns</td>
<td>moves by <span class="math inline">\(\lVert\delta\rVert\)</span></td>
<td>move by <span class="math inline">\(\lVert\delta\rVert/\sigma_2\)</span></td>
<td>unchanged</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The fitted vector is never the unstable part. Its coordinates in a basis of two nearly parallel arrows are.</p>
</section>
<section id="the-linear-algebra" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="the-linear-algebra"><span class="header-section-number">4</span> The linear algebra</h2>
<section id="sum-and-difference" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="sum-and-difference"><span class="header-section-number">4.1</span> Sum and difference</h3>
<p>Take the columns to have length 1. Their Gram matrix and its eigenvectors are</p>
<p><span class="math display">\[
X^\top X = \begin{bmatrix} 1 &amp; \cos\theta \\ \cos\theta &amp; 1 \end{bmatrix},
\qquad
v_1 = \tfrac{1}{\sqrt 2}\begin{bmatrix} 1 \\ 1 \end{bmatrix},\;\;
v_2 = \tfrac{1}{\sqrt 2}\begin{bmatrix} -1 \\ 1 \end{bmatrix},
\]</span></p>
<p>with eigenvalues <span class="math inline">\(1 + \cos\theta\)</span> and <span class="math inline">\(1 - \cos\theta\)</span>. The singular values of <span class="math inline">\(X\)</span> are their square roots:</p>
<p><span class="math display">\[
\sigma_1 = \sqrt{1 + \cos\theta} = \sqrt 2\,\cos\tfrac{\theta}{2},
\qquad
\sigma_2 = \sqrt{1 - \cos\theta} = \sqrt 2\,\sin\tfrac{\theta}{2}.
\]</span></p>
<ul>
<li><span class="math inline">\(X v_1 = (x_1 + x_2)/\sqrt 2\)</span> has length <span class="math inline">\(\sigma_1\)</span>, between 1 and <span class="math inline">\(\sqrt 2\)</span>. Raising both coefficients together moves the fitted vector a long way.</li>
<li><span class="math inline">\(X v_2 = (x_2 - x_1)/\sqrt 2\)</span> has length <span class="math inline">\(\sigma_2 \approx \theta/\sqrt 2\)</span>. Raising one coefficient and lowering the other by the same amount moves the fitted vector by almost nothing, because the two columns nearly cancel.</li>
</ul>
<p><span class="math inline">\(v_2\)</span> is the direction the data cannot see. A unit step along it changes every fitted value by a total length of <span class="math inline">\(\sigma_2\)</span>, so the data hold almost no evidence for or against that step.</p>
</section>
<section id="least-squares-in-the-singular-basis" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="least-squares-in-the-singular-basis"><span class="header-section-number">4.2</span> Least squares in the singular basis</h3>
<p>Write the singular value decomposition <span class="math inline">\(X = \sigma_1 u_1 v_1^\top + \sigma_2 u_2 v_2^\top\)</span>, with <span class="math inline">\(u_1, u_2\)</span> the unit vectors along <span class="math inline">\(x_1 + x_2\)</span> and <span class="math inline">\(x_2 - x_1\)</span>. Then</p>
<p><span class="math display">\[
\hat\beta = \frac{u_1^\top y}{\sigma_1}\, v_1 + \frac{u_2^\top y}{\sigma_2}\, v_2 .
\]</span></p>
<ul>
<li><span class="math inline">\(u_1^\top y / \sigma_1\)</span> sets the sum <span class="math inline">\(\hat\beta_1 + \hat\beta_2\)</span>.</li>
<li><span class="math inline">\(u_2^\top y / \sigma_2\)</span> sets the difference <span class="math inline">\(\hat\beta_2 - \hat\beta_1\)</span>.</li>
<li>A nudge <span class="math inline">\(\delta\)</span> changes the coefficients by <span class="math inline">\((u_1^\top\delta/\sigma_1)\,v_1 + (u_2^\top\delta/\sigma_2)\,v_2\)</span>. The part of <span class="math inline">\(\delta\)</span> along <span class="math inline">\(u_2\)</span> is divided by <span class="math inline">\(\sigma_2\)</span>.</li>
</ul>
<p>That accounts for the scene.</p>
<ul>
<li>The target has length 1.565, so the nudge has length 0.0313.</li>
<li>At <span class="math inline">\(\theta = 0.5°\)</span> the smaller singular value <span class="math inline">\(\sigma_2\)</span> is 0.00617.</li>
<li>A nudge along <span class="math inline">\(u_2\)</span> moves the coefficients by 0.0313 ÷ 0.00617 = 5.07, which is 362% of <span class="math inline">\(\lVert\hat\beta\rVert = 1.4\)</span>.</li>
<li>The same nudge along <span class="math inline">\(u_1\)</span> moves them by 0.0221.</li>
</ul>
<p>The scene that prompted the questions uses a nudge perpendicular to <span class="math inline">\(x_1\)</span>, which lies almost entirely along <span class="math inline">\(u_2\)</span> at small angles, and a target with <span class="math inline">\(\lVert\hat\beta\rVert = \sqrt 2\)</span>: the same division, giving 324% at half a degree.</p>
</section>
<section id="many-noise-draws" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="many-noise-draws"><span class="header-section-number">4.3</span> Many noise draws</h3>
<p>Random noise has a component along <span class="math inline">\(u_2\)</span> in every sample, so repeated samples scatter the coefficients along <span class="math inline">\(v_2\)</span>.</p>
<div id="cell-fig-cloud" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>n, sigma, beta_true <span class="op">=</span> <span class="dv">40</span>, <span class="fl">0.6</span>, np.array([<span class="fl">1.0</span>, <span class="fl">1.0</span>])</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> pair(theta_deg, n, rng):</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Two centred unit-length columns at angle theta."""</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    Z <span class="op">=</span> rng.standard_normal((n, <span class="dv">2</span>))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    Z <span class="op">-=</span> Z.mean(<span class="dv">0</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    Q, _ <span class="op">=</span> np.linalg.qr(Z)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    t <span class="op">=</span> np.deg2rad(theta_deg)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.column_stack([Q[:, <span class="dv">0</span>], np.cos(t) <span class="op">*</span> Q[:, <span class="dv">0</span>] <span class="op">+</span> np.sin(t) <span class="op">*</span> Q[:, <span class="dv">1</span>]])</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>cloud <span class="op">=</span> {}</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="fl">7.4</span>, <span class="fl">2.9</span>), sharex<span class="op">=</span><span class="va">True</span>, sharey<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, r <span class="kw">in</span> <span class="bu">zip</span>(axes, [<span class="fl">0.0</span>, <span class="fl">0.9</span>, <span class="fl">0.99</span>]):</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    theta <span class="op">=</span> np.degrees(np.arccos(r))</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> np.sqrt(n) <span class="op">*</span> pair(theta, n, rng)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    E <span class="op">=</span> sigma <span class="op">*</span> rng.standard_normal((<span class="dv">2000</span>, n))</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    B <span class="op">=</span> beta_true <span class="op">+</span> E <span class="op">@</span> np.linalg.pinv(X).T</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    cloud[r] <span class="op">=</span> B</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    ax.plot([<span class="op">-</span><span class="dv">2</span>, <span class="dv">4</span>], [<span class="dv">4</span>, <span class="op">-</span><span class="dv">2</span>], color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">0.7</span>, ls<span class="op">=</span><span class="st">"--"</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    ax.scatter(B[:, <span class="dv">0</span>], B[:, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">4</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, color<span class="op">=</span>PURPLE, lw<span class="op">=</span><span class="dv">0</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    ax.plot(<span class="dv">1</span>, <span class="dv">1</span>, <span class="st">"o"</span>, color<span class="op">=</span>AMBER, ms<span class="op">=</span><span class="fl">4.5</span>, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"r = </span><span class="sc">{</span>r<span class="sc">:g}</span><span class="ss">,  θ = </span><span class="sc">{</span>theta<span class="sc">:.0f}</span><span class="ss">°"</span>)</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"coefficient of $x_1$"</span>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(<span class="op">-</span><span class="fl">1.2</span>, <span class="fl">3.2</span>)</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    ax.set_ylim(<span class="op">-</span><span class="fl">1.2</span>, <span class="fl">3.2</span>)</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>    ax.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"coefficient of $x_2$"</span>)</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-cloud" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cloud-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-cloud-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cloud-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Least-squares coefficients from 2,000 noise draws on the synthetic data of the first scene (<span class="math inline">\(n = 40\)</span>, noise sd 0.6, true coefficients <span class="math inline">\((1, 1)\)</span>, marked). The dashed line is <span class="math inline">\(\beta_1 + \beta_2 = 2\)</span>. As the correlation rises the cloud stretches along that line and stays narrow across it.
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>The standard deviation of the sum <span class="math inline">\(\hat\beta_1 + \hat\beta_2\)</span> is 0.13, 0.10 and 0.10 in the three panels.</li>
<li>The standard deviation of the difference is 0.13, 0.41 and 1.29.</li>
</ul>
</section>
</section>
<section id="the-condition-number" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="the-condition-number"><span class="header-section-number">5</span> The condition number</h2>
<section id="definition-and-the-two-column-value" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="definition-and-the-two-column-value"><span class="header-section-number">5.1</span> Definition and the two-column value</h3>
<p>The <strong>condition number</strong> of <span class="math inline">\(X\)</span> is the ratio of its largest to its smallest singular value, <span class="math inline">\(\kappa(X) = \sigma_{\max}/\sigma_{\min}\)</span>. It measures how unequally <span class="math inline">\(X\)</span> stretches different directions.</p>
<p>For two columns of equal length,</p>
<p><span class="math display">\[
\kappa(X) = \frac{\sqrt 2\,\cos(\theta/2)}{\sqrt 2\,\sin(\theta/2)} = \cot\frac{\theta}{2} \approx \frac{2}{\theta} \quad (\theta \text{ in radians, small}).
\]</span></p>
<ul>
<li><span class="math inline">\(\sigma_{\max}\)</span> stays between 1 and <span class="math inline">\(\sqrt 2\)</span> whatever the angle: two unit columns cannot add up to more than a vector of length 2.</li>
<li><span class="math inline">\(\sigma_{\min}\)</span> goes to zero in proportion to <span class="math inline">\(\theta\)</span>.</li>
<li>So <span class="math inline">\(\kappa\)</span> grows like <span class="math inline">\(1/\theta\)</span>. Halving the angle doubles it. Nothing is special about any threshold; the ratio is unbounded because its denominator reaches zero when the columns coincide.</li>
</ul>
</section>
<section id="what-it-bounds" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="what-it-bounds"><span class="header-section-number">5.2</span> What it bounds</h3>
<p>For a nudge <span class="math inline">\(\delta\)</span> to <span class="math inline">\(y\)</span> that lies in the column plane,</p>
<p><span class="math display">\[
\frac{\lVert\Delta\hat\beta\rVert}{\lVert\hat\beta\rVert} \;\le\; \kappa(X)\,\frac{\lVert\delta\rVert}{\lVert\hat y\rVert}.
\]</span></p>
<ul>
<li>The bound is reached when <span class="math inline">\(\hat y\)</span> lies along <span class="math inline">\(u_1\)</span> and <span class="math inline">\(\delta\)</span> along <span class="math inline">\(u_2\)</span>: the fit uses the strong direction and the nudge hits the weak one.</li>
<li>The denominator is <span class="math inline">\(\lVert\hat y\rVert\)</span>, not <span class="math inline">\(\lVert y\rVert\)</span>. A target that is mostly residual has a small fitted vector, and the same nudge is a larger fraction of it.</li>
<li><span class="math inline">\(\kappa\)</span> is a worst case. The nudge <strong>along the columns</strong> in the scene is nowhere near it.</li>
</ul>
<p><span class="math inline">\(\sigma_{\min}\)</span> is also the distance, in the spectral norm, from <span class="math inline">\(X\)</span> to the nearest matrix with exactly collinear columns (the Eckart–Young theorem). Relative to <span class="math inline">\(\lVert X\rVert = \sigma_{\max}\)</span> that distance is <span class="math inline">\(1/\kappa\)</span>. At <span class="math inline">\(\kappa = 100\)</span> a 1% change to <span class="math inline">\(X\)</span> is enough to make the columns exactly dependent.</p>
</section>
<section id="a-change-to-x-or-a-change-to-y" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="a-change-to-x-or-a-change-to-y"><span class="header-section-number">5.3</span> A change to X or a change to y</h3>
<p>The target enters <span class="math inline">\(\hat\beta = X^{+} y\)</span> linearly, so a nudge to <span class="math inline">\(y\)</span> is amplified by at most <span class="math inline">\(\kappa\)</span>. The predictors enter through the pseudoinverse <span class="math inline">\(X^{+}\)</span>, and the first-order bound for a perturbation <span class="math inline">\(E\)</span> of <span class="math inline">\(X\)</span> has two terms (Wedin, 1973; Golub and Van Loan, 2013, §5.3):</p>
<p><span class="math display">\[
\frac{\lVert\Delta\hat\beta\rVert}{\lVert\hat\beta\rVert} \;\lesssim\; \Big(\kappa + \kappa^2 \tan\phi\Big)\,\frac{\lVert E\rVert}{\lVert X\rVert},
\]</span></p>
<p>where <span class="math inline">\(\phi\)</span> is the angle between <span class="math inline">\(y\)</span> and the column plane, so <span class="math inline">\(\tan\phi = \lVert y - \hat y\rVert / \lVert\hat y\rVert\)</span>.</p>
<ul>
<li>With an exact fit, <span class="math inline">\(\tan\phi = 0\)</span> and a change to <span class="math inline">\(X\)</span> is no worse than a change to <span class="math inline">\(y\)</span>.</li>
<li>With a residual, the <span class="math inline">\(\kappa^2\)</span> term appears. Perturbing <span class="math inline">\(X\)</span> tilts the plane, and the residual, which was perpendicular to the old plane, acquires a component inside the new one along the weak direction.</li>
</ul>
<p>A simulation separates the two cases. It is synthetic: <span class="math inline">\(n = 50\)</span>, unit columns at angle <span class="math inline">\(\theta\)</span>, <span class="math inline">\(y = x_1 + x_2\)</span> plus a residual perpendicular to both columns, scaled to 0%, 5% or 30% of the signal’s length. Each of 1,000 seeds applies one random perturbation of relative size 2% to <span class="math inline">\(y\)</span>, and separately to <span class="math inline">\(X\)</span>.</p>
<div class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> one_seed(theta, resid, seed):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> <span class="dv">50</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> pair(theta, n, rng)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    signal <span class="op">=</span> X <span class="op">@</span> np.array([<span class="fl">1.0</span>, <span class="fl">1.0</span>])</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    e <span class="op">=</span> rng.standard_normal(n)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    e <span class="op">-=</span> X <span class="op">@</span> np.linalg.lstsq(X, e, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> signal <span class="op">+</span> resid <span class="op">*</span> np.linalg.norm(signal) <span class="op">*</span> e <span class="op">/</span> np.linalg.norm(e)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    b0 <span class="op">=</span> np.linalg.lstsq(X, y, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    dy <span class="op">=</span> rng.standard_normal(n)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    dy <span class="op">*=</span> <span class="fl">0.02</span> <span class="op">*</span> np.linalg.norm(y) <span class="op">/</span> np.linalg.norm(dy)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    dX <span class="op">=</span> rng.standard_normal((n, <span class="dv">2</span>))</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    dX <span class="op">*=</span> <span class="fl">0.02</span> <span class="op">*</span> np.linalg.norm(X, <span class="dv">2</span>) <span class="op">/</span> np.linalg.norm(dX, <span class="dv">2</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    by <span class="op">=</span> np.linalg.lstsq(X, y <span class="op">+</span> dy, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    bx <span class="op">=</span> np.linalg.lstsq(X <span class="op">+</span> dX, y, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.linalg.norm(by <span class="op">-</span> b0) <span class="op">/</span> np.linalg.norm(b0), np.linalg.norm(bx <span class="op">-</span> b0) <span class="op">/</span> np.linalg.norm(b0)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cell(v):</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    lo, mid, hi <span class="op">=</span> np.percentile(v, [<span class="dv">5</span>, <span class="dv">50</span>, <span class="dv">95</span>]) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="ss">f"</span><span class="sc">{</span>mid<span class="sc">:.1f}</span><span class="ss">% [</span><span class="sc">{</span>lo<span class="sc">:.1f}</span><span class="ss">, </span><span class="sc">{</span>hi<span class="sc">:.1f}</span><span class="ss">]"</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>xy <span class="op">=</span> {}</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> [<span class="fl">0.0</span>, <span class="fl">0.99</span>, <span class="fl">0.999</span>, <span class="fl">0.99996</span>]:</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    theta <span class="op">=</span> np.degrees(np.arccos(r)) <span class="cf">if</span> r <span class="op">&lt;</span> <span class="fl">0.9999</span> <span class="cf">else</span> <span class="fl">0.5</span></span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    row <span class="op">=</span> {<span class="st">"$</span><span class="ch">\\</span><span class="st">theta$"</span>: <span class="ss">f"</span><span class="sc">{</span>theta<span class="sc">:.2f}</span><span class="ss">°"</span>, <span class="st">"$</span><span class="ch">\\</span><span class="st">kappa$"</span>: <span class="ss">f"</span><span class="sc">{</span><span class="dv">1</span> <span class="op">/</span> np<span class="sc">.</span>tan(np.deg2rad(theta) <span class="op">/</span> <span class="dv">2</span>)<span class="sc">:.1f}</span><span class="ss">"</span>}</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> resid <span class="kw">in</span> [<span class="fl">0.0</span>, <span class="fl">0.05</span>, <span class="fl">0.30</span>]:</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>        out <span class="op">=</span> np.array([one_seed(theta, resid, s) <span class="cf">for</span> s <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1000</span>)])</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>        xy[(r, resid)] <span class="op">=</span> np.median(out, axis<span class="op">=</span><span class="dv">0</span>) <span class="op">*</span> <span class="dv">100</span></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> resid <span class="op">==</span> <span class="fl">0.0</span>:</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>            row[<span class="st">"nudge $y$"</span>] <span class="op">=</span> cell(out[:, <span class="dv">0</span>])</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>        row[<span class="ss">f"nudge $X$, residual </span><span class="sc">{</span>resid<span class="sc">:.0%}</span><span class="ss">"</span>] <span class="op">=</span> cell(out[:, <span class="dv">1</span>])</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    rows.append(row)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>md(pd.DataFrame(rows), index<span class="op">=</span><span class="va">False</span>, colalign<span class="op">=</span>(<span class="st">"right"</span>,) <span class="op">*</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-xy" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="6">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-xy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Median relative change in the coefficients, <span class="math inline">\(\lVert\Delta\hat\beta\rVert/\lVert\hat\beta\rVert\)</span>, after a random 2% perturbation, over 1,000 seeds. The 5–95% interval is in brackets.
</figcaption>
<div aria-describedby="tbl-xy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="6">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 16%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(\theta\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\kappa\)</span></th>
<th style="text-align: right;">nudge <span class="math inline">\(y\)</span></th>
<th style="text-align: right;">nudge <span class="math inline">\(X\)</span>, residual 0%</th>
<th style="text-align: right;">nudge <span class="math inline">\(X\)</span>, residual 5%</th>
<th style="text-align: right;">nudge <span class="math inline">\(X\)</span>, residual 30%</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">90.00°</td>
<td style="text-align: right;">1.0</td>
<td style="text-align: right;">0.3% [0.1, 0.7]</td>
<td style="text-align: right;">0.3% [0.1, 0.6]</td>
<td style="text-align: right;">0.3% [0.1, 0.6]</td>
<td style="text-align: right;">0.3% [0.1, 0.7]</td>
</tr>
<tr class="even">
<td style="text-align: right;">8.11°</td>
<td style="text-align: right;">14.1</td>
<td style="text-align: right;">2.6% [0.4, 7.7]</td>
<td style="text-align: right;">2.5% [0.3, 7.0]</td>
<td style="text-align: right;">2.8% [0.3, 8.2]</td>
<td style="text-align: right;">9.6% [0.9, 29.5]</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2.56°</td>
<td style="text-align: right;">44.7</td>
<td style="text-align: right;">8.2% [0.8, 24.6]</td>
<td style="text-align: right;">6.2% [0.7, 17.8]</td>
<td style="text-align: right;">11.5% [1.3, 35.5]</td>
<td style="text-align: right;">63.7% [6.3, 182.9]</td>
</tr>
<tr class="even">
<td style="text-align: right;">0.50°</td>
<td style="text-align: right;">229.2</td>
<td style="text-align: right;">42.2% [4.0, 127.2]</td>
<td style="text-align: right;">9.2% [1.0, 28.0]</td>
<td style="text-align: right;">25.8% [2.1, 76.5]</td>
<td style="text-align: right;">148.1% [14.1, 435.9]</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ul>
<li>A random nudge to <span class="math inline">\(y\)</span> is amplified in proportion to <span class="math inline">\(\kappa\)</span>, at about a tenth of the worst case, because a random direction in 50 dimensions has only a small component along <span class="math inline">\(u_2\)</span>.</li>
<li>With an exact fit, the same-sized change to <span class="math inline">\(X\)</span> does less than the change to <span class="math inline">\(y\)</span>: 9% against 42% at half a degree.</li>
<li>With a residual 30% as long as the signal, the change to <span class="math inline">\(X\)</span> does more: 148% against 42%.</li>
</ul>
<p>Regression data have residuals, so in practice noise in the predictors is the more damaging of the two. The reason is the size of the residual, and the claim fails for a system that is solved exactly.</p>
</section>
<section id="floating-point" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="floating-point"><span class="header-section-number">5.4</span> Floating point</h3>
<p>Rounding in the arithmetic is one more perturbation, of relative size about <span class="math inline">\(10^{-16}\)</span> in double precision, and <span class="math inline">\(\kappa\)</span> amplifies it as it does any other.</p>
<ul>
<li>A solver that works on <span class="math inline">\(X\)</span> directly (QR or the SVD) loses about <span class="math inline">\(\log_{10}\kappa\)</span> of its 16 digits.</li>
<li>The normal equations <span class="math inline">\(X^\top X \beta = X^\top y\)</span> work on <span class="math inline">\(X^\top X\)</span>, whose condition number is <span class="math inline">\(\kappa^2\)</span>, and lose twice as many.</li>
</ul>
<div class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> []</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> [<span class="fl">1e2</span>, <span class="fl">1e4</span>, <span class="fl">1e6</span>, <span class="fl">1e8</span>]:</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    theta <span class="op">=</span> np.degrees(<span class="dv">2</span> <span class="op">*</span> np.arctan(<span class="dv">1</span> <span class="op">/</span> k))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    err_ne, err_ls <span class="op">=</span> [], []</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> s <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">200</span>):</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>        X <span class="op">=</span> pair(theta, <span class="dv">50</span>, np.random.default_rng(s))</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>        y <span class="op">=</span> X <span class="op">@</span> np.array([<span class="fl">1.0</span>, <span class="fl">1.0</span>])</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">try</span>:</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>            b_ne <span class="op">=</span> np.linalg.solve(X.T <span class="op">@</span> X, X.T <span class="op">@</span> y)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>            err_ne.append(np.linalg.norm(b_ne <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> np.sqrt(<span class="dv">2</span>))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>        <span class="cf">except</span> np.linalg.LinAlgError:</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>            err_ne.append(np.inf)</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>        err_ls.append(np.linalg.norm(np.linalg.lstsq(X, y, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>] <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> np.sqrt(<span class="dv">2</span>))</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    rows.append(</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>        {</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>            <span class="st">"$</span><span class="ch">\\</span><span class="st">kappa(X)$"</span>: <span class="ss">f"$10^</span><span class="ch">{{</span><span class="sc">{</span><span class="bu">int</span>(np.log10(k))<span class="sc">}</span><span class="ch">}}</span><span class="ss">$"</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>            <span class="st">"normal equations"</span>: <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>median(err_ne)<span class="sc">:.0e}</span><span class="ss"> [</span><span class="sc">{</span><span class="st">'fails'</span> <span class="cf">if</span> np<span class="sc">.</span>isinf(np.<span class="bu">max</span>(err_ne)) <span class="cf">else</span> <span class="bu">format</span>(np.<span class="bu">max</span>(err_ne), <span class="st">'.0e'</span>)<span class="sc">}</span><span class="ss">]"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>            <span class="st">"SVD on $X$ (`lstsq`)"</span>: <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>median(err_ls)<span class="sc">:.0e}</span><span class="ss"> [</span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">max</span>(err_ls)<span class="sc">:.0e}</span><span class="ss">]"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>        }</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>float_rows <span class="op">=</span> rows</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>md(pd.DataFrame(rows), index<span class="op">=</span><span class="va">False</span>, colalign<span class="op">=</span>(<span class="st">"right"</span>,) <span class="op">*</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-float" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="7">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-float-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Relative error in the computed coefficients for exact data <span class="math inline">\(y = x_1 + x_2\)</span> in double precision, at increasing condition number. The median of 200 seeds, with the largest in brackets; “fails” means the solver reported a singular matrix on at least one seed.
</figcaption>
<div aria-describedby="tbl-float-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="7">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;"><span class="math inline">\(\kappa(X)\)</span></th>
<th style="text-align: right;">normal equations</th>
<th style="text-align: right;">SVD on <span class="math inline">\(X\)</span> (<code>lstsq</code>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(10^{2}\)</span></td>
<td style="text-align: right;">8e-13 [3e-12]</td>
<td style="text-align: right;">1e-15 [2e-14]</td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(10^{4}\)</span></td>
<td style="text-align: right;">8e-09 [3e-08]</td>
<td style="text-align: right;">1e-13 [1e-12]</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(10^{6}\)</span></td>
<td style="text-align: right;">6e-05 [4e-04]</td>
<td style="text-align: right;">1e-11 [9e-11]</td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(10^{8}\)</span></td>
<td style="text-align: right;">1e+00 [fails]</td>
<td style="text-align: right;">1e-09 [1e-08]</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>This part of the problem is solved by the choice of algorithm. The statistical part is not: no solver recovers information the data do not hold.</p>
</section>
</section>
<section id="the-loss-surface" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="the-loss-surface"><span class="header-section-number">6</span> The loss surface</h2>
<p>The singular values also set the shape of the loss. With <span class="math inline">\(\hat\beta\)</span> the minimiser,</p>
<p><span class="math display">\[
L(\beta) = \lVert y - X\beta\rVert^2 = L_{\min} + (\beta - \hat\beta)^\top X^\top X\, (\beta - \hat\beta).
\]</span></p>
<ul>
<li>The surface is a bowl whose curvature is <span class="math inline">\(2\sigma_1^2\)</span> along <span class="math inline">\(v_1\)</span> and <span class="math inline">\(2\sigma_2^2\)</span> along <span class="math inline">\(v_2\)</span>.</li>
<li>The ratio of the two curvatures is <span class="math inline">\(\kappa^2\)</span>.</li>
<li><span class="math inline">\(L_{\min}\)</span> is the squared distance from <span class="math inline">\(y\)</span> to the column plane.</li>
</ul>
<p>The scene plots the mean squared error, <span class="math inline">\(L/n\)</span>, for the synthetic data of the first scene, with columns of standard deviation 1.</p>
<div id="widget-valley">

</div>
<ol type="1">
<li>Press <strong>r = 0</strong>. The bowl is round: curvature 2 in every direction. The grey minima of the other 199 draws huddle at its bottom, and this draw’s minimum loss is 0.298.</li>
<li>Press <strong>0.99</strong>. The bowl has become a trough. Its curvature is 3.98 across and 0.020 along, a ratio of 199, which is <span class="math inline">\(\kappa^2 = 14.1^2\)</span>. The other draws’ minima lie strewn along its floor. The minimum loss is still 0.298.</li>
<li>Press <strong>0.999</strong>. The floor is ten times flatter and the minimum has moved from <span class="math inline">\((1.18, 0.68)\)</span> to <span class="math inline">\((1.87, 0.00)\)</span>. The minimum loss is still 0.298.</li>
<li>Press <strong>0.99</strong> again, then <strong>New noise</strong> four times. The trough slides along its own length and the amber minimum visits <span class="math inline">\((0.82, 1.09)\)</span>, <span class="math inline">\((0.90, 1.15)\)</span>, <span class="math inline">\((1.84, 0.13)\)</span> and <span class="math inline">\((0.02, 2.04)\)</span>.</li>
</ol>
<p>Steps 2 and 3 answer the question about the loss. The minimum loss depends only on the plane the columns span, and turning one column towards the other inside that plane leaves the plane where it was. A sample that moves the minimum a long way along the trough changes the loss at the old minimum by almost nothing, since the floor of the trough is nearly flat.</p>
<p>Gradient descent has to cross this surface. Its step size is limited by the steep direction and its progress along the floor is slower by the factor <span class="math inline">\(\kappa^2\)</span>.</p>
</section>
<section id="the-statistics" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="the-statistics"><span class="header-section-number">7</span> The statistics</h2>
<p>Under the model <span class="math inline">\(y = X\beta + \varepsilon\)</span> with independent noise of variance <span class="math inline">\(\sigma^2\)</span> (here <span class="math inline">\(\sigma\)</span> is the noise level, not a singular value), the covariance of the estimate is <span class="math inline">\(\operatorname{Var}(\hat\beta) = \sigma^2 (X^\top X)^{-1}\)</span>. For two centred columns with sum of squares <span class="math inline">\(S\)</span> each:</p>
<p><span class="math display">\[
\operatorname{Var}(\hat\beta_j) = \frac{\sigma^2}{S}\cdot\frac{1}{1 - r^2},
\qquad
\operatorname{Corr}(\hat\beta_1, \hat\beta_2) = -r .
\]</span></p>
<ul>
<li><strong>Variance inflation factor.</strong> <span class="math inline">\(\mathrm{VIF} = 1/(1 - r^2) = 1/\sin^2\theta\)</span> is the factor by which the variance of a coefficient exceeds what it would be with uncorrelated columns. For small angles <span class="math inline">\(\mathrm{VIF} \approx \kappa^2/4\)</span>.</li>
<li><strong>Opposite errors.</strong> The two estimates are correlated at <span class="math inline">\(-r\)</span>. When one comes out too high the other comes out too low by nearly the same amount, which is how the fourth noise draw of the first scene, at half a degree, fits <span class="math inline">\((15.1, -13.1)\)</span> to data generated with <span class="math inline">\((1, 1)\)</span>.</li>
<li><strong>Sum and difference.</strong> <span class="math inline">\(\operatorname{Var}(\hat\beta_1 + \hat\beta_2) = 2\sigma^2 / (S(1 + r))\)</span> falls slightly as <span class="math inline">\(r\)</span> rises. <span class="math inline">\(\operatorname{Var}(\hat\beta_1 - \hat\beta_2) = 2\sigma^2 / (S(1 - r))\)</span> has <span class="math inline">\(1 - r\)</span> in the denominator.</li>
<li><strong>Tests.</strong> Each coefficient’s <span class="math inline">\(t\)</span>-statistic shrinks by <span class="math inline">\(\sqrt{\mathrm{VIF}}\)</span>. Two predictors can each test as indistinguishable from zero while the pair is, jointly, strongly related to <span class="math inline">\(y\)</span>.</li>
<li><strong>Predictions.</strong> The variance of a prediction at a new point <span class="math inline">\(x\)</span> is <span class="math inline">\(\sigma^2 x^\top (X^\top X)^{-1} x\)</span>: small when <span class="math inline">\(x\)</span> lies along <span class="math inline">\(v_1\)</span>, where the data are, and large along <span class="math inline">\(v_2\)</span>.</li>
</ul>
<p>The first scene agrees: <span class="math inline">\(\sigma = 0.6\)</span>, <span class="math inline">\(S = 40\)</span> and <span class="math inline">\(r = 0.99\)</span> give a standard deviation of <span class="math inline">\(0.6/\sqrt{40 \times 0.0199} = 0.67\)</span> for a coefficient, against 0.68 over the scene’s 200 draws.</p>
</section>
<section id="more-than-two-columns" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="more-than-two-columns"><span class="header-section-number">8</span> More than two columns</h2>
<p>With <span class="math inline">\(p\)</span> columns, near collinearity means that some combination of them nearly cancels: <span class="math inline">\(Xv \approx 0\)</span> for a unit vector <span class="math inline">\(v\)</span>. That is the statement that the smallest singular value is small, and <span class="math inline">\(v\)</span> is its right singular vector.</p>
<ul>
<li><span class="math inline">\(v\)</span> is again the direction the data cannot see, now a combination of several coefficients.</li>
<li><span class="math inline">\(\hat\beta = \sum_i (u_i^\top y / \sigma_i)\, v_i\)</span> still holds, with one term for each singular value.</li>
<li><span class="math inline">\(\mathrm{VIF}_j = 1/(1 - R_j^2)\)</span>, where <span class="math inline">\(R_j^2\)</span> is the <span class="math inline">\(R^2\)</span> from regressing column <span class="math inline">\(j\)</span> on the other columns.</li>
</ul>
<p>No two columns need be close for this to happen.</p>
<div id="widget-three">

</div>
<ol type="1">
<li>At 90° the three columns are perpendicular. The box has volume 1 and <span class="math inline">\(\kappa = 1\)</span>.</li>
<li>Drag the lift down to about 8°. The box is nearly flat. The largest correlation between any two columns is 0.70, and <span class="math inline">\(\kappa\)</span> is 14, the value two columns reach at <span class="math inline">\(r = 0.99\)</span>.</li>
<li>Drag to 1°. The largest pairwise correlation is 0.707 and will never exceed it. The VIF of <span class="math inline">\(x_3\)</span> is above 3,000.</li>
</ol>
<p>The Gram matrix of these three columns has eigenvalues <span class="math inline">\(1 + \cos\alpha\)</span>, <span class="math inline">\(1\)</span> and <span class="math inline">\(1 - \cos\alpha\)</span> for a lift of <span class="math inline">\(\alpha\)</span>, so <span class="math inline">\(\kappa = \cot(\alpha/2)\)</span>: the two-column formula, with the angle between <span class="math inline">\(x_3\)</span> and the plane of the others in place of the angle between two columns. A table of pairwise correlations shows none of it.</p>
<p>Two diagnostics do:</p>
<ul>
<li>The singular values of <span class="math inline">\(X\)</span> after scaling every column to the same length, and the right singular vector of the smallest one, which names the columns involved. Belsley, Kuh and Welsch (1980) built their collinearity diagnostics on these.</li>
<li>The VIFs, which are the diagonal of the inverse correlation matrix.</li>
</ul>
</section>
<section id="real-data" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="real-data"><span class="header-section-number">9</span> Real data</h2>
<section id="longley-two-columns-then-six" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="longley-two-columns-then-six"><span class="header-section-number">9.1</span> Longley: two columns, then six</h3>
<ul>
<li><strong>Source.</strong> Longley (1967): 16 annual observations of the US economy, 1947 to 1962, taken from official statistics. It ships with <code>statsmodels</code>.</li>
<li><strong>Motive.</strong> Longley used it to test the regression programs of the day. They disagreed with each other, some in the leading digit.</li>
<li><strong>Columns.</strong> Total employment (the target), the GNP price deflator, GNP, the number unemployed, the size of the armed forces, the population aged 14 and over, and the year.</li>
<li><strong>What this post asks of it.</strong> How far the coefficients move under changes to the data too small to matter.</li>
<li><strong>Cost of a wrong answer.</strong> Reading a coefficient as an effect: for example, concluding from a negative coefficient that population growth lowers employment.</li>
<li><strong>Why it fits.</strong> Four of the six predictors rise almost in step with the year.</li>
</ul>
<p>Start with two columns, GNP and population, each standardised.</p>
<div class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"Model"</span>: <span class="st">"GNP alone"</span>, <span class="st">"GNP"</span>: <span class="ss">f"</span><span class="sc">{</span>fit_gnp<span class="sc">.</span>params[<span class="st">'GNP'</span>]<span class="sc">:,.0f}</span><span class="ss"> (</span><span class="sc">{</span>fit_gnp<span class="sc">.</span>bse[<span class="st">'GNP'</span>]<span class="sc">:,.0f}</span><span class="ss">)"</span>, <span class="st">"Population"</span>: <span class="st">""</span>, <span class="st">"$R^2$"</span>: <span class="ss">f"</span><span class="sc">{</span>fit_gnp<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span>},</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"Model"</span>: <span class="st">"Population alone"</span>, <span class="st">"GNP"</span>: <span class="st">""</span>, <span class="st">"Population"</span>: <span class="ss">f"</span><span class="sc">{</span>fit_pop<span class="sc">.</span>params[<span class="st">'POP'</span>]<span class="sc">:,.0f}</span><span class="ss"> (</span><span class="sc">{</span>fit_pop<span class="sc">.</span>bse[<span class="st">'POP'</span>]<span class="sc">:,.0f}</span><span class="ss">)"</span>, <span class="st">"$R^2$"</span>: <span class="ss">f"</span><span class="sc">{</span>fit_pop<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span>},</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Model"</span>: <span class="st">"Both"</span>,</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        <span class="st">"GNP"</span>: <span class="ss">f"</span><span class="sc">{</span>fit_both<span class="sc">.</span>params[<span class="st">'GNP'</span>]<span class="sc">:,.0f}</span><span class="ss"> (</span><span class="sc">{</span>fit_both<span class="sc">.</span>bse[<span class="st">'GNP'</span>]<span class="sc">:,.0f}</span><span class="ss">)"</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Population"</span>: <span class="ss">f"</span><span class="sc">{</span>fit_both<span class="sc">.</span>params[<span class="st">'POP'</span>]<span class="sc">:,.0f}</span><span class="ss"> (</span><span class="sc">{</span>fit_both<span class="sc">.</span>bse[<span class="st">'POP'</span>]<span class="sc">:,.0f}</span><span class="ss">)"</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>        <span class="st">"$R^2$"</span>: <span class="ss">f"</span><span class="sc">{</span>fit_both<span class="sc">.</span>rsquared<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    },</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>md(pd.DataFrame(rows), index<span class="op">=</span><span class="va">False</span>, colalign<span class="op">=</span>(<span class="st">"left"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-longley-two" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="9">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-longley-two-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Total employment (thousands) regressed on standardised GNP and population, separately and together. Standard errors in brackets.
</figcaption>
<div aria-describedby="tbl-longley-two-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="9">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">GNP</th>
<th style="text-align: right;">Population</th>
<th style="text-align: right;"><span class="math inline">\(R^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GNP alone</td>
<td style="text-align: right;">3,454 (170)</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">0.967</td>
</tr>
<tr class="even">
<td style="text-align: left;">Population alone</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">3,373 (262)</td>
<td style="text-align: right;">0.922</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Both</td>
<td style="text-align: right;">6,279 (1,058)</td>
<td style="text-align: right;">-2,850 (1,058)</td>
<td style="text-align: right;">0.979</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<ul>
<li>The two columns correlate at 0.991: an angle of 7.7°, a condition number of 14.9, and a VIF of 56.</li>
<li>Alone, each has a positive coefficient near 3,400. Together, GNP’s is 6,279 and population’s is -2,850.</li>
<li>Their sum is 3,429, close to either coefficient alone. The data fix the sum and leave the split open, and the standard errors grow from 170 to 1,058.</li>
</ul>
<p>Now all six predictors.</p>
<div class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="st">"GNPDEFL"</span>, <span class="st">"GNP"</span>, <span class="st">"UNEMP"</span>, <span class="st">"ARMED"</span>, <span class="st">"POP"</span>, <span class="st">"YEAR"</span>]</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> {<span class="st">"GNPDEFL"</span>: <span class="st">"GNP deflator"</span>, <span class="st">"GNP"</span>: <span class="st">"GNP"</span>, <span class="st">"UNEMP"</span>: <span class="st">"Unemployed"</span>, <span class="st">"ARMED"</span>: <span class="st">"Armed forces"</span>, <span class="st">"POP"</span>: <span class="st">"Population"</span>, <span class="st">"YEAR"</span>: <span class="st">"Year"</span>}</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>XL <span class="op">=</span> L[cols].values</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>fit6 <span class="op">=</span> sm.OLS(yL, sm.add_constant(L[cols])).fit()</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>vif6 <span class="op">=</span> np.diag(np.linalg.inv(np.corrcoef(XL.T)))</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>ZL <span class="op">=</span> (XL <span class="op">-</span> XL.mean(<span class="dv">0</span>)) <span class="op">/</span> XL.std(<span class="dv">0</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>svL <span class="op">=</span> np.linalg.svd(ZL, compute_uv<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>kappa6 <span class="op">=</span> svL[<span class="dv">0</span>] <span class="op">/</span> svL[<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>rows <span class="op">=</span> [</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    {</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Predictor"</span>: names[c],</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Coefficient"</span>: <span class="ss">f"</span><span class="sc">{</span>fit6<span class="sc">.</span>params[c]<span class="sc">:.4g}</span><span class="ss">"</span>,</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>        <span class="st">"Standard error"</span>: <span class="ss">f"</span><span class="sc">{</span>fit6<span class="sc">.</span>bse[c]<span class="sc">:.3g}</span><span class="ss">"</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>        <span class="st">"$t$"</span>: <span class="ss">f"</span><span class="sc">{</span>fit6<span class="sc">.</span>tvalues[c]<span class="sc">:.2f}</span><span class="ss">"</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"VIF"</span>: <span class="ss">f"</span><span class="sc">{</span>vif6[j]<span class="sc">:,.0f}</span><span class="ss">"</span>,</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j, c <span class="kw">in</span> <span class="bu">enumerate</span>(cols)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>md(pd.DataFrame(rows), index<span class="op">=</span><span class="va">False</span>, colalign<span class="op">=</span>(<span class="st">"left"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>, <span class="st">"right"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="tbl-longley-six" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="10">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-longley-six-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: The six-predictor Longley regression in the published units, with each predictor’s variance inflation factor.
</figcaption>
<div aria-describedby="tbl-longley-six-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="10">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Predictor</th>
<th style="text-align: right;">Coefficient</th>
<th style="text-align: right;">Standard error</th>
<th style="text-align: right;"><span class="math inline">\(t\)</span></th>
<th style="text-align: right;">VIF</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">GNP deflator</td>
<td style="text-align: right;">15.06</td>
<td style="text-align: right;">84.9</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">136</td>
</tr>
<tr class="even">
<td style="text-align: left;">GNP</td>
<td style="text-align: right;">-0.03582</td>
<td style="text-align: right;">0.0335</td>
<td style="text-align: right;">-1.07</td>
<td style="text-align: right;">1,789</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Unemployed</td>
<td style="text-align: right;">-2.02</td>
<td style="text-align: right;">0.488</td>
<td style="text-align: right;">-4.14</td>
<td style="text-align: right;">34</td>
</tr>
<tr class="even">
<td style="text-align: left;">Armed forces</td>
<td style="text-align: right;">-1.033</td>
<td style="text-align: right;">0.214</td>
<td style="text-align: right;">-4.82</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Population</td>
<td style="text-align: right;">-0.0511</td>
<td style="text-align: right;">0.226</td>
<td style="text-align: right;">-0.23</td>
<td style="text-align: right;">399</td>
</tr>
<tr class="even">
<td style="text-align: left;">Year</td>
<td style="text-align: right;">1829</td>
<td style="text-align: right;">455</td>
<td style="text-align: right;">4.02</td>
<td style="text-align: right;">759</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p><span class="math inline">\(R^2\)</span> is 0.9955, the condition number of the standardised predictors is 111, and three coefficients have <span class="math inline">\(\lvert t\rvert\)</span> below 1.1.</p>
<p>Two perturbations show how little holds those coefficients in place.</p>
<ul>
<li><strong>Rounding.</strong> The published figures are rounded. Following Beaton, Rubin and Barone (1976), add to every predictor value except the year a uniform random amount within half a unit of its last published digit, and refit. A perturbed dataset would round to the published one.</li>
<li><strong>One year.</strong> Refit 16 times, leaving out one year each time.</li>
</ul>
<div id="cell-fig-longley" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>half_unit <span class="op">=</span> np.array([<span class="fl">0.05</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.5</span>, <span class="fl">0.0</span>])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>b_full <span class="op">=</span> fit6.params[cols].values</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>B_round, r2_round <span class="op">=</span> [], []</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2000</span>):</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    Xp <span class="op">=</span> np.column_stack([np.ones(<span class="dv">16</span>), XL <span class="op">+</span> rng.uniform(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, XL.shape) <span class="op">*</span> half_unit])</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> np.linalg.lstsq(Xp, yL, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    B_round.append(b[<span class="dv">1</span>:])</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    r2_round.append(<span class="dv">1</span> <span class="op">-</span> ((yL <span class="op">-</span> Xp <span class="op">@</span> b) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>() <span class="op">/</span> ((yL <span class="op">-</span> yL.mean()) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>())</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>B_round, r2_round <span class="op">=</span> np.array(B_round) <span class="op">/</span> b_full, np.array(r2_round)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>B_loo <span class="op">=</span> []</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">16</span>):</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>    keep <span class="op">=</span> np.arange(<span class="dv">16</span>) <span class="op">!=</span> i</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    B_loo.append(np.linalg.lstsq(np.column_stack([np.ones(<span class="dv">15</span>), XL[keep]]), yL[keep], rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>][<span class="dv">1</span>:])</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>B_loo <span class="op">=</span> np.array(B_loo) <span class="op">/</span> b_full</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.2</span>, <span class="fl">3.3</span>))</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>jit <span class="op">=</span> np.random.default_rng(<span class="dv">1</span>)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j, c <span class="kw">in</span> <span class="bu">enumerate</span>(cols):</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    yy <span class="op">=</span> <span class="bu">len</span>(cols) <span class="op">-</span> <span class="dv">1</span> <span class="op">-</span> j</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    ax.scatter(np.clip(B_round[::<span class="dv">8</span>, j], <span class="op">-</span><span class="dv">4</span>, <span class="dv">5</span>), yy <span class="op">+</span> <span class="fl">0.18</span> <span class="op">+</span> <span class="fl">0.1</span> <span class="op">*</span> jit.uniform(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">250</span>), s<span class="op">=</span><span class="dv">4</span>, alpha<span class="op">=</span><span class="fl">0.35</span>, color<span class="op">=</span>PURPLE, lw<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    ax.scatter(np.clip(B_loo[:, j], <span class="op">-</span><span class="dv">4</span>, <span class="dv">5</span>), np.full(<span class="dv">16</span>, yy <span class="op">-</span> <span class="fl">0.2</span>), s<span class="op">=</span><span class="dv">16</span>, color<span class="op">=</span>AMBER, alpha<span class="op">=</span><span class="fl">0.85</span>, lw<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">1</span>, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">0</span>, color<span class="op">=</span>RULE, lw<span class="op">=</span><span class="fl">0.7</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>ax.set_yticks(<span class="bu">range</span>(<span class="bu">len</span>(cols)))</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>ax.set_yticklabels([names[c] <span class="cf">for</span> c <span class="kw">in</span> cols][::<span class="op">-</span><span class="dv">1</span>])</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"coefficient ÷ coefficient in the full published fit"</span>)</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="op">-</span><span class="fl">4.2</span>, <span class="fl">5.2</span>)</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-longley" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-longley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-longley-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-longley-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Longley coefficients under two small changes to the data, each divided by its value in the full published fit, so 1 means no change. Purple: 2,000 refits with the predictors perturbed within their rounding. Amber: 16 refits with one year left out. The horizontal axis is clipped at −4 and 5.
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li><strong>Rounding.</strong> The largest perturbation is 0.05% of a typical value in its column. The GNP deflator’s coefficient, 15.1 in the published fit, has a 95% range of 11.1 to 19.1. Population’s, -0.051, ranges from -0.058 to -0.044. <span class="math inline">\(R^2\)</span> stays between 0.99546 and 0.99550.</li>
<li><strong>One year.</strong> Population’s coefficient changes sign in 3 of the 16 refits, reaching 0.166 without 1951. The deflator’s runs from -52 to 41. The year’s runs from 1,432 to 2,584.</li>
<li><strong>The stable ones.</strong> Unemployment and the armed forces, with the two smallest VIFs, keep their sign and rough size throughout.</li>
</ul>
<p>A change of at most 0.05% in the inputs moved one coefficient by a quarter of its value, and removing one row of 16 changed another’s sign.</p>
</section>
<section id="diabetes-an-identity-among-four-columns" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="diabetes-an-identity-among-four-columns"><span class="header-section-number">9.2</span> Diabetes: an identity among four columns</h3>
<ul>
<li><strong>Source.</strong> Efron, Hastie, Johnstone and Tibshirani (2004): 442 diabetes patients, ten baseline measurements, and a measure of disease progression one year later. It ships with scikit-learn, whose documentation names the six blood-serum columns.</li>
<li><strong>Motive.</strong> The authors used it to demonstrate least angle regression, a way of choosing among correlated predictors.</li>
<li><strong>Columns.</strong> Age, sex, body mass index, blood pressure, and six serum measurements: total cholesterol (<code>s1</code>), LDL (<code>s2</code>), HDL (<code>s3</code>), the ratio of total cholesterol to HDL (<code>s4</code>), a column scikit-learn describes as possibly the log of triglycerides (<code>s5</code>), and glucose (<code>s6</code>).</li>
<li><strong>What this post asks of it.</strong> Which columns are tied together, and what that does to their coefficients.</li>
<li><strong>Cost of a wrong answer.</strong> Reading the fitted coefficient of total cholesterol as its effect on the disease.</li>
<li><strong>Why it fits.</strong> The dependence involves four columns and no pairwise correlation reveals it.</li>
</ul>
<p>In the ten-predictor fit on standardised columns, total cholesterol has a coefficient of -37.7 (standard error 19.8) and LDL +22.7 (16.1). Fitted alone, total cholesterol’s coefficient is +16.3.</p>
<ul>
<li>The VIF of total cholesterol is 59.</li>
<li>Its largest pairwise correlation is 0.90, with LDL. Two columns at that correlation give a VIF of 5.1.</li>
<li>Its correlation with HDL is 0.05.</li>
</ul>
<p>The singular vector of the smallest singular value shows what the pairwise correlations miss. Its largest entries are +0.71 on s1, -0.56 on s2, -0.32 on s3, -0.26 on s5: total cholesterol against LDL, HDL and the triglyceride column.</p>
<p>That is a formula. LDL is rarely measured directly; it is usually computed from the other three by the Friedewald equation, <span class="math inline">\(\text{LDL} = \text{TC} - \text{HDL} - \text{TG}/5\)</span> (Friedewald, Levy and Fredrickson, 1972). If <code>s5</code> is the natural log of triglycerides, then <code>s1 − s2 − s3</code> should equal <code>exp(s5)/5</code>, and it does: the largest gap over the 442 patients is 0.40 mg/dL and the median gap is 0.0005. Four columns satisfy an exact identity, and the regression sees it through a logarithm, which is why the VIF is 59 and not infinite.</p>
<div id="cell-fig-diabetes" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> np.column_stack([np.ones(<span class="bu">len</span>(yD)), ZD.values])</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>boot, boot_r2 <span class="op">=</span> [], []</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">2000</span>):</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> rng.integers(<span class="dv">0</span>, <span class="bu">len</span>(yD), <span class="bu">len</span>(yD))</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    b <span class="op">=</span> np.linalg.lstsq(A[idx], yD[idx], rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    boot.append(b[<span class="dv">1</span>:])</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    boot_r2.append(<span class="dv">1</span> <span class="op">-</span> ((yD[idx] <span class="op">-</span> A[idx] <span class="op">@</span> b) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>() <span class="op">/</span> ((yD[idx] <span class="op">-</span> yD[idx].mean()) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>())</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>boot <span class="op">=</span> pd.DataFrame(boot, columns<span class="op">=</span>XD.columns)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">4.6</span>, <span class="fl">3.6</span>))</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="dv">0</span>, color<span class="op">=</span>RULE, lw<span class="op">=</span><span class="fl">0.7</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>ax.axvline(<span class="dv">0</span>, color<span class="op">=</span>RULE, lw<span class="op">=</span><span class="fl">0.7</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>ax.scatter(boot[<span class="st">"s1"</span>], boot[<span class="st">"s2"</span>], s<span class="op">=</span><span class="dv">4</span>, alpha<span class="op">=</span><span class="fl">0.3</span>, color<span class="op">=</span>PURPLE, lw<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>ax.plot(fitD.params[<span class="st">"s1"</span>], fitD.params[<span class="st">"s2"</span>], <span class="st">"o"</span>, color<span class="op">=</span>AMBER, ms<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"coefficient of total cholesterol (s1)"</span>)</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"coefficient of LDL (s2)"</span>)</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-diabetes" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-diabetes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-diabetes-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-diabetes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Coefficients of total cholesterol and LDL in the ten-predictor diabetes regression, refitted on 2,000 bootstrap resamples of the 442 patients. The marker is the fit to the original data; the dashed lines are zero.
</figcaption>
</figure>
</div>
</div>
</div>
<ul>
<li>The two coefficients correlate at -0.96 over the resamples.</li>
<li>Their sum has a standard deviation of 6.2; their difference, 35.1.</li>
<li>Body mass index, outside the identity with a VIF of 1.5, has a coefficient of 24.8 with a bootstrap standard deviation of 3.2.</li>
<li><span class="math inline">\(R^2\)</span> runs from 0.48 to 0.58 (5th to 95th percentile) and does not depend on how the cholesterol columns share their weight.</li>
</ul>
<p>A negative coefficient on total cholesterol is the regression’s way of writing “holding LDL, HDL and triglycerides fixed”, a comparison the identity makes almost impossible within these data.</p>
</section>
</section>
<section id="what-breaks-and-what-does-not" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="what-breaks-and-what-does-not"><span class="header-section-number">10</span> What breaks and what does not</h2>
<p>Unaffected by collinearity among the predictors:</p>
<ul>
<li>The fitted values, the residuals, and <span class="math inline">\(R^2\)</span>.</li>
<li>Predictions for new rows whose predictors follow the pattern of the training rows.</li>
<li>Coefficients of predictors outside the dependence.</li>
</ul>
<p>Affected:</p>
<ul>
<li>The size and sign of the coefficients inside the dependence, their standard errors, and their tests.</li>
<li>Predictions for new rows that break the pattern, where the weak direction is no longer cancelled.</li>
<li>The arithmetic, by <span class="math inline">\(\log_{10}\kappa\)</span> digits, or twice that through the normal equations.</li>
</ul>
<p>More decimal places and better solvers address only the third item in that list. The first two are a statement about the data: the rows contain almost no variation along one direction, so they cannot say what happens along it. Either new rows supply that variation, or something other than the data settles the direction. <a href="../collinearity-remedies/">Part 2</a> is about the second option.</p>
<p>Columns. Align. One. Direction. Vanishes. Coefficients. Swing. Sums. Hold. Predictions. Survive.</p>
</section>
<section id="references" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="references"><span class="header-section-number">11</span> References</h2>
<ul>
<li>Beaton, A. E., Rubin, D. B., and Barone, J. L. (1976). The acceptability of regression solutions: another look at computational accuracy. <em>Journal of the American Statistical Association</em>, 71(353), 158–168.</li>
<li>Belsley, D. A., Kuh, E., and Welsch, R. E. (1980). <em>Regression Diagnostics: Identifying Influential Data and Sources of Collinearity</em>. Wiley.</li>
<li>Efron, B., Hastie, T., Johnstone, I., and Tibshirani, R. (2004). <a href="https://doi.org/10.1214/009053604000000067">Least angle regression</a>. <em>Annals of Statistics</em>, 32(2), 407–499.</li>
<li>Friedewald, W. T., Levy, R. I., and Fredrickson, D. S. (1972). Estimation of the concentration of low-density lipoprotein cholesterol in plasma, without use of the preparative ultracentrifuge. <em>Clinical Chemistry</em>, 18(6), 499–502.</li>
<li>Golub, G. H., and Van Loan, C. F. (2013). <em>Matrix Computations</em>, 4th edition. Johns Hopkins University Press.</li>
<li>Longley, J. W. (1967). An appraisal of least squares programs for the electronic computer from the point of view of the user. <em>Journal of the American Statistical Association</em>, 62(319), 819–841.</li>
<li>Wedin, P.-Å. (1973). Perturbation theory for pseudo-inverses. <em>BIT Numerical Mathematics</em>, 13, 217–232.</li>
<li>scikit-learn, <a href="https://scikit-learn.org/stable/datasets/toy_dataset.html#diabetes-dataset">Diabetes dataset</a>.</li>
<li>The <a href="https://project-delphi.github.io/tensors-workshop/interactive/linalg-stage.html#collinear">linear-algebra stage</a> of the tensors workshop, scene 7.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/project-delphi\.github\.io\/ml-blog\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Synthetic Musings, by Ravi Kalia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/collinearity/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>