{
  "hash": "c2eeaa0b65e61f951976f0af6da4b843",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Uses of Tensor Factorizations\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-08-29\"\ncategories: [Linear Algebra, Machine Learning, Numerical Methods, Tensors]\nimage: \"./cover.png\"\ntags: [tensors, CP, tensor-train, CNN, compression, Kruskal]\njupyter: tensor-blog\nresources:\n  - cover.png\n  - media\n  - widgets.js\n  - widget-data/data.js\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    number-sections: true\n---\n\n\n![Uses of Tensor Factorizations](./cover.png)\n\nThe main application of tensor factorizations is compression: images and video, or the parameter tensors inside a neural net — a VGG conv kernel, a transformer dense map.\n\nThe algebra is in [Tensor Factorizations and Tensor Inverses](../tensor-factorizations/). A post on tensor inverses is coming.\n\nNumPy for CP, Tucker, and truncated HOSVD is first. Then the two compressions, then an unmixing cube: flattening loses the dyes.\n\n## Tensor data\n\n- **Film clip.** Five seconds of the 1962 *Lawrence of Arabia* theatrical trailer ([public domain, Wikimedia Commons](https://commons.wikimedia.org/wiki/File:Lawrence_Of_Arabia_(1962)_-_Trailer.webm)). Colour, picture and sound. Cut at 00:00:55 (train explosion, then the cut that follows). Files: `media/clip.mp4`, `still.png`, `frames.npy`, `clip.wav`.\n- **Conv kernel.** Synthetic $3\\times 3\\times 64\\times 64$ CP rank-16 weight plus noise, seed 7. Stands in for one VGG-16 `conv5` layer. The 512-channel counts are closed-form, not a downloaded VGG.\n- **Dense map.** Synthetic $256\\times 256$ TT-rank-4 matrix plus noise. Stands in for a $4096\\times 4096$ transformer projection. The $4096$ counts use the same formula.\n- **Mixing cube.** Synthetic $20\\times 24\\times 18$ table, three dyes plus noise: sample × emission colour × excitation colour. Seed 7. Stands in for a fluorescence excitation–emission stack.\n\nFigures and the slider read `widget-data/curves.json`, written from the same seed.\n\n<video controls width=\"480\" src=\"media/clip.mp4\"></video>\n\n\n\n## Factorizations\n\nCP, Tucker, and truncated HOSVD in NumPy. The algebra is in [Tensor Factorizations and Tensor Inverses](../tensor-factorizations/). Later sections call these same functions.\n\n### Toy cube\n\nThis section uses a synthetic $8\\times 7\\times 6$ array.\n\n- Rank-2 CP: two outer products of Gaussian bumps, plus i.i.d. Gaussian noise at $0.08$ times the clean scale, seed 7.\n- Stands in for a small 3-way table (sample × feature × condition). The size is so the factors fit on one screen.\n- Objective: recover the two components. Report $\\|X-\\hat X\\|_F/\\|X\\|_F$.\n- A flattened SVD mixes the two bumps. An overspecified CP rank invents a third. Either error mis-assigns which condition drives which feature.\n- Tensor methods fit because Kruskal uniqueness (CP) and per-mode truncation (HOSVD / Tucker) are properties of this layout, not of any matrix obtained from it.\n\n::: {#7a32b2c5 .cell execution_count=2}\n``` {.python .cell-code}\ndef bump_1d(n, center, width):\n    grid = np.linspace(0.0, 1.0, n)\n    return np.exp(-0.5 * ((grid - center) / width) ** 2)\n\n\nrng_toy = np.random.default_rng(7)\nshape = (8, 7, 6)\nterms = []\nfor center in ((0.28, 0.22, 0.30), (0.72, 0.75, 0.70)):\n    a = bump_1d(shape[0], center[0], 0.16)\n    b = bump_1d(shape[1], center[1], 0.16)\n    c = bump_1d(shape[2], center[2], 0.16)\n    terms.append(a[:, None, None] * b[None, :, None] * c[None, None, :])\nX_clean = sum(terms)\nX = X_clean + 0.08 * float(X_clean.std()) * rng_toy.normal(size=X_clean.shape)\nprint(\"X.shape\", X.shape, \"entries\", X.size)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nX.shape (8, 7, 6) entries 336\n```\n:::\n:::\n\n\n### Unfolding\n\nMode-$n$ unfolding $X_{(n)}$ puts mode $n$ on the rows. SVD of that matrix is Eckart–Young for the unfolding, not for $X$. Mode-$n$ product $X\\times_n M$ is $M$ times that unfolding, folded back.\n\n::: {#a35f8e03 .cell execution_count=3}\n``` {.python .cell-code}\ndef unfold(X, n):\n    return np.moveaxis(X, n, 0).reshape(X.shape[n], -1)\n\n\ndef fold(mat, n, shape):\n    full = [shape[n]] + [s for i, s in enumerate(shape) if i != n]\n    return np.moveaxis(mat.reshape(full), 0, n)\n\n\ndef mode_prod(X, M, n):\n    shape = list(X.shape)\n    shape[n] = M.shape[0]\n    return fold(M @ unfold(X, n), n, tuple(shape))\n```\n:::\n\n\n### Truncated HOSVD\n\nHigher-order SVD (De Lathauwer, De Moor, Vandewalle 2000): one truncated SVD per unfolding; the core is $X$ projected onto those bases. The three truncations are not jointly optimal for the Tucker loss.\n\n::: {#be894ab5 .cell execution_count=4}\n``` {.python .cell-code}\ndef truncated_hosvd(X, ranks):\n    factors = []\n    for n, r in enumerate(ranks):\n        u, _, _ = np.linalg.svd(unfold(X, n), full_matrices=False)\n        factors.append(u[:, :r])\n    core = X\n    for n, U in enumerate(factors):\n        core = mode_prod(core, U.T, n)\n    recon = core\n    for n, U in enumerate(factors):\n        recon = mode_prod(recon, U, n)\n    return recon, core, factors\n\n\ndef hosvd_approx(tensor, ranks):\n    recon, _, _ = truncated_hosvd(tensor, ranks)\n    n_params = int(\n        np.prod(ranks) + sum(s * r for s, r in zip(tensor.shape, ranks))\n    )\n    err = float(np.linalg.norm(tensor - recon) / np.linalg.norm(tensor))\n    return recon, n_params, err\n\n\nX_hosvd, G_hosvd, _ = truncated_hosvd(X, (2, 2, 2))\nprint(\"HOSVD core\", G_hosvd.shape)\nprint(f\"HOSVD relative error {T.rel_fro(X, X_hosvd):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nHOSVD core (2, 2, 2)\nHOSVD relative error 0.0619\n```\n:::\n:::\n\n\n### Tucker\n\nHOOI starts from that HOSVD and cycles modes: contract the others, replace the factor by the leading left singular vectors (Tucker 1966). TensorLy's `tucker(..., init=\"svd\")` is this pipeline.\n\n::: {#3cf5abcd .cell execution_count=5}\n``` {.python .cell-code}\ndef tucker_als(X, ranks, n_iter=15):\n    _, _, factors = truncated_hosvd(X, ranks)\n    for _ in range(n_iter):\n        for n, r in enumerate(ranks):\n            Y = X\n            for m, U in enumerate(factors):\n                if m != n:\n                    Y = mode_prod(Y, U.T, m)\n            u, _, _ = np.linalg.svd(unfold(Y, n), full_matrices=False)\n            factors[n] = u[:, :r]\n    core = X\n    for n, U in enumerate(factors):\n        core = mode_prod(core, U.T, n)\n    recon = core\n    for n, U in enumerate(factors):\n        recon = mode_prod(recon, U, n)\n    return recon, core, factors\n\n\nX_tucker, G_tucker, _ = tucker_als(X, (2, 2, 2))\nprint(\"Tucker core\", G_tucker.shape)\nprint(f\"Tucker relative error {T.rel_fro(X, X_tucker):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTucker core (2, 2, 2)\nTucker relative error 0.0619\n```\n:::\n:::\n\n\n### CP\n\nCANDECOMP/PARAFAC writes $X$ as a sum of rank-1 outer products. ALS: fix every factor but one, solve a Khatri–Rao least-squares problem, cycle (Harshman 1970; Kolda and Bader 2009). CP rank can exceed a mode size; extra columns are random if the unfolding SVD runs out of vectors.\n\n::: {#af86718d .cell execution_count=6}\n``` {.python .cell-code}\ndef khatri_rao_except(factors, skip):\n    mats = [F for i, F in enumerate(factors) if i != skip]\n    out = mats[0]\n    for F in mats[1:]:\n        out = np.einsum(\"ir,jr->ijr\", out, F).reshape(-1, out.shape[1])\n    return out\n\n\ndef cp_reconstruct(factors):\n    subs = \",\".join(f\"{chr(105 + n)}r\" for n in range(len(factors)))\n    out = \"\".join(chr(105 + n) for n in range(len(factors)))\n    return np.einsum(f\"{subs}->{out}\", *factors)\n\n\ndef cp_als(X, rank, n_iter=50, seed=7):\n    rng = np.random.default_rng(seed)\n    factors = []\n    for n in range(X.ndim):\n        u, _, _ = np.linalg.svd(unfold(X, n), full_matrices=False)\n        U = rng.normal(size=(X.shape[n], rank))\n        keep = min(rank, u.shape[1])\n        U[:, :keep] = u[:, :keep]\n        factors.append(U)\n    for _ in range(n_iter):\n        for n in range(X.ndim):\n            gram = np.ones((rank, rank))\n            for m, F in enumerate(factors):\n                if m != n:\n                    gram *= F.T @ F\n            factors[n] = (\n                unfold(X, n) @ khatri_rao_except(factors, n) @ np.linalg.pinv(gram)\n            )\n        for n in range(X.ndim - 1):\n            scale = np.linalg.norm(factors[n], axis=0, keepdims=True) + 1e-12\n            factors[n] /= scale\n            factors[-1] *= scale\n    return factors\n\n\ncp_factors = cp_als(X, rank=2, n_iter=40)\nX_cp = cp_reconstruct(cp_factors)\nprint(\"CP factor shapes\", [F.shape for F in cp_factors])\nprint(f\"CP relative error {T.rel_fro(X, X_cp):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCP factor shapes [(8, 2), (7, 2), (6, 2)]\nCP relative error 0.0619\n```\n:::\n:::\n\n\nNoise was added at $0.08$ times the clean scale. A residual near $0.06$ is that noise, not a missed component. The three fits land on the same floor because the cube *is* rank-2 CP.\n\n::: {#cell-fig-toy-factorizations .cell fig-height='2.8' fig-width='10' execution_count=7}\n``` {.python .cell-code code-fold=\"true\"}\nk = 3\npanels = (\n    (X[:, :, k], r\"data $X$\"),\n    (X_hosvd[:, :, k], \"HOSVD\"),\n    (X_tucker[:, :, k], \"Tucker\"),\n    (X_cp[:, :, k], \"CP\"),\n)\nfig, axes = plt.subplots(1, 4, figsize=(10, 2.8))\nvmax = max(np.abs(p[0]).max() for p in panels)\nfor ax, (sl, title) in zip(axes, panels):\n    ax.imshow(sl, origin=\"lower\", cmap=\"magma\", vmin=0, vmax=vmax)\n    ax.set_title(title)\n    ax.set_xticks([])\n    ax.set_yticks([])\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![One slice of the $8\\times 7\\times 6$ cube (third mode, index 3). Left to right: data, truncated HOSVD, Tucker (HOOI), CP-ALS. Rank $(2,2,2)$ / CP rank $2$.](index_files/figure-html/fig-toy-factorizations-output-1.png){#fig-toy-factorizations}\n:::\n:::\n\n\n## CP convolution\n\nVGG-16 (Simonyan and Zisserman 2015) uses $3\\times 3$ convolutions throughout. After the fourth pool the feature map is $14\\times 14$. Each of `conv5_1`, `conv5_2`, `conv5_3` maps 512 channels to 512 channels.\n\n**Before.** That kernel is a 4-way array $3\\times 3\\times 512\\times 512$: one $3\\times 3$ patch for every input–output pair. Storage $3\\cdot 3\\cdot 512\\cdot 512=2{,}359{,}296$ weights. Every spatial site on the $14\\times 14$ map pays that cost, so one forward pass is $9\\cdot 512\\cdot 512\\cdot 14\\cdot 14\\approx 462$ million multiply-adds.\n\n**What CP changes.** Canonical polyadic decomposition writes that 4-D stack as a short sum of separable pieces. In the network that becomes four skinny convolutions in a row (Lebedev et al. 2015):\n\n- $1\\times 1$ squeeze: 512 channels down to $R$.\n- Depthwise $3\\times 1$: smear vertically, one channel at a time.\n- Depthwise $1\\times 3$: smear horizontally.\n- $1\\times 1$ expand: $R$ channels back to 512.\n\nSame $3\\times 3$ receptive field as VGG. Far fewer weights. Too small an $R$ mixes input channels that should stay separate — that shows up as relative error, not as a storage bug. The usual workflow is compress a trained net, then fine-tune.\n\n**After.** Rank $64$ stores $65{,}920$ weights — $35.8\\times$ fewer. Multiply-adds drop by the same factor, because the spatial size of the map cancels. Formula: $R(2d+C_{\\mathrm{in}}+C_{\\mathrm{out}})$ against $d^{2}C_{\\mathrm{in}}C_{\\mathrm{out}}$.\n\n$$\nW_{ijkl}\\approx\\sum_{r=1}^{R}a_{ir}\\,b_{jr}\\,c_{kr}\\,d_{lr}.\n$$\n\nStorage is exact. Fit quality is relative error $\\|W-\\hat W\\|_F/\\|W\\|_F$: the leftover fraction of the kernel. A trained VGG layer is not exact CP, so some relative error remains even at rank $64$; that is why Lebedev et al. fine-tune.\n\nThe 512-channel drop is a closed-form count (no VGG is fitted). Toy relative error on a $3\\times 3\\times 64\\times 64$ kernel (true rank 16, noise $0.08$): rank 4 is $0.62$; rank 16 is $0.077$ (the noise); rank 64 is $0.066$. Rank 16 on the toy stores $2{,}144$ weights instead of $36{,}864$ ($17.2\\times$).\n\n::: {#37db8cdc .cell execution_count=8}\n``` {.python .cell-code}\nW, _ = T.make_cp_kernel(np.random.default_rng(T.SEED))\nW_hat = cp_reconstruct(cp_als(W, rank=16, n_iter=40))\nn_cp = T.cp_conv_params(W.shape[0], W.shape[2], W.shape[3], 16)\nprint(\"kernel\", W.shape)\nprint(\n    f\"CP rank 16: {n_cp:,} / {W.size:,} weights \"\n    f\"({W.size / n_cp:.1f}x), \"\n    f\"relative error {T.rel_fro(W, W_hat):.3f}\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nkernel (3, 3, 64, 64)\nCP rank 16: 2,144 / 36,864 weights (17.2x), relative error 0.077\n```\n:::\n:::\n\n\n## TT-matrix dense layers\n\nA transformer block at model dimension $4096$ stores square maps of that width: the output projection of multi-head attention $W_O\\in\\mathbb{R}^{4096\\times 4096}$ (Vaswani et al. 2017). Novikov et al. (2015) write a dense matrix of this kind as a tensor-train.\n\n**Before.** Mapping 4096 numbers to 4096 numbers stores $4096^{2}=16{,}777{,}216$ weights. Multiplying a residual-stream vector by $W_O$ costs $O(N^{2})$.\n\n**What a TT-matrix changes.** Factor $4096=8\\times 8\\times 8\\times 8$. Fold the rectangle into a higher-order array and write it as a chain of small cores $G_k\\in\\mathbb{R}^{r_{k-1}\\times 8\\times 8\\times r_k}$ (Novikov et al. 2015; Oseledets 2011). Multiplying a vector is a sweep along that chain, not one huge matmul. Storage at equal mode size $n$ and internal rank $r$ is $O(d n^{2} r^{2})$, not $O(N^{2})$.\n\n**After.** Rank $16$ stores $34{,}816$ weights — $481.9\\times$ fewer. Apply cost drops to $O(d r^{2} n N)$. Ordinary SVD of the unfolded rectangle cannot see that chain: a map that is low-rank *after folding* still looks high-rank as a matrix, so its relative error stays large.\n\nThe 4096-wide drop is closed-form (no transformer is fitted). @fig-param-impact is both layers at those ranks. Toy relative error on a $256\\times 256$ map built at TT-rank 4 plus noise $0.08$: TT-rank 4 is $0.079$ on $640$ weights; SVD rank 4 is $0.932$ on $2{,}052$ weights; SVD rank 64 is $0.436$ on $32{,}832$ weights.\n\n::: {#b7908d81 .cell execution_count=9}\n``` {.python .cell-code}\nms = ns = [T.TT_MODE] * T.TT_ORDER\nM, _ = T.make_tt_matrix(np.random.default_rng(T.SEED), ms, ns)\ncores = T.tt_matrix_svd(M, ms, ns, max_rank=4)\nM_tt = T.tt_matrix_to_dense(cores)\nprint(\"matrix\", M.shape, \"TT cores\", [c.shape for c in cores])\nprint(f\"TT-rank 4 relative error {T.rel_fro(M, M_tt):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmatrix (256, 256) TT cores [(1, 4, 4, 4), (4, 4, 4, 4), (4, 4, 4, 4), (4, 4, 4, 1)]\nTT-rank 4 relative error 0.079\n```\n:::\n:::\n\n\n::: {#cell-fig-param-impact .cell fig-height='3.8' fig-width='10' execution_count=10}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(10, 3.8))\nlayer_impact(\n    axes,\n    [\"VGG-16 conv5\", r\"Transformer $W_O$\"],\n    [CP[\"headline\"][\"dense_params\"], TT[\"headline\"][\"dense_params\"]],\n    [CP[\"headline\"][\"cp_params\"], TT[\"headline\"][\"tt_params\"]],\n    [ACCENT, TEAL],\n)\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Closed-form storage at the ranks in the two sections. Left: weights, dense vs kept. Middle: compression (dense / kept). Right: fraction of the dense layer that remains. No network is fitted.](index_files/figure-html/fig-param-impact-output-1.png){#fig-param-impact}\n:::\n:::\n\n\nThe slider below varies rank. Relative error there is the toys.\n\n::: {.widget-container}\n::: {.widget-header}\n<span class=\"widget-title\">Seven ranks — weights and relative error</span>\n<span class=\"widget-badge\">runs in the browser</span>\n:::\n<div id=\"tf-widget\"></div>\n<div class=\"widget-note\">Seven ranks. Defaults are the ranks the toys were built at (CP 16, TT 4) — the gold band on the error plot. Weight bars are VGG-16 conv5 / transformer $W_O$ closed-form counts, not the toys.</div>\n:::\n\n## Complexity\n\nThe table answers two questions: how many numbers you store, and how much arithmetic one forward pass costs. $H,W$ are the spatial size of a feature map. $N=n^{d}$ is one side of a square TT-matrix with $d$ equal modes. Apply is the thing you run at inference — a convolution, or $Wx$.\n\n| Method | Storage | Apply |\n|---|---|---|\n| Dense conv | $O(d^{2}C_{\\mathrm{in}}C_{\\mathrm{out}})$ | $O(d^{2}C_{\\mathrm{in}}C_{\\mathrm{out}}HW)$ |\n| CP-conv rank $R$ | $O(R(2d+C_{\\mathrm{in}}+C_{\\mathrm{out}}))$ | $O(R(C_{\\mathrm{in}}+2d+C_{\\mathrm{out}})HW)$ |\n| Dense $M\\times N$ | $O(MN)$ | $O(MN)$ |\n| SVD rank $k$ | $O(k(M+N))$ | $O(k(M+N))$ |\n| TT-matrix rank $r$, $d$ modes of size $n$ | $O(d n^{2} r^{2})$ | $O(d r^{2} n N)$ |\n\nThe VGG-16 `conv5` counts and the $4096$ transformer map are the closed-form counts from the two sections above. The clock below is NumPy on the toy 64-channel kernel and a $16\\times 16$ map — not a cuDNN GEMM. Factorized is still fewer multiply-adds; wall-clock can go the other way on a GPU once the chain of small contractions becomes memory-bound.\n\n::: {#conv-timing .cell execution_count=11}\n``` {.python .cell-code}\nrng = np.random.default_rng(T.SEED)\nW, _ = T.make_cp_kernel(rng)\nweights, factors = parafac(W, rank=16, n_iter_max=40, init=\"svd\")\nX = rng.normal(size=(16, 16, 64))\nd = 3\nA_f, B_f, C_f, D_f = factors\n\n\ndef dense_conv():\n    out = np.zeros((14, 14, 64))\n    for i in range(d):\n        for j in range(d):\n            out += X[i : i + 14, j : j + 14] @ W[i, j]\n    return out\n\n\ndef cp_conv():\n    z = X @ C_f\n    y1 = np.zeros((14, 16, 16))\n    for i in range(d):\n        y1 += z[i : i + 14] * A_f[i]\n    y2 = np.zeros((14, 14, 16))\n    for j in range(d):\n        y2 += y1[:, j : j + 14] * B_f[j]\n    return y2 @ D_f.T\n\n\nyd, yc = dense_conv(), cp_conv()\nt_dense = bench(dense_conv)\nt_cp = bench(cp_conv)\nprint(\n    f\"conv rel error {np.linalg.norm(yd - yc) / np.linalg.norm(yd):.4f}; \"\n    f\"dense {t_dense * 1e3:.2f} ms; CP {t_cp * 1e3:.2f} ms; \"\n    f\"speedup {t_dense / t_cp:.1f}x\"\n)\nprint(\n    f\"headline MACs 512-ch 14x14: dense {9 * 512 * 512 * 196:,} vs \"\n    f\"CP {64 * (512 + 6 + 512) * 196:,} ({(9 * 512 * 512) / (64 * 1030):.1f}x)\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nconv rel error 0.1057; dense 0.13 ms; CP 0.05 ms; speedup 2.8x\nheadline MACs 512-ch 14x14: dense 462,422,016 vs CP 12,920,320 (35.8x)\n```\n:::\n:::\n\n\n### A film clip\n\nA pixel is three numbers: red, green, blue. Height and width stack those triples into an image. Colour is a third mode of the array; time is a fourth. The clip is those four modes in one tensor.\n\n\n\n::: {#cell-fig-tensor-containers .cell fig-height='4.15' fig-width='12.2' execution_count=13}\n``` {.python .cell-code}\nCHAN = [\"#C0392B\", \"#1E8449\", \"#2471A3\"]\nrh, rw = 12, 16\nsat = still.astype(float).std(axis=2)\nbest, pos = -1.0, (0, 0)\nfor i in range(0, still.shape[0] - rh, 3):\n    for j in range(0, still.shape[1] - rw, 4):\n        score = float(sat[i : i + rh, j : j + rw].mean())\n        if score > best:\n            best, pos = score, (i, j)\nr0, c0 = pos\npix = still[r0 : r0 + rh, c0 : c0 + rw]\ncrop_box = (c0, r0, rw, rh)  # x, y, w, h in image coords\nH_img, W_img = still.shape[:2]\nn_t = frames.shape[-1]\nt_idx = (0, n_t // 2, n_t - 1)\n\nfig = plt.figure(figsize=(12.2, 4.15))\ngs = fig.add_gridspec(1, 4, width_ratios=[1.05, 1.12, 1.22, 1.55], wspace=0.22)\n\nax0 = fig.add_subplot(gs[0])\nax0.imshow(pix.astype(np.uint8), interpolation=\"nearest\")\nny, nx = pix.shape[:2]\nax0.set_xticks(np.arange(-0.5, nx, 1), minor=True)\nax0.set_yticks(np.arange(-0.5, ny, 1), minor=True)\nax0.grid(which=\"minor\", color=\"white\", lw=0.55)\nax0.tick_params(which=\"both\", bottom=False, left=False, labelbottom=False, labelleft=False)\nax0.set_title(\"pixels\", fontsize=11, pad=8)\nax0.set_xlabel(\"each cell is (R, G, B)\", fontsize=9, color=\"#5F6672\")\nfor spine in ax0.spines.values():\n    spine.set_color(INK)\n    spine.set_linewidth(0.8)\n\nax1 = fig.add_subplot(gs[1])\nax1.imshow(still.astype(np.uint8))\nax1.add_patch(\n    Rectangle(\n        (crop_box[0] - 0.5, crop_box[1] - 0.5),\n        crop_box[2],\n        crop_box[3],\n        fill=False,\n        edgecolor=CORAL,\n        lw=1.4,\n    )\n)\nax1.set_title(\"image\", fontsize=11, pad=8)\nax1.tick_params(bottom=False, left=False, labelbottom=False, labelleft=False)\nax1.annotate(\n    \"\",\n    xy=(-0.04, 0.02),\n    xytext=(-0.04, 0.98),\n    xycoords=\"axes fraction\",\n    textcoords=\"axes fraction\",\n    arrowprops=dict(arrowstyle=\"<->\", color=ACCENT, lw=1.4),\n)\nax1.text(\n    -0.10, 0.5, \"height\", rotation=90, va=\"center\", ha=\"center\",\n    color=ACCENT, fontsize=9, transform=ax1.transAxes,\n)\nax1.annotate(\n    \"\",\n    xy=(0.02, -0.04),\n    xytext=(0.98, -0.04),\n    xycoords=\"axes fraction\",\n    textcoords=\"axes fraction\",\n    arrowprops=dict(arrowstyle=\"<->\", color=TEAL, lw=1.4),\n)\nax1.text(\n    0.5, -0.12, \"width\", ha=\"center\", va=\"top\",\n    color=TEAL, fontsize=9, transform=ax1.transAxes,\n)\nax1.text(\n    0.5, -0.22, rf\"$H \\times W = {H_img}\\times {W_img}$\",\n    ha=\"center\", va=\"top\", fontsize=9, color=\"#5F6672\",\n    transform=ax1.transAxes,\n)\nfor spine in ax1.spines.values():\n    spine.set_visible(False)\n\nax2 = fig.add_subplot(gs[2])\nax2.set_xlim(0.05, 2.55)\nax2.set_ylim(-0.35, 2.35)\nax2.set_aspect(\"equal\")\nax2.axis(\"off\")\nax2.set_title(\"3-tensor\", fontsize=11, pad=8)\nc2 = draw_mode_cube(\n    ax2, origin=np.array([0.22, 0.28]), image=still,\n    size=(1.55, 1.55, 0.42), depth=0.42, scale=1.0, chan_colors=CHAN,\n)\ndim_arrow(ax2, c2[\"bl\"], c2[\"br\"], \"width\", TEAL, outward=-1.0)\ndim_arrow(ax2, c2[\"bl\"], c2[\"tl\"], \"height\", ACCENT, outward=1.0)\ndim_arrow(ax2, c2[\"br\"], c2[\"brz\"], \"color\", CORAL, outward=-1.15, fontsize=8)\nax2.text(\n    1.28, -0.28, r\"$H \\times W \\times C$\",\n    ha=\"center\", va=\"top\", fontsize=9, color=\"#5F6672\",\n)\nfor i, lab in enumerate(\"RGB\"):\n    ax2.text(\n        c2[\"brz\"][0] + 0.10,\n        c2[\"br\"][1] + (c2[\"tr\"][1] - c2[\"br\"][1]) * (0.18 + 0.32 * i),\n        lab,\n        color=CHAN[i],\n        fontsize=8,\n        ha=\"left\",\n        va=\"center\",\n        fontweight=\"bold\",\n    )\n\nax3 = fig.add_subplot(gs[3])\nax3.set_xlim(0.0, 3.35)\nax3.set_ylim(-0.45, 2.58)\nax3.set_aspect(\"equal\")\nax3.axis(\"off\")\nax3.set_title(\"4-tensor\", fontsize=11, pad=8)\norigins = [np.array([0.12, 0.18]), np.array([0.78, 0.46]), np.array([1.44, 0.74])]\ncubes = [None] * 3\nfor i in reversed(range(3)):\n    cubes[i] = draw_mode_cube(\n        ax3, origin=origins[i], image=frames[:, :, :, t_idx[i]],\n        size=(1.05, 1.05, 0.28), depth=0.28, scale=1.0, chan_colors=CHAN,\n    )\nc0 = cubes[0]\ndim_arrow(ax3, c0[\"bl\"], c0[\"br\"], \"width\", TEAL, outward=-1.05, fontsize=8)\ndim_arrow(ax3, c0[\"bl\"], c0[\"tl\"], \"height\", ACCENT, outward=1.05, fontsize=8)\ndim_arrow(ax3, c0[\"br\"], c0[\"brz\"], \"color\", CORAL, outward=-1.2, fontsize=8)\nax3.annotate(\n    \"\",\n    xy=cubes[-1][\"trz\"] + np.array([0.08, 0.12]),\n    xytext=c0[\"tlz\"] + np.array([-0.02, 0.12]),\n    arrowprops=dict(arrowstyle=\"->\", color=GOLD, lw=1.45),\n)\nax3.text(\n    1.95, 2.22, \"time\", color=GOLD, fontsize=9, ha=\"center\", va=\"bottom\",\n)\nfor cube, t in zip(cubes, t_idx):\n    ax3.text(\n        0.5 * (cube[\"tl\"][0] + cube[\"tr\"][0]),\n        cube[\"tlz\"][1] + 0.10,\n        f\"t = {t}\",\n        fontsize=8,\n        color=\"#5F6672\",\n        ha=\"center\",\n        va=\"bottom\",\n    )\nax3.text(\n    1.65, -0.38, r\"$H \\times W \\times C \\times T$\",\n    ha=\"center\", va=\"top\", fontsize=9, color=\"#5F6672\",\n)\nax3.text(\n    1.65, -0.58, rf\"$120\\times 160\\times 3\\times {n_t}$\",\n    ha=\"center\", va=\"top\", fontsize=8, color=\"#5F6672\",\n)\n\nfig.subplots_adjust(left=0.04, right=0.99, top=0.86, bottom=0.16)\n```\n\n::: {.cell-output .cell-output-display}\n![Pixel triples stacked into tensor containers. Height and width make an image; colour is a third mode; time stacks frames into a 4-tensor.](index_files/figure-html/fig-tensor-containers-output-1.png){#fig-tensor-containers}\n:::\n:::\n\n\nThe source clip is in Tensor data: 5 s, picture and sound. Truncated HOSVD (one SVD per mode, no HOOI) compresses the still, the RGB video, and the soundtrack STFT. Ranks target relative error about $0.05$. Reconstructed picture and sound are muxed into `media/clip-hosvd.mp4`. It is the same `truncated_hosvd` as in Factorizations.\n\n::: {#c023fc24 .cell execution_count=14}\n``` {.python .cell-code}\nIMG_RANKS = (20, 28, 3)\nVID_RANKS = (60, 80, 3, 30)\nAUD_RANKS = (88, 140, 2)\nstill_hat, still_core, _ = truncated_hosvd(still, IMG_RANKS)\nprint(\"still\", still.shape, \"→ core\", still_core.shape)\nprint(f\"still relative error {T.rel_fro(still, still_hat):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nstill (240, 320, 3) → core (20, 28, 3)\nstill relative error 0.049\n```\n:::\n:::\n\n\n\n\n### Video\n\nStill $240\\times 320\\times 3$, ranks $(20,28,3)$. Clip $120\\times 160\\times 3\\times 60$, ranks $(60,80,3,30)$. Time is its own mode, so motion is not smeared into space.\n\n::: {#cell-fig-film-video-stats .cell fig-height='3.6' fig-width='10' execution_count=16}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(10, 3.6))\nclip_tradeoff(\n    axes,\n    [\"Still\", \"Video\"],\n    [still.size, frames.size],\n    [img_params, vid_params],\n    [\"Still\", \"Video\"],\n    [img_err, vid_err],\n    ACCENT,\n)\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Still and video after HOSVD. Left: numbers stored, dense vs kept. Middle: compression (dense / kept). Right: relative error.](index_files/figure-html/fig-film-video-stats-output-1.png){#fig-film-video-stats}\n:::\n:::\n\n\n- Still: $15,449$ / $230,400$ numbers ($14.9\\times$), relative error $0.049$.\n- Video: $453,809$ / $3,456,000$ ($7.6\\times$), relative error $0.049$.\n\n\n\n::: {#cell-fig-film-still .cell fig-height='3.8' fig-width='10' execution_count=18}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(10, 3.8))\nfor ax, arr, title in (\n    (axes[0], still, \"original\"),\n    (axes[1], np.clip(img_hat, 0, 255), \"compressed\"),\n):\n    ax.imshow(arr.astype(np.uint8))\n    ax.set_title(title)\n    ax.set_axis_off()\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![One trailer frame. Left: original. Right: compressed (keep 20 height pieces, 28 width pieces, and all 3 colour channels).](index_files/figure-html/fig-film-still-output-1.png){#fig-film-still}\n:::\n:::\n\n\nOriginal 5 s clip (picture and sound):\n\n<video controls width=\"480\" src=\"media/clip.mp4\"></video>\n\nAfter HOSVD. Video relative error $0.049$.\n\n\n\n<video controls width=\"480\" src=\"media/clip-hosvd.mp4\"></video>\n\n::: {#cell-fig-film-video .cell fig-height='4.4' fig-width='10' execution_count=20}\n``` {.python .cell-code}\nn_t = frames.shape[-1]\nidx = (0, n_t // 2, n_t - 1)\nfig, axes = plt.subplots(2, 3, figsize=(10, 4.4))\nfor j, t in enumerate(idx):\n    axes[0, j].imshow(np.clip(frames[:, :, :, t], 0, 255).astype(np.uint8))\n    axes[1, j].imshow(np.clip(vid_hat[:, :, :, t], 0, 255).astype(np.uint8))\n    axes[0, j].set_title(f\"original, frame {t}\")\n    axes[1, j].set_title(f\"compressed, frame {t}\")\n    axes[0, j].set_axis_off()\n    axes[1, j].set_axis_off()\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Three frames from the 5 s clip. Top: original. Bottom: compressed. Time is kept as its own axis, so motion is not smeared into space.](index_files/figure-html/fig-film-video-output-1.png){#fig-film-video}\n:::\n:::\n\n\n\n\n### Audio\n\nA microphone stores air pressure as one number per sample. That list is a 1-tensor: one mode, time. Factorizing it is a 1-D SVD — there is no second mode to separate.\n\nThe short-time Fourier transform (STFT) cuts the list into overlapping windows and writes each window as a spectrum. Stack the spectra along time. The array is frequency $\\times$ time, a 2-tensor — the same layout as a greyscale image. Each bin is complex, so split real and imaginary into a third mode. Frequency $\\times$ time $\\times$ \\{real, imag\\} is a 3-tensor, the same layout as an RGB still.\n\nThis clip: 5 s mono at 8 kHz. Window $n=256$, hop $128$. Truncated HOSVD ranks $(88,140,2)$.\n\n- **samples** — each cell is one pressure number.\n- **1-tensor** — the waveform. Overlapping windows are the STFT cuts.\n- **2-tensor** — those spectra stacked: frequency $\\times$ time.\n- **3-tensor** — add \\{real, imag\\}, the way colour is added to an image.\n\n::: {#cell-fig-audio-containers .cell fig-height='4.2' fig-width='12.2' execution_count=22}\n``` {.python .cell-code}\nNPER = 256\nHOP = NPER // 2\npeak = int(np.argmax(np.abs(wav)))\nn_show = 16\ni_samp = max(0, peak - n_show // 2)\nsamps = wav[i_samp : i_samp + n_show]\nview = int(0.28 * sr)\ni0 = max(0, peak - view // 2)\ni1 = min(wav.size, i0 + view)\nwin_starts = [\n    s for s in range(0, wav.size - NPER + 1, HOP)\n    if s + NPER > i0 and s < i1\n][:5]\nwin_cols = [ACCENT, TEAL, CORAL, GOLD, \"#5F6672\"]\nREIM = [CORAL, TEAL]\nspec_img = spec_to_rgb(Z)\n\nfig = plt.figure(figsize=(12.2, 4.2))\ngs = fig.add_gridspec(1, 4, width_ratios=[1.02, 1.18, 1.22, 1.45], wspace=0.28)\n\nax0 = fig.add_subplot(gs[0])\nvmax = float(np.max(np.abs(samps))) + 1e-9\nax0.imshow(\n    samps[np.newaxis, :],\n    cmap=\"coolwarm\",\n    vmin=-vmax,\n    vmax=vmax,\n    interpolation=\"nearest\",\n    aspect=\"auto\",\n)\nax0.set_xticks(np.arange(-0.5, n_show, 1), minor=True)\nax0.set_yticks([-0.5, 0.5], minor=True)\nax0.grid(which=\"minor\", color=\"white\", lw=0.7)\nax0.tick_params(which=\"both\", bottom=False, left=False, labelbottom=False, labelleft=False)\nax0.set_title(\"samples\", fontsize=11, pad=8)\nax0.set_xlabel(\"each cell is one number\", fontsize=9, color=\"#5F6672\")\nfor spine in ax0.spines.values():\n    spine.set_color(INK)\n    spine.set_linewidth(0.8)\n\nax1 = fig.add_subplot(gs[1])\ntt = np.arange(i0, i1) / sr\nax1.plot(tt, wav[i0:i1], color=INK, lw=1.05, zorder=3)\nfor k, s in enumerate(win_starts):\n    ax1.axvspan(\n        s / sr, (s + NPER) / sr,\n        color=win_cols[k % len(win_cols)], alpha=0.22, lw=0, zorder=0,\n    )\nax1.axvline(i_samp / sr, color=CORAL, lw=1.0, ls=\":\", zorder=4)\nax1.axvline((i_samp + n_show) / sr, color=CORAL, lw=1.0, ls=\":\", zorder=4)\nax1.set_title(\"1-tensor\", fontsize=11, pad=8)\nax1.tick_params(length=0)\nax1.set_yticks([])\nax1.annotate(\n    \"\",\n    xy=(0.02, -0.08),\n    xytext=(0.98, -0.08),\n    xycoords=\"axes fraction\",\n    textcoords=\"axes fraction\",\n    arrowprops=dict(arrowstyle=\"<->\", color=TEAL, lw=1.4),\n)\nax1.text(\n    0.5, -0.18, \"time\", ha=\"center\", va=\"top\",\n    color=TEAL, fontsize=9, transform=ax1.transAxes,\n)\nax1.text(\n    0.5, -0.30, rf\"$N = {wav.size}$ samples\",\n    ha=\"center\", va=\"top\", fontsize=9, color=\"#5F6672\",\n    transform=ax1.transAxes,\n)\nfor spine in ax1.spines.values():\n    spine.set_visible(False)\nax1.set_xlim(tt[0], tt[-1])\n\nax2 = fig.add_subplot(gs[2])\nax2.pcolormesh(\n    stft_times, stft_freq, spec_db(Z),\n    cmap=\"magma\", shading=\"auto\",\n)\nax2.set_title(\"2-tensor\", fontsize=11, pad=8)\nax2.tick_params(length=0, labelsize=8)\nax2.set_xticks([])\nax2.set_yticks([])\nax2.annotate(\n    \"\",\n    xy=(-0.04, 0.02),\n    xytext=(-0.04, 0.98),\n    xycoords=\"axes fraction\",\n    textcoords=\"axes fraction\",\n    arrowprops=dict(arrowstyle=\"<->\", color=ACCENT, lw=1.4),\n)\nax2.text(\n    -0.12, 0.5, \"frequency\", rotation=90, va=\"center\", ha=\"center\",\n    color=ACCENT, fontsize=9, transform=ax2.transAxes,\n)\nax2.annotate(\n    \"\",\n    xy=(0.02, -0.04),\n    xytext=(0.98, -0.04),\n    xycoords=\"axes fraction\",\n    textcoords=\"axes fraction\",\n    arrowprops=dict(arrowstyle=\"<->\", color=TEAL, lw=1.4),\n)\nax2.text(\n    0.5, -0.14, \"time\", ha=\"center\", va=\"top\",\n    color=TEAL, fontsize=9, transform=ax2.transAxes,\n)\nax2.text(\n    0.5, -0.26, rf\"$F \\times T = {Z.shape[0]}\\times {Z.shape[1]}$\",\n    ha=\"center\", va=\"top\", fontsize=9, color=\"#5F6672\",\n    transform=ax2.transAxes,\n)\nfor spine in ax2.spines.values():\n    spine.set_visible(False)\n\nax3 = fig.add_subplot(gs[3])\nax3.set_xlim(0.05, 2.55)\nax3.set_ylim(-0.40, 2.38)\nax3.set_aspect(\"equal\")\nax3.axis(\"off\")\nax3.set_title(\"3-tensor\", fontsize=11, pad=8)\nc3 = draw_mode_cube(\n    ax3, origin=np.array([0.22, 0.32]), image=spec_img,\n    size=(1.55, 1.55, 0.38), depth=0.38, scale=1.0, chan_colors=REIM,\n)\ndim_arrow(ax3, c3[\"bl\"], c3[\"br\"], \"time\", TEAL, outward=-1.0)\ndim_arrow(ax3, c3[\"bl\"], c3[\"tl\"], \"frequency\", ACCENT, outward=1.0)\ndim_arrow(ax3, c3[\"br\"], c3[\"brz\"], \"real / imag\", CORAL, outward=-1.2, fontsize=8)\nax3.text(\n    1.28, -0.32, r\"$F \\times T \\times 2$\",\n    ha=\"center\", va=\"top\", fontsize=9, color=\"#5F6672\",\n)\nfor i, lab in enumerate((\"Re\", \"Im\")):\n    ax3.text(\n        c3[\"brz\"][0] + 0.10,\n        c3[\"br\"][1] + (c3[\"tr\"][1] - c3[\"br\"][1]) * (0.28 + 0.44 * i),\n        lab,\n        color=REIM[i],\n        fontsize=8,\n        ha=\"left\",\n        va=\"center\",\n        fontweight=\"bold\",\n    )\n\nfig.subplots_adjust(left=0.05, right=0.99, top=0.86, bottom=0.18)\n```\n\n::: {.cell-output .cell-output-display}\n![Pressure samples stacked into tensor containers. The waveform is a 1-tensor. The STFT makes a 2-tensor (frequency × time). Real and imaginary parts are a third mode, as colour is for an image.](index_files/figure-html/fig-audio-containers-output-1.png){#fig-audio-containers}\n:::\n:::\n\n\n::: {#cell-fig-film-audio-stats .cell fig-height='3.6' fig-width='10' execution_count=23}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 3, figsize=(10, 3.6))\nclip_tradeoff(\n    axes,\n    [\"STFT\"],\n    [stft_t.size],\n    [aud_params],\n    [\"STFT tensor\", \"Complex\", \"Waveform\"],\n    [aud_err[\"stft_tensor\"], aud_err[\"stft_complex\"], aud_err[\"waveform\"]],\n    TEAL,\n)\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![Soundtrack STFT after HOSVD. Left: numbers stored, dense vs kept. Middle: compression (dense / kept). Right: relative error on the STFT tensor, the complex STFT, and the waveform.](index_files/figure-html/fig-film-audio-stats-output-1.png){#fig-film-audio-stats}\n:::\n:::\n\n\n- STFT: $79,956$ / $81,012$ numbers ($1.01\\times$).\n- Relative error: STFT tensor $0.056$, complex $0.056$, waveform $0.039$.\n\n\n\n::: {#cell-fig-film-audio .cell fig-height='5' fig-width='10' execution_count=25}\n``` {.python .cell-code}\nt_wav = np.arange(wav.size) / sr\nfig, axes = plt.subplots(2, 2, figsize=(10, 5.0), sharex=\"col\", sharey=\"row\")\nfor ax, z, title in (\n    (axes[0, 0], Z, \"original\"),\n    (axes[0, 1], Z_hat, \"compressed\"),\n):\n    im = ax.pcolormesh(\n        stft_times, stft_freq, spec_db(z),\n        cmap=\"magma\", shading=\"auto\",\n    )\n    ax.set_title(title)\n    ax.set_ylabel(\"frequency (Hz)\")\nfor ax, y in (\n    (axes[1, 0], wav),\n    (axes[1, 1], wav_hat),\n):\n    ax.plot(t_wav, y, color=INK, lw=0.55)\n    ax.set_xlabel(\"time (s)\")\n    ax.set_ylabel(\"pressure\")\n    ax.set_xlim(0, t_wav[-1])\nfig.colorbar(im, ax=axes[0], fraction=0.03, pad=0.02, label=\"loudness (dB)\")\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n/var/folders/p9/vwq0gfs15vb07tg6xw1r14180000gn/T/ipykernel_23493/2602618714.py:22: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.\n  fig.tight_layout()\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Original vs compressed. Top: STFT magnitude. Bottom: waveform after inverting the compressed STFT.](index_files/figure-html/fig-film-audio-output-2.png){#fig-film-audio}\n:::\n:::\n\n\nOriginal soundtrack:\n\n<audio controls src=\"media/clip.wav\"></audio>\n\nCompressed soundtrack. Relative error $0.039$ (waveform), $0.056$ (STFT tensor).\n\n\n\n<audio controls src=\"media/clip-cp.wav\"></audio>\n\n## Unmixing\n\n### Assay\n\nYou want how much of each dye is in each well. The dyes are already mixed; you cannot pipette them apart.\n\nThe instrument shines one excitation colour into one well and records how bright that well is at one emission colour. That number is **intensity**. Sweep both colours and one well becomes a map (emission colour × excitation colour). Twenty wells become a stack of twenty maps.\n\nThat stack is a 3-way tensor $\\mathcal{X}\\in\\mathbb{R}^{20\\times 24\\times 18}$.\n\n- **Sample** (20). Which well.\n- **Emission colour** (24). Colour coming out.\n- **Excitation colour** (18). Colour shone in.\n- **Intensity.** The value in each cell, not a fourth axis.\n\nDye is not an axis of $\\mathcal{X}$. Each dye is one rank-1 tensor: amount × emission spectrum × excitation spectrum. The observed cube is the sum of three of those, plus noise.\n\nThe maps do not give the amounts. The three fingerprints overlap, so a bright spot is a mix. Flatten the two colour axes into one long row and the cube becomes a $20\\times 432$ matrix: SVD then returns mixed dyes. CP keeps the three axes and recovers the amounts.\n\nThis cube is synthetic (seed 7, noise $0.08$). It stands in for a fluorescence excitation–emission stack. No wet-lab data.\n\n@fig-mixing-assay is the whole assay: settings in, one observation out, that tensor, and what the two splits return.\n\n\n\n::: {.column-page}\n![You want dye amounts; you measure intensity. Top: twenty wells of mixed dye; three settings — which well, which excitation colour, which emission colour; the instrument returns one observation. Sweeping the two colour settings gives one map per well, and stacking the wells gives $\\mathcal{X}\\in\\mathbb{R}^{20\\times 24\\times 18}$, 8,640 readings. Middle: the three rank-1 dyes the cube is made of; their amounts overlap. Bottom: CP returns the dyes, flatten-then-SVD returns mixes. Drawn; the cube is synthetic, seed 7.](media/mixing-assay.png){#fig-mixing-assay fig-alt=\"Drawn assay poster in five numbered stages. One, the samples: a scientist in a lab coat and goggles pipettes three dyes into a twenty-well plate, one well ringed. Two, the settings: a console listing well 11 of 20, excitation colour 10 of 18, emission colour 13 of 24. Three, the instrument: lamp, prism and slit picking the excitation colour, the well, then emission read at ninety degrees through a second prism and slit. Four, the observation: a detector and a single intensity, 0.95. Five, the tensor: the swept map for that well, then twenty such maps stacked into a 20 by 24 by 18 cube. Middle band: the three rank-1 dyes, each an emission-by-excitation map with its two spectra, and their overlapping amounts. Bottom: branch A, CP returns the three dye maps and matching amounts; branch B, flattening then SVD returns mixed maps and amounts that go negative.\"}\n:::\n\n### Recoveries\n\n@fig-mixing is CP versus flatten-then-SVD on that cube.\n\n![It opens on the instrument, then builds the cube dye by dye. Each sample is an emission × excitation map; the needle marks that sample. CP recovers the three dyes. Flatten-then-SVD returns mixed dyes.](media/mixing.gif){#fig-mixing fig-alt=\"Animation: a drawn fluorimeter reads one intensity, then three dyes build a cube of emission-excitation maps, then CP recovers the dyes and flatten-then-SVD mixes them.\"}\n\n::: {#887a109c .cell execution_count=28}\n``` {.python .cell-code}\ncube, true = T.make_mixing_cube(np.random.default_rng(T.SEED))\nmix_factors = cp_als(cube, rank=3, n_iter=80)\nX_cp_mix = cp_reconstruct(mix_factors)\n_, cp_corr = T.align_factors(true[0], mix_factors[0])\nu, _, _ = np.linalg.svd(cube.reshape(cube.shape[0], -1), full_matrices=False)\n_, svd_corr = T.align_factors(true[0], u[:, :3])\nprint(\"cube\", cube.shape)\nprint(\n    f\"CP relative error {T.rel_fro(cube, X_cp_mix):.3f}, \"\n    f\"mean |corr| {float(np.mean(cp_corr)):.2f}\"\n)\nprint(f\"flatten-SVD mean |corr| {float(np.mean(svd_corr)):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncube (20, 24, 18)\nCP relative error 0.071, mean |corr| 1.00\nflatten-SVD mean |corr| 0.536\n```\n:::\n:::\n\n\n- **What you measure** (the sweep). One map per sample. Bright spots move as the mix changes. The methods see only those maps.\n- **CP.** Write the cube as three outer products, one per dye. Amount correlation $1.00$. Leftover error $0.071$ is the noise that was added. Kruskal's condition holds ($k_A+k_B+k_C\\ge 2R+2$ at rank $3$), so this split is unique up to renaming and scaling the dyes.\n- **Flatten, then SVD.** Stack each map into one long row. The cube becomes a $20\\times 432$ matrix. SVD finds three directions among the samples; they are mixes of the dyes (correlation $0.536$). Amounts go negative. The maps are not the dyes.\n\nAn unfolding SVD can reconstruct the matrix well and still not return the sources.\n\n## Constraints\n\n- **GEMM vs contractions.** One large matrix multiply is replaced by a chain of small tensor contractions. On GPUs that chain is often memory-bound; theoretical MAC drop is not wall-clock. [cuTENSOR](https://developer.nvidia.com/cutensor) and [TensorLy-Torch](https://tensorly.org/torch/dev/) exist to close part of that gap (Kossaifi et al. 2019).\n- **Lossy fit.** Truncation discards higher-order mass. Lebedev et al. compress then fine-tune; a raw CP or TT drop-in lowers accuracy.\n- **Rank search.** Exact CP rank is NP-hard. ALS can split a component or stall. The synthetic residuals above flatten at the noise floor only because the generating rank is known.\n\nDon't. Flatten. Modes. Carry. Meaning. Ranks. Trade. Memory. Factorizations. Almost. Always.\n\n## References\n\n- Håstad, J. (1990). Tensor rank is NP-complete. *Journal of Algorithms* 11(4), 644–654.\n- Harshman, R. A. (1970). Foundations of the PARAFAC procedure. *UCLA Working Papers in Phonetics* 16, 1–84.\n- Tucker, L. R. (1966). Some mathematical notes on three-mode factor analysis. *Psychometrika* 31(3), 279–311.\n- De Lathauwer, L., De Moor, B., and Vandewalle, J. (2000). A multilinear singular value decomposition. *SIAM Journal on Matrix Analysis and Applications* 21(4), 1253–1278.\n- Kolda, T. G., and Bader, B. W. (2009). Tensor decompositions and applications. *SIAM Review* 51(3), 455–500.\n- Oseledets, I. V. (2011). Tensor-train decomposition. *SIAM Journal on Scientific Computing* 33(5), 2295–2317.\n- Lebedev, V., Ganin, Y., Rakhuba, M., Oseledets, I., and Lempitsky, V. (2015). [Speeding-up convolutional neural networks using fine-tuned CP-decomposition](https://arxiv.org/abs/1412.6553). ICLR workshop.\n- Simonyan, K., and Zisserman, A. (2015). [Very Deep Convolutional Networks for Large-Scale Image Recognition](https://arxiv.org/abs/1409.1556). ICLR.\n- Novikov, A., Podoprikhin, D., Osokin, A., and Vetrov, D. (2015). Tensorizing neural networks. *NeurIPS*.\n- Vaswani, A., Shazeer, N., Parmar, N., Uszkoreit, J., Jones, L., Gomez, A. N., Kaiser, Ł., and Polosukhin, I. (2017). Attention is all you need. *NeurIPS*.\n- Kossaifi, J., Panagakis, Y., Anandkumar, A., and Pantic, M. (2019). [TensorLy: tensor learning in Python](https://tensorly.org/). *JMLR* 20(26), 1–6.\n- [Lawrence of Arabia (1962) theatrical trailer](https://commons.wikimedia.org/wiki/File:Lawrence_Of_Arabia_(1962)_-_Trailer.webm) — public domain; 5 s clip in `media/`.\n- [Tensor Factorizations and Tensor Inverses](../tensor-factorizations/) — CP, Tucker, TT, t-SVD, and the four inverses.\n- [cuTENSOR](https://developer.nvidia.com/cutensor); [TensorLy-Torch](https://tensorly.org/torch/dev/).\n\n\n```{=html}\n<script src=\"widget-data/data.js\"></script>\n<script src=\"widgets.js\"></script>\n```\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}