---
title: "AI Programming Writing Blog Posts"
author: "Ravi Kalia"
date: "2025-04-01"
format: 
  html:
    toc: true
    toc-depth: 2
    code-fold: true
---

# Blog Posts with AI Tools

It feels like cheating, but is it? 

I've been using AI tools to write blog posts. My productivity has increased exponentially, but I'm not sure how much the quality has suffered. 

Here's how I did it:

1. Generate a list of blog post ideas

2. Pick one

3. Ask an LLM several probing questions about the topic

4. Flesh out some examples after some introspection

5. Ask an LLM to write and edit the blog post based on a scaffold

6. Publish the blog post

So doubtless there is some copy/paste from other sources, but I'm not sure how to attribute that. On the other hand, I'm the one prompting and forming a cohesive blog post. 



A downside is that I don't always have the time to carefully check the code snippets. I also don't always have the time to carefully proofread the blog post.  But this is a good compromise, I can always come back when I have more time. 

