{
  "hash": "fcb0cbec0a682b63a144b818a38d6815",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"What TDA Actually Builds: A Filtered Simplicial Complex, Not a Fancy Graph\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-07-23\"\ncategories: [Machine Learning, Topology, TDA, Mathematics]\nimage: \"./cover.png\"\ntags: [Persistent Homology, Simplicial Complexes, Vietoris-Rips, Ripser]\njupyter: tda-filtered-blog\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    number-sections: true\n---\n\n\n![What TDA Actually Builds: A Filtered Simplicial Complex, Not a Fancy Graph](./cover.png)\n\nTDA builds a **filtered simplicial complex** over a fixed vertex set — not a threshold graph alone. Graphs cannot distinguish a hollow cycle from a filled triangle; simplicial complexes can.\n\n::: {.callout-note collapse=\"true\"}\n## Reproducibility: environment setup\n\nThis post runs in its own virtualenv, registered as a Jupyter kernel per this blog's convention:\n\n```bash\npython3 -m venv .venv-tda-filtered\n.venv-tda-filtered/bin/pip install numpy scipy matplotlib networkx ripser persim ipykernel\n.venv-tda-filtered/bin/python -m ipykernel install --user --name tda-filtered-blog\n```\n\nQuarto discovers Jupyter kernels through the Python it runs, so if it reports `Jupyter kernel 'tda-filtered-blog' not found`, point it at the post's venv:\n\n```bash\nQUARTO_PYTHON=.venv-tda-filtered/bin/python quarto render posts/tda-filtered-simplicial-complexes/index.qmd\n```\n\nKey versions at render time are printed in the setup cell below. The random seed is fixed, so every figure and number reproduces exactly.\n:::\n\n::: {#4e5de8e4 .cell execution_count=1}\n``` {.python .cell-code code-summary=\"Setup: imports, style constants, and the drawing helper used throughout\"}\nimport itertools\n\nimport matplotlib.pyplot as plt\nimport networkx as nx\nimport numpy as np\nimport ripser\nimport scipy\nfrom IPython.display import Markdown\nfrom matplotlib.colors import LinearSegmentedColormap\nfrom scipy.spatial.distance import pdist, squareform\n\nprint(\n    f\"numpy {np.__version__} · scipy {scipy.__version__} · \"\n    f\"networkx {nx.__version__} · ripser {ripser.__version__}\"\n)\n\n# --- shared color roles (validated palette) ---------------------------------\nINK = \"#0b0b0b\"      # vertices, primary text\nMUTED = \"#898781\"    # axis labels, ticks\nGRIDC = \"#e1e0d9\"    # hairline grid\nBLUE = \"#2a78d6\"     # edges (1-simplices), H0 series\nORANGE = \"#eb6834\"   # H1 series\nVIOLET = \"#4a3aa7\"   # filled triangles (2-simplices), H2 series\nSEQ_RAMP = LinearSegmentedColormap.from_list(\n    \"blue_seq\", [\"#cde2fb\", \"#86b6ef\", \"#3987e5\", \"#1c5cab\", \"#0d366b\"]\n)\n\nplt.rcParams.update(\n    {\n        \"font.family\": \"sans-serif\",\n        \"axes.edgecolor\": MUTED,\n        \"axes.labelcolor\": MUTED,\n        \"xtick.color\": MUTED,\n        \"ytick.color\": MUTED,\n        \"axes.titlecolor\": INK,\n        \"figure.dpi\": 120,\n    }\n)\n\n\ndef style_axes(ax, keep_ticks=False):\n    \"\"\"Recessive chrome: no spines, optional ticks.\"\"\"\n    for side in (\"top\", \"right\", \"left\", \"bottom\"):\n        ax.spines[side].set_visible(False)\n    if not keep_ticks:\n        ax.set_xticks([])\n        ax.set_yticks([])\n\n\ndef draw_complex(ax, eps, show_triangles=True, node_size=210, font_size=8.5):\n    \"\"\"Draw the Vietoris-Rips complex at scale eps over the fixed points.\n\n    Filled violet patches are 2-simplices (3-cliques of the threshold\n    graph), blue segments are 1-simplices, ink dots are the fixed vertices.\n    \"\"\"\n    n = len(points)\n    dm = squareform(pdist(points))\n    n_tri = 0\n    if show_triangles:\n        for i, j, k in itertools.combinations(range(n), 3):\n            if max(dm[i, j], dm[i, k], dm[j, k]) <= eps:\n                n_tri += 1\n                ax.add_patch(\n                    plt.Polygon(\n                        points[[i, j, k]],\n                        closed=True,\n                        facecolor=VIOLET,\n                        alpha=0.20,\n                        edgecolor=\"none\",\n                        zorder=1,\n                    )\n                )\n    n_edges = 0\n    for i, j in itertools.combinations(range(n), 2):\n        if dm[i, j] <= eps:\n            n_edges += 1\n            ax.plot(\n                points[[i, j], 0], points[[i, j], 1], color=BLUE, lw=2, zorder=2\n            )\n    ax.scatter(points[:, 0], points[:, 1], s=node_size, color=INK, zorder=3)\n    for lbl, (x, y) in zip(labels, points):\n        ax.text(\n            x, y, lbl, color=\"white\", fontsize=font_size, fontweight=\"bold\",\n            ha=\"center\", va=\"center\", zorder=4,\n        )\n    ax.set_aspect(\"equal\")\n    ax.set_xlim(-1.45, 3.35)\n    ax.set_ylim(-1.45, 1.95)\n    style_axes(ax)\n    return n_edges, n_tri\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnumpy 2.5.1 · scipy 1.18.0 · networkx 3.6.1 · ripser 0.6.15\n```\n:::\n:::\n\n\n## Toy point cloud\n\n**Data provenance** (synthetic, hand-built):\n\n- Six points: unit circle at equal angles + Gaussian noise ($\\sigma = 0.08$).\n- Two points at $(2.6, 1.10)$ and $(2.9, 1.45)$: separate pair far from the ring.\n- Fixed seed (`rng = 42`); all later figures use these coordinates.\n- Stands in for cyclic dynamics plus an outlying regime (e.g. periodic signal + burst).\n- Expected phenomena: disconnected pieces at small $\\varepsilon$, a loop at intermediate $\\varepsilon$, triangles that eventually fill the loop.\n\n::: {#cell-fig-cloud .cell execution_count=2}\n``` {.python .cell-code}\nrng = np.random.default_rng(42)\n\nangles = np.linspace(0, 2 * np.pi, 6, endpoint=False)\ncircle_points = np.column_stack([np.cos(angles), np.sin(angles)])\ncircle_points += rng.normal(scale=0.08, size=circle_points.shape)\n\npair = np.array([[2.6, 1.10], [2.9, 1.45]])\n\npoints = np.vstack([circle_points, pair])\nlabels = list(\"ABCDEFGH\")\n\nfig, ax = plt.subplots(figsize=(7, 4))\ndraw_complex(ax, eps=0.0, show_triangles=False)\nax.set_title(\"The toy point cloud\", fontsize=12, fontweight=\"bold\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The running example: eight 2D points. A–F sit roughly on a circle; G and H form a tight pair off to the upper right. Nothing topological has happened yet — this is just a set of coordinates.](index_files/figure-html/fig-cloud-output-1.png){#fig-cloud}\n:::\n:::\n\n\nVertices **A–F**: would-be loop. **G–H**: satellite pair. Coordinates alone carry no topology.\n\n## Distance matrix\n\nTDA consumes the **pairwise distance matrix** $D$ with $D_{ij} = \\|x_i - x_j\\|$.\n\n- Input only; not a topological summary.\n- Example: $D_{GH} \\approx 0.46$ (closest pair).\n- Powers of $D$ do not count graph walks; shape requires an explicit scale parameter.\n\n::: {#cell-fig-distmat .cell execution_count=3}\n``` {.python .cell-code}\nD = squareform(pdist(points))\n\nfig, ax = plt.subplots(figsize=(6.4, 5.4))\nim = ax.imshow(D, cmap=SEQ_RAMP)\nax.set_xticks(range(8), labels)\nax.set_yticks(range(8), labels)\nax.tick_params(length=0)\nfor side in (\"top\", \"right\", \"left\", \"bottom\"):\n    ax.spines[side].set_visible(False)\nmid = D.max() / 2\nfor i in range(8):\n    for j in range(8):\n        ax.text(\n            j, i, f\"{D[i, j]:.2f}\",\n            ha=\"center\", va=\"center\", fontsize=7.5,\n            color=\"white\" if D[i, j] > mid else INK,\n        )\ncbar = fig.colorbar(im, ax=ax, shrink=0.85)\ncbar.set_label(\"Euclidean distance\", color=MUTED)\ncbar.outline.set_visible(False)\nax.set_title(\"Pairwise distance matrix\", fontsize=12, fontweight=\"bold\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The 8×8 Euclidean distance matrix, annotated to two decimals. Darker blue = farther apart. The matrix is symmetric with a zero diagonal. It records pairwise distances only — which pairs are close — and says nothing *by itself* about components, loops, or voids.](index_files/figure-html/fig-distmat-output-1.png){#fig-distmat}\n:::\n:::\n\n\n## Threshold graphs\n\nAt scale $\\varepsilon \\geq 0$, graph $G_\\varepsilon$:\n\n- **Vertices**: fixed set A–H at every scale.\n- **Edges**: $(i,j)$ whenever $D_{ij} \\leq \\varepsilon$.\n\nNested family:\n\n$$\nG_{\\varepsilon_1} \\subseteq G_{\\varepsilon_2} \\subseteq G_{\\varepsilon_3} \\subseteq \\cdots\n\\qquad \\text{whenever } \\varepsilon_1 \\leq \\varepsilon_2 \\leq \\varepsilon_3 \\leq \\cdots\n$$\n\nEdges only accumulate; vertices never change.\n\n::: {#cell-fig-threshold .cell execution_count=4}\n``` {.python .cell-code}\nthreshold_eps = [0.6, 0.9, 1.25, 1.9]\n\nfig, axes = plt.subplots(1, 4, figsize=(13, 3.4))\nfor ax, eps in zip(axes, threshold_eps):\n    n_edges, _ = draw_complex(ax, eps, show_triangles=False, node_size=130, font_size=7)\n    G = nx.Graph()\n    G.add_nodes_from(labels)\n    G.add_edges_from(\n        (labels[i], labels[j])\n        for i, j in itertools.combinations(range(8), 2)\n        if D[i, j] <= eps\n    )\n    n_comp = nx.number_connected_components(G)\n    edge_word = \"edge\" if n_edges == 1 else \"edges\"\n    ax.set_title(\n        f\"$\\\\varepsilon$ = {eps}\\n{n_edges} {edge_word} · {n_comp} components\",\n        fontsize=10,\n    )\nfig.suptitle(\n    \"One fixed vertex set, a growing edge set\", fontsize=12, fontweight=\"bold\", y=1.06\n)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Threshold graphs at four scales, drawn over the identical fixed coordinates. ε = 0.6: only the closest pair (G–H, distance 0.46) is joined — seven components. ε = 0.9: A–F and C–D have joined in — five components. ε = 1.25: the six circle points close into a ring, leaving two components. ε = 1.9: many long edges have appeared; the pair still hangs on as its own component until ε ≈ 1.97. Every panel's edge set contains the previous panel's.](index_files/figure-html/fig-threshold-output-1.png){#fig-threshold}\n:::\n:::\n\n\nComponent counts at this stage match single-linkage clustering. Loops and voids require higher-dimensional simplices.\n\n## Filled vs hollow cycles\n\nAt $\\varepsilon = 1.75$, points C, D, E are pairwise within range. Two distinct objects:\n\n- **Boundary**: three edges C–D–E–C → 1-cycle that may enclose a hole.\n- **Filled 2-simplex** $\\{C,D,E\\}$ → certifies the cycle bounds a patch; hole killed.\n\n::: {#cell-fig-triangle .cell execution_count=5}\n``` {.python .cell-code}\nsub = [labels.index(c) for c in \"CDE\"]\ntri = points[sub]\n\nfig, axes = plt.subplots(1, 2, figsize=(9, 3.8))\nfor ax, filled in zip(axes, [False, True]):\n    if filled:\n        ax.add_patch(\n            plt.Polygon(tri, closed=True, facecolor=VIOLET, alpha=0.25,\n                        edgecolor=\"none\", zorder=1)\n        )\n    for i, j in itertools.combinations(range(3), 2):\n        ax.plot(tri[[i, j], 0], tri[[i, j], 1], color=BLUE, lw=2.2, zorder=2)\n    ax.scatter(tri[:, 0], tri[:, 1], s=260, color=INK, zorder=3)\n    for lbl, (x, y) in zip(\"CDE\", tri):\n        ax.text(x, y, lbl, color=\"white\", fontsize=10, fontweight=\"bold\",\n                ha=\"center\", va=\"center\", zorder=4)\n    ax.set_aspect(\"equal\")\n    ax.set_xlim(-1.35, 0.05)\n    ax.set_ylim(-1.25, 1.15)\n    style_axes(ax)\naxes[0].set_title(\"Boundary only: three 1-simplices\\n(a cycle with a hole)\", fontsize=10)\naxes[1].set_title(\"Filled 2-simplex {C, D, E}\\n(one 3-way object; hole destroyed)\", fontsize=10)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Left: the triangle *boundary* — three edges C–D, D–E, C–E, each a relationship between exactly two points. This is a 1-dimensional cycle: you can walk around it, and it encloses a hole. Right: the *filled* 2-simplex {C, D, E} — a single three-way relationship, drawn as a violet membrane. The filled triangle is a different object, not a styling of the edges: its presence declares that the cycle around it bounds nothing, killing the hole.](index_files/figure-html/fig-triangle-output-1.png){#fig-triangle}\n:::\n:::\n\n\nAn edge is a two-way relation. A 2-simplex is one three-way relation. Graph decorations cannot express fill status.\n\n## Simplicial complexes\n\n**Simplex**: finite vertex set; dimension = $|S| - 1$.\n\n- $\\{v\\}$: 0-simplex (vertex).\n- $\\{u,v\\}$: 1-simplex (edge).\n- $\\{u,v,w\\}$: 2-simplex (filled triangle).\n- $(k{+}1)$ vertices: $k$-simplex.\n\n**Abstract simplicial complex**: collection of simplices **closed under faces** — every face of an included simplex is included.\n\nClosure example: if $\\{C,D,E\\}$ is present, then $\\{C,D\\}, \\{D,E\\}, \\{C,E\\}, \\{C\\}, \\{D\\}, \\{E\\}$ must be present. A generic hypergraph need not satisfy this.\n\nLeft panel above: complex without $\\{C,D,E\\}$. Right panel: same skeleton plus $\\{C,D,E\\}$.\n\n## Vietoris-Rips construction\n\n**Vietoris–Rips complex** $\\mathrm{VR}_\\varepsilon$: one simplex per **clique** of the threshold graph — equivalently, every subset whose pairwise distances are $\\leq \\varepsilon$.\n\n$$\n\\{x_{i_0}, \\ldots, x_{i_k}\\} \\in \\mathrm{VR}_\\varepsilon\n\\iff\nD_{i_p i_q} \\leq \\varepsilon \\ \\text{ for every pair } p, q .\n$$\n\nFace closure is automatic (every subset of a clique is a clique).\n\n::: {#cell-fig-rips .cell execution_count=6}\n``` {.python .cell-code}\nrips_eps = [0.9, 1.25, 1.75, 1.9]\n\nfig, axes = plt.subplots(2, 2, figsize=(11, 7))\nfor ax, eps in zip(axes.flat, rips_eps):\n    n_edges, n_tri = draw_complex(ax, eps, node_size=150, font_size=7.5)\n    ax.set_title(\n        f\"$\\\\varepsilon$ = {eps} · {n_edges} edges · {n_tri} filled triangles\",\n        fontsize=10,\n    )\nfig.suptitle(\n    \"Vietoris–Rips complexes: every clique becomes a simplex\",\n    fontsize=12, fontweight=\"bold\",\n)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Vietoris–Rips complexes at four scales. Ink dots are 0-simplices (always all eight), blue segments 1-simplices, violet patches filled 2-simplices; where patches overlap the violet deepens. ε = 0.9: a few edges, no triangles. ε = 1.25: the ring closes — a genuine 1-dimensional loop, with no triangles yet to dispute it. ε = 1.75: four triangles have filled in and the loop has shrunk to the still-unfilled middle. ε = 1.9: enough triangles overlap that the central cycle is entirely filled — the loop is dead.](index_files/figure-html/fig-rips-output-1.png){#fig-rips}\n:::\n:::\n\n\nSimplex counts by dimension (including 3-simplices not drawable in 2D):\n\n::: {#13866ad8 .cell execution_count=7}\n``` {.python .cell-code code-summary=\"Count simplices by dimension at each scale (cliques of the threshold graph)\"}\ndef simplex_counts(eps, max_size=4):\n    counts = {}\n    for size in range(1, max_size + 1):\n        counts[size - 1] = sum(\n            1\n            for combo in itertools.combinations(range(8), size)\n            if all(D[i, j] <= eps for i, j in itertools.combinations(combo, 2))\n        )\n    return counts\n\nrows = [\"| $\\\\varepsilon$ | 0-simplices | 1-simplices | 2-simplices | 3-simplices |\",\n        \"|---|---|---|---|---|\"]\nfor eps in [0.9, 1.25, 1.75, 1.9, 2.0]:\n    c = simplex_counts(eps)\n    rows.append(f\"| {eps} | {c[0]} | {c[1]} | {c[2]} | {c[3]} |\")\nMarkdown(\"\\n\".join(rows))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=7}\n| $\\varepsilon$ | 0-simplices | 1-simplices | 2-simplices | 3-simplices |\n|---|---|---|---|---|\n| 0.9 | 8 | 3 | 0 | 0 |\n| 1.25 | 8 | 7 | 0 | 0 |\n| 1.75 | 8 | 11 | 4 | 0 |\n| 1.9 | 8 | 13 | 8 | 0 |\n| 2.0 | 8 | 15 | 12 | 4 |\n:::\n:::\n\n\nAt $\\varepsilon = 2.0$, four 3-simplices appear when edge C–F ($\\approx 1.99$) completes four tetrahedra. The Rips complex is **abstract** — built from $D$ only, with no embedding dimension.\n\n**Čech complex** (alternative): simplex when $\\varepsilon/2$-balls share a common point; stricter, better guarantees, higher cost. This post uses Rips (standard in fast libraries).\n\n## Filtration and persistence\n\nNested Rips complexes:\n\n$$\n\\mathrm{VR}_{\\varepsilon_1} \\subseteq \\mathrm{VR}_{\\varepsilon_2} \\subseteq \\cdots\n$$\n\nEach simplex enters at its **diameter** (longest pairwise edge length).\n\nDistinction:\n\n- **Filtration**: which simplices exist at each $\\varepsilon$ (combinatorial bookkeeping).\n- **Persistent homology**: which components, loops, voids exist at each scale, and their birth/death scales (requires homology across the filtration).\n\nIn dimension $k$: **$k$-cycles** minus **boundaries** of $(k{+}1)$-simplices → **Betti number** $\\beta_k$.\n\n$$\n\\beta_k = \\dim\\ker\\partial_k - \\operatorname{rank}\\partial_{k+1}.\n$$\n\nPersistent homology tracks each feature from birth scale to death scale across the full filtration.\n\n## Ripser output\n\n`ripser` computes Rips persistence from the point cloud. Conventions:\n\n- Simplex enters when diameter $\\leq \\varepsilon$.\n- Filtration values match Euclidean distances in the figures.\n- One $H_0$ component has death $= \\infty$ once everything connects.\n\n::: {#cdb946e2 .cell execution_count=8}\n``` {.python .cell-code code-summary=\"Compute persistent homology with ripser (dimensions 0, 1, 2)\"}\nres = ripser.ripser(points, maxdim=2)\ndgms = res[\"dgms\"]\nfor k, dgm in enumerate(dgms):\n    print(f\"H{k} intervals (birth, death):\")\n    for b, d in dgm:\n        print(f\"  ({b:.3f}, {'∞' if np.isinf(d) else f'{d:.3f}'})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nH0 intervals (birth, death):\n  (0.000, 0.461)\n  (0.000, 0.852)\n  (0.000, 0.855)\n  (0.000, 1.032)\n  (0.000, 1.080)\n  (0.000, 1.125)\n  (0.000, 1.970)\n  (0.000, ∞)\nH1 intervals (birth, death):\n  (1.229, 1.827)\nH2 intervals (birth, death):\n  (1.881, 1.989)\n```\n:::\n:::\n\n\n### Persistence diagram\n\nEach feature → point (birth $\\varepsilon$, death $\\varepsilon$). Distance above the diagonal = lifetime.\n\n::: {#cell-fig-diagram .cell execution_count=9}\n``` {.python .cell-code}\nfinite_max = max(d for dgm in dgms for _, d in dgm if np.isfinite(d))\nlim = finite_max * 1.12\ninf_y = lim * 1.06\n\nfig, ax = plt.subplots(figsize=(6.2, 6.2))\nax.set_facecolor(\"none\")\nax.plot([0, lim], [0, lim], color=GRIDC, lw=1.2, zorder=1)\nax.axhline(inf_y, color=MUTED, lw=1, ls=(0, (4, 4)), zorder=1)\nax.text(0.12, inf_y, \"∞ \", ha=\"right\", va=\"center\", color=MUTED, fontsize=11)\n\nseries = [(\"$H_0$ components\", BLUE, \"o\"),\n          (\"$H_1$ loops\", ORANGE, \"s\"),\n          (\"$H_2$ voids\", VIOLET, \"^\")]\nfor dgm, (name, color, marker) in zip(dgms, series):\n    births = dgm[:, 0]\n    deaths = np.where(np.isinf(dgm[:, 1]), inf_y, dgm[:, 1])\n    ax.scatter(births, deaths, s=70, color=color, marker=marker, label=name,\n               zorder=3, edgecolors=\"white\", linewidths=1.2)\n\nax.annotate(\"the ring A–F\\n(1.23, 1.83)\", xy=(1.23, 1.83), xytext=(0.35, 1.62),\n            fontsize=9, color=INK,\n            arrowprops=dict(arrowstyle=\"-\", color=MUTED, lw=1))\nax.annotate(\"G–H pair joins\\nthe rest (1.97)\", xy=(0.0, 1.97), xytext=(0.42, 2.06),\n            fontsize=9, color=INK,\n            arrowprops=dict(arrowstyle=\"-\", color=MUTED, lw=1))\nax.set_xlim(-0.08, lim)\nax.set_ylim(-0.08, inf_y * 1.05)\nax.set_xlabel(\"birth scale $\\\\varepsilon$\")\nax.set_ylabel(\"death scale $\\\\varepsilon$\")\nax.set_aspect(\"equal\")\nfor side in (\"top\", \"right\"):\n    ax.spines[side].set_visible(False)\nax.grid(color=GRIDC, lw=0.6)\nax.set_axisbelow(True)\nax.legend(frameon=False, loc=\"lower right\", labelcolor=INK)\nax.set_title(\"Persistence diagram\", fontsize=12, fontweight=\"bold\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Persistence diagram for the toy cloud. Both axes are the scale parameter ε — there is no time axis. Blue circles (H₀): component mergers, including the long-lived bar for the G–H pair dying at ε ≈ 1.97, and one immortal component plotted on the dashed ∞ line. The orange square (H₁) is the ring A–F: born 1.23, dead 1.83 — far off the diagonal, hence a real feature. The violet triangle (H₂) is a fleeting abstract void, born 1.88 and filled at 1.99 by the tetrahedron {C,D,E,F} — close to the diagonal, hence more curiosity than signal.](index_files/figure-html/fig-diagram-output-1.png){#fig-diagram}\n:::\n:::\n\n\n### Persistence barcode\n\nSame intervals as horizontal bars over $\\varepsilon$.\n\n::: {#cell-fig-barcode .cell execution_count=10}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(8.5, 4.6))\ny = 0\nyticks, ylabels = [], []\ngroup_gap = 1.6\nfor dgm, (name, color, _) in zip(dgms, series):\n    order = np.argsort(dgm[:, 0] + np.where(np.isinf(dgm[:, 1]), 1e9, dgm[:, 1]))\n    group_top = y\n    for b, d in dgm[order][::-1]:\n        if np.isinf(d):\n            ax.plot([b, lim * 1.02], [y, y], color=color, lw=3.5,\n                    solid_capstyle=\"round\")\n            ax.annotate(\"\", xy=(lim * 1.08, y), xytext=(lim * 1.02, y),\n                        arrowprops=dict(arrowstyle=\"->\", color=color, lw=1.6))\n        else:\n            ax.plot([b, d], [y, y], color=color, lw=3.5, solid_capstyle=\"round\")\n        y += 1\n    yticks.append((group_top + y - 1) / 2)\n    ylabels.append(name)\n    y += group_gap\nax.set_yticks(yticks, ylabels, fontsize=11, color=INK)\nax.tick_params(axis=\"y\", length=0)\nax.set_xlim(-0.05, lim * 1.12)\nax.set_xlabel(\"scale $\\\\varepsilon$\")\nfor side in (\"top\", \"right\", \"left\"):\n    ax.spines[side].set_visible(False)\nax.grid(axis=\"x\", color=GRIDC, lw=0.6)\nax.set_axisbelow(True)\nax.set_title(\"Persistence barcode\", fontsize=12, fontweight=\"bold\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Persistence barcode — the same intervals as the diagram, drawn as bars over the ε-axis. Reading H₀ top-down: the shortest bar ends at 0.46 (G and H merge), the next at 0.85 twice (A–F and C–D join the circle group), then 1.03, 1.08, 1.12 as the circle assembles, one long bar to 1.97 (the pair holding out), and one bar running off to infinity (the final single component). The lone H₁ bar spans [1.23, 1.83] — the ring. The sliver H₂ bar spans [1.88, 1.99].](index_files/figure-html/fig-barcode-output-1.png){#fig-barcode}\n:::\n:::\n\n\n### Feature reading\n\n- **$H_1$ ring**: interval $[1.23, 1.83]$; persistence $0.60$; loop born when B–C closes A–F, dies when interior fills.\n- **$H_0$ merges**: seven finite bars; death scales match edge lengths (0.46 G–H, 0.85, 0.85, 1.03, 1.08, 1.12, 1.97 A–G).\n- **$H_2$ void**: $[1.88, 1.99]$; abstract enclosed void filled by tetrahedra at C–F arrival; short lifetime ≈ noise.\n\n### Betti numbers at fixed scales\n\n$\\beta_k(\\varepsilon)$ = count of bars with $b \\leq \\varepsilon < d$.\n\n::: {#be89ba38 .cell execution_count=11}\n``` {.python .cell-code code-summary=\"Betti numbers at selected scales, from the intervals, cross-checked against networkx\"}\ndef betti(eps, dgm):\n    return int(np.sum((dgm[:, 0] <= eps) & (eps < dgm[:, 1])))\n\nrows = [\"| $\\\\varepsilon$ | $\\\\beta_0$ (components) | $\\\\beta_1$ (loops) | $\\\\beta_2$ (voids) | graph components (networkx) |\",\n        \"|---|---|---|---|---|\"]\nfor eps in [0.6, 0.9, 1.25, 1.75, 1.9, 2.0]:\n    G = nx.Graph()\n    G.add_nodes_from(range(8))\n    G.add_edges_from(\n        (i, j) for i, j in itertools.combinations(range(8), 2) if D[i, j] <= eps\n    )\n    nx_comp = nx.number_connected_components(G)\n    b0, b1, b2 = (betti(eps, dgm) for dgm in dgms)\n    assert b0 == nx_comp, \"β₀ must equal the number of graph components\"\n    rows.append(f\"| {eps} | {b0} | {b1} | {b2} | {nx_comp} |\")\nMarkdown(\"\\n\".join(rows))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=11}\n| $\\varepsilon$ | $\\beta_0$ (components) | $\\beta_1$ (loops) | $\\beta_2$ (voids) | graph components (networkx) |\n|---|---|---|---|---|\n| 0.6 | 7 | 0 | 0 | 7 |\n| 0.9 | 5 | 0 | 0 | 5 |\n| 1.25 | 2 | 1 | 0 | 2 |\n| 1.75 | 2 | 1 | 0 | 2 |\n| 1.9 | 2 | 0 | 1 | 2 |\n| 2.0 | 1 | 0 | 0 | 1 |\n:::\n:::\n\n\nAt $\\varepsilon = 1.25$: $(\\beta_0, \\beta_1, \\beta_2) = (2, 1, 0)$. Betti counts at two scales do not identify whether the same loop persists; the single $H_1$ bar $[1.23, 1.83]$ does.\n\n## Glossary\n\nTerms tied to the eight-point example:\n\n- **Point cloud**: finite coordinates or distance matrix (A–H).\n- **Distance matrix**: $D_{GH} \\approx 0.46$; topology-free input.\n- **Simplex**: $\\{G\\}$, $\\{G,H\\}$, $\\{C,D,E\\}$, $\\{C,D,E,F\\}$, etc.\n- **Simplicial complex**: simplices closed under faces.\n- **Closure property**: triangle implies its edges and vertices.\n- **Vietoris–Rips complex**: cliques of threshold graph = simplices.\n- **Filtration**: $\\mathrm{VR}_{\\varepsilon_1} \\subseteq \\mathrm{VR}_{\\varepsilon_2} \\subseteq \\cdots$.\n- **Betti numbers**: $\\beta_0$ components, $\\beta_1$ loops, $\\beta_2$ voids.\n- **Persistence diagram**: (birth, death) per feature; ring at $(1.23, 1.83)$.\n- **Persistence barcode**: same intervals as bars over $\\varepsilon$.\n- **Persistence landscape**: diagram → real-valued functions for ML pipelines.\n- **Bottleneck distance**: max single-point matching distance between diagrams.\n- **Wasserstein distance**: sum of matching distances between diagrams.\n\n## Common misconceptions\n\n- **\"TDA is a weighted multigraph.\"** Edges have two endpoints; cannot encode filled $\\{C,D,E\\}$ or fill status of cycles.\n- **\"Powers of $D$ reveal topology.\"** Only a filtration + homology over nested complexes does.\n- **\"Persistence diagram has a time axis.\"** Both axes are scale $\\varepsilon$.\n- **\"Long graph cycle ⇒ persistent loop.\"** $\\beta_1 = 0$ at $\\varepsilon = 1.9$ despite many graph cycles — higher simplices fill them.\n\n## References\n\n- [Topological Data Analysis: Finding Clusters, Loops, and Voids Across Scales](../topological-data-analysis-clustering/index.qmd) — hand homology computation and persistence as ML features.\n- [Two Ways to Expand the Space: Persistent Homology and Kernel SVMs](../tda-vs-svm-expanding-the-space/index.qmd) — contrast with kernel methods.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}