{
  "hash": "529a48784c72302ccd5e146f6ca7d514",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Probabilistic PCA\"\nsubtitle: \"A Gaussian model recovers the principal subspace, then changes what reconstruction means.\"\ndescription: \"Derive the PPCA covariance fit and latent posterior, then compare its shrunk reconstruction with classical PCA on a reproducible sensor example.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-09-13\"\ncategories: [Linear Algebra, Machine Learning, Statistics]\nimage: \"./cover.png\"\ntags: [PCA, probabilistic PCA, latent variables, Gaussian models, dimensionality reduction]\njupyter: ppca-blog\nformat:\n  html:\n    toc: true\n    number-sections: true\n    code-fold: true\n    fig-dpi: 150\nexecute:\n  warning: false\n---\n\n\n\n\n![Probabilistic PCA](./cover.png){fig-alt=\"A two-sensor cloud with classical PCA and PPCA reconstructions, beside an example of a posterior distribution for an unobserved coordinate.\"}\n\nProbabilistic PCA estimates a noisy low-dimensional signal with a Gaussian model: its maximum-likelihood fit recovers PCA's principal subspace, while its posterior reconstruction shrinks toward the mean.\n\nA classical PCA projection gives us coordinates and a reconstruction error. If we also want uncertainty about the unobserved signal, we need assumptions about how the measurements were generated; that is the role of the probability model.\n\n[Six Views of PCA](../six-views-of-pca/) derives the geometric optimization. We use that subspace result here and distinguish three objects: the fitted distribution of observations, the posterior latent coordinates, and the reconstructed signal.\n\n## Gaussian latent-variable model\n\nSuppose a few unobserved quantities influence many measurements. Write one observation as\n\n$$\nx=\\mu+Wz+\\varepsilon,\\qquad\nz\\sim N(0,I_k),\\qquad\n\\varepsilon\\sim N(0,\\sigma^2 I_d),\n\\qquad z\\perp\\varepsilon.\n$$\n\n- $x\\in\\mathbb R^d$ contains observed features; $z\\in\\mathbb R^k$ contains latent, or unobserved, coordinates, with $k<d$.\n- $W\\in\\mathbb R^{d\\times k}$ maps latent coordinates to features. Its columns need not be orthonormal.\n- $\\mu$ is the observation mean. We assume independent observations with common parameters.\n- $\\sigma^2>0$ is the noise variance in every feature direction. This equal-variance assumption is called **isotropic noise**; it refers to the chosen measurement coordinates.\n\nIndependent Gaussian contributions add their covariances, giving\n\n$$\nx\\sim N(\\mu,C),\\qquad C=WW^\\top+\\sigma^2I_d.\n$$\n\nThe signal covariance $WW^\\top$ has rank at most $k$. Noise adds variance in all $d$ directions, so the observation distribution has full rank even though its signal lies in a smaller subspace.\n\nThis is the PPCA model introduced by [Tipping and Bishop (1999)](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/bishop-ppca-jrss.pdf). Fixing the latent covariance to $I_k$ leaves a rotation ambiguity: $W$ and $WR$ describe the same observation distribution whenever $R^\\top R=I_k$.\n\n## Maximum-likelihood fit\n\n### Covariance convention\n\nFor $n$ complete observations, the fitted mean is $\\hat\\mu=\\bar x$. Let $X$ contain the centred observations as rows, and define\n\n$$\nS_{\\mathrm{ML}}=\\frac1nX^\\top X\n=V\\operatorname{diag}(\\lambda_1,\\ldots,\\lambda_d)V^\\top,\n\\qquad \\lambda_1\\ge\\cdots\\ge\\lambda_d.\n$$\n\nThe denominator is $n$, as required by this Gaussian likelihood. Eigenvalues computed using $n-1$ must be multiplied by $(n-1)/n$ before using the PPCA formulas; the eigenvectors are unchanged.\n\nApart from a constant, the log likelihood is\n\n$$\n\\ell(W,\\sigma^2)\n=-\\frac n2\\left[\\log\\det C+\n\\operatorname{tr}(C^{-1}S_{\\mathrm{ML}})\\right].\n$$\n\nThe determinant term penalizes an excessively diffuse distribution. The trace term penalizes observed variation that the model assigns too little variance to.\n\n### Principal subspace and residual variance\n\nAt the maximum, the model aligns its signal subspace with the leading sample eigenvectors. Let $c_j$ denote its covariance eigenvalues: the first $k$ can exceed $\\sigma^2$, while the remaining $d-k$ all equal $\\sigma^2$.\n\nWith that alignment, minimizing the negative likelihood reduces to\n\n$$\n\\sum_{j=1}^k\\left(\\log c_j+\\frac{\\lambda_j}{c_j}\\right)\n +(d-k)\\log\\sigma^2+\n \\frac{\\sum_{j=k+1}^d\\lambda_j}{\\sigma^2}.\n$$\n\nDifferentiating gives $c_j=\\lambda_j$ for retained directions and an average for the discarded directions. Thus\n\n$$\n\\hat\\sigma^2=\\frac{1}{d-k}\\sum_{j=k+1}^{d}\\lambda_j,\n\\qquad\n\\hat W=V_k(\\Lambda_k-\\hat\\sigma^2I_k)^{1/2}R.\n$$\n\nHere $\\Lambda_k=\\operatorname{diag}(\\lambda_1,\\ldots,\\lambda_k)$ and $R$ is any orthogonal $k\\times k$ matrix. The construction matches retained covariance eigenvalues and replaces discarded ones with their average.\n\n- If $\\lambda_k>\\hat\\sigma^2>0$, the columns of $\\hat W$ span the classical principal subspace. The scales of those columns differ from unit PCA axes.\n- If $\\lambda_k=\\hat\\sigma^2$, the corresponding loading vanishes, so the effective signal dimension is smaller than the requested $k$.\n- If the discarded variance is zero, the solution lies at a singular zero-noise boundary; it is not a nonsingular Gaussian density.\n\nThe leading-subspace result follows from the likelihood optimization in Tipping and Bishop. It is agreement between optimizers under a model, not an identity between the likelihood and PCA's reconstruction error for every $W$.\n\n## Posterior coordinates and reconstruction\n\n### Conditional distribution\n\nFor a new measurement, we infer $z$ with fitted parameters held fixed. Let $M=W^\\top W+\\sigma^2I_k$; completing the square in the Gaussian density gives\n\n$$\nz\\mid x\\sim N(m_z,\\Sigma_z),\\qquad\nm_z=M^{-1}W^\\top(x-\\mu),\\qquad\n\\Sigma_z=\\sigma^2M^{-1}.\n$$\n\nThe posterior expresses uncertainty about this observation's latent coordinates. It does not include uncertainty in the fitted parameters $W$, $\\mu$, or $\\sigma^2$.\n\nChoose $R=I_k$ to compare directly with classical scores $a_j=v_j^\\top(x-\\mu)$. At the maximum-likelihood fit,\n\n$$\n(m_z)_j=\\frac{\\sqrt{\\lambda_j-\\hat\\sigma^2}}{\\lambda_j}a_j,\n\\qquad\n(\\Sigma_z)_{jj}=\\frac{\\hat\\sigma^2}{\\lambda_j}.\n$$\n\nLatent coordinates use the model's unit-variance prior scale. They are not the ordinary PCA scores $a_j$.\n\n### Signal reconstruction\n\nThe posterior mean of the noise-free signal $s=\\mu+Wz$ is\n\n$$\n\\mathbb E[s\\mid x]\n=\\mu+Wm_z\n=\\mu+V_k\\operatorname{diag}\\!\\left(1-\\frac{\\hat\\sigma^2}{\\lambda_j}\\right)\n V_k^\\top(x-\\mu).\n$$\n\nClassical PCA retains $a_j$ unchanged in the selected subspace. PPCA multiplies it by $1-\\hat\\sigma^2/\\lambda_j$: when a retained direction has little variance beyond the fitted noise, the model attributes less of an extreme measurement to signal.\n\nFor a fixed principal subspace with positive retained eigenvalues, the reconstruction approaches the classical orthogonal projection as $\\sigma^2\\to0$. The latent mean instead approaches $\\Lambda_k^{-1/2}V_k^\\top(x-\\mu)$, up to the latent rotation; its rescaling does not disappear.\n\n### Worked calculation\n\nConsider a centred sample with eigenvalues $(9,4,1)$ under the $1/n$ convention and axes equal to the coordinate axes. This is an illustrative covariance, chosen to make the residual average explicit, not an empirical dataset.\n\nFor $k=1$, we obtain $\\hat\\sigma^2=(4+1)/2=2.5$ and $\\hat W=(\\sqrt{6.5},0,0)^\\top$. For an observation $x=(3,1,0)^\\top$, compare the three outputs:\n\n| Object | Value |\n|---|---|\n| Classical PCA score | $a_1=3$ |\n| Posterior latent mean | $m_z=3\\sqrt{6.5}/9\\approx0.850$ |\n| Classical reconstruction | $(3,0,0)^\\top$ |\n| Posterior signal mean | $(13/6,0,0)^\\top\\approx(2.167,0,0)^\\top$ |\n| Posterior latent variance | $2.5/9\\approx0.278$ |\n\nBoth reconstructions lie on the first coordinate axis. The posterior signal estimate is closer to the mean, while its latent coordinate is expressed on a different scale.\n\n## Reproducible sensor example\n\n### Data and fit\n\nWe generate 500 synthetic paired sensor readings from $z\\sim N(0,1)$, $W=(2.2,0.9)^\\top$, $\\mu=(1,-1)^\\top$, and independent sensor noise with standard deviation $0.8$. The example represents two calibrated sensors responding to one shared quantity with equal noise variance.\n\nThere is no external collector: the code generates both the signal and the noise. We ask whether the fitted model recovers the shared direction and changes reconstruction as derived; a real application would need to check the equal-noise assumption before trusting its uncertainty estimates.\n\n\n\n::: {#ppca-fit .cell execution_count=2}\n``` {.python .cell-code code-fold=\"false\"}\nrng = np.random.default_rng(19)\nn, d, k = 500, 2, 1\nW_true = np.array([[2.2], [0.9]])\nmu_true = np.array([1.0, -1.0])\nz_true = rng.normal(size=(n, k))\nobservations = mu_true + z_true @ W_true.T + rng.normal(scale=0.8, size=(n, d))\nmu = observations.mean(axis=0)\nX = observations - mu\n_, singular, Vt = np.linalg.svd(X, full_matrices=False)\neigenvalues = singular**2 / n\nV = Vt[:k].T\n# Fix a plotting convention without consulting labels or the true latent z.\nV *= np.where(V[np.argmax(abs(V), axis=0), np.arange(k)] < 0, -1, 1)\nnoise = eigenvalues[k:].mean()\nW = V * np.sqrt(eigenvalues[:k] - noise)\ncovariance = W @ W.T + noise * np.eye(d)\nprint(\"sample covariance eigenvalues:\", eigenvalues)\nprint(f\"fitted noise variance: {noise:.4f}; generating value: {0.8**2:.4f}\")\nalignment = abs(float(V[:, 0] @ W_true[:, 0])) / np.linalg.norm(W_true)\nprint(f\"absolute cosine with generating direction: {alignment:.4f}\")\nassert np.allclose(np.linalg.eigvalsh(covariance)[::-1], eigenvalues)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsample covariance eigenvalues: [6.0691 0.6283]\nfitted noise variance: 0.6283; generating value: 0.6400\nabsolute cosine with generating direction: 1.0000\n```\n:::\n:::\n\n\nThe fitted noise variance is 0.6283, compared with the generating value 0.6400. With $d=2$ and $k=1$, only one eigenvalue is discarded, so this PPCA model can reproduce both eigenvalues of any positive-definite sample covariance.\n\nCovariance agreement here checks the implementation; it is not a goodness-of-fit test for Gaussianity or a proof about the true sensor noise.\n\n### Reconstruction check\n\nWe compute both estimates for every observation and check the shrinkage equation. A fixed probe, three units along the fitted first axis and one unit perpendicular to it, makes the two reconstructions easy to distinguish in the figure.\n\n::: {#ppca-posterior .cell execution_count=3}\n``` {.python .cell-code}\nM = W.T @ W + noise * np.eye(k)\nlatent_mean = np.linalg.solve(M, W.T @ X.T).T\nlatent_cov = noise * np.linalg.solve(M, np.eye(k))\nclassic = X @ V @ V.T\nsignal_mean = latent_mean @ W.T\nshrink = 1 - noise / eigenvalues[:k]\nassert np.allclose(signal_mean, (X @ V * shrink) @ V.T)\nassert np.allclose(latent_cov.diagonal(), noise / eigenvalues[:k])\nassert np.sum((X - classic)**2) <= np.sum((X - signal_mean)**2)\n\n# Verify the hand calculation independently of the simulated fit.\nhand_noise = np.mean([4.0, 1.0])\nhand_W = np.sqrt(9.0 - hand_noise)\nhand_mean = hand_W * 3.0 / 9.0\nassert np.isclose(hand_mean * hand_W, 13 / 6)\nassert np.isclose(hand_noise / 9.0, 5 / 18)\nprint(f\"hand example: latent mean {hand_mean:.4f}; signal coordinate {hand_mean * hand_W:.4f}\")\nprint(f\"sensor fit: reconstruction multiplier {shrink[0]:.4f}\")\nprint(f\"posterior latent standard deviation: {np.sqrt(latent_cov[0, 0]):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nhand example: latent mean 0.8498; signal coordinate 2.1667\nsensor fit: reconstruction multiplier 0.8965\nposterior latent standard deviation: 0.3218\n```\n:::\n:::\n\n\nThe fitted reconstruction multiplier is 0.8965: the posterior signal mean retains about 90% of the classical score along this axis. Classical PCA has the smaller squared error against the observed measurements, the quantity it optimizes.\n\nPPCA's posterior mean estimates the unobserved signal under the fitted model; better fit to the noisy observations is not its criterion.\n\n::: {#cell-fig-ppca .cell fig-height='3.8' fig-width='9' execution_count=4}\n``` {.python .cell-code}\nv = V[:, 0]\nperpendicular = np.array([-v[1], v[0]])\nprobe = 3 * v + perpendicular\nprobe_classic = 3 * v\nprobe_latent = np.linalg.solve(M, W.T @ probe)\nprobe_signal = W @ probe_latent\nfig, (ax, density_ax) = plt.subplots(1, 2, figsize=(9, 3.8))\nax.scatter(X[:, 0], X[:, 1], s=9, alpha=0.25, color=INK)\nspan = np.array([-5.5, 5.5])\nax.plot(span * v[0], span * v[1], color=PURPLE, lw=1, label=\"principal axis\")\nax.plot([probe[0], probe_classic[0]], [probe[1], probe_classic[1]],\n        color=INK, ls=\":\", lw=1)\nax.scatter(*probe, color=INK, marker=\"x\", s=55, label=\"probe\")\nax.scatter(*probe_classic, facecolors=\"none\", edgecolors=TEAL,\n           s=95, linewidths=2, label=\"classical projection\", zorder=4)\nax.scatter(*probe_signal, color=ORANGE, marker=\"D\", s=35,\n           label=\"posterior signal mean\", zorder=5)\nax.scatter(0, 0, color=INK, marker=\"+\", s=55)\nax.set(xlabel=\"sensor 1, centred\", ylabel=\"sensor 2, centred\", title=\"Same axis, different reconstruction\")\nax.set_aspect(\"equal\")\nax.legend(frameon=True, fontsize=7, loc=\"upper left\")\ngrid = np.linspace(-3.5, 3.5, 500)\nsd = np.sqrt(latent_cov[0, 0])\nnormal = lambda t, mean, scale: np.exp(-0.5 * ((t - mean) / scale)**2) / (scale * np.sqrt(2 * np.pi))\ndensity_ax.plot(grid, normal(grid, 0, 1), color=INK, ls=\"--\", label=\"prior N(0, 1)\")\ndensity_ax.plot(grid, normal(grid, probe_latent[0], sd), color=ORANGE, label=\"posterior for probe\")\ndensity_ax.axvline(probe_latent[0], color=ORANGE, ls=\":\", lw=1)\ndensity_ax.set(xlabel=\"latent coordinate z\", ylabel=\"density\", title=\"Uncertainty conditional on the model\")\ndensity_ax.legend(frameon=False, fontsize=8)\nfig.tight_layout(pad=1.2)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Left: synthetic sensor readings and a fixed probe, with its classical projection and PPCA posterior signal mean on the fitted axis. Right: the probe's latent prior and posterior densities, conditional on fitted parameters.](index_files/figure-html/fig-ppca-output-1.png){#fig-ppca fig-alt='A diagonal cloud of paired readings with a probe off the fitted line. Its PPCA reconstruction is closer to the fitted mean than its classical projection. A second panel compares a broad standard normal prior with a narrower shifted latent posterior.'}\n:::\n:::\n\n\nThe orange point stays on the principal axis but moves toward the fitted mean. The posterior density describes the latent coordinate's remaining uncertainty; it is not a confidence interval for the axis itself.\n\n## Constraints and use\n\n- **Equal noise is a substantive assumption.** Feature rescaling changes its meaning. Different sensor noise variances call for a different observation model; ordinary standardization does not establish isotropic noise.\n- **Latent uncertainty is conditional.** A narrow posterior can still be misleading if the noise model or fitted parameters are wrong. PPCA with point-estimated parameters is not a fully Bayesian treatment of parameter uncertainty.\n- **Choosing $k$ requires a criterion.** The MLE formulas assume $k$ is fixed. A larger fitted likelihood alone does not validate a larger dimension; model comparison or held-out performance must account for complexity.\n- **Missing values require a different fitting procedure.** Given parameters, the Gaussian model can condition on observed coordinates. Learning those parameters from incomplete data requires an observed-data likelihood, for example optimized by EM; the complete-data covariance formula does not apply unchanged. The original PPCA paper develops that extension.\n\nUse classical PCA when the goal is an orthogonal projection minimizing squared reconstruction error. Use PPCA when a Gaussian observation model is defensible and a density or conditional latent uncertainty is useful.\n\nModel. Signal. Estimate. Noise. Recover. Subspaces. Shrink. Reconstructions. Check. Assumptions.\n\n## References\n\n- Tipping, M. E., and Bishop, C. M. (1999). [Probabilistic principal component analysis](https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/bishop-ppca-jrss.pdf). *Journal of the Royal Statistical Society, Series B* 61(3), 611–622. [DOI](https://doi.org/10.1111/1467-9868.00196).\n- [Six Views of PCA](../six-views-of-pca/) — projection geometry, equivalent objectives, and preprocessing.\n\n",
    "supporting": [
      "index_files/figure-html"
    ],
    "filters": [],
    "includes": {}
  }
}