{
  "hash": "99b6c18ddcb3e8b896d32a4ecf59405c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Neutrophil Metabolomes as a Matrix\"\nsubtitle: \"Mild COVID neutrophils are not halfway from healthy to severe. A classifier will still separate the groups.\"\ndescription: \"Seventy-five neutrophil metabolomes, three COVID labels. Fit a line through the group means before PCA, a classifier, or a tensor. Mild sits off that line. Use the leftover; do not score past it.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-09-10\"\ncategories: [Bioinformatics, Machine Learning, Linear Algebra]\nimage: \"./cover.png\"\ntags: [metabolomics, neutrophils, COVID-19, PCA, tensors, LC-MS]\njupyter: neutrophil-axis-blog\nresources:\n  - cover.png\n  - data\nexecute:\n  warning: false\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    code-fold: true\n    number-sections: true\n    fig-width: 8\n    fig-height: 4.8\n    fig-dpi: 150\n---\n\n\n![Neutrophil Metabolomes as a Matrix](./cover.png){fig-alt=\"Three group-mean points in a plane: Control and Severe on a line, Mild off that line.\"}\n\nA classifier will separate these three COVID neutrophil groups. That is the easy trick. It does not mean mild disease sits on the road from healthy to severe.\n\nSeventy-five people, 285 metabolites, three labels. PCA, then a linear model, then — if the labels look like an extra axis — a tensor: that is the usual ML stack. The labels are tags on rows, the way train and test tags are. Stacking them into a cube fills two-thirds of the array with holes. A severity score that parks Mild at the midpoint mixes two kinds of change: metabolites that rise with disease, and metabolites that dip in Mild and bounce in Severe.\n\nLi et al. (2023) isolated neutrophils from 75 people, extracted two million cells each, and deposited LC-MS peak areas as Metabolomics Workbench ST002477 (CC BY 4.0). They wanted the cell that kills, not plasma. The numbers are relative ion intensities, not counts and not fluxes. The job that fits the file is a line through three group means, then a look at what the line misses.\n\n\n\n## Neutrophil metabolomes\n\nPlasma metabolomes mix liver, muscle, and lunch. This table is one cell type: the neutrophil, the cell that does the killing.\n\nNeutrophils eat microbes, dump oxidants, and throw DNA nets (NETs). That work runs on glycolysis and the pentose-phosphate pathway (Morrison, Watts, Sadiku, and Walmsley 2022). In severe COVID-19 these cells pile up in failing lungs. If their fuel is off, killing and damage move together. Li et al. saw amino-acid, redox, and central-carbon pools shift, and showed GAPDH can suppress NET formation. Peak area is not that flux. It is still the public readout of the cell.\n\nErythrose 4-phosphate sits on the pathway that powers the oxidant burst (Britt et al. 2022). Hypotaurine and glycine sit near redox handling. A linear \"disease score\" will scramble names like these if they do not move in a straight line from Control to Severe.\n\n## Source table\n\n75 profiles: 19 Control, 30 Mild, 26 Severe. 287 named rows, 285 unique vectors. Chromatogram peak areas from a targeted Q Exactive method, median-normalised per sample. Nonnegative and continuous. Not integer counts.\n\n| metabolite | PMN_74 (C) | PMN_75 (C) | PMN_02 (M) | PMN_03 (M) | PMN_48 (S) | PMN_49 (S) |\n| --- | ---: | ---: | ---: | ---: | ---: | ---: |\n| Hypotaurine | 6.97e+08 | 3.66e+08 | 5.58e+08 | 1.39e+08 | 9.88e+08 | 6.45e+08 |\n| Glycine | 1.07e+08 | 8.54e+07 | 7.55e+07 | 8.73e+07 | 9.30e+07 | 1.09e+08 |\n| Erythrose 4-phosphate | 1.06e+06 | 5.94e+06 | 2.67e+06 | 3.12e+06 | 3.40e+04 | 1.85e+05 |\n| 1,3/ 2,3-Bisphosphoglycerate | 6.71e+04 | 1.11e+05 | 1.73e+06 | 3.79e+07 | 2.28e+05 | 5.03e+06 |\n| Creatine | 9.06e+09 | 6.27e+09 | 9.80e+09 | 7.02e+09 | 8.04e+09 | 1.49e+10 |\n| Uridine monophosphate | 4.36e+07 | 1.39e+06 | 1.54e+06 | 1.98e+06 | 1.64e+06 | 1.68e+06 |\n\n\nRelative peak areas, two samples per group. The range is normal for ion intensity. It is not a count table.\n\n## Matrix layout\n\nEach person is one row. Each metabolite is one column. $X \\in \\mathbb{R}^{75 \\times 285}$. Control, Mild, and Severe partition those rows. They do not add a third index.\n\nA tensor mode can vary on its own. Here each person sits in one group. `sample × metabolite × group` leaves two slices empty for every person. CP on that cube would spend rank explaining holes the design made.\n\nCollapse to group means and the sample mode becomes three levels: a $3 \\times 285$ matrix, still two-way. Three points live in a plane. Rank at most two.\n\n\n```{mermaid}\nflowchart LR\n  subgraph nested [Nested design]\n    samples[\"75 samples\"] --> matrixX[\"X: 75 x 285\"]\n    samples --> partition[\"19 Control / 30 Mild / 26 Severe\"]\n  end\n  subgraph crossed [Crossed design]\n    donor[\"donor\"] --> cube[\"donor x condition x metabolite\"]\n    condition[\"condition\"] --> cube\n    metabolite[\"metabolite\"] --> cube\n  end\n```\n\n\nGroup would be a third mode if the same people were measured in all three states. This cohort is one snapshot per person. Raw chromatograms could still be `sample × retention time × m/z`. Those files are not in the public table.\n\n## Shared mean axis\n\nThree class means in 285 dimensions are three points. They always sit in a plane. The live question is whether they also sit on a line: whether one severity number reconstructs the means. If not, any model that uses that number mixes two directions.\n\nPark Mild at a free place $t$ on the Control–Severe line:\n\n$$\n\\kappa(t)=\\bar x_{\\mathrm{Mild}}-\\bigl[(1-t)\\bar x_{\\mathrm{Control}}+t\\bar x_{\\mathrm{Severe}}\\bigr].\n$$\n\nOne shared $t$ minimises $\\lVert\\kappa(t)\\rVert_2^2$. Ordinary least squares. The midpoint model is $t=0.5$.\n\n::: {#c03c66c6 .cell execution_count=3}\n``` {.python .cell-code}\nprint(f\"t_hat = {t_hat:.2f}\")\nprint(f\"off-line fraction of between-group SS = {off_line:.2f}\")\nprint(f\"Control n = {(labels == 'Control').sum()}\")\nprint(f\"Mild n = {(labels == 'Mild').sum()}\")\nprint(f\"Severe n = {(labels == 'Severe').sum()}\")\nprint(f\"features = {Z.shape[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nt_hat = 0.69\noff-line fraction of between-group SS = 0.28\nControl n = 19\nMild n = 30\nSevere n = 26\nfeatures = 285\n```\n:::\n:::\n\n\nLeast-squares puts Mild at $t=0.69$, nearer Severe than Control. The leftover $\\kappa$ is 28% of the between-group sum of squares. Most of the three means still sit on the line. What misses it is structured.\n\nHypotaurine and glycine dip in Mild and rise in Severe. Erythrose 4-phosphate and bisphosphoglycerate drop in Severe. A severity score will not look like those names. They are candidates for a follow-up assay. They are not a pathway map.\n\n::: {#cell-fig-axis .cell execution_count=4}\n``` {.python .cell-code}\nchord = float(np.linalg.norm(delta))\nfig, ax = plt.subplots()\nax.plot([0.0, chord], [0.0, 0.0], color=LINE, lw=1.8, zorder=1)\nax.plot([t_hat * chord, t_hat * chord], [0.0, float(np.linalg.norm(kappa))], color=MUTED, ls=\"--\", lw=1.2)\npoints = {\n    \"Control\": (0.0, 0.0),\n    \"Mild\": (t_hat * chord, float(np.linalg.norm(kappa))),\n    \"Severe\": (chord, 0.0),\n}\nfor group, (x, y) in points.items():\n    ax.scatter([x], [y], s=90, color=COLOURS[group], zorder=3, label=group)\n    ax.annotate(group, (x, y), textcoords=\"offset points\", xytext=(8, 8), color=INK)\nax.set_xlabel(\"Position on the Control–Severe chord\")\nax.set_ylabel(\"Residual\")\nax.legend(frameon=False, loc=\"upper left\")\nfig.tight_layout()\nletterbox_cover(fig)\n```\n\n::: {.cell-output .cell-output-display}\n![Group means in the plane of the Control–Severe chord and its residual. Control and Severe sit on the horizontal line. Mild sits off it. Coordinates are log1p then IQR-scaled peak areas.](index_files/figure-html/fig-axis-output-1.png){#fig-axis fig-alt='Scatter of three labelled points. Control at the origin, Severe on the x-axis, Mild above the x-axis with a vertical residual.'}\n:::\n:::\n\n\nRank one of the three centroids is the line. Rank two is the leftover. Rank three is empty. CP on the 75 × 285 table is SVD. Padding groups into a cube does not change that.\n\n## PCA\n\nDo the 75 people separate, or only their means?\n\n::: {#e9e8d3cd .cell execution_count=5}\n``` {.python .cell-code}\nprint(f\"PC1 variance fraction = {pc_var[0]:.2f}\")\nprint(f\"PC2 variance fraction = {pc_var[1]:.2f}\")\nfor group in GROUPS:\n    centre = pc_scores[labels == group].mean(axis=0)\n    print(f\"{group} mean PC1 = {centre[0]:.2f}, mean PC2 = {centre[1]:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPC1 variance fraction = 0.21\nPC2 variance fraction = 0.11\nControl mean PC1 = -6.95, mean PC2 = 0.13\nMild mean PC1 = 1.75, mean PC2 = -2.23\nSevere mean PC1 = 3.06, mean PC2 = 2.48\n```\n:::\n:::\n\n\n::: {#cell-fig-pca .cell execution_count=6}\n``` {.python .cell-code}\nfig, ax = plt.subplots()\nfor group in GROUPS:\n    pts = pc_scores[labels == group]\n    ax.scatter(pts[:, 0], pts[:, 1], s=28, color=COLOURS[group], alpha=0.85, label=group)\nax.set_xlabel(\"PC1\")\nax.set_ylabel(\"PC2\")\nax.legend(frameon=False)\nfig.tight_layout()\n```\n\n::: {.cell-output .cell-output-display}\n![First two principal components of the 75 log1p/IQR profiles. PC1 holds 21% of sample variance; PC2 holds 11%.](index_files/figure-html/fig-pca-output-1.png){#fig-pca fig-alt='Scatter of 75 points coloured by Control, Mild, and Severe on PC1 versus PC2.'}\n:::\n:::\n\n\nPC1 holds 21% of sample variance; PC2 holds 11%. Group means on PC1: Control −6.95, Mild 1.75, Severe 3.06. Mild sits between the ends, closer to Severe. On PC2, Mild (−2.23) sits opposite Severe (2.48). People overlap. The leftover is in the cloud, not only in the means.\n\n## Downstream models\n\nUse the split. Do not score past it.\n\n- **Line through the three means.** Is one severity number enough? $t=0.69$ and a 28% leftover say no.\n- **PCA of people.** Do individuals separate? They overlap.\n- **Tests with false-discovery control**, as in a [volcano plot](../volcano-plots/). Rank metabolites by distance off the line, not by label accuracy.\n- **Sparse PLS or elastic net**, group-stratified CV, only to rank features. 75 people will not carry a biomarker; see [From Dataset to Biological Signature](../dataset-to-biological-signature/).\n- **CP / PARAFAC** only on a real cube: chromatograms, or the same donors in more than one state. [Uses of Tensor Factorizations](../uses-of-tensor-factorizations/) is that case. This file is not.\n\nSkip an unregularised 285-feature classifier, a deep net, Poisson models, and NMF on Li et al.'s signed Dataset 3.\n\nNumPy and scikit-learn for the line and PCA. MetaboAnalyst for tables (Pang et al. 2021). mixOmics / ropls for PLS. MZmine, XCMS, pyOpenMS, matchms for chromatograms. TensorLy for PARAFAC (Bro 1997).\n\n## Constraints\n\nThis is one transform of one matrix, not a biomarker panel.\n\n- Peak area is not flux and not NETs.\n- A deposited name is not a confirmed structure. Forty lipids are sum-composition labels.\n- Groups are not time. One cohort is not a replication. Bulk pellets mix cell-state with within-cell change.\n- $t=0.69$ and the 28% leftover move if the transform moves.\n\nLine. First. Mild. Sits. Off. Score. After. Residual. Cubes. Need. Crossed. Modes.\n\n## References\n\n- Britt, E. C., et al. (2022). Switching to the cyclic pentose phosphate pathway powers the oxidative burst in activated neutrophils. *Nature Metabolism*. [doi:10.1038/s42255-022-00550-8](https://doi.org/10.1038/s42255-022-00550-8)\n- Bro, R. (1997). PARAFAC. Tutorial and applications. *Chemometrics and Intelligent Laboratory Systems* 38: 149–171. [doi:10.1016/S0169-7439(97)00032-4](https://doi.org/10.1016/S0169-7439(97)00032-4)\n- Information retained and lost by a shared linear mean axis in COVID-19 neutrophil metabolomics. Research Square preprint `rs-10583501`. [doi:10.21203/rs.3.rs-10583501/v1](https://doi.org/10.21203/rs.3.rs-10583501/v1)\n- Li, Y., et al. (2023). Neutrophil metabolomics in severe COVID-19 reveal GAPDH as a suppressor of neutrophil extracellular trap formation. *Nature Communications* 14: 2610. [doi:10.1038/s41467-023-37567-w](https://doi.org/10.1038/s41467-023-37567-w)\n- Metabolomics Workbench ST002477 / PR001600. [doi:10.21228/M8W70C](https://doi.org/10.21228/M8W70C)\n- Morrison, T., Watts, E. R., Sadiku, P., and Walmsley, S. R. (2022). The emerging role for metabolism in fueling neutrophilic inflammation. *Immunological Reviews*. [doi:10.1111/imr.13157](https://doi.org/10.1111/imr.13157)\n- Pang, Z., et al. (2021). MetaboAnalyst 5.0: narrowing the gap between raw spectra and functional insights. *Nucleic Acids Research*. [doi:10.1093/nar/gkab382](https://doi.org/10.1093/nar/gkab382)\n- [From Dataset to Biological Signature](../dataset-to-biological-signature/)\n- [The Anatomy of a Volcano Plot](../volcano-plots/)\n- [Uses of Tensor Factorizations](../uses-of-tensor-factorizations/)\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}