{
  "hash": "c9ecc47784268dccf429e4b4916983aa",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"LLM Agents from First Principles\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-08-02\"\ncategories: [Agents, LLM, Machine Learning]\nimage: \"./cover.png\"\ntags: [agents, llm, tool-use, react, groq]\njupyter: llm-agents\nresources:\n  - agent.py\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n    code-fold: true\n    number-sections: true\n---\n\n```{=html}\n<style>\n/* Model transcripts are the payload of this post and some THOUGHT lines run\n   long. Wrap printed cell output instead of clipping it to a scrollbar; the\n   source blocks above keep their normal no-wrap behaviour. */\n.cell-output-stdout pre code { white-space: pre-wrap; word-break: break-word; }\n</style>\n```\n\n\n![LLM Agents from First Principles](./cover.png)\n\nAn LLM agent is a `while` loop with one stochastic step per iteration. Everything else — message history, tool dispatch, output parsing, turn budgets — is deterministic Python with no learned parameters.\n\nThis post builds that loop in [`agent.py`](./agent.py), imports it below (not retyped), and runs it live against a real model. Transcripts were captured at render time.\n\n## Agent components\n\nThree terms define the design:\n\n- **Action** — call a tool, or stop and answer.\n- **Observation** — what the environment returns after an action.\n- **Policy** — maps history to the next action; here, the language model.\n\nThe model is not the agent. It is one function sampled once per iteration; its output is a string that must be parsed into an action.\n\nFailure modes to expect: unparseable policy output, tool exceptions, non-terminating loops. All are scaffold problems — code you write, not model weights.\n\n## Model backend\n\nThe only stochastic connection is an HTTP POST and a dictionary lookup:\n\n```python\n@dataclass\nclass GroqBackend:\n    \"\"\"OpenAI-compatible chat completions against Groq's free tier.\n\n    The API key is read from the environment, never passed in and never\n    written down. This is the only object in the module that touches the\n    network, and the only source of randomness in the whole agent.\n    \"\"\"\n\n    model: str = DEFAULT_MODEL\n    calls: int = 0  # how many times the policy was sampled\n\n    def create(\n        self, messages: list[dict], max_tokens: int = 512, temperature: float = 0.0\n    ) -> str:\n        key = os.environ.get(\"GROQ_API_KEY\")\n        if not key:\n            raise RuntimeError(\n                \"GROQ_API_KEY is not set. Get a free key at \"\n                \"https://console.groq.com/keys and export it before running.\"\n            )\n        payload = json.dumps(\n            {\n                \"model\": self.model,\n                \"messages\": messages,\n                \"max_tokens\": max_tokens,\n                \"temperature\": temperature,\n            }\n        ).encode()\n        request = urllib.request.Request(\n            GROQ_URL,\n            data=payload,\n            headers={\n                \"Authorization\": f\"Bearer {key}\",\n                \"Content-Type\": \"application/json\",\n                # Without this the edge rejects the request with a bare 403\n                # (Cloudflare 1010): the stdlib's default `Python-urllib/3.x`\n                # agent string is on a blocklist. `requests` gets away with it\n                # only because it sends a UA the blocklist doesn't cover.\n                \"User-Agent\": \"llm-agents-from-first-principles/1.0\",\n            },\n        )\n        try:\n            with urllib.request.urlopen(request, timeout=90) as response:\n                body = json.load(response)\n        except urllib.error.HTTPError as exc:  # surface the API's own message\n            raise RuntimeError(f\"Groq {exc.code}: {exc.read().decode()[:400]}\") from exc\n        self.calls += 1\n        return body[\"choices\"][0][\"message\"][\"content\"].strip()\n```\n\n\n**Policy:** [Llama 3.3 70B Instruct](https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct) (Meta), served via [Groq](https://console.groq.com/) free tier.\n\n**Provenance:** Pretrained on a large undisclosed web corpus; instruction-tuned for chat-format following.\n\n**Task in this post:** Given a question and tool list, emit the next action.\n\n**Downstream impact here:** Wrong action → wrong arithmetic in a blog post. The same loop wired to spending or database tools inherits these failure modes with real cost.\n\n**Why this policy:** Instruction tuning makes the format contract below work as a statistical tendency, not a guarantee.\n\n`create(messages) -> str` has no key, retry policy, or state. Swap in any function with that signature — local model, other provider, stub — and the rest of the file is unchanged.\n\n## State\n\nTwo state kinds must stay separate:\n\n- **`Transcript`** — dialogue; the message list the model conditions on.\n- **`AgentState`** — scaffold bookkeeping (turn count, budget); the model sees only what the prompt includes.\n\n```python\n@dataclass\nclass Transcript:\n    \"\"\"Dialogue state -- the exact message list handed to the model.\"\"\"\n\n    messages: list[dict] = field(default_factory=list)\n\n    def user(self, content: str) -> None:\n        self.messages.append({\"role\": \"user\", \"content\": content})\n\n    def assistant(self, content: str) -> None:\n        self.messages.append({\"role\": \"assistant\", \"content\": content})\n\n    def observation(self, content: str) -> None:\n        # Tool results re-enter as user turns: the chat schema has no separate\n        # \"environment\" role, so the observation is framed as one.\n        self.messages.append({\"role\": \"user\", \"content\": f\"OBSERVATION: {content}\"})\n\n    def as_messages(self) -> list[dict]:\n        return list(self.messages)\n\n@dataclass\nclass AgentState:\n    \"\"\"Scaffold state. The model never sees this except as a budget line.\"\"\"\n\n    turn: int = 0\n    max_turns: int = 6\n    tool_calls: int = 0\n    max_tool_calls: int = 4\n    memory: dict[str, Any] = field(default_factory=dict)\n\n    def budget_line(self) -> str:\n        left = self.max_turns - self.turn\n        return f\"You have {left} turn(s) left. Finish before they run out.\"\n```\n\n\nThe chat schema has no environment role. Tool results re-enter as user turns prefixed `OBSERVATION:`. The `memory` dict is unused in this version.\n\n## Tool registry\n\nA tool is a Python function plus a description string. The registry holds both; `execute` is the main design choice:\n\n```python\n@dataclass\nclass Tool:\n    \"\"\"A callable the model may invoke, plus the text describing it.\"\"\"\n\n    name: str\n    description: str\n    args: dict[str, str]  # arg name -> type, purely for the prompt\n    fn: Callable[..., str]\n\n    def spec(self) -> str:\n        signature = \", \".join(f\"{k}: {v}\" for k, v in self.args.items())\n        return f\"  {self.name}({signature}) -- {self.description}\"\n\n@dataclass\nclass ToolRegistry:\n    \"\"\"Holds the tools and runs them. Never raises into the agent loop.\n\n    Every failure mode -- unknown tool name, wrong argument names, an\n    exception inside the tool itself -- comes back as an observation string.\n    A crashed tool is information the policy can act on, not a bug in the\n    scaffold, so the loop keeps running and the model gets told what broke.\n    \"\"\"\n\n    tools: dict[str, Tool] = field(default_factory=dict)\n\n    def add(self, tool: Tool) -> \"ToolRegistry\":\n        self.tools[tool.name] = tool\n        return self\n\n    def specs(self) -> str:\n        if not self.tools:\n            return \"  (none)\"\n        return \"\\n\".join(t.spec() for t in self.tools.values())\n\n    def execute(self, name: str, args: dict) -> str:\n        tool = self.tools.get(name)\n        if tool is None:\n            known = \", \".join(self.tools) or \"none\"\n            return f\"ERROR: no tool named {name!r}. Available tools: {known}.\"\n        try:\n            return str(tool.fn(**args))\n        except TypeError as exc:\n            expected = \", \".join(tool.args) or \"no arguments\"\n            return f\"ERROR: bad arguments for {name} (expects {expected}): {exc}\"\n        except Exception as exc:\n            return f\"ERROR: {name} raised {type(exc).__name__}: {exc}\"\n```\n\n\nNothing raises. Unknown tool names, bad arguments, and in-tool exceptions all return observation strings. The policy can recover on the next turn; raising kills the run.\n\nExample tools:\n\n```python\ndef _eval_node(node: ast.AST) -> float:\n    \"\"\"Evaluate a whitelisted arithmetic AST node.\"\"\"\n    if isinstance(node, ast.Expression):\n        return _eval_node(node.body)\n    if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):\n        return node.value\n    if isinstance(node, ast.BinOp) and type(node.op) in _BINOPS:\n        left, right = _eval_node(node.left), _eval_node(node.right)\n        if isinstance(node.op, ast.Pow) and abs(right) > _MAX_EXPONENT:\n            raise ValueError(f\"exponent {right} exceeds the limit of {_MAX_EXPONENT}\")\n        return _BINOPS[type(node.op)](left, right)\n    if isinstance(node, ast.UnaryOp) and type(node.op) in _UNARYOPS:\n        return _UNARYOPS[type(node.op)](_eval_node(node.operand))\n    raise ValueError(f\"unsupported syntax: {type(node).__name__}\")\n\ndef calculator(expr: str) -> str:\n    \"\"\"Evaluate an arithmetic expression exactly, without `eval`.\"\"\"\n    # `^` means xor in Python but exponentiation in maths notation, and models\n    # write the maths one. Translate it rather than failing on it.\n    cleaned = expr.replace(\"^\", \"**\")\n    value = _eval_node(ast.parse(cleaned, mode=\"eval\"))\n    # `/` always yields a float, so an exact result reads as \"2341.0\" and the\n    # model then feeds that string to a tool wanting an integer. Narrow it.\n    if isinstance(value, float) and value.is_integer():\n        value = int(value)\n    return f\"{expr} = {value}\"\n\ndef is_prime(n: int) -> str:\n    \"\"\"Trial-divide to decide primality.\"\"\"\n    n = int(n)\n    if n < 2:\n        return f\"{n} is not prime\"\n    factor = next((d for d in range(2, int(n**0.5) + 1) if n % d == 0), None)\n    if factor is None:\n        return f\"{n} is prime\"\n    return f\"{n} is not prime (divisible by {factor})\"\n```\n\n\n- **`calculator`** — AST walk with a whitelist, not `eval`; model-written expressions are untrusted input.\n- **Cost bound** — whitelist blocks arbitrary code but not expensive legal expressions (e.g. `9**9**9`).\n- Both tools return strings for transcript insertion.\n\n## Output parsing\n\nThe prompt requests one of two output shapes. Compliance is not guaranteed; `parse` enforces the contract:\n\n```python\ndef parse(text: str) -> Action:\n    \"\"\"Extract a tool call or a final answer from raw model output.\n\n    This is where the contract with the model is actually enforced. The model\n    was *asked* for a format; nothing guarantees it complied. A violation is\n    an expected event, so it returns a ParseError value rather than raising --\n    the loop feeds it back and lets the policy correct itself.\n    \"\"\"\n    thought_match = _THOUGHT_RE.search(text)\n    thought = thought_match.group(1).strip() if thought_match else \"\"\n\n    action_match = _ACTION_RE.search(text)\n    if action_match and action_match.group(1).strip().lower() in _NULL_ACTIONS:\n        action_match = None\n\n    if action_match:\n        input_match = _INPUT_RE.search(text)\n        if not input_match:\n            return ParseError(\n                \"ACTION was given without a valid ACTION_INPUT line. \"\n                \"ACTION_INPUT must be a single-line JSON object.\"\n            )\n        try:\n            args = json.loads(input_match.group(1))\n        except json.JSONDecodeError as exc:\n            return ParseError(f\"ACTION_INPUT was not valid JSON: {exc}\")\n        if not isinstance(args, dict):\n            return ParseError(\"ACTION_INPUT must be a JSON object, not a scalar.\")\n        return ToolCall(name=action_match.group(1), args=args, thought=thought)\n\n    final_match = _FINAL_RE.search(text)\n    if final_match:\n        return Final(answer=final_match.group(1).strip(), thought=thought)\n\n    return ParseError(\n        \"Output matched neither form. Emit either ACTION plus ACTION_INPUT, \"\n        \"or FINAL followed by your answer.\"\n    )\n```\n\n\n`_NULL_ACTIONS` handles a observed bug: Llama 3.3 often emits `ACTION: None` alongside a valid `FINAL:` line. Treating null tokens as \"no action\" fixed wasted turns.\n\nGenuine violations return a `ParseError` value, not an exception — malformed output is a normal event on the happy path.\n\n## Agent loop\n\n`render` assembles protocol, tool specs, budget, and transcript. It is a pure function of state:\n\n```python\ndef render(\n    transcript: Transcript, state: AgentState, registry: ToolRegistry\n) -> list[dict]:\n    \"\"\"Assemble the full message list from transcript + state + tool specs.\"\"\"\n    system = PROTOCOL.format(tools=registry.specs(), budget=state.budget_line())\n    return [{\"role\": \"system\", \"content\": system}, *transcript.as_messages()]\n```\n\n\nThe loop:\n\n```python\n@dataclass\nclass Agent:\n    \"\"\"Deterministic control flow around one stochastic call.\"\"\"\n\n    backend: Backend\n    registry: ToolRegistry = field(default_factory=ToolRegistry)\n    max_turns: int = 6\n    max_tool_calls: int = 4\n    temperature: float = 0.0\n\n    def run(self, question: str) -> Trace:\n        state = AgentState(max_turns=self.max_turns, max_tool_calls=self.max_tool_calls)\n        transcript = Transcript()\n        transcript.user(question)\n        trace = Trace(question=question)\n\n        while state.turn < state.max_turns:\n            state.turn += 1\n\n            # The one stochastic line in this function.\n            raw = self.backend.create(\n                render(transcript, state, self.registry),\n                temperature=self.temperature,\n            )\n            transcript.assistant(raw)\n            action = parse(raw)\n            step = Step(turn=state.turn, raw=raw, action=action)\n            trace.steps.append(step)\n\n            if isinstance(action, Final):\n                trace.answer = action.answer\n                trace.stop_reason = \"answered\"\n                return trace\n\n            if isinstance(action, ParseError):\n                step.observation = f\"ERROR: {action.reason}\"\n                transcript.observation(step.observation)\n                continue\n\n            if state.tool_calls >= state.max_tool_calls:\n                step.observation = (\n                    \"ERROR: tool call budget exhausted. Answer with FINAL now.\"\n                )\n                transcript.observation(step.observation)\n                continue\n\n            state.tool_calls += 1\n            step.observation = self.registry.execute(action.name, action.args)\n            state.memory[f\"turn{state.turn}:{action.name}\"] = step.observation\n            transcript.observation(step.observation)\n\n        trace.stop_reason = \"turn budget exhausted\"\n        return trace\n```\n\n\nPer iteration: increment turn, sample policy, parse, then return, feed back a parse error, or run a tool and append its observation. Turn and tool-call budgets make termination a code property, not a model hope.\n\n## Example: direct answer, no tools\n\nArithmetic the model can solve without tools; tests bare loop termination:\n\n::: {#10128ae9 .cell execution_count=8}\n``` {.python .cell-code code-fold=\"false\"}\nfrom agent import Agent, GroqBackend, default_registry\n\nAgent(backend=GroqBackend()).run(\"What is (37 * 4 - 9) / 5?\").show()\n```\n:::\n\n\nCaptured transcript from the original render (one sample; re-running the cell needs `GROQ_API_KEY` and may differ):\n\n```\nQUESTION: What is (37 * 4 - 9) / 5?\n\n--- turn 1 | model output ---\nTHOUGHT: To find the result of the given expression, I need to follow the order of operations: first multiplication, then subtraction, and finally division.\nACTION: None\nFINAL: (37 * 4 - 9) / 5 = (148 - 9) / 5 = 139 / 5 = 27.8\n\nANSWER (answered): (37 * 4 - 9) / 5 = (148 - 9) / 5 = 139 / 5 = 27.8\n```\n\nOne turn, no tools. Answer: `139 / 5 = 27.8`. Raw output may include `ACTION: None`, absorbed by the parser.\n\n## Example: two tool round trips\n\nSame loop with both tools; question requires computation the model cannot know without tools:\n\n::: {#f7c50033 .cell execution_count=9}\n``` {.python .cell-code code-fold=\"false\"}\nAgent(backend=GroqBackend(), registry=default_registry()).run(\n    \"Use the calculator tool to compute (128^2 + 3) / 7, \"\n    \"then tell me whether the result is prime.\"\n).show()\n```\n:::\n\n\nCaptured transcript from the original render:\n\n```\nQUESTION: Use the calculator tool to compute (128^2 + 3) / 7, then tell me whether the result is prime.\n\n--- turn 1 | model output ---\nTHOUGHT: First, we need to compute the value of (128^2 + 3) / 7 using the calculator tool.\nACTION: calculator\nACTION_INPUT: {\"expr\": \"(128^2 + 3) / 7\"}\n--- turn 1 | observation ---\n(128^2 + 3) / 7 = 2341\n\n--- turn 2 | model output ---\nTHOUGHT: Now that we have the result of the calculation, we need to check whether 2341 is a prime number using the is_prime tool.\nACTION: is_prime\nACTION_INPUT: {\"n\": 2341}\n--- turn 2 | observation ---\n2341 is prime\n\n--- turn 3 | model output ---\nTHOUGHT: We have now determined that the result of the calculation, 2341, is indeed a prime number.\nFINAL: 2341 is prime\n\nANSWER (answered): 2341 is prime\n```\n\nThree turns, two tool round trips:\n\n1. `ACTION: calculator` → `16387 / 7 = 2341`\n2. `ACTION: is_prime` → `2341 is prime`\n3. `FINAL:` — stop\n\nCheckable facts: `128² + 3 = 16387`, `16387 / 7 = 2341`, 2341 is prime.\n\nBetween model calls: regex match, `dict.get`, function call.\n\n## Constraints\n\nBoth runs used `temperature=0.0` (greedy decoding). Batching and floating-point non-associativity on the server can still yield different text for identical requests.\n\nTranscripts here are one sample from a trajectory distribution, not a fixed point. Re-rendering may change route or tool order. Turn and tool-call budgets exist in code for this reason.\n\n## Local execution\n\n`agent.py` uses only the standard library.\n\n```bash\nexport GROQ_API_KEY=...          # never hardcode it; the module reads the env\npython agent.py                  # runs both examples above\n```\n\nKey source: [console.groq.com/keys](https://console.groq.com/keys). If unset, `GroqBackend.create` raises with that instruction.\n\n## Summary\n\n- **Stochastic:** `create` calls only.\n- **Deterministic:** prompt assembly, parsing, dispatch, budgets, termination.\n- **Tool outputs:** deterministic in these examples; real environments (search, files) add a second randomness source.\n\n**Debugging:** When an agent misbehaves, ask whether the policy picked a bad action or the scaffold mishandled a good one. The `ACTION: None` case was a strict parser, not a model failure.\n\nFrameworks add memory across runs, multi-step planning, multi-agent coordination — all scaffold changes; the loop shape stays the same.\n\n## References\n\n- [Llama 3.3 70B Instruct](https://huggingface.co/meta-llama/Llama-3.3-70B-Instruct) — Meta\n- [Groq console](https://console.groq.com/) — model serving\n- [Groq API keys](https://console.groq.com/keys)\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}