{
  "hash": "c038cfa857d4867a119cb1ade8312212",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Two Ways to Expand the Space: Persistent Homology and Kernel SVMs on the Same Toy Dataset\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-07-22\"\ncategories: [Machine Learning, Topology, TDA, Support Vector Machines, Kernel Methods]\nimage: \"./cover.png\"\ntags: [Persistent Homology, Ripser, Kernel Trick, RBF, Feature Maps]\njupyter: tda-svm-blog\nformat:\n    html:\n        toc: true\n        toc-depth: 3\n        code-fold: true\n        number-sections: true\n---\n\n\n![Two Ways to Expand the Space: Persistent Homology and Kernel SVMs on the Same Toy Dataset](./cover.png)\n\nA disk inside a ring is not linearly separable in $\\mathbb{R}^2$. **Persistent homology** (unsupervised) reports the annular hole. A **kernel SVM** (supervised) finds a curved decision boundary. Neither fits a curve in the plane; both lift data into a richer space.\n\n## Toy dataset\n\n**Data provenance** (synthetic):\n\n- 100 points uniform inside disk radius 0.35 (class 0).\n- 140 points on circle radius 1.0 + Gaussian noise $\\sigma = 0.06$ (class 1).\n- 240 points total; empty annulus between radii 0.35 and 1.0 = one hole by construction.\n- Stands in for one class surrounding another (e.g. normal regime ringed by fault conditions).\n- Same shape as `make_circles` but one filled blob inside one ring (avoids two-loop bookkeeping).\n\n::: {#091457bf .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport matplotlib.pyplot as plt\n\n\ndef make_disk_and_ring(n_inside=100, n_ring=140, r_inside=0.35, r_ring=1.0, ring_noise=0.06, seed=7):\n    rng = np.random.default_rng(seed)\n    theta_in = rng.uniform(0, 2 * np.pi, n_inside)\n    r_in = r_inside * np.sqrt(rng.uniform(0, 1, n_inside))\n    inside = np.column_stack([r_in * np.cos(theta_in), r_in * np.sin(theta_in)])\n\n    theta_out = rng.uniform(0, 2 * np.pi, n_ring)\n    r_out = r_ring + rng.normal(0, ring_noise, n_ring)\n    ring = np.column_stack([r_out * np.cos(theta_out), r_out * np.sin(theta_out)])\n\n    X = np.vstack([inside, ring])\n    y = np.concatenate([np.zeros(n_inside), np.ones(n_ring)]).astype(int)\n    return X, y\n\n\nX, y = make_disk_and_ring()\n\nfig, ax = plt.subplots(figsize=(5, 5))\nax.scatter(*X[y == 0].T, s=18, color=\"tab:blue\", label=\"inside (class 0)\")\nax.scatter(*X[y == 1].T, s=18, color=\"tab:red\", label=\"ring (class 1)\")\nax.set_aspect(\"equal\")\nax.set_title(\"The toy dataset: 100 points inside, 140 on a noisy ring\")\nax.legend(loc=\"upper right\", fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-2-output-1.png){}\n:::\n:::\n\n\nAll later sections use this fixed `X`, `y`.\n\n## Persistent homology\n\nLabels are not used. Input: 240 points and pairwise distances.\n\n### Vietoris-Rips filtration\n\nJoin pairs within radius $\\varepsilon$; increase $\\varepsilon$ from 0. Nested **simplicial complexes** $R_\\varepsilon(X)$: edges, filled triangles, higher simplices. Distinguishes hollow loops from filled regions.\n\n::: {#7bfd06d3 .cell execution_count=2}\n``` {.python .cell-code}\nfrom itertools import combinations\n\n\ndef plot_edges(points, eps, ax, colors=None):\n    n = len(points)\n    dists = np.linalg.norm(points[:, None] - points[None, :], axis=-1)\n    for i, j in combinations(range(n), 2):\n        if dists[i, j] <= eps:\n            ax.plot(*zip(points[i], points[j]), color=\"tab:purple\", lw=0.5, alpha=0.5, zorder=1)\n    c = colors if colors is not None else \"black\"\n    ax.scatter(points[:, 0], points[:, 1], s=6, zorder=2, c=c, cmap=\"coolwarm\")\n    ax.set_title(f\"$\\\\varepsilon$ = {eps}\")\n    ax.set_xlim(-1.4, 1.4)\n    ax.set_ylim(-1.4, 1.4)\n    ax.set_aspect(\"equal\")\n    ax.set_xticks([])\n    ax.set_yticks([])\n\n\nfig, axes = plt.subplots(1, 4, figsize=(14, 4))\nfor ax, eps in zip(axes, [0.05, 0.15, 0.4, 0.8]):\n    plot_edges(X, eps, ax, colors=y)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-3-output-1.png){}\n:::\n:::\n\n\nBetti numbers at four scales (from `ripser`, evaluated at these $\\varepsilon$):\n\n- $\\varepsilon = 0.05$: $\\beta_0 = 120$, $\\beta_1 = 0$ — too fine.\n- $\\varepsilon = 0.15$: $\\beta_0 = 12$, $\\beta_1 = 5$ — transient micro-loops (noise).\n- $\\varepsilon = 0.4$: $\\beta_0 = 2$, $\\beta_1 = 1$ — ring loop + separate disk blob.\n- $\\varepsilon = 0.8$: $\\beta_0 = 1$, $\\beta_1 = 0$ — annulus filled; one component.\n\nSingle-scale snapshots mis-count loops; lifetime separates signal from noise.\n\n### Persistence diagram\n\nEach loop → (birth, death). Vertical distance from diagonal = lifetime.\n\n::: {#ac1e4f62 .cell execution_count=3}\n``` {.python .cell-code}\nfrom ripser import ripser\nfrom persim import plot_diagrams\n\ndgms = ripser(X, maxdim=1)[\"dgms\"]\nh1 = dgms[1]\nlifetimes = h1[:, 1] - h1[:, 0]\ntop = h1[np.argmax(lifetimes)]\n\nfig, ax = plt.subplots(figsize=(5, 5))\nplot_diagrams(dgms, ax=ax, show=False)\nax.annotate(\n    \"the hole\\n(disk/ring gap)\",\n    xy=(top[0], top[1]), xytext=(top[0] - 0.15, top[1] + 0.55),\n    arrowprops=dict(arrowstyle=\"->\", color=\"black\"), fontsize=9,\n)\nax.set_title(\"Persistence diagram (H0 = components, H1 = loops)\")\nplt.show()\n\nprint(f\"longest-lived H1 feature: born {top[0]:.3f}, dies {top[1]:.3f}, lifetime {lifetimes.max():.3f}\")\nprint(f\"next-longest H1 lifetime: {np.sort(lifetimes)[-2]:.3f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-4-output-1.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nlongest-lived H1 feature: born 0.291, dies 0.645, lifetime 0.354\nnext-longest H1 lifetime: 0.089\n```\n:::\n:::\n\n\nLongest $H_1$ lifetime ≈ 0.354 vs next-longest ≈ 0.089 (~4×). Labels never entered the computation.\n\n## Kernel SVM\n\nSame 240 points with labels. Task: find a class separator.\n\n### Linear SVM failure\n\n::: {#78c61fba .cell execution_count=4}\n``` {.python .cell-code}\nfrom sklearn.svm import LinearSVC\n\nlinear = LinearSVC(max_iter=10000)\nlinear.fit(X, y)\nprint(f\"linear SVM training accuracy: {linear.score(X, y):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlinear SVM training accuracy: 0.58\n```\n:::\n:::\n\n\nTraining accuracy 0.58 ≈ majority-class rate (140/240 ring points). Structural: ring wraps disk; no line separates classes.\n\n### Explicit feature lift\n\nMap $x = (x_1, x_2) \\mapsto \\phi(x) = (x_1, x_2, x_1^2 + x_2^2)$. Third coordinate = squared radius; separates inner disk from outer ring.\n\n::: {#9accd076 .cell execution_count=5}\n``` {.python .cell-code}\nfrom mpl_toolkits.mplot3d import Axes3D  # noqa: F401\nfrom sklearn.svm import LinearSVC\n\nZ = np.column_stack([X[:, 0], X[:, 1], X[:, 0] ** 2 + X[:, 1] ** 2])\n\nlifted = LinearSVC(max_iter=10000)\nlifted.fit(Z, y)\nprint(f\"linear SVM on phi(x), training accuracy: {lifted.score(Z, y):.2f}\")\nprint(f\"separating-plane coefficients (x1, x2, x1^2+x2^2): {lifted.coef_.round(3)}\")\n\nfig = plt.figure(figsize=(6, 5))\nax = fig.add_subplot(projection=\"3d\")\nax.scatter(*Z[y == 0].T, s=12, color=\"tab:blue\", label=\"inside\")\nax.scatter(*Z[y == 1].T, s=12, color=\"tab:red\", label=\"ring\")\nax.set_xlabel(\"$x_1$\")\nax.set_ylabel(\"$x_2$\")\nax.set_zlabel(\"$x_1^2+x_2^2$\")\nax.set_title(r\"$\\phi(x) = (x_1, x_2, x_1^2+x_2^2)$: now linearly separable\")\nax.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlinear SVM on phi(x), training accuracy: 1.00\nseparating-plane coefficients (x1, x2, x1^2+x2^2): [[0.016 0.02  2.53 ]]\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-6-output-2.png){}\n:::\n:::\n\n\nAccuracy 1.00. Dominant coefficient on $x_1^2+x_2^2$ (2.53 vs ~0.02 on $x_1, x_2$). Requires prior knowledge of radial structure.\n\n### RBF kernel\n\n**Kernel** $k(x, x') = \\langle \\phi(x), \\phi(x') \\rangle$ without materializing $\\phi$. RBF:\n\n$$\nk(x, x') = \\exp\\!\\left(-\\gamma \\lVert x - x' \\rVert^2\\right).\n$$\n\nCorresponds to infinite-dimensional $\\phi$; SVM uses only pairwise $k(x_i, x_j)$.\n\n::: {#460c795d .cell execution_count=6}\n``` {.python .cell-code}\nfrom sklearn.svm import SVC\n\nrbf = SVC(kernel=\"rbf\", C=1.0, gamma=2.0)\nrbf.fit(X, y)\nprint(f\"RBF-kernel SVM training accuracy: {rbf.score(X, y):.2f}\")\nprint(f\"support vectors used: {rbf.n_support_} (of {len(X)} points)\")\n\nxx, yy = np.meshgrid(np.linspace(-1.5, 1.5, 300), np.linspace(-1.5, 1.5, 300))\nzz = rbf.decision_function(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)\n\nfig, ax = plt.subplots(figsize=(5, 5))\nax.contourf(xx, yy, zz, levels=20, cmap=\"coolwarm\", alpha=0.55)\nax.contour(xx, yy, zz, levels=[0], colors=\"black\", linewidths=2)\nax.contour(xx, yy, zz, levels=[-1, 1], colors=\"black\", linewidths=0.8, linestyles=\"--\")\nax.scatter(*X[y == 0].T, s=16, color=\"tab:blue\", edgecolor=\"k\", linewidth=0.3)\nax.scatter(*X[y == 1].T, s=16, color=\"tab:red\", edgecolor=\"k\", linewidth=0.3)\nax.scatter(*X[rbf.support_].T, s=60, facecolors=\"none\", edgecolors=\"black\", linewidth=0.8, label=\"support vectors\")\nax.set_aspect(\"equal\")\nax.set_title(\"RBF-kernel SVM decision boundary\")\nax.legend(loc=\"upper right\", fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRBF-kernel SVM training accuracy: 1.00\nsupport vectors used: [8 9] (of 240 points)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](index_files/figure-html/cell-7-output-2.png){}\n:::\n:::\n\n\nRBF boundary ≈ circular (matches hand-built $\\phi$); 17 support vectors; no radial feature supplied.\n\n## Method comparison\n\n| | Persistent homology | Kernel SVM |\n|---|---|---|\n| Uses labels `y`? | No | Yes |\n| Object of study | Whole point cloud shape | One decision surface |\n| Scale | Every $\\varepsilon$ in diagram | One implicit scale ($\\gamma$) |\n| Expanded space | Filtration $R_\\varepsilon(X)$ | Implicit $\\phi(X)$ |\n| Output | (birth, death) pairs | $f(x) = \\text{sign}(\\sum_i \\alpha_i y_i k(x,x_i)+b)$ |\n| Hole in output | $H_1$ interval | Sign change of $f$ (unnamed) |\n| Stability | Stable to small point perturbations | Boundary sensitive to support vectors |\n\nAgreement on this dataset: class 0 inside hole, class 1 on rim → boundary and loop both ≈ circle $x_1^2+x_2^2 = r^2$, $r \\in (0.35, 1.0)$.\n\nShuffle labels: SVM still fits training data; persistence diagram unchanged.\n\nPersistent homology: unsupervised structure at all scales. SVM: supervised separation; undefined without labels.\n\n## Coordinate expansion\n\nBoth methods enrich coordinates instead of fighting curvature in the input space.\n\n**TDA**:\n\n$$\nX \\;\\longmapsto\\; R_\\varepsilon(X), \\qquad \\varepsilon: 0 \\to \\infty.\n$$\n\nAdds simplices (edges, triangles, …) across all scales; persistence diagram records the full sweep.\n\n**Kernel SVM**:\n\n$$\nx \\;\\longmapsto\\; \\phi(x) \\in \\mathcal{H}, \\qquad k(x, x') = \\langle \\phi(x), \\phi(x') \\rangle.\n$$\n\nAdds coordinates per point; cross-validation picks one kernel setting; only the boundary is kept.\n\nTDA keeps multi-scale structure because shape is the answer. SVM keeps one boundary because classification is the answer.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}