{
  "hash": "a1f3d06f675e1b33dd3db3cee2064ce2",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Six Views of PCA\"\nsubtitle: \"Maximum variance, maximum projected energy, minimum reconstruction error, best rank-k approximation, covariance eigenvectors, truncated SVD — one optimization problem, written six ways, with the bridge derived rather than asserted.\"\ndescription: \"PCA is not six algorithms. One projector identity turns minimum reconstruction error into maximum projected energy, the trace turns energy into variance, Ky Fan turns variance into eigenvectors, and the SVD closes the loop onto the best rank-k approximation. Then the chain is run on MovieLens genre ratings and a neutrophil metabolome.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-09-13\"\ncategories: [Linear Algebra, Machine Learning, Mathematics]\nimage: \"./cover.png\"\ntags: [PCA, SVD, eigendecomposition, low-rank approximation, dimensionality reduction, probabilistic PCA, Eckart-Young]\njupyter: pca-blog\nresources:\n  - cover.png\n  - data\nexecute:\n  warning: false\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: show\n    number-sections: true\n    fig-width: 8\n    fig-height: 4.2\n    fig-dpi: 150\n---\n\n\n![Six Views of PCA](./cover.png){fig-alt=\"Left: a centred 2D point cloud with the first principal direction drawn through it, each point joined to its projection by a perpendicular residual segment. Right: projected energy and residual sum of squares plotted against direction angle, two mirrored curves whose sum is flat.\"}\n\nOpen three references on PCA and you get three definitions. One says PCA finds the directions of largest variance. One says it finds the subspace minimising squared distance to the data. One says it is the truncated SVD of the centred matrix. Each states its own as *the* definition, and none of them mentions the other two.\n\nThat reads like three algorithms. It is one, and the bridge between the readings is about ten lines of algebra about a projection matrix. This post derives those lines, checks every step numerically, and then runs the chain end to end on two real matrices — user ratings from MovieLens, and a neutrophil metabolome — where the shape of the matrix decides which of the six readings is the one you can compute.\n\nTwo companion posts carry background. [The Directions a Matrix Refuses to Turn](../eigendecomposition/) is eigenvectors and eigenvalues from scratch. [The Matrix That Rotates, Stretches, and Rotates Again](../svd-rotate-stretch-rotate/) is the geometry of $U$, $\\Sigma$, and $V$.\n\n\n\n## Notation\n\nAll six views use one matrix and one basis.\n\n- $X \\in \\mathbb{R}^{n \\times d}$ — the data. Each of the $n$ rows is an observation, each of the $d$ columns a feature.\n- $X$ is **centred**: every column has mean zero. PCA without this step answers a different question, and @sec-assumptions says which one.\n- $W \\in \\mathbb{R}^{d \\times k}$ — the basis we are looking for, with $W^\\top W = I_k$. Its $k$ columns are orthonormal directions in feature space.\n- $Z = XW \\in \\mathbb{R}^{n \\times k}$ — the **projection**, or scores. Row $i$ holds the $k$ coordinates of observation $i$ in the new basis.\n- $\\hat X = XWW^\\top \\in \\mathbb{R}^{n \\times d}$ — the **reconstruction**. Back in the original $d$ features, but of rank at most $k$.\n- $P = WW^\\top \\in \\mathbb{R}^{d \\times d}$ — the orthogonal projector onto the span of $W$'s columns. $P^2 = P$ and $P^\\top = P$.\n\nProjection and reconstruction are different objects and get confused constantly. $Z$ is $n \\times k$ and lives in the small space. $\\hat X$ is $n \\times d$ and lives back in the big one, on a $k$-dimensional flat inside it.\n\n## The six views\n\nEach of these is a complete definition of PCA, and each one is what some textbook opens with.\n\n1. **Maximum variance.** Find the directions along which the projected observations spread out the most.\n2. **Maximum projected energy.** Find $W$ maximising $\\|XW\\|_F^2$, the total squared magnitude of the projected representation.\n3. **Minimum reconstruction error.** Find the $k$-dimensional subspace minimising $\\|X - XWW^\\top\\|_F^2$, the squared perpendicular distance from the data to the subspace.\n4. **Best rank-$k$ approximation.** Find the rank-$k$ matrix closest to $X$ in Frobenius norm.\n5. **Covariance eigendecomposition.** Take the leading eigenvectors of the sample covariance matrix.\n6. **Truncated SVD.** Take the leading right singular vectors of $X$.\n\nThey are not six independent problems. Views 1, 2, and 3 are one optimization problem written in three notations. Views 5 and 6 are two *routes to the solution* of that problem, not separate objectives. View 4 is the same optimum read as a statement about matrices rather than about subspaces. @sec-equivalence does the work of showing that.\n\n## Maximum variance\n\nStart with $k = 1$. A unit direction $w \\in \\mathbb{R}^d$ turns each observation $x_i$ into the single number $x_i^\\top w$, and because $X$ is centred those $n$ numbers already have mean zero. Their sample variance is\n\n$$\n\\operatorname{Var}(Xw) = \\frac{1}{n-1}\\sum_{i=1}^{n} (x_i^\\top w)^2 = \\frac{w^\\top X^\\top X w}{n-1}.\n$$\n\nMaximising that over unit $w$ is maximising the **Rayleigh quotient** of $X^\\top X$:\n\n$$\nw_1 = \\arg\\max_{w \\neq 0} \\frac{w^\\top X^\\top X w}{w^\\top w}.\n$$\n\nThe quotient measures how much $X^\\top X$ stretches a direction, with the length of $w$ divided out so that only the direction matters. Its maximum is the largest eigenvalue of $X^\\top X$, attained at the matching eigenvector — that is the Rayleigh–Ritz theorem, and @sec-kyfan sketches why.\n\nFor $k$ components, sum the variances of the $k$ projected coordinates. That sum is a trace:\n\n$$\n\\max_{W^\\top W = I_k} \\ \\operatorname{tr}\\!\\left(W^\\top \\frac{X^\\top X}{n-1} W\\right).\n$$\n\n$W^\\top X^\\top X W$ is $k \\times k$; its diagonal holds the $k$ projected variances (times $n-1$) and the trace adds them up. The constraint $W^\\top W = I_k$ is what stops the answer being $k$ copies of $w_1$.\n\n## Maximum projected energy\n\n**Energy** is the signal-processing name for a sum of squared magnitudes. A discrete signal $s[1], \\dots, s[T]$ has energy $\\sum_t |s[t]|^2$; a vector has energy $\\|v\\|_2^2$; a matrix has energy\n\n$$\n\\|Z\\|_F^2 = \\sum_{i=1}^{n}\\sum_{j=1}^{k} Z_{ij}^2 = \\sum_{i=1}^{n} \\|z_i\\|_2^2 .\n$$\n\nWith $Z = XW$ this is $\\|XW\\|_F^2$: add up the squared length of every observation's projected coordinate vector. It says how much of the data's squared magnitude survives the projection.\n\nThe reason the word transfers from signals to matrices is Parseval's identity. An orthonormal change of basis moves energy between coordinates but never creates or destroys it, so a *full* orthonormal $W$ with $k = d$ gives $\\|XW\\|_F^2 = \\|X\\|_F^2$ exactly. Truncating to $k < d$ throws some away, and PCA is the choice of which part to keep.\n\nFor centred $X$ the connection to variance is arithmetic. Column $j$ of $Z$ has mean zero, because the column means of $Z$ are the column means of $X$ times $W$, and those are zero. So $\\sum_i Z_{ij}^2 = (n-1)\\operatorname{Var}(Z_{:,j})$, and\n\n$$\n\\|XW\\|_F^2 = (n-1) \\sum_{j=1}^{k} \\operatorname{Var}(Z_{:,j}).\n$$\n\nProjected energy is total projected variance times the constant $n-1$. Maximising one maximises the other, over the same $W$, with the same maximiser. **Energy is the matrix-norm writing of view 1, not a second algorithm.** The only thing it adds is a norm that the next two views also speak.\n\n## Minimum reconstruction error\n\nProject, then come back: $Z = XW$ drops each observation to $k$ numbers, and $\\hat X = ZW^\\top = XWW^\\top$ lifts those numbers back into the original $d$ features. PCA in this reading is\n\n$$\n\\min_{W^\\top W = I_k} \\ \\|X - XWW^\\top\\|_F^2 .\n$$\n\nGeometrically, $\\hat x_i = WW^\\top x_i$ is the closest point to $x_i$ on the subspace spanned by $W$, and $x_i - \\hat x_i$ is perpendicular to that subspace. The objective is the total squared length of those perpendiculars. PCA is the $k$-dimensional flat through the origin — the origin because $X$ is centred — that the cloud sits closest to.\n\nThis is the one view that is not obviously about variance at all. It asks for a good *fit*, not a large *spread*. @sec-projector is the line that makes them the same question.\n\n## Best rank-$k$ approximation\n\nForget subspaces and ask for a matrix. Among all $n \\times d$ matrices $B$ of rank at most $k$, which is closest to $X$?\n\n$$\n\\min_{\\operatorname{rank}(B) \\le k} \\|X - B\\|_F^2 .\n$$\n\nThe **Eckart–Young–Mirsky theorem** answers it: the minimiser is the truncated SVD $B^\\star = U_k\\Sigma_kV_k^\\top$, and the minimum value is $\\sum_{i > k}\\sigma_i^2$, the energy in the singular values you dropped.\n\nThe distinction the two framings hide:\n\n- **Finding a subspace** returns a $k$-dimensional flat. Any $W$ whose columns span it is an equally valid answer, so $W$ is determined only up to a $k \\times k$ orthogonal rotation. The genuine object is the subspace.\n- **Approximating a matrix** returns one matrix $\\hat X$. It is unique as soon as $\\sigma_k > \\sigma_{k+1}$, and it does not change when you rotate $W$ inside its own span, because $WW^\\top$ does not change.\n\nSo $\\hat X$ is the invariant; the loadings are a chart on it. That is why two PCA implementations can report visibly different loadings and identical reconstructions.\n\n## Covariance eigendecomposition\n\nThe sample covariance of centred $X$ is\n\n$$\nS = \\frac{X^\\top X}{n-1} \\in \\mathbb{R}^{d \\times d},\n$$\n\nwith **$n-1$, not $n$**, in the denominator. The $n-1$ is Bessel's correction: one degree of freedom went into estimating the mean we subtracted when we centred. The $1/n$ convention is the maximum-likelihood estimate and is also in wide use — it scales every eigenvalue by $n/(n-1)$ and moves no eigenvector at all, so it changes no principal direction and no explained-variance *ratio*. It changes reported eigenvalues, which is enough reason to say which one you used.\n\n$S$ is symmetric positive semi-definite, so it has an orthonormal eigenbasis with non-negative eigenvalues:\n\n$$\nS = V\\Lambda V^\\top, \\qquad \\Lambda = \\operatorname{diag}(\\lambda_1 \\ge \\dots \\ge \\lambda_d \\ge 0).\n$$\n\nThe principal directions are the leading columns of $V$, and $\\lambda_j$ is the variance of the data along direction $v_j$ — set $W = v_j$ in the trace objective and read it off. Because $\\operatorname{tr}(S) = \\sum_j \\lambda_j$ is the total variance across all $d$ features, $\\lambda_j / \\sum_i \\lambda_i$ is the fraction of variance explained by component $j$.\n\n## Singular value decomposition\n\nThe thin SVD of the centred matrix is\n\n$$\nX = U\\Sigma V^\\top, \\qquad U \\in \\mathbb{R}^{n \\times r}, \\ \\Sigma \\in \\mathbb{R}^{r\\times r}, \\ V \\in \\mathbb{R}^{d \\times r},\n$$\n\nwith $r = \\min(n, d)$, $U^\\top U = V^\\top V = I_r$, and $\\Sigma$ diagonal with $\\sigma_1 \\ge \\dots \\ge \\sigma_r \\ge 0$. Then\n\n$$\nX^\\top X = V\\Sigma U^\\top U \\Sigma V^\\top = V\\Sigma^2V^\\top .\n$$\n\nThat is an eigendecomposition of $X^\\top X$ sitting in plain sight. Comparing it with $S = V\\Lambda V^\\top$:\n\n- the covariance eigenvectors **are** the right singular vectors of $X$;\n- $\\lambda_j = \\sigma_j^2/(n-1)$;\n- the left singular vectors scaled by the singular values, $U\\Sigma$, are the scores $Z$ for the full basis.\n\nEigenvectors and singular vectors are not the same kind of object — eigenvectors are defined for a square matrix by $Av = \\lambda v$, singular vectors come in left–right pairs for any shape via $Av_j = \\sigma_j u_j$ — and the identity $X^\\top X = V\\Sigma^2V^\\top$ is where they coincide for PCA: $V$ is simultaneously the right singular vectors of $X$ and the eigenvectors of the square matrix $X^\\top X$.\n\nSVD is the computational route for two reasons. Forming $X^\\top X$ squares the condition number, so directions that were merely badly scaled in $X$ become numerically indistinguishable in $X^\\top X$; and when $d \\gg n$ the covariance matrix is $d \\times d$ and singular, while the SVD never builds it. [The Matrix That Rotates, Stretches, and Rotates Again](../svd-rotate-stretch-rotate/) makes the precision argument in full.\n\nViews 5 and 6 are **solution methods**. They compute the answer to the optimization problem in views 1–3; they are not a seventh and eighth objective.\n\n## Equivalence {#sec-equivalence}\n\nSix statements, one optimum. Four steps join them.\n\n### From reconstruction to energy {#sec-projector}\n\n$P = WW^\\top$ is an orthogonal projector: $P^\\top = P$, and $P^2 = WW^\\top WW^\\top = W(W^\\top W)W^\\top = WW^\\top = P$ because $W^\\top W = I_k$. Expand the reconstruction error:\n\n$$\n\\|X - XP\\|_F^2\n= \\operatorname{tr}\\!\\left[(X - XP)^\\top (X - XP)\\right]\n= \\operatorname{tr}(X^\\top X) - 2\\operatorname{tr}(X^\\top X P) + \\operatorname{tr}(P X^\\top X P).\n$$\n\nThe last term collapses. Using the cyclic property of the trace and $P^2 = P$,\n\n$$\n\\operatorname{tr}(PX^\\top XP) = \\operatorname{tr}(X^\\top X P P) = \\operatorname{tr}(X^\\top X P),\n$$\n\nso two of the three terms cancel into one:\n\n$$\n\\|X - XWW^\\top\\|_F^2 = \\operatorname{tr}(X^\\top X) - \\operatorname{tr}(X^\\top X WW^\\top) = \\|X\\|_F^2 - \\|XW\\|_F^2 .\n$$\n\nThe last equality is the same cyclic move: $\\operatorname{tr}(X^\\top X WW^\\top) = \\operatorname{tr}(W^\\top X^\\top X W) = \\|XW\\|_F^2$.\n\nThis is the Pythagorean split. Every observation's squared length divides into the part the subspace keeps and the part it loses, with no cross term. And $\\|X\\|_F^2$ does not contain $W$:\n\n$$\n\\min_{W^\\top W = I} \\|X - XWW^\\top\\|_F^2\n\\iff\n\\max_{W^\\top W = I} \\|XW\\|_F^2 .\n$$\n\nFitting the data as closely as possible and capturing as much energy as possible are the same instruction, because the two quantities sum to a constant.\n\n### From energy to variance\n\nOne line, already used in @sec-projector:\n\n$$\n\\|XW\\|_F^2 = \\operatorname{tr}\\!\\left[(XW)^\\top(XW)\\right] = \\operatorname{tr}(W^\\top X^\\top X W) = (n-1)\\operatorname{tr}(W^\\top S W).\n$$\n\n$W^\\top X^\\top X W$ is the $k \\times k$ covariance of the scores, up to the factor $n-1$. Its trace is the total projected variance. So maximum energy is maximum projected variance, and the $(n-1)$ never affects the maximiser.\n\n### From variance to eigenvectors {#sec-kyfan}\n\nWhat maximises $\\operatorname{tr}(W^\\top A W)$ over $W^\\top W = I_k$, for symmetric $A$ with eigenvalues $\\lambda_1 \\ge \\dots \\ge \\lambda_d$?\n\nWrite $A = V\\Lambda V^\\top$ and set $M = V^\\top W$, which satisfies $M^\\top M = I_k$. Then\n\n$$\n\\operatorname{tr}(W^\\top A W) = \\operatorname{tr}(M^\\top \\Lambda M) = \\sum_{j=1}^{d} \\lambda_j \\, c_j,\n\\qquad c_j = \\sum_{l=1}^{k} M_{jl}^2 .\n$$\n\nThe weights $c_j$ are constrained: each $c_j \\in [0, 1]$ because $M$ has orthonormal columns, and $\\sum_j c_j = \\|M\\|_F^2 = k$. Maximising a weighted sum of the $\\lambda_j$ under \"budget $k$, at most $1$ each\" puts all of the budget on the $k$ largest eigenvalues. The maximum is $\\lambda_1 + \\dots + \\lambda_k$, attained when $W$ spans the leading $k$ eigenvectors. That is the Ky Fan theorem, and at $k = 1$ it is Rayleigh–Ritz.\n\nApplied to $A = X^\\top X$: the maximiser is $W = V_k$, the leading eigenvectors of $X^\\top X$, which are the leading eigenvectors of $S$.\n\n### From eigenvectors to the SVD\n\n$X^\\top X = V\\Sigma^2V^\\top$, so $V_k$ is the first $k$ right singular vectors of $X$ and $\\lambda_j = \\sigma_j^2/(n-1)$. The reconstruction at that optimum is\n\n$$\n\\hat X = XV_kV_k^\\top = U\\Sigma V^\\top V_kV_k^\\top = U_k\\Sigma_kV_k^\\top ,\n$$\n\nwhich is the truncated SVD, which is Eckart–Young's best rank-$k$ approximation. The loop closes: the subspace that fits the data best reconstructs it as the matrix that approximates it best.\n\n### The chain {#sec-chain}\n\n$$\n\\boxed{\n\\begin{aligned}\n\\min_{W}\\ \\|X - XWW^\\top\\|_F^2\n&\\iff \\max_{W}\\ \\|XW\\|_F^2\n\\iff \\max_{W}\\ \\operatorname{tr}(W^\\top X^\\top X W) \\\\[2pt]\n&\\iff W = V_k \\ \\text{(leading eigenvectors of } X^\\top X\\text{)} \\\\[2pt]\n&\\iff \\hat X = U_k\\Sigma_kV_k^\\top \\ \\text{(truncated SVD} = \\text{best rank-}k\\text{)}\n\\end{aligned}\n}\n$$\n\nRead left to right it is: fit, energy, variance, eigenvectors, singular vectors, low rank. Every arrow is an identity, not an approximation.\n\n### Assumptions {#sec-assumptions}\n\nThe chain holds under conditions, and each one is a real way to break it.\n\n- **$X$ is centred.** Without it, $X^\\top X/(n-1)$ is a second-moment matrix, not a covariance, and its leading eigenvector chases the mean. The reconstruction view is then fitting a subspace through the origin rather than through the data.\n- **Every entry is observed.** The projector identity needs a complete $X$. With missing cells there is no single $\\|X\\|_F^2$ to hold fixed and the equivalence fails; @sec-movielens is the case.\n- **The loss is Frobenius.** Eckart–Young also holds in the spectral norm with the same minimiser, but an $\\ell_1$ or Huber loss gives a different optimum and none of these identities.\n- **Feature scaling is fixed.** Rescaling a column rescales its contribution to every trace. Covariance PCA and correlation PCA are different questions with different answers, not two algorithms for one question.\n- **The spectrum has a gap at $k$.** If $\\sigma_k = \\sigma_{k+1}$, the optimal subspace is not unique.\n- **Signs and rotations are free.** $v_j$ and $-v_j$ are both valid; within a tied block, so is any rotation. Reconstructions are unique where loadings are not.\n\n## Geometry of the equivalence\n\nThe synthetic cloud used here: 200 draws of a scalar latent $t \\sim N(0,1)$, mapped to $(2.2t,\\ 0.9t)$ and perturbed by independent $N(0, 0.45^2)$ noise in both coordinates, then column-centred. It is synthetic, its generating process is one line of NumPy, and it stands in for any measurement pair where one underlying quantity drives both readings and the instrument adds isotropic noise — two sensors on one process, two assays of one sample. Two dimensions only, because the point is to draw the residuals.\n\n::: {#cell-fig-equivalence .cell fig-height='3.5' fig-width='9.2' execution_count=2}\n``` {.python .cell-code}\nn = 200\nlatent = rng.normal(size=n)\nX = np.column_stack([2.2 * latent, 0.9 * latent]) + rng.normal(scale=0.45, size=(n, 2))\nX = X - X.mean(axis=0)\n\nU, S, Vt = np.linalg.svd(X, full_matrices=False)\npc1 = Vt[0]\n\nthetas = np.linspace(0.0, np.pi, 3601)\ndirs = np.vstack([np.cos(thetas), np.sin(thetas)])\nproj = X @ dirs\nenergy = (proj**2).sum(axis=0)\nresid = ((X[:, None, :] - proj[:, :, None] * dirs.T[None, :, :]) ** 2).sum(axis=(0, 2))\ntotal = float((X**2).sum())\n\nfig, (ax_l, ax_r) = plt.subplots(\n    1, 2, figsize=(9.2, 3.5), gridspec_kw={\"width_ratios\": [1.15, 1.0]}\n)\n\nscores = X @ pc1\nfeet = np.outer(scores, pc1)\nax_l.scatter(X[:, 0], X[:, 1], s=14, color=MUTED, alpha=0.45, zorder=2)\nfor i in range(0, n, 3):\n    ax_l.plot(\n        [X[i, 0], feet[i, 0]], [X[i, 1], feet[i, 1]],\n        color=CORAL, lw=1.0, alpha=0.8, zorder=3,\n    )\nax_l.scatter(feet[:, 0], feet[:, 1], s=9, color=ACCENT, zorder=4)\nspan = np.array([scores.min(), scores.max()])\nax_l.plot(span * pc1[0], span * pc1[1], color=ACCENT, lw=1.8, zorder=5)\nax_l.set_aspect(\"equal\")\nax_l.set_xlabel(\"feature 1\")\nax_l.set_ylabel(\"feature 2\")\nax_l.set_title(\"Projection onto PC1, and what is left over\")\n\ndeg = np.degrees(thetas)\nax_r.plot(deg, energy, color=ACCENT, lw=1.8)\nax_r.plot(deg, resid, color=CORAL, lw=1.8)\nax_r.plot(deg, energy + resid, color=TEAL, lw=1.4, ls=\"--\")\nax_r.axvline(deg[energy.argmax()], color=MUTED, lw=0.9, ls=\":\")\nax_r.set_xlabel(\"direction angle (degrees)\")\nax_r.set_ylabel(\"sum of squares\")\nax_r.set_xlim(0, 180)\nax_r.set_ylim(0, total * 1.30)\n\n# Label the curves on the curves: a legend box has nowhere to sit here.\nax_r.text(deg[energy.argmax()], total * 1.05, r\"energy $\\|Xw\\|_F^2$\",\n          color=ACCENT, fontsize=8, ha=\"center\")\nax_r.text(deg[resid.argmax()], total * 1.05, r\"residual $\\|X-Xww^\\top\\|_F^2$\",\n          color=CORAL, fontsize=8, ha=\"center\")\nax_r.text(170, total * 0.92, r\"sum $=\\|X\\|_F^2$\",\n          color=TEAL, fontsize=8, ha=\"right\", va=\"bottom\")\nax_r.set_title(\"One curve is the other, upside down\")\n\nfig.tight_layout(pad=1.1)\nplt.show()\n\nprint(f\"energy peaks at {deg[energy.argmax()]:.2f} deg\")\nprint(f\"residual bottoms at {deg[resid.argmin()]:.2f} deg\")\nprint(f\"sum varies by {np.ptp(energy + resid):.2e} across the sweep\")\nprint(f\"||X||_F^2 = {total:.4f}\")\n```\n\n::: {.cell-output .cell-output-display}\n![Left: the centred cloud with PC1 and, for a sample of observations, the perpendicular residual joining each point to its projection. Right: projected energy and residual sum of squares against direction angle, with their constant sum.](index_files/figure-html/fig-equivalence-output-1.png){#fig-equivalence fig-alt='Two panels. The left shows a 2D elliptical point cloud with a line through its long axis and short perpendicular segments from points to that line. The right shows two mirrored curves against angle, one peaking where the other bottoms out, and a flat line at their sum.'}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nenergy peaks at 22.15 deg\nresidual bottoms at 22.15 deg\nsum varies by 2.84e-12 across the sweep\n||X||_F^2 = 903.0973\n```\n:::\n:::\n\n\nThe two curves peak and bottom out at the same angle, 22.15 degrees, and their sum is flat to $2.84\\times10^{-12}$ — floating-point noise on a total of 903.0973. That flat line is the identity of @sec-projector. Maximising the purple curve and minimising the orange one are the same search, because the dashed line does not move.\n\n## The six views as a diagram\n\nEach edge is the identity that carries one view into the next.\n\n\n```{mermaid}\n%%| label: fig-map\n%%| fig-cap: \"The six views and the identity joining each pair. Views 1 to 3 are one objective in three notations; views 5 and 6 are routes to its solution; view 4 is the same optimum read as a statement about matrices.\"\nflowchart TD\n  R[\"<b>Minimum<br/>reconstruction error</b><br/>min ‖X − XWWᵀ‖²_F\"]\n  E[\"<b>Maximum<br/>projected energy</b><br/>max ‖XW‖²_F\"]\n  V[\"<b>Maximum<br/>variance</b><br/>max tr(WᵀXᵀXW)\"]\n  G[\"<b>Covariance<br/>eigenvectors</b><br/>S = VΛVᵀ\"]\n  D[\"<b>Truncated<br/>SVD</b><br/>X = UΣVᵀ\"]\n  L[\"<b>Best rank-k<br/>approximation</b><br/>X̂ = U_kΣ_kV_kᵀ\"]\n  R -->|\"‖X‖²_F − ‖XW‖²_F<br/>projector identity\"| E\n  E -->|\"‖XW‖²_F = tr(WᵀXᵀXW)<br/>cyclic trace\"| V\n  V -->|\"Ky Fan<br/>W = V_k\"| G\n  G -->|\"XᵀX = VΣ²Vᵀ<br/>λ = σ²/(n−1)\"| D\n  D -->|\"Eckart–Young–Mirsky\"| L\n```\n\n\n## Numerical demonstration\n\nThe claims of @sec-equivalence are checkable on the same synthetic cloud. The code is NumPy throughout, so the algebra stays visible; `assert` statements fail the render rather than the reader if a claim stops holding.\n\n::: {#demo .cell execution_count=3}\n``` {.python .cell-code}\nlam, vec = np.linalg.eigh(X.T @ X / (n - 1))\nlam, vec = lam[::-1], vec[:, ::-1]          # eigh returns ascending order\n\nprint(\"singular values of X        \", S)\nprint(\"eigenvalues of S = XtX/(n-1)\", lam)\nprint(\"sigma^2 / (n-1)             \", S**2 / (n - 1))\nprint(\"eigen PC1\", vec[:, 0], \" svd PC1\", Vt[0])\nprint(f\"|cos angle between them| = {abs(vec[:, 0] @ Vt[0]):.12f}\")\n\n# 1. Eigendecomposition and SVD give the same direction, up to sign.\nassert np.allclose(lam, S**2 / (n - 1))\nassert np.isclose(abs(vec[:, 0] @ Vt[0]), 1.0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsingular values of X         [29.4519  5.9733]\neigenvalues of S = XtX/(n-1) [4.3589 0.1793]\nsigma^2 / (n-1)              [4.3589 0.1793]\neigen PC1 [-0.9262 -0.3771]  svd PC1 [0.9262 0.3771]\n|cos angle between them| = 1.000000000000\n```\n:::\n:::\n\n\nThe two routes agree to twelve decimal places on the direction, and disagree on its sign: `eigh` returned $-v_1$ where `svd` returned $+v_1$. Both are correct, since $v$ and $-v$ span the same line, which is why the check is on $|\\cos|$ rather than on the vectors.\n\nNext, the sweep: does PC1 win the variance contest and the energy contest, and are they the same contest?\n\n::: {#demo-sweep .cell execution_count=4}\n``` {.python .cell-code}\nbest_dir = dirs[:, energy.argmax()]\nvar_sweep = proj.var(axis=0, ddof=1)\n\nprint(f\"largest projected variance over the sweep : {var_sweep.max():.10f}\")\nprint(f\"leading eigenvalue of S                   : {lam[0]:.10f}\")\nprint(f\"argmax energy vs argmax variance (deg)    : \"\n      f\"{deg[energy.argmax()]:.3f} vs {deg[var_sweep.argmax()]:.3f}\")\nprint(f\"|cos| between sweep winner and PC1        : {abs(best_dir @ Vt[0]):.10f}\")\n\n# 2 and 3. The same direction maximises projected variance and projected energy,\n#          and it is PC1. Compared as angles, since the curves are flat at the\n#          peak and a grid of 3,601 directions resolves it only to 0.05 degrees.\nstep = deg[1] - deg[0]\nassert abs(deg[energy.argmax()] - deg[var_sweep.argmax()]) <= step\nassert abs(deg[energy.argmax()] - deg[resid.argmin()]) <= step\nassert np.isclose(abs(best_dir @ Vt[0]), 1.0, atol=1e-6)\nassert np.isclose(var_sweep.max(), lam[0], rtol=1e-6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlargest projected variance over the sweep : 4.3588788685\nleading eigenvalue of S                   : 4.3588788832\nargmax energy vs argmax variance (deg)    : 22.150 vs 22.150\n|cos| between sweep winner and PC1        : 0.9999999983\n```\n:::\n:::\n\n\nA 3,601-point sweep of directions picks the same angle for maximum energy, maximum variance, and minimum residual, and that angle is PC1 to within the sweep's own resolution.\n\nLast, the rank ladder and the Eckart–Young claim.\n\n::: {#demo-rank .cell execution_count=5}\n``` {.python .cell-code}\nfor k in (1, 2):\n    W = Vt[:k].T\n    recon = float(np.sum((X - X @ W @ W.T) ** 2))\n    kept = float(np.sum((X @ W) ** 2))\n    print(f\"k={k}: reconstruction {recon:9.4f}   energy kept {kept:9.4f}   \"\n          f\"sum {recon + kept:9.4f}\")\n\nsvd_rank1 = (U[:, :1] * S[:1]) @ Vt[:1]     # truncated SVD\npca_rank1 = X @ Vt[:1].T @ Vt[:1]           # PCA reconstruction\nprint(f\"||X||_F^2 = {total:.4f}, sum of squared singular values = {(S**2).sum():.4f}\")\nprint(f\"max |truncated SVD - PCA rank-1| = {np.abs(svd_rank1 - pca_rank1).max():.2e}\")\n\n# 4. Reconstruction error falls from rank 1 to rank 2.\n# 5. Truncated SVD and PCA give the same rank-1 reconstruction.\nerr1 = np.sum((X - X @ Vt[:1].T @ Vt[:1]) ** 2)\nerr2 = np.sum((X - X @ Vt[:2].T @ Vt[:2]) ** 2)\nassert err1 > err2\nassert np.isclose(err2, 0.0, atol=1e-20)    # k = d recovers X exactly\nassert np.allclose(svd_rank1, pca_rank1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nk=1: reconstruction   35.6804   energy kept  867.4169   sum  903.0973\nk=2: reconstruction    0.0000   energy kept  903.0973   sum  903.0973\n||X||_F^2 = 903.0973, sum of squared singular values = 903.0973\nmax |truncated SVD - PCA rank-1| = 3.25e-15\n```\n:::\n:::\n\n\nReconstruction error drops from 35.6804 at rank 1 to zero at rank 2, since $k = d = 2$ leaves nothing to discard, and energy kept climbs from 867.4169 to the full 903.0973. The two numbers add to $\\|X\\|_F^2$ on both rows. Truncated SVD and PCA agree to $3.25\\times10^{-15}$, which is the machine, not the mathematics.\n\nOne cross-check against a library, with the derivation left in NumPy:\n\n::: {#demo-sklearn .cell execution_count=6}\n``` {.python .cell-code}\nfrom sklearn.decomposition import PCA\n\nsk = PCA(n_components=2).fit(X)\nprint(\"sklearn components (rows)  \", sk.components_)\nprint(\"sklearn explained variance \", sk.explained_variance_)\nprint(\"our eigenvalues            \", lam)\nassert np.allclose(sk.explained_variance_, lam)\nassert np.isclose(abs(sk.components_[0] @ Vt[0]), 1.0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsklearn components (rows)   [[ 0.9262  0.3771]\n [-0.3771  0.9262]]\nsklearn explained variance  [4.3589 0.1793]\nour eigenvalues             [4.3589 0.1793]\n```\n:::\n:::\n\n\n## Tech: MovieLens genre ratings {#sec-movielens}\n\n### The data\n\n- **Provenance.** GroupLens ml-100k: 100,000 ratings from 943 users on 1,682 films, collected through the MovieLens site between September 1997 and April 1998 and released for research.\n- **Collector and motive.** The GroupLens lab at the University of Minnesota, building and evaluating recommender algorithms. Ratings are volunteered by people choosing what to rate, so they are not a random sample of opinions.\n- **What this post uses.** For each user, the mean rating they gave in each of the 12 most widely rated genres, keeping users with at least three rated films in every one of those genres. That is a complete $313 \\times 12$ table with no missing cells.\n- **Why not the ratings matrix itself.** 93.7% of the user-by-film grid is empty, and the equivalences need every entry observed (@sec-assumptions). The largest fully observed user-by-film rectangle inside ml-100k is 30 users by 28 films — measured by peeling, not guessed. Aggregating to genres is how a complete matrix gets built at all.\n- **What being wrong costs.** Nothing clinical. A misread taste axis ships a worse recommendation.\n\n::: {#movielens-load .cell execution_count=7}\n``` {.python .cell-code}\ngenres = pd.read_csv(DATA / \"movielens_genres.csv\", index_col=0)\nmanifest = json.loads((DATA / \"manifest.json\").read_text())[\"movielens\"]\n\nG = genres.to_numpy()\nprint(f\"table: {G.shape[0]} users x {G.shape[1]} genres, \"\n      f\"missing cells: {int(np.isnan(G).sum())}\")\nprint(f\"full grid density: {manifest['grid_density']:.4f}\")\nprint(f\"largest complete user-by-film block: \"\n      f\"{manifest['largest_complete_film_block'][0]} x \"\n      f\"{manifest['largest_complete_film_block'][1]}\")\nprint(\"genres:\", \", \".join(genres.columns))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntable: 313 users x 12 genres, missing cells: 0\nfull grid density: 0.0630\nlargest complete user-by-film block: 30 x 28\ngenres: Action, Adventure, Children's, Comedy, Crime, Drama, Horror, Mystery, Romance, Sci-Fi, Thriller, War\n```\n:::\n:::\n\n\n### The upstream ask\n\nA recommender team wants to know how many taste dimensions the catalogue really has. Twelve genre columns is the measurement; the question is how many independent axes are hiding behind them, because that number sets how small a user profile can get before recommendations degrade.\n\nThat ask is well-posed for PCA and for nothing fancier. It asks for directions of largest spread and for how fast the spread runs out — which is views 1 and 3, and the answer is a spectrum.\n\n### Running the chain\n\n$n = 313$ and $d = 12$, so $n \\gg d$: the covariance matrix is a comfortable $12 \\times 12$, full rank, and both routes are available. That is the regime where the choice between eigendecomposition and SVD is about precision, not possibility.\n\n::: {#movielens-pca .cell execution_count=8}\n``` {.python .cell-code}\nGc = G - G.mean(axis=0)                       # centre the columns\nUg, Sg, Vtg = np.linalg.svd(Gc, full_matrices=False)\nlam_g = Sg**2 / (Gc.shape[0] - 1)\neig_g, vec_g = np.linalg.eigh(Gc.T @ Gc / (Gc.shape[0] - 1))\n\nprint(f\"cov route top eigenvalue {eig_g[-1]:.10f}\")\nprint(f\"svd route sigma^2/(n-1)  {lam_g[0]:.10f}\")\nprint(f\"|cos| between the two PC1s: {abs(vec_g[:, -1] @ Vtg[0]):.12f}\")\nprint(\"explained variance ratio:\", (lam_g / lam_g.sum())[:4].round(4))\nprint(\"cumulative              :\", np.cumsum(lam_g / lam_g.sum())[:4].round(4))\n\nfor k in (1, 2, 3, 4):\n    W = Vtg[:k].T\n    rel = np.sum((Gc - Gc @ W @ W.T) ** 2) / np.sum(Gc**2)\n    kept = np.sum((Gc @ W) ** 2) / np.sum(Gc**2)\n    print(f\"  rank {k}: relative reconstruction error {rel:.4f}, energy kept {kept:.4f}\")\n\nassert np.isclose(eig_g[-1], lam_g[0])\nassert np.isclose(abs(vec_g[:, -1] @ Vtg[0]), 1.0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ncov route top eigenvalue 2.1906723037\nsvd route sigma^2/(n-1)  2.1906723037\n|cos| between the two PC1s: 1.000000000000\nexplained variance ratio: [0.6566 0.0813 0.0649 0.0534]\ncumulative              : [0.6566 0.7379 0.8028 0.8563]\n  rank 1: relative reconstruction error 0.3434, energy kept 0.6566\n  rank 2: relative reconstruction error 0.2621, energy kept 0.7379\n  rank 3: relative reconstruction error 0.1972, energy kept 0.8028\n  rank 4: relative reconstruction error 0.1437, energy kept 0.8563\n```\n:::\n:::\n\n\nBoth routes return the same leading eigenvalue and the same direction. Relative reconstruction error and fraction of energy kept sum to 1 at every rank, which is @sec-projector again, now on a $313 \\times 12$ matrix instead of a drawing.\n\nThe first component takes 65.66% of the variance. That looks like a decisive answer — one dominant taste axis — until you read its loadings.\n\n::: {#movielens-pc1 .cell execution_count=9}\n``` {.python .cell-code}\norder = np.argsort(-np.abs(Vtg[0]))\nprint(\"PC1 loadings, largest magnitude first:\")\nfor j in order:\n    print(f\"   {genres.columns[j]:12s} {Vtg[0][j]:+.3f}\")\n\npc1_scores = Gc @ Vtg[0]\nuser_mean = G.mean(axis=1)\nr = float(np.corrcoef(pc1_scores, user_mean)[0, 1])\nprint(f\"\\ncorr(PC1 score, that user's mean rating over all 12 genres) = {r:.4f}\")\nassert abs(r) > 0.99\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPC1 loadings, largest magnitude first:\n   Adventure    +0.316\n   Horror       +0.313\n   Action       +0.308\n   Children's   +0.306\n   Sci-Fi       +0.287\n   Thriller     +0.284\n   War          +0.281\n   Mystery      +0.278\n   Romance      +0.276\n   Comedy       +0.272\n   Crime        +0.269\n   Drama        +0.267\n\ncorr(PC1 score, that user's mean rating over all 12 genres) = 0.9999\n```\n:::\n:::\n\n\nEvery loading is positive and they are nearly equal, between 0.267 and 0.316. A direction with equal positive weight on every genre is the all-ones direction, and projecting a user onto it measures their average rating. The correlation between PC1 score and the user's own mean rating is 0.9999.\n\n**PC1 is not a taste. It is rating generosity.** Some users give fours and fives to every genre, some give twos and threes, and that single habit is two thirds of the variance in the table. The upstream ask was about taste dimensions, and the largest-variance direction is a property of the rating scale.\n\n### Downstream impact\n\nThe fix follows from @sec-assumptions: centring choice is part of the question. Remove each user's own mean before centring the columns, and the generosity axis is gone by construction.\n\n::: {#movielens-double-centred .cell execution_count=10}\n``` {.python .cell-code}\nR = G - G.mean(axis=1, keepdims=True)         # remove each user's own level\nRc = R - R.mean(axis=0)                       # then centre the columns\nUr, Sr, Vtr = np.linalg.svd(Rc, full_matrices=False)\nlam_r = Sr**2 / (Rc.shape[0] - 1)\n\nprint(f\"rank of the row-centred table: {np.linalg.matrix_rank(Rc)} (was {np.linalg.matrix_rank(Gc)})\")\nprint(\"explained variance ratio:\", (lam_r / lam_r.sum())[:4].round(4))\nprint(\"cumulative              :\", np.cumsum(lam_r / lam_r.sum())[:4].round(4))\nprint(f\"corr(new PC1, user mean rating) = {np.corrcoef(Rc @ Vtr[0], user_mean)[0, 1]:+.4f}\")\n\ntop = np.argsort(-np.abs(Vtr[0]))[:5]\nprint(\"\\nnew PC1 loadings, largest magnitude first:\")\nfor j in top:\n    print(f\"   {genres.columns[j]:12s} {Vtr[0][j]:+.3f}\")\n\nassert abs(float(np.corrcoef(Rc @ Vtr[0], user_mean)[0, 1])) < 0.05\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrank of the row-centred table: 11 (was 12)\nexplained variance ratio: [0.2353 0.188  0.1582 0.1293]\ncumulative              : [0.2353 0.4233 0.5816 0.7109]\ncorr(new PC1, user mean rating) = -0.0168\n\nnew PC1 loadings, largest magnitude first:\n   Children's   -0.717\n   Horror       +0.571\n   Crime        +0.248\n   Thriller     +0.156\n   Mystery      +0.153\n```\n:::\n:::\n\n\nThree things changed, and each one is a decision the team has to make.\n\n- **The rank dropped from 12 to 11.** Subtracting each row's mean puts every row in the space orthogonal to the all-ones vector, which costs exactly one dimension. That is not a bug; the generosity direction was a real dimension of the original table and it has been deliberately removed.\n- **The answer to the ask changed.** With column centring alone, one component covered 65.66% and the report was \"one axis, and it is not taste\". After row centring, the leading component takes 23.53%, two take 42.33%, and four take 71.09%. A user taste profile needs about four numbers, not one.\n- **PC1 became a taste.** Children's $-0.717$ against Horror $+0.571$: a family-viewing axis with the two ends of the catalogue at the two ends of the component. Correlation with rating generosity is $-0.0168$.\n\nThe wider consequence is the assumption that forced the genre aggregation in the first place. On the raw user-by-film matrix, 93.7% of entries are missing, so $\\|X\\|_F^2$ is not a fixed quantity and the projector identity of @sec-projector has nothing to hold constant. Minimum reconstruction error over the *observed* entries and maximum variance stop being the same problem. That gap is why production recommenders fit a factorization to the observed cells directly — alternating least squares, or gradient descent on the observed residuals — instead of running PCA on a filled-in matrix.\n\n::: {#cell-fig-movielens .cell fig-height='3.6' fig-width='8.6' execution_count=11}\n``` {.python .cell-code}\nfig, (ax_a, ax_b) = plt.subplots(1, 2, figsize=(8.6, 3.6))\n\nks = np.arange(1, 13)\nax_a.plot(ks, np.cumsum(lam_g / lam_g.sum()), \"o-\", color=ACCENT, ms=4,\n          label=\"column-centred\")\nax_a.plot(ks, np.cumsum(lam_r / lam_r.sum()), \"s-\", color=CORAL, ms=4,\n          label=\"row- then column-centred\")\nax_a.set_xlabel(\"components kept\")\nax_a.set_ylabel(\"cumulative explained variance\")\nax_a.set_ylim(0, 1.02)\nax_a.legend(frameon=False, fontsize=8, loc=\"lower right\")\nax_a.set_title(\"What centring decides\")\n\nax_b.scatter(user_mean, pc1_scores, s=16, color=TEAL, alpha=0.6)\nax_b.set_xlabel(\"user's mean rating across 12 genres\")\nax_b.set_ylabel(\"PC1 score\")\nax_b.set_title(f\"PC1 is generosity (r = {r:.4f})\")\n\nfig.tight_layout(pad=1.1)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Left: cumulative explained variance for the two centrings, with the generosity axis present and removed. Right: PC1 score against the user's own mean rating under column centring only.](index_files/figure-html/fig-movielens-output-1.png){#fig-movielens fig-alt='Two panels. The left plots two cumulative explained-variance curves against number of components; the column-centred curve starts near 0.66 and the row-centred curve starts near 0.24. The right is a tight straight-line scatter of PC1 score against mean rating.'}\n:::\n:::\n\n\n## Biotech: neutrophil metabolomes\n\n### The data\n\n- **Provenance.** Li et al. (2023), Metabolomics Workbench study ST002477, released CC BY 4.0. LC-MS peak areas for 285 metabolites measured in neutrophils isolated from 75 people, tagged Control (19), Mild (30), or Severe (26) COVID-19.\n- **Collector and motive.** The authors isolated neutrophils and extracted roughly two million cells per person, wanting the metabolic state of the cell that kills rather than of plasma.\n- **What this post uses.** The full $75 \\times 285$ peak-area matrix, on $\\log(1+x)$ with each metabolite divided by its interquartile range — the same transform as [Neutrophil Metabolomes as a Matrix](../neutrophil-metabolome-axis/), which clusters this file, so the numbers here line up with that post's.\n- **What this post asks of it.** Whether the direction of largest variance in the run tracks disease severity.\n- **What being wrong costs.** A dominant axis that turns out to be a batch or a run-order artefact invalidates every differential-abundance test computed downstream of it. The test does not fail loudly; it reports metabolites.\n- **Why PCA.** Peak areas are relative ion intensities, not counts and not fluxes. PCA asks for the direction of largest spread and assumes nothing about labels, which is what a quality-control gate needs.\n\n::: {#metabolome-load .cell execution_count=12}\n``` {.python .cell-code}\nabund = pd.read_csv(DATA / \"abundances.tsv\", sep=\"\\t\", index_col=0)\nmeta = pd.read_csv(DATA / \"samples.tsv\", sep=\"\\t\")\nassert list(abund.columns) == list(meta[\"sample_id\"])\n\nXm_raw = abund.to_numpy(dtype=np.float64).T\nlabels = meta[\"group\"].to_numpy()\n\nt = np.log1p(Xm_raw)\nmedian = np.median(t, axis=0)\niqr = np.subtract(*np.percentile(t, [75, 25], axis=0))\niqr = np.where(iqr == 0.0, 1.0, iqr)\nZm = (t - median) / iqr\nXm = Zm - Zm.mean(axis=0)\n\nn_m, d_m = Xm.shape\nprint(f\"matrix: {n_m} samples x {d_m} metabolites\")\nprint(\"groups:\", {g: int((labels == g).sum()) for g in (\"Control\", \"Mild\", \"Severe\")})\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nmatrix: 75 samples x 285 metabolites\ngroups: {'Control': 19, 'Mild': 30, 'Severe': 26}\n```\n:::\n:::\n\n\n### The upstream ask\n\nBefore any metabolite-by-metabolite test, someone has to answer a quality-control question: is the biggest source of variation in this run the biology, or the machine? Run order, extraction batch, and column drift all produce large coherent shifts across hundreds of metabolites, and a per-metabolite test cannot tell them from signal.\n\nPCA is the standard gate because it answers without being told the labels. Take the direction of largest variance, colour the scores by the label afterwards, and see whether the two agree. If the leading component tracks batch rather than severity, the tests downstream are measuring the machine.\n\n### Running the chain\n\nThe shape decides the method here. $n = 75$ and $d = 285$, so $n \\ll d$ and the covariance matrix is $285 \\times 285$ with rank at most $n - 1 = 74$. It is singular by construction, and 211 of its eigenvalues are zero not because the data says so but because there are not enough samples for them to be anything else.\n\n::: {#metabolome-pca .cell execution_count=13}\n``` {.python .cell-code}\nUm, Sm, Vtm = np.linalg.svd(Xm, full_matrices=False)\nlam_m = Sm**2 / (n_m - 1)\n\nprint(f\"rank(X) = {np.linalg.matrix_rank(Xm)}, min(n, d) = {min(n_m, d_m)}, n - 1 = {n_m - 1}\")\nprint(f\"non-negligible singular values: {int((Sm > 1e-9 * Sm[0]).sum())} of {len(Sm)}\")\n\ncov = Xm.T @ Xm / (n_m - 1)\neig_m, vec_m = np.linalg.eigh(cov)\nprint(f\"covariance matrix is {cov.shape[0]} x {cov.shape[1]}\")\nprint(f\"cov route top eigenvalue {eig_m[-1]:.10f}\")\nprint(f\"svd route sigma^2/(n-1)  {lam_m[0]:.10f}\")\nprint(f\"|cos| between the two PC1s: {abs(vec_m[:, -1] @ Vtm[0]):.12f}\")\nprint(\"explained variance ratio:\", (lam_m / lam_m.sum())[:4].round(4))\n\nassert np.linalg.matrix_rank(Xm) == n_m - 1\nassert np.isclose(eig_m[-1], lam_m[0])\nassert np.isclose(abs(vec_m[:, -1] @ Vtm[0]), 1.0)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nrank(X) = 74, min(n, d) = 75, n - 1 = 74\nnon-negligible singular values: 74 of 75\ncovariance matrix is 285 x 285\ncov route top eigenvalue 47.4693303238\nsvd route sigma^2/(n-1)  47.4693303238\n|cos| between the two PC1s: 1.000000000000\nexplained variance ratio: [0.2073 0.1136 0.0596 0.055 ]\n```\n:::\n:::\n\n\nBoth routes still agree — the chain does not care that the matrix is wide. What changes is cost and conditioning: the covariance route builds a $285 \\times 285$ matrix to extract at most 74 useful directions from it, and squares the condition number on the way. The SVD never forms it. This is the regime where view 6 stops being a convenience and becomes the only route worth taking.\n\n::: {#metabolome-scores .cell execution_count=14}\n``` {.python .cell-code}\nscores_m = Xm @ Vtm[:2].T\nseverity = np.select([labels == \"Control\", labels == \"Mild\"], [0.0, 1.0], 2.0)\ncorr_sev = float(np.corrcoef(scores_m[:, 0], severity)[0, 1])\n\nprint(f\"PC1 {lam_m[0] / lam_m.sum():.1%} of variance, \"\n      f\"PC2 {lam_m[1] / lam_m.sum():.1%}, \"\n      f\"first two together {np.cumsum(lam_m / lam_m.sum())[1]:.1%}\")\nfor g in (\"Control\", \"Mild\", \"Severe\"):\n    s = scores_m[labels == g, 0]\n    print(f\"  {g:8s} PC1 mean {s.mean():+6.2f}  sd {s.std():5.2f}\")\nprint(f\"corr(PC1 score, severity coded 0/1/2) = {corr_sev:.4f}\")\n\nfor k in (1, 2, 5, 10, 74):\n    W = Vtm[:k].T\n    rel = np.sum((Xm - Xm @ W @ W.T) ** 2) / np.sum(Xm**2)\n    print(f\"  rank {k:3d}: relative reconstruction error {rel:.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPC1 20.7% of variance, PC2 11.4%, first two together 32.1%\n  Control  PC1 mean  -6.95  sd  7.74\n  Mild     PC1 mean  +1.75  sd  5.37\n  Severe   PC1 mean  +3.06  sd  3.13\ncorr(PC1 score, severity coded 0/1/2) = 0.5363\n  rank   1: relative reconstruction error 0.7927\n  rank   2: relative reconstruction error 0.6791\n  rank   5: relative reconstruction error 0.5156\n  rank  10: relative reconstruction error 0.3571\n  rank  74: relative reconstruction error 0.0000\n```\n:::\n:::\n\n\nPC1 takes 20.7% and PC2 11.4%, so the first two components together carry 32.1% — a spectrum that decays slowly, which is what 285 correlated metabolites on 75 samples usually looks like. The group means do separate along PC1: Control at $-6.95$, Mild at $+1.75$, Severe at $+3.06$, correlating 0.5363 with severity coded 0/1/2.\n\n::: {#cell-fig-metabolome .cell fig-height='3.6' fig-width='8.6' execution_count=15}\n``` {.python .cell-code}\nfig, (ax_s, ax_p) = plt.subplots(1, 2, figsize=(8.6, 3.6))\n\n# All d eigenvalues of the covariance, not the n kept by the thin SVD, so the\n# 211 that are zero for want of samples are on the page.\nspectrum = eig_m[::-1]\nfloor = spectrum[: n_m - 1].min() * 1e-2\nax_s.semilogy(np.arange(1, d_m + 1), np.maximum(spectrum, floor),\n              color=ACCENT, lw=1.5)\nax_s.axvline(n_m - 1, color=CORAL, lw=1.0, ls=\"--\")\nax_s.annotate(f\"rank {n_m - 1} = n − 1\", xy=(n_m + 8, spectrum[0] * 0.15),\n              color=CORAL, fontsize=8)\nax_s.set_ylim(floor * 0.5, spectrum[0] * 3)\nax_s.set_xlabel(\"component index\")\nax_s.set_ylabel(\"eigenvalue (log scale)\")\nax_s.set_title(f\"{d_m} features, {n_m - 1} directions\")\n\nCOLOURS = {\"Control\": TEAL, \"Mild\": GOLD, \"Severe\": CORAL}\nfor g in (\"Control\", \"Mild\", \"Severe\"):\n    sel = labels == g\n    ax_p.scatter(scores_m[sel, 0], scores_m[sel, 1], s=26,\n                 color=COLOURS[g], alpha=0.85, label=g)\nax_p.set_xlabel(f\"PC1 ({lam_m[0] / lam_m.sum():.1%})\")\nax_p.set_ylabel(f\"PC2 ({lam_m[1] / lam_m.sum():.1%})\")\nax_p.legend(frameon=True, framealpha=0.9, edgecolor=RULE, fontsize=8,\n            loc=\"lower left\", scatterpoints=1)\nax_p.set_title(\"Scores, coloured after the fact\")\n\nfig.tight_layout(pad=1.1)\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Left: all 285 covariance eigenvalues, cut off at 74 by the sample count. Eigenvalues past 74 are zero and are drawn at a floor so the log axis can hold them. Right: the 75 samples on PC1 and PC2, coloured by COVID label.](index_files/figure-html/fig-metabolome-output-1.png){#fig-metabolome fig-alt='Two panels. The left is a log-scale plot of eigenvalue against index for 285 components, decaying smoothly then dropping off a cliff at index 74 to a flat floor. The right is a scatter of 75 points on two principal components, coloured in three groups that overlap substantially.'}\n:::\n:::\n\n\n### Downstream impact\n\nThe gate passes, and it passes weakly. That distinction is what running the gate buys.\n\n- **What it licenses.** The leading axis moves with severity rather than against it, so there is no evidence of a batch effect large enough to dominate the run. Differential-abundance testing can proceed.\n- **What it refuses to license.** A correlation of 0.5363 and a Control group with a PC1 standard deviation of 7.74 — larger than the gap between the Mild and Severe means — means PC1 is not a disease axis. Reporting a per-sample severity score read off PC1 would be reading more into the largest-variance direction than it contains. [Neutrophil Metabolomes as a Matrix](../neutrophil-metabolome-axis/) takes that argument further, showing that clustering this matrix does not recover the labels either.\n- **What the rank bound costs.** With 74 usable directions for 285 metabolites, rank-10 reconstruction still leaves 35.71% of the energy unexplained. Any claim that \"a handful of components summarises the metabolome\" fails on this matrix, and the reconstruction curve is where you check it rather than the scree plot's first two bars.\n\n## Probabilistic PCA\n\nViews 1 through 6 are one optimization problem and two ways of solving it. Probabilistic PCA is a different kind of statement, and the difference matters more than the agreement.\n\nIt starts from a generative model rather than an objective. A latent $z \\in \\mathbb{R}^k$ generates an observation:\n\n$$\nx = Wz + \\mu + \\varepsilon, \\qquad z \\sim N(0, I_k), \\quad \\varepsilon \\sim N(0, \\sigma^2 I_d),\n$$\n\nso that marginally $x \\sim N(\\mu, WW^\\top + \\sigma^2 I_d)$. Tipping and Bishop (1999) maximised that likelihood and found\n\n$$\nW_{\\mathrm{ML}} = V_k(\\Lambda_k - \\sigma^2 I_k)^{1/2} R,\n\\qquad\n\\sigma^2_{\\mathrm{ML}} = \\frac{1}{d-k}\\sum_{j=k+1}^{d}\\lambda_j,\n$$\n\nwith $V_k$ and $\\Lambda_k$ the leading eigenvectors and eigenvalues of the sample covariance, and $R$ an arbitrary $k \\times k$ rotation. The columns of $W_{\\mathrm{ML}}$ span the principal subspace, the leftover noise variance is the average discarded eigenvalue, and as $\\sigma^2 \\to 0$ the model's posterior mean for $z$ collapses onto the classical projection.\n\nWhere it is *not* the same statement:\n\n- **$W_{\\mathrm{ML}}$ is not orthonormal.** Its columns are scaled by $(\\lambda_j - \\sigma^2)^{1/2}$. The subspace matches; the basis does not, and $R$ leaves it undetermined anyway.\n- **It assumes a distribution.** Views 1–6 assume nothing about how $X$ arose. Probabilistic PCA assumes Gaussian latents and isotropic Gaussian noise, and those assumptions can be wrong in ways an algebraic identity cannot be.\n- **It agrees at the optimum, not everywhere.** The equivalences of @sec-equivalence are identities that hold for every $W$. This is a coincidence of maximisers between two different problems.\n\nWhat the extra assumptions buy is the reason to pay for them: a likelihood, and therefore missing data handled by EM rather than by aggregation, mixtures of PCA models, Bayesian selection of $k$, and a generative sampler. The MovieLens sparsity of @sec-movielens is a case where classical PCA has nothing to say and a probabilistic model does.\n\n## Constraints\n\nWhere the chain of @sec-chain stops holding:\n\n- **Missing entries.** The projector identity needs every cell. ml-100k is 93.7% empty and the equivalence fails outright.\n- **A non-Frobenius loss.** Robust PCA and $\\ell_1$ variants optimise something else and reach a different subspace; Eckart–Young covers the Frobenius and spectral norms and no others.\n- **Units and scaling.** Covariance PCA on metabolite peak areas and correlation PCA on the same file are different questions. Both dataset sections here scale first and say how.\n- **Centring choice.** Column centring, row centring, and double centring give three different leading components, as @sec-movielens measures.\n- **$n \\ll d$.** The rank of the covariance is capped at $n-1$. Eigenvalues past that are zero by arithmetic, and any interpretation of them is interpretation of nothing.\n- **Nonlinear structure.** PCA fits a flat. A curved manifold gets a flat fitted to it, with no warning in the spectrum.\n- **Signs and rotations.** Loadings are determined only up to sign, and up to rotation inside a tied block. Compare reconstructions, not loadings.\n\n## Summary\n\nEvery number in the table was computed, not quoted.\n\n| Perspective | Objective / operation | Intuition | Mathematical tool |\n|---|---|---|---|\n| Maximum variance | $\\max_W \\operatorname{tr}(W^\\top S W)$ | find the directions the data spreads out along | Rayleigh quotient, Ky Fan |\n| Maximum projected energy | $\\max_W \\lVert XW\\rVert_F^2$ | keep as much squared magnitude as $k$ directions can hold | Frobenius norm, Parseval |\n| Minimum reconstruction error | $\\min_W \\lVert X - XWW^\\top\\rVert_F^2$ | find the flat the cloud sits closest to | orthogonal projector, Pythagoras |\n| Best rank-$k$ approximation | $\\min_{\\operatorname{rank} B \\le k}\\lVert X - B\\rVert_F$ | find the simplest matrix that still looks like $X$ | Eckart–Young–Mirsky |\n| Covariance eigendecomposition | $S = V\\Lambda V^\\top$, take $V_k$ | the axes of the data's ellipsoid, with their lengths | symmetric eigendecomposition |\n| Truncated SVD | $X = U\\Sigma V^\\top$, take $V_k$ | the same axes, without ever forming $S$ | singular value decomposition |\n| Probabilistic PCA | $\\max_{W,\\sigma^2} \\ \\log p(X \\mid W, \\sigma^2)$ | a generative model whose MLE lands on the same subspace | Gaussian latent variable model, EM |\n\nThe first three rows are one objective in three notations. Rows 5 and 6 are two routes to its solution. Row 4 is the same optimum stated about matrices instead of subspaces. Row 7 is a different problem that happens to agree at its maximum.\n\n## From matrices to tensors\n\nPCA is the base case that makes higher-order factorizations legible, and the reason it is worth doing first is that the base case is the one where the six views coincide.\n\nThe chain of @sec-chain runs on one fact that does not generalise: Eckart–Young. For matrices, the best rank-$k$ approximation is the truncation of one decomposition, the optimal rank-$k$ answer is nested inside the optimal rank-$(k{+}1)$ answer, and greedy is optimal. For tensors, all three fail. Truncated HOSVD is quasi-optimal, off by at most a factor $\\sqrt{N}$ in $N$ modes but not optimal; the best rank-$k$ CP decomposition need not exist at all, since the set of tensors of rank at most $k$ is not closed; and CP components are not nested, so rank-2 is not rank-1 plus a correction.\n\nSo the tensor posts spend their effort on things PCA never has to decide: which product the operator lives under, which mode to unfold, which decomposition trades memory for accuracy on this cube. [Tensor Factorizations and Tensor Inverses](../tensor-factorizations/) sets out CP, Tucker, TT, and t-SVD on a synthetic cube; [Uses of Tensor Factorizations](../uses-of-tensor-factorizations/) works the compression case. Both start from the assumption that a reader knows what a truncated SVD buys, and that is the assumption PCA supplies.\n\nOne. Object. Six. Windows. Centre. First. Missing. Data. Breaks. It.\n\n## References\n\n- Eckart, C., and Young, G. (1936). [The approximation of one matrix by another of lower rank](https://doi.org/10.1007/BF02288367). *Psychometrika* 1(3), 211–218.\n- Golub, G. H., and Van Loan, C. F. (2013). *Matrix Computations*, 4th edition. Johns Hopkins University Press.\n- Hotelling, H. (1933). [Analysis of a complex of statistical variables into principal components](https://doi.org/10.1037/h0071325). *Journal of Educational Psychology* 24(6), 417–441.\n- Li, Y., et al. (2023). Neutrophil metabolomics in COVID-19. Metabolomics Workbench study [ST002477](https://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&StudyID=ST002477), CC BY 4.0.\n- Mirsky, L. (1960). [Symmetric gauge functions and unitarily invariant norms](https://doi.org/10.1093/qmath/11.1.50). *The Quarterly Journal of Mathematics* 11(1), 50–59.\n- Pearson, K. (1901). [On lines and planes of closest fit to systems of points in space](https://doi.org/10.1080/14786440109462720). *Philosophical Magazine* 2(11), 559–572.\n- Tipping, M. E., and Bishop, C. M. (1999). [Probabilistic principal component analysis](https://doi.org/10.1111/1467-9868.00196). *Journal of the Royal Statistical Society, Series B* 61(3), 611–622.\n- [MovieLens 100K](https://grouplens.org/datasets/movielens/100k/) — GroupLens, University of Minnesota; Harper and Konstan (2015), *ACM TiiS* 5(4).\n- [The Directions a Matrix Refuses to Turn](../eigendecomposition/) — eigenvectors and eigenvalues from scratch.\n- [The Matrix That Rotates, Stretches, and Rotates Again](../svd-rotate-stretch-rotate/) — SVD geometry, and the precision case against forming $X^\\top X$.\n- [Neutrophil Metabolomes as a Matrix](../neutrophil-metabolome-axis/) — clustering the same 75 × 285 file, and why a line through the group means is not a disease axis.\n- [Tensor Factorizations and Tensor Inverses](../tensor-factorizations/) — CP, Tucker, TT, and t-SVD, where Eckart–Young stops applying.\n- [Uses of Tensor Factorizations](../uses-of-tensor-factorizations/) — the compression case in three and four modes.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}