<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-08-10">
<meta name="description" content="Perception, covariation, intervention, counterfactuals — children assemble a causal toolkit before school. Pearl’s graphs and Rubin’s potential outcomes are that toolkit written down, and on a growth team’s promo and feature they turn two dashboard numbers into two different decisions.">

<title>How Causality Works: From Toddlers to Do-Calculus – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">How Causality Works: From Toddlers to Do-Calculus</h1>
            <p class="subtitle lead">A two-year-old settles causal questions in three flips of a light switch. Science spends a century recovering what it gave up to ask harder ones.</p>
                  <div>
        <div class="description">
          Perception, covariation, intervention, counterfactuals — children assemble a causal toolkit before school. Pearl’s graphs and Rubin’s potential outcomes are that toolkit written down, and on a growth team’s promo and feature they turn two dashboard numbers into two different decisions.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Causal Inference</div>
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Machine Learning</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 10, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-toddler-runs-the-whole-causal-inference-curriculum-before-school" id="toc-a-toddler-runs-the-whole-causal-inference-curriculum-before-school" class="nav-link active" data-scroll-target="#a-toddler-runs-the-whole-causal-inference-curriculum-before-school">A toddler runs the whole causal-inference curriculum before school</a></li>
  <li><a href="#time-is-causalitys-most-reliable-symptom-not-its-essence" id="toc-time-is-causalitys-most-reliable-symptom-not-its-essence" class="nav-link" data-scroll-target="#time-is-causalitys-most-reliable-symptom-not-its-essence">Time is causality’s most reliable symptom, not its essence</a></li>
  <li><a href="#two-dashboard-numbers-and-the-budget-riding-on-each" id="toc-two-dashboard-numbers-and-the-budget-riding-on-each" class="nav-link" data-scroll-target="#two-dashboard-numbers-and-the-budget-riding-on-each">Two dashboard numbers, and the budget riding on each</a></li>
  <li><a href="#pearl-draws-the-assumption-rubin-does-the-arithmetic" id="toc-pearl-draws-the-assumption-rubin-does-the-arithmetic" class="nav-link" data-scroll-target="#pearl-draws-the-assumption-rubin-does-the-arithmetic">Pearl draws the assumption, Rubin does the arithmetic</a></li>
  <li><a href="#the-promos-10.35-is-mostly-the-holiday-not-the-coupon" id="toc-the-promos-10.35-is-mostly-the-holiday-not-the-coupon" class="nav-link" data-scroll-target="#the-promos-10.35-is-mostly-the-holiday-not-the-coupon">The promo’s $10.35 is mostly the holiday, not the coupon</a>
  <ul class="collapse">
  <li><a href="#pearl-the-surgery-deletes-the-arrow-into-the-promo" id="toc-pearl-the-surgery-deletes-the-arrow-into-the-promo" class="nav-link" data-scroll-target="#pearl-the-surgery-deletes-the-arrow-into-the-promo">Pearl: the surgery deletes the arrow into the promo</a></li>
  <li><a href="#rubin-the-same-4-without-the-rerun" id="toc-rubin-the-same-4-without-the-rerun" class="nav-link" data-scroll-target="#rubin-the-same-4-without-the-rerun">Rubin: the same $4 without the rerun</a></li>
  <li><a href="#the-decision-flips-and-it-flips-against-the-promo" id="toc-the-decision-flips-and-it-flips-against-the-promo" class="nav-link" data-scroll-target="#the-decision-flips-and-it-flips-against-the-promo">The decision flips, and it flips against the promo</a></li>
  </ul></li>
  <li><a href="#the-features-adopters-were-never-comparable-to-its-non-adopters" id="toc-the-features-adopters-were-never-comparable-to-its-non-adopters" class="nav-link" data-scroll-target="#the-features-adopters-were-never-comparable-to-its-non-adopters">The feature’s adopters were never comparable to its non-adopters</a>
  <ul class="collapse">
  <li><a href="#pearl-the-graph-says-engagement-is-enough-and-says-why" id="toc-pearl-the-graph-says-engagement-is-enough-and-says-why" class="nav-link" data-scroll-target="#pearl-the-graph-says-engagement-is-enough-and-says-why">Pearl: the graph says engagement is enough, and says why</a></li>
  <li><a href="#rubin-weighting-arrives-at-the-same-place-from-the-other-side" id="toc-rubin-weighting-arrives-at-the-same-place-from-the-other-side" class="nav-link" data-scroll-target="#rubin-weighting-arrives-at-the-same-place-from-the-other-side">Rubin: weighting arrives at the same place from the other side</a></li>
  <li><a href="#what-the-roadmap-turns-on-is-a-ranking-not-a-threshold" id="toc-what-the-roadmap-turns-on-is-a-ranking-not-a-threshold" class="nav-link" data-scroll-target="#what-the-roadmap-turns-on-is-a-ranking-not-a-threshold">What the roadmap turns on is a ranking, not a threshold</a></li>
  </ul></li>
  <li><a href="#caveat-both-frameworks-fail-identically-when-the-confounder-isnt-logged" id="toc-caveat-both-frameworks-fail-identically-when-the-confounder-isnt-logged" class="nav-link" data-scroll-target="#caveat-both-frameworks-fail-identically-when-the-confounder-isnt-logged">Caveat: both frameworks fail identically when the confounder isn’t logged</a></li>
  <li><a href="#platforms-dont-want-the-average-effect-they-want-yours" id="toc-platforms-dont-want-the-average-effect-they-want-yours" class="nav-link" data-scroll-target="#platforms-dont-want-the-average-effect-they-want-yours">Platforms don’t want the average effect, they want yours</a>
  <ul class="collapse">
  <li><a href="#caveat-the-uplift-model-overstates-its-own-win" id="toc-caveat-the-uplift-model-overstates-its-own-win" class="nav-link" data-scroll-target="#caveat-the-uplift-model-overstates-its-own-win">Caveat: the uplift model overstates its own win</a></li>
  </ul></li>
  <li><a href="#every-method-is-a-machine-for-guessing-what-didnt-happen" id="toc-every-method-is-a-machine-for-guessing-what-didnt-happen" class="nav-link" data-scroll-target="#every-method-is-a-machine-for-guessing-what-didnt-happen">Every method is a machine for guessing what didn’t happen</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/causality-from-toddlers-to-do-calculus/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>How Causality Works: From Toddlers to Do-Calculus</figcaption>
</figure>
</div>
<p>A two-year-old at a light switch does not have a sample size. They flip it, watch the room, flip it again, and by the third repetition they own the fact: this thing causes that thing. No control group, no p-value, no worry about unmeasured confounding. Science spends enormous effort recovering that certainty and mostly falls short — not because scientists reason worse than toddlers, but because the questions worth asking rarely permit the toddler’s one move. Reach out and wiggle the world yourself.</p>
<section id="a-toddler-runs-the-whole-causal-inference-curriculum-before-school" class="level2">
<h2 class="anchored" data-anchor-id="a-toddler-runs-the-whole-causal-inference-curriculum-before-school">A toddler runs the whole causal-inference curriculum before school</h2>
<p>The instinct arrives early, in pieces. Albert Michotte, screening crude animations in the 1940s, found that a square sliding into a second square that immediately moves off is not <em>seen</em> as two events but as a launch, as directly as a colour is. Add a fifth of a second of delay and the impression collapses into unrelated motions. Infants show the same sensitivity to contact and timing before they have words for either.</p>
<p>Perception alone is a poor detector, so children add statistics. In Gopnik’s blicket detector studies, a machine lights up when certain blocks are set on it, and preschoolers track which blocks coincide with the light. They discount a block whose apparent power is fully explained by another present at the same time: toddlers screen off spurious associations.</p>
<p>Then they do what no observer can: they intervene. A child at an unfamiliar machine does not wait for informative data; they push, pull and remove one block at a time, manufacturing comparisons a watcher might wait years for. Play is experimental design.</p>
<p>By three or four the counterfactual arrives — <em>if you hadn’t knocked it, it would still be standing</em> — and with it blame and regret. They also start demanding mechanism, building naive theories of how plants grow, and taking causal claims on testimony.</p>
<p>Formal science is this toolkit — perception, covariation, intervention, counterfactuals, mechanism, testimony — made explicit, written down and left where strangers can check it.</p>
</section>
<section id="time-is-causalitys-most-reliable-symptom-not-its-essence" class="level2">
<h2 class="anchored" data-anchor-id="time-is-causalitys-most-reliable-symptom-not-its-essence">Time is causality’s most reliable symptom, not its essence</h2>
<p>The toolkit leans hard on one regularity: causes come first. Hume built his account on it, defining a cause as constant conjunction plus temporal priority plus contiguity. Modern accounts drop it. Pearl’s causes are fixed by structural equations, Woodward’s by what stays invariant under intervention; in both the essential relation is dependence — change the cause, the effect follows — with time order nowhere in the definition.</p>
<p>The gap shows where nothing waits. A book resting on a table causes the tabletop’s deformation <em>now</em>: pressure and sag are simultaneous, as equilibrium models in economics assume. Temporal order remains the best-behaved symptom of causation we have, and the methods below lean on it in one specific place — deciding which variables count as pre-treatment, and so which are safe to adjust for. It just isn’t what causation is.</p>
</section>
<section id="two-dashboard-numbers-and-the-budget-riding-on-each" class="level2">
<h2 class="anchored" data-anchor-id="two-dashboard-numbers-and-the-budget-riding-on-each">Two dashboard numbers, and the budget riding on each</h2>
<p>Dependence under intervention is the thing to measure, then, and measuring it is expensive enough that nobody funds it out of curiosity. Everything below runs on one company and two numbers somebody is about to act on.</p>
<p>Picture a consumer subscription app: roughly two million monthly actives, about $30 of spend per user per month across subscriptions and in-app add-ons, and a growth team three weeks out from quarterly planning.</p>
<p><strong>The promotion.</strong> Marketing sent a $5-off coupon to 400,000 users across the November and December window. It applies automatically at checkout, so it costs roughly $5 of margin per recipient per month whether or not the recipient noticed it — which makes finance’s rule for renewing the $2M annual promo budget a single comparison: the programme pays for itself only if it <em>adds</em> more than $5 of monthly spend per user <em>sent</em>. Treating incremental spend as near-pure margin is generous to the promo; it is the assumption its defenders would choose, and the promo will lose anyway. The dashboard says promoted users spend $10.35 more per month.</p>
<p><strong>The feature.</strong> “Collections” — saved, curated lists — shipped to everyone four months ago, and about half the userbase has touched it. Three decisions ride on its measured lift: whether next quarter’s engineering goes into deepening it or into the checkout redesign, whether the onboarding flow spends one of its few slots pushing it, and, quietly, which team gets credited at review time. The dashboard says adopters spend $9.26 more per month.</p>
<p>Both numbers are correct, in the sense that the SQL is correct. Neither is the number either decision needs.</p>
<p>No real company is being reported on here: every figure below comes from a simulation whose code is on the page. That is not a convenience, it is the only way to grade the methods. The quantity all of them estimate — what a user would have spent under the treatment they did not get — is missing from every real dataset by construction, so a real dataset can tell you which estimator you <em>like</em> but never which one is right. Writing the true effect down first and then hiding it is the only experiment available.</p>
<p>What the simulation stands in for is ordinary product telemetry: an event log of sessions and feature touches joined to a billing table, one row per user per month, of the sort every subscription business already has sitting in a warehouse. The generating processes are deliberately small — a holiday flag, a pre-launch engagement score, a tenure variable — because the failure being demonstrated needs no complexity to appear. It appears with one confounder and eight thousand rows, and here it is worth about $2M a year.</p>
</section>
<section id="pearl-draws-the-assumption-rubin-does-the-arithmetic" class="level2">
<h2 class="anchored" data-anchor-id="pearl-draws-the-assumption-rubin-does-the-arithmetic">Pearl draws the assumption, Rubin does the arithmetic</h2>
<p>Two traditions grew up around questions like these, and the folklore says they compete. They don’t, and the division of labour is the reason both appear below on both examples. Judea Pearl’s graphical framework is a language for <em>declaring</em> what causes what, and its payoff is a verdict: given this structure, is the effect recoverable from data at all, and which variables must you adjust for? Neyman and Rubin’s potential outcomes framework is a language for <em>estimating</em>: given that some set of variables suffices, here is how to weight, impute or match your way to a number, with a standard error attached. One licenses the adjustment; the other performs it. A third tradition, uplift modelling, throws the average away entirely and asks the question a platform actually acts on.</p>
<p>Pearl’s <em>ladder of causation</em> sorts the growth team’s questions by how much of the world you have to be able to move to answer them.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart TB
  R1["&lt;b&gt;1 · Seeing&lt;/b&gt;&lt;br/&gt;what promoted users spend&lt;br/&gt;&lt;i&gt;the dashboard: +$10.35&lt;/i&gt;"]
  R2["&lt;b&gt;2 · Doing&lt;/b&gt;&lt;br/&gt;what happens if we send the coupon&lt;br/&gt;&lt;i&gt;the budget-renewal decision&lt;/i&gt;"]
  R3["&lt;b&gt;3 · Imagining&lt;/b&gt;&lt;br/&gt;what this user would have done untreated&lt;br/&gt;&lt;i&gt;who to target, and who to spare&lt;/i&gt;"]
  R1 --&gt;|"needs a causal assumption"| R2
  R2 --&gt;|"needs a model per user"| R3
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Every dashboard in the company lives on rung one. Both decisions in the planning meeting live on rung two, the targeting question on rung three, and no quantity of rung-one data climbs by itself. The promo shows what the climb costs.</p>
</section>
<section id="the-promos-10.35-is-mostly-the-holiday-not-the-coupon" class="level2">
<h2 class="anchored" data-anchor-id="the-promos-10.35-is-mostly-the-holiday-not-the-coupon">The promo’s $10.35 is mostly the holiday, not the coupon</h2>
<p>Start where Pearl starts, by drawing the assumption. A directed graph declares which variables cause which, and the <code>do</code> operator is surgery on it: delete every arrow <em>into</em> the treatment, because you, not the world, decide who gets it now.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Confounder
</div>
</div>
<div class="callout-body-container callout-body">
<p>A variable that causes both the treatment and the outcome, manufacturing correlation between two variables with no causal arrow linking them. That is how “correlated with” and “causes” come apart.</p>
</div>
</div>
<p>Marketing sent the coupon during the holiday window, when people were going to spend more anyway. The holiday therefore causes both the promo and the spend, and the two get tangled along a path — <code>promo ← holiday → spend</code> — that runs <em>backwards</em> out of the treatment. Pearl calls it a backdoor path, and the surgery is what cuts it.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  subgraph OBS["What marketing ran"]
    direction TB
    H1["🎄 holiday window"] --&gt;|"targeting rule"| P1["promo sent"]
    H1 --&gt;|"people spend more&lt;br/&gt;anyway (the backdoor)"| S1["monthly spend"]
    P1 --&gt;|"the effect we want"| S1
  end

  subgraph DOG["do(promo): a coin decides"]
    direction TB
    C2(("coin")) --&gt; P2["promo sent"]
    H2["🎄 holiday window"] --&gt; S2["monthly spend"]
    P2 --&gt;|"the effect we want"| S2
  end

  %% Invisible link, purely to pin the observed graph left of the surgery.
  OBS ~~~ DOG
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<section id="pearl-the-surgery-deletes-the-arrow-into-the-promo" class="level3">
<h3 class="anchored" data-anchor-id="pearl-the-surgery-deletes-the-arrow-into-the-promo">Pearl: the surgery deletes the arrow into the promo</h3>
<p>The graph is a claim, not a result, so the way to test it is to build a world that obeys it. Below a promo truly adds $4 of monthly spend. We run the same world twice, changing only who gets the promo: first marketing chooses, then a coin does.</p>
<div id="5a934428" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> networkx <span class="im">as</span> nx</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">7</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">20_000</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>TRUE_LIFT <span class="op">=</span> <span class="fl">4.0</span>  <span class="co"># dollars of monthly spend a promo really causes</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>COUPON_COST <span class="op">=</span> <span class="fl">5.0</span>  <span class="co"># dollars of margin the coupon gives away each month</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># The assumed structure: the holiday window drives targeting *and* spending.</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>g <span class="op">=</span> nx.DiGraph([(<span class="st">"holiday"</span>, <span class="st">"promo"</span>), (<span class="st">"holiday"</span>, <span class="st">"spend"</span>), (<span class="st">"promo"</span>, <span class="st">"spend"</span>)])</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"parents of spend:"</span>, <span class="bu">sorted</span>(g.predecessors(<span class="st">"spend"</span>)))</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co"># One population, drawn once: the same users, the same holidays, the same luck.</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>holiday <span class="op">=</span> rng.binomial(<span class="dv">1</span>, <span class="fl">0.3</span>, n)  <span class="co"># 30% of users are in a holiday window</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>luck <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="dv">5</span>, n)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> assign(marketing_targets: <span class="bu">bool</span>):</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Intervening severs holiday -&gt; promo: a coin decides, so targeting can't bias it.</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> <span class="fl">0.2</span> <span class="op">+</span> <span class="fl">0.6</span> <span class="op">*</span> holiday <span class="cf">if</span> marketing_targets <span class="cf">else</span> np.full(n, <span class="fl">0.5</span>)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rng.binomial(<span class="dv">1</span>, p)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> spend_under(promo):</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">30</span> <span class="op">+</span> <span class="dv">12</span> <span class="op">*</span> holiday <span class="op">+</span> TRUE_LIFT <span class="op">*</span> promo <span class="op">+</span> luck</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> gap(promo, spend):</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">round</span>(spend[promo <span class="op">==</span> <span class="dv">1</span>].mean() <span class="op">-</span> spend[promo <span class="op">==</span> <span class="dv">0</span>].mean(), <span class="dv">2</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>promo <span class="op">=</span> assign(marketing_targets<span class="op">=</span><span class="va">True</span>)  <span class="co"># who marketing chose</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>promo_rct <span class="op">=</span> assign(marketing_targets<span class="op">=</span><span class="va">False</span>)  <span class="co"># who a coin would have chosen</span></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>spend, spend_rct <span class="op">=</span> spend_under(promo), spend_under(promo_rct)</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>dashboard <span class="op">=</span> gap(promo, spend)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>do_estimate <span class="op">=</span> gap(promo_rct, spend_rct)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"seeing, E[spend | promo]    :"</span>, dashboard)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"doing,  E[spend | do(promo)]:"</span>, do_estimate)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>parents of spend: ['holiday', 'promo']
seeing, E[spend | promo]    : 10.35
doing,  E[spend | do(promo)]: 4.06</code></pre>
</div>
</div>
<p>Seeing credits the promo with $10.35; doing returns $4.06, within noise of the true $4. The surplus is the holiday arriving along a path that was never causal, and no further observation shrinks it — the promo looks two and a half times better than it is because it was aimed at people already about to spend. Randomise the send and the bias is gone. The trouble is that nobody can rerun last December.</p>
</section>
<section id="rubin-the-same-4-without-the-rerun" class="level3">
<h3 class="anchored" data-anchor-id="rubin-the-same-4-without-the-rerun">Rubin: the same $4 without the rerun</h3>
<p>Randomising was a simulation luxury; the growth team has one dataset, the targeted one. Rubin’s framework is built for exactly that position. Give each unit two potential outcomes — spend under the coupon and spend without it — and the causal effect is their difference, unobservable by construction, because only one of the two ever happens.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Counterfactual
</div>
</div>
<div class="callout-body-container callout-body">
<p>The outcome that would have occurred under the treatment a unit did not receive. Every estimate in this post is an attempt to fill that missing column with something defensible.</p>
</div>
</div>
<p>Randomisation would make the missing column <em>ignorable</em>: coin-flip assignment leaves the groups differing only by chance, so group averages stand in for each other. Absent the coin, you argue for a weaker version — treatment is as good as random <em>among users alike on the holiday flag</em> — which is precisely what Pearl’s graph already licensed by naming <code>{holiday}</code> as a set that blocks the backdoor. Inverse propensity weighting cashes that licence in.</p>
<div id="ccc34b62" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Only the observational arm: marketing targeted, and there is no rerun.</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> holiday[:, <span class="va">None</span>]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>ps <span class="op">=</span> LogisticRegression().fit(X, promo).predict_proba(X)[:, <span class="dv">1</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Weight each user by 1 / P(the arm they landed in), rebuilding a population in</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># which the holiday no longer predicts who was sent a coupon.</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> np.where(promo <span class="op">==</span> <span class="dv">1</span>, <span class="dv">1</span> <span class="op">/</span> ps, <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> ps))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>ipw_promo <span class="op">=</span> <span class="bu">round</span>(</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    np.average(spend[promo <span class="op">==</span> <span class="dv">1</span>], weights<span class="op">=</span>w[promo <span class="op">==</span> <span class="dv">1</span>])</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span> np.average(spend[promo <span class="op">==</span> <span class="dv">0</span>], weights<span class="op">=</span>w[promo <span class="op">==</span> <span class="dv">0</span>]),</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"dashboard gap      :"</span>, dashboard)</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"propensity-weighted:"</span>, ipw_promo)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>dashboard gap      : 10.35
propensity-weighted: 3.88</code></pre>
</div>
</div>
<p>Weighting recovers $3.88 from the same rows the dashboard read as $10.35, and it never saw the randomised world. Pearl said <em>which</em> variable to adjust for and that adjusting for it was enough; Rubin said what to do about it. The estimate that comes out is close enough to the coin-flip rerun that the difference no longer matters — but the decision it implies is the opposite one.</p>
</section>
<section id="the-decision-flips-and-it-flips-against-the-promo" class="level3">
<h3 class="anchored" data-anchor-id="the-decision-flips-and-it-flips-against-the-promo">The decision flips, and it flips against the promo</h3>
<p>The break-even is the only arithmetic finance needs, and the two estimates fall on opposite sides of it.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  D["one dataset&lt;br/&gt;400k coupons&lt;br/&gt;sent in Nov–Dec"]
  D --&gt; N["read it raw&lt;br/&gt;&lt;b&gt;+$10.35&lt;/b&gt;"]
  D --&gt; A["adjust for&lt;br/&gt;the holiday&lt;br/&gt;&lt;b&gt;+$3.88&lt;/b&gt;"]
  N --&gt; N2["clears the $5&lt;br/&gt;coupon cost&lt;br/&gt;→ renew the $2M budget"]
  A --&gt; A2["misses the $5&lt;br/&gt;coupon cost&lt;br/&gt;→ stop, or retarget off-season"]
  N2 --&gt; N3["≈ −$1 per user&lt;br/&gt;per month, booked&lt;br/&gt;as the quarter's win"]
  A2 --&gt; A3["$2M freed, and the&lt;br/&gt;holiday cohort stops&lt;br/&gt;being double-counted"]
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>Plotting the estimates against that $5 line makes the sign change visible: everything the adjustment does is move the programme from one side of a decision boundary to the other.</p>
<div id="a26f2da0" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>PURPLE, PURPLE_MID, PURPLE_LIGHT <span class="op">=</span> <span class="st">"#4A3AA7"</span>, <span class="st">"#6A5CBB"</span>, <span class="st">"#B7AEE4"</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>ACCENT, INK, MUTED, GRID <span class="op">=</span> <span class="st">"#C2570A"</span>, <span class="st">"#1F1D24"</span>, <span class="st">"#6B6673"</span>, <span class="st">"#DCDAE2"</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> estimate_chart(labels, values, truth, truth_label, line, line_label, region_label):</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Estimates as bars, with the truth and the decision boundary as rules."""</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">2.9</span>))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.arange(<span class="bu">len</span>(labels))[::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    colours <span class="op">=</span> [PURPLE_LIGHT] <span class="op">+</span> [PURPLE_MID] <span class="op">*</span> (<span class="bu">len</span>(labels) <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    ax.barh(y, values, height<span class="op">=</span><span class="fl">0.55</span>, color<span class="op">=</span>colours, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> yi, v <span class="kw">in</span> <span class="bu">zip</span>(y, values):</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>        <span class="co"># White backing so a value label never reads as crossed out by the decision rule.</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>        ax.text(v <span class="op">+</span> <span class="fl">0.12</span>, yi, <span class="ss">f"$</span><span class="sc">{</span>v<span class="sc">:.2f}</span><span class="ss">"</span>, va<span class="op">=</span><span class="st">"center"</span>, color<span class="op">=</span>INK, fontsize<span class="op">=</span><span class="dv">10</span>, zorder<span class="op">=</span><span class="dv">7</span>,</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>                bbox<span class="op">=</span><span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">"white"</span>, edgecolor<span class="op">=</span><span class="st">"none"</span>, pad<span class="op">=</span><span class="fl">1.2</span>))</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    top <span class="op">=</span> <span class="bu">max</span>(values <span class="op">+</span> [line, truth]) <span class="op">*</span> <span class="fl">1.28</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    ax.axvspan(line, top, color<span class="op">=</span>ACCENT, alpha<span class="op">=</span><span class="fl">0.06</span>, zorder<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    ax.axvline(truth, color<span class="op">=</span>INK, lw<span class="op">=</span><span class="fl">1.4</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    ax.axvline(line, color<span class="op">=</span>ACCENT, lw<span class="op">=</span><span class="fl">1.4</span>, ls<span class="op">=</span><span class="st">"--"</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    ax.text(truth, <span class="bu">len</span>(labels) <span class="op">-</span> <span class="fl">0.35</span>, <span class="ss">f"  </span><span class="sc">{</span>truth_label<span class="sc">}</span><span class="ss">"</span>, color<span class="op">=</span>INK, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    ax.text(line, <span class="op">-</span><span class="fl">0.95</span>, <span class="ss">f" </span><span class="sc">{</span>line_label<span class="sc">}</span><span class="ss">"</span>, color<span class="op">=</span>ACCENT, fontsize<span class="op">=</span><span class="dv">9</span>, va<span class="op">=</span><span class="st">"center"</span>)</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    ax.text(top, <span class="op">-</span><span class="fl">0.95</span>, <span class="ss">f"</span><span class="sc">{</span>region_label<span class="sc">}</span><span class="ss"> "</span>, color<span class="op">=</span>ACCENT, fontsize<span class="op">=</span><span class="dv">9</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>            va<span class="op">=</span><span class="st">"center"</span>, ha<span class="op">=</span><span class="st">"right"</span>, style<span class="op">=</span><span class="st">"italic"</span>)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    ax.set_yticks(y, labels, fontsize<span class="op">=</span><span class="dv">10</span>, color<span class="op">=</span>INK)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>    ax.set_xlim(<span class="dv">0</span>, top)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    ax.set_ylim(<span class="op">-</span><span class="fl">1.4</span>, <span class="bu">len</span>(labels) <span class="op">-</span> <span class="fl">0.1</span>)</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"incremental monthly spend per user ($)"</span>, color<span class="op">=</span>MUTED, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>    ax.xaxis.grid(<span class="va">True</span>, color<span class="op">=</span>GRID, lw<span class="op">=</span><span class="fl">0.7</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(colors<span class="op">=</span>MUTED, labelsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    ax.tick_params(axis<span class="op">=</span><span class="st">"y"</span>, colors<span class="op">=</span>INK)</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> side <span class="kw">in</span> (<span class="st">"top"</span>, <span class="st">"right"</span>, <span class="st">"left"</span>):</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>        ax.spines[side].set_visible(<span class="va">False</span>)</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>    ax.spines[<span class="st">"bottom"</span>].set_color(GRID)</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    fig.tight_layout()</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> fig</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>estimate_chart(</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"Dashboard</span><span class="ch">\n</span><span class="st">(promoted vs not)"</span>, <span class="st">"Rubin</span><span class="ch">\n</span><span class="st">(propensity-weighted)"</span>, <span class="st">"Randomised rerun</span><span class="ch">\n</span><span class="st">(unavailable in practice)"</span>],</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>    [dashboard, ipw_promo, do_estimate],</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>    truth<span class="op">=</span>TRUE_LIFT,</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>    truth_label<span class="op">=</span><span class="ss">f"true lift $</span><span class="sc">{</span>TRUE_LIFT<span class="sc">:.2f}</span><span class="ss">"</span>,</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    line<span class="op">=</span>COUPON_COST,</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>    line_label<span class="op">=</span><span class="ss">f"$</span><span class="sc">{</span>COUPON_COST<span class="sc">:.0f}</span><span class="ss"> coupon cost — break-even"</span>,</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>    region_label<span class="op">=</span><span class="st">"renew territory"</span>,</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img" alt="Horizontal bar chart of three promo estimates. The dashboard gap at $10.35 sits right of the $5 break-even line; the propensity-weighted estimate at $3.88 and the randomised rerun at $4.06 sit left of it, next to the true $4.00 lift."></p>
<figcaption>Two readings of December against the coupon’s own cost, plus the randomised rerun nobody gets to run. Only the unadjusted reading clears break-even.</figcaption>
</figure>
</div>
</div>
</div>
<p>The dashboard is the only bar in renew territory, and it is the one the promo programme was being judged on. A product manager who ships the adjusted number into the planning meeting is not reporting a smaller win; they are reporting a loss of roughly a dollar per user per month, recommending the coupon be stopped or retargeted at users <em>outside</em> the holiday window, and freeing $2M — while conceding that the retarget is a new question the old data cannot answer, and needs a real test. The feature question looks easier, because nothing was targeted at all. It isn’t.</p>
</section>
</section>
<section id="the-features-adopters-were-never-comparable-to-its-non-adopters" class="level2">
<h2 class="anchored" data-anchor-id="the-features-adopters-were-never-comparable-to-its-non-adopters">The feature’s adopters were never comparable to its non-adopters</h2>
<p>Nobody assigned Collections to anyone: it shipped to everyone, and users decided for themselves whether to touch it. That removes marketing’s targeting rule and replaces it with the users’ own, which is worse, because the heaviest users adopt first and heavy users were always going to spend more. The confounder here is engagement before launch — sessions per week in the months before Collections existed — and it plays exactly the role the holiday played.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  E["pre-launch engagement&lt;br/&gt;&lt;i&gt;sessions per week&lt;/i&gt;"] --&gt;|"heavy users&lt;br/&gt;adopt first"| A["adopted Collections"]
  E --&gt;|"heavy users&lt;br/&gt;spend more"| S["monthly spend"]
  A --&gt;|"the effect we want"| S
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<section id="pearl-the-graph-says-engagement-is-enough-and-says-why" class="level3">
<h3 class="anchored" data-anchor-id="pearl-the-graph-says-engagement-is-enough-and-says-why">Pearl: the graph says engagement is enough, and says why</h3>
<p>Read the backdoor rule off that picture. There is one path from <code>adopted</code> to <code>spend</code> that starts with an arrow pointing <em>into</em> <code>adopted</code> — via engagement — and conditioning on engagement blocks it. No other path qualifies, so <code>{engagement}</code> is a sufficient adjustment set, and the effect of adopting is identified as the <em>adjustment formula</em>: average the outcome model over the population, once with everyone set to adopt and once with nobody adopting. Implemented directly, that is g-computation.</p>
<div id="84809501" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">8_000</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>engagement <span class="op">=</span> rng.normal(size<span class="op">=</span>n)  <span class="co"># measured confounder: sessions/week before launch</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Both potential outcomes, written down for everyone. Reality reveals one.</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>y0 <span class="op">=</span> <span class="dv">30</span> <span class="op">+</span> <span class="dv">8</span> <span class="op">*</span> engagement <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="dv">4</span>, n)  <span class="co"># monthly spend if they never adopt</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>y1 <span class="op">=</span> y0 <span class="op">+</span> <span class="fl">2.50</span>  <span class="co"># spend if they adopt: true average lift = $2.50</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Nobody assigned this: heavy users found the feature on their own.</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>adopted <span class="op">=</span> rng.binomial(<span class="dv">1</span>, <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>engagement)))</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>spend <span class="op">=</span> np.where(adopted <span class="op">==</span> <span class="dv">1</span>, y1, y0)  <span class="co"># the other column is now missing</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>naive_feature <span class="op">=</span> <span class="bu">round</span>(spend[adopted <span class="op">==</span> <span class="dv">1</span>].mean() <span class="op">-</span> spend[adopted <span class="op">==</span> <span class="dv">0</span>].mean(), <span class="dv">2</span>)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"dashboard adopter gap:"</span>, naive_feature)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="co"># The adjustment formula: model spend given adoption *and* engagement, then average</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="co"># the model over everyone twice -- once forcing adoption on, once forcing it off.</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>outcome <span class="op">=</span> LinearRegression().fit(np.column_stack([adopted, engagement]), spend)</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> population_mean(arm):</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> outcome.predict(np.column_stack([np.full(n, arm), engagement])).mean()</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>gcomp <span class="op">=</span> <span class="bu">round</span>(population_mean(<span class="dv">1</span>) <span class="op">-</span> population_mean(<span class="dv">0</span>), <span class="dv">2</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"adjustment formula   :"</span>, gcomp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>dashboard adopter gap: 9.26
adjustment formula   : 2.44</code></pre>
</div>
</div>
<p>The adjustment formula returns $2.44 where the dashboard read $9.26, and the true lift is $2.50. Notice what the graph contributed: not the estimate, but the permission to compute one, plus the fact that engagement alone closes every backdoor, so no further covariate is needed to remove bias. Others might still be worth measuring — a covariate that predicts spend tightens the estimate even when it changes nothing about identification — but that is a question about variance, and the graph is silent on it. What the graph also did not supply is a second opinion on the arithmetic.</p>
</section>
<section id="rubin-weighting-arrives-at-the-same-place-from-the-other-side" class="level3">
<h3 class="anchored" data-anchor-id="rubin-weighting-arrives-at-the-same-place-from-the-other-side">Rubin: weighting arrives at the same place from the other side</h3>
<p>Potential outcomes give one. Instead of modelling the <em>outcome</em> and averaging over the population, model the <em>treatment</em> and reweight the population — each user counted by the reciprocal of their probability of landing in the cohort they landed in, so that engagement stops predicting adoption in the weighted world.</p>
<div id="2a1ee9b5" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> engagement[:, <span class="va">None</span>]</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>ps <span class="op">=</span> LogisticRegression().fit(X, adopted).predict_proba(X)[:, <span class="dv">1</span>]</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> np.where(adopted <span class="op">==</span> <span class="dv">1</span>, <span class="dv">1</span> <span class="op">/</span> ps, <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> ps))</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>ipw_feature <span class="op">=</span> <span class="bu">round</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    np.average(spend[adopted <span class="op">==</span> <span class="dv">1</span>], weights<span class="op">=</span>w[adopted <span class="op">==</span> <span class="dv">1</span>])</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span> np.average(spend[adopted <span class="op">==</span> <span class="dv">0</span>], weights<span class="op">=</span>w[adopted <span class="op">==</span> <span class="dv">0</span>]),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="dv">2</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"propensity-weighted:"</span>, ipw_feature)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>propensity-weighted: 2.45</code></pre>
</div>
</div>
<p>$2.45, against g-computation’s $2.44 and a truth of $2.50. The two estimators share nothing but the adjustment set: one fits a model of spend, the other a model of adoption. Don’t read too much into the penny between them — the sampling error on either is several times that, and the outcome model here is the true one, so g-computation is close to just reading off a regression coefficient. What the agreement is worth is a check that neither model is badly misspecified. What it is <em>not</em> worth is the subject of the next section. First, the roadmap.</p>
</section>
<section id="what-the-roadmap-turns-on-is-a-ranking-not-a-threshold" class="level3">
<h3 class="anchored" data-anchor-id="what-the-roadmap-turns-on-is-a-ranking-not-a-threshold">What the roadmap turns on is a ranking, not a threshold</h3>
<p>The feature decision is not go/no-go — Collections is already shipped and costs nothing to leave alone. It is a queue. Next quarter has one engineering slot and one onboarding slot, and the other contender is a checkout redesign whose $3.10 lift came out of an actual randomised test and needs no argument at all.</p>
<div id="77ec1684" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>NEXT_BEST <span class="op">=</span> <span class="fl">3.10</span>  <span class="co"># checkout redesign, measured in a clean A/B test</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>estimate_chart(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    [<span class="st">"Dashboard</span><span class="ch">\n</span><span class="st">(adopters vs not)"</span>, <span class="st">"Pearl</span><span class="ch">\n</span><span class="st">(adjustment formula)"</span>, <span class="st">"Rubin</span><span class="ch">\n</span><span class="st">(propensity-weighted)"</span>],</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    [naive_feature, gcomp, ipw_feature],</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    truth<span class="op">=</span><span class="fl">2.50</span>,</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    truth_label<span class="op">=</span><span class="st">"true lift $2.50"</span>,</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    line<span class="op">=</span>NEXT_BEST,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    line_label<span class="op">=</span><span class="ss">f"$</span><span class="sc">{</span>NEXT_BEST<span class="sc">:.2f}</span><span class="ss"> — randomised checkout redesign"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    region_label<span class="op">=</span><span class="st">"Collections goes first"</span>,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img" alt="Horizontal bar chart of three Collections estimates. The dashboard gap at $9.26 sits right of the $3.10 line marking the randomised checkout redesign; the adjustment formula at $2.44 and the propensity-weighted estimate at $2.45 sit left of it, near the true $2.50 lift."></p>
<figcaption>The same four months of telemetry, read three ways, against the one competing initiative that was properly randomised.</figcaption>
</figure>
</div>
</div>
</div>
<p>At $9.26 Collections is the largest lever anyone can point at and takes both slots. At $2.45 it drops below a rival that was measured properly, so the engineers and the onboarding slot go to checkout, Collections gets maintenance, and the team that shipped it is credited with a real but ordinary $2.50 rather than a fictional $9.26. Same telemetry, same quarter, inverted priorities — and all of it resting on a claim about the world that the data never checked.</p>
</section>
</section>
<section id="caveat-both-frameworks-fail-identically-when-the-confounder-isnt-logged" class="level2">
<h2 class="anchored" data-anchor-id="caveat-both-frameworks-fail-identically-when-the-confounder-isnt-logged">Caveat: both frameworks fail identically when the confounder isn’t logged</h2>
<p>Everything above assumed engagement was the whole story. Suppose it isn’t. People start new jobs, have babies, move cities; those changes make them both more likely to reorganise their app into Collections <em>and</em> more likely to spend, and none of them appear in the event log. The graph acquires a node nobody can condition on.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
  E["pre-launch engagement&lt;br/&gt;&lt;i&gt;logged&lt;/i&gt;"] --&gt; A["adopted Collections"]
  E --&gt; S["monthly spend"]
  A --&gt;|"the effect we want"| S
  U["life change&lt;br/&gt;&lt;i&gt;never logged&lt;/i&gt;"] -.-&gt;|"open backdoor"| A
  U -.-&gt; S
  style U fill:#FDF1E7,stroke:#C2570A,stroke-dasharray:4 3
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>The backdoor <code>adopted ← life change → spend</code> is open and conditioning on engagement does nothing to it, so Pearl’s verdict is not “adjust harder” but “not identified”: no function of this data returns the causal effect. The instructive part is what the estimators do when you run them anyway.</p>
<div id="f676ba90" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">11</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">8_000</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>engagement <span class="op">=</span> rng.normal(size<span class="op">=</span>n)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>life_change <span class="op">=</span> rng.binomial(<span class="dv">1</span>, <span class="fl">0.25</span>, n)  <span class="co"># new job, new baby, new city -- never logged</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>y0 <span class="op">=</span> <span class="dv">30</span> <span class="op">+</span> <span class="dv">8</span> <span class="op">*</span> engagement <span class="op">+</span> <span class="dv">9</span> <span class="op">*</span> life_change <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="dv">4</span>, n)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>y1 <span class="op">=</span> y0 <span class="op">+</span> <span class="fl">2.50</span>  <span class="co"># the true lift has not changed</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>adopted <span class="op">=</span> rng.binomial(<span class="dv">1</span>, <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>(engagement <span class="op">+</span> <span class="fl">1.6</span> <span class="op">*</span> life_change))))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>spend <span class="op">=</span> np.where(adopted <span class="op">==</span> <span class="dv">1</span>, y1, y0)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Adjust for everything that was logged, which is engagement and nothing else.</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> engagement[:, <span class="va">None</span>]</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>ps <span class="op">=</span> LogisticRegression().fit(X, adopted).predict_proba(X)[:, <span class="dv">1</span>]</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> np.where(adopted <span class="op">==</span> <span class="dv">1</span>, <span class="dv">1</span> <span class="op">/</span> ps, <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">-</span> ps))</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>ipw_u <span class="op">=</span> np.average(spend[adopted <span class="op">==</span> <span class="dv">1</span>], weights<span class="op">=</span>w[adopted <span class="op">==</span> <span class="dv">1</span>]) <span class="op">-</span> np.average(</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    spend[adopted <span class="op">==</span> <span class="dv">0</span>], weights<span class="op">=</span>w[adopted <span class="op">==</span> <span class="dv">0</span>]</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>mu <span class="op">=</span> LinearRegression().fit(np.column_stack([adopted, engagement]), spend)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>g_u <span class="op">=</span> mu.predict(np.column_stack([np.ones(n), engagement])).mean() <span class="op">-</span> mu.predict(</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>    np.column_stack([np.zeros(n), engagement])</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>).mean()</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"dashboard adopter gap:"</span>, <span class="bu">round</span>(spend[adopted <span class="op">==</span> <span class="dv">1</span>].mean() <span class="op">-</span> spend[adopted <span class="op">==</span> <span class="dv">0</span>].mean(), <span class="dv">2</span>))</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"propensity-weighted  :"</span>, <span class="bu">round</span>(ipw_u, <span class="dv">2</span>))</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"adjustment formula   :"</span>, <span class="bu">round</span>(g_u, <span class="dv">2</span>))</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"true lift            : 2.5"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>dashboard adopter gap: 10.71
propensity-weighted  : 4.8
adjustment formula   : 4.8
true lift            : 2.5</code></pre>
</div>
</div>
<p>Both return $4.80 — near enough the same wrong answer, from two estimators with almost nothing in common. Nearly double the truth, and delivered with all the reassuring machinery of the previous section: the adjustment ran, the two methods cross-checked, the number moved sensibly away from the naive $10.71. They agree because they inherit the same bias from the same missing column, which is exactly why their agreement carries no information about whether that column mattered. Cross-validation would not catch it, a larger sample would only tighten the confidence interval around the wrong value, and no diagnostic computed from these columns can, because the information required is not in them.</p>
<p>What a careful team does instead is stop treating the estimate as a point and start asking how much hidden confounding it would take to explain the result away — Rosenbaum bounds, or VanderWeele and Ding’s E-value, which reports exactly that in the units of the problem. The PM-facing version is one sentence, and it is the most useful sentence in the post: two methods agreeing tells you the arithmetic is sound, not that the assumption held. Which argues for buying the assumption outright, with a randomised test — and even that, it turns out, answers a narrower question than teams think.</p>
</section>
<section id="platforms-dont-want-the-average-effect-they-want-yours" class="level2">
<h2 class="anchored" data-anchor-id="platforms-dont-want-the-average-effect-they-want-yours">Platforms don’t want the average effect, they want yours</h2>
<p>Suppose the growth team had run the feature properly, splitting users into experimental groups before launch. That buys a clean average effect and stops there — frequently the least useful number, because the third question was never about the average. Below the feature helps newcomers exactly as much as it costs veterans, so the two cancel and the honest reading of the experiment is “ship nothing”. Fitting one model per arm and differencing at each user recovers the split that the average buried.</p>
<div id="c60306dd" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestRegressor</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">42</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">8_000</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>tenure <span class="op">=</span> rng.uniform(<span class="dv">0</span>, <span class="dv">1</span>, n)  <span class="co"># 0 = brand new user, 1 = long-time power user</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>variant <span class="op">=</span> rng.binomial(<span class="dv">1</span>, <span class="fl">0.5</span>, n)  <span class="co"># a clean 50/50 split: no confounding at all</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co"># The feature helps newcomers and annoys veterans; averaged over users it cancels.</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>effect <span class="op">=</span> <span class="fl">0.60</span> <span class="op">-</span> <span class="fl">1.20</span> <span class="op">*</span> tenure</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>spend <span class="op">=</span> <span class="dv">30</span> <span class="op">+</span> <span class="dv">16</span> <span class="op">*</span> tenure <span class="op">+</span> variant <span class="op">*</span> effect <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="fl">1.2</span>, n)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>measured <span class="op">=</span> <span class="bu">round</span>(spend[variant <span class="op">==</span> <span class="dv">1</span>].mean() <span class="op">-</span> spend[variant <span class="op">==</span> <span class="dv">0</span>].mean(), <span class="dv">2</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"measured average effect :"</span>, measured)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="co"># One model per arm. Their gap at the same user is that user's predicted effect.</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit(arm):</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> tenure[variant <span class="op">==</span> arm][:, <span class="va">None</span>]</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> RandomForestRegressor(min_samples_leaf<span class="op">=</span><span class="dv">50</span>, random_state<span class="op">=</span><span class="dv">0</span>).fit(</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>        X, spend[variant <span class="op">==</span> arm]</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>ite <span class="op">=</span> fit(<span class="dv">1</span>).predict(tenure[:, <span class="va">None</span>]) <span class="op">-</span> fit(<span class="dv">0</span>).predict(tenure[:, <span class="va">None</span>])</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"newest quartile         :"</span>, <span class="bu">round</span>(ite[tenure <span class="op">&lt;</span> <span class="fl">0.25</span>].mean(), <span class="dv">2</span>))</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"longest-tenured quartile:"</span>, <span class="bu">round</span>(ite[tenure <span class="op">&gt;</span> <span class="fl">0.75</span>].mean(), <span class="dv">2</span>))</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"share with positive lift:"</span>, <span class="bu">round</span>((ite <span class="op">&gt;</span> <span class="dv">0</span>).mean(), <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>measured average effect : 0.01
newest quartile         : 0.56
longest-tenured quartile: -0.49
share with positive lift: 0.49</code></pre>
</div>
</div>
<p>An average of one cent described nobody: the model puts the newest quartile at 56 cents a month and the longest-tenured at minus 49, against a truth of plus and minus 45 — the direction and the split are right, the magnitudes run hot, for reasons the end of this section makes precise. Shipping to everyone spends the second group to buy the first. Plotting the per-user estimate against tenure shows how completely the average hides the shape it came from.</p>
<div id="0f434204" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>order <span class="op">=</span> np.argsort(tenure)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>t_sorted, ite_sorted <span class="op">=</span> tenure[order], ite[order]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>crossing <span class="op">=</span> <span class="fl">0.60</span> <span class="op">/</span> <span class="fl">1.20</span>  <span class="co"># tenure at which the true effect changes sign</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>lo, hi <span class="op">=</span> ite[tenure <span class="op">&lt;</span> <span class="fl">0.25</span>].mean(), ite[tenure <span class="op">&gt;</span> <span class="fl">0.75</span>].mean()</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>label_box <span class="op">=</span> <span class="bu">dict</span>(facecolor<span class="op">=</span><span class="st">"white"</span>, edgecolor<span class="op">=</span><span class="st">"none"</span>, alpha<span class="op">=</span><span class="fl">0.85</span>, pad<span class="op">=</span><span class="fl">1.8</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.6</span>, <span class="fl">3.8</span>))</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>ax.axvspan(<span class="dv">0</span>, crossing, color<span class="op">=</span>PURPLE, alpha<span class="op">=</span><span class="fl">0.06</span>, zorder<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>ax.axvline(crossing, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">1.0</span>, ls<span class="op">=</span>(<span class="dv">0</span>, (<span class="dv">4</span>, <span class="dv">3</span>)), zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>ax.plot(t_sorted, ite_sorted, color<span class="op">=</span>PURPLE, lw<span class="op">=</span><span class="fl">1.1</span>, alpha<span class="op">=</span><span class="fl">0.55</span>, zorder<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"predicted per-user effect"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>ax.plot(t_sorted, <span class="fl">0.60</span> <span class="op">-</span> <span class="fl">1.20</span> <span class="op">*</span> t_sorted, color<span class="op">=</span>INK, lw<span class="op">=</span><span class="fl">1.5</span>, ls<span class="op">=</span>(<span class="dv">0</span>, (<span class="dv">5</span>, <span class="dv">3</span>)), zorder<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"true effect"</span>)</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>ax.axhline(measured, color<span class="op">=</span>ACCENT, lw<span class="op">=</span><span class="fl">1.8</span>, ls<span class="op">=</span><span class="st">":"</span>, zorder<span class="op">=</span><span class="dv">5</span>,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>           label<span class="op">=</span><span class="ss">f"what the A/B test reported: $</span><span class="sc">{</span>measured<span class="sc">:+.2f}</span><span class="ss">"</span>)</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a><span class="co"># The two quartile averages, drawn where they actually apply.</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>ax.hlines(lo, <span class="dv">0</span>, <span class="fl">0.25</span>, color<span class="op">=</span>ACCENT, lw<span class="op">=</span><span class="dv">3</span>, zorder<span class="op">=</span><span class="dv">6</span>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>ax.hlines(hi, <span class="fl">0.75</span>, <span class="dv">1</span>, color<span class="op">=</span>ACCENT, lw<span class="op">=</span><span class="dv">3</span>, zorder<span class="op">=</span><span class="dv">6</span>)</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">0.125</span>, lo <span class="op">+</span> <span class="fl">0.16</span>, <span class="ss">f"newest quartile  $</span><span class="sc">{</span>lo<span class="sc">:+.2f}</span><span class="ss">"</span>, color<span class="op">=</span>ACCENT, fontsize<span class="op">=</span><span class="dv">9</span>,</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>        ha<span class="op">=</span><span class="st">"center"</span>, zorder<span class="op">=</span><span class="dv">7</span>, bbox<span class="op">=</span>label_box)</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>ax.text(<span class="fl">0.875</span>, hi <span class="op">-</span> <span class="fl">0.24</span>, <span class="ss">f"longest-tenured  $</span><span class="sc">{</span>hi<span class="sc">:+.2f}</span><span class="ss">"</span>, color<span class="op">=</span>ACCENT, fontsize<span class="op">=</span><span class="dv">9</span>,</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>        ha<span class="op">=</span><span class="st">"center"</span>, zorder<span class="op">=</span><span class="dv">7</span>, bbox<span class="op">=</span>label_box)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>ax.text(crossing <span class="op">-</span> <span class="fl">0.02</span>, ite_sorted.<span class="bu">min</span>() <span class="op">*</span> <span class="fl">1.05</span>, <span class="st">"ship to this side "</span>, color<span class="op">=</span>MUTED,</span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>        fontsize<span class="op">=</span><span class="dv">9</span>, ha<span class="op">=</span><span class="st">"right"</span>, style<span class="op">=</span><span class="st">"italic"</span>, zorder<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"tenure  (0 = brand new, 1 = long-time power user)"</span>, color<span class="op">=</span>MUTED, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"effect on monthly spend ($)"</span>, color<span class="op">=</span>MUTED, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>ax.set_xlim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>ax.yaxis.grid(<span class="va">True</span>, color<span class="op">=</span>GRID, lw<span class="op">=</span><span class="fl">0.7</span>, zorder<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a>ax.tick_params(colors<span class="op">=</span>MUTED, labelsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> side <span class="kw">in</span> (<span class="st">"top"</span>, <span class="st">"right"</span>):</span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>    ax.spines[side].set_visible(<span class="va">False</span>)</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> side <span class="kw">in</span> (<span class="st">"bottom"</span>, <span class="st">"left"</span>):</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a>    ax.spines[side].set_color(GRID)</span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>, loc<span class="op">=</span><span class="st">"upper right"</span>, labelcolor<span class="op">=</span>INK)</span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="index_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img" alt="Line chart against tenure. A straight dashed line shows the true effect falling from +$0.60 for the newest users to -$0.60 for the longest-tenured, crossing zero at the midpoint. A jagged purple line, the per-user forest estimate, tracks it loosely but swings between about +$1.2 and -$1.0. A flat dotted line marks the A/B test's reported average of about one cent."></p>
<figcaption>Per-user predicted effect against tenure, with the experiment’s headline average laid over it. The reported figure describes no user in the sample.</figcaption>
</figure>
</div>
</div>
</div>
<p>The reported average is a flat line through a curve that spans more than a dollar. This is uplift modelling, the machinery behind targeted rollouts and personalisation, and it turns “ship nothing” into a gate: ship where the predicted effect is positive, which is about half the userbase. Because this is a simulation, the gate can be graded against the effect it was aiming at.</p>
<section id="caveat-the-uplift-model-overstates-its-own-win" class="level3">
<h3 class="anchored" data-anchor-id="caveat-the-uplift-model-overstates-its-own-win">Caveat: the uplift model overstates its own win</h3>
<p>The obvious way to size the prize is to add up the predicted effects of the users you chose to treat. That number is inflated, and by the post’s own mechanism: those users were chosen <em>because</em> their estimate came out high, so the selection keeps the upward noise and discards the downward. It is the winner’s curse, and the simulation can price it.</p>
<div id="40656217" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>AUDIENCE <span class="op">=</span> <span class="dv">2_000_000</span>  <span class="co"># monthly actives</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>ship <span class="op">=</span> ite <span class="op">&gt;</span> <span class="dv">0</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> monthly(mask, per_user):</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> AUDIENCE <span class="op">*</span> per_user[mask].<span class="bu">sum</span>() <span class="op">/</span> n</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"promised by the model :"</span>, <span class="bu">round</span>(monthly(ship, ite)))  <span class="co"># sums the estimates</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"actually delivered    :"</span>, <span class="bu">round</span>(monthly(ship, effect)))  <span class="co"># sums the true effects</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"best possible gate    :"</span>, <span class="bu">round</span>(monthly(effect <span class="op">&gt;</span> <span class="dv">0</span>, effect)))</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"ship to everyone      :"</span>, <span class="bu">round</span>(monthly(np.ones(n, <span class="bu">bool</span>), effect)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>promised by the model : 393990
actually delivered    : 272321
best possible gate    : 304602
ship to everyone      : 10025</code></pre>
</div>
</div>
<p>Read off the estimates, the gate promises about $394k a month. It delivers $272k — a real win against shipping to everyone, which by construction is worth exactly nothing (the generating process cancels; the $10k the last line prints is sampling noise on eight thousand users, and flips sign with the seed) — but a third less than advertised, and only $32k short of what a gate with perfect knowledge could have managed. The gap between $394k and $272k is not a bug in the method; it is the same error the promo and the feature made, arriving one level up. A number computed from the same estimates that chose the audience is not evidence about that audience, and a product manager who books $394k against this rollout will miss the quarter by $122k.</p>
<p>What none of these figures price is the standing cost of the gate itself: two product experiences to design, support, document and eventually reconcile, forever. That cost is real, it is not in the experiment, and it is the part of the decision that stays the manager’s judgement rather than the model’s.</p>
</section>
</section>
<section id="every-method-is-a-machine-for-guessing-what-didnt-happen" class="level2">
<h2 class="anchored" data-anchor-id="every-method-is-a-machine-for-guessing-what-didnt-happen">Every method is a machine for guessing what didn’t happen</h2>
<p>Lined up, these methods all estimate the same unobservable thing: what would have happened otherwise. What separates them is the kind of as-if randomness each can claim. A trial claims it outright, owning the randomiser. Propensity weighting and the adjustment formula claim it conditionally — treatment is as good as random among users alike on everything recorded — which is why they agreed twice, once on the truth and once on a number that was $2.30 wrong. A DAG claims it structurally, asserting which arrows do not exist. Each is only as good as its claim, and the claim is an assumption about the world, not a result the data hands back.</p>
<p>That is the division of labour worth taking to a planning meeting. Pearl’s contribution is to make the assumption writable down, arguable, and occasionally refusable — “not identified” is an answer, and a more valuable one than a confident estimate of the wrong quantity. Rubin’s is to turn a licensed assumption into a number with error bars. Uplift’s is to notice that the number a platform acts on was never the average anyway — and then, when you total up its own promise, to demonstrate that the trap is recursive: every estimate used to <em>choose</em> something is optimistic about the thing it chose. The $2M budget, the engineering quarter and the $122k rollout gap all turned on which of these got done before the dashboard was read.</p>
<p>Which returns us to the switch. The toddler’s certainty came from the strongest claim available to anyone: they were the randomiser. Everything since — graphs, weights, two-model fits — buys back a fragment of that position from data somebody else generated. Worth remembering how much is reconstruction, and how casually a two-year-old had it.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li><strong>Michotte, A.</strong> — <em>The Perception of Causality</em> (1946): the launching effect, and causality as something seen rather than inferred.</li>
<li><strong>Gopnik, A. and colleagues</strong> — blicket detector studies on causal learning and intervention in preschoolers.</li>
<li><strong>Hume, D.</strong> — <em>A Treatise of Human Nature</em> (1739): constant conjunction, contiguity, temporal priority.</li>
<li><strong>Pearl, J.</strong> — <em>Causality</em> (2000) and <em>The Book of Why</em> (2018): DAGs, the <code>do</code> operator, the backdoor criterion, the ladder of causation.</li>
<li><strong>Neyman, J. and Rubin, D.</strong> — the potential outcomes framework; Rosenbaum and Rubin
<ol start="1983" type="1">
<li>on propensity scores.</li>
</ol></li>
<li><strong>Hernán, M. and Robins, J.</strong> — <em>Causal Inference: What If</em> (2020): the standard modern treatment of the adjustment formula and g-computation, after Robins (1986).</li>
<li><strong>VanderWeele, T. and Ding, P.</strong> — “Sensitivity Analysis in Observational Research: Introducing the E-Value” (2017): how much unmeasured confounding would be needed.</li>
<li><strong>Künzel, S. and colleagues</strong> — “Metalearners for estimating heterogeneous treatment effects” (2019): the one-model-per-arm construction used above.</li>
<li><strong>Woodward, J.</strong> — <em>Making Things Happen</em> (2003): the interventionist account of causal explanation.</li>
<li><strong>Chernozhukov, V. and colleagues</strong> — “Double/Debiased Machine Learning” (2018): using ML nuisance models without importing their bias.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/causality-from-toddlers-to-do-calculus/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>