{
  "hash": "dfd3f52caebbc9a9d4804c0aa8e4c547",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Lost in Translation: How Math Tribes Speak Different Languages (And Why Epidemiologists Hate MSE)\"\nsubtitle: \"Statisticians, epidemiologists, ML researchers, and mathematicians all say 'calibration' — and all mean different things. Here is a phrasebook, and one number they will fight over.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-07-24\"\ncategories: [Epidemiology, Statistics, Machine Learning, Mathematical Modeling, SIR Models, Python]\nimage: \"./cover.png\"\ntags: [SIR, MSE, Poisson, negative-log-likelihood, calibration, count-data, R0]\njupyter: tribes-blog\nformat:\n  html:\n    theme: cosmo\n    toc: true\n    toc-depth: 2\n    toc-location: left\n    code-fold: true\n    code-summary: \"Show the code\"\n    number-sections: true\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n\n![Lost in Translation](./cover.png)\n\n## Calibration across four fields\n\nThe word **calibration** names different procedures in statistics, epidemiology, machine learning, and mathematics. Cross-disciplinary work fails when the same term is used without checking definitions.\n\nCompanion post: [Training vs. Calibrating Epidemiological Models](../sir-training-vs-calibration/) draws *training* (fitting to match predictions) from *calibration* (pinning physically meaningful parameters for portability).\n\nThis post:\n\n- Phrasebook for shared terms across four tribes.\n- Worked example: MSE vs Poisson negative log-likelihood on count data, fitted to the same SIR model.\n\n## Phrasebook\n\nSame word, different meaning per field:\n\n| Concept | Statistician | Epidemiologist | ML / CS Researcher | Mathematician |\n|---|---|---|---|---|\n| **Mechanistic** | Parameters map to a data-generating process | Equations encode disease spread (SIR, contacts) | Hand-built simulator vs learned black box | Deterministic dynamical system (ODEs) |\n| **Stochastic** | Randomness in a probability distribution | Chance in who infects whom | Dropout, mini-batches, Monte Carlo | Process on a probability space |\n| **Interpretable** | Coefficients with effect size and CI | Biological parameters: $R_0$, incubation, generation time | Post-hoc rationalisation (SHAP, attention) | Closed form or provable property |\n| **Calibration** | Predicted probabilities match long-run frequencies | Tune mechanistic parameters to reproduce epidemics | Post-hoc score rescaling (Platt, temperature) | Constants chosen to meet boundary conditions |\n| **Training** | Estimation (ML, least squares) | Usually \"calibrating\" to surveillance data | Gradient descent on weights | Minimising an objective |\n| **NLL** | Negative log-likelihood (ML objective) | Loss respecting count generation | Cross-entropy | Functional to minimise |\n| **MSE** | Gaussian log-likelihood with constant variance | Default that ignores count variance structure | Standard regression loss ($L_2$) | Squared $L_2$ norm of residuals |\n\nMSE and NLL are interchangeable menu entries in ML; the statistician treats them as the same object under different noise assumptions; the epidemiologist treats MSE as a route to wrong $R_0$ on count data.\n\n## Parameter interpretation\n\nDisagreement is about what a fitted parameter represents:\n\n- **ML training:** weights are coordinates with no external referent; permuting or rescaling can leave the function unchanged. Goal: small loss on observed data.\n- **Epidemiological calibration:** $\\beta$ (transmission) and $\\gamma$ (recovery) are biological claims. $R_0 = \\beta/\\gamma$ is the basic reproduction number — threshold for outbreak growth vs decay.\n\n**Structural portability:** calibrated $(\\beta, \\gamma)$ carry to new cities, pathogens, and interventions; trained weights do not. See [companion post](../sir-training-vs-calibration/) for a transfer example.\n\nLeo Breiman's [*Statistical Modeling: The Two Cultures*](https://www2.math.uu.se/~thulin/mm/breiman.pdf) (2001): data-modeling culture (stochastic model, interpret parameters) vs algorithmic-modeling culture (black box, prediction accuracy). The four-tribe confusion maps onto that split.\n\n**Loss function implication:** when parameters are interpretable, the loss is an assumption about how data were generated. A wrong loss yields a plausible, wrong $R_0$.\n\n## Boarding-school influenza data\n\n**Provenance:** Daily counts of boys confined to bed during a January 1978 influenza outbreak at a boys' boarding school in northern England. Published as \"Influenza in a boarding school\" (*BMJ* 1978;1:587). Standard SIR teaching dataset.\n\n**Why this dataset:** closed population ($N = 763$), near-homogeneous mixing, short duration (14 days). Conditions match SIR assumptions more closely than typical field data.\n\n**Objective:** estimate $R_0$ by fitting $(\\beta, \\gamma)$ to daily infected counts.\n\n**Downstream impact:** $R_0$ drives school closure, vaccine sizing, and outbreak-control decisions. A 6% bias in $R_0$ mis-scales intervention cost.\n\n**Why the loss matters here:** observations are counts (variance grows with mean), span 1–255, and $n = 14$ — no averaging rescues a wrong noise model.\n\nSetup: imports and colour convention (red = MSE, blue = Poisson NLL).\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code}\n%config InlineBackend.figure_format = 'retina'\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy.integrate import odeint\nfrom scipy.optimize import minimize\nfrom scipy.special import gammaln\n\nplt.rcParams.update({\n    \"figure.dpi\": 140,\n    \"savefig.dpi\": 140,\n    \"font.size\": 11,\n    \"axes.grid\": True,\n    \"grid.alpha\": 0.3,\n    \"axes.spines.top\": False,\n    \"axes.spines.right\": False,\n})\nsns.set_palette(\"deep\")\n\nMSE_COLOR = \"#d1495b\"   # red\nNLL_COLOR = \"#2e6f95\"   # blue\nDATA_COLOR = \"#20232a\"  # near-black\n```\n:::\n\n\nThe outbreak itself is short enough to type out in full: the day number, and the number of boys confined to bed on that day.\n\n::: {#cell-data .cell execution_count=2}\n``` {.python .cell-code}\nN = 763  # total boys in the school (closed population)\n\noutbreak = pd.DataFrame({\n    \"day\":      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],\n    \"infected\": [1, 3, 7, 24, 73, 192, 238, 255, 231, 150, 72, 29, 11, 4],\n})\noutbreak.T\n```\n\n::: {#data .cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n      <th>3</th>\n      <th>4</th>\n      <th>5</th>\n      <th>6</th>\n      <th>7</th>\n      <th>8</th>\n      <th>9</th>\n      <th>10</th>\n      <th>11</th>\n      <th>12</th>\n      <th>13</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>day</th>\n      <td>1</td>\n      <td>2</td>\n      <td>3</td>\n      <td>4</td>\n      <td>5</td>\n      <td>6</td>\n      <td>7</td>\n      <td>8</td>\n      <td>9</td>\n      <td>10</td>\n      <td>11</td>\n      <td>12</td>\n      <td>13</td>\n      <td>14</td>\n    </tr>\n    <tr>\n      <th>infected</th>\n      <td>1</td>\n      <td>3</td>\n      <td>7</td>\n      <td>24</td>\n      <td>73</td>\n      <td>192</td>\n      <td>238</td>\n      <td>255</td>\n      <td>231</td>\n      <td>150</td>\n      <td>72</td>\n      <td>29</td>\n      <td>11</td>\n      <td>4</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nFourteen daily infected counts. Rise to peak 255 (day 8), then decline.\n\n## MSE vs Poisson NLL on count data\n\nTwo ingredients: a curve family (SIR) and a fit criterion. Both fits use the same model; only the loss differs.\n\n### SIR model\n\nCompartment flows:\n\n$$\n\\frac{dS}{dt} = -\\beta \\frac{S I}{N}, \\qquad\n\\frac{dI}{dt} = \\beta \\frac{S I}{N} - \\gamma I, \\qquad\n\\frac{dR}{dt} = \\gamma I .\n$$\n\nIntegrating yields $I(t; \\beta, \\gamma)$. Early phase ($S \\approx N$): exponential growth at rate $r = \\beta - \\gamma$.\n\n### Mean squared error\n\n$$\n\\mathrm{MSE}(\\beta, \\gamma) = \\frac{1}{T} \\sum_{t=1}^{T} \\Big( y_t - I(t; \\beta, \\gamma) \\Big)^2 .\n$$\n\nEquivalent to maximum likelihood under constant-variance Gaussian noise:\n\n$$\ny_t \\sim \\mathcal{N}\\big(I(t;\\beta,\\gamma),\\ \\sigma^2\\big), \\quad \\sigma^2 \\text{ fixed}.\n$$\n\nPoor fit to count data: variance at day 2 ($y = 3$) cannot equal variance at day 8 ($y = 255$).\n\n### Poisson negative log-likelihood\n\nIndependent Poisson counts at rate $\\lambda_t = I(t; \\beta, \\gamma)$:\n\n$$\nP(Y_t = y_t \\mid \\lambda_t) = \\frac{\\lambda_t^{\\,y_t}\\, e^{-\\lambda_t}}{y_t!}.\n$$\n\nNegative log-likelihood (minimised for ML):\n\n$$\n\\mathrm{NLL}(\\beta, \\gamma) = \\sum_{t=1}^{T} \\Big[ \\lambda_t - y_t \\log \\lambda_t + \\log(y_t!) \\Big] .\n$$\n\nPoisson property: $\\mathrm{Var}(Y_t) = \\lambda_t$.\n\n### Second-order link\n\nPoisson NLL approximates weighted least squares:\n\n$$\n\\mathrm{NLL} \\;\\approx\\; \\text{const} + \\tfrac{1}{2}\\sum_{t=1}^{T} \\frac{\\big(y_t - \\lambda_t\\big)^2}{\\lambda_t}.\n$$\n\n- MSE: equal weight per day; peak days dominate (squared residuals).\n- NLL: weight $1/\\lambda_t$; low-count days retain influence.\n\n## Fitting under both losses\n\nProcedure: hold data and SIR model fixed; change only the loss; compare $R_0 = \\beta/\\gamma$.\n\n### SIR simulator\n\n`odeint` integrates from $S_0 = N - 1$, $I_0 = 1$, $R_0 = 0$. Infected column floored above zero for log terms.\n\n::: {#sir-model .cell execution_count=3}\n``` {.python .cell-code}\ndef sir_infected(params, days, N=N, I0=1.0):\n    \"\"\"Integrate the SIR ODEs and return predicted infected counts on `days`.\"\"\"\n    beta, gamma = params\n\n    def deriv(y, t):\n        S, I, R = y\n        dS = -beta * S * I / N\n        dI = beta * S * I / N - gamma * I\n        dR = gamma * I\n        return [dS, dI, dR]\n\n    y0 = [N - I0, I0, 0.0]          # state at the first day: one index case\n    sol = odeint(deriv, y0, days)\n    return np.clip(sol[:, 1], 1e-8, None)   # infected column, floored positive\n```\n:::\n\n\n### Loss functions\n\nBoth losses reject negative $(\\beta, \\gamma)$. `gammaln(observed + 1)` computes $\\log(y_t!)$ without overflow; it does not shift the minimum.\n\n### Optimisation\n\nBoth fits start from $(\\beta, \\gamma) = (2.0, 0.5)$, Nelder-Mead. Summary: $\\beta$, $\\gamma$, $R_0 = \\beta/\\gamma$, infectious period $1/\\gamma$.\n\n::: {#objectives .cell execution_count=4}\n``` {.python .cell-code}\ndays = outbreak[\"day\"].to_numpy(dtype=float)\nobserved = outbreak[\"infected\"].to_numpy(dtype=float)\n\ndef mse_loss(params):\n    if params[0] <= 0 or params[1] <= 0:      # keep rates physical\n        return 1e12\n    lam = sir_infected(params, days)\n    return np.mean((observed - lam) ** 2)\n\ndef poisson_nll(params):\n    if params[0] <= 0 or params[1] <= 0:\n        return 1e12\n    lam = sir_infected(params, days)\n    return np.sum(lam - observed * np.log(lam) + gammaln(observed + 1))\n```\n:::\n\n\nBoth fits start from $(\\beta, \\gamma) = (2.0, 0.5)$, Nelder-Mead.\n\n::: {#cell-optimize .cell execution_count=5}\n``` {.python .cell-code}\nstart = [2.0, 0.5]   # a plausible flu-like starting guess\nfit_mse = minimize(mse_loss,     start, method=\"Nelder-Mead\")\nfit_nll = minimize(poisson_nll,  start, method=\"Nelder-Mead\")\n\ndef summarise(name, res):\n    beta, gamma = res.x\n    return {\n        \"loss\": name,\n        \"beta\": beta,\n        \"gamma\": gamma,\n        \"R0\": beta / gamma,\n        \"infectious_period_days\": 1.0 / gamma,\n    }\n\nsummary = pd.DataFrame([\n    summarise(\"MSE\",         fit_mse),\n    summarise(\"Poisson NLL\", fit_nll),\n])\nsummary.round(3)\n```\n\n::: {#optimize .cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>loss</th>\n      <th>beta</th>\n      <th>gamma</th>\n      <th>R0</th>\n      <th>infectious_period_days</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>MSE</td>\n      <td>1.703</td>\n      <td>0.518</td>\n      <td>3.288</td>\n      <td>1.931</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Poisson NLL</td>\n      <td>1.756</td>\n      <td>0.566</td>\n      <td>3.103</td>\n      <td>1.767</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nResults:\n\n- MSE: $R_0 \\approx 3.29$.\n- Poisson NLL: $R_0 \\approx 3.10$.\n- Gap ≈ 0.19, driven mainly by $\\gamma$ (MSE ≈ 0.52 vs NLL ≈ 0.57).\n\n### Fit comparison\n\nLeft panel: linear scale. Right panel: log scale (equal relative errors appear equal-sized).\n\n::: {#cell-fig-fits .cell execution_count=6}\n``` {.python .cell-code}\nfine_days = np.linspace(1, 14, 200)\ncurve_mse = sir_infected(fit_mse.x, fine_days)\ncurve_nll = sir_infected(fit_nll.x, fine_days)\nR0_mse = fit_mse.x[0] / fit_mse.x[1]\nR0_nll = fit_nll.x[0] / fit_nll.x[1]\n\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4.9))\nfor ax in (ax1, ax2):\n    ax.scatter(days, observed, color=DATA_COLOR, s=48, zorder=5,\n               label=\"Observed (boys confined to bed)\")\n    ax.plot(fine_days, curve_mse, \"--\", color=MSE_COLOR, lw=2.3,\n            label=f\"MSE fit   ($R_0$ = {R0_mse:.2f})\")\n    ax.plot(fine_days, curve_nll, \"-\", color=NLL_COLOR, lw=2.3,\n            label=f\"Poisson NLL fit   ($R_0$ = {R0_nll:.2f})\")\n    ax.set_xlabel(\"Day of outbreak\")\n\nax1.set_ylabel(\"Infected\")\nax1.set_title(\"Linear scale\")\nax1.legend(frameon=False, fontsize=9, loc=\"upper right\")\n\nax1.annotate(\"MSE leans on the tall peak\\n(largest squared errors live here)\",\n             xy=(7.4, 249), xytext=(8.2, 300), fontsize=8.5, color=MSE_COLOR,\n             arrowprops=dict(arrowstyle=\"->\", color=MSE_COLOR, lw=1.3))\nax1.annotate(\"...and pays for it by\\novershooting the decline\",\n             xy=(12.8, 40), xytext=(9.6, 150), fontsize=8.5, color=MSE_COLOR,\n             arrowprops=dict(arrowstyle=\"->\", color=MSE_COLOR, lw=1.3))\n\nax2.set_yscale(\"log\")\nax2.set_ylabel(\"Infected (log scale)\")\nax2.set_title(\"Log scale — the count-data view\")\nax2.annotate(\"relative error is what\\nyou actually feel here\",\n             xy=(13, curve_mse[-1]), xytext=(8.5, 4), fontsize=8.5, color=MSE_COLOR,\n             arrowprops=dict(arrowstyle=\"->\", color=MSE_COLOR, lw=1.3))\n\nfig.suptitle(\"Same data, same model, two loss functions\", fontsize=13, weight=\"bold\")\nfig.tight_layout()\nfig.savefig(\"cover.png\", dpi=200, bbox_inches=\"tight\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The same 14 dots, the same SIR model, two loss functions. MSE (dashed red) leans on the tall peak and overshoots the low-count tail; Poisson NLL (solid blue) spreads its attention across every magnitude. The right panel puts the y-axis on a log scale — the natural habitat of count data — where the tail disagreement is impossible to miss.](index_files/figure-html/fig-fits-output-1.png){#fig-fits width=1663 height=677}\n:::\n:::\n\n\nOn linear scale the curves look similar. On log scale MSE overshoots the decline (days 11–14); Poisson NLL tracks low counts.\n\n## Monte Carlo bias check\n\nSingle-dataset gap could be sampling noise. Simulation: treat observed counts as Poisson means; draw 200 replicates; fit each under both losses.\n\nGenerating process: $y_t \\sim \\mathrm{Poisson}(\\lambda_t)$ with $\\lambda_t$ equal to observed counts. Poisson variation matches count-data generation.\n\nExpected bias: peak days carry highest Poisson variance ($\\sqrt{255} \\approx 16$ at day 8); MSE weights absolute residuals, overweighting noisy peak days. MSE $R_0$ should sit systematically high.\n\n::: {#cell-monte-carlo .cell execution_count=7}\n``` {.python .cell-code}\nrng = np.random.default_rng(0)\ntruth = observed\nreps = 200\nr0_mse, r0_nll = [], []\n\nfor _ in range(reps):\n    y = rng.poisson(truth).astype(float)\n    y[y < 1] = 1.0                      # keep at least one case for the log terms\n\n    def mse_l(p, y=y):\n        if p[0] <= 0 or p[1] <= 0:\n            return 1e12\n        return np.mean((y - sir_infected(p, days)) ** 2)\n\n    def nll_l(p, y=y):\n        if p[0] <= 0 or p[1] <= 0:\n            return 1e12\n        lam = sir_infected(p, days)\n        return np.sum(lam - y * np.log(lam) + gammaln(y + 1))\n\n    m = minimize(mse_l, start, method=\"Nelder-Mead\").x\n    n = minimize(nll_l, start, method=\"Nelder-Mead\").x\n    r0_mse.append(m[0] / m[1])\n    r0_nll.append(n[0] / n[1])\n\nr0_mse = np.array(r0_mse)\nr0_nll = np.array(r0_nll)\n\nmc = pd.DataFrame({\n    \"loss\": [\"MSE\", \"Poisson NLL\"],\n    \"mean_R0\": [r0_mse.mean(), r0_nll.mean()],\n    \"sd_R0\":   [r0_mse.std(),  r0_nll.std()],\n    \"p5\":      [np.percentile(r0_mse, 5),  np.percentile(r0_nll, 5)],\n    \"p95\":     [np.percentile(r0_mse, 95), np.percentile(r0_nll, 95)],\n})\nmc.round(3)\n```\n\n::: {#monte-carlo .cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>loss</th>\n      <th>mean_R0</th>\n      <th>sd_R0</th>\n      <th>p5</th>\n      <th>p95</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>MSE</td>\n      <td>3.294</td>\n      <td>0.079</td>\n      <td>3.160</td>\n      <td>3.411</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Poisson NLL</td>\n      <td>3.106</td>\n      <td>0.062</td>\n      <td>3.007</td>\n      <td>3.188</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nHistogram comparison across 200 replicates:\n\n::: {#cell-fig-r0 .cell execution_count=8}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7.6, 4.2))\nbins = np.linspace(2.9, 3.55, 30)\nax.hist(r0_mse, bins=bins, alpha=0.65, color=MSE_COLOR, label=\"MSE\")\nax.hist(r0_nll, bins=bins, alpha=0.65, color=NLL_COLOR, label=\"Poisson NLL\")\nax.axvline(r0_mse.mean(), color=MSE_COLOR, ls=\"--\", lw=1.6)\nax.axvline(r0_nll.mean(), color=NLL_COLOR, ls=\"--\", lw=1.6)\nax.set_xlabel(\"Estimated $R_0$\")\nax.set_ylabel(\"Count across 200 noisy outbreaks\")\nax.set_title(\"MSE systematically over-estimates $R_0$\")\nax.legend(frameon=False)\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Estimated R0 across 200 synthetic outbreaks with fresh Poisson noise each time. MSE (red) sits systematically higher than Poisson NLL (blue); the two distributions barely overlap. Choosing the loss shifts the headline number by more than either estimator's own sampling spread.](index_files/figure-html/fig-r0-output-1.png){#fig-r0 width=1047 height=568}\n:::\n:::\n\n\nFindings:\n\n- MSE mean $R_0 \\approx 3.29$; Poisson NLL mean $\\approx 3.11$.\n- Each estimator's sampling spread ≈ 0.06–0.08.\n- Loss-choice bias exceeds either estimator's statistical uncertainty.\n- More data tightens CIs but does not remove loss-induced bias when the wrong noise model is used.\n\n## Summary\n\n- Loss function = claim about data generation. MSE: constant-variance Gaussian. Poisson NLL: count variance proportional to mean.\n- On this count data the difference moves $R_0$ by more than sampling error.\n- Cross-field vocabulary (\"calibration\", \"training\", \"NLL\") maps to different procedures; verify definitions before comparing fits.\n\n## References\n\n- Breiman, L. (2001). [*Statistical Modeling: The Two Cultures.*](https://www2.math.uu.se/~thulin/mm/breiman.pdf) *Statistical Science* 16(3), 199–231.\n- Kermack, W. O., and McKendrick, A. G. (1927). *A Contribution to the Mathematical Theory of Epidemics.* *Proceedings of the Royal Society of London A* 115(772), 700–721.\n- \"Influenza in a boarding school.\" (1978). *British Medical Journal* 1(6112), 587.\n- McCullagh, P., and Nelder, J. A. (1989). *Generalized Linear Models* (2nd ed.). Chapman & Hall/CRC.\n- Kalia, R. [*Training vs. Calibrating Epidemiological Models*](../sir-training-vs-calibration/).\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}