<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-08-18">
<meta name="description" content="Quenouille’s bias eraser and Tukey’s pseudovalues, worked through four examples: ratio bias in small cohorts, promo-abuse syndicates, censored survival regression, and clinical biomarker stability — with interactive widgets that run in the browser.">

<title>The Statistical Jackknife – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a57418ee22da850e2975fefbdbd2f646.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">The Statistical Jackknife</h1>
            <p class="subtitle lead">Leave out one observation at a time and a small-sample estimate stops lying to you. The same n passes that cancel its bias also name the single data point holding the answer up — a fraud ring’s hub, a fragile drug target, a censored retention curve.</p>
                  <div>
        <div class="description">
          Quenouille’s bias eraser and Tukey’s pseudovalues, worked through four examples: ratio bias in small cohorts, promo-abuse syndicates, censored survival regression, and clinical biomarker stability — with interactive widgets that run in the browser.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Resampling</div>
                <div class="quarto-category">Growth-Engineering</div>
                <div class="quarto-category">Bioinformatics</div>
                <div class="quarto-category">Python</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 18, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-ratio-computed-from-five-customers-comes-out-systematically-too-high" id="toc-a-ratio-computed-from-five-customers-comes-out-systematically-too-high" class="nav-link active" data-scroll-target="#a-ratio-computed-from-five-customers-comes-out-systematically-too-high">A ratio computed from five customers comes out systematically too high</a></li>
  <li><a href="#quenouilles-trick-cancels-the-leading-error-term" id="toc-quenouilles-trick-cancels-the-leading-error-term" class="nav-link" data-scroll-target="#quenouilles-trick-cancels-the-leading-error-term">Quenouille’s trick cancels the leading error term</a></li>
  <li><a href="#tukey-turns-one-estimate-into-n-per-observation-fingerprints" id="toc-tukey-turns-one-estimate-into-n-per-observation-fingerprints" class="nav-link" data-scroll-target="#tukey-turns-one-estimate-into-n-per-observation-fingerprints">Tukey turns one estimate into <span class="math inline">\(n\)</span> per-observation fingerprints</a></li>
  <li><a href="#in-growth-systems-jackknife-influence-catches-fraud-rings-that-averages-hide" id="toc-in-growth-systems-jackknife-influence-catches-fraud-rings-that-averages-hide" class="nav-link" data-scroll-target="#in-growth-systems-jackknife-influence-catches-fraud-rings-that-averages-hide">In growth systems, jackknife influence catches fraud rings that averages hide</a></li>
  <li><a href="#in-cohort-survival-pseudovalues-turn-censored-curves-into-ordinary-regressions" id="toc-in-cohort-survival-pseudovalues-turn-censored-curves-into-ordinary-regressions" class="nav-link" data-scroll-target="#in-cohort-survival-pseudovalues-turn-censored-curves-into-ordinary-regressions">In cohort survival, pseudovalues turn censored curves into ordinary regressions</a></li>
  <li><a href="#in-clinical-omics-leave-one-out-variance-stops-multi-million-dollar-false-targets" id="toc-in-clinical-omics-leave-one-out-variance-stops-multi-million-dollar-false-targets" class="nav-link" data-scroll-target="#in-clinical-omics-leave-one-out-variance-stops-multi-million-dollar-false-targets">In clinical omics, leave-one-out variance stops multi-million dollar false targets</a></li>
  <li><a href="#the-jackknife-shatters-on-non-smooth-statistics-like-the-median" id="toc-the-jackknife-shatters-on-non-smooth-statistics-like-the-median" class="nav-link" data-scroll-target="#the-jackknife-shatters-on-non-smooth-statistics-like-the-median">The jackknife shatters on non-smooth statistics like the median</a>
  <ul class="collapse">
  <li><a href="#the-remedy-delete-more-than-one" id="toc-the-remedy-delete-more-than-one" class="nav-link" data-scroll-target="#the-remedy-delete-more-than-one">The remedy: delete more than one</a></li>
  </ul></li>
  <li><a href="#jackknife-or-bootstrap-deterministic-speed-against-stochastic-generality" id="toc-jackknife-or-bootstrap-deterministic-speed-against-stochastic-generality" class="nav-link" data-scroll-target="#jackknife-or-bootstrap-deterministic-speed-against-stochastic-generality">Jackknife or bootstrap: deterministic speed against stochastic generality</a></li>
  <li><a href="#when-to-reach-for-the-jackknife-in-your-pocket" id="toc-when-to-reach-for-the-jackknife-in-your-pocket" class="nav-link" data-scroll-target="#when-to-reach-for-the-jackknife-in-your-pocket">When to reach for the jackknife in your pocket</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/statistical-jackknife/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p><img src="./cover.png" class="img-fluid" alt="Cover card reading The Statistical Jackknife, over a solid purple background."></p>
<p>You compute a number from a handful of data points — revenue per visit for last month’s cohort, the fold-change of a gene between tumour and healthy tissue — and you write it into a deck as though it were the answer. Usually it isn’t, and the interesting part is that it is wrong in a direction you could have worked out in advance. Divide average revenue by average visits over five customers and the result comes out too high. Draw a fresh five customers and it comes out too high again. The error is not noise that averages away; it is a systematic tilt built into the arithmetic of dividing one estimate by another.</p>
<p>There is a second, sharper problem hiding underneath. One concealed outlier — a bot account, a mishandled tissue sample — can carry an estimate almost by itself, and nothing in the number tells you that. Teams greenlight unprofitable acquisition channels and commit years of laboratory budget to drug targets that rest on a single patient.</p>
<p>The modern answer to both is the bootstrap: draw thousands of random resamples and watch the estimate wobble. But decades before a computer could hold ten thousand artificial worlds in memory, Maurice Quenouille and John Tukey found a deterministic shortcut. <strong>Perturb the dataset by leaving out exactly one observation at a time.</strong> Doing that <span class="math inline">\(n\)</span> times cancels the leading systematic error, and — this is Tukey’s contribution — the <span class="math inline">\(n\)</span> leftover quantities turn out to be a per-observation ledger of who moved the answer and by how much. No random numbers, no seed, no tuning.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
What is in a name?
</div>
</div>
<div class="callout-body-container callout-body">
<p>In 1958, John Tukey named the method after the pocket <strong>jackknife</strong>. It is not a surgeon’s scalpel, sharpened for one known parametric distribution. It is the rough all-purpose blade you carry anyway, and it handles most of what you meet in the field.</p>
</div>
</div>
<section id="a-ratio-computed-from-five-customers-comes-out-systematically-too-high" class="level2">
<h2 class="anchored" data-anchor-id="a-ratio-computed-from-five-customers-comes-out-systematically-too-high">A ratio computed from five customers comes out systematically too high</h2>
<p>Start with the simplest estimator that misbehaves: a ratio of two averages. Suppose you want revenue per visit for a cohort — total revenue divided by total visits, or equivalently average revenue divided by average visits. Each average is individually unbiased. Their ratio is not, because dividing is a curved operation: the denominator’s random wobble hurts you more when it lands low than it helps when it lands high, and the two do not cancel. The distortion is largest when the cohort is small, which is exactly when someone is trying to read an early signal from it.</p>
<p>The data below is simulated, and it has to be. To <em>measure</em> a bias you need to know the true value being missed, and no real dataset hands you that. So we generate customers from a known process: weekly visits per customer as a Gamma draw with mean 10, and weekly revenue as an independent Gamma draw with mean 25. The true revenue-per-visit is therefore exactly 2.50 by construction. Gamma is the right stand-in because both quantities are positive and right-skewed the way real spend and engagement counts are, and drawing revenue independently of visits reflects the ordinary case where a customer’s spend is not simply proportional to how often they show up. The decision downstream is budget: revenue-per-visit feeds payback horizons, so a metric that reads high on small cohorts systematically flatters new channels and keeps money flowing to ones that never pay back.</p>
<p>We run 50,000 synthetic cohorts at each size and record how far the average estimate sits from 2.50 — once for the plug-in ratio, once for its jackknife correction.</p>
<div id="bbac626d" class="cell" data-execution_count="2">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Synthetic cohorts: visits ~ Gamma(mean 10), revenue ~ Gamma(mean 25), drawn independently,</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># so revenue-per-visit is exactly 2.50 and any departure from it is bias, not noise.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>true_mu_x, true_mu_y <span class="op">=</span> <span class="fl">10.0</span>, <span class="fl">25.0</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>true_ratio <span class="op">=</span> true_mu_y <span class="op">/</span> true_mu_x  <span class="co"># exactly 2.50</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>sample_sizes <span class="op">=</span> [<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">40</span>, <span class="dv">80</span>, <span class="dv">160</span>]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>n_sims <span class="op">=</span> <span class="dv">50_000</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>plugin_biases <span class="op">=</span> []</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>jackknife_biases <span class="op">=</span> []</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n <span class="kw">in</span> sample_sizes:</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> np.random.gamma(shape<span class="op">=</span><span class="fl">5.0</span>, scale<span class="op">=</span><span class="fl">2.0</span>, size<span class="op">=</span>(n_sims, n))   <span class="co"># visits,  mean 10</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> np.random.gamma(shape<span class="op">=</span><span class="fl">5.0</span>, scale<span class="op">=</span><span class="fl">5.0</span>, size<span class="op">=</span>(n_sims, n))   <span class="co"># revenue, mean 25</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Plug-in estimate: ratio of the two sample means</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    plugin_est <span class="op">=</span> np.mean(y, axis<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> np.mean(x, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    plugin_biases.append(np.mean(plugin_est) <span class="op">-</span> true_ratio)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Leave-one-out: recompute the ratio n times, each time dropping one customer</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    sum_x <span class="op">=</span> np.<span class="bu">sum</span>(x, axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    sum_y <span class="op">=</span> np.<span class="bu">sum</span>(y, axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>    r_i <span class="op">=</span> ((sum_y <span class="op">-</span> y) <span class="op">/</span> (n <span class="op">-</span> <span class="dv">1</span>)) <span class="op">/</span> ((sum_x <span class="op">-</span> x) <span class="op">/</span> (n <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>    r_bar <span class="op">=</span> np.mean(r_i, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Quenouille's recombination</span></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>    jack_est <span class="op">=</span> n <span class="op">*</span> plugin_est <span class="op">-</span> (n <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> r_bar</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>    jackknife_biases.append(np.mean(jack_est) <span class="op">-</span> true_ratio)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">7.5</span>, <span class="fl">3.8</span>))</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>ax.plot(sample_sizes, plugin_biases, <span class="st">"o-"</span>, color<span class="op">=</span>PRIMARY, lw<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"Plug-in ratio $</span><span class="ch">\\</span><span class="st">bar</span><span class="sc">{Y}</span><span class="st">/</span><span class="ch">\\</span><span class="st">bar</span><span class="sc">{X}</span><span class="st">$"</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>ax.plot(sample_sizes, jackknife_biases, <span class="st">"s--"</span>, color<span class="op">=</span>SECONDARY, lw<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"Jackknife-corrected ratio"</span>)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="dv">0</span>, color<span class="op">=</span>RULE, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Customers per cohort ($n$)"</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"Average error in revenue-per-visit"</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"The plug-in ratio runs high on small cohorts; the jackknife does not"</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>ax.legend(frameon<span class="op">=</span><span class="va">True</span>, facecolor<span class="op">=</span><span class="st">"white"</span>, edgecolor<span class="op">=</span>RULE)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n, pb, jb <span class="kw">in</span> <span class="bu">zip</span>(sample_sizes, plugin_biases, jackknife_biases):</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"n = </span><span class="sc">{</span>n<span class="sc">:3d}</span><span class="ss">   plug-in error </span><span class="sc">{</span>pb<span class="sc">:+.4f}</span><span class="ss">   jackknife error </span><span class="sc">{</span>jb<span class="sc">:+.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-3-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>n =   5   plug-in error +0.1034   jackknife error -0.0062
n =  10   plug-in error +0.0562   jackknife error +0.0038
n =  20   plug-in error +0.0241   jackknife error -0.0013
n =  40   plug-in error +0.0114   jackknife error -0.0012
n =  80   plug-in error +0.0055   jackknife error -0.0008
n = 160   plug-in error +0.0033   jackknife error +0.0001</code></pre>
</div>
</div>
<p>At five customers the plug-in ratio reads about <strong>+0.10 too high</strong> — a 4% overstatement of a metric people budget against. Double the cohort to ten and the error roughly halves to +0.056; double again and it halves again. That halving is the signature to remember: the error shrinks like <span class="math inline">\(1/n\)</span>, so it is invisible at <span class="math inline">\(n = 100{,}000\)</span> and dominant at <span class="math inline">\(n = 20\)</span>. Statisticians call it the <strong><span class="math inline">\(O(1/n)\)</span> bias term</strong>. The jackknife line, meanwhile, sits within 0.007 of zero at every cohort size, including the smallest — it has removed the entire <span class="math inline">\(1/n\)</span> term and left only what decays faster.</p>
<p>That is the empirical claim. The next section is why the recombination <code>n * plugin - (n-1) * r_bar</code> does it.</p>
</section>
<section id="quenouilles-trick-cancels-the-leading-error-term" class="level2">
<h2 class="anchored" data-anchor-id="quenouilles-trick-cancels-the-leading-error-term">Quenouille’s trick cancels the leading error term</h2>
<p>Quenouille’s observation in 1949 was almost embarrassingly simple. Drop one point from a sample of <span class="math inline">\(n\)</span> and what remains is a perfectly good sample of size <span class="math inline">\(n-1\)</span>. It suffers from the same kind of bias — same cause, same formula — just very slightly <em>more</em> of it, because it is one observation smaller.</p>
<p>So you have the same unknown error appearing twice, at two known strengths. Two equations, one nuisance. Weight them so the nuisance subtracts out. Averaging the <span class="math inline">\(n\)</span> leave-one-out estimates into <span class="math inline">\(\bar{\theta}_{(\cdot)}\)</span> and combining gives the jackknife estimator:</p>
<p><span class="math display">\[\hat{\theta}_{\text{jack}} = n\hat{\theta}_n - (n-1)\bar{\theta}_{(\cdot)}\]</span></p>
<p>Read it as an extrapolation rather than a formula. You have the estimate at sample size <span class="math inline">\(n\)</span> and the estimate at sample size <span class="math inline">\(n-1\)</span>; you can see which way the answer is drifting as the sample grows, so you step one notch further in that direction. The <span class="math inline">\(1/n\)</span> error is gone; what survives shrinks like <span class="math inline">\(1/n^2\)</span>, which is why the jackknife line above was flat rather than merely lower.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The two-line cancellation, for the curious
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>For almost any smooth non-linear statistic, the expectation admits an asymptotic expansion in powers of <span class="math inline">\(1/n\)</span>:</p>
<p><span class="math display">\[\mathbb{E}[\hat{\theta}_n] = \theta + \frac{a}{n} + \frac{b}{n^2} + O\!\left(\frac{1}{n^3}\right)\]</span></p>
<p>Each leave-one-out estimate is computed on a sample of size <span class="math inline">\(n-1\)</span>, so it obeys the same expansion evaluated one lower, and so does their average:</p>
<p><span class="math display">\[\mathbb{E}[\bar{\theta}_{(\cdot)}] = \theta + \frac{a}{n-1} + \frac{b}{(n-1)^2} + O\!\left(\frac{1}{n^3}\right)\]</span></p>
<p>Multiply the first by <span class="math inline">\(n\)</span>, the second by <span class="math inline">\(n-1\)</span>, and subtract. The <span class="math inline">\(\theta\)</span> terms leave one copy behind, and the <span class="math inline">\(a\)</span> terms — now <span class="math inline">\(a\)</span> and <span class="math inline">\(a\)</span> exactly — annihilate:</p>
<p><span class="math display">\[\mathbb{E}[\hat{\theta}_{\text{jack}}] = \theta + \left(\frac{b}{n} - \frac{b}{n-1}\right) + O\!\left(\frac{1}{n^2}\right) = \theta - \frac{b}{n(n-1)} + O\!\left(\frac{1}{n^2}\right)\]</span></p>
<p>The constant <span class="math inline">\(a\)</span> never had to be known. That is the whole point: the correction is arithmetic on estimates you already computed, not an analysis of the particular statistic in front of you.</p>
</div>
</div>
</div>
<p>Bias is only half the problem, though. A corrected point estimate with no sense of its own uncertainty is still a number you cannot act on. Tukey’s move was to notice that the same <span class="math inline">\(n\)</span> leave-one-out fits were already carrying that information.</p>
</section>
<section id="tukey-turns-one-estimate-into-n-per-observation-fingerprints" class="level2">
<h2 class="anchored" data-anchor-id="tukey-turns-one-estimate-into-n-per-observation-fingerprints">Tukey turns one estimate into <span class="math inline">\(n\)</span> per-observation fingerprints</h2>
<p>Quenouille’s formula averages the leave-one-out estimates and then recombines. Tukey rearranged it so the recombination happens <em>first</em>, once per observation. For each point <span class="math inline">\(i\)</span>, define its <strong>pseudovalue</strong>:</p>
<p><span class="math display">\[J_i = n \hat{\theta}_n - (n-1)\hat{\theta}_{(i)}\]</span></p>
<p>and the jackknife estimate is just their average, <span class="math inline">\(\hat{\theta}_{\text{jack}} = \frac{1}{n}\sum_i J_i\)</span>.</p>
<p>The rearrangement looks cosmetic and is not. Think of <span class="math inline">\(J_i\)</span> as the answer you would be forced to report if observation <span class="math inline">\(i\)</span> were the only thing distinguishing this sample from a sample without it — the estimate with that point’s entire contribution amplified out of the average. A point that changes nothing when removed gets a pseudovalue sitting right on the overall estimate. A point that props the whole thing up gets a pseudovalue flung far away from it. Subtract the overall estimate and what remains, <span class="math inline">\(J_i - \hat{\theta}_{\text{jack}}\)</span>, is that observation’s fingerprint on the answer.</p>
<p>Tukey’s real claim was stronger: for smooth statistics those <span class="math inline">\(n\)</span> fingerprints behave like <span class="math inline">\(n\)</span> independent draws from a single distribution. That is a surprising thing to get for free, and it is what licenses treating them as ordinary data. In particular, their scatter estimates the estimator’s own variance:</p>
<p><span class="math display">\[v_{\text{jack}} = \frac{1}{n(n-1)}\sum_{i=1}^n \left(J_i - \hat{\theta}_{\text{jack}}\right)^2 = \frac{n-1}{n}\sum_{i=1}^n \left(\hat{\theta}_{(i)} - \bar{\theta}_{(\cdot)}\right)^2\]</span></p>
<p>with <span class="math inline">\(\text{SE}_{\text{jack}} = \sqrt{v_{\text{jack}}}\)</span>, and a confidence interval follows the ordinary way, <span class="math inline">\(\hat{\theta}_{\text{jack}} \pm t_{n-1,\,\alpha/2}\cdot\text{SE}_{\text{jack}}\)</span>. No distributional assumption about the data went into that — only smoothness of the statistic.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Why the fingerprints are independent: the influence function
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Von Mises’ statistical calculus expands any smooth functional <span class="math inline">\(T\)</span> of the empirical distribution <span class="math inline">\(F_n\)</span> around the population distribution <span class="math inline">\(F\)</span>:</p>
<p><span class="math display">\[T(F_n) - T(F) = \frac{1}{n}\sum_{i=1}^n L(X_i; F) + R_n\]</span></p>
<p>where <span class="math inline">\(L(x; F)\)</span> is the <strong>influence function</strong> — the derivative of the functional when you nudge an infinitesimal point mass onto <span class="math inline">\(x\)</span>. It measures the effect of a single observation on the estimate, in the limit.</p>
<p>Deleting <span class="math inline">\(X_i\)</span> removes exactly that point’s term from the sum:</p>
<p><span class="math display">\[\hat{\theta}_n - \hat{\theta}_{(i)} \approx \frac{1}{n-1}\left(L(X_i; F) - \bar{L}\right)\]</span></p>
<p>Substituting into <span class="math inline">\(J_i = \hat{\theta}_n + (n-1)(\hat{\theta}_n - \hat{\theta}_{(i)})\)</span> collapses the factors of <span class="math inline">\(n-1\)</span>:</p>
<p><span class="math display">\[J_i \approx \hat{\theta}_n + L(X_i; F) \qquad \Longrightarrow \qquad J_i - \hat{\theta}_{\text{jack}} \approx L(X_i; F)\]</span></p>
<p>The pseudovalues are the influence function evaluated at each observation, offset by a constant. The <span class="math inline">\(X_i\)</span> are i.i.d., so the <span class="math inline">\(L(X_i; F)\)</span> are i.i.d., and the sample variance of an i.i.d. mean is the familiar <span class="math inline">\(\frac{1}{n}\text{Var}(L(X))\)</span> — which is the variance formula above. The approximation is exactly where the smoothness assumption enters, and it is exactly what fails for the median later on.</p>
</div>
</div>
</div>
<p>Before the applications, it helps to have handled the objects directly. The lab below is a scatter of twelve points whose statistic you can watch respond: drag a point, add one, delete one, and the bar chart beside it recomputes every pseudovalue. Drag a point out toward the edge and watch its own bar grow while the others barely stir — that asymmetry, one bar dwarfing the rest, is the shape you will be looking for in all three applications that follow.</p>
<div class="widget-container">
<div class="widget-header">
<p><span class="widget-title">Interactive Lab 1: Pseudovalues &amp; Empirical Influence</span> <span class="widget-badge">Local Compute</span></p>
</div>
<div id="widget-pseudovalues">

</div>
</div>
<p>The theory is now in place: bias cancellation from Quenouille, per-observation influence and variance from Tukey. The next three sections put it against problems where the alternative tools genuinely struggle.</p>
</section>
<section id="in-growth-systems-jackknife-influence-catches-fraud-rings-that-averages-hide" class="level2">
<h2 class="anchored" data-anchor-id="in-growth-systems-jackknife-influence-catches-fraud-rings-that-averages-hide">In growth systems, jackknife influence catches fraud rings that averages hide</h2>
<p>Consumer fintech and marketplace apps run referral programmes: recruit a friend, and both of you get $20 in credit. Growth teams watch the <strong>promo-to-spend ratio</strong> — total credits handed out across a cohort, divided by the real revenue those customers subsequently generated. It is the same shape of statistic as the revenue-per-visit ratio above, and it inherits the same small-sample tilt, but here the more urgent question is different: when a referral cluster’s ratio looks bad, <em>which account</em> made it bad?</p>
<p>Organised abuse runs hub-and-spoke. One coordinating account registers dozens of throwaway phone numbers and device fingerprints, collects a referral bonus for each, and none of the spokes ever spends a cent. The obvious detector — flag accounts with zero post-promo spend — finds the spokes. It cannot find the hub, because the hub does spend a little, which is the entire reason it was set up that way.</p>
<p>The jackknife asks a different question of each account: <em>how much better would this cohort’s economics look if this account had never joined?</em> That reframing is what catches the hub, because the hub’s cost is not its own $20. It is the $20 it collected plus a $20 credit for each spoke it recruited — money the programme paid out because that account existed. Charging each account for the credits it caused is not a modelling trick; it is what the referral programme’s own terms already say.</p>
<p>The cluster below is simulated, and would have to be: real referral-abuse data is confidential by nature and the ground truth of who coordinated what is precisely what nobody has. So we construct eight genuine customers with one to five real referrals each and ordinary spend, one ringleader recruiting seven synthetic spokes and spending $5, and the seven spokes spending nothing. The point of simulating is that we know who the hub is and can check whether the method finds it. Getting this wrong in production costs in both directions: miss the hub and the syndicate keeps farming credits, ban the wrong accounts and you have terminated paying customers on a statistic.</p>
<div id="46a04ddc" class="cell" data-execution_count="3">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulated referral cluster: 8 genuine customers, 1 coordinating hub, 7 synthetic spokes.</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Each account is charged its own signup credit plus one credit per referee it recruited.</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">101</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>BONUS <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>legit_referrals <span class="op">=</span> [<span class="dv">3</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">1</span>, <span class="dv">3</span>]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>accounts <span class="op">=</span> [</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    {<span class="st">"name"</span>: <span class="ss">f"Legit User </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>, <span class="st">"referrals"</span>: r,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>     <span class="st">"spend"</span>: <span class="bu">int</span>(np.random.randint(<span class="dv">100</span>, <span class="dv">300</span>)), <span class="st">"is_hub"</span>: <span class="va">False</span>}</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, r <span class="kw">in</span> <span class="bu">enumerate</span>(legit_referrals)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>accounts.append({<span class="st">"name"</span>: <span class="st">"Syndicate Ringleader"</span>, <span class="st">"referrals"</span>: <span class="dv">7</span>, <span class="st">"spend"</span>: <span class="dv">5</span>, <span class="st">"is_hub"</span>: <span class="va">True</span>})</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">7</span>):</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    accounts.append({<span class="st">"name"</span>: <span class="ss">f"Synthetic Bot </span><span class="sc">{</span>j<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>, <span class="st">"referrals"</span>: <span class="dv">0</span>, <span class="st">"spend"</span>: <span class="dv">0</span>, <span class="st">"is_hub"</span>: <span class="va">False</span>})</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>df_fraud <span class="op">=</span> pd.DataFrame(accounts)</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>df_fraud[<span class="st">"promo"</span>] <span class="op">=</span> BONUS <span class="op">*</span> (<span class="dv">1</span> <span class="op">+</span> df_fraud[<span class="st">"referrals"</span>])</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>n_users <span class="op">=</span> <span class="bu">len</span>(df_fraud)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>cluster_r <span class="op">=</span> df_fraud[<span class="st">"promo"</span>].<span class="bu">sum</span>() <span class="op">/</span> df_fraud[<span class="st">"spend"</span>].<span class="bu">sum</span>()</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Leave-one-out: recompute the cohort ratio with each account removed in turn</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>df_fraud[<span class="st">"sub_r"</span>] <span class="op">=</span> [</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    df_fraud.drop(index<span class="op">=</span>i)[<span class="st">"promo"</span>].<span class="bu">sum</span>() <span class="op">/</span> df_fraud.drop(index<span class="op">=</span>i)[<span class="st">"spend"</span>].<span class="bu">sum</span>()</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_users)</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>df_fraud[<span class="st">"influence"</span>] <span class="op">=</span> cluster_r <span class="op">-</span> df_fraud[<span class="st">"sub_r"</span>]</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>df_fraud[<span class="st">"pseudovalue"</span>] <span class="op">=</span> n_users <span class="op">*</span> cluster_r <span class="op">-</span> (n_users <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> df_fraud[<span class="st">"sub_r"</span>]</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>top_culprits <span class="op">=</span> df_fraud.sort_values(by<span class="op">=</span><span class="st">"influence"</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">5</span>)</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">3.8</span>))</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> [DANGER <span class="cf">if</span> is_hub <span class="cf">else</span> PRIMARY <span class="cf">for</span> is_hub <span class="kw">in</span> top_culprits[<span class="st">"is_hub"</span>]]</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>bars <span class="op">=</span> ax.barh(top_culprits[<span class="st">"name"</span>], top_culprits[<span class="st">"influence"</span>], color<span class="op">=</span>colors, height<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"Improvement in cohort promo-to-spend ratio if this account were removed"</span>)</span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Top accounts distorting cohort unit economics"</span>)</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>ax.invert_yaxis()</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> bar, val <span class="kw">in</span> <span class="bu">zip</span>(bars, top_culprits[<span class="st">"influence"</span>]):</span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>    ax.text(val <span class="op">+</span> <span class="fl">0.002</span>, bar.get_y() <span class="op">+</span> bar.get_height()<span class="op">/</span><span class="dv">2</span>, <span class="ss">f"+</span><span class="sc">{</span>val<span class="sc">:.3f}</span><span class="ss">"</span>,</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>            va<span class="op">=</span><span class="st">"center"</span>, fontsize<span class="op">=</span><span class="dv">9</span>, color<span class="op">=</span>INK)</span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cohort promo-to-spend ratio: </span><span class="sc">{</span>cluster_r<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Ringleader leverage:  </span><span class="sc">{</span>df_fraud<span class="sc">.</span>loc[df_fraud.is_hub, <span class="st">'influence'</span>]<span class="sc">.</span>item()<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Each spoke's leverage: </span><span class="sc">{</span>df_fraud<span class="sc">.</span>loc[df_fraud.name.<span class="bu">str</span>.startswith(<span class="st">'Synthetic'</span>), <span class="st">'influence'</span>]<span class="sc">.</span>iloc[<span class="dv">0</span>]<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Cohort promo-to-spend ratio: 0.618
Ringleader leverage:  0.1106
Each spoke's leverage: 0.0140</code></pre>
</div>
</div>
<p>The cohort burns $0.618 of credit per dollar of revenue, which is bad but tells you nothing about who. The leave-one-out pass does. Removing the ringleader improves the ratio by <strong>0.111</strong>; removing any single spoke improves it by <strong>0.014</strong>, and all seven spokes score identically because they are identical. The hub sits roughly eight times above the next account, alone at the top of a chart otherwise made of ties — the one-bar-dwarfing-the-rest shape from Lab 1, arriving in a real decision.</p>
<p>Notice what did the work. No graph neural network, no community detection, no labelled training set of known fraudsters. Sixteen recomputations of a ratio you were already computing.</p>
<p>The lab below lets you push on the assumptions. The promo-credit slider changes how much each signup is worth; the bot-node slider changes how many spokes the hub recruits, which also changes what the hub is charged. Drag the spoke count down toward zero and watch the hub’s lead collapse: at eight spokes it sits about nine times above the next account, at zero spokes barely twice. A hub with nothing to coordinate is just a slightly stingy customer, and the jackknife correctly stops shouting about it.</p>
<div class="widget-container">
<div class="widget-header">
<p><span class="widget-title">Interactive Lab 2: The Referral Syndicate Unmasker</span> <span class="widget-badge">Simulation</span></p>
</div>
<div id="widget-syndicate">

</div>
</div>
<p>Both examples so far have jackknifed a ratio — a statistic you could write down in closed form and, with effort, differentiate by hand. The next one cannot be written down that way at all.</p>
</section>
<section id="in-cohort-survival-pseudovalues-turn-censored-curves-into-ordinary-regressions" class="level2">
<h2 class="anchored" data-anchor-id="in-cohort-survival-pseudovalues-turn-censored-curves-into-ordinary-regressions">In cohort survival, pseudovalues turn censored curves into ordinary regressions</h2>
<p>Ask how long a subscription cohort stays active and you hit a wall immediately: for most customers you do not know. They signed up recently and are still subscribed, so all you know is that their lifetime exceeds however long you have been watching. That is <strong>right-censoring</strong>, and it rules out simply averaging the observed durations — the customers who look shortest-lived are often just the ones who joined last week.</p>
<p>The standard summary that survives censoring is the area under the retention curve up to a fixed horizon: the average number of days a customer stays active during, say, their first year, counting a customer who is still active at day 365 as a full 365. Statisticians call it <strong>restricted mean survival time</strong>, and it has the useful property of being a real quantity in days rather than a hazard ratio nobody can interpret in a planning meeting.</p>
<p>The wall is that it is a property of the <em>whole cohort’s curve</em>, not of any one customer. You get one number for the cohort. You cannot regress it on acquisition channel or discount depth to ask which lever moves it, because there is no per-customer response variable to put on the left-hand side — the censored customers have no usable duration, and the uncensored ones are a biased subset.</p>
<p>Andersen and Perme’s insight (2010) is that Tukey already built the missing response variable. Compute the cohort’s restricted mean; then, for each customer, recompute it with that customer deleted and form their pseudovalue. That pseudovalue is a per-customer number, defined for censored and uncensored customers alike, whose average is the cohort figure and whose conditional expectation given the covariates is the thing you actually wanted to model. Regress it on whatever you like with ordinary least squares. The censoring problem was absorbed by the Kaplan–Meier curve one level down.</p>
<p>The cohort below is simulated for a reason that matters here: the whole claim is that the regression recovers the truth, and only a simulation has a truth to recover. Four hundred customers arrive on one of two channels, with a signup discount drawn uniformly between 0% and 40%. Their true lifetime is exponential with a mean that organic acquisition raises by 80 days and discounting lowers by up to 150 — so heavier discounting genuinely buys worse customers. Each is then observed for a uniformly random window between 60 and 365 days and censored there, mimicking a cohort where recent signups dominate. The decision this feeds is where acquisition budget goes, so the regression is only useful if its error bars are honest — which is why the code below prints a standard error beside every coefficient and the true value beside that.</p>
<div id="d4db15a2" class="cell" data-execution_count="4">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulated subscription cohort, N=400, heavily right-censored.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># True lifetime: Exponential(mean = 250 + 80*organic - 150*discount), observed through a</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># uniform 60-365 day window. Because the generating process is known, the regression can be</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># checked against the truth it is trying to recover.</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">55</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>n_cohort <span class="op">=</span> <span class="dv">400</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>channels <span class="op">=</span> np.random.binomial(<span class="dv">1</span>, <span class="fl">0.5</span>, size<span class="op">=</span>n_cohort)      <span class="co"># 0 = Organic, 1 = Paid Search</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>discounts <span class="op">=</span> np.random.uniform(<span class="dv">0</span>, <span class="fl">0.4</span>, size<span class="op">=</span>n_cohort)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>scale <span class="op">=</span> <span class="dv">250</span> <span class="op">+</span> <span class="dv">80</span> <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> channels) <span class="op">-</span> <span class="dv">150</span> <span class="op">*</span> discounts</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>true_survival <span class="op">=</span> np.random.exponential(scale<span class="op">=</span>scale)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>censor_time <span class="op">=</span> np.random.uniform(<span class="dv">60</span>, <span class="dv">365</span>, size<span class="op">=</span>n_cohort)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>observed_time <span class="op">=</span> np.minimum(true_survival, censor_time)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>event_observed <span class="op">=</span> (true_survival <span class="op">&lt;=</span> censor_time).astype(<span class="bu">int</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> calc_rmst(times, events, t_star<span class="op">=</span><span class="dv">365</span>):</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Area under the Kaplan-Meier curve out to t_star."""</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> np.argsort(times)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    t_sorted, e_sorted <span class="op">=</span> times[order], events[order]</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>    n_k <span class="op">=</span> <span class="bu">len</span>(times)</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>    s_t, rmst, prev_t <span class="op">=</span> <span class="fl">1.0</span>, <span class="fl">0.0</span>, <span class="fl">0.0</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(n_k):</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>        cur_t <span class="op">=</span> <span class="bu">min</span>(t_sorted[k], t_star)</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> cur_t <span class="op">&gt;</span> prev_t:</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>            rmst <span class="op">+=</span> s_t <span class="op">*</span> (cur_t <span class="op">-</span> prev_t)</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>            prev_t <span class="op">=</span> cur_t</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> cur_t <span class="op">&gt;=</span> t_star:</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> e_sorted[k] <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>            s_t <span class="op">*=</span> (<span class="fl">1.0</span> <span class="op">-</span> <span class="fl">1.0</span> <span class="op">/</span> (n_k <span class="op">-</span> k))</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> prev_t <span class="op">&lt;</span> t_star:</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>        rmst <span class="op">+=</span> s_t <span class="op">*</span> (t_star <span class="op">-</span> prev_t)</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> rmst</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>cohort_rmst <span class="op">=</span> calc_rmst(observed_time, event_observed)</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a><span class="co"># One pseudovalue per customer: the cohort figure, re-levered by deleting that customer</span></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a>pseudo_rmst <span class="op">=</span> np.array([</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>    n_cohort <span class="op">*</span> cohort_rmst</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>    <span class="op">-</span> (n_cohort <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> calc_rmst(np.delete(observed_time, i), np.delete(event_observed, i))</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_cohort)</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordinary least squares on the pseudovalues, with robust (sandwich) standard errors</span></span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>X_mat <span class="op">=</span> np.column_stack([np.ones(n_cohort), channels, discounts])</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> np.linalg.lstsq(X_mat, pseudo_rmst, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>resid <span class="op">=</span> pseudo_rmst <span class="op">-</span> X_mat <span class="op">@</span> beta_hat</span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>XtX_inv <span class="op">=</span> np.linalg.inv(X_mat.T <span class="op">@</span> X_mat)</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>cov_hat <span class="op">=</span> XtX_inv <span class="op">@</span> (X_mat.T <span class="op">@</span> (X_mat <span class="op">*</span> resid[:, <span class="va">None</span>] <span class="op">**</span> <span class="dv">2</span>)) <span class="op">@</span> XtX_inv</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>se_hat <span class="op">=</span> np.sqrt(np.diag(cov_hat))</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a><span class="co"># The truth: each customer's exact restricted mean, best-fit by the same design matrix</span></span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a>true_rmst_i <span class="op">=</span> scale <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> np.exp(<span class="op">-</span><span class="dv">365</span> <span class="op">/</span> scale))</span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a>beta_true <span class="op">=</span> np.linalg.lstsq(X_mat, true_rmst_i, rcond<span class="op">=</span><span class="va">None</span>)[<span class="dv">0</span>]</span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cohort 365-day restricted mean: </span><span class="sc">{</span>cohort_rmst<span class="sc">:.1f}</span><span class="ss"> active days</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">"Organic baseline (days)"</span>, <span class="st">"Paid Search effect (days)"</span>, <span class="st">"Full-discount effect (days)"</span>]</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, b, s, t <span class="kw">in</span> <span class="bu">zip</span>(labels, beta_hat, se_hat, beta_true):</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>    lo, hi <span class="op">=</span> b <span class="op">-</span> <span class="fl">1.96</span> <span class="op">*</span> s, b <span class="op">+</span> <span class="fl">1.96</span> <span class="op">*</span> s</span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>    covered <span class="op">=</span> <span class="st">"yes"</span> <span class="cf">if</span> lo <span class="op">&lt;=</span> t <span class="op">&lt;=</span> hi <span class="cf">else</span> <span class="st">"NO"</span></span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&lt;28}</span><span class="ss"> </span><span class="sc">{</span>b<span class="sc">:8.1f}</span><span class="ss"> +/- </span><span class="sc">{</span>s<span class="sc">:5.1f}</span><span class="ss">   95% CI [</span><span class="sc">{</span>lo<span class="sc">:7.1f}</span><span class="ss">, </span><span class="sc">{</span>hi<span class="sc">:7.1f}</span><span class="ss">]"</span></span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"   true </span><span class="sc">{</span>t<span class="sc">:7.1f}</span><span class="ss">   covered: </span><span class="sc">{</span>covered<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Cohort 365-day restricted mean: 204.2 active days

Organic baseline (days)         241.2 +/-  15.7   95% CI [  210.4,   272.0]   true   223.3   covered: yes
Paid Search effect (days)       -45.6 +/-  14.5   95% CI [  -74.1,   -17.1]   true   -32.9   covered: yes
Full-discount effect (days)     -77.4 +/-  64.0   95% CI [ -202.8,    48.0]   true   -62.5   covered: yes</code></pre>
</div>
</div>
<p>Every coefficient’s interval covers the value the simulation actually used. Paid-search customers are worth about 46 fewer active days in their first year, with a standard error of roughly 15 — against a true penalty of 33 days. Full-depth discounting costs around 77 days, but with a standard error near 64: on 400 customers the discount slope is barely distinguishable from zero, and the honest read is “we do not yet know.” That is a result too, and it is one the point estimate alone would have concealed. A team reading <code>-77.4</code> off a slide would go and rebuild the discount ladder; a team reading <code>-77.4 ± 64</code> would go and collect more data first.</p>
<p>What made all this possible is that a curve-level functional became 400 ordinary numbers. Every regression tool you already own works on them.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caveat: the horizon must be inside the data
</div>
</div>
<div class="callout-body-container callout-body">
<p>Restricted mean survival time is only estimable out to a horizon the observation window actually reaches. Here every customer is censored by day 365 at the latest, so the Kaplan–Meier curve is being read right at the edge of its support and the tail is effectively held flat. Push the horizon past the largest observed follow-up time and the estimate stops being non-parametric — it becomes an extrapolation with the flat-tail assumption doing the work. Pick <span class="math inline">\(t^*\)</span> from the data you have, not the horizon you wish you had.</p>
</div>
</div>
<p>Both applications so far used the jackknife to <em>find</em> a number. The last one uses it to refuse one.</p>
</section>
<section id="in-clinical-omics-leave-one-out-variance-stops-multi-million-dollar-false-targets" class="level2">
<h2 class="anchored" data-anchor-id="in-clinical-omics-leave-one-out-variance-stops-multi-million-dollar-false-targets">In clinical omics, leave-one-out variance stops multi-million dollar false targets</h2>
<p>Early-phase oncology screening has an uncomfortable shape: thirty to sixty patients, twenty thousand genes. Every gene gets a score — typically the log-ratio of its average expression in tumour tissue against healthy tissue — and the top of that ranked list determines which targets get years of laboratory work behind them.</p>
<p>With only thirty patients, one patient can own a gene’s score outright. A mishandled sample, an undetected co-morbidity, a batch effect on one sequencing run: any of these can inflate one patient’s reading for one gene by an order of magnitude, and the average of thirty numbers cannot tell you it happened. The gene surfaces near the top of the list looking like a strong, clean signal.</p>
<p>The jackknife asks whether the score survives its own patients. Recompute the fold-change thirty times, each time with a different patient held out. If the signal is real, all thirty answers agree and the jackknife standard error is small. If one patient is carrying it, the run without that patient collapses, the standard error explodes, and the ratio of effect to standard error — call it a <strong>stability index</strong> — drops through the floor. It is the same <span class="math inline">\(|\text{estimate}| / \text{SE}\)</span> shape as a t-statistic, but built from deletions rather than a distributional assumption, which matters at <span class="math inline">\(n = 30\)</span>.</p>
<p>The screen below is simulated because the alternative is not available: patient-level expression matrices are protected health information, and in any case a real screen would not tell us which of its hits are artifacts — that is the thing we want to demonstrate the method finding. So we plant both cases. CDK1 stands in for a genuine target, overexpressed by about 3.2 log-units consistently across all thirty patients. LINC009 stands in for a sample-prep artifact: essentially no signal in twenty-nine patients, and one enormous reading in patient 15, of the magnitude an RNA-seq count artifact actually produces. The spike is sized so the two genes look equally attractive on the naive score, which is precisely the situation that costs money.</p>
<div id="3ae4945b" class="cell" data-execution_count="5">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulated RNA-seq oncology screen, N=30 patients, tumour vs normal log-fold change.</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># CDK1: a genuine target, consistent across all patients.</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># LINC009: an artifact, flat in 29 patients with one enormous reading in patient 15.</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">77</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>n_patients <span class="op">=</span> <span class="dv">30</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>cdk1_diff <span class="op">=</span> np.random.normal(loc<span class="op">=</span><span class="fl">3.2</span>, scale<span class="op">=</span><span class="fl">0.6</span>, size<span class="op">=</span>n_patients)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>linc_diff <span class="op">=</span> np.random.normal(loc<span class="op">=</span><span class="fl">0.2</span>, scale<span class="op">=</span><span class="fl">0.4</span>, size<span class="op">=</span>n_patients)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>linc_diff[<span class="dv">14</span>] <span class="op">=</span> <span class="fl">90.0</span>  <span class="co"># single-patient sample-prep artifact</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>genes <span class="op">=</span> {<span class="st">"CDK1 (true target)"</span>: cdk1_diff, <span class="st">"LINC009 (artifact)"</span>: linc_diff}</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">3.6</span>))</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (gname, diffs) <span class="kw">in</span> <span class="bu">zip</span>(axes, genes.items()):</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    mean_val <span class="op">=</span> np.mean(diffs)</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Leave-one-patient-out</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>    sub_means <span class="op">=</span> np.array([np.mean(np.delete(diffs, i)) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_patients)])</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>    theta_dot <span class="op">=</span> sub_means.mean()</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    jack_val <span class="op">=</span> n_patients <span class="op">*</span> mean_val <span class="op">-</span> (n_patients <span class="op">-</span> <span class="dv">1</span>) <span class="op">*</span> theta_dot</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    se_j <span class="op">=</span> np.sqrt(((n_patients <span class="op">-</span> <span class="dv">1</span>) <span class="op">/</span> n_patients) <span class="op">*</span> np.<span class="bu">sum</span>((sub_means <span class="op">-</span> theta_dot) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>    stability <span class="op">=</span> <span class="bu">abs</span>(jack_val) <span class="op">/</span> se_j</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    is_target <span class="op">=</span> <span class="st">"CDK1"</span> <span class="kw">in</span> gname</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>    ax.scatter(<span class="bu">range</span>(<span class="dv">1</span>, n_patients <span class="op">+</span> <span class="dv">1</span>), diffs,</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>               color<span class="op">=</span>PRIMARY <span class="cf">if</span> is_target <span class="cf">else</span> DANGER, alpha<span class="op">=</span><span class="fl">0.8</span>, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>    ax.axhline(mean_val, color<span class="op">=</span>SECONDARY, lw<span class="op">=</span><span class="dv">2</span>, label<span class="op">=</span><span class="ss">f"Naive mean LFC: </span><span class="sc">{</span>mean_val<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>    ax.axhline(<span class="dv">0</span>, color<span class="op">=</span>RULE, ls<span class="op">=</span><span class="st">":"</span>)</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"</span><span class="sc">{</span>gname<span class="sc">}</span><span class="ch">\n</span><span class="ss">Stability index: </span><span class="sc">{</span>stability<span class="sc">:.2f}</span><span class="ss">   (SE$_</span><span class="ch">{{</span><span class="ss">jack</span><span class="ch">}}</span><span class="ss">$ = </span><span class="sc">{</span>se_j<span class="sc">:.2f}</span><span class="ss">)"</span>)</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"Patient index"</span>)</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">"Tumour - normal expression"</span>)</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    ax.legend(loc<span class="op">=</span><span class="st">"center left"</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="kw">not</span> is_target:</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>        ax.annotate(<span class="st">"patient 15"</span>, xy<span class="op">=</span>(<span class="dv">15</span>, linc_diff[<span class="dv">14</span>]), xytext<span class="op">=</span>(<span class="dv">19</span>, <span class="dv">70</span>),</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>                    fontsize<span class="op">=</span><span class="dv">8</span>, color<span class="op">=</span>INK,</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a>                    arrowprops<span class="op">=</span><span class="bu">dict</span>(arrowstyle<span class="op">=</span><span class="st">"-&gt;"</span>, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>On the naive score the artifact wins. LINC009 averages <strong>3.12</strong> log-units against CDK1’s <strong>3.06</strong>, so a ranked list sorted by fold-change puts the artifact <em>above</em> the real target, and a team working down that list from the top reaches the wrong gene first.</p>
<p>The stability index inverts the ranking completely: <strong>28.2</strong> for CDK1 against <strong>1.04</strong> for LINC009. Read the two panels and you can see why. CDK1’s thirty points cluster tightly around their mean, so deleting any one of them barely moves it and the jackknife standard error is 0.11. LINC009’s panel looks almost empty by comparison, because a single point at 90 has stretched the axis until twenty-nine real measurements are squashed against the floor — and that visual is the finding, not a plotting defect. Delete patient 15 and the estimate falls to near zero; delete anyone else and it does not budge. That disagreement among the thirty leave-one-out runs is what the standard error of 3.00 is reporting.</p>
<p>A stability index near 1 says the effect and its uncertainty are the same size — the gene is one patient away from having no signal at all. That is a cheap filter to run over twenty thousand candidates before anyone orders reagents.</p>
<p>The lab below runs the screen over ten genes at once. The button injects the artifact patient and removes it again, so you can watch a single ranking flip: on the naive fold-change LINC009 climbs the list, and on the stability index it falls off it.</p>
<div class="widget-container">
<div class="widget-header">
<p><span class="widget-title">Interactive Lab 3: Biomarker Stability Stress-Tester</span> <span class="widget-badge">Oncology Target Screen</span></p>
</div>
<div id="widget-biomarkers">

</div>
</div>
<p>Three applications, three wins. But the smoothness assumption that has been quietly holding everything up is a real condition, and there is a familiar statistic that violates it outright.</p>
</section>
<section id="the-jackknife-shatters-on-non-smooth-statistics-like-the-median" class="level2">
<h2 class="anchored" data-anchor-id="the-jackknife-shatters-on-non-smooth-statistics-like-the-median">The jackknife shatters on non-smooth statistics like the median</h2>
<p>Everything above rested on one property: deleting a single observation nudges the estimate a little, in proportion to how unusual that observation was. That is what let the leave-one-out spread stand in for the sampling variance.</p>
<p>The sample median does not work like that. Sort the data and the median is whichever value sits in the middle — it is <em>one of the observations</em>, chosen by position rather than computed from all of them. Delete a point and the middle shifts by one slot, so the new median is the average of two adjacent central values. It makes no difference whether the point you deleted was the largest in the dataset or barely above the middle: the median moves by the gap between two neighbours near the centre, and by nothing else. Delete the most extreme observation you have and the median shrugs.</p>
<p>So the leave-one-out spread stops measuring influence. It measures the spacing of whichever two or three points happen to sit in the middle of this particular sample — an accident of one small neighbourhood of the data. Add more data and that neighbourhood gets tighter but never settles down, because it is always determined by a couple of order statistics rather than by all <span class="math inline">\(n\)</span> points. The formal consequence is that the jackknife variance estimator for the median is <strong>inconsistent</strong>: as <span class="math inline">\(n \to \infty\)</span> it does not converge to the true asymptotic variance at all, but to a random multiple of it — specifically a scaled chi-square with 2 degrees of freedom, which is to say it keeps rattling around forever. It is not merely imprecise. It is wrong, and collecting more data does not fix it.</p>
<p>The lab below puts the two side by side on the same eleven points. Switch between mean and median and watch the leave-one-out values: for the mean they fan out smoothly, each point displaced in proportion to its distance from centre. For the median they collapse onto two or three repeated values, and the point out at 9.8 — visibly the most extreme in the sample — gets a pseudovalue indistinguishable from its neighbours’.</p>
<div class="widget-container">
<div class="widget-header">
<p><span class="widget-title">Interactive Lab 4: Smooth vs.&nbsp;Non-Smooth Stress Test</span> <span class="widget-badge">Diagnostic</span></p>
</div>
<div id="widget-smooth-jagged">

</div>
</div>
<section id="the-remedy-delete-more-than-one" class="level3">
<h3 class="anchored" data-anchor-id="the-remedy-delete-more-than-one">The remedy: delete more than one</h3>
<p>Wu (1986) and Shao and Wu (1989) traced the failure to its cause. Deleting one point moves the median by exactly one slot, which is a discrete jump, so no amount of averaging smooths it. Delete <span class="math inline">\(d\)</span> points at a time instead and the median can land anywhere in a whole neighbourhood of order statistics, and averaging over many such deletions does smooth it.</p>
<p>The condition is that <span class="math inline">\(d\)</span> must grow with <span class="math inline">\(n\)</span> but stay a vanishing fraction of it — large enough that the deletions genuinely mix, small enough that each retained subsample still resembles the full one. In practice <span class="math inline">\(d \approx \sqrt{n}\)</span> satisfies both. This is the <strong>delete-<span class="math inline">\(d\)</span> jackknife</strong>, and it restores consistency for medians, quantiles, and the other order-statistic-based estimators that break the ordinary version. The cost is that you are back to sampling subsets rather than making <span class="math inline">\(n\)</span> deterministic passes — which is to say, back in the bootstrap’s territory.</p>
</section>
</section>
<section id="jackknife-or-bootstrap-deterministic-speed-against-stochastic-generality" class="level2">
<h2 class="anchored" data-anchor-id="jackknife-or-bootstrap-deterministic-speed-against-stochastic-generality">Jackknife or bootstrap: deterministic speed against stochastic generality</h2>
<p>Both methods resample the data you already have rather than assuming a distribution for it. They differ in what they buy with it.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">The jackknife</th>
<th style="text-align: left;">Efron’s bootstrap</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Cost</strong></td>
<td style="text-align: left;">Deterministic: exactly <span class="math inline">\(n\)</span> passes, same answer every run</td>
<td style="text-align: left;">Stochastic: <span class="math inline">\(B \ge 1{,}000\)</span> draws, plus a seed to record</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Smooth statistics</strong> (means, ratios, GLMs)</td>
<td style="text-align: left;">Removes the <span class="math inline">\(1/n\)</span> bias outright; no simulation noise</td>
<td style="text-align: left;">Accurate, but adds Monte Carlo noise of your own making</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Non-smooth statistics</strong> (median, quantiles)</td>
<td style="text-align: left;">Fails; needs delete-<span class="math inline">\(d\)</span></td>
<td style="text-align: left;">Works unmodified</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Per-observation diagnostics</strong></td>
<td style="text-align: left;">Free: the pseudovalues <em>are</em> the influence estimates</td>
<td style="text-align: left;">Needs a secondary regression on resampling weights</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Setup</strong></td>
<td style="text-align: left;">None: no tuning, no seed, no reproducibility caveat</td>
<td style="text-align: left;">Choose <span class="math inline">\(B\)</span>, fix the seed, record both</td>
</tr>
</tbody>
</table>
<p>The honest summary is that the bootstrap is more general and the jackknife is more informative when it applies. On a smooth statistic they will agree on the standard error; only one of them also hands you a ranked list of which observations produced it.</p>
</section>
<section id="when-to-reach-for-the-jackknife-in-your-pocket" class="level2">
<h2 class="anchored" data-anchor-id="when-to-reach-for-the-jackknife-in-your-pocket">When to reach for the jackknife in your pocket</h2>
<p>The claim at the top was that leaving out one observation at a time fixes a predictable error and, in the same <span class="math inline">\(n\)</span> passes, tells you which observation is holding your answer up. All four examples were the same two lines of arithmetic applied to different estimators.</p>
<p>The bias correction earned its keep on cohorts of five, where the plug-in ratio ran 4% high and the correction removed essentially all of it — and it becomes irrelevant by the time <span class="math inline">\(n\)</span> reaches the thousands, which is the honest limit of that half. The influence half does not fade with sample size, because “which single observation is this resting on” is a question about leverage rather than about <span class="math inline">\(n\)</span>: it found the hub of a referral syndicate that a zero-spend filter structurally could not see, and it demoted a biomarker that outranked a genuine target on the naive score. In between, pseudovalues turned a censored survival curve into 400 ordinary regression rows and, more usefully, into error bars wide enough to stop a decision.</p>
<p>Where it stops holding is precise, and worth carrying alongside the method: the statistic has to be smooth. If it is a median, a quantile, or anything else that reads a value off a sorted position, the ordinary jackknife’s variance estimate is not merely noisy but inconsistent, and you want delete-<span class="math inline">\(d\)</span> or the bootstrap instead.</p>
<p>For everything else — every ratio, every rate, every curve functional, every model coefficient — you do not need ten thousand simulated universes. You need <span class="math inline">\(n\)</span> passes and a subtraction.</p>
<script id="jackknife-data" type="application/json">{"toy":{"points":[{"id":1,"x":1.2,"y":2.1},{"id":2,"x":2.0,"y":2.9},{"id":3,"x":2.8,"y":3.7},{"id":4,"x":3.5,"y":4.1},{"id":5,"x":4.1,"y":5.2},{"id":6,"x":4.9,"y":5.8},{"id":7,"x":5.8,"y":6.9},{"id":8,"x":6.7,"y":7.4},{"id":9,"x":7.5,"y":8.5},{"id":10,"x":8.4,"y":9.2},{"id":11,"x":9.2,"y":9.8},{"id":12,"x":5.0,"y":9.5}]},"syndicate":{"accounts":[{"id":"U101","type":"legit","name":"Organic A","promo_cost":20,"net_spend":185,"referrals":3},{"id":"U102","type":"legit","name":"Organic B","promo_cost":20,"net_spend":140,"referrals":2},{"id":"U103","type":"legit","name":"Organic C","promo_cost":20,"net_spend":220,"referrals":4},{"id":"U104","type":"legit","name":"Organic D","promo_cost":20,"net_spend":95,"referrals":1},{"id":"U105","type":"legit","name":"Organic E","promo_cost":20,"net_spend":160,"referrals":2},{"id":"U106","type":"legit","name":"Organic F","promo_cost":20,"net_spend":310,"referrals":5},{"id":"U107","type":"legit","name":"Organic G","promo_cost":20,"net_spend":115,"referrals":1},{"id":"U108","type":"legit","name":"Organic H","promo_cost":20,"net_spend":190,"referrals":3},{"id":"U201","type":"syndicate_hub","name":"Bot Farm Ringleader","promo_cost":20,"net_spend":5,"referrals":18},{"id":"U202","type":"syndicate_spoke","name":"Bot Spoke 1","promo_cost":20,"net_spend":0,"referrals":0},{"id":"U203","type":"syndicate_spoke","name":"Bot Spoke 2","promo_cost":20,"net_spend":0,"referrals":0},{"id":"U204","type":"syndicate_spoke","name":"Bot Spoke 3","promo_cost":20,"net_spend":0,"referrals":0},{"id":"U205","type":"syndicate_spoke","name":"Bot Spoke 4","promo_cost":20,"net_spend":0,"referrals":0},{"id":"U206","type":"syndicate_spoke","name":"Bot Spoke 5","promo_cost":20,"net_spend":0,"referrals":0},{"id":"U207","type":"syndicate_spoke","name":"Bot Spoke 6","promo_cost":20,"net_spend":0,"referrals":0},{"id":"U208","type":"syndicate_spoke","name":"Bot Spoke 7","promo_cost":20,"net_spend":0,"referrals":0}]},"biomarkers":{"genes":[{"name":"CDK1","type":"robust","tumor_mean":6.8,"normal_mean":2.1,"std":0.8,"description":"Consistently overexpressed across all 30 patients"},{"name":"MYC","type":"robust","tumor_mean":7.4,"normal_mean":3.0,"std":0.9,"description":"Strong oncogenic transcription factor, widespread upregulation"},{"name":"EGFR","type":"robust","tumor_mean":5.9,"normal_mean":2.2,"std":0.7,"description":"Receptor kinase amplification across cohort"},{"name":"BRCA1","type":"robust","tumor_mean":2.2,"normal_mean":5.8,"std":0.6,"description":"Tumor suppressor loss across cohort"},{"name":"TP53","type":"robust","tumor_mean":1.9,"normal_mean":5.4,"std":0.7,"description":"Consistent downregulation / loss of function"},{"name":"LINC009","type":"brittle","tumor_mean":3.1,"normal_mean":3.0,"std":0.4,"outlier_patient":14,"outlier_val":14.5,"description":"Flat in 29 patients; massive artifact in Patient #14"},{"name":"FAM83A","type":"brittle","tumor_mean":2.8,"normal_mean":2.7,"std":0.5,"outlier_patient":3,"outlier_val":12.8,"description":"Looks significant on naive mean, driven entirely by Patient #3"},{"name":"OR2T1","type":"null","tumor_mean":3.2,"normal_mean":3.1,"std":0.6,"description":"Olfactory receptor, unexpressed noise background"},{"name":"ZNF281","type":"null","tumor_mean":4.0,"normal_mean":3.9,"std":0.5,"description":"Zinc finger, no differential expression"},{"name":"ACTB","type":"housekeeping","tumor_mean":11.2,"normal_mean":11.1,"std":0.3,"description":"Housekeeping reference gene, stable expression"}]},"smooth_jagged":{"samples":[{"val":1.2},{"val":1.5},{"val":1.9},{"val":2.3},{"val":2.8},{"val":3.1},{"val":3.4},{"val":3.9},{"val":4.2},{"val":4.7},{"val":5.1},{"val":5.8},{"val":6.3},{"val":7.1},{"val":9.5}]}}</script>
<script>/* Widgets for "The Statistical Jackknife"
 *
 * Dependency-free: no CDN, no module loading, no framework.
 * Built with DOM APIs and inline SVG for seamless local and offline viewing.
 */
"use strict";

const JK = (function () {
  const NS = "http://www.w3.org/2000/svg";
  const C = {
    primary: "#1D5C6E",
    secondary: "#C98A12",
    accent: "#7A3B6B",
    danger: "#C62828",
    success: "#2E7D32",
    ink: "#171C1B",
    muted: "#67706E",
    rule: "#D2D6D1",
    bgLight: "#F8F9FA",
    white: "#FFFFFF"
  };

  // DOM helpers
  function el(tag, attrs, kids) {
    const e = document.createElementNS(NS, tag);
    for (const k in (attrs || {})) e.setAttribute(k, attrs[k]);
    for (const c of (kids || [])) e.appendChild(c);
    return e;
  }
  function h(tag, attrs, kids) {
    const e = document.createElement(tag);
    for (const k in (attrs || {})) {
      if (k === "html") e.innerHTML = attrs[k];
      else if (k === "text") e.textContent = attrs[k];
      else if (k === "style" && typeof attrs[k] === "object") {
        Object.assign(e.style, attrs[k]);
      } else e.setAttribute(k, attrs[k]);
    }
    for (const c of (kids || [])) e.appendChild(c);
    return e;
  }
  function clear(node) {
    while (node.firstChild) node.removeChild(node.firstChild);
  }

  // --- WIDGET 1: Pseudovalues & Influence Playground ---
  function initWidget1(containerId, initialData) {
    const root = document.getElementById(containerId);
    if (!root) return;
    clear(root);

    let points = (initialData && initialData.points) 
      ? JSON.parse(JSON.stringify(initialData.points))
      : [
          {id: 1, x: 2, y: 3}, {id: 2, x: 3, y: 4}, {id: 3, x: 4, y: 5},
          {id: 4, x: 5, y: 6}, {id: 5, x: 6, y: 7}, {id: 6, x: 7, y: 8},
          {id: 7, x: 8, y: 9}, {id: 8, x: 5, y: 9.5}
        ];

    const width = 680;
    const height = 340;
    const pad = 40;

    // Controls & Summary Header
    const statPanel = h("div", {
      style: {
        display: "flex",
        flexWrap: "wrap",
        gap: "1.2rem",
        marginBottom: "0.8rem",
        fontSize: "0.9rem",
        background: "#F4F6F6",
        padding: "0.6rem 1rem",
        borderRadius: "6px",
        border: `1px solid ${C.rule}`
      }
    });

    const svgWrap = h("div", { style: { display: "flex", gap: "1rem", flexWrap: "wrap" } });
    
    // Left: 2D scatter svg
    const scatterSvg = el("svg", {
      viewBox: `0 0 380 300`,
      width: "380",
      height: "300",
      style: "background:#fff;border:1px solid #E2E6E1;border-radius:6px;cursor:crosshair"
    });

    // Right: Influence bar chart svg
    const barSvg = el("svg", {
      viewBox: `0 0 280 300`,
      width: "280",
      height: "300",
      style: "background:#fff;border:1px solid #E2E6E1;border-radius:6px"
    });

    svgWrap.appendChild(scatterSvg);
    svgWrap.appendChild(barSvg);

    const note = h("div", {
      class: "widget-note",
      text: "Drag any point on the left. Watch its influence bar (right) and the Jackknife standard error recalculate instantly."
    });

    root.appendChild(statPanel);
    root.appendChild(svgWrap);
    root.appendChild(note);

    let activeDrag = null;

    function toScreenX(x) { return pad + (x / 10) * (380 - 2 * pad); }
    function toScreenY(y) { return (300 - pad) - (y / 10) * (300 - 2 * pad); }
    function toDataX(sx) { return Math.max(0.5, Math.min(9.5, ((sx - pad) / (380 - 2 * pad)) * 10)); }
    function toDataY(sy) { return Math.max(0.5, Math.min(9.5, (((300 - pad) - sy) / (300 - 2 * pad)) * 10)); }

    function update() {
      const n = points.length;
      // Estimator: Correlation r (or mean y)
      // Let's use correlation r as a classic non-linear statistic
      const sumX = points.reduce((s, p) => s + p.x, 0);
      const sumY = points.reduce((s, p) => s + p.y, 0);
      const meanX = sumX / n;
      const meanY = sumY / n;

      function calcSlope(pts) {
        const mX = pts.reduce((s, p) => s + p.x, 0) / pts.length;
        const mY = pts.reduce((s, p) => s + p.y, 0) / pts.length;
        let num = 0, den = 0;
        for (const p of pts) {
          num += (p.x - mX) * (p.y - mY);
          den += (p.x - mX) * (p.x - mX);
        }
        return den === 0 ? 0 : num / den;
      }

      const thetaHat = calcSlope(points);

      // Leave-one-out
      const theta_i = [];
      const pseudovalues = [];
      for (let i = 0; i < n; i++) {
        const sub = points.filter((_, idx) => idx !== i);
        const t_i = calcSlope(sub);
        theta_i.push(t_i);
        const J_i = n * thetaHat - (n - 1) * t_i;
        pseudovalues.push(J_i);
      }

      const thetaDot = theta_i.reduce((s, v) => s + v, 0) / n;
      const thetaJack = n * thetaHat - (n - 1) * thetaDot;
      const biasEst = (n - 1) * (thetaDot - thetaHat);

      // Jackknife variance
      let sumSqDiff = 0;
      for (let i = 0; i < n; i++) {
        sumSqDiff += Math.pow(theta_i[i] - thetaDot, 2);
      }
      const vJack = ((n - 1) / n) * sumSqDiff;
      const seJack = Math.sqrt(vJack);

      // Influence functions
      const influences = pseudovalues.map(j => j - thetaJack);

      // Update statPanel
      clear(statPanel);
      statPanel.appendChild(h("div", {
        html: `<strong>Sample slope:</strong> <span class="metric-pill">${thetaHat.toFixed(3)}</span>`
      }));
      statPanel.appendChild(h("div", {
        html: `<strong>Jackknife-corrected slope:</strong> <span class="metric-pill positive">${thetaJack.toFixed(3)}</span>`
      }));
      statPanel.appendChild(h("div", {
        html: `<strong>Est. Bias:</strong> <span class="metric-pill ${Math.abs(biasEst) > 0.05 ? 'warning' : ''}">${biasEst.toFixed(3)}</span>`
      }));
      statPanel.appendChild(h("div", {
        html: `<strong>Jackknife SE:</strong> <span class="metric-pill">${seJack.toFixed(3)}</span>`
      }));

      // Render Scatter SVG
      clear(scatterSvg);
      // Grid lines
      for (let g = 2; g <= 8; g += 2) {
        scatterSvg.appendChild(el("line", {
          x1: toScreenX(g), y1: pad, x2: toScreenX(g), y2: 300 - pad,
          stroke: "#EEF0F0", "stroke-width": "1"
        }));
        scatterSvg.appendChild(el("line", {
          x1: pad, y1: toScreenY(g), x2: 380 - pad, y2: toScreenY(g),
          stroke: "#EEF0F0", "stroke-width": "1"
        }));
      }

      // Regression line
      const lineX1 = 0.5, lineX2 = 9.5;
      const lineY1 = meanY + thetaHat * (lineX1 - meanX);
      const lineY2 = meanY + thetaHat * (lineX2 - meanX);
      scatterSvg.appendChild(el("line", {
        x1: toScreenX(lineX1), y1: toScreenY(lineY1),
        x2: toScreenX(lineX2), y2: toScreenY(lineY2),
        stroke: C.primary, "stroke-width": "2", "stroke-dasharray": "4 2"
      }));

      // Points
      points.forEach((p, idx) => {
        const cx = toScreenX(p.x);
        const cy = toScreenY(p.y);
        const infl = Math.abs(influences[idx]);
        const isHigh = infl > 0.3;

        const circle = el("circle", {
          cx, cy, r: isHigh ? "8" : "6",
          fill: isHigh ? C.danger : C.primary,
          stroke: "#fff",
          "stroke-width": "2",
          style: "cursor:grab"
        });

        circle.addEventListener("mousedown", (e) => {
          activeDrag = idx;
          e.preventDefault();
        });
        circle.addEventListener("touchstart", (e) => {
          activeDrag = idx;
          e.preventDefault();
        }, { passive: false });

        scatterSvg.appendChild(circle);

        // Point label
        scatterSvg.appendChild(el("text", {
          x: cx + 8, y: cy - 6,
          fill: C.muted, "font-size": "10", "font-family": "monospace"
        }, [document.createTextNode(`#${p.id}`)]));
      });

      // Render Bar SVG (Influence)
      clear(barSvg);
      barSvg.appendChild(el("text", {
        x: 140, y: 22, "text-anchor": "middle",
        fill: C.ink, "font-size": "12", "font-weight": "bold"
      }, [document.createTextNode("Empirical Influence (Jᵢ - β̂_jack)")]));

      const midX = 140;
      barSvg.appendChild(el("line", {
        x1: midX, y1: 35, x2: midX, y2: 280,
        stroke: C.rule, "stroke-width": "1.5"
      }));

      const maxAbsInfl = Math.max(0.6, ...influences.map(Math.abs));
      const rowHeight = (240) / n;

      influences.forEach((inf, idx) => {
        const y = 45 + idx * rowHeight;
        const barW = (inf / maxAbsInfl) * 110;
        const isPos = inf >= 0;

        const bar = el("rect", {
          x: isPos ? midX : midX + barW,
          y: y - 6,
          width: Math.abs(barW),
          height: Math.max(4, rowHeight - 4),
          fill: Math.abs(inf) > 0.3 ? C.danger : C.primary,
          rx: "2"
        });
        barSvg.appendChild(bar);

        barSvg.appendChild(el("text", {
          x: isPos ? midX - 8 : midX + 8,
          y: y + 4,
          "text-anchor": isPos ? "end" : "start",
          fill: C.muted, "font-size": "10", "font-family": "monospace"
        }, [document.createTextNode(`#${points[idx].id}`)]));
      });
    }

    function handleMove(clientX, clientY) {
      if (activeDrag === null) return;
      const rect = scatterSvg.getBoundingClientRect();
      const sx = clientX - rect.left;
      const sy = clientY - rect.top;
      points[activeDrag].x = toDataX(sx);
      points[activeDrag].y = toDataY(sy);
      update();
    }

    window.addEventListener("mousemove", (e) => handleMove(e.clientX, e.clientY));
    window.addEventListener("touchmove", (e) => {
      if (activeDrag !== null && e.touches.length > 0) {
        handleMove(e.touches[0].clientX, e.touches[0].clientY);
      }
    }, { passive: false });

    window.addEventListener("mouseup", () => { activeDrag = null; });
    window.addEventListener("touchend", () => { activeDrag = null; });

    update();
  }

  // --- WIDGET 2: Referral Syndicate Unmasker ---
  function initWidget2(containerId, initialData) {
    const root = document.getElementById(containerId);
    if (!root) return;
    clear(root);

    const accounts = (initialData && initialData.accounts) 
      ? JSON.parse(JSON.stringify(initialData.accounts))
      : [];

    let bonus = 20;
    let botSpokes = 8;

    // Controls
    const ctrlWrap = h("div", { class: "widget-controls" });

    const bonusSlider = h("input", {
      type: "range", min: "10", max: "50", step: "5", value: String(bonus),
      style: { width: "130px" }
    });
    const bonusVal = h("span", { text: `$${bonus}`, style: { fontWeight: "bold" } });
    bonusSlider.addEventListener("input", (e) => {
      bonus = parseInt(e.target.value);
      bonusVal.textContent = `$${bonus}`;
      render();
    });

    const botSlider = h("input", {
      type: "range", min: "0", max: "15", step: "1", value: String(botSpokes),
      style: { width: "130px" }
    });
    const botVal = h("span", { text: `${botSpokes} bots`, style: { fontWeight: "bold" } });
    botSlider.addEventListener("input", (e) => {
      botSpokes = parseInt(e.target.value);
      botVal.textContent = `${botSpokes} bots`;
      render();
    });

    ctrlWrap.appendChild(h("label", { style: { display: "flex", alignItems: "center", gap: "0.5rem", fontSize: "0.88rem" } }, [
      h("span", { text: "Promo Credit:" }), bonusSlider, bonusVal
    ]));
    ctrlWrap.appendChild(h("label", { style: { display: "flex", alignItems: "center", gap: "0.5rem", fontSize: "0.88rem" } }, [
      h("span", { text: "Syndicate Bot Nodes:" }), botSlider, botVal
    ]));

    const cardContainer = h("div", {
      style: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
        gap: "1rem",
        marginTop: "1rem"
      }
    });

    const statusBanner = h("div", { style: { marginTop: "1rem" } });

    root.appendChild(ctrlWrap);
    root.appendChild(cardContainer);
    root.appendChild(statusBanner);

    function render() {
      // Build dynamic user list
      const activeUsers = accounts.filter(a => a.type === "legit" || a.type === "syndicate_hub");
      for (let b = 1; b <= botSpokes; b++) {
        activeUsers.push({
          id: `BOT-${b}`,
          type: "syndicate_spoke",
          name: `Synthetic Node ${b}`,
          promo_cost: bonus,
          net_spend: 0,
          referrals: 0
        });
      }
      // Charge each account the credits it caused: its own signup bonus plus one
      // bonus per referee it recruited. The hub's referral count tracks the bot slider,
      // so its cost is the whole syndicate's payout, not a single $20 credit.
      activeUsers.forEach(u => {
        const referrals = u.type === "syndicate_hub" ? botSpokes : (u.referrals || 0);
        u.referrals = referrals;
        u.promo_cost = bonus * (1 + referrals);
      });

      const n = activeUsers.length;
      const totalPromo = activeUsers.reduce((s, u) => s + u.promo_cost, 0);
      const totalSpend = activeUsers.reduce((s, u) => s + u.net_spend, 0);
      const clusterRatio = totalSpend > 0 ? (totalPromo / totalSpend) : 999;

      // Leave-one-out
      const results = activeUsers.map((u, idx) => {
        const sub = activeUsers.filter((_, i) => i !== idx);
        const subP = sub.reduce((s, x) => s + x.promo_cost, 0);
        const subS = sub.reduce((s, x) => s + x.net_spend, 0);
        const subR = subS > 0 ? (subP / subS) : 999;
        const pseudovalue = n * clusterRatio - (n - 1) * subR;
        const leverage = clusterRatio - subR; // How much health drops when this user is PRESENT
        return { ...u, subR, pseudovalue, leverage };
      });

      // Sort by absolute leverage / pseudovalue anomaly
      results.sort((a, b) => b.leverage - a.leverage);

      clear(cardContainer);

      // Summary Card
      const summaryCard = h("div", {
        style: {
          background: "#FFFFFF",
          border: `1px solid ${C.rule}`,
          borderRadius: "8px",
          padding: "1rem"
        }
      }, [
        h("h4", { text: "Cohort Unit Economics", style: { margin: "0 0 0.5rem 0", color: C.ink } }),
        h("div", { html: `<strong>Cohort Size:</strong> ${n} users (${botSpokes} syndicate bots)` }),
        h("div", { html: `<strong>Total Promo Burn:</strong> $${totalPromo}` }),
        h("div", { html: `<strong>Total Net Revenue:</strong> $${totalSpend}` }),
        h("div", {
          style: { marginTop: "0.5rem", fontSize: "1.1rem" },
          html: `<strong>Promo-to-Spend Ratio:</strong> <span class="metric-pill ${clusterRatio > 0.5 ? 'danger' : 'positive'}">${clusterRatio.toFixed(3)}</span>`
        })
      ]);
      cardContainer.appendChild(summaryCard);

      // Top Anomaly Table Card
      const topAnomalies = results.slice(0, 5);
      const anomalyCard = h("div", {
        style: {
          background: "#FFFFFF",
          border: `1px solid ${C.rule}`,
          borderRadius: "8px",
          padding: "1rem"
        }
      }, [
        h("h4", { text: "Top Jackknife Leverage (Who Breaks the Metric?)", style: { margin: "0 0 0.5rem 0", color: C.ink } }),
        h("table", { style: { width: "100%", fontSize: "0.85rem", borderCollapse: "collapse" } }, [
          h("thead", {}, [
            h("tr", { style: { borderBottom: `1px solid ${C.rule}`, textAlign: "left", color: C.muted } }, [
              h("th", { text: "User" }),
              h("th", { text: "Spend" }),
              h("th", { text: "Ratio without them" }),
              h("th", { text: "Pseudovalue" })
            ])
          ]),
          h("tbody", {}, topAnomalies.map(u => {
            const isRingleader = u.type === "syndicate_hub";
            return h("tr", {
              style: {
                borderBottom: "1px solid #F0F2F2",
                background: isRingleader ? "#FFF5F5" : "transparent",
                fontWeight: isRingleader ? "bold" : "normal",
                color: isRingleader ? C.danger : C.ink
              }
            }, [
              h("td", { text: u.name }),
              h("td", { text: `$${u.net_spend}` }),
              h("td", { text: u.subR.toFixed(3) }),
              h("td", { text: u.pseudovalue.toFixed(2) })
            ]);
          }))
        ])
      ]);
      cardContainer.appendChild(anomalyCard);

      // Status alert
      clear(statusBanner);
      const ringleader = results.find(r => r.type === "syndicate_hub");
      if (ringleader && botSpokes > 0) {
        statusBanner.appendChild(h("div", {
          class: "jackknife-hero",
          style: { borderColor: C.danger, background: "rgba(198, 40, 40, 0.05)" },
          html: `<strong>🎯 Jackknife Isolation:</strong> Removing <em>${ringleader.name}</em> (${botSpokes} referrals, $${ringleader.net_spend} spend) causes the cohort Promo-to-Spend ratio to drop from <strong>${clusterRatio.toFixed(3)}</strong> to <strong>${ringleader.subR.toFixed(3)}</strong>. The jackknife identifies the coordinator without requiring network-graph clustering.`
        }));
      }
    }

    render();
  }

  // --- WIDGET 3: Biomarker Stability Stress-Tester ---
  function initWidget3(containerId, initialData) {
    const root = document.getElementById(containerId);
    if (!root) return;
    clear(root);

    const genes = (initialData && initialData.genes) 
      ? JSON.parse(JSON.stringify(initialData.genes))
      : [];

    let injectOutlier = false;

    const ctrlWrap = h("div", { class: "widget-controls", style: { alignItems: "center" } });
    const toggleBtn = h("button", {
      text: "⚡ Inject Outlier Patient into LINC009",
      style: {
        background: C.primary,
        color: "#FFF",
        border: "none",
        padding: "0.5rem 1rem",
        borderRadius: "4px",
        cursor: "pointer",
        fontWeight: "600"
      }
    });
    toggleBtn.addEventListener("click", () => {
      injectOutlier = !injectOutlier;
      toggleBtn.textContent = injectOutlier 
        ? "🔄 Remove Outlier Patient (Restore Baseline)"
        : "⚡ Inject Outlier Patient into LINC009";
      toggleBtn.style.background = injectOutlier ? C.danger : C.primary;
      render();
    });

    ctrlWrap.appendChild(toggleBtn);
    ctrlWrap.appendChild(h("span", {
      style: { fontSize: "0.85rem", color: C.muted },
      text: "Watch how naive fold change promotes a fragile target, while Jackknife Stability Index demotes it."
    }));

    const displayGrid = h("div", {
      style: {
        display: "grid",
        gridTemplateColumns: "1fr 1fr",
        gap: "1rem",
        marginTop: "1rem"
      }
    });

    root.appendChild(ctrlWrap);
    root.appendChild(displayGrid);

    function simulateGene(gene, n = 30) {
      // Create N patient expression differences
      let diffs = [];
      for (let i = 0; i < n; i++) {
        // Normal dist approx
        const base = (gene.tumor_mean - gene.normal_mean) + (Math.sin(i * 3 + gene.name.length) * gene.std);
        diffs.push(base);
      }
      if (injectOutlier && gene.name === "LINC009") {
        diffs[14] = 12.5; // Inject massive outlier in patient 15
      }

      const meanLFC = diffs.reduce((s, v) => s + v, 0) / n;

      // Jackknife
      const subMeans = diffs.map((_, idx) => {
        const sub = diffs.filter((_, i) => i !== idx);
        return sub.reduce((s, v) => s + v, 0) / (n - 1);
      });
      const thetaDot = subMeans.reduce((s, v) => s + v, 0) / n;
      const jackLFC = n * meanLFC - (n - 1) * thetaDot;
      const vJack = ((n - 1) / n) * subMeans.reduce((s, m) => s + Math.pow(m - thetaDot, 2), 0);
      const seJack = Math.sqrt(vJack);
      const stability = seJack > 0 ? Math.abs(jackLFC) / seJack : 0;

      return {
        name: gene.name,
        type: gene.type,
        meanLFC,
        jackLFC,
        seJack,
        stability
      };
    }

    function render() {
      const results = genes.map(g => simulateGene(g, 30));

      // Sort by naive LFC
      const naiveSorted = [...results].sort((a, b) => b.meanLFC - a.meanLFC);
      // Sort by Jackknife Stability
      const jackSorted = [...results].sort((a, b) => b.stability - a.stability);

      clear(displayGrid);

      // Left Column: Naive Ranking
      const leftCol = h("div", {
        style: { background: "#FFFFFF", border: `1px solid ${C.rule}`, borderRadius: "8px", padding: "1rem" }
      }, [
        h("h4", { text: "Naive Ranking (Mean Log-Fold Change)", style: { margin: "0 0 0.5rem 0", color: C.ink } }),
        h("div", { style: { fontSize: "0.8rem", color: C.muted, marginBottom: "0.5rem" }, text: "Ranks genes solely by cohort sample average." }),
        h("table", { style: { width: "100%", fontSize: "0.85rem", borderCollapse: "collapse" } }, [
          h("thead", {}, [
            h("tr", { style: { borderBottom: `1px solid ${C.rule}`, textAlign: "left", color: C.muted } }, [
              h("th", { text: "Rank" }),
              h("th", { text: "Gene" }),
              h("th", { text: "Mean LFC" })
            ])
          ]),
          h("tbody", {}, naiveSorted.slice(0, 5).map((g, i) => {
            const isLinc = g.name === "LINC009";
            return h("tr", {
              style: {
                borderBottom: "1px solid #F0F2F2",
                background: isLinc && injectOutlier ? "#FFF5F5" : "transparent",
                fontWeight: isLinc && injectOutlier ? "bold" : "normal",
                color: isLinc && injectOutlier ? C.danger : C.ink
              }
            }, [
              h("td", { text: `#${i + 1}` }),
              h("td", { text: `${g.name} ${isLinc && injectOutlier ? '⚠️' : ''}` }),
              h("td", { text: g.meanLFC.toFixed(2) })
            ]);
          }))
        ])
      ]);

      // Right Column: Jackknife Stability Ranking
      const rightCol = h("div", {
        style: { background: "#FFFFFF", border: `1px solid ${C.rule}`, borderRadius: "8px", padding: "1rem" }
      }, [
        h("h4", { text: "Jackknife Stability Ranking (|LFC| / SE_jack)", style: { margin: "0 0 0.5rem 0", color: C.primary } }),
        h("div", { style: { fontSize: "0.8rem", color: C.muted, marginBottom: "0.5rem" }, text: "Penalizes genes with high leave-one-out variance." }),
        h("table", { style: { width: "100%", fontSize: "0.85rem", borderCollapse: "collapse" } }, [
          h("thead", {}, [
            h("tr", { style: { borderBottom: `1px solid ${C.rule}`, textAlign: "left", color: C.muted } }, [
              h("th", { text: "Rank" }),
              h("th", { text: "Gene" }),
              h("th", { text: "SE_jack" }),
              h("th", { text: "Stability" })
            ])
          ]),
          h("tbody", {}, jackSorted.slice(0, 5).map((g, i) => {
            const isLinc = g.name === "LINC009";
            return h("tr", {
              style: {
                borderBottom: "1px solid #F0F2F2",
                background: isLinc && injectOutlier ? "#FFF5F5" : "transparent",
                color: isLinc && injectOutlier ? C.danger : C.ink
              }
            }, [
              h("td", { text: `#${i + 1}` }),
              h("td", { text: g.name }),
              h("td", { text: g.seJack.toFixed(2) }),
              h("td", { text: g.stability.toFixed(2), style: { fontWeight: "bold" } })
            ]);
          }))
        ])
      ]);

      displayGrid.appendChild(leftCol);
      displayGrid.appendChild(rightCol);
    }

    render();
  }

  // --- WIDGET 4: Smooth vs. Non-Smooth Stress Test ---
  function initWidget4(containerId) {
    const root = document.getElementById(containerId);
    if (!root) return;
    clear(root);

    let statType = "mean";
    const sample = [1.2, 1.8, 2.3, 2.9, 3.4, 3.8, 4.2, 4.9, 5.5, 6.2, 9.8];

    const ctrlWrap = h("div", { class: "widget-controls" });
    const radioMean = h("input", { type: "radio", id: "w4-opt-mean", name: "w4-stat", value: "mean", checked: true });
    const radioMed = h("input", { type: "radio", id: "w4-opt-med", name: "w4-stat", value: "median" });

    radioMean.addEventListener("change", () => { statType = "mean"; render(); });
    radioMed.addEventListener("change", () => { statType = "median"; render(); });

    ctrlWrap.appendChild(h("label", { style: { display: "inline-flex", alignItems: "center", gap: "0.3rem", fontSize: "0.9rem", cursor: "pointer" } }, [
      radioMean, h("span", { text: "Smooth: Sample Mean" })
    ]));
    ctrlWrap.appendChild(h("label", { style: { display: "inline-flex", alignItems: "center", gap: "0.3rem", fontSize: "0.9rem", cursor: "pointer" } }, [
      radioMed, h("span", { text: "Non-Smooth: Sample Median" })
    ]));

    const canvasWrap = h("div", { style: { background: "#FFF", border: `1px solid ${C.rule}`, borderRadius: "8px", padding: "1rem", marginTop: "1rem" } });

    root.appendChild(ctrlWrap);
    root.appendChild(canvasWrap);

    function calcMedian(arr) {
      const s = [...arr].sort((a, b) => a - b);
      const m = Math.floor(s.length / 2);
      return s.length % 2 === 0 ? (s[m - 1] + s[m]) / 2 : s[m];
    }
    function calcMean(arr) {
      return arr.reduce((s, v) => s + v, 0) / arr.length;
    }

    function render() {
      clear(canvasWrap);
      const n = sample.length;
      const fullEst = statType === "mean" ? calcMean(sample) : calcMedian(sample);
      const subEsts = sample.map((_, idx) => {
        const sub = sample.filter((_, i) => i !== idx);
        return statType === "mean" ? calcMean(sub) : calcMedian(sub);
      });

      const deltas = subEsts.map(sub => fullEst - sub);

      const svgEl = el("svg", {
        viewBox: "0 0 600 200",
        width: "100%",
        height: "200",
        style: "display:block"
      });

      // Axis
      svgEl.appendChild(el("line", {
        x1: "50", y1: "150", x2: "550", y2: "150",
        stroke: C.rule, "stroke-width": "1.5"
      }));

      // Plot stem lines for leave-one-out delta
      const maxDelta = Math.max(0.2, ...deltas.map(Math.abs));
      deltas.forEach((d, idx) => {
        const x = 70 + idx * 44;
        const barH = (d / maxDelta) * 80;
        const y = 150 - barH;

        svgEl.appendChild(el("line", {
          x1: x, y1: "150", x2: x, y2: y,
          stroke: statType === "mean" ? C.primary : C.danger,
          "stroke-width": "3"
        }));
        svgEl.appendChild(el("circle", {
          cx: x, cy: y, r: "5",
          fill: statType === "mean" ? C.primary : C.danger
        }));

        svgEl.appendChild(el("text", {
          x, y: "170", "text-anchor": "middle",
          fill: C.muted, "font-size": "10", "font-family": "monospace"
        }, [document.createTextNode(`-${idx + 1}`)]));
      });

      canvasWrap.appendChild(svgEl);

      const expl = h("div", {
        style: { marginTop: "0.8rem", fontSize: "0.88rem", color: C.ink },
        html: statType === "mean"
          ? `<strong>Smooth Response:</strong> When leaving out observations from the mean, each point creates a gentle, continuous shift proportional to its distance from the sample mean. The influence function is differentiable.`
          : `<strong>Discontinuous Jumps:</strong> For the median, dropping points that are not adjacent to the center produces a change of exactly <strong>0.00</strong>, while dropping a central point causes an abrupt step jump. The jackknife variance formula fails because the sample median lacks Fréchet differentiability.`
      });
      canvasWrap.appendChild(expl);
    }

    render();
  }

  return {
    initWidget1,
    initWidget2,
    initWidget3,
    initWidget4
  };
})();

// Auto-initialize when DOM and JSON script data are ready
document.addEventListener("DOMContentLoaded", () => {
  const dataScript = document.getElementById("jackknife-data");
  let data = {};
  if (dataScript) {
    try {
      data = JSON.parse(dataScript.textContent);
    } catch (e) {
      console.error("Error parsing jackknife data payload", e);
    }
  }

  if (document.getElementById("widget-pseudovalues")) {
    JK.initWidget1("widget-pseudovalues", data.toy);
  }
  if (document.getElementById("widget-syndicate")) {
    JK.initWidget2("widget-syndicate", data.syndicate);
  }
  if (document.getElementById("widget-biomarkers")) {
    JK.initWidget3("widget-biomarkers", data.biomarkers);
  }
  if (document.getElementById("widget-smooth-jagged")) {
    JK.initWidget4("widget-smooth-jagged");
  }
});
</script>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/statistical-jackknife/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>