<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-08-30">

<title>Tensor Inverses in Practice – Synthetic Musings</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-a9fbfb7a887b62f4d313264b6afc3d0d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-784891f9eaa39f9ffae573c9e0f86e17.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">
<script src="../../widget-kit/kit.js"></script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Tensor Inverses in Practice – Synthetic Musings">
<meta property="og:description" content="Technical write-ups on machine learning, statistics, linear algebra, and the tooling around them, by Ravi Kalia.">
<meta property="og:image" content="https://project-delphi.github.io/ml-blog/posts/tensor-inverses-in-practice/cover.png">
<meta property="og:site_name" content="Synthetic Musings">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:title" content="Tensor Inverses in Practice – Synthetic Musings">
<meta name="twitter:description" content="Technical write-ups on machine learning, statistics, linear algebra, and the tooling around them, by Ravi Kalia.">
<meta name="twitter:image" content="https://project-delphi.github.io/ml-blog/posts/tensor-inverses-in-practice/cover.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="630">
<meta name="twitter:image-width" content="1200">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Synthetic Musings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="Home">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Tensor Inverses in Practice</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Linear Algebra</div>
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Numerical Methods</div>
                <div class="quarto-category">Tensors</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 30, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#words-used-here" id="toc-words-used-here" class="nav-link active" data-scroll-target="#words-used-here"><span class="header-section-number">1</span> Words used here</a></li>
  <li><a href="#the-kinds-of-tensor-inverse" id="toc-the-kinds-of-tensor-inverse" class="nav-link" data-scroll-target="#the-kinds-of-tensor-inverse"><span class="header-section-number">2</span> The kinds of tensor inverse</a>
  <ul class="collapse">
  <li><a href="#two-rules-that-come-with-the-table" id="toc-two-rules-that-come-with-the-table" class="nav-link" data-scroll-target="#two-rules-that-come-with-the-table"><span class="header-section-number">2.1</span> Two rules that come with the table</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">3</span> Data</a>
  <ul class="collapse">
  <li><a href="#an-off-axis-carbonepoxy-ply" id="toc-an-off-axis-carbonepoxy-ply" class="nav-link" data-scroll-target="#an-off-axis-carbonepoxy-ply"><span class="header-section-number">3.1</span> An off-axis carbon/epoxy ply</a></li>
  <li><a href="#pavia-university" id="toc-pavia-university" class="nav-link" data-scroll-target="#pavia-university"><span class="header-section-number">3.2</span> Pavia University</a></li>
  <li><a href="#a-synthetic-four-dimensional-scan" id="toc-a-synthetic-four-dimensional-scan" class="nav-link" data-scroll-target="#a-synthetic-four-dimensional-scan"><span class="header-section-number">3.3</span> A synthetic four-dimensional scan</a></li>
  <li><a href="#chicago-incident-counts" id="toc-chicago-incident-counts" class="nav-link" data-scroll-target="#chicago-incident-counts"><span class="header-section-number">3.4</span> Chicago incident counts</a></li>
  </ul></li>
  <li><a href="#compliance-the-einstein-product" id="toc-compliance-the-einstein-product" class="nav-link" data-scroll-target="#compliance-the-einstein-product"><span class="header-section-number">4</span> Compliance: the Einstein product</a>
  <ul class="collapse">
  <li><a href="#why-voigt-notation-is-a-flattening-that-works" id="toc-why-voigt-notation-is-a-flattening-that-works" class="nav-link" data-scroll-target="#why-voigt-notation-is-a-flattening-that-works"><span class="header-section-number">4.1</span> Why Voigt notation is a flattening that works</a></li>
  <li><a href="#the-mistake-voigt-still-lets-you-make" id="toc-the-mistake-voigt-still-lets-you-make" class="nav-link" data-scroll-target="#the-mistake-voigt-still-lets-you-make"><span class="header-section-number">4.2</span> The mistake Voigt still lets you make</a></li>
  </ul></li>
  <li><a href="#hyperspectral-restoration-the-t-product" id="toc-hyperspectral-restoration-the-t-product" class="nav-link" data-scroll-target="#hyperspectral-restoration-the-t-product"><span class="header-section-number">5</span> Hyperspectral restoration: the t-product</a></li>
  <li><a href="#the-t-inverse-stage-by-stage" id="toc-the-t-inverse-stage-by-stage" class="nav-link" data-scroll-target="#the-t-inverse-stage-by-stage"><span class="header-section-number">6</span> The t-inverse, stage by stage</a></li>
  <li><a href="#task-maps-the-mode-n-pseudoinverse" id="toc-task-maps-the-mode-n-pseudoinverse" class="nav-link" data-scroll-target="#task-maps-the-mode-n-pseudoinverse"><span class="header-section-number">7</span> Task maps: the mode-<span class="math inline">\(n\)</span> pseudoinverse</a></li>
  <li><a href="#urban-demand-a-separable-precision" id="toc-urban-demand-a-separable-precision" class="nav-link" data-scroll-target="#urban-demand-a-separable-precision"><span class="header-section-number">8</span> Urban demand: a separable precision</a></li>
  <li><a href="#why-not-just-flatten" id="toc-why-not-just-flatten" class="nav-link" data-scroll-target="#why-not-just-flatten"><span class="header-section-number">9</span> Why not just flatten</a></li>
  <li><a href="#open-problems" id="toc-open-problems" class="nav-link" data-scroll-target="#open-problems"><span class="header-section-number">10</span> Open problems</a></li>
  <li><a href="#next-steps" id="toc-next-steps" class="nav-link" data-scroll-target="#next-steps"><span class="header-section-number">11</span> Next steps</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">12</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tensor-inverses-in-practice/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Tensor Inverses in Practice</figcaption>
</figure>
</div>
<p>Four real problems where the operator is a tensor. For each one, this post names the product that applies, takes the inverse in that product, and measures what flattening the tensor into a matrix would have cost.</p>
<p>Two earlier posts give the background. <a href="../tensor-factorizations/">Tensor Factorizations and Tensor Inverses</a> has the algebra. <a href="../uses-of-tensor-factorizations/">Uses of Tensor Factorizations</a> has the compression case. The first one shows that a tensor has no default product. Because of that, it has no default inverse either.</p>
<p>This post answers the question that leaves open. For a given problem, which product applies, and what does flattening cost?</p>
<p>The table of inverses comes first. Then the four problems. Then all the numbers side by side.</p>
<section id="words-used-here" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="words-used-here"><span class="header-section-number">1</span> Words used here</h2>
<p>Some of these words have a different everyday meaning. This is what they mean in this post.</p>
<ul>
<li><strong>Mode.</strong> One axis of an array. A <span class="math inline">\(52\times24\times8\)</span> array has three modes.</li>
<li><strong>Order.</strong> How many modes an array has. A vector has order 1, a matrix order 2.</li>
<li><strong>Frontal slice.</strong> For a three-mode array <span class="math inline">\(\mathcal{A}\)</span>, the matrix <span class="math inline">\(\mathcal{A}[:,:,k]\)</span>. There is one for each value of <span class="math inline">\(k\)</span>.</li>
<li><strong>Flatten.</strong> Rearrange a tensor into a matrix or a vector. Other papers say <em>unfold</em> or <em>vectorise</em> for the same idea. This post says <em>flatten</em> throughout.</li>
<li><strong>Operator.</strong> Anything that takes an input and returns an output. Here it is usually a tensor that takes a tensor and returns a tensor.</li>
<li><strong>Rank.</strong> How many independent directions an operator really uses. An operator on nine dimensions can have rank 6.</li>
<li><strong>Null space.</strong> The set of inputs that an operator sends to zero. An operator with a null space larger than <span class="math inline">\(\{0\}\)</span> has no inverse.</li>
<li><strong>Inverse.</strong> The operator that undoes another operator.</li>
<li><strong>Pseudoinverse.</strong> What you use when no inverse exists. It undoes the operator on the directions the operator keeps, and returns zero on the directions the operator destroys.</li>
<li><strong>Condition number, <span class="math inline">\(\kappa\)</span>.</strong> How much an operator can magnify an error. If <span class="math inline">\(\kappa = 10^{12}\)</span>, an error in the twelfth digit of the input can reach the first digit of the output.</li>
<li><strong>Residual.</strong> How far a computed answer sits from the answer it should give.</li>
<li><strong>Covariance.</strong> A table saying how strongly each pair of measurements moves together.</li>
<li><strong>Precision matrix.</strong> The inverse of a covariance matrix. Here the word does not mean accuracy.</li>
</ul>
</section>
<section id="the-kinds-of-tensor-inverse" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="the-kinds-of-tensor-inverse"><span class="header-section-number">2</span> The kinds of tensor inverse</h2>
<p>A matrix inverse undoes matrix multiplication. There is one matrix product, so there is one matrix inverse.</p>
<p>Tensors work differently. There are several tensor products, and each one has its own inverse. You cannot use one in place of another, and none of them is <em>the</em> tensor inverse.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Inverse</th>
<th>Product it inverts</th>
<th>Order and shape it needs</th>
<th>Reach for it when</th>
<th>What it costs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Mode-<span class="math inline">\(n\)</span> pseudoinverse</strong></td>
<td>mode-<span class="math inline">\(n\)</span> product <span class="math inline">\(\times_n\)</span></td>
<td>any order</td>
<td>you want to recover a factor, a mixing matrix, or a change of basis along <strong>one</strong> mode: <span class="math inline">\(A = Y_{(n)}X_{(n)}^{\dagger}\)</span></td>
<td>it inverts a matrix that acts on one mode. It does <strong>not</strong> invert the tensor. Readers confuse these two more often than anything else in this table</td>
</tr>
<tr class="even">
<td><strong>t-inverse / t-pseudoinverse</strong></td>
<td>t-product <span class="math inline">\(*\)</span></td>
<td>third order, with a meaningful third mode</td>
<td>the third mode is time, wavelength, or a frequency grid: video, hyperspectral cubes, some fMRI layouts</td>
<td>one FFT along mode 3, then <span class="math inline">\(n_3\)</span> matrix inverses. Each slice is inverted on its own, so a single bad slice ruins the whole answer</td>
</tr>
<tr class="odd">
<td><strong>Einstein-product inverse</strong></td>
<td>Einstein product <span class="math inline">\(\circledast\)</span></td>
<td>even order, square: <span class="math inline">\(I_1{\times}\cdots{\times}I_N{\times}I_1{\times}\cdots{\times}I_N\)</span></td>
<td>the tensor really <em>is</em> a linear map that takes a tensor and returns one: stiffness and compliance, or a PDE written out on a grid</td>
<td>it is the same object as a <span class="math inline">\((\prod_k I_k)^2\)</span> matrix, and it exists exactly when that matrix can be inverted</td>
</tr>
<tr class="even">
<td><strong>Multilinear Moore–Penrose</strong></td>
<td>Einstein product</td>
<td>even order, rectangular or rank-deficient</td>
<td>same setting, but the operator is not square or not full rank</td>
<td>the one object that satisfies the four Penrose conditions; at order 2 it is the ordinary matrix pseudoinverse</td>
</tr>
<tr class="odd">
<td><strong>Tucker- or TT-format inverse</strong></td>
<td>mode products, TT contraction</td>
<td>any order, low multilinear or TT rank</td>
<td>the full operator will not fit in memory, and you need the inverse stored in the same compressed form</td>
<td>only approximate. The inverse usually needs a higher rank than the operator</td>
</tr>
<tr class="even">
<td><strong>CP-based approximate inverse</strong></td>
<td>—</td>
<td>any order</td>
<td>a rough, cheap approximation is enough and you never need the exact inverse</td>
<td>nothing guarantees that it exists or that it is unique. Treat it as an approximation, not an inverse</td>
</tr>
<tr class="odd">
<td><strong>Kronecker-separable precision</strong></td>
<td>—</td>
<td>any order</td>
<td>you are modelling a covariance over a multi-way array (the tensor-normal or matrix-normal model)</td>
<td><strong>not a tensor inverse at all.</strong> You are assuming that the inverse splits mode by mode. It is in this table because people mistake it for one</td>
</tr>
</tbody>
</table>
<section id="two-rules-that-come-with-the-table" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="two-rules-that-come-with-the-table"><span class="header-section-number">2.1</span> Two rules that come with the table</h3>
<p><strong>In real work you solve, you do not invert.</strong> This is the same rule as for matrices. Tensor Krylov methods, such as t-product GMRES, find <span class="math inline">\(\mathcal{X}\)</span> in <span class="math inline">\(\mathcal{A} * \mathcal{X} = \mathcal{B}\)</span> without ever building <span class="math inline">\(\mathcal{A}^{-1}\)</span> (El Guide et al.&nbsp;2021). This post builds the inverse anyway, so that you can see what it looks like. That is a choice made for teaching, not advice for production code.</p>
<p><strong>Using the wrong product is a mistake of kind, not a mistake of accuracy.</strong> Suppose <span class="math inline">\(\lVert \mathcal{A} \times_n \mathcal{X} - \mathcal{B}\rVert\)</span> comes out small. That tells you nothing about <span class="math inline">\(\mathcal{A} * \mathcal{X} = \mathcal{B}\)</span>. The two products multiply along different modes. They are different equations that happen to use the same letters. Computing in higher precision will never turn one into the other.</p>
</section>
</section>
<section id="data" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="data"><span class="header-section-number">3</span> Data</h2>
<p>Four problems and four sources. Two are downloaded. One is a set of published material constants. One is simulated, because the real data needs a signed agreement.</p>
<section id="an-off-axis-carbonepoxy-ply" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="an-off-axis-carbonepoxy-ply"><span class="header-section-number">3.1</span> An off-axis carbon/epoxy ply</h3>
<ul>
<li><strong>What it is.</strong> Five elastic constants for a unidirectional T300/5208 carbon-fibre/epoxy ply at room temperature: <span class="math inline">\(E_1 = 181\)</span> GPa along the fibres, <span class="math inline">\(E_2 = 10.3\)</span> GPa across them, <span class="math inline">\(G_{12} = 7.17\)</span> GPa, <span class="math inline">\(\nu_{12} = 0.28\)</span>, <span class="math inline">\(\nu_{23} = 0.35\)</span>. These are typical published values for that material, written out in full so you can check the arithmetic below. Nothing here turns on the third significant figure.</li>
<li><strong>Who measures them and why.</strong> Materials labs pull, press and twist small test pieces cut from cured panels. Structural engineers use the results to predict how a part will bend before anyone builds it. The measurement exists to feed a stiffness model.</li>
<li><strong>What this post asks of them.</strong> Build the fourth-order stiffness tensor and rotate the ply <span class="math inline">\(30°\)</span> off the fibre axis. Then invert it to get compliance, so that a known stress returns the strain it caused.</li>
<li><strong>What being wrong costs.</strong> Compliance turns a load into a deflection. An error here means an aircraft panel or a pressure vessel is sized against the wrong strain. That is a part that breaks, not a plot that looks wrong.</li>
<li><strong>Why a tensor inverse.</strong> A <span class="math inline">\(3\times3\times3\times3\)</span> stiffness tensor really is a linear map. It takes a symmetric <span class="math inline">\(3\times3\)</span> matrix and returns a symmetric <span class="math inline">\(3\times3\)</span> matrix. This is exactly what the Einstein product describes. It is also the one problem here where flattening works, so it is a fair place to start.</li>
</ul>
</section>
<section id="pavia-university" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="pavia-university"><span class="header-section-number">3.2</span> Pavia University</h3>
<ul>
<li><strong>Provenance.</strong> A hyperspectral image of the University of Pavia campus in northern Italy, <span class="math inline">\(610\times340\)</span> pixels over 103 spectral bands at 1.3 m ground resolution. The ROSIS sensor recorded it from an aircraft. Prof.&nbsp;Paolo Gamba released it for research; he works at the Telecommunications and Remote Sensing Laboratory at the University of Pavia. Graña, Veganzones and Ayerdi at UPV/EHU then put it into the Hyperspectral Remote Sensing Scenes collection, which serves it today.</li>
<li><strong>Collector and motive.</strong> An aircraft flight, not a survey and not a web scrape. The team flew the scene and released it so that hyperspectral classification methods would share one benchmark. Hundreds of remote-sensing papers now use it.</li>
<li><strong>What this post uses.</strong> A <span class="math inline">\(128\times128\times103\)</span> crop. <code>src/fetch_data.py</code> writes it to <code>data/paviaU_crop.npz</code>, which is committed. The official host blocks scripted downloads, so the script takes the whole scene from an open mirror, cuts out the crop, and throws the rest away.</li>
<li><strong>What this post asks of it.</strong> Blur the cube with an operator that smears space <em>and</em> mixes neighbouring bands, then try to get it back two ways.</li>
<li><strong>What being wrong costs.</strong> Hyperspectral analysis identifies a material from the shape of a pixel’s spectrum. Suppose a method sharpens the picture but leaves the bands mixed. It then reports the wrong material, and reports it with confidence. A mineral survey, a crop-disease map or a pollution estimate would rest on a spectrum that belongs to no real material.</li>
<li><strong>Why a tensor inverse.</strong> The blur mixes the bands into each other. You therefore cannot treat each band as a separate problem. The t-product is built for this case: a third mode whose order means something, and slices that mix.</li>
</ul>
</section>
<section id="a-synthetic-four-dimensional-scan" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="a-synthetic-four-dimensional-scan"><span class="header-section-number">3.3</span> A synthetic four-dimensional scan</h3>
<ul>
<li><strong>It is synthetic, and this is how it is made.</strong> A <span class="math inline">\(16\times16\times16\times120\)</span> array. There are four regressors: a constant, two on-off task blocks with different periods, and a slow linear drift. Each regressor has its own Gaussian blob somewhere in space. The array is the design matrix times those blobs, plus independent Gaussian noise with <span class="math inline">\(\sigma = 0.4\)</span>. The random seed is 7.</li>
<li><strong>What it stands in for, and why it is simulated.</strong> A task-fMRI session of the kind in ADNI or the CMU StarPlus set. Those need an application and a signed agreement, so a render cannot download them. There is a better reason too. This section has to recover a map that it already knows, so that it can score the result. No real scan comes with the answer attached.</li>
<li><strong>What being wrong costs.</strong> A task map that puts activity in the wrong voxels becomes a published claim about which part of the brain does a job. The claim would be wrong.</li>
<li><strong>Why a mode-<span class="math inline">\(n\)</span> pseudoinverse.</strong> Time is one mode out of four, and the design matrix acts only on that mode. Regress along that mode, treating the three space modes as samples, and the whole solve is <span class="math inline">\(120\times4\)</span>. The alternative is written out below.</li>
</ul>
</section>
<section id="chicago-incident-counts" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="chicago-incident-counts"><span class="header-section-number">3.4</span> Chicago incident counts</h3>
<ul>
<li><strong>Provenance.</strong> The City of Chicago open data portal, “Crimes — 2001 to Present” (Socrata resource <code>ijzp-q8t2</code>), a public extract of the police department’s records-management system.</li>
<li><strong>Collector and motive.</strong> Officers of the Chicago Police Department enter each reported incident, and the city publishes the records under its open-data programme. These are <em>reports</em>, not offences. How often people report a crime varies by area and by offence type, and the portal says so.</li>
<li><strong>What this post uses.</strong> All of 2023, for community areas 1–24 and the eight most common offence types. The counts go into a <span class="math inline">\(52 \times 24 \times 8\)</span> array: week by area by offence type. The bins are 52 whole weeks. The one leftover day of the year is thrown away, so that the last bin is not longer than the others. <code>src/fetch_data.py</code> writes the array to <code>data/chicago_counts.npz</code>, which is committed, so a render never calls the API. The cell below prints the incident count.</li>
<li><strong>What this post asks of it.</strong> Estimate the covariance of the weekly array. A forecast needs that covariance before it can give any error bars.</li>
<li><strong>What being wrong costs.</strong> Cities use covariance estimates to plan patrols and staffing. A model that is confident about the wrong areas sends officers to the wrong areas.</li>
<li><strong>Why a structured inverse.</strong> Flattened, one week is a 192-dimensional vector, and there are only 52 weeks. The full covariance therefore cannot be inverted. A precision matrix that splits mode by mode can be fitted from the same data. As that section explains, splitting it is an assumption you are making, not an inverse you are taking.</li>
</ul>
</section>
</section>
<section id="compliance-the-einstein-product" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="compliance-the-einstein-product"><span class="header-section-number">4</span> Compliance: the Einstein product</h2>
<p><strong>Who does this.</strong> A mechanical engineer setting up a finite-element run on an anisotropic laminate.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-mech" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mech-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-mech">flowchart LR
  S["&lt;b&gt;σ&lt;/b&gt;&lt;br/&gt;stress, 3 × 3"] --&gt; C["&lt;b&gt;ℂ&lt;/b&gt;&lt;br/&gt;stiffness&lt;br/&gt;3 × 3 × 3 × 3"]
  C --&gt;|"invert under ⊛"| SS["&lt;b&gt;𝕊 = ℂ&lt;sup&gt;+&lt;/sup&gt;&lt;/b&gt;&lt;br/&gt;compliance"]
  SS --&gt; E["&lt;b&gt;ε = 𝕊 ⊛ σ&lt;/b&gt;&lt;br/&gt;strain, 3 × 3"]
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mech-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Stress in, strain out. The operator is a fourth-order stiffness tensor, and the inverse is taken under the Einstein product.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Hooke’s law in tensor form is <span class="math inline">\(\sigma_{ij} = \mathbb{C}_{ijkl}\varepsilon_{kl}\)</span>. Summing over the last two indices of <span class="math inline">\(\mathbb{C}\)</span> against a <span class="math inline">\(3\times3\)</span> matrix is the Einstein product.</p>
<p>So <span class="math inline">\(\mathbb{C}\)</span> takes a <span class="math inline">\(3\times3\)</span> matrix and returns a <span class="math inline">\(3\times3\)</span> matrix. Compliance is the operator that undoes it.</p>
<p>Build the ply, rotate it <span class="math inline">\(30°\)</span> off the fibre axis, and look at the operator as a <span class="math inline">\(9\times9\)</span> matrix.</p>
<div id="stiffness" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>C4 <span class="op">=</span> D.off_axis_stiffness(<span class="fl">30.0</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>flat <span class="op">=</span> C4.reshape(<span class="dv">9</span>, <span class="dv">9</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>sv <span class="op">=</span> np.linalg.svd(flat, compute_uv<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"stiffness tensor  </span><span class="sc">{</span>C4<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, as an operator </span><span class="sc">{</span>flat<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"singular values / largest:"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.array2string(sv <span class="op">/</span> sv.<span class="bu">max</span>(), precision<span class="op">=</span><span class="dv">6</span>, suppress_small<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"rank </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>matrix_rank(flat)<span class="sc">}</span><span class="ss"> of 9"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>stiffness tensor  (3, 3, 3, 3), as an operator (9, 9)
singular values / largest:
[1.000000e+00 8.611932e-02 7.803630e-02 7.803630e-02 4.151939e-02
 4.151939e-02 4.158847e-18 1.170415e-18 7.788320e-20]
rank 6 of 9</code></pre>
</div>
</div>
<p>Three of the nine singular values are zero, to machine precision. So the stiffness tensor is a <span class="math inline">\(9\times9\)</span> operator of rank 6, not rank 9. <strong>The Einstein-product inverse does not exist.</strong></p>
<div id="inverse-fails" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="cf">try</span>:</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    T.einstein_inv(C4, <span class="dv">2</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="cf">except</span> np.linalg.LinAlgError <span class="im">as</span> err:</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"einstein_inv: </span><span class="sc">{</span>err<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>einstein_inv: Singular matrix</code></pre>
</div>
</div>
<p>This is not a flaw in the material. It follows from the minor symmetries <span class="math inline">\(\mathbb{C}_{ijkl} = \mathbb{C}_{jikl} = \mathbb{C}_{ijlk}\)</span>. Those symmetries mean the operator ignores the antisymmetric part of its input, and never produces one.</p>
<p>The antisymmetric <span class="math inline">\(3\times3\)</span> matrices fill three dimensions. Those three are the null space. This makes physical sense: turning a rigid body does not stretch it.</p>
<p>The object that does exist is the <strong>multilinear Moore–Penrose inverse</strong>, which is row 4 of the table rather than row 3. It undoes the map on the six symmetric directions, and returns zero on the other three.</p>
<div id="compliance" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>S4 <span class="op">=</span> T.einstein_pinv(C4, <span class="dv">2</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>sigma <span class="op">=</span> D.applied_stress()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>eps <span class="op">=</span> T.einstein(S4, sigma, <span class="dv">2</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>back <span class="op">=</span> T.einstein(C4, eps, <span class="dv">2</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"applied stress (MPa)"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.array2string(sigma <span class="op">/</span> <span class="fl">1e6</span>, precision<span class="op">=</span><span class="dv">1</span>, suppress_small<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">recovered strain (x 1e-3)"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.array2string(eps <span class="op">*</span> <span class="fl">1e3</span>, precision<span class="op">=</span><span class="dv">4</span>, suppress_small<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">strain is symmetric: </span><span class="sc">{</span>np<span class="sc">.</span>allclose(eps, eps.T)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"round trip C(eps) vs sigma, relative error: </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(back <span class="op">-</span> sigma) <span class="op">/</span> np<span class="sc">.</span>linalg<span class="sc">.</span>norm(sigma)<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>applied stress (MPa)
[[120.  54.   0.]
 [ 54.  42.   0.]
 [  0.   0.   0.]]

recovered strain (x 1e-3)
[[ 1.303  -0.4146  0.    ]
 [-0.4146  0.6906 -0.    ]
 [ 0.     -0.     -0.7285]]

strain is symmetric: True
round trip C(eps) vs sigma, relative error: 2.04e-16</code></pre>
</div>
</div>
<p>The strain comes back symmetric, and the round trip closes to machine precision.</p>
<p>Notice the shear–extension coupling. A ply turned by <span class="math inline">\(30°\)</span> under mostly normal stress also picks up a negative shear strain. Engineers stack plies in balanced pairs so that these shear strains cancel.</p>
<section id="why-voigt-notation-is-a-flattening-that-works" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="why-voigt-notation-is-a-flattening-that-works"><span class="header-section-number">4.1</span> Why Voigt notation is a flattening that works</h3>
<p>Voigt notation stacks the six independent components of a symmetric <span class="math inline">\(3\times3\)</span> tensor into a vector of length 6. That turns <span class="math inline">\(\mathbb{C}\)</span> into a <span class="math inline">\(6\times6\)</span> matrix. It is a flattening, it is standard engineering practice, and here it is exactly right.</p>
<p>The rank count above explains why. The three directions that Voigt throws away are exactly the three in the null space. Flattening onto the symmetric directions loses nothing, because there was nothing there to lose.</p>
<div id="voigt" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>C6 <span class="op">=</span> D.tensor_to_voigt_stiffness(C4)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>S6 <span class="op">=</span> np.linalg.inv(C6)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>S4_from_voigt <span class="op">=</span> D.compliance_to_tensor(S6, reuter<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Voigt stiffness 6x6: rank </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>matrix_rank(C6)<span class="sc">}</span><span class="ss">, condition number </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>cond(C6)<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"max |S4_from_voigt - S4|: </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">abs</span>(S4_from_voigt <span class="op">-</span> S4)<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Voigt stiffness 6x6: rank 6, condition number 39.9
max |S4_from_voigt - S4|: 1.29e-25</code></pre>
</div>
</div>
<p>The Voigt matrix is well conditioned and full rank, and it matches the multilinear pseudoinverse to the last digit.</p>
<p>Flattening is not the problem. Flattening <em>along the wrong structure</em> is the problem.</p>
</section>
<section id="the-mistake-voigt-still-lets-you-make" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="the-mistake-voigt-still-lets-you-make"><span class="header-section-number">4.2</span> The mistake Voigt still lets you make</h3>
<p>Voigt compliance uses <strong>engineering</strong> shear strains, <span class="math inline">\(\gamma_{12} = 2\varepsilon_{12}\)</span>. The tensor uses <span class="math inline">\(\varepsilon_{12}\)</span> instead. So converting the inverted <span class="math inline">\(6\times6\)</span> back to a fourth-order tensor needs Reuter’s factors: divide by 2 for each shear index. Skip them and the shear terms come out 2 or 4 times too large.</p>
<div id="reuter" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>bad <span class="op">=</span> D.compliance_to_tensor(S6, reuter<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>eps_bad <span class="op">=</span> T.einstein(bad, sigma, <span class="dv">2</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>err_bad <span class="op">=</span> np.linalg.norm(T.einstein(C4, eps_bad, <span class="dv">2</span>) <span class="op">-</span> sigma) <span class="op">/</span> np.linalg.norm(sigma)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"strain without Reuter factors (x 1e-3)"</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.array2string(eps_bad <span class="op">*</span> <span class="fl">1e3</span>, precision<span class="op">=</span><span class="dv">4</span>, suppress_small<span class="op">=</span><span class="va">True</span>))</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">shear  ratio to correct: </span><span class="sc">{</span>eps_bad[<span class="dv">0</span>, <span class="dv">1</span>] <span class="op">/</span> eps[<span class="dv">0</span>, <span class="dv">1</span>]<span class="sc">:+.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"normal ratio to correct: </span><span class="sc">{</span>eps_bad[<span class="dv">0</span>, <span class="dv">0</span>] <span class="op">/</span> eps[<span class="dv">0</span>, <span class="dv">0</span>]<span class="sc">:+.2f}</span><span class="ss">"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"round-trip relative error: </span><span class="sc">{</span>err_bad<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>strain without Reuter factors (x 1e-3)
[[-1.2328  5.3348  0.    ]
 [ 5.3348 -1.0556  0.    ]
 [ 0.      0.      0.7883]]

shear  ratio to correct: -12.87
normal ratio to correct: -0.95
round-trip relative error: 3.16</code></pre>
</div>
</div>
<p>When the ply is turned off-axis, the error is not limited to shear. Turning the ply puts shear–extension terms into the compliance. If their scale is wrong, the error spreads through the whole solve. The normal strains then flip sign, and the round trip is wrong by more than 300%.</p>
<p>On the fibre axis those coupling terms are zero. The same mistake then makes the shear exactly 4 times too large, and leaves everything else correct.</p>
<div id="reuter-on-axis" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>C4_0 <span class="op">=</span> D.off_axis_stiffness(<span class="fl">0.0</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>eps_0 <span class="op">=</span> T.einstein(T.einstein_pinv(C4_0, <span class="dv">2</span>), sigma, <span class="dv">2</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>S6_0 <span class="op">=</span> np.linalg.inv(D.tensor_to_voigt_stiffness(C4_0))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>bad_0 <span class="op">=</span> T.einstein(D.compliance_to_tensor(S6_0, reuter<span class="op">=</span><span class="va">False</span>), sigma, <span class="dv">2</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"on-axis shear  ratio: </span><span class="sc">{</span>bad_0[<span class="dv">0</span>, <span class="dv">1</span>] <span class="op">/</span> eps_0[<span class="dv">0</span>, <span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"on-axis normal ratio: </span><span class="sc">{</span>bad_0[<span class="dv">0</span>, <span class="dv">0</span>] <span class="op">/</span> eps_0[<span class="dv">0</span>, <span class="dv">0</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>on-axis shear  ratio: 4.000
on-axis normal ratio: 1.000</code></pre>
</div>
</div>
<p>The pseudoinverse cannot make this mistake, because it never leaves the tensor. So there is a trade. Flattening gives you a smaller, better-behaved object. In exchange, you must apply a conversion rule by hand, and apply it correctly.</p>
</section>
</section>
<section id="hyperspectral-restoration-the-t-product" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="hyperspectral-restoration-the-t-product"><span class="header-section-number">5</span> Hyperspectral restoration: the t-product</h2>
<p><strong>Who does this.</strong> A remote-sensing analyst deblurring a data cube before classifying it.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-hsi-flow" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hsi-flow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-hsi-flow">flowchart LR
  X["&lt;b&gt;𝒳&lt;/b&gt;&lt;br/&gt;clean cube&lt;br/&gt;128 × 128 × 103"] --&gt; A["&lt;b&gt;𝒜&lt;/b&gt;&lt;br/&gt;blur operator&lt;br/&gt;smear + band leak"]
  A --&gt; B["&lt;b&gt;ℬ = 𝒜 * 𝒳&lt;/b&gt;&lt;br/&gt;observed"]
  B --&gt; F["band-by-band&lt;br/&gt;invert slice 0 only"]
  B --&gt; TP["t-solve&lt;br/&gt;all 103 Fourier slices"]
  F --&gt; R1["spatially sharp,&lt;br/&gt;spectrally still mixed"]
  TP --&gt; R2["&lt;b&gt;𝒳̂&lt;/b&gt;"]
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hsi-flow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: One t-solve against 103 separate 2D deblurring problems. The flattening keeps only the first frontal slice, and the band mixing lives in the ones it drops.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The blur has two parts. The optics smear each band across space. The sensor also leaks signal between neighbouring wavelengths.</p>
<p>Under the t-product both parts fit into one operator <span class="math inline">\(\mathcal{A}\)</span>. Frontal slice 0 holds the spatial smear, and slices <span class="math inline">\(\pm 1\)</span> hold the leak.</p>
<div id="hsi-setup" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>cube, meta <span class="op">=</span> D.pavia_crop()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>n, bands <span class="op">=</span> cube.shape[<span class="dv">0</span>], cube.shape[<span class="dv">2</span>]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>LEAK <span class="op">=</span> <span class="fl">0.12</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> D.blur_operator(n, bands, width<span class="op">=</span><span class="fl">1.4</span>, leak<span class="op">=</span>LEAK)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(T.SEED)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>observed <span class="op">=</span> T.tprod(A, cube)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>observed <span class="op">=</span> observed <span class="op">+</span> rng.normal(<span class="dv">0</span>, <span class="fl">1e-3</span> <span class="op">*</span> observed.std(), observed.shape)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"crop </span><span class="sc">{</span>cube<span class="sc">.</span>shape<span class="sc">}</span><span class="ss"> from the </span><span class="sc">{</span><span class="bu">tuple</span>(meta[<span class="st">'full_shape'</span>])<span class="sc">}</span><span class="ss"> scene at origin </span><span class="sc">{</span>meta[<span class="st">'origin'</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"operator </span><span class="sc">{</span>A<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">: spatial smear in slice 0, </span><span class="sc">{</span>LEAK<span class="sc">:.0%}</span><span class="ss"> band leak in slices 1 and -1"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"operator as a tensor:            </span><span class="sc">{</span>A<span class="sc">.</span>nbytes <span class="op">/</span> <span class="fl">1e6</span><span class="sc">:6.1f}</span><span class="ss"> MB"</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"same operator flattened to a matrix:      </span><span class="sc">{</span>(n <span class="op">*</span> bands) <span class="op">**</span> <span class="dv">2</span> <span class="op">*</span> <span class="dv">8</span> <span class="op">/</span> <span class="fl">1e9</span><span class="sc">:6.1f}</span><span class="ss"> GB"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>crop (128, 128, 103) from the (610, 340, 103) scene at origin [150, 100]
operator (128, 128, 103): spatial smear in slice 0, 12% band leak in slices 1 and -1
operator as a tensor:              13.5 MB
same operator flattened to a matrix:         1.4 GB</code></pre>
</div>
</div>
<p>Two methods are compared below. <strong>Band-by-band</strong> deblurs each of the 103 bands on its own, which is the flattening. <strong>t-solve</strong> solves the whole cube at once in the t-product.</p>
<p>Undoing a blur is unstable. A small amount of noise in the input becomes a large amount of noise in the answer.</p>
<p>Both methods therefore get the same Tikhonov damping, and each one picks the <span class="math inline">\(\lambda\)</span> that suits it best. This is generous to the flattening. It also leaves the band mixing as the only real difference between the two methods.</p>
<div id="hsi-solve" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> relative(x):</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.linalg.norm(x <span class="op">-</span> cube) <span class="op">/</span> np.linalg.norm(cube)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>lambdas <span class="op">=</span> np.logspace(<span class="op">-</span><span class="dv">6</span>, <span class="dv">1</span>, <span class="dv">15</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>results <span class="op">=</span> {}</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, solver <span class="kw">in</span> (</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"band-by-band"</span>, T.band_by_band_solve),</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"t-solve"</span>, T.treg_solve),</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>    err, lam <span class="op">=</span> <span class="bu">min</span>((relative(solver(A, observed, l)), l) <span class="cf">for</span> l <span class="kw">in</span> lambdas)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>    start <span class="op">=</span> time.perf_counter()</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>    recovered <span class="op">=</span> solver(A, observed, lam)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>    results[name] <span class="op">=</span> {</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>        <span class="st">"cube"</span>: recovered,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>        <span class="st">"lam"</span>: lam,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>        <span class="st">"rel"</span>: err,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>        <span class="st">"sam"</span>: <span class="bu">float</span>(D.spectral_angle(cube, recovered).mean()),</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>        <span class="st">"secs"</span>: time.perf_counter() <span class="op">-</span> start,</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>header <span class="op">=</span> <span class="ss">f"</span><span class="sc">{</span><span class="st">''</span><span class="sc">:&lt;13}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'lambda'</span><span class="sc">:&gt;8}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'rel error'</span><span class="sc">:&gt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'mean SAM'</span><span class="sc">:&gt;9}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'seconds'</span><span class="sc">:&gt;8}</span><span class="ss">"</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(header)</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"-"</span> <span class="op">*</span> <span class="bu">len</span>(header))</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'observed'</span><span class="sc">:&lt;13}</span><span class="ss"> </span><span class="sc">{</span><span class="st">''</span><span class="sc">:&gt;8}</span><span class="ss"> </span><span class="sc">{</span>relative(observed)<span class="sc">:10.4f}</span><span class="ss"> "</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>D<span class="sc">.</span>spectral_angle(cube, observed)<span class="sc">.</span>mean()<span class="sc">:8.2f}</span><span class="ss">° </span><span class="sc">{</span><span class="st">''</span><span class="sc">:&gt;8}</span><span class="ss">"</span>)</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, r <span class="kw">in</span> results.items():</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&lt;13}</span><span class="ss"> </span><span class="sc">{</span>r[<span class="st">'lam'</span>]<span class="sc">:8.0e}</span><span class="ss"> </span><span class="sc">{</span>r[<span class="st">'rel'</span>]<span class="sc">:10.4f}</span><span class="ss"> </span><span class="sc">{</span>r[<span class="st">'sam'</span>]<span class="sc">:8.2f}</span><span class="ss">° </span><span class="sc">{</span>r[<span class="st">'secs'</span>]<span class="sc">:8.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                lambda  rel error  mean SAM  seconds
----------------------------------------------------
observed                   0.2444     3.26°         
band-by-band     3e-01     0.1247     3.12°     0.06
t-solve          1e-04     0.0376     1.79°     0.14</code></pre>
</div>
</div>
<p>Band-by-band deblurring halves the relative error and then stops improving. Its best <span class="math inline">\(\lambda\)</span> sits at the smoothest end of the grid. A method chooses heavy smoothing when it cannot fix the real problem. Here the real problem is the band mixing, which this method threw away.</p>
<p>The t-solve gets about three times closer. The spectral angle also drops by 40%. Spectral angle is the measure that decides which material a pixel contains, so that is the number that matters.</p>
<div id="cell-fig-hsi-restore" class="cell" data-fig-height="6.4" data-fig-width="11" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> rgb(c):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    im <span class="op">=</span> np.stack([c[:, :, <span class="dv">46</span>], c[:, :, <span class="dv">27</span>], c[:, :, <span class="dv">10</span>]], axis<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    lo, hi <span class="op">=</span> np.percentile(im, [<span class="dv">1</span>, <span class="dv">99</span>])</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.clip((im <span class="op">-</span> lo) <span class="op">/</span> (hi <span class="op">-</span> lo), <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>recovered <span class="op">=</span> {k: results[k][<span class="st">"cube"</span>] <span class="cf">for</span> k <span class="kw">in</span> results}</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>sam <span class="op">=</span> {</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>    name: D.spectral_angle(cube, data).reshape(n, n)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name, data <span class="kw">in</span> [(<span class="st">"observed"</span>, observed), <span class="op">*</span>recovered.items()]</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Mark a pixel where the two methods actually disagree, rather than an</span></span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a><span class="co"># arbitrary one: the 97th percentile of the band-by-band minus t-solve gap,</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a><span class="co"># taken away from the border so the marker is not clipped.</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>gap <span class="op">=</span> sam[<span class="st">"band-by-band"</span>] <span class="op">-</span> sam[<span class="st">"t-solve"</span>]</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>interior <span class="op">=</span> np.zeros_like(gap, dtype<span class="op">=</span><span class="bu">bool</span>)</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>interior[<span class="dv">8</span>:<span class="op">-</span><span class="dv">8</span>, <span class="dv">8</span>:<span class="op">-</span><span class="dv">8</span>] <span class="op">=</span> <span class="va">True</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a><span class="co"># argsort puts the masked-out border pixels first, so index from the top.</span></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>ranked <span class="op">=</span> np.argsort(np.where(interior, gap, <span class="op">-</span>np.inf).ravel())</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>px, py <span class="op">=</span> np.unravel_index(ranked[<span class="op">-</span><span class="dv">1</span> <span class="op">-</span> <span class="bu">int</span>(<span class="fl">0.03</span> <span class="op">*</span> interior.<span class="bu">sum</span>())], (n, n))</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">6.0</span>), height_ratios<span class="op">=</span>[<span class="fl">1.35</span>, <span class="dv">1</span>])</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>fig.subplots_adjust(hspace<span class="op">=</span><span class="fl">0.28</span>)</span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, (name, data) <span class="kw">in</span> <span class="bu">zip</span>(</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>], [(<span class="st">"clean"</span>, cube), (<span class="st">"observed"</span>, observed), <span class="op">*</span>recovered.items()]</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>    ax.imshow(rgb(data))</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>    title <span class="op">=</span> name <span class="cf">if</span> name <span class="op">==</span> <span class="st">"clean"</span> <span class="cf">else</span> <span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ch">\n</span><span class="ss">relative error </span><span class="sc">{</span>relative(data)<span class="sc">:.3f}</span><span class="ss">"</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title)</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>    ax.plot(py, px, <span class="st">"o"</span>, mfc<span class="op">=</span><span class="st">"none"</span>, mec<span class="op">=</span>GOLD, mew<span class="op">=</span><span class="fl">1.8</span>, ms<span class="op">=</span><span class="dv">13</span>)</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks([])</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>    ax.set_yticks([])</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>spec <span class="op">=</span> axes[<span class="dv">1</span>][<span class="dv">0</span>]</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>spec.plot(cube[px, py, :], color<span class="op">=</span>INK, lw<span class="op">=</span><span class="fl">2.0</span>, label<span class="op">=</span><span class="st">"clean"</span>, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>spec.plot(observed[px, py, :], color<span class="op">=</span>GOLD, lw<span class="op">=</span><span class="fl">1.2</span>, label<span class="op">=</span><span class="st">"observed"</span>)</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>spec.plot(recovered[<span class="st">"band-by-band"</span>][px, py, :], color<span class="op">=</span>CORAL, lw<span class="op">=</span><span class="fl">1.3</span>, label<span class="op">=</span><span class="st">"band-by-band"</span>)</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>spec.plot(recovered[<span class="st">"t-solve"</span>][px, py, :], color<span class="op">=</span>TEAL, lw<span class="op">=</span><span class="fl">1.3</span>, label<span class="op">=</span><span class="st">"t-solve"</span>)</span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>spec.set_title(<span class="ss">f"spectrum at the marked pixel (</span><span class="sc">{</span>px<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>py<span class="sc">}</span><span class="ss">)"</span>)</span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>spec.set_xlabel(<span class="st">"band"</span>)</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>spec.set_ylabel(<span class="st">"reflectance"</span>)</span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>spec.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a>vmax <span class="op">=</span> <span class="bu">float</span>(np.percentile(sam[<span class="st">"observed"</span>], <span class="dv">99</span>))</span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, name <span class="kw">in</span> <span class="bu">zip</span>(axes[<span class="dv">1</span>][<span class="dv">1</span>:], [<span class="st">"observed"</span>, <span class="st">"band-by-band"</span>, <span class="st">"t-solve"</span>]):</span>
<span id="cb17-47"><a href="#cb17-47" aria-hidden="true" tabindex="-1"></a>    im <span class="op">=</span> ax.imshow(sam[name], cmap<span class="op">=</span><span class="st">"inferno"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span>vmax)</span>
<span id="cb17-48"><a href="#cb17-48" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ch">\n</span><span class="ss">mean SAM </span><span class="sc">{</span>sam[name]<span class="sc">.</span>mean()<span class="sc">:.2f}</span><span class="ss">°"</span>)</span>
<span id="cb17-49"><a href="#cb17-49" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks([])</span>
<span id="cb17-50"><a href="#cb17-50" aria-hidden="true" tabindex="-1"></a>    ax.set_yticks([])</span>
<span id="cb17-51"><a href="#cb17-51" aria-hidden="true" tabindex="-1"></a>fig.colorbar(im, ax<span class="op">=</span>axes[<span class="dv">1</span>][<span class="dv">1</span>:], shrink<span class="op">=</span><span class="fl">0.85</span>, label<span class="op">=</span><span class="st">"spectral angle (deg)"</span>)</span>
<span id="cb17-52"><a href="#cb17-52" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-hsi-restore" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hsi-restore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hsi-restore-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hsi-restore-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Pavia University, a 128×128 crop. Top: an RGB view built from bands 46, 27 and 10. Bottom left: the spectrum at one marked pixel. Bottom right: the spectral angle at every pixel against the clean cube, all three on one scale. Band-by-band deblurring sharpens the picture but leaves the spectral-angle errors almost as large as in the blurred input. The t-solve reduces them.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The spectra show this most clearly. The band-by-band curve keeps the shape of the clean curve, but it does not sit on top of it. It runs above the truth over some bands and below over others. Every band still carries 12% of each neighbour. The t-solve curve lies on the truth.</p>
<p>The spectral-angle maps show the same result across the whole scene. In the band-by-band map the errors are almost as large as in the blurred input. The largest errors sit on roofs and edges. Neighbouring bands differ most there, so the leak does most damage there. In the t-solve map the errors drop everywhere.</p>
<p>Look at the memory line above as well. The same operator takes 13.5 MB as a tensor and 1.4 GB after flattening into a matrix. So the t-product does more than give a better answer. On the full scene it is the only one of the two that fits in memory.</p>
</section>
<section id="the-t-inverse-stage-by-stage" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="the-t-inverse-stage-by-stage"><span class="header-section-number">6</span> The t-inverse, stage by stage</h2>
<p>The t-inverse takes four steps, and each step can be drawn. The widget below goes through them on a small <span class="math inline">\(8\times8\times6\)</span> tensor, built from the same random seed as the rest of the post.</p>
<div class="widget-container">
<div class="widget-header">
<p><span class="widget-title">The t-inverse in four stages</span> <span class="widget-badge">runs in the browser</span></p>
</div>
<div id="ti-widget">

</div>
<div class="widget-note">
Stage 2 is the important one. After the FFT along mode 3 the six slices become independent of each other, so one tensor inverse turns into six separate matrix inverses. Next, drag <b>Conditioning</b> to the right. Slice 2 and its conjugate partner slice 4 become singular together. The largest entry of the inverse climbs past 1e11, and the solve error rises to 2.6e6. One bad slice ruins the whole tensor. Now switch the solver to <b>pinv</b>. The pseudoinverse drops the bad direction. The identity check then fails, because A·A<sup>+</sup> sends that direction to zero instead of leaving it alone — but the solve error falls back to 0.09. That is the trade, and the two numbers disagree for a reason.
</div>
</div>
<p>The numbers in that note come from the same function that produced the widget’s data, so you can check them here:</p>
<div id="tinv-stages" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> level <span class="kw">in</span> (<span class="fl">0.0</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>):</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    row <span class="op">=</span> []</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> solver <span class="kw">in</span> (<span class="st">"inv"</span>, <span class="st">"pinv"</span>):</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>        s <span class="op">=</span> T.widget_state(level, solver)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>        row.append((solver, s[<span class="st">"residual"</span>], s[<span class="st">"max_abs"</span>], s[<span class="st">"solve_error"</span>]))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    kappa <span class="op">=</span> T.widget_state(level, <span class="st">"inv"</span>)[<span class="st">"conds"</span>][<span class="dv">2</span>]</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"conditioning </span><span class="sc">{</span>level<span class="sc">:.1f}</span><span class="ss">   kappa(slice 2) = </span><span class="sc">{</span>kappa<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> solver, res, mx, solve <span class="kw">in</span> row:</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"    </span><span class="sc">{</span>solver<span class="sc">:&gt;4}</span><span class="ss">  identity residual </span><span class="sc">{</span>res<span class="sc">:8.2e}</span><span class="ss">   max|X| </span><span class="sc">{</span>mx<span class="sc">:8.2e}</span><span class="ss">   solve error </span><span class="sc">{</span>solve<span class="sc">:8.2e}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>conditioning 0.0   kappa(slice 2) = 6.93e+00
     inv  identity residual 5.26e-16   max|X| 5.67e-01   solve error 1.21e-05
    pinv  identity residual 1.33e-15   max|X| 5.67e-01   solve error 1.21e-05
conditioning 0.5   kappa(slice 2) = 6.93e+06
     inv  identity residual 2.01e-10   max|X| 1.67e+05   solve error 2.57e+00
    pinv  identity residual 2.99e-10   max|X| 1.67e+05   solve error 2.57e+00
conditioning 1.0   kappa(slice 2) = 6.92e+12
     inv  identity residual 1.97e-04   max|X| 1.68e+11   solve error 2.57e+06
    pinv  identity residual 2.04e-01   max|X| 5.51e-01   solve error 9.47e-02</code></pre>
</div>
</div>
<p>Two points.</p>
<p>First, the identity residual and the solve error disagree once the pseudoinverse starts dropping directions. The solve error is the one to read, because it measures the answer you actually wanted.</p>
<p>Second, slices 2 and 4 are a conjugate pair. In a tensor with real entries, one of them cannot become ill-conditioned on its own.</p>
</section>
<section id="task-maps-the-mode-n-pseudoinverse" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="task-maps-the-mode-n-pseudoinverse"><span class="header-section-number">7</span> Task maps: the mode-<span class="math inline">\(n\)</span> pseudoinverse</h2>
<p><strong>Who does this.</strong> A computational neuroscientist mapping a four-dimensional scan onto a task design.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-scan-flow" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scan-flow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-scan-flow">flowchart LR
  Y["&lt;b&gt;𝒴&lt;/b&gt;&lt;br/&gt;scan&lt;br/&gt;16 × 16 × 16 × 120"] --&gt; U["flatten on mode 4&lt;br/&gt;120 × 4096"]
  X["&lt;b&gt;X&lt;/b&gt;&lt;br/&gt;design&lt;br/&gt;120 × 4"] --&gt; P["&lt;b&gt;X&lt;sup&gt;†&lt;/sup&gt;&lt;/b&gt;&lt;br/&gt;mode-n pseudoinverse"]
  U --&gt; M["&lt;b&gt;B = X&lt;sup&gt;†&lt;/sup&gt; 𝒴&lt;sub&gt;(4)&lt;/sub&gt;&lt;/b&gt;"]
  P --&gt; M
  M --&gt; R["coefficient maps&lt;br/&gt;4 × 4096"]
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scan-flow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Regression along one mode. Time is mode 4, and the three space modes become columns, so the solve is the size of the design rather than the size of the scan.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Readers misread this row of the table more often than any other. The mode-<span class="math inline">\(n\)</span> pseudoinverse inverts the <em>design matrix, on one mode</em>. It does not invert the scan. In fact no tensor is inverted here at all.</p>
<div id="scan" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>scan, design, beta_true <span class="op">=</span> D.synthetic_scan()</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> time.perf_counter()</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>beta_hat <span class="op">=</span> T.mode_pinv_solve(scan, design, <span class="dv">3</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>mode_secs <span class="op">=</span> time.perf_counter() <span class="op">-</span> start</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>truth <span class="op">=</span> beta_true.reshape(design.shape[<span class="dv">1</span>], <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"scan </span><span class="sc">{</span>scan<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, design </span><span class="sc">{</span>design<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, solve took </span><span class="sc">{</span>mode_secs <span class="op">*</span> <span class="fl">1e3</span><span class="sc">:.1f}</span><span class="ss"> ms"</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>names <span class="op">=</span> [<span class="st">"intercept"</span>, <span class="st">"task A"</span>, <span class="st">"task B"</span>, <span class="st">"drift"</span>]</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p, name <span class="kw">in</span> <span class="bu">enumerate</span>(names[<span class="dv">1</span>:], start<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>    corr <span class="op">=</span> np.corrcoef(beta_hat[p], truth[p])[<span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>name<span class="sc">:&lt;10}</span><span class="ss"> correlation with truth </span><span class="sc">{</span>corr<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  overall relative error </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(beta_hat <span class="op">-</span> truth) <span class="op">/</span> np<span class="sc">.</span>linalg<span class="sc">.</span>norm(truth)<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>scan (16, 16, 16, 120), design (120, 4), solve took 0.3 ms
  task A     correlation with truth 0.960
  task B     correlation with truth 0.903
  drift      correlation with truth 0.657
  overall relative error 0.230</code></pre>
</div>
</div>
<p>The two task maps come back with correlation 0.96 and 0.90 against the truth. The drift map is weaker, which is what you would expect. Over 120 frames, a slow ramp looks much like noise.</p>
<p>Now count the parameters. The mode-<span class="math inline">\(n\)</span> method solves one <span class="math inline">\(120\times4\)</span> system, then reuses that solution across all 4,096 voxels.</p>
<div id="scan-counts" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>voxels, frames, params <span class="op">=</span> <span class="dv">16</span><span class="op">**</span><span class="dv">3</span>, design.shape[<span class="dv">0</span>], design.shape[<span class="dv">1</span>]</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>vec_rows, vec_cols <span class="op">=</span> voxels <span class="op">*</span> frames, voxels <span class="op">*</span> params</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mode-n:  solve is </span><span class="sc">{</span>frames<span class="sc">}</span><span class="ss"> x </span><span class="sc">{</span>params<span class="sc">}</span><span class="ss">, estimates </span><span class="sc">{</span>params <span class="op">*</span> voxels<span class="sc">:,}</span><span class="ss"> coefficients"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"flattened GLM design matrix: </span><span class="sc">{</span>vec_rows<span class="sc">:,}</span><span class="ss"> x </span><span class="sc">{</span>vec_cols<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  = </span><span class="sc">{</span>vec_rows <span class="op">*</span> vec_cols<span class="sc">:.2e}</span><span class="ss"> entries = </span><span class="sc">{</span>vec_rows <span class="op">*</span> vec_cols <span class="op">*</span> <span class="dv">8</span> <span class="op">/</span> <span class="fl">1e9</span><span class="sc">:.1f}</span><span class="ss"> GB"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>mode-n:  solve is 120 x 4, estimates 16,384 coefficients
flattened GLM design matrix: 491,520 x 16,384
  = 8.05e+09 entries = 64.4 GB</code></pre>
</div>
</div>
<p>The estimates are identical, and the design matrix is 64 GB. That matrix is the same <span class="math inline">\(120\times4\)</span> block repeated 4,096 times along a diagonal. The mode-<span class="math inline">\(n\)</span> pseudoinverse is what you get once you notice the repetition and stop writing the copies down.</p>
<div id="cell-fig-scan" class="cell" data-fig-height="4.4" data-fig-width="10" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>maps <span class="op">=</span> beta_hat.reshape(beta_true.shape)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">4.4</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>slices <span class="op">=</span> [(<span class="dv">1</span>, <span class="dv">8</span>), (<span class="dv">2</span>, <span class="dv">7</span>), (<span class="dv">3</span>, <span class="dv">8</span>)]</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col, (p, z) <span class="kw">in</span> <span class="bu">enumerate</span>(slices):</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>    vmax <span class="op">=</span> <span class="bu">float</span>(np.<span class="bu">abs</span>(beta_true[p]).<span class="bu">max</span>())</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>, col].imshow(beta_true[p][:, :, z], cmap<span class="op">=</span><span class="st">"magma"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span>vmax)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>, col].imshow(maps[p][:, :, z], cmap<span class="op">=</span><span class="st">"magma"</span>, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span>vmax)</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    corr <span class="op">=</span> np.corrcoef(beta_hat[p], truth[p])[<span class="dv">0</span>, <span class="dv">1</span>]</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>, col].set_title(<span class="ss">f"</span><span class="sc">{</span>names[p]<span class="sc">}</span><span class="ss"> — truth"</span>)</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>, col].set_title(<span class="ss">f"recovered, r = </span><span class="sc">{</span>corr<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> axes.ravel():</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks([])</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    ax.set_yticks([])</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-scan" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-scan-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Recovered coefficient maps against the truth, one slice through each blob. The two task maps come back cleanly. The drift map does not, because its regressor is a slow ramp that noise can imitate.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="urban-demand-a-separable-precision" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="urban-demand-a-separable-precision"><span class="header-section-number">8</span> Urban demand: a separable precision</h2>
<p><strong>Who does this.</strong> An urban data scientist putting an interval on a forecast over a week <span class="math inline">\(\times\)</span> area <span class="math inline">\(\times\)</span> offence-type array.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-demand-flow" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-demand-flow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-demand-flow">flowchart LR
  Y["&lt;b&gt;𝒴&lt;/b&gt;&lt;br/&gt;52 × 24 × 8&lt;br/&gt;weekly counts"] --&gt; F["flatten to 192-vectors"]
  Y --&gt; S["keep the modes"]
  F --&gt; DC["dense Σ&lt;br/&gt;192 × 192&lt;br/&gt;rank 39 of 192"]
  S --&gt; K["Σ&lt;sub&gt;area&lt;/sub&gt; ⊗ Σ&lt;sub&gt;type&lt;/sub&gt;&lt;br/&gt;flip-flop MLE"]
  DC --&gt; R1["singular — needs a ridge"]
  K --&gt; R2["336 free parameters"]
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-demand-flow-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: One dense covariance over the flattened array, or one covariance per mode. Forty weeks are enough to fit the second. They are not enough to fit the first.
</figcaption>
</figure>
</div>
</div>
</div>
<p>This is the one row of the table that is not an algebraic tensor inverse. Assuming that the covariance splits as <span class="math inline">\(\Sigma_{\text{area}} \otimes \Sigma_{\text{type}}\)</span> is a claim you make about the world. The array does not tell you it is true.</p>
<p>It appears here for two reasons. People often call it “the tensor inverse” of a covariance, and it is not one. And on this data it does not pay off.</p>
<div id="demand-setup" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>counts, cmeta <span class="op">=</span> D.chicago_counts()</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> np.sqrt(counts.astype(<span class="bu">float</span>))  <span class="co"># variance-stabilise Poisson-like counts</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>train, test <span class="op">=</span> Y[:<span class="dv">40</span>], Y[<span class="dv">40</span>:]</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>centre <span class="op">=</span> train.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>Ztr, Zte <span class="op">=</span> train <span class="op">-</span> centre, test <span class="op">-</span> centre</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>dim <span class="op">=</span> Ztr[<span class="dv">0</span>].size</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>cmeta[<span class="st">'n_incidents'</span>]<span class="sc">:,}</span><span class="ss"> incidents, </span><span class="sc">{</span>cmeta[<span class="st">'year'</span>]<span class="sc">}</span><span class="ss">, community areas 1-</span><span class="sc">{</span><span class="bu">max</span>(cmeta[<span class="st">'areas'</span>])<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"array </span><span class="sc">{</span>counts<span class="sc">.</span>shape<span class="sc">}</span><span class="ss"> -&gt; </span><span class="sc">{</span><span class="bu">len</span>(train)<span class="sc">}</span><span class="ss"> training weeks, </span><span class="sc">{</span><span class="bu">len</span>(test)<span class="sc">}</span><span class="ss"> held out"</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"one week flattened is a </span><span class="sc">{</span>dim<span class="sc">}</span><span class="ss">-vector; the dense sample covariance has rank "</span></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>matrix_rank(Ztr.reshape(<span class="bu">len</span>(Ztr), <span class="op">-</span><span class="dv">1</span>).T <span class="op">@</span> Ztr.reshape(<span class="bu">len</span>(Ztr), <span class="op">-</span><span class="dv">1</span>))<span class="sc">}</span><span class="ss"> of </span><span class="sc">{</span>dim<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>70,182 incidents, 2023, community areas 1-24
array (52, 24, 8) -&gt; 40 training weeks, 12 held out
one week flattened is a 192-vector; the dense sample covariance has rank 39 of 192</code></pre>
</div>
</div>
<p>Forty readings of a 192-dimensional vector cannot give a full-rank covariance. This is not bad luck with a small sample. It is arithmetic: 40 numbers cannot pin down 18,528.</p>
<p>The separable model fits one covariance per mode, using Dutilleul’s flip-flop algorithm. Whiten every other mode, take the sample covariance of the mode you are updating, then repeat until it settles.</p>
<div id="demand-fit" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>covs <span class="op">=</span> D.flip_flop(Ztr, iters<span class="op">=</span><span class="dv">60</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>logdet <span class="op">=</span> D.separable_logdet(covs)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>quad <span class="op">=</span> D.separable_quadform(Zte, covs)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>sep_ll <span class="op">=</span> <span class="bu">float</span>(np.mean(<span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> (dim <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi) <span class="op">+</span> logdet <span class="op">+</span> quad)))</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>sep_params <span class="op">=</span> <span class="bu">sum</span>(c.shape[<span class="dv">0</span>] <span class="op">*</span> (c.shape[<span class="dv">0</span>] <span class="op">+</span> <span class="dv">1</span>) <span class="op">//</span> <span class="dv">2</span> <span class="cf">for</span> c <span class="kw">in</span> covs)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>Xtr, Xte <span class="op">=</span> Ztr.reshape(<span class="bu">len</span>(Ztr), <span class="op">-</span><span class="dv">1</span>), Zte.reshape(<span class="bu">len</span>(Zte), <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>S <span class="op">=</span> Xtr.T <span class="op">@</span> Xtr <span class="op">/</span> <span class="bu">len</span>(Xtr)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>best_ll, best_ridge <span class="op">=</span> <span class="op">-</span>np.inf, <span class="va">None</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r <span class="kw">in</span> np.logspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">2</span>, <span class="dv">25</span>):</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    Sr <span class="op">=</span> S <span class="op">+</span> r <span class="op">*</span> np.trace(S) <span class="op">/</span> dim <span class="op">*</span> np.eye(dim)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    _, ld <span class="op">=</span> np.linalg.slogdet(Sr)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> np.einsum(<span class="st">"nd,de,ne-&gt;n"</span>, Xte, np.linalg.inv(Sr), Xte)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    ll <span class="op">=</span> <span class="bu">float</span>(np.mean(<span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> (dim <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi) <span class="op">+</span> ld <span class="op">+</span> q)))</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> ll <span class="op">&gt;</span> best_ll:</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>        best_ll, best_ridge <span class="op">=</span> ll, r</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Where does the gain come from? Keep the mode variances, drop the mode</span></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="co"># correlations; then drop the variances too.</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> sep_loglik(cs):</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>    q <span class="op">=</span> D.separable_quadform(Zte, cs)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.mean(<span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> (dim <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi) <span class="op">+</span> D.separable_logdet(cs) <span class="op">+</span> q)))</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>diag_ll <span class="op">=</span> sep_loglik([np.diag(np.diag(c)) <span class="cf">for</span> c <span class="kw">in</span> covs])</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>iso <span class="op">=</span> [np.eye(d) <span class="cf">for</span> d <span class="kw">in</span> Ztr.shape[<span class="dv">1</span>:]]</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a>iso[<span class="dv">0</span>] <span class="op">=</span> np.eye(Ztr.shape[<span class="dv">1</span>]) <span class="op">*</span> (Ztr<span class="op">**</span><span class="dv">2</span>).mean()</span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>iso_ll <span class="op">=</span> sep_loglik(iso)</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-30"><a href="#cb27-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'model'</span><span class="sc">:&lt;32}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'held-out log-lik'</span><span class="sc">:&gt;17}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'free params'</span><span class="sc">:&gt;12}</span><span class="ss">"</span>)</span>
<span id="cb27-31"><a href="#cb27-31" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"-"</span> <span class="op">*</span> <span class="dv">63</span>)</span>
<span id="cb27-32"><a href="#cb27-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'separable, area x type'</span><span class="sc">:&lt;32}</span><span class="ss"> </span><span class="sc">{</span>sep_ll<span class="sc">:17.1f}</span><span class="ss"> </span><span class="sc">{</span>sep_params<span class="sc">:12,}</span><span class="ss">"</span>)</span>
<span id="cb27-33"><a href="#cb27-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'separable, variances only'</span><span class="sc">:&lt;32}</span><span class="ss"> </span><span class="sc">{</span>diag_ll<span class="sc">:17.1f}</span><span class="ss"> "</span></span>
<span id="cb27-34"><a href="#cb27-34" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="bu">sum</span>(c.shape[<span class="dv">0</span>] <span class="cf">for</span> c <span class="kw">in</span> covs)<span class="sc">:12,}</span><span class="ss">"</span>)</span>
<span id="cb27-35"><a href="#cb27-35" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'one variance for everything'</span><span class="sc">:&lt;32}</span><span class="ss"> </span><span class="sc">{</span>iso_ll<span class="sc">:17.1f}</span><span class="ss"> </span><span class="sc">{</span><span class="dv">1</span><span class="sc">:12,}</span><span class="ss">"</span>)</span>
<span id="cb27-36"><a href="#cb27-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'dense 192x192 + best ridge'</span><span class="sc">:&lt;32}</span><span class="ss"> </span><span class="sc">{</span>best_ll<span class="sc">:17.1f}</span><span class="ss"> </span><span class="sc">{</span>dim <span class="op">*</span> (dim <span class="op">+</span> <span class="dv">1</span>) <span class="op">//</span> <span class="dv">2</span><span class="sc">:12,}</span><span class="ss">"</span>)</span>
<span id="cb27-37"><a href="#cb27-37" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">the dense model's ridge (</span><span class="sc">{</span>best_ridge<span class="sc">:.2g}</span><span class="ss">) was chosen on the held-out weeks themselves"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>model                             held-out log-lik  free params
---------------------------------------------------------------
separable, area x type                      -192.7          336
separable, variances only                   -191.2           32
one variance for everything                 -192.7            1
dense 192x192 + best ridge                  -202.2       18,528

the dense model's ridge (1) was chosen on the held-out weeks themselves</code></pre>
</div>
</div>
<p>The separable model beats the ridged dense one, and it uses 55 times fewer parameters. The dense model was even allowed to choose its ridge using the test weeks, which no honest pipeline would permit.</p>
<p>But the margin is small: about nine nats per week. A nat is a unit of log-likelihood, so nine nats is a modest gain, not a large one.</p>
<p>Now look at the third row. <strong>One single variance for the whole array scores as well as the separable model.</strong> On this data, the mode structure is not worth the extra work.</p>
<p>The fitted correlations reach only about 0.3 between community areas and about 0.1 between offence types. Once the weekly means are removed, very little is left for a covariance to explain.</p>
<p>One modelling choice drives that result, and it should be stated. The numbers above subtract a separate weekly mean for each area and each offence type.</p>
<p>Subtract a single overall mean instead. The area and type effects then stay inside the covariance, the fitted correlations climb past 0.85, and the mode structure starts to look impressive. But the ridged dense model then wins instead. The covariance is now describing a mean, and the Kronecker assumption is the wrong shape for a mean.</p>
<p>Neither way of centring makes this array a good example of separable covariance.</p>
<p>So this row of the table delivers less than it usually promises. As a statistical argument it is weak here. What remains is that the structured model can be fitted at all, and at full size that alone decides the question.</p>
<div id="demand-counts" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>full <span class="op">=</span> counts.size</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"full array flattened: </span><span class="sc">{</span>full<span class="sc">:,}</span><span class="ss">-vector"</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  dense covariance:   </span><span class="sc">{</span>full <span class="op">*</span> (full <span class="op">+</span> <span class="dv">1</span>) <span class="op">//</span> <span class="dv">2</span><span class="sc">:,}</span><span class="ss"> free parameters, </span><span class="sc">{</span>full <span class="op">*</span> full <span class="op">*</span> <span class="dv">8</span> <span class="op">/</span> <span class="fl">1e9</span><span class="sc">:.1f}</span><span class="ss"> GB"</span>)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  separable, 3 modes: "</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="bu">sum</span>(d <span class="op">*</span> (d <span class="op">+</span> <span class="dv">1</span>) <span class="op">//</span> <span class="dv">2</span> <span class="cf">for</span> d <span class="kw">in</span> counts.shape)<span class="sc">:,}</span><span class="ss"> free parameters, "</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="bu">sum</span>(d <span class="op">*</span> d <span class="cf">for</span> d <span class="kw">in</span> counts.shape) <span class="op">*</span> <span class="dv">8</span> <span class="op">/</span> <span class="fl">1e3</span><span class="sc">:.1f}</span><span class="ss"> kB"</span>)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  and you have exactly 1 observation of that </span><span class="sc">{</span>full<span class="sc">:,}</span><span class="ss">-vector"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>full array flattened: 9,984-vector
  dense covariance:   49,845,120 free parameters, 0.8 GB
  separable, 3 modes: 1,714 free parameters, 26.8 kB
  and you have exactly 1 observation of that 9,984-vector</code></pre>
</div>
</div>
<div id="cell-fig-demand" class="cell" data-fig-height="3.9" data-fig-width="12.5" data-execution_count="18">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> to_corr(cov):</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> np.sqrt(np.diag(cov))</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>    R <span class="op">=</span> cov <span class="op">/</span> np.outer(d, d)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>    np.fill_diagonal(R, np.nan)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> R</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [t.title().replace(<span class="st">" "</span>, <span class="st">"</span><span class="ch">\n</span><span class="st">"</span>) <span class="cf">for</span> t <span class="kw">in</span> cmeta[<span class="st">"types"</span>]]</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="fl">12.5</span>, <span class="fl">3.9</span>), width_ratios<span class="op">=</span>[<span class="fl">1.15</span>, <span class="dv">1</span>, <span class="fl">1.05</span>, <span class="fl">0.8</span>])</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>cmap <span class="op">=</span> plt.get_cmap(<span class="st">"RdBu_r"</span>).copy()</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>cmap.set_bad(<span class="st">"#E9EBEF"</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>im <span class="op">=</span> axes[<span class="dv">0</span>].imshow(to_corr(covs[<span class="dv">0</span>]), cmap<span class="op">=</span>cmap, vmin<span class="op">=-</span><span class="fl">0.3</span>, vmax<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"community area correlation"</span>)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks(<span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">24</span>, <span class="dv">4</span>), <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">25</span>, <span class="dv">4</span>))</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_yticks(<span class="bu">range</span>(<span class="dv">0</span>, <span class="dv">24</span>, <span class="dv">4</span>), <span class="bu">range</span>(<span class="dv">1</span>, <span class="dv">25</span>, <span class="dv">4</span>))</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].imshow(to_corr(covs[<span class="dv">1</span>]), cmap<span class="op">=</span>cmap, vmin<span class="op">=-</span><span class="fl">0.3</span>, vmax<span class="op">=</span><span class="fl">0.3</span>)</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"offence-type correlation"</span>)</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(<span class="bu">range</span>(<span class="dv">8</span>), labels, fontsize<span class="op">=</span><span class="dv">6</span>, rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_yticks(<span class="bu">range</span>(<span class="dv">8</span>), labels, fontsize<span class="op">=</span><span class="dv">6</span>)</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>cbar <span class="op">=</span> fig.colorbar(im, ax<span class="op">=</span>axes[:<span class="dv">2</span>], shrink<span class="op">=</span><span class="fl">0.82</span>, pad<span class="op">=</span><span class="fl">0.16</span>,</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>                    label<span class="op">=</span><span class="st">"correlation (diagonal masked)"</span>)</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>cbar.ax.yaxis.set_label_position(<span class="st">"left"</span>)</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a>sd_area <span class="op">=</span> np.sqrt(np.diag(covs[<span class="dv">0</span>]))</span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>sd_type <span class="op">=</span> np.sqrt(np.diag(covs[<span class="dv">1</span>]))</span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].bar(np.arange(<span class="dv">1</span>, <span class="dv">25</span>), sd_area <span class="op">/</span> sd_area.mean(), color<span class="op">=</span>PURPLE, width<span class="op">=</span><span class="fl">0.75</span>)</span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"scale per community area"</span>)</span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xlabel(<span class="st">"community area"</span>)</span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylabel(<span class="st">"std dev / mean"</span>)</span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].axhline(<span class="fl">1.0</span>, color<span class="op">=</span>INK, lw<span class="op">=</span><span class="fl">0.8</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].bar(np.arange(<span class="dv">8</span>), sd_type <span class="op">/</span> sd_type.mean(), color<span class="op">=</span>TEAL, width<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].set_title(<span class="st">"scale per offence type"</span>)</span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].set_xticks(<span class="bu">range</span>(<span class="dv">8</span>), labels, fontsize<span class="op">=</span><span class="dv">6</span>, rotation<span class="op">=</span><span class="dv">90</span>)</span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">3</span>].axhline(<span class="fl">1.0</span>, color<span class="op">=</span>INK, lw<span class="op">=</span><span class="fl">0.8</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-demand" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-demand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-demand-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-demand-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: What the separable model actually found, which is not much. Left two panels: the fitted mode correlations with the diagonal hidden, on a ±0.3 scale. Right two: the scale of each area and each offence type, all within about 20% of one another. The structure is real but too weak to pay for itself, which is why one variance for the whole array scores as well.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="why-not-just-flatten" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="why-not-just-flatten"><span class="header-section-number">9</span> Why not just flatten</h2>
<p>Every number below was computed by a cell above.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Problem</th>
<th>Product</th>
<th>Inverse used</th>
<th>Operator, as a tensor</th>
<th>Operator, flattened</th>
<th>What flattening costs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Compliance</td>
<td>Einstein <span class="math inline">\(\circledast\)</span></td>
<td>multilinear Moore–Penrose</td>
<td>81 entries</td>
<td><span class="math inline">\(9\times9\)</span>, rank 6</td>
<td><strong>Nothing.</strong> Voigt drops exactly the null space. But converting back needs Reuter’s factors, and skipping them gives a 316% error off-axis</td>
</tr>
<tr class="even">
<td>Hyperspectral</td>
<td>t-product <span class="math inline">\(*\)</span></td>
<td>regularised t-solve</td>
<td>13.5 MB</td>
<td>1.4 GB block-circulant</td>
<td>relative error 0.125 against 0.038; spectral angle 3.12° against 1.79°</td>
</tr>
<tr class="odd">
<td>Task maps</td>
<td>mode-<span class="math inline">\(n\)</span> <span class="math inline">\(\times_n\)</span></td>
<td>mode-<span class="math inline">\(n\)</span> pseudoinverse</td>
<td><span class="math inline">\(120\times4\)</span> solve</td>
<td><span class="math inline">\(491{,}520 \times 16{,}384\)</span> design, 64 GB</td>
<td>nothing, statistically. The flattening is the same estimator written out 4,096 times</td>
</tr>
<tr class="even">
<td>Urban demand</td>
<td>— (separable model)</td>
<td>one precision per mode</td>
<td>336 parameters</td>
<td>18,528 parameters, rank 39 of 192</td>
<td>at this size, <strong>almost nothing.</strong> 9 nats of held-out log-likelihood, and one single variance matches that. On the full three-mode array, 0.8 GB and 49.8M parameters from one reading</td>
</tr>
</tbody>
</table>
<p>Two of these four rows say that flattening is fine. A third says it is fine at this size and impossible at full size. Only one row is a clear win for the tensor.</p>
<p>So the question is never “tensor or matrix”. The question is whether your chosen flattening keeps the structure that the operator actually has.</p>
<ul>
<li><strong>Compliance.</strong> The flattening loses nothing, because the directions it throws away are the ones the operator sends to zero. You risk a conversion error, not a loss of information.</li>
<li><strong>Task maps.</strong> The flattened GLM gives identical estimates. It wastes memory, but it is not wrong.</li>
<li><strong>Hyperspectral.</strong> The flattening drops the cross-band slices of the operator, so it solves a different problem. The error it cannot get below is the band mixing it threw away.</li>
<li><strong>Urban demand.</strong> The flattening asks for more parameters than the data can support. At three modes it asks for 0.8 GB of them from a single reading. But on this array the structure buys a model you can fit, and almost no accuracy. Check a structural assumption against the data. Do not adopt one just because the array has three modes.</li>
</ul>
</section>
<section id="open-problems" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="open-problems"><span class="header-section-number">10</span> Open problems</h2>
<p>Matrix inverses are settled textbook material. Tensor inverses are not.</p>
<ul>
<li><strong>The list is still growing.</strong> Over roughly the last decade, researchers have carried the classical family of generalized inverses across to tensors under the Einstein product. That includes the Moore–Penrose inverse (Sun et al.&nbsp;2016), the Drazin inverse (Behera et al.&nbsp;2020), and the core and core-EP inverses (Sahoo et al.&nbsp;2020). Papers defining more of them keep appearing. Nobody has agreed on a standard set, the way <span class="math inline">\(A^{-1}\)</span> and <span class="math inline">\(A^{\dagger}\)</span> are standard for matrices.</li>
<li><strong>The numerics are behind the algebra.</strong> We know when most of these inverses exist, and whether they are unique. We know much less about how the algorithms behave in floating point, or what they cost to run. For several of them there is no agreed condition number to quote.</li>
<li><strong>There are few tools.</strong> <a href="https://tensorly.org/">TensorLy</a> covers decompositions well. For the inverses, you mostly write your own code from the definition. That is what <code>src/tinv.py</code> in this post does.</li>
<li><strong>Do not overstate this.</strong> For elasticity, the Einstein-product inverse has been settled engineering practice for decades, under a different name. What is still open is the general theory and its numerics, not every use shown above.</li>
</ul>
</section>
<section id="next-steps" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="next-steps"><span class="header-section-number">11</span> Next steps</h2>
<ul>
<li><strong>t-product solvers.</strong> t-GMRES and tensor Golub–Kahan (El Guide et al.&nbsp;2021) find <span class="math inline">\(\mathcal{X}\)</span> without ever building <span class="math inline">\(\mathcal{A}^{-1}\)</span>. On a full <span class="math inline">\(610\times340\times103\)</span> scene, that is the difference between a program that runs and one that does not.</li>
<li><strong>Tucker- and TT-format inverses.</strong> Worth timing when the operator itself will not fit in memory. The inverse usually has a higher rank than the operator, so the question that matters is how much higher, on your own problem.</li>
<li><strong>CP-based approximate inverses.</strong> These give a rough approximation, not an inverse. They are cheap, but nothing is guaranteed.</li>
<li><strong>Where TensorLy stops.</strong> It gives you CP, Tucker, TT and t-SVD. For the inverses above, the definitions are short and <code>numpy</code> is enough. The four in <code>src/tinv.py</code> are about a dozen lines each.</li>
</ul>
<p>Problems. Pick. Products. Inverses. Follow. Flattening. Sometimes. Works. Check. First.</p>
</section>
<section id="references" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="references"><span class="header-section-number">12</span> References</h2>
<ul>
<li>Brazell, M., Li, N., Navasca, C., and Tamon, C. (2013). Solving multilinear systems via tensor inversion. <em>SIAM Journal on Matrix Analysis and Applications</em> 34(2), 542–570.</li>
<li>Behera, R., Nandi, A. K., and Sahoo, J. K. (2020). <a href="https://doi.org/10.1002/nla.2317">Further results on the Drazin inverse of even-order tensors</a>. <em>Numerical Linear Algebra with Applications</em> 27(5), e2317.</li>
<li>Dutilleul, P. (1999). <a href="https://doi.org/10.1080/00949659908811970">The MLE algorithm for the matrix normal distribution</a>. <em>Journal of Statistical Computation and Simulation</em> 64(2), 105–123.</li>
<li>El Guide, M., El Ichi, A., Jbilou, K., and Sadaka, R. (2021). <a href="https://doi.org/10.13001/ela.2021.5471">On tensor GMRES and Golub–Kahan methods via the t-product for color image processing</a>. <em>The Electronic Journal of Linear Algebra</em> 37, 524–543.</li>
<li>Hoff, P. D. (2011). <a href="https://doi.org/10.1214/11-BA606">Separable covariance arrays via the Tucker product, with applications to multivariate relational data</a>. <em>Bayesian Analysis</em> 6(2), 179–196.</li>
<li>Kilmer, M. E., and Martin, C. D. (2011). Factorization strategies for third-order tensors. <em>Linear Algebra and its Applications</em> 435(3), 641–658.</li>
<li>Kolda, T. G., and Bader, B. W. (2009). Tensor decompositions and applications. <em>SIAM Review</em> 51(3), 455–500.</li>
<li>Kossaifi, J., Panagakis, Y., Anandkumar, A., and Pantic, M. (2019). <a href="https://tensorly.org/">TensorLy: tensor learning in Python</a>. <em>JMLR</em> 20(26), 1–6.</li>
<li>Sahoo, J. K., Behera, R., Stanimirović, P. S., Katsikis, V. N., and Ma, H. (2020). <a href="https://doi.org/10.1007/s40314-019-0983-5">Core and core-EP inverses of tensors</a>. <em>Computational and Applied Mathematics</em> 39, 9.</li>
<li>Sun, L., Zheng, B., Bu, C., and Wei, Y. (2016). <a href="https://doi.org/10.1080/03081087.2015.1083933">Moore–Penrose inverse of tensors via Einstein product</a>. <em>Linear and Multilinear Algebra</em> 64(4), 686–698.</li>
<li><a href="https://www.ehu.eus/ccwintco/index.php/Hyperspectral_Remote_Sensing_Scenes">Hyperspectral Remote Sensing Scenes</a> — Pavia University, ROSIS sensor; scenes provided by P. Gamba (University of Pavia), collection assembled by M. Graña, M. A. Veganzones and B. Ayerdi (UPV/EHU). Fetched here from an <a href="https://huggingface.co/datasets/danaroth/pavia">ungated mirror</a>.</li>
<li><a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-Present/ijzp-q8t2">Crimes — 2001 to Present</a> — City of Chicago open data portal.</li>
<li><a href="../tensor-factorizations/">Tensor Factorizations and Tensor Inverses</a> — CP, Tucker, TT, t-SVD, and the four inverses on a synthetic cube.</li>
<li><a href="../uses-of-tensor-factorizations/">Uses of Tensor Factorizations</a> — the compression case.</li>
</ul>
<script src="widget-data/data.js"></script>
<script src="widgets.js"></script>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/project-delphi\.github\.io\/ml-blog\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Synthetic Musings, by Ravi Kalia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tensor-inverses-in-practice/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>