{
  "hash": "776e02ef022d89474d393c446a90295d",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"From Dataset to Biological Signature\"\nsubtitle: \"The same pipeline, told twice — once for a machine learning scientist, once for a statistician. The disagreement is only in vocabulary, and both vocabularies are describing a selection event.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-08-27\"\ncategories: [Genomics, Statistics, Machine Learning, Bioinformatics, Python]\ntags: [gene-expression, feature-selection, elastic-net, stability-selection, leakage, golub, leukemia]\nimage: \"./cover.png\"\ndescription: \"Golub's 1999 ALL/AML data, run end to end: recovering the original designed train/test split from an unlabelled CSV, fitting a signature with nested cross-validation, and showing why the honest error rate is the hard one to get.\"\njupyter: signature-blog\nresources:\n  - cover.png\n  - data\nexecute:\n  warning: false\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: show\n    theme: [zephyr, theme.scss]\n    fig-width: 8\n    fig-height: 4.5\n    fig-dpi: 150\n---\n\n\n![](./cover.png){fig-alt=\"Cover card reading From Dataset to a Biological Signature, over a solid purple background.\"}\n\nTwo acute leukemias arrive at the clinic looking much the same. Both fill the marrow\nwith immature white cells, both make the patient acutely ill within weeks, and under\na microscope the blasts of one can pass for the blasts of the other. They need\nopposite treatments. Get it wrong and you give a toxic regimen that will not work to\nsomeone who has a few weeks to spare.\n\nBefore 1999 that call was made by an experienced haematologist reading morphology,\nchemical stains and surface markers. It was good, and it was not reproducible between\nhospitals. Golub and colleagues asked whether gene expression could make the call on\nits own — and whether you could have discovered the two diseases without being told\nthey existed.\n\nThis post runs that question end to end, twice. The argument underneath it is one\nsentence: **a signature is a supervised object, and every number you attach to one is\nconditioned on the selection event that produced it.** A machine learning scientist\nand a statistician describe that fact in different words. Both descriptions are here,\nand they are the same pipeline.\n\n### Two assembly lines, and a glitch on one of them\n\nThe biology is worth two minutes, because it turns out to be what the model recovers.\nThink of bone marrow as a factory with two assembly lines running from a single stem\ncell. The **lymphoid** line builds B-cells and T-cells — the targeted, specific arm of\nthe immune system, the sharpshooters. The **myeloid** line builds everything else: red\ncells that carry oxygen, platelets that clot, granulocytes that do the frontline\nbrawling.\n\nAn acute leukemia is a glitch that jams one line, flooding the marrow with immature\ncells — blasts — that will neither mature into anything useful nor stop dividing.\n\n\n```{mermaid}\nflowchart TD\n  S[\"Bone marrow stem cell\"] --> L[\"Lymphoid line<br/>B-cells, T-cells\"]\n  S --> M[\"Myeloid line<br/>red cells, platelets, granulocytes\"]\n  L -->|glitch| ALL[\"<b>ALL</b><br/>lymphoblasts\"]\n  M -->|glitch| AML[\"<b>AML</b><br/>myeloblasts\"]\n```\n\n\nJam the lymphoid line and you get acute lymphoblastic leukemia, ALL — the commonest\ncancer of childhood. Jam the myeloid line and you get acute myeloid leukemia, AML,\nmostly an adult disease diagnosed at a median age near 68, and faster to strip out\noxygen transport and clotting because the myeloid line covers more jobs.\n\nSo the diagnostic question has a clean biological shape: *which line is stuck?* Hold\non to that. It is what the classifier ends up measuring.\n\n### The data, and who went to the trouble of collecting it\n\nThe measurements come from Golub et al. (1999) at the Whitehead Institute and\nDana-Farber, who ran marrow and blood from 72 acute leukemia patients on Affymetrix\nHU6800 arrays — 7,129 probes, one fluorescence intensity each. They were not building\na product; they assembled samples from existing clinical archives to argue that\ntumour class is legible in expression at all.\n\nA decision made from this analysis is a treatment assignment: vincristine and\nsteroids for ALL, cytarabine and an anthracycline for AML, for a patient seriously\nill either way. So the interesting quantity is not peak accuracy. It is how much of\nthe accuracy survives contact with a different hospital.\n\nI use the copy on Efron and Hastie's *Computer Age Statistical Inference* data page,\ncached in this post's `data/` directory so the render never touches the network.\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Imports, plot style, and loading the cached matrices\"}\nimport warnings\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\nfrom scipy.stats import beta\n\nwarnings.filterwarnings(\"ignore\")\nrng_seed = 0\n\nplt.rcParams.update({\n    \"figure.dpi\": 150, \"savefig.bbox\": \"tight\", \"font.size\": 9,\n    \"axes.spines.top\": False, \"axes.spines.right\": False,\n    \"axes.grid\": True, \"grid.alpha\": 0.25, \"axes.axisbelow\": True,\n})\nALL_C, AML_C = \"#1D5C6E\", \"#C98A12\"\n\n# The CASI matrix: 7,128 genes x 72 samples, column names carry the labels.\ncasi = pd.read_csv(\"data/leukemia_big.csv.gz\")\nX = casi.to_numpy().T                                    # samples x genes\ny = np.array([int(c.split(\".\")[0].startswith(\"AML\")) for c in casi.columns])\n\n# The original Whitehead files, used only as a key: they carry the Affymetrix\n# probe accessions and the per-patient sample IDs that the CASI copy dropped.\ndef read_golub(path):\n    d = pd.read_csv(path)\n    ids = [c for c in d.columns[2:] if not c.startswith(\"call\")]\n    return d[\"Gene Accession Number\"].to_numpy(), d[\"Gene Description\"].to_numpy(), \\\n           d[ids].to_numpy(dtype=float), ids\n\nacc, desc, G_train, id_train = read_golub(\"data/golub_train.csv.gz\")\n_, _, G_test, id_test = read_golub(\"data/golub_independent.csv.gz\")\ntruth = pd.read_csv(\"data/golub_labels.csv\").set_index(\"patient\")[\"cancer\"].to_dict()\n\nprint(f\"expression matrix : {X.shape[0]} samples x {X.shape[1]} genes\")\nprint(f\"class balance     : {(y==0).sum()} ALL, {y.sum()} AML\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nexpression matrix : 72 samples x 7128 genes\nclass balance     : 47 ALL, 25 AML\n```\n:::\n:::\n\n\nSeventy-two samples, 7,128 genes: a hundred times more things measured than people\nto measure them on. Every difficulty below follows from that ratio.\n\n::: {#cell-slice .cell execution_count=2}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"A corner of the matrix\"}\npd.DataFrame(\n    X[:5, :6].round(3),\n    index=[f\"sample {i} ({'AML' if y[i] else 'ALL'})\" for i in range(5)],\n    columns=[f\"gene {j}\" for j in range(6)],\n)\n```\n\n::: {#slice .cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>gene 0</th>\n      <th>gene 1</th>\n      <th>gene 2</th>\n      <th>gene 3</th>\n      <th>gene 4</th>\n      <th>gene 5</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>sample 0 (ALL)</th>\n      <td>-1.534</td>\n      <td>-1.236</td>\n      <td>-0.334</td>\n      <td>0.489</td>\n      <td>-1.301</td>\n      <td>-1.683</td>\n    </tr>\n    <tr>\n      <th>sample 1 (ALL)</th>\n      <td>-0.868</td>\n      <td>-1.276</td>\n      <td>0.376</td>\n      <td>0.444</td>\n      <td>-1.230</td>\n      <td>-1.642</td>\n    </tr>\n    <tr>\n      <th>sample 2 (ALL)</th>\n      <td>-0.433</td>\n      <td>-1.184</td>\n      <td>-0.459</td>\n      <td>0.436</td>\n      <td>-1.326</td>\n      <td>-1.407</td>\n    </tr>\n    <tr>\n      <th>sample 3 (ALL)</th>\n      <td>-1.672</td>\n      <td>-1.596</td>\n      <td>-1.423</td>\n      <td>0.193</td>\n      <td>-1.818</td>\n      <td>-1.744</td>\n    </tr>\n    <tr>\n      <th>sample 4 (ALL)</th>\n      <td>-1.188</td>\n      <td>-1.335</td>\n      <td>-0.797</td>\n      <td>0.236</td>\n      <td>-1.311</td>\n      <td>-1.654</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe values are not raw intensities. Each *column* has been standardised to mean zero\nand unit standard deviation across genes, and beyond that the file's own\ndocumentation says the gene-level transformation is \"lost in time\".\n\n## The file on Hastie's server is Golub's two cohorts, stored backwards\n\nGolub's design had a feature that matters more than anything else here. The 72\nsamples are not one pool. Thirty-eight came from a single institution, all bone\nmarrow, and built the predictor. The other 34 were collected later from different\nreference laboratories, on different preparation protocols, and included peripheral\nblood as well as marrow — a genuine external cohort with a real distribution shift,\nwhich is the only kind of test set worth quoting.\n\nThe CASI file has no sample identifiers, so that split looks lost. It is recoverable,\nand worth recovering properly rather than guessing from label counts. Per-sample\nstandardisation is monotone within a column, so it preserves the *ranking* of genes\ninside a sample. Rank each column of both files and correlate.\n\n::: {#recover-split .cell execution_count=3}\n``` {.python .cell-code code-fold=\"show\"}\nG = np.hstack([G_train, G_test])[:X.shape[1]]   # CASI drops Golub's last probe\nids = id_train + id_test\ngolub_y = np.array([int(truth[int(i)] == \"AML\") for i in ids])\n\nrank = lambda A: np.argsort(np.argsort(A, axis=0), axis=0).astype(float)\nRc, Rg = rank(casi.to_numpy()), rank(G)\nRc = (Rc - Rc.mean(0)) / Rc.std(0)\nRg = (Rg - Rg.mean(0)) / Rg.std(0)\nS = (Rc.T @ Rg) / G.shape[0]                    # 72 x 72 Spearman matrix\nmatch, best = S.argmax(1), np.sort(S, axis=1)\n\nprint(f\"unique matches      : {len(set(match.tolist()))}/72\")\nprint(f\"labels agree        : {(golub_y[match] == y).sum()}/72\")\nprint(f\"worst true match    : {best[:, -1].min():.3f}\")\nprint(f\"best runner-up      : {best[:, -2].max():.3f}\")\nprint(f\"CASI column 0 -> patient {ids[match[0]]};  column 34 -> patient {ids[match[34]]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nunique matches      : 72/72\nlabels agree        : 72/72\nworst true match    : 0.945\nbest runner-up      : 0.884\nCASI column 0 -> patient 39;  column 34 -> patient 1\n```\n:::\n:::\n\n\nEvery column matches one patient, uniquely, and every label agrees. The weakest true\nmatch scores 0.945 against a best runner-up of 0.884, so the assignment is not close\nto ambiguous. It also settles the ordering: column 0 is patient 39 and column 34 is\npatient 1, so the file stores the **independent test cohort first** — the reverse of\nthe conventional layout. Splitting this file at the front hands you Golub's held-out\nsamples as training data.\n\nOne caveat that no amount of downstream care removes: the per-gene transformation\nthe CASI page cannot document may well have been fitted across all 72 samples.\nPer-sample standardisation is leak-free, since a column only ever sees itself. That\nother step is not. Everything below is conditional on it.\n\n::: {#cell-fig-data .cell execution_count=4}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Figure 1\"}\ntest_ix, train_ix = np.arange(34), np.arange(34, 72)\nprobe = {a: i for i, a in enumerate(acc[:X.shape[1]])}\nmpo, ccnd3 = probe[\"M19507_at\"], probe[\"M92287_at\"]\n\nZ = (X - X.mean(0)) / (X.std(0) + 1e-9)\nU, sv, _ = np.linalg.svd(Z - Z.mean(0), full_matrices=False)\npcs = U[:, :5] * sv[:5]\n\n# Pick the axes by what they actually carry, rather than assuming PC1/PC2:\n# correlate each component with class and with cohort membership.\ncohort = np.r_[np.zeros(34), np.ones(38)]\ncorr = lambda v: np.array([abs(np.corrcoef(v, pcs[:, k])[0, 1]) for k in range(5)])\nk_cls, k_coh = corr(y).argmax(), corr(cohort).argmax()\n\nfig, (a1, a2) = plt.subplots(1, 2, figsize=(8, 3.6))\nfor cls, name, col in [(0, \"ALL\", ALL_C), (1, \"AML\", AML_C)]:\n    m = y == cls\n    a1.scatter(X[m, ccnd3], X[m, mpo], c=col, s=28, alpha=0.85, label=name,\n               edgecolor=\"white\", linewidth=0.5)\na1.set(xlabel=\"CCND3 (cyclin D3), lymphoid\", ylabel=\"MPO (myeloperoxidase), myeloid\",\n       title=\"Two genes\")\na1.legend(frameon=False, fontsize=8)\n\nfor cls, col in [(0, ALL_C), (1, AML_C)]:\n    for ix, mark, lab in [(train_ix, \"o\", \"training\"), (test_ix, \"^\", \"external\")]:\n        m = np.intersect1d(np.flatnonzero(y == cls), ix)\n        a2.scatter(pcs[m, k_cls], pcs[m, k_coh], c=col, marker=mark, s=28, alpha=0.85,\n                   edgecolor=\"white\", linewidth=0.5,\n                   label=f\"{'AML' if cls else 'ALL'}, {lab}\")\na2.set(xlabel=f\"PC{k_cls + 1}  (carries class, |r| = {corr(y)[k_cls]:.2f})\",\n       ylabel=f\"PC{k_coh + 1}  (carries cohort, |r| = {corr(cohort)[k_coh]:.2f})\",\n       title=\"Colour = class, shape = cohort\")\na2.legend(frameon=False, fontsize=7, loc=\"best\")\nfig.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Left: two genes named later in the post, one myeloid and one lymphoid, separate the classes almost on their own. Right: the component that carries diagnosis plotted against the one that carries cohort. Class separates left-to-right and the laboratory separates bottom-to-top, on different axes — the nuisance variable has structure of its own.](index_files/figure-html/fig-data-output-1.png){#fig-data}\n:::\n:::\n\n\nThe classes are nearly separable in two hand-picked genes, which tells you the signal\nhere is unusually strong — remember that when the error rates arrive. The right panel\nis the warning attached to it. Diagnosis and laboratory load on *different* principal\ncomponents, so the batch effect is not noise smeared over the class signal; it is its\nown coherent direction in the data. A ridge classifier trained to predict which\nlaboratory a sample came from, ignoring diagnosis entirely, reaches 78% under\ncross-validation. Batch is a learnable feature, and a model will use it if you let it.\n\n## For the ML scientist: the signature is supervised, the plumbing is not\n\n**What is the design matrix, and where does the domain knowledge sit?** Rows are\npatients, columns are genes, entries are normalised expression. All the biology lives\nupstream of that matrix — which probes map to which transcript, how intensities are\nfloored and logged, how arrays are normalised against each other. That featurisation\nis assay-specific and does not transfer; rebuild this study on RNA-seq and the whole\npreprocessing stack changes. What happens after the matrix exists is ordinary\nsupervised learning. The asymmetry is why genomics pipelines break when they are\nported rather than when they are fit.\n\n**Is finding a signature supervised or unsupervised?** Supervised, and worth saying\nflatly because the field's vocabulary blurs it. A signature is defined *relative to a\nphenotype*. Strip the labels and you still have structure, but structure is not a\nsignature; it is a pattern that might be disease, sex, batch, or the day the samples\nwere run. Unsupervised methods do the plumbing: normalisation, dimensionality\nreduction, and checking that the dominant variation tracks biology rather than the\nlaboratory — which is what the right panel above was for.\n\nThe exception is real, and Golub's paper is why it is famous. Cluster first, discover\na grouping nobody had a label for, then treat the cluster assignments as labels. That\nis class *discovery*, and their paper did both halves. Discovery proposes the\nphenotype; the signature is still supervised once you have one.\n\n**What actually ships?** A fixed gene list, fixed coefficients, and a threshold\nlocked before anyone opens the test set. Not a model you keep tuning. Which is why\nthe penalty is chosen inside cross-validation rather than by looking at the answer:\n\n$$\n\\hat\\beta \\;=\\; \\arg\\min_{\\beta}\\; -\\frac{1}{n}\\sum_{i=1}^{n}\\Big[y_i\\,x_i^{\\top}\\beta - \\log\\big(1 + e^{x_i^{\\top}\\beta}\\big)\\Big] \\;+\\; \\lambda\\Big(\\alpha\\lVert\\beta\\rVert_1 + \\tfrac{1-\\alpha}{2}\\lVert\\beta\\rVert_2^2\\Big)\n$$\n\nThe $\\ell_1$ term forces most coefficients to zero, which is what makes the result a\nshort gene list; the $\\ell_2$ term stops correlated genes being picked arbitrarily\none-from-each-group. With $\\alpha = 0.5$ the only free parameter is $\\lambda$,\nchosen in an inner loop while an outer loop estimates performance — so the number\nbelow never saw the data that produced it.\n\n::: {#cell-fig-path .cell execution_count=5}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Nested cross-validation, and Figure 2\"}\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.model_selection import StratifiedKFold, cross_val_score\nfrom sklearn.metrics import accuracy_score, roc_auc_score, brier_score_loss\n\nXtr, ytr, Xte, yte = X[train_ix], y[train_ix], X[test_ix], y[test_ix]\nCs = np.logspace(-2, 1, 7)\n\ndef enet(C):\n    return LogisticRegression(penalty=\"elasticnet\", solver=\"saga\", l1_ratio=0.5,\n                              C=C, max_iter=3000, tol=1e-3, random_state=rng_seed)\n\ndef screen(A, k=2000):\n    \"\"\"Unsupervised variance screen. Never sees y, so it is safe inside a fold.\"\"\"\n    return np.argsort(-A.var(0))[:k]\n\nouter, scores = StratifiedKFold(5, shuffle=True, random_state=0), []\nfor a, b in outer.split(Xtr, ytr):\n    g = screen(Xtr[a])\n    mu, sd = Xtr[a][:, g].mean(0), Xtr[a][:, g].std(0) + 1e-9\n    Za, Zb = (Xtr[a][:, g] - mu) / sd, (Xtr[b][:, g] - mu) / sd\n    inner = StratifiedKFold(4, shuffle=True, random_state=1)\n    C = max(Cs, key=lambda c: cross_val_score(enet(c), Za, ytr[a], cv=inner).mean())\n    scores.append(accuracy_score(ytr[b], enet(C).fit(Za, ytr[a]).predict(Zb)))\n\n# Full-training-set path, for the figure and for the final penalty.\ng = screen(Xtr)\nmu, sd = Xtr[:, g].mean(0), Xtr[:, g].std(0) + 1e-9\nZtr, Zte = (Xtr[:, g] - mu) / sd, (Xte[:, g] - mu) / sd\ncv5 = StratifiedKFold(5, shuffle=True, random_state=1)\npath = np.array([cross_val_score(enet(c), Ztr, ytr, cv=cv5) for c in Cs])\nC_star = Cs[path.mean(1).argmax()]\n\nprint(f\"nested CV accuracy : {np.mean(scores):.3f}  (outer folds \"\n      f\"{[round(s, 2) for s in scores]})\")\n\nfig, ax = plt.subplots(figsize=(6.2, 3.2))\nax.errorbar(Cs, path.mean(1), yerr=path.std(1), marker=\"o\", color=ALL_C,\n            capsize=3, linewidth=1.5, markersize=5)\nax.axvline(C_star, color=AML_C, linestyle=\"--\", linewidth=1.3,\n           label=f\"chosen C = {C_star:.2f}\")\nax.set(xscale=\"log\", xlabel=\"C  (inverse penalty strength)\",\n       ylabel=\"inner-fold accuracy\", title=\"Regularisation path\")\nax.legend(frameon=False, fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnested CV accuracy : 0.921  (outer folds [0.75, 1.0, 1.0, 0.86, 1.0])\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Inner-fold accuracy along the regularisation path, on the 38 training samples only. Accuracy peaks at a single interior value. To the left the penalty is strong enough to zero out genes the model needs; to the right it is weak enough to admit genes that only help on the training fold. Error bars are one standard deviation across five folds, and they are wide — 38 samples do not locate this optimum precisely.](index_files/figure-html/fig-path-output-2.png){#fig-path}\n:::\n:::\n\n\nNested cross-validation puts the predictor at 0.921 on the training cohort. Now\nlock it and open the external samples once.\n\n::: {#external .cell execution_count=6}\n``` {.python .cell-code code-fold=\"show\"}\nfinal = enet(C_star).fit(Ztr, ytr)\nselected = g[np.flatnonzero(final.coef_[0])]\np_test = final.predict_proba(Zte)[:, 1]\n\nprint(f\"genes with non-zero coefficient : {len(selected)}\")\nprint(f\"external accuracy : {accuracy_score(yte, p_test > 0.5):.3f} \"\n      f\"({int((( p_test > 0.5) == yte).sum())}/34)\")\nprint(f\"external AUC      : {roc_auc_score(yte, p_test):.3f}\")\nprint(f\"external Brier    : {brier_score_loss(yte, p_test):.3f}\")\nwrong = np.flatnonzero((p_test > 0.5).astype(int) != yte)\nprint(f\"the one error     : predicted p(AML) = {p_test[wrong][0]:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ngenes with non-zero coefficient : 88\nexternal accuracy : 0.971 (33/34)\nexternal AUC      : 1.000\nexternal Brier    : 0.041\nthe one error     : predicted p(AML) = 0.468\n```\n:::\n:::\n\n\n**What did it find?** Thirty-three of 34 external samples correct, AUC 1.000, and the\nsingle mistake sits at $p = 0.468$ — on the wrong side of the threshold by three\nhundredths, not a confident error. Note the direction of the gap: nested\ncross-validation said 0.921 and the external cohort delivered 0.971. The internal\nestimate was *pessimistic*, which is worth flagging because the failure mode everyone\nis trained to expect runs the other way.\n\nThe gene list is what closes the loop back to the marrow.\n\n::: {#lineage .cell execution_count=7}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Naming the selected genes\"}\nlineage = {\n    \"M19507_at\": \"MPO, myeloperoxidase — the granulocyte enzyme\",\n    \"M23197_at\": \"CD33 — myeloid surface antigen\",\n    \"X52056_at\": \"SPI1 / PU.1 — myeloid master transcription factor\",\n    \"M84526_at\": \"DF, adipsin — Golub's AML-high list\",\n    \"M27891_at\": \"CST3, cystatin C — Golub's AML-high list\",\n    \"M92287_at\": \"CCND3, cyclin D3 — Golub's ALL-high list\",\n    \"U05259_rna1_at\": \"MB-1 / CD79a — B-cell receptor component\",\n    \"M31523_at\": \"TCF3 / E2A — required for B-cell development\",\n}\nhits = [(acc[i], lineage[acc[i]]) for i in selected if acc[i] in lineage]\nfor a, note in hits:\n    print(f\"  {a:16s} {note}\")\nprint(f\"\\n{len(hits)} of these annotated markers survived selection.\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  M27891_at        CST3, cystatin C — Golub's AML-high list\n  X52056_at        SPI1 / PU.1 — myeloid master transcription factor\n  M84526_at        DF, adipsin — Golub's AML-high list\n  M19507_at        MPO, myeloperoxidase — the granulocyte enzyme\n  U05259_rna1_at   MB-1 / CD79a — B-cell receptor component\n  M23197_at        CD33 — myeloid surface antigen\n  M92287_at        CCND3, cyclin D3 — Golub's ALL-high list\n\n7 of these annotated markers survived selection.\n```\n:::\n:::\n\n\nMyeloid markers on one side, lymphoid markers on the other. The classifier is reading\nout which assembly line is stuck — it has recovered the lineage question, not\nmemorised 72 patients. And among the genes it keeps is myeloperoxidase, precisely the\nenzyme the pre-1999 cytochemical stain tested for. The expression profile arrives at\nthe haematologist's own marker from the other direction.\n\nThat is the optimistic reading. The next section runs the same pipeline and asks what\nthose numbers are estimates *of*.\n\n## For the statistician: every coefficient is conditioned on a selection event\n\nRecast the problem and the difficulty changes shape. This is sparse variable\nselection with $p \\gg n$: 7,128 candidate predictors, 38 training observations, and\nan assumption that only a handful matter. The estimator picks that handful and\nreports coefficients for it. Those two steps are not separable, and the second\ninherits the first.\n\nSo a naive confidence interval on a selected coefficient is meaningless. It is\ncomputed as though the gene had been named in advance, when the gene is there\n*because* it looked good in this sample. The interval is too narrow and the p-value\ntoo small, by an amount that depends on the selection rule. The repairs are known and\nnone of them is \"use the same-data p-values\": split the sample and do inference on\nthe untouched half; condition on the selection event explicitly, as selective\ninference does; or construct knockoff variables that mimic the correlation structure\nwith no real association, and calibrate against them.\n\nMultiplicity is the second problem, and a Bonferroni reflex does not solve it. The\nrelevant guarantee at this scale is the false discovery rate,\n\n$$\n\\mathrm{FDR} \\;=\\; \\mathbb{E}\\!\\left[\\frac{V}{\\max(R, 1)}\\right],\n$$\n\nwith $R$ the number of rejections and $V$ the number of them that are false. The\npractical difficulty is that genes are not independent. They sit in co-regulated\nmodules, so one upstream event moves fifty together and the effective number of\nindependent tests is far below 7,128. Benjamini–Hochberg holds under positive\ndependence, but correlation makes the realised false discovery proportion highly\nvariable around its mean — you can control the average and still draw a badly wrong\nlist this time.\n\nStated as stages, the pipeline the section above ran informally is:\n\n1. Lock the estimand and the operating point before looking at anything.\n2. Split, before any transformation touches the data.\n3. Fit normalisation and any filter on training folds only.\n4. Choose the penalty in an inner loop, estimate performance in an outer loop.\n5. Check the selected set is stable, not merely optimal once.\n6. Lock coefficients and threshold, evaluate externally once, and report calibration\n   and intervals rather than a bare discrimination number.\n\nStep 3 is the one usually violated, and the violation is almost never deliberate.\n\n### Leakage is the default because the filter sees the whole dataset\n\nThe natural way to handle 7,128 genes is to rank them by a two-sample t-statistic,\nkeep the top 50, and cross-validate on those. It feels safe: inside the loop the model\nonly ever trains on the training fold. But the *filter* ran once, on everything, so\nthe held-out fold helped choose the genes it is later used to score. Ambroise and\nMcLachlan named this in 2002, and it reproduces in a few lines.\n\n::: {#leakage .cell execution_count=8}\n``` {.python .cell-code code-fold=\"show\"}\ndef top_genes(A, lab, k=50):\n    m0, m1 = A[lab == 0].mean(0), A[lab == 1].mean(0)\n    se = np.sqrt(A[lab == 0].var(0) / (lab == 0).sum()\n                 + A[lab == 1].var(0) / lab.sum()) + 1e-9\n    return np.argsort(-np.abs((m1 - m0) / se))[:k]\n\ndef two_ways(lab, cv=StratifiedKFold(10, shuffle=True, random_state=7)):\n    once = cross_val_score(enet(1.0), Z[:, top_genes(Z, lab)], lab, cv=cv).mean()\n    fold = [accuracy_score(lab[b], enet(1.0)\n            .fit(Z[a][:, (gi := top_genes(Z[a], lab[a]))], lab[a])\n            .predict(Z[b][:, gi])) for a, b in cv.split(Z, lab)]\n    return 1 - once, 1 - np.mean(fold)\n\nopt, honest = two_ways(y)\nprint(f\"real labels     : filter once {opt:.1%} error | filter in fold {honest:.1%}\")\n\nshuffled = np.random.default_rng(3).permutation(y)\nopt_n, honest_n = two_ways(shuffled)\nprint(f\"labels shuffled : filter once {opt_n:.1%} error | filter in fold {honest_n:.1%}\")\nprint(f\"chance for this class balance : {(y == 0).mean():.1%} correct by always saying ALL\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nreal labels     : filter once 2.9% error | filter in fold 4.3%\nlabels shuffled : filter once 7.0% error | filter in fold 33.2%\nchance for this class balance : 65.3% correct by always saying ALL\n```\n:::\n:::\n\n\nOn the real labels the gap is small — 2.9% against 4.3% — and that is the honest\nresult, not a failed demonstration. The ALL/AML signal is so strong that leakage has\nalmost nothing left to add.\n\nThe second line is the demonstration. Shuffle the labels so no signal exists at all,\nand selecting genes once on the full dataset reports 7.0% error: 93% accuracy on pure\nnoise. Do the same selection inside each fold and the error goes to 33.2%, against\nthe 34.7% you get by always guessing ALL. The optimism is not a small bias that\nscales with the signal; it is nearly the whole number when there is nothing there.\nLeakage is almost invisible in the regime where you do not need the estimate, and\ncatastrophic in the regime where you do.\n\n### A signature is a draw from a distribution of signatures\n\nOptimality on one sample is not reproducibility. Refit on random halves of the\ntraining set and record how often each gene survives: genes chosen for real structure\nkeep appearing, genes chosen for noise do not.\n\n::: {#cell-fig-stability .cell execution_count=9}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Stability selection, and Figure 3\"}\nrng = np.random.default_rng(rng_seed)\nfreq, B = np.zeros(X.shape[1]), 100\npool = screen(Xtr)\nfor _ in range(B):\n    take = rng.choice(len(ytr), len(ytr) // 2, replace=False)\n    if len(np.unique(ytr[take])) < 2:\n        continue\n    A = Xtr[take][:, pool]\n    A = (A - A.mean(0)) / (A.std(0) + 1e-9)\n    freq[pool[np.flatnonzero(enet(0.5).fit(A, ytr[take]).coef_[0])]] += 1\nfreq /= B\n\norder = np.argsort(-freq)\nfor t in (0.5, 0.6, 0.7, 0.9):\n    print(f\"selection frequency >= {t}: {(freq >= t).sum()} genes\")\n\nfig, ax = plt.subplots(figsize=(7.6, 3.4))\ntop = order[:60]\nax.bar(range(len(top)), freq[top], color=ALL_C, width=0.8)\nax.axhline(0.6, color=AML_C, linestyle=\"--\", linewidth=1.3, label=\"cutoff = 0.6\")\nabove = int((freq[top] >= 0.6).sum())\nax.set_xticks(range(above))\nax.set_xticklabels([acc[i] for i in top[:above]], rotation=90, fontsize=5)\nax.set(xlim=(-1, len(top)), ylabel=\"selection frequency\",\n       xlabel=\"genes, ranked\", title=f\"{B} half-samples of the 38 training patients\")\nax.legend(frameon=False, fontsize=8)\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nselection frequency >= 0.5: 45 genes\nselection frequency >= 0.6: 33 genes\nselection frequency >= 0.7: 26 genes\nselection frequency >= 0.9: 12 genes\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Selection frequency across 100 half-samples of the training cohort, sorted. The dashed line is a 0.6 cutoff. Genes above it are labelled by Affymetrix probe.](index_files/figure-html/fig-stability-output-2.png){#fig-stability}\n:::\n:::\n\n\nForty-five genes clear a 0.5 cutoff and only 12 clear 0.9. The 88-gene list is\ntherefore not one thing: most of its members are interchangeable with a correlated\nneighbour, and a different 38 patients would have returned a visibly different list\nwith much the same accuracy.\n\nThat instability is not an artefact of the elastic net. Reconstruct Golub's own\n50-gene predictor with the signal-to-noise statistic from his paper,\n$P(g,c) = (\\mu_1 - \\mu_0)/(\\sigma_1 + \\sigma_0)$, and compare it against the same\nstatistic computed after the preprocessing his methods section describes — clip\nintensities to $[100, 16000]$, then take logs.\n\n::: {#golub50 .cell execution_count=10}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Reconstructing the 1999 predictor\"}\ndef snr(A, lab):\n    d = A[lab == 1].mean(0) - A[lab == 0].mean(0)\n    return d / (A[lab == 1].std(0, ddof=1) + A[lab == 0].std(0, ddof=1) + 1e-12)\n\nraw = G_train.T\nP_raw = snr(raw, golub_y[:38])\nP_log = snr(np.log10(np.clip(raw, 100, 16000)), golub_y[:38])\nfifty = lambda P: set(np.argsort(-P)[:25]) | set(np.argsort(P)[:25])\ng50_raw, g50_log = fifty(P_raw), fifty(P_log)\n\nprint(f\"Golub-50, raw vs his own log10 preprocessing : {len(g50_raw & g50_log)}/50 shared\")\nprint(f\"elastic net set vs Golub-50 (log10)         : \"\n      f\"{len(set(selected) & g50_log)} of 50 genes in common\")\nprint(\"top AML-high probes:\",\n      \", \".join(acc[i] for i in np.argsort(-P_log)[:4]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGolub-50, raw vs his own log10 preprocessing : 32/50 shared\nelastic net set vs Golub-50 (log10)         : 26 of 50 genes in common\ntop AML-high probes: M27891_at, X95735_at, U50136_rna1_at, M23197_at\n```\n:::\n:::\n\n\nGolub's own top 50 moves by 18 genes on a preprocessing choice his paper mentions in\npassing. Against that backdrop the elastic net's overlap of 26 out of 50 is neither a\nfailure to replicate nor a confirmation. It is what two reasonable selection rules\nagree on when the underlying object is this unstable. The gene list is an estimate,\nand estimates have sampling distributions.\n\n## Closing: 34 samples cannot pin down an operating characteristic\n\nThe external cohort did what it was supposed to do. Collected elsewhere, prepared\ndifferently, including a tissue the training set did not, and the locked model still\ngot 33 of 34 right. That is a real result, and Golub's designed split is why it means\nanything at all.\n\nBut 34 is 34.\n\n::: {#closing .cell execution_count=11}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"Intervals, and what happens at a different prevalence\"}\ndef wilson(k, n, z=1.96):\n    c = (k / n + z * z / (2 * n)) / (1 + z * z / n)\n    h = z * np.sqrt(k / n * (1 - k / n) / n + z * z / (4 * n * n)) / (1 + z * z / n)\n    return c - h, c + h\n\nprint(f\"external accuracy 33/34   : 95% CI [{wilson(33, 34)[0]:.3f}, {wilson(33, 34)[1]:.3f}]\")\nprint(f\"nested CV, 35/38          : 95% CI [{wilson(35, 38)[0]:.3f}, {wilson(35, 38)[1]:.3f}]\")\n\nsens, fpr_hi = 13 / 14, beta.ppf(0.975, 1, 20)\nprint(f\"\\nspecificity 20/20, but 95% upper bound on the false-positive rate: {fpr_hi:.3f}\")\nfor prev, where in [(0.35, \"suspected leukemia at referral\"), (0.02, \"a broader haematology clinic\")]:\n    ppv = sens * prev / (sens * prev + fpr_hi * (1 - prev))\n    print(f\"  prevalence {prev:>5.0%} ({where}): PPV could be as low as {ppv:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nexternal accuracy 33/34   : 95% CI [0.851, 0.995]\nnested CV, 35/38          : 95% CI [0.792, 0.973]\n\nspecificity 20/20, but 95% upper bound on the false-positive rate: 0.168\n  prevalence   35% (suspected leukemia at referral): PPV could be as low as 0.75\n  prevalence    2% (a broader haematology clinic): PPV could be as low as 0.10\n```\n:::\n:::\n\n\nThe point estimate of 0.971 carries a 95% interval from 0.851 to 0.995. A model that\ngot 30 of 34 right is not distinguishable from this one on this evidence.\nSpecificity looks perfect at 20 out of 20, but zero errors in twenty observations\nonly bounds the false-positive rate below about 17% — and carrying that bound through\nBayes' rule is where the number stops travelling: predictive value falls from 0.75 at\nthe prevalence of a suspected-leukemia referral to 0.10 at 2%.\n\nWhich returns to the sentence at the top. A signature is supervised, so it is defined\nrelative to a phenotype *and* to the population you drew it from. Accuracy is not a\nproperty of the model; it is a property of the model applied to a population at a\nparticular prevalence. Golub's predictor answers \"which of these two leukemias does\nthis patient have\" for a patient who already has one. Point it at a screening\npopulation and the arithmetic above, not the classifier, decides what it is worth.\n\n## References\n\n**Biology and genomics**\n\n- Golub, T. R. et al. (1999). Molecular classification of cancer: class discovery and class prediction by gene expression monitoring. *Science* 286:531–537.\n- Alizadeh, A. A. et al. (2000). Distinct types of diffuse large B-cell lymphoma identified by gene expression profiling. *Nature* 403:503–511.\n- van 't Veer, L. J. et al. (2002). Gene expression profiling predicts clinical outcome of breast cancer. *Nature* 415:530–536.\n- Subramanian, A. et al. (2005). Gene set enrichment analysis: a knowledge-based approach for interpreting genome-wide expression profiles. *PNAS* 102:15545–15550.\n- Leek, J. T. et al. (2010). Tackling the widespread and critical impact of batch effects in high-throughput data. *Nature Reviews Genetics* 11:733–739.\n- Whalen, S. et al. (2022). Navigating the pitfalls of applying machine learning in genomics. *Nature Reviews Genetics* 23:169–181.\n\n**Statistics and machine learning**\n\n- Tibshirani, R. (1996). Regression shrinkage and selection via the lasso. *JRSS-B* 58:267–288.\n- Benjamini, Y. & Hochberg, Y. (1995). Controlling the false discovery rate: a practical and powerful approach to multiple testing. *JRSS-B* 57:289–300.\n- Zou, H. & Hastie, T. (2005). Regularization and variable selection via the elastic net. *JRSS-B* 67:301–320.\n- Guyon, I., Weston, J., Barnhill, S. & Vapnik, V. (2002). Gene selection for cancer classification using support vector machines. *Machine Learning* 46:389–422.\n- Dudoit, S., Fridlyand, J. & Speed, T. P. (2002). Comparison of discrimination methods for the classification of tumors using gene expression data. *JASA* 97:77–87.\n- Ambroise, C. & McLachlan, G. J. (2002). Selection bias in gene extraction on the basis of microarray gene-expression data. *PNAS* 99:6562–6566.\n- Meinshausen, N. & Bühlmann, P. (2010). Stability selection. *JRSS-B* 72:417–473.\n- Barber, R. F. & Candès, E. J. (2015). Controlling the false discovery rate via knockoffs. *Annals of Statistics* 43:2055–2085.\n- Candès, E., Fan, Y., Janson, L. & Lv, J. (2018). Panning for gold: 'model-X' knockoffs for high-dimensional controlled variable selection. *JRSS-B* 80:551–577.\n- Efron, B. & Hastie, T. (2016). *Computer Age Statistical Inference: Algorithms, Evidence, and Data Science.* Cambridge University Press.\n\n**Data.** The expression matrix is `leukemia_big.csv` from the [CASI data page](https://hastie.su.domains/CASI_files/DATA/leukemia.html). Probe accessions and sample identifiers come from the original Whitehead files, `data_set_ALL_AML_train.csv` and `data_set_ALL_AML_independent.csv`; the URL cited in the 1999 paper is long dead, so this post uses a [mirror](https://github.com/dharsandip/Classification_of_Cancer_by_Gene_Expression_Dataset) of them. Both are cached under `data/` by `src/fetch_data.py`.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}