<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-08-12">

<title>Matrix Factorizations as Optimization Problems: QR, SVD, Eigendecomposition, NMF, and Cholesky – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Matrix Factorizations as Optimization Problems: QR, SVD, Eigendecomposition, NMF, and Cholesky</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Linear Algebra</div>
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Numerical Methods</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 12, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#squaring-the-condition-number-is-the-hidden-cost-of-the-normal-equations" id="toc-squaring-the-condition-number-is-the-hidden-cost-of-the-normal-equations" class="nav-link active" data-scroll-target="#squaring-the-condition-number-is-the-hidden-cost-of-the-normal-equations">Squaring the condition number is the hidden cost of the normal equations</a></li>
  <li><a href="#truncating-the-svd-is-the-only-rank-k-approximation-optimization-cant-beat" id="toc-truncating-the-svd-is-the-only-rank-k-approximation-optimization-cant-beat" class="nav-link" data-scroll-target="#truncating-the-svd-is-the-only-rank-k-approximation-optimization-cant-beat">Truncating the SVD is the only rank-k approximation optimization can’t beat</a></li>
  <li><a href="#the-same-variational-argument-that-optimizes-svd-also-diagonalizes-a-symmetric-matrix" id="toc-the-same-variational-argument-that-optimizes-svd-also-diagonalizes-a-symmetric-matrix" class="nav-link" data-scroll-target="#the-same-variational-argument-that-optimizes-svd-also-diagonalizes-a-symmetric-matrix">The same variational argument that optimizes SVD also diagonalizes a symmetric matrix</a></li>
  <li><a href="#forcing-nonnegativity-trades-optimality-for-interpretability" id="toc-forcing-nonnegativity-trades-optimality-for-interpretability" class="nav-link" data-scroll-target="#forcing-nonnegativity-trades-optimality-for-interpretability">Forcing nonnegativity trades optimality for interpretability</a></li>
  <li><a href="#factor-once-solve-many-times-cholesky-turns-on3-into-on2-per-query" id="toc-factor-once-solve-many-times-cholesky-turns-on3-into-on2-per-query" class="nav-link" data-scroll-target="#factor-once-solve-many-times-cholesky-turns-on3-into-on2-per-query">Factor once, solve many times: Cholesky turns O(n^3) into O(n^2) per query</a></li>
  <li><a href="#an-ec2-fleets-telemetry-is-a-low-rank-signal-plus-a-spike-svd-isolates" id="toc-an-ec2-fleets-telemetry-is-a-low-rank-signal-plus-a-spike-svd-isolates" class="nav-link" data-scroll-target="#an-ec2-fleets-telemetry-is-a-low-rank-signal-plus-a-spike-svd-isolates">An EC2 fleet’s telemetry is a low-rank signal plus a spike SVD isolates</a></li>
  <li><a href="#linkage-disequilibrium-is-collinearity-with-a-biological-name-and-qr-survives-it" id="toc-linkage-disequilibrium-is-collinearity-with-a-biological-name-and-qr-survives-it" class="nav-link" data-scroll-target="#linkage-disequilibrium-is-collinearity-with-a-biological-name-and-qr-survives-it">Linkage disequilibrium is collinearity with a biological name, and QR survives it</a></li>
  <li><a href="#nonnegativity-finds-an-all-only-signature-nobody-labelled" id="toc-nonnegativity-finds-an-all-only-signature-nobody-labelled" class="nav-link" data-scroll-target="#nonnegativity-finds-an-all-only-signature-nobody-labelled">Nonnegativity finds an ALL-only signature nobody labelled</a></li>
  <li><a href="#the-constraint-was-always-the-point" id="toc-the-constraint-was-always-the-point" class="nav-link" data-scroll-target="#the-constraint-was-always-the-point">The constraint was always the point</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/matrix-factorizations/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Matrix Factorizations as Optimization Problems: QR, SVD, Eigendecomposition, NMF, and Cholesky</figcaption>
</figure>
</div>
<p>Linear algebra courses hand you matrix factorizations as a list. Here is QR, here is the SVD, here is Cholesky — each with its own algorithm, its own proof, and no answer to the question a user actually has, which is: given this matrix and this job, which one do I reach for? The list is memorable. The choice is not.</p>
<p>All of them do the same kind of thing. Take a matrix and write it as a product of simpler matrices, where <em>simpler</em> means triangular, or orthogonal, or diagonal, or all-nonnegative — simple enough that whatever you wanted to compute becomes cheap, or numerically safe, or readable by a human. That product is the factorization. What the list format hides is that each one is also the solution to an optimization problem: minimize some error, subject to some constraint. Write the constraint down and the choice stops being arbitrary.</p>
<p>QR is least squares refusing to square its condition number. Truncated SVD is the provably best answer to “compress this matrix.” Eigendecomposition falls out of maximizing variance along one direction instead of building two orthogonal bases. NMF is SVD’s optimum with a sign constraint bolted on. Cholesky is a positive-definite solve that stops re-deriving the inverse every time. Picking a factorization is picking which constraint buys stability, compression, or interpretability.</p>
<p>The rest of this post earns those five claims twice over: first on matrices built to isolate the effect, then on three real datasets — cloud telemetry, a wheat breeding panel, and leukemia biopsies — where choosing wrong has a price. One setup cell serves the lot.</p>
<div id="783f040c" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> io</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.ticker <span class="im">as</span> mticker</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyreadr</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> requests</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> numpy.linalg <span class="im">import</span> cond, eigh, svd</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.linalg <span class="im">import</span> cho_factor, cho_solve, cholesky, qr, solve, solve_triangular</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.decomposition <span class="im">import</span> NMF</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>sns.set_theme(style<span class="op">=</span><span class="st">"whitegrid"</span>, rc<span class="op">=</span>{<span class="st">"axes.edgecolor"</span>: <span class="st">"0.85"</span>})</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>ACCENT <span class="op">=</span> <span class="st">"#4A3AA7"</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>GREY <span class="op">=</span> <span class="st">"#999999"</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="squaring-the-condition-number-is-the-hidden-cost-of-the-normal-equations" class="level2">
<h2 class="anchored" data-anchor-id="squaring-the-condition-number-is-the-hidden-cost-of-the-normal-equations">Squaring the condition number is the hidden cost of the normal equations</h2>
<p>Fitting a line, or a plane, or a hyperplane through a cloud of points is the oldest job in the book. Ordinary least squares picks the coefficients that make the total squared miss as small as possible,</p>
<p><span class="math display">\[\min_\beta \|y-X\beta\|_2^2,\]</span></p>
<p>and calculus hands back a closed form for it, the <em>normal equations</em>:</p>
<p><span class="math display">\[\hat\beta=(X^TX)^{-1}X^Ty.\]</span></p>
<p>That formula is correct, and computing it literally is a bad idea. The reason is conditioning. A matrix’s condition number <span class="math inline">\(\kappa\)</span> measures how much it magnifies error: perturb the input in its last decimal place and the answer moves in a place <span class="math inline">\(\log_{10}\kappa\)</span> digits earlier. Forming <span class="math inline">\(X^TX\)</span> squares that magnifier, because <span class="math inline">\(X^TX\)</span>’s eigenvalues are <span class="math inline">\(X\)</span>’s squared singular values, so</p>
<p><span class="math display">\[\kappa(X^TX)=\kappa(X)^2\]</span></p>
<p>— the whole proof, from the definition of <span class="math inline">\(A^TA\)</span>’s eigenvalues. An ill-conditioned solve then amplifies floating-point error roughly as <span class="math inline">\(\kappa(X)^2\varepsilon\)</span> instead of <span class="math inline">\(\kappa(X)\varepsilon\)</span>, where <span class="math inline">\(\varepsilon\)</span> is machine precision, the gap between <span class="math inline">\(1\)</span> and the next number a <code>float64</code> can represent. Squaring the condition number spends half your significant digits before you have looked at the data.</p>
<p>The fix is to never form <span class="math inline">\(X^TX\)</span> at all. Any matrix with independent columns splits into a part that distorts nothing and a part that carries all the distortion: an <em>orthonormal</em> <span class="math inline">\(Q\)</span>, whose columns are unit-length and mutually perpendicular, so it rotates without stretching and has <span class="math inline">\(\kappa(Q)=1\)</span>; and an upper-triangular <span class="math inline">\(R\)</span> holding everything else. That split is the QR factorization. Substitute <span class="math inline">\(X=QR\)</span>:</p>
<p><span class="math display">\[R^TQ^TQR\beta=R^TQ^Ty.\]</span></p>
<p><span class="math inline">\(Q^TQ=I\)</span> gives</p>
<p><span class="math display">\[R^TR\beta=R^TQ^Ty,\]</span></p>
<p>and since <span class="math inline">\(R^T\)</span> is invertible, both sides cancel it, leaving</p>
<p><span class="math display">\[R\beta=Q^Ty.\]</span></p>
<p>Back-substitution solves this in <span class="math inline">\(O(n^2)\)</span>, conditioned on <span class="math inline">\(\kappa(X)\)</span> — never <span class="math inline">\(\kappa(X)^2\)</span> — because <span class="math inline">\(X^TX\)</span> is never formed.</p>
<p>Seeing the difference needs a matrix whose condition number you already know, so the demo below builds one instead of borrowing one. It draws two random orthonormal bases, imposes singular values decaying geometrically from <span class="math inline">\(1\)</span> down to <span class="math inline">\(10^{-6}\)</span>, and multiplies them back together, which pins <span class="math inline">\(\kappa(X)\)</span> at exactly <span class="math inline">\(10^6\)</span>. Real design matrices get ill-conditioned the same way — two sensors reporting nearly the same thing, two genetic markers inherited together — but their conditioning is whatever the data happened to hand you, which is no good for a controlled comparison. The response <span class="math inline">\(y\)</span> is generated noiselessly from a known <span class="math inline">\(\beta\)</span>, so every digit of error below is floating point and nothing else.</p>
<div id="432830ba" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Build X with a controlled condition number instead of a raw high-degree</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Vandermonde basis, whose columns are so nearly dependent that beta itself</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># becomes ill-posed, not just numerically delicate -- singular values decaying</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># geometrically isolate the conditioning effect the derivation is about.</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>n, p <span class="op">=</span> <span class="dv">200</span>, <span class="dv">12</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>U0, _ <span class="op">=</span> np.linalg.qr(rng.normal(size<span class="op">=</span>(n, p)))</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>V0, _ <span class="op">=</span> np.linalg.qr(rng.normal(size<span class="op">=</span>(p, p)))</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>singvals <span class="op">=</span> np.logspace(<span class="dv">0</span>, <span class="op">-</span><span class="dv">6</span>, p)  <span class="co"># cond(X) ~ 1e6, cond(X.T @ X) ~ 1e12</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> (U0 <span class="op">*</span> singvals) <span class="op">@</span> V0.T</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>beta_true <span class="op">=</span> rng.normal(size<span class="op">=</span>p)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> X <span class="op">@</span> beta_true  <span class="co"># noiseless: recovery error below is pure floating-point conditioning</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cond(X)     = </span><span class="sc">{</span>cond(X)<span class="sc">:.3e}</span><span class="ss">"</span>)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cond(X.T@X) = </span><span class="sc">{</span>cond(X.T <span class="op">@</span> X)<span class="sc">:.3e}</span><span class="ss">"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>beta_normal <span class="op">=</span> solve(X.T <span class="op">@</span> X, X.T <span class="op">@</span> y)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>Q, R <span class="op">=</span> qr(X, mode<span class="op">=</span><span class="st">"economic"</span>)</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>beta_qr <span class="op">=</span> solve_triangular(R, Q.T <span class="op">@</span> y)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||beta_normal - beta_true|| = </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(beta_normal <span class="op">-</span> beta_true)<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||beta_qr - beta_true||     = </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(beta_qr <span class="op">-</span> beta_true)<span class="sc">:.2e}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>cond(X)     = 1.000e+06
cond(X.T@X) = 1.000e+12
||beta_normal - beta_true|| = 2.70e-05
||beta_qr - beta_true||     = 5.63e-12</code></pre>
</div>
</div>
<p>Both solves see identical data. The normal equations recover <span class="math inline">\(\beta\)</span> to about five decimal places; QR gets eleven — close to seven orders of magnitude of accuracy, bought by declining to square anything.</p>
</section>
<section id="truncating-the-svd-is-the-only-rank-k-approximation-optimization-cant-beat" class="level2">
<h2 class="anchored" data-anchor-id="truncating-the-svd-is-the-only-rank-k-approximation-optimization-cant-beat">Truncating the SVD is the only rank-k approximation optimization can’t beat</h2>
<p>Stability was the first thing a constraint could buy. Compression is the second, and there the guarantee is stronger than “works well in practice.”</p>
<p>Start with the shape of the problem. You have a matrix and you want a smaller stand-in for it — one that stores <span class="math inline">\(k\)</span> patterns instead of the full grid, because storage is finite or because the patterns are the thing you were after. <em>Rank</em> is the count of genuinely independent patterns a matrix contains, so “smaller stand-in” formally means: among all matrices of rank at most <span class="math inline">\(k\)</span>, find the one closest to <span class="math inline">\(A\)</span>. Closest in the Frobenius norm, which is just the square root of the sum of every squared entry — the ordinary Euclidean distance, applied to a matrix flattened out.</p>
<p>The singular value decomposition answers that, and does not merely answer it well. It writes</p>
<p><span class="math display">\[A=U\Sigma V^T,\]</span></p>
<p>with <span class="math inline">\(U\)</span> and <span class="math inline">\(V\)</span> orthonormal and <span class="math inline">\(\Sigma\)</span> diagonal, its entries the singular values <span class="math inline">\(\sigma_1\ge\sigma_2\ge\dots\)</span> ranked by how much of <span class="math inline">\(A\)</span> each pattern accounts for. Keep the top <span class="math inline">\(k\)</span> and throw the rest away, and the Eckart-Young-Mirsky theorem says nothing else of that rank can do better. For any <span class="math inline">\(B\)</span> with rank<span class="math inline">\((B)\le k\)</span>, it bounds the error:</p>
<p><span class="math display">\[\|A-B\|_F \ge \sqrt{\sum_{i&gt;k}\sigma_i^2},\]</span></p>
<p>with equality exactly at the truncation</p>
<p><span class="math display">\[A_k=\sum_{i\le k}\sigma_i u_i v_i^T.\]</span></p>
<p>The proof runs through the Courant-Fischer min-max theorem, which pins each singular value down as the best a subspace of a given dimension can do. Any rank-<span class="math inline">\(k\)</span> <span class="math inline">\(B\)</span> collapses some <span class="math inline">\((n-k)\)</span>-dimensional subspace to zero, and that alone lower-bounds its residual by the discarded singular values, no matter how cleverly <span class="math inline">\(B\)</span> was chosen. This is a claim about <em>every</em> rank-<span class="math inline">\(k\)</span> matrix, not just about rival factorizations — nothing beats truncated SVD on Frobenius error at a given rank.</p>
<p>Which makes the check below arithmetic rather than evidence. Truncate a random <span class="math inline">\(60\times40\)</span> matrix at <span class="math inline">\(k=10\)</span> and the residual should not merely be small; it should equal the tail bound to the last printed digit.</p>
<div id="ef5a2ca2" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> rng.normal(size<span class="op">=</span>(<span class="dv">60</span>, <span class="dv">40</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>U, s, Vt <span class="op">=</span> svd(A, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>A_k <span class="op">=</span> (U[:, :k] <span class="op">*</span> s[:k]) <span class="op">@</span> Vt[:k]</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>residual_frobenius <span class="op">=</span> np.linalg.norm(A <span class="op">-</span> A_k, <span class="st">"fro"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>tail_bound <span class="op">=</span> np.sqrt(np.<span class="bu">sum</span>(s[k:] <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||A - A_k||_F    = </span><span class="sc">{</span>residual_frobenius<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sqrt(sum tail^2) = </span><span class="sc">{</span>tail_bound<span class="sc">:.6f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>||A - A_k||_F    = 32.942888
sqrt(sum tail^2) = 32.942888</code></pre>
</div>
</div>
<p>It does: both print <code>32.942888</code>. The bound is attained, which is the content of the theorem.</p>
</section>
<section id="the-same-variational-argument-that-optimizes-svd-also-diagonalizes-a-symmetric-matrix" class="level2">
<h2 class="anchored" data-anchor-id="the-same-variational-argument-that-optimizes-svd-also-diagonalizes-a-symmetric-matrix">The same variational argument that optimizes SVD also diagonalizes a symmetric matrix</h2>
<p>That last proof leaned on a subspace argument, and the argument is more general than the theorem it just proved. Apply it to one symmetric matrix instead of two orthogonal bases and eigendecomposition falls out of it — which is worth doing explicitly, because it explains why principal components and singular values keep turning out to be the same numbers.</p>
<p>Here the question is not “compress this” but “which single direction does this matrix stretch the most?” Maximize the projected variance <span class="math inline">\(v^TAv\)</span>, subject to <span class="math inline">\(v\)</span> having unit length so the answer cannot be made large by simply making <span class="math inline">\(v\)</span> large:</p>
<p><span class="math display">\[\max_{\|v\|=1} v^TAv.\]</span></p>
<p>The standard tool for optimizing under a constraint is a Lagrangian: fold the constraint into the objective with a multiplier <span class="math inline">\(\lambda\)</span>, and an unconstrained stationary point of the combination is a constrained one of the original. Here that gives</p>
<p><span class="math display">\[\mathcal L(v,\lambda)=v^TAv-\lambda(v^Tv-1),\]</span></p>
<p>with stationarity condition</p>
<p><span class="math display">\[\nabla_v\mathcal L=2Av-2\lambda v=0 \implies Av=\lambda v\]</span></p>
<p>— so the eigenvectors are precisely the stationary points of the ratio <span class="math inline">\(v^TAv/v^Tv\)</span>, known as the Rayleigh quotient, and the eigenvalues are the values it takes there. The full decomposition <span class="math inline">\(A=Q\Lambda Q^T\)</span> falls out by repeating the maximization on whatever directions are left perpendicular to the ones already found.</p>
<p>That derivation has a practical edge, and it is the QR lesson wearing different clothes. A covariance matrix is <span class="math inline">\(\Sigma=X_c^TX_c\)</span> for centered data <span class="math inline">\(X_c\)</span>, so eigendecomposing a covariance matrix <em>is</em> forming <span class="math inline">\(X^TX\)</span>, with the squared conditioning that implies. The eigenvalues of <span class="math inline">\(\Sigma\)</span> are the squared singular values of <span class="math inline">\(X_c\)</span> — same numbers — so taking the SVD of <span class="math inline">\(X_c\)</span> directly gets you there at the original condition number. Below, both routes on the same ill-conditioned <span class="math inline">\(X\)</span> from earlier, with the two condition numbers printed side by side.</p>
<div id="b9b616ff" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>Xc <span class="op">=</span> X <span class="op">-</span> X.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>Sigma <span class="op">=</span> Xc.T <span class="op">@</span> Xc</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>eigvals, eigvecs <span class="op">=</span> eigh(Sigma)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>_, s_centered, _ <span class="op">=</span> svd(Xc, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"top eigenvalues:          </span><span class="sc">{</span>np<span class="sc">.</span>sort(eigvals)[::<span class="op">-</span><span class="dv">1</span>][:<span class="dv">4</span>]<span class="sc">.</span><span class="bu">round</span>(<span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"top squared singular vals: </span><span class="sc">{</span>(s_centered[:<span class="dv">4</span>] <span class="op">**</span> <span class="dv">2</span>)<span class="sc">.</span><span class="bu">round</span>(<span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cond(Sigma) = </span><span class="sc">{</span>cond(Sigma)<span class="sc">:.3e}</span><span class="ss">   cond(Xc) = </span><span class="sc">{</span>cond(Xc)<span class="sc">:.3e}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>top eigenvalues:          [0.989 0.08  0.007 0.001]
top squared singular vals: [0.989 0.08  0.007 0.001]
cond(Sigma) = 9.911e+11   cond(Xc) = 9.955e+05</code></pre>
</div>
</div>
<p>The two lists of numbers match to every printed digit, as the algebra says they must. The two condition numbers do not: <span class="math inline">\(9.9\times10^{11}\)</span> for the covariance route against <span class="math inline">\(9.96\times10^{5}\)</span> for the SVD route. Six orders of magnitude of numerical headroom, given away for an answer that was identical anyway.</p>
</section>
<section id="forcing-nonnegativity-trades-optimality-for-interpretability" class="level2">
<h2 class="anchored" data-anchor-id="forcing-nonnegativity-trades-optimality-for-interpretability">Forcing nonnegativity trades optimality for interpretability</h2>
<p>Stability and optimality are properties of the numbers. Interpretability is a property of the person reading them, and it is the one thing none of the three factorizations so far will give you.</p>
<p>The obstacle is signs. SVD’s optimum is free to use negative entries, so its components routinely cancel — a factor can subtract as much signal as it adds, and a “pattern” that is partly a subtraction from another pattern is a poor model of anything you would call a part. Insist instead that every entry of both factors be zero or positive and cancellation becomes impossible: each factor can only add, so the pieces are forced to behave like parts that stack into a whole. That constraint, imposed on the same objective, is nonnegative matrix factorization — NMF:</p>
<p><span class="math display">\[\min_{W,H\ge0} \|V-WH\|_F^2.\]</span></p>
<p>Lee and Seung’s multiplicative update rescales gradient descent so nonnegativity holds automatically:</p>
<p><span class="math display">\[H \leftarrow H \odot \frac{W^TV}{W^TWH}, \qquad W \leftarrow W \odot \frac{VH^T}{WHH^T},\]</span></p>
<p>and it provably decreases the objective at every step. The bill for the constraint arrives here. The problem is only biconvex — convex in <span class="math inline">\(W\)</span> with <span class="math inline">\(H\)</span> held fixed, convex in <span class="math inline">\(H\)</span> with <span class="math inline">\(W\)</span> held fixed, not convex in both at once — so the updates converge to <em>a</em> stationary point rather than the global one, and which one depends on where they started. The <code>nndsvda</code> initialization used below seeds <span class="math inline">\(W\)</span> and <span class="math inline">\(H\)</span> from the SVD, which makes the answer deterministic. Deterministic is not the same as optimal.</p>
<p>The cell below is a sanity check, not an application. It factors a <span class="math inline">\(50\times30\)</span> matrix of gamma-distributed random draws — gamma variates are nonnegative by construction, which makes them a stand-in for the counts and intensities NMF is normally pointed at, such as word counts in documents or probe intensities on a microarray. All it establishes is that the machinery runs and the factors come back nonnegative; the real test is on leukemia biopsies, further down.</p>
<div id="e735ebe9" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>V_demo <span class="op">=</span> rng.gamma(shape<span class="op">=</span><span class="fl">2.0</span>, scale<span class="op">=</span><span class="fl">1.0</span>, size<span class="op">=</span>(<span class="dv">50</span>, <span class="dv">30</span>))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>demo_model <span class="op">=</span> NMF(n_components<span class="op">=</span><span class="dv">5</span>, init<span class="op">=</span><span class="st">"nndsvda"</span>, max_iter<span class="op">=</span><span class="dv">500</span>, random_state<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>W_demo <span class="op">=</span> demo_model.fit_transform(V_demo)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>H_demo <span class="op">=</span> demo_model.components_</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"reconstruction error = </span><span class="sc">{</span>demo_model<span class="sc">.</span>reconstruction_err_<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"W, H nonnegative: </span><span class="sc">{</span>(W_demo <span class="op">&gt;=</span> <span class="dv">0</span>)<span class="sc">.</span><span class="bu">all</span>()<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>(H_demo <span class="op">&gt;=</span> <span class="dv">0</span>)<span class="sc">.</span><span class="bu">all</span>()<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>reconstruction error = 41.9530
W, H nonnegative: True, True</code></pre>
</div>
</div>
</section>
<section id="factor-once-solve-many-times-cholesky-turns-on3-into-on2-per-query" class="level2">
<h2 class="anchored" data-anchor-id="factor-once-solve-many-times-cholesky-turns-on3-into-on2-per-query">Factor once, solve many times: Cholesky turns O(n^3) into O(n^2) per query</h2>
<p>NMF bought readability with a constraint on the factors. The last factorization buys speed with a constraint on the input, and it is the one case here where the constraint is a precondition rather than a preference.</p>
<p>The situation it answers is a solve you have to repeat. Covariance matrices in a Kalman filter, Gram matrices in a kernel method, the Hessian inside a Newton step: the same matrix <span class="math inline">\(A\)</span> meets a fresh right-hand side every iteration, and solving from scratch costs <span class="math inline">\(O(n^3)\)</span> every time. When <span class="math inline">\(A\)</span> is symmetric and every eigenvalue of it is positive — equivalently <span class="math inline">\(x^TAx&gt;0\)</span> for every nonzero <span class="math inline">\(x\)</span>, the property called <em>symmetric positive definite</em>, SPD — the matrix has something close to a square root. A single lower-triangular <span class="math inline">\(L\)</span> satisfies</p>
<p><span class="math display">\[A=LL^T\]</span></p>
<p>with positive diagonal, and it exists exactly when <span class="math inline">\(A\)</span> is SPD, which is why the condition is not a technicality to check off. That factorization is Cholesky.</p>
<p>Finding <span class="math inline">\(L\)</span> costs <span class="math inline">\(O(n^3/3)\)</span> — half the work of general-purpose LU elimination, because symmetry means the algorithm only ever touches one triangle. Every solve after that is two triangular substitutions at <span class="math inline">\(O(n^2)\)</span>. For <span class="math inline">\(m\)</span> right-hand sides sharing one <span class="math inline">\(A\)</span>, the total is</p>
<p><span class="math display">\[O(n^3+mn^2).\]</span></p>
<p>Forming <span class="math inline">\(A^{-1}\)</span> explicitly and multiplying has the same asymptotic look and worse constants and worse conditioning, which is the reason for the standing advice never to invert a matrix in order to solve with it. The benchmark below is that advice made checkable: the same SPD system and the same five right-hand sides, factored once versus inverted once, across growing <span class="math inline">\(n\)</span>.</p>
<p><span class="math inline">\(L\)</span> also does a second job that has nothing to do with solving. Draw a vector <span class="math inline">\(z\)</span> of independent standard normals and form <span class="math inline">\(x=Lz\)</span>; then</p>
<p><span class="math display">\[x=Lz, \quad z\sim\mathcal N(0,I) \implies x\sim\mathcal N(0,\Sigma),\]</span></p>
<p>so the triangular factor of a covariance matrix is the machine that turns uncorrelated noise into noise with exactly that covariance. Cholesky is the sampling mechanism, not just the solver — a fact the wheat section puts to work.</p>
<div id="87203a04" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>sizes <span class="op">=</span> [<span class="dv">50</span>, <span class="dv">100</span>, <span class="dv">200</span>, <span class="dv">400</span>, <span class="dv">800</span>]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>factor_times, inv_times <span class="op">=</span> [], []</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> size <span class="kw">in</span> sizes:</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    Rm <span class="op">=</span> rng.normal(size<span class="op">=</span>(size, size))</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    Am <span class="op">=</span> Rm <span class="op">@</span> Rm.T <span class="op">+</span> size <span class="op">*</span> np.eye(size)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    Bm <span class="op">=</span> rng.normal(size<span class="op">=</span>(size, <span class="dv">5</span>))</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    t0 <span class="op">=</span> time.perf_counter()</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    c, low <span class="op">=</span> cho_factor(Am)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    cho_solve((c, low), Bm)</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    factor_times.append(time.perf_counter() <span class="op">-</span> t0)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>    t0 <span class="op">=</span> time.perf_counter()</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    np.linalg.inv(Am) <span class="op">@</span> Bm</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    inv_times.append(time.perf_counter() <span class="op">-</span> t0)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">4</span>))</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>ax.loglog(sizes, factor_times, <span class="st">"o-"</span>, color<span class="op">=</span>ACCENT, label<span class="op">=</span><span class="st">"cho_factor + cho_solve"</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>ax.loglog(sizes, inv_times, <span class="st">"o-"</span>, color<span class="op">=</span>GREY, label<span class="op">=</span><span class="st">"explicit inverse"</span>)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_locator(mticker.FixedLocator(sizes))</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_major_formatter(mticker.FixedFormatter([<span class="bu">str</span>(s) <span class="cf">for</span> s <span class="kw">in</span> sizes]))</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_minor_locator(mticker.NullLocator())</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"matrix size n"</span>)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"wall-clock seconds"</span>)</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Factor once, solve many: Cholesky vs. explicit inverse"</span>)</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>ax.legend()</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-7-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="an-ec2-fleets-telemetry-is-a-low-rank-signal-plus-a-spike-svd-isolates" class="level2">
<h2 class="anchored" data-anchor-id="an-ec2-fleets-telemetry-is-a-low-rank-signal-plus-a-spike-svd-isolates">An EC2 fleet’s telemetry is a low-rank signal plus a spike SVD isolates</h2>
<p>Five constraints, five factorizations, every one demonstrated on a matrix built to make the demonstration clean. The rest of the post spends them on data somebody actually went out and collected — starting with the case where compression is not a convenience but the entire product.</p>
<p>A team running a fleet of cloud servers cannot watch every machine’s dashboard. What they want is a handful of numbers: few enough to look at, sensitive enough to catch a real incident, quiet enough not to wake the on-call engineer over noise. That is the compression-versus-vigilance tradeoff, and stated in matrix terms it is a low-rank approximation problem.</p>
<p>The data is the <a href="https://github.com/numenta/NAB">Numenta Anomaly Benchmark</a>, or NAB, assembled by the machine-intelligence company Numenta to score anomaly detectors against real streaming metrics instead of synthetic ones — injected anomalies are easier than the real article and flatter whatever detector is being sold. Its <code>realAWSCloudwatch</code> category holds CPU utilization recorded by AmazonCloudwatch, Amazon’s monitoring service, from eight production EC2 instances, EC2 being Amazon’s rented virtual servers. Every anomaly timestamp in it was flagged by a person reading the trace rather than generated to order. Eight instances, not thousands, which is worth saying plainly: any claim about fleet-wide structure below rests on eight columns.</p>
<p>The question asked of it here is the operational one, unmodified. Stack the eight traces as columns, keep the top few components as the fleet’s shared behaviour, and treat whatever refuses to fit as the anomaly score. Both kinds of error cost something real: a missed spike is an outage nobody got paged for, and a false one wakes an engineer for nothing, which is how alerting gets muted and then stops working at all. SVD is the right instrument for <em>this</em> data because eight machines in one fleet are not independent — they share load, deploys, and time-of-day traffic — so the matrix genuinely is close to low-rank, and Eckart-Young-Mirsky guarantees the truncation throws away as little as any rank-<span class="math inline">\(k\)</span> summary could.</p>
<p><em>(This section and the two after it fetch data live at render time, so a future re-render depends on those repositories staying up — though a project-wide render never re-executes this page once frozen.)</em></p>
<div id="23a5ce2a" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>base <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/numenta/NAB/master"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ec2_ids <span class="op">=</span> [<span class="st">"53ea38"</span>, <span class="st">"24ae8d"</span>, <span class="st">"5f5533"</span>, <span class="st">"77c1ca"</span>, <span class="st">"825cc2"</span>, <span class="st">"ac20cd"</span>, <span class="st">"c6585a"</span>, <span class="st">"fe7f93"</span>]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> requests.get(<span class="ss">f"</span><span class="sc">{</span>base<span class="sc">}</span><span class="ss">/labels/combined_labels.json"</span>, timeout<span class="op">=</span><span class="dv">30</span>).json()</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>columns, anomaly_idx <span class="op">=</span> {}, {}</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> id_ <span class="kw">in</span> ec2_ids:</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    key <span class="op">=</span> <span class="ss">f"realAWSCloudwatch/ec2_cpu_utilization_</span><span class="sc">{</span>id_<span class="sc">}</span><span class="ss">.csv"</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.read_csv(io.StringIO(requests.get(<span class="ss">f"</span><span class="sc">{</span>base<span class="sc">}</span><span class="ss">/data/</span><span class="sc">{</span>key<span class="sc">}</span><span class="ss">"</span>, timeout<span class="op">=</span><span class="dv">30</span>).text))</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">"timestamp"</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">"timestamp"</span>])</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    columns[id_] <span class="op">=</span> df[<span class="st">"value"</span>].to_numpy()</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    label_times <span class="op">=</span> pd.to_datetime(labels.get(key, []))</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    anomaly_idx[id_] <span class="op">=</span> df.index[df[<span class="st">"timestamp"</span>].isin(label_times)].to_numpy()</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># stacked by position, not wall-clock: fleet-wide regime structure, not calendar sync</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>telemetry <span class="op">=</span> pd.DataFrame(columns)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"real telemetry matrix: </span><span class="sc">{</span>telemetry<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> timesteps x </span><span class="sc">{</span>telemetry<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> real EC2 instances"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>real telemetry matrix: 4032 timesteps x 8 real EC2 instances</code></pre>
</div>
</div>
<p>Take the SVD of that matrix and plot the singular values in descending order. What comes out is a scree plot — named after the slope of loose rubble at the foot of a cliff, because that is its shape: a steep drop, then a long flat tail. The elbow between the two is the count of components carrying genuine shared structure, and here it arrives after a handful.</p>
<div id="3c464275" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>X_tel <span class="op">=</span> telemetry.to_numpy()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>Xc_tel <span class="op">=</span> X_tel <span class="op">-</span> X_tel.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>U_tel, s_tel, Vt_tel <span class="op">=</span> svd(Xc_tel, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">4</span>))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>ax.semilogy(np.arange(<span class="dv">1</span>, <span class="bu">len</span>(s_tel) <span class="op">+</span> <span class="dv">1</span>), s_tel, <span class="st">"o-"</span>, color<span class="op">=</span>ACCENT)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"component"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"singular value (log scale)"</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Singular values of 8 real EC2 CPU-utilization traces"</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Each of those components has a left singular vector attached: one value per timestep, saying how strongly that pattern was switched on at that moment. Laid out as rows, the top five read as the fleet’s regimes over the four thousand timesteps — the stretches where every machine was busy together and the stretches where none of them were.</p>
<div id="008ca740" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="fl">2.8</span>))</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>sns.heatmap(U_tel[:, :<span class="dv">5</span>].T, cmap<span class="op">=</span><span class="st">"RdBu_r"</span>, center<span class="op">=</span><span class="dv">0</span>, cbar_kws<span class="op">=</span>{<span class="st">"label"</span>: <span class="st">"loading"</span>}, ax<span class="op">=</span>ax)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"timestep"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"left singular vector"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Top 5 temporal regime vectors across the real fleet"</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-10-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Rebuild the matrix from the top four components and subtract it from the original. What survives is everything the fleet’s shared behaviour cannot account for, and that leftover is not merely busy-looking near the labelled anomalies — it <em>is</em> the anomaly score. The dashed lines below are the human-flagged timestamps, which makes the plot a check rather than an illustration.</p>
<div id="9490de00" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>k_tel <span class="op">=</span> <span class="dv">4</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>X_k_tel <span class="op">=</span> (U_tel[:, :k_tel] <span class="op">*</span> s_tel[:k_tel]) <span class="op">@</span> Vt_tel[:k_tel]</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>residual <span class="op">=</span> np.<span class="bu">abs</span>(Xc_tel <span class="op">-</span> X_k_tel)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> <span class="st">"fe7f93"</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>j <span class="op">=</span> ec2_ids.index(target)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">4</span>))</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>ax.plot(residual[:, j], color<span class="op">=</span>ACCENT, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> idx <span class="kw">in</span> anomaly_idx[target]:</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>    ax.axvline(idx, color<span class="op">=</span><span class="st">"crimson"</span>, ls<span class="op">=</span><span class="st">"--"</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="ss">f"Rank-</span><span class="sc">{</span>k_tel<span class="sc">}</span><span class="ss"> residual, instance </span><span class="sc">{</span>target<span class="sc">}</span><span class="ss"> (dashed = real labeled anomaly)"</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"timestep"</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"|residual|"</span>)</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>So the top singular vectors become a few regime scores an autoscaler can react to in place of eight raw series, and the leftover energy after truncation — checked here against labels a person wrote down — is the quantity alerting pipelines page on. That is Eckart-Young-Mirsky cashed in: the guarantee is what lets you claim the discarded part is signal rather than a bad choice of basis.</p>
<p>Compression worked here because the eight columns were genuinely redundant. The next dataset is redundant in a different way, and severely enough to break the normal equations outright.</p>
</section>
<section id="linkage-disequilibrium-is-collinearity-with-a-biological-name-and-qr-survives-it" class="level2">
<h2 class="anchored" data-anchor-id="linkage-disequilibrium-is-collinearity-with-a-biological-name-and-qr-survives-it">Linkage disequilibrium is collinearity with a biological name, and QR survives it</h2>
<p>Redundant columns in the telemetry matrix came from machines sharing traffic. In a genome they come from inheritance. Stretches of chromosome travel down the generations as blocks, so two markers sitting close together are almost never separated, and their columns in a genotype matrix end up near-copies of each other. Geneticists call that non-independence <em>linkage disequilibrium</em>. A numerical analyst looking at the same matrix would call it collinear and expect exactly the trouble collinearity always causes.</p>
<p>Here the trouble costs a year. A wheat breeding program can genotype far more candidate lines than it can afford to plant out and measure, and advancing the wrong ones burns a growing season that no budget will speed up. Genomic selection is the practice of ranking candidates from their marker profiles alone, before a seed goes in the ground, in order not to spend that season on lines that were never going to win.</p>
<p>The data comes from CIMMYT — the International Maize and Wheat Improvement Center, the public research body whose wheat breeding underwrote the Green Revolution. Its Global Wheat Program genotyped 599 breeding lines at 1279 DArT markers (Diversity Arrays Technology: a hybridisation assay that reports each marker as present or absent, a 0 or a 1, rather than reading out the underlying base) and recorded grain yield for every line across four field environments. It is distributed for reuse as the <code>wheat</code> dataset in the <a href="https://github.com/gdlc/BGLR-R">BGLR</a> R package, a genomic-prediction toolkit, which is where the cell below fetches it from.</p>
<p>Two features of that matrix make it the right stress test for QR. There are more markers than lines, <span class="math inline">\(p=1279\)</span> against <span class="math inline">\(n=599\)</span>, so <span class="math inline">\(X^TX\)</span> is singular before conditioning is even the question. And the markers are linkage-correlated with one another, so any subset large enough to predict with is also badly conditioned. This is where the squaring from the opening section stops being a demonstration and starts being a limit on how many markers you are permitted to use.</p>
<div id="15ee96a9" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>resp <span class="op">=</span> requests.get(<span class="st">"https://raw.githubusercontent.com/gdlc/BGLR-R/master/data/wheat.RData"</span>, timeout<span class="op">=</span><span class="dv">60</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="cf">with</span> <span class="bu">open</span>(<span class="st">"/tmp/wheat.RData"</span>, <span class="st">"wb"</span>) <span class="im">as</span> f:</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    f.write(resp.content)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>wheat <span class="op">=</span> pyreadr.read_r(<span class="st">"/tmp/wheat.RData"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>X_markers <span class="op">=</span> wheat[<span class="st">"wheat.X"</span>].to_numpy()</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>grain_yield <span class="op">=</span> wheat[<span class="st">"wheat.Y"</span>].iloc[:, <span class="dv">0</span>].to_numpy()  <span class="co"># real yield, environment 1</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"real markers: </span><span class="sc">{</span>X_markers<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> wheat lines x </span><span class="sc">{</span>X_markers<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> real DArT markers"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>real markers: 599 wheat lines x 1279 real DArT markers</code></pre>
</div>
</div>
<p>So the sweep below never uses all 1279 at once. It ranks markers by variance, takes the top <span class="math inline">\(p\)</span> for a growing <span class="math inline">\(p\)</span>, fits plain least squares by QR on 450 training lines, and scores the fit by correlating predicted against observed yield on the 149 lines held out. Two things move as <span class="math inline">\(p\)</span> climbs toward <span class="math inline">\(n\)</span>, and they are worth watching separately.</p>
<div id="8d5f7bb6" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>marker_var <span class="op">=</span> X_markers.var(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>ranked_markers <span class="op">=</span> np.argsort(marker_var)[::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>n_lines <span class="op">=</span> X_markers.shape[<span class="dv">0</span>]</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>perm <span class="op">=</span> rng.permutation(n_lines)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>train_idx, test_idx <span class="op">=</span> perm[:<span class="dv">450</span>], perm[<span class="dv">450</span>:]</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>y_train, y_test <span class="op">=</span> grain_yield[train_idx], grain_yield[test_idx]</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>marker_counts <span class="op">=</span> [<span class="dv">50</span>, <span class="dv">150</span>, <span class="dv">250</span>, <span class="dv">350</span>, <span class="dv">400</span>, <span class="dv">430</span>, <span class="dv">449</span>]</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>corr_qr, cond_x, cond_xtx <span class="op">=</span> [], [], []</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> p_count <span class="kw">in</span> marker_counts:</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    Xp <span class="op">=</span> X_markers[:, ranked_markers[:p_count]].astype(<span class="bu">float</span>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    Xp <span class="op">-=</span> Xp.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>    X_train, X_test <span class="op">=</span> Xp[train_idx], Xp[test_idx]</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>    Q_tr, R_tr <span class="op">=</span> qr(X_train, mode<span class="op">=</span><span class="st">"economic"</span>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>    beta_qr <span class="op">=</span> solve_triangular(R_tr, Q_tr.T <span class="op">@</span> y_train)</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    corr_qr.append(np.corrcoef(X_test <span class="op">@</span> beta_qr, y_test)[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>    cond_x.append(cond(X_train))</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    cond_xtx.append(cond(X_train.T <span class="op">@</span> X_train))</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"markers:      "</span>, marker_counts)</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"held-out corr:"</span>, [<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:.3f}</span><span class="ss">"</span> <span class="cf">for</span> c <span class="kw">in</span> corr_qr])</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"cond(X):      "</span>, [<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:.2e}</span><span class="ss">"</span> <span class="cf">for</span> c <span class="kw">in</span> cond_x])</span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"cond(X.T@X):  "</span>, [<span class="ss">f"</span><span class="sc">{</span>c<span class="sc">:.2e}</span><span class="ss">"</span> <span class="cf">for</span> c <span class="kw">in</span> cond_xtx])</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>X_sub <span class="op">=</span> X_markers[:, ranked_markers[:<span class="dv">350</span>]].astype(<span class="bu">float</span>)</span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>X_sub <span class="op">-=</span> X_sub.mean(axis<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>markers:       [50, 150, 250, 350, 400, 430, 449]
held-out corr: ['0.200', '0.267', '0.181', '0.090', '0.106', '0.114', '0.050']
cond(X):       ['2.28e+01', '8.56e+01', '2.37e+02', '5.25e+02', '1.13e+03', '2.21e+03', '1.89e+04']
cond(X.T@X):   ['5.19e+02', '7.33e+03', '5.62e+04', '2.75e+05', '1.27e+06', '4.88e+06', '3.57e+08']</code></pre>
</div>
</div>
<p>Three panels make those numbers legible. The first is <span class="math inline">\(R\)</span> itself for a 20-marker slice — the triangular factor QR produces, with the strictly-lower half empty by construction. The second is held-out accuracy against marker count. The third is the two condition numbers on a log scale, with a dashed line marking where <code>float64</code> gives out.</p>
<div id="138dd2ec" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">4</span>))</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>Q20, R20 <span class="op">=</span> qr(X_sub[:, :<span class="dv">20</span>], mode<span class="op">=</span><span class="st">"economic"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>sns.heatmap(np.triu(R20), cmap<span class="op">=</span><span class="st">"RdBu_r"</span>, center<span class="op">=</span><span class="dv">0</span>, ax<span class="op">=</span>axes[<span class="dv">0</span>], cbar_kws<span class="op">=</span>{<span class="st">"label"</span>: <span class="st">"R value"</span>})</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Upper-triangular R</span><span class="ch">\n</span><span class="st">(20 real markers)"</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(marker_counts, corr_qr, <span class="st">"o-"</span>, color<span class="op">=</span>ACCENT)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].axhline(<span class="dv">0</span>, color<span class="op">=</span>GREY, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"markers used (of 450 training lines)"</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"held-out yield correlation"</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Plain OLS overfits as p -&gt; n"</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].semilogy(marker_counts, cond_x, <span class="st">"o-"</span>, color<span class="op">=</span>ACCENT, label<span class="op">=</span><span class="st">"cond(X)"</span>)</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].semilogy(marker_counts, cond_xtx, <span class="st">"o-"</span>, color<span class="op">=</span>GREY, label<span class="op">=</span><span class="st">"cond(X'X)"</span>)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].axhline(<span class="dv">1</span> <span class="op">/</span> np.finfo(<span class="bu">float</span>).eps, color<span class="op">=</span><span class="st">"crimson"</span>, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="dv">1</span>, label<span class="op">=</span><span class="st">"float64 ceiling"</span>)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_xlabel(<span class="st">"markers used"</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylabel(<span class="st">"condition number"</span>)</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"Normal eqs burns precision twice as fast"</span>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].legend(fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Held-out correlation peaks early — 0.27 at 150 markers — then falls away, unevenly but unmistakably, to 0.05 once 449 markers are competing for 450 training lines. That is overfitting doing exactly what it does, and it is why genomic selection never runs plain least squares at genome-wide marker density.</p>
<p>Conditioning is the second effect, and the plot shows the squaring rather than asserting it. Both curves climb by orders of magnitude as <span class="math inline">\(p\to n\)</span>: <span class="math inline">\(\kappa(X)\)</span> from about <span class="math inline">\(2\times10^1\)</span> to <span class="math inline">\(2\times10^4\)</span>, and <span class="math inline">\(\kappa(X^TX)\)</span> from <span class="math inline">\(5\times10^2\)</span> to <span class="math inline">\(4\times10^8\)</span> — the square of the first at every single point, as the opening derivation said it would be. Worth being honest about what that does and does not show. Neither curve reaches the dashed float64 ceiling at these sizes, so nothing here has actually run out of precision; the demonstration is of the <em>rate</em>, not of a failure. The consequence is still real, though, because it fixes where each method dies: the normal equations exhaust double precision once <span class="math inline">\(\kappa(X)\)</span> reaches about <span class="math inline">\(10^8\)</span>, while QR keeps working until <span class="math inline">\(\kappa(X)\)</span> reaches <span class="math inline">\(10^{16}\)</span>. Eight orders of headroom, surrendered for an answer that was no better.</p>
<p>Overfitting and conditioning point the same direction, which is why breeding programs use ridge-shrunk GBLUP — genomic best linear unbiased prediction, least squares with a penalty pulling marker effects toward zero — rather than raw least squares. Its central object is built from the same markers.</p>
<p>Multiply the marker matrix by its own transpose and you get <span class="math inline">\(G\propto XX^T\)</span>, the genomic relationship matrix: entry <span class="math inline">\((i,j)\)</span> says how much of their marker profile lines <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span> share, which is a measurement of relatedness rather than an assumption about a pedigree. <span class="math inline">\(G\)</span> is a covariance matrix, so the Cholesky trick applies directly — factor it, multiply standard normal noise by <span class="math inline">\(L\)</span>, and out come breeding values correlated exactly as the relatedness says they should be. That is the sampling step GBLUP actually performs:</p>
<div id="e9e1565f" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> (X_sub <span class="op">@</span> X_sub.T) <span class="op">/</span> X_sub.shape[<span class="dv">1</span>]</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>G <span class="op">+=</span> <span class="fl">1e-6</span> <span class="op">*</span> np.eye(G.shape[<span class="dv">0</span>])  <span class="co"># ridge for numerical PD</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>L <span class="op">=</span> cholesky(G, lower<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>breeding_values <span class="op">=</span> L <span class="op">@</span> rng.normal(size<span class="op">=</span>G.shape[<span class="dv">0</span>])</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sampled breeding values: mean=</span><span class="sc">{</span>breeding_values<span class="sc">.</span>mean()<span class="sc">:.3f}</span><span class="ss">, var=</span><span class="sc">{</span>breeding_values<span class="sc">.</span>var()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>sampled breeding values: mean=0.000, var=0.137</code></pre>
</div>
</div>
<p><span class="math inline">\(G\)</span> is symmetric, so the eigendecomposition derived three sections ago applies to it directly — this time as a tool rather than as a theorem. Its leading eigenvectors are the directions along which the 599 lines differ most in relatedness, and in a breeding panel that means the axes separating ancestral groups. Plot each line against the first two and lineages pull apart into clusters. Geneticists call the result population structure.</p>
<div id="0e35251f" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>eigvals_G, eigvecs_G <span class="op">=</span> eigh(G)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>order <span class="op">=</span> np.argsort(eigvals_G)[::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>pc1, pc2 <span class="op">=</span> eigvecs_G[:, order[<span class="dv">0</span>]], eigvecs_G[:, order[<span class="dv">1</span>]]</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">5</span>, <span class="dv">5</span>))</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>ax.scatter(pc1, pc2, s<span class="op">=</span><span class="dv">16</span>, color<span class="op">=</span>ACCENT, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"PC1 (top eigenvector of G)"</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"PC2"</span>)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Population structure, 599 real wheat lines"</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The scatter is deliberately uncoloured. The dataset’s <code>wheat.sets</code> field is a cross-validation fold assignment, not a population label, so there is no ancestry grouping here to colour by and inventing one would be worse than leaving it plain.</p>
<p>What these axes are actually for is correction. Genome-wide association studies in humans run this identical calculation under the name EIGENSTRAT and hand the top eigenvectors back to the regression as covariates, so that a systematic difference between subpopulations cannot masquerade as a marker genuinely associated with the trait. Any breeding panel mixing lineages needs the same guard, for the same reason.</p>
<p>Three factorizations, one dataset, each earning its constraint. The last dataset needs the constraint none of them impose.</p>
</section>
<section id="nonnegativity-finds-an-all-only-signature-nobody-labelled" class="level2">
<h2 class="anchored" data-anchor-id="nonnegativity-finds-an-all-only-signature-nobody-labelled">Nonnegativity finds an ALL-only signature nobody labelled</h2>
<p>Acute leukemia arrives in two forms that can look alike down a microscope and are not the same disease. Acute lymphoblastic leukemia, ALL, begins in the lymphoid cell line; acute myeloid leukemia, AML, in the myeloid one. They take materially different drug regimens, so calling the wrong one costs a patient the right protocol at the moment treatment matters most — and a blood smear alone does not always settle which is which.</p>
<p>Measuring how strongly every gene is switched on in a sample was the first thing that could settle it molecularly. Golub et al.&nbsp;profiled bone-marrow samples from 72 leukemia patients on Affymetrix microarrays in 1999 — a microarray being a chip carrying probes for thousands of genes at once, each probe glowing in proportion to how much of that gene’s transcript the sample contains — and founded molecular cancer classification in the process. Brunet et al.&nbsp;reused this same data in 2004 to introduce NMF-based tumour subtyping, which is the analysis this section repeats.</p>
<p>What is asked of the data here is the harder version of the question. Not “can a classifier trained on the labels predict the label”, but “does the structure fall out of the expression matrix with no label shown to the model at all” — because only the unsupervised version could ever surface a subtype nobody had named yet. NMF fits <em>this</em> data for two reasons. Expression intensities are nonnegative quantities, so the constraint costs nothing the data had. And the biology is additive: a tumour expresses a combination of gene programs, never one program minus another. A signed factorization would return components that cancel, fitting just as well and reading as nothing at all.</p>
<div id="443bc5ff" class="cell" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>gbase <span class="op">=</span> <span class="st">"https://raw.githubusercontent.com/dharsandip/Classification_of_Cancer_by_Gene_Expression_Dataset/master"</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>train_raw <span class="op">=</span> pd.read_csv(<span class="ss">f"</span><span class="sc">{</span>gbase<span class="sc">}</span><span class="ss">/data_set_ALL_AML_train.csv"</span>)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>indep_raw <span class="op">=</span> pd.read_csv(<span class="ss">f"</span><span class="sc">{</span>gbase<span class="sc">}</span><span class="ss">/data_set_ALL_AML_independent.csv"</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>actual <span class="op">=</span> pd.read_csv(<span class="ss">f"</span><span class="sc">{</span>gbase<span class="sc">}</span><span class="ss">/actual.csv"</span>)</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> expression_matrix(raw):</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    id_cols <span class="op">=</span> [c <span class="cf">for</span> c <span class="kw">in</span> raw.columns <span class="cf">if</span> <span class="kw">not</span> c.startswith(<span class="st">"call"</span>) <span class="kw">and</span> c <span class="kw">not</span> <span class="kw">in</span> (<span class="st">"Gene Description"</span>, <span class="st">"Gene Accession Number"</span>)]</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> raw[id_cols].to_numpy(dtype<span class="op">=</span><span class="bu">float</span>).T, [<span class="bu">int</span>(c) <span class="cf">for</span> c <span class="kw">in</span> id_cols]</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>X_train_expr, train_patients <span class="op">=</span> expression_matrix(train_raw)</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>X_test_expr, test_patients <span class="op">=</span> expression_matrix(indep_raw)</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>expr <span class="op">=</span> np.vstack([X_train_expr, X_test_expr])  <span class="co"># 72 real patients x 7129 real genes</span></span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>patient_order <span class="op">=</span> train_patients <span class="op">+</span> test_patients</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>diagnosis <span class="op">=</span> actual.set_index(<span class="st">"patient"</span>).loc[patient_order, <span class="st">"cancer"</span>].to_numpy()</span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"real expression matrix: </span><span class="sc">{</span>expr<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> patients x </span><span class="sc">{</span>expr<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> genes "</span></span>
<span id="cb24-19"><a href="#cb24-19" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"(</span><span class="sc">{</span>(diagnosis <span class="op">==</span> <span class="st">'ALL'</span>)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> ALL / </span><span class="sc">{</span>(diagnosis <span class="op">==</span> <span class="st">'AML'</span>)<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">}</span><span class="ss"> AML, real diagnoses)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>real expression matrix: 72 patients x 7129 genes (47 ALL / 25 AML, real diagnoses)</code></pre>
</div>
</div>
<p>NMF needs <span class="math inline">\(V\ge0\)</span>, so raw intensities — which include negative background noise — get floored to a small positive value, then log-transformed and subset to the most variable genes: standard microarray preprocessing, and the step Brunet et al.&nbsp;also applied before fitting NMF to this exact data:</p>
<div id="5df7ef8c" class="cell" data-execution_count="17">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>expr_log <span class="op">=</span> np.log2(np.clip(expr, <span class="fl">1.0</span>, <span class="va">None</span>))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>gene_var <span class="op">=</span> expr_log.var(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>top_genes <span class="op">=</span> np.argsort(gene_var)[::<span class="op">-</span><span class="dv">1</span>][:<span class="dv">1500</span>]</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>V_leuk <span class="op">=</span> expr_log[:, top_genes]</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>leuk_model <span class="op">=</span> NMF(n_components<span class="op">=</span><span class="dv">2</span>, init<span class="op">=</span><span class="st">"nndsvda"</span>, max_iter<span class="op">=</span><span class="dv">1000</span>, random_state<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a>W_leuk <span class="op">=</span> leuk_model.fit_transform(V_leuk)</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>H_leuk <span class="op">=</span> leuk_model.components_</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>dominant <span class="op">=</span> np.argmax(W_leuk, axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(pd.crosstab(diagnosis, dominant, rownames<span class="op">=</span>[<span class="st">"real diagnosis"</span>], colnames<span class="op">=</span>[<span class="st">"dominant metagene"</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>dominant metagene   0   1
real diagnosis           
ALL                26  21
AML                25   0</code></pre>
</div>
</div>
<p>Fit with <span class="math inline">\(k=2\)</span> and no diagnosis ever shown to the model, the two components — <em>metagenes</em>, in this literature: weighted bundles of genes that rise and fall together — come out sharply asymmetric. One dominates 21 patients, and all 21 of them are ALL, with no AML at all. The other dominates the remaining 51, split almost evenly at 26 ALL against 25 AML, which is to say it carries no diagnostic signal whatsoever.</p>
<p>Worth stating precisely, because that is less than a clean two-way split and considerably more than nothing. NMF did not partition the cohort into ALL and AML. It isolated a pure-ALL subgroup — a little under half the ALL patients — out of an otherwise undifferentiated remainder, having been told nothing.</p>
<div id="b9c152e4" class="cell" data-execution_count="18">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">11</span>, <span class="fl">4.5</span>))</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> np.where(diagnosis <span class="op">==</span> <span class="st">"ALL"</span>, ACCENT, <span class="st">"#E07B39"</span>)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].scatter(W_leuk[:, <span class="dv">0</span>], W_leuk[:, <span class="dv">1</span>], c<span class="op">=</span>colors, s<span class="op">=</span><span class="dv">30</span>, alpha<span class="op">=</span><span class="fl">0.85</span>)</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"metagene 1 weight"</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"metagene 2 weight"</span>)</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"NMF weights, colored by real diagnosis"</span>)</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>sns.heatmap(H_leuk[:, :<span class="dv">150</span>], cmap<span class="op">=</span><span class="st">"viridis"</span>, cbar_kws<span class="op">=</span>{<span class="st">"label"</span>: <span class="st">"gene weight"</span>}, ax<span class="op">=</span>axes[<span class="dv">1</span>])</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"gene (top-variance subset, first 150 shown)"</span>)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"metagene"</span>)</span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"Learned H: two real metagenes"</span>)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/cell-19-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A pure signature recovered without supervision is the precedent expression-based subtyping was built on, and subtype calls of this kind now route patients to different protocols — which is where the clinical stakes named at the top of this section actually land. Nonnegativity is the whole reason <span class="math inline">\(W\)</span> and <span class="math inline">\(H\)</span> can be read as gene programs. Signed components would have approximated the same matrix at least as well and meant nothing, which is the trade this factorization was introduced to make: convexity given up, legibility bought.</p>
</section>
<section id="the-constraint-was-always-the-point" class="level2">
<h2 class="anchored" data-anchor-id="the-constraint-was-always-the-point">The constraint was always the point</h2>
<p>The list at the top of this post is still the same list — QR, SVD, eigendecomposition, NMF, Cholesky. What it no longer is, is arbitrary, because every entry now carries the thing it refuses to do. QR refuses to form <span class="math inline">\(X^TX\)</span>, and buys back the digits that squaring the condition number would have spent. Truncated SVD refuses an exact fit, and buys a bound no matrix of the same rank can beat. Eigendecomposition refuses the second basis, and buys the identity that makes covariance eigenvalues and squared singular values the same numbers. NMF refuses negative entries, and buys a factor a biologist can read, at the price of never knowing whether it found the global optimum. Cholesky refuses to invert, and buys every solve after the first at <span class="math inline">\(O(n^2)\)</span>.</p>
<p>So the choice is not a matter of taste, and it is not settled by the matrix alone. It is settled by what you need the answer to <em>mean</em> — stable, smallest, additive, reusable — and the eight EC2 traces, 599 wheat lines, and 72 leukemia biopsies above are three places where meaning the wrong thing has a price attached: a missed outage, a wasted season, a patient on the wrong protocol. Pick the constraint first. The factorization follows from it.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/matrix-factorizations/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>