<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-08-31">

<title>Tensor Inverses: Independence, Completion, Identification – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Tensor Inverses: Independence, Completion, Identification</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Linear Algebra</div>
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Numerical Methods</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 31, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#words-used-here" id="toc-words-used-here" class="nav-link active" data-scroll-target="#words-used-here"><span class="header-section-number">1</span> Words used here</a></li>
  <li><a href="#why-the-inverse-is-not-unique" id="toc-why-the-inverse-is-not-unique" class="nav-link" data-scroll-target="#why-the-inverse-is-not-unique"><span class="header-section-number">2</span> Why the inverse is not unique</a></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">3</span> Data</a>
  <ul class="collapse">
  <li><a href="#three-voices-one-mix" id="toc-three-voices-one-mix" class="nav-link" data-scroll-target="#three-voices-one-mix"><span class="header-section-number">3.1</span> Three voices, one mix</a></li>
  <li><a href="#movielens-100k" id="toc-movielens-100k" class="nav-link" data-scroll-target="#movielens-100k"><span class="header-section-number">3.2</span> MovieLens 100K</a></li>
  <li><a href="#an-industrial-dryer" id="toc-an-industrial-dryer" class="nav-link" data-scroll-target="#an-industrial-dryer"><span class="header-section-number">3.3</span> An industrial dryer</a></li>
  </ul></li>
  <li><a href="#independence" id="toc-independence" class="nav-link" data-scroll-target="#independence"><span class="header-section-number">4</span> Independence</a></li>
  <li><a href="#completion" id="toc-completion" class="nav-link" data-scroll-target="#completion"><span class="header-section-number">5</span> Completion</a></li>
  <li><a href="#identification" id="toc-identification" class="nav-link" data-scroll-target="#identification"><span class="header-section-number">6</span> Identification</a></li>
  <li><a href="#side-by-side" id="toc-side-by-side" class="nav-link" data-scroll-target="#side-by-side"><span class="header-section-number">7</span> Side by side</a></li>
  <li><a href="#constraints" id="toc-constraints" class="nav-link" data-scroll-target="#constraints"><span class="header-section-number">8</span> Constraints</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">9</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tensor-inverse-examples/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block page-columns page-full" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Tensor Inverses: Independence, Completion, Identification</figcaption>
</figure>
</div>
<p>You already undo a mixed recording, fill a blank rating, and pick plant settings from a desired output. For a square, full-rank matrix those three jobs share one inverse. A tensor does not. You pick a product, then extra structure, and a leftover still remains — permutation and scale, a rank, a lag.</p>
<p>A meeting transcript, a recommendation, and a dryer batch each hang on which leftover you keep.</p>
<p><a href="../tensor-factorizations/">Tensor Factorizations and Tensor Inverses</a> has the algebra. <a href="../uses-of-tensor-factorizations/">Uses of Tensor Factorizations</a> has the compression case. <a href="../tensor-inverses-in-practice/">Tensor Inverses in Practice</a> works four other problems and lists the products. This post takes three more — unmixing speech, filling missing ratings, identifying a dryer — and shows that even after you pick a product, the inverse is not unique.</p>
<section id="words-used-here" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="words-used-here"><span class="header-section-number">1</span> Words used here</h2>
<p>Mode, flatten, rank, null space, inverse, and pseudoinverse are defined in <a href="../tensor-inverses-in-practice/">Tensor Inverses in Practice</a>. Four more words appear below.</p>
<ul>
<li><strong>Cumulant.</strong> A moment of the data with the Gaussian part subtracted. The fourth-order cumulant of a vector is a <span class="math inline">\(n\times n\times n\times n\)</span> tensor. Independent non-Gaussian sources make that tensor diagonal.</li>
<li><strong>Joint diagonalization.</strong> One orthogonal change of basis that makes several matrices as diagonal as they can be at once. JADE does this to the slices of the cumulant.</li>
<li><strong>Sampling operator.</strong> The map that keeps the observed cells of an array and throws the rest away. Its null space is every array that is zero on those cells.</li>
<li><strong>Impulse-response tensor.</strong> For a linear plant, <span class="math inline">\(H_{ijk}\)</span> is how output <span class="math inline">\(i\)</span> responds to input <span class="math inline">\(j\)</span> at lag <span class="math inline">\(k\)</span>.</li>
</ul>
<div id="setup" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stderr">
<pre><code>/Users/ravikalia/Code/github.com/ml-blog/.venv-tensor-factorizations/lib/python3.12/site-packages/tensorly/solvers/nnls.py:103: SyntaxWarning: invalid escape sequence '\l'
  .. math:: \lambda_s, \lambda_r
/Users/ravikalia/Code/github.com/ml-blog/.venv-tensor-factorizations/lib/python3.12/site-packages/tensorly/solvers/admm.py:99: SyntaxWarning: invalid escape sequence '\_'
  .. math:: dual\_var = dual\_var + (Ax + Bx_{split} - c)</code></pre>
</div>
</div>
</section>
<section id="why-the-inverse-is-not-unique" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="why-the-inverse-is-not-unique"><span class="header-section-number">2</span> Why the inverse is not unique</h2>
<p>A matrix inverse undoes matrix multiplication. There is one matrix product, so there is one inverse when the matrix is square and full rank.</p>
<p>A tensor has several products. Each product has its own inverse. That is the algebra in the earlier posts. This post is about the leftover that stays after you pick one.</p>
<ul>
<li><strong>Independence.</strong> The mixing matrix is recoverable only up to permutation and scale, and only if the sources are independent with at most one Gaussian. Two signed permutations of <span class="math inline">\(A^{-1}\)</span> both undo the mix. They are different matrices.</li>
<li><strong>Missing entries.</strong> The sampling operator has a huge null space. Infinitely many arrays match the observed ratings. Rank and the ALS start pick one filling. Two ranks fill the same hole with two numbers.</li>
<li><strong>MIMO identification.</strong> Input-output data underdetermines a full parameter tensor. A lag length picks one impulse-response tensor. Inverting that tensor for a control input is a second, different inverse. Two products, two settings.</li>
</ul>
<p>In real work you solve, you do not invert. That line is already in <a href="../tensor-inverses-in-practice/">Tensor Inverses in Practice</a>. This post builds the inverse anyway, so you can see the leftover.</p>
</section>
<section id="data" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="data"><span class="header-section-number">3</span> Data</h2>
<p>Three sources. Two are downloaded. The speech mix is constructed from real recordings, so the recovery can be scored.</p>
<section id="three-voices-one-mix" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="three-voices-one-mix"><span class="header-section-number">3.1</span> Three voices, one mix</h3>
<ul>
<li><strong>What it is.</strong> Four seconds each of three Wikimedia recordings of Aesop’s <em>The North Wind and the Sun</em>: <a href="https://commons.wikimedia.org/wiki/File:Recording_of_speaker_of_British_English_(Received_Pronunciation).ogg">British English, Received Pronunciation</a> (P. Roach / International Phonetic Association, CC BY-SA 3.0), <a href="https://commons.wikimedia.org/wiki/File:Sv-The_North_Wind_and_the_Sun.ogg">Swedish</a>, and <a href="https://commons.wikimedia.org/wiki/File:Cdo_northwind_sun_04.ogg">Foochow</a> (GnuDoyng, public domain). Resampled to 8 kHz mono.</li>
<li><strong>Who recorded them and why.</strong> Phonetic archives keep this fable so accents can be compared. The recordings were not made for unmixing.</li>
<li><strong>What this post asks of them.</strong> Mix the three tracks with a known <span class="math inline">\(3\times 3\)</span> matrix (seed 7) and try to get the voices back. The mix is constructed. The waveforms are not.</li>
<li><strong>The business problem.</strong> A meeting recorder, a hearing aid, or a call centre hears several talkers on one microphone. The product is a transcript, a boosted voice, or a compliance log that follows one speaker.</li>
<li><strong>What solving buys.</strong> Each voice comes back on its own channel. A transcript can attribute a sentence. A hearing aid can raise one talker and lower the others.</li>
<li><strong>What a wrong inverse costs.</strong> Words land on the wrong speaker. A quote in minutes, a medical note, or a legal record names the person who did not say it.</li>
<li><strong>Why a tensor inverse.</strong> The fourth-order cumulant of the mix is a <span class="math inline">\(3\times 3\times 3\times 3\)</span> tensor. Independent non-Gaussian sources make it diagonal. Inverting that structure is how you recover the mixing matrix. The inverse is unique only up to permutation and scale.</li>
</ul>
<p>The three sources, then the three mixed channels.</p>
<p><strong>English (RP)</strong></p>
<audio controls="" src="media/source-0.wav">
</audio>
<p><strong>Swedish</strong></p>
<audio controls="" src="media/source-1.wav">
</audio>
<p><strong>Foochow</strong></p>
<audio controls="" src="media/source-2.wav">
</audio>
<p><strong>Mixed channel 1</strong></p>
<audio controls="" src="media/mix-0.wav">
</audio>
<p><strong>Mixed channel 2</strong></p>
<audio controls="" src="media/mix-1.wav">
</audio>
<p><strong>Mixed channel 3</strong></p>
<audio controls="" src="media/mix-2.wav">
</audio>
<div id="speech-load" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>sp <span class="op">=</span> np.load(DATA <span class="op">/</span> <span class="st">"speech.npz"</span>, allow_pickle<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>sources, mixed, A <span class="op">=</span> sp[<span class="st">"sources"</span>], sp[<span class="st">"mixed"</span>], sp[<span class="st">"mix_matrix"</span>].astype(<span class="bu">float</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>rate <span class="op">=</span> <span class="bu">int</span>(sp[<span class="st">"rate"</span>])</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>sources<span class="sc">.</span>shape[<span class="dv">1</span>] <span class="op">/</span> rate<span class="sc">:.1f}</span><span class="ss"> s at </span><span class="sc">{</span>rate<span class="sc">}</span><span class="ss"> Hz, mix condition number </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>cond(A)<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"labels:"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> lab <span class="kw">in</span> sp[<span class="st">"labels"</span>]:</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>lab<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>4.0 s at 8000 Hz, mix condition number 3.60
labels:
  The North Wind and the Sun (British English, RP)
  The North Wind and the Sun (Swedish)
  The North Wind and the Sun (Foochow)</code></pre>
</div>
</div>
<div id="cell-fig-speech" class="cell" data-fig-height="5.2" data-fig-width="10" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> np.arange(sources.shape[<span class="dv">1</span>]) <span class="op">/</span> rate</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">5.2</span>), sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>):</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    axes[i, <span class="dv">0</span>].plot(t, sources[i], color<span class="op">=</span>TEAL, lw<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    axes[i, <span class="dv">1</span>].plot(t, mixed[i], color<span class="op">=</span>CORAL, lw<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    axes[i, <span class="dv">0</span>].set_ylabel(<span class="ss">f"src </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    axes[i, <span class="dv">1</span>].set_ylabel(<span class="ss">f"mic </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">0</span>].set_title(<span class="st">"Sources"</span>)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>, <span class="dv">1</span>].set_title(<span class="st">"Mix"</span>)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>].set_xlabel(<span class="st">"time (s)"</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>].set_xlabel(<span class="st">"time (s)"</span>)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-speech" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-speech-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-speech-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-speech-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Three source waveforms (teal) and the three mixed channels (coral). The mix is a known 3 × 3 applied at every sample.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="movielens-100k" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="movielens-100k"><span class="header-section-number">3.2</span> MovieLens 100K</h3>
<ul>
<li><strong>Provenance.</strong> The <a href="https://grouplens.org/datasets/movielens/100k/">MovieLens 100K</a> ratings dump from GroupLens Research at the University of Minnesota (Harper and Konstan 2015). 100,000 ratings, 943 users, 1,682 movies, 19 September 1997 to 22 April 1998.</li>
<li><strong>Collector and motive.</strong> Students in a recommender-systems class, plus visitors to the MovieLens site, rated films so the lab could study collaborative filtering. These are ratings, not watches.</li>
<li><strong>What this post uses.</strong> The 80 most-active users and the 80 most-rated movies, binned by calendar month. A cell is the mean rating of that user for that movie in that month, or missing. <code>src/fetch_data.py</code> writes <code>data/movielens.npz</code>. A render never downloads the zip. The crop is <span class="math inline">\(80\times 80\times 8\)</span> with 4,797 observed cells — about 9% of the array.</li>
<li><strong>The business problem.</strong> A catalogue page cannot show an empty slot. The product is a ranked list: which title to put in front of this user this month.</li>
<li><strong>What solving buys.</strong> A held-out rating is filled, so a title the user would like is not buried. Inventory and attention go to that title.</li>
<li><strong>What a wrong inverse costs.</strong> Rank 3 and rank 8 fill the same hole with different numbers. One number says “show <em>The Terminator</em>”. The other says “do not”. A bad fill wastes a slot and trains the next model on a rating nobody gave.</li>
<li><strong>Why a tensor method.</strong> User, movie, and month are three modes. Flattening to user <span class="math inline">\(\times\)</span> movie throws the month away. A rating in October is not a rating in April.</li>
</ul>
<div id="ml-load" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ml <span class="op">=</span> np.load(DATA <span class="op">/</span> <span class="st">"movielens.npz"</span>, allow_pickle<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>ratings <span class="op">=</span> ml[<span class="st">"ratings"</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>obs <span class="op">=</span> np.isfinite(ratings)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"crop </span><span class="sc">{</span>ratings<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span><span class="bu">int</span>(obs.<span class="bu">sum</span>())<span class="sc">}</span><span class="ss"> observed cells "</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"(</span><span class="sc">{</span><span class="dv">100</span> <span class="op">*</span> obs<span class="sc">.</span>mean()<span class="sc">:.1f}</span><span class="ss">%), months </span><span class="sc">{</span><span class="bu">list</span>(ml[<span class="st">'months'</span>])<span class="sc">}</span><span class="ss">"</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"first titles:"</span>, <span class="st">", "</span>.join(<span class="bu">str</span>(t) <span class="cf">for</span> t <span class="kw">in</span> ml[<span class="st">"titles"</span>][:<span class="dv">5</span>]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>crop (80, 80, 8), 4797 observed cells (9.4%), months [np.str_('1997-09'), np.str_('1997-10'), np.str_('1997-11'), np.str_('1997-12'), np.str_('1998-01'), np.str_('1998-02'), np.str_('1998-03'), np.str_('1998-04')]
first titles: Star Wars (1977), Contact (1997), Fargo (1996), Return of the Jedi (1983), Liar Liar (1997)</code></pre>
</div>
</div>
<div id="cell-fig-ratings" class="cell" data-fig-height="5.4" data-fig-width="7" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>nov <span class="op">=</span> <span class="bu">list</span>(ml[<span class="st">"months"</span>]).index(<span class="st">"1997-11"</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>panel <span class="op">=</span> ratings[:, :, nov]</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="fl">5.4</span>))</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>im <span class="op">=</span> ax.imshow(panel, cmap<span class="op">=</span><span class="st">"magma"</span>, vmin<span class="op">=</span><span class="dv">1</span>, vmax<span class="op">=</span><span class="dv">5</span>, aspect<span class="op">=</span><span class="st">"auto"</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"movie (most-rated first)"</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"user (most-active first)"</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"1997-11"</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>fig.colorbar(im, ax<span class="op">=</span>ax, fraction<span class="op">=</span><span class="fl">0.046</span>, label<span class="op">=</span><span class="st">"mean rating"</span>)</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-ratings" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ratings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-ratings-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ratings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Mean rating by user and movie in 1997-11. White is missing. Most of the month is empty; that emptiness is the sampling operator.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="an-industrial-dryer" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="an-industrial-dryer"><span class="header-section-number">3.3</span> An industrial dryer</h3>
<ul>
<li><strong>Provenance.</strong> DaISy dataset <a href="https://ftp.esat.kuleuven.be/pub/SISTA/data/process_industry/dryer2.txt">96-016</a>, “Data from an industrial dryer (supplied by Cambridge Control Ltd)”, contributed by Jan Maciejowski. 867 samples at 10 s. Three inputs: fuel flow, hot-gas exhaust fan speed, raw-material flow. Three outputs: dry-bulb temperature, wet-bulb temperature, moisture of the raw material.</li>
<li><strong>Collector and motive.</strong> Cambridge Control recorded a working dryer so multivariable identification methods could be compared on one plant (Maciejowski 1996; Chou and Maciejowski 1997). De Moor hosts the file in <a href="https://homes.esat.kuleuven.be/~smc/daisy/">DaISy</a>.</li>
<li><strong>What this post uses.</strong> The six series, centred. <code>data/dryer.npz</code> is committed. A render never hits the KU Leuven host.</li>
<li><strong>The business problem.</strong> The dryer has to hit a moisture target without scorching the product or wasting fuel. The product of the inverse is a set of actuator settings: fuel, fan, feed.</li>
<li><strong>What solving buys.</strong> You can ask “what input window gives this moisture and these temperatures?” and get a number you can put on the plant.</li>
<li><strong>What a wrong inverse costs.</strong> One inverse of the fitted tensor asks for a small change in feed. Another, on the same target, asks for a thousand-unit dump. A wrong pick over-dries a batch, or ships it wet.</li>
<li><strong>Why a tensor inverse.</strong> The plant map is output <span class="math inline">\(\times\)</span> input <span class="math inline">\(\times\)</span> lag. That is three physical modes. Flattening them into one matrix hides which inverse you took.</li>
</ul>
<div id="dryer-load" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>dr <span class="op">=</span> np.load(DATA <span class="op">/</span> <span class="st">"dryer.npz"</span>, allow_pickle<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>U_raw, Y_raw <span class="op">=</span> dr[<span class="st">"U"</span>].astype(<span class="bu">float</span>), dr[<span class="st">"Y"</span>].astype(<span class="bu">float</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>U <span class="op">=</span> U_raw <span class="op">-</span> U_raw.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> Y_raw <span class="op">-</span> Y_raw.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>dt <span class="op">=</span> <span class="bu">float</span>(dr[<span class="st">"dt"</span>])</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dr[<span class="st">"cite"</span>])</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(U)<span class="sc">}</span><span class="ss"> samples at </span><span class="sc">{</span>dt<span class="sc">:.0f}</span><span class="ss"> s, inputs </span><span class="sc">{</span><span class="bu">list</span>(dr[<span class="st">'inputs'</span>])<span class="sc">}</span><span class="ss">, outputs </span><span class="sc">{</span><span class="bu">list</span>(dr[<span class="st">'outputs'</span>])<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>96-016 industrial dryer (Cambridge Control Ltd)
867 samples at 10 s, inputs [np.str_('fuel flow'), np.str_('exhaust fan'), np.str_('raw-material flow')], outputs [np.str_('dry-bulb temp'), np.str_('wet-bulb temp'), np.str_('moisture')]</code></pre>
</div>
</div>
<div id="cell-fig-dryer" class="cell" data-fig-height="5.2" data-fig-width="10" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tt <span class="op">=</span> np.arange(<span class="bu">len</span>(U)) <span class="op">*</span> dt <span class="op">/</span> <span class="fl">60.0</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">5.2</span>), sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">3</span>):</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    axes[i, <span class="dv">0</span>].plot(tt, U[:, i], color<span class="op">=</span>TEAL, lw<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    axes[i, <span class="dv">1</span>].plot(tt, Y[:, i], color<span class="op">=</span>CORAL, lw<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    axes[i, <span class="dv">0</span>].set_ylabel(<span class="bu">str</span>(dr[<span class="st">"inputs"</span>][i]))</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    axes[i, <span class="dv">1</span>].set_ylabel(<span class="bu">str</span>(dr[<span class="st">"outputs"</span>][i]))</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="op">-</span><span class="dv">1</span>, <span class="dv">0</span>].set_xlabel(<span class="st">"minutes"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>].set_xlabel(<span class="st">"minutes"</span>)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-dryer" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dryer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-dryer-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dryer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Centred dryer inputs (teal) and outputs (coral). Fuel, fan, and feed on the left; dry-bulb, wet-bulb, and moisture on the right.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="independence" class="level2 page-columns page-full" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="independence"><span class="header-section-number">4</span> Independence</h2>
<p><strong>Who does this.</strong> A speech engineer pulling one talker out of a meeting recording.</p>
<div class="page-columns page-full">
<div id="fig-poster-speech" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" alt="Poster in four numbered stages plus a footer. One: English, Swedish, and Foochow source waveforms. Two: a constructed 3 by 3 mix, three microphone channels. Three: an isometric cube labelled order 4, 3 by 3 by 3 by 3, the cumulant C. Four: two cards, A inverse keeps English as English, signed-permutation inverse swaps speakers. Footer: the inverse puts each voice on its own channel so a transcript can attribute a quote; a leftover permutation names the wrong speaker.">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-poster-speech-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="media/poster-speech.png" class="img-fluid figure-img column-page" alt="Poster in four numbered stages plus a footer. One: English, Swedish, and Foochow source waveforms. Two: a constructed 3 by 3 mix, three microphone channels. Three: an isometric cube labelled order 4, 3 by 3 by 3 by 3, the cumulant C. Four: two cards, A inverse keeps English as English, signed-permutation inverse swaps speakers. Footer: the inverse puts each voice on its own channel so a transcript can attribute a quote; a leftover permutation names the wrong speaker.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-poster-speech-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Three voices become one mix, then a <span class="math inline">\(3\times3\times3\times3\)</span> cumulant. Two inverses of that tensor both undo the mix. <span class="math inline">\(A^{-1}\)</span> keeps the speaker names. <span class="math inline">\(P A^{-1}\)</span> swaps them.
</figcaption>
</figure>
</div>
</div>
<p>The fourth-order cumulant of a centred, whitened recording <span class="math inline">\(Z\)</span> is</p>
<p><span class="math display">\[
C_{ijkl}=\mathbb{E}[z_i z_j z_k z_l]-\delta_{ij}\delta_{kl}-\delta_{ik}\delta_{jl}-\delta_{il}\delta_{jk}.
\]</span></p>
<p>Independent non-Gaussian sources make <span class="math inline">\(C\)</span> diagonal. A mixing matrix <span class="math inline">\(A\)</span> rotates those axes. Recovering <span class="math inline">\(A^{-1}\)</span> is a joint diagonalization of the slices of <span class="math inline">\(C\)</span>. Any signed permutation of <span class="math inline">\(A^{-1}\)</span> diagonalizes <span class="math inline">\(C\)</span> as well. That leftover is the inverse that is not unique.</p>
<p>The mix here is constructed, so <span class="math inline">\(A^{-1}\)</span> is known. Two inverses, then a third that only inverts the covariance.</p>
<div id="ica-inverses" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Ainv <span class="op">=</span> np.linalg.inv(A)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>perm <span class="op">=</span> np.array([<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">0</span>])</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>signs <span class="op">=</span> np.array([<span class="fl">1.0</span>, <span class="op">-</span><span class="fl">1.0</span>, <span class="fl">1.0</span>])</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>Ainv_perm <span class="op">=</span> C.signed_perm(Ainv, perm, signs)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>rec_true <span class="op">=</span> Ainv <span class="op">@</span> mixed</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>rec_perm <span class="op">=</span> Ainv_perm <span class="op">@</span> mixed</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>rec_pca <span class="op">=</span> C.pca_sources(mixed)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>rec_ica, _ <span class="op">=</span> C.fastica(mixed)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> report(name, rec):</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    sir <span class="op">=</span> C.sir_db(rec, sources)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&lt;18}</span><span class="ss"> SIR dB  </span><span class="sc">{</span>sir[<span class="dv">0</span>]<span class="sc">:5.1f}</span><span class="ss"> </span><span class="sc">{</span>sir[<span class="dv">1</span>]<span class="sc">:5.1f}</span><span class="ss"> </span><span class="sc">{</span>sir[<span class="dv">2</span>]<span class="sc">:5.1f}</span><span class="ss">   mean </span><span class="sc">{</span>sir<span class="sc">.</span>mean()<span class="sc">:4.1f}</span><span class="ss">"</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"A inverse"</span>, rec_true)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"signed perm"</span>, rec_perm)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"PCA / whiten"</span>, rec_pca)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>report(<span class="st">"FastICA"</span>, rec_ica)</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>Cz <span class="op">=</span> C.fourth_cumulant(C.whiten(mixed)[<span class="dv">0</span>])</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>Cs <span class="op">=</span> C.fourth_cumulant(C.whiten(sources)[<span class="dv">0</span>])</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cumulant </span><span class="sc">{</span>Cz<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"off-diagonal energy  sources </span><span class="sc">{</span>C<span class="sc">.</span>offdiag_energy(Cs)<span class="sc">:.3f}</span><span class="ss">   mix </span><span class="sc">{</span>C<span class="sc">.</span>offdiag_energy(Cz)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"A inverse and the signed permutation are different matrices: "</span></span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"||W1 - W2|| / ||W1|| = </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(Ainv <span class="op">-</span> Ainv_perm) <span class="op">/</span> np<span class="sc">.</span>linalg<span class="sc">.</span>norm(Ainv)<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>A inverse          SIR dB  144.9 145.3 146.8   mean 145.7
signed perm        SIR dB  145.3 146.8 144.9   mean 145.7
PCA / whiten       SIR dB   15.9  16.0  20.2   mean 17.4
FastICA            SIR dB   16.3   9.8  10.8   mean 12.3
cumulant (3, 3, 3, 3)
off-diagonal energy  sources 0.007   mix 0.081
A inverse and the signed permutation are different matrices: ||W1 - W2|| / ||W1|| = 1.47</code></pre>
</div>
</div>
<p><span class="math inline">\(A^{-1}\)</span> and <span class="math inline">\(P A^{-1}\)</span> both recover the three voices. Mean SIR is high because the mix is known. They are not the same matrix: relative Frobenius difference <span class="math inline">\(1.47\)</span>. The leftover is a permutation and two sign flips. A transcript that uses the second inverse swaps speakers and flips a polarity. The words are the same. The names are not.</p>
<p>PCA inverts the covariance, not the cumulant. Whitening is a second-order inverse. The leftover rotation stays. FastICA picks one rotation from the fourth-order structure. On four seconds of real speech it is a finite-sample pick, not the true <span class="math inline">\(A^{-1}\)</span>.</p>
<div id="cell-fig-ica" class="cell" data-fig-height="3.6" data-fig-width="10" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> np.arange(sources.shape[<span class="dv">1</span>]) <span class="op">/</span> rate</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># After the signed permutation, English (row 0) lives on recovered row 2 with a plus sign.</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">3</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">3.6</span>), sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].plot(t, sources[<span class="dv">0</span>], color<span class="op">=</span>TEAL, lw<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_ylabel(<span class="st">"source 1"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].plot(t, rec_true[<span class="dv">0</span>], color<span class="op">=</span>GOLD, lw<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"A inverse"</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].plot(t, rec_perm[<span class="dv">2</span>], color<span class="op">=</span>CORAL, lw<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_ylabel(<span class="st">"signed perm"</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="op">-</span><span class="dv">1</span>].set_xlabel(<span class="st">"time (s)"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-ica" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ica-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-ica-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ica-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Source 1 against two recoveries. Teal is the English track. Gold is A inverse. Coral is the signed permutation, which has moved this voice to another channel and flipped its sign.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The coral trace is the English voice, recovered by the second inverse, on a different channel and with the opposite sign. Both inverses solved the mix. Only one of them keeps the speaker labels.</p>
</section>
<section id="completion" class="level2 page-columns page-full" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="completion"><span class="header-section-number">5</span> Completion</h2>
<p><strong>Who does this.</strong> A recommender filling a catalogue cell so a page is not empty.</p>
<div class="page-columns page-full">
<div id="fig-poster-ratings" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" alt="Poster in four numbered stages plus a footer. One: isometric cube user 80 by movie 80 by month 8, 4,797 of 51,200 cells observed. Two: the same cube as a sampling operator, holes in the null space. Three: two CP inverses, rank 3 says Terminator 3.1 show it, rank 8 says 2.0 park it. Four: two catalogue pages, one uses the slot, one hides the film. Footer: a rank picks one filling of the holes; a wrong leftover hides a film the user rated.">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-poster-ratings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="media/poster-ratings.png" class="img-fluid figure-img column-page" alt="Poster in four numbered stages plus a footer. One: isometric cube user 80 by movie 80 by month 8, 4,797 of 51,200 cells observed. Two: the same cube as a sampling operator, holes in the null space. Three: two CP inverses, rank 3 says Terminator 3.1 show it, rank 8 says 2.0 park it. Four: two catalogue pages, one uses the slot, one hides the film. Footer: a rank picks one filling of the holes; a wrong leftover hides a film the user rated.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-poster-ratings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: An <span class="math inline">\(80\times80\times8\)</span> rating tensor, mostly empty. The sampling operator has no inverse. Rank 3 fills <em>The Terminator</em> at 3.1 and shows it. Rank 8 fills 2.0 and hides it.
</figcaption>
</figure>
</div>
</div>
<p>The sampling operator <span class="math inline">\(\mathcal{P}_\Omega\)</span> keeps the observed cells and throws the rest away. Its null space is every <span class="math inline">\(80\times 80\times 8\)</span> array that is zero on <span class="math inline">\(\Omega\)</span>. No inverse of <span class="math inline">\(\mathcal{P}_\Omega\)</span> exists. A rank-<span class="math inline">\(R\)</span> CP model picks one point in that affine space. ALS is how the point is found. The rank is a choice. The start is a choice. Both change the filling.</p>
<p>Hold out 20% of the observed cells (seed 7). Complete from the rest at rank 3 and at rank 8. Flatten to user <span class="math inline">\(\times\)</span> movie, fill with a rank-3 SVD, and repeat that matrix across months.</p>
<div id="complete-fit" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>train <span class="op">=</span> K.holdout(obs, frac<span class="op">=</span><span class="fl">0.2</span>, seed<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>held <span class="op">=</span> obs <span class="op">&amp;</span> <span class="op">~</span>train</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.where(obs, ratings, <span class="fl">0.0</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>fill3 <span class="op">=</span> K.cp_complete(X, train, rank<span class="op">=</span><span class="dv">3</span>, seed<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>fill8 <span class="op">=</span> K.cp_complete(X, train, rank<span class="op">=</span><span class="dv">8</span>, seed<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>flat <span class="op">=</span> K.flatten_svd_complete(X, train, rank<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"train </span><span class="sc">{</span><span class="bu">int</span>(train.<span class="bu">sum</span>())<span class="sc">}</span><span class="ss"> cells, held out </span><span class="sc">{</span><span class="bu">int</span>(held.<span class="bu">sum</span>())<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE rank 3   </span><span class="sc">{</span>K<span class="sc">.</span>rmse(fill3, ratings, held)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE rank 8   </span><span class="sc">{</span>K<span class="sc">.</span>rmse(fill8, ratings, held)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"RMSE flatten  </span><span class="sc">{</span>K<span class="sc">.</span>rmse(flat, ratings, held)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mean |rank3 - rank8| on held cells </span><span class="sc">{</span>np<span class="sc">.</span>mean(np.<span class="bu">abs</span>(fill3[held] <span class="op">-</span> fill8[held]))<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>train 3838 cells, held out 959
RMSE rank 3   0.932
RMSE rank 8   0.924
RMSE flatten  0.919
mean |rank3 - rank8| on held cells 0.187</code></pre>
</div>
</div>
<p>On this crop the flattened SVD is slightly better on RMSE. That is not a win for flattening as a method. It is a warning that RMSE on a 9% observed tensor is a weak score. The two CP ranks still disagree on the held cells by about 0.2 stars on average. The hole that disagrees most is the one a catalogue page would have to act on.</p>
<div id="complete-hole" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>diff <span class="op">=</span> np.<span class="bu">abs</span>(fill3 <span class="op">-</span> fill8)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>diff[<span class="op">~</span>held] <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>i, j, k <span class="op">=</span> np.unravel_index(<span class="bu">int</span>(np.argmax(diff)), diff.shape)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"user </span><span class="sc">{</span><span class="bu">int</span>(ml[<span class="st">'users'</span>][i])<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>ml[<span class="st">'titles'</span>][j]<span class="sc">}</span><span class="ss">, </span><span class="sc">{</span>ml[<span class="st">'months'</span>][k]<span class="sc">}</span><span class="ss">: "</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"true </span><span class="sc">{</span>ratings[i, j, k]<span class="sc">:.1f}</span><span class="ss">, rank 3 </span><span class="sc">{</span>fill3[i, j, k]<span class="sc">:.2f}</span><span class="ss">, "</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="ss">f"rank 8 </span><span class="sc">{</span>fill8[i, j, k]<span class="sc">:.2f}</span><span class="ss">, flatten </span><span class="sc">{</span>flat[i, j, k]<span class="sc">:.2f}</span><span class="ss">"</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>user 269, Terminator, The (1984), 1998-04: true 3.0, rank 3 3.11, rank 8 1.99, flatten 2.67</code></pre>
</div>
</div>
<p>User 269, <em>The Terminator</em> (1984), April 1998. The true rating is 3. Rank 3 fills 3.1 — a middling title, showable. Rank 8 fills 2.0 — park it. The flatten, which has no month, fills one number for every month of that user-movie pair. A ranking that uses rank 8 hides a film the user rated 3. A ranking that uses rank 3 shows it. Both ranks solved the same incomplete tensor. They shipped two different pages.</p>
<div id="cell-fig-complete" class="cell" data-fig-height="4.6" data-fig-width="10" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>month <span class="op">=</span> k</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>show <span class="op">=</span> np.where(held[:, :, month], fill3[:, :, month], np.nan)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>delta <span class="op">=</span> np.where(held[:, :, month], fill8[:, :, month] <span class="op">-</span> fill3[:, :, month], np.nan)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">4.6</span>))</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>im0 <span class="op">=</span> axes[<span class="dv">0</span>].imshow(show, cmap<span class="op">=</span><span class="st">"magma"</span>, vmin<span class="op">=</span><span class="dv">1</span>, vmax<span class="op">=</span><span class="dv">5</span>, aspect<span class="op">=</span><span class="st">"auto"</span>)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>im1 <span class="op">=</span> axes[<span class="dv">1</span>].imshow(delta, cmap<span class="op">=</span><span class="st">"coolwarm"</span>, vmin<span class="op">=-</span><span class="fl">1.5</span>, vmax<span class="op">=</span><span class="fl">1.5</span>, aspect<span class="op">=</span><span class="st">"auto"</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="ss">f"rank 3 fill, </span><span class="sc">{</span>ml[<span class="st">'months'</span>][month]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"rank 8 minus rank 3"</span>)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax <span class="kw">in</span> axes:</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"movie"</span>)</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">"user"</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>fig.colorbar(im0, ax<span class="op">=</span>axes[<span class="dv">0</span>], fraction<span class="op">=</span><span class="fl">0.046</span>, label<span class="op">=</span><span class="st">"rating"</span>)</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>fig.colorbar(im1, ax<span class="op">=</span>axes[<span class="dv">1</span>], fraction<span class="op">=</span><span class="fl">0.046</span>, label<span class="op">=</span><span class="st">"stars"</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-complete" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-complete-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-complete-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-complete-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Held-out cells for one month. Left: rank-3 fill. Right: rank-8 fill minus rank-3 fill. The right panel is the leftover. It is not noise: it is the part of the inverse that the rank chose.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="identification" class="level2 page-columns page-full" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="identification"><span class="header-section-number">6</span> Identification</h2>
<p><strong>Who does this.</strong> A control engineer setting fuel, fan, and feed on a dryer so moisture hits a target.</p>
<div class="page-columns page-full">
<div id="fig-poster-dryer" class="quarto-float quarto-figure quarto-figure-center anchored page-columns page-full" alt="Poster in four numbered stages plus a footer. One: drawn dryer, fuel fan feed in, two temperatures and moisture out. Two: isometric cube H, output 3 by input 3 by lag L, L is 5 or 15. Three: two inverses, lag-0 slice pseudoinverse versus stacked Einstein Moore-Penrose. Four: two settings, feed about plus 1,200 versus feed about 0. Footer: inverting H for a desired y is a second product; a wrong leftover over-dries a batch or ships it wet.">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-poster-dryer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">
<img src="media/poster-dryer.png" class="img-fluid figure-img column-page" alt="Poster in four numbered stages plus a footer. One: drawn dryer, fuel fan feed in, two temperatures and moisture out. Two: isometric cube H, output 3 by input 3 by lag L, L is 5 or 15. Three: two inverses, lag-0 slice pseudoinverse versus stacked Einstein Moore-Penrose. Four: two settings, feed about plus 1,200 versus feed about 0. Footer: inverting H for a desired y is a second product; a wrong leftover over-dries a batch or ships it wet.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-poster-dryer-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: A dryer with three inputs and three outputs becomes an impulse-response tensor <span class="math inline">\(H\in\mathbb{R}^{3\times3\times L}\)</span>. The lag-0 inverse asks for a 1,200-unit feed dump. The stacked inverse asks for a small correction. Same moisture target.
</figcaption>
</figure>
</div>
</div>
<p>A linear MIMO plant is</p>
<p><span class="math display">\[
y(t)=\sum_{k=0}^{L-1} H_{:,:,k}\,u(t-k).
\]</span></p>
<p><span class="math inline">\(H\)</span> is output <span class="math inline">\(\times\)</span> input <span class="math inline">\(\times\)</span> lag. Fitting <span class="math inline">\(H\)</span> is least squares on a lagged design. That solve is unique for a fixed <span class="math inline">\(L\)</span> when the design has full rank. <span class="math inline">\(L\)</span> is not unique. Inverting <span class="math inline">\(H\)</span> for a control input is a different product, and two products disagree.</p>
<p>Fit <span class="math inline">\(L=5\)</span> and <span class="math inline">\(L=15\)</span> on the centred dryer. Then invert the <span class="math inline">\(L=5\)</span> tensor two ways, on a target taken from the model so the arithmetic is consistent.</p>
<div id="mimo-fit" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>H5 <span class="op">=</span> M.fit_fir(U, Y, n_lags<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>H15 <span class="op">=</span> M.fit_fir(U, Y, n_lags<span class="op">=</span><span class="dv">15</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>Yhat <span class="op">=</span> M.predict(H5, U)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>t_star <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>y_star <span class="op">=</span> Yhat[t_star]</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>u0 <span class="op">=</span> M.invert_lag0(H5, y_star)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>u_st <span class="op">=</span> M.invert_stacked(H5, y_star)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>u0_15 <span class="op">=</span> M.invert_lag0(H15, y_star)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"fit RMSE   L=5 </span><span class="sc">{</span>M<span class="sc">.</span>fit_rmse(H5, U, Y)<span class="sc">:.3f}</span><span class="ss">   L=15 </span><span class="sc">{</span>M<span class="sc">.</span>fit_rmse(H15, U, Y)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cond(H[:,:,0])  L=5 </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>cond(H5[:, :, <span class="dv">0</span>])<span class="sc">:.0f}</span><span class="ss">   L=15 </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>cond(H15[:, :, <span class="dv">0</span>])<span class="sc">:.0f}</span><span class="ss">"</span>)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"target y (centred) </span><span class="sc">{</span>np<span class="sc">.</span>array2string(y_star, precision<span class="op">=</span><span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"lag-0 inverse, L=5   </span><span class="sc">{</span>np<span class="sc">.</span>array2string(u0, precision<span class="op">=</span><span class="dv">2</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"stacked inverse, L=5 </span><span class="sc">{</span>np<span class="sc">.</span>array2string(u_st[:<span class="dv">3</span>], precision<span class="op">=</span><span class="dv">2</span>)<span class="sc">}</span><span class="ss">  (lag 0 of the window)"</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"lag-0 inverse, L=15  </span><span class="sc">{</span>np<span class="sc">.</span>array2string(u0_15, precision<span class="op">=</span><span class="dv">2</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||u0(L=5) - stacked lag0|| </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(u0 <span class="op">-</span> u_st[:<span class="dv">3</span>])<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||u0(L=5) - u0(L=15)||     </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(u0 <span class="op">-</span> u0_15)<span class="sc">:.1f}</span><span class="ss">"</span>)</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"lag-0 reconstructs y  </span><span class="sc">{</span>np<span class="sc">.</span>array2string(H5[:, :, <span class="dv">0</span>] <span class="op">@</span> u0, precision<span class="op">=</span><span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"stacked reconstructs  </span><span class="sc">{</span>np<span class="sc">.</span>array2string(M.apply_window(H5, u_st), precision<span class="op">=</span><span class="dv">3</span>)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>fit RMSE   L=5 1.610   L=15 1.329
cond(H[:,:,0])  L=5 1102   L=15 369
target y (centred) [-6.53  -2.956  0.359]
lag-0 inverse, L=5   [ -30.52   56.31 1262.67]
stacked inverse, L=5 [-2.61  3.07  0.01]  (lag 0 of the window)
lag-0 inverse, L=15  [  -69.69   147.95 11581.81]
||u0(L=5) - stacked lag0|| 1264.1
||u0(L=5) - u0(L=15)||     10319.6
lag-0 reconstructs y  [-6.53  -2.956  0.359]
stacked reconstructs  [-6.53  -2.956  0.359]</code></pre>
</div>
</div>
<p><span class="math inline">\(L=15\)</span> fits the training series a little better than <span class="math inline">\(L=5\)</span>. Both are plausible plants. Their lag-0 inverses, asked for the same <span class="math inline">\(y\)</span>, disagree by thousands of raw-material units.</p>
<p>The <span class="math inline">\(L=5\)</span> lag-0 slice has condition number about <span class="math inline">\(10^3\)</span>. Its inverse reconstructs <span class="math inline">\(y\)</span> and asks for a huge feed. The stacked inverse of the same <span class="math inline">\(H\)</span> asks for a small window. One inverse is a one-step product, <span class="math inline">\(H_{:,:,0}^\dagger y\)</span>. The other is the Einstein / Moore–Penrose inverse of the unfolding <span class="math inline">\(H\in\mathbb{R}^{3\times(3\cdot 5)}\)</span>. Both are legitimate inverses of <span class="math inline">\(H\)</span>. They are different control moves.</p>
<p>A dryer that takes the lag-0 number dumps feed. A dryer that takes the stacked number makes a small correction. The moisture target was the same.</p>
<div id="cell-fig-mimo" class="cell" data-fig-height="3.8" data-fig-width="10" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">3.8</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>im <span class="op">=</span> axes[<span class="dv">0</span>].imshow(H5[:, :, <span class="dv">0</span>], cmap<span class="op">=</span><span class="st">"coolwarm"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xticks(<span class="bu">range</span>(<span class="dv">3</span>), <span class="bu">list</span>(dr[<span class="st">"inputs"</span>]), rotation<span class="op">=</span><span class="dv">20</span>, ha<span class="op">=</span><span class="st">"right"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_yticks(<span class="bu">range</span>(<span class="dv">3</span>), <span class="bu">list</span>(dr[<span class="st">"outputs"</span>]))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"H[:,:,0] at L=5"</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>fig.colorbar(im, ax<span class="op">=</span>axes[<span class="dv">0</span>], fraction<span class="op">=</span><span class="fl">0.046</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>labs <span class="op">=</span> [<span class="st">"fuel"</span>, <span class="st">"fan"</span>, <span class="st">"feed"</span>]</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.arange(<span class="dv">3</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> <span class="fl">0.35</span></span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar(x <span class="op">-</span> w <span class="op">/</span> <span class="dv">2</span>, u0, width<span class="op">=</span>w, color<span class="op">=</span>CORAL, label<span class="op">=</span><span class="st">"lag-0 pinv"</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].bar(x <span class="op">+</span> w <span class="op">/</span> <span class="dv">2</span>, u_st[:<span class="dv">3</span>], width<span class="op">=</span>w, color<span class="op">=</span>TEAL, label<span class="op">=</span><span class="st">"stacked, lag 0"</span>)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xticks(x, labs)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_ylabel(<span class="st">"centred input"</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].legend(frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_title(<span class="st">"two inverses, one target"</span>)</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-mimo" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mimo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-mimo-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mimo-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Lag-0 slice of H at L=5, and the two control inputs it produces for one target. The stacked window is drawn at lag 0 only, so the two bars are the same three actuators.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The coral bars are the one-step inverse. The teal bars are the stacked inverse, lag 0. The feed bars do not fit on the same scale by accident. That gap is the leftover.</p>
</section>
<section id="side-by-side" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="side-by-side"><span class="header-section-number">7</span> Side by side</h2>
<p>Every number below was computed by a cell above.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Problem</th>
<th>Extra structure</th>
<th>What is unique</th>
<th>What is not</th>
<th>What flattening costs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Speech mix</td>
<td>independence, at most one Gaussian</td>
<td>the sources, up to permutation and scale</td>
<td>which signed permutation you keep; FastICA’s finite-sample rotation</td>
<td>PCA inverts the covariance and leaves the cumulant’s rotation</td>
</tr>
<tr class="even">
<td>MovieLens</td>
<td>CP rank <span class="math inline">\(R\)</span></td>
<td>nothing about the holes</td>
<td>the filling. Rank 3 vs rank 8: <em>Terminator</em>, April 1998, 3.1 vs 2.0</td>
<td>user <span class="math inline">\(\times\)</span> movie throws month away; RMSE can look fine</td>
</tr>
<tr class="odd">
<td>Dryer</td>
<td>FIR length <span class="math inline">\(L\)</span>, then a product</td>
<td><span class="math inline">\(H\)</span> at a fixed <span class="math inline">\(L\)</span> when the design is full rank</td>
<td><span class="math inline">\(L\)</span> itself; the control inverse of <span class="math inline">\(H\)</span> (lag-0 vs stacked)</td>
<td>a <span class="math inline">\(3\times 15\)</span> matrix does not say which product you inverted</td>
</tr>
</tbody>
</table>
<p>Two of the three rows say that flattening is a different inverse, not a cheaper one. The ratings row says flattening can win a weak score and still hide a month.</p>
</section>
<section id="constraints" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="constraints"><span class="header-section-number">8</span> Constraints</h2>
<ul>
<li><strong>Speech.</strong> Four seconds at 8 kHz is a short record for a fourth-order statistic. FastICA’s leftover is a finite-sample leftover. The signed-permutation leftover is algebraic and does not go away with more data.</li>
<li><strong>Ratings.</strong> 9% observed. ALS has local minima. A second start at the same rank would move the filling again. RMSE on 959 held cells does not rank a catalogue.</li>
<li><strong>Dryer.</strong> 867 samples. <span class="math inline">\(L=15\)</span> already spends 45 parameters per output. A longer FIR will fit and will invert to a different <span class="math inline">\(u\)</span>. The series is one plant on one week. It is not a licence to retune a dryer from this page.</li>
</ul>
<p>Inverses. Are. Not. Unique. Structure. Picks. One. Downstream. Feels. The. Choice.</p>
</section>
<section id="references" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="references"><span class="header-section-number">9</span> References</h2>
<ul>
<li>Cardoso, J.-F., and Souloumiac, A. (1993). Blind beamforming for non-Gaussian signals. <em>IEE Proceedings F</em> 140(6), 362–370.</li>
<li>Chou, C. T., and Maciejowski, J. M. (1997). <a href="https://doi.org/10.1109/9.599969">System identification using balanced parametrizations</a>. <em>IEEE Transactions on Automatic Control</em> 42(7), 956–974.</li>
<li>De Moor, B. L. R. (ed.). <a href="https://homes.esat.kuleuven.be/~smc/daisy/">DaISy: Database for the Identification of Systems</a>. ESAT/STADIUS, KU Leuven. Dataset 96-016, industrial dryer.</li>
<li>Harper, F. M., and Konstan, J. A. (2015). <a href="https://doi.org/10.1145/2827872">The MovieLens datasets: history and context</a>. <em>ACM Transactions on Interactive Intelligent Systems</em> 5(4), 19.</li>
<li>Hyvärinen, A., and Oja, E. (2000). Independent component analysis: algorithms and applications. <em>Neural Networks</em> 13(4–5), 411–430.</li>
<li>Kolda, T. G., and Bader, B. W. (2009). Tensor decompositions and applications. <em>SIAM Review</em> 51(3), 455–500.</li>
<li>Maciejowski, J. M. (1996). Parameter estimation of multivariable systems using balanced realizations. In Bittanti, S. (ed.), <em>Identification, Adaptation, and Learning</em>. Springer.</li>
<li><a href="https://grouplens.org/datasets/movielens/100k/">MovieLens 100K</a> — GroupLens Research.</li>
<li><a href="https://commons.wikimedia.org/wiki/File:Recording_of_speaker_of_British_English_(Received_Pronunciation).ogg">Recording of speaker of British English (Received Pronunciation)</a> — P. Roach / International Phonetic Association, CC BY-SA 3.0.</li>
<li><a href="https://commons.wikimedia.org/wiki/File:Sv-The_North_Wind_and_the_Sun.ogg">Sv-The North Wind and the Sun</a> — Wikimedia Commons.</li>
<li><a href="https://commons.wikimedia.org/wiki/File:Cdo_northwind_sun_04.ogg">Cdo northwind sun 04</a> — GnuDoyng, public domain.</li>
<li><a href="../tensor-factorizations/">Tensor Factorizations and Tensor Inverses</a> — CP, Tucker, TT, t-SVD, and the four inverses.</li>
<li><a href="../uses-of-tensor-factorizations/">Uses of Tensor Factorizations</a> — the compression case.</li>
<li><a href="../tensor-inverses-in-practice/">Tensor Inverses in Practice</a> — compliance, Pavia, a scan, and Chicago counts.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/tensor-inverse-examples/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>