<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-09-17">
<meta name="description" content="Two mechanisms that give the same mean clearance curve, a history-dependent recurrent-event model that separates them, and the design that makes the contrast causal rather than merely predictive.">

<title>Who Does the Clearing? – Synthetic Musings</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2320c3286543d00a1b02fc8c95bfefbb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-2bf7ad2c2d8ffd45a30263a1fba6e5d1.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Who Does the Clearing? – Synthetic Musings">
<meta property="og:description" content="Two mechanisms that give the same mean clearance curve, a history-dependent recurrent-event model that separates them, and the design that makes the contrast causal rather than merely predictive.">
<meta property="og:image" content="https://project-delphi.github.io/ml-blog/posts/efferocytosis-history-model/cover.png">
<meta property="og:site_name" content="Synthetic Musings">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:title" content="Who Does the Clearing? – Synthetic Musings">
<meta name="twitter:description" content="Two mechanisms that give the same mean clearance curve, a history-dependent recurrent-event model that separates them, and the design that makes the contrast causal rather than merely predictive.">
<meta name="twitter:image" content="https://project-delphi.github.io/ml-blog/posts/efferocytosis-history-model/cover.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="630">
<meta name="twitter:image-width" content="1200">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Synthetic Musings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="Home">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Who Does the Clearing?</h1>
            <p class="subtitle lead">A population uptake curve does not say which macrophages did the work, and an assigned two-wave design does.</p>
                  <div>
        <div class="description">
          Two mechanisms that give the same mean clearance curve, a history-dependent recurrent-event model that separates them, and the design that makes the contrast causal rather than merely predictive.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Bayesian</div>
                <div class="quarto-category">Immunology</div>
                <div class="quarto-category">Simulation</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 17, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#efferocytosis" id="toc-efferocytosis" class="nav-link active" data-scroll-target="#efferocytosis"><span class="header-section-number">1</span> Efferocytosis</a></li>
  <li><a href="#same-mean-different-mechanism" id="toc-same-mean-different-mechanism" class="nav-link" data-scroll-target="#same-mean-different-mechanism"><span class="header-section-number">2</span> Same mean, different mechanism</a></li>
  <li><a href="#a-recurrent-event-intensity" id="toc-a-recurrent-event-intensity" class="nav-link" data-scroll-target="#a-recurrent-event-intensity"><span class="header-section-number">3</span> A recurrent-event intensity</a></li>
  <li><a href="#a-simulated-two-wave-experiment" id="toc-a-simulated-two-wave-experiment" class="nav-link" data-scroll-target="#a-simulated-two-wave-experiment"><span class="header-section-number">4</span> A simulated two-wave experiment</a></li>
  <li><a href="#fitting" id="toc-fitting" class="nav-link" data-scroll-target="#fitting"><span class="header-section-number">5</span> Fitting</a></li>
  <li><a href="#out-of-donor-evaluation" id="toc-out-of-donor-evaluation" class="nav-link" data-scroll-target="#out-of-donor-evaluation"><span class="header-section-number">6</span> Out-of-donor evaluation</a></li>
  <li><a href="#prediction-and-causation" id="toc-prediction-and-causation" class="nav-link" data-scroll-target="#prediction-and-causation"><span class="header-section-number">7</span> Prediction and causation</a></li>
  <li><a href="#design" id="toc-design" class="nav-link" data-scroll-target="#design"><span class="header-section-number">8</span> Design</a></li>
  <li><a href="#constraints" id="toc-constraints" class="nav-link" data-scroll-target="#constraints"><span class="header-section-number">9</span> Constraints</a></li>
  <li><a href="#reproducibility" id="toc-reproducibility" class="nav-link" data-scroll-target="#reproducibility"><span class="header-section-number">10</span> Reproducibility</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">11</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/efferocytosis-history-model/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img" alt="Two cumulative uptake curves lying on top of each other, beside a bar chart showing the per-cell contributions underneath them diverging sharply."></p>
<figcaption>Who Does the Clearing?</figcaption>
</figure>
</div>
<p>A macrophage population clears apoptotic cells at some rate, and that rate is usually all an assay reports. The number is a sum over cells, and a sum has no memory of which cells produced it.</p>
<p>Watch a clearance assay for long enough and the same total uptake can arrive two ways. Experienced macrophages can take on more, so clearance concentrates in the cells that have already eaten. Or experienced macrophages can slow down while fresh cells absorb what they leave, so clearance spreads out. Both trajectories are consistent with continual efferocytosis as it is described, and both give the same population curve. Separating them needs a model of the per-cell event history and a design that assigns the history rather than observing it.</p>
<p>Everything here is simulated. No experimental data were used, and no result below is a claim about a real macrophage population — the point is what an analysis can and cannot recover when the generating process is known exactly.</p>
<section id="efferocytosis" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="efferocytosis"><span class="header-section-number">1</span> Efferocytosis</h2>
<p>Efferocytosis is the recognition, engulfment and disposal of an apoptotic cell by a phagocyte (<a href="https://doi.org/10.1038/s41577-019-0240-6">Doran et al.&nbsp;2020</a>). It runs in stages that are worth keeping separate:</p>
<ul>
<li><strong>Find-me.</strong> Nucleotides and lipids released by the dying cell recruit the phagocyte (<a href="https://doi.org/10.1016/j.immuni.2011.09.004">Ravichandran 2011</a>).</li>
<li><strong>Eat-me.</strong> Exposed phosphatidylserine, read directly or through a bridging molecule, marks the target for engulfment (<a href="https://doi.org/10.1038/nri3607">Poon et al.&nbsp;2014</a>).</li>
<li><strong>Internalisation.</strong> The target is drawn into a phagosome.</li>
<li><strong>Processing.</strong> The phagolysosome degrades the cargo, and the phagocyte metabolises what it recovers.</li>
</ul>
<p>These are not a strict queue. A macrophage can bind one target while still digesting another, so binding, internalisation and processing overlap in time.</p>
<p>Macrophages clear targets repeatedly rather than once, and what happens after the first meal is the part that matters here. Processing the first corpse changes the cell: mitochondrial fission supports continued uptake (<a href="https://doi.org/10.1016/j.cell.2017.08.041">Wang et al.&nbsp;2017</a>), arginine recovered from the cargo is metabolised into polyamines that promote further uptake (<a href="https://doi.org/10.1016/j.cmet.2020.01.001">Yurdagul et al.&nbsp;2020</a>), and loss of the phagocyte’s UCP2 protein blocks continued clearance specifically (<a href="https://doi.org/10.1038/nature10340">Park et al.&nbsp;2011</a>). Against that, a cell carrying undigested cargo has finite capacity.</p>
<p>So a cell’s own history could push its next uptake either way. Prior uptake could prime it, or saturate it. Both are described in the literature, and an assay that reports a population mean cannot tell which one is running.</p>
<p>Neighbours matter too, in two different ways that are easy to conflate. A neighbour that eats a target removes that target, which lowers the opportunity in the local neighbourhood. Separately, metabolites released by apoptotic cells act on surrounding tissue as signals in their own right (<a href="https://doi.org/10.1038/s41586-020-2121-3">Medina et al.&nbsp;2020</a>). The first is depletion; the second is signalling; they are distinguishable only if opportunity is measured.</p>
</section>
<section id="same-mean-different-mechanism" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="same-mean-different-mechanism"><span class="header-section-number">2</span> Same mean, different mechanism</h2>
<p>When targets are limited, the population curve is set by supply, and the allocation underneath it is free.</p>
<p>Two rules draw on one fixed pool of targets. Under priming, cells with prior experience take a larger share; under satiety they take a smaller one and the naive cells absorb the remainder. The pool is what runs out, so both rules eat through the same supply on the same schedule.</p>
<div id="cell-fig-same-mean" class="cell" data-fig-height="3.6" data-fig-width="9" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">3.6</span>))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>steps <span class="op">=</span> np.arange(<span class="bu">len</span>(priming.cumulative))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ax1.plot(steps, priming.cumulative, color<span class="op">=</span>house.ACCENT, lw<span class="op">=</span><span class="fl">2.4</span>, label<span class="op">=</span><span class="st">"priming"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>ax1.plot(steps, satiety.cumulative, color<span class="op">=</span>house.CORAL, lw<span class="op">=</span><span class="fl">1.4</span>, ls<span class="op">=</span><span class="st">"--"</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>         label<span class="op">=</span><span class="st">"satiety + redistribution"</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>ax1.set_xlabel(<span class="st">"time step"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>ax1.set_ylabel(<span class="st">"cumulative targets cleared"</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>ax1.legend(loc<span class="op">=</span><span class="st">"lower right"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>ax2.bar([<span class="st">"priming"</span>, <span class="st">"satiety +</span><span class="ch">\n</span><span class="st">redistribution"</span>], [share_p, share_s],</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>[house.ACCENT, house.CORAL], width<span class="op">=</span><span class="fl">0.55</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>ax2.axhline(<span class="fl">0.35</span>, color<span class="op">=</span>house.MUTED, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>ax2.set_ylabel(<span class="st">"share of uptake by experienced cells"</span>)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>ax2.set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>ax2.annotate(<span class="st">"experienced cells are 35</span><span class="sc">% o</span><span class="st">f the population"</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>             xy<span class="op">=</span>(<span class="fl">0.5</span>, <span class="fl">0.38</span>), xycoords<span class="op">=</span>(<span class="st">"axes fraction"</span>, <span class="st">"data"</span>),</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>             ha<span class="op">=</span><span class="st">"center"</span>, color<span class="op">=</span>house.MUTED, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"final totals differ by </span><span class="sc">{</span>total_gap<span class="sc">:.0f}</span><span class="ss"> targets"</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"experienced-cell share: priming </span><span class="sc">{</span>share_p<span class="sc">:.3f}</span><span class="ss">, satiety </span><span class="sc">{</span>share_s<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-same-mean" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two panels. The left shows two cumulative curves that rise together and overlap so closely that one hides the other. The right shows two bars of very different height.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-same-mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-same-mean-output-1.png" class="img-fluid figure-img" alt="Two panels. The left shows two cumulative curves that rise together and overlap so closely that one hides the other. The right shows two bars of very different height.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-same-mean-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Simulated supply-limited clearance of 900 targets by 200 cells under two allocation rules. Left: cumulative population uptake through time under priming and under satiety plus redistribution. Right: the share of all uptake taken by the 35% of cells designated as experienced, under each rule.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>final totals differ by 0 targets
experienced-cell share: priming 0.602, satiety 0.144</code></pre>
</div>
</div>
<p>The two population curves are identical, not merely close: the pool empties on a fixed schedule, so the allocation rule cannot change the total. That is the construction, not a finding — it is what lets the figure vary the mechanism with the population curve held exactly still. The share of the work done by experienced cells is 0.60 against 0.14 — a factor of 4.2. The mean is the same; the mechanism is not.</p>
</section>
<section id="a-recurrent-event-intensity" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="a-recurrent-event-intensity"><span class="header-section-number">3</span> A recurrent-event intensity</h2>
<p>Uptake by one cell is a recurrent event, so the object to model is an intensity: the instantaneous rate of the next uptake given everything that has happened to that cell so far (<a href="https://doi.org/10.1214/aos/1176345976">Andersen and Gill 1982</a>, <a href="https://doi.org/10.1007/978-0-387-69810-6">Cook and Lawless 2007</a>).</p>
<p><span class="math display">\[
\lambda_i(t) = \lambda_0 \exp\Bigl\{ f_1\bigl(\ell_i(t)\bigr) + f_2\bigl(g_i(t)\bigr)
+ f_3\bigl(n_i(t)\bigr) + u_{d(i)} + w_{j(i)} \Bigr\} \cdot o_i(t)
\]</span></p>
<p>Each term carries a separate piece of biology.</p>
<ul>
<li><span class="math inline">\(\ell_i(t)\)</span> — <strong>current load</strong>, targets internalised but not yet processed. This is where priming and satiety compete, so <span class="math inline">\(f_1\)</span> is the curve of interest.</li>
<li><span class="math inline">\(g_i(t)\)</span> — <strong>time since the last uptake</strong>. <span class="math inline">\(f_2\)</span> is a refractory term: a cell that has just engulfed something is briefly occupied.</li>
<li><span class="math inline">\(n_i(t)\)</span> — <strong>neighbour load</strong>. <span class="math inline">\(f_3\)</span> is appetite changed by neighbours through signalling, over and above their effect on supply.</li>
<li><span class="math inline">\(u_{d(i)}\)</span>, <span class="math inline">\(w_{j(i)}\)</span> — donor and well random effects. Donors differ, and so do wells within a donor.</li>
<li><span class="math inline">\(o_i(t)\)</span> — <strong>opportunity</strong>: the number of unconsumed targets within reach of cell <span class="math inline">\(i\)</span>.</li>
</ul>
<p>The opportunity term enters as an offset with coefficient fixed at one, not as a fitted covariate. This is the load-bearing choice. A cell in a depleted neighbourhood eats little because there is nothing to eat, and without the offset that cell’s low count is read as low appetite. Low uptake is not low appetite; the offset is what keeps the two apart, and it is also what makes depletion and neighbour signalling separately identifiable.</p>
</section>
<section id="a-simulated-two-wave-experiment" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="a-simulated-two-wave-experiment"><span class="header-section-number">4</span> A simulated two-wave experiment</h2>
<p>The design delivers the <strong>same first-wave target budget</strong> two ways, then gives every arm the same second wave.</p>
<ul>
<li><strong><code>broad</code></strong> — the first-wave targets are scattered across the well.</li>
<li><strong><code>focal</code></strong> — the same number of targets, packed around a subset of cells fixed in advance.</li>
<li><strong><code>none</code></strong> — no first wave, as a reference for what an inexperienced population does.</li>
</ul>
<p>After the first wave there is a wash, a three-hour interval, and a second wave common to every arm. 6 donors each contribute one well to each arm: 18 wells and 1440 cells in total. Cells are lost from tracking at a constant hazard, and 12.8% of them are censored before the end.</p>
<p>The generating process gives <span class="math inline">\(f_1\)</span> a rise then a fall — priming at low load, satiety at high — and <span class="math inline">\(f_2\)</span> a refractory dip that decays with a time constant of 0.75 h. Digestion clears a target in 4 h, which is slow relative to the interval between waves; that is what carries first-wave history into the second wave rather than letting it wash out. Neighbour effects are generated twice: once by depletion alone, where <span class="math inline">\(f_3\)</span> is flat at zero and neighbours act only through the offset, and once by depletion plus signalling.</p>
<div id="cell-fig-raster" class="cell" data-fig-height="5" data-fig-width="9" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">2</span>, <span class="dv">1</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">5.0</span>), sharex<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>panel <span class="op">=</span> exp.panel</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, arm <span class="kw">in</span> <span class="bu">zip</span>(axes, (<span class="st">"broad"</span>, <span class="st">"focal"</span>)):</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    sub <span class="op">=</span> panel[(panel[<span class="st">"arm"</span>] <span class="op">==</span> arm) <span class="op">&amp;</span> (panel[<span class="st">"donor"</span>] <span class="op">==</span> <span class="dv">0</span>)]</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> (</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>        cells[(cells[<span class="st">"arm"</span>] <span class="op">==</span> arm) <span class="op">&amp;</span> (cells[<span class="st">"donor"</span>] <span class="op">==</span> <span class="dv">0</span>)]</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>        .sort_values(<span class="st">"wave1_uptake"</span>, ascending<span class="op">=</span><span class="va">False</span>)[<span class="st">"uid"</span>].to_numpy()[:<span class="dv">60</span>]</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    rank <span class="op">=</span> {u: r <span class="cf">for</span> r, u <span class="kw">in</span> <span class="bu">enumerate</span>(order)}</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    ev <span class="op">=</span> sub[(sub[<span class="st">"y"</span>] <span class="op">&gt;</span> <span class="dv">0</span>) <span class="op">&amp;</span> (sub[<span class="st">"uid"</span>].isin(rank))]</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    ax.axvspan(sim.WAVE1[<span class="dv">0</span>] <span class="op">*</span> sim.DT, sim.WAVE1[<span class="dv">1</span>] <span class="op">*</span> sim.DT, color<span class="op">=</span>house.RULE, alpha<span class="op">=</span><span class="fl">0.55</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    ax.axvspan(sim.WAVE2[<span class="dv">0</span>] <span class="op">*</span> sim.DT, sim.WAVE2[<span class="dv">1</span>] <span class="op">*</span> sim.DT, color<span class="op">=</span>house.RULE, alpha<span class="op">=</span><span class="fl">0.55</span>)</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    ax.scatter(</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>        ev[<span class="st">"bin"</span>] <span class="op">*</span> sim.DT, [rank[u] <span class="cf">for</span> u <span class="kw">in</span> ev[<span class="st">"uid"</span>]],</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>        s<span class="op">=</span><span class="dv">5</span>, color<span class="op">=</span>house.ARM_COLOUR[arm], alpha<span class="op">=</span><span class="fl">0.85</span>, linewidths<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="ss">f"</span><span class="sc">{</span>arm<span class="sc">}</span><span class="ch">\n</span><span class="ss">cell"</span>)</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    ax.set_ylim(<span class="op">-</span><span class="dv">1</span>, <span class="dv">60</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    ax.grid(<span class="va">False</span>)</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">1</span>].set_xlabel(<span class="st">"hours"</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mean_w1.<span class="bu">round</span>(<span class="dv">2</span>).to_string())</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mean_w2.<span class="bu">round</span>(<span class="dv">2</span>).to_string())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-raster" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two stacked panels of dot rows. In the upper panel marks are spread evenly across rows during the first shaded band. In the lower panel the marks in the first band are concentrated in the rows at the top.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-raster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-raster-output-1.png" class="img-fluid figure-img" alt="Two stacked panels of dot rows. In the upper panel marks are spread evenly across rows during the first shaded band. In the lower panel the marks in the first band are concentrated in the rows at the top.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-raster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Simulated uptake events for 60 cells drawn from one donor, in the broad and focal arms. Each row is one cell, each mark one uptake. The shaded bands are the two target waves; the gap between them is the wash and interval. Cells are ordered by first-wave uptake.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>arm
broad    2.79
focal    3.21
none     0.00
arm
broad    3.49
focal    3.45
none     3.51</code></pre>
</div>
</div>
<p>Mean first-wave uptake is 2.79 per cell in <code>broad</code> and 3.21 in <code>focal</code>, from the same delivered budget. Mean second-wave uptake is 3.49 against 3.45 — a difference of 1.1%. The population readout is nearly blind to the manipulation, which is the point of running it.</p>
</section>
<section id="fitting" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="fitting"><span class="header-section-number">5</span> Fitting</h2>
<p>The model is fitted on the second wave, with first-wave history carried in as covariates. The counting-process likelihood factorises into independent contributions on any partition of follow-up, so the events are aggregated to 1.5-hour blocks — about twice the refractory time constant, chosen on that scale rather than by looking at the fit. That gives 7,805 rows.</p>
<p>Two models, fixed before either was run:</p>
<ul>
<li><strong>Baseline</strong> — negative-binomial, linear in load, gap and <span class="math inline">\(\log(1 + \text{neighbour
load})\)</span>, with the same offset.</li>
<li><strong>Main model</strong> — the same likelihood with <span class="math inline">\(f_1\)</span>, <span class="math inline">\(f_2\)</span> and <span class="math inline">\(f_3\)</span> as penalised cubic B-splines. The penalty is a second-order random walk on the basis coefficients, which is the P-spline prior (<a href="https://doi.org/10.1201/9781315370279">Wood 2017</a>), written non-centred so the sampler sees unit-scale parameters. Fitted in PyMC (<a href="https://doi.org/10.7717/peerj-cs.1516">Abril-Pla et al.&nbsp;2023</a>), with donor and well random effects.</li>
</ul>
<p>The two are fitted by different machinery, and that matters for what the comparison means. The smooths and their credible bands come from the Bayesian fit, random effects included. The model comparison in the next section refits <strong>both</strong> models by maximum likelihood <strong>without</strong> random effects, because full leave-one-donor-out on two Bayesian models was out of compute budget. The approximation is the same on both sides, so the comparison is fair, but it is not a comparison of the two models exactly as specified here.</p>
<div id="fit-gam" class="cell" data-execution_count="7">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> nutpie</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.perf_counter()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>weights <span class="op">=</span> np.ones(<span class="bu">len</span>(fit_panel))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>compiled <span class="op">=</span> nutpie.compile_pymc_model(fitting.gam_model(design, weights))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># `cores` is pinned, not left to the machine. nutpie is bit-reproducible for a</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># fixed seed only when the chain-to-core allocation is also fixed; leaving it to</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># whatever the host has free moves the posterior summaries in the last digit.</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>trace <span class="op">=</span> nutpie.sample(</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    compiled, chains<span class="op">=</span><span class="dv">2</span>, cores<span class="op">=</span><span class="dv">2</span>, draws<span class="op">=</span><span class="dv">300</span>, tune<span class="op">=</span><span class="dv">300</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    seed<span class="op">=</span><span class="dv">20260917</span>, progress_bar<span class="op">=</span><span class="va">False</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> lap(<span class="st">"sample"</span>, t0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="cell-fig-smooths" class="cell" data-fig-height="3.6" data-fig-width="9" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>fig, (ax1, ax2) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="fl">3.6</span>))</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, grid, draws, truth, xlab, title <span class="kw">in</span> (</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    (ax1, grid_load, d_load, true_load, <span class="st">"load (undigested targets)"</span>, <span class="st">"$f_1$: load"</span>),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>    (ax2, grid_gap, d_gap, true_gap, <span class="st">"hours since last uptake"</span>, <span class="st">"$f_2$: refractory"</span>),</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>    lo, hi <span class="op">=</span> np.quantile(draws, [<span class="fl">0.025</span>, <span class="fl">0.975</span>], axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    ax.fill_between(grid, lo, hi, color<span class="op">=</span>house.ACCENT, alpha<span class="op">=</span><span class="fl">0.20</span>, linewidth<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    ax.plot(grid, draws.mean(<span class="dv">0</span>), color<span class="op">=</span>house.ACCENT, lw<span class="op">=</span><span class="fl">2.0</span>, label<span class="op">=</span><span class="st">"estimated"</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    ax.plot(grid, truth, color<span class="op">=</span>house.INK, lw<span class="op">=</span><span class="fl">1.4</span>, ls<span class="op">=</span><span class="st">"--"</span>, label<span class="op">=</span><span class="st">"generating"</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(xlab)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">"contribution to log intensity"</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    ax.set_title(title)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>ax1.legend(loc<span class="op">=</span><span class="st">"lower left"</span>)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"f1 RMSE </span><span class="sc">{</span>rmse_load<span class="sc">:.3f}</span><span class="ss">, 95% band covers </span><span class="sc">{</span>cover_load<span class="sc">:.0%}</span><span class="ss"> of the grid"</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"f2 RMSE </span><span class="sc">{</span>rmse_gap<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"estimated f1 peak at load </span><span class="sc">{</span>peak_est<span class="sc">:.2f}</span><span class="ss">; generating peak at </span><span class="sc">{</span>peak_true<span class="sc">:.2f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-smooths" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two panels, each with a dashed line, a solid line close to it, and a shaded band around the solid line that widens towards the right edge.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-smooths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-smooths-output-1.png" class="img-fluid figure-img" alt="Two panels, each with a dashed line, a solid line close to it, and a shaded band around the solid line that widens towards the right edge.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-smooths-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Estimated against generating smooths from the simulated depletion-only experiment, on the log-intensity scale. Left: the load term, rising at low load and falling at high load. Right: the refractory term against time since the last uptake. Bands are 95% credible intervals; both curves are centred over the fitted rows.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>f1 RMSE 0.339, 95% band covers 18% of the grid
f2 RMSE 0.233
estimated f1 peak at load 3.34; generating peak at 1.62</code></pre>
</div>
</div>
<p>The load term recovers its <strong>sign pattern</strong> and not much more. The estimate rises then falls, as the generating curve does, so the qualitative claim that priming gives way to satiety survives. The quantitative recovery is poor: the estimated peak sits at load 3.3 against a generating peak at 1.6, root-mean-square error is 0.339 on the log-intensity scale, and the 95% credible band covers the true curve over only 18% of the grid.</p>
<p>That last number is the honest headline. A band that excludes the truth over 82% of the range is <strong>under-covering</strong>, so the intervals here are too narrow to be taken at face value. The random-walk penalty is doing more shrinking than the data warrant, and the 1.5-hour aggregation blurs the covariate within each block. The refractory term is better behaved, at root-mean-square error 0.233. Only 1.6% of rows carry a load above 4, which is where the band is widest and the estimate worst.</p>
<p>The estimated dispersion is effectively Poisson: with the opportunity offset in place, there is no extra-Poisson variation left for the negative binomial to absorb. That estimate comes from a fixed-effect Poisson fit on the same design, not from the Bayesian model’s own dispersion posterior. The negative binomial nests the Poisson, so this costs nothing, but it is worth saying rather than reporting a dispersion that is doing no work.</p>
</section>
<section id="out-of-donor-evaluation" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="out-of-donor-evaluation"><span class="header-section-number">6</span> Out-of-donor evaluation</h2>
<p>The margin was fixed before any model was fitted: <strong>keep the spline model only if it beats the baseline by more than 4 log points and by more than twice the standard error of the difference.</strong> Both conditions, not either.</p>
<div id="lodo" class="cell" data-execution_count="10">
<details open="" class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.perf_counter()</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>folds <span class="op">=</span> fitting.lodo_glm(fit_panel, design, alpha_hat)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>score <span class="op">=</span> fitting.score_summary(folds)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>calib <span class="op">=</span> fitting.calibration_table(fit_panel, design, alpha_hat)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> lap(<span class="st">"evaluation"</span>, t0)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>kept <span class="op">=</span> (score[<span class="st">"diff"</span>] <span class="op">&gt;</span> <span class="dv">4</span>) <span class="kw">and</span> (score[<span class="st">"diff"</span>] <span class="op">&gt;</span> <span class="dv">2</span> <span class="op">*</span> score[<span class="st">"se"</span>])</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"spline  </span><span class="sc">{</span>score[<span class="st">'gam'</span>]<span class="sc">:9.1f}</span><span class="ss">"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"linear  </span><span class="sc">{</span>score[<span class="st">'linear'</span>]<span class="sc">:9.1f}</span><span class="ss">"</span>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"diff    </span><span class="sc">{</span>score[<span class="st">'diff'</span>]<span class="sc">:9.2f}</span><span class="ss">"</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  se     </span><span class="sc">{</span>score[<span class="st">'se'</span>]<span class="sc">:9.2f}</span><span class="ss">  (across </span><span class="sc">{</span>score[<span class="st">'n_donors'</span>]<span class="sc">}</span><span class="ss"> donors, the resampling unit)"</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"  se_row </span><span class="sc">{</span>score[<span class="st">'se_row'</span>]<span class="sc">:9.2f}</span><span class="ss">  (across </span><span class="sc">{</span>score[<span class="st">'n'</span>]<span class="sc">}</span><span class="ss"> rows, which are not independent)"</span>)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"margin met: </span><span class="sc">{</span>kept<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>spline    -7818.0
linear    -7827.3
diff         9.30
  se          3.63  (across 6 donors, the resampling unit)
  se_row      5.78  (across 7805 rows, which are not independent)
margin met: True</code></pre>
</div>
</div>
<p>Each donor is held out in turn, both models are refitted by maximum likelihood on the remaining donors, and the held-out donor’s counts are scored. These are <strong>plug-in log scores at the fitted coefficients, not expected log predictive densities</strong> (<a href="https://doi.org/10.1007/s11222-016-9696-4">Vehtari et al.&nbsp;2017</a>): they ignore coefficient uncertainty, carry no random effects, and predict the held-out donor at the average donor. The approximation is identical for both models, so the comparison is fair, but neither number is an ELPD. The scoring rule is the log score, which is strictly proper (<a href="https://doi.org/10.1198/016214506000001437">Gneiting and Raftery 2007</a>). Both fits carry a small ridge on the non-intercept columns, because an unpenalised spline GLM extrapolates without limit on a fold whose training donors do not span the knot range. The standard error is taken across donors, the unit that is actually resampled; the row-wise figure is printed beside it and is the larger of the two here.</p>
<p>The spline model scores 9.3 log points above the baseline with a standard error of 3.6, so it meets the pre-registered margin. Recovering the shape of <span class="math inline">\(f_1\)</span> and predicting a new donor better are different achievements, and on this simulation both hold.</p>
<div id="cell-fig-calibration" class="cell" data-fig-height="4" data-fig-width="6.2" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="fl">4.0</span>))</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, colour, label <span class="kw">in</span> (</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    (<span class="st">"gam"</span>, house.ACCENT, <span class="st">"spline"</span>), (<span class="st">"linear"</span>, house.CORAL, <span class="st">"linear baseline"</span>),</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>):</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    sub <span class="op">=</span> calib[calib[<span class="st">"model"</span>] <span class="op">==</span> name]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    ax.errorbar(</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>        sub[<span class="st">"predicted"</span>], sub[<span class="st">"observed"</span>], yerr<span class="op">=</span>sub[<span class="st">"se"</span>],</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        fmt<span class="op">=</span><span class="st">"o"</span>, ms<span class="op">=</span><span class="dv">5</span>, lw<span class="op">=</span><span class="fl">1.2</span>, color<span class="op">=</span>colour, label<span class="op">=</span>label, capsize<span class="op">=</span><span class="dv">2</span>,</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>lims <span class="op">=</span> [</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>    <span class="bu">min</span>(calib[<span class="st">"predicted"</span>].<span class="bu">min</span>(), calib[<span class="st">"observed"</span>].<span class="bu">min</span>()) <span class="op">*</span> <span class="fl">0.8</span>,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>    <span class="bu">max</span>(calib[<span class="st">"predicted"</span>].<span class="bu">max</span>(), calib[<span class="st">"observed"</span>].<span class="bu">max</span>()) <span class="op">*</span> <span class="fl">1.2</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>ax.plot(lims, lims, ls<span class="op">=</span><span class="st">"--"</span>, color<span class="op">=</span>house.MUTED, lw<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>ax.set_xscale(<span class="st">"log"</span>)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>ax.set_yscale(<span class="st">"log"</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"predicted uptake per block"</span>)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"observed uptake per block"</span>)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"upper left"</span>)</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-calibration" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A scatter of points with error bars lying close to a dashed diagonal line, in two colours, on log-scaled axes.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-calibration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-calibration-output-1.png" class="img-fluid figure-img" alt="A scatter of points with error bars lying close to a dashed diagonal line, in two colours, on log-scaled axes.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-calibration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Held-out donor calibration for both models on the simulated experiment. Points are bins of predicted rate; the vertical extent is one standard error of the observed mean. The diagonal is perfect calibration.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="prediction-and-causation" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="prediction-and-causation"><span class="header-section-number">7</span> Prediction and causation</h2>
<p>Within an arm, a cell’s load is observed, not assigned. Cells that are intrinsically avid eat more in the first wave <em>and</em> more in the second, so the observed relationship between history and later uptake is confounded by that avidity — which no instrument measures.</p>
<p>Latent avidity correlates 0.41 with first-wave uptake and 0.43 with second-wave uptake. Regressing later uptake on observed history gives a slope of 0.0941; holding the latent term fixed — which the simulation can do and an experiment cannot — gives 0.0663. The observed-load curve is biased by 42%.</p>
<p>The assigned arm is different. Arm is randomised across donors, so the broad-versus-focal contrast is a causal contrast of delivery patterns whatever avidity does (<a href="https://miguelhernan.org/whatifbook">Hernan and Robins 2020</a>). The quantity it moves is not the mean.</p>
<div id="cell-fig-share" class="cell" data-fig-height="4" data-fig-width="6.4" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.4</span>, <span class="fl">4.0</span>))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>order <span class="op">=</span> [<span class="st">"broad"</span>, <span class="st">"focal"</span>, <span class="st">"none"</span>]</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>means <span class="op">=</span> [<span class="bu">float</span>(share_by_arm[a]) <span class="cf">for</span> a <span class="kw">in</span> order]</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>ax.bar(order, means, color<span class="op">=</span>[house.ARM_COLOUR[a] <span class="cf">for</span> a <span class="kw">in</span> order], width<span class="op">=</span><span class="fl">0.55</span>, alpha<span class="op">=</span><span class="fl">0.75</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, arm <span class="kw">in</span> <span class="bu">enumerate</span>(order):</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    pts <span class="op">=</span> ns[ns[<span class="st">"arm"</span>] <span class="op">==</span> arm][<span class="st">"share"</span>].to_numpy()</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    ax.scatter(</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>        np.full(pts.size, i) <span class="op">+</span> np.linspace(<span class="op">-</span><span class="fl">0.12</span>, <span class="fl">0.12</span>, pts.size),</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>        pts, s<span class="op">=</span><span class="dv">26</span>, color<span class="op">=</span>house.INK, zorder<span class="op">=</span><span class="dv">3</span>, linewidths<span class="op">=</span><span class="dv">0</span>,</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"share of second-wave uptake</span><span class="ch">\n</span><span class="st">from first-wave-naive cells"</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="fl">1.08</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(share_by_arm.<span class="bu">round</span>(<span class="dv">3</span>).to_string())</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"logit contrast focal - broad = </span><span class="sc">{</span>contrast_logit<span class="sc">:.2f}</span><span class="ss">  95% CI [</span><span class="sc">{</span>ci[<span class="dv">0</span>]<span class="sc">:.2f}</span><span class="ss">, </span><span class="sc">{</span>ci[<span class="dv">1</span>]<span class="sc">:.2f}</span><span class="ss">]"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-share" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A bar chart of three bars of very different height, with individual donor points scattered over each bar.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-share-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-share-output-1.png" class="img-fluid figure-img" alt="A bar chart of three bars of very different height, with individual donor points scattered over each bar.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-share-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Share of second-wave uptake taken by cells that ate nothing in the first wave, by assigned arm, across the simulated donors. Points are donors; bars are the donor mean. The no-first-wave arm is at one by construction and is shown for scale.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>arm
broad    0.043
focal    0.169
none     1.000
logit contrast focal - broad = 1.58  95% CI [0.98, 2.18]</code></pre>
</div>
</div>
<p>Naive cells supply 4.3% of second-wave uptake in <code>broad</code> and 16.9% in <code>focal</code>, from the same delivered budget and with second-wave means that differ by under two percent. The logit contrast is 1.58 (95% CI 0.98 to 2.18, donor bootstrap).</p>
<p>One caution about that readout. A share is a composition, and a composition moves when <em>any</em> part moves (<a href="https://doi.org/10.3389/fmicb.2017.02224">Gloor et al.&nbsp;2017</a>). The naive-cell share can rise because naive cells ate more or because experienced cells ate less, and those are different mechanisms. Relative abundance is not flux: the share needs the total beside it, which is why the second-wave totals are reported above.</p>
</section>
<section id="design" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="design"><span class="header-section-number">8</span> Design</h2>
<p>What a design has to record, if this model is to be fitted at all:</p>
<ul>
<li><strong>Per-cell event times</strong>, not endpoint counts. The intensity is defined on the history.</li>
<li><strong>Two distinguishable waves.</strong> Separate labels are what make a second-wave event attributable and make “naive” a measurable category.</li>
<li><strong>Targets within reach.</strong> The opportunity offset is not optional, and it cannot be reconstructed after the fact.</li>
<li><strong>Viability and tracking loss.</strong> A cell that stops being tracked is censored, not a cell that stopped eating.</li>
<li><strong>Assigned delivery.</strong> Observed history is confounded; assigned delivery is not.</li>
</ul>
<div id="cell-fig-power" class="cell" data-fig-height="3.8" data-fig-width="6.2" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> time.perf_counter()</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>power <span class="op">=</span> fitting.power_curve([<span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">6</span>, <span class="dv">8</span>], n_rep<span class="op">=</span><span class="dv">200</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>t0 <span class="op">=</span> lap(<span class="st">"power"</span>, t0)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="fl">6.2</span>, <span class="fl">3.8</span>))</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>ax.plot(power[<span class="st">"donors"</span>], power[<span class="st">"power"</span>], <span class="st">"o-"</span>, color<span class="op">=</span>house.ACCENT, lw<span class="op">=</span><span class="fl">2.0</span>, ms<span class="op">=</span><span class="dv">6</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="fl">0.8</span>, color<span class="op">=</span>house.MUTED, ls<span class="op">=</span><span class="st">"--"</span>, lw<span class="op">=</span><span class="fl">1.2</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>ax.annotate(<span class="st">"80%"</span>, xy<span class="op">=</span>(power[<span class="st">"donors"</span>].<span class="bu">max</span>(), <span class="fl">0.8</span>), xytext<span class="op">=</span>(<span class="op">-</span><span class="dv">24</span>, <span class="dv">6</span>),</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>            textcoords<span class="op">=</span><span class="st">"offset points"</span>, color<span class="op">=</span>house.MUTED, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="st">"donors"</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>ax.set_ylabel(<span class="st">"probability of detection"</span>)</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="fl">1.05</span>)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>fig.tight_layout()</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(power.to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-power" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A rising curve of points against number of donors, flattening near the top of the panel, with a horizontal dashed reference line.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-power-output-1.png" class="img-fluid figure-img" alt="A rising curve of points against number of donors, flattening near the top of the panel, with a horizontal dashed reference line.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-power-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Simulated probability of detecting the assigned broad-versus-focal contrast in the naive-cell share, against the number of donors. Each point is 200 simulated experiments tested with a donor-paired t-test on the logit share at the 5% level.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> donors  power  n_rep
      3  0.195    200
      4  0.485    200
      5  0.675    200
      6  0.825    200
      8  0.955    200</code></pre>
</div>
</div>
<p>6 donors reach 80% power for this contrast at this effect size. That is a statement about the naive-cell share; the same experiment is badly underpowered for the population mean, which the design deliberately holds still. The test used here is a donor-paired comparison, which is cheaper than the fitted intensity model and therefore conservative.</p>
</section>
<section id="constraints" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="constraints"><span class="header-section-number">9</span> Constraints</h2>
<ul>
<li><strong>The generating process is mine.</strong> The smooths, the digestion time and the neighbour radius were chosen to make the identification problem visible, not measured from an assay. Recovering <span class="math inline">\(f_1\)</span> here says the estimator works when the model is true; it says nothing about how it behaves under a mechanism nobody wrote down. <strong>This is modelling opinion, not an empirical finding.</strong></li>
<li><strong>The evaluation is a plug-in score, not an ELPD, and not of the fitted models.</strong> Full leave-one-donor-out with both Bayesian models was out of compute budget, so the fold comparison refits by maximum likelihood with no random effects. Coefficient uncertainty is ignored and the held-out donor is predicted at the average donor. The smooths shown above come from the Bayesian fit; the score below does not.</li>
<li><strong>The score is sensitive to the aggregation grid.</strong> The 1.5 h block was chosen against the refractory time constant, before looking at the fit; a coarser grid narrows the gap between the two models substantially. A comparison that moves with a nuisance choice should be reported with that choice, not without it.</li>
<li><strong>Six donors is a small random-effect sample.</strong> The donor standard deviation is estimated from six values, and its posterior is correspondingly wide.</li>
<li><strong>The credible bands under-cover.</strong> The 95% band for <span class="math inline">\(f_1\)</span> contains the generating curve over 18% of its range. Reported rather than tuned away: a penalty prior and an aggregation grid both chosen before fitting should not be adjusted until the intervals look right. The shape conclusion stands; the interval widths do not.</li>
<li><strong>The penalty shrinks more than a P-spline should.</strong> The random walk is written <code>tau * cumsum(cumsum(z))</code>, which puts the constant and linear components of each smooth under the same <code>tau</code> as the curvature. A standard P-spline leaves that two-dimensional null space unpenalised. The result is asymmetric in the basis index — the first coefficient is pinned hardest — which is a specific structural reason the estimated peak sits to the right of the true one, over and above block blurring.</li>
<li><strong>The folds are not fully held out.</strong> The dispersion estimate, the spline knots and the covariate standardisation are all computed on the full panel, so a held-out donor contributes to them. It is the same leakage on both sides, so the comparison stays fair, but each absolute score is optimistic.</li>
<li><strong><span class="math inline">\(f_3\)</span> is the weakest of the three.</strong> Depletion and signalling are separable in principle through the offset, but the two generating modes are not compared head to head here.</li>
<li><strong>Simulated tracking loss is non-informative.</strong> Real loss is not: a cell that dies after over-eating is censored precisely because of its history, and that breaks the censoring assumption this model relies on.</li>
<li><strong>One label-free imaging method is cited as an example only</strong> (<a href="https://doi.org/10.7554/eLife.77373">Neto et al.&nbsp;2022</a>). Nothing here rests on it.</li>
</ul>
</section>
<section id="reproducibility" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="reproducibility"><span class="header-section-number">10</span> Reproducibility</h2>
<div id="session" class="cell" data-execution_count="16">
<div class="cell-output cell-output-stdout">
<pre><code>toy             0.0 s
simulate        0.4 s
design          1.2 s
sample         86.8 s
evaluation      0.6 s
power         110.4 s
total         201.2 s

python 3.12.13  numpy 2.5.3  pandas 3.0.5
pymc 6.3.2  nutpie 0.16.11</code></pre>
</div>
</div>
<p>Every seed is fixed in <code>src/sim.py</code> and at each call site, and the post’s numbers are computed at render time and interpolated into the prose, so a figure and the sentence beside it cannot drift apart.</p>
<p>The simulation, the maximum-likelihood scoring and the power curve are deterministic and reproduce exactly. The posterior summaries need one more thing: nutpie is bit-reproducible for a fixed seed only when the chain-to-core allocation is fixed too, so <code>cores</code> is pinned alongside <code>chains</code> above. Left to the host, the smooth summaries moved in the last reported digit between runs on this machine. To rerun it, build the environment in <code>requirements.txt</code>, register the kernel, and render this document.</p>
<p>Means. Hide. Mechanisms. Offsets. Restore. Opportunity. Assignment. Beats. Observation. Every. Time.</p>
</section>
<section id="references" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="references"><span class="header-section-number">11</span> References</h2>
<ul>
<li>Abril-Pla, O., et al.&nbsp;(2023). PyMC: a modern, and comprehensive probabilistic programming framework in Python. <em>PeerJ Computer Science</em> 9: e1516. <a href="https://doi.org/10.7717/peerj-cs.1516">doi:10.7717/peerj-cs.1516</a></li>
<li>Andersen, P. K., and Gill, R. D. (1982). Cox’s regression model for counting processes: a large sample study. <em>The Annals of Statistics</em> 10(4). <a href="https://doi.org/10.1214/aos/1176345976">doi:10.1214/aos/1176345976</a></li>
<li>Cook, R. J., and Lawless, J. F. (2007). <em>The Statistical Analysis of Recurrent Events</em>. Springer. <a href="https://doi.org/10.1007/978-0-387-69810-6">doi:10.1007/978-0-387-69810-6</a></li>
<li>Doran, A. C., Yurdagul, A., and Tabas, I. (2020). Efferocytosis in health and disease. <em>Nature Reviews Immunology</em> 20(4): 254-267. <a href="https://doi.org/10.1038/s41577-019-0240-6">doi:10.1038/s41577-019-0240-6</a></li>
<li>Gloor, G. B., Macklaim, J. M., Pawlowsky-Glahn, V., and Egozcue, J. J. (2017). Microbiome datasets are compositional: and this is not optional. <em>Frontiers in Microbiology</em> 8: 2224. <a href="https://doi.org/10.3389/fmicb.2017.02224">doi:10.3389/fmicb.2017.02224</a></li>
<li>Gneiting, T., and Raftery, A. E. (2007). Strictly proper scoring rules, prediction, and estimation. <em>Journal of the American Statistical Association</em> 102(477): 359-378. <a href="https://doi.org/10.1198/016214506000001437">doi:10.1198/016214506000001437</a></li>
<li>Hernan, M. A., and Robins, J. M. (2020). <em>Causal Inference: What If</em>. Chapman and Hall/CRC. <a href="https://miguelhernan.org/whatifbook">miguelhernan.org/whatifbook</a></li>
<li>Medina, C. B., et al.&nbsp;(2020). Metabolites released from apoptotic cells act as tissue messengers. <em>Nature</em> 580: 130-135. <a href="https://doi.org/10.1038/s41586-020-2121-3">doi:10.1038/s41586-020-2121-3</a></li>
<li>Neto, N. G. B., O’Rourke, S. A., Zhang, M., Fitzgerald, H. K., Dunne, A., and Monaghan, M. G. (2022). Non-invasive classification of macrophage polarisation by 2P-FLIM and machine learning. <em>eLife</em> 11: e77373. <a href="https://doi.org/10.7554/eLife.77373">doi:10.7554/eLife.77373</a></li>
<li>Park, D., et al.&nbsp;(2011). Continued clearance of apoptotic cells critically depends on the phagocyte Ucp2 protein. <em>Nature</em> 477(7363): 220-224. <a href="https://doi.org/10.1038/nature10340">doi:10.1038/nature10340</a></li>
<li>Poon, I. K. H., Lucas, C. D., Rossi, A. G., and Ravichandran, K. S. (2014). Apoptotic cell clearance: basic biology and therapeutic potential. <em>Nature Reviews Immunology</em> 14(3): 166-180. <a href="https://doi.org/10.1038/nri3607">doi:10.1038/nri3607</a></li>
<li>Ravichandran, K. S. (2011). Beginnings of a good apoptotic meal: the find-me and eat-me signaling pathways. <em>Immunity</em> 35(4): 445-455. <a href="https://doi.org/10.1016/j.immuni.2011.09.004">doi:10.1016/j.immuni.2011.09.004</a></li>
<li>Vehtari, A., Gelman, A., and Gabry, J. (2017). Practical Bayesian model evaluation using leave-one-out cross-validation and WAIC. <em>Statistics and Computing</em> 27(5): 1413-1432. <a href="https://doi.org/10.1007/s11222-016-9696-4">doi:10.1007/s11222-016-9696-4</a></li>
<li>Wang, Y., et al.&nbsp;(2017). Mitochondrial fission promotes the continued clearance of apoptotic cells by macrophages. <em>Cell</em> 171(2): 331-345.e22. <a href="https://doi.org/10.1016/j.cell.2017.08.041">doi:10.1016/j.cell.2017.08.041</a></li>
<li>Wood, S. N. (2017). <em>Generalized Additive Models: An Introduction with R</em>, 2nd edition. Chapman and Hall/CRC. <a href="https://doi.org/10.1201/9781315370279">doi:10.1201/9781315370279</a></li>
<li>Yurdagul, A., et al.&nbsp;(2020). Macrophage metabolism of apoptotic cell-derived arginine promotes continual efferocytosis and resolution of injury. <em>Cell Metabolism</em> 31(3): 518-533.e10. <a href="https://doi.org/10.1016/j.cmet.2020.01.001">doi:10.1016/j.cmet.2020.01.001</a></li>
<li><a href="../causality-from-toddlers-to-do-calculus/">Causality: From Toddlers to Do-Calculus</a> - assignment against observation.</li>
<li><a href="../sir-training-vs-calibration/">Training Is Not Calibration</a> - fitting a mechanistic model to simulated epidemic data.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/project-delphi\.github\.io\/ml-blog\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Synthetic Musings, by Ravi Kalia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/efferocytosis-history-model/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>