{
  "hash": "e81939512e49e8ee0a04851057261fd0",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Clustering Has No Labels to Tune Against, So the Metric Can Lie\"\ndescription: \"Which clustering hyperparameters can honestly be tuned on a held-out split, what the label-free metrics measure, and a worked case where the silhouette picks the wrong number of clusters with a straight face.\"\nauthor: \"Ravi Kalia\"\ndate: \"2025-01-27\"\ncategories: [Clustering, Machine Learning]\ntags: [k-means, silhouette, adjusted-rand-index, validation, scikit-learn]\nimage: \"./cover.png\"\njupyter: clustering-blog\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n---\n\n![Clustering](./cover.png)\n\nTuning a classifier is a solved routine: hold out some data, try the settings, keep\nthe one that scores best on the held-out part. Clustering breaks the routine at the\nlast step, because there is no score. Nothing in the data says which points belong\ntogether, so the number of clusters, the density threshold or the linkage rule has to\nbe chosen against a metric that is computed from the clustering itself. Those metrics\nare useful and they are not the truth, and the gap between the two is what this post\nis about: which knobs can be tuned on a split at all, what the label-free metrics\nreward, and a small case where the most popular one picks the wrong answer.\n\n## Only some clustering algorithms can be tuned on a split\n\nA validation split works for a classifier because the model can be fitted on one part\nand scored on another. Some clustering algorithms have that shape and some do not.\nK-means and Gaussian mixtures produce a rule that assigns a *new* point to a cluster,\nso they can be fitted on training data and their assignments scored on validation\ndata. Agglomerative clustering has no such rule in scikit-learn, but its clusters have\ncentroids, and assigning each held-out point to the nearest one is a rule of the same\nkind, written by hand. DBSCAN and OPTICS do not: they label the points they were given\nby local density, and a held-out point has no label until it is clustered along with\nthe rest. Spectral clustering needs the affinity matrix of the whole set, which a\nsplit distorts.\n\n| Algorithm | Knobs | Tune on a split? |\n|---|---|---|\n| K-means | `n_clusters`, `init` | yes: `predict` exists |\n| Agglomerative | `n_clusters`, `linkage` | yes, by nearest training centroid, written by hand |\n| Gaussian mixture | `n_components`, `covariance_type` | yes, and log-likelihood or BIC is a real score |\n| DBSCAN, OPTICS | `eps`, `min_samples` | no: refit on subsets instead |\n| Spectral | `n_clusters`, `affinity` | no: the affinity matrix is global |\n\nFor the first three the recipe is the classifier's, with one change: the score on the\nvalidation set is a label-free metric rather than accuracy.\n\n## The label-free metrics reward compactness and separation, not correctness\n\nThree metrics come up, and they all measure geometry:\n\n- The **silhouette** of a point compares its mean distance to its own cluster with its\n  mean distance to the nearest other cluster; the score averages over points and runs\n  from $-1$ to $1$. High means tight clusters far apart.\n- **Davies–Bouldin** is a ratio of within-cluster scatter to between-cluster distance,\n  averaged over the worst pairing; lower is better.\n- **Inertia**, k-means's own objective, is the total squared distance to the centroids;\n  it always falls as $k$ grows, so it is read for an elbow rather than a minimum.\n\nWith ground truth, the **adjusted Rand index** and **normalised mutual information**\ncompare a clustering to the true labels, and those are the honest scores. They are\nalso unavailable in exactly the situation clustering is for. The metrics above stand\nin for them by assuming that the true clusters are compact and well separated, and\nthat assumption is where they fail.\n\n## A case where the silhouette is confident and wrong\n\nThe data is synthetic so that the truth is known: 500 points in the plane from four\nGaussian blobs of equal size, generated by scikit-learn's `make_blobs`, standing in for\nany dataset with a handful of real groups. Split 70/15/15, fit k-means on the training\npart for $k$ from 2 to 6, and score the validation assignments both ways.\n\n::: {#tune-round .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nfrom sklearn.cluster import KMeans\nfrom sklearn.datasets import make_blobs\nfrom sklearn.metrics import adjusted_rand_score, silhouette_score\nfrom sklearn.model_selection import train_test_split\n\nX, y = make_blobs(n_samples=500, centers=4, cluster_std=0.6, random_state=42)\nX_train, X_tmp, y_train, y_tmp = train_test_split(X, y, test_size=0.3, random_state=42)\nX_val, X_test, y_val, y_test = train_test_split(X_tmp, y_tmp, test_size=0.5, random_state=42)\n\n\ndef score_by_k(X_fit, X_score, y_score, ks=(2, 3, 4, 5, 6)):\n    rows = []\n    for k in ks:\n        labels = KMeans(n_clusters=k, n_init=10, random_state=42).fit(X_fit).predict(X_score)\n        rows.append((k, silhouette_score(X_score, labels), adjusted_rand_score(y_score, labels)))\n    return rows\n\n\nprint(\"round blobs   k   silhouette   ARI\")\nfor k, sil, ari in score_by_k(X_train, X_val, y_val):\n    print(f\"{'':13} {k}      {sil:.3f}    {ari:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nround blobs   k   silhouette   ARI\n              2      0.597    0.304\n              3      0.817    0.724\n              4      0.887    1.000\n              5      0.767    0.958\n              6      0.587    0.854\n```\n:::\n:::\n\n\nOn round, well-separated blobs the silhouette and the ARI agree: both peak at\n$k = 4$, the silhouette at 0.887 and the ARI at 1.000. This is the case the metric was\ndesigned for, and a validation split with a silhouette score picks the right $k$.\n\nNow shear the same points, so that each blob becomes an elongated ellipse leaning the\nsame way. The four groups are unchanged; only their shape is.\n\n::: {#tune-sheared .cell execution_count=2}\n``` {.python .cell-code}\nshear = np.array([[0.6, -0.6], [-0.4, 0.8]])\nXs = X @ shear\nXs_train, Xs_val = X_train @ shear, X_val @ shear\n\nprint(\"sheared blobs k   silhouette   ARI\")\nfor k, sil, ari in score_by_k(Xs_train, Xs_val, y_val):\n    print(f\"{'':13} {k}      {sil:.3f}    {ari:.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsheared blobs k   silhouette   ARI\n              2      0.843    0.501\n              3      0.803    0.705\n              4      0.774    1.000\n              5      0.733    0.948\n              6      0.667    0.835\n```\n:::\n:::\n\n\nThe ARI still peaks at $k = 4$, because the groups are still there. The silhouette\nnow peaks at $k = 2$: two elongated blobs lying near each other look, to a metric\nbuilt from mean distances, like one wide cluster, and merging them raises the score.\nA tuning loop that keeps the best silhouette returns two clusters, prints a\nrespectable score, and is wrong, with nothing in its output to say so.\n\n::: {#cell-plot .cell execution_count=3}\n``` {.python .cell-code}\nimport matplotlib.pyplot as plt\n\nfig, axes = plt.subplots(1, 2, figsize=(9, 4))\nfor ax, data, title in ((axes[0], X, \"round\"), (axes[1], Xs, \"sheared\")):\n    ax.scatter(data[:, 0], data[:, 1], c=y, s=8, cmap=\"tab10\")\n    ax.set_title(title)\n    ax.set_aspect(\"equal\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![The same four groups, round (left) and sheared (right). The silhouette picks four clusters on the left and two on the right; the truth is four in both.](index_files/figure-html/plot-output-1.png){#plot}\n:::\n:::\n\n\n## What to do when the metric cannot be trusted\n\nThe failure is not a bug in the silhouette; it is the assumption of compact, round\nclusters being false. Three responses follow from that.\n\n**Match the model to the shape.** A Gaussian mixture with full covariance fits\nelongated clusters that k-means cannot, and its likelihood gives a score that does not\nassume roundness: the Bayesian information criterion, the fitted log-likelihood\npenalised by the number of parameters, lower being better. On the sheared training\ndata it picks four components, and those four match the truth on the validation set.\n\n::: {#gmm .cell execution_count=4}\n``` {.python .cell-code}\nfrom sklearn.mixture import GaussianMixture\n\nprint(\"sheared blobs k   BIC (train)   ARI (val)\")\nfor k in (2, 3, 4, 5, 6):\n    gmm = GaussianMixture(n_components=k, covariance_type=\"full\", random_state=42).fit(Xs_train)\n    print(f\"{'':13} {k}      {gmm.bic(Xs_train):7.0f}     {adjusted_rand_score(y_val, gmm.predict(Xs_val)):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nsheared blobs k   BIC (train)   ARI (val)\n              2         2311     0.501\n              3         1699     0.724\n              4         1369     1.000\n              5         1401     0.974\n              6         1436     0.872\n```\n:::\n:::\n\n\n**Read the metric against the data, not alone.** A silhouette curve that peaks at\n$k = 2$ on data with visible structure is a prompt to look, and a scatter plot is\ncheap. Where the data are high-dimensional, plot the clusters in a two-dimensional\nprojection rather than trusting a number.\n\n**Use cross-validation for the algorithms without `predict`.** For DBSCAN and\nspectral clustering, refit on several subsets of the training data and check that\nthe clustering is *stable* across them; a parameter setting whose clusters change\nfrom subset to subset is not finding structure.\n\nAnd keep the test set for the end, as in supervised learning: a test-set silhouette\nis only informative about the settings chosen on validation data if it was never used\nto choose them.\n\nClustering. Hides. Errors. Tune. Anyway. Metrics. Assume. Shapes. Look. First.\n\n## References\n\n- Rousseeuw, P. J. (1987). Silhouettes: a graphical aid to the interpretation and\n  validation of cluster analysis. *Journal of Computational and Applied Mathematics*\n  **20**, 53–65.\n- Davies, D. L. and Bouldin, D. W. (1979). A cluster separation measure. *IEEE TPAMI*\n  **1**(2).\n- Hubert, L. and Arabie, P. (1985). Comparing partitions. *Journal of Classification*\n  **2**, 193–218. (The adjusted Rand index.)\n- [scikit-learn: clustering performance evaluation](https://scikit-learn.org/stable/modules/clustering.html#clustering-performance-evaluation)\n- [Train, dev, test splits](../train-dev-test-splits/) on this blog\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}
