<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-09-13">
<meta name="description" content="Derive the links between variance, projection error, covariance eigenvectors, and truncated SVD. MovieLens and metabolomics show why the largest-variance direction still needs interpretation.">

<title>Six Views of PCA – Synthetic Musings</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-8ea72dc5fed832574809a9c94082fbbb.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-2320c3286543d00a1b02fc8c95bfefbb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-2bf7ad2c2d8ffd45a30263a1fba6e5d1.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script src="../../site_libs/quarto-diagram/mermaid.min.js"></script>
<script src="../../site_libs/quarto-diagram/mermaid-init.js"></script>
<link href="../../site_libs/quarto-diagram/mermaid.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Six Views of PCA – Synthetic Musings">
<meta property="og:description" content="Derive the links between variance, projection error, covariance eigenvectors, and truncated SVD. MovieLens and metabolomics show why the largest-variance direction still needs interpretation.">
<meta property="og:image" content="https://project-delphi.github.io/ml-blog/posts/six-views-of-pca/cover.png">
<meta property="og:site_name" content="Synthetic Musings">
<meta property="og:image:height" content="630">
<meta property="og:image:width" content="1200">
<meta name="twitter:title" content="Six Views of PCA – Synthetic Musings">
<meta name="twitter:description" content="Derive the links between variance, projection error, covariance eigenvectors, and truncated SVD. MovieLens and metabolomics show why the largest-variance direction still needs interpretation.">
<meta name="twitter:image" content="https://project-delphi.github.io/ml-blog/posts/six-views-of-pca/cover.png">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:image-height" content="630">
<meta name="twitter:image-width" content="1200">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Synthetic Musings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS feed">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="Home">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Six Views of PCA</h1>
            <p class="subtitle lead">One projection problem, six formulations, and the preprocessing choices that change its answer.</p>
                  <div>
        <div class="description">
          Derive the links between variance, projection error, covariance eigenvectors, and truncated SVD. MovieLens and metabolomics show why the largest-variance direction still needs interpretation.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Linear Algebra</div>
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Mathematics</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">September 13, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#projection-geometry" id="toc-projection-geometry" class="nav-link active" data-scroll-target="#projection-geometry"><span class="header-section-number">1</span> Projection geometry</a></li>
  <li><a href="#notation" id="toc-notation" class="nav-link" data-scroll-target="#notation"><span class="header-section-number">2</span> Notation</a></li>
  <li><a href="#the-six-views" id="toc-the-six-views" class="nav-link" data-scroll-target="#the-six-views"><span class="header-section-number">3</span> The six views</a></li>
  <li><a href="#sec-equivalence" id="toc-sec-equivalence" class="nav-link" data-scroll-target="#sec-equivalence"><span class="header-section-number">4</span> Equivalence</a>
  <ul class="collapse">
  <li><a href="#covariance-and-normalization" id="toc-covariance-and-normalization" class="nav-link" data-scroll-target="#covariance-and-normalization"><span class="header-section-number">4.1</span> Covariance and normalization</a></li>
  <li><a href="#sec-projector" id="toc-sec-projector" class="nav-link" data-scroll-target="#sec-projector"><span class="header-section-number">4.2</span> From reconstruction to energy</a></li>
  <li><a href="#from-energy-to-variance" id="toc-from-energy-to-variance" class="nav-link" data-scroll-target="#from-energy-to-variance"><span class="header-section-number">4.3</span> From energy to variance</a></li>
  <li><a href="#sec-lagrange" id="toc-sec-lagrange" class="nav-link" data-scroll-target="#sec-lagrange"><span class="header-section-number">4.4</span> Stationary directions</a></li>
  <li><a href="#sec-kyfan" id="toc-sec-kyfan" class="nav-link" data-scroll-target="#sec-kyfan"><span class="header-section-number">4.5</span> The maximizing subspace</a></li>
  <li><a href="#sec-lowrank" id="toc-sec-lowrank" class="nav-link" data-scroll-target="#sec-lowrank"><span class="header-section-number">4.6</span> SVD and rank approximation</a></li>
  <li><a href="#sec-chain" id="toc-sec-chain" class="nav-link" data-scroll-target="#sec-chain"><span class="header-section-number">4.7</span> The chain</a></li>
  <li><a href="#sec-assumptions" id="toc-sec-assumptions" class="nav-link" data-scroll-target="#sec-assumptions"><span class="header-section-number">4.8</span> Equivalence, uniqueness, and stability</a></li>
  </ul></li>
  <li><a href="#numerical-check" id="toc-numerical-check" class="nav-link" data-scroll-target="#numerical-check"><span class="header-section-number">5</span> Numerical check</a></li>
  <li><a href="#sec-scaling" id="toc-sec-scaling" class="nav-link" data-scroll-target="#sec-scaling"><span class="header-section-number">6</span> Centring and scaling</a></li>
  <li><a href="#sec-movielens" id="toc-sec-movielens" class="nav-link" data-scroll-target="#sec-movielens"><span class="header-section-number">7</span> MovieLens genre ratings</a>
  <ul class="collapse">
  <li><a href="#data-and-task" id="toc-data-and-task" class="nav-link" data-scroll-target="#data-and-task"><span class="header-section-number">7.1</span> Data and task</a></li>
  <li><a href="#covariance-pca" id="toc-covariance-pca" class="nav-link" data-scroll-target="#covariance-pca"><span class="header-section-number">7.2</span> Covariance PCA</a></li>
  <li><a href="#sec-dropfirst" id="toc-sec-dropfirst" class="nav-link" data-scroll-target="#sec-dropfirst"><span class="header-section-number">7.3</span> Removing users’ overall levels</a></li>
  <li><a href="#interpretation-limits" id="toc-interpretation-limits" class="nav-link" data-scroll-target="#interpretation-limits"><span class="header-section-number">7.4</span> Interpretation limits</a></li>
  </ul></li>
  <li><a href="#sec-metabolome" id="toc-sec-metabolome" class="nav-link" data-scroll-target="#sec-metabolome"><span class="header-section-number">8</span> Neutrophil metabolomics</a>
  <ul class="collapse">
  <li><a href="#data-and-task-1" id="toc-data-and-task-1" class="nav-link" data-scroll-target="#data-and-task-1"><span class="header-section-number">8.1</span> Data and task</a></li>
  <li><a href="#sec-metabolome-scaling" id="toc-sec-metabolome-scaling" class="nav-link" data-scroll-target="#sec-metabolome-scaling"><span class="header-section-number">8.2</span> Comparing preprocessing routes</a></li>
  <li><a href="#wide-matrices" id="toc-wide-matrices" class="nav-link" data-scroll-target="#wide-matrices"><span class="header-section-number">8.3</span> Wide matrices</a></li>
  <li><a href="#interpretation-limits-1" id="toc-interpretation-limits-1" class="nav-link" data-scroll-target="#interpretation-limits-1"><span class="header-section-number">8.4</span> Interpretation limits</a></li>
  </ul></li>
  <li><a href="#constraints" id="toc-constraints" class="nav-link" data-scroll-target="#constraints"><span class="header-section-number">9</span> Constraints</a></li>
  <li><a href="#related-questions" id="toc-related-questions" class="nav-link" data-scroll-target="#related-questions"><span class="header-section-number">10</span> Related questions</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">11</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/six-views-of-pca/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img" alt="A centred point cloud projected onto a line, beside complementary curves of projected energy and reconstruction error."></p>
<figcaption>Six Views of PCA</figcaption>
</figure>
</div>
<p>PCA’s maximum-variance and minimum-error definitions choose the same subspace; the projection geometry explains why, and the algebra connects both to truncated SVD.</p>
<p>When we replace a measurement table with fewer coordinates, we want to know what those coordinates preserve. The six formulations answer that question for a fixed matrix; centring and scaling determine which matrix we have asked them to summarize.</p>
<p><a href="../eigendecomposition/">Eigenvectors and eigenvalues</a> and <a href="../svd-rotate-stretch-rotate/">SVD geometry</a> provide the linear-algebra background.</p>
<section id="projection-geometry" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="projection-geometry"><span class="header-section-number">1</span> Projection geometry</h2>
<p>We can compare a line that keeps the most spread with a line that leaves the shortest perpendicular residuals. Both choose the direction called the first principal component, or PC1.</p>
<p>The synthetic cloud used here: 200 draws of a scalar latent <span class="math inline">\(t \sim N(0,1)\)</span>, mapped to <span class="math inline">\((2.2t,\ 0.9t)\)</span> and perturbed by independent <span class="math inline">\(N(0, 0.45^2)\)</span> noise in both coordinates, then column-centred. It stands in for any measurement pair where one underlying quantity drives both readings and the instrument adds isotropic noise — two sensors on one process, two assays of one sample. Two dimensions let us draw the residuals. The example checks an algebraic identity; it does not validate a sensor model on real measurements.</p>
<div id="cell-fig-equivalence" class="cell" data-fig-height="3.5" data-fig-width="9.2" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>latent <span class="op">=</span> rng.normal(size<span class="op">=</span>n)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.column_stack([<span class="fl">2.2</span> <span class="op">*</span> latent, <span class="fl">0.9</span> <span class="op">*</span> latent]) <span class="op">+</span> rng.normal(scale<span class="op">=</span><span class="fl">0.45</span>, size<span class="op">=</span>(n, <span class="dv">2</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> X <span class="op">-</span> X.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>U, S, Vt <span class="op">=</span> np.linalg.svd(X, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>pc1 <span class="op">=</span> Vt[<span class="dv">0</span>]</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>thetas <span class="op">=</span> np.linspace(<span class="fl">0.0</span>, np.pi, <span class="dv">3601</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>dirs <span class="op">=</span> np.vstack([np.cos(thetas), np.sin(thetas)])</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>proj <span class="op">=</span> X <span class="op">@</span> dirs</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>energy <span class="op">=</span> (proj<span class="op">**</span><span class="dv">2</span>).<span class="bu">sum</span>(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>resid <span class="op">=</span> ((X[:, <span class="va">None</span>, :] <span class="op">-</span> proj[:, :, <span class="va">None</span>] <span class="op">*</span> dirs.T[<span class="va">None</span>, :, :]) <span class="op">**</span> <span class="dv">2</span>).<span class="bu">sum</span>(axis<span class="op">=</span>(<span class="dv">0</span>, <span class="dv">2</span>))</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>total <span class="op">=</span> <span class="bu">float</span>((X<span class="op">**</span><span class="dv">2</span>).<span class="bu">sum</span>())</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>fig, (ax_l, ax_r) <span class="op">=</span> plt.subplots(</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">9.2</span>, <span class="fl">3.5</span>), gridspec_kw<span class="op">=</span>{<span class="st">"width_ratios"</span>: [<span class="fl">1.15</span>, <span class="fl">1.0</span>]}</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> X <span class="op">@</span> pc1</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>feet <span class="op">=</span> np.outer(scores, pc1)</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>ax_l.scatter(X[:, <span class="dv">0</span>], X[:, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">14</span>, color<span class="op">=</span>MUTED, alpha<span class="op">=</span><span class="fl">0.45</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, n, <span class="dv">3</span>):</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>    ax_l.plot(</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>        [X[i, <span class="dv">0</span>], feet[i, <span class="dv">0</span>]], [X[i, <span class="dv">1</span>], feet[i, <span class="dv">1</span>]],</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>        color<span class="op">=</span>CORAL, lw<span class="op">=</span><span class="fl">1.0</span>, alpha<span class="op">=</span><span class="fl">0.8</span>, zorder<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>ax_l.scatter(feet[:, <span class="dv">0</span>], feet[:, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">9</span>, color<span class="op">=</span>ACCENT, zorder<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>span <span class="op">=</span> np.array([scores.<span class="bu">min</span>(), scores.<span class="bu">max</span>()])</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>ax_l.plot(span <span class="op">*</span> pc1[<span class="dv">0</span>], span <span class="op">*</span> pc1[<span class="dv">1</span>], color<span class="op">=</span>ACCENT, lw<span class="op">=</span><span class="fl">1.8</span>, zorder<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>ax_l.set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>ax_l.set_xlabel(<span class="st">"feature 1"</span>)</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>ax_l.set_ylabel(<span class="st">"feature 2"</span>)</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>ax_l.set_title(<span class="st">"Projection onto PC1, and what is left over"</span>)</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>deg <span class="op">=</span> np.degrees(thetas)</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>ax_r.plot(deg, energy, color<span class="op">=</span>ACCENT, lw<span class="op">=</span><span class="fl">1.8</span>)</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>ax_r.plot(deg, resid, color<span class="op">=</span>CORAL, lw<span class="op">=</span><span class="fl">1.8</span>)</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>ax_r.plot(deg, energy <span class="op">+</span> resid, color<span class="op">=</span>TEAL, lw<span class="op">=</span><span class="fl">1.4</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>ax_r.axvline(deg[energy.argmax()], color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">0.9</span>, ls<span class="op">=</span><span class="st">":"</span>)</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>ax_r.set_xlabel(<span class="st">"direction angle (degrees)"</span>)</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>ax_r.set_ylabel(<span class="st">"sum of squares"</span>)</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>ax_r.set_xlim(<span class="dv">0</span>, <span class="dv">180</span>)</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>ax_r.set_ylim(<span class="dv">0</span>, total <span class="op">*</span> <span class="fl">1.30</span>)</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Label the curves on the curves: a legend box has nowhere to sit here.</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>ax_r.text(deg[energy.argmax()], total <span class="op">*</span> <span class="fl">1.05</span>, <span class="vs">r"energy $\|Xw\|_F^2$"</span>,</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>          color<span class="op">=</span>ACCENT, fontsize<span class="op">=</span><span class="dv">8</span>, ha<span class="op">=</span><span class="st">"center"</span>)</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>ax_r.text(deg[resid.argmax()], total <span class="op">*</span> <span class="fl">1.05</span>, <span class="vs">r"residual $\|X-Xww^\top\|_F^2$"</span>,</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a>          color<span class="op">=</span>CORAL, fontsize<span class="op">=</span><span class="dv">8</span>, ha<span class="op">=</span><span class="st">"center"</span>)</span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>ax_r.text(<span class="dv">170</span>, total <span class="op">*</span> <span class="fl">0.92</span>, <span class="vs">r"sum $=\|X\|_F^2$"</span>,</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a>          color<span class="op">=</span>TEAL, fontsize<span class="op">=</span><span class="dv">8</span>, ha<span class="op">=</span><span class="st">"right"</span>, va<span class="op">=</span><span class="st">"bottom"</span>)</span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>ax_r.set_title(<span class="st">"One curve is the other, upside down"</span>)</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>fig.tight_layout(pad<span class="op">=</span><span class="fl">1.1</span>)</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"energy peaks at </span><span class="sc">{</span>deg[energy.argmax()]<span class="sc">:.2f}</span><span class="ss"> deg"</span>)</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"residual bottoms at </span><span class="sc">{</span>deg[resid.argmin()]<span class="sc">:.2f}</span><span class="ss"> deg"</span>)</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"sum varies by </span><span class="sc">{</span>np<span class="sc">.</span>ptp(energy <span class="op">+</span> resid)<span class="sc">:.2e}</span><span class="ss"> across the sweep"</span>)</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||X||_F^2 = </span><span class="sc">{</span>total<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-equivalence" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two panels. The left shows a 2D elliptical point cloud with a line through its long axis and short perpendicular segments from points to that line. The right shows two mirrored curves against angle, one peaking where the other bottoms out, and a flat line at their sum.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-equivalence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-equivalence-output-1.png" class="img-fluid figure-img" alt="Two panels. The left shows a 2D elliptical point cloud with a line through its long axis and short perpendicular segments from points to that line. The right shows two mirrored curves against angle, one peaking where the other bottoms out, and a flat line at their sum.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-equivalence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Left: the centred cloud with PC1 and, for a sample of observations, the perpendicular residual joining each point to its projection. Right: projected energy and residual sum of squares against direction angle, with their constant sum.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>energy peaks at 22.15 deg
residual bottoms at 22.15 deg
sum varies by 2.84e-12 across the sweep
||X||_F^2 = 903.0973</code></pre>
</div>
</div>
<p>The two curves peak and bottom out at the same angle, 22.15 degrees, and their sum is flat to <span class="math inline">\(2.84\times10^{-12}\)</span> — floating-point noise on a total of 903.0973. That flat line is the identity of <a href="#sec-projector" class="quarto-xref">Section&nbsp;4.2</a>. Maximising the purple curve and minimising the orange one are the same search, because the dashed line does not move.</p>
</section>
<section id="notation" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="notation"><span class="header-section-number">2</span> Notation</h2>
<p>All six views use one centred matrix and one orthonormal basis, with <span class="math inline">\(n &gt; 1\)</span> and <span class="math inline">\(1 \le k \le \min(n,d)\)</span>.</p>
<ul>
<li><span class="math inline">\(X \in \mathbb{R}^{n \times d}\)</span> — the data. Each of the <span class="math inline">\(n\)</span> rows is an observation, each of the <span class="math inline">\(d\)</span> columns a feature.</li>
<li><span class="math inline">\(X\)</span> is <strong>centred</strong>: every column has mean zero. PCA without this step answers a different question, and <a href="#sec-assumptions" class="quarto-xref">Section&nbsp;4.8</a> says which one.</li>
<li><span class="math inline">\(W \in \mathbb{R}^{d \times k}\)</span> — the basis we are looking for, with <span class="math inline">\(W^\top W = I_k\)</span>. Its <span class="math inline">\(k\)</span> columns are orthonormal directions in feature space.</li>
<li><span class="math inline">\(Z = XW \in \mathbb{R}^{n \times k}\)</span> — the <strong>projection</strong>, or scores. Row <span class="math inline">\(i\)</span> holds the <span class="math inline">\(k\)</span> coordinates of observation <span class="math inline">\(i\)</span> in the new basis.</li>
<li><span class="math inline">\(\hat X = XWW^\top \in \mathbb{R}^{n \times d}\)</span> — the <strong>reconstruction</strong>. Back in the original <span class="math inline">\(d\)</span> features, but of rank at most <span class="math inline">\(k\)</span>.</li>
<li><span class="math inline">\(P = WW^\top \in \mathbb{R}^{d \times d}\)</span> — the orthogonal projector onto the span of <span class="math inline">\(W\)</span>’s columns. <span class="math inline">\(P^2 = P\)</span> and <span class="math inline">\(P^\top = P\)</span>.</li>
</ul>
<p>Scores and reconstructions have different dimensions. <span class="math inline">\(Z\)</span> is <span class="math inline">\(n \times k\)</span> and lives in the small space. <span class="math inline">\(\hat X\)</span> is <span class="math inline">\(n \times d\)</span> and lives back in the big one, on a <span class="math inline">\(k\)</span>-dimensional flat inside it.</p>
</section>
<section id="the-six-views" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="the-six-views"><span class="header-section-number">3</span> The six views</h2>
<p>Three objectives, a matrix approximation, and two solution methods describe the principal subspace:</p>
<ol type="1">
<li><strong>Maximum variance.</strong> Find the directions along which the projected observations spread out the most.</li>
<li><strong>Maximum projected energy.</strong> Find <span class="math inline">\(W\)</span> maximising <span class="math inline">\(\|XW\|_F^2\)</span>, the total squared magnitude of the projected representation.</li>
<li><strong>Minimum reconstruction error.</strong> Find the <span class="math inline">\(k\)</span>-dimensional subspace minimising <span class="math inline">\(\|X - XWW^\top\|_F^2\)</span>, the squared perpendicular distance from the data to the subspace.</li>
<li><strong>Best rank-<span class="math inline">\(k\)</span> approximation.</strong> Find the rank-<span class="math inline">\(k\)</span> matrix closest to <span class="math inline">\(X\)</span> in Frobenius norm.</li>
<li><strong>Covariance eigendecomposition.</strong> Take the leading eigenvectors of the sample covariance matrix.</li>
<li><strong>Truncated SVD.</strong> Take the leading right singular vectors of <span class="math inline">\(X\)</span>.</li>
</ol>
<p>They are not six independent problems. Views 1, 2, and 3 are one optimization problem written in three notations. Views 5 and 6 are two <em>routes to the solution</em> of that problem, not separate objectives. View 4 is the same optimum read as a statement about matrices rather than about subspaces. <a href="#sec-equivalence" class="quarto-xref">Section&nbsp;4</a> does the work of showing that.</p>
<p>Here <strong>energy</strong> means a sum of squares: <span class="math inline">\(\|X\|_F^2 = \sum_{ij} X_{ij}^2\)</span>. For centred data it is <span class="math inline">\((n-1)\)</span> times the total sample variance.</p>
<p>The arrows distinguish algebraic identities from the optimization results needed to choose a solution.</p>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div id="fig-map" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>
<pre class="mermaid mermaid-js" data-label="fig-map">flowchart TD
  R["&lt;b&gt;Minimum&lt;br/&gt;reconstruction error&lt;/b&gt;&lt;br/&gt;min ‖X − XWWᵀ‖²_F"]
  E["&lt;b&gt;Maximum&lt;br/&gt;projected energy&lt;/b&gt;&lt;br/&gt;max ‖XW‖²_F"]
  V["&lt;b&gt;Maximum&lt;br/&gt;variance&lt;/b&gt;&lt;br/&gt;max tr(WᵀSW)"]
  G["&lt;b&gt;Covariance&lt;br/&gt;eigenvectors&lt;/b&gt;&lt;br/&gt;S = VΛVᵀ"]
  D["&lt;b&gt;Truncated&lt;br/&gt;SVD&lt;/b&gt;&lt;br/&gt;X = UΣVᵀ"]
  L["&lt;b&gt;Best rank-k&lt;br/&gt;approximation&lt;/b&gt;&lt;br/&gt;X̂ = U_kΣ_kV_kᵀ"]
  R --&gt;|"‖X‖²_F − ‖XW‖²_F&lt;br/&gt;projector identity"| E
  E --&gt;|"‖XW‖²_F = (n−1) tr(WᵀSW)&lt;br/&gt;cyclic trace"| V
  V --&gt;|"stationarity + Ky Fan&lt;br/&gt;W = V_k"| G
  G --&gt;|"XᵀX = VΣ²Vᵀ&lt;br/&gt;λ = σ²/(n−1)"| D
  D --&gt;|"Eckart–Young–Mirsky"| L
</pre>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The six views and their mathematical connections. Views 1 to 3 are one objective in three notations; views 5 and 6 are routes to its solution; view 4 is the same optimum read as a statement about matrices.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-equivalence" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="sec-equivalence"><span class="header-section-number">4</span> Equivalence</h2>
<p>The proof first relates the objectives for any admissible basis, then finds their optimizers. We fix centring, feature scaling, and a complete matrix throughout.</p>
<section id="covariance-and-normalization" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="covariance-and-normalization"><span class="header-section-number">4.1</span> Covariance and normalization</h3>
<p>The sample covariance of centred <span class="math inline">\(X\)</span> is</p>
<p><span class="math display">\[
S = \frac{X^\top X}{n-1} \in \mathbb{R}^{d \times d},
\]</span></p>
<p>The denominator <span class="math inline">\(n-1\)</span> accounts for estimating the column means. Switching to the maximum-likelihood convention <span class="math inline">\(X^\top X/n\)</span> multiplies every eigenvalue by <span class="math inline">\((n-1)/n\)</span>; it changes neither eigenvectors nor explained-variance ratios.</p>
<p><span class="math inline">\(S\)</span> is symmetric positive semi-definite, so it has an orthonormal eigenbasis with non-negative eigenvalues:</p>
<p><span class="math display">\[
S = V\Lambda V^\top, \qquad \Lambda = \operatorname{diag}(\lambda_1 \ge \dots \ge \lambda_d \ge 0).
\]</span></p>
<p>The principal directions are the leading columns of <span class="math inline">\(V\)</span>, and <span class="math inline">\(\lambda_j\)</span> is the variance of the data along direction <span class="math inline">\(v_j\)</span> — set <span class="math inline">\(W = v_j\)</span> in the trace objective and read it off. Because <span class="math inline">\(\operatorname{tr}(S) = \sum_j \lambda_j\)</span> is the total variance across all <span class="math inline">\(d\)</span> features, <span class="math inline">\(\lambda_j / \sum_i \lambda_i\)</span> is the fraction of variance explained by component <span class="math inline">\(j\)</span>.</p>
</section>
<section id="sec-projector" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="sec-projector"><span class="header-section-number">4.2</span> From reconstruction to energy</h3>
<p><span class="math inline">\(P = WW^\top\)</span> is an orthogonal projector: <span class="math inline">\(P^\top = P\)</span>, and <span class="math inline">\(P^2 = WW^\top WW^\top = W(W^\top W)W^\top = WW^\top = P\)</span> because <span class="math inline">\(W^\top W = I_k\)</span>. Expand the reconstruction error:</p>
<p><span class="math display">\[
\|X - XP\|_F^2
= \operatorname{tr}\!\left[(X - XP)^\top (X - XP)\right]
= \operatorname{tr}(X^\top X) - 2\operatorname{tr}(X^\top X P) + \operatorname{tr}(P X^\top X P).
\]</span></p>
<p>The last term collapses. Using the cyclic property of the trace and <span class="math inline">\(P^2 = P\)</span>,</p>
<p><span class="math display">\[
\operatorname{tr}(PX^\top XP) = \operatorname{tr}(X^\top X P P) = \operatorname{tr}(X^\top X P),
\]</span></p>
<p>so two of the three terms cancel into one:</p>
<p><span class="math display">\[
\|X - XWW^\top\|_F^2 = \operatorname{tr}(X^\top X) - \operatorname{tr}(X^\top X WW^\top) = \|X\|_F^2 - \|XW\|_F^2 .
\]</span></p>
<p>The last equality is the same cyclic move: <span class="math inline">\(\operatorname{tr}(X^\top X WW^\top) = \operatorname{tr}(W^\top X^\top X W) = \|XW\|_F^2\)</span>.</p>
<p>This is the Pythagorean split. Every observation’s squared length divides into the part the subspace keeps and the part it loses, with no cross term. And <span class="math inline">\(\|X\|_F^2\)</span> does not contain <span class="math inline">\(W\)</span>:</p>
<p><span class="math display">\[
\min_{W^\top W = I} \|X - XWW^\top\|_F^2
\iff
\max_{W^\top W = I} \|XW\|_F^2 .
\]</span></p>
<p>Fitting the data as closely as possible and capturing as much energy as possible are the same instruction, because the two quantities sum to a constant.</p>
</section>
<section id="from-energy-to-variance" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="from-energy-to-variance"><span class="header-section-number">4.3</span> From energy to variance</h3>
<p>One line, already used in <a href="#sec-projector" class="quarto-xref">Section&nbsp;4.2</a>:</p>
<p><span class="math display">\[
\|XW\|_F^2 = \operatorname{tr}\!\left[(XW)^\top(XW)\right] = \operatorname{tr}(W^\top X^\top X W) = (n-1)\operatorname{tr}(W^\top S W).
\]</span></p>
<p><span class="math inline">\(W^\top X^\top X W\)</span> is the <span class="math inline">\(k \times k\)</span> covariance of the scores, up to the factor <span class="math inline">\(n-1\)</span>. Its trace is the total projected variance. So maximum energy is maximum projected variance, and the <span class="math inline">\((n-1)\)</span> never affects the maximiser.</p>
</section>
<section id="sec-lagrange" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="sec-lagrange"><span class="header-section-number">4.4</span> Stationary directions</h3>
<p>Nothing so far mentioned eigenvectors. They arrive as the solution of a constrained maximisation, and the constraint is what puts them there.</p>
<p>Maximising <span class="math inline">\(w^\top A w\)</span> with <span class="math inline">\(A = X^\top X\)</span> has no answer on its own: scale <span class="math inline">\(w\)</span> up and the objective grows without bound. The constraint <span class="math inline">\(w^\top w = 1\)</span> is what makes the problem well posed, and a constrained stationary point is found by <strong>Lagrange multipliers</strong> — add the constraint to the objective with an unknown coefficient, then look for a point where the combined function is flat in every direction:</p>
<p><span class="math display">\[
\mathcal{L}(w, \lambda) = w^\top A w - \lambda\,(w^\top w - 1).
\]</span></p>
<p>Differentiating in <span class="math inline">\(w\)</span> and setting the gradient to zero gives</p>
<p><span class="math display">\[
\nabla_w \mathcal{L} = 2Aw - 2\lambda w = 0
\qquad \Longleftrightarrow \qquad
Aw = \lambda w .
\]</span></p>
<p>The eigenvector equation is the first-order condition. It was not assumed, and no eigendecomposition was invoked to get it: <strong>every stationary point of projected variance on the unit sphere is an eigenvector of <span class="math inline">\(X^\top X\)</span></strong>, and nothing else is.</p>
<p>The multiplier is not bookkeeping either. At a stationary point,</p>
<p><span class="math display">\[
w^\top A w = w^\top (\lambda w) = \lambda\,w^\top w = \lambda ,
\]</span></p>
<p>so <span class="math inline">\(\lambda\)</span> <em>is</em> the value of the objective there — the projected energy, and <span class="math inline">\(\lambda/(n-1)\)</span> the projected variance. With distinct eigenvalues there are <span class="math inline">\(d\)</span> stationary directions, each with two unit-vector signs. Repeated eigenvalues admit every unit vector in the corresponding eigenspace; comparing their objective values selects the largest eigenvalue. That is Rayleigh–Ritz, derived rather than quoted.</p>
<p>For <span class="math inline">\(k\)</span> components the constraint <span class="math inline">\(W^\top W = I_k\)</span> is <span class="math inline">\(k(k+1)/2\)</span> scalar equations, so the multiplier is a symmetric <span class="math inline">\(k \times k\)</span> matrix <span class="math inline">\(\Lambda\)</span>:</p>
<p><span class="math display">\[
\mathcal{L}(W, \Lambda) = \operatorname{tr}(W^\top A W) - \operatorname{tr}\!\left[\Lambda (W^\top W - I_k)\right],
\qquad
\nabla_W \mathcal{L} = 2AW - 2W\Lambda = 0 .
\]</span></p>
<p>So <span class="math inline">\(AW = W\Lambda\)</span>. A stationary <span class="math inline">\(W\)</span> need not hold eigenvectors — but <span class="math inline">\(\Lambda\)</span> is symmetric, so <span class="math inline">\(\Lambda = RDR^\top\)</span> for an orthogonal <span class="math inline">\(R\)</span>, and <span class="math inline">\(\widetilde W = WR\)</span> satisfies <span class="math inline">\(A\widetilde W = \widetilde W D\)</span>. Its columns <em>are</em> eigenvectors, and it spans the same subspace as <span class="math inline">\(W\)</span>.</p>
<p>For the subspace optimization, the stationarity condition pins the <strong>subspace</strong>, and leaves the basis inside it free up to the orthogonal <span class="math inline">\(R\)</span> that diagonalises the multiplier.</p>
</section>
<section id="sec-kyfan" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="sec-kyfan"><span class="header-section-number">4.5</span> The maximizing subspace</h3>
<p>Stationarity gives <span class="math inline">\(k\)</span> eigenvectors; it does not say which <span class="math inline">\(k\)</span>. For that, take <span class="math inline">\(A\)</span> symmetric with eigenvalues <span class="math inline">\(\lambda_1 \ge \dots \ge \lambda_d\)</span> and ask what maximises <span class="math inline">\(\operatorname{tr}(W^\top A W)\)</span> over <span class="math inline">\(W^\top W = I_k\)</span>.</p>
<p>Write <span class="math inline">\(A = V\Lambda V^\top\)</span> and set <span class="math inline">\(M = V^\top W\)</span>, which satisfies <span class="math inline">\(M^\top M = I_k\)</span>. Then</p>
<p><span class="math display">\[
\operatorname{tr}(W^\top A W) = \operatorname{tr}(M^\top \Lambda M) = \sum_{j=1}^{d} \lambda_j \, c_j,
\qquad c_j = \sum_{l=1}^{k} M_{jl}^2 .
\]</span></p>
<p>The weights <span class="math inline">\(c_j\)</span> are constrained: each <span class="math inline">\(c_j \in [0, 1]\)</span> because <span class="math inline">\(M\)</span> has orthonormal columns, and <span class="math inline">\(\sum_j c_j = \|M\|_F^2 = k\)</span>. Maximising a weighted sum of the <span class="math inline">\(\lambda_j\)</span> under “budget <span class="math inline">\(k\)</span>, at most <span class="math inline">\(1\)</span> each” puts all of the budget on the <span class="math inline">\(k\)</span> largest eigenvalues. The maximum is <span class="math inline">\(\lambda_1 + \dots + \lambda_k\)</span>, attained when <span class="math inline">\(W\)</span> spans the leading <span class="math inline">\(k\)</span> eigenvectors. That is the Ky Fan theorem, and at <span class="math inline">\(k = 1\)</span> it is Rayleigh–Ritz.</p>
<p>Applied to <span class="math inline">\(A = X^\top X\)</span>: the maximiser is <span class="math inline">\(W = V_k\)</span>, the leading eigenvectors of <span class="math inline">\(X^\top X\)</span>, which are the leading eigenvectors of <span class="math inline">\(S\)</span>.</p>
</section>
<section id="sec-lowrank" class="level3" data-number="4.6">
<h3 data-number="4.6" class="anchored" data-anchor-id="sec-lowrank"><span class="header-section-number">4.6</span> SVD and rank approximation</h3>
<p>For the thin SVD <span class="math inline">\(X = U\Sigma V^\top\)</span>, let <span class="math inline">\(r=\min(n,d)\)</span>, so <span class="math inline">\(U\)</span> is <span class="math inline">\(n\times r\)</span>, <span class="math inline">\(V\)</span> is <span class="math inline">\(d\times r\)</span>, and <span class="math inline">\(\Sigma\)</span> holds the <span class="math inline">\(r\)</span> singular values. Zero singular values are included when <span class="math inline">\(X\)</span> has smaller rank.</p>
<p><span class="math display">\[
X^\top X = V\Sigma^2V^\top,
\qquad \lambda_j(S)=\frac{\sigma_j^2}{n-1}.
\]</span></p>
<p>The right singular vectors provide the covariance eigenvectors represented by the thin decomposition. When <span class="math inline">\(d&gt;n\)</span>, a full covariance eigenbasis also contains <span class="math inline">\(d-n\)</span> additional null-space directions.</p>
<p>At the optimum, the scores and reconstruction are</p>
<p><span class="math display">\[
Z=XV_k=U_k\Sigma_k,\qquad
\hat X=XV_kV_k^\top=U_k\Sigma_kV_k^\top.
\]</span></p>
<p>The <strong>Eckart–Young–Mirsky theorem</strong> says this reconstruction also minimizes <span class="math inline">\(\|X-B\|_F^2\)</span> over all matrices <span class="math inline">\(B\)</span> of rank at most <span class="math inline">\(k\)</span>. Its error is <span class="math inline">\(\sum_{j&gt;k}\sigma_j^2\)</span>; the theorem joins the subspace problem to the broader matrix-approximation problem.</p>
<p>Direct SVD avoids forming <span class="math inline">\(X^\top X\)</span>, which squares the ratio of largest to smallest nonzero singular value. It also avoids storing a <span class="math inline">\(d\times d\)</span> covariance matrix when the data are wide; <a href="../svd-rotate-stretch-rotate/">the SVD companion</a> develops the numerical argument.</p>
</section>
<section id="sec-chain" class="level3" data-number="4.7">
<h3 data-number="4.7" class="anchored" data-anchor-id="sec-chain"><span class="header-section-number">4.7</span> The chain</h3>
<p>For every <span class="math inline">\(W\)</span> satisfying <span class="math inline">\(W^\top W=I_k\)</span>,</p>
<p><span class="math display">\[
\boxed{\|X-XWW^\top\|_F^2
=\|X\|_F^2-\|XW\|_F^2
=\|X\|_F^2-(n-1)\operatorname{tr}(W^\top S W).}
\]</span></p>
<p>These are identities between objective values. Rayleigh–Ritz and Ky Fan identify a maximizing subspace, and Eckart–Young–Mirsky identifies a best rank-<span class="math inline">\(k\)</span> reconstruction.</p>
<ul>
<li><span class="math inline">\(W=V_k\)</span> is an optimizer; so is <span class="math inline">\(V_kR\)</span> for any orthogonal <span class="math inline">\(k\times k\)</span> matrix <span class="math inline">\(R\)</span>.</li>
<li>Conventional PCA chooses ordered eigenvectors, giving uncorrelated scores with covariance <span class="math inline">\(\operatorname{diag}(\lambda_1,\ldots,\lambda_k)\)</span>.</li>
<li>An arbitrary rotation within the retained subspace preserves its projector and reconstruction, but generally makes the score covariance nondiagonal. It is an optimal subspace basis without necessarily being a set of principal axes.</li>
</ul>
</section>
<section id="sec-assumptions" class="level3" data-number="4.8">
<h3 data-number="4.8" class="anchored" data-anchor-id="sec-assumptions"><span class="header-section-number">4.8</span> Equivalence, uniqueness, and stability</h3>
<p>These are separate guarantees:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Question</th>
<th>Condition and consequence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Do the objectives agree?</td>
<td>A complete, fixed matrix, orthogonal projection, and squared Frobenius error give the projector identity. Column centring supplies the variance interpretation.</td>
</tr>
<tr class="even">
<td>Is the optimal subspace unique?</td>
<td>A strict boundary gap <span class="math inline">\(\lambda_k&gt;\lambda_{k+1}\)</span> fixes the leading <span class="math inline">\(k\)</span>-dimensional subspace. A positive tie across the boundary permits multiple optimal subspaces and reconstructions; the objective equivalence still holds.</td>
</tr>
<tr class="odd">
<td>Are individual axes unique?</td>
<td>Distinct eigenvalues fix eigenvector directions up to sign. Ties permit rotations inside the tied eigenspace.</td>
</tr>
<tr class="even">
<td>Is the estimated subspace stable?</td>
<td>A small boundary gap relative to sampling or measurement perturbations can make it unstable, even when the sample optimizer is unique. Resampling evaluates sensitivity to a specified sampling process.</td>
</tr>
</tbody>
</table>
<p>If <span class="math inline">\(k\)</span> reaches the data rank, reconstruction is <span class="math inline">\(X\)</span> itself. Adding directions from the null space can make the chosen basis or subspace nonunique while the reconstruction stays fixed.</p>
</section>
</section>
<section id="numerical-check" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="numerical-check"><span class="header-section-number">5</span> Numerical check</h2>
<p>We can check covariance eigenvalues, the projector identity, and the best-rank reconstruction on the synthetic cloud without hiding the algebra behind a PCA API.</p>
<div id="demo" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>eigenvalues <span class="op">=</span> np.linalg.eigvalsh(X.T <span class="op">@</span> X <span class="op">/</span> (n <span class="op">-</span> <span class="dv">1</span>))[::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>k <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>W <span class="op">=</span> Vt[:k].T</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>scores <span class="op">=</span> X <span class="op">@</span> W</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>reconstruction <span class="op">=</span> scores <span class="op">@</span> W.T</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>error <span class="op">=</span> np.<span class="bu">sum</span>((X <span class="op">-</span> reconstruction) <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>kept <span class="op">=</span> np.<span class="bu">sum</span>(scores<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(eigenvalues, S<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (n <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(error <span class="op">+</span> kept, np.<span class="bu">sum</span>(X<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(error, np.<span class="bu">sum</span>(S[k:] <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(reconstruction, (U[:, :k] <span class="op">*</span> S[:k]) <span class="op">@</span> Vt[:k])</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"kept </span><span class="sc">{</span>kept<span class="sc">:.4f}</span><span class="ss">; error </span><span class="sc">{</span>error<span class="sc">:.4f}</span><span class="ss">; total </span><span class="sc">{</span>kept <span class="op">+</span> error<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>kept 867.4169; error 35.6804; total 903.0973</code></pre>
</div>
</div>
<p>Rank 1 keeps 867.4169 and leaves 35.6804, adding to 903.0973. These are the peak and trough in the projection figure; rank 2 reconstructs this two-dimensional cloud completely.</p>
<p>The extended checks compare directions up to sign and verify that the eigenvector equation is stationary even at a variance minimum.</p>
<div id="demo-lagrange" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>A <span class="op">=</span> X.T <span class="op">@</span> X</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>w1 <span class="op">=</span> Vt[<span class="dv">0</span>]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>lam1 <span class="op">=</span> <span class="bu">float</span>(w1 <span class="op">@</span> A <span class="op">@</span> w1)                   <span class="co"># the objective at the stationary point</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"||grad L|| = ||2Aw - 2*lambda*w|| = </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>norm(<span class="dv">2</span> <span class="op">*</span> A <span class="op">@</span> w1 <span class="op">-</span> <span class="dv">2</span> <span class="op">*</span> lam1 <span class="op">*</span> w1)<span class="sc">:.3e}</span><span class="ss">"</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"multiplier lambda        = </span><span class="sc">{</span>lam1<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"projected energy ||Xw||^2 = </span><span class="sc">{</span>np<span class="sc">.</span><span class="bu">sum</span>((X <span class="op">@</span> w1) <span class="op">**</span> <span class="dv">2</span>)<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"lambda / (n-1)           = </span><span class="sc">{</span>lam1 <span class="op">/</span> (n <span class="op">-</span> <span class="dv">1</span>)<span class="sc">:.6f}</span><span class="ss">  vs eigenvalue </span><span class="sc">{</span>eigenvalues[<span class="dv">0</span>]<span class="sc">:.6f}</span><span class="ss">"</span>)</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># The multiplier IS the objective, and the gradient vanishes at the eigenvector.</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(A <span class="op">@</span> w1, lam1 <span class="op">*</span> w1)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(lam1, np.<span class="bu">sum</span>((X <span class="op">@</span> w1) <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(lam1 <span class="op">/</span> (n <span class="op">-</span> <span class="dv">1</span>), eigenvalues[<span class="dv">0</span>])</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Every eigenvector is stationary, not just the leading one -- including the</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co"># worst direction, which is the minimum rather than the maximum.</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> (<span class="dv">0</span>, <span class="dv">1</span>):</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    wj <span class="op">=</span> Vt[j]</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> np.allclose(A <span class="op">@</span> wj, <span class="bu">float</span>(wj <span class="op">@</span> A <span class="op">@</span> wj) <span class="op">*</span> wj)</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"both eigenvectors satisfy Aw = lambda w; only the larger lambda is the maximum"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>||grad L|| = ||2Aw - 2*lambda*w|| = 3.216e-13
multiplier lambda        = 867.416898
projected energy ||Xw||^2 = 867.416898
lambda / (n-1)           = 4.358879  vs eigenvalue 4.358879
both eigenvectors satisfy Aw = lambda w; only the larger lambda is the maximum</code></pre>
</div>
</div>
<div id="demo-sklearn" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.decomposition <span class="im">import</span> PCA</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>sk <span class="op">=</span> PCA(n_components<span class="op">=</span><span class="dv">2</span>).fit(X)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"sklearn components (rows)  "</span>, sk.components_)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"sklearn explained variance "</span>, sk.explained_variance_)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"our eigenvalues            "</span>, eigenvalues)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.allclose(sk.explained_variance_, eigenvalues)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(<span class="bu">abs</span>(sk.components_[<span class="dv">0</span>] <span class="op">@</span> Vt[<span class="dv">0</span>]), <span class="fl">1.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>sklearn components (rows)   [[ 0.9262  0.3771]
 [-0.3771  0.9262]]
sklearn explained variance  [4.3589 0.1793]
our eigenvalues             [4.3589 0.1793]</code></pre>
</div>
</div>
</section>
<section id="sec-scaling" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="sec-scaling"><span class="header-section-number">6</span> Centring and scaling</h2>
<p>The six formulations agree on the matrix they receive. Preprocessing determines what distances and variances that matrix represents.</p>
<ul>
<li><strong>Column centring</strong> subtracts feature means. In the original coordinates, the fitted affine subspace passes through the mean; add the mean back to reconstruct observations.</li>
<li><strong>Covariance PCA</strong> retains the chosen measurement scales. Changing a length from centimetres to metres divides its variance by <span class="math inline">\(10^4\)</span> and can change the answer.</li>
<li><strong>Correlation PCA</strong> divides each nonconstant centred feature by its sample standard deviation. It gives features equal variance, including features that contain mostly noise.</li>
<li><strong>Other transforms</strong> encode other measurement choices. A log compresses large positive values; IQR scaling uses the middle half of the observations to set a feature’s scale. Neither guarantees outlier resistance for PCA itself.</li>
</ul>
<p>Scaling also changes the coordinates of a loading vector. For <span class="math inline">\(Y=XD^{-1}\)</span>, a score <span class="math inline">\(Yv\)</span> equals <span class="math inline">\(X(D^{-1}v)\)</span>, so <span class="math inline">\(v\)</span> alone is not a coefficient vector in the original units. A nonlinear log transform has no global linear conversion back to raw coordinates.</p>
<p>To compare two preprocessing routes on the same observations, we will compare their score vectors using absolute correlation. This is a descriptive agreement measure, invariant to the arbitrary PC sign, not a test of which route is better.</p>
</section>
<section id="sec-movielens" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="sec-movielens"><span class="header-section-number">7</span> MovieLens genre ratings</h2>
<section id="data-and-task" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="data-and-task"><span class="header-section-number">7.1</span> Data and task</h3>
<ul>
<li><strong>Source.</strong> GroupLens collected MovieLens 100K through its recommendation site in 1997–1998 for recommender research: 100,000 volunteered ratings from 943 users on 1,682 films. Users chose which films to rate.</li>
<li><strong>Matrix.</strong> We average ratings in the 12 genres with widest user coverage and retain users with at least three films in every retained genre. The result is a complete <span class="math inline">\(313\times12\)</span> matrix of means on the <span class="math inline">\(1\)</span>–<span class="math inline">\(5\)</span> scale; it represents relatively active, broad-viewing users.</li>
<li><strong>Question.</strong> Does the leading component describe differences between genres or users’ overall rating levels? Confusing the two could produce a misleading user profile; recommendation accuracy is not measured here.</li>
<li><strong>Why aggregate?</strong> The original user-by-film grid is 93.7% unobserved. Genre aggregation supplies a complete matrix for demonstrating classical PCA, while changing the unit of analysis from films to genres.</li>
<li><strong>Measurement uncertainty.</strong> A cell averages between 3 and 410 ratings. The companion counts file preserves that distinction, and films with several genre tags contribute to several cells.</li>
</ul>
<div id="movielens-load" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>genres <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">"movielens_genres.csv"</span>, index_col<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>counts <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">"movielens_counts.csv"</span>, index_col<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> genres.index.equals(counts.index)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> genres.columns.equals(counts.columns)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> genres.to_numpy()</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>C <span class="op">=</span> counts.to_numpy()</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isfinite(G).<span class="bu">all</span>()</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>G<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> users, </span><span class="sc">{</span>G<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> genres"</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"ratings per cell: </span><span class="sc">{</span>C<span class="sc">.</span><span class="bu">min</span>()<span class="sc">}</span><span class="ss"> to </span><span class="sc">{</span>C<span class="sc">.</span><span class="bu">max</span>()<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>313 users, 12 genres
ratings per cell: 3 to 410</code></pre>
</div>
</div>
</section>
<section id="covariance-pca" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="covariance-pca"><span class="header-section-number">7.2</span> Covariance PCA</h3>
<p>All columns share a rating scale, so we retain that scale for this demonstration. Both SVD and eigendecomposition are inexpensive for twelve columns.</p>
<div id="movielens-pca" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>Gc <span class="op">=</span> G <span class="op">-</span> G.mean(axis<span class="op">=</span><span class="dv">0</span>)                       <span class="co"># centre the columns</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>Ug, Sg, Vtg <span class="op">=</span> np.linalg.svd(Gc, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>lam_g <span class="op">=</span> Sg<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (Gc.shape[<span class="dv">0</span>] <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>eig_g, vec_g <span class="op">=</span> np.linalg.eigh(Gc.T <span class="op">@</span> Gc <span class="op">/</span> (Gc.shape[<span class="dv">0</span>] <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cov route top eigenvalue </span><span class="sc">{</span>eig_g[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.10f}</span><span class="ss">"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"svd route sigma^2/(n-1)  </span><span class="sc">{</span>lam_g[<span class="dv">0</span>]<span class="sc">:.10f}</span><span class="ss">"</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"|cos| between the two PC1s: </span><span class="sc">{</span><span class="bu">abs</span>(vec_g[:, <span class="op">-</span><span class="dv">1</span>] <span class="op">@</span> Vtg[<span class="dv">0</span>])<span class="sc">:.12f}</span><span class="ss">"</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"explained variance ratio:"</span>, (lam_g <span class="op">/</span> lam_g.<span class="bu">sum</span>())[:<span class="dv">4</span>].<span class="bu">round</span>(<span class="dv">4</span>))</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"cumulative              :"</span>, np.cumsum(lam_g <span class="op">/</span> lam_g.<span class="bu">sum</span>())[:<span class="dv">4</span>].<span class="bu">round</span>(<span class="dv">4</span>))</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>):</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    W <span class="op">=</span> Vtg[:k].T</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    rel <span class="op">=</span> np.<span class="bu">sum</span>((Gc <span class="op">-</span> Gc <span class="op">@</span> W <span class="op">@</span> W.T) <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> np.<span class="bu">sum</span>(Gc<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    kept <span class="op">=</span> np.<span class="bu">sum</span>((Gc <span class="op">@</span> W) <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> np.<span class="bu">sum</span>(Gc<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  rank </span><span class="sc">{</span>k<span class="sc">}</span><span class="ss">: relative reconstruction error </span><span class="sc">{</span>rel<span class="sc">:.4f}</span><span class="ss">, energy kept </span><span class="sc">{</span>kept<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(eig_g[<span class="op">-</span><span class="dv">1</span>], lam_g[<span class="dv">0</span>])</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(<span class="bu">abs</span>(vec_g[:, <span class="op">-</span><span class="dv">1</span>] <span class="op">@</span> Vtg[<span class="dv">0</span>]), <span class="fl">1.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>cov route top eigenvalue 2.1906723037
svd route sigma^2/(n-1)  2.1906723037
|cos| between the two PC1s: 1.000000000000
explained variance ratio: [0.6566 0.0813 0.0649 0.0534]
cumulative              : [0.6566 0.7379 0.8028 0.8563]
  rank 1: relative reconstruction error 0.3434, energy kept 0.6566
  rank 2: relative reconstruction error 0.2621, energy kept 0.7379
  rank 3: relative reconstruction error 0.1972, energy kept 0.8028
  rank 4: relative reconstruction error 0.1437, energy kept 0.8563</code></pre>
</div>
</div>
<p>PC1 accounts for 65.66% of the variance. We inspect its loadings before interpreting that fraction as a taste dimension.</p>
<div id="movielens-pc1" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>order <span class="op">=</span> np.argsort(<span class="op">-</span>np.<span class="bu">abs</span>(Vtg[<span class="dv">0</span>]))</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"PC1 loadings, largest magnitude first:"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> j <span class="kw">in</span> order:</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"   </span><span class="sc">{</span>genres<span class="sc">.</span>columns[j]<span class="sc">:12s}</span><span class="ss"> </span><span class="sc">{</span>Vtg[<span class="dv">0</span>][j]<span class="sc">:+.3f}</span><span class="ss">"</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>pc1_scores <span class="op">=</span> Gc <span class="op">@</span> Vtg[<span class="dv">0</span>]</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>user_mean <span class="op">=</span> G.mean(axis<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>r <span class="op">=</span> <span class="bu">float</span>(np.corrcoef(pc1_scores, user_mean)[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">corr(PC1 score, that user's mean rating over all 12 genres) = </span><span class="sc">{</span>r<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">abs</span>(r) <span class="op">&gt;</span> <span class="fl">0.99</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>PC1 loadings, largest magnitude first:
   Adventure    +0.316
   Horror       +0.313
   Action       +0.308
   Children's   +0.306
   Sci-Fi       +0.287
   Thriller     +0.284
   War          +0.281
   Mystery      +0.278
   Romance      +0.276
   Comedy       +0.272
   Crime        +0.269
   Drama        +0.267

corr(PC1 score, that user's mean rating over all 12 genres) = 0.9999</code></pre>
</div>
</div>
<p>The loadings have one sign and nearly equal magnitudes, between 0.267 and 0.316. The absolute correlation between PC1 scores and users’ unweighted mean genre rating is 0.9999: this component measures overall rating level, which we call rating generosity here.</p>
<p>That description does not identify a psychological trait. Film selection and genre overlap also affect the observed averages.</p>
</section>
<section id="sec-dropfirst" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="sec-dropfirst"><span class="header-section-number">7.3</span> Removing users’ overall levels</h3>
<p>If the task is to represent relative genre preferences, we can subtract each user’s mean genre rating before column centring. This specifies a nuisance direction in advance; simply dropping PC1 would only remove that direction when PCA happened to rank it first.</p>
<div id="movielens-drop-vs-debias" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> principal_angles(A, B):</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Angles in degrees between the column spaces of two matrices."""</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>    Qa, _ <span class="op">=</span> np.linalg.qr(A)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>    Qb, _ <span class="op">=</span> np.linalg.qr(B)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> np.linalg.svd(Qa.T <span class="op">@</span> Qb, compute_uv<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> np.degrees(np.arccos(np.clip(s, <span class="op">-</span><span class="fl">1.0</span>, <span class="fl">1.0</span>)))</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>R <span class="op">=</span> G <span class="op">-</span> G.mean(axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)         <span class="co"># remove each user's own level</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>Rc <span class="op">=</span> R <span class="op">-</span> R.mean(axis<span class="op">=</span><span class="dv">0</span>)                       <span class="co"># then centre the columns</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>Ur, Sr, Vtr <span class="op">=</span> np.linalg.svd(Rc, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>lam_r <span class="op">=</span> Sr<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (Rc.shape[<span class="dv">0</span>] <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"rank: </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>matrix_rank(Rc)<span class="sc">}</span><span class="ss"> after debiasing, "</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>matrix_rank(Gc)<span class="sc">}</span><span class="ss"> before"</span>)</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"angles between PC2-PC3 of the raw fit and PC1-PC2 of the debiased fit:"</span>,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>      principal_angles(Vtg[<span class="dv">1</span>:<span class="dv">3</span>].T, Vtr[:<span class="dv">2</span>].T).<span class="bu">round</span>(<span class="dv">2</span>), <span class="st">"deg"</span>)</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>share <span class="op">=</span> <span class="bu">float</span>((Rc <span class="op">@</span> Vtg[<span class="dv">0</span>]).var(ddof<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> Rc.var(axis<span class="op">=</span><span class="dv">0</span>, ddof<span class="op">=</span><span class="dv">1</span>).<span class="bu">sum</span>())</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"share of debiased variance lying along the raw PC1: </span><span class="sc">{</span>share<span class="sc">:.4%}</span><span class="ss">"</span>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> principal_angles(Vtg[<span class="dv">1</span>:<span class="dv">3</span>].T, Vtr[:<span class="dv">2</span>].T).<span class="bu">max</span>() <span class="op">&lt;</span> <span class="fl">5.0</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>rank: 11 after debiasing, 12 before
angles between PC2-PC3 of the raw fit and PC1-PC2 of the debiased fit: [0.2  1.33] deg
share of debiased variance lying along the raw PC1: 0.0453%</code></pre>
</div>
</div>
<p>On this table the two-dimensional spans differ by principal angles of <span class="math inline">\(0.20^\circ\)</span> and <span class="math inline">\(1.33^\circ\)</span>, so removing the mean and dropping raw PC1 produce similar retained spans. They are not identical operations in general.</p>
<p>Row centring reduces the rank from 12 to 11 because all rows become orthogonal to the all-ones vector. The first five variance shares then become 23.5%, 18.8%, 15.8%, 12.9%, and 9.9%: less concentrated than the original spectrum, but not tied eigenvalues.</p>
<div id="cell-fig-movielens" class="cell" data-fig-height="3.5" data-fig-width="8.6" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>fig, (ax_a, ax_b) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">8.6</span>, <span class="fl">3.5</span>))</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>ax_a.scatter(user_mean, pc1_scores, s<span class="op">=</span><span class="dv">14</span>, color<span class="op">=</span>TEAL, alpha<span class="op">=</span><span class="fl">0.65</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>ax_a.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"user's mean genre rating"</span>, ylabel<span class="op">=</span><span class="st">"raw PC1 score"</span>,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>         title<span class="op">=</span><span class="ss">f"Overall rating level (|r| = </span><span class="sc">{</span><span class="bu">abs</span>(r)<span class="sc">:.4f}</span><span class="ss">)"</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> values, name, colour <span class="kw">in</span> ((lam_g, <span class="st">"column-centred"</span>, ACCENT),</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                             (lam_r, <span class="st">"row- then column-centred"</span>, CORAL)):</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    ax_b.plot(np.arange(<span class="dv">1</span>, <span class="dv">13</span>), values <span class="op">/</span> values.<span class="bu">sum</span>(), <span class="st">"o-"</span>, ms<span class="op">=</span><span class="dv">4</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>              color<span class="op">=</span>colour, label<span class="op">=</span>name)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>ax_b.<span class="bu">set</span>(xlabel<span class="op">=</span><span class="st">"component"</span>, ylabel<span class="op">=</span><span class="st">"share of variance"</span>, title<span class="op">=</span><span class="st">"Changing the question"</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>ax_b.set_xticks([<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">6</span>, <span class="dv">9</span>, <span class="dv">12</span>])</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>ax_b.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>fig.tight_layout(pad<span class="op">=</span><span class="fl">1.1</span>)</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-movielens" class="quarto-float quarto-figure quarto-figure-center anchored" alt="A nearly straight scatter of mean genre rating against PC1 score, beside two component spectra. Raw PC1 explains about 66 percent; after row centring PC1 explains about 24 percent.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-movielens-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-movielens-output-1.png" class="img-fluid figure-img" alt="A nearly straight scatter of mean genre rating against PC1 score, beside two component spectra. Raw PC1 explains about 66 percent; after row centring PC1 explains about 24 percent.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-movielens-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Left: raw PC1 scores track users’ mean genre ratings. Right: variance shares before and after removing users’ means; each curve is normalized by its own total variance.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-limits" class="level3" data-number="7.4">
<h3 data-number="7.4" class="anchored" data-anchor-id="interpretation-limits"><span class="header-section-number">7.4</span> Interpretation limits</h3>
<ul>
<li><strong>Counts are not an independent-error model.</strong> The approximation <span class="math inline">\(\operatorname{Var}(\bar r_{ij})=s^2/n_{ij}\)</span> needs sampling assumptions. Genre overlap induces covariance between cell means, so a diagonal noise covariance would omit part of the uncertainty.</li>
<li><strong>This spectrum does not choose a recommender’s dimension.</strong> A stable subspace can still predict poorly. Choosing <span class="math inline">\(k\)</span> for recommendations requires held-out ratings and a pipeline that fits preprocessing on training data.</li>
<li><strong>No noise fraction or deployment threshold is inferred here.</strong> Quantifying them would require a rating-level model or resampling scheme that preserves the overlaps, followed by task-specific validation.</li>
</ul>
</section>
</section>
<section id="sec-metabolome" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="sec-metabolome"><span class="header-section-number">8</span> Neutrophil metabolomics</h2>
<section id="data-and-task-1" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="data-and-task-1"><span class="header-section-number">8.1</span> Data and task</h3>
<ul>
<li><strong>Source.</strong> Li et al.&nbsp;(2023), Metabolomics Workbench study ST002477, CC BY 4.0: LC-MS peak areas for 285 metabolites in neutrophils from 75 people, labelled Control (19), Mild (30), or Severe (26) COVID-19. The researchers isolated neutrophils to study their metabolic state during disease.</li>
<li><strong>Matrix.</strong> We use the complete <span class="math inline">\(75\times285\)</span> matrix, with samples as rows. Peak areas measure relative ion intensities, not metabolic fluxes.</li>
<li><strong>Question.</strong> How does preprocessing change the leading component, and are its scores associated with the disease groups? PCA describes variation without using those labels to fit the directions.</li>
<li><strong>Consequence of error.</strong> Mistaking technical variation for a biological association could misdirect follow-up experiments. The supplied metadata contains only sample IDs and disease groups; it cannot establish whether batch or run order is confounded with disease.</li>
</ul>
<div id="metabolome-load" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>abund <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">"abundances.tsv"</span>, sep<span class="op">=</span><span class="st">"</span><span class="ch">\t</span><span class="st">"</span>, index_col<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>meta <span class="op">=</span> pd.read_csv(DATA <span class="op">/</span> <span class="st">"samples.tsv"</span>, sep<span class="op">=</span><span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">list</span>(abund.columns) <span class="op">==</span> <span class="bu">list</span>(meta[<span class="st">"sample_id"</span>])</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>Xm_raw <span class="op">=</span> abund.to_numpy(dtype<span class="op">=</span>np.float64).T</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> meta[<span class="st">"group"</span>].to_numpy()</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Code severity once, here, and refuse anything the coding does not cover: a</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="co"># fourth group or a stray case variant would otherwise be silently scored as</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Severe and shift every correlation computed from it.</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>GROUPS <span class="op">=</span> (<span class="st">"Control"</span>, <span class="st">"Mild"</span>, <span class="st">"Severe"</span>)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> <span class="bu">set</span>(labels) <span class="op">==</span> <span class="bu">set</span>(GROUPS), <span class="bu">sorted</span>(<span class="bu">set</span>(labels))</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>severity <span class="op">=</span> np.select([labels <span class="op">==</span> <span class="st">"Control"</span>, labels <span class="op">==</span> <span class="st">"Mild"</span>], [<span class="fl">0.0</span>, <span class="fl">1.0</span>], <span class="fl">2.0</span>)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>t <span class="op">=</span> np.log1p(Xm_raw)</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>median <span class="op">=</span> np.median(t, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>iqr <span class="op">=</span> np.subtract(<span class="op">*</span>np.percentile(t, [<span class="dv">75</span>, <span class="dv">25</span>], axis<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>iqr <span class="op">=</span> np.where(iqr <span class="op">==</span> <span class="fl">0.0</span>, <span class="fl">1.0</span>, iqr)</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>Zm <span class="op">=</span> (t <span class="op">-</span> median) <span class="op">/</span> iqr</span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>Xm <span class="op">=</span> Zm <span class="op">-</span> Zm.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>n_m, d_m <span class="op">=</span> Xm.shape</span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"matrix: </span><span class="sc">{</span>n_m<span class="sc">}</span><span class="ss"> samples x </span><span class="sc">{</span>d_m<span class="sc">}</span><span class="ss"> metabolites"</span>)</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"groups:"</span>, {g: <span class="bu">int</span>((labels <span class="op">==</span> g).<span class="bu">sum</span>()) <span class="cf">for</span> g <span class="kw">in</span> GROUPS})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>matrix: 75 samples x 285 metabolites
groups: {'Control': 19, 'Mild': 30, 'Severe': 26}</code></pre>
</div>
</div>
</section>
<section id="sec-metabolome-scaling" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="sec-metabolome-scaling"><span class="header-section-number">8.2</span> Comparing preprocessing routes</h3>
<p>We compare raw covariance PCA, correlation PCA, and PCA after <span class="math inline">\(\log(1+x)\)</span> plus IQR scaling. The log/IQR route matches <a href="../neutrophil-metabolome-axis/">Neutrophil Metabolomes as a Matrix</a>; it compresses large peak areas and reduces the influence of extreme observations on the scale estimate.</p>
<p>The added 1 assumes the numerical units in this file: changing those units changes <span class="math inline">\(\log(1+x)\)</span>. The transform is a stated analysis choice, not a universal correction for skew or outliers.</p>
<div id="metabolome-scaling" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>raw_var <span class="op">=</span> Xm_raw.var(axis<span class="op">=</span><span class="dv">0</span>, ddof<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>names_m <span class="op">=</span> abund.index.to_numpy()</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fit(M):</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>    A <span class="op">=</span> M <span class="op">-</span> M.mean(axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>    _, singular, Vt_ <span class="op">=</span> np.linalg.svd(A, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> A, Vt_, singular<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> np.<span class="bu">sum</span>(singular<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>A_cov, Vt_cov_m, r_cov <span class="op">=</span> fit(Xm_raw)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>A_cor, Vt_cor_m, r_cor <span class="op">=</span> fit(Xm_raw <span class="op">/</span> Xm_raw.std(axis<span class="op">=</span><span class="dv">0</span>, ddof<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>A_log, Vt_log_m, r_log <span class="op">=</span> fit(Zm)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>routes <span class="op">=</span> {<span class="st">"raw"</span>: (A_cov, Vt_cov_m, r_cov),</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>          <span class="st">"standardized"</span>: (A_cor, Vt_cor_m, r_cor),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>          <span class="st">"log/IQR"</span>: (A_log, Vt_log_m, r_log)}</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>route_scores <span class="op">=</span> {name: A <span class="op">@</span> Vt_[<span class="dv">0</span>] <span class="cf">for</span> name, (A, Vt_, _) <span class="kw">in</span> routes.items()}</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"largest/smallest raw feature variance: </span><span class="sc">{</span>raw_var<span class="sc">.</span><span class="bu">max</span>() <span class="op">/</span> raw_var<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>biggest <span class="op">=</span> <span class="bu">int</span>(np.argmax(raw_var))</span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"largest-variance metabolite: </span><span class="sc">{</span>names_m[biggest]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"its share of raw squared PC1 loading: </span><span class="sc">{</span>Vt_cov_m[<span class="dv">0</span>, biggest]<span class="op">**</span><span class="dv">2</span><span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, (_, _, ratios) <span class="kw">in</span> routes.items():</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    agreement <span class="op">=</span> <span class="bu">abs</span>(np.corrcoef(route_scores[name], route_scores[<span class="st">"log/IQR"</span>])[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>    association <span class="op">=</span> <span class="bu">abs</span>(np.corrcoef(route_scores[name], severity)[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:12s}</span><span class="ss">: PC1 </span><span class="sc">{</span>ratios[<span class="dv">0</span>]<span class="sc">:.1%}</span><span class="ss">; |corr with log/IQR scores| "</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>agreement<span class="sc">:.4f}</span><span class="ss">; |corr with severity| </span><span class="sc">{</span>association<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>largest/smallest raw feature variance: 9.49e+09
largest-variance metabolite: choline
its share of raw squared PC1 loading: 51.9%
raw         : PC1 49.5%; |corr with log/IQR scores| 0.6159; |corr with severity| 0.4561
standardized: PC1 16.1%; |corr with log/IQR scores| 0.9811; |corr with severity| 0.5472
log/IQR     : PC1 20.7%; |corr with log/IQR scores| 1.0000; |corr with severity| 0.5363</code></pre>
</div>
</div>
<p>Raw feature variances span a factor of <span class="math inline">\(9.49\times10^9\)</span>. Raw PC1 explains 49.5% of the variance and assigns 51.9% of its squared loading to choline alone, the highest-variance column.</p>
<p>The standardized and log/IQR score vectors have absolute correlation 0.9811; the raw and log/IQR scores have absolute correlation 0.6159. These compare how the routes arrange the same 75 samples, without mixing loading vectors expressed in different coordinates.</p>
<p>Absolute correlations with severity are 0.4561 (raw), 0.5472 (standardized), and 0.5363 (log/IQR). These are descriptive associations with an ordinal label coded 0/1/2, which assumes equal spacing between categories; they do not rank the preprocessing choices.</p>
<p>The correlations share observations and the severity variable. A standard error for one correlation cannot establish whether their difference is meaningful; that requires joint uncertainty, such as a paired resampling analysis that refits preprocessing and PCA.</p>
<div id="cell-fig-scaling" class="cell" data-fig-height="3.4" data-fig-width="8.6" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>fig, (ax_v, ax_l) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">8.6</span>, <span class="fl">3.4</span>))</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>ax_v.semilogy(np.sort(raw_var)[::<span class="op">-</span><span class="dv">1</span>], color<span class="op">=</span>ACCENT, lw<span class="op">=</span><span class="fl">1.6</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>ax_v.set_xlabel(<span class="st">"metabolite, sorted by variance"</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>ax_v.set_ylabel(<span class="st">"variance as measured (log scale)"</span>)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>ax_v.set_title(<span class="st">"Ten orders of magnitude"</span>)</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>ax_l.semilogy(np.sort(Vt_cov_m[<span class="dv">0</span>] <span class="op">**</span> <span class="dv">2</span>)[::<span class="op">-</span><span class="dv">1</span>], color<span class="op">=</span>CORAL, lw<span class="op">=</span><span class="fl">1.6</span>,</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>              label<span class="op">=</span><span class="st">"covariance, as measured"</span>)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>ax_l.semilogy(np.sort(Vt_log_m[<span class="dv">0</span>] <span class="op">**</span> <span class="dv">2</span>)[::<span class="op">-</span><span class="dv">1</span>], color<span class="op">=</span>TEAL, lw<span class="op">=</span><span class="fl">1.6</span>,</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>              label<span class="op">=</span><span class="st">"log1p + IQR"</span>)</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>ax_l.axhline(<span class="dv">1</span> <span class="op">/</span> d_m, color<span class="op">=</span>MUTED, lw<span class="op">=</span><span class="fl">1.0</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>ax_l.text(d_m, <span class="dv">1</span> <span class="op">/</span> d_m <span class="op">*</span> <span class="fl">1.4</span>, <span class="st">"equal weight on every metabolite"</span>,</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>          color<span class="op">=</span>MUTED, fontsize<span class="op">=</span><span class="fl">7.5</span>, ha<span class="op">=</span><span class="st">"right"</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>ax_l.set_xlabel(<span class="st">"metabolite, sorted by loading"</span>)</span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>ax_l.set_ylabel(<span class="st">"squared PC1 loading (log scale)"</span>)</span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>ax_l.legend(frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="fl">7.5</span>, loc<span class="op">=</span><span class="st">"lower left"</span>)</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a>ax_l.set_title(<span class="st">"PC1 weight concentration"</span>)</span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>fig.tight_layout(pad<span class="op">=</span><span class="fl">1.1</span>)</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-scaling" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two panels. The left is a steeply falling curve of variance against metabolite rank on a log scale spanning ten decades. The right shows two sorted squared-loading curves: the covariance one starts above 0.5 and collapses, the log/IQR one starts near 0.01 and decays gently.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scaling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-scaling-output-1.png" class="img-fluid figure-img" alt="Two panels. The left is a steeply falling curve of variance against metabolite rank on a log scale spanning ten decades. The right shows two sorted squared-loading curves: the covariance one starts above 0.5 and collapses, the log/IQR one starts near 0.01 and decays gently.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scaling-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Left: per-metabolite variance as measured, sorted, over ten orders of magnitude. Right: squared loadings of PC1, sorted, under covariance PCA on the file as measured and under the log/IQR transform.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The squared loadings describe weight concentration within each route’s coordinates. They are not raw-unit effect sizes or evidence that log/IQR has recovered a biological direction.</p>
</section>
<section id="wide-matrices" class="level3" data-number="8.3">
<h3 data-number="8.3" class="anchored" data-anchor-id="wide-matrices"><span class="header-section-number">8.3</span> Wide matrices</h3>
<p>With <span class="math inline">\(n=75\)</span> and <span class="math inline">\(d=285\)</span>, centring caps the rank at <span class="math inline">\(n-1=74\)</span>. At least 211 covariance eigenvalues must be zero; that arithmetic does not imply that 211 biological processes are absent.</p>
<div id="metabolome-pca" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>Um, Sm, Vtm <span class="op">=</span> np.linalg.svd(Xm, full_matrices<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>lam_m <span class="op">=</span> Sm<span class="op">**</span><span class="dv">2</span> <span class="op">/</span> (n_m <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"rank(X) = </span><span class="sc">{</span>np<span class="sc">.</span>linalg<span class="sc">.</span>matrix_rank(Xm)<span class="sc">}</span><span class="ss">, min(n, d) = </span><span class="sc">{</span><span class="bu">min</span>(n_m, d_m)<span class="sc">}</span><span class="ss">, n - 1 = </span><span class="sc">{</span>n_m <span class="op">-</span> <span class="dv">1</span><span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"non-negligible singular values: </span><span class="sc">{</span><span class="bu">int</span>((Sm <span class="op">&gt;</span> <span class="fl">1e-9</span> <span class="op">*</span> Sm[<span class="dv">0</span>]).<span class="bu">sum</span>())<span class="sc">}</span><span class="ss"> of </span><span class="sc">{</span><span class="bu">len</span>(Sm)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>cov <span class="op">=</span> Xm.T <span class="op">@</span> Xm <span class="op">/</span> (n_m <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>eig_m, vec_m <span class="op">=</span> np.linalg.eigh(cov)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"covariance matrix is </span><span class="sc">{</span>cov<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> x </span><span class="sc">{</span>cov<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"cov route top eigenvalue </span><span class="sc">{</span>eig_m[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.10f}</span><span class="ss">"</span>)</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"svd route sigma^2/(n-1)  </span><span class="sc">{</span>lam_m[<span class="dv">0</span>]<span class="sc">:.10f}</span><span class="ss">"</span>)</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"|cos| between the two PC1s: </span><span class="sc">{</span><span class="bu">abs</span>(vec_m[:, <span class="op">-</span><span class="dv">1</span>] <span class="op">@</span> Vtm[<span class="dv">0</span>])<span class="sc">:.12f}</span><span class="ss">"</span>)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"explained variance ratio:"</span>, (lam_m <span class="op">/</span> lam_m.<span class="bu">sum</span>())[:<span class="dv">4</span>].<span class="bu">round</span>(<span class="dv">4</span>))</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.linalg.matrix_rank(Xm) <span class="op">==</span> n_m <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(eig_m[<span class="op">-</span><span class="dv">1</span>], lam_m[<span class="dv">0</span>])</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(<span class="bu">abs</span>(vec_m[:, <span class="op">-</span><span class="dv">1</span>] <span class="op">@</span> Vtm[<span class="dv">0</span>]), <span class="fl">1.0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>rank(X) = 74, min(n, d) = 75, n - 1 = 74
non-negligible singular values: 74 of 75
covariance matrix is 285 x 285
cov route top eigenvalue 47.4693303238
svd route sigma^2/(n-1)  47.4693303238
|cos| between the two PC1s: 1.000000000000
explained variance ratio: [0.2073 0.1136 0.0596 0.055 ]</code></pre>
</div>
</div>
<p>The covariance and SVD routes agree on the leading direction and eigenvalue. Both are feasible at this size; direct SVD avoids the larger covariance matrix and the loss of numerical accuracy from forming it.</p>
<div id="metabolome-scores" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>scores_m <span class="op">=</span> Xm <span class="op">@</span> Vtm[:<span class="dv">2</span>].T</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>corr_sev <span class="op">=</span> <span class="bu">float</span>(np.corrcoef(scores_m[:, <span class="dv">0</span>], severity)[<span class="dv">0</span>, <span class="dv">1</span>])</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"PC1 </span><span class="sc">{</span>lam_m[<span class="dv">0</span>] <span class="op">/</span> lam_m<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1%}</span><span class="ss"> of variance, "</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"PC2 </span><span class="sc">{</span>lam_m[<span class="dv">1</span>] <span class="op">/</span> lam_m<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1%}</span><span class="ss">, "</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"first two together </span><span class="sc">{</span>np<span class="sc">.</span>cumsum(lam_m <span class="op">/</span> lam_m.<span class="bu">sum</span>())[<span class="dv">1</span>]<span class="sc">:.1%}</span><span class="ss">"</span>)</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> g <span class="kw">in</span> GROUPS:</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> scores_m[labels <span class="op">==</span> g, <span class="dv">0</span>]</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  </span><span class="sc">{</span>g<span class="sc">:8s}</span><span class="ss"> PC1 mean </span><span class="sc">{</span>s<span class="sc">.</span>mean()<span class="sc">:+6.2f}</span><span class="ss">  sd </span><span class="sc">{</span>s<span class="sc">.</span>std()<span class="sc">:5.2f}</span><span class="ss">"</span>)</span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"corr(PC1 score, severity coded 0/1/2) = </span><span class="sc">{</span>corr_sev<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">74</span>):</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>    W <span class="op">=</span> Vtm[:k].T</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>    rel <span class="op">=</span> np.<span class="bu">sum</span>((Xm <span class="op">-</span> Xm <span class="op">@</span> W <span class="op">@</span> W.T) <span class="op">**</span> <span class="dv">2</span>) <span class="op">/</span> np.<span class="bu">sum</span>(Xm<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"  rank </span><span class="sc">{</span>k<span class="sc">:3d}</span><span class="ss">: relative reconstruction error </span><span class="sc">{</span>rel<span class="sc">:.4f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>PC1 20.7% of variance, PC2 11.4%, first two together 32.1%
  Control  PC1 mean  -6.95  sd  7.74
  Mild     PC1 mean  +1.75  sd  5.37
  Severe   PC1 mean  +3.06  sd  3.13
corr(PC1 score, severity coded 0/1/2) = 0.5363
  rank   1: relative reconstruction error 0.7927
  rank   2: relative reconstruction error 0.6791
  rank   5: relative reconstruction error 0.5156
  rank  10: relative reconstruction error 0.3571
  rank  74: relative reconstruction error 0.0000</code></pre>
</div>
</div>
<p>PC1 explains 20.7% and PC2 11.4%, for 32.1% together. The group means differ along PC1, but the observations overlap; the sign of the scores is arbitrary.</p>
<div id="cell-fig-metabolome" class="cell" data-fig-height="3.6" data-fig-width="8.6" data-execution_count="16">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>fig, (ax_s, ax_p) <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="fl">8.6</span>, <span class="fl">3.6</span>))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># All d eigenvalues of the covariance, not the n kept by the thin SVD, so the</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 211 that are zero for want of samples are on the page.</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>spectrum <span class="op">=</span> eig_m[::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>floor <span class="op">=</span> spectrum[: n_m <span class="op">-</span> <span class="dv">1</span>].<span class="bu">min</span>() <span class="op">*</span> <span class="fl">1e-2</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>ax_s.semilogy(np.arange(<span class="dv">1</span>, d_m <span class="op">+</span> <span class="dv">1</span>), np.maximum(spectrum, floor),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>              color<span class="op">=</span>ACCENT, lw<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>ax_s.axvline(n_m <span class="op">-</span> <span class="dv">1</span>, color<span class="op">=</span>CORAL, lw<span class="op">=</span><span class="fl">1.0</span>, ls<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>ax_s.annotate(<span class="ss">f"rank </span><span class="sc">{</span>n_m <span class="op">-</span> <span class="dv">1</span><span class="sc">}</span><span class="ss"> = n − 1"</span>, xy<span class="op">=</span>(n_m <span class="op">+</span> <span class="dv">8</span>, spectrum[<span class="dv">0</span>] <span class="op">*</span> <span class="fl">0.15</span>),</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>              color<span class="op">=</span>CORAL, fontsize<span class="op">=</span><span class="dv">8</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>ax_s.set_ylim(floor <span class="op">*</span> <span class="fl">0.5</span>, spectrum[<span class="dv">0</span>] <span class="op">*</span> <span class="dv">3</span>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>ax_s.set_xlabel(<span class="st">"component index"</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>ax_s.set_ylabel(<span class="st">"eigenvalue (log scale)"</span>)</span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>ax_s.set_title(<span class="ss">f"</span><span class="sc">{</span>d_m<span class="sc">}</span><span class="ss"> features, </span><span class="sc">{</span>n_m <span class="op">-</span> <span class="dv">1</span><span class="sc">}</span><span class="ss"> directions"</span>)</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>COLOURS <span class="op">=</span> {<span class="st">"Control"</span>: TEAL, <span class="st">"Mild"</span>: GOLD, <span class="st">"Severe"</span>: CORAL}</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> g <span class="kw">in</span> GROUPS:</span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>    sel <span class="op">=</span> labels <span class="op">==</span> g</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a>    ax_p.scatter(scores_m[sel, <span class="dv">0</span>], scores_m[sel, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">26</span>,</span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>                 color<span class="op">=</span>COLOURS[g], alpha<span class="op">=</span><span class="fl">0.85</span>, label<span class="op">=</span>g)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>ax_p.set_xlabel(<span class="ss">f"PC1 (</span><span class="sc">{</span>lam_m[<span class="dv">0</span>] <span class="op">/</span> lam_m<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1%}</span><span class="ss">)"</span>)</span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a>ax_p.set_ylabel(<span class="ss">f"PC2 (</span><span class="sc">{</span>lam_m[<span class="dv">1</span>] <span class="op">/</span> lam_m<span class="sc">.</span><span class="bu">sum</span>()<span class="sc">:.1%}</span><span class="ss">)"</span>)</span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>ax_p.legend(frameon<span class="op">=</span><span class="va">True</span>, framealpha<span class="op">=</span><span class="fl">0.9</span>, edgecolor<span class="op">=</span>RULE, fontsize<span class="op">=</span><span class="dv">8</span>,</span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a>            loc<span class="op">=</span><span class="st">"lower left"</span>, scatterpoints<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a>ax_p.set_title(<span class="st">"Scores, coloured after the fact"</span>)</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-28"><a href="#cb27-28" aria-hidden="true" tabindex="-1"></a>fig.tight_layout(pad<span class="op">=</span><span class="fl">1.1</span>)</span>
<span id="cb27-29"><a href="#cb27-29" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-metabolome" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Two panels. The left is a log-scale plot of eigenvalue against index for 285 components, decaying smoothly then dropping off a cliff at index 74 to a flat floor. The right is a scatter of 75 points on two principal components, coloured in three groups that overlap substantially.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-metabolome-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-metabolome-output-1.png" class="img-fluid figure-img" alt="Two panels. The left is a log-scale plot of eigenvalue against index for 285 components, decaying smoothly then dropping off a cliff at index 74 to a flat floor. The right is a scatter of 75 points on two principal components, coloured in three groups that overlap substantially.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-metabolome-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Left: all 285 covariance eigenvalues, cut off at 74 by the sample count. Eigenvalues past 74 are zero and are drawn at a floor so the log axis can hold them. Right: the 75 samples on PC1 and PC2, coloured by COVID label.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interpretation-limits-1" class="level3" data-number="8.4">
<h3 data-number="8.4" class="anchored" data-anchor-id="interpretation-limits-1"><span class="header-section-number">8.4</span> Interpretation limits</h3>
<ul>
<li><strong>Association is observable; its source is unresolved.</strong> PC1 is associated with the coded severity label. If processing batch also follows severity, that association could be technical, biological, or both. <a href="https://www.nature.com/articles/nrg2825">Leek et al.&nbsp;(2010)</a> show how this confounding can mislead high-throughput analyses.</li>
<li><strong>This is not a passed QC gate.</strong> Batch and run-order metadata, technical controls, and the experimental design are needed to assess technical effects before differential-abundance analysis. Neither label separation nor its absence supplies that assessment by itself.</li>
<li><strong>Overlap limits prediction claims.</strong> The plot does not validate an individual severity score. It also does not prove that PC1 lacks disease-related information; prediction would need independent evaluation.</li>
<li><strong>Compression has a measurable cost.</strong> Rank 10 leaves 35.71% of the transformed matrix’s squared magnitude unreconstructed. Whether that loss is acceptable depends on the intended task, not on the rank bound alone.</li>
</ul>
</section>
</section>
<section id="constraints" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="constraints"><span class="header-section-number">9</span> Constraints</h2>
<ul>
<li><strong>Missing entries.</strong> With an observation mask, the observed data’s squared magnitude is fixed, but residuals are no longer orthogonal under the masked loss. The unweighted projector split therefore does not transfer to observed-entry fitting. Filling the holes makes classical PCA computable, while making the answer depend on the filling rule.</li>
<li><strong>Loss choice.</strong> The trace and variance identities rely on squared Frobenius error. Truncated SVD also minimizes rank-constrained error in any unitarily invariant norm, including the spectral norm, by Eckart–Young–Mirsky. Entrywise <span class="math inline">\(\ell_1\)</span> and Huber losses generally require different solutions.</li>
<li><strong>Stability.</strong> A boundary eigenvalue gap concerns uniqueness; its size relative to perturbations concerns estimation stability. Neither a flat-looking scree plot nor an average noise level is a universal cutoff for <span class="math inline">\(k\)</span>.</li>
<li><strong>Interpretation.</strong> Large variance can reflect measurement scale, overall response level, technical effects, or biology. Explained variance measures reconstruction of the chosen matrix; it does not measure predictive usefulness or causality.</li>
</ul>
</section>
<section id="related-questions" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="related-questions"><span class="header-section-number">10</span> Related questions</h2>
<p><a href="../probabilistic-pca/">Probabilistic PCA</a> adds a Gaussian model and a posterior distribution for latent coordinates. Its fitted principal subspace agrees with classical PCA under the stated model, while its posterior reconstruction generally shrinks toward the mean.</p>
<p>Tensor PCA is a topic for a separate post.</p>
<p>Centre. Scale. Fix. Geometry. Fit. Subspaces. Check. Stability. Validate. Interpretation.</p>
</section>
<section id="references" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="references"><span class="header-section-number">11</span> References</h2>
<ul>
<li>Eckart, C., and Young, G. (1936). <a href="https://doi.org/10.1007/BF02288367">The approximation of one matrix by another of lower rank</a>. <em>Psychometrika</em> 1(3), 211–218.</li>
<li>Golub, G. H., and Van Loan, C. F. (2013). <em>Matrix Computations</em>, 4th edition. Johns Hopkins University Press.</li>
<li>Hotelling, H. (1933). <a href="https://doi.org/10.1037/h0071325">Analysis of a complex of statistical variables into principal components</a>. <em>Journal of Educational Psychology</em> 24(6), 417–441.</li>
<li>Leek, J. T., et al.&nbsp;(2010). <a href="https://www.nature.com/articles/nrg2825">Tackling the widespread and critical impact of batch effects in high-throughput data</a>. <em>Nature Reviews Genetics</em> 11, 733–739.</li>
<li>Li, Y., et al.&nbsp;(2023). Neutrophil metabolomics in COVID-19. Metabolomics Workbench study <a href="https://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&amp;StudyID=ST002477">ST002477</a>, CC BY 4.0.</li>
<li>Mirsky, L. (1960). <a href="https://doi.org/10.1093/qmath/11.1.50">Symmetric gauge functions and unitarily invariant norms</a>. <em>The Quarterly Journal of Mathematics</em> 11(1), 50–59.</li>
<li>Pearson, K. (1901). <a href="https://doi.org/10.1080/14786440109462720">On lines and planes of closest fit to systems of points in space</a>. <em>Philosophical Magazine</em> 2(11), 559–572.</li>
<li><a href="https://grouplens.org/datasets/movielens/100k/">MovieLens 100K</a> — GroupLens, University of Minnesota.</li>
<li><a href="../eigendecomposition/">The Directions a Matrix Refuses to Turn</a> — eigenvectors and eigenvalues.</li>
<li><a href="../svd-rotate-stretch-rotate/">The Matrix That Rotates, Stretches, and Rotates Again</a> — SVD geometry and numerical accuracy.</li>
<li><a href="../neutrophil-metabolome-axis/">Neutrophil Metabolomes as a Matrix</a> — clustering the 75 × 285 file.</li>
<li><a href="../probabilistic-pca/">Probabilistic PCA</a> — a Gaussian latent-variable model, its fit, and posterior reconstruction.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/project-delphi\.github\.io\/ml-blog\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Synthetic Musings, by Ravi Kalia</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/six-views-of-pca/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>Built with <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>