{
  "hash": "1a53a3a1219ffcd4c9709509a5a6e7b9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Soft Prompts vs. Hard Prompts\"\ndescription: \"Initialise a soft prompt from real words and it sits exactly on the vocabulary. Sixty gradient steps later it is somewhere no sentence can reach.\"\nauthor: \"Ravi Kalia\"\ndate: \"2025-03-30\"\ncategories: [AI, NLP, Prompt Engineering]\nimage: \"./cover.png\"\ntags: [prompts, peft, prompt-tuning, gpt2]\njupyter: huggingface-blog\nformat:\n  html:\n    toc: true\n    code-fold: true\n---\n\n\n![Soft Prompts vs. Hard Prompts](./cover.png)\n\nEvery prompt you have ever typed is a sequence of tokens, and every token is an index into a lookup table of vectors. The model never sees your words; it sees the vectors those words select. That table has 50,257 rows for GPT-2, and writing a prompt means picking a path through them.\n\nWhich raises the question this post is about: why restrict yourself to rows of the table? The vectors live in a continuous 768-dimensional space, and the ones the vocabulary happens to occupy are a vanishingly small, arbitrary subset of it. A **soft prompt** is what you get when you drop the restriction \u2014 a sequence of vectors optimised directly by gradient descent, free to land anywhere.\n\nThe claim is that this is a genuine expansion rather than a reparameterisation, and it is demonstrable. Below, a soft prompt is initialised from the words *\"Classify the review sentiment:\"* \u2014 so it starts exactly on the vocabulary \u2014 and after sixty training steps it has moved somewhere that no sequence of tokens can express.\n\n## Hard prompts are a discrete search\n\nA hard prompt is text. Its virtues are that you can read it, version it, paste it into a bug report, and move it between models without retraining. Its limitation is that improving it means *search* over a discrete space, guided by intuition, because there is no gradient from \"the output was wrong\" back to \"use the word *carefully* instead of *thoroughly*\".\n\n::: {#855d6f36 .cell execution_count=1}\n``` {.python .cell-code}\nimport warnings\n\nwarnings.filterwarnings(\"ignore\")\n\nimport torch\nfrom transformers import AutoTokenizer, AutoModelForCausalLM\n\nMODEL = \"openai-community/gpt2\"\ntokenizer = AutoTokenizer.from_pretrained(MODEL)\ntokenizer.pad_token = tokenizer.eos_token\nmodel = AutoModelForCausalLM.from_pretrained(MODEL)\n\nHARD_PROMPT = \"Classify the review sentiment:\"\nids = tokenizer(HARD_PROMPT, return_tensors=\"pt\")[\"input_ids\"]\nembeddings = model.get_input_embeddings()(ids)[0]\n\nprint(f\"prompt      : {HARD_PROMPT!r}\")\nprint(f\"tokens      : {tokenizer.convert_ids_to_tokens(ids[0])}\")\nprint(f\"becomes     : a {tuple(embeddings.shape)} tensor\")\nprint(f\"vocabulary  : {model.get_input_embeddings().weight.shape[0]:,} rows of width \"\n      f\"{model.get_input_embeddings().weight.shape[1]}\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<script type=\"application/vnd.jupyter.widget-view+json\">\n{\"model_id\":\"d1b84481a4544c9392d93447b144ae8f\",\"version_major\":2,\"version_minor\":0,\"quarto_mimetype\":\"application/vnd.jupyter.widget-view+json\"}\n</script>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nprompt      : 'Classify the review sentiment:'\ntokens      : ['Class', 'ify', '\u0120the', '\u0120review', '\u0120sentiment', ':']\nbecomes     : a (6, 768) tensor\nvocabulary  : 50,257 rows of width 768\n```\n:::\n:::\n\n\nSix tokens become six vectors of width 768. Everything the prompt does, it does through those vectors \u2014 and a hard prompt can only ever select from the 50,257 that the tokenizer knows about.\n\n## A soft prompt starts on the vocabulary\n\n`peft` implements soft prompts as a small tensor prepended to the input embeddings, with the entire model frozen. Crucially it can be *initialised from text*, which is what makes the comparison exact \u2014 we begin at the hard prompt and see where gradients take us.\n\n::: {#39baf45b .cell execution_count=2}\n``` {.python .cell-code}\nfrom peft import PromptTuningConfig, PromptTuningInit, TaskType, get_peft_model\n\nconfig = PromptTuningConfig(\n    task_type=TaskType.CAUSAL_LM,\n    num_virtual_tokens=8,\n    prompt_tuning_init=PromptTuningInit.TEXT,\n    prompt_tuning_init_text=HARD_PROMPT,\n    tokenizer_name_or_path=MODEL,\n)\npeft_model = get_peft_model(model, config)\npeft_model.print_trainable_parameters()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntrainable params: 6,144 || all params: 124,445,952 || trainable%: 0.0049\n```\n:::\n:::\n\n\n8 virtual tokens \u00d7 768 dimensions = 6,144 trainable parameters, 0.005% of GPT-2. Everything else is frozen \u2014 this is the same family of technique as LoRA, discussed in the [companion post on `peft`](../peft/index.qmd), but intervening on the input rather than on the weights.\n\nTo see where the soft prompt *is*, decode it: for each of its 8 vectors, find the vocabulary row it most resembles.\n\n::: {#fb2c5e43 .cell execution_count=3}\n``` {.python .cell-code}\nvocabulary = model.get_input_embeddings().weight.detach()\n\n\ndef nearest_tokens(prompt_vectors):\n    \"\"\"Closest vocabulary token to each prompt vector, by cosine similarity.\"\"\"\n    similarity = (\n        torch.nn.functional.normalize(prompt_vectors, dim=-1)\n        @ torch.nn.functional.normalize(vocabulary, dim=-1).T\n    )\n    best = similarity.max(-1)\n    return [tokenizer.decode([i]) for i in best.indices], best.values\n\n\nbefore = peft_model.get_prompt_embedding_to_save(\"default\").detach().clone()\ntokens_before, similarity_before = nearest_tokens(before)\n\nprint(f\"nearest tokens   : {tokens_before}\")\nprint(f\"mean similarity  : {similarity_before.mean():.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnearest tokens   : ['Class', 'ify', ' the', ' review', ' sentiment', ':', 'Class', 'ify']\nmean similarity  : 1.000\n```\n:::\n:::\n\n\nSimilarity 1.000, and the tokens spell out the original phrase. That is the point of initialising from text: at step zero the soft prompt *is* the hard prompt, exactly, so anything that happens next is attributable to training rather than to a different starting point.\n\n## Training moves it off the vocabulary\n\nNow optimise it on a tiny sentiment task \u2014 eight examples, all of the model frozen except those 6,144 numbers.\n\n::: {#8030471a .cell execution_count=4}\n``` {.python .cell-code}\nPOSITIVE = [\"great film\", \" loved it\", \" wonderful acting\", \" a masterpiece\"]\nNEGATIVE = [\"terrible film\", \" hated it\", \" awful acting\", \" a disaster\"]\n\nexamples = [f\"Review: {text} Sentiment: positive\" for text in POSITIVE] + [\n    f\"Review: {text} Sentiment: negative\" for text in NEGATIVE\n]\nbatch = tokenizer(examples, return_tensors=\"pt\", padding=True)\ntargets = batch[\"input_ids\"].clone()\ntargets[batch[\"attention_mask\"] == 0] = -100\n\noptimizer = torch.optim.AdamW(\n    [p for p in peft_model.parameters() if p.requires_grad], lr=0.05\n)\n\npeft_model.train()\nfor step in range(60):\n    output = peft_model(**batch, labels=targets)\n    output.loss.backward()\n    optimizer.step()\n    optimizer.zero_grad()\n    if step % 20 == 0:\n        print(f\"step {step:2d}  loss {output.loss.item():.4f}\")\nprint(f\"step 59  loss {output.loss.item():.4f}\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n[transformers] `loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nstep  0  loss 7.3566\nstep 20  loss 3.3505\nstep 40  loss 2.0130\nstep 59  loss 1.4409\n```\n:::\n:::\n\n\nThe loss falls substantially, and it fell by moving only the prompt. Now decode the prompt again:\n\n::: {#cfc1fd56 .cell execution_count=5}\n``` {.python .cell-code}\nafter = peft_model.get_prompt_embedding_to_save(\"default\").detach().clone()\ntokens_after, similarity_after = nearest_tokens(after)\n\nprint(f\"nearest tokens  : {tokens_after}\")\nprint(f\"mean similarity : {similarity_after.mean():.3f}   (was {similarity_before.mean():.3f})\")\nprint(f\"distance moved  : {(after - before).norm():.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nnearest tokens  : ['Class', 'ify', ' the', ' sitcom', ' sentiment', ':', 'Class', 'ify']\nmean similarity : 0.346   (was 1.000)\ndistance moved  : 30.7\n```\n:::\n:::\n\n\nThis is the result the post exists for. The mean similarity to the nearest real token has collapsed from **1.000 to roughly 0.33**, and the decoded tokens are no longer language \u2014 unrelated nouns and a fragment of mojibake, where the phrase used to be. The positions that barely moved still decode to their original tokens, which makes the contrast within the same prompt: some of it stayed near the vocabulary and some of it left.\n\nThe soft prompt has left the vocabulary. There is no longer any sentence you could type that would produce these vectors, which means whatever it learned is not expressible as a hard prompt at all. The continuous space genuinely contains instructions the discrete space does not.\n\n### Caveat: eight examples and no held-out set\n\nThe loss above is training loss on eight hand-written strings, and this training loss does not measure classification accuracy. It very likely overfits: 6,144 parameters against eight short examples is ample capacity to memorise them.\n\nThe drift result does not depend on that \u2014 the prompt provably left the vocabulary manifold regardless of whether it learned anything useful \u2014 but do not read the falling loss as evidence of a working classifier. Prompt tuning is known to need reasonably large base models before it becomes competitive with fine-tuning, and GPT-2 small is under that bar.\n\n## Which to reach for\n\nThe two are not competitors so much as different regimes, and the distinguishing question is whether you have labelled data and gradient access.\n\n| | Hard prompt | Soft prompt |\n|---|---|---|\n| Lives in | 50,257 discrete tokens | continuous \u211d\u2077\u2076\u2078 per position |\n| Improved by | human search, trial and error | gradient descent |\n| Needs | nothing | training data, backprop access |\n| Portable across models | yes | no \u2014 tied to one embedding space |\n| Human-readable | yes | no, as demonstrated above |\n| Works via API | yes | only if the provider exposes tuning |\n\nHard prompts are the default for good reasons: zero setup, they survive a model swap, and you can debug them by reading them. Soft prompts earn their place when you have a fixed task with labelled examples, you cannot or will not fine-tune the whole model, and you need more than words can express.\n\n## What the drift shows\n\nThe claim was that soft prompts are a real expansion of what a prompt can be, not a reparameterisation of text. The evidence is a single number moving: cosine similarity to the nearest real token, 1.000 at initialisation and about 0.33 after sixty steps. The prompt began as a sentence and ended somewhere unspeakable.\n\nThe cost of that expressiveness is the vocabulary: transfer, review, and a string you can type. A soft prompt is tied to the exact embedding matrix it was trained against, so it does not transfer to another model or survive a tokenizer change. It cannot be reviewed, diffed, or explained to a colleague. And it cannot be typed into a chat box \u2014 it is a tensor, and it has to be loaded as one.\n\nThat is the trade in one sentence: you gain the space between the words, and you lose the words.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n<script src=\"https://unpkg.com/@jupyter-widgets/html-manager@*/dist/embed-amd.js\" crossorigin=\"anonymous\"></script>\n"
      ],
      "include-after-body": [
        "<script type=application/vnd.jupyter.widget-state+json>\n{\"state\":{\"14a86915d6b04f6aa87cf72e524dc290\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_module_version\":\"2.0.0\",\"model_name\":\"HTMLStyleModel\",\"state\":{\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLStyleModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"StyleView\",\"background\":null,\"description_width\":\"\",\"font_size\":null,\"text_color\":null}},\"29329fbfa4864643afedf46bf8b89b00\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_module_version\":\"2.0.0\",\"model_name\":\"HTMLModel\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"HTMLView\",\"description\":\"\",\"description_allow_html\":false,\"layout\":\"IPY_MODEL_45f84ee82aae4d809342d20254714303\",\"placeholder\":\"\u200b\",\"style\":\"IPY_MODEL_14a86915d6b04f6aa87cf72e524dc290\",\"tabbable\":null,\"tooltip\":null,\"value\":\"\u2007148/148\u2007[00:00&lt;00:00,\u20078546.02it/s]\"}},\"34a1b6a1cf6e4ac6b014f8443a70843c\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_module_version\":\"2.0.0\",\"model_name\":\"HTMLModel\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"HTMLView\",\"description\":\"\",\"description_allow_html\":false,\"layout\":\"IPY_MODEL_bd9f97a59bbf4ccf9edfc8cbcb2a1f97\",\"placeholder\":\"\u200b\",\"style\":\"IPY_MODEL_9bb9c4a61d2b425582de2f8f27767fca\",\"tabbable\":null,\"tooltip\":null,\"value\":\"Loading\u2007weights:\u2007100%\"}},\"45f84ee82aae4d809342d20254714303\":{\"model_module\":\"@jupyter-widgets/base\",\"model_module_version\":\"2.0.0\",\"model_name\":\"LayoutModel\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}},\"5e8a7d9a86914b5da6617cd57b646df0\":{\"model_module\":\"@jupyter-widgets/base\",\"model_module_version\":\"2.0.0\",\"model_name\":\"LayoutModel\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}},\"886277c08fc24d4a96937d36c721b32e\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_module_version\":\"2.0.0\",\"model_name\":\"ProgressStyleModel\",\"state\":{\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"ProgressStyleModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"StyleView\",\"bar_color\":null,\"description_width\":\"\"}},\"9bb9c4a61d2b425582de2f8f27767fca\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_module_version\":\"2.0.0\",\"model_name\":\"HTMLStyleModel\",\"state\":{\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HTMLStyleModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"StyleView\",\"background\":null,\"description_width\":\"\",\"font_size\":null,\"text_color\":null}},\"9c4a7ec2428e40c7bd2c9ee9a5a2411d\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_module_version\":\"2.0.0\",\"model_name\":\"FloatProgressModel\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"FloatProgressModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"ProgressView\",\"bar_style\":\"success\",\"description\":\"\",\"description_allow_html\":false,\"layout\":\"IPY_MODEL_e89f152a93244c3ca651d7a4bed90617\",\"max\":148,\"min\":0,\"orientation\":\"horizontal\",\"style\":\"IPY_MODEL_886277c08fc24d4a96937d36c721b32e\",\"tabbable\":null,\"tooltip\":null,\"value\":148}},\"bd9f97a59bbf4ccf9edfc8cbcb2a1f97\":{\"model_module\":\"@jupyter-widgets/base\",\"model_module_version\":\"2.0.0\",\"model_name\":\"LayoutModel\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}},\"d1b84481a4544c9392d93447b144ae8f\":{\"model_module\":\"@jupyter-widgets/controls\",\"model_module_version\":\"2.0.0\",\"model_name\":\"HBoxModel\",\"state\":{\"_dom_classes\":[],\"_model_module\":\"@jupyter-widgets/controls\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"HBoxModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/controls\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"HBoxView\",\"box_style\":\"\",\"children\":[\"IPY_MODEL_34a1b6a1cf6e4ac6b014f8443a70843c\",\"IPY_MODEL_9c4a7ec2428e40c7bd2c9ee9a5a2411d\",\"IPY_MODEL_29329fbfa4864643afedf46bf8b89b00\"],\"layout\":\"IPY_MODEL_5e8a7d9a86914b5da6617cd57b646df0\",\"tabbable\":null,\"tooltip\":null}},\"e89f152a93244c3ca651d7a4bed90617\":{\"model_module\":\"@jupyter-widgets/base\",\"model_module_version\":\"2.0.0\",\"model_name\":\"LayoutModel\",\"state\":{\"_model_module\":\"@jupyter-widgets/base\",\"_model_module_version\":\"2.0.0\",\"_model_name\":\"LayoutModel\",\"_view_count\":null,\"_view_module\":\"@jupyter-widgets/base\",\"_view_module_version\":\"2.0.0\",\"_view_name\":\"LayoutView\",\"align_content\":null,\"align_items\":null,\"align_self\":null,\"border_bottom\":null,\"border_left\":null,\"border_right\":null,\"border_top\":null,\"bottom\":null,\"display\":null,\"flex\":null,\"flex_flow\":null,\"grid_area\":null,\"grid_auto_columns\":null,\"grid_auto_flow\":null,\"grid_auto_rows\":null,\"grid_column\":null,\"grid_gap\":null,\"grid_row\":null,\"grid_template_areas\":null,\"grid_template_columns\":null,\"grid_template_rows\":null,\"height\":null,\"justify_content\":null,\"justify_items\":null,\"left\":null,\"margin\":null,\"max_height\":null,\"max_width\":null,\"min_height\":null,\"min_width\":null,\"object_fit\":null,\"object_position\":null,\"order\":null,\"overflow\":null,\"padding\":null,\"right\":null,\"top\":null,\"visibility\":null,\"width\":null}}},\"version_major\":2,\"version_minor\":0}\n</script>\n"
      ]
    }
  }
}
