<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-07-23">

<title>Uses and Abuses of Topological Data Analysis: A Pragmatic Guide – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Uses and Abuses of Topological Data Analysis: A Pragmatic Guide</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Machine Learning</div>
                <div class="quarto-category">Topology</div>
                <div class="quarto-category">TDA</div>
                <div class="quarto-category">Feature Engineering</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">July 23, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#clustering-asks-where-the-mass-is-topology-asks-what-the-mass-is-shaped-like" id="toc-clustering-asks-where-the-mass-is-topology-asks-what-the-mass-is-shaped-like" class="nav-link active" data-scroll-target="#clustering-asks-where-the-mass-is-topology-asks-what-the-mass-is-shaped-like">Clustering asks where the mass is; topology asks what the mass is shaped like</a></li>
  <li><a href="#deciding-what-close-means-turns-a-point-cloud-into-an-object-with-parts" id="toc-deciding-what-close-means-turns-a-point-cloud-into-an-object-with-parts" class="nav-link" data-scroll-target="#deciding-what-close-means-turns-a-point-cloud-into-an-object-with-parts">Deciding what “close” means turns a point cloud into an object with parts</a>
  <ul class="collapse">
  <li><a href="#three-points-are-enough-to-watch-a-hole-open-and-close" id="toc-three-points-are-enough-to-watch-a-hole-open-and-close" class="nav-link" data-scroll-target="#three-points-are-enough-to-watch-a-hole-open-and-close">Three points are enough to watch a hole open and close</a></li>
  <li><a href="#the-hole-that-never-was-does-not-appear-in-the-output" id="toc-the-hole-that-never-was-does-not-appear-in-the-output" class="nav-link" data-scroll-target="#the-hole-that-never-was-does-not-appear-in-the-output">The hole that never was does not appear in the output</a></li>
  <li><a href="#eighty-points-on-a-ring-hold-their-hole-open-for-most-of-the-sweep" id="toc-eighty-points-on-a-ring-hold-their-hole-open-for-most-of-the-sweep" class="nav-link" data-scroll-target="#eighty-points-on-a-ring-hold-their-hole-open-for-most-of-the-sweep">Eighty points on a ring hold their hole open for most of the sweep</a></li>
  </ul></li>
  <li><a href="#published-tda-falls-into-four-patterns-and-only-one-of-them-is-a-reflex" id="toc-published-tda-falls-into-four-patterns-and-only-one-of-them-is-a-reflex" class="nav-link" data-scroll-target="#published-tda-falls-into-four-patterns-and-only-one-of-them-is-a-reflex">Published TDA falls into four patterns, and only one of them is a reflex</a>
  <ul class="collapse">
  <li><a href="#pattern-a-the-diagram-becomes-extra-columns-in-a-feature-matrix" id="toc-pattern-a-the-diagram-becomes-extra-columns-in-a-feature-matrix" class="nav-link" data-scroll-target="#pattern-a-the-diagram-becomes-extra-columns-in-a-feature-matrix">Pattern A: the diagram becomes extra columns in a feature matrix</a></li>
  <li><a href="#pattern-b-the-diagram-is-a-test-statistic-and-nothing-gets-trained" id="toc-pattern-b-the-diagram-is-a-test-statistic-and-nothing-gets-trained" class="nav-link" data-scroll-target="#pattern-b-the-diagram-is-a-test-statistic-and-nothing-gets-trained">Pattern B: the diagram is a test statistic, and nothing gets trained</a></li>
  <li><a href="#pattern-c-the-topological-object-itself-is-the-deliverable" id="toc-pattern-c-the-topological-object-itself-is-the-deliverable" class="nav-link" data-scroll-target="#pattern-c-the-topological-object-itself-is-the-deliverable">Pattern C: the topological object itself is the deliverable</a></li>
  <li><a href="#pattern-d-the-quantity-of-interest-is-the-distance-between-two-diagrams" id="toc-pattern-d-the-quantity-of-interest-is-the-distance-between-two-diagrams" class="nav-link" data-scroll-target="#pattern-d-the-quantity-of-interest-is-the-distance-between-two-diagrams">Pattern D: the quantity of interest is the distance between two diagrams</a></li>
  </ul></li>
  <li><a href="#three-of-the-patterns-run-on-flowers-everybody-already-knows" id="toc-three-of-the-patterns-run-on-flowers-everybody-already-knows" class="nav-link" data-scroll-target="#three-of-the-patterns-run-on-flowers-everybody-already-knows">Three of the patterns, run on flowers everybody already knows</a>
  <ul class="collapse">
  <li><a href="#global-h_0-sees-setosa-and-nothing-finer" id="toc-global-h_0-sees-setosa-and-nothing-finer" class="nav-link" data-scroll-target="#global-h_0-sees-setosa-and-nothing-finer">Global <span class="math inline">\(H_0\)</span> sees Setosa and nothing finer</a></li>
  <li><a href="#mapper-draws-the-transition-that-h_0-could-only-call-one-clump" id="toc-mapper-draws-the-transition-that-h_0-could-only-call-one-clump" class="nav-link" data-scroll-target="#mapper-draws-the-transition-that-h_0-could-only-call-one-clump">Mapper draws the transition that <span class="math inline">\(H_0\)</span> could only call one clump</a></li>
  <li><a href="#local-persistence-turns-each-flowers-neighborhood-into-six-numbers" id="toc-local-persistence-turns-each-flowers-neighborhood-into-six-numbers" class="nav-link" data-scroll-target="#local-persistence-turns-each-flowers-neighborhood-into-six-numbers">Local persistence turns each flower’s neighborhood into six numbers</a></li>
  </ul></li>
  <li><a href="#persistence-is-a-hypothesis-about-your-data-not-a-free-block-of-columns" id="toc-persistence-is-a-hypothesis-about-your-data-not-a-free-block-of-columns" class="nav-link" data-scroll-target="#persistence-is-a-hypothesis-about-your-data-not-a-free-block-of-columns">Persistence is a hypothesis about your data, not a free block of columns</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/uses-and-abuses-of-tda/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Uses and Abuses of Topological Data Analysis: A Pragmatic Guide</figcaption>
</figure>
</div>
<p>Run k-means on a scatter plot and it hands you back cluster centres. Run a kernel density estimate and it hands you back a landscape of peaks. Both are answering the same question — where does the data pile up? — and for most datasets that is the right question to ask.</p>
<p>Now picture a dartboard with the bullseye rubbed out: points scattered evenly around a ring, nothing in the middle. Every stretch of that ring has the same local density as every other stretch, so the density tools report one long featureless plateau. What they never report is the thing you saw the instant you looked at the picture. The middle is empty. The ring has a hole in it, and a hole is not a density fact.</p>
<p>Topological data analysis is the machinery for reporting holes. It is worth learning partly because it finds structure that nothing else will, and partly because it will run happily on data that has no holes at all — which is where most of the trouble starts.</p>
<section id="clustering-asks-where-the-mass-is-topology-asks-what-the-mass-is-shaped-like" class="level2">
<h2 class="anchored" data-anchor-id="clustering-asks-where-the-mass-is-topology-asks-what-the-mass-is-shaped-like">Clustering asks where the mass is; topology asks what the mass is shaped like</h2>
<p>Nearly every tool in the standard kit is a <em>density</em> tool underneath. K-means asks where points pile up. Kernel density estimation smooths those piles into a landscape. A Gaussian mixture model fits blobs of probability mass. Even a random forest, when it partitions feature space, is chasing regions where the labels concentrate. The implicit question is always the same: <strong>where is the data dense?</strong></p>
<p>Topological Data Analysis (TDA) asks a stubbornly different question: <strong>what is the data’s shape?</strong> Not where the mass concentrates, but how the point cloud is <em>connected</em> — does it have gaps, loops, tunnels, voids? A filled disk and an annulus (a ring with a hole punched out of the middle) can have the same average local density everywhere and still be nothing alike. One has a loop; the other does not. Density is blind to that loop. Topology sees it immediately.</p>
<p>That loop matters more often than you’d guess. Periodic behavior in a dynamical system traces a loop in phase space. A cyclic chemical reaction, a recurrent neural trajectory, a seasonal market regime, the coordinated firing of a population of neurons — these leave <em>holes</em> in their point clouds, and no clustering algorithm is built to report a hole. TDA’s central promise is to detect and quantify that connectivity at every scale at once, without you having to commit to a single distance up front.</p>
<p>Two things have to happen before that promise is worth acting on. The machinery has to stop looking like magic, which takes an example small enough to check by hand. And then the harder question: of the ways TDA actually gets used in published research, which ones earn their cost, and which one is a reflex.</p>
</section>
<section id="deciding-what-close-means-turns-a-point-cloud-into-an-object-with-parts" class="level2">
<h2 class="anchored" data-anchor-id="deciding-what-close-means-turns-a-point-cloud-into-an-object-with-parts">Deciding what “close” means turns a point cloud into an object with parts</h2>
<p>A bare point cloud has no shape. It is a finite set of coordinates, and between any two of them there is nothing at all. Shape only appears once you make a decision the data cannot make for you: how near two points have to be before you are willing to call them joined.</p>
<p>Fix a distance <span class="math inline">\(\varepsilon\)</span> and apply that decision uniformly. Two points within <span class="math inline">\(\varepsilon\)</span> of each other get joined by a segment. Three points that are <em>all</em> mutually within <span class="math inline">\(\varepsilon\)</span> get more than three segments — they get the patch of surface they enclose, filled in solid. Four such points get the solid lump they enclose. The rule never changes with size: a set of points becomes one filled piece exactly when every pair inside it is within <span class="math inline">\(\varepsilon\)</span>.</p>
<p>Those filled pieces get a name each, indexed by dimension. A lone point is a <strong>0-simplex</strong>, a joined pair a <strong>1-simplex</strong> (an edge), a filled triangle a <strong>2-simplex</strong>, a solid tetrahedron a <strong>3-simplex</strong>. The whole collection you hold at one value of <span class="math inline">\(\varepsilon\)</span> is a <strong>simplicial complex</strong>, and this particular recipe for building one — fill every pairwise-close set — is the <strong>Vietoris–Rips complex</strong>.</p>
<p>If hypergraphs are familiar, there is a shorter way to say all of that. An ordinary graph has only edges, which join <em>pairs</em> of vertices; a hypergraph is more permissive, letting a single <strong>hyperedge</strong> join any subset of vertices at all. Every subset of your data points — the entire power set — is a candidate hyperedge, and <span class="math inline">\(\varepsilon\)</span> is the rule that decides which candidates get in:</p>
<blockquote class="blockquote">
<p>A subset of points becomes a hyperedge (a <em>simplex</em>) exactly when <strong>every pair</strong> of points inside it lies within distance <span class="math inline">\(\varepsilon\)</span> of each other.</p>
</blockquote>
<p>One property separates the result from a generic hypergraph. If a filled triangle is present then its three edges and three vertices are present too, automatically, because every subset of a pairwise-close set is itself pairwise close. A collection closed under “every face of a simplex is also present” is what earns the name simplicial complex, and it is why a triangle can be said to <em>fill</em> the cycle of its own edges: the cycle is guaranteed to be in there with it.</p>
<p>Nothing obliges you to pick one <span class="math inline">\(\varepsilon\)</span> and live with it. Start it at zero, where no two distinct points are within range and only the singletons qualify, then turn it up. Pairs fall into range and edges appear; mutually close triples snap shut into filled triangles; and so on up the power set. That ordered sequence of complexes — nested, since nothing ever leaves — is a <strong>filtration</strong>, and it is what TDA actually studies. Not the shape at some scale you had to guess, but the whole sweep of scales at once.</p>
<section id="three-points-are-enough-to-watch-a-hole-open-and-close" class="level3">
<h3 class="anchored" data-anchor-id="three-points-are-enough-to-watch-a-hole-open-and-close">Three points are enough to watch a hole open and close</h3>
<p>Abstractions dissolve fast against a concrete example, so take the smallest cloud that still does something interesting: three points, <span class="math inline">\(A\)</span>, <span class="math inline">\(B\)</span>, and <span class="math inline">\(C\)</span>, placed by hand as a loose triangle rather than an equilateral one, so that its three side lengths are distinct and the sweep has three separate events to show. Rather than assert the distances, let the code place the points and report them.</p>
<div id="tbl-toy-distances" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-execution_count="1">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-toy-distances-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1
</figcaption>
<div aria-describedby="tbl-toy-distances-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.spatial.distance <span class="im">import</span> pdist, squareform</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Three points forming a loose triangle: A, B, C</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>pts <span class="op">=</span> np.array([[<span class="fl">0.0</span>, <span class="fl">0.0</span>],    <span class="co"># A</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>                [<span class="fl">1.0</span>, <span class="fl">0.0</span>],    <span class="co"># B</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>                [<span class="fl">0.6</span>, <span class="fl">1.3</span>]])   <span class="co"># C</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>labels <span class="op">=</span> [<span class="st">"A"</span>, <span class="st">"B"</span>, <span class="st">"C"</span>]</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>D <span class="op">=</span> squareform(pdist(pts))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Pairwise distance matrix (rows/cols = A, B, C):"</span>)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.<span class="bu">round</span>(D, <span class="dv">3</span>))</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">d(A,B) = </span><span class="sc">{</span>D[<span class="dv">0</span>,<span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">   d(B,C) = </span><span class="sc">{</span>D[<span class="dv">1</span>,<span class="dv">2</span>]<span class="sc">:.3f}</span><span class="ss">   d(A,C) = </span><span class="sc">{</span>D[<span class="dv">0</span>,<span class="dv">2</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Pairwise distance matrix (rows/cols = A, B, C):
[[0.    1.    1.432]
 [1.    0.    1.36 ]
 [1.432 1.36  0.   ]]

d(A,B) = 1.000   d(B,C) = 1.360   d(A,C) = 1.432</code></pre>
</div>
</div>
</figure>
</div>
<p>So the three pairwise distances, sorted, are <span class="math inline">\(d(A,B) = 1.000\)</span>, then <span class="math inline">\(d(B,C) = 1.360\)</span>, then <span class="math inline">\(d(A,C) = 1.432\)</span>. Now run the filtration on them: sweep <span class="math inline">\(\varepsilon\)</span> up from <span class="math inline">\(0\)</span> and watch which subsets become simplices. With three points there are only three distances, so only three things can ever happen. The code below draws four frames of the sweep and colors each simplex the moment it is born.</p>
<div id="cell-fig-toy-filtration" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> itertools <span class="im">import</span> combinations</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>PURPLE, ORANGE <span class="op">=</span> <span class="st">"#4A3AA7"</span>, <span class="st">"#E07B39"</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>eps_frames <span class="op">=</span> [<span class="fl">0.0</span>, <span class="fl">1.0</span>, <span class="fl">1.36</span>, <span class="fl">1.432</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">4</span>))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> ax, eps <span class="kw">in</span> <span class="bu">zip</span>(axes, eps_frames):</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># radius-eps/2 disks: two disks touch exactly when centers are eps apart</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (x, y) <span class="kw">in</span> pts:</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>        ax.add_patch(plt.Circle((x, y), eps <span class="op">/</span> <span class="dv">2</span>, color<span class="op">=</span>PURPLE, alpha<span class="op">=</span><span class="fl">0.10</span>, zorder<span class="op">=</span><span class="dv">0</span>))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># filled 2-simplex: present when ALL three pairwise distances &lt;= eps</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">all</span>(D[i, j] <span class="op">&lt;=</span> eps <span class="cf">for</span> i, j <span class="kw">in</span> combinations(<span class="bu">range</span>(<span class="dv">3</span>), <span class="dv">2</span>)):</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>        ax.add_patch(plt.Polygon(pts, closed<span class="op">=</span><span class="va">True</span>, color<span class="op">=</span>ORANGE, alpha<span class="op">=</span><span class="fl">0.35</span>, zorder<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 1-simplices (edges): present when that pair's distance &lt;= eps</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i, j <span class="kw">in</span> combinations(<span class="bu">range</span>(<span class="dv">3</span>), <span class="dv">2</span>):</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> D[i, j] <span class="op">&lt;=</span> eps:</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>            ax.plot(<span class="op">*</span><span class="bu">zip</span>(pts[i], pts[j]), color<span class="op">=</span>PURPLE, lw<span class="op">=</span><span class="fl">2.5</span>, zorder<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 0-simplices (the points themselves)</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    ax.scatter(pts[:, <span class="dv">0</span>], pts[:, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">90</span>, color<span class="op">=</span><span class="st">"black"</span>, zorder<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (x, y), lab <span class="kw">in</span> <span class="bu">zip</span>(pts, labels):</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>        ax.annotate(lab, (x, y), textcoords<span class="op">=</span><span class="st">"offset points"</span>, xytext<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">8</span>), fontweight<span class="op">=</span><span class="st">"bold"</span>)</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="vs">fr"$\varepsilon = </span><span class="sc">{</span>eps<span class="sc">:g}</span><span class="vs">$"</span>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>    ax.set_aspect(<span class="st">"equal"</span>)<span class="op">;</span> ax.set_xlim(<span class="op">-</span><span class="fl">0.9</span>, <span class="fl">1.9</span>)<span class="op">;</span> ax.set_ylim(<span class="op">-</span><span class="fl">0.9</span>, <span class="fl">2.2</span>)</span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>    ax.set_xticks([])<span class="op">;</span> ax.set_yticks([])</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-toy-filtration" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-toy-filtration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-toy-filtration-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-toy-filtration-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: The Vietoris–Rips filtration on three points, at four thresholds. Faint circles have radius ε/2, so two points connect (an edge appears) exactly when their circles touch. Nodes are born at ε=0, the A–B edge at ε=1.000, the B–C edge at ε=1.360, and at ε=1.432 the last edge closes the loop and the triangle fills in the same instant.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Read the four frames left to right:</p>
<ul>
<li><strong><span class="math inline">\(\varepsilon = 0\)</span>.</strong> Nothing is within range of anything else — three isolated 0-simplices, the singletons <span class="math inline">\(\{A\}\)</span>, <span class="math inline">\(\{B\}\)</span>, <span class="math inline">\(\{C\}\)</span>. Three separate connected components.</li>
<li><strong><span class="math inline">\(\varepsilon = 1.000\)</span>.</strong> The threshold reaches <span class="math inline">\(d(A,B)\)</span>. The pair <span class="math inline">\(\{A,B\}\)</span> becomes a 1-simplex (an edge); <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> merge into one component while <span class="math inline">\(C\)</span> sits alone. Two components.</li>
<li><strong><span class="math inline">\(\varepsilon = 1.360\)</span>.</strong> The threshold reaches <span class="math inline">\(d(B,C)\)</span>. The edge <span class="math inline">\(\{B,C\}\)</span> appears, linking all three points into one component — but as a bent <em>path</em>, because the edge <span class="math inline">\(\{A,C\}\)</span> is still missing.</li>
<li><strong><span class="math inline">\(\varepsilon = 1.432\)</span>.</strong> The threshold reaches the longest distance <span class="math inline">\(d(A,C)\)</span>, closing the triangle. For an instant the three edges enclose an empty region — a 1-dimensional hole. But the Vietoris–Rips rule now also admits the full triple <span class="math inline">\(\{A,B,C\}\)</span> (all its pairs are within <span class="math inline">\(\varepsilon\)</span>), so the filled 2-simplex appears the <em>same instant</em> and plugs the hole immediately.</li>
</ul>
</section>
<section id="the-hole-that-never-was-does-not-appear-in-the-output" class="level3">
<h3 class="anchored" data-anchor-id="the-hole-that-never-was-does-not-appear-in-the-output">The hole that never was does not appear in the output</h3>
<p>That reading came off a picture, which is a habit worth checking against the arithmetic. Software will do the sweep exactly: <a href="https://ripser.scikit-tda.org/"><code>ripser</code></a> takes a point cloud, runs the whole filtration internally, and for every feature it finds reports the threshold at which the feature appeared and the threshold at which it vanished. Those two numbers are the feature’s <strong>birth</strong> and <strong>death</strong>. Here are the raw arrays for our three points.</p>
<div id="toy-persistence" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ripser <span class="im">import</span> ripser</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>dgms <span class="op">=</span> ripser(pts, maxdim<span class="op">=</span><span class="dv">1</span>)[<span class="st">"dgms"</span>]</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"H0 (connected components) — [birth, death]:"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dgms[<span class="dv">0</span>])</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">H1 (loops) — [birth, death]:"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(dgms[<span class="dv">1</span>] <span class="cf">if</span> <span class="bu">len</span>(dgms[<span class="dv">1</span>]) <span class="cf">else</span> <span class="st">"(empty — no loop is recorded)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>H0 (connected components) — [birth, death]:
[[0.       1.      ]
 [0.       1.360147]
 [0.            inf]]

H1 (loops) — [birth, death]:
(empty — no loop is recorded)</code></pre>
</div>
</div>
<p>Features come sorted by dimension, and the two labels are worth having plainly. <span class="math inline">\(H_0\)</span> collects the separate pieces of the complex — the connected components. <span class="math inline">\(H_1\)</span> collects the loops: cycles of edges that enclose a region nothing has filled in.</p>
<ul>
<li><strong><span class="math inline">\(H_0\)</span>.</strong> Three bars, all born at <span class="math inline">\(\varepsilon = 0\)</span>. One dies at <span class="math inline">\(\varepsilon = 1.000\)</span> (the <span class="math inline">\(A\)</span>–<span class="math inline">\(B\)</span> merge), one at <span class="math inline">\(\varepsilon = 1.360\)</span> (when <span class="math inline">\(C\)</span> joins via the <span class="math inline">\(B\)</span>–<span class="math inline">\(C\)</span> edge), and one has death <span class="math inline">\(= \infty\)</span>: once everything is connected, that last component never dies.</li>
<li><strong><span class="math inline">\(H_1\)</span>.</strong> The array is <strong>empty</strong>. The loop that flickered into existence at <span class="math inline">\(\varepsilon = 1.432\)</span> was filled by the triangle at the very same threshold, so its death minus its birth is exactly zero, and <code>ripser</code> does not record it at all.</li>
</ul>
<p>That empty <span class="math inline">\(H_1\)</span> is the whole discipline in one array: <strong>a hole only counts if it persists.</strong> A feature born and killed at the same scale carries no signal. The quantity that matters is always the <em>gap</em> between birth and death — features born early and dying late are real structure, features with birth <span class="math inline">\(\approx\)</span> death are noise. Plot each feature as a point at coordinates (birth, death) and real features sit high above the diagonal while noise clings to it; that scatter is a <strong>persistence diagram</strong>. Plot each instead as a horizontal bar running from birth to death and long bars are the signal; that is a <strong>barcode</strong>. Same information, two pictures.</p>
<p>Three points were never going to hold a hole open. For a loop that survives, the points have to be arranged so the middle stays empty while the rim knits together.</p>
</section>
<section id="eighty-points-on-a-ring-hold-their-hole-open-for-most-of-the-sweep" class="level3">
<h3 class="anchored" data-anchor-id="eighty-points-on-a-ring-hold-their-hole-open-for-most-of-the-sweep">Eighty points on a ring hold their hole open for most of the sweep</h3>
<p>A circle is the smallest arrangement where the gap between birth and death has room to be large, so that is what we sample. The data here is synthetic: 80 angles drawn uniformly around the unit circle, each point then pushed off the ring by Gaussian noise with standard deviation 0.08, from a seeded generator so the figure is the same on every render. It stands in for any measured process that cycles — a rotating machine part sampled at random phases, a periodic signal embedded in a plane — where the instrument adds error but the cycle is real.</p>
<p>Simulating beats a real dataset here because the answer is known in advance. There is exactly one loop, I put it there, and anything else <code>ripser</code> reports is noise I can name as such.</p>
<div id="cell-fig-circle-persistence" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ripser <span class="im">import</span> ripser</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> persim <span class="im">import</span> plot_diagrams</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co"># House palette (CVD-validated purple / orange two-series).</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>PURPLE, ORANGE <span class="op">=</span> <span class="st">"#4A3AA7"</span>, <span class="st">"#E07B39"</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Synthetic data: 80 points on the unit circle + Gaussian noise ---</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">7</span>)</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>n <span class="op">=</span> <span class="dv">80</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>theta <span class="op">=</span> rng.uniform(<span class="dv">0</span>, <span class="dv">2</span> <span class="op">*</span> np.pi, n)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>circle <span class="op">=</span> np.column_stack([np.cos(theta), np.sin(theta)])</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>circle <span class="op">+=</span> rng.normal(scale<span class="op">=</span><span class="fl">0.08</span>, size<span class="op">=</span>circle.shape)</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="co"># --- Persistent homology up to H1 (loops) ---</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>result <span class="op">=</span> ripser(circle, maxdim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>dgms <span class="op">=</span> result[<span class="st">"dgms"</span>]          <span class="co"># dgms[0] = H0 components, dgms[1] = H1 loops</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="fl">4.2</span>))</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel 1: the point cloud</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].scatter(circle[:, <span class="dv">0</span>], circle[:, <span class="dv">1</span>], s<span class="op">=</span><span class="dv">28</span>, color<span class="op">=</span>PURPLE, edgecolor<span class="op">=</span><span class="st">"white"</span>, linewidth<span class="op">=</span><span class="fl">0.5</span>)</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_title(<span class="st">"Noisy circle (point cloud)"</span>)</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_aspect(<span class="st">"equal"</span>)</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">0</span>].set_xlabel(<span class="st">"x"</span>)<span class="op">;</span> axes[<span class="dv">0</span>].set_ylabel(<span class="st">"y"</span>)</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel 2: barcode (drawn by hand so we control the two-series palette)</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> {<span class="dv">0</span>: PURPLE, <span class="dv">1</span>: ORANGE}</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>labels_done <span class="op">=</span> <span class="bu">set</span>()</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> dim <span class="kw">in</span> (<span class="dv">0</span>, <span class="dv">1</span>):</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>    bars <span class="op">=</span> dgms[dim]</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>    finite <span class="op">=</span> bars[np.isfinite(bars[:, <span class="dv">1</span>])]</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> birth, death <span class="kw">in</span> <span class="bu">sorted</span>(finite, key<span class="op">=</span><span class="kw">lambda</span> b: b[<span class="dv">0</span>]):</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>        lbl <span class="op">=</span> <span class="ss">f"$H_</span><span class="sc">{</span>dim<span class="sc">}</span><span class="ss">$"</span> <span class="cf">if</span> dim <span class="kw">not</span> <span class="kw">in</span> labels_done <span class="cf">else</span> <span class="va">None</span></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>        ax.plot([birth, death], [y, y], color<span class="op">=</span>colors[dim], lw<span class="op">=</span><span class="fl">2.5</span>, label<span class="op">=</span>lbl, solid_capstyle<span class="op">=</span><span class="st">"round"</span>)</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>        labels_done.add(dim)</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>        y <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Barcode"</span>)</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="vs">r"filtration scale $\varepsilon$"</span>)</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>ax.set_yticks([])</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"lower right"</span>, frameon<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a><span class="co"># Panel 3: persistence diagram (persim handles H0/H1 coloring + diagonal)</span></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a>plot_diagrams(dgms, ax<span class="op">=</span>axes[<span class="dv">2</span>], show<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a>axes[<span class="dv">2</span>].set_title(<span class="st">"Persistence diagram"</span>)</span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-circle-persistence" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-circle-persistence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-circle-persistence-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-circle-persistence-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: A noisy circle (left) and the persistent homology of its Vietoris–Rips filtration, shown as a barcode (center) and a persistence diagram (right). The single long H1 bar / high off-diagonal point is the loop.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The barcode makes the story visual. The purple <span class="math inline">\(H_0\)</span> bars all start at <span class="math inline">\(\varepsilon = 0\)</span> (every point is its own component at the outset) and die off quickly as the noisy rim knits together — leaving one immortal component. The single long orange <span class="math inline">\(H_1\)</span> bar is the loop: born once the rim connects into a ring, and not dying until <span class="math inline">\(\varepsilon\)</span> grows large enough to fill the whole disk in. In the persistence diagram, that same loop is the lone orange point sitting high above the diagonal, unmistakably separated from the noise clinging to it. <strong>That one persistent point is the entire topological signal of “this data is a circle.”</strong></p>
</section>
</section>
<section id="published-tda-falls-into-four-patterns-and-only-one-of-them-is-a-reflex" class="level2">
<h2 class="anchored" data-anchor-id="published-tda-falls-into-four-patterns-and-only-one-of-them-is-a-reflex">Published TDA falls into four patterns, and only one of them is a reflex</h2>
<p>One point sitting high above the diagonal is a satisfying answer to <em>is this data a circle?</em> — but almost nobody’s real question is that. The diagram is where the work starts, not where it ends, and what happens to it next is where the choices live. Read enough applied papers that use persistent homology and four patterns account for nearly all of them. They differ in what the diagram is <em>for</em>: fuel for a learner, a test statistic, a picture for a domain expert, or one end of a comparison.</p>
<p>Knowing which of the four you are in is most of the difference between using TDA and cargo-culting it — copying the visible moves of a method that worked somewhere else, without the conditions that made it work.</p>
<section id="pattern-a-the-diagram-becomes-extra-columns-in-a-feature-matrix" class="level3">
<h3 class="anchored" data-anchor-id="pattern-a-the-diagram-becomes-extra-columns-in-a-feature-matrix">Pattern A: the diagram becomes extra columns in a feature matrix</h3>
<p>This is the workhorse, and the one most ML researchers meet first. Topology is treated as a <strong>feature expander</strong>: something that turns a shape into numbers a model already knows how to read.</p>
<p>The obstacle is that a persistence diagram is an unordered set of (birth, death) points, and its size changes from sample to sample — so it is not a fixed-length vector, and no standard model will accept it. Vectorizing means squashing that set into a fixed number of slots: a persistence image, a persistence landscape, a vector of Betti-curve samples, or plain summary statistics like total persistence and longest lifetime. That vector is concatenated with your other features and handed to an SVM, a random forest, gradient boosting, or a neural net. Topology becomes just another block of columns.</p>
<p>The appeal is that persistence features can encode structure that per-sample features miss entirely — long-range connectivity, cyclic patterns, multi-scale organization. When the underlying phenomenon genuinely has such structure, this can lift accuracy for free. Representative work:</p>
<ul>
<li><strong>Mixed numeric-and-categorical classification.</strong> Zhou &amp; Wang build topological features from heterogeneous tabular data and feed them to downstream classifiers, with heart-disease prediction as a benchmark — a case where the interactions between categorical and continuous variables have a geometric fingerprint that persistence captures.</li>
<li><strong>Link prediction in graphs.</strong> Bhatia et al.&nbsp;extract persistence-based descriptors of local neighborhood structure and use them as features to predict which edges a graph is missing.</li>
<li><strong>Materials structure–property prediction.</strong> Minamitani et al.&nbsp;derive a persistent-homology descriptor of atomic arrangements in amorphous materials and use it to drive machine-learning potentials — the ring and void statistics of a disordered solid are exactly the kind of thing topology summarizes well.</li>
<li><strong>Financial crash early-warning.</strong> Ismail et al.&nbsp;and, earlier, Gidea &amp; Katz compute persistence on sliding windows of multivariate market time series (embedded via time-delay coordinates) and show that topological summaries spike ahead of major crashes — including Bitcoin — feeding the signal into a detector.</li>
</ul>
<p>If you only remember one pattern, remember this one — and remember that it is also the one that gets reached for without a reason, which is the argument this post ends on. The other three are harder to apply by reflex, starting with the one that trains nothing at all.</p>
</section>
<section id="pattern-b-the-diagram-is-a-test-statistic-and-nothing-gets-trained" class="level3">
<h3 class="anchored" data-anchor-id="pattern-b-the-diagram-is-a-test-statistic-and-nothing-gets-trained">Pattern B: the diagram is a test statistic, and nothing gets trained</h3>
<p>Here there is <strong>no downstream learner</strong>. The persistence diagram — or a single number derived from it, such as the count of holes at a fixed scale, or persistence summed over all features — is used directly as a <em>test statistic</em>: a number you compute from data whose behavior under “nothing interesting is going on” you already know.</p>
<p>So you compute it on the real data, work out its distribution under a theoretical or simulated null model, and ask whether the observed topology is surprising next to what pure noise would produce. This is classical statistical inference wearing a topology costume. The topology is just an unusually shape-aware summary statistic.</p>
<ul>
<li><strong>Cosmology.</strong> Pranav et al.&nbsp;describe the Cosmic Microwave Background — the faint leftover radiation from the early universe — and the large-scale structure of matter in terms of persistent Betti numbers, counts of components and holes and voids at each scale. Wilding et al.&nbsp;analyze cosmic voids the same way, comparing the observed topology of the cosmic web against simulations run under <span class="math inline">\(\Lambda\)</span>CDM, the standard model of cosmology, and against Gaussian random fields as a null.</li>
<li><strong>Text as point clouds.</strong> Wright &amp; Zheng turn Simple English Wikipedia articles into point clouds, placing each word at its embedding coordinates, and compare their persistent homology against random-noise baselines — asking whether real prose is topologically distinguishable from noise of matched size and dimension.</li>
</ul>
<p>The tell for Pattern B is a null model and a p-value-shaped conclusion, with no trained predictor anywhere. The next pattern drops the null model too, and hands the topology straight to a person.</p>
</section>
<section id="pattern-c-the-topological-object-itself-is-the-deliverable" class="level3">
<h3 class="anchored" data-anchor-id="pattern-c-the-topological-object-itself-is-the-deliverable">Pattern C: the topological object itself is the deliverable</h3>
<p>Here there is <strong>no vectorization and no test</strong>. The shape is the output, and a human reads it.</p>
<p>The dominant tool is <strong>Mapper</strong>, which compresses a dataset into a small graph you can actually look at. Pick a function that scores every data point — a projection onto one axis, a density, anything that gives a number. Slice the range of that score into overlapping bins, cluster the points inside each bin separately, draw one node per cluster, and join two nodes whenever they share a point. Overlapping bins are what make the joins possible, and the result is a network that keeps the data’s connectivity while throwing away its coordinates. The scoring function has a name in this literature: the <strong>lens</strong>, or filter.</p>
<ul>
<li><strong>Cancer subtyping.</strong> Nicolau, Levine &amp; Carlsson used topology-based analysis — the Progression Analysis of Disease methodology, the line of work that later became the company Ayasdi — to identify a previously unrecognized subgroup of breast cancers with distinct, excellent survival. The subgroup fell out of the shape of the gene-expression data, not from any prior labeling.</li>
<li><strong>Single-cell trajectories.</strong> Rizvi et al.&nbsp;apply topological analysis to single-cell RNA-seq data to recover cell-fate differentiation trajectories, reconstructing the branching path cells take through gene-expression space during development.</li>
<li><strong>Molecular structure.</strong> Xia &amp; Wei use persistent homology to characterize protein structure, flexibility, and folding, and Stolz et al.&nbsp;analyze knotting and supercoiling in DNA — the loops and tangles of a molecule <em>are</em> topological features, so topology is the natural descriptive language.</li>
</ul>
<p>Pattern C is exploratory and interpretive. Success is a scientist learning something, not a held-out metric. What it cannot do is tell you whether two datasets differ, which is the last pattern’s whole job.</p>
</section>
<section id="pattern-d-the-quantity-of-interest-is-the-distance-between-two-diagrams" class="level3">
<h3 class="anchored" data-anchor-id="pattern-d-the-quantity-of-interest-is-the-distance-between-two-diagrams">Pattern D: the quantity of interest is the distance between two diagrams</h3>
<p>The final pattern compares <em>whole objects</em> instead of classifying points inside one object. To do that you need a way to say how far apart two persistence diagrams are, and there is a natural one: pair up the points of one diagram with the points of the other, and measure how far you had to move them. Points with no partner get matched to the diagonal instead, which is the right punishment because a point on the diagonal is a feature with zero lifetime — a feature that may as well not exist.</p>
<p>Take the largest single move and you have the <strong>bottleneck distance</strong>; add the moves up and you have the <strong>Wasserstein distance</strong>. Either gives a shape-aware answer to “how different are these two things?”, which is what change detection and before-and-after comparison need.</p>
<ul>
<li><strong>Time-varying graphs.</strong> Hajij et al.&nbsp;track a graph as it evolves, compute a persistence diagram at each timestep, and use the distance between consecutive diagrams to flag structural change — a spike in diagram distance marks a topological event that node- or edge-level metrics might smear over.</li>
</ul>
<p>The signature of Pattern D is a <em>distance between diagrams</em> as the quantity of interest, rather than a feature vector or a test statistic. Four patterns, described; the question is what they look like when you run three of them on the same data and watch where the payoff runs out.</p>
</section>
</section>
<section id="three-of-the-patterns-run-on-flowers-everybody-already-knows" class="level2">
<h2 class="anchored" data-anchor-id="three-of-the-patterns-run-on-flowers-everybody-already-knows">Three of the patterns, run on flowers everybody already knows</h2>
<p>Patterns are easier to trust once you have watched them run end to end on data whose answer you already have. That is the point of using <a href="https://archive.ics.uci.edu/dataset/53/iris">Iris</a>: 150 iris flowers, four measurements each — sepal length and width, petal length and width — across three species, Setosa, Versicolor and Virginica.</p>
<p>The measurements are Edgar Anderson’s. He was a botanist, and he was recording flower dimensions as part of a study of variation within and between iris species — the question of where one species stops and the next begins, decided from the plant rather than from a taxonomist’s judgement. R. A. Fisher took the table in 1936 and used it to introduce linear discriminant analysis, and it has been a teaching benchmark ever since. Its geometry is famous: Setosa sits well away from the other two, and Versicolor and Virginica overlap.</p>
<p>What is being asked of it here is not “which species is this flower”. Nobody needs another Iris classifier, and a wrong answer costs a botanist nothing — that is exactly why it is safe to run diagnostics on. The question is whether the <em>shape</em> of the data reproduces what we already know about it, and how much a topological description adds once the four raw measurements are already on the table. Iris is a good test of that precisely because it is a case where topology should be redundant: four measurements that already separate the species is the regime where a shape-based method has the least room to earn its cost. If persistence pays here, it pays cheaply, and the size of “cheaply” is the number worth having.</p>
<p>Three of the four patterns fit on it: <strong>global</strong> persistent homology (the whole cloud’s shape, Pattern B/C territory), <strong>Mapper</strong> (a skeleton for the eye, Pattern C), and <strong>local</strong> persistent homology (per-flower features for a classifier, Pattern A). Throughout, the numbers and figures below are computed at render time — nothing is asserted that the code does not produce.</p>
<div id="iris-setup" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.datasets <span class="im">import</span> load_iris</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>iris <span class="op">=</span> load_iris()</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> StandardScaler().fit_transform(iris.data)   <span class="co"># 150 x 4, standardized</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> iris.target</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>species <span class="op">=</span> iris.target_names</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"X shape:"</span>, X.shape, <span class="st">"| species:"</span>, <span class="bu">list</span>(species))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>X shape: (150, 4) | species: [np.str_('setosa'), np.str_('versicolor'), np.str_('virginica')]</code></pre>
</div>
</div>
<section id="global-h_0-sees-setosa-and-nothing-finer" class="level3">
<h3 class="anchored" data-anchor-id="global-h_0-sees-setosa-and-nothing-finer">Global <span class="math inline">\(H_0\)</span> sees Setosa and nothing finer</h3>
<p>Start with the crudest question the filtration can answer: run the same <span class="math inline">\(\varepsilon\)</span>-sweep over all 150 flowers at once and ask how this four-dimensional cloud connects up as the threshold grows. Only <span class="math inline">\(H_0\)</span> is needed — the separate pieces, the clumps.</p>
<p>The useful summary is a single count that changes as the sweep runs: how many separate pieces are still alive at threshold <span class="math inline">\(\varepsilon\)</span>. Every point starts as its own piece, and the count falls as pieces merge. Plotted against <span class="math inline">\(\varepsilon\)</span> it is a staircase, and a long flat step means a grouping that survives across a wide band of scales rather than one that appears at a threshold you happened to pick. That count has a name — the <strong>Betti number</strong> <span class="math inline">\(\beta_0(\varepsilon)\)</span>, the zero-dimensional one because it counts components; <span class="math inline">\(\beta_1\)</span> would count loops, <span class="math inline">\(\beta_2\)</span> voids.</p>
<div id="cell-fig-iris-global" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> ripser <span class="im">import</span> ripser</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>PURPLE, ORANGE, TEAL <span class="op">=</span> <span class="st">"#4A3AA7"</span>, <span class="st">"#E07B39"</span>, <span class="st">"#2A9D8F"</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>h0 <span class="op">=</span> ripser(X, maxdim<span class="op">=</span><span class="dv">1</span>)[<span class="st">"dgms"</span>][<span class="dv">0</span>]</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>finite <span class="op">=</span> np.sort(h0[np.isfinite(h0[:, <span class="dv">1</span>])][:, <span class="dv">1</span>])   <span class="co"># finite death times, ascending</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="fl">4.6</span>))</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Left: H0 barcode (all births at 0). Draw the finite bars + one infinite bar.</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">0</span>]</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k, death <span class="kw">in</span> <span class="bu">enumerate</span>(finite):</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    ax.plot([<span class="dv">0</span>, death], [k, k], color<span class="op">=</span>PURPLE, lw<span class="op">=</span><span class="fl">0.8</span>, solid_capstyle<span class="op">=</span><span class="st">"butt"</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>ax.plot([<span class="dv">0</span>, finite.<span class="bu">max</span>() <span class="op">*</span> <span class="fl">1.15</span>], [<span class="bu">len</span>(finite), <span class="bu">len</span>(finite)], color<span class="op">=</span>ORANGE, lw<span class="op">=</span><span class="fl">1.6</span>,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>        label<span class="op">=</span><span class="st">"immortal component (death = ∞)"</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="vs">r"$H_0$ barcode (global Iris)"</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="vs">r"filtration scale $\varepsilon$"</span>)<span class="op">;</span> ax.set_ylabel(<span class="st">"component (bar) index"</span>)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>ax.legend(loc<span class="op">=</span><span class="st">"lower right"</span>, frameon<span class="op">=</span><span class="va">False</span>, fontsize<span class="op">=</span><span class="dv">9</span>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Right: Betti-0 curve. β0(ε) = (#H0 classes) - (#deaths ≤ ε);</span></span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="co"># #H0 classes = finite bars + the one immortal component (Iris has a duplicate</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="co"># row, so ripser reports 149 classes for 150 points, not 150).</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>n_classes <span class="op">=</span> <span class="bu">len</span>(finite) <span class="op">+</span> <span class="dv">1</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>grid <span class="op">=</span> np.linspace(<span class="dv">0</span>, finite.<span class="bu">max</span>() <span class="op">*</span> <span class="fl">1.05</span>, <span class="dv">400</span>)</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>beta0 <span class="op">=</span> n_classes <span class="op">-</span> np.searchsorted(finite, grid, side<span class="op">=</span><span class="st">"right"</span>)</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> axes[<span class="dv">1</span>]</span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>ax.step(grid, beta0, where<span class="op">=</span><span class="st">"post"</span>, color<span class="op">=</span>TEAL, lw<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>ax.axhline(<span class="dv">3</span>, color<span class="op">=</span><span class="st">"gray"</span>, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="dv">1</span>)<span class="op">;</span> ax.axhline(<span class="dv">2</span>, color<span class="op">=</span><span class="st">"gray"</span>, ls<span class="op">=</span><span class="st">":"</span>, lw<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>ax.set_ylim(<span class="dv">0</span>, <span class="dv">12</span>)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="vs">r"$\beta_0(\varepsilon)$: components alive at scale $\varepsilon$"</span>)</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>ax.set_xlabel(<span class="vs">r"filtration scale $\varepsilon$"</span>)<span class="op">;</span> ax.set_ylabel(<span class="vs">r"$\beta_0$"</span>)</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-iris-global" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-iris-global-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-iris-global-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iris-global-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Global H0 of standardized Iris. Left: the H0 barcode — 149 bars born at ε=0, all but one dying as clumps merge; the two longest finite bars are the last merges. Right: β0(ε), the number of components alive at each scale. The wide plateau at β0=3, then β0=2, is the persistent cluster structure.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The barcode and the <span class="math inline">\(\beta_0\)</span> curve tell one story. As <span class="math inline">\(\varepsilon\)</span> grows the 148 finite components merge away fast, and then the count <em>lingers</em> — <span class="math inline">\(\beta_0 = 3\)</span> across a broad band, then <span class="math inline">\(\beta_0 = 2\)</span>, before collapsing to a single blob. Those plateaus are the persistent cluster structure.</p>
<p>They do not say which flowers are in which clump, though, and that is the part worth knowing. Merging points into whichever piece is nearest, in the order the distances allow, is exactly what single-linkage hierarchical clustering does — the <span class="math inline">\(H_0\)</span> filtration and the single-linkage tree are the same computation with different bookkeeping. So we can cut that tree at 2 and at 3 components and count species inside each.</p>
<div id="iris-linkage" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.cluster.hierarchy <span class="im">import</span> linkage, fcluster</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.spatial.distance <span class="im">import</span> pdist</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>Z <span class="op">=</span> linkage(pdist(X), method<span class="op">=</span><span class="st">"single"</span>)   <span class="co"># single-linkage == H0 merge order</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> k <span class="kw">in</span> (<span class="dv">2</span>, <span class="dv">3</span>):</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    lab <span class="op">=</span> fcluster(Z, t<span class="op">=</span>k, criterion<span class="op">=</span><span class="st">"maxclust"</span>)</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    comp <span class="op">=</span> {c: np.bincount(y[lab <span class="op">==</span> c], minlength<span class="op">=</span><span class="dv">3</span>) <span class="cf">for</span> c <span class="kw">in</span> np.unique(lab)}</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>k<span class="sc">}</span><span class="ss"> components:"</span>)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> c, b <span class="kw">in</span> comp.items():</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"   cluster </span><span class="sc">{</span>c<span class="sc">}</span><span class="ss">: setosa=</span><span class="sc">{</span>b[<span class="dv">0</span>]<span class="sc">:2d}</span><span class="ss">  versicolor=</span><span class="sc">{</span>b[<span class="dv">1</span>]<span class="sc">:2d}</span><span class="ss">  virginica=</span><span class="sc">{</span>b[<span class="dv">2</span>]<span class="sc">:2d}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2 components:
   cluster 1: setosa= 0  versicolor=50  virginica=50
   cluster 2: setosa=50  versicolor= 0  virginica= 0
3 components:
   cluster 1: setosa= 0  versicolor=50  virginica=50
   cluster 2: setosa=49  versicolor= 0  virginica= 0
   cluster 3: setosa= 1  versicolor= 0  virginica= 0</code></pre>
</div>
</div>
<p>The 2-component cut is clean: one cluster is all 50 Setosa, the other is all 100 Versicolor and Virginica together. The single longest finite bar in the barcode <em>is</em> Setosa refusing to merge until the very end.</p>
<p>The 3-component cut is where the caveat lives. Splitting into three does not separate Versicolor from Virginica. It peels off one stray Setosa flower and leaves the 100 overlapping ones fused as a single clump. That is single-linkage chaining: because a piece grows by its nearest point, one outlier sitting slightly apart survives as its own component long after the real structure has settled, and the third “cluster” you get is that outlier rather than a group. Global <span class="math inline">\(H_0\)</span> has said the true thing it is able to see — Setosa is topologically distinct, the other two are not separable by connectivity alone — and it has nothing further. Seeing inside that fused clump needs a tool that does not insist on cutting it.</p>
</section>
<section id="mapper-draws-the-transition-that-h_0-could-only-call-one-clump" class="level3">
<h3 class="anchored" data-anchor-id="mapper-draws-the-transition-that-h_0-could-only-call-one-clump">Mapper draws the transition that <span class="math inline">\(H_0\)</span> could only call one clump</h3>
<p>Mapper is that tool, and it is Pattern C: the graph it produces is the answer, not an input to something else. It does not have to declare a number of clusters, because it never partitions the data — it slices, clusters locally, and then reconnects, so two groups that shade into each other come out as one connected shape rather than as two boxes with a boundary drawn between them.</p>
<p>Here the lens is the first two principal components: the two directions along which the flowers vary most, used only to lay out the overlapping bins. Clustering inside each bin is DBSCAN, which groups points that sit in dense neighborhoods and leaves the rest unassigned. Every node is then colored by the mean species label of the flowers inside it, running 0 for Setosa to 2 for Virginica — the labels are used to color the picture, never to build it.</p>
<div id="cell-fig-iris-mapper" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings<span class="op">;</span> warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> kmapper <span class="im">as</span> km</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> networkx <span class="im">as</span> nx</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.cluster <span class="im">import</span> DBSCAN</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.decomposition <span class="im">import</span> PCA</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.cm <span class="im">import</span> ScalarMappable</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.colors <span class="im">import</span> Normalize</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>mapper <span class="op">=</span> km.KeplerMapper(verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>lens <span class="op">=</span> mapper.fit_transform(X, projection<span class="op">=</span>PCA(n_components<span class="op">=</span><span class="dv">2</span>), scaler<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>graph <span class="op">=</span> mapper.<span class="bu">map</span>(lens, X,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>                   cover<span class="op">=</span>km.Cover(n_cubes<span class="op">=</span><span class="dv">8</span>, perc_overlap<span class="op">=</span><span class="fl">0.4</span>),</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>                   clusterer<span class="op">=</span>DBSCAN(eps<span class="op">=</span><span class="fl">1.2</span>, min_samples<span class="op">=</span><span class="dv">3</span>))</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>G <span class="op">=</span> nx.Graph()</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>node_color, node_size <span class="op">=</span> {}, {}</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> node, members <span class="kw">in</span> graph[<span class="st">"nodes"</span>].items():</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>    G.add_node(node)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a>    node_color[node] <span class="op">=</span> y[members].mean()      <span class="co"># 0=setosa ... 2=virginica</span></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a>    node_size[node] <span class="op">=</span> <span class="dv">40</span> <span class="op">+</span> <span class="dv">30</span> <span class="op">*</span> <span class="bu">len</span>(members)</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> src, dsts <span class="kw">in</span> graph[<span class="st">"links"</span>].items():</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> d <span class="kw">in</span> dsts:</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>        G.add_edge(src, d)</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Lay out each connected component on its own, then space the components apart</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a><span class="co"># horizontally so that disconnection is visually unambiguous.</span></span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>pos <span class="op">=</span> {}</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>x_offset <span class="op">=</span> <span class="fl">0.0</span></span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> cc <span class="kw">in</span> <span class="bu">sorted</span>(nx.connected_components(G), key<span class="op">=</span><span class="bu">len</span>, reverse<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb12-30"><a href="#cb12-30" aria-hidden="true" tabindex="-1"></a>    sub <span class="op">=</span> G.subgraph(cc)</span>
<span id="cb12-31"><a href="#cb12-31" aria-hidden="true" tabindex="-1"></a>    sub_pos <span class="op">=</span> nx.spring_layout(sub, seed<span class="op">=</span><span class="dv">1</span>, k<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb12-32"><a href="#cb12-32" aria-hidden="true" tabindex="-1"></a>    xs <span class="op">=</span> [p[<span class="dv">0</span>] <span class="cf">for</span> p <span class="kw">in</span> sub_pos.values()]</span>
<span id="cb12-33"><a href="#cb12-33" aria-hidden="true" tabindex="-1"></a>    span <span class="op">=</span> (<span class="bu">max</span>(xs) <span class="op">-</span> <span class="bu">min</span>(xs)) <span class="cf">if</span> <span class="bu">len</span>(xs) <span class="op">&gt;</span> <span class="dv">1</span> <span class="cf">else</span> <span class="fl">1.0</span></span>
<span id="cb12-34"><a href="#cb12-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> node, (px, py) <span class="kw">in</span> sub_pos.items():</span>
<span id="cb12-35"><a href="#cb12-35" aria-hidden="true" tabindex="-1"></a>        pos[node] <span class="op">=</span> (px <span class="op">+</span> x_offset, py)</span>
<span id="cb12-36"><a href="#cb12-36" aria-hidden="true" tabindex="-1"></a>    x_offset <span class="op">+=</span> span <span class="op">+</span> <span class="fl">1.4</span>       <span class="co"># gap between components</span></span>
<span id="cb12-37"><a href="#cb12-37" aria-hidden="true" tabindex="-1"></a>cmap <span class="op">=</span> plt.cm.viridis</span>
<span id="cb12-38"><a href="#cb12-38" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">6</span>))</span>
<span id="cb12-39"><a href="#cb12-39" aria-hidden="true" tabindex="-1"></a>nx.draw_networkx_edges(G, pos, ax<span class="op">=</span>ax, alpha<span class="op">=</span><span class="fl">0.4</span>, edge_color<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb12-40"><a href="#cb12-40" aria-hidden="true" tabindex="-1"></a>nx.draw_networkx_nodes(G, pos, ax<span class="op">=</span>ax,</span>
<span id="cb12-41"><a href="#cb12-41" aria-hidden="true" tabindex="-1"></a>                       node_color<span class="op">=</span>[node_color[n] <span class="cf">for</span> n <span class="kw">in</span> G.nodes()],</span>
<span id="cb12-42"><a href="#cb12-42" aria-hidden="true" tabindex="-1"></a>                       node_size<span class="op">=</span>[node_size[n] <span class="cf">for</span> n <span class="kw">in</span> G.nodes()],</span>
<span id="cb12-43"><a href="#cb12-43" aria-hidden="true" tabindex="-1"></a>                       cmap<span class="op">=</span>cmap, vmin<span class="op">=</span><span class="dv">0</span>, vmax<span class="op">=</span><span class="dv">2</span>, edgecolors<span class="op">=</span><span class="st">"white"</span>, linewidths<span class="op">=</span><span class="fl">0.6</span>)</span>
<span id="cb12-44"><a href="#cb12-44" aria-hidden="true" tabindex="-1"></a>sm <span class="op">=</span> ScalarMappable(cmap<span class="op">=</span>cmap, norm<span class="op">=</span>Normalize(<span class="dv">0</span>, <span class="dv">2</span>))<span class="op">;</span> sm.set_array([])</span>
<span id="cb12-45"><a href="#cb12-45" aria-hidden="true" tabindex="-1"></a>cb <span class="op">=</span> fig.colorbar(sm, ax<span class="op">=</span>ax, ticks<span class="op">=</span>[<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>], shrink<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb12-46"><a href="#cb12-46" aria-hidden="true" tabindex="-1"></a>cb.ax.set_yticklabels(species)</span>
<span id="cb12-47"><a href="#cb12-47" aria-hidden="true" tabindex="-1"></a>ax.set_title(<span class="st">"Mapper skeleton of Iris (colored by mean species)"</span>)</span>
<span id="cb12-48"><a href="#cb12-48" aria-hidden="true" tabindex="-1"></a>ax.axis(<span class="st">"off"</span>)</span>
<span id="cb12-49"><a href="#cb12-49" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb12-50"><a href="#cb12-50" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb12-51"><a href="#cb12-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-52"><a href="#cb12-52" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"connected components in Mapper graph: </span><span class="sc">{</span>nx<span class="sc">.</span>number_connected_components(G)<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div id="fig-iris-mapper" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-iris-mapper-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-iris-mapper-output-1.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-iris-mapper-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Mapper graph of Iris. Node size ∝ number of member flowers; node color = mean species label of its members (0 Setosa → 2 Virginica). Setosa forms an isolated island; Versicolor and Virginica share one connected, branching structure that grades continuously from one to the other — the topological signature of two overlapping species.
</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>connected components in Mapper graph: 3</code></pre>
</div>
</div>
<p>The picture reproduces the textbook Iris story from the shape alone. There is an <strong>isolated island</strong> of pure-Setosa nodes, dark purple and joined to nothing — Mapper has rediscovered that Setosa stands apart, never having seen a label. And there is a single <strong>connected, branching structure</strong> whose color grades from teal to yellow: Versicolor and Virginica come out not as two islands but as one shape that blends from one species into the other, because that is what the four-dimensional geometry does.</p>
<p>The third component is the caveat in the picture. It is a small Virginica satellite, a handful of extreme flowers that DBSCAN cut loose, and it exists because of the bin width, the overlap and the DBSCAN radius rather than because of the flowers. Change those knobs and the satellite moves or disappears. That sensitivity is permanent and it is why Mapper is an exploratory instrument rather than an automatic one — you read the graph the way you read a scatter plot, not the way you read a p-value.</p>
<p>With that caveat priced in, the gain over global <span class="math inline">\(H_0\)</span> is real: where <span class="math inline">\(H_0\)</span> could only report “these 100 flowers are one clump,” Mapper shows the transition running through it. The deliverable is the graph, read by a person. That is Pattern C exactly — and it is still a statement about the whole dataset, which is no help at all if the thing you want is a decision about one flower.</p>
</section>
<section id="local-persistence-turns-each-flowers-neighborhood-into-six-numbers" class="level3">
<h3 class="anchored" data-anchor-id="local-persistence-turns-each-flowers-neighborhood-into-six-numbers">Local persistence turns each flower’s neighborhood into six numbers</h3>
<p>Pattern A needs per-sample features, and global topology has none to give. The move is to shrink the microscope: instead of the shape of the dataset, take the shape of the small patch of data immediately around each flower, and turn that into a fixed-length row you can bolt onto the four raw measurements as extra columns.</p>
<p>Getting a fixed length out of a diagram is the whole trick, and here is one way to do it. Draw each bar as a little tent standing over the interval it spans — the tent’s peak height is half the bar’s length, so a long-lived feature makes a tall tent and a short-lived one makes a flat bump. Lay all the tents on the same axis and trace the outline over the top of them. Now the diagram is a curve, and a curve can be measured at whatever fixed positions you choose. Read off its height at six chosen values of <span class="math inline">\(\varepsilon\)</span> and every flower, however many bars it happened to produce, hands back six numbers. That curve is a <strong>persistence landscape</strong>. The pipeline, per flower:</p>
<ol type="1">
<li>Find its <span class="math inline">\(k = 15\)</span> nearest neighbors (a 16-point mini-cloud).</li>
<li>Run the Vietoris–Rips filtration on just those points, keeping the finite <span class="math inline">\(H_0\)</span> bars — these encode how tightly and at what scales the local neighborhood knits together.</li>
<li>Turn each bar <span class="math inline">\([b, d]\)</span> into its tent <span class="math inline">\(\Lambda(t) = \max(0, \min(t-b,\, d-t))\)</span>, take the upper envelope <span class="math inline">\(\lambda_1(t) = \max_\text{bars} \Lambda(t)\)</span>, and sample <span class="math inline">\(\lambda_1\)</span> on a fixed grid of six <span class="math inline">\(\varepsilon\)</span> values.</li>
</ol>
<div id="iris-local-features" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.neighbors <span class="im">import</span> NearestNeighbors</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">15</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>GRID <span class="op">=</span> np.linspace(<span class="fl">0.0</span>, <span class="fl">2.0</span>, <span class="dv">6</span>)     <span class="co"># 6 fixed ε slices -&gt; 6 features per flower</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>nbrs <span class="op">=</span> NearestNeighbors(n_neighbors<span class="op">=</span>K <span class="op">+</span> <span class="dv">1</span>).fit(X)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>_, idx <span class="op">=</span> nbrs.kneighbors(X)          <span class="co"># idx[i] = flower i and its 15 neighbors</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> local_landscape(neighbor_pts):</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""First H0 persistence landscape, sampled on GRID."""</span></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    bars <span class="op">=</span> ripser(neighbor_pts, maxdim<span class="op">=</span><span class="dv">1</span>)[<span class="st">"dgms"</span>][<span class="dv">0</span>]</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    bars <span class="op">=</span> bars[np.isfinite(bars[:, <span class="dv">1</span>])]         <span class="co"># finite H0 bars (births all 0)</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    lam <span class="op">=</span> np.zeros_like(GRID)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> b, d <span class="kw">in</span> bars:</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>        tent <span class="op">=</span> np.clip(np.minimum(GRID <span class="op">-</span> b, d <span class="op">-</span> GRID), <span class="dv">0</span>, <span class="va">None</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>        lam <span class="op">=</span> np.maximum(lam, tent)              <span class="co"># upper envelope λ1</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> lam</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>topo <span class="op">=</span> np.vstack([local_landscape(X[idx[i]]) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(X))])</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>cols <span class="op">=</span> [<span class="ss">f"topo_ε=</span><span class="sc">{</span>g<span class="sc">:.1f}</span><span class="ss">"</span> <span class="cf">for</span> g <span class="kw">in</span> GRID]</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>demo <span class="op">=</span> pd.DataFrame(topo, columns<span class="op">=</span>cols)</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>demo.insert(<span class="dv">0</span>, <span class="st">"species"</span>, [species[t] <span class="cf">for</span> t <span class="kw">in</span> y])</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Local persistence-landscape features (one row per flower):"</span>)</span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(demo.iloc[[<span class="dv">0</span>, <span class="dv">50</span>, <span class="dv">100</span>]].to_string(index<span class="op">=</span><span class="va">True</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Local persistence-landscape features (one row per flower):
        species  topo_ε=0.0  topo_ε=0.4  topo_ε=0.8  topo_ε=1.2  topo_ε=1.6  topo_ε=2.0
0        setosa         0.0    0.000000         0.0         0.0         0.0         0.0
50   versicolor         0.0    0.281265         0.0         0.0         0.0         0.0
100   virginica         0.0    0.113791         0.0         0.0         0.0         0.0</code></pre>
</div>
</div>
<p>Look at the three example rows, one flower per species. The Setosa row is <strong>all zeros</strong>: its 15 neighbors sit so tightly together that every local <span class="math inline">\(H_0\)</span> bar has died before the sweep reaches the first grid point that could register it, so the tents are flat everywhere the curve is sampled. The Versicolor and Virginica rows carry a <strong>nonzero</strong> height at <span class="math inline">\(\varepsilon = 0.4\)</span> and zeros elsewhere — their neighborhoods are looser, so some of the local merges have not happened yet at 0.4, though all of them are done by 0.8. That is a thin signal, one number wide, and it is still enough to be a difference a classifier can use. Whether it is a difference worth paying for is the next question.</p>
<div id="iris-classifier" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.ensemble <span class="im">import</span> RandomForestClassifier</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score, StratifiedKFold</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>cv <span class="op">=</span> StratifiedKFold(<span class="dv">5</span>, shuffle<span class="op">=</span><span class="va">True</span>, random_state<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> acc(features):</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> cross_val_score(RandomForestClassifier(n_estimators<span class="op">=</span><span class="dv">200</span>, random_state<span class="op">=</span><span class="dv">0</span>),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>                           features, y, cv<span class="op">=</span>cv).mean()</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"raw 4 measurements only : </span><span class="sc">{</span>acc(X)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"topo landscape only (6) : </span><span class="sc">{</span>acc(topo)<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"raw + topo (10 features): </span><span class="sc">{</span>acc(np.hstack([X, topo]))<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>raw 4 measurements only : 0.933
topo landscape only (6) : 0.827
raw + topo (10 features): 0.947</code></pre>
</div>
</div>
<p>Both numbers are worth sitting with. The <strong>local-shape features alone</strong>, with the four measurements thrown away entirely, classify the three species at about <strong>0.83</strong>. That is more than it sounds: those six columns know nothing about how big a petal is, only about how the flowers near this flower are spaced. Adding them back to the raw measurements moves accuracy from roughly <strong>0.93</strong> to <strong>0.95</strong> — a real improvement, and a small one.</p>
<p>That small number is the honest result, and it is the argument the rest of this post has been walking toward.</p>
</section>
</section>
<section id="persistence-is-a-hypothesis-about-your-data-not-a-free-block-of-columns" class="level2">
<h2 class="anchored" data-anchor-id="persistence-is-a-hypothesis-about-your-data-not-a-free-block-of-columns">Persistence is a hypothesis about your data, not a free block of columns</h2>
<p>The four patterns are TDA used well. Each matches the machinery to a question where shape genuinely carries information: cyclic dynamics, void structure, branching trajectories, structural change. The abuse is not a fifth pattern. It is Pattern A applied without asking whether this dataset has a shape at all — persistent homology as a feature generator you sprinkle on for luck.</p>
<p>The Iris run is a mild, friendly instance of exactly that. The local landscapes did add signal, 0.93 to 0.95, but the four raw measurements had already solved the problem, so topology earned a rounding error in exchange for a nearest-neighbor filtration per flower. On data whose signal lived in the shape rather than the coordinates, the same pipeline could be decisive. Here it is decoration. The lesson is not that TDA failed — it worked, and it told the truth about the flowers — but that the size of the payoff was set by the data before the method was chosen.</p>
<p>The expensive version of the same mistake is quiet. Bolt persistence onto tabular data whose signal lives in a handful of marginal effects, or onto a point cloud with no loops or voids in it, and you pay in full — Vietoris–Rips grows combinatorially in the number of points and in the homology dimension — for nothing. Worse, you can <em>manufacture</em> signal. Short-lived features hugging the diagonal are noise, but a flexible model handed them as columns will find handles in them and overfit, and the topology lends a look of principled sophistication to what is really the model memorizing the sample.</p>
<p>So the discipline is diagnostic before decorative, and it is one question asked before the pipeline is built rather than after. Plot the persistence diagram. Is anything sitting well above the diagonal? And can you name the mechanism that would put it there — a periodicity, a cycle, a spatial exclusion that keeps the middle empty — in <em>this</em> domain? If the diagram is noise on the diagonal and you cannot name the geometry you expected, a density method will be cheaper and just as good.</p>
<p>Which is where we came in. The dartboard with the bullseye rubbed out is the case that justifies all of this: a hole is not a density fact, no clustering algorithm will ever report one, and TDA is the machinery that will. It will also run, uncomplainingly and at full price, on the dartboard with the bullseye still in it. The tool cannot tell you which one you are holding. That part is yours.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li>Zhou, Y. &amp; Wang, B. <em>Topological Machine Learning for Mixed Numeric and Categorical Data.</em> arXiv:2003.04584. <a href="https://arxiv.org/abs/2003.04584" class="uri">https://arxiv.org/abs/2003.04584</a></li>
<li>Bhatia, S., Chatterjee, B., Nathani, D. &amp; Kaul, M. <em>Understanding and Predicting Links in Graphs: A Persistent Homology Perspective.</em> arXiv:1811.04049. <a href="https://arxiv.org/abs/1811.04049" class="uri">https://arxiv.org/abs/1811.04049</a></li>
<li>Minamitani, E. et al.&nbsp;<em>Persistent homology-based descriptor for machine-learning potential of amorphous structures.</em> Journal of Chemical Physics <strong>159</strong>, 084101 (2023). <a href="https://doi.org/10.1063/5.0159349" class="uri">https://doi.org/10.1063/5.0159349</a></li>
<li>Ismail, M. S. et al.&nbsp;<em>Detecting Early Warning Signals of Major Financial Crashes in Bitcoin Using Persistent Homology.</em> IEEE Access <strong>8</strong> (2020). <a href="https://doi.org/10.1109/ACCESS.2020.3033701" class="uri">https://doi.org/10.1109/ACCESS.2020.3033701</a></li>
<li>Gidea, M. &amp; Katz, Y. <em>Topological Data Analysis of Financial Time Series: Landscapes of Crashes.</em> Physica A <strong>491</strong>, 820–834 (2018). <a href="https://doi.org/10.1016/j.physa.2017.09.028" class="uri">https://doi.org/10.1016/j.physa.2017.09.028</a></li>
<li>Pranav, P. et al.&nbsp;<em>The topology of the Cosmic Web in terms of persistent Betti numbers.</em> Monthly Notices of the Royal Astronomical Society <strong>465</strong>, 4281–4310 (2017). <a href="https://doi.org/10.1093/mnras/stw2862" class="uri">https://doi.org/10.1093/mnras/stw2862</a></li>
<li>Wilding, G. et al.&nbsp;<em>Persistent homology of the cosmic web I: Hierarchical topology in ΛCDM cosmologies.</em> Monthly Notices of the Royal Astronomical Society <strong>507</strong>, 2968–2990 (2021). <a href="https://doi.org/10.1093/mnras/stab2326" class="uri">https://doi.org/10.1093/mnras/stab2326</a></li>
<li>Wright, M. &amp; Zheng, X. <em>Topological Data Analysis on Simple English Wikipedia Articles.</em> arXiv:2007.00063. <a href="https://arxiv.org/abs/2007.00063" class="uri">https://arxiv.org/abs/2007.00063</a></li>
<li>Nicolau, M., Levine, A. J. &amp; Carlsson, G. <em>Topology based data analysis identifies a subgroup of breast cancers with a unique mutational profile and excellent survival.</em> Proceedings of the National Academy of Sciences <strong>108</strong>, 7265–7270 (2011). <a href="https://doi.org/10.1073/pnas.1102826108" class="uri">https://doi.org/10.1073/pnas.1102826108</a></li>
<li>Rizvi, A. H. et al.&nbsp;<em>Single-cell topological RNA-seq analysis reveals insights into cellular differentiation and development.</em> Nature Biotechnology <strong>35</strong>, 551–560 (2017). <a href="https://doi.org/10.1038/nbt.3854" class="uri">https://doi.org/10.1038/nbt.3854</a></li>
<li>Xia, K. &amp; Wei, G. W. <em>Persistent homology analysis of protein structure, flexibility, and folding.</em> International Journal for Numerical Methods in Biomedical Engineering <strong>30</strong>, 814–844 (2014). <a href="https://doi.org/10.1002/cnm.2655" class="uri">https://doi.org/10.1002/cnm.2655</a></li>
<li>Stolz, B. J. et al.&nbsp;<em>Topological data analysis of knot structures in DNA.</em> (Analysis of knotting and supercoiling in biological polymers via persistent homology.) <a href="https://doi.org/10.1007/s41468-018-0018-0" class="uri">https://doi.org/10.1007/s41468-018-0018-0</a></li>
<li>Hajij, M. et al.&nbsp;<em>Visual Detection of Structural Changes in Time-Varying Graphs Using Persistent Homology.</em> arXiv:1707.06683. <a href="https://arxiv.org/abs/1707.06683" class="uri">https://arxiv.org/abs/1707.06683</a></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/uses-and-abuses-of-tda/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>