{
  "hash": "7a7569e55a49d731c8f1c459dd9bfe6e",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"CP or Tucker in Practice\"\nsubtitle: \"Knowledge graphs, conv kernels, and choosing the rank\"\ndescription: \"Measured on FB15k-237 and a trained ResNet-18 kernel. DistMult's symmetry rarely gets the chance to cost a ranking, and Tucker's case in knowledge graphs is parameter count. CP stores the kernel in about half Tucker-2's numbers at the same error, by cancelling terms many times the kernel's size. The kernel's HOSVD scree has no elbow, and an over-parameterised CP prunes itself to the true rank under any of three factor penalties.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-09-26\"\ncategories: [Tensors, Linear Algebra, Deep Learning, Machine Learning]\nimage: \"./cover.png\"\ntags: [CP, Tucker, HOSVD, TuckER, DistMult, ComplEx, RESCAL, knowledge graph, FB15k-237, CNN compression, ResNet-18, rank selection, group lasso, TensorLy, PyTorch]\njupyter: cp-tucker-blog\nresources:\n  - cover.png\n  - data\nexecute:\n  warning: false\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    number-sections: true\n    fig-width: 8\n    fig-height: 4.2\n    fig-dpi: 150\n---\n\n\n![CP or Tucker in Practice](./cover.png){fig-alt=\"Relative reconstruction error of a ResNet-18 conv kernel against compression ratio for CP and Tucker-2, beside the size of CP's largest component relative to the kernel.\"}\n\nCP and Tucker differ in one object, the core tensor, and the right core depends on\nwhether the factorization has to predict entries nobody observed or store a known\ntensor in fewer numbers.\n\nA knowledge-graph embedding and a compressed convolution layer are both tensor\nfactorizations, and both literatures offer the same two families. The jobs pull\napart. A knowledge-graph model has to score facts nobody recorded, and has to score\n(Paris, capital of, France) high while scoring (France, capital of, Paris) low. A\ncompressed layer has to reproduce a kernel it has already seen, in fewer numbers,\nwithout making the network unstable to fine-tune. The first job asks what a core can\nexpress. The second asks what it costs.\n\n[CP or Tucker](../cp-or-tucker/) derives both models: CP's uniqueness, Tucker's\nrotational freedom, and their storage counts. Here they meet two real tensors — the\nFB15k-237 knowledge graph and a trained ResNet-18 kernel — and then the question both\nleave open, which rank to fit. HOSVD appears as a way to fit Tucker and read off its\nranks, not as a third model.\n\n\n\n## Notation\n\nFor an $N$-way tensor $\\mathcal{X}\\in\\mathbb{R}^{I_1\\times\\cdots\\times I_N}$:\n\n- **CP at rank $R$.** A sum of $R$ rank-one terms, one column per mode per term:\n\n  $$\n  \\mathcal{X}\\approx\\sum_{r=1}^{R} a^{(1)}_r\\circ a^{(2)}_r\\circ\\cdots\\circ a^{(N)}_r .\n  $$\n\n- **Tucker at multilinear rank $(R_1,\\dots,R_N)$.** A core $\\mathcal{G}$ multiplied\n  by one factor matrix per mode:\n\n  $$\n  \\mathcal{X}\\approx\\mathcal{G}\\times_1 U^{(1)}\\times_2 U^{(2)}\\cdots\\times_N U^{(N)},\n  \\qquad \\mathcal{G}\\in\\mathbb{R}^{R_1\\times\\cdots\\times R_N}.\n  $$\n\n- **CP is Tucker with a superdiagonal core.** Set every $R_n=R$ and zero every entry\n  of $\\mathcal{G}$ except $\\mathcal{G}_{r r\\cdots r}$. Component $r$ of mode 1 then\n  meets only component $r$ of the other modes. A dense core lets any component of one\n  mode meet any component of another.\n- **Parameter counts.** CP stores $R\\sum_n I_n$ numbers. Tucker stores\n  $\\prod_n R_n+\\sum_n I_nR_n$, and the core product is what grows fastest.\n- **HOSVD.** Take the SVD of each mode-$n$ unfolding $\\mathcal{X}_{(n)}$, keep $R_n$\n  left singular vectors as $U^{(n)}$, and set\n  $\\mathcal{G}=\\mathcal{X}\\times_1 U^{(1)\\top}\\cdots\\times_N U^{(N)\\top}$. HOOI\n  iterates from there; `tensorly`'s `tucker(init=\"svd\")` is HOSVD followed by HOOI.\n\n## Knowledge-graph completion\n\n### Tensor\n\n::: {#kg-data .cell execution_count=2}\n``` {.python .cell-code}\nkg = json.loads((DATA / \"fb15k237_manifest.json\").read_text())\nrel = pd.read_csv(DATA / \"fb15k237_relations.csv\")\n\nn_ent, n_rel = kg[\"entities\"], kg[\"relations\"]\nn_train = kg[\"triples\"][\"train\"]\ncells = n_ent * n_rel * n_ent\ndensity = n_train / cells\n\nnever = rel.reversed_fraction == 0\nmostly = rel.reversed_fraction >= 0.5\npairs = rel.train_pairs.sum()\nshare_never = rel.train_pairs[never].sum() / pairs\nshare_mostly = rel.train_pairs[mostly].sum() / pairs\nshare_reversed = (rel.train_pairs * rel.reversed_fraction).sum() / pairs\nn_between = int(((rel.reversed_fraction > 0.1) & (rel.reversed_fraction < 0.5)).sum())\nassert n_between == 1  # the prose says \"1 relation falls\"\n\n# Exposure: a pair whose object is also a subject of the relation, or whose\n# subject is also an object. Only then can a symmetric score put a reversed pair\n# ahead of a true answer in a ranking query.\nnv = rel[never]\none_role = nv.two_role_fraction == 0\nn_one_role = int(one_role.sum())\nexposed_never = (nv.train_pairs * nv.two_role_fraction).sum() / nv.train_pairs.sum()\ncontains = rel.set_index(\"relation\").loc[\"/location/location/contains\"]\n```\n:::\n\n\nFB15k-237 is the standard benchmark for this job.\n\n- **Provenance.** Bordes et al. (2013) cut FB15k out of Freebase, the\n  crowd-edited knowledge base Google bought and later shut down. Toutanova and\n  Chen (2015) removed near-duplicate and inverse relations from it, because many\n  FB15k test triples could be answered by flipping a training triple. The copy read here is the\n  one distributed with TuckER; `src/fetch_fb15k237.py` downloads it, counts it, and\n  keeps only per-relation counts.\n- **Shape.** Subject × relation × object: a binary tensor $\\mathcal{Y}$ of shape\n  14\\,541 × 237 × 14\\,541, with a 1 for\n  every recorded fact.\n- **Size.** 50\\,111\\,441\\,397 cells, 272\\,115 of them ones in\n  training: a density of 5\\.4e\\-06. At $10^5$ entities and $10^3$\n  relations the count would be $10^{13}$ cells.\n- **What a wrong answer costs.** A model that cannot tell a fact from its reversal\n  ranks (Paris, contains, France) as high as (France, contains, Paris), and every\n  downstream query inherits the error.\n\nThe question to ask of the data is how often a relation's reversal is also a fact.\n\n- 207 of the 237 relations — carrying\n  81% of the training triples — never contain a reversed\n  pair $(o,s)$ alongside $(s,o)$.\n- 24 relations have reversals for at least half their\n  pairs. They are the symmetric ones: siblings, cast members of the same season,\n  combatants in the same war.\n- Only 1 relation falls between 10% and 50%. A relation is either\n  directional or symmetric, almost never partly both.\n- Over the training set, 12\\.5% of triples have their\n  reversal recorded.\n\n::: {#cell-fig-reversal .cell fig-height='3.2' execution_count=3}\n``` {.python .cell-code}\nfig, ax = plt.subplots()\nax.hist(\n    rel.reversed_fraction,\n    bins=np.linspace(0, 1, 21),\n    weights=rel.train_pairs / pairs,\n    color=ACCENT,\n    edgecolor=\"white\",\n)\nax.set_xlabel(\"fraction of a relation's pairs whose reversal is also recorded\")\nax.set_ylabel(\"share of training triples\")\nax.yaxis.set_major_formatter(plt.FuncFormatter(lambda v, _: f\"{v:.0%}\"))\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Per-relation fraction of FB15k-237 training pairs $(s,o)$ whose reversal $(o,s)$ is also a training triple, weighted by how many triples the relation carries.](index_files/figure-html/fig-reversal-output-1.png){#fig-reversal fig-alt='Histogram of the reversed fraction for FB15k-237 relations, weighted by triples. About 85% of the weight sits in the bar at zero and about 15% in one bar near 0.8, with nothing between.'}\n:::\n:::\n\n\n### Scoring functions as cores\n\nEvery model in this family scores a triple $(s,r,o)$ as a multilinear form in three\nembeddings, $e_s$, $w_r$ and $e_o$. The core decides which coordinates may meet.\n\n- **DistMult** (Yang et al. 2015): superdiagonal core, one entity matrix for both\n  subject and object.\n\n  $$\n  \\phi(s,r,o)=\\sum_k e_{s,k}\\,w_{r,k}\\,e_{o,k}=\\phi(o,r,s).\n  $$\n\n  The sum is unchanged when $s$ and $o$ swap, for every relation. On FB15k-237 that\n  gives every fact in the 207 never-reversed relations the\n  same score as its reversal. The score only costs a ranking when an entity plays\n  both roles in one relation, though, since only then does a reversed pair compete\n  with a true answer. In 173 of those 207\n  relations no entity does, and across all of them 3\\.0%\n  of pairs are exposed. Hierarchies are where it bites: a city contains districts and\n  is contained by a country. `/location/location/contains` is never reversed, and\n  80% of its\n  5\\,201 pairs are exposed.\n- **CP with untied entities**: superdiagonal core, separate subject matrix $A$ and\n  object matrix $C$.\n\n  $$\n  \\phi(s,r,o)=\\sum_k a_{s,k}\\,w_{r,k}\\,c_{o,k}.\n  $$\n\n  This is asymmetric. Its weakness is different: $a_s$ and $c_s$ share nothing, so\n  what the model learns about Paris as a subject says nothing about Paris as an\n  object. Lacroix et al. (2018) fix that by also training on the reciprocal triple\n  $(o,r^{-1},s)$, which puts every entity in both roles.\n- **ComplEx** (Trouillon et al. 2016): superdiagonal core over complex embeddings,\n  tied entities, $\\phi=\\operatorname{Re}\\sum_k e_{s,k}w_{r,k}\\bar e_{o,k}$. The\n  conjugate breaks the symmetry.\n- **RESCAL** (Nickel et al. 2011): one full $d_e\\times d_e$ matrix $M_r$ per relation,\n  $\\phi=e_s^\\top M_re_o$. That is Tucker-2: entity modes compressed, relation mode\n  left at full length, core $=$ the stack of $M_r$.\n- **TuckER** (Balažević et al. 2019): a dense core\n  $\\mathcal{G}\\in\\mathbb{R}^{d_e\\times d_r\\times d_e}$ shared by every relation,\n  and tied entities.\n\n  $$\n  \\phi(s,r,o)=\\mathcal{G}\\times_1 e_s\\times_2 w_r\\times_3 e_o .\n  $$\n\n  Each relation's matrix $M_r=\\mathcal{G}\\times_2 w_r$ is a mix of $d_r$ shared slices.\n  Tied entities keep one vector per entity, as in DistMult. The asymmetry comes from\n  the core: nothing forces a slice of $\\mathcal{G}$ to be a symmetric matrix.\n\nTuckER's paper shows that \"RESCAL, DistMult, ComplEx and SimplE are special cases of\nTuckER\": each is a TuckER core with a constraint. The choice is which constraint to\npay for.\n\n### Loss\n\nThe tensor is almost all unobserved, and unobserved is not false. Least squares over\nevery cell treats each missing triple as a known zero, and all but\n5\\.4 in every million of its terms are those zeros. The benchmark scores rank,\nnot reconstruction.\n\n- **Binary cross-entropy with 1-N scoring** (TuckER): score $(s,r,\\cdot)$ against every\n  entity at once, with target 1 for the recorded objects, 0 elsewhere, and label\n  smoothing of 0.1.\n- **Softmax cross-entropy over entities** (Lacroix et al. 2018): the recorded object\n  must win against all others.\n- **BPR** (Rendle et al. 2009), for implicit feedback: a pairwise ranking loss,\n  $-\\log\\sigma\\big(\\phi(s,r,o)-\\phi(s,r,o')\\big)$ for a recorded $o$ and a sampled\n  unrecorded $o'$. It suits user × item × context recommender tensors, where the\n  only signal is what was clicked.\n\n### Published results\n\n::: {#cell-kg-params .cell execution_count=4}\n``` {.python .cell-code}\nrecip = 2 * n_rel  # both papers also train on reciprocal relations\n\nsizes = {\n    # model: (entity numbers per entity, relation numbers per relation, core)\n    \"CP-N3, rank 4000\": (2 * 4000, 4000, 0),  # separate subject and object tables\n    \"ComplEx-N3, rank 2000\": (2 * 2000, 2 * 2000, 0),  # real and imaginary parts\n    \"TuckER, $d_e=d_r=200$\": (200, 200, 200**3),\n}\nparams = {\n    name: n_ent * per_ent + recip * per_rel + core\n    for name, (per_ent, per_rel, core) in sizes.items()\n}\ncp_n3, complex_n3, tucker_kg = params.values()\nper_entity = {name: per_ent for name, (per_ent, _, _) in sizes.items()}\n\nmd_table(\n    pd.DataFrame(\n        {\n            \"Model\": [\n                \"DistMult\",\n                \"ComplEx\",\n                \"RESCAL\",\n                \"CP-N3\",\n                \"ComplEx-N3\",\n                \"TuckER\",\n            ],\n            \"Core\": [\n                \"superdiagonal\",\n                \"superdiagonal, complex\",\n                \"full matrix per relation\",\n                \"superdiagonal\",\n                \"superdiagonal, complex\",\n                \"dense, shared\",\n            ],\n            \"Entities\": [\"tied\", \"tied\", \"tied\", \"untied\", \"tied\", \"tied\"],\n            \"Numbers per entity\": [\"\", \"\", \"\", *(f\"{n:,}\" for n in per_entity.values())],\n            \"Parameters\": [\"\", \"\", \"\", millions(cp_n3), millions(complex_n3), millions(tucker_kg)],\n            \"FB15k-237 MRR\": [\"0.343\", \"0.348\", \"0.356\", \"0.36\", \"0.37\", \"0.358\"],\n            \"Source\": [\n                \"Ruffinelli et al. 2020\",\n                \"Ruffinelli et al. 2020\",\n                \"Ruffinelli et al. 2020\",\n                \"Lacroix et al. 2018\",\n                \"Lacroix et al. 2018\",\n                \"Balažević et al. 2019\",\n            ],\n        }\n    )\n)\n```\n\n::: {#kg-params .cell-output .cell-output-display .cell-output-markdown execution_count=4}\n| Model | Core | Entities | Numbers per entity | Parameters | FB15k-237 MRR | Source |\n|---|---|---|---|---|---|---|\n| DistMult | superdiagonal | tied |  |  | 0.343 | Ruffinelli et al. 2020 |\n| ComplEx | superdiagonal, complex | tied |  |  | 0.348 | Ruffinelli et al. 2020 |\n| RESCAL | full matrix per relation | tied |  |  | 0.356 | Ruffinelli et al. 2020 |\n| CP-N3 | superdiagonal | untied | 8,000 | 118.2M | 0.36 | Lacroix et al. 2018 |\n| ComplEx-N3 | superdiagonal, complex | tied | 4,000 | 60.1M | 0.37 | Lacroix et al. 2018 |\n| TuckER | dense, shared | tied | 200 | 11.0M | 0.358 | Balažević et al. 2019 |\n:::\n:::\n\n\nMRR is mean reciprocal rank of the true entity; higher is better. Parameter counts are\ncomputed from each paper's published embedding sizes and FB15k-237's\n14\\,541 entities and 474 relations with reciprocals. The\nRuffinelli et al. rows come from a common hyperparameter search in LibKGE, where sizes\nvary by model, so they carry no count.\n\n- **Symmetry costs less than the algebra suggests.** DistMult reaches 0.343 once\n  tuned. TuckER's own table lists it at 0.241, so the training recipe moved one model\n  by about 0.10 MRR, more than the spread between all six rows. The exposure\n  count shows why it costs so little: on this benchmark the symmetry rarely gets the\n  chance.\n- **Untied CP is not symmetric, and ties TuckER on MRR.** CP-N3 reaches 0.36 against\n  TuckER's 0.358.\n- **Tucker's case is size.** At the published settings TuckER matches CP-N3 with\n  11× fewer parameters and ComplEx-N3 with\n  5\\.5× fewer. Entity tables dominate every count,\n  and TuckER stores 200 numbers per entity against CP-N3's 8,000. At $10^5$ entities\n  that is $2\\times10^7$ numbers against $8\\times10^8$.\n- **The relation dimension is a separate dial.** TuckER sets $d_r=30$ against\n  $d_e=200$ on WN18RR, which has 11 relations. CP and ComplEx force one rank on every\n  mode.\n- **Sharing is TuckER's argument, not a measurement here.** Its authors describe the\n  shared core as multi-task learning across relations, which should help relations\n  with few triples. None of the published tables isolates that effect.\n\nThe ranking this supports:\n\n- Rule out DistMult when entities play both roles in asymmetric relations —\n  containment, parenthood, citation.\n- Choose a Tucker core when entity count or memory is the constraint.\n- Treat the MRR gap between CP-N3, ComplEx-N3 and TuckER as noise next to the training\n  recipe.\n\n## Conv-kernel compression\n\n### Tensor\n\n::: {#kernel .cell execution_count=5}\n``` {.python .cell-code}\nmeta = json.loads((DATA / \"resnet18_manifest.json\").read_text())\nK = np.load(DATA / \"resnet18_layer3_1_conv2.npy\").astype(np.float64)\nK_norm = np.linalg.norm(K)\ndense = K.size\nC_out, C_in, kh, kw = K.shape\n```\n:::\n\n\n- **Provenance.** `layer3.1.conv2.weight` from ResNet-18 (He et al. 2016), in the\n  ImageNet weights torchvision ships as `IMAGENET1K_V1`\n  (resnet18\\-f37072fd\\.pth). `src/fetch_kernel.py` pulls the one layer\n  and caches it.\n- **Shape.** Out-channels × in-channels × height × width\n  = 256 × 256 × 3 × 3,\n  589\\,824 weights, stride 1. ResNets repeat this shape: layer 3 of\n  ResNet-18 has three such kernels.\n- **What is asked of it.** How many numbers CP and Tucker-2 need to reach a given\n  weight error, and whether the fitted terms stay well-behaved.\n- **What a wrong answer costs.** A factorization that fits the weights badly needs\n  long fine-tuning to recover accuracy. One that fits them unstably may not\n  fine-tune at all.\n\nA trained kernel is the right test because it carries whatever structure training\ngave it. A random tensor of the same shape would have none.\n\n### CP as four convolutions\n\nWrite the rank-$R$ CP of the kernel with one factor matrix per mode:\n\n$$\n\\mathcal{K}_{t,s,i,j}\\approx\\sum_{r=1}^{R}U^{\\text{out}}_{t r}\\,U^{\\text{in}}_{s r}\\,U^{h}_{i r}\\,U^{w}_{j r}.\n$$\n\nSubstituting into the convolution $y_t=\\sum_s\\mathcal{K}_{t,s}\\ast x_s$ splits it\ninto four steps (Lebedev et al. 2015):\n\n1. 1×1 conv, 256 → $R$ channels, weights $U^{\\text{in}}$.\n2. 3×1 depthwise conv on each of the $R$ channels, weights $U^{h}$.\n3. 1×3 depthwise conv on each of the $R$ channels, weights $U^{w}$.\n4. 1×1 conv, $R$ → 256 channels, weights $U^{\\text{out}}$.\n\nThe sequence stores $R(256+3+3+256)=518R$ numbers, and at stride 1 it does that many\nmultiply-adds per output pixel.\n[Uses of Tensor Factorizations](../uses-of-tensor-factorizations/) walks through this\nchain on a synthetic kernel. Here it runs on the real one, next to Tucker-2.\n\n::: {#cp-convs .cell execution_count=6}\n``` {.python .cell-code}\nR = 36\nweights, (U_out, U_in, U_h, U_w) = parafac(K, rank=R, init=\"random\", random_state=0, n_iter_max=50)\nU_out = U_out * weights  # fold the CP weights into one factor\n\n\ndef t32(a):\n    return torch.tensor(np.ascontiguousarray(a), dtype=torch.float32)\n\n\ncp_convs = nn.Sequential(\n    nn.Conv2d(C_in, R, 1, bias=False),\n    nn.Conv2d(R, R, (kh, 1), padding=(kh // 2, 0), groups=R, bias=False),\n    nn.Conv2d(R, R, (1, kw), padding=(0, kw // 2), groups=R, bias=False),\n    nn.Conv2d(R, C_out, 1, bias=False),\n)\nwith torch.no_grad():\n    cp_convs[0].weight.copy_(t32(U_in.T[:, :, None, None]))\n    cp_convs[1].weight.copy_(t32(U_h.T[:, None, :, None]))\n    cp_convs[2].weight.copy_(t32(U_w.T[:, None, None, :]))\n    cp_convs[3].weight.copy_(t32(U_out[:, :, None, None]))\n\nx = torch.randn(8, C_in, 14, 14, generator=torch.Generator().manual_seed(0))\nK_cp = t32(tl.cp_to_tensor((np.ones(R), [U_out, U_in, U_h, U_w])))\nwith torch.no_grad():\n    cp_gap = (cp_convs(x) - F.conv2d(x, K_cp, padding=1)).abs().max().item()\n    cp_scale = F.conv2d(x, K_cp, padding=1).abs().max().item()\ncp_count = sum(p.numel() for p in cp_convs.parameters())\n```\n:::\n\n\nThe check feeds a random batch through the four-layer chain and through one 3×3 conv\nwhose kernel is the CP reconstruction. The largest output difference is\n8\\.6e\\-06 on outputs of size up to 5\\.2:\nfloat32 rounding. The chain holds 18\\,648 weights, the formula's\n518 × 36. The check tests the wiring, not the approximation.\n\n### Tucker-2\n\nTucker-2 compresses only the two channel modes and keeps the 3×3 spatial modes\nwhole (Kim et al. 2016):\n\n$$\n\\mathcal{K}\\approx\\mathcal{G}\\times_1U^{\\text{out}}\\times_2U^{\\text{in}},\n\\qquad\\mathcal{G}\\in\\mathbb{R}^{R_o\\times R_i\\times3\\times3}.\n$$\n\n1. 1×1 conv, 256 → $R_i$ channels, weights $U^{\\text{in}}$.\n2. 3×3 conv, $R_i\\to R_o$ channels, weights $\\mathcal{G}$, with the original stride\n   and padding.\n3. 1×1 conv, $R_o$ → 256 channels, weights $U^{\\text{out}}$.\n\nIt stores $256R_i+256R_o+9R_oR_i$ numbers. Kim et al. leave the spatial modes alone\nbecause they \"are already quite small\": a length-3 mode has little to give.\n\n::: {#tucker2-convs .cell execution_count=7}\n``` {.python .cell-code}\n(core, (V_out, V_in)), _ = partial_tucker(K, rank=[40, 43], modes=[0, 1], init=\"svd\", n_iter_max=50)\ntucker_convs = nn.Sequential(\n    nn.Conv2d(C_in, 43, 1, bias=False),\n    nn.Conv2d(43, 40, 3, padding=1, bias=False),\n    nn.Conv2d(40, C_out, 1, bias=False),\n)\nwith torch.no_grad():\n    tucker_convs[0].weight.copy_(t32(V_in.T[:, :, None, None]))\n    tucker_convs[1].weight.copy_(t32(core))\n    tucker_convs[2].weight.copy_(t32(V_out[:, :, None, None]))\n    K_t2 = t32(tl.tenalg.multi_mode_dot(core, [V_out, V_in], modes=[0, 1]))\n    t2_gap = (tucker_convs(x) - F.conv2d(x, K_t2, padding=1)).abs().max().item()\nt2_count = sum(p.numel() for p in tucker_convs.parameters())\n```\n:::\n\n\nAt $(R_o,R_i)=(40,43)$ the chain holds 36\\,728 weights and matches\nits reconstruction to 8\\.6e\\-06.\n\n### Matched budgets\n\n\"Tucker's core caps compression\" is arithmetic before it is a measurement. At equal\nrank, Tucker-2 costs $512R+9R^2$ against CP's $518R$, so the quadratic core term wins\nearly. CP stops compressing at all only past $R\\approx1139$, square Tucker-2 past\n$R\\approx229$.\n\nEqual rank is the wrong comparison, though: the two models fit the kernel to\ndifferent errors. The fair one fixes a parameter budget and asks which fits better.\n\n- **Budgets.** 64, 32, 16, 8, 4 and 2 times fewer numbers than the dense kernel.\n- **CP.** The rank that meets each budget, fitted by ALS with line search, 1000\n  iterations, three random starts.\n- **Tucker-2.** Every $(R_o,R_i)$ whose count stays within CP's at that budget — $R_o$\n  in steps of 4, then every $R_o$ within 3 of the best — fitted by HOOI from HOSVD.\n  The best pair is kept, so Tucker-2 never gets more numbers than CP.\n- **Degeneracy tell.** For CP, the largest rank-one term's Frobenius norm divided by\n  $\\|\\mathcal{K}\\|$. A term many times larger than the tensor it helps build is\n  cancelling against another one. Tucker-2's orthonormal factors keep its core's norm\n  at or below $\\|\\mathcal{K}\\|$.\n- `src/sweep.py` runs the sweep and caches it; the fits take minutes each at the\n  larger ranks.\n\n::: {#cell-sweep .cell execution_count=8}\n``` {.python .cell-code}\ncp_runs = pd.concat(pd.read_csv(p) for p in sorted(DATA.glob(\"sweep_cp_seed*.csv\")))\nt2_runs = pd.read_csv(DATA / \"sweep_tucker2.csv\")\n\ncp_sum = (\n    cp_runs.groupby(\"ratio\")\n    .agg(\n        rank=(\"rank\", \"first\"),\n        params=(\"params\", \"first\"),\n        lo=(\"rel_error\", \"min\"),\n        hi=(\"rel_error\", \"max\"),\n        norm_lo=(\"max_component_norm\", \"min\"),\n        norm_hi=(\"max_component_norm\", \"max\"),\n        seeds=(\"seed\", \"nunique\"),\n    )\n    .sort_index(ascending=False)\n)\nt2_best = (\n    t2_runs.loc[t2_runs.groupby(\"ratio\").rel_error.idxmin()]\n    .set_index(\"ratio\")\n    .sort_index(ascending=False)\n)\nratios = cp_sum.index.to_numpy()\ngap = t2_best.rel_error.loc[ratios] - cp_sum.hi\ncp_wins = bool((gap > 0).all())\nassert cp_wins, \"the prose says CP wins at every budget\"\nspread = (cp_sum.hi - cp_sum.lo).max()\ntail = cp_runs.tail_improvement.max()\n\n\ndef span(lo, hi, fmt):\n    \"\"\"One value when the two ends agree at this precision, else a range.\"\"\"\n    a, b = format(lo, fmt), format(hi, fmt)\n    return a if a == b else f\"{a}–{b}\"\n\n\ndef cp_err(r):\n    return span(cp_sum.lo[r], cp_sum.hi[r], \".3f\")\n\n\ndef t2_err(r):\n    return f\"{t2_best.rel_error[r]:.3f}\"\n\nmd_table(\n    pd.DataFrame(\n        {\n            \"Compression\": [f\"{r}×\" for r in ratios],\n            \"CP rank\": cp_sum[\"rank\"].to_numpy(),\n            \"CP numbers\": [f\"{n:,}\" for n in cp_sum.params],\n            \"CP error (range)\": [span(a, b, \".3f\") for a, b in zip(cp_sum.lo, cp_sum.hi)],\n            \"CP largest term / ‖K‖\": [\n                span(a, b, \".1f\") for a, b in zip(cp_sum.norm_lo, cp_sum.norm_hi)\n            ],\n            \"Tucker-2 $(R_o,R_i)$\": [\n                f\"({o}, {i})\" for o, i in zip(t2_best.r_out.loc[ratios], t2_best.r_in.loc[ratios])\n            ],\n            \"Tucker-2 numbers\": [f\"{n:,}\" for n in t2_best.params.loc[ratios]],\n            \"Tucker-2 error\": [f\"{e:.3f}\" for e in t2_best.rel_error.loc[ratios]],\n        }\n    )\n)\n```\n\n::: {#sweep .cell-output .cell-output-display .cell-output-markdown execution_count=8}\n| Compression | CP rank | CP numbers | CP error (range) | CP largest term / ‖K‖ | Tucker-2 $(R_o,R_i)$ | Tucker-2 numbers | Tucker-2 error |\n|---|---|---|---|---|---|---|---|\n| 64× | 18 | 9,324 | 0.903–0.904 | 7.5–227.8 | (15, 14) | 9,314 | 0.908 |\n| 32× | 36 | 18,648 | 0.847 | 9.2–22.1 | (25, 25) | 18,425 | 0.866 |\n| 16× | 71 | 36,778 | 0.764 | 8.9–13.6 | (40, 43) | 36,728 | 0.807 |\n| 8× | 142 | 73,556 | 0.634–0.635 | 7.5–8.6 | (60, 73) | 73,468 | 0.728 |\n| 4× | 285 | 147,630 | 0.452 | 6.0–8.0 | (99, 106) | 146,926 | 0.618 |\n| 2× | 569 | 294,742 | 0.233–0.234 | 4.0–4.5 | (145, 165) | 294,685 | 0.460 |\n:::\n:::\n\n\n::: {#cell-fig-matched-error .cell execution_count=9}\n``` {.python .cell-code}\nfig, (ax, bx) = plt.subplots(1, 2, figsize=(9, 3.8))\nax.fill_between(ratios, cp_sum.lo, cp_sum.hi, color=ACCENT, alpha=0.25, lw=0)\nax.plot(ratios, cp_sum.lo, \"o-\", color=ACCENT, label=\"CP\")\nax.plot(ratios, t2_best.rel_error.loc[ratios], \"s-\", color=CORAL, label=\"Tucker-2\")\nax.set_xscale(\"log\", base=2)\nax.set_xticks(ratios, [f\"{r}×\" for r in ratios])\nax.invert_xaxis()\nax.set_xlabel(\"compression (dense weights ÷ stored numbers)\")\nax.set_ylabel(r\"$\\|\\mathcal{K}-\\hat{\\mathcal{K}}\\|\\,/\\,\\|\\mathcal{K}\\|$\")\nax.legend(frameon=False)\nax.set_title(\"Weight error at matched budgets\")\n\nbx.fill_between(ratios, cp_sum.norm_lo, cp_sum.norm_hi, color=ACCENT, alpha=0.25, lw=0)\nbx.plot(ratios, cp_sum.norm_hi, \"o-\", color=ACCENT)\nbx.axhline(1, color=MUTED, ls=\"--\", lw=1)\nbx.set_yscale(\"log\")\nbx.set_xscale(\"log\", base=2)\nbx.set_xticks(ratios, [f\"{r}×\" for r in ratios])\nbx.invert_xaxis()\nbx.set_xlabel(\"compression\")\nbx.set_ylabel(r\"largest CP term $/\\ \\|\\mathcal{K}\\|$\")\nbx.set_title(\"CP's cancelling terms\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Left: relative Frobenius error of the ResNet-18 kernel against compression ratio, for CP (band: three random starts) and the best Tucker-2 rank pair at each budget. Right: CP's largest rank-one term relative to the kernel's norm, on a log scale; the dashed line marks the kernel's own norm.](index_files/figure-html/fig-matched-error-output-1.png){#fig-matched-error fig-alt='Two panels. On the left, both error curves fall as compression drops from 64 times to 2 times, and the CP curve sits below the Tucker-2 curve at every budget. On the right, CP\\'s largest term is many times the kernel\\'s norm at every budget, far above the dashed line at one.'}\n:::\n:::\n\n\nCP fits the kernel more closely than Tucker-2 at every budget.\n\n- At 8× compression CP's error is 0\\.634–0\\.635 against Tucker-2's\n  0\\.728. At 4× it is 0\\.452 against 0\\.618.\n- CP at 4× is about as close to the kernel as Tucker-2 at 2×:\n  0\\.452 against 0\\.460. Tucker-2 needs about twice the\n  numbers for the same error.\n- The three CP starts agree to within 0\\.0012 at every budget, so\n  the gap is not a lucky seed.\n- CP's error was still falling at 1,000 iterations, by up to 5\\.5e\\-04\n  over the last tenth of them. ALS with line search never raises the error, so more\n  iterations could only widen the gap.\n\nThe price is in the right panel. At every budget CP's largest term is between\n4\\.0 and 228\ntimes the norm of the kernel it helps approximate. CP reaches its low error by adding\nlarge terms that nearly cancel: the degeneracy [CP or Tucker](../cp-or-tucker/) warns\nabout, and what Phan et al. (2020) found in conv kernels generally. A 1% change to\none factor of a term 6 times the kernel's norm moves\nthe kernel by 6% of its norm: the fine-tuning\ninstability Lebedev et al. report.\n\n[CP or Tucker](../cp-or-tucker/) notes that storage separates the two only at fixed\nerror. On this kernel, at fixed error, CP needs about half the numbers, and gets them\nby cancellation rather than because the kernel is a short sum of rank-one terms.\n\n- **Choose CP** when the compression ratio is the target and the pipeline controls\n  degeneracy: a norm penalty, Phan et al.'s stability term, a low fine-tuning learning\n  rate, or frozen inserted layers, as Lebedev et al. suggest.\n- **Choose Tucker-2** when a well-conditioned start for fine-tuning matters more than\n  the last factor of two in storage.\n\n## Rank selection\n\n### HOSVD scree\n\nHOSVD gives one singular-value spectrum per mode. A scree plot reads the rank off\neach one.\n\n1. Unfold $\\mathcal{K}$ along mode $n$ into a $I_n\\times\\prod_{m\\ne n}I_m$ matrix.\n2. Take its singular values $\\sigma_{n,1}\\ge\\sigma_{n,2}\\ge\\cdots$.\n3. Plot them, and the retained energy\n   $E_n(R)=\\sum_{i\\le R}\\sigma_{n,i}^2/\\sum_i\\sigma_{n,i}^2$.\n4. Pick $R_n$ at the elbow, where the spectrum drops to a floor.\n\nThe truncation error is bounded by the energy thrown away (De Lathauwer et al. 2000):\n\n$$\n\\frac{\\|\\mathcal{K}-\\hat{\\mathcal{K}}\\|^2}{\\|\\mathcal{K}\\|^2}\\ \\le\\ \\sum_n\\big(1-E_n(R_n)\\big).\n$$\n\nSteps 1–3 in `tensorly` and PyTorch:\n\n::: {#scree .cell execution_count=10}\n``` {.python .cell-code code-fold=\"show\"}\nspectra = {n: torch.linalg.svdvals(torch.tensor(tl.unfold(K, n))) for n in range(4)}\nenergy = {n: s.square().cumsum(0) / s.square().sum() for n, s in spectra.items()}\n\n\ndef rank_at(n, share):\n    \"\"\"Smallest R_n whose retained energy reaches the share.\"\"\"\n    return int(torch.searchsorted(energy[n], torch.tensor(share, dtype=energy[n].dtype))) + 1\n```\n:::\n\n\n::: {#scree-bound .cell execution_count=11}\n``` {.python .cell-code}\nr90 = (rank_at(0, 0.90), rank_at(1, 0.90))\nr95 = (rank_at(0, 0.95), rank_at(1, 0.95))\nr50 = (rank_at(0, 0.50), rank_at(1, 0.50))\n\n\ndef t2_cost(ro, ri):\n    return C_out * ro + C_in * ri + kh * kw * ro * ri\n\n\n# HOSVD truncation at the 90% ranks, against the bound that guarantees it.\nU0 = np.linalg.svd(tl.unfold(K, 0), full_matrices=False)[0][:, : r90[0]]\nU1 = np.linalg.svd(tl.unfold(K, 1), full_matrices=False)[0][:, : r90[1]]\nK_90 = tl.tenalg.multi_mode_dot(K, [U0 @ U0.T, U1 @ U1.T], modes=[0, 1])\nerr_90 = np.linalg.norm(K - K_90) / K_norm\nlost = sum(1 - energy[n][r - 1].item() for n, r in zip((0, 1), r90))\nbound_90 = np.sqrt(lost)\nassert rank_at(2, 0.9) == rank_at(3, 0.9)  # the prose treats the spatial modes as one\n```\n:::\n\n\n::: {#cell-fig-scree .cell execution_count=12}\n``` {.python .cell-code}\nfig, (ax, bx) = plt.subplots(1, 2, figsize=(9, 3.6))\nidx = np.arange(1, C_out + 1)\nfor n, name, colour in [(0, \"out-channels\", ACCENT), (1, \"in-channels\", TEAL)]:\n    ax.plot(idx, (spectra[n] / spectra[n][0]).numpy(), color=colour, label=name)\n    bx.plot(idx, energy[n].numpy(), color=colour, label=name)\nax.set_yscale(\"log\")\nax.set_xlabel(\"index $i$\")\nax.set_ylabel(r\"$\\sigma_i / \\sigma_1$\")\nax.legend(frameon=False)\nax.set_title(\"No elbow\")\nfor share in (0.90, 0.95):\n    bx.axhline(share, color=MUTED, ls=\"--\", lw=1)\nbx.set_xlabel(\"rank $R_n$\")\nbx.set_ylabel(\"retained energy $E_n(R_n)$\")\nbx.set_title(\"Retained energy\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![HOSVD spectra of the ResNet-18 kernel's two channel modes. Left: singular values divided by the largest, log scale. Right: retained energy against rank, with 90% and 95% marked.](index_files/figure-html/fig-scree-output-1.png){#fig-scree fig-alt='Two panels. On the left, the singular values of the out-channel and in-channel unfoldings decay smoothly over all 256 indices with no visible elbow. On the right, both energy curves rise steadily and cross 90% only past index 150.'}\n:::\n:::\n\n\nThe kernel's spectra have no elbow.\n\n- Past the first few values, both channel spectra fall smoothly all the way to index\n  256. No index separates structure from a floor.\n- Half the energy needs $(R_o,R_i)=$ (46, 51). 90% needs\n  (165, 177), and 95% needs\n  (199, 209).\n- At the 90% ranks Tucker-2 stores 350\\,397 numbers, a\n  compression of 1\\.68×. The truncation error is\n  0\\.417, inside the bound's 0\\.445.\n- Both spatial modes need 3 of their 3 slices for 90%. That\n  is Kim et al.'s reason for leaving them whole, measured.\n\nA scree finds a rank when the tensor has one: a low-rank signal above a noise floor.\nA trained kernel spreads its energy over most of its channels, so the scree becomes an\nenergy budget, and the budget is a guess about accuracy after fine-tuning. Kim et al.\npick Tucker-2 ranks with global analytic VBMF (variational Bayesian matrix\nfactorization) on the two channel unfoldings instead, which sets the rank from a noise\nmodel rather than a threshold.\n\nOn the knowledge-graph tensor a scree says nothing. Its mode-1 unfolding is\n14\\,541 × 3\\,446\\,217, and its zeros are missing\nentries, not measured ones. Ranks there come from validation MRR.\n\n### Over-parameterise and prune\n\nGrid search does not scale to these models. Tucker-2 on this kernel alone has\n$256^2=65{,}536$ rank pairs, a full four-mode Tucker adds two more dials, and one CP-ALS\nstart at rank 285 took about\n9 minutes\nhere. The alternative is one fit with too many components and a penalty that switches\nwhole components off.\n\n#### Scale freedom\n\nCP has a scale freedom. Multiply the mode-$n$ column of term $r$ by $c_n>0$, with\n$\\prod_n c_n=1$, and the fit does not change. A penalty on the factors is therefore\nminimised over that freedom, and the AM–GM inequality says what it becomes:\n\n$$\n\\sum_{n=1}^{N}\\big\\|a^{(n)}_r\\big\\|_2\\ \\ge\\ N\\Big(\\prod_{n}\\big\\|a^{(n)}_r\\big\\|_2\\Big)^{1/N}=N\\,\\lambda_r^{1/N},\n$$\n\nwith equality when the $N$ norms are equal. Here $\\lambda_r$ is the Frobenius norm of\nterm $r$'s rank-one tensor.\n\n- **Group lasso** — the L2 norm of every column — charges term $r$ exactly\n  $N\\lambda_r^{1/N}$ at a balanced point. At $N=3$ that is a cube root: steepest at\n  zero, so small terms are pushed all the way to zero.\n- **Elementwise L1** gives the same bound in L1 norms. Since\n  $\\prod_n\\|a^{(n)}_r\\|_1=\\|a^{(1)}_r\\circ\\cdots\\circ a^{(N)}_r\\|_1$, it charges\n  $N\\|\\mathcal{T}_r\\|_1^{1/N}$ for term $\\mathcal{T}_r$, and it also zeroes entries\n  inside the terms that survive.\n- **Weight decay** — squared L2 — gives $N\\lambda_r^{2/N}$. For a matrix ($N=2$) that\n  is the nuclear norm. From $N=3$ on, the exponent is below one, so plain weight decay\n  prunes terms too.\n- **Lacroix et al.'s N3 penalty**, $\\sum_n\\|a^{(n)}_r\\|_3^3$, is the same construction\n  with the exponent chosen so that at $N=3$ it charges $3\\prod_n\\|a^{(n)}_r\\|_3$: linear\n  in term size, a tensor nuclear norm.\n\nEvery local minimum is balanced — otherwise rescaling would lower the penalty at no\ncost to the fit — so the bound is met there. An optimiser's iterates need not be\nbalanced, so the fits here rebalance after every step.\n\nTucker has no such reduction. Its freedom is an invertible matrix per mode,\n$U^{(n)}\\to U^{(n)}Q_n$ with $\\mathcal{G}\\to\\mathcal{G}\\times_nQ_n^{-1}$, not a scale\nper term. Group penalties on factor columns and the matching core slices are used for\nTucker, without the same one-line guarantee.\n\n#### Proximal steps\n\nA gradient step never lands on zero. Proximal gradient descent takes a gradient step\non the fit, then applies the penalty's proximal map, which can.\n\n- **Group lasso**: $a\\leftarrow a\\,\\max\\big(0,\\,1-\\eta\\mu/\\|a\\|_2\\big)$ for step\n  $\\eta$ and strength $\\mu$ — a whole column at once.\n- **L1**: soft-threshold each entry by $\\eta\\mu$.\n- **Weight decay** has no zeroing map. Its terms decay toward zero, and a term counts\n  as gone once $\\lambda_r<10^{-6}$ on a unit-norm tensor.\n- Adding any of the three penalties to the loss and running Adam gives no zeroing map\n  either, so it needs the same threshold on $\\lambda_r$ after training.\n\nThe two maps and the rebalancing step, as `src/prune.py` defines them:\n\n::: {#prune-code .cell execution_count=13}\n```python\ndef prox(factors, kind, step, strength):\n    \"\"\"Proximal map of the non-smooth penalties; weight decay stays in the gradient.\"\"\"\n    if kind == \"group\":\n        return [\n            f * (1 - step * strength / f.norm(dim=0).clamp_min(1e-300)).clamp(min=0)\n            for f in factors\n        ]\n    if kind == \"l1\":\n        return [f.sign() * (f.abs() - step * strength).clamp(min=0) for f in factors]\n    return factors\n\ndef rebalance(factors, kind):\n    \"\"\"Rescale each component's columns to equal norm; the product is unchanged.\n\n    A component with one all-zero column is zero already, so every column of it\n    is zeroed. Rescaling it instead would leave its other columns near 1e-100,\n    and arithmetic on numbers that small is slow.\n    \"\"\"\n    p = 1 if kind == \"l1\" else 2\n    norms = torch.stack([f.norm(p=p, dim=0) for f in factors])\n    dead = (norms == 0).any(0)\n    norms = norms.clamp_min(1e-300)\n    target = norms.log().mean(0).exp().masked_fill(dead, 0.0)\n    return [f * (target / n) for f, n in zip(factors, norms)]\n\n```\n:::\n\n\n#### Test tensor\n\nThe test tensor is synthetic, because grading a rank needs the true one.\n\n- **Generating process.** Six rank-one terms with Gaussian factors on a\n  60 × 50 × 40\n  grid, scaled to unit norm, plus Gaussian noise of norm 0.1 — a\n  signal-to-noise ratio of 20 dB.\n- **What it stands in for.** A tensor whose rank is unknown and whose noise floor is\n  real: a ratings cube, a sensor array, a batch of spectra.\n- **The fit.** Rank 30, five times too many, from a small\n  random start, 4\\,000 proximal steps with backtracking.\n- **Seeds.** Five; a seed changes both the tensor and the start.\n- **Sweep.** Seven strengths per penalty, from $10^{-5}$ to $10^{-2}$, plus an\n  unpenalised fit with the same rebalancing. `src/prune.py` runs it and caches it.\n\n::: {#prune-demo .cell execution_count=14}\n``` {.python .cell-code}\nclean, noisy, start = prune.make_problem(0)\ndemo_mu = 3e-4\ndemo = prune.fit(noisy, start, \"group\", demo_mu)\ndemo_lam = np.sort(prune.component_weights(demo).numpy())[::-1]\ndemo_alive = int((demo_lam > prune.ALIVE).sum())\ndemo_zero = int((demo_lam == 0).sum())\ndemo_err = (clean - prune.cp_tensor(demo)).norm().item()\n\nwd = prune.fit(noisy, start, \"wd\", 1e-3)\nwd_lam = np.sort(prune.component_weights(wd).numpy())[::-1]\nwd_alive = int((wd_lam > prune.ALIVE).sum())\nwd_dead = wd_lam[wd_alive]\n\n# The prose reads these outcomes; fail the render if a rerun changes them.\nassert demo_alive == wd_alive == prune.TRUE_RANK\nassert demo_zero == prune.FIT_RANK - demo_alive and wd_dead > 0\n```\n:::\n\n\nOne group-lasso fit at strength $\\mu$ = 0\\.0003 on seed 0 keeps\n6 of 30 terms. Their weights run from\n0\\.471 down to 0\\.329,\nand the other 24 are exactly zero. The fit sits 0\\.0086 from the noiseless tensor. Weight decay\nat $\\mu=10^{-3}$ on the same seed also keeps 6, but its largest\ndiscarded term is 4e\\-24, small rather than zero.\n\n::: {#cell-prune-sweep .cell execution_count=15}\n``` {.python .cell-code}\nruns = pd.concat(pd.read_csv(p) for p in sorted(DATA.glob(\"prune_*.csv\")))\nnames = {\"none\": \"none\", \"group\": \"group lasso\", \"l1\": \"elementwise L1\", \"wd\": \"weight decay\"}\nsummary = (\n    runs.groupby([\"kind\", \"strength\"])\n    .agg(\n        lo=(\"alive\", \"min\"),\n        hi=(\"alive\", \"max\"),\n        err=(\"error_to_truth\", \"median\"),\n    )\n    .reset_index()\n)\nbaseline = summary[summary.kind == \"none\"].iloc[0]\nexact = summary[(summary.lo == 6) & (summary.hi == 6)]\nwindow = {\n    k: (g.strength.min(), g.strength.max(), g.err.min()) for k, g in exact.groupby(\"kind\")\n}\ntoo_strong = {\n    k: g.sort_values(\"strength\").iloc[0]\n    for k, g in summary[(summary.kind != \"none\") & (summary.lo < prune.TRUE_RANK)].groupby(\"kind\")\n}\n# The prose names these outcomes; fail the render if a rerun changes them.\nassert set(window) == {\"group\", \"l1\", \"wd\"}\nassert set(too_strong) == {\"group\", \"l1\"}\n\n\ndef mu(k, end):\n    return f\"{window[k][end]:g}\"\n\nwide = summary[summary.kind != \"none\"].copy()\nwide[\"cell\"] = [\n    (f\"{lo}\" if lo == hi else f\"{lo}–{hi}\") + f\" · {e:.4f}\"\n    for lo, hi, e in zip(wide.lo, wide.hi, wide.err)\n]\ngrid = wide.pivot(index=\"strength\", columns=\"kind\", values=\"cell\")[[\"group\", \"l1\", \"wd\"]]\ngrid.columns = [names[c] for c in grid.columns]\ngrid.insert(0, \"strength $\\\\mu$\", [f\"{m:g}\" for m in grid.index])\nmd_table(grid)\n```\n\n::: {#prune-sweep .cell-output .cell-output-display .cell-output-markdown execution_count=15}\n| strength $\\mu$ | group lasso | elementwise L1 | weight decay |\n|---|---|---|---|\n| 1e-05 | 30 · 0.0222 | 12–21 · 0.0097 | 30 · 0.0231 |\n| 3e-05 | 27–29 · 0.0165 | 6–7 · 0.0086 | 30 · 0.0221 |\n| 0.0001 | 6–8 · 0.0088 | 6 · 0.0094 | 30 · 0.0174 |\n| 0.0003 | 6 · 0.0086 | 6 · 0.0154 | 7–10 · 0.0087 |\n| 0.001 | 6 · 0.0095 | 5–6 · 0.3156 | 6 · 0.0107 |\n| 0.003 | 6 · 0.0164 | 0–1 · 1.0000 | 6 · 0.0220 |\n| 0.01 | 0–3 · 0.7998 | 0 · 1.0000 | 6 · 0.0690 |\n:::\n:::\n\n\nEach cell gives the terms left across five seeds (a range where seeds disagree) and\nthe median distance to the noiseless tensor. Without a penalty all\n30 terms survive and the fit sits\n0\\.0232 from the truth, because the spare terms fit noise.\n\n- **All three penalties find the rank.** Each has a range of strengths that leaves\n  exactly six terms on all five seeds: group lasso from 0\\.0003 to\n  0\\.003, elementwise L1 from 0\\.0001 to\n  0\\.0003, and weight decay from 0\\.001 to\n  0\\.01.\n- **Pruning also denoises.** At its best strength, each penalty lands closer to the\n  noiseless tensor than the unpenalised fit: 0\\.0086,\n  0\\.0094 and 0\\.0107 against\n  0\\.0232. The spare terms were fitting noise.\n- **Too weak keeps spares; too strong cuts true terms.** Group lasso at\n  0\\.01 and L1 at\n  0\\.001 drop below six on some seeds, and the\n  median distance to the truth jumps to 0\\.80 and\n  0\\.32. Weight decay still keeps six at the top of\n  the grid.\n- **Inside the range the penalty still shrinks the survivors**, so the error climbs\n  toward the top of it. Refitting at the found rank with no penalty removes that\n  shrinkage; it is the usual last step, and not measured here.\n- **Weight decay prunes without a zeroing map**, as the $\\lambda_r^{2/3}$ bound\n  predicts for three modes.\n\nThe range moves with the penalty's scale and with the noise, so on a real tensor it\nis found against held-out entries: one sweep over a single strength in place of one\nover ranks.\n\n## Decision matrix\n\n| | CP | Tucker (HOSVD to initialise and to read ranks) |\n|---|---|---|\n| Core | Superdiagonal: component $r$ meets only component $r$ | Dense: any component meets any other |\n| Goal it serves | Interpretable parts; the lowest weight error per stored number, if degeneracy is controlled | Asymmetric relations through one shared core; a well-conditioned compressed layer |\n| Uniqueness | Unique up to order and scale under Kruskal's condition | A subspace per mode; factors fixed only up to rotation |\n| Numbers, 256×256×3×3 kernel | $518R$ | $512R+9R^2$ (square Tucker-2) |\n| Numbers, FB15k-237 at published size | 118\\.2M (CP-N3) | 11\\.0M (TuckER) |\n| Overfitting risk | Linear in $R$, but entity tables dominate: CP-N3 carries 434 numbers per training triple and leans on its N3 penalty | Core grows as $\\prod_n R_n$; TuckER carries 40 per training triple |\n| Rank selection | No spectrum to read; over-parameterise and prune with a factor penalty | HOSVD scree when a gap exists; otherwise an energy budget or VBMF |\n| Typical failure | Rank-one terms many times the tensor's norm, cancelling | A core that eats the budget before the factors can |\n\n## Constraints\n\n- **Weight error is not accuracy.** Lebedev et al. and Kim et al. both fine-tune after\n  decomposing. Kim et al. report VGG-16 at 4.93× fewer FLOPs for a 0.5-point top-5\n  loss once fine-tuned. The weight error measured here ignores the input activations and the batch norm after the\n  layer.\n- **Multiply-adds track parameters only at stride 1.** Wall-clock time can reverse the\n  ranking: the 3×1 and 1×3 depthwise steps do little arithmetic per byte they move.\n- **CP degeneracy.** Lebedev et al. report that gradients inside the inserted layers\n  \"are prone to gradient explosion\". Phan et al. (2020) trace it to \"extremely large\n  rank-one tensors but canceling each other\" and add a penalty against it. The largest\n  term relative to $\\|\\mathcal{K}\\|$ is the check.\n- **Kruskal's condition runs out.** For an $N$-way array it needs\n  $\\sum_n k_n\\ge2R+N-1$ (Sidiropoulos and Bro 2000). With generic factors on this\n  kernel that is $518\\ge2R+3$, which fails past $R=257$. The 4× and 2× CP fits sit\n  past it, so their components carry no uniqueness guarantee.\n- **Tucker's core is exponential in $N$.** At eight modes with $R_n=10$ the core alone\n  is $10^8$ numbers.\n- **The knowledge-graph verdict rests on published sizes.** Each paper tuned its own\n  embedding size, and none of the quoted tables reports CP-N3 at TuckER's parameter\n  count.\n\nSymmetry. Rarely. Bites. Tucker. Saves. Parameters. CP. Compresses. Unstably. Penalties. Prune.\n\n## References\n\n- Balažević, I., Allen, C., and Hospedales, T. (2019).\n  [TuckER: Tensor factorization for knowledge graph completion](https://arxiv.org/abs/1901.09590).\n  *EMNLP*. The shared-core model, its special cases, and its FB15k-237 table.\n- Bordes, A., Usunier, N., García-Durán, A., Weston, J., and Yakhnenko, O. (2013).\n  [Translating embeddings for modeling multi-relational data](https://proceedings.neurips.cc/paper/2013/hash/1cecc7a77928ca8133fa24680a88d2f9-Abstract.html).\n  *NeurIPS*. FB15k.\n- De Lathauwer, L., De Moor, B., and Vandewalle, J. (2000).\n  [A multilinear singular value decomposition](https://doi.org/10.1137/S0895479896305696).\n  *SIAM Journal on Matrix Analysis and Applications* 21(4). HOSVD and its truncation\n  bound.\n- He, K., Zhang, X., Ren, S., and Sun, J. (2016).\n  [Deep residual learning for image recognition](https://arxiv.org/abs/1512.03385).\n  *CVPR*. ResNet-18.\n- Kim, Y.-D., Park, E., Yoo, S., Choi, T., Yang, L., and Shin, D. (2016).\n  [Compression of deep convolutional neural networks for fast and low power mobile applications](https://arxiv.org/abs/1511.06530).\n  *ICLR*. Tucker-2 conv compression with VBMF ranks.\n- Kossaifi, J., Panagakis, Y., Anandkumar, A., and Pantic, M. (2019).\n  [TensorLy: Tensor learning in Python](https://jmlr.org/papers/v20/18-277.html).\n  *JMLR* 20.\n- Lacroix, T., Usunier, N., and Obozinski, G. (2018).\n  [Canonical tensor decomposition for knowledge base completion](https://arxiv.org/abs/1806.07297).\n  *ICML*. CP-N3, ComplEx-N3, reciprocal relations.\n- Lebedev, V., Ganin, Y., Rakhuba, M., Oseledets, I., and Lempitsky, V. (2015).\n  [Speeding-up convolutional neural networks using fine-tuned CP-decomposition](https://arxiv.org/abs/1412.6553).\n  *ICLR*. CP as four convolutions.\n- Nickel, M., Tresp, V., and Kriegel, H.-P. (2011).\n  [A three-way model for collective learning on multi-relational data](https://icml.cc/2011/papers/438_icmlpaper.pdf).\n  *ICML*. RESCAL.\n- Phan, A.-H., Sobolev, K., Sozykin, K., Ermilov, D., Gusak, J., Tichavský, P.,\n  Glukhov, V., Oseledets, I., and Cichocki, A. (2020).\n  [Stable low-rank tensor decomposition for compression of convolutional neural network](https://arxiv.org/abs/2008.05441).\n  *ECCV*. CP degeneracy in conv kernels.\n- Rendle, S., Freudenthaler, C., Gantner, Z., and Schmidt-Thieme, L. (2009).\n  [BPR: Bayesian personalized ranking from implicit feedback](https://arxiv.org/abs/1205.2618).\n  *UAI*.\n- Ruffinelli, D., Broscheit, S., and Gemulla, R. (2020).\n  [You CAN teach an old dog new tricks! On training knowledge graph embeddings](https://openreview.net/forum?id=BkxSmlBFvr).\n  *ICLR*. Re-tuned baselines; the MRRs quoted are from the\n  [LibKGE results table](https://github.com/uma-pi1/kge).\n- Sidiropoulos, N. D., and Bro, R. (2000).\n  [On the uniqueness of multilinear decomposition of N-way arrays](<https://analyticalsciencejournals.onlinelibrary.wiley.com/doi/abs/10.1002/1099-128X(200005/06)14:3%3C229::AID-CEM587%3E3.0.CO;2-N>).\n  *Journal of Chemometrics* 14(3). Kruskal's condition for $N$ modes.\n- Toutanova, K., and Chen, D. (2015).\n  [Observed versus latent features for knowledge base and text inference](https://aclanthology.org/W15-4007/).\n  *Workshop on Continuous Vector Space Models and their Compositionality*. FB15k-237.\n- Trouillon, T., Welbl, J., Riedel, S., Gaussier, É., and Bouchard, G. (2016).\n  [Complex embeddings for simple link prediction](https://arxiv.org/abs/1606.06357).\n  *ICML*. ComplEx.\n- Yang, B., Yih, W., He, X., Gao, J., and Deng, L. (2015).\n  [Embedding entities and relations for learning and inference in knowledge bases](https://arxiv.org/abs/1412.6575).\n  *ICLR*. DistMult.\n- [CP or Tucker](../cp-or-tucker/) — uniqueness, rotational freedom and storage for\n  the two models.\n- [Uses of Tensor Factorizations](../uses-of-tensor-factorizations/) — the CP\n  conv chain on a synthetic kernel, and compression of video and audio.\n- [Tensor Factorizations and Tensor Inverses](../tensor-factorizations/) — the\n  algebra for general $N$, including HOSVD and HOOI.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}