{
  "hash": "66cf78d4611711e62be13ac2ce9bcbd8",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Calibrated Decisions, Part 2: Calibration and Proper Scoring Rules\"\nsubtitle: \"What it means for a probability to be right, how to measure it, and which losses reward honest probabilities\"\ndescription: \"Calibration is a property of predictive probabilities, separate from accuracy and from the procedure that fitted them. Definitions, reliability diagrams, ECE and its bias, proper scoring rules from Brier to CRPS, why maximum likelihood alone does not deliver calibration, and what TypeSafe's RLCD could and could not add.\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-09-27T11:00:00\"\ncategories: [Statistics, Machine Learning, LLMs]\nimage: \"./cover.png\"\ntags: [calibration, proper scoring rules, brier score, log loss, reliability diagram, expected calibration error, maximum likelihood, RLHF, RLVR, RLCD, Jev]\njupyter: calibration-blog\nresources:\n  - widgets.js\n  - requirements.txt\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    number-sections: true\n    css: post.css\nexecute:\n  warning: false\n---\n\n\n![Calibrated Decisions, Part 2: Calibration and Proper Scoring Rules](./cover.png)\n\nA forecast of 70% rain cannot be wrong on one day: it rains or it does not. It can be wrong over a season, if it rained on far more or far fewer than 70% of the days that got that forecast. That season-long check is calibration, and a decision model's probabilities need to pass it before software can act on them.\n\n[Part 1](../jev-system-one-model/) described Jev, TypeSafe's model that answers typed questions with probabilities, and TypeSafe's claim that those probabilities are calibrated. This part defines calibration, measures it, and sets out the scoring rules that reward it. Those are the tools for judging the claim, and for asking what TypeSafe's training method, RLCD, could add to ordinary maximum likelihood. [Part 3](../recalibration-and-decisions/) repairs miscalibration on your own data and turns calibrated probabilities into decisions.\n\nStatements about Jev carry a label. [vendor]{.tag-vendor} means documented by TypeSafe. [theory]{.tag-theory} means standard statistics. [inference]{.tag-inference} means our reading of documented facts. [speculation]{.tag-spec} means a hypothesis about undisclosed internals.\n\n\n\n## Data\n\nAll data in this part is synthetic. One generating process stands in for a labelled evaluation set for a yes/no question, such as a Noul asking \"Does this message request a refund?\" over tickets whose true answer is known:\n\n$$\nX \\sim N(0, 1), \\qquad p^*(x) = \\sigma(2x), \\qquad Y \\mid X = x \\sim \\operatorname{Bernoulli}\\big(p^*(x)\\big).\n$$\n\n- $x$ plays the role of the evidence in one ticket, and $p^*(x)$ is the true probability that the answer is yes.\n- Simulation fixes $p^*$, so a forecaster's error can be measured against the truth instead of only estimated from labels.\n- A wrong answer here has a price: a model that says 0.96 on cases that are yes 84% of the time automates decisions it should escalate.\n\nMiscalibrated forecasters are built by distorting the true probability on the logit scale:\n\n$$\n\\hat p_\\alpha(x) = \\sigma\\big(\\alpha \\operatorname{logit} p^*(x)\\big).\n$$\n\n$\\alpha > 1$ pushes every probability away from 0.5 (overconfident); $\\alpha < 1$ pulls it toward 0.5 (underconfident); $\\alpha = 1$ is the truth.\n\n::: {#helpers .cell execution_count=2}\n``` {.python .cell-code}\ndef draw(rng, n, slope=2.0):\n    \"\"\"X ~ N(0, 1), p*(x) = sigmoid(slope * x), Y ~ Bernoulli(p*).\"\"\"\n    x = rng.standard_normal(n)\n    p_star = expit(slope * x)\n    y = (rng.random(n) < p_star).astype(float)\n    return x, p_star, y\n\n\ndef distort(p, alpha):\n    \"\"\"sigmoid(alpha * logit(p)): alpha > 1 is overconfident, alpha < 1 underconfident.\"\"\"\n    return expit(alpha * logit(p))\n\n\ndef brier(p, y):\n    return np.mean((p - y) ** 2)\n\n\ndef log_loss(p, y):\n    p = np.clip(p, EPS, 1 - EPS)\n    return -np.mean(y * np.log(p) + (1 - y) * np.log(1 - p))\n\n\ndef ece(p, y, m=15):\n    \"\"\"Binned ECE with m equal-width bins on the positive-class probability.\"\"\"\n    idx = np.minimum((p * m).astype(int), m - 1)\n    gap = sum(np.sum(idx == b) * abs(y[idx == b].mean() - p[idx == b].mean()) for b in np.unique(idx))\n    return gap / len(p)\n\n\ndef murphy(p, y, m=10):\n    \"\"\"Reliability, resolution and uncertainty on m equal-count bins of the forecast.\"\"\"\n    if np.unique(p).size <= m:\n        groups = [np.flatnonzero(p == v) for v in np.unique(p)]\n    else:\n        groups = np.array_split(np.argsort(p, kind=\"stable\"), m)\n    ybar = y.mean()\n    rel = sum(len(g) * (p[g].mean() - y[g].mean()) ** 2 for g in groups) / len(p)\n    res = sum(len(g) * (y[g].mean() - ybar) ** 2 for g in groups) / len(p)\n    return rel, res, ybar * (1 - ybar)\n\n\ndef reliability_bins(p, y, m=10):\n    \"\"\"Mean forecast, event frequency and count in m equal-width bins.\"\"\"\n    idx = np.minimum((p * m).astype(int), m - 1)\n    rows = [(p[idx == b].mean(), y[idx == b].mean(), np.sum(idx == b)) for b in np.unique(idx)]\n    return np.array(rows).T\n\n\ndef summary(a, d=3):\n    a = np.asarray(a)\n    return f\"{np.median(a):.{d}f} [{np.quantile(a, 0.05):.{d}f}, {np.quantile(a, 0.95):.{d}f}]\"\n\n\ndef cell(a, d=3):\n    \"\"\"Median over seeds, with the 5-95% interval on a second, smaller line.\"\"\"\n    a = np.asarray(a)\n    lo, hi = np.quantile(a, [0.05, 0.95])\n    return f\"{np.median(a):.{d}f}<br><span class='rng'>{lo:.{d}f}–{hi:.{d}f}</span>\"\n\n\ndef md_table(df):\n    return Markdown(df.to_markdown(index=False, disable_numparse=True))\n```\n:::\n\n\n## Calibration\n\nA binary forecaster outputs $\\hat p(X) = P_\\theta(Y = 1 \\mid X)$. It is calibrated when\n\n$$\nP\\big(Y = 1 \\mid \\hat p(X) = p\\big) = p \\quad \\text{for every } p \\text{ it outputs}.\n$$\n\nAmong the cases that receive 0.8, about 80% are positive; among the cases that receive 0.1, about 10% are.\n\n- The condition is on the forecast value, not on the input. Two inputs with the same $\\hat p$ are pooled, however different they are.\n- It is a statement about groups of predictions. TypeSafe's own documentation says the same about Jev: \"Calibration is measured across groups of predictions; it does not guarantee that an individual answer is correct.\" [vendor]{.tag-vendor}\n\n::: {#tbl-reliability .cell tbl-cap='Mean forecast and observed frequency of $Y = 1$ in five equal-width bins, one sample of 200,000 cases. The calibrated forecaster is $\\hat p_1 = p^*$; the overconfident one is $\\hat p_{2.5}$.' execution_count=3}\n``` {.python .cell-code}\nx, p_star, y = draw(np.random.default_rng(0), 200_000)\nrows = []\nedges = np.linspace(0, 1, 6)\nfor lo, hi in zip(edges[:-1], edges[1:]):\n    row = {\"Bin\": f\"[{lo:.1f}, {hi:.1f})\"}\n    for name, alpha in ((\"Calibrated\", 1.0), (\"Overconfident\", 2.5)):\n        p = distort(p_star, alpha)\n        s = (p >= lo) & (p < hi)\n        row[f\"{name}: mean forecast\"] = f\"{p[s].mean():.3f}\"\n        row[f\"{name}: frequency\"] = f\"{y[s].mean():.3f}\"\n    rows.append(row)\nmd_table(pd.DataFrame(rows))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=3}\n| Bin        | Calibrated: mean forecast   | Calibrated: frequency   | Overconfident: mean forecast   | Overconfident: frequency   |\n|:-----------|:----------------------------|:------------------------|:-------------------------------|:---------------------------|\n| [0.0, 0.2) | 0.093                       | 0.094                   | 0.040                          | 0.163                      |\n| [0.2, 0.4) | 0.297                       | 0.297                   | 0.294                          | 0.410                      |\n| [0.4, 0.6) | 0.499                       | 0.500                   | 0.500                          | 0.502                      |\n| [0.6, 0.8) | 0.703                       | 0.703                   | 0.706                          | 0.587                      |\n| [0.8, 1.0) | 0.907                       | 0.907                   | 0.960                          | 0.837                      |\n:::\n:::\n\n\n\n\nIn the top bin the overconfident forecaster averages 0\\.96 while the event happens 0\\.84 of the time. A threshold of 0.9 on its output automates cases whose forecasts average 0\\.98, so they should be wrong about 2% of the time. They are wrong 13% of the time.\n\n### Multiclass calibration\n\nA Choice answer is a probability vector $\\hat{\\mathbf p}(X)$ over $K$ options. Three definitions are in use [theory]{.tag-theory}:\n\n1. **Canonical:** $P\\big(Y = k \\mid \\hat{\\mathbf p}(X) = \\mathbf p\\big) = p_k$ for every $k$ and every vector $\\mathbf p$.\n2. **Classwise:** $P\\big(Y = k \\mid \\hat p_k(X) = c\\big) = c$ for every $k$.\n3. **Top-label:** $P\\big(Y = \\hat y \\mid \\max_k \\hat p_k(X) = c\\big) = c$, where $\\hat y$ is the arg max.\n\nCanonical calibration implies the other two, which do not imply each other. Vaicenavicius et al. (2019) give an example where both of the weaker conditions hold and canonical calibration fails. Machine learning papers usually call $\\max_k \\hat p_k$ the \"confidence\" and check top-label calibration (Guo et al. 2017). TypeSafe's `confidence` field is a different number: a statistic of the spread of the distribution, discussed in Part 1. This series writes $p_{\\max}$ for the largest probability.\n\n### Calibration and accuracy\n\nA monotone distortion moves probabilities without changing which side of 0.5 they fall on, or the order of any two cases. Accuracy at 0.5 and AUC therefore cannot see it.\n\n::: {#tbl-metrics .cell tbl-cap='Four forecasters on the same data, $n = 5{,}000$ per seed, 200 seeds: median, and the 5–95% interval beneath it. REL and RES are the Murphy reliability and resolution terms on ten equal-count bins.' execution_count=5}\n``` {.python .cell-code}\nforecasters = {\"Calibrated\": 1.0, \"Overconfident α = 2.5\": 2.5, \"Underconfident α = 0.4\": 0.4, \"Base rate\": None}\nmetric_names = [\"Accuracy\", \"AUC\", \"Brier\", \"Log loss\", \"ECE\", \"REL\", \"RES\"]\nruns = {f: {m: [] for m in metric_names} for f in forecasters}\nfor r in range(R):\n    x, p_star, y = draw(np.random.default_rng(1000 + r), 5000)\n    for name, alpha in forecasters.items():\n        p = np.full_like(p_star, y.mean()) if alpha is None else distort(p_star, alpha)\n        rel, res, _ = murphy(p, y)\n        vals = [np.mean((p > 0.5) == y), roc_auc_score(y, p) if alpha else 0.5, brier(p, y), log_loss(p, y), ece(p, y), rel, res]\n        for m, v in zip(metric_names, vals):\n            runs[name][m].append(v)\ntable = pd.DataFrame({\"Metric\": metric_names} | {f: [cell(runs[f][m]) for m in metric_names] for f in forecasters})\nmd_table(table)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=5}\n| Metric   | Calibrated                                    | Overconfident α = 2.5                         | Underconfident α = 0.4                        | Base rate                                     |\n|:---------|:----------------------------------------------|:----------------------------------------------|:----------------------------------------------|:----------------------------------------------|\n| Accuracy | 0.778<br><span class='rng'>0.768–0.786</span> | 0.778<br><span class='rng'>0.768–0.786</span> | 0.778<br><span class='rng'>0.768–0.786</span> | 0.505<br><span class='rng'>0.500–0.514</span> |\n| AUC      | 0.862<br><span class='rng'>0.854–0.870</span> | 0.862<br><span class='rng'>0.854–0.870</span> | 0.862<br><span class='rng'>0.854–0.870</span> | 0.500<br><span class='rng'>0.500–0.500</span> |\n| Brier    | 0.151<br><span class='rng'>0.147–0.156</span> | 0.168<br><span class='rng'>0.162–0.175</span> | 0.172<br><span class='rng'>0.170–0.175</span> | 0.250<br><span class='rng'>0.250–0.250</span> |\n| Log loss | 0.461<br><span class='rng'>0.450–0.475</span> | 0.598<br><span class='rng'>0.573–0.625</span> | 0.525<br><span class='rng'>0.520–0.532</span> | 0.693<br><span class='rng'>0.693–0.693</span> |\n| ECE      | 0.016<br><span class='rng'>0.012–0.022</span> | 0.118<br><span class='rng'>0.110–0.126</span> | 0.131<br><span class='rng'>0.123–0.140</span> | 0.000<br><span class='rng'>0.000–0.000</span> |\n| REL      | 0.000<br><span class='rng'>0.000–0.001</span> | 0.017<br><span class='rng'>0.015–0.020</span> | 0.021<br><span class='rng'>0.019–0.023</span> | 0.000<br><span class='rng'>0.000–0.000</span> |\n| RES      | 0.098<br><span class='rng'>0.094–0.103</span> | 0.098<br><span class='rng'>0.094–0.103</span> | 0.098<br><span class='rng'>0.094–0.103</span> | 0.000<br><span class='rng'>0.000–0.000</span> |\n:::\n:::\n\n\n\n\n- Accuracy and AUC are identical, seed by seed, for the three distorted forecasters (true on all 200 seeds). Brier, log loss and ECE all separate them.\n- The base-rate forecaster gives every case the sample's base rate, about one half here, and is perfectly calibrated: its ECE is 0\\.000. It is also useless, with accuracy 0\\.50 and AUC 0.5.\n- A lower-accuracy forecaster can therefore be better calibrated than a higher-accuracy one. Calibration and discrimination are separate axes.\n\n::: {.callout-caution title=\"Common misconception\"}\n\"The model is 95% accurate, so its probabilities are trustworthy.\" Accuracy counts how often the arg max is right. Calibration asks whether the stated probability matches the frequency. A model can be 95% accurate and still say 0.999 on the 5% it gets wrong.\n:::\n\n### Calibration and uncertainty quantification\n\nCalibration is one property of a predictive distribution. It leaves open the questions a full uncertainty analysis asks [theory]{.tag-theory}:\n\n- **Individual correctness.** A calibrated 0.8 is wrong one time in five, and calibration does not say which time.\n- **Sharpness.** The base-rate forecaster is calibrated and says nothing. Gneiting, Balabdaoui & Raftery (2007) frame the goal as maximising sharpness subject to calibration.\n- **Conditional validity.** Calibration pools every case with the same forecast. It can hold on average while failing in every subgroup, which Part 3 demonstrates.\n- **Source of uncertainty.** A calibrated probability does not separate noise in the outcome (aleatoric) from ignorance about the model (epistemic).\n- **Shift.** Calibration is measured on one distribution. It is not a property the model carries to new data.\n\n### Thresholds\n\nSoftware turns a probability into an action with thresholds:\n\n```python\nif p > 0.99:\n    execute_automatically()\nelif p > 0.80:\n    cheap_secondary_check()\nelse:\n    human_review()\n```\n\n- The 0.99 line means \"automate when the error rate is below 1%\" only if $P(Y = 1 \\mid \\hat p > 0.99)$ is at least 0.99. That is a calibration statement.\n- An overconfident model sends more cases over the line than the line was designed for. Part 3 prices the damage.\n\n::: {.callout-note title=\"Statistical subtlety\"}\nTypeSafe's launch post says Jev is \"Calibrated: higher confidence means higher accuracy.\" [vendor]{.tag-vendor} The second half describes monotonicity: accuracy rises with the score. Monotonicity is weaker than calibration. The $\\alpha = 2.5$ forecaster is perfectly monotone and still says 0.96 where the frequency is 0.84. TypeSafe's AI primer states the stronger property (\"Outcomes assigned a probability of `0.8` should occur about 80% of the time\"), which is the one thresholds need. [vendor]{.tag-vendor}\n:::\n\n## Maximum likelihood, MAP and calibration\n\nMaximum likelihood (MLE) and maximum a posteriori (MAP) estimation are procedures for choosing parameters:\n\n$$\n\\hat\\theta_{\\mathrm{MLE}} = \\arg\\max_\\theta \\sum_{i=1}^n \\log p_\\theta(y_i \\mid x_i),\n\\qquad\n\\hat\\theta_{\\mathrm{MAP}} = \\arg\\max_\\theta \\left[\\sum_{i=1}^n \\log p_\\theta(y_i \\mid x_i) + \\log p(\\theta)\\right].\n$$\n\nCalibration is a property of the probabilities the fitted model then produces: $P(Y = 1 \\mid \\hat p = p) = p$. A procedure and a property are different kinds of object, so neither implies the other by definition.\n\n### Log loss as a proper scoring rule\n\nThe negative log likelihood is the log loss, and the log loss is a strictly proper scoring rule [theory]{.tag-theory}. Its expectation is minimised only by the true conditional probability. Under four idealisations, minimising it recovers $p^*$ and therefore calibration:\n\n1. infinite data, so the empirical loss equals the expected loss;\n2. a correctly specified model family that contains $p^*$;\n3. an optimiser that finds the global minimum;\n4. test data drawn from the training distribution.\n\n### Sources of miscalibration in MLE-trained models\n\nEach idealisation fails in practice, and each failure has a known effect:\n\n- **Finite samples and overparameterisation.** Coefficients are fitted to noise, and the fitted logits come out too large.\n- **Misspecification.** The best model in a wrong family is the one closest to $p^*$ in KL divergence, which need not be calibrated.\n- **Regularisation and MAP.** A prior shrinks logits toward zero and can leave a model underconfident.\n- **Optimisation effects.** Early stopping, learning-rate schedules and label smoothing all change the final logit scale.\n- **Dataset shift.** Calibration on the training distribution says nothing about a new one.\n- **Class imbalance, label noise and model selection.** Resampling changes base rates; noisy labels change what \"true\" means; choosing the model with the best validation accuracy selects on a quantity that ignores calibration.\n\nGuo et al. (2017) documented the effect in deep networks: modern architectures trained with the log loss were markedly overconfident, and a single temperature fitted on held-out data repaired most of it.\n\n### Example: high-dimensional logistic regression\n\nLogistic regression is the cleanest case. With an intercept, the MLE score equations force\n\n$$\n\\sum_{i=1}^n \\big(y_i - \\hat p(x_i)\\big) = 0\n$$\n\non the training data. The mean forecast equals the base rate there, whatever else goes wrong.\n\nThe experiment fits an unpenalised logistic regression by Newton's method to $n = 1{,}000$ cases with $d = 200$ features. Only the first feature matters (true logit $2x_1$); the other 199 are noise. Sur & Candès (2019) showed that when $d/n$ is not small, the MLE inflates coefficients, so its probabilities come out too extreme; in their example at $d/n = 0.2$ the estimates average about 1.5 times the true values.\n\n::: {#mle .cell execution_count=7}\n``` {.python .cell-code}\nn_train, d, n_test = 1000, 200, 20_000\nmle = {k: [] for k in (\"citl\", \"ece_train\", \"ece_test\", \"slope\", \"ll_test\", \"ll_true\")}\nfailed = 0\nfor r in range(R):\n    rng = np.random.default_rng(9000 + r)\n    X = rng.standard_normal((n_train, d))\n    y = (rng.random(n_train) < expit(2 * X[:, 0])).astype(float)\n    fit = sm.Logit(y, sm.add_constant(X)).fit(disp=0, maxiter=100)\n    if not fit.mle_retvals[\"converged\"]:\n        failed += 1\n        continue\n    p_train = fit.predict(sm.add_constant(X))\n    Xt = rng.standard_normal((n_test, d))\n    p_true = expit(2 * Xt[:, 0])\n    yt = (rng.random(n_test) < p_true).astype(float)\n    p_test = fit.predict(sm.add_constant(Xt))\n    slope = sm.Logit(yt, sm.add_constant(logit(np.clip(p_test, 1e-12, 1 - 1e-12)))).fit(disp=0).params[1]\n    mle[\"citl\"].append(abs(np.sum(y - p_train)))\n    mle[\"ece_train\"].append(ece(p_train, y))\n    mle[\"ece_test\"].append(ece(p_test, yt))\n    mle[\"slope\"].append(slope)\n    mle[\"ll_test\"].append(log_loss(p_test, yt))\n    mle[\"ll_true\"].append(log_loss(p_true, yt))\n    if r == 0:\n        example = (p_train, y, p_test, yt)\n```\n:::\n\n\n::: {#cell-fig-mle .cell execution_count=8}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(7.2, 3.4), sharey=True)\nfor ax, (p, yy, title) in zip(axes, [(example[0], example[1], \"Training data\"), (example[2], example[3], \"Test data\")]):\n    mp, fr, cnt = reliability_bins(p, yy)\n    ax.plot([0, 1], [0, 1], color=MUTED, lw=1, ls=\"--\", label=\"calibrated\")\n    ax.plot(mp, fr, color=PURPLE, lw=1.2)\n    ax.scatter(mp, fr, s=400 * cnt / cnt.sum() + 8, color=PURPLE, zorder=3, label=\"binned frequency\")\n    ax.set(title=title, xlabel=\"Forecast probability\", xlim=(0, 1), ylim=(0, 1))\n    ax.set_aspect(\"equal\")\naxes[0].set_ylabel(\"Observed frequency of Y = 1\")\naxes[0].legend(frameon=False, loc=\"upper left\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![One seed of the high-dimensional logistic regression. Left: on its 1,000 training cases the MLE looks calibrated. Right: on 20,000 fresh cases its high forecasts are too high and its low forecasts too low. Dot area is proportional to the number of cases in the bin.](index_files/figure-html/fig-mle-output-1.png){#fig-mle}\n:::\n:::\n\n\nOver 200 converged seeds:\n\n- On training data, $\\big|\\sum_i (y_i - \\hat p_i)\\big|$ is at most 2e\\-14: calibration in the large holds to solver precision.\n- Training ECE is 0\\.031 \\[0\\.022\\, 0\\.042\\]. Test ECE is 0\\.138 \\[0\\.118\\, 0\\.163\\].\n- Regressing test outcomes on the model's test logit gives a calibration slope of 0\\.39 \\[0\\.32\\, 0\\.45\\]. A slope below 1 means the logits are too large, which is overconfidence.\n- Test log loss is 0\\.691 \\[0\\.638\\, 0\\.777\\] against 0\\.462 \\[0\\.456\\, 0\\.468\\] for the true probabilities.\n\nThe training-set number is close to the noise floor of a perfectly calibrated forecaster at $n = 1{,}000$ (@sec-ece). Evaluating calibration on the data the model was fitted to hides the defect.\n\n## Proper scoring rules\n\nA scoring rule $S(p, y)$ assigns a reward to the forecast $p$ when outcome $y$ occurs. Let the true distribution of $Y$ be $q$, while the forecaster reports $p$. The rule is **proper** if\n\n$$\n\\mathbb E_{Y \\sim q}\\big[S(q, Y)\\big] \\ge \\mathbb E_{Y \\sim q}\\big[S(p, Y)\\big] \\quad \\text{for every } p,\n$$\n\nand **strictly proper** if equality holds only at $p = q$ (Gneiting & Raftery 2007).\n\n- A proper rule makes an honest report of one's beliefs optimal in expectation. Reporting anything else cannot gain.\n- Every strictly proper rule for categorical outcomes has the form $S(p, y) = G(p) + \\langle G'(p), e_y - p \\rangle$ for a strictly convex $G$ with subgradient $G'$, where $e_y$ is the indicator vector of the outcome. Different $G$ give different rules.\n- Losses in this series are negatively oriented: lower is better. A loss $L$ is proper when $-L$ is.\n\n### Brier score\n\nFor a binary outcome the Brier score (Brier 1950) is the squared error of the probability:\n\n$$\n\\mathrm{BS}(p, y) = (p - y)^2.\n$$\n\nIt penalises each outcome by the distance from $p$ to where the forecast should have been:\n\n$$\ny = 1: \\ \\mathrm{BS} = (1 - p)^2, \\qquad y = 0: \\ \\mathrm{BS} = p^2.\n$$\n\nWith $Y \\sim \\operatorname{Bernoulli}(q)$, the expected score is\n\n$$\n\\mathbb E\\big[(p - Y)^2\\big] = q(p - 1)^2 + (1 - q)p^2 = q(p^2 - 2p + 1) + (1 - q)p^2 = p^2 - 2pq + q.\n$$\n\nIts derivative in $p$ is\n\n$$\n\\frac{d}{dp}\\,\\mathbb E\\big[(p - Y)^2\\big] = 2p - 2q,\n$$\n\nwhich is zero only at $p = q$, and the second derivative is $2 > 0$. The expected Brier score is minimised by the true probability. Writing it as $(p - q)^2 + q(1 - q)$ shows the penalty for misreporting is the squared distance $(p - q)^2$.\n\nFor $K$ classes, with $y_k = 1$ for the observed class and 0 otherwise:\n\n$$\n\\mathrm{BS}(\\mathbf p, y) = \\sum_{k=1}^K (p_k - y_k)^2.\n$$\n\n### Log score\n\nThe log score rewards the probability placed on what happened (Good 1952):\n\n$$\nS(p, y) = \\log p_y, \\qquad L(p, y) = -\\log p_y,\n$$\n\nwhich for a binary outcome is the familiar\n\n$$\nL = -y \\log p - (1 - y) \\log(1 - p).\n$$\n\nIts expectation splits into the entropy of $q$ and the Kullback–Leibler divergence from $q$ to $p$:\n\n$$\n\\mathbb E_{Y \\sim q}\\big[-\\log p_Y\\big] = -\\sum_k q_k \\log p_k = H(q) + \\mathrm{KL}(q \\,\\|\\, p).\n$$\n\n$H(q)$ does not depend on the report and $\\mathrm{KL}(q\\,\\|\\,p) \\ge 0$ with equality only at $p = q$, so the log score is strictly proper.\n\nThe two rules differ in how they charge for a high probability on the wrong outcome:\n\n- Brier is quadratic and bounded: the worst possible loss is 1.\n- Log loss is unbounded: a probability of 0.001 on an event that happens costs $-\\log 0.001 \\approx 6.9$.\n- Both judge the whole probability, not just the arg max.\n\n::: {#cell-fig-penalty .cell execution_count=9}\n``` {.python .cell-code}\np = np.linspace(0.001, 1, 800)\nfig, ax = plt.subplots(figsize=(6.2, 3.2))\nax.plot(p, -np.log(p), color=PURPLE, lw=1.8, label=r\"log loss $-\\log p$\")\nax.plot(p, (1 - p) ** 2, color=TEAL, lw=1.8, label=r\"Brier $(1-p)^2$\")\nfor pp in (0.01, 0.1):\n    ax.annotate(f\"p = {pp}: log {-np.log(pp):.1f}, Brier {(1 - pp) ** 2:.2f}\", xy=(pp, -np.log(pp)),\n                xytext=(pp + 0.12, -np.log(pp) + 0.4), fontsize=8, color=INK,\n                arrowprops=dict(arrowstyle=\"-\", color=MUTED, lw=0.8))\nax.set(xlabel=\"Probability given to the event that happened\", ylabel=\"Loss\", xlim=(0, 1), ylim=(0, 7))\nax.legend(frameon=False)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Loss when the event happens, as a function of the probability the forecaster gave it. Brier stays below 1; log loss grows without bound as the probability goes to zero.](index_files/figure-html/fig-penalty-output-1.png){#fig-penalty}\n:::\n:::\n\n\nThe widget puts a forecaster with true belief $q$ in front of four rules. Move the report $p$ away from $q$ and every proper rule charges for it. The improper absolute error rewards jumping to 0 or 1 whenever $q \\ne 0.5$, and at $q = 0.5$ it cannot tell any two reports apart.\n\n::: {#widget-scoring-rules}\n:::\n\n### Other proper scoring rules\n\nPropriety matters more than the choice among proper rules. The rules differ in what outcomes they handle and how they weight errors:\n\n| Rule | Loss for outcome $y$ | Proper? | Use |\n|:---|:---|:---|:---|\n| Multiclass log | $-\\log p_y$ | strictly | $K$ classes; the cross-entropy used to train classifiers; unbounded |\n| Multiclass Brier | $\\sum_k (p_k - y_k)^2$ | strictly | $K$ classes; bounded |\n| Spherical | $-p_y / \\lVert \\mathbf p \\rVert_2$ | strictly | $K$ classes; bounded |\n| Ranked probability (RPS) | $\\sum_{k=1}^{K-1} \\big(P_k - \\mathbb 1\\{y \\le k\\}\\big)^2$ | strictly | ordered levels; $P_k$ is cumulative, so near misses cost less (Epstein 1969) |\n| CRPS | $\\int \\big(F(z) - \\mathbb 1\\{y \\le z\\}\\big)^2 dz$ | strictly | continuous outcomes; RPS in the limit (Matheson & Winkler 1976) |\n| Absolute error | $\\lvert p - y \\rvert$ | no | minimised at 0 or 1, not at $q$ |\n| 0–1 loss of the arg max | $\\mathbb 1\\{\\hat y \\ne y\\}$ | no | ignores the probability |\n\n: Scoring rules for categorical and continuous outcomes, written as losses. {#tbl-rules}\n\nA Score question returns a distribution over ordered levels, so RPS is the natural rule for evaluating it: putting mass on \"frustrated\" when the truth is \"very angry\" should cost less than putting it on \"calm\". This is a suggestion for evaluation, not a statement about how Jev is trained [inference]{.tag-inference}.\n\n### Brier decomposition\n\nMurphy (1973) split the Brier score of forecasts that take a finite set of values $f_b$, with $n_b$ cases and observed frequency $\\bar y_b$ at each value:\n\n$$\n\\mathrm{BS} = \\underbrace{\\frac1n \\sum_b n_b (f_b - \\bar y_b)^2}_{\\text{reliability (REL)}} - \\underbrace{\\frac1n \\sum_b n_b (\\bar y_b - \\bar y)^2}_{\\text{resolution (RES)}} + \\underbrace{\\bar y (1 - \\bar y)}_{\\text{uncertainty}}.\n$$\n\n- REL is a calibration error: zero when every forecast value matches its frequency.\n- RES rewards forecasts that separate cases with different outcome rates. It is where discrimination lives.\n- Uncertainty depends only on the data.\n\n@tbl-metrics computes REL and RES on ten equal-count bins. The bins depend only on the order of the forecasts, and a monotone distortion keeps the order, so RES is identical for the three distorted forecasters (true on every seed) and only REL moves. A proper score is not a calibration metric: it adds calibration and discrimination into one number.\n\n## RLHF, RLVR and RLCD {#sec-rlcd}\n\nPost-training reward decides what a model is pushed toward. The three methods named in TypeSafe's AI primer reward different things.\n\n### RLHF\n\nReinforcement learning from human feedback (Christiano et al. 2017; Ouyang et al. 2022) fits a reward model to human comparisons and optimises the policy against it:\n\n$$\nx \\rightarrow (y_1, y_2) \\rightarrow \\text{human preference} \\rightarrow r_\\phi(x, y) \\rightarrow \\max_\\pi \\ \\mathbb E_{y \\sim \\pi(\\cdot \\mid x)}\\big[r_\\phi(x, y)\\big] - \\beta\\,\\mathrm{KL}(\\pi \\,\\|\\, \\pi_{\\text{ref}}).\n$$\n\n- **Objective:** produce responses people prefer.\n- Nothing in $r_\\phi$ scores a probability against an outcome. A fluent answer that sounds certain can be preferred whether or not the certainty is warranted.\n- The evidence agrees. In the GPT-4 technical report the pre-trained model has an ECE of 0.007 on a subset of MMLU and the post-trained model 0.074 (OpenAI 2023, Figure 8). Kadavath et al. (2022) found RLHF policies poorly calibrated until a temperature of 2.5 was applied.\n\n### RLVR\n\nReinforcement learning with verifiable rewards replaces the reward model with a program that checks the answer: a unit test, a proof checker, an exact-match grader (Lambert et al. 2024).\n\n- **Objective:** produce an answer that passes the verifier.\n- A pass/fail reward $r = \\mathbb 1\\{\\text{correct}\\}$ has expectation $P(\\text{correct})$. It rewards being right more often and says nothing about reporting how often one is right.\n\n### RLCD\n\nTypeSafe describes RLCD as \"Reinforcement learning for calibrated decisions\", which \"trains TypeSafe to return decisions and calibrated probabilities instead of generated text\" [vendor]{.tag-vendor}. The launch post says it optimises for \"answers with epistemically honest probabilities on System One tasks\", and the documentation says the probabilities \"are optimized against outcomes to reflect uncertainty\" [vendor]{.tag-vendor}.\n\n- **Claimed objective:** typed decisions whose probabilities match empirical frequencies of being correct.\n- **Undisclosed:** the reward, the loss, the source of the outcomes, the training data, and how calibration is evaluated.\n\nThe theory suggests a chain:\n\n\n```{mermaid}\n%%| label: fig-rlcd-chain\n%%| fig-cap: \"How a calibration objective connects to older ideas. Each link is standard theory; which links RLCD uses is not public.\"\nflowchart LR\n  A[\"RLCD<br/>(reward undisclosed)\"] <--> B[\"probabilistic<br/>forecasting\"]\n  B <--> C[\"proper<br/>scoring rules\"]\n  C <--> D[\"calibration\"]\n```\n\n\n**Could RLCD simply reward decisions with a proper scoring rule?** It is mathematically plausible and has published precedent. Damani et al. (2025) train a reasoning model to state a probability $c$ that its answer is correct, with the reward $\\mathbb 1\\{\\text{correct}\\} - \\big(c - \\mathbb 1\\{\\text{correct}\\}\\big)^2$: a correctness term plus a Brier term. No TypeSafe source says RLCD does this. It should not be stated as Jev's implementation [speculation]{.tag-spec}.\n\nThe theory also limits what RL can add [inference]{.tag-inference}. If the model outputs a distribution $p_\\theta(\\cdot \\mid x)$ directly and the reward is a proper score $S(p_\\theta, y)$ of that distribution, the expected reward is the negative of an ordinary supervised loss, and its gradient is the supervised gradient. For the log score that is maximum likelihood again. RL earns its keep only where the supervised setting does not fit. Hypotheses, none confirmed [speculation]{.tag-spec}:\n\n1. **Rewards from downstream outcomes**, such as whether a routed ticket was resolved, which arrive without a label for the question asked.\n2. **Sequence-level decisions**, where a chain of typed answers is scored as a whole.\n3. **Off-policy data**, reweighting logged decisions made by an earlier model.\n4. **Exploration**, choosing which questions to learn from.\n5. **Operational utilities** optimised alongside a calibration term, such as a cost for escalation.\n6. **Non-differentiable environments**, where a workflow's result cannot be backpropagated.\n7. **Delayed outcomes**, known days after the decision.\n\nThe question that matters for a user does not depend on the answer. Whatever RLCD optimises, calibration on your data is checked with the tools in @sec-reliability and @sec-ece.\n\n## Reliability diagrams {#sec-reliability}\n\nA reliability diagram (Niculescu-Mizil & Caruana 2005 popularised it in machine learning; the idea comes from weather forecasting) estimates the calibration function $m(p) = P(Y = 1 \\mid \\hat p = p)$ by binning:\n\n1. Split the forecasts into $M$ bins, here ten of width 0.1.\n2. In each bin, plot the mean forecast against the fraction of positive outcomes.\n3. Compare with the diagonal $y = x$, which is perfect calibration.\n\n::: {#cell-fig-reliability .cell execution_count=10}\n``` {.python .cell-code}\nx, p_star, y = draw(np.random.default_rng(1), 5000)\nfig, axes = plt.subplots(1, 3, figsize=(8.4, 3.2), sharey=True)\nfor ax, (title, alpha, colour) in zip(axes, [(\"Calibrated (α = 1)\", 1.0, PURPLE), (\"Overconfident (α = 2.5)\", 2.5, AMBER), (\"Underconfident (α = 0.4)\", 0.4, TEAL)]):\n    p = distort(p_star, alpha)\n    mp, fr, cnt = reliability_bins(p, y)\n    half = 1.96 * np.sqrt(fr * (1 - fr) / cnt)\n    counts, _ = np.histogram(p, bins=np.linspace(0, 1, 11))\n    ax.bar(np.linspace(0.05, 0.95, 10), 0.25 * counts / counts.max(), width=0.09, color=RULE, zorder=0)\n    ax.plot([0, 1], [0, 1], color=MUTED, lw=1, ls=\"--\")\n    ax.errorbar(mp, fr, yerr=half, fmt=\"o-\", color=colour, ms=4, lw=1.2, capsize=2)\n    ax.set(title=title, xlabel=\"Forecast probability\", xlim=(0, 1), ylim=(0, 1))\n    ax.set_aspect(\"equal\")\naxes[0].set_ylabel(\"Observed frequency of Y = 1\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Reliability diagrams for three forecasters on one sample of 5,000 cases. Error bars are 95% binomial intervals; the grey bars along the bottom are the histogram of forecasts. The overconfident forecaster's curve is flatter than the diagonal; the underconfident one's is steeper.](index_files/figure-html/fig-reliability-output-1.png){#fig-reliability}\n:::\n:::\n\n\nRead the curve against the diagonal, and read it on both sides of 0.5:\n\n- **Overconfident:** above the diagonal at low forecasts and below it at high forecasts. The curve is flatter than the forecasts claim.\n- **Underconfident:** the reverse, steeper than the diagonal.\n- **Biased:** entirely above (forecasts too low) or entirely below (too high).\n\nBinning has costs [theory]{.tag-theory}:\n\n- The picture depends on the number and placement of bins, and sparse bins at the extremes carry wide intervals.\n- A bin averages over all the cases in it, so structure inside a bin disappears.\n- Equal-width bins put most cases of a sharp forecaster into the two end bins, where a small gap on many cases matters most.\n\nPart 3 replaces the bins with a LOESS curve. In the lab, $\\alpha$ distorts the forecaster; $n$, the bin count and the LOESS span change how well a finite sample reveals it.\n\n::: {#widget-calibration-lab}\n:::\n\n\n```{=html}\n<script src=\"widgets.js\"></script>\n```\n\n\n- Slide $\\alpha$ from 0.25 to 4 at $n = 1{,}000$. Accuracy and AUC do not move. ECE, Brier and log loss bottom out between about $\\alpha = 0.85$ and $1.15$, depending on the sample.\n- Set $\\alpha = 1$ and $n = 200$, then draw new samples. ECE lands between about 0.04 and 0.10 for a forecaster that is calibrated by construction; at $n = 20{,}000$ it falls to about 0.007.\n\n## Expected calibration error {#sec-ece}\n\nThe expected calibration error summarises a reliability diagram in one number (Naeini et al. 2015; Guo et al. 2017):\n\n$$\n\\mathrm{ECE} = \\sum_{m=1}^M \\frac{|B_m|}{n} \\left| \\operatorname{acc}(B_m) - \\operatorname{conf}(B_m) \\right|.\n$$\n\nIn the top-label form, $B_m$ holds the cases whose $p_{\\max}$ falls in bin $m$, $\\operatorname{acc}(B_m)$ is the fraction of them whose arg max is correct, and $\\operatorname{conf}(B_m)$ is their mean $p_{\\max}$. For a binary problem this series uses the positive-class form: frequency of $Y = 1$ against mean $\\hat p$, fifteen equal-width bins.\n\nECE is useful and flawed [theory]{.tag-theory}:\n\n- **Binning dependence.** Different bin counts give different values on the same forecasts.\n- **Sample-size dependence.** Noise in each bin's frequency is added as an absolute value, so the plug-in estimate is biased upward, and the bias shrinks only as $n$ grows (Kumar, Liang & Ma 2019).\n- **Cancellation.** Gaps of opposite sign inside one bin cancel, which hides local miscalibration.\n- **Not a proper score.** The base-rate forecaster scores zero in @tbl-metrics. Minimising ECE alone rewards saying the base rate.\n\n::: {#cell-fig-ece-bias .cell execution_count=11}\n``` {.python .cell-code}\nsizes = [100, 300, 1000, 3000, 10_000, 30_000]\nbias = {m: [] for m in (5, 15, 30)}\nfor n in sizes:\n    vals = {m: [] for m in bias}\n    for r in range(R):\n        x, p_star, y = draw(np.random.default_rng(5000 + r), n)\n        for m in bias:\n            vals[m].append(ece(p_star, y, m))\n    for m in bias:\n        bias[m].append(np.quantile(vals[m], [0.05, 0.5, 0.95]))\nfig, ax = plt.subplots(figsize=(6.2, 3.4))\nfor m, colour in zip(bias, (TEAL, PURPLE, AMBER)):\n    q = np.array(bias[m])\n    ax.fill_between(sizes, q[:, 0], q[:, 2], color=colour, alpha=0.15, lw=0)\n    ax.plot(sizes, q[:, 1], \"o-\", color=colour, ms=3.5, lw=1.4, label=f\"{m} bins\")\nax.axhline(med[\"Overconfident α = 2.5\"][\"ECE\"], color=INK, lw=1, ls=\":\")\nax.set(xscale=\"log\", xlabel=\"Sample size n\", ylabel=\"ECE of a calibrated forecaster\")\nax.legend(frameon=False)\nplt.tight_layout()\nplt.show()\nece_100 = np.array(bias[15])[0, 1]\nece_1000 = np.array(bias[15])[2, 1]\n```\n\n::: {.cell-output .cell-output-display}\n![ECE of a forecaster that is perfectly calibrated by construction, against sample size, for three bin counts; median and 5–95% band over 200 seeds. The dotted line is the median ECE of the overconfident forecaster ($\\alpha = 2.5$) at $n = 5{,}000$ from @tbl-metrics.](index_files/figure-html/fig-ece-bias-output-1.png){#fig-ece-bias}\n:::\n:::\n\n\n- With fifteen bins, a calibrated forecaster scores a median ECE of 0\\.037 at $n = 1{,}000$ and 0\\.117 at $n = 100$.\n- At $n = 100$ that noise floor matches the ECE of the overconfident forecaster at $n = 5{,}000$ (0\\.118). A small evaluation set cannot tell a calibrated model from a badly miscalibrated one by ECE.\n- ECE values are comparable only at equal $n$ and equal binning. A published ECE without both is hard to interpret.\n\nBrier score and log loss measure more than calibration. By the Murphy decomposition, a lower Brier score can come from better calibration, better discrimination, or both, and @tbl-metrics shows the two moving separately. Report a proper score for overall quality and a calibration measure, with its sample size and binning, for calibration.\n\n## Constraints\n\n- Every experiment is synthetic and binary. The Choice and Score primitives need the multiclass and ordinal versions of the same checks.\n- None of the numbers measure Jev. No independent evaluation of Jev's calibration had been published when this was written.\n- The overconfident forecaster is a logit-scale distortion. Real miscalibration can be non-monotone, local, or different in subgroups.\n\nCalibration. Checks. Frequencies. Accuracy. Checks. Labels. Proper. Scores. Reward. Both.\n\n## References\n\n- Brier, G. W. (1950). [Verification of forecasts expressed in terms of probability](https://doi.org/10.1175/1520-0493(1950)078%3C0001:VOFEIT%3E2.0.CO;2). *Monthly Weather Review* 78(1), 1–3.\n- Christiano, P. et al. (2017). [Deep reinforcement learning from human preferences](https://arxiv.org/abs/1706.03741). *NeurIPS*.\n- Damani, M. et al. (2025). [Beyond binary rewards: training LMs to reason about their uncertainty](https://arxiv.org/abs/2507.16806). arXiv.\n- Epstein, E. S. (1969). [A scoring system for probability forecasts of ranked categories](https://doi.org/10.1175/1520-0450(1969)008%3C0985:ASSFPF%3E2.0.CO;2). *Journal of Applied Meteorology* 8(6), 985–987.\n- Gneiting, T., Balabdaoui, F. & Raftery, A. E. (2007). [Probabilistic forecasts, calibration and sharpness](https://doi.org/10.1111/j.1467-9868.2007.00587.x). *JRSS B* 69(2), 243–268.\n- Gneiting, T. & Raftery, A. E. (2007). [Strictly proper scoring rules, prediction, and estimation](https://doi.org/10.1198/016214506000001437). *JASA* 102(477), 359–378.\n- Good, I. J. (1952). [Rational decisions](https://doi.org/10.1111/j.2517-6161.1952.tb00104.x). *JRSS B* 14(1), 107–114.\n- Guo, C., Pleiss, G., Sun, Y. & Weinberger, K. Q. (2017). [On calibration of modern neural networks](https://proceedings.mlr.press/v70/guo17a.html). *ICML*.\n- Kadavath, S. et al. (2022). [Language models (mostly) know what they know](https://arxiv.org/abs/2207.05221). arXiv.\n- Kumar, A., Liang, P. & Ma, T. (2019). [Verified uncertainty calibration](https://arxiv.org/abs/1909.10155). *NeurIPS*.\n- Lambert, N. et al. (2024). [Tülu 3: pushing frontiers in open language model post-training](https://arxiv.org/abs/2411.15124). arXiv.\n- Matheson, J. E. & Winkler, R. L. (1976). [Scoring rules for continuous probability distributions](https://doi.org/10.1287/mnsc.22.10.1087). *Management Science* 22(10), 1087–1096.\n- Murphy, A. H. (1973). [A new vector partition of the probability score](https://doi.org/10.1175/1520-0450(1973)012%3C0595:ANVPOT%3E2.0.CO;2). *Journal of Applied Meteorology* 12(4), 595–600.\n- Naeini, M. P., Cooper, G. F. & Hauskrecht, M. (2015). [Obtaining well calibrated probabilities using Bayesian binning](https://doi.org/10.1609/aaai.v29i1.9602). *AAAI*.\n- Niculescu-Mizil, A. & Caruana, R. (2005). [Predicting good probabilities with supervised learning](https://doi.org/10.1145/1102351.1102430). *ICML*.\n- OpenAI (2023). [GPT-4 technical report](https://arxiv.org/abs/2303.08774). arXiv.\n- Ouyang, L. et al. (2022). [Training language models to follow instructions with human feedback](https://arxiv.org/abs/2203.02155). *NeurIPS*.\n- Sur, P. & Candès, E. J. (2019). [A modern maximum-likelihood theory for high-dimensional logistic regression](https://doi.org/10.1073/pnas.1810420116). *PNAS* 116(29), 14516–14525.\n- Vaicenavicius, J. et al. (2019). [Evaluating model calibration in classification](https://proceedings.mlr.press/v89/vaicenavicius19a.html). *AISTATS*.\n- TypeSafe (2026). [Introducing System One Models & Jev](https://typesafe.ai/blog/introducing-system-one-models-and-jev). Launch post, 2026-09-15.\n- TypeSafe (2026). Documentation: [System One](https://docs.typesafe.ai/concepts/system-one), [AI primer](https://docs.typesafe.ai/introduction/machine-learning-primer), [Confidence](https://docs.typesafe.ai/confidence). Accessed 2026-09-27.\n- [Calibrated Decisions, Part 1: Jev and the System One Model](../jev-system-one-model/) — what Jev returns and what TypeSafe claims.\n- [Calibrated Decisions, Part 3: Recalibration and Decisions](../recalibration-and-decisions/) — LOESS, recalibration maps, domain shift and cost-based thresholds.\n- [Tribes and Calibration](../tribes-and-calibration/) — Platt and temperature scaling in another setting.\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}