{
  "hash": "e5193a39593214bf675ff3a8226a76cb",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Why So Many Matrix Factorizations\"\nauthor: \"Ravi Kalia\"\ndate: \"2026-09-03\"\ncategories: [Linear Algebra, Machine Learning, Numerical Methods]\nimage: \"./cover.png\"\ndescription: \"Different factorizations exist because they solve different problems: QR for tall least squares, Cholesky for an SPD covariance, LU for a square system that is not SPD, SVD for a rank-k summary or a rectangular inverse.\"\ntags: [QR, Cholesky, LU, SVD, eigendecomposition, matrix factorization, pseudoinverse, computational complexity]\njupyter: mfc-blog\nresources:\n  - widgets.js\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    number-sections: true\n    css: post.css\nexecute:\n  warning: false\n---\n\n\n![Why So Many Matrix Factorizations](./cover.png)\n\nA matrix is like a complicated 3D object: what you see depends entirely on where you stand. Just as rewriting a polynomial can instantly reveal its roots, factoring a matrix isolates the exact properties you need to solve a specific problem. We don't choose between Cholesky, QR, or SVD because one is inherently superior to the others. We choose them because the jobs differ wildly. One day you need to solve least squares; the next, you need a rank-$k$ summary or a spectrum analysis. Each factorization is simply a different mathematical lens, perfectly ground to bring a specific application into focus.\n\n\n\n## Quadratic forms\n\nThe same parabola has four writings. Each writing makes one geometric fact cheap to read.\n\n- **Standard** $y = ax^2 + bx + c$ — the $y$-intercept is $c$.\n- **Vertex** $y = a(x-h)^2 + k$ — the min or max is $(h,k)$.\n- **Factored** $y = a(x-r_1)(x-r_2)$ — the roots are $r_1,r_2$.\n- **Matrix** $y = \\begin{bmatrix}x & 1\\end{bmatrix}\\begin{bmatrix}a & b/2 \\\\ b/2 & c\\end{bmatrix}\\begin{bmatrix}x \\\\ 1\\end{bmatrix}$ — the $2\\times 2$ already holds $(a,b,c)$. Cholesky of that $2\\times 2$ is completing the square.\n\nThe curve in the widget is synthetic: $a,b,c$ are slider values, not fitted data. It stands in for any 1-D quadratic whose job changes with the writing.\n\n<div id=\"quad-widget\"></div>\n\nPick **Vertex** from the form menu and the widget marks the turning point $(h,k)$. Pick **Factored** and it marks the roots $r_1, r_2$ when the curve crosses the axis, and says so when it does not. Pick **Standard** and it marks the intercept $c$; pick **Matrix** and it shows the $2\\times 2$ itself. Each writing makes one feature the thing you can read off.\n\n## Which factorization\n\nThe benefit is not the smallest leading term. Cholesky is the cheapest factor of an SPD covariance and is not defined on the photograph. We pick a factorization for the object it hands to the next step: a coefficient, a draw, a weight, a rank-$k$ image, a spectrum, or an inverse that exists.\n\n| Factorization | Matrix it needs | Downstream job | What we take |\n|---|---|---|---|\n| QR | tall $X$, full column rank | OLS | $\\hat\\beta$ from $R\\beta=Q^Ty$, without $X^TX$ |\n| Cholesky | SPD $\\Sigma$ | correlated draws; repeated SPD solves | $x=Lz$, or two triangular solves |\n| LU | square, not SPD | general $Ax=b$ (KKT, any invertible $A$) | the solve |\n| SVD | any shape, any rank | compression; $A^+$ | rank-$k$ summary, or the pseudoinverse |\n| Eigen | square symmetric, modest $\\kappa$ | spectrum / PCA of a covariance we trust | $Q$ and $\\Lambda$ |\n| NMF | $V\\ge 0$ | parts or topics | $W,H\\ge 0$ |\n\n: Use case, not a ranking. {#tbl-usecase}\n\nNMF is iterative, $O(t\\,k\\,mn)$. The Golub leukemia matrix is worked in [Matrix Factorizations as Optimization Problems](../matrix-factorizations/). For a Gram matrix $X^TX$, SVD of $X$ is the stable writing of the same spectrum. Flop-count models are Golub & Van Loan / Trefethen & Bau for dense $n\\times n$, not wall-clock.\n\n## QR\n\n$$\nA = QR, \\qquad O(mn^2)\\ \\text{for tall } m\\times n \\text{ (square: } 4n^3/3\\text{)}.\n$$\n\nHouseholder $Q$ is orthogonal. Back-substitution on $R\\beta = Q^Ty$ solves\n\n$$\n\\min_\\beta \\|y - X\\beta\\|_2^2\n$$\n\nwithout forming $X^TX$. [Matrix Factorizations as Optimization Problems](../matrix-factorizations/) treats the same factorization on the wheat markers, where $\\kappa(X)$ is large. The design here is ordinary OLS and well conditioned.\n\n### Diabetes\n\n- **Source:** Efron, Hastie, Johnstone, Tibshirani (2004), *Least Angle Regression*; the copy shipped with `sklearn.datasets.load_diabetes`.\n- **Measurements:** 442 patients × 10 baseline variables (age, sex, BMI, blood pressure, six serum assays), quantitative disease-progression response. sklearn standardises each column to mean 0 and squared length 1.\n- **This post asks:** recover $\\hat\\beta$ two ways — normal equations vs QR — and report the coefficient gap.\n- **A wrong $\\hat\\beta$:** a progression score that ranks patients in the wrong order.\n- **Why QR:** the job is tall OLS. $\\kappa(X)\\approx 22$ here, so the two solves will agree. QR is the factorization that remains accurate on a later design whose $\\kappa$ is large.\n\n::: {#diabetes-qr .cell execution_count=2}\n``` {.python .cell-code}\ndiabetes = load_diabetes()\nX = diabetes.data\ny = diabetes.target\nprint(f\"diabetes design: {X.shape[0]} patients x {X.shape[1]} variables\")\nprint(f\"cond(X)     = {cond(X):.3e}\")\nprint(f\"cond(X.T@X) = {cond(X.T @ X):.3e}\")\n\nbeta_ne = np.linalg.solve(X.T @ X, X.T @ y)\nQ, R = qr(X, mode=\"economic\")\nbeta_qr = solve_triangular(R, Q.T @ y)\nprint(f\"||beta_ne - beta_qr|| = {np.linalg.norm(beta_ne - beta_qr):.3e}\")\nprint(f\"RSS (both)            = {np.linalg.norm(y - X @ beta_qr):.4f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ndiabetes design: 442 patients x 10 variables\ncond(X)     = 2.168e+01\ncond(X.T@X) = 4.701e+02\n||beta_ne - beta_qr|| = 1.820e-10\nRSS (both)            = 3390.2651\n```\n:::\n:::\n\n\n`cond(X) ≈ 22` and `cond(X.T@X) ≈ 470 ≈ 22^2`. The two $\\hat\\beta$ agree to $1.8\\times 10^{-10}$. On this design the methods coincide. QR is the one we keep when a later $X$ has $\\kappa(X)$ near $10^8$, as on the wheat markers.\n\n## Cholesky\n\n$$\nA = LL^T, \\qquad O(n^3/3),\\quad A \\text{ SPD}.\n$$\n\nIf $z\\sim\\mathcal N(0,I)$ then $x = Lz\\sim\\mathcal N(0,\\Sigma)$ when $A=\\Sigma$. That is how we draw a correlated return vector from an SPD covariance.\n\n### Returns, 2022-09-01 to 2026-09-01\n\n- **Source:** Nasdaq.com historical `Close/Last` for `META`, `AAPL`, `AMZN`, `NFLX`, `GOOGL`, `NVDA`, and `AZN` (AstraZeneca), fetched once by `src/fetch_prices.py` into the committed `prices.csv`.\n- **Window:** 2022-09-01 through 2026-09-01 (1,003 common trading days; 1,002 log returns).\n- **Collector:** the listing exchange, via Nasdaq's split-adjusted close. The 10-for-1 NVDA split of 2024-06-10 is already in that series.\n- **This post asks:** a $7\\times 7$ sample covariance of daily log returns, equal-weight draws $x=Lz$, and a 300-day fan fitted on all but the last 300 days, with the held-out equal-weight path overlaid. AZN is a FTSE 100 pharmaceutical, included so the book is not one US-tech factor: its daily correlation with GOOGL is $0.006$.\n- **A wrong covariance:** a simulated book whose day-to-day risk does not match the seven names.\n- **Why Cholesky:** a return covariance is SPD (ridge it if a sample is only semidefinite). Leading term $n^3/3$, half of LU.\n\n::: {#load-prices .cell execution_count=3}\n``` {.python .cell-code}\nprices = pd.read_csv(\"prices.csv\", parse_dates=[\"date\"], index_col=\"date\")\nrets = np.log(prices).diff().dropna()\nnames = list(prices.columns)\nR = rets.to_numpy()\nn_names = R.shape[1]\nSigma = np.cov(R, rowvar=False)\nL = cholesky(Sigma, lower=True)\nw_eq = np.ones(n_names) / n_names\nprint(f\"log returns: {R.shape[0]} days x {n_names} names ({rets.index.min().date()} .. {rets.index.max().date()})\")\nprint(\"corr with GOOGL:\", {k: float(np.corrcoef(R[:, names.index(\"GOOGL\")], R[:, i])[0, 1]) for i, k in enumerate(names)})\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlog returns: 1002 days x 7 names (2022-09-02 .. 2026-09-01)\ncorr with GOOGL: {'META': 0.4833464519128782, 'AAPL': 0.44328985346547295, 'AMZN': 0.5984381147607905, 'NFLX': 0.29901306102125685, 'GOOGL': 1.0, 'NVDA': 0.41303817913126784, 'AZN': 0.005784626769348884}\n```\n:::\n:::\n\n\n::: {#cell-fig-performance .cell execution_count=4}\n``` {.python .cell-code}\nindexed = 100.0 * prices / prices.iloc[0]\npalette = {\n    \"META\": \"#4A3AA7\",\n    \"AAPL\": \"#1D6E6E\",\n    \"AMZN\": \"#9A5B00\",\n    \"NFLX\": \"#7A3B6B\",\n    \"GOOGL\": \"#1D5C6E\",\n    \"NVDA\": \"#C45C26\",\n    \"AZN\": \"#5F6672\",\n}\nfig, ax = plt.subplots(figsize=(7.4, 4.2))\nfor col in indexed.columns:\n    lw = 2.4 if col in (\"GOOGL\", \"AZN\") else 1.3\n    ax.plot(indexed.index, indexed[col], color=palette[col], lw=lw, label=col)\nax.set_ylabel(\"index (100 = 2022-09-01)\")\nax.set_title(\"Seven names, same window\")\nax.legend(ncol=4, fontsize=8, loc=\"upper left\")\nplt.tight_layout()\nplt.show()\nprint((prices.iloc[-1] / prices.iloc[0] - 1).round(3).to_dict())\n```\n\n::: {.cell-output .cell-output-display}\n![Split-adjusted closes indexed to 100 on 2022-09-01. AZN is the nearly flat British pharmaceutical; NVDA is the steep US-tech line.](index_files/figure-html/fig-performance-output-1.png){#fig-performance}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n{'META': 2.499, 'AAPL': 1.058, 'AMZN': 0.994, 'NFLX': 2.513, 'GOOGL': 2.053, 'NVDA': 14.602, 'AZN': 0.376}\n```\n:::\n:::\n\n\nIndexed to 100 at the first print, NVDA ends near $1{,}560$ and GOOGL near $305$. AZN ends near $138$. The British name barely tracks the US-tech block over the window.\n\n::: {#cell-fig-corr .cell execution_count=5}\n``` {.python .cell-code}\ncorr = np.corrcoef(R, rowvar=False)\n\nfig, ax = plt.subplots(figsize=(5.6, 4.6))\nim = ax.imshow(corr, cmap=\"RdBu_r\", vmin=-1, vmax=1)\nax.set_xticks(range(n_names), names, rotation=45, ha=\"right\")\nax.set_yticks(range(n_names), names)\nfig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)\nax.set_title(\"Return correlations\")\nax.grid(False)\nplt.tight_layout()\nplt.show()\nprint(np.round(corr, 3))\n```\n\n::: {.cell-output .cell-output-display}\n![Sample correlations of daily log returns, seven names, 2022-09-01 to 2026-09-01.](index_files/figure-html/fig-corr-output-1.png){#fig-corr}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[[ 1.     0.396  0.571  0.328  0.483  0.423 -0.052]\n [ 0.396  1.     0.423  0.343  0.443  0.383  0.059]\n [ 0.571  0.423  1.     0.388  0.598  0.459 -0.009]\n [ 0.328  0.343  0.388  1.     0.299  0.344  0.032]\n [ 0.483  0.443  0.598  0.299  1.     0.413  0.006]\n [ 0.423  0.383  0.459  0.344  0.413  1.    -0.006]\n [-0.052  0.059 -0.009  0.032  0.006 -0.006  1.   ]]\n```\n:::\n:::\n\n\nThe six US-tech names correlate between $0.30$ and $0.60$ with each other. AZN vs GOOGL is $0.006$. The book is no longer one factor plus residuals.\n\n::: {#chol-sample .cell execution_count=6}\n``` {.python .cell-code}\nprint(f\"||L L^T - Sigma||_F = {np.linalg.norm(L @ L.T - Sigma):.3e}\")\nprint(f\"cond(Sigma) = {cond(Sigma):.3f}\")\n\nhist_port = R @ w_eq\nZ = rng.normal(size=(10_000, n_names))\nsim_port = (Z @ L.T) @ w_eq\nprint(f\"equal-weight daily std  hist={hist_port.std(ddof=1):.5f}  sim={sim_port.std(ddof=1):.5f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n||L L^T - Sigma||_F = 1.437e-19\ncond(Sigma) = 11.125\nequal-weight daily std  hist=0.01463  sim=0.01474\n```\n:::\n:::\n\n\n::: {#cell-fig-portfolio .cell execution_count=7}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(6.4, 3.8))\nax.hist(sim_port, bins=40, color=ACCENT, alpha=0.85, density=True, label=\"Lz draws\")\ngrid = np.linspace(sim_port.min(), sim_port.max(), 200)\nmu_h, sd_h = hist_port.mean(), hist_port.std(ddof=1)\nax.plot(\n    grid,\n    np.exp(-0.5 * ((grid - mu_h) / sd_h) ** 2) / (sd_h * np.sqrt(2 * np.pi)),\n    color=AMBER,\n    lw=2,\n    label=\"N(hist mean, hist var)\",\n)\nax.set_xlabel(\"equal-weight daily log return\")\nax.set_ylabel(\"density\")\nax.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Equal-weight next-day portfolio return. Histogram: 10,000 Cholesky draws. Curve: kernel-free normal with the historical mean and variance.](index_files/figure-html/fig-portfolio-output-1.png){#fig-portfolio}\n:::\n:::\n\n\n$\\|LL^T-\\Sigma\\|_F$ is on the order of $10^{-19}$. Equal-weight daily volatility on the historical book and on the $Lz$ draws will match to a few basis points. Independent normals would treat every off-diagonal of $\\Sigma$ as zero and understate the US-tech block.\n\nThe histogram is one day. The same generator, fitted on returns through 2025-06-23, is then run for the 300 days that follow. The held-out equal-weight book is the actual path.\n\n::: {#cell-fig-forecast-fan .cell execution_count=8}\n``` {.python .cell-code}\nhorizon = 300\nn_paths = 5_000\new = 100.0 * np.exp(np.cumsum(R @ w_eq))\nfit_R = R[:-horizon]\nL_fit = cholesky(np.cov(fit_R, rowvar=False), lower=True)\nmu_fit = fit_R.mean(axis=0)\nrng_fan = np.random.default_rng(7)\nZ = rng_fan.normal(size=(n_paths, horizon, n_names))\nport_fwd = (mu_fit + Z @ L_fit.T) @ w_eq\norigin = ew[-horizon - 1]\nwealth = origin * np.exp(np.cumsum(port_fwd, axis=1))\nq = np.quantile(wealth, [0.05, 0.25, 0.50, 0.75, 0.95], axis=0)\nfwd_idx = rets.index[-horizon:]\nactual = ew[-horizon:]\nrank = float((wealth[:, -1] <= actual[-1]).mean())\n\nfig, ax = plt.subplots(figsize=(7.4, 4.0))\nax.fill_between(fwd_idx, q[0], q[4], color=ACCENT, alpha=0.15, label=\"5-95%\")\nax.fill_between(fwd_idx, q[1], q[3], color=ACCENT, alpha=0.30, label=\"25-75%\")\nax.plot(fwd_idx, q[2], color=AMBER, lw=1.8, label=\"median\")\nax.plot(rets.index, ew, color=INK, lw=1.6, label=\"equal-weight actual\", zorder=5)\nax.axvline(rets.index[-horizon], color=GREY, lw=1, ls=\"--\")\nax.set_ylabel(\"index (100 = 2022-09-01)\")\nax.set_title(\"300-day holdout fan\")\nax.legend(ncol=2, fontsize=8, loc=\"upper left\")\nplt.tight_layout()\nplt.show()\nprint(\n    f\"origin={origin:.1f}  actual={actual[-1]:.1f}  \"\n    f\"median={q[2, -1]:.1f}  p5={q[0, -1]:.1f}  p95={q[4, -1]:.1f}  \"\n    f\"actual_pct={rank:.2f}\"\n)\n```\n\n::: {.cell-output .cell-output-display}\n![Equal-weight book, indexed to 100 on 2022-09-01. Fan starts at the dashed line: 5,000 Cholesky paths from a mean and covariance fitted on the earlier window. The dark line through the fan is the held-out actual. Bands are 5-95 and 25-75 percentiles.](index_files/figure-html/fig-forecast-fan-output-1.png){#fig-forecast-fan}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\norigin=264.1  actual=318.3  median=396.3  p5=253.8  p95=626.8  actual_pct=0.21\n```\n:::\n:::\n\n\nFit $\\mu$ and $L$ on 702 days; hold out 2025-06-24 through 2026-09-01. Wealth at the split is $264$. Day 300: actual $318$, median $396$, $5$–$95$ band $254$–$627$. The actual path stays inside the band and finishes below the median (21st percentile of the paths). The band is the object Cholesky is for. The median is not a hit.\n\n## LU\n\n$$\nPA = LU, \\qquad O(2n^3/3).\n$$\n\nPartial pivoting $P$ keeps the solve stable on a general square matrix. Cholesky applies only when $A$ is SPD.\n\nMean-variance with a budget (and a return target) is the same seven names and a **different** matrix. Minimise $\\tfrac12 w^T\\Sigma w$ subject to $1^Tw=1$ and $\\mu^Tw=\\mu_\\star$:\n\n$$\n\\begin{bmatrix}\n\\Sigma & 1 & \\mu \\\\\n1^T & 0 & 0 \\\\\n\\mu^T & 0 & 0\n\\end{bmatrix}\n\\begin{bmatrix} w \\\\ \\lambda \\\\ \\gamma \\end{bmatrix}\n=\n\\begin{bmatrix} 0 \\\\ 1 \\\\ \\mu_\\star \\end{bmatrix}.\n$$\n\nThe KKT matrix is $(n+2)\\times(n+2)$ and symmetric indefinite. $\\mu_\\star$ is the equal-weight historical mean, so a feasible book exists.\n\n::: {#kkt-lu .cell execution_count=9}\n``` {.python .cell-code}\nmu = R.mean(axis=0)\nmu_star = float(mu @ w_eq)\nkkt_n = n_names + 2\nK = np.zeros((kkt_n, kkt_n))\nK[:n_names, :n_names] = Sigma\nK[:n_names, n_names] = 1.0\nK[n_names, :n_names] = 1.0\nK[:n_names, n_names + 1] = mu\nK[n_names + 1, :n_names] = mu\nrhs = np.zeros(kkt_n)\nrhs[n_names] = 1.0\nrhs[n_names + 1] = mu_star\nprint(f\"KKT shape {K.shape}\")\nprint(\"KKT eigenvalues:\", np.linalg.eigvalsh(K).round(6))\n\ntry:\n    cho_factor(K)\n    print(\"cho_factor: succeeded\")\nexcept np.linalg.LinAlgError as err:\n    print(f\"cho_factor: {type(err).__name__}\")\n\nlu, piv = lu_factor(K)\nsol = lu_solve((lu, piv), rhs)\nw_kkt = sol[:n_names]\nprint(\"weights:\", dict(zip(names, w_kkt.round(4))))\nprint(f\"1^T w = {w_kkt.sum():.6f}   mu^T w = {w_kkt @ mu:.6e}   target = {mu_star:.6e}\")\nprint(f\"||K sol - rhs|| = {np.linalg.norm(K @ sol - rhs):.3e}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nKKT shape (9, 9)\nKKT eigenvalues: [-2.645004e+00 -1.622000e-03  1.850000e-04  2.040000e-04  2.960000e-04\n  3.990000e-04  5.820000e-04  2.265000e-03  2.646503e+00]\ncho_factor: LinAlgError\nweights: {'META': np.float64(0.0542), 'AAPL': np.float64(0.2074), 'AMZN': np.float64(-0.0792), 'NFLX': np.float64(0.1671), 'GOOGL': np.float64(0.2294), 'NVDA': np.float64(0.1624), 'AZN': np.float64(0.2587)}\n1^T w = 1.000000   mu^T w = 1.155372e-03   target = 1.155372e-03\n||K sol - rhs|| = 2.813e-19\n```\n:::\n:::\n\n\n`cho_factor` raises `LinAlgError` because a constraint pivot is not positive. LU returns weights that sum to $1$ and hit $\\mu_\\star$ to printed precision. The residual is on the order of $10^{-16}$. The weights are a constrained quadratic programme, not a return forecast.\n\n## SVD\n\n$$\nA = U\\Sigma V^T, \\qquad O(\\min(mn^2, m^2n)).\n$$\n\nTruncation at rank $k$ stores $k(m+n+1)$ numbers instead of $mn$. Geometry of the three factors is [The Matrix That Rotates, Stretches, and Rotates Again](../svd-rotate-stretch-rotate/). This section is compression only.\n\n### Astronaut photograph\n\n- **Source:** `skimage.data.astronaut()`, NASA public-domain photograph of Eileen Collins, $512\\times 512$ grayscale in $[0,1]$.\n- **This post asks:** Frobenius residual and storage at ranks $5$, $20$, $50$.\n- **A poorly chosen rank:** a reconstruction that drops the face, or a store that does not shrink.\n- **Why SVD:** the photograph is a rectangular array (here square, still not SPD and not a least-squares design). Eckart–Young says the truncated SVD is the optimal rank-$k$ Frobenius summary.\n\n::: {#cell-fig-astronaut .cell execution_count=10}\n``` {.python .cell-code}\nimg = rgb2gray(data.astronaut())\nU_img, s_img, Vt_img = svd(img, full_matrices=False)\nm, n = img.shape\nranks = (5, 20, 50)\nenergy = (s_img ** 2).cumsum() / (s_img ** 2).sum()\n\nfig, axes = plt.subplots(1, 4, figsize=(11, 3.2))\naxes[0].imshow(img, cmap=\"gray\")\naxes[0].set_title(f\"original\\n{m * n} values\")\naxes[0].axis(\"off\")\nfor ax, k in zip(axes[1:], ranks):\n    approx = (U_img[:, :k] * s_img[:k]) @ Vt_img[:k]\n    stored = k * (m + n + 1)\n    ax.imshow(approx, cmap=\"gray\")\n    ax.set_title(f\"rank {k}\\n{stored} values, {energy[k - 1] * 100:.1f}%\")\n    ax.axis(\"off\")\nplt.tight_layout()\nplt.show()\n\nfor k in ranks:\n    approx = (U_img[:, :k] * s_img[:k]) @ Vt_img[:k]\n    print(\n        f\"k={k:2d}  ||A-A_k||_F={np.linalg.norm(img - approx, 'fro'):.1f}  \"\n        f\"energy={energy[k - 1] * 100:.1f}%  \"\n        f\"storage={k * (m + n + 1)} / {m * n} ({k * (m + n + 1) / (m * n) * 100:.1f}%)\"\n    )\n```\n\n::: {.cell-output .cell-output-display}\n![Grayscale astronaut photograph and truncated SVD at ranks 5, 20, and 50.](index_files/figure-html/fig-astronaut-output-1.png){#fig-astronaut}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nk= 5  ||A-A_k||_F=79.4  energy=91.5%  storage=5125 / 262144 (2.0%)\nk=20  ||A-A_k||_F=40.1  energy=97.8%  storage=20500 / 262144 (7.8%)\nk=50  ||A-A_k||_F=22.0  energy=99.3%  storage=51250 / 262144 (19.6%)\n```\n:::\n:::\n\n\nRank $5$ keeps $91.5\\%$ of Frobenius energy in $2.0\\%$ of the raw values. Rank $50$ keeps $99.3\\%$ in $19.6\\%$. JPEG will use fewer bytes at a given quality. The factorization is still a compressor for a rectangular array, which is the job here.\n\n## Eigendecomposition\n\n$$\nA = Q\\Lambda Q^T, \\qquad O(n^3),\\quad A \\text{ symmetric}.\n$$\n\nOn a covariance whose $\\kappa$ is small, eigen and SVD of the centered data agree. Forming the Gram matrix $X^TX$ and taking eigen squares the condition number:\n\n$$\n\\kappa(X^TX) = \\kappa(X)^2.\n$$\n\n### Well-conditioned covariance\n\nThe $7\\times 7$ return covariance has modest $\\kappa$. Eigenvalues of $\\Sigma$ must match squared singular values of the centered return matrix, up to the $1/(T-1)$ in `np.cov`.\n\n::: {#eigen-cov .cell execution_count=11}\n``` {.python .cell-code}\nXc = R - R.mean(axis=0)\nevals = np.sort(eigh(Sigma)[0])[::-1]\n_, s_c, _ = svd(Xc, full_matrices=False)\ns2 = (s_c ** 2) / (len(Xc) - 1)\nprint(\"Sigma eigenvalues:     \", evals.round(6))\nprint(\"sigma^2 / (T-1):       \", s2.round(6))\nprint(\"relative gap:          \", np.abs(evals - s2) / evals)\nprint(f\"cond(Sigma) = {cond(Sigma):.3f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSigma eigenvalues:      [0.001782 0.000508 0.000482 0.000397 0.000281 0.000197 0.00016 ]\nsigma^2 / (T-1):        [0.001782 0.000508 0.000482 0.000397 0.000281 0.000197 0.00016 ]\nrelative gap:           [3.64963989e-16 4.26580996e-16 5.61795600e-16 4.09238418e-16\n 1.15879974e-15 8.26176621e-16 1.18418879e-15]\ncond(Sigma) = 11.125\n```\n:::\n:::\n\n\nRelative gaps stay near $10^{-15}$. The two writings of this spectrum agree.\n\n### Polynomial-in-time design\n\nA polynomial in years-since-first-print of log NVDA price is the same series written as a tall, nearly dependent design. Degree $10$ (eleven columns), $t_i = i/252$:\n\n::: {#cell-fig-eigen-digits .cell execution_count=12}\n``` {.python .cell-code}\ny_nvda = np.log(prices[\"NVDA\"].to_numpy())\nt_years = np.arange(len(y_nvda)) / 252.0\ndeg = 10\nV = np.vander(t_years, N=deg + 1, increasing=True)\nG = V.T @ V\nge = np.sort(eigh(G)[0])[::-1]\n_, s_v, _ = svd(V, full_matrices=False)\ns2_v = s_v ** 2\n\nprint(f\"Vandermonde V: {V.shape[0]} x {V.shape[1]}\")\nprint(f\"cond(V)     = {cond(V):.3e}\")\nprint(f\"cond(V.T@V) = {cond(G):.3e}\")\nprint(\"trailing eig(V.T@V):\", ge[-3:])\nprint(\"trailing sigma^2:   \", s2_v[-3:])\n\nfig, axes = plt.subplots(1, 2, figsize=(10.5, 4.0))\nidx_s = np.arange(1, n_names + 1)\naxes[0].semilogy(idx_s, evals, \"o-\", color=ACCENT, label=\"eig(Sigma)\")\naxes[0].semilogy(idx_s, s2, \"s--\", color=TEAL, label=\"sigma^2 / (T-1) of Xc\")\naxes[0].set_xlabel(\"component\")\naxes[0].set_ylabel(\"value\")\naxes[0].set_title(\"7x7 covariance: agreement\")\naxes[0].legend(fontsize=8)\n\nidx_v = np.arange(1, len(ge) + 1)\nrel = np.abs(ge - s2_v) / np.maximum(s2_v, 1e-300)\naxes[1].semilogy(idx_v, rel, \"o-\", color=ACCENT)\naxes[1].axhline(1e-15, color=GREY, ls=\"--\", lw=1, label=\"machine-eps scale\")\naxes[1].set_xlabel(\"component\")\naxes[1].set_ylabel(\"|lambda - sigma^2| / sigma^2\")\naxes[1].set_title(\"degree-10 time polynomial: relative gap\")\naxes[1].legend(fontsize=8)\nprint(\"relative gap last3:\", rel[-3:])\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nVandermonde V: 1003 x 11\ncond(V)     = 1.484e+09\ncond(V.T@V) = 2.196e+18\ntrailing eig(V.T@V): [7.96121242e-02 1.94061656e-03 1.95533167e-05]\ntrailing sigma^2:    [8.03613608e-02 2.03273618e-03 2.29717038e-05]\nrelative gap last3: [0.00932334 0.04531804 0.1488086 ]\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![Left: eigenvalues of the 7x7 covariance match squared singular values of the centered returns. Right: relative gap |lambda - sigma^2| / sigma^2 on the degree-10 time polynomial, growing once kappa(X^T X) leaves float64.](index_files/figure-html/fig-eigen-digits-output-2.png){#fig-eigen-digits}\n:::\n:::\n\n\n$\\kappa(V)\\approx 1.5\\times 10^9$ and $\\kappa(V^TV)\\approx 2.2\\times 10^{18}$, past the float64 ceiling $\\approx 10^{16}$. The last two eigenvalues of $V^TV$ differ from $\\sigma^2$ by about $5\\%$ and $15\\%$. $V^TV$ is SPD by construction; the gap is the squared condition number in floating point.\n\n## SVD as inverse\n\n$$\nA^+ = V\\Sigma^+ U^T.\n$$\n\n$\\Sigma^+$ inverts the nonzero singular values and leaves the zeros as zeros. That one object covers the four linear-system jobs.\n\n| Matrix | Inverse that exists | What LU / `inv` / eigen-inverse need |\n|---|---|---|\n| Square, full rank | $A^{-1}=A^+$ | Square and full rank |\n| Tall, full column rank | left inverse; OLS $\\hat\\beta=A^+y$ | cannot apply |\n| Fat, full row rank | right inverse; least-norm solve | cannot apply |\n| Rank-deficient | $A^+$ drops the null space | `inv` is undefined; eigen needs a full set of eigenvectors |\n\n::: {#pinv-checks .cell execution_count=13}\n``` {.python .cell-code}\nbeta_pinv = pinv(V) @ y_nvda\nbeta_ne = np.linalg.solve(G, V.T @ y_nvda)\nprint(f\"||beta_ne - beta_pinv|| = {np.linalg.norm(beta_ne - beta_pinv):.3f}\")\nprint(f\"RSS pinv = {np.linalg.norm(V @ beta_pinv - y_nvda):.4f}\")\nprint(f\"RSS NE   = {np.linalg.norm(V @ beta_ne - y_nvda):.4f}\")\nprint(f\"max |inv(G)|  = {np.abs(inv(G)).max():.1f}\")\nprint(f\"max |pinv(V)| = {np.abs(pinv(V)).max():.1f}\")\n\nS = np.array([[1.0, 2.0], [2.0, 4.0]])\nprint(f\"det(S) = {np.linalg.det(S):.1f}\")\ntry:\n    inv(S)\n    print(\"inv(S): succeeded\")\nexcept np.linalg.LinAlgError as err:\n    print(f\"inv(S): {type(err).__name__}\")\nprint(\"pinv(S) =\")\nprint(pinv(S))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n||beta_ne - beta_pinv|| = 0.820\nRSS pinv = 2.9075\nRSS NE   = 2.9075\nmax |inv(G)|  = 17223.7\nmax |pinv(V)| = 26.0\ndet(S) = 0.0\ninv(S): LinAlgError\npinv(S) =\n[[0.04 0.08]\n [0.08 0.16]]\n```\n:::\n:::\n\n\nOn the degree-10 NVDA design, $\\hat\\beta$ from `solve(V.T@V, V.T@y)` and from `pinv(V)@y` differ by $0.82$ in Euclidean norm (`||β||≈188`). Residuals still match to $10^{-5}$ because the error lives in the near-null columns. `inv(G)` has entries of size $1.7\\times 10^4$; `pinv(V)` stays under $26$.\n\nThe $2\\times 2$ $S=\\begin{bmatrix}1&2\\\\2&4\\end{bmatrix}$ is exactly singular. `inv` raises `LinAlgError`. `pinv` returns the Moore–Penrose inverse. LU on $S$ needs a rank decision. The SVD pseudoinverse is defined for every real matrix, which is why it is the inverse we use when the shape or the rank is not known in advance.\n\n## Cost\n\nFlop counts decide among methods that already fit the job. They do not pick the job. The table is the leading term for dense $n\\times n$; the widget is the same models restricted to methods that apply.\n\n| Factorization | Flops | When the matrix is rectangular |\n|---|---|---|\n| Cholesky | $n^3/3$ | SPD only; not defined |\n| LU | $2n^3/3$ | square only |\n| Householder QR | $4n^3/3$ | $2mn^2-2n^3/3$ for tall $m\\times n$ |\n| Symmetric eigen | $\\sim 9n^3$ | square symmetric |\n| Full SVD | $\\sim 21n^3$ | $O(\\min(mn^2,m^2n))$ |\n| NMF | $O(t\\,k\\,n^2)$ | $O(t\\,k\\,mn)$; iterative, not a direct factor |\n\n: Flop-count models (Golub & Van Loan / Trefethen & Bau). {#tbl-flops}\n\n<div id=\"cost-widget\"></div>\n\nPick a job. Each bar is a flop-count model at the current $n$; a blank row is not defined for that matrix. Color is the method's name, held across jobs, not a heat scale. The ▸ is the pick. The $m/n$ slider appears on tall least squares; $k$ and $t$ appear on nonnegative parts.\n\nJobs. Differ. Factors. Follow. Applications. Choose. The. Inverse. That. Fits.\n\n## References\n\n- Golub, G. H., and Van Loan, C. F. [*Matrix Computations*](https://www.amazon.com/dp/1421407949) (4th ed., Johns Hopkins, 2013). Leading-term flop counts.\n- Trefethen, L. N., and Bau, D. [*Numerical Linear Algebra*](https://www.amazon.com/dp/1611977150) (25th anniversary ed., SIAM, 2022). QR, SVD, and $\\kappa(X^TX)=\\kappa(X)^2$.\n- Efron, B., Hastie, T., Johnstone, I., and Tibshirani, R. (2004). [Least angle regression](https://doi.org/10.1214/009053604000000067). *Annals of Statistics* 32(2). Diabetes data via [`sklearn.datasets.load_diabetes`](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html).\n- [Nasdaq.com historical quotes](https://www.nasdaq.com/market-activity/quotes/historical) — `META`, `AAPL`, `AMZN`, `NFLX`, `GOOGL`, `NVDA`, `AZN`, 2022-09-01 to 2026-09-01 (`prices.csv`).\n- [`skimage.data.astronaut()`](https://scikit-image.org/docs/stable/api/skimage.data.html#skimage.data.astronaut) — [NASA public-domain photograph of Eileen Collins](https://flic.kr/p/r9qvLn).\n- [Matrix Factorizations as Optimization Problems](../matrix-factorizations/) — QR conditioning, NMF on Golub leukemia.\n- [The Directions a Matrix Refuses to Turn](../eigendecomposition/) — eigenvectors as unrotated directions.\n- [The Matrix That Rotates, Stretches, and Rotates Again](../svd-rotate-stretch-rotate/) — SVD geometry and the astronaut widget.\n\n\n```{=html}\n<script src=\"widgets.js\"></script>\n```\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}