<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ravi Kalia">
<meta name="dcterms.date" content="2026-08-31">
<meta name="description" content="Friction ridges are a prenatal pattern. Identification is the problem of turning that pattern into a comparable digital object — first as minutiae, now as a learned embedding bounded by the sensor.">

<title>Fingerprint Algorithms: From Ridge Formation to On-Device Embeddings – Blog Directory</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-9923a10789e6ee87d406762b4ff79bf7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Blog Directory</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/project-delphi"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/ravi-kalia-phd"> <i class="bi bi-linkedin" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://project-delphi.github.io"> <i class="bi bi-house-fill" role="img" aria-label="LinkedIn">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Fingerprint Algorithms: From Ridge Formation to On-Device Embeddings</h1>
                  <div>
        <div class="description">
          Friction ridges are a prenatal pattern. Identification is the problem of turning that pattern into a comparable digital object — first as minutiae, now as a learned embedding bounded by the sensor.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Computer Vision</div>
                <div class="quarto-category">Biometrics</div>
                <div class="quarto-category">Machine Learning</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Ravi Kalia </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 31, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#a-pattern-nobody-chose-not-even-your-genome" id="toc-a-pattern-nobody-chose-not-even-your-genome" class="nav-link active" data-scroll-target="#a-pattern-nobody-chose-not-even-your-genome"><span class="header-section-number">1</span> A pattern nobody chose, not even your genome</a></li>
  <li><a href="#fingers-twice-each-and-what-it-cost-to-standardise-them" id="toc-fingers-twice-each-and-what-it-cost-to-standardise-them" class="nav-link" data-scroll-target="#fingers-twice-each-and-what-it-cost-to-standardise-them"><span class="header-section-number">2</span> 397 fingers, twice each, and what it cost to standardise them</a></li>
  <li><a href="#everything-downstream-needs-to-know-which-way-the-ridges-run" id="toc-everything-downstream-needs-to-know-which-way-the-ridges-run" class="nav-link" data-scroll-target="#everything-downstream-needs-to-know-which-way-the-ridges-run"><span class="header-section-number">3</span> Everything downstream needs to know which way the ridges run</a></li>
  <li><a href="#rung-0-slide-the-two-pictures-over-each-other" id="toc-rung-0-slide-the-two-pictures-over-each-other" class="nav-link" data-scroll-target="#rung-0-slide-the-two-pictures-over-each-other"><span class="header-section-number">4</span> Rung 0: slide the two pictures over each other</a></li>
  <li><a href="#rung-1-comb-the-whole-print-then-count-the-energy-cell-by-cell" id="toc-rung-1-comb-the-whole-print-then-count-the-energy-cell-by-cell" class="nav-link" data-scroll-target="#rung-1-comb-the-whole-print-then-count-the-energy-cell-by-cell"><span class="header-section-number">5</span> Rung 1: comb the whole print, then count the energy cell by cell</a></li>
  <li><a href="#rung-2-throw-the-picture-away-and-keep-the-constellation" id="toc-rung-2-throw-the-picture-away-and-keep-the-constellation" class="nav-link" data-scroll-target="#rung-2-throw-the-picture-away-and-keep-the-constellation"><span class="header-section-number">6</span> Rung 2: throw the picture away and keep the constellation</a>
  <ul class="collapse">
  <li><a href="#this-rung-measures-the-extractor-not-the-method" id="toc-this-rung-measures-the-extractor-not-the-method" class="nav-link" data-scroll-target="#this-rung-measures-the-extractor-not-the-method"><span class="header-section-number">6.1</span> This rung measures the extractor, not the method</a></li>
  </ul></li>
  <li><a href="#rung-3-let-the-network-decide-what-to-keep" id="toc-rung-3-let-the-network-decide-what-to-keep" class="nav-link" data-scroll-target="#rung-3-let-the-network-decide-what-to-keep"><span class="header-section-number">7</span> Rung 3: let the network decide what to keep</a></li>
  <li><a href="#the-ladder-scored" id="toc-the-ladder-scored" class="nav-link" data-scroll-target="#the-ladder-scored"><span class="header-section-number">8</span> The ladder, scored</a></li>
  <li><a href="#turn-the-probes-and-the-ranking-changes" id="toc-turn-the-probes-and-the-ranking-changes" class="nav-link" data-scroll-target="#turn-the-probes-and-the-ranking-changes"><span class="header-section-number">9</span> Turn the probes, and the ranking changes</a></li>
  <li><a href="#the-sensor-decides-what-any-of-this-can-see" id="toc-the-sensor-decides-what-any-of-this-can-see" class="nav-link" data-scroll-target="#the-sensor-decides-what-any-of-this-can-see"><span class="header-section-number">10</span> The sensor decides what any of this can see</a></li>
  <li><a href="#what-to-keep-and-when" id="toc-what-to-keep-and-when" class="nav-link" data-scroll-target="#what-to-keep-and-when"><span class="header-section-number">11</span> What to keep, and when</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">12</span> References</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/fingerprint-algorithms/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./cover.png" class="img-fluid figure-img"></p>
<figcaption>Fingerprint Algorithms: From Ridge Formation to On-Device Embeddings</figcaption>
</figure>
</div>
<p>You unlock a phone with your thumb a hundred times a week. It works when your thumb is wet, turned forty degrees off, pressed too hard, or only half on the glass. It fails when you offer a different finger.</p>
<p>The strange part is that the phone has no picture of your thumb. There is nothing in it to compare a photograph against. At enrolment it threw the picture away and kept something much smaller, and every unlock since has been a comparison between two of those smaller things.</p>
<p>So the interesting question is not “how do you match a fingerprint”. It is <strong>what do you keep</strong>, and what survives when the capture is bad. This post builds four answers to that question out of 397 real inked fingers from NIST, and scores every one of them against the same gallery of two hundred. One of the four is a modern metric-learning network. It does not win, and the reason it does not win turns out to be the most useful thing here.</p>
<section id="a-pattern-nobody-chose-not-even-your-genome" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="a-pattern-nobody-chose-not-even-your-genome"><span class="header-section-number">1</span> A pattern nobody chose, not even your genome</h2>
<p>Friction ridges form on the volar pads between roughly week 10 and week 17 of gestation. The basal layer of the epidermis is a stiff sheet growing on a soft foundation, and it is being compressed as the pad underneath it swells and then regresses. A stiff sheet under compression on a soft bed does not stay flat. It buckles, into a regular corrugation, at a wavelength set by the mechanics rather than by any instruction.</p>
<p>Kücken and Newell (2005) fit that picture to fetal pad geometry: ridge direction follows the lines of the compressive stress field, and the pattern type — loop, whorl, arch — falls out of the pad’s shape and timing. The same periodic stripes can be produced by a Turing reaction–diffusion system, which is why chemistry is the intuitive guess, but the model that matches the embryology is mechanical.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Where the ridge spacing comes from
</div>
</div>
<div class="callout-body-container callout-body">
<p>For a stiff film of thickness <span class="math inline">\(h\)</span> and modulus <span class="math inline">\(E_f\)</span> bonded to a soft substrate of modulus <span class="math inline">\(E_s\)</span>, compression buckles the film at the wavelength that minimises the total energy — bending the film wants long waves, deforming the substrate wants short ones. The balance gives the classical wrinkling result</p>
<p><span class="math display">\[
\lambda = 2\pi h \left(\frac{E_f}{3E_s}\right)^{1/3}.
\]</span></p>
<p>What matters is not the constant but that <span class="math inline">\(\lambda\)</span> depends only on a thickness and a stiffness ratio, so a patch of skin has a ridge period whether or not anything told it what period to have. Every filter in this post has to be tuned to that period, and measuring it per print is the first thing the code does.</p>
</div>
</div>
<p>Once the epidermis keratinises the pattern is fixed for life, scars aside. And identical twins, who share a genome, do not share ridge detail — the minute arrangement of endings and forks differs between them, and between your own two index fingers. That is what makes this a usable identifier: the thing being measured is a developmental accident, not an inherited plan, so it is effectively a per-finger random draw that then never changes.</p>
<p>A <a href="../what-is-a-biological-signature/">biological signature</a> in the molecular sense is a short list of features that stands in for a condition. A fingerprint template is the same move performed on skin. The engineering problem is to make the standing-in deterministic, so that two captures of one finger reduce to the same object and two captures of different fingers do not.</p>
</section>
<section id="fingers-twice-each-and-what-it-cost-to-standardise-them" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="fingers-twice-each-and-what-it-cost-to-standardise-them"><span class="header-section-number">2</span> 397 fingers, twice each, and what it cost to standardise them</h2>
<p>Everything measured here comes from one cache, so here is what is in it before anything is asked of it.</p>
<ul>
<li><strong>What it is.</strong> NIST’s MINEX III validation imagery: 801 raw 8-bit grayscale scans of inked fingerprint cards at 500 dpi, from the <code>usnistgov/minex</code> repository (commit <code>dc57b22</code>), released into the public domain as a US Government work. Retrieved 2026-09-12; the built cache is 20.3 MB, sha256 <code>426f1ccf…</code>.</li>
<li><strong>Who made it and why.</strong> NIST publishes it so that vendors’ minutiae extractors and matchers can be validated against a common set before certification. It exists <em>to be a benchmark</em>, which is exactly why it is safe to use as one, and why the results here are not a comment on anyone’s product.</li>
<li><strong>The structure that makes it a test.</strong> Files are named <code>&lt;set&gt;&lt;subject&gt;_&lt;position&gt;</code> — <code>a001_02</code> is set A, subject 001, right index. Sets A and B are two separate impressions of the same finger. Two impressions is the minimum that makes identification measurable: enrol one, search with the other, and ask which enrolled finger comes back first. 397 fingers have both impressions, giving 794 images; three of the 801 scans have no mate and are dropped.</li>
<li><strong>What this post asks of it.</strong> Rank-1 identification against a gallery of two hundred fingers, and an equal error rate for the one-against-one case. Nothing about latents, and nothing about live sensors — these are inked cards.</li>
<li><strong>What a wrong answer costs.</strong> In the deployed version of this problem, a false accept opens someone else’s phone and a false reject locks you out of your own. Those two errors trade against each other, which is why one accuracy number is never enough and the tables here carry both.</li>
</ul>
<p>Each scan is put on one scale and one centre by <code>src/fetch_data.py</code>, and that step makes a trade which bites one of the rungs later:</p>
<div id="12a423e2" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/fetch_data.py -- standardise(), abridged</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>own <span class="op">=</span> ridges.analyse(img).period        <span class="co"># this print's own ridge period</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>zoom <span class="op">=</span> period <span class="op">/</span> own                     <span class="co"># resample every print to a common period</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>source <span class="op">=</span> img.astype(np.float64)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> zoom <span class="op">&lt;</span> <span class="dv">1</span>:</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Anti-alias before shrinking. Resampling a 10-pixel ridge period down to 6</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># without it folds the ridges back as high-frequency noise.</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>    source <span class="op">=</span> ndimage.gaussian_filter(source, <span class="fl">0.5</span> <span class="op">/</span> zoom)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>scaled <span class="op">=</span> np.clip(ndimage.zoom(source, zoom, order<span class="op">=</span><span class="dv">1</span>), <span class="dv">0</span>, <span class="dv">255</span>).astype(np.uint8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Two things vary between cards for reasons that have nothing to do with whose finger it is: how large the print was rolled, and where on the card it landed. Both are removed — every print is resampled to a ridge period of 6 pixels and cropped to a 192-pixel square centred on its inked area. Everything a matcher has to survive is left in: rotation, ink coverage, elastic distortion of the skin, damage, and how much of the finger the roll caught.</p>
<p>The cost is resolution. The source scans run a median ridge period of 11.5 pixels and the cache halves that, which keeps the whole print inside a small square — necessary, because the rungs that measure global ridge flow lose about four times the accuracy on a sensor-sized window at full resolution. Ridge <em>flow</em> survives the resampling comfortably. Individual ridge endings and forks do not, and that is a debt the minutiae rung pays in full.</p>
<p>One more thing about the data, because it explains a lot of the spread later: this imagery is not uniformly good. Over 80 randomly drawn prints, the ridge mask covers a median 56% of the frame, seven prints fall under 10%, and on three of them the analysis finds no reliable ridge region at all. NIST’s own quality grade correlates only about 0.56 with that coverage, so grade is informative and not decisive.</p>
</section>
<section id="everything-downstream-needs-to-know-which-way-the-ridges-run" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="everything-downstream-needs-to-know-which-way-the-ridges-run"><span class="header-section-number">3</span> Everything downstream needs to know which way the ridges run</h2>
<p>Before any method can describe a print, it has to answer a smaller question at every point: which direction do the ridges run here, and how far apart are they? Three of the four rungs are built on that answer, so it is computed once and shared.</p>
<p>Direction is the awkward part, because a ridge has no arrowhead. A ridge running north-east is the same ridge running south-west, so the two gradient directions <span class="math inline">\(\theta\)</span> and <span class="math inline">\(\theta + \pi\)</span> are the same answer. Averaging them naively cancels them out. The fix is to average the <em>doubled</em> angle, where the two agree instead of opposing:</p>
<p><span class="math display">\[
\theta = \frac{1}{2}\operatorname{atan2}\!\left(2\sum g_x g_y,\; \sum\left(g_x^2 - g_y^2\right)\right) + \frac{\pi}{2}.
\]</span></p>
<div id="9a51f41b" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/ridges.py -- orientation()</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>gy, gx <span class="op">=</span> np.gradient(ndimage.gaussian_filter(x, <span class="fl">1.0</span>))</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>gxx, gyy, gxy <span class="op">=</span> blocks(gx <span class="op">*</span> gx, block), blocks(gy <span class="op">*</span> gy, block), blocks(gx <span class="op">*</span> gy, block)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>num, den <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> gxy, gxx <span class="op">-</span> gyy</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>theta <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> np.arctan2(num, den) <span class="op">+</span> np.pi <span class="op">/</span> <span class="dv">2</span>   <span class="co"># gradient normal -&gt; ridge tangent</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>coherence <span class="op">=</span> np.hypot(num, den) <span class="op">/</span> (gxx <span class="op">+</span> gyy <span class="op">+</span> <span class="fl">1e-12</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>That second line out is <code>coherence</code>: how single-minded the gradients in a block are. It runs near 1 on clean parallel ridges and near 0 on blank card, which makes it the natural measure of whether a block is worth trusting.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./figures/ridge-geometry.png" class="img-fluid figure-img"></p>
<figcaption>The print, its orientation field, the ridge-strength map, and the mask of blocks holding friction ridges. Drawn from <code>a002_04</code>, whose mask covers 75% of the frame. The orientation field curves around the core of the loop, which is the structure every later rung is reading.</figcaption>
</figure>
</div>
<p>With direction and period in hand, the enhancement step is a <strong>directional comb</strong>. A Gabor filter is a sinusoid wrapped in a Gaussian envelope — it has teeth at one spacing, running in one direction — and combing a patch of ridges along the direction they already run reinforces them, while noise that runs across the teeth is flattened:</p>
<p><span class="math display">\[
g(x,y;\lambda,\theta,\psi,\sigma,\gamma)
=\exp\left(-\frac{x'^2+\gamma^2 y'^2}{2\sigma^2}\right)
\cos\left(2\pi\frac{x'}{\lambda}+\psi\right),
\]</span></p>
<p>with <span class="math inline">\(x'=x\cos\theta+y\sin\theta\)</span> and <span class="math inline">\(y'=-x\sin\theta+y\cos\theta\)</span>. <span class="math inline">\(\lambda\)</span> is the ridge period, <span class="math inline">\(\theta\)</span> the local orientation, <span class="math inline">\(\sigma\)</span> the envelope width. Use the wrong <span class="math inline">\(\theta\)</span> and the comb fights the ridges instead of combing them, which is why the orientation field has to come first (Hong, Wan and Jain, 1998).</p>
<div id="5c8a5428" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/enhance.py -- enhance(): filter with the whole bank, then select per pixel</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>bank <span class="op">=</span> gabor_bank(img, analysis)                  <span class="co"># one filtered copy per orientation</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>theta <span class="op">=</span> _fit(np.kron(analysis.theta, np.ones((BLOCK, BLOCK))), img.shape)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> np.<span class="bu">round</span>(theta <span class="op">/</span> (np.pi <span class="op">/</span> ORIENTATIONS)).astype(<span class="bu">int</span>) <span class="op">%</span> ORIENTATIONS</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="cf">return</span> np.take_along_axis(bank, idx[<span class="va">None</span>], axis<span class="op">=</span><span class="dv">0</span>)[<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./figures/enhance-steps.png" class="img-fluid figure-img"></p>
<figcaption>Left to right the same print gets legible: the raw scan is faint and unevenly inked, the Gabor bank recovers continuous ridges, the crest map reduces each ridge to a line, and tracing plus gap-bridging closes most of the breaks. The visible improvement from the third panel to the fourth is the repair of ink gaps, which matters in the third rung.</figcaption>
</figure>
</div>
</section>
<section id="rung-0-slide-the-two-pictures-over-each-other" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="rung-0-slide-the-two-pictures-over-each-other"><span class="header-section-number">4</span> Rung 0: slide the two pictures over each other</h2>
<p>The bottom of the ladder keeps everything and understands nothing. No ridge model, no landmarks, no training — just how well one image lines up with another once you allow it to slide.</p>
<p>Correlation at every possible shift costs one Fourier transform per image rather than one comparison per offset, so “try every alignment” is cheaper than it sounds:</p>
<div id="0cb75410" class="cell" data-execution_count="4">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/pixels.py -- match_all(): best shift-aligned correlation, via the FFT</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>probe_f <span class="op">=</span> np.fft.rfft2(probe)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>gallery_f <span class="op">=</span> np.fft.rfft2(gallery, axes<span class="op">=</span>(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>surface <span class="op">=</span> np.fft.irfft2(gallery_f <span class="op">*</span> np.conj(probe_f), s<span class="op">=</span>probe.shape, axes<span class="op">=</span>(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>))</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="cf">return</span> surface.reshape(<span class="bu">len</span>(gallery), <span class="op">-</span><span class="dv">1</span>).<span class="bu">max</span>(axis<span class="op">=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Sliding is allowed because the prints are centred on their inked area, which moves with how much of the finger each roll caught. Rotation is <em>not</em> allowed, because handling it here would mean re-transforming the probe at every angle — and being unable to afford that is precisely why the higher rungs describe a print in terms that do not change when the finger turns.</p>
<p>This rung runs twice: once on the raw grey image, once on the Gabor-enhanced one. The gap between those two is a clean measurement of what the enhancement alone is worth, with no descriptor involved.</p>
</section>
<section id="rung-1-comb-the-whole-print-then-count-the-energy-cell-by-cell" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="rung-1-comb-the-whole-print-then-count-the-energy-cell-by-cell"><span class="header-section-number">5</span> Rung 1: comb the whole print, then count the energy cell by cell</h2>
<p>Jain, Prabhakar, Hong and Pankanti (2000) turned the filter bank into a fixed-length descriptor, the FingerCode. Lay a polar tessellation over the print — concentric rings cut into wedges — and for each cell record how much energy each Gabor orientation puts into it. Concatenate, and you have a vector of fixed size no matter what the print looked like.</p>
<p>The elegant part is what happens when the finger turns. Rotating the print moves energy around the tessellation in a completely predictable way: the wedges shift round by some number of sectors, and the ridge directions shift by a matching number of orientation bins. So comparing against a rotated version of a print costs two array rolls instead of re-filtering a rotated image:</p>
<div id="8d5c797b" class="cell" data-execution_count="5">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/enhance.py -- rotations(): every whole-sector rotation of a FingerCode</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> s <span class="kw">in</span> <span class="bu">range</span>(sectors):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sectors divide a full turn and orientations divide a half turn, so s</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># sectors of rotation is s * 2 * orientations / sectors orientation bins.</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    bins <span class="op">=</span> <span class="bu">int</span>(<span class="bu">round</span>(s <span class="op">*</span> <span class="dv">2</span> <span class="op">*</span> orientations <span class="op">/</span> sectors)) <span class="op">%</span> orientations</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">yield</span> np.roll(np.roll(code, s, axis<span class="op">=</span><span class="dv">2</span>), bins, axis<span class="op">=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>That comment is load-bearing. Rolling the histogram by half as far as the tessellation leaves every candidate but the zero-rotation one comparing a turned tessellation against unturned ridge directions, and a print rotated 90° then scores 0.78 against itself instead of 1.00.</p>
<p>The claim is checkable, so the third panel checks it. Turn a print ninety degrees, recompute its descriptor from scratch, and score it against the original at all sixteen assumed rotations:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./figures/fingercode.png" class="img-fluid figure-img"></p>
<figcaption>The polar tessellation over the print, its FingerCode as an 8-by-64 energy map, and the match score of the same print turned 90° against the original at each assumed rotation. The score peaks at exactly 90° and reaches 1.000, against 0.611 for comparing the two descriptors unrolled. Rotation really is an array roll. The lesser bump near 270° is the ambiguity from earlier coming back: ridge direction has no arrowhead, so a half-turn puts much of the energy back where it started.</figcaption>
</figure>
</div>
</section>
<section id="rung-2-throw-the-picture-away-and-keep-the-constellation" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="rung-2-throw-the-picture-away-and-keep-the-constellation"><span class="header-section-number">6</span> Rung 2: throw the picture away and keep the constellation</h2>
<p>This is what an examiner means by a fingerprint, and what every automated system meant by one until the 2010s. Walk the thinned ridges and record only the places where something happens — a ridge stops, or a ridge splits — as a list of points <span class="math inline">\((x, y, \theta)\)</span>. The image is then discarded entirely.</p>
<p>Finding them is a local counting exercise. On a skeleton one pixel wide, walk the eight neighbours of a pixel in a ring and count how many times the ring flips between skeleton and background. In the middle of a ridge it flips twice. One flip is a ridge ending; three is a bifurcation:</p>
<div id="8b1567c3" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/minutiae.py -- crossing_number(): half the flips around each pixel's ring</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>ring <span class="op">=</span> np.stack([np.roll(np.roll(skel, <span class="op">-</span>dy, <span class="dv">0</span>), <span class="op">-</span>dx, <span class="dv">1</span>) <span class="cf">for</span> dy, dx <span class="kw">in</span> _RING])</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>changes <span class="op">=</span> np.<span class="bu">abs</span>(ring.astype(np.int8) <span class="op">-</span> np.roll(ring, <span class="op">-</span><span class="dv">1</span>, axis<span class="op">=</span><span class="dv">0</span>).astype(np.int8))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="cf">return</span> changes.<span class="bu">sum</span>(<span class="dv">0</span>) <span class="op">//</span> <span class="dv">2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Matching two such lists is the hard half, and the right way to picture it is <strong>constellation alignment</strong>. You have two star charts of the same patch of sky, taken with different cameras, at different rotations, with different amounts of cloud. Neither chart is complete and neither is quite to scale. You are not asked whether the two images look alike; you are asked whether the same <em>arrangement</em> of stars appears in both.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Registering constellations: Kendall shape and Procrustes distance
</div>
</div>
<div class="callout-body-container callout-body">
<p>Treat the minutiae as labelled landmarks. Two impressions of one finger differ by a translation, a rotation, and — after standardisation — very nearly a scale. Quotient those out and what is left is the print’s <em>shape</em> in the sense of <a href="../kendall-shape-analysis/">Kendall shape analysis</a>: a point in a space where two configurations are the same point when some similarity transform carries one to the other.</p>
<p>For landmark matrices <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span>, centred and normalised to unit size, the Procrustes distance is the residual after the best rotation:</p>
<p><span class="math display">\[
d_P(X, Y) = \min_{R \in SO(2)} \lVert X - Y R \rVert_F ,
\]</span></p>
<p>solved in closed form by the SVD of <span class="math inline">\(Y^\top X\)</span>. It is the right way to compare two constellations — <em>if</em> you already know which star corresponds to which.</p>
<p>That proviso is the whole difficulty. Procrustes needs correspondences, and correspondences are what a fingerprint matcher does not have. So this rung sidesteps the transform entirely: each minutia is described by its own neighbourhood in its own frame of reference — how far its neighbours sit, in what direction relative to the way it points, and which way they point. Such a description does not change when the finger rotates, so two prints are compared by matching descriptions rather than by searching for an alignment. That is the idea behind Cappelli, Ferrara and Maltoni’s Minutia Cylinder-Code (2010), in a smaller form.</p>
</div>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./figures/minutiae.png" class="img-fluid figure-img"></p>
<figcaption>The two extractors on one print, and the mate impression. Crossing numbers on a thinned binary image find 20 landmarks, clustered where the ink is heavy. Ridge following finds 42, spread more evenly across the pattern. The mate gives 41. More landmarks, better spread — and, as the next section measures, no more repeatable.</figcaption>
</figure>
</div>
<section id="this-rung-measures-the-extractor-not-the-method" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="this-rung-measures-the-extractor-not-the-method"><span class="header-section-number">6.1</span> This rung measures the extractor, not the method</h3>
<p>Here is the uncomfortable result, stated before the table rather than after it. On this cache, the minutiae rung identifies a few percent of probes. Plain correlation of the enhanced images — rung 0 with a comb run over it, no landmarks at all — identifies ten times as many.</p>
<p>That is not a fact about minutiae matching. Real automated fingerprint identification systems do well on exactly this imagery, which is why NIST published it. It is a fact about <em>this extractor</em>, and the way to show that is to measure the landmarks directly instead of arguing about the score.</p>
<p>The diagnostic: take two impressions of one finger and register them by their ridge flow, searching over rotation and shift for the alignment that best correlates the enhanced images. This hands the matcher the transform it would otherwise have to find. Then ask the only question that matters — what fraction of the landmarks in one impression have a landmark in the other within a ridge period of them?</p>
<div id="9539aa46" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/minutiae_follow.py -- the gate</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>angle, peak, _ <span class="op">=</span> best_alignment(b_enhanced, a_enhanced, angles)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>moved <span class="op">=</span> transform_points(b_min.xy, angle, peak, a_enhanced.shape)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>genuine.append(landing_rate(moved, a_min.xy, tolerance))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Against an impostor floor — a different finger, registered the same way, whose points overlap by accident at this density — the crossing-number extractor lands <strong>0.156 of its landmarks against a floor of 0.072</strong>. About a fifth against a tenth. A neighbourhood descriptor needs the neighbourhood to be stable, and at that rate almost every description is built from mostly different members. No scoring rule can recover a correspondence that was never there, which is why the log of attempts in <code>src/minutiae.py</code> — greedy one-to-one pairing, normalising by landmark count, voting on the implied rotation, a full rigid point-pattern search, three binarisations, a pixel-resolution orientation field, three thinning variants — moves none of it.</p>
<p>So the fix has to be a different class of extractor: ridge <em>following</em> with a quality map, in the manner of NIST’s MINDTCT, rather than crossing numbers on a thinned skeleton. <code>src/minutiae_follow.py</code> is that attempt. It finds ridges as crests — the line where the enhanced image is a local maximum measured across the flow, which is a statement about ridge geometry rather than about where a threshold fell — smooths along the flow to close ink gaps, bridges the gaps that survive, and scores every candidate by coherence, ridge strength and distance from the edge of the print:</p>
<div id="c03a3fce" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/minutiae_follow.py -- bridge_gaps(): join endpoints that face each other</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>towards <span class="op">=</span> delta[i, j] <span class="op">/</span> d</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Each endpoint must be heading at the other, not merely near it.</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> towards <span class="op">@</span> tangent[i] <span class="op">&lt;</span> cone <span class="kw">or</span> (<span class="op">-</span>towards) <span class="op">@</span> tangent[j] <span class="op">&lt;</span> cone:</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">continue</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>rr, cc <span class="op">=</span> draw_line(<span class="bu">int</span>(ends[i, <span class="dv">1</span>]), <span class="bu">int</span>(ends[i, <span class="dv">0</span>]), <span class="bu">int</span>(ends[j, <span class="dv">1</span>]), <span class="bu">int</span>(ends[j, <span class="dv">0</span>]))</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>out[rr, cc] <span class="op">=</span> <span class="va">True</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>It behaves better on controls. On a synthetic ridge field containing no true minutiae, both extractors correctly return nothing. On a field carrying one deliberate ridge dislocation, the new extractor returns exactly that one landmark, where the old one returns three — the true one and two artefacts. It also finds more landmarks on real prints, and spreads them across the pattern instead of bunching them where the ink is thick.</p>
<p>And it does not help:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>extractor</th>
<th style="text-align: right;">minutiae per print</th>
<th style="text-align: right;">genuine landing</th>
<th style="text-align: right;">impostor floor</th>
<th style="text-align: right;">lift</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>crossing number, thinned skeleton</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">0.156</td>
<td style="text-align: right;">0.072</td>
<td style="text-align: right;"><strong>2.17</strong></td>
</tr>
<tr class="even">
<td>ridge following, quality ≥ 0.15</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">0.145</td>
<td style="text-align: right;">0.093</td>
<td style="text-align: right;">1.56</td>
</tr>
<tr class="odd">
<td>ridge following, quality ≥ 0.35</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">0.100</td>
<td style="text-align: right;">0.077</td>
<td style="text-align: right;">1.30</td>
</tr>
<tr class="even">
<td>ridge following, quality ≥ 0.55</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">0.084</td>
<td style="text-align: right;">0.054</td>
<td style="text-align: right;">1.56</td>
</tr>
</tbody>
</table>
<p>The extra landmarks are not more repeatable, and because there are more of them they collide by accident more often, so the lift over the floor gets <em>worse</em>. Tightening the quality threshold trades count for nothing: genuine landing falls faster than the floor does.</p>
<p>The resampling did this, upstream of every extractor. At a 6-pixel ridge period a ridge ending is a few pixels of evidence, and both extractors are reading a feature the cache no longer resolves. Rebuilding at the source period of 11.5 pixels lifts repeatability by about a third — real, and nowhere near enough, and it costs the global ridge flow that the rungs which <em>do</em> work depend on. Both minutiae rungs are scored anyway, because a rewrite that fails is worth as much as one that works and costs the reader less to believe. Neither is evidence about minutiae matching as a technique.</p>
</section>
</section>
<section id="rung-3-let-the-network-decide-what-to-keep" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="rung-3-let-the-network-decide-what-to-keep"><span class="header-section-number">7</span> Rung 3: let the network decide what to keep</h2>
<p>The first three rungs are hand-built. Someone decided that ridge orientation matters, that a Gabor bank is the way to measure it, that endings and forks are the landmarks worth keeping. A metric-learning network is told none of that. It is given pairs and a rule about distances, and has to work out what to measure for itself.</p>
<p>The mental picture is a <strong>field of attractors</strong>. Every finger is a mass placed on the surface of a 128-dimensional sphere, and training pulls the two impressions of one finger into the same well while pushing different fingers’ wells apart. Nothing tells the network what a ridge is. It only ever learns that these two images must end up close and those two must not.</p>
<p>For an anchor <span class="math inline">\(a\)</span>, a positive <span class="math inline">\(p\)</span> from the same finger, and a negative <span class="math inline">\(n\)</span> from another, the triplet loss is</p>
<p><span class="math display">\[
\mathcal{L}=\bigl[\;\lVert f(a)-f(p)\rVert_2^2
-\lVert f(a)-f(n)\rVert_2^2
+m\;\bigr]_+ .
\]</span></p>
<p>Picking triplets at random wastes almost every one of them, because most triplets already satisfy the margin and contribute no gradient. The batch-hard form (Hermans, Beyer and Leibe, 2017) takes the <em>worst</em> case in each batch instead — for every image, its own mate as the hardest positive and the nearest image of a different finger as the hardest negative:</p>
<div id="b2531c34" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/embed.py -- batch_hard_triplet()</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>distance <span class="op">=</span> torch.cdist(embeddings, embeddings)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>same <span class="op">=</span> labels[:, <span class="va">None</span>] <span class="op">==</span> labels[<span class="va">None</span>, :]</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>eye <span class="op">=</span> torch.eye(<span class="bu">len</span>(labels), dtype<span class="op">=</span>torch.<span class="bu">bool</span>, device<span class="op">=</span>labels.device)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>hardest_positive <span class="op">=</span> (distance <span class="op">*</span> (same <span class="op">&amp;</span> <span class="op">~</span>eye)).<span class="bu">max</span>(dim<span class="op">=</span><span class="dv">1</span>).values</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>hardest_negative <span class="op">=</span> (distance <span class="op">+</span> same <span class="op">*</span> <span class="fl">1e6</span>).<span class="bu">min</span>(dim<span class="op">=</span><span class="dv">1</span>).values</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="cf">return</span> F.relu(hardest_positive <span class="op">-</span> hardest_negative <span class="op">+</span> margin).mean()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>With two images per finger the network would otherwise memorise the pair rather than learn what makes it a pair, so each batch is augmented with random rotation, shift, scale and a blanked-out block. Each of those stands for something the sensor does anyway: the finger lands at a different angle, presses harder, and covers a different part of the platen. The blanked block is the partial print.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
ArcFace: putting the margin in the angle
</div>
</div>
<div class="callout-body-container callout-body">
<p>The embeddings here are L2-normalised, so similarity is a dot product and all the information is in angle. ArcFace (Deng et al., 2019) takes that seriously. Start from softmax cross-entropy, drop the bias, and normalise both the weight vectors and the features, so the logit for class <span class="math inline">\(j\)</span> becomes <span class="math inline">\(W_j^\top f = \cos\theta_j\)</span>. Then add a fixed margin <span class="math inline">\(m\)</span> <em>inside</em> the cosine for the true class only, and rescale by <span class="math inline">\(s\)</span>:</p>
<p><span class="math display">\[
\mathcal{L}_{\text{arc}} = -\log
\frac{e^{\,s\cos(\theta_y + m)}}
{e^{\,s\cos(\theta_y + m)} + \sum_{j \neq y} e^{\,s\cos\theta_j}} .
\]</span></p>
<p>Because <span class="math inline">\(\cos\)</span> is decreasing on <span class="math inline">\([0,\pi]\)</span>, demanding <span class="math inline">\(\cos(\theta_y + m)\)</span> beat the other logits is demanding that the true class win <em>by an angular margin</em> <span class="math inline">\(m\)</span> — a constant-width band on the sphere, the same everywhere. A Euclidean margin is not that: the same distance means different angles depending on where you are. This is the loss behind most modern face recognition, and it is used for fingerprints unchanged.</p>
<p>This post scores the triplet version, because a margin in angle needs enough identities for the classification head to be meaningful and a few hundred fingers is not enough for the comparison to say anything.</p>
</div>
</div>
<p>Which is the caveat the whole rung rests on. This network sees a few hundred images of a couple of hundred fingers. The systems that beat hand-built features on this problem see millions of prints, and millions is not a nicety — with two impressions per finger, the nearest image of a <em>different</em> finger is usually closer than a print’s own mate, so the loss can be reduced faster by shrinking the whole embedding than by separating anything in it. The scoring section reports what that looks like when it happens.</p>
</section>
<section id="the-ladder-scored" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="the-ladder-scored"><span class="header-section-number">8</span> The ladder, scored</h2>
<p>Two rules keep the comparison honest, and both cost accuracy.</p>
<p><strong>Nothing is scored on a finger it was fitted on.</strong> The fingers are split in two before anything runs. The network trains on one half; every rung, trained or not, is scored on the other. The hand-built rungs would score the same either way, which is the point — they get no advantage from the rule and the network gets no advantage from breaking it. The split is by <em>finger</em>, not by image, because a model that trained on one impression of a finger and was then asked to recognise the other would be answering a question no phone ever asks.</p>
<p><strong>Every rung is charged for the ridge geometry it needs.</strong> Rungs 0+, 1 and 2 all start by asking which way the ridges run. Computing that once and sharing it is the only sane way to run the ladder, but attributing it to nobody would make three rungs look free, so the shared pass is timed once and added to each rung that reads it.</p>
<p>Everything reported comes off one object per rung — a score matrix, one row per probe, one column per enrolled finger, higher meaning more alike — which is what makes a pixel correlation, a Gabor descriptor, a point set and a learned vector comparable at all. Ties are resolved against the matcher, deliberately:</p>
<div id="44cf7b0d" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/bench.py -- score(): ties count against the matcher, so silence scores last</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>genuine <span class="op">=</span> matrix[rows, truth]</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Counting only strictly-better entries would give a matcher that returns the</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># same score for everything a rank of zero on every probe -- a perfect result</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co"># for saying nothing.</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>ranks <span class="op">=</span> (matrix <span class="op">&gt;=</span> genuine[:, <span class="va">None</span>]).<span class="bu">sum</span>(<span class="dv">1</span>) <span class="op">-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Two hundred fingers enrolled, two hundred probes, one impression each. Chance rank-1 is <span class="math inline">\(1/199 = 0.005\)</span>, so anything near half a percent is guessing.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Rung</th>
<th>What it keeps</th>
<th style="text-align: right;">rank-1</th>
<th style="text-align: right;">rank-5</th>
<th style="text-align: right;">median rank</th>
<th style="text-align: right;">EER</th>
<th style="text-align: right;">d′</th>
<th style="text-align: right;">search</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0 pixel correlation</td>
<td>the image</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.085</td>
<td style="text-align: right;">63</td>
<td style="text-align: right;">0.431</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">12 s</td>
</tr>
<tr class="even">
<td>0+ pixel correlation, enhanced</td>
<td>the combed image</td>
<td style="text-align: right;"><strong>0.332</strong></td>
<td style="text-align: right;"><strong>0.508</strong></td>
<td style="text-align: right;"><strong>5</strong></td>
<td style="text-align: right;"><strong>0.251</strong></td>
<td style="text-align: right;"><strong>1.15</strong></td>
<td style="text-align: right;">35 s</td>
</tr>
<tr class="odd">
<td>1 FingerCode</td>
<td>flow energy, per cell and direction</td>
<td style="text-align: right;">0.161</td>
<td style="text-align: right;">0.332</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">0.370</td>
<td style="text-align: right;">0.58</td>
<td style="text-align: right;">23 s</td>
</tr>
<tr class="even">
<td>2 minutiae, crossing number</td>
<td>a list of landmarks</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.070</td>
<td style="text-align: right;">110</td>
<td style="text-align: right;">0.482</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: right;">25 s</td>
</tr>
<tr class="odd">
<td>2+ minutiae, ridge following</td>
<td>a list of landmarks</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">0.495</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">33 s</td>
</tr>
<tr class="even">
<td>3 learned embedding, triplet</td>
<td>128 floats</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.111</td>
<td style="text-align: right;">51</td>
<td style="text-align: right;">0.407</td>
<td style="text-align: right;">0.53</td>
<td style="text-align: right;"><strong>1 s</strong></td>
</tr>
</tbody>
</table>
<p>The search column is the whole 199-by-199 comparison, with the shared ridge geometry charged to every rung that reads it. The network’s 144 seconds of training is not in it, because training happens once before any finger is enrolled.</p>
<p><strong>The largest effect in the table is the oldest idea in it.</strong> The only difference between the first two rows is whether the images were combed with a Gabor bank before being correlated, and it moves rank-1 from 0.020 to 0.332 — a factor of sixteen, from a 1998 paper, with no descriptor, no landmarks and no training anywhere in sight. Enhancement is not a preprocessing detail that precedes the real method. On this data it <em>is</em> most of the method.</p>
<p><strong>FingerCode buys portability, not accuracy.</strong> It lands at half the rank-1 of enhanced correlation. What it gets in exchange is a fixed-length template a few kilobytes wide, and rotation handled by two array rolls instead of not handled at all.</p>
<p><strong>Both minutiae rungs are near chance</strong>, at 0.030 and 0.015 against 0.005, with d′ of 0.08 and 0.07 — which is to say the genuine and impostor score distributions are on top of each other and no threshold separates them. The ridge-following rewrite is the <em>worse</em> of the two, exactly as its repeatability gate predicted. Neither number is evidence about minutiae matching; both are evidence about extractors reading a feature this cache resampled away.</p>
<p><strong>And the learned rung is the interesting failure.</strong> It ties the minutiae extractor on rank-1 at 0.030, and beats it on everything else: rank-5 0.111 against 0.070, median rank 51 against 110, d′ 0.53 against 0.08. But look at the last column. One second, against twenty-three to thirty-five for everything else — because at query time it does no ridge analysis, no filtering and no point matching. It encodes once and takes a dot product.</p>
<p>Be precise about that last column, because it is the reason phones work this way at all. The embedding is thirty-odd times cheaper to search and its template is 128 floats, and it achieves that while being a <strong>collapsed</strong> embedding: the loss settles at 0.300 against a margin of 0.3, which is what the hinge returns when every distance is equal, and per-dimension spread across prints comes out at <span class="math inline">\(1.7 \times 10^{-4}\)</span>. Soft-margin, a quarter of the learning rate, a smaller margin and half the batch were all tried; each settles at its own degenerate value and none recovers the spread. With two impressions per finger and two hundred fingers, shrinking everything is the only move that reduces the loss.</p>
<p>So the d′ of 0.53 is a real signal living in the residual directions of an embedding that has almost no extent. It is not a network that learned a little. It is a network that collapsed and still has a whisker of the answer in the rounding.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./figures/embedding.png" class="img-fluid figure-img"></p>
<figcaption>Left: the batch-hard triplet loss settling onto the margin, which is the collapse — equal hardest-positive and hardest-negative distances return exactly the margin. Right: genuine and impostor similarity, plotted as an offset from the impostor median because every pair sits within about <span class="math inline">\(10^{-5}\)</span> of every other. The separation is real, and it is tiny.</figcaption>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="./figures/cmc.png" class="img-fluid figure-img"></p>
<figcaption>Cumulative match characteristic: how often the true mate appears in the top <span class="math inline">\(k\)</span> as <span class="math inline">\(k\)</span> grows, one line per rung. The curve to read is the one at <span class="math inline">\(k=1\)</span>; the rest tells you how quickly a near-miss becomes a hit.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Two different questions, two different numbers
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Rank-1</strong> answers the search problem: one finger against a database, and the answer is a shortlist. This is a border crossing or a latent print against a criminal gallery.</p>
<p><strong>EER</strong> answers the verification problem: one finger against one claim, and the answer is yes or no. The equal error rate is the threshold where as many genuine pairs are rejected as impostor pairs are accepted — a single summary of the trade you would tune in practice. This is your phone.</p>
<p>A rung can be respectable at one and poor at the other, because rank-1 only needs the true mate to beat the gallery <em>for this probe</em>, while EER needs one global threshold to work across all probes. <strong>d′</strong> is the third column: how many impostor standard deviations separate the two score distributions, which says whether a threshold exists to be tuned at all.</p>
</div>
</div>
</section>
<section id="turn-the-probes-and-the-ranking-changes" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="turn-the-probes-and-the-ranking-changes"><span class="header-section-number">9</span> Turn the probes, and the ranking changes</h2>
<p>There is a quiet gift in that table, and it belongs to the two rungs that did best. Inked cards are rolled onto a form, so every print in this cache is roughly upright. Rung 0 and rung 0+ cannot search over rotation at all — they slide one image over another and that is the whole repertoire — so the data has been flattering them.</p>
<p>A finger on a phone lands at whatever angle it lands at. That is one flag away from being measurable, so it is cheaper to measure it than to argue about it:</p>
<div id="714c4f4f" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># src/ladder.py -- turn_probes(): every probe gets its own random angle</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>angles <span class="op">=</span> rng.uniform(<span class="op">-</span>degrees, degrees, <span class="bu">len</span>(probe.images))</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>turned <span class="op">=</span> np.stack([</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    np.clip(rotate_about_centre(img.astype(<span class="bu">float</span>), np.deg2rad(a)), <span class="dv">0</span>, <span class="dv">255</span>).astype(np.uint8)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> img, a <span class="kw">in</span> <span class="bu">zip</span>(probe.images, angles)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Enrol the same gallery, turn each probe by its own random angle up to <span class="math inline">\(\pm 30°\)</span>, and run the ladder again:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rung</th>
<th style="text-align: right;">rank-1 upright</th>
<th style="text-align: right;">rank-1 turned</th>
<th style="text-align: right;">EER upright</th>
<th style="text-align: right;">EER turned</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0 pixel correlation</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.431</td>
<td style="text-align: right;">0.461</td>
</tr>
<tr class="even">
<td>0+ pixel correlation, enhanced</td>
<td style="text-align: right;"><strong>0.332</strong></td>
<td style="text-align: right;">0.101</td>
<td style="text-align: right;">0.251</td>
<td style="text-align: right;">0.380</td>
</tr>
<tr class="odd">
<td>1 FingerCode</td>
<td style="text-align: right;">0.161</td>
<td style="text-align: right;"><strong>0.131</strong></td>
<td style="text-align: right;">0.370</td>
<td style="text-align: right;"><strong>0.371</strong></td>
</tr>
<tr class="even">
<td>2 minutiae, crossing number</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.482</td>
<td style="text-align: right;">0.477</td>
</tr>
<tr class="odd">
<td>2+ minutiae, ridge following</td>
<td style="text-align: right;">0.015</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.495</td>
<td style="text-align: right;">0.487</td>
</tr>
<tr class="even">
<td>3 learned embedding, triplet</td>
<td style="text-align: right;">0.030</td>
<td style="text-align: right;">0.020</td>
<td style="text-align: right;">0.407</td>
<td style="text-align: right;">0.427</td>
</tr>
</tbody>
</table>
<p><strong>Enhanced correlation loses two thirds of its accuracy and FingerCode barely moves, so the order swaps.</strong> Rung 0+ falls from 0.332 to 0.101; rung 1 goes from 0.161 to 0.131 and is now the best of the six. Look at the EER columns for the cleanest version of it: FingerCode’s goes from 0.370 to 0.371, and its d′ from 0.58 to 0.57. Rotating the finger costs the descriptor that was designed to absorb rotation almost exactly nothing.</p>
<p>The learned rung also holds up better than it scores — d′ 0.53 to 0.45 — which is not a mystery: it was trained on batches augmented with rotations up to <span class="math inline">\(\pm 25°\)</span>, so turned probes are inside what it was shown. It paid for that robustness in advance, with data.</p>
<p>The two minutiae rows move by three to six probes out of 199, which at those rates is noise rather than a finding. Nothing here rescues them.</p>
<p>So the ranking depends on a property of the capture, not of the algorithm. On upright rolled cards, comb the images and correlate them — the 1998 answer wins and nothing since has earned its keep. Let the finger turn, and the descriptor that treats rotation as an array roll takes over, at half the peak accuracy but without a cliff to fall off. This is the shape of the whole history in one table: later methods are not uniformly better, they are less dependent on the capture being kind.</p>
</section>
<section id="the-sensor-decides-what-any-of-this-can-see" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="the-sensor-decides-what-any-of-this-can-see"><span class="header-section-number">10</span> The sensor decides what any of this can see</h2>
<p>Everything measured here came off inked cards. The comparison on a phone is the same comparison, but the sensor decides what the representation is even allowed to contain — and the three sensors in shipping phones measure three different physical quantities.</p>
<div>

</div>
<div class="quarto-layout-panel" data-layout-ncol="3">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Capacitive — Apple Touch ID</strong></p>
<p>A silicon array measures electrical capacitance between the array and the live layer of skin under the epidermis. Ridges sit closer than valleys, so the image is 2D electrical contrast, not a photograph.</p>
<p>Depth: none. Template never leaves the <a href="https://support.apple.com/guide/security/touch-id-sec066eb0cd4/web">Secure Enclave</a> and matching happens there.</p>
</div>
</div>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Ultrasonic — Qualcomm 3D Sonic</strong></p>
<p>A piezoelectric transducer emits an ultrasonic pulse and times the echoes. Time of flight gives a genuine depth map of ridge and pore topography, through glass and through moisture.</p>
<p>Depth: yes. A printed 2D spoof has no volume, so its echo profile is wrong.</p>
</div>
</div>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 33.3%;justify-content: flex-start;">
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Optical — in-display</strong></p>
<p>An illuminator under the glass photographs the finger and reads subsurface light scattering — how light diffuses back out of living tissue.</p>
<p>Depth: none. Liveness is a small network on scatter statistics, run locally, because the alternative is shipping fingerprint images off-device.</p>
</div>
</div>
</div>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Capacitive</th>
<th>Ultrasonic</th>
<th>Optical</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Physical quantity</td>
<td>capacitance to subdermal skin</td>
<td>acoustic time of flight</td>
<td>back-scattered light</td>
</tr>
<tr class="even">
<td>Depth channel</td>
<td>no</td>
<td><strong>yes</strong></td>
<td>no</td>
</tr>
<tr class="odd">
<td>Through water / grease</td>
<td>poor</td>
<td>good</td>
<td>moderate</td>
</tr>
<tr class="even">
<td>Defeats a flat printed spoof</td>
<td>weakly</td>
<td>by geometry</td>
<td>by scatter statistics, learned</td>
</tr>
<tr class="odd">
<td>Area captured</td>
<td>small, so partial prints are normal</td>
<td>small to large</td>
<td>medium</td>
</tr>
<tr class="even">
<td>What the template may contain</td>
<td>2D contrast only</td>
<td>ridge and pore relief</td>
<td>2D image plus scatter</td>
</tr>
</tbody>
</table>
<p>And this is where the arc bends towards learning, on an argument the scored ladder cannot make. A phone sensor sees a small, rotated, partly wet fragment. A forensic latent is worse: partial, smudged, overlapping another print, lifted off a curved surface. Minutiae extraction assumes there is a clean skeleton to walk, and on a latent there is not.</p>
<p>NIST <a href="https://pages.nist.gov/elft/">ELFT</a> (Evaluation of Latent Friction Ridge Technology) is the test that matters for that regime: open-set search of a gallery using latent probes, hit rates reported at fixed false-positive rates. It specifies no architecture and measures a black box. Systems that lead those tables combine spatial-domain enhancement — reconstructing ridge flow in the regions where it has been destroyed — with learned embeddings, sometimes embedding the latent and a rolled mate jointly. ELFT does not say which piece did the work, and the results here are not a claim about that regime. They are a claim about what each representation keeps.</p>
</section>
<section id="what-to-keep-and-when" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="what-to-keep-and-when"><span class="header-section-number">11</span> What to keep, and when</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Rung</th>
<th>What it keeps</th>
<th>Handles rotation</th>
<th>Survives a partial print</th>
<th>Template</th>
<th>Needs training data</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0 pixel correlation</td>
<td>the whole image</td>
<td>no</td>
<td>poorly</td>
<td>the image</td>
<td>no</td>
</tr>
<tr class="even">
<td>0+ enhanced correlation</td>
<td>the combed image</td>
<td>no</td>
<td>poorly</td>
<td>the image</td>
<td>no</td>
</tr>
<tr class="odd">
<td>1 FingerCode</td>
<td>energy per cell, per direction</td>
<td><strong>yes, as an array roll</strong></td>
<td>moderately</td>
<td>~4 kB, fixed</td>
<td>no</td>
</tr>
<tr class="even">
<td>2 minutiae</td>
<td>a list of <span class="math inline">\((x,y,\theta)\)</span> landmarks</td>
<td><strong>yes, by construction</strong></td>
<td><strong>well, in principle</strong></td>
<td>tens of points</td>
<td>no</td>
</tr>
<tr class="odd">
<td>3 learned embedding</td>
<td>whatever separates fingers</td>
<td>only what it was shown</td>
<td><strong>well, if trained for it</strong></td>
<td>128 floats</td>
<td>a great deal</td>
</tr>
</tbody>
</table>
<p>The ranking in that table is not the ranking in the scores, and the reasons are specific rather than damning. The minutiae rung is reading a feature this cache resampled away, and it would be a different rung on 500 dpi originals. The learned rung is reading a few hundred prints where it wants millions, and it would be a different rung inside a phone vendor with a data pipeline. Only the two middle rungs are near what their method can do, and they are the two that scored.</p>
<p>Which returns to the question this started with. Keeping the picture works startlingly well — 0.332 rank-1, better than everything else here — right up until the finger turns, and then it is 0.101. Keeping a measurement of the flow is blunter at its best and costs 0.001 of its equal error rate to a thirty-degree turn. Keeping landmarks is the densest choice and the most fragile, because it presumes the capture was good enough to find them, and on a cache resampled to a 6-pixel ridge period it was not. Keeping a learned vector moves the fragility into the training set, where it stops being a property of the algorithm and becomes someone’s data-collection budget — and buys, in exchange, a search that costs one second instead of thirty-five.</p>
<p>None of those is the best representation. Each is the best answer to a different question about the capture, and the sensor is what decides which question you are being asked.</p>
<p>Ridges. Buckle. Patterns. Persist. Combs. Beat. Landmarks. Capture. Decides. Which. Wins.</p>
</section>
<section id="references" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="references"><span class="header-section-number">12</span> References</h2>
<ul>
<li>Kücken, M. &amp; Newell, A. C. (2005). <a href="https://doi.org/10.1016/j.jtbi.2005.01.005">Fingerprint formation</a>. <em>Journal of Theoretical Biology</em> 235(1):71–83.</li>
<li>Hong, L., Wan, Y. &amp; Jain, A. (1998). <a href="https://doi.org/10.1109/34.709565">Fingerprint image enhancement: algorithm and performance evaluation</a>. <em>IEEE Transactions on Pattern Analysis and Machine Intelligence</em> 20(8):777–789.</li>
<li>Jain, A. K., Prabhakar, S., Hong, L. &amp; Pankanti, S. (2000). <a href="https://doi.org/10.1109/83.841531">Filterbank-based fingerprint matching</a>. <em>IEEE Transactions on Image Processing</em> 9(5):846–859.</li>
<li>Cappelli, R., Ferrara, M. &amp; Maltoni, D. (2010). <a href="https://doi.org/10.1109/TPAMI.2010.52">Minutia Cylinder-Code: a new representation and matching technique for fingerprint recognition</a>. <em>IEEE Transactions on Pattern Analysis and Machine Intelligence</em> 32(12):2128–2141.</li>
<li>Schroff, F., Kalenichenko, D. &amp; Philbin, J. (2015). <a href="https://arxiv.org/abs/1503.03832">FaceNet: a unified embedding for face recognition and clustering</a>. <em>CVPR</em>.</li>
<li>Hermans, A., Beyer, L. &amp; Leibe, B. (2017). <a href="https://arxiv.org/abs/1703.07737">In defense of the triplet loss for person re-identification</a>. <em>arXiv:1703.07737</em>.</li>
<li>Deng, J., Guo, J., Xue, N. &amp; Zafeiriou, S. (2019). <a href="https://arxiv.org/abs/1801.07698">ArcFace: additive angular margin loss for deep face recognition</a>. <em>CVPR</em>.</li>
<li>NIST. <a href="https://github.com/usnistgov/minex">MINEX III validation imagery</a>. Public domain (US Government work).</li>
<li>NIST. <a href="https://pages.nist.gov/elft/">Evaluation of Latent Friction Ridge Technology (ELFT)</a>.</li>
<li>NIST. <a href="https://www.nist.gov/services-resources/software/nist-biometric-image-software-nbis">NBIS / MINDTCT minutiae detector</a>.</li>
<li>Apple. <a href="https://support.apple.com/guide/security/touch-id-sec066eb0cd4/web">Touch ID security</a>. <em>Apple Platform Security</em>.</li>
<li>Qualcomm. <a href="https://www.qualcomm.com/products/features/3d-sonic-sensor">3D Sonic Sensor</a>.</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/project-delphi/ml-blog/edit/main/posts/fingerprint-algorithms/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li></ul></div></div></div></footer></body></html>